### ISSUE TITLE
Radcliffe 2: Issue with Footer Credit

### ISSUE THREAD

**Issue by sixhours** [Automattic/themes#1]
Originally reported by @donalirl :

A Personal plan user wanted to remove this text from the footer:

> RADCLIFFE 2 PAR ANDERS NORÉN

from their site: https://julierakot.com

In the customizer, the footer is set to “WordPress.com logo” so `THÈME  : RADCLIFFE 2 PAR ANDERS NORÉN.` should be hidden.

Screenshot: http://cld.wthms.co/ZW8PZh

- User report: 672549-hc
- Ticket follow-up: 715742-zen
- Slack context: p1507023458000059-slack-themes

Also reported by @gugaalves : 

> Another site with the same issue, just have a chat with that site owner: quercypierresechefr.wordpress.com

**Comment by sarahfg** [comment]
I had another user in chat about this issue

## Steps to replicate

The user activates Radcliffe 2 on their site

## Result

The footer credit includes "THÈME  : RADCLIFFE 2 PAR ANDERS NORÉN"
https://cloudup.com/cD36EIOJDY5

## Expected

The footer credit on the demo and in my testing on a free site show only the normal WordPress.com footer credit. It does not include the theme creators name
My Site: https://cloudup.com/clPR6_KXvAu

The demo without the "THÈME  : RADCLIFFE 2 PAR ANDERS NORÉN"
https://radcliffe2demo.wordpress.com/

Both my site and the user's site in the screenshots have the WordPress.com logo option selected

* User report: #3266915-HC
* Follow-up ticket: #1131890-Zen
* User's site: virgule.blog

**Comment by JoshuaGoode** [comment]
Another instance of this came in today.

## Steps to replicate
* Activating Radcliffe 2
* Set footer credit to WordPress.com Logo under Customize > Site Identity

## Results
* The footer credit includes "THÈME : RADCLIFFE 2 PAR ANDERS NORÉN"

## Expected 
* The footer credit would hide "THÈME : RADCLIFFE 2 PAR ANDERS NORÉN" and only show the WordPress.com logo

Ticket: 1465354-zen.
Site: quercypierreseche.fr

**Comment by ashercantrell** [comment]
I just had a very similar issue, but with an EN-GB site. As long as the language is set to EN-GB, the credit says "Proudly Powered by WordPress" and links to https://en-gb.wordpress.org/

Changing the language to just EN fixes the issue.

#1552270-zen

**Comment by lakellie** [comment]
Ran into the same issue today, reported in #8772912-hc on an Atomic site. 
User's site: https://enigmaias.com/
I provided them with CSS to hide it for now.

**Comment by rachelwinspear** [comment]
Same issue on Atomic site, sent CSS to hide **von Anders Norén.**
Ticket: [#1890779-zen](https://woothemes.zendesk.com/agent/tickets/1890779)

**Comment by juliasydnor** [comment]
Another report on EN-GB AT site: 1890993-zen

Sent CSS fix.

**Comment by rachelwinspear** [comment]
Site issue on annefeeney.ie, Personal plan, language was set as EN-GB: #137447-hc

**Comment by sophiegyo** [comment]
Another instance of this in #13239514-hc - Simple site.
Personal plan, language set as EN-GB

Tested and reconfirmed on one of my Simple sites - free site, language EN-GB.
Switched my test site to FR-FR and got the "Thème: Radcliffe 2 par Anders Norén", but the logo changes.

Switched my site language over to EN-US, and the problem disappeared.

**Comment by nielslange** [comment]
@mendezcode: As this issue keeps coming back in various themes when the site language is not set to English. Wouldn't it be an option to simply remove the following part from the footer.php:

```
<span class="sep"> | </span>
<?php
/* translators: 1: Theme name, 2: Theme author. */
printf( esc_html__( 'Theme: %1$s by %2$s.', 'radcliffe-2' ), 'Radcliffe 2', '<a href="http://www.andersnoren.se" rel="designer">Anders Nor&eacute;n</a>' );
?>
```

After all, we do not show `Theme: {NAME} by {AUTHOR}` on any of our WordPress.com themes. I understood that we're parsing that part away. But wouldn't it be more efficient not having that part in the first place?

**Comment by zdenys** [comment]
Should be fixed in D36982-code as mentioned in https://github.com/Automattic/wp-calypso/issues/35968#issuecomment-568037889
