### ISSUE TITLE
Pique: When Site Title and Tagline are selected, they disappear on mobile screens

### ISSUE THREAD

**Issue by gracie** [Automattic/themes#101]
## Steps to replicate

- Navigate to My Site > Themes Customize > Site Identity.
- Add a title & tagline, and check the box for Display Site Title and Tagline.
- Publish
- View the site on either a narrow browser or mobile device.

## Result

The site title and tagline disappear for <=767px wide.

## Expected

The site title and tagline would remain in place and adjust to the screen width.

* User report: #1091258-zd
* User's site: https://happyhippomedia.com/ (also replicated in Customizer on the Pique demo).

**Comment by thomasguillot** [comment]
Hi @gracie this is the expected behaviour for Pique when a site has a logo set.

from style.css:

```
@media (max-width: 767px) {
	.site-logo-link + .site-title,
	.site-description {
		display: none;
	}
}
```

Changing this would affect our current users. The best solution here would be to provide the user with some custom CSS, e.g.:

```
@media (max-width: 767px) {
	.site-logo-link + .site-title,
	.site-description {
		display: block;
	}
}
```
