### ISSUE TITLE
Update our Gutenberg Test Data.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1018]
It'd be good to update our Gutenberg test data with more helpful block examples. https://github.com/Automattic/theme-tools/issues/38

**Comment by danieldudzic** [comment]
## List of blocks:

- [ ] Heading
- [ ] Paragraph
- [ ] Media & Text
- [ ] Cover
- [ ] Quote
- [ ] Pullquote

**Comment by jeffikus** [comment]
- [ ] File Upload
- [ ] Video
