### ISSUE TITLE
Revelar: Horizontal scroll on blog post

### ISSUE THREAD

**Issue by tofumatt** [Automattic/themes#102]
## Steps to replicate

* Enable Revelar theme
* Visit https://codinginairports.com/2018/04/16/wordcamp-london-2018-day-one/ on a desktop (Safari MacOS 10.12, Firefox Developer Edition MacOS 10.12)

I'm not sure what content is causing the scroll.

## Result

Observe horizontal scroll (despite no overflowing/long content)

## Expected

No horizontal scroll.

**Comment by thomasguillot** [comment]
Hey @tofumatt this is a know edge case which is not quite possible to fix (without affecting current users) with left-aligned menus and the last item containing sub-items. You can always add some custom CSS to fix it on your site:

```
@media screen and (min-width: 48.0625em) {
	.main-navigation ul ul {
		min-width: 187px;
	}	
}
```
