### ISSUE TITLE
Boardwalk: Positioning of Site Logo suggestion 

### ISSUE THREAD

**Issue by thebud15** [Automattic/themes#1022]
This is being left as a suggestion from a user. He mentioned wanting to be able to have the site logo be inline with the site title, as opposed to being above it. Thanks!

Reported in #1598274-hc
Follow up ticket at #2132926-zd (A thread primarily being used for another theme issue)

**Comment by danieldudzic** [comment]
Hi @thebud15,

Thank you for reporting this.

A different header layout can be achieved using Custom CSS.

At the moment we are not adding any new features or enhancements to existing themes, so I'll close this issue.
