### ISSUE TITLE
TFT: Build Professional Homepage Template 7

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1029]
![7](https://user-images.githubusercontent.com/177929/60517966-7a493d80-9cd8-11e9-9704-37a6716d2190.png)

_Example currently available at https://dev.thomasguillot.com/portfolio-style-1/_

### Blocks used

1. Spacer
2. Heading (h1)
3. Spacer
4. Masonry [CoBlocks] (full-width, column size L, link to custom URL)
5. Spacer
6. Paragraph (x2)
7. Button

**Comment by iamtakashi** [comment]
@thomasguillot 

For the template that I can see here: https://dev.thomasguillot.com/portfolio-style-1/

* It takes a really long time for Masonry to kick-in. I know this is an issue with the block, but is there anything you can do? 
* You could reduce the number of image on this template. I think people get it with the maximum of 9 images.I like the mix proportion of the images used here to demonstrate Masonry.
* It'd be great to have a call to action at the bottom. For example, a contact form or a CTA that leads them to a contact page.

**Comment by thomasguillot** [comment]
![7](https://user-images.githubusercontent.com/177929/60501423-f2513c80-9cb3-11e9-8b50-d3827aac7d35.png)

_Example currently available at https://dev.thomasguillot.com/portfolio-style-1/_

### Blocks used

1. Spacer
2. Heading (h1)
3. Spacer
4. Masonry [CoBlocks] (full-width, column size XL, link to custom URL)
5. Spacer
6. Paragraph (x2)
7. Button

**Comment by thomasguillot** [comment]
> * It takes a really long time for Masonry to kick-in. I know this is an issue with the block, but is there anything you can do?

My site is on Production mode with Jetpack's site accelerator disabled, so it might explain why it's slow.

> * You could reduce the number of image on this template. I think people get it with the maximum of 9 images.I like the mix proportion of the images used here to demonstrate Masonry.
> * It'd be great to have a call to action at the bottom. For example, a contact form or a CTA that leads them to a contact page.

Done, see updated screenshot: https://github.com/Automattic/themes/issues/1029#issuecomment-507597406

**Comment by iamtakashi** [comment]
We usually take screenshot.png with 1280px viewport. Considering that, the L column size work better. Also can you throw some portrait image as well? I think you had is before.

**Comment by iamtakashi** [comment]
We might use the template in future, let's shelf this for now.
