### ISSUE TITLE
Penscratch 2: Low contrast for block/pullquotes

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1033]
## Steps to replicate

1. Add a blockquote or pullqoute to a post
2. View in browser

## Result

Blockquotes have a text color value of `#999`, which is somewhat lighter than the `#666` used for body text, and causes readability issues for some people against the default white background for this theme.

* User report: https://en.forums.wordpress.com/topic/readability-issues-for-pull-quotes-due-to-low-contrast-text-colour/

User currently using Penscratch, but I told them that theme has been retired and recommended they switch to Penscratch 2 instead.

**Comment by danieldudzic** [comment]
Hi @KokkieH,

Thank you for reporting this.

I agree that #999 doesn't meet the accessibility standard, however, Penscratch 2 doesn't have the Accessibility Ready tag in the showcase, and we don't generally tweak existing themes if the issue isn't an explicit bug.
