### ISSUE TITLE
Orvis: Text on Follow Button turned to white and unreadable when Dark Color scheme is active

### ISSUE THREAD

**Issue by retnonindya** [Automattic/themes#1034]
## Steps to replicate
When using Dark Color scheme, it turns the text color to white. All texts, including the one on Follow Button.

At first, the text 'Enter your email address' is still visible on green color.

![follow](https://cldup.com/epeBK08Vts.png)
*Direct link: https://cldup.com/epeBK08Vts.png*

Then when we need to enter our e-mail...

![email](https://cldup.com/edahmVcj09.png)
*Direct link: https://cldup.com/edahmVcj09.png*

I need to highlight the text so it's readable and shows that the text is indeed there.

This can be seen on Chrome; both on Windows and Mac.

## Expected

I expected the text when we enter our e-mail will stay black or on dark color so it's readable. 

* User report: #12353499-hc
* Follow-up ticket: #2138434-zen

**Comment by danieldudzic** [comment]
Hi @retnonindya,

Thank you for reporting.

This has now been fixed in r54699.
