### ISSUE TITLE
_Dsgnsystm: Work on build tool

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1037]

**Comment by jeffikus** [comment]
As per meeting with @allancole today:

- [ ] /sass/child-theme/* is the reference/master file set to use in each child theme.
- [ ] Modify the imports in those SASS files to reference the /_dsgnsystm/ folder from within each child theme .
- [ ] Test this concept.
- [ ] If concept builds successfully, create a script in the repository root to generate a new child theme based on the given inputs.

**Comment by jeffikus** [comment]
I created a build tool in https://github.com/Automattic/_dsgnsystm/tree/tools/build-system ready for testing. 

Here's how it works:
1 - Switch to the above branch. Keep in mind, it's a totally different file structure to master. This should be in your /theme/ root. After switching you should see 2 folders.
2 - in terminal, navigate into the /_dsgnsystm/ folder
3 - type `npm run child`
4 - you will be presented with this screen:
<img width="618" alt="build-tool" src="https://user-images.githubusercontent.com/937325/60543287-36752900-9d16-11e9-91e1-0a9ac313b13d.png">
5 - Choose a theme name (just stick to regular chars for now, uppercase is permitted though)
6 - Child theme should be created in a new folder and stylesheets should compile and package.json should be present inside the child theme.
7 - You can start dev'ing the child theme styles inside /sass/ with the usual `npm run watch` for the child theme running.

The only changes I made to parent theme files are in the package.json file where I added a new npm command for the build script.

**Comment by allancole** [comment]
This is working like a charm so far Jeff! Got a little feedback for ya:

1) Is the resulting child-theme literally made out of `/themes/_dsgnsystm/sass/child-theme/`? If so, we should make it so that the sass files within that directory don’t get compiled inside the child-theme directory. To fix this, we can just add an `_` to the beginning of those two `.scss` files and delete those two compiled `.css` files.
2) Is it possible to add a boilerplate `functions.php` to `/themes/_dsgnsystm/sass/child-theme/` and have it copied to the child theme build as well? Bonus points if the function names could be auto-prefixed, but only if its easy to do ;-)

**Comment by danieldudzic** [comment]
Tested and indeed it works great :)

![cookiemonster_—_node_◂_npm_TERM_PROGRAM_Apple_Terminal_NVM_CD_FLAGS__SHELL__bin_bash_—_80×24_i_wp-calypso_—_node_◂_npm_TERM_PROGRAM_Apple_Terminal_NVM_CD_FLAGS__—_80×24](https://user-images.githubusercontent.com/905781/60551369-6da20500-9d2b-11e9-9d1a-2b4f4492b02f.jpg)

**Comment by jeffikus** [comment]
@allancole all things are possible 👍 

1 - it is a straight copy that then has the import paths modified for the child theme. Remember that inside the parent it references the parent SASS files. After moving to the child theme, we have to still reference the parent SASS files. We can definitely delete the .css files in the parent and then child though. The only .css files we care about are the ones in the child theme root. 

2 - sure, we can add a functions.php and we prefix functions. do you have an example of what you want in there?

@danieldudzic thanks for testing! Glad it works!

**Comment by allancole** [comment]
> 1 
Awesome!

> 2
Yup, I’ll add the boilerplate `functions.php` file to the child-theme directory in your build-tool branch.

**Comment by jeffikus** [comment]
@allancole @danieldudzic  I made all the above changes. Let me know if it works :)

**Comment by allancole** [comment]
While Jeff is recovering from a bout of sickness, I made a boilerplate child theme that we can use along with the `_dsgnsystm` to start quickly building child themes that work with our new Template-first theme designs. 

It can be downloaded here as a zip file: https://cloudup.com/cHjgrYcZo_P

To create a new child theme follow these steps:

1. Extract the zip file, make a copy of `/boilerplate-child-theme/` and add it to your `/themes/` directory. 
2. Rename the directory to something new like `/themes/my-child-theme`. Make sure it lives in the `/themes/` directory right next to `/themes/_dsgnsystm` (master branch).
2. Using a code editor, go into `/themes/my-child-theme/` and do a find-and-replace on all instances of the `boilerplate-child-theme` and `boilerplate_child_theme_` prefixes. This is similar to what we used to do in `_s` and you can follow the same steps [mentioned in the readme](https://github.com/Automattic/_s/). 
3. Rename the theme by opening `/themes/my-child-theme/sass/style-child-theme.scss` and update the `Theme Name` on line 2. 
4. Next, using terminal  `cd` to `/themes/my-child-theme/` and run `npm install`.
5. Once installed you can use `npm run build` to build the CSS files once, or `npm run watch` to rebuild anytime the Sass files are changed.
6. Activate `My Child Theme`.
7. To make changes to the variables in the system, open `/themes/my-child-theme/sass/_config-child-theme-deep.scss` and you’ll see an array of design related variables. 
8. I usually like to start with colors first so change the primary and/or secondary color and then, run the build and watch how it changes the editor and the frontend. From there you can start making more changes and tweaks as needed. 
9. Any changes to theme colors, sm - xl font-sizes, and Google fonts need to be present in the editor in a few places. This requires us to tweak the _theme setup_ function in `functions.php` a bit. The file has a few variable arrays for the editor and we need to make sure they match the Sass variables wherever possible. 
10. There’s also an `_extra-child-theme.scss` file which you can use to write normal CSS or Sass that doesn’t rely on the system. This is useful for tweaking areas _outside_ of the Gutenberg context like the header, comments or next/previous links. 

That’s pretty much it! Wishing Jeff a speedy recovery, and when he’s back we’ll be able to automate the majority of these steps making this process even easier ;-)
