### ISSUE TITLE
Gazette: Unlink header if it's on the home page only

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#1038]
## Steps to replicate
- Customize the site and specify a theme header
- Under Theme Options, check Display Header on Blog Index Only
- Ensure posts is set to the front page

Then view the site. 

## Result

Notice the header has a link and a fancy rollover effect enticing folks to click it.  If you click on it, it takes you .. right back to the same page.

## Expected

This user finds that annoying, and asked if we can disable the link when the header image only shows up on the home page anyway, as there's really no great reason for the home page to have a big fancy link to itself.

* User report: https://en.forums.wordpress.com/topic/header-image-link-in-gazette-free-theme/

**Comment by danieldudzic** [comment]
Hey,

This is standard WordPress behavior. Perhaps they could disable the hover styling using CSS.

I'm marking this one as a wontfix.
