### ISSUE TITLE
Dyad 2: improve support for WooCommerce Product Images

### ISSUE THREAD

**Issue by liviopv** [Automattic/themes#104]
User reported on 1063981-zd (WooCommerce Ticket) that Product Images are not showing in the left-hand section, like the Dyad 2 handles Post/Page Featured Images.

Unlike Dyad 1, Dyad 2 shows the Product Image just in Product Content, instead of showing on the left, which is a much nicer layout.

Dyad 1 treats Product Images like Post/Page Featured Images.

Screenshots:
* Dyad 1: ![Screenshot](http://cld.wthms.co/eQbuHf+)
Screenshot: http://cld.wthms.co/eQbuHf
* Dyad 2: ![Screenshot](http://cld.wthms.co/5VeTc6+)
Screenshot: http://cld.wthms.co/5VeTc6

## Steps to replicate

1. Activate Dyad 2 on an Atomic Site
2. Create a new product
3. Add a product image
4. Publish the product and it will not show the Product Image on the left.

## Result

The Product Image shows up only on the product content area http://cld.wthms.co/5VeTc6

## Expected

I expected that the Product Image would be shown like the Post Image https://dyad2demo.wordpress.com/2015/07/22/fresh-ingredients-this-season/

* User report: 1063981-zd (Woo queue)
* User's site: https://boromirpancafe.ro and https://boromirpancafe.ro/product/smoothie-relaxare/

**Comment by thomasguillot** [comment]
This is how WooCommerce product pages have been designed.
Posts are posts, Product pages are product pages.

We will not change the design at this stage as it would affect all our current users.

**Comment by liviopv** [comment]
Thanks for clarifying, Thomas! Answered the user on 1115094-zen
