### ISSUE TITLE
Sophisticated Business: Header Overlaps Cover Block on Mobile

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/themes#1040]
## Steps to replicate

1. Create a page with a Cover block as the first block on the page.
2. Assign that page as the static front page.

![Screen Shot on 2019-06-30 at 13:13:22](https://user-images.githubusercontent.com/29981758/60396377-dbd2a600-9b38-11e9-9d6b-39ba1eab44d6.png)

## Result

On mobile, the header covers part of the first paragraph in the Cover block, so it cannot be read. It appears the height of the Cover block is set incorrectly, as changing it makes all the text visible again.

![Screen Shot on 2019-06-30 at 13:15:21](https://user-images.githubusercontent.com/29981758/60396394-25bb8c00-9b39-11e9-94bf-bd2a4555685e.png)

![Screen Shot on 2019-06-30 at 13:16:01](https://user-images.githubusercontent.com/29981758/60396405-41bf2d80-9b39-11e9-9aae-f086a60e0191.png)

## Expected

I expected all of the Cover block text to be visible on mobile.

* User report: 2145090-zen
* reproduced on test site

**Comment by danieldudzic** [comment]
Sophisticated Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Rivington: https://wordpress.com/theme/rivington
