### ISSUE TITLE
Twenty Nineteen: Default pages using incorrect nomenclature

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/themes#1043]
## Steps to replicate

1. Create a site
2. Choose Blogging when prompted "What's your site about"
3. Select 2019 theme or one of its children
4. Go to Customizer or Site > Pages

## Result

The default pages, used to showcase a static homepage and a posts page, use the titles Blog Home and Blog Feed, respectively.

WordPress core is aiming to move away from using Blog, and instead Site should be used.

If anything, could be useful to use simply Home and Blog, as these are more concise and to the point, using *Blog* leads to user confusion as is the case in this instance towards the bottom of the chat - 13764042-hc

![2019_default_pages](https://user-images.githubusercontent.com/16580129/60550410-de2e2f00-9cf5-11e9-8509-9725f08cabe1.png)

## Expected

I expected a more concise default name to be used, such as Home or Blog, rather than Blog Home and Blog Feed.

* User report: 13764042-hc
* Slack discussion p1562099434181600-slack-themes

**Comment by lancewillett** [comment]
Moved to https://github.com/Automattic/wp-calypso/issues/34422
