### ISSUE TITLE
Sophisticated Business: Text on block appeared white with white background

### ISSUE THREAD

**Issue by retnonindya** [Automattic/themes#1047]
## Steps to replicate

- Activate 'Sophisticated Business' theme and edit a page/post with Block Editor active.
- Choose a block which gives feature on entering text -- in this case, Shortcode Block.

![editor](https://cldup.com/KsbRIdV5pZ.gif)
*Direct link: https://cldup.com/KsbRIdV5pZ.gif*

## Result

The text is not visible; unless the block is clicked.

## Expected

The text is visible every time so we know what's in the block.

* Report: Personal P2/blog.

**Comment by danieldudzic** [comment]
Sophisticated Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Rivington: https://wordpress.com/theme/rivington
