### ISSUE TITLE
Libretto: Missing Translation String

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#105]
I'm not able to get this to show on my test site, but on line 56 of template-tags.php is the pagination code, and there is a span with "of" in it that does not get translated.
`<div class="page-number"><?php echo intval( $paged ); ?> <span>of</span> <?php echo intval( $wp_query->max_num_pages ); ?></div>`

Since I was not able to reproduce the user's setup and see this, I can't provide any screenshots.

* User report: [https://wordpress.org/support/topic/missing-translation-code-_x-in-inc-template-tags-php/#post-10192239](url)
* User's site: Not provided

**Comment by alaczek** [comment]
Yep, I can see the issue - to reproduce Infinite Scroll needs to be disabled so that the default theme paging behaviour is used.

**Comment by alaczek** [comment]
I _think_ the glotpress project will be regenerated automatically, and once that's done we'll need to regenerate the .zip and resubmit to .org. Leaving open until all that's done.

**Comment by laurelfulford** [comment]
This in the theme's .pot file now on WP.com (line 223) so I've resubmitted the theme to WP.org: https://themes.trac.wordpress.org/ticket/54105

I've also followed up in the ticket, but left it open as I don't have the power to resolve. @thesacredpath can you please close if everything's resolved? Thanks!
