### ISSUE TITLE
Shoreditch: Drop-down menu items appearing behind content on homepage

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/themes#1053]
## Steps to replicate

This is the CSS in use on the site currently (though please note that even without this added, the issue is present)
```
.wp-block-jetpack-slideshow.alignfull .wp-block-jetpack-slideshow_image {
	width: 100vw;
	max-width: unset;
	object-fit: cover;
}

/* Slideshow Block: hide the navigation controls | XXXXX-hc */
.wp-block-jetpack-slideshow .wp-block-jetpack-slideshow_button-prev,
.wp-block-jetpack-slideshow .wp-block-jetpack-slideshow_button-next,
.wp-block-jetpack-slideshow .wp-block-jetpack-slideshow_pagination,
.wp-block-jetpack-slideshow[data-autoplay=true] .wp-block-jetpack-slideshow_button-pause {
	display: none !important;
}

/* Hide page title on homepage | 13839601-hc */
.home .entry-title {
	display: none;
}

/* Reduce padding above slider on homepage | 13839601-hc */
.home .hentry {
	padding-top: 0;
}
```

The user has a slideshow block (Gutenberg) added as the first thing on the page.

## Result

The drop-down menu items are appearing behind the slideshow like this: https://cloudup.com/cf386thQJmg

## Expected

They should appear on top of the slideshow like this: https://cloudup.com/cNTjcqHBB_D

We've asked the user to add this CSS to their site for a temporary work-around:
```
/* --- Fix header z-index / 13839601-HC (MI) --- */
.site-header {
     position:relative;
     z-index:2;
}
```

* User report: #13839601-hc
* Follow-up ticket: #2160323-zd
* Discussed in Slack here: https://a8c.slack.com/archives/C03TY6J1A/p1562440044444500

**Comment by Aurorum** [comment]
PR in #1054 for this issue. :)

**Comment by ezebecke** [comment]
Another user reported this issue: #2383413-zd. I wonder if we can merge your pull request @Aurorum :)
