### ISSUE TITLE
AltoFocus: Widgets not appearing in Footer widget area

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/themes#1055]
## Steps to replicate

If you visit these sites below, you'll see that there are no footer widgets however there should be at least four active widgets as seen in this screenshot: [https://cld.wthms.co/xL2g5M](https://cld.wthms.co/xL2g5M)

Sites: 
- [https://ronmarcusmusic.wordpress.com/](https://ronmarcusmusic.wordpress.com/)
- [https://altofocusdemo.wordpress.com/](https://altofocusdemo.wordpress.com/) (Theme Demo site)

## Result

Blank footer widget area:

[https://cld.wthms.co/ljooXo](https://cld.wthms.co/ljooXo)

## Expected

We should expect to see at least four active widgets in the footer widget area (at the above sites)

* Ticket: 2162688-zen

**Comment by danieldudzic** [comment]
Hi @adelineyaw,

According to the [docs](https://wordpress.com/theme/altofocus):

> AltoFocus comes with one widget area below **single posts** and **archives** 

I have tested this, and the footer widget area seems to be displaying fine on archive and single post pages on my test installation.
