### ISSUE TITLE
P2: The site title is not a link anymore.

### ISSUE THREAD

**Issue by silvio-meter** [Automattic/themes#1060]
**Steps to replicate**

- Open the site that's using the P2 theme.

- Click on the site title.

- Open the Customizer and check if there are any widget issues.

- Check the Custom CSS.

- Change a theme to another one, and change it back to P2 theme.

**Result**

The site title doesn't act as a link anymore. The issue started on 2019-07-10 when the theme was updated. The title acts normally on the mobile view but starts to malfunction at width: 876px. 

 **Expected**

The site title should act as a link.

User report: [2172118-hc]

**Comment by KristinaKay** [comment]
This is actually as expected. The title is no longer a link because the user has the Page set as the static home page in Home Page Settings. Removing that setting in Home Page Settings will correct this.

**Comment by arcangelini** [comment]
I am not sure that is the correct analysis of the issue. I have tested this pretty extensively and have found that it should be working in both Static Homepages and Latest Posts. Examining the code for the site it does show the site-title as a link:

![Site-title HTML](https://cld.wthms.co/pJPCW7+)

To further that point the site-title link works in all other orientations (i.e. mobile and tablet) in its current state.

On this test site ⇢ llamaeatsagiraffe.wordpress.com

The theme is P2 and the homepage is static with widgets in the sidebar (to move the site-title over) and the site title is a link.

User report: [2172118-zd] & [9863806-hc]

**Comment by KristinaKay** [comment]
Oh, you're right. When I tested the site and create my own, there was not site title showing so I thought they referred to the title of the static page on the left. Thanks for reopening and working through it!

**Comment by cathymcbride** [comment]
retired theme. Closing...
