### ISSUE TITLE
Dara: Featured Image Sizes Create Issue with Homepage Content

### ISSUE THREAD

**Issue by sarahfg** [Automattic/themes#1071]
## Steps to replicate

1. Have a static homepage with some simple text content
2. Add more than 2 featured posts with featured images to the slider
3. Set one post to have a featured image that is very long and not tall. For another post have their featured image be more square 

## Result

The text on the homepage will be "clickable" and lead the viewer to the content on the post with the square featured image

![](https://cld.wthms.co/AbOPf5+)

(Image link: https://cld.wthms.co/AbOPf5 )

## Expected
Homepage content should remain plain and not turn into a hyperlink to a featured post.

* User report: #12978411-hc
* Follow-up ticket: #2182160-zen

Replicated on my test site at https://sarahfoxgreenlee271489076.wordpress.com/

@thesacredpath noted

>there is the following CSS in a media query which is setting the overflow to visible on screens/windows 850px and wider.

```
@media screen and (min-width: 850px) {
.hero-content {
overflow: visible;
}
}

```

>When I switch that to overflow: hidden; the issue goes away.

**Comment by danieldudzic** [comment]
Dara has been retired so I'm closing this as a wontfix.

We have launched a replacement called Shawburn: https://wordpress.com/theme/shawburn
