### ISSUE TITLE
_Dsgnsystm: Color settings in the customizer doesn't work

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/themes#1074]
![Screenshot 2019-07-17 at 15 43 24](https://user-images.githubusercontent.com/177929/61385030-a43e5a80-a8a9-11e9-86f3-8a160d689778.png)

The color picker doesn't affect the site.
Same with the "Apply a filter to featured images using the primary color" checkbox

**Comment by allancole** [comment]
I’m just going to remove these for now. These settings will likely reappear as global styles in /core. 

See here: https://github.com/Automattic/pages/pull/323
