### ISSUE TITLE
_Dsgnsystm: Should we hide the entry header?

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/themes#1075]
It can be awkward when building a block template/layout to have the entry header at the top. Maybe we could have a checkbox somewhere (customizer) to manipulate this behaviour?

__Before:__

![1 before](https://user-images.githubusercontent.com/177929/61385849-15cad880-a8ab-11e9-8838-154bcd9d8c88.jpg)

__After:__

![2 after](https://user-images.githubusercontent.com/177929/61385868-1fecd700-a8ab-11e9-8bd5-0083ad57a128.jpg)

**Comment by allancole** [comment]
There’s actually already a setting for this in the Customizer at the bottom of the Home Page settings panel here: 

![image](https://user-images.githubusercontent.com/709581/61417237-84686000-a8c4-11e9-8713-630a7c736883.png)

It only applies to the Home Page but I think thats where it’d be most useful. I think we’d prefer to stay away from adding more options to the customizer. Ideally, this should (and likely will) become an option for the Gutenberg editor, so I lean toward waiting for that for now.

**Comment by thomasguillot** [comment]
Hmm I don't see the checkbox on my local install. What am I missing?

<img width="537" alt="Screenshot 2019-07-18 at 08 48 52" src="https://user-images.githubusercontent.com/177929/61439161-e367bc80-a938-11e9-93c2-0515bd565aa2.png">

**Comment by allancole** [comment]
Yeah, this feature only appears on wpcom (including Atomic sites as well).

**Comment by thomasguillot** [comment]
Oh ok. That's fine then 👌
