### ISSUE TITLE
_Dsgnsystm: Search form padding seems off

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#1083]
## Steps to replicate

The issue occurs for both the Search widget and the 404 page.

**_dsgnsystm**

![Search__Dsgnsystm](https://user-images.githubusercontent.com/905781/61417758-95cb5f80-a8f8-11e9-98f2-87cb961e7ff3.jpg)

**Redhill** 

![Cwh1SIosmw-3000x3000](https://user-images.githubusercontent.com/905781/61417695-556be180-a8f8-11e9-857f-08bf0f65426e.jpeg)

All form fields should have some padding.

**Comment by allancole** [comment]
Closing this since a fix was merged in #1088
