### ISSUE TITLE
_Dsgnsystm: Pullquote text alignment inconsistencies

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#1087]
**Left and Right aligned Pullquotes in the editor:**

![Editor](https://user-images.githubusercontent.com/905781/61454238-a31c3480-a960-11e9-95ec-985ae00939b1.jpg)

----------

**Left and Right aligned Pullquotes on the front-end:**
![Front-end](https://user-images.githubusercontent.com/905781/61454308-d52d9680-a960-11e9-9dce-50c0375d1a86.jpg)

-----------
In the editor the text is aligned to the center, and on the front-end the Left aligned text is aligned to the left, and the Right aligned text is aligned to the center.

**Comment by allancole** [comment]
Ahhh, good catch! I’ll sort that out now…

**Comment by allancole** [comment]
Fixed in #1092 
Closing…
