### ISSUE TITLE
Calm Business: Recent Blog Posts block colors do not follow Customizer Color setting

### ISSUE THREAD

**Issue by jessestu** [Automattic/themes#1091]
## Steps to replicate

1. Activate Calm Business.
2. Set a custom color in Customize → Colors.
3. Add the Recent Blog Posts block to a page.
4. View page.

## Result

Colors remain a loud brown (that is quite rough when it doesn't match). Screenshot of issue, Customizer setting, and relevant CSS:

![Screen Shot on 2019-07-18 at 12:17:37](https://user-images.githubusercontent.com/32908730/61477957-21bfa480-a956-11e9-96f8-17279bacdb8d.png)

## Expected

I expect the View all posts button to display in the Custom color.

---

Discovered during a 1:1 Quick Start call. User doesn't need a response.

**Comment by danieldudzic** [comment]
Calm Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Mayland: https://wordpress.com/theme/mayland
