### ISSUE TITLE
 Illustratr: Content width for large images on portfolio pages overridden with Photon active 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#11]
This issue was originally reported by @SiobhyB in 3965-wpcom-themes:

The content width for large images on portfolio pages is overridden with Photon is active.

A similar issue was previously reported in 2720-wpcom-themes.

## Steps to replicate

1. Install Jetpack and activate the Photon module.
2. Add a portfolio project.
3. In the project post, insert a large image (over 1100px) and select the large size from the size options.
4. View the single portfolio project post on the front end - observe how the image is only 840px wide.
5. Deactivate Photon.
6. View the single portfolio project post on the front end - observe how the image is now 1100px wide, as it should be. 

I was able to replicate on my test site. The code for the image was as follows with Photon disabled: 

`<img class="alignnone wp-image-1023 size-full image-big" src="https://bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper.jpg" alt="I Am Worth Loving Wallpaper" width="1920" height="1200" srcset="https://bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper.jpg 1920w, https://bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper-300x188.jpg 300w, https://bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper-768x480.jpg 768w, https://bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper-1024x640.jpg 1024w" sizes="(max-width: 1920px) 100vw, 1920px">`

 Here's the code when Photon was enabled:

`<img class="alignnone wp-image-1023 size-full" src="https://i2.wp.com/bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper.jpg?resize=1100%2C688&amp;ssl=1" alt="I Am Worth Loving Wallpaper" srcset="https://i2.wp.com/bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper.jpg?w=1920&amp;ssl=1 1920w, https://i2.wp.com/bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper.jpg?resize=300%2C188&amp;ssl=1 300w, https://i2.wp.com/bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper.jpg?resize=768%2C480&amp;ssl=1 768w, https://i2.wp.com/bambi.mystagingwebsite.com/wp-content/uploads/2013/03/soworthloving-wallpaper.jpg?resize=1024%2C640&amp;ssl=1 1024w" sizes="(max-width: 1920px) 100vw, 1920px" width="840" height="525">`

The image-big class is removed when Photon is enabled, which means that the following CSS doesn't work correctly:

```
@media screen and (min-width: 1220px) {
    .portfolio-entry .size-full.image-big {
        margin-left: -130px;
        max-width: 1100px;
    }
}
```

The above CSS class is added via illustratr.js. 

* User report: https://wordpress.org/support/topic/portfolio-image-size-problem-with-photon-plugin?replies=1
* Related Slack convo: p1466097591002175-slack-jpop-support

**Comment by sixhours** [comment]
It sounds like this is a Photon issue, not specific to Illustratr, so I'm going to suggest we close this ticket and move the user follow-up info to Automattic/jetpack#7291
