### ISSUE TITLE
Varia: 100% large image overflows the editor area

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#1101]
![image_large](https://user-images.githubusercontent.com/905781/61529530-d70b5e80-aa21-11e9-95e3-c0dc61e4bd73.jpg)

--------

![F9qc7bGv5u](https://user-images.githubusercontent.com/905781/61529666-3b2e2280-aa22-11e9-9c26-ceaf74c80402.gif)

**Comment by jeffikus** [comment]
I think this is actually a bug in the block itself. I've tested this with the same result in:
Twenty Nineteen
Chaplin
CoBlocks
Storefront
Calm Business

All with the same result. Not sure on a solution yet.

**Comment by iamtakashi** [comment]
@kjellr kindly let us know this is a core bug. https://github.com/WordPress/gutenberg/issues/12168

@jeffikus Thanks for looking into it!

Closing this for now.
