### ISSUE TITLE
Redhill: No Preview on Theme Showcase

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#1112]
## Steps to replicate

1. Access the theme's showcase on WordPress.com.
2. Find the Redhill theme.

## Result

It doesn't show its preview, as follows:

![RedhillPreview](https://user-images.githubusercontent.com/16104522/61583882-de5f6480-ab14-11e9-887d-50865891b67b.png)

## Expected

To show a preview like other themes.

It seems that the image is missing:

https://i0.wp.com/jhnstndec13d.wpcomstaging.com/wp-content/themes/pub/redhill/screenshot.png

**Comment by carinapilar** [comment]
I just noticed that once you click on a theme, and then click on Back to the theme's showcase, the preview shows. But then the image's address is different:

https://i2.wp.com/s2.wp.com/wp-content/themes/pub/redhill/screenshot.png

Which is an URL that works.

**Comment by iamtakashi** [comment]
I believe this is not the theme specific issue as the theme has the screenshot in it. 

@carinapilar would you mind report this in https://github.com/Automattic/wp-calypso as a theme showcase issue? Thank you!

**Comment by davidakennedy** [comment]
I'm closing this since it's now reported in the best spot.
