### ISSUE TITLE
Business variations: Long navigation label on submenu gets cut off

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/themes#1114]
## Steps to replicate

Applies to the themes Professional Business, Sophisticated Business, Elegant Business, Friendly Business, Calm Business, Modern Business.

1. Create a submenu item with a long navigation label

## Result

The submenu gets cut off, as shown in this screenshot: https://cld.wthms.co/s89jQK

## Expected

I would expect the text to wrap so that the full submenu navigation label is visible, similar to other themes.

* User report: 14106093-hc

**Comment by danieldudzic** [comment]
All Business themes have been retired now so I'm closing this as a wontfix.
