### ISSUE TITLE
Varia: Vertically stretched image 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1115]
Originally reported [here](https://github.com/Automattic/themes/pull/1085) by @MichaelArestad 

Suggested fix is add `height: auto` to `<img>`.

The latest Gutenberg plugin takes care of it because it already has the auto height rule, but without the plugin, a large 100% image will stretch. The core will eventually catches up, but in the meantime, it's probably best to add the fix.

**Comment by davidakennedy** [comment]
Closing as fixed.
