### ISSUE TITLE
Varia: Footer menu is registered but not outputted anywhere

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#1125]
Changed the name of the footer menu location to `menu-2` to follow https://developer.wordpress.com/themes/#tux and also added the missing output for the menu in footer.php in https://github.com/Automattic/themes/commit/0eec4313c177938b8495e92747a7971bbbb379c2

The last thing missing is styling.

**Comment by iamtakashi** [comment]
Fixed with #1126
