### ISSUE TITLE
Baskerville 2: Recent Posts number doesn't work

### ISSUE THREAD

**Issue by davoraltman** [Automattic/themes#113]
## Steps to replicate

Limiting the number of posts that show up on the front page doesn't work.

For the site (ID: 144902591), I did the following:

- Under Writing settings, I set to display 4 blog posts per page
- I did the same in the WP admin area
- I turned on `Load more posts in page with a button` setting

## Result

The front page still displays all 5 posts instead of 4.

## Expected

I should see only 4 posts on the homepage.

* User report: 3230213-hc
* Follow-up ticket: 1128623-zen
* User's site: https://thenetworkopsdelivery.com/

**Comment by laurelfulford** [comment]
Hi @davoraltman - thanks for reporting this issue!

It looks like this is working as expected. The site has one sticky post; the sticky posts are not counted in the posts-per-page total, so for example if you have a site with one sticky post and have the posts-per-page set to 10, it will show 11. 

This is WordPress Core behaviour, and not theme-specific.

I'm going to close this report and I'll add a comment to the follow-up ticket.

**Comment by davoraltman** [comment]
Ah, gotcha. Sorry I missed this. Thanks for the clarification, @laurelfulford !
