### ISSUE TITLE
Modern Business: Alignment issue on element inside group block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1137]
See https://gutenbergtestdata.wordpress.com/2019/07/22/group-block/

It's rough, we should fix them :)

**Comment by iamtakashi** [comment]
This is costing a lot of time of us, and we'll retire Modern Business soon as soon as it's taken down from the signup, and I don't think it's worth for trying at this moment.

**Comment by danieldudzic** [comment]
Modern Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Maywood: https://wordpress.com/theme/maywood
