### ISSUE TITLE
Redhill: Typo in style.css License Information

### ISSUE THREAD

**Issue by mrwweb** [Automattic/themes#1142]
It looks like someone copied the Varia stylesheet and missed changing this line in the new Redhill theme:

["Varia is based on Underscores https://underscores.me/, (C) 2012-2019 Automattic, Inc."](https://github.com/Automattic/themes/blob/master/redhill/style.css#L19)

**Comment by allancole** [comment]
Ahhh, good catch! We’ll get that fixed shortly. 

Thanks for reporting :-)

**Comment by nielslange** [comment]
This issue affects the following child themes of Varia:

- [ ] [Alves](https://github.com/Automattic/themes/blob/master/alves/sass/style-child-theme.scss)
- [ ] [Balasana](https://github.com/Automattic/themes/blob/master/balasana/sass/style-child-theme.scss)
- [ ] [Barnsbury](https://github.com/Automattic/themes/blob/master/barnsbury/sass/style-child-theme.scss)
- [ ] [Brompton](https://github.com/Automattic/themes/blob/master/brompton/sass/style-child-theme.scss)
- [ ] [Coutoire](https://github.com/Automattic/themes/blob/master/coutoire/sass/style-child-theme.scss)
- [ ] [Dalston](https://github.com/Automattic/themes/blob/master/dalston/sass/style-child-theme.scss)
- [ ] [Exford](https://github.com/Automattic/themes/blob/master/exford/sass/style-child-theme.scss)
- [ ] [Hever](https://github.com/Automattic/themes/blob/master/hever/sass/style-child-theme.scss)
- [ ] [Leven](https://github.com/Automattic/themes/blob/master/leven/sass/style-child-theme.scss)
- [ ] [Mayland](https://github.com/Automattic/themes/blob/master/mayland/sass/style-child-theme.scss)
- [ ] [Maywood](https://github.com/Automattic/themes/blob/master/maywood/sass/style-child-theme.scss)
- [ ] [Morden](https://github.com/Automattic/themes/blob/master/morden/sass/style-child-theme.scss)
- [ ] [Redhill](https://github.com/Automattic/themes/blob/master/redhill/sass/style-child-theme.scss)
- [ ] [Rivington](https://github.com/Automattic/themes/blob/master/rivington/sass/style-child-theme.scss)
- [ ] [Rockfield](https://github.com/Automattic/themes/blob/master/rockfield/sass/style-child-theme.scss)
- [ ] [Shawburn](https://github.com/Automattic/themes/blob/master/shawburn/sass/style-child-theme.scss)
- [ ] [Stow](https://github.com/Automattic/themes/blob/master/stow/sass/style-child-theme.scss)
- [ ] [Stratford](https://github.com/Automattic/themes/blob/master/stratford/sass/style-child-theme.scss)
