### ISSUE TITLE
Leven Demo Links

### ISSUE THREAD

**Issue by arcangelini** [Automattic/themes#1151]
## Issue
All buttons in the Leven Demo homepage are going to a broken URL. Example:
* https://dsgnsystm.development/about/
* https://dsgnsystm.development/sample-page/

## Expected
Those buttons should link to the internal pages. Example:
* https://levendemo.wordpress.com/about/
* https://levendemo.wordpress.com/sample-page/

**Comment by allancole** [comment]
I’ve updated the demo so that all links point to `#` like the Redhill demo.

**Comment by allancole** [comment]
Thanks for reporting! Closing this issue…
