### ISSUE TITLE
Calm Business: Nested menus on mobile have unusual behaviour when clicking on menu text link

### ISSUE THREAD

**Issue by anant1811** [Automattic/themes#1156]
## Steps to replicate
- Add one menu item as the parent menu, along with multiple nested/sub-menus (in Primary menu location)
- Open the site on a phone, click the parent menu's text link (not the dropdown). 

## Result
- The menu opens revealing the sub-menus, then the page linked to parent menu opens and the sub-menu disappears (because the page linked to parent menu has now opened). Since the sub-menu opens for a moment and then disappears, it confuses the uses. 

Pls see this screencast of the issue: https://cld.wthms.co/bHvQ2K

## Expected

- On mobile, clicking on the menu links should either only open the page linked to the menu link, or the sidebar should open in case they contain sub-menus. 

* User report: 14193376-hc

**Comment by danieldudzic** [comment]
Calm Business has been retired so I'm closing this as a wontfix.
