### ISSUE TITLE
Goran: List alignment Issues

### ISSUE THREAD

**Issue by vajrasar** [Automattic/themes#1157]
## Steps to replicate
- While using Block Editor create a List Block
- Enter List items, where each list item is in multiple lines
- Publish the page

## Result
- The list items spanning in multiple lines are unaligned. The second line of the list item moves below the list style (square, circle etc.)

![](https://cloudup.com/cFbj_zeEi2Y+)
_(Image Link: https://cloudup.com/cFbj_zeEi2Y)_

## Expected
- The list items should be properly aligned where every line (in case of multiple lines on the single list item) should start right after the list style.

![](https://cloudup.com/cyPhNefY6Nt+)
_(Image Link: https://cloudup.com/cyPhNefY6Nt)_

* User report: #14034921-hc
* Follow-up ticket: #2213868-zd

**Comment by jeffikus** [comment]
Goran has been retired.
