### ISSUE TITLE
Unneeded comma in footer in Modern Business Theme

### ISSUE THREAD

**Issue by joweber123** [Automattic/themes#1162]
## Steps to replicate
Hide _Footer Credit_ in _Site Identity_ on the Business plan.

![screenshot](https://cld.wthms.co/cuPklL+)
[*Direct link to screenshot if the above does not load correctly*](https://cld.wthms.co/cuPklL)

## Result
The comma that was meant to separate the _Footer Credit_ and the _Site Title_ is no longer needed.

## Expected
If the Footer Credit was hidden, this comma would automatically disappear. 

* User report: #14278015-hc

**Comment by danieldudzic** [comment]
Modern Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Maywood: https://wordpress.com/theme/maywood
