### ISSUE TITLE
Dara: Hidden slideshow captions

### ISSUE THREAD

**Issue by catkiinson** [Automattic/themes#1166]
## Steps to replicate

- Add images to the media library
- Add captions to images
- Insert a slideshow into a post or page
- See captions appear in editor
- Preview or Publish - the captions disappear. 

The offending CSS: https://cld.wthms.co/UT5a16
Coming from within Dara's CSS itself: https://cld.wthms.co/FN6oMj

## Result

-  Slideshow image captions are hidden. 

## Expected

- Slideshow image captions to be visible. 

* User report: #13878357-hc

**Comment by danieldudzic** [comment]
Dara has been retired so I'm closing this as a wontfix.

We have launched a replacement called Shawburn: https://wordpress.com/theme/shawburn
