### ISSUE TITLE
Varia: Should wide width element be wider than normal width in mobile? 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1192]
I've noticed this while I'm looking at Leven. On mobile, a wide width element is very close to the edge of the screen. I can understand the logic, and technically this is correct, but should it be? My opinion is that this technicality creates unnecessary visual noise because there is not much difference between wide and normal in small screen, and a wide element should be the same width until the viewport that a wide element can have enough difference.

<img width="349" alt="Screen Shot 2019-08-05 at 14 25 47" src="https://user-images.githubusercontent.com/908665/62469143-92a4f000-b78f-11e9-8c6b-08213bb06a0e.png">

cc @allancole

**Comment by allancole** [comment]
Yeah, I’ve noticed this a bit with Coutoire and agree its its too small of a space to really matter. 

Just for clarity, are you saying you think `.alignwide` should become `.alignfull` on mobile? Or should it go to normal width on mobile?

**Comment by iamtakashi** [comment]
> Just for clarity, are you saying you think .alignwide should become .alignfull on mobile? Or should it go to normal width on mobile?

Ah sorry it wasn't clear. My gut feeling is it should be the same with normal width. I think there are more cases that wide width being used with text content like the example above. If it was full width the text will bump to the edge of the screen.

**Comment by allancole** [comment]
Great, yeah I think Normal width would look best too.

**Comment by allancole** [comment]
’ll work out a PR shortly.

**Comment by iamtakashi** [comment]
@allancole This is a different issue in my mind though.

As we discussed in #1217, we should increase the threshold for the wide breakpoint so that wide width become different from normal on desktop.
