### ISSUE TITLE
Altofocus: Masonry load older post display on top of each other

### ISSUE THREAD

**Issue by rezzap** [Automattic/themes#122]
Looks like this has been discussed (https://github.com/Automattic/themes/issues/47) already, but the issue is closed and it doesn't seem to have fixed so I'm opening a new issue.

## Steps to replicate

When clicking the load older post button on the AltoFocus theme and scrolling down while the posts are loading, the new posts will display one above each other.

<img width="1758" alt="image 2018-05-07 at 11 21 57 am" src="https://user-images.githubusercontent.com/10325627/39697677-af482a22-51e9-11e8-92e2-76af39ca5c26.png">

## Steps to replicate

1. Load the demo site in Chrome, Safari or Firefox: https://altofocusdemo.wordpress.com/
2. Click the 'Older Posts' button on the home page and start scrolling while the posts are loading.

![screen recording 2018-05-07 at 11 33 am](https://user-images.githubusercontent.com/10325627/39698306-3f7b112a-51ec-11e8-8897-cfec2c5304ce.gif)

## Result

If you let the posts load before you start scrolling, the display is fine. But if you scroll they show one on top of the other. 

## Expected

I would expect the posts to load in the correct order as soon as I start scrolling.

* User report: #1142329-zd
* User's site: https://samsoul.blog/ (mature content)

**Comment by alaczek** [comment]
cc @allancole to take a look

**Comment by thebud15** [comment]
@allancole just thought I'd check on the progress of this, as it came up again in 1142329-zen. Once we figure this one out, we can follow up with the user there with an update. Thanks!

**Comment by alaczek** [comment]
I wonder if this issue popping up again has something to do with @laurelfulford updates https://github.com/Automattic/themes/pull/118

I remember testing it when Allan created a patch, and it was working properly then.

**Comment by alaczek** [comment]
I just removed latest changes on my sandbox, and that seems to fix the issue. @laurelfulford not sure what we should do here? I looked at the original ads issue, and it wasn't affecting Altofocus, or at least I haven't seen any reports. Do you think it would be fine to revert? Or do you have a better idea for a fix?

**Comment by laurelfulford** [comment]
> I looked at the original ads issue, and it wasn't affecting Altofocus, or at least I haven't seen any reports. 

There was just one report for Altofocus I saw, buried in one of the Ads threads (p4x5kY-Go-p2).

**Comment by laurelfulford** [comment]
What's also weird is that the only thing I changed was the event used for when posts faded in on page load -- nothing to do with masonry timing, or when things happened when the Older Posts are loaded. I'm confused how it cause this kind of regression! 🤔

**Comment by laurelfulford** [comment]
I had a heck of a time recreating this issue until I used a full-sized browser window on my 13" laptop screen (thanks for helping me recreate it, @alaczek!).

I was able to recreate the issue both before and after the update in #118, so I don't think that's the issue, unfortunately. 

I also chatted with @allancole briefly about it and he said, from his experience investigating #47, it seems to be related to Photon somehow. It seems like a tricky one to resolve completely!

**Comment by allancole** [comment]
There’s some additional background on the Photon stuff here: pNEWy-9cT-p2

**Comment by mahangu** [comment]
@allancole @laurelfulford since this is not something that can be resolved completely atm, I've let the user know (in 1142329-zen) that their next option here is to switch themes for now.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
