### ISSUE TITLE
Dyad 2: Extra Text in Footer Credit Can't Be Hidden in non-English

### ISSUE THREAD

**Issue by jacoswan** [Automattic/themes#1222]
The `Powered by WordPress` Footer Credit shows an extra string `Theme: Dyad 2 by WordPress.com` in some non-English languages, and that extra string ignores the Customizer setting to hide the Footer Credit. 

## Steps to replicate

1. Business plan site, English language
2. Activate Dyad 2 from the theme directory
3. Go to Design » Customize »  Site Identity » Footer Credit » Select HIDE
4. Footer credit is now hidden. Publish to save. 
5. Exit Customizer, go to Settings » Language » Select DANISH, Save Settings
6. View Site. Part of the Footer Credit `Tema: Dyad 2 af WordPress.com` is (still) visible.
7. Same in Catalan, Icelandic, Lithuanian, Dutch, Finnish, Greek, Italian, Neapolitan, and possibly quite a few more languages, but not all.

## Result

In some non-English languages an extra string is visible, and it ignores the HIDE setting set in customizer.

## Expected

- All of the Footer Credit should be hidden
- "Theme:Dyad 2 by WordPress.com" part only shows in non-English languages, so should probably not show at all. 

* User report: #14455718-hc
* Follow-up ticket: #2259118-zd (includes CSS solution)

**Comment by zdenys** [comment]
Should be fixed in D36982-code as mentioned in https://github.com/Automattic/wp-calypso/issues/35968#issuecomment-568037889
