### ISSUE TITLE
Varia: Element on cover block has no margins.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1224]
This might be intentional at that time, but since the spacing utility classes are in with #1168, can we add vertical margins to the element on cover block?

<img width="881" alt="Screen Shot 2019-08-09 at 00 18 44" src="https://user-images.githubusercontent.com/908665/62743762-96f53580-ba3b-11e9-83c3-1257a216fef1.png">

**Comment by allancole** [comment]
Yup, I think both Cover and M&T block have compressed margins that need to be removed. I’ll strike up a PR tomorrow.

**Comment by allancole** [comment]
That is unless you’ve already started working on it :-)

**Comment by iamtakashi** [comment]
I've done the cover in #1225, I'll make a PR for M&T shortly.
