### ISSUE TITLE
Opti: Lazy Loading interfering with Masonry in Atomic sites

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/themes#123]
## Steps to replicate

1.- On an Atomic site (I used atraultest.blog).
2.- Create several posts with featured images and under one category
3.- Select lazy loading in JetPack settings (https://atraultest.blog/wp-admin/admin.php?page=jetpack#/writing)
4.- Open the category page, in this case: https://atraultest.blog/category/tendencias-itcomext/

Result: the masonry layout is not properly resolved 
![trends site title 2018-05-08 12-18-30](https://user-images.githubusercontent.com/6404071/39752289-3dca16f8-52bb-11e8-964c-768c4a8ab53b.png)

- This was reported by an user, site meinwarschau.com on category pages like https://meinwarschau.com/category/wirtschaft-und-politik/. More info here https://wp.me/p9F6qB-up

![leben in warschau archive - warschau und polen 2018-05-08 11-01-31](https://user-images.githubusercontent.com/6404071/39752131-ce7f084e-52ba-11e8-8eba-c806b36079de.png)
![leben in warschau archive - warschau und polen 2018-05-08 11-02-58](https://user-images.githubusercontent.com/6404071/39752175-f10446e0-52ba-11e8-87af-27abd1db1f8d.png)

## Result

The masonry layout is recalculated when the screen is resized but not at the end of the image loading, so it is not properly created when combined with lazy loading settings in JetPack.

When you resize the screen, the masonry layout adapts to that and then it looks good. 

## Expected

The masonry layout should be recalculated at the end of the images loading. 

* User report: [https://wp.me/p9F6qB-up]
* Follow-up ticket: [Asked the user to remove lazy loading option #1143441-zd]
* User's site: [usr site https://meinwarschau.com/category/wirtschaft-und-politik/ -they'll probably fix it- so test site https://atraultest.blog/category/tendencias-itcomext/]

**Comment by thomasguillot** [comment]
It's a premium theme. Please use our premium trac to report this issue.

**Comment by rantoncuadrado** [comment]
My bad... I mistakenly thought it was trac for free, GH for premium :/ Going to report this there.
