### ISSUE TITLE
P2: Square icon appears in small screen / mobile

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#1238]
## Steps to replicate

- In mobile, view the site.  
- In desktop, reduce the window size and view the site. 

## Result

In the Customizer > Theme Options, when "Enable front-end editing" is not selected, a square icon will be displayed in small screens: 

- In desktop (Chrome, Safari and Firefox), the site in 876 pixels or smaller screen will display a square icon on the upper left hand side. 

<img width="391" alt="Screenshot 2019-08-10 at 16 54 54" src="https://user-images.githubusercontent.com/36863633/62823310-23b10800-bb90-11e9-9482-bd49deae24f5.png">

- In mobile, the square icon will be displayed on the upper left hand side right away. 

<img width="662" alt="Screenshot 2019-08-10 at 17 07 37" src="https://user-images.githubusercontent.com/36863633/62823472-69220500-bb91-11e9-9848-41b66ef0c0a9.png">

## Expected

(In small screen and mobile): 

- Using CSS code hid the square icon, but without CSS access, the square icon will remain. 

- And in the Customizer > Theme Options, when "Enable front-end editing" is selected, the square icon will be replaced by a hamburger menu. 

- When "Enable front-end editing" is deselected, the square icon will appear again.

* User report and follow-up ticket: #2264479-zd

**Comment by cathymcbride** [comment]
retired theme. Closing...
