### ISSUE TITLE
Radcliffe 2: Checkout Info. on Store Page Using WooCommerce Not Visible

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/themes#124]
## Steps to replicate

Go to a checkout page and try to enter information. The information is there (seen when you go back to the box and click or highlight) but disappears when one goes to the next box.

![screen capture on 2018-05-08 at 11-35-14](https://user-images.githubusercontent.com/2545184/39767210-33a2d4fa-52b4-11e8-88e6-d245489ea247.gif)

## Result

It appears the form fields are using white text when not focused. This could have something to do with the Style Packs, but when I switch the pack, it still happens.

## Expected

I expected my information to show in black font and remain there.

* Follow-up ticket: #1145182-zen
* User's site: https://lakevillesouthstrength.com/checkout/ 
(you can add items to the cart from https://lakevillesouthstrength.com/shop/

**Comment by kathrynwp** [comment]
The WooCommerce cart page had the same problem, visible on the Quantity field. 

Suggested this custom CSS to the user:

```
/* Change text color on form input fields so it's visible on white form-field backgrounds */
input[type="date"], 
input[type="datetime"], 
input[type="datetime-local"], 
input[type="email"], 
input[type="month"], 
input[type="number"], 
input[type="password"], 
input[type="range"], 
input[type="tel"], 
input[type="text"], 
input[type="time"], 
input[type="url"], 
input[type="week"], 
textarea {
  color: #111;
}
```

**Comment by kathrynwp** [comment]
p.s. I made the custom CSS classes broader since the white-on-white form fields would likely be on issue if they ever add a contact form or any other forms. 

Issue seems to be coming from the `<style type="text/css" id="custom-colors-css">` block in the head, although the site is running the default style pack.

**Comment by laurelfulford** [comment]
Fixed in r48995-wpcom-themes.

Since this is Business Plan site, the fix will be pushed to this site later this week -- I'll follow up here once it's on the user's site!

**Comment by laurelfulford** [comment]
(Late) confirmation that this has been synced up to the user's site. 

@ChrissiePollock could you please follow up with the user? It looks like the linked ZD ticket has been closed, so I can't add a comment. Thanks!
