### ISSUE TITLE
[P2]Password protected posts do not render the content if front-end editing is turned

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#1243]
## Steps to replicate
1. Create a password-protected post.
2. Make sure that under Customize-> Theme options-> Front-end editing is turned on.
3. Check if the post renders the password protected field + message.

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

## Result
It doesn't.

* User report: #2267318-zen

Also, was able to replicate it on my end.

**Comment by cathymcbride** [comment]
retired theme. Closing...
