### ISSUE TITLE
Modern Business: Add Black Color in Custom Color options

### ISSUE THREAD

**Issue by rahul020691** [Automattic/themes#1244]
Currently, in Modern Business theme in Custom Color options we cannot choose black color

1) Open Customizer
2) Click on Colors tab.

https://cld.wthms.co/Hnek7J

You cannot select black color (such an obvious option to have)

User Reported: hc-14475763

**Comment by danieldudzic** [comment]
Modern Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Maywood: https://wordpress.com/theme/maywood
