### ISSUE TITLE
Affinity: Logo not present on any inner pages (logo only appears on the homepage)

### ISSUE THREAD

**Issue by angelica10000** [Automattic/themes#125]
## Steps to replicate

1. Activate the Affinity theme
2. Add a site logo
3. You will see that the logo only appears on the homepage and not the others pages

## Result

No logo displayed in any of pages except for the home page.

## Expected

- Make sure that the logo is added under Site Branding and not Description.
- Logo should display on all pages.

* User report: [#2269834-hc]
* Follow-up ticket: [#1148163-zen]
* User's site: [https://rocksaltbrighton.wordpress.com/ and https://rocksaltbrighton.wordpress.com/drink/]

**Comment by alaczek** [comment]
Yes, looking at the code the logo will only be displayed on homepage, archives, and search results pages. This was a conscious design decision, and not something we would change at this point.

If this user would be open to switching themes, I'd recommend they try Pique.

**Comment by sourourn** [comment]
Noted, thank you!
