### ISSUE TITLE
Varia: Full-width Columns inside of a full-width Cover block are not full-width on the front-end

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#1252]
Editor:

![Editor](https://user-images.githubusercontent.com/905781/63025695-076fdc80-beaa-11e9-969e-b69969629611.jpg)

Front-end:

![Front-end](https://user-images.githubusercontent.com/905781/63025778-37b77b00-beaa-11e9-8001-ca40eabb483a.jpg)

**Comment by allancole** [comment]
Yup, this will get fixed when #1246 is merged. The fix is a fairly large refactor, so we’re going to apply the fix to all child themes at once. 

If you’re launching your theme on Thursday, you can launch it without the fix, but if not it’ll get fixed after Thurs, possibly Monday.
