### ISSUE TITLE
Varia: Align wide/full in a Cover block doesn't work

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/themes#1254]
## Steps to replicate

Add a child block (e.g. columns) to a Cover block and then set the alignment to wide or full.

## Result

<img width="1552" alt="Screenshot 2019-08-14 at 18 22 38" src="https://user-images.githubusercontent.com/177929/63041843-aa335580-bec0-11e9-9f38-4750b655a4a7.png">

## Expected

Elements should be displayed wide or full.

**Comment by allancole** [comment]
Yeah this a known issue in Varia and it will get fixed when this PR is merged: https://github.com/Automattic/themes/pull/1246. If you found this in a new child-theme you’re planning to launch Thurs, you can go ahead and launch without the fix. We’re gonna merge that Varia PR, on Monday and we’ll semi-auto-fix all the child themes at once.

**Comment by thomasguillot** [comment]
Oh ok perfect, thank you @allancole 😊
