### ISSUE TITLE
Varia: Add separator block color variable

### ISSUE THREAD

**Issue by allancole** [Automattic/themes#1255]
The `.wp-block-separator` is [missing a config setting](https://github.com/Automattic/themes/blob/master/varia/sass/blocks/separator/_style.scss#L3) for the border-color. It defaults to the global border-color variable, but some themes may want the separator color to be different.

Since there’s already a config variable for the separator height, I think a color variable would make this easier to change on the front end and backend.

**Comment by nielslange** [comment]
@allancole It seems that this featured had been implemented already:

<table>
<tr>
<td>

![#1255-editor](https://user-images.githubusercontent.com/3323310/75619880-0f783b00-5bb4-11ea-9f07-c420afb86bb3.png)
</td>
<td>

![#1255-frontend](https://user-images.githubusercontent.com/3323310/75619878-0dae7780-5bb4-11ea-9ffd-a9f9d612ab4b.png)
</td>
</tr>
</table>

I guess this issue can be closed, right?

**Comment by jffng** [comment]
Confirmed, Gutenberg allows users to customize the separator color, and I think it is best to avoid adding additional configuration options at the Varia level at this time.
