### ISSUE TITLE
Canape: Menu Items aren't listed in Calypso

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#126]
## Steps to replicate

![canape-bug](https://user-images.githubusercontent.com/3521683/39817284-1b62e5f4-5374-11e8-860f-ab8ad6b1f502.gif)

## Result

As you can see in the gif above, the menu item is added, but Calypso doesn't list it, and displays the "No Menu Items found" message although it counts it. The menu item appears in WP Admin and can be edited there.
The items count is also wrong. It shows 3 Published menu items, that's because I used to have 3 menu items before in my test site, but I have deleted them to make this gif. I cleared my browser's cache to see if it would update, but it didn't.

## Expected

Calypso should list menu items that were created and published count should match it.

* User report: #1822654-hc
* Follow-up ticket: #1148472-zd
* User's site: http://thefodband.wordpress.com

**Comment by thomasguillot** [comment]
I would say this is more of a Calypso/CPT issue than something specific to Canapé.
Have you tried testing this with wp-admin?

**Comment by catkit** [comment]
Yes, I have tested it with WP Admin and it works there. The problem is at Calypso only, but I don't know where this is coded, if in the theme or in Calypso. I assumed in the theme as there are other themes that also have post types that can be managed via Calypso without problems. I assume this is something a developer would know better than me and move the ticket if needed.

**Comment by alaczek** [comment]
This issue has been reported in Calypso here: https://github.com/Automattic/wp-calypso/issues/15234

I added your report and will be closing this ticket.
