### ISSUE TITLE
Harmonic: Sticky posts don't show on front page

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#1261]
## Steps to replicate

1. Create a couple of posts on your site.
2. Create a new page, choose the Front Page template and set as the site's front page in the Customizer.
3. Choose 1 of the posts to be sticky.

## Result

The sticky post is removed from the post list on the front page.

## Expected

To show the sticky post on the top, on the front page.

Here's an example from the front page, where I have 6 posts and set the 4th as sticky:

![Screenshot - Free Plan – Guten 2019-08-15 08-11-16](https://user-images.githubusercontent.com/16104522/63091476-db4d6d80-bf34-11e9-8b5c-d242f93880ff.png)

While it shows correctly on the post's page:

![Screenshot - Blog – Free Plan – Guten 2019-08-15 08-11-56](https://user-images.githubusercontent.com/16104522/63091493-e4d6d580-bf34-11e9-93f7-06042005a3fc.png)

* User report: #2274256-zd

**Comment by danieldudzic** [comment]
Hi @carinapilar,

For one reason or another, Harmonic excludes Sticky posts intentionally (on the Front Page template).

From file content-front-news.php:

```
$args = array(
	'posts_per_page'  		=> 7,
	'ignore_sticky_posts' 	=> 1,
	'post__not_in'        	=> $sticky,
);
```

Please note that Harmonic is retired, so we won't be making any changes/enhancements at this point.
