### ISSUE TITLE
Twentysixteen: Having no sidebar widget breaks the single post layout

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#1263]
## Steps to replicate

1. Create a post - usually one with more content is more obvious.
2. Make sure there's no sidebar widget
3. Elements will start to overlap each other on the single blog post page.

## Result
https://monosnap.com/file/rwQqTO15r1TwFTbosHV2SdiDoMLBb2

When I add a sidebar widget the styling returns to normal.

* User report: #14414896-hc
* Follow-up ticket: #2276351-zen

**Comment by danieldudzic** [comment]
This seems to be not correct. A valid content will display correctly, even if the sidebar is not present.

If you look at the content added on the user's site: https://kcmpdwordpresscom.wordpress.com/2019/08/15/importance-of-independence-day-2019/ - it's a mess of HTML markup.

I would have been surprised if it _didn't_ break anything.

I'd recommend to the user, to use Gutenberg blocks and avoid inserting (complicated) custom html.
