### ISSUE TITLE
Karuna: Incorrect Demo site link

### ISSUE THREAD

**Issue by galakhyati** [Automattic/themes#1270]
## Steps to replicate
When on the [Karuna theme page](https://wordpress.com/theme/karuna), click on the `Open live demo` link opens the link to the [Rockfield demo site](https://rockfielddemo.wordpress.com/). 

## Result

The link opens the link to the Rockfield demo site.

## Expected

Expected to land on https://karunademo.wordpress.com

* User report: #14601069-hc

**Comment by nielslange** [comment]
Close issue as this seems to be fixed by now.
