### ISSUE TITLE
Sela: Featured images not being saved to posts after initial publication

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#128]
This issue is based on a report from a user who informed us that when they add featured images to their posts, the featured images are disassociated from the posts on initial publication.

## Steps to replicate

1. Create a new post in Calypso
2. Add text (in my test, this was placeholder text)
3. Add a featured image (I used an image from the free library)
4. Publish the post once the featured image was loaded.

My `Content Options` settings in Customizer are the following:

![](http://cld.wthms.co/dcRhnm+)

## Result

The post published without the featured image. See here:

![sela_featured_image_post](https://user-images.githubusercontent.com/2912202/39858079-25955834-543e-11e8-9c03-c11687e5dfae.gif)

I created a post in WP Admin and the featured image was correctly applied to my test post:

![](http://cld.wthms.co/hn4enm+)

I am able to add the featured image back to the post after publication. When I do that, the featured image seems to remain in place as expected.

## Expected

When adding a featured image, the image should be applied to the post and published based on `Content Options` on the site.

* User report: 1126406-zen
* User's site: acsquaredbookblog.com

**Comment by alaczek** [comment]
I tested three ways of adding featured image:
* from previously uploaded images
* by uploading new image to the post
* using the free photo library

Of the three only the last one didn't work, which made me think it's an issue with the free photo library feature. I also tested this in one other theme (Dyad 2), and got the same results.

I looked in Calypso repo, and there's an issue for this already (https://github.com/Automattic/wp-calypso/issues/24807), so I'll add your report there and will be closing this ticket.
