### ISSUE TITLE
Varia: default and wide separators are identical

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1286]
This is a side effect of #1246.

Now the default and wide separators are the same on the front of the site.

<img width="821" alt="Screen Shot 2019-08-19 at 17 17 39" src="https://user-images.githubusercontent.com/908665/63281742-48e6fa00-c2a5-11e9-9947-3e8870eca48a.png">

**Comment by allancole** [comment]
Fixed in #1288
