### ISSUE TITLE
Varia: (and possibly child themes) Logo is loading as thumbnail, scales poorly

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/themes#1287]
## Steps to replicate

1. Load up Varia or one of the child themes like Redhill
2. Add a site logo over ~300px
3. Inspect the logo, it is loading as the smallest possible size, usually around 150px

## Result
If you add CSS to enlarge the image, it will scale poorly and become distorted. Hard to implement larger logos as they are being loaded as very small images.

![image](https://user-images.githubusercontent.com/16580129/63282191-41f7c180-c27c-11e9-9fe4-5151bdc35fe4.png)

1. Image shows as blurry if scaled up with CSS
2. Width is set to 250px manually
3. But the intrinsic width is 99px

## Expected
Ideally, I could load an image at a median size, ~500px, so I can scale it accordingly.

* User report: p1566230277047000-slack-livechat

**Comment by allancole** [comment]
Thanks for reporting, @jjchrisdiehl :-) 

I think we’re gonna borrow the logo resizer script used in Radcliffe 2 as seen here: https://wordpress.com/theme/radcliffe-2#logo. That way, you and/or customers won’t need to bother with custom CSS at all. Adding this to the Varia parent means all child themes will benefit.

**Comment by eduardozulian** [comment]
@allancole can you confirm that this won't be an option for these themes? The compression is not ideal at the moment.

**Comment by eduardozulian** [comment]
Another report on 2403274-zen, now coming from Stratford.

**Comment by ariel-maidana** [comment]
Another report on 4567802-zen, Hever Theme.
