### ISSUE TITLE
Varia: Aligned Button inside of a Column block issue

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#1289]
If you add a Button inside of a Column block and then Align the button to left/right, it will display incorrectly:

Front-end:
![aligned_buttons_in_columns](https://user-images.githubusercontent.com/905781/63338306-d7f61f80-c342-11e9-9bf8-2fe797f8dfae.jpg)

Editor:

![aligned_buttons_in_editor](https://user-images.githubusercontent.com/905781/63338349-e6dcd200-c342-11e9-9a59-2ba0a4591131.jpg)

**Comment by thomasguillot** [comment]
Fixed in #1297
