### ISSUE TITLE
Orvis: Portfolio gallery and individual images switch places on the front-end of the site

### ISSUE THREAD

**Issue by kriskorn** [Automattic/themes#129]
When galleries and individual images are added to the Orvis theme via the Portfolio feature, then they switch places on the front-end. This does not happen, when you create Pages instead of Portfolios.

## Steps to replicate

1) Activate Orvis theme
2) Go to Portfolios -> Add
3) Add a gallery
4) Add an individual image
5) Add another gallery

## Result

<img width="1040" alt="orvis-front-end" src="https://user-images.githubusercontent.com/12064241/39867779-45889ab8-545f-11e8-869e-cf3a977e904f.PNG">

## Expected

<img width="778" alt="orvis-back-end" src="https://user-images.githubusercontent.com/12064241/39867785-4a7f2492-545f-11e8-8465-bf2ad80f9c49.PNG">

As you can see, the Portfolio galleries and images have switched places on the front-end of the. All of the individual images come after galleries.

* User report: #1145061-zen
* Follow-up ticket: #1145061-zen

**Comment by alaczek** [comment]
We discussed it at length before in 4949-wpcom-themes, and closed as wontfix, so I'm gonna do the same here. TL;DR is that while this behaviour is illogical, there's no easy way to fix this, not without disturbing existing user sites. In that ticket there is a possible CSS solution, but looks like this user doesn't have any upgrades :|

Let me know if there's anything else we can do here to help.
