### ISSUE TITLE
Redhill: Footer credit option is missing or doesn't behave correctly

### ISSUE THREAD

**Issue by caimin-j** [Automattic/themes#1291]
A user came into chat to report that changing the footer credit option under Site Identity wasn't having any affect on the preview content in the customizer or on the public site.

I was able to replicate this when SU'd as them.

When testing Redhill on my test site, I found the option to change the footer was completely missing. 

## Steps to replicate

1. Switch to Redhill theme.
2. Open customizer, then Site Identity.
3. If the footer credit option appears, try to use it to customize the footer credit.

This is what I see with Redhill installed:

<img width="277" alt="Screenshot 2019-08-20 at 12 51 14" src="https://user-images.githubusercontent.com/37620825/63344830-3aeab500-c349-11e9-9e23-9d71a70e45ba.png">

Original HC: https://mc.a8c.com/support-stats/happychat/transcript.php?id=14644322

Follow up ticket: https://woothemes.zendesk.com/agent/tickets/2288121

**Comment by iamtakashi** [comment]
@caimin-j I can see the footer credit option and is working correctly. By the way, this is WP.com specific option so if you're testing with your local install, you won't see it.

<img width="1124" alt="Screen Shot 2019-09-27 at 16 35 52" src="https://user-images.githubusercontent.com/908665/65782227-1f8f7880-e145-11e9-9568-a4ca62ec24c0.png">

**Comment by caimin-j** [comment]
@iamtakashi Thanks for taking a look.

I'm testing with my WordPress.com plan but after some further testing I can see the option is missing with every theme I've looked at, so it's not related to Redhill specifically.

I'll do some more testing and report this elsewhere if needed.

**Comment by iamtakashi** [comment]
@caimin-j More info about the Footer Credit here: https://en.support.wordpress.com/footer-credits/

I'm closing this because this is not the theme specific issue.
