### ISSUE TITLE
Varia: Quote block needs some tweaking

### ISSUE THREAD

**Issue by thomasguillot** [Automattic/themes#1292]
## Default Style

The default style has a border which can become invisible when using a background colour (e.g. in a group). I'd suggest the border inherits the text colour.

Also, there's a padding on the right that shouldn't be needed.

![Screenshot 2019-08-20 at 17 46 38](https://user-images.githubusercontent.com/177929/63366996-ccbae800-c372-11e9-9f2b-332c3c607bf8.png)

## Large Style

For the large style, the `cite` can be invisible when using a background colour (e.g. in a group). I'd suggest it inherits the text colour.

Also, the right and left paddings aren't needed.

![Screenshot 2019-08-20 at 17 46 04](https://user-images.githubusercontent.com/177929/63367108-08ee4880-c373-11e9-9e3b-089776531985.png)

**Comment by iamtakashi** [comment]
The border and the citation colour issue has been fixed in #1434. I'll work on the padding issue.
