### ISSUE TITLE
Coutoire: Broken iFrame CSS for embeds

### ISSUE THREAD

**Issue by sarahfg** [Automattic/themes#1302]
## Steps to replicate
1. Activate Coutoire on an Atomic site
2. Use an HTML block paste the code to embed iFrame code in a page or post
3. Publish

## Result

The iFrame will have a width of 32px.

![](https://cld.wthms.co/6heKCa+)
(Image link: https://cld.wthms.co/6heKCa )

This is due to the following CSS

```
@media only screen and (min-width: 560px) {
  .entry-content > iframe[style] {
      max-width: 32px !important;
  }
}
```

This is in OpenGrok at `/coutoire/style.css#2745`

## Expected
I expected the iFrame embeds to have the same content width as the rest of the post or page

The user experienced this issue when embedding a schedule from Acuity Scheduling. I repeated it on my test Atomic site using a Google Doc embed. I was not able to repeat it with other embeds like the ones from the built in Instagram, Tumblr, Reddit, etc blocks.

* User report: #2291861-zen
* Follow-up ticket: I have given the user CSS to correct the issue so they need no follow up.

**Comment by allancole** [comment]
Interesting. I’ll take a look shortly…

**Comment by eduardozulian** [comment]
@allancole I think you're probably aware of that but since I was testing another issue, I just realized that is happening apparently on every Varia-based theme. Screenshot from my test with Rockfield:

![see screen shot](https://cld.wthms.co/QM7fgX+)
_Link:_ https://cld.wthms.co/QM7fgX

**Comment by allancole** [comment]
@eduardozulian or @sarahfg do either of you have an iframe embed code I can test with. Or better yet, could you share the text in the “Code Editor” view of one of these posts? That way I can test with the exact content causing the issue. Thanks!

**Comment by sarahfg** [comment]
@allancole Here's the code I was using:

```
<iframe src="https://docs.google.com/document/d/e/2PACX-1vQ3LUltEnHvu_ztordWDulnI3wv5zZPOwTVyua4TEikFuElBCcJwx23V4ZcXvOXsAsNJ472ixRT60_g/pub?embedded=true"></iframe>
```

Here's what it looks like in the editor, being used in an HTML block. 

![](https://cld.wthms.co/pJYqBU+)
(Image link: https://cld.wthms.co/pJYqBU )

I first noticed it when helping a user. The user was using the plugin and accompanying shortcode here https://help.acuityscheduling.com/hc/en-us/articles/218725428-Embedding-Your-Scheduler-on-WordPress .

**Comment by jonnyruzek** [comment]
Reported in #2447862-zen

**Comment by separatelyunited** [comment]
@allancole in Jonny's report above, the iframe came from a Bandcamp Shortcode embed on a Simple site.

Shortcode used was: [bandcamp width=100% height=120 album=645121342 size=large bgcol=ffffff linkcol=0687f5 tracklist=false artwork=small]

**Comment by tanjoymor** [comment]
I had another user with the Stow theme having unexpected issues with an iframe. I was able to recreate the issue on my test site on this page: 

https://tanyajones.blog/broken-iframe-css/

I played around with the code and did find some issues that were resolved in the original code provided by the user, but it still pushes the iframe off to the left. Setting margins via CSS caused the right side of the embed to disappear.

I was able to find a work around by:
1) adding a Group block
2) adding a custom html block into the group block
3) adding the iframe code

This placed the embedded iframe where it was expected (bottom one on my example page above.

(If my sample page ends up not being on the Stow theme at some point, just ping me and I'll change it back - it's one of my test sites.)

#2493676-zd

**Comment by ccwalburn** [comment]
Another report from a user using Mayland.

#3170967-zen

**Comment by danieldudzic** [comment]
This seems to be working fine now: 
<img width="1275" alt="iframe" src="https://user-images.githubusercontent.com/905781/107633658-affe2880-6c68-11eb-9d29-264d388ec4a6.png">
