### ISSUE TITLE
Redhill: Top level menu items appear indented on mobile

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1307]
## Steps to replicate

1. Add a menu to the site containing only top-level menu items
2. View on mobile and tap the menu button

## Result

The menu expands, but show the menu items at several levels of indentation, as if the menu has child and grandchild-pages.

![Types_of_yoga_–_Redhill](https://user-images.githubusercontent.com/11873759/63506419-c42ef280-c4d5-11e9-9fd0-8e85027db9f3.png)

Screen shot from responsive mode in Firefox, but confirmed in Chrome on Android as well.

Setting an actual child menu item causes it to be distinguished from top-level items with a dash, but the top-level items still get indented:

![Customize__Redhill_–_4600_International_Gateway__Columbus__OH_43219__USA](https://user-images.githubusercontent.com/11873759/63506536-00fae980-c4d6-11e9-9d5c-7a7144e646af.png)

## Expected

For all top-level menu items to appear directly under each other, and only actual child menu items to be indented.

* User report: https://en.forums.wordpress.com/topic/lists-shifted-to-the-edge-of-the-screen

**Comment by allancole** [comment]
This was fixed in #1315, but not yet deployed to wpcom. Gonna leave this issue open until we move the fix to wpcom.

**Comment by galakhyati** [comment]
Another reported here: #12663551-hc

Helped the user with some CSS fix.

**Comment by iamtakashi** [comment]
The fix has been deployed to WP.com.

<img width="386" alt="Screen Shot 2019-09-27 at 17 13 24" src="https://user-images.githubusercontent.com/908665/65784548-35536c80-e14a-11e9-8eca-d20895e48825.png">
