### ISSUE TITLE
Comment fields broken on logged out view in Chrome

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/themes#1317]
## Steps to replicate
- sign out of your WordPress.com account
- visit bloomsburylitter.home.blog
- open a post and scroll down to the comments box
- it will look like this: https://photos.app.goo.gl/CMqkHfPX6xZjj3h29
[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

## Result
unable to complete fields necessary to leave comments

[What happened.]

## Expected
Would expect the comment boxes to function same as the logged in view (which is not broken)
[What you expected to happen.]

* User report: https://en.forums.wordpress.com/topic/comments-not-working-22/#post-3358294

**Comment by iamtakashi** [comment]
Which theme is in question? The current active theme is Redhill, and the comment form works fine for me (Chrome)

<img width="801" alt="Screen Shot 2019-09-27 at 17 05 20" src="https://user-images.githubusercontent.com/908665/65784055-26b88580-e149-11e9-9335-22edcd9fe513.png">

**Comment by danieldudzic** [comment]
I was unable to replicate the issue with Redhill.

I'm closing this. Please re-open if the issue persists.
