### ISSUE TITLE
Hever: Hide Footer Credit Leaves the Site Title Behind

### ISSUE THREAD

**Issue by jacoswan** [Automattic/themes#1321]
## Steps to replicate

1. Install Hever theme
2. In Customize » Site Identity, add a site title to the site
3. Footer credit on front end now reads "Site Title, Powered by WordPress.com."
3. In Customize » Site Identity, Set "Footer Credit" to hide. 
4. Footer credit on front end now reads "Site Title"

## Result

Only "Power by WordPress.com" is hidden, the site title remains. 

## Expected

Based on the assumption that the site title is part of the "footer credit", user expected that to be hidden along with the WordPress.com part of the footer credit. 

* User report: [14790056-hc]
* Follow-up ticket: None, solved with CSS snippet.

**Comment by iamtakashi** [comment]
> Only "Power by WordPress.com" is hidden, the site title remains.

This is how it supposed to be :) Won't fix.
