### ISSUE TITLE
Calm Business: Latest Posts Block White Text Colour Makes it Difficult to Read

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#1322]
## Steps to replicate

1. Activate Calm Business theme.
2. Make sure there are a few Blog posts on the site.
3. Add Latest Posts Block.

![Screen Shot on 2019-08-25 at 10:19:55](https://user-images.githubusercontent.com/25105483/63647524-ac987980-c722-11e9-8dc8-3988cbec2a9f.png)

## Result

Text is white, difficult to read.

## Expected

Text has darker colour and is easier to read.

* User report: #2298953-zen

In this case I helped the user with the following custom CSS:

```
/* Calm Business theme Latest Posts block bug workaround / io / #2298953-zen */
.wp-block-latest-posts__post-excerpt {
  color: #242424;
}
```

**Comment by ivan-ottinger** [comment]
Maybe related to #1091 ?

**Comment by danieldudzic** [comment]
Calm Business has been retired so I'm closing this as a wontfix.
