### ISSUE TITLE
Stow: mobile menu items appear indented despite not being submenus.

### ISSUE THREAD

**Issue by sourourn** [Automattic/themes#1324]
## Steps to replicate

1. Click on My Site > Design > Customize > Menus > add new menu items (make sure that they are main level menu items (not sub-menus).

## Result

Preview the menu on mobile screens - the menu items appear indented even though they are main menu items. This is happening on the theme demo too.

## Expected
Menu items should not be indented unless they are added as submenus.

![Screen Shot 2019-08-22 at 10 19 44](https://user-images.githubusercontent.com/39188945/63714421-122f5780-c842-11e9-8d51-3b4fe49407ea.png)

* User report: #2279678-zen

**Comment by iamtakashi** [comment]
The fix has been deployed to WP.com.

<img width="410" alt="Screen Shot 2019-09-27 at 17 15 15" src="https://user-images.githubusercontent.com/908665/65784643-6d5aaf80-e14a-11e9-96b8-be3fac89571b.png">
