### ISSUE TITLE
Dara: Print Stylesheet loading date for posts twice.

### ISSUE THREAD

**Issue by rezzap** [Automattic/themes#134]
## Steps to replicate

1. Open your post page with the Dara Theme active and dates showing.
2. Select the option to print and look at the preview window

## Result
3. The date for posts is listed twice:

<img width="986" alt="image 2018-05-17 at 9 50 58 am" src="https://user-images.githubusercontent.com/10325627/40167102-0dfa44d0-59b8-11e8-806f-e8bd3722b438.png">

## Expected

The date should only display once in the format selected by the user in settings. 

I have tried this in both Chrome and Firefox and the same thing replicates. The user also mentioned it on his site in Safari and Firefox. 

When I view the page source and open the print stylesheet I see two entries for the date in the CSS. 
<img width="1580" alt="image 2018-05-17 at 9 49 43 am" src="https://user-images.githubusercontent.com/10325627/40167220-6372f07e-59b8-11e8-962f-21a94afcc782.png">
I'm not sure if that's relevent or not, but perhaps useful.

I tested this with the Twenty Sixteen Theme, and the issue was not replicated there. I also tried testing with the French or English language setting set and this didn't change anything.

* User report: #1159461-zd
* Follow-up ticket: #1159461-zd
* User's site: https://jacquesdesrosiers.blog/ (front page is blog page)

**Comment by laurelfulford** [comment]
I was also able to recreate this issue with Altofocus and Dyad 2; it seems to be an issue with the global print styles, and not be theme-specific.

I've reported it here: 8084-wpcom.
