### ISSUE TITLE
Varia: Full Width, Full Size Image Block cuts off on mobile

### ISSUE THREAD

**Issue by thebud15** [Automattic/themes#1348]
## Steps to replicate

1. Add an image block on the top of the homepage for a Varia themed site (or its child themes, such as Alves, Morden, Coutoire, Stow)
2. Set it up to be full width and full size.
3. View the page on a mobile screen.

![Screen Shot 2019-08-28 at 19 09 01](https://user-images.githubusercontent.com/29046778/63899031-30b36100-c9b0-11e9-822b-f15c7beaf56d.png)

## Result

The right side of the image block cuts off on mobile, seemingly at 559px and smaller. 

![Screen Shot 2019-08-28 at 19 06 20](https://user-images.githubusercontent.com/29046778/63898912-abc84780-c9af-11e9-8c31-5e74474313ff.png)

## Expected

I expected it to display in full across the entire screen.

* User report: #14877555-hc
* Follow-up ticket: #2307980-zd (which includes a link to a related a8c Slack conversation)

**Comment by JoshuaGoode** [comment]
* Slack conservation related to discovery and workaround: p1567031561056000-slack-tickets

* Some example workaround CSS:

```
/* Fix Image Block Margins on Mobile */
@media only screen and (max-width: 559px) {
 figure.wp-block-image.alignfull.size-full {
    margin: 0 auto;
  }
}
```

**Comment by supernovia** [comment]
Free site - user can't fix with CSS because they don't have it. https://en.forums.wordpress.com/topic/images-full-width-and-spacers-dont-appear-in-sites-mobile-version/
