### ISSUE TITLE
Stratford: Button Block, Align Right is misaligned over Cover Block.

### ISSUE THREAD

**Issue by deancroyal** [Automattic/themes#1349]
## Steps to replicate

Test Site used: https://stratfordtestsite.wordpress.com/

Steps outlined below are **visualized here**: https://cld.wthms.co/WFA3Ep

1. Create a new page.
2. Add a Cover image and set it to Full Width.
3. Add a Text Block with some sample text.
4. Apply "Align Text Right" to the Text Block.
4. Below the Text Block, add a Button Block.
5. Give the Button Block some text, and a URL.
6. Apply "Align Right" to the Button Block.
7. Preview the page.

## Result

In the editor this is the result: 

<img width="1163" alt="Screen Shot 2019-08-28 at 7 58 44 PM" src="https://user-images.githubusercontent.com/13387217/63906878-4768b080-c9ce-11e9-99e5-3bf6e7b2e5b7.png">

In Preview (and published to the site) this is the result:

<img width="1414" alt="Screen Shot 2019-08-28 at 7 59 52 PM" src="https://user-images.githubusercontent.com/13387217/63906941-6cf5ba00-c9ce-11e9-9b0a-02153a919c32.png">

## Expected

I expected that what appeared in the editor would also appear in Preview and in the live site.

* Originally noticed in this chat: #14856290-hc
* Follow-up ticket with user: #2305874-zd

**Comment by iamtakashi** [comment]
@deancroyal Thanks for the report. I'd advice the user to add a group block first and add the text and the button inside the group if they want them to be aligned at the same place.

**Comment by iamtakashi** [comment]
Closing this issue as the solution has been proposed.
