### ISSUE TITLE
Pique: Inconsistency in "Read more" on various areas and on Grid Page Template

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#135]
This is a report from a self-hosted Pique user regarding some inconsistency in "Read More" on various sections of the theme, and on the Grid Template pages. Since this user wrote a very nice, and clear description of this in his forum thread, I'll not repeat it here (see link below).

I'm filing this enhancement request after first consulting with @davidakennedy in #themes Slack channel.

* User report: [https://wordpress.org/support/topic/custom-read-more-consider-applying-both-for-excerpt-and-content/](url)

**Comment by davidakennedy** [comment]
This is a worthy, but minor enhancement. We're mainly focused on new Gutenberg-enhanced themes and high-priority bug fixes in older themes. This enhancement doesn't fit that. I'm going to close for that reason.
