### ISSUE TITLE
Sophisticated Business: Missing custom color input field in Customizer

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/themes#1370]
In the Color section of the Customizer, there isn’t a place to add a HEX code, only a color picker.

Screenshot: https://cld.wthms.co/ZJdRjE

![ELO5zJ](https://user-images.githubusercontent.com/39252765/64026971-04592b00-cafd-11e9-840f-202553ec9e2c.jpg)

User report: #14916709-hc

## Steps to replicate

- Activate the Sophisticated Business theme
- Go to My Site > Design > Customize > Colors
- Set Primary Color to Custom

## Result

- There is only a color picker/slider

## Expected

- There should be a custom color input field to specify the exact desired color

**Comment by danieldudzic** [comment]
Sophisticated Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Rivington: https://wordpress.com/theme/rivington
