### ISSUE TITLE
Snaps: Anonymous Pro font cut off on small screens.

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#138]
## Steps to replicate

1. Activate Snaps theme
2. Set Anonymous Pro as Headings font
3. Navigate to a page that has a title
4. Reduce browser window size and view the site on a mobile device

## Result

The first letter of the site title is slightly cut off.

Screenshot: http://cld.wthms.co/sPad8r

## Expected

Expected behavior is the font to not be cut off. Issue does not occur on other themes with this font, or on the Snaps theme using a different font.

* User report: #3831468-hc
* Follow-up ticket: none yet
* User's site: https://cinnasnail.com

**Comment by laurelfulford** [comment]
This has been fixed in r48996-wpcom-themes; I've double-checked the affected site and no longer see the edge of the "C" cut off on the Contact Page.

@donalirl can you please follow up with the user? Thanks!
