### ISSUE TITLE
Independent Publisher 2: Table Block Column Width Does Not Adjust

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#1383]
## Steps to replicate

1. Create a new table with cell data of varying widths
2. Publish

## Result

The columns in the table do not respect the widths of the data inside them, even with 'fixed width table cells' disabled in the table block settings.

See this screenshot:  
![Annotation on 2019-09-03 at 09-48-46](https://user-images.githubusercontent.com/30727666/64135856-7351bf00-ce30-11e9-9c2b-bc35b62e6b99.png)

compared to the same table on a block-editor theme (Maywood):
![Screen Shot on 2019-09-03 at 09_46_36](https://user-images.githubusercontent.com/30727666/64135878-98dec880-ce30-11e9-8359-6ec29959d3cc.png)

## Expected

I expected the column widths to conform to the data inside.

* User report: #2316265-zen

**Comment by nielslange** [comment]
@donalirl I fixed this issue in https://github.com/Automattic/themes/pull/1778. Feel free to test this PR. 😉

**Comment by sdixon194** [comment]
Just an FYI that I came across this issue in 12864833-hc. Seems like a fix might be on the way?

**Comment by donalirl** [comment]
Another case of this in 21815850-hc. @nielslange is the fix going to be deployed?

For anyone who lands here, this CSS will address the issue:

/*  fix table width issue on IP2 theme -- XXXXXX-hc  */
table {
  table-layout: auto;
}
