### ISSUE TITLE
Apostrophe 2: no post_class() on single post page

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#1386]
When trying to help a user with CSS (the idea was to hide the audio block on posts with a certain tag), we discovered that there's we're not calling [`post_class()` on the single post page](https://github.com/Automattic/themes/blob/master/apostrophe-2/content-single.php#L7).

### Expected

To see all the extra classes I can use to customize just like [we have on `content.php`](https://github.com/Automattic/themes/blob/master/apostrophe-2/content.php#L8) or [in `content-page.php`](https://github.com/Automattic/themes/blob/master/apostrophe-2/content-page.php#L9).

Without this function, we can't target specific categories or tags when visiting a single post.

***

User report: 15003605-hc (not actually a user report but we realized that we wanted to do wasn't possible due to the missing `post_class()`)

cc @msilbers

**Comment by danieldudzic** [comment]
Thanks for the PR @eduardozulian !
