### ISSUE TITLE
Rockfield: Widget area alignment changes if no footer menu selected

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1395]
## Steps to replicate

1. Activate Rockfield, and add some footer widgets and assign a footer menu.
2. View the site and note alignment of the widget area
3. Return to the Customizer and remove the footer menu
4. View the site again - make sure this is on a wider screen: on my 13-inch monitor I only see the issue if I zoom out the page to around 90%

## Result

The widget area moves to be flush with the left margin of the screen:

<img width="959" alt="Shift_to_the_left_–_This_is_the_tagline" src="https://user-images.githubusercontent.com/11873759/64315950-c1430000-cfb3-11e9-9ccc-6686f12fcab4.png">

## Expected

For the widget area to remain aligned with the left margin of the content area on the site.

<img width="654" alt="Shift_to_the_left_–_This_is_the_tagline" src="https://user-images.githubusercontent.com/11873759/64315897-a4a6c800-cfb3-11e9-99af-3fab82d6a4a4.png">

* User report: https://en.forums.wordpress.com/topic/getting-the-hang-of-rockfield-theme/

Confirmed on a test site, and in multiple browsers.

**Comment by KokkieH** [comment]
I've let the user know, thanks!

**Comment by iamtakashi** [comment]
Thanks. I've deployed the new version to WP.com now.
