### ISSUE TITLE
Rockfield: More block alignment broken

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1396]
## Steps to replicate

1. Create a post using the block editor, add some text blocks separated by a More-block
2. View the post on the home/posts page of the site

## Result

The "Continue Reading" link is flush against the left margin of the page.

## Expected

For the link to appear within the content area instead.

Posts created in the classic editor using the more-tag display correctly.

<img width="796" alt="Posts_page_–_Shift_to_the_left" src="https://user-images.githubusercontent.com/11873759/64316337-cd7b8d00-cfb4-11e9-9314-86ed09fadffb.png">

* User report: https://en.forums.wordpress.com/topic/getting-the-hang-of-rockfield-theme/

Confirmed on a test site, and in multiple browsers.

**Comment by iamtakashi** [comment]
@KokkieH Thanks for the report.

This needs to be fixed in the parent theme Varia and I've created the issue as you can see above.

**Comment by KokkieH** [comment]
Thanks, @iamtakashi!

**Comment by iamtakashi** [comment]
@KokkieH The fix has been deploy to WP.com. Thanks!

**Comment by KokkieH** [comment]
Thank you!
