### ISSUE TITLE
 Gazette: Inconsistant image display on blog page 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#14]
This issue was originally reported by @chad1008 in 4354-wpcom-themes:

## Background:

On Gazette's home page, posts are displayed with `the_content()` if there is a More Tag in use, and then `the_excerpt()` if there is no More Tag:

From `content.php`:

```
<div class="entry-summary">
	    <?php
	        if ( strpos( $post->post_content, '<!--more' ) ) {
	            the_content( sprintf(
	                /* translators: %s: Name of current post. */
	                wp_kses( __( 'Continue reading %s', 'gazette' ), array( 'span' => array( 'class' => array() ) ) ),
	                the_title( '<span class="screen-reader-text">"', '"</span>', false )
	            ) );
	        } else {
	            the_excerpt();
	        }
	    ?>
	</div><!-- .entry-summary -->
```

In addition, images in post summaries (for the times when `the_content()` is used) are hidden by the theme's CSS:

```
.entry-summary img {
    display: none;
}
```

So, theoretically, if `the_content()` is used, images are CSS'd away. If `the_excerpt()` is used, they wouldn't be displayed anyway. There shouldn't be any images on the homepage.

## The problem:

The above rules do not account for images with captions, which get wrapped in `<figure>` elements. Those images appear on the front page just fine.

This can be confusing for a user who uses a lot of captions, then suddenly notices a missing image when they _don't_ caption ([example forum posting](http://en.forums.wordpress.com/topic/lead-photofeature-photo-appear-in-post-but-not-on-home-page)).

The other issue - if an image has a caption, it will be displayed when a More tag is used. On Image and Gallery post formats, that doesn't looks so great, due to the background images that are used (I suspect this is partially why images were being hidden in the first place?)

Example of a Gallery post, with a captioned image and a More Tag on the home page:

![](https://cldup.com/sZKK-zEnAJ.png)

## Steps to reproduce:

1. Create a post with a More Tag, and an image (place the image before the More Tag.
2. View your Posts Page - no image, and you can see it hidden if you inspect the CSS
3. Add a caption to your image, update and view the Posts Page again
4. Now the image should be visible
5. Set the post status to Gallery
6. Give the post a Featured Image, update and view the Post Page again
7. The captioned image appears over the Featured Image background

On the original ticket, @thomasguillot commented:

> It's a tricky one now... Because I'd be inclined to add `.entry-summary figure { display: none; }` to the css. But if I do that it'd affect the users already using a caption in their content... 
> 
> I'm not sure what we can do here apart from making the caption more readable on Gallery post format 

* User report: http://en.forums.wordpress.com/topic/lead-photofeature-photo-appear-in-post-but-not-on-home-page
* User's site: https://outwardhounds.wordpress.com/

**Comment by alaczek** [comment]
I'm gonna close this as wontfix, as this is a bit of an edge case, and it looks like the user who reported this issue moved on to a different theme already. We'll keep it in mind if we decide on releasing v2 of this theme. 

As for improving the readability of the image caption - it's tricky because it appears over an image. I'm gonna leave it as is for now, but we can revisit if we get another report.
