### ISSUE TITLE
Radcliffe 2: decreased transparency on hover is not applied consistently on the posts page

### ISSUE THREAD

**Issue by designsimply** [Automattic/themes#140]
Moved from 8060-wpcom. cc @xpurichan 

Note: I have copied the original bug report but I am also wondering if what is described is an intentional part of the design? ([ref](https://github.com/Automattic/themes/blob/master/radcliffe-2/style.css#L1484-L1488)) 

## Steps to replicate

Issue: A user had their homepage displaying their latest blog posts. Three blog posts were present. The first and third blog posts displayed decreased transparency while hovering over the title of the post, but the second post did not.

## Result

The site is AT and they did have CSS already applied to their site, but this problem was persistent even when their CSS was removed.

## Workaround

Solution details: Allan Cole in #themes found that CSS meant for the archive page was effecting this home page. He provided CSS to repair this problem and it has been applied to the user's site:

```
.blog #page article:nth-of-type(even) .entry-header:hover {
    background: rgba(0, 0, 0, 0.75);
}
```

* User report: 3823299-hc
* User's site: https://writerlywitch.com/

**Comment by laurelfulford** [comment]
Fixed in r48997-wpcom-themes.

@xpurichan can you please follow up with the user? Thanks!
