### ISSUE TITLE
Varia: Manually resized image become centred align on front of site

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1407]
Originally reported here: https://github.com/Automattic/wp-calypso/pull/36026#issuecomment-528900980

Image is left aligned if you don't set the alignment both in the editor and on the front of the site.

<img width="857" alt="Screen Shot 2019-09-06 at 16 06 06" src="https://user-images.githubusercontent.com/908665/64454505-0d409280-d0e3-11e9-826b-8b8c4b1ff360.png">

But if we manually resize the image, it becomes centre aligned, because the width of the `figure` becomes the size of the image. 

<img width="1643" alt="Screen Shot 2019-09-06 at 20 06 56" src="https://user-images.githubusercontent.com/908665/64454547-26e1da00-d0e3-11e9-841c-d49d925e9034.png">

We'll need to exclude this from the rue that adds auto margins to the sides.

```
.entry-content > *:not(... {
    max-width: 100%;
    margin-left: auto;
    margin-right: auto;
}

```

**Comment by Copons** [comment]
Just copying the gif I've posted in the other PR that could make it clearer of what's happening:

![Sep-06-2019 16-26-39](https://user-images.githubusercontent.com/2070010/64440044-2f2a1d00-d0c3-11e9-96d5-42a51a384092.gif)

**Comment by allancole** [comment]
This seems somewhat related to #1414. We can probably fix both in one PR.

**Comment by iamtakashi** [comment]
I looked into this issue, but it's trickier than I thought.

Image block changes the display behaviour of a resized image to `table` which change the width of the block.

**Comment by iamtakashi** [comment]
> Image block changes the display behaviour of a resized image to table which changes the width of the block.

This approach has been in question before: https://github.com/WordPress/gutenberg/issues/13684 In my opinion, this makes difficult to work with.

I'm not sure what we can do about it. @allancole any thought?

**Comment by allancole** [comment]
@iamtakashi Yeah, I think we may need to punt this one, unfortunately. Based on the comment [here](https://github.com/WordPress/gutenberg/issues/13684#issuecomment-465473023), any fix we apply in Varia will likely conflict with the true fix which needs to happen in core first.

**Comment by iamtakashi** [comment]
@allancole But the disparity in alignment between the editor and the front-end concerns me.

<img width="2556" alt="Screen Shot 2019-09-28 at 16 48 26" src="https://user-images.githubusercontent.com/908665/65819105-8d54a680-e210-11e9-93ef-edd0218dc1a7.png">

I wonder if Varia should make images centred align as default until a user specifies alignment for it. The position of the caption suggests that as well.

<img width="804" alt="Screen Shot 2019-09-28 at 16 55 38" src="https://user-images.githubusercontent.com/908665/65819121-db69aa00-e210-11e9-8dad-d5821423258a.png">
