### ISSUE TITLE
Modern Business: Unable to fully hide footer credit

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#1408]
## Steps to replicate

1. Set an Atomic site to use Modern Business.
2. Hide the footer credit in Design → Customize → Site Identity.

## Result

Some of the footer credit still shows: `Site title,`

## Expected

The site title (and comma) should be hidden as well.

* #15135519-hc

**Comment by danieldudzic** [comment]
Modern Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Maywood: https://wordpress.com/theme/maywood
