### ISSUE TITLE
Ryu: Menu unresponsive after scrolling to the bottom of the page that has embedded videos on mobile

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#1410]
## Steps to replicate
- In Safari on iOS open a page that has an embedded video (e.g. YouTube) https://antoinelami.com/music/
- Scroll to the bottom of the page
- Scroll to the top again
- Click on Menu to open it

Reloading the page fixes the issue.

![](https://cld.wthms.co/ctcnWm+)
_Screenshot link: https://cld.wthms.co/ctcnWm_

Reproduced in:
| Device | iPhone 7 |
| Browser | Mobile_safari |
| Operating System | iOS 12.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.64 x 5.44 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

## Result

Menu is not clickable anymore

## Expected

Menu expands

* User report: 2329361-zen
* Follow-up ticket: 2329361-zen

**Comment by danieldudzic** [comment]
Hey @zdenys,

It seems to be working fine for me: https://cloudup.com/c5qhHmR_3v6

Feel free to re-open the issue, if the problem persists.
