### ISSUE TITLE
P2: Display newest comments first

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#1412]
A request from our [forums](https://en.forums.wordpress.com/topic/sugestion-to-p2-theme/):

> We should have the OPTION to make every comment post go to the top of the page, as in a normal forum

Here's why they want that:

> In the case of my team, we are forming a publisher that will republish rare 19th century books in Brazil, and all posts have a perennial value, so the most important thing is not their posting date, but the date of the comments made on them.

> Also, I think it would create an important alternative for anyone who wanted to have a forum on the WP.com platform.

* User report: https://en.forums.wordpress.com/topic/sugestion-to-p2-theme/
* Follow-up ticket: https://en.forums.wordpress.com/topic/sugestion-to-p2-theme/

**Comment by cathymcbride** [comment]
retired theme. Closing...
