### ISSUE TITLE
Varia: Resized images larger than their container look as large as the container on the front end

### ISSUE THREAD

**Issue by Copons** [Automattic/themes#1414]
Originally reported here: https://github.com/Automattic/wp-calypso/pull/36026#pullrequestreview-285730964

## Steps to replicate

* Activate Varia.
* Insert an image without alignment settings.
* Manually resize the image as large as possible.
* Save and preview.

![Screenshot 2019-09-20 at 11 26 01](https://user-images.githubusercontent.com/2070010/65320356-9357e100-db99-11e9-9944-ca5e2a55aafa.png)

(Please note that the overflowing image has been already reported, and it's unrelated to this issue: https://github.com/Automattic/themes/issues/1101)

## Result

* The image is as large as its container.

![Screenshot 2019-09-20 at 11 26 22](https://user-images.githubusercontent.com/2070010/65320383-9ce14900-db99-11e9-801c-6a9c5586f9b0.png)

## Expected

* The image is as large as large as I've resized it.

---

It might be as easy as having max-width: none (instead of 100%) on .is-resized images. 🤔

**Comment by allancole** [comment]
Seems like a bit of an edge case, but one worth fixing :-) 
Interesting, I’ll take a look and see if I can replicate.

**Comment by iamtakashi** [comment]
I'd say the theme behaviour is correct. Users should not be able to make an image larger than the block. And this is an image block bug that has been reported. https://github.com/WordPress/gutenberg/issues/12168

Based on this, I'd close this as a theme issue. Please reopen if we don't agree :)
