### ISSUE TITLE
Exford:  Page titles split in submenus (Safari)

### ISSUE THREAD

**Issue by markx2** [Automattic/themes#1416]
## Steps to replicate

1. Use Safari

2. Add a page with a long title to a submenu 

Page title is Macrobiotic Restaurant
<img width="282" alt="Exford-Safari2" src="https://user-images.githubusercontent.com/7057656/65384757-ec508200-dd1d-11e9-8045-93215315402e.png">

## Result

See image

## Expected

That there not be a split

* User report: #13508004-hc

**Comment by iamtakashi** [comment]
@markx2 There is not much we can do about this. There will always be cases like this with any size of the dropdown. In my opinion, breaking a word like below will be worse.

```
Macrobiotic Restaura
nt 
```

**Comment by iamtakashi** [comment]
@@markx2 Sorry, I spoke too soon. The dropdown width should expand as it does in other browsers but Safari. We'll investigate.

**Comment by AtrumGeost** [comment]
Hi @iamtakashi !

Can the same fix be implemented for the Morden theme?

@eduardozulian helped me with some CSS code to fix this for a user. He said this could be coming from the `max-content` argument and that this could be a Varia-related bug.

Slack convo: p1573062328101700-slack-C03TY6J1A

Let me know if I should create a separate issue.

**Comment by iamtakashi** [comment]
> Let me know if I should create a separate issue.

@AtrumGeost Yes, I think that would be better. I won't be able to keep working on themes, but someone from the theme team should be able to pick up the issue soon. Thanks in advance!
