### ISSUE TITLE
Canard: Display Tagline

### ISSUE THREAD

**Issue by AashikP** [Automattic/themes#1419]
## Steps to replicate

Enable the option to display site title and tagline under: **WordPress.com > My Sites > Design > Customize > Site Identity**

![https://cld.wthms.co/avjXxv+](https://cld.wthms.co/avjXxv+)
*Direct Link: https://cld.wthms.co/avjXxv*

## Result

The tagline isn't displayed

![https://cld.wthms.co/33fbqU+](https://cld.wthms.co/33fbqU+)
*Direct Link: https://cld.wthms.co/33fbqU*

## Expected

Since the configuration option suggests user to check the box to display the title and tagline, I'd expect it to display them both. As seen in other themes:

![https://cld.wthms.co/79QFqW+](https://cld.wthms.co/79QFqW+)
*Direct Link: https://cld.wthms.co/79QFqW*

---

* User report: 5120557-hc

**Comment by danieldudzic** [comment]
This is a wontfix: https://wpcom-themes.trac.automattic.com/ticket/3987
