### ISSUE TITLE
Twenty Ten: Cookies & Banners Widget Missing Styling

### ISSUE THREAD

**Issue by jeremypaavola** [Automattic/themes#144]
A user reported an issue with Twenty Ten and the 'Cookies & Banners' widget, which is missing the following style (user likes the theme because it's 'simple'; it's in use on three of their sites):

```
.widget_eu_cookie_law_widget {
    border: none;
    bottom: 1em;
    left: 1em;
    margin: 0;
    padding: 0;
    position: fixed;
    right: 1em;
    width: auto;
    z-index: 500001;
}
```

This causes the widget to display at the very bottom of the page, rather than float. I know the theme is retired, but I'm wondering if this impacts on GDPR compliance, so reporting (as the theme is still installable on Atomic sites, and WPorg).

See video: https://cl.ly/0A1b0n110p0X

## Steps to replicate

1. On any Business plan site, install and activate the Twenty Ten theme
2. Add the Cookies & Banners widget to any sidebar
3. Scroll the homepage, and notice that the widget is not floating

## Result

The Cookies & Banner widgets sits at the bottom of the page

## Expected

The Cookies & Banners widget should float at the bottom of a visitors browser

* User report: #3970178-hc
* Follow-up ticket: #1191043-zd
* User's site: https://selfpublishingadventures.com/

**Comment by laurelfulford** [comment]
Thanks for the report, @jeremypaavola! 

This is something related to the widget, and it's been fixed in r176168-wpcom; I added a comment to the ZD ticket.
