### ISSUE TITLE
Karuna: Cover Block set to Full Width and Fixed Background Breaks

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/themes#1447]
Full width cover blocks with fixed backgrounds are broken.

## Steps to replicate

1. Create a new page.
2. Add a Cover block
3. Insert an image into the Cover block.
3. Set the Cover block to be full width
4. Turn Fixed Background on for the Cover block within Cover Settings.
5. Preview or publish the page.

## Result
Cover block appears broken.

![image](https://user-images.githubusercontent.com/4887830/65822392-2683bd00-e211-11e9-8346-c31fc1daa882.png)

## Expected

For Fixed Background option to work.

Regular full-width cover block works as expected. 

![image](https://user-images.githubusercontent.com/4887830/65822403-68acfe80-e211-11e9-9653-efaa9c5dd013.png)

## Rough Workaround

Can resolve by applying some CSS such as the following:

```
/* Karuna Theme - Resolve Full Wdith Cover Block Fixed Background Issues - xxxxx-hc/zen */
.wp-block-cover.alignfull.has-parallax {
    left: unset;
    transform: unset;
    margin-left: calc(50% - 50vw);
    margin-right: calc(50% - 50vw);
    max-width: 100vw;
 }
```

* User report: 14925225-hc
* Follow-up ticket: 2385552-zen
* Appears to impact other themes such as Illustratr:  #742

**Comment by damiannep** [comment]
Thanks for the CSS @JoshuaGoode. Used in it 2678636-zen

**Comment by davipontesblog** [comment]
Another user report in 3219083-zen. Thanks for the CSS @JoshuaGoode !

**Comment by scruffian** [comment]
I have a simpler solution to this: https://github.com/Automattic/themes/pull/2769

**Comment by davipontesblog** [comment]
Reported back to the users below that the fix is in place.
2385552-zen
2678636-zen
3219083-zen
Thanks @scruffian !
