### ISSUE TITLE
Shawburn: menu does not display as expected with cover image block and no social media menu

### ISSUE THREAD

**Issue by serabi** [Automattic/themes#1449]
On the Shawburn home page with the Home Page template applied, if the top block is a Cover Image block and you do not have a social media menu set to show, the Primary menu displays incorrectly. 

## Steps to replicate

With Shawburn as the theme, create a new home page using the Home Page template. Then, in the Customizer, set that page as the static home page, and disable the social media menu. 

## Result

<img width="780" alt="Screen Shot 2019-09-29 at 5 52 27 PM" src="https://user-images.githubusercontent.com/30205248/65840177-9bbfc280-e2e3-11e9-8b7c-96ec2ae9e5a1.png">

<img width="766" alt="Screen Shot 2019-09-29 at 6 06 02 PM" src="https://user-images.githubusercontent.com/30205248/65840192-d6c1f600-e2e3-11e9-991a-c0ef068336d0.png">

User report: 2387102-zen

**Comment by AtrumGeost** [comment]
Got another report here: 15647340-hc
