### ISSUE TITLE
Coblocks Pricing Table Item Title alignment is not centered on some template-first themes

### ISSUE THREAD

**Issue by sarahcada** [Automattic/themes#1453]
For sites using most template-first themes, the item titles for Coblocks Pricing Tables are not centered.

## Steps to replicate

1. On a Simple or Atomic site, change the theme to any template-first theme _aside from_  Varia, Leven, or Coutoire.
2. Create a Pricing Table on a page and put test content.
3. Publish or Preview the Page.

## Result

The Item Title is aligned to the left.

![not centered](https://cld.wthms.co/gLze78+) 

## Expected

The Item Title should be centered. This is how it appears in the Editor.

Note that the expected result happens for Varia, Leven, or Coutoire, and earlier themes like Twenty Nineteen, Lodestar, etc.

For now, we've provided this CSS as workaround (h/t @kristarella):

```
.wp-block-coblocks-pricing-table-item .wp-block-coblocks-pricing-table-item__title {
    margin-left: auto;
    margin-right: auto;
}
```

* User report: #14942015-hc

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
