### ISSUE TITLE
Dara: Gallery block not center aligned

### ISSUE THREAD

**Issue by thabotswana** [Automattic/themes#1456]
## Steps to replicate

1. Create a post using the block editor
2. Add a gallery block with 4 images
3. Make sure block is center aligned
3. Set gallery block to 2 columns

## Result

The Gallery will not be center aligned

(Image link: https://cld.wthms.co/ayYrXE)

## Expected

The gallery should be center aligned

* User report: #2386209-zen

Replicated on my test site at https://thabogutenberg.blog/2019/09/28/top-things-to-do-in-cochem-germany/

**Comment by danieldudzic** [comment]
Dara has been retired so I'm closing this as a wontfix.

We have launched a replacement called Shawburn: https://wordpress.com/theme/shawburn

**Comment by arunsathiya** [comment]
Thanks! I have asked the user to move to Shawburn.
