### ISSUE TITLE
Lovecraft: RTL mobile view

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#146]
## Steps to replicate

 view lovecraft at mobile widths on RTL language site

## Result

There is a large gap on the left of the page that is not present in the usual LTR view

<img width="378" alt="screen shot 2018-05-31 at 12 13 36 pm" src="https://user-images.githubusercontent.com/2031017/40758778-4fc3d6f4-64d2-11e8-9f29-09ecef6d0c76.png">

It appears that the mobile (or smaller than desktop) styles are not replicated for RTL:

<img width="313" alt="screen shot 2018-05-31 at 12 17 19 pm" src="https://user-images.githubusercontent.com/2031017/40758806-6cfd72e8-64d2-11e8-86f5-d27e80aeb673.png">

## Expected

The page width should behave the same for RTL and LTR

* User report: #1177938-zd
* Follow-up ticket: #1177938-zd
* User's site: https://orittest18.wordpress.com/

**Comment by crunnells** [comment]
Hey @kristarella I fixed the gap, thanks for the report. Can you follow-up with the customer and let them know it should be resolved (and to let us know if they see any other RTL oddness).
