### ISSUE TITLE
Maywood: Nav & Social menu are slightly off center

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#1465]
## Steps to replicate
Add a site with a tagline and a menu

## Result
Title and tagline are centered, and navigation and social links are centered after shifting 32 px to the left.

![Screen Shot 2019-10-01 at 2 51 08 PM](https://user-images.githubusercontent.com/3476361/65999949-af8e3480-e45b-11e9-810e-eeb2b1ba7ca6.png)

## Expected
I'd normally expect it to center with other centered elements, or align to the left or right instead.

![Screen Shot 2019-10-01 at 2 54 50 PM](https://user-images.githubusercontent.com/3476361/65999967-b61cac00-e45b-11e9-8ce4-ad4051b0ae69.png)

* User report: Just dogfooding. I'm not sure whether this is intentional, but it looked a bit off. Also I noticed the demo screenshot has the icons centered with the title.
![screenshot](https://user-images.githubusercontent.com/3476361/66000064-e8c6a480-e45b-11e9-85bf-5a4f329c1aec.png)

**Comment by iamtakashi** [comment]
Thanks for the report @supernovia. This should be fixed in #1469 And the theme has been deployed to WP.com.
