### ISSUE TITLE
Pique: Anchored pages - flickering effect when clicking on menu items

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/themes#147]
## Steps to replicate

- Browser Version: Google Chrome Version 66.0.3359.181 (Official Build) (64-bit) on Mac OS

- Create a WordPress.com site
- Add theme Pique
- Customize the theme to include an anchored menu under `Theme Options > Menu Settings> Add an anchor menu to the front page.`
- Set the Theme panels with any pages, as seen here under "Theme Options": https://cloudup.com/cqea_NNSp1n
- Publish changes done in the customizer
- Visit site in a browser
- Click on one of the panel menu items
- Once the page scrolls down to the given panel, click on the same menu item for the same panel. 

## Result

This makes the panel flicker momentarily for a short second, as seen here: https://monosnap.com/file/QC016oL3ebOwSnRIYBIEF1k778mgg6.

I am able to reproduce the issue with a test site on the premium plan here: https://testdp656544638.wordpress.com/

## Expected

I don't think the flickering should be expected, but rather, clicking on the menu item for the same panel you are viewing at the moment should not move the front page, since you're already viewing the given panel.

* User report: #1188024-zen
* User's site: https://timeaeon.blog

**Comment by jenlynnemc** [comment]
User replied that they are using Chrome and a Dell intel Core i5.

**Comment by laurelfulford** [comment]
I was also able to replicate on a Mac running Firefox.

**Comment by jeffikus** [comment]
@laurelfulford would you be able to give my latest commit a test for me?

**Comment by allancole** [comment]
@jeffikus I tested that last commit you made but I still see the flickering. I see it a bit less, but its still there sometimes.

**Comment by jeffikus** [comment]
Thanks @allancole Will look at this again.

**Comment by allancole** [comment]
Re-opening this one. I was testing this latest commit and the change accidentally got included in an unrelated PR that is now closed.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
