### ISSUE TITLE
Full Width images not full-width on mobile

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#1471]
## Steps to replicate

Using one of the themes listed below, create a page with an image block set to Full Width.
View on mobile-sized screen.

## Result

The image is not the full-width of the browser
<img width="426" alt="full-width-image_alves" style="border:1px solid black;" src="https://user-images.githubusercontent.com/2031017/66100070-d891ff00-e5ec-11e9-924e-0a0869014d8c.png">

## Expected

There should be no blank space at either sides

## Themes affected
I tested Twenty Nineteen and all its child themes, these were affected:
- Alves
- Mayland
- Balasana
- Shawburn
- Exford
- Rockfield
- Stratford
- Coutoire
- Morden
- Stow
- Hever
- Leven
- Brompton
- Redhill

## Possible fix
```
.entry-content>.alignfull {
  max-width: unset;
}
```

* Follow-up ticket: #2392868-zd
* Also reported:
https://a8c.slack.com/archives/C4WC5LYM6/p1569980303314700
https://a8c.slack.com/archives/C03TY6J1A/p1570066892469500

**Comment by iamtakashi** [comment]
@kristarella We deploy big updates for those themes, and I can confirm this is no longer an issue. Thanks!
