### ISSUE TITLE
Captions off-center in wide blocks

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#1472]
## Steps to replicate

Using one of the themes listed below, create a page with an image or video block set to Wide Width and with a caption.

## Result

The caption is slightly off-center (more obvious on mobile, but it's on desktop too)

<img width="427" alt="video-caption_shawburn" src="https://user-images.githubusercontent.com/2031017/66101009-99fe4380-e5f0-11e9-9b27-1f0e3a0539d6.png">

## Expected

It should either be left-aligned or properly centered, not part way.

## Potential fix
Caused by CSS (inheriting from `.entry-content>.alignwide`):
```
header *, main *, footer * {
    max-width: inherit;
}
```
Fixed by:
```
.entry-content>.alignwide figcaption {
  max-width: 100%;
}
```

**Comment by iamtakashi** [comment]
> Using one of the themes listed below,

@kristarella I don't see the list, but I assume those were Varia child themes. We've updated and deployed the fix.
