### ISSUE TITLE
[Balasana] Logo width is stretched/distorted

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/themes#1478]
## Steps to replicate

User visited their site today to notice that their site's logo is stretched too wide, as shown here:

<img width="1090" alt="Screen Shot 2019-10-03 at 8 25 44 AM" src="https://user-images.githubusercontent.com/39252765/66136209-5556b600-e5b8-11e9-960d-0828f0fe4e72.png">

The logo itself should look like this:

![cropped-artboard-1](https://user-images.githubusercontent.com/39252765/66136188-48d25d80-e5b8-11e9-8be1-0ff32e310604.png)

## Result

Logo is stretched too wide. 

## Expected

While the theme setup states that the logo height should be 96px, they claim that they did not make any changes and it had been working properly in the past. 

* User report: #15562770-hc
* Follow-up ticket: #2396681

**Comment by iamtakashi** [comment]
@jonnyruzek Thanks for the report. The fix has been deployed to WP.com
