### ISSUE TITLE
Sketch: Email and Print sharing buttons not working only on the latest Portfolio project

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#148]
## Steps to replicate
- Use an AT Site
- Use Sketch theme .org version (https://wordpress.org/themes/sketch/) and/or .com version (https://wordpress.com/theme/sketch) 
- Create a couple of Portfolio projects
- Enable Sharing buttons (Email, Print, Social Network ones)
- Open the latest published Portfolio project
- Click Print or Email sharing buttons
- _[Extra: not reported by the user, but involves other sharing buttons]_ Click any other sharing button

## Result vs. Expected

Clicking Print button results in a duplicate tab being opened. **Expected:** a print dialogue should open enabling me to see a print preview and print without redirecting me to a new browser tab.

Clicking Email button results in a duplicate tab being opened. **Expected:** a popup which let me conveniently share the post via email without redirecting me to a new browser tab.

**[Extra]**
If you click on any of the sharing buttons, including the Facebook and Google+ ones, you’re taken to a separate tab that lets you share the post on a social media service. **Expected:** see popups which let me conveniently share the post without redirecting you to a new browser tab.

## Notes
1. On projects where sharing buttons are working, the Javascript required to make them work is present. On projects with the issue, that Javascript is missing. Inserting the missing code in a project where it is missing only makes it partially work. The Print and Share buttons start to work but social media buttons don’t, so there must be another piece I’m missing.
2. Email share links that work end this way: /?share=email&amp;nb=1 Share links that don't work end this way: ?share=email
3. The issue was reported on Github: https://github.com/Automattic/wp-calypso/issues/24836
4. This issue was alread reported in the .org forums two years ago: https://wordpress.org/support/topic/sharing-buttons-not-working-properly-for-first-project-in-portfolio/ but was never resolved, since the user didn’t think it was important.

* User report: #1151733-zen
* User' site: http://www.bakerealestate.com/
* URL of the specific post where issue is present: As of May 31th, 2018 https://bakerealestate.com/portfolio/coming-soon-1199-sheldon-road-unit-77-1-bedroom-1-bath-condo/ If no issue there, look for the most recent Portfolio post.

**Comment by Robertght** [comment]
#1221761-zen 
I've also replicated this on a AT site. The very last project's More button won't work.

**Comment by Robertght** [comment]
@laurelfulford Sorry for the delayed reply. Yes - back then, I've used the Sketch theme, but I haven't seen any other themes with the same behavior so far.

**Comment by laurelfulford** [comment]
Thanks @Robertght -- sorry for my even more delayed reply!

I dug into this a bit -- I could recreate it on the latest portfolio project with Sketch on my AT test site, but not with Lodestar or Snaps (two other themes that support portfolios) on the same project. As described, the buttons worked fine on older projects with Sketch or other themes.

On projects that work, the following JS file is loaded:

`<script type='text/javascript' src='https://c0.wp.com/p/jetpack/6.8.1/_inc/build/sharedaddy/sharing.min.js'></script>`

... but that line is missing on the project where it doesn't work. 

Sketch doesn't seem to do anything special with the share buttons, like [trying to move them](https://jetpack.com/2013/06/10/moving-sharing-icons/), so I'm a bit lost why this is happening with this one theme but not others. 

I'll add the above to the Calypso issue, too, if it's more helpful there. It seems like it is theme specific but I'm a bit lost as to why.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
