### ISSUE TITLE
Cerauno Logo Size

### ISSUE THREAD

**Issue by joweber123** [Automattic/themes#1490]
## Steps to replicate

1.) Choose theme Cerauno
2.) Set any size image as the site's logo in the Customizer.
3.) Preview the page and the logo size will be width:150px.

**Uploaded logo**
Size: 999px by 299px
![Screen Shot 2019-10-04 at 13 43 19](https://user-images.githubusercontent.com/24914028/66181750-f7f06100-e6ac-11e9-8180-dd86c4cfaec5.png)

## Result

**How Image Displays on Site**
![logo-test-1](https://user-images.githubusercontent.com/24914028/66181596-6254d180-e6ac-11e9-880d-96a39dcf13a4.png)

**Image Source Code**
![logo-test-2](https://user-images.githubusercontent.com/24914028/66181663-8dd7bc00-e6ac-11e9-8cc1-db13a27531d2.png)

`<img src="https://genericsamplesite.files.wordpress.com/2019/10/logo_black_box.jpg?w=150" class="site-logo attachment-thumbnail" alt="" data-size="thumbnail" itemprop="logo" srcset="https://genericsamplesite.files.wordpress.com/2019/10/logo_black_box.jpg?w=150 150w, https://genericsamplesite.files.wordpress.com/2019/10/logo_black_box.jpg?w=300 300w" sizes="(max-width: 150px) 100vw, 150px" data-attachment-id="1405" data-permalink="https://genericsamplesite.wordpress.com/logo_black_box/" data-orig-file="https://genericsamplesite.files.wordpress.com/2019/10/logo_black_box.jpg" data-orig-size="999,299" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="logo_black_box" data-image-description="" data-medium-file="https://genericsamplesite.files.wordpress.com/2019/10/logo_black_box.jpg?w=300" data-large-file="https://genericsamplesite.files.wordpress.com/2019/10/logo_black_box.jpg?w=900" width="150" height="45">`

## Expected

I expected that the image's size would be larger than 150px wide.  The theme guide asks to upload an image at a maximum of 1000px by 300px so I assumed the image's max width would be set at 1000px and not 150px. 

* User report: #8356786-hc
* Follow-up ticket: #2398128-zd

**Comment by joweber123** [comment]
This seems to be occuring on multiple themes.  I have so far seen this occurring on the following themes to dates.


- Cerauno
- Hive
- Sela
- Big Brother
- Prosperity
- Onigiri

**Comment by nagpai** [comment]
User report: #15716944-hc
Theme: Toujors

**Comment by grvrulz** [comment]
User report: 15713603-hc
Theme: Big Brother

**Comment by rinazrina** [comment]
Another reports: 
#6232705-hc - Theme: Sela

#11715130-hc - Theme: Canard

**Comment by liviopv** [comment]
Same behavior reported for logo image on #2397656-zen 
Site: https://escolalinguaspn.com/
Theme: Restaurant

**Comment by sarahcada** [comment]
Same behavior reported at #15713933-hc for Sela
Follow-up ticket: #2398236-zen

**Comment by simranjeetkaur10** [comment]
Another report: #15718574-hc for Atlas
Follow-up ticket: #2398621-zen

**Comment by nerdysandy** [comment]
Reported on 9916035-hc
Follow-up: 2398711-zen
Theme: Dicot

**Comment by simison** [comment]
being investigated at p1570186246117200-slack-explorers

**Comment by scruffian** [comment]
I reverted the cause of this, so it should now be fixed.

**Comment by creativecoder** [comment]
I've deployed another update related to logos. It should not affect anything about the size or markup of the logo. Please let me know if you see any problems. (D33755-code)
