### ISSUE TITLE
Hever: Theme won't allow changing preview images on social

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#1502]
## Steps to replicate

SUMMARY:
When you preview **https://buryrelics.com** in Twitter card validator (https://cards-dev.twitter.com/validator)
It shows a thumbnail of an image which can't seem to be changed when using the Hever theme but you can with a default theme.

INVESTIGATION SO FAR:
* This image which appears is the site's old logo - https://cld.wthms.co/zMmEMH
* It seems to be determined by what is set in the og:image in the page code.
* Facebook is also doing the same
* It looks like Twitter and FB are picking up the featured image of the home page.
* However, there is no option to change the featured image when using the theme.
* Tested this on a seperate site
* By changing to twentytwelve the featured image option reappears and I can change the image which appears on Twitter. When switching back to Hever the changed image remains. In other words the only way to change the thumbnail is by switching to a default theme and switching back again

## Expected
There to be a featured image option on the home page and the ability to change the image

* User report: 15708104-zen
* Follow-up ticket: 2404463-zen

**Comment by gracie** [comment]
Looks like this issue impacts Gutenthemes in general [(ref, slack Convo here)](p1570488195294200-slack-C029FM1EH). 

User report: 15787096-hc
Follow-up ticket: 2406175-zen

**Comment by eduardozulian** [comment]
Also being discussed on #1461

**Comment by MaggieCabrera** [comment]
This should have been fixed by https://github.com/Automattic/themes/pull/1609. Needs testing.

**Comment by jeffikus** [comment]
I can test this first thing tomorrow.

**Comment by jeffikus** [comment]
Tested, and works.
