### ISSUE TITLE
Orvis: Portfolio not moving VideoPress videos to the right

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#1503]
## Steps to replicate

1. Create a new portfolio item
2. Add a Video Block and some text to its content
3. Publish it

## Result

The video and text are displayed on the left column:

![Screen Shot 2019-10-08 at 15 14 32](https://user-images.githubusercontent.com/3696121/66429802-6b141300-e9de-11e9-9ea9-efb9b3161fc9.png)

## Expected

As per the theme description and how it behaves with YouTube videos:

> Orvis will extract your images, videos or galleries from the content and will display these at full width on larger screens on the single portfolio pages. 

I expected the VideoPress video to be displayed on the right column

* User report: 2407054-zen

I was able to replicate on a test site with the Premium plan.

Chrome Version 77.0.3865.90 (Official Build) (64-bit)
macOS Catalina 10.15 (19A583)

**Comment by automattic-ian** [comment]
new report in #16376790-hc

**Comment by eduardozulian** [comment]
As a note, this was originally reported on Trac#4625  a couple of years ago.

**Comment by adelineyaw** [comment]
Another report to add via #20985560-hc

**Comment by danieldudzic** [comment]
Fixed in r56049
