### ISSUE TITLE
Rockfield: long username overlaps comments

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1505]
## Steps to replicate

Comment on a post using an account with a long username (18+ characters) or display name without spaces

## Result

The username is not broken off/hyphenated when it reaches the edge of the comment meta area, and as a result extends into and overlaps the comment content.

<img width="829" alt="More_block_–_Shift_to_the_left" src="https://user-images.githubusercontent.com/11873759/66453506-db657780-ea64-11e9-8327-55f22739ee86.png">

## Expected

For the username to be hyphenated so it splits across multiple lines.

* User report: https://en.forums.wordpress.com/topic/getting-the-hang-of-rockfield-theme/page/2/#post-3377811

**Comment by sptutusukanta** [comment]
Hello, I think I can fix this. :)
