### ISSUE TITLE
Stratford: mobile menu is partly covered on small screens

### ISSUE THREAD

**Issue by caimin-j** [Automattic/themes#1508]
## Steps to replicate

On smaller screens, the *Menu* is partly covered by the div below it:

<img width="307" alt="Screenshot 2019-10-09 at 11 41 56" src="https://user-images.githubusercontent.com/37620825/66476144-c6044380-ea8c-11e9-8061-128b7d97cb13.png">

Checked with Chrome 77 on a Mac and Chrome 77 on an iPhone. I'm just using the out-of-the-box theme and menu settings, nothing fancy.

* User report: [#2409474-zd](https://woothemes.zendesk.com/agent/tickets/2409474)

I sent the user this quick CSS fix:

`.main-navigation {
    height: 30px;
}`

**Comment by iamtakashi** [comment]
I believe this issue should be resolved in #1544. In my local install, I can't replicate the issue.

**Comment by caimin-j** [comment]
Looks fixed to me :) The issue is resolved on my test site; I'll close this.
