### ISSUE TITLE
Ixion widget dropdown text issue

### ISSUE THREAD

**Issue by detlefholtz** [Automattic/themes#1513]
## Steps to replicate

Add a category or archive widget to the sidebar area. Go to My Site > Design > Customize > Widgets > Sidebar > Category or Archive. Make sure the widget is set to show as a dropdown.

Next, make the theme's primary color #9c273e. Go to My Site > Design > Customize > Colors and Backgrounds > Choose your own color: #9c273e. Any color within this range will also do.

## Result

The widget's dropdown text is not showing up as normal. It will not show up unless clicked on or hovered over. 
![image](https://user-images.githubusercontent.com/30025667/66690415-6dcc6d80-ec55-11e9-98be-29708a010240.png)

If the theme's color is changed to something drastically different, however, the text will work.

## Expected

Text should be appearing in the dropdown. 

* User report: #12299574-hc
* Follow-up ticket: #2415800-zd

**Comment by danieldudzic** [comment]
The fix is now live (r54683).
