### ISSUE TITLE
Scratchpad: Password-protected posts showing post content on Blog page

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#152]
## Steps to replicate

1. Create a post and assign a featured image, or create a post, add an image gallery, and assign post the Gallery post format
2. Password-protect the post
3. View the front/blog page of the site

## Result

The featured image or the image gallery was visible from the front page above the post title. Clicking through to the single post view, no images are shown unless a password is entered.

With featured image:
![posts_page_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/41047173-41fba842-69ac-11e8-8ec8-f3cd83e27ff4.png)

With image gallery:
![posts_page_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/41047100-15a89d0e-69ac-11e8-8cf2-5b0529149b28.png)
Note no password entry field is even visible.

Image format is also broken:
![posts_page_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/41047140-2dbc7424-69ac-11e8-928c-18011a4e5f79.png)
That's the password entry field within the photo frame.

## Expected

For all posts to show as protected on the front page, displaying only a password entry field, and no content at all from the posts. For example (standard post without featured image)

![posts_page_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/41047204-4d94744a-69ac-11e8-8b1f-9ff21b6b32e4.png)

* User report: None - discovered while trying out the theme for a personal site

**Comment by KokkieH** [comment]
Looks like this might affect more than one theme - I'm observing similar behaviour in Nucleare as well.

**Comment by laurelfulford** [comment]
> Looks like this might affect more than one theme - I'm observing similar behaviour in Nucleare as well.

It depends how themes are built - in Scratchpad's case, the problem areas look like cases where a post doesn't use the standard `the_content()` (which that theme does for a few different post formats). Themes that do something similar without checking if a post is password-protected could have similar issues.

@KokkieH If you run into any other themes that do this, can you please file them as separate issues? Thanks!

**Comment by laurelfulford** [comment]
This has been fixed in r49003-wpcom-themes.

**Comment by KokkieH** [comment]
>  If you run into any other themes that do this, can you please file them as separate issues? Thanks!

Will do. Thanks, @laurelfulford !

**Comment by laurelfulford** [comment]
Thanks @KokkieH!
