### ISSUE TITLE
Stratford: Navigation bar sits on top of the site content

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#1529]
## Steps to replicate

1. Make sure to have a logo image.
2. Use the demo content on a home page.

## Result

The content gets under the navigation menu:

https://monosnap.com/file/71qdWVZMUP1bSo6eSE2sODGlMh0c5T

I used this code to work around it:

```
body.wp-custom-logo .site-content {
    padding-top: 8.75em;
}

@media only screen and (max-width: 559px) {
body.wp-custom-logo.page.hide-homepage-title .site-content, body.wp-custom-logo.page .site-content {
    padding-top: 8em;
 }
}
```

* User report: #2435687-zen

**Comment by brezocordero** [comment]
Another report here #2440357-zen

**Comment by rykovmedia** [comment]
There is still a problem (even with the above code). When you create an HTML Anchor, when you click for example on a word at the top of the page to jump to the anchor somewhere below, visually it jumps to the block that comes AFTER the block that is marked with this anchor. (Header basically completely covers the block with HTML Anchor)
