### ISSUE TITLE
Cubic: GDPR banner isn't fixed to bottom of viewport

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#153]
## Steps to replicate
Enable Cubic on a free site or other site that has a GDPR banner

## Result
Banner appears below the fold, where it may not be seen at all.  It also appears weirdly in the widget area. :/

## Expected
In most themes, the banner appears at the bottom of the viewport, where it's obvious and easy to see.

* User report: [this forum thread](https://en.forums.wordpress.com/topic/cookie-banner-is-not-visible-without-scrolling-down/)
* Follow-up ticket: (same thread)
* User's site: https://yumenosekaiorg.wordpress.com/

**Comment by KokkieH** [comment]
Another report [in the forums](https://en.forums.wordpress.com/topic/cubic-theme-bugs)

They reported another issue which I suspect might be related: on a mobile device, if you expand the site menu, the banner floats over the menu, obscuring several menu links:

![screenshot_20180611-122712](https://user-images.githubusercontent.com/11873759/41226860-100fa106-6d73-11e8-8487-68c3d38e0213.png)

Also note the banner appears to be wider than the viewport - I see the same on a desktop screen.

**Comment by laurelfulford** [comment]
This issue has been fixed in r48999-wpcom-themes (in Cubic's parent theme, Boardwalk). 

I've added comments to the two threads linked above, updating the status of the issue.

**Comment by KokkieH** [comment]
Thank you!
