### ISSUE TITLE
Baskerville 2: RTL Author avatar and title overlapped

### ISSUE THREAD

**Issue by edwinho89** [Automattic/themes#1530]
## Steps to replicate

When set site to RTL on Baskerville 2 theme, the author avatar and title overlapped each other.

## Result

![image link 2](https://cldup.com/Sn1TOtxev7.png)
image link: https://cloudup.com/c0w79E4xpkh

## Workaround

Apply the following CSS to provide margin before author avatar.

```
.wf-active .entry-author .author-title {
    margin-right: 50px;
}
```

* User report: #2436181-zen

**Comment by danieldudzic** [comment]
The fix is live now (r54691)
