### ISSUE TITLE
Libre 2: Menu bar issue

### ISSUE THREAD

**Issue by tagvverk** [Automattic/themes#154]
## Steps to replicate
![screen shot 2018-06-01 at 3 54 08 pm](https://user-images.githubusercontent.com/40017981/41081840-256af216-69e1-11e8-818e-08fb78b290c5.png)
![screen shot 2018-06-01 at 3 54 34 pm](https://user-images.githubusercontent.com/40017981/41081841-25851f06-69e1-11e8-9a5f-56be5f8af43a.png)

Hello,

We have been experiencing trouble with our menu bar on our site in the latest version of Chrome, using theme Libre 2. As you can see from the Chrome screenshot, the Pages menu bar is not locked to the top of the window, and there is a gap that obstructs text and makes our content difficult to read/is distracting/is not how it has been for four years, and is not how it is depicted to appear in the preview. The Safari screenshot shows how it has always been and how we would like it to look.

Here is what I'm running on with Chrome:
Web Browser: Chrome 66.0.3359.181  
Operating System: Mac OSX 10.9 Mavericks

While everyone I have spoken to with Wordpress/Automattic support claims that they do not have an issue with this, I have multiple other people who have confirmed that this is also how the page appears in Chrome. It looks like a glitch. 

## Result

The desired result would be that it is fixed and returned to the way it was before. Please let us know if we can do anything else to help resolve this, or if you need any more information, please let us know.

## Expected

[What you expected to happen.]

* Follow-up ticket: #1201151-zen
* User's site: [tagvverk.info]

**Comment by laurelfulford** [comment]
Thanks for the report, @tagvverk! 

I've tested with Chrome 71.0.3578.98 in Mac OSX 10.14, both logged in and not, and I can't recreate this issue, but I could be missing some condition that's needed! 

![image](https://user-images.githubusercontent.com/177561/50491064-37bf4500-09c5-11e9-9847-f9851f113f84.png)

The gap looks like it's roughly the size of the admin bar that appears when logged in -- could you please confirm if being logged in to WordPress.com makes a difference when recreating this? 

It also looks like the site is being loaded in a `frame`, which can mess up some visual things (for example, if you visit the site on a mobile device, it doesn't use the theme's mobile styles, it still looks like it does on desktop). 

When you load https://tvverk.wordpress.com directly, can you still recreate the issue?

**Comment by davidakennedy** [comment]
I'm going to close this as we can't recreate the issue. We can always come back to it, if need be.
