### ISSUE TITLE
Rockfield: Broken image URLs for homepage

### ISSUE THREAD

**Issue by samiff** [Automattic/themes#1540]
## Steps to replicate

1. Activate the Rockfield theme on a WordPress.com site: https://wordpress.com/theme/rockfield

## Result

The homepage images contain broken image URLs for the cover blocks:

Activated site theme: `https://rockfielddemo.files.wordpress.com/2019/08/appetizers-chef-cuisine-1267320-1.jpg`

Demo site theme working URL: `https://rockfielddemo.files.wordpress.com/2019/08/appetizers-chef-cuisine-1267320-1-1.jpg`

## Context

#user-report
13958384-hc

**Comment by danieldudzic** [comment]
The Headstart file seems to have the correct url:
`\"url\":\"https:\/\/rockfielddemo.files.wordpress.com\/2019\/08\/appetizers-chef-cuisine-1267320-1-1.jpg\",`

I'm checking now to see if there's some kind of caching going on.

**Comment by danieldudzic** [comment]
@samiff I have just created a new test site and the images seem to be displaying fine for me: https://rockfieldsburgerstestestest.wordpress.com/

Can you please provide more details regarding how the site was created/theme activated?

**Comment by iamtakashi** [comment]
This has been fixed in #1537, and I can confirm the image on the homepage appears correctly when I switch to Rockfield.

**Comment by iamtakashi** [comment]
Noting that you'd need to trash the homepage with broken images once and switch back to Rockfield to get the homepage with correct image paths.

**Comment by samiff** [comment]
@iamtakashi Thanks, tested again from my end and looks good 👍
