### ISSUE TITLE
Apostrophe 2: Lazy Images Causes Duplicate Images on Home Page

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/themes#155]
Chrome Browser version Version 66.0.3359.181

When `Automatically use first image in post` and `Display on blog and archives` are active in **Content Options**, Jetpack's Lazy Images module causes duplicate images to appear on the home page for posts with no selected Featured Image.

I found this while doing a guided transfer for a user. I've disabled **Lazy Images** on that site for now and not mentioned it to them. All is well on the user's site.

I am able to replicate this on my test site. 

## Steps to replicate

1. Open the Customizer and go to Content Options.
2. Select both **Display on blog and archives** and **Automatically use first image in post**. Publish those changes.
3. Go to Jetpack → Settings → Discussion.
4. Activate **Lazy load images**.
5. Create a post with images in the body but no featured image selected.
6. Observe the duplicate images on the home page. 

![annotation on 2018-5-4](https://user-images.githubusercontent.com/22805865/41122820-c5774924-6a6a-11e8-9624-fde134fde435.png)

From Inspect Element:

`<img src="https://i2.wp.com/tracyspress.net/wp-content/uploads/2018/04/ast3.jpg?zoom=2&amp;resize=224%2C224&amp;crop=1" title="Galleries in Email" class="attachment-post-thumbnail wp-post-image jetpack-lazy-image--handled" data-lazy-loaded="1" width="224" height="224" srcset="https://i2.wp.com/tracyspress.net/wp-content/uploads/2018/04/ast3.jpg?zoom=2&amp;resize=224%2C224&amp;crop=1" src-orig="https://i2.wp.com/tracyspress.net/wp-content/uploads/2018/04/ast3.jpg?resize=450%2C450&amp;crop=1" scale="2">`

`<img src="https://i2.wp.com/tracyspress.net/wp-content/uploads/2018/04/ast3.jpg?zoom=2&amp;resize=224%2C224&amp;crop=1" title="Galleries in Email" class="attachment-post-thumbnail wp-post-image" width="224" height="224" srcset="https://i2.wp.com/tracyspress.net/wp-content/uploads/2018/04/ast3.jpg?zoom=2&amp;resize=224%2C224&amp;crop=1" src-orig="https://i2.wp.com/tracyspress.net/wp-content/uploads/2018/04/ast3.jpg?resize=450%2C450&amp;crop=1" scale="2">
`
## Result

Duplicate images appear for posts with no featured image. 

## Expected

Only one image would appear for each post. 

* Follow-up ticket: No need to follow up here. 
* User's site: https://tracyspress.net/ (This is my test site. I've left the theme and Lazy Images in place for now. )

**Comment by SiobhyB** [comment]
We've had another report of this issue in 1576490-z and I can confirm I was able to replicate by following the steps Tracy laid out.

**Comment by laurelfulford** [comment]
I can recreate this on my AT test site as well.

**Comment by edequalsawesome** [comment]
Also reported in #2099736-hc, disabling Lazy Load in Jetpack resolved the issue

**Comment by tbradsha** [comment]
11534469-hc

**Comment by ktyfuller604** [comment]
#2136973-zen

Turning off lazy load resolved the issue.

**Comment by juliasydnor** [comment]
Another report in 2192057-zen.

**Comment by otpidusprime** [comment]
Also reported at 2207999-zen

**Comment by eduardozulian** [comment]
This also happens if you set up a Testimonials page. So I believe it's featured image-related.

**Comment by galakhyati** [comment]
Another one reported at #2795391-zen

**Comment by sophiegyo** [comment]
I had another instance of this: 23133698-hc

I used a CSS workaround:

```
/*Hide duplicated featured image on front page 23133698-hc sy*/
article .wp-post-image:last-child {
display: none;
}
```

**Comment by nagpai** [comment]
#25094225-hc

Gave the CSS workaround and suggested using featured images for future, to make sure the site is ready for future themes.

**Comment by mdrockwell** [comment]
#24589384-hc

Suggested they disable lazy load and that did the trick.

**Comment by rinazrina** [comment]
Another report: #3459502-zen

**Comment by eduardozulian** [comment]
Another report in 25349441-hc

**Comment by mdrockwell** [comment]
Another: 26114907-hc

**Comment by AtrumGeost** [comment]
Got a report here: 26651887-hc

**Comment by xpurichan** [comment]
30343723-hc
& 
23138678-hc

**Comment by jackiejade** [comment]
32283363-hc

**Comment by ClassicRKR27** [comment]
Another report here: 4644512-zd-woothemes

**Comment by ccwalburn** [comment]
Another report here: 34996016-hc
I didn't see this bug while chatting so I used a CSS workaround:

```
.home .entry-thumbnail img:first-child {
    display: none;
}
```

**Comment by Robertght** [comment]
I can confirm this is still an issue.

**Comment by eduardozulian** [comment]
@Automattic/dotcom-pa-group, opening this again as the priority is still set as high. Would it make sense to lower the priority given it's one of our old themes?

**Comment by Robertght** [comment]
Apostrophe 2 is currently active on at least 263,488 sites.

I'm setting this to Normal for now. cc @jeffikus

**Comment by dcoleonline** [comment]
#5254229-zen I turned off Lazy Load as a workaround for them

**Comment by essleeung** [comment]
Another case here- 5373951-zd-woothemes
Disabled lazy loading.

**Comment by Jaccuse** [comment]
Another case in 35851604-hc, turning off lazy loading removed the duplicate images
