### ISSUE TITLE
Dyad 2: WooCommerce moves entry header above content

### ISSUE THREAD

**Issue by vparkhere** [Automattic/themes#156]
## Steps to replicate

1) Activate Dyad 2 on AT site.
2) Install WooCommerce, but do not activate plugin.
3) Open a post and make sure browser is wide enough to be on desktop, not mobile view.  Entry header content will be at the bottom left.
4) Activate WooCommerce.
5) Reload browser.

## Result
Entry header will have moved from left side on top of featured image to right side above content.
![screen shot 2018-06-06 at 18 15 37](https://user-images.githubusercontent.com/11635760/41132294-20147262-6a75-11e8-877b-417b27203917.png)
## Expected

I expected there to be no changes when activating WooCommerce on an AT site.
![screen shot 2018-06-06 at 18 14 55](https://user-images.githubusercontent.com/11635760/41132302-2ab164aa-6a75-11e8-8ace-d7ddbc9bf9a9.png)

* User report: #3998897-hc
* Follow-up ticket: #1207391-zen
* User's post: https://northend.org/2018/04/is-this-who-you-are/

**Comment by laurelfulford** [comment]
This has been fixed in r49008-wpcom-themes.

It will either be synced up to Business Plan sites today, or early next week -- I'll double-back and update this thread when it's live on the user's site, and they can be contacted.

**Comment by laurelfulford** [comment]
I've double-checked on my own test site, and these changes have been synced up.

@vparkhere could you please follow up with the user who reported this? It looks like the original ZD ticket has been closed so I can't leave a comment there. Thanks!

**Comment by vparkhere** [comment]
Thanks @laurelfulford! Followed up in #1270172-zen.
