### ISSUE TITLE
Stratford: Category Pages and Tag Pages missing Continue Reading link after post excerpts

### ISSUE THREAD

**Issue by lizswafford** [Automattic/themes#1576]
## Steps to replicate

- Activate the theme Stratford (or Maywood) on a simple site. 
- Add a menu button to a specific category or tag to create the Category Page or Tag Page.
- View the new Category or Tag Page on the published view of the site. 
- The link will be something like: https://myawesomesite.com/tag/excellent/

## Result

- When viewing the Category or Tag Page you will see the post excerpts. 
- However, there is no Read More or Continue Reading link to go to the full post. 
- This happens even though there is a Read More Block in each post.

## Expected

- Expect to see a Continue Reading link below the post excerpt as shown on the blog page assigned from the Customzier > Homepage Settings. 

## Screenshots
Tag Archive Page - https://d.pr/R7VgwX
Blog Page - https://cld.wthms.co/CRP9QC

* User report:  #2440638-zen
* Follow-up ticket:  #2440638-zen

@allancole

**Comment by allancole** [comment]
Thanks @lizswafford 

As you mentioned earlier this actually effects multiple Varia-based themes, so I’ll fix it in Varia so all the others can benefit from this fix.

**Comment by carladoria** [comment]
Thanks @allancole for working on this. I had this issue today with Redhill theme. Do you know when this fix will be updated?
