### ISSUE TITLE
Argent: Grid spacing breaks after infinite loader on narrower screens

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#158]
## Steps to replicate
- View the site at a screen sized between 769 and 1079px
- Look at a portfolio with several projects, enough that you'll need to scroll past an infinite loader.

## Result
Grid spacing collapses after so many projects
https://cloudup.com/cbdAki0OKy1

## Expected
Grid spacing should be maintained through all projects, but it breaks because the CSS uses nth-child instead of nth-of-type. The invisible infinite-loader span counts as a child, so the article spacing is lost going forward.

* User report: [#](https://en.forums.wordpress.com/topic/problem-with-template-argent-in-the-archive-page)
* Follow-up ticket: (same thread)
* User's site: https://anabelleblanc.wordpress.com/portfolio/

**Comment by laurelfulford** [comment]
Fixed in r49005-wpcom-themes; I've added a comment to the forum thread to let the user know!
