### ISSUE TITLE
Varia: text-align: center in aligncenter class

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1597]
@allancole What was the reason for the CSS class `aligncenter` to have `text-align: center`? 

I'm asking this because I've seen blocks having the class as the default such as Newspack Homepage Articles block, and I remember some Jetpack blocks used to have that too. 

I'm not too sure why those blocks have the class, but because of `text-align: center` in Varia, the text inside appears as centre-aligned on the front-end while it's left-aligned in the editor.

![localhost_wordpress_wp-admin_post php_post=2123 action=edit](https://user-images.githubusercontent.com/908665/67586892-97ec5800-f74a-11e9-9172-d8bb3376e6f0.png)

![localhost_wordpress__p=2123](https://user-images.githubusercontent.com/908665/67586908-a2a6ed00-f74a-11e9-9cd3-884980a77d9e.png)

Twenty Nineteen doesn't have it, and with auto side margins, it's probably not necessary. What do you think?

**Comment by allancole** [comment]
@iamtakashi Hmmm, I think this is an artifact from adapting to some of the changes that have happened in Gutenberg over time. Early on, you couldn’t always center text contained in a Block (like the Cover Block, for example), so centering the text with `.aligncenter` was there as an assumption on what a customer might be trying to do. 

Now that we can more explicitly set text-align rules for text in Blocks and nested Blocks, I’m pretty sure we can safely remove it, without causing a major regression. But it’s definitely worth testing with other Blocks to be sure.

**Comment by iamtakashi** [comment]
@allancole I saw widgets blocks are benefitting from the rule. The position of the bullets is strange though.

<img width="822" alt="Screenshot 2019-10-28 at 12 29 53" src="https://user-images.githubusercontent.com/908665/67678845-86d85c80-f97f-11e9-9b45-8bcec1018ef0.png">

Twenty Nineteen and Twenty Twenty don't have that rule in the class, and that makes me think what the expectation on this.

Should we keep it for now?

**Comment by allancole** [comment]
Hmmm, on second thought, I wonder if it’s worth keeping `.aligncenter` as a utility class so we can use it in templates. Sort of like what we have for `.margin-top-none`.

**Comment by iamtakashi** [comment]
> I wonder if it’s worth keeping .aligncenter as a utility class

Oh definitely. The question was whether we keep `text-align: center` in the class or not.

**Comment by allancole** [comment]
Oh, shoot—I wasn’t very clear in my last comment, @iamtakashi. I meant maybe we could add `.text-align-center { text-align: center; }` as a utility class so we can control text alignment without conflicting with `.aligncenter` or other _content_ alignment utility classes.

**Comment by iamtakashi** [comment]
ok, maybe? And are you suggesting to remove or keep the `text-align: center;` from `.aligncenter`?

Other alignment classes such as ` alignleft` or `alignright` don't alter text alignment, but I found the following rule from core, and this makes me think the class should also make the text inside to be centre-aligned. The position of the bullets is strange though. 

```
.block-editor-block-list__block[data-align=center] {
    text-align: center;
}
```

<img width="822" alt="Screenshot 2019-10-30 at 12 27 32" src="https://user-images.githubusercontent.com/908665/67858683-b028f200-fb11-11e9-8644-0481a99c8bd7.png">
