### ISSUE TITLE
Varia: Separator Block Dot style doesn't display the custom color

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#1602]
## Steps to replicate

1. Create a post/page
2. Add the separator block
3. Choose the `dot` style
4. Add color to it

## Result

I saw a grayish color. Here's my test with Mayland:

<img width="840" alt="Captura de Tela 2019-10-25 às 19 52 16" src="https://user-images.githubusercontent.com/1136160/67608974-06d4ab80-f761-11e9-9220-b5e1c1b453b5.png">

In Varia, it's coming from:

```
hr.wp-block-separator.is-style-dots:before {
	color: #DDDDDD;
	font-size: 1.728rem;
	letter-spacing: 0.83333rem;
	padding-left: 0.83333rem;
}
```

More info on the separator styles: https://github.com/WordPress/gutenberg/issues/16483

**Comment by eduardozulian** [comment]
In case we got reports, looks like this CSS should help for now:

```
hr.wp-block-separator.is-style-dots.has-text-color:before {
  color: currentColor;
}
```

**Comment by allancole** [comment]
I’ll work out a fix for this shortly :-)
