### ISSUE TITLE
Lovecraft: Invisible links in Calendar Widget

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#1603]
## Steps to replicate
- Use Lovecraft
- Add a calendar widget
- Ensure you've published posts this month, or select a month where posts are published.

## Result
- Links for recent posts are not marked in any way unless you happen to hover over them

## Expected
- Links in a calendar widget should be visible

* User report: https://en.forums.wordpress.com/topic/calendar-47/
* Follow-up ticket: same

**Comment by chiape** [comment]
Hey, seems that the widget and theme use the same color for links. I've just applied a custom css as a test

`.widget a {
    color: blue;
}`

Seems worked well! Hope that helps!

**Comment by danieldudzic** [comment]
I'd change the widget link color to `#ca2017` to match the post content link color.

Any objections, @jeffikus ?

**Comment by jeffikus** [comment]
@danieldudzic no objection from me - if it matches the theme I'm happy :)

**Comment by danieldudzic** [comment]
Hi @supernovia 

This has now been fixed and pushed live:

![lovecraftt](https://user-images.githubusercontent.com/905781/68062958-e6cb5c00-fd0d-11e9-8df8-e6ba2a3cab75.jpg)
