### ISSUE TITLE
Gazette: Featured Content Doesn't Appear in Category Listings

### ISSUE THREAD

**Issue by macmanx2** [Automattic/themes#1608]
## Steps to replicate

To reproduce the issue, mark a post as featured, then check its category archive. Once the post is marked as featured, it is removed from the category archive.

## Result

For example, both https://gracelynnlau.wordpress.com/2019/09/08/a-hong-kong-womans-attempt-to-learn-the-indigenous-and-colonial-history-of-kingston-katarohkwi-my-phd-research-started-me-before-i-start/ and https://gracelynnlau.wordpress.com/2019/09/25/decolonization-is-not-a-metaphor/ are featured, and they are also in the  https://gracelynnlau.wordpress.com/category/decolonizing-indigenizing-studies/ category.

But, they do not appear in the category listing, only non-featured posts do.

## Expected

I'd expect featured posts to still appear under their designated categories.

* User report: https://en.forums.wordpress.com/topic/gazette-theme-posts-tagged-as-featured-not-showing-under-categories/

**Comment by KokkieH** [comment]
I'm not sure this is a bug - I'm not able to replicate this on another site at all. But I also can't figure out what's causing it on this site.

**Comment by danieldudzic** [comment]
Hi @macmanx2 and @KokkieH,

There is a setting for this in the Customizer > Featured Content > Also display tagged posts outside the Featured Content area.

http://g.recordit.co/S7tEiuvDY9.gif

Please let me know if that helps!

**Comment by danieldudzic** [comment]
Sorry I didn't mean to close just yet.

Please confirm that the Customizer setting actually solves the issue.

**Comment by macmanx2** [comment]
Reply sent, thanks! :)
