### ISSUE TITLE
Radcliffe 2: Theme-specific validation errors from W3C validator

### ISSUE THREAD

**Issue by thabotswana** [Automattic/themes#161]
## Steps to replicate

The user found 11 validation errors with the W3C validator at w3.org for her Radcliffe 2 theme. I activated Radcliffe 2 on a test site and checked it

## Result

https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fthabostoreadmin.blog&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en

At least three of these look to be theme-specific errors:

Line 1782: 	.comments-title, .comment-reply-title
Value Error : letter-spacing only 0 can be a unit. You must put a unit after your number : 1

Line 2175:	.main-navigation > div	all is not a transition value : max-height all 0.425s ease-in-out

Line 2695:	.site-branding .custom-logo	Value Error : max-height Too many values or values are not recognized : auto

* User report: #1221098-zen
* User's site: https://artprints-moonfleet-gallery.com

**Comment by laurelfulford** [comment]
This has been fixed in r49010-wpcom-themes; I've also re-zipped the theme.

@thabotswana can you please follow up with the user? Thanks!

**Comment by thabotswana** [comment]
Thank you, Laurel! I just notified the user.
