### ISSUE TITLE
Hemingway Rewritten: "Follow Blog" Widget Button Text Too Dark

### ISSUE THREAD

**Issue by allykmyta** [Automattic/themes#1610]
## Steps to replicate
1. Customize > Add `Follow Blog` Widget
2. Navigate to Customize > Colors and Background > Palettes
3. Select any other palettes

## Result
Any other palette chosen gives dark text within the widget button which makes it hard to see/read:

![Screenshot](https://cld.wthms.co/8ClV91/jy1uMIVVD4+)
Original screenshot link: https://cld.wthms.co/8ClV91/jy1uMIVVD4

Select `Pick your own color` in Manual does not offer the ability to change the text color either.

## Expected
Expecting a white background with white text in the 'Follow Blog' widget button (only available if we select 'Default'):
![Screenshot](https://cld.wthms.co/ZYCw2K/LZyGt1hWWH+)
Original screenshot link: https://cld.wthms.co/ZYCw2K/LZyGt1hWWH

* User report: N/A
* Follow-up ticket: #2458541-zen

**Comment by danieldudzic** [comment]
Hi @allykmyta !

Hope you are doing well :)

I have now fixed the issue (Revision 54622) and deployed the patch, so it should be live.

![fix](https://user-images.githubusercontent.com/905781/67909501-c2417980-fb7f-11e9-9abb-2834a4bf9ec0.jpg)
