### ISSUE TITLE
MistyLook: Cookie banner not properly aligned when site set to RTL language

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#163]
## Steps to replicate

1) Activate theme on a free site
2) Go to My Site ->Settings ->General and select a RTL langauge, like Hebrew, as the site language.
3) View site

## Result
The text in the banner appear to be center-alinged.
![jacob_s_blog___free_markets_and_free_mind_weblog](https://user-images.githubusercontent.com/11873759/41506151-7ac94e58-7218-11e8-9f8a-55fb1e3d9402.png)

## Expected
For the text to be right-aligned, as it is when viewing the site with a different theme, e.g. TwentySixteen:
![jacob_s_blog_ _free_markets_and_free_mind_weblog](https://user-images.githubusercontent.com/11873759/41506165-bdbfca7a-7218-11e8-9cca-d1b618ff45ed.png)

* User report: https://en.forums.wordpress.com/topic/cookie-consent-in-foreign-languages-rtl-issue/
* User's site: https://jacobress.wordpress.com/

**Comment by lizkarkoski** [comment]
There's another report of the cookie banner sitting all the way to the bottom of the page rather than floating at the top where a visitor would see it: 

https://en.forums.wordpress.com/topic/problem-with-gdpr-cookie-banner/#add-note

**Comment by KokkieH** [comment]
The user in that thread has since switched away from the Misty Lake (not MistyLook), so it's no longer an issue for them.

**Comment by laurelfulford** [comment]
MistyLook has been retired since 2012 (!!). It looks like the Cookies Consent banner text is centred for both LTR and RTL languages -- but it doesn't affect the ability to dismiss it in either case. Because of that, and the theme's age, I'm going to close this as a 'wontfix'. 

I've followed up on the forum thread.
