### ISSUE TITLE
Dalston: Hover Effects of Image Overlay Not Working

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/themes#1636]
## Steps to replicate

The issue seems to occur also on the theme demo, no need to replicate. 

https://www.loom.com/share/496854235fb549e38f39f0cc32e44719

## Result

Featured images on the homepage have overlay/reveal features. Images displayed with the overlay without hovering them. 

https://www.loom.com/share/ace0c3faab7a452d8876e3c669f7c4f0

## Expected

Images suppose to display without the overlay/opacity. The overlay seems to be a part of the reveal effects. As you hover your mouse, the text titles would appear, and the image will have the  overlay. 

https://www.loom.com/share/f73a1e86e89543aaa9d923ca1b7f024e

* User report: HC-15899592
* Follow-up ticket: ZD-2462098

**Comment by allancole** [comment]
Should have this fixed shortly…

**Comment by allancole** [comment]
Fixed and deployed. 
See: https://dalstondemo.wordpress.com
