### ISSUE TITLE
Balasana: mobile menu shows below the logo instead of next to the logo

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#1637]
As per the theme demo mockup, the mobile menu should be in the top right:

![Image](https://theme.files.wordpress.com/2019/08/balasana-device-mock.png)

However, it now looks like this:

![image](https://user-images.githubusercontent.com/32492176/68055416-33834880-fcb6-11e9-947e-4d5c964b0e74.png)

I don't know if it is an intentional change or a regression.

Reported in #16356616-hc; the user was quite upset about this change.

**Comment by danieldudzic** [comment]
Hey @allancole,

This seems to be caused by the 1.2.0 update ( https://wpcom-themes.trac.automattic.com/changeset/54626/balasana )

**Comment by katiebethbrown** [comment]
Another user report in #16330388-hc

**Comment by allancole** [comment]
Got it. This looks like a regression from the recently added WooCommerce support. 
Should be a fairly quick fix. Will look into it today.
