### ISSUE TITLE
Orvis: Cookie banner still in front of content even after it's dismissed

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#164]
## Steps to replicate

1) View a free site that's not set to private using this theme
2) When the cookies and consent banner appears, dismiss it
3) Try clicking on the action bar or the WordPress.com attribution in the footer

## Result

The action bar cannot be clicked, nor can the footer attribution link, and if there is content on the screen that reaches to the bottom of the viewport, including the social menu in the footer, those items are also not clickable.

## Expected

For items in that area of the screen to be clickable.

It appears that the cookie banner is still there on the page, even if dismissed. In Safari I was even able to highlight the invisible cookie banner:

<img width="1015" alt="views_ _by_voyager006" src="https://user-images.githubusercontent.com/11873759/41537291-529b80ae-7308-11e8-89da-e1e988d62e94.png">

<img width="984" alt="views_ _by_voyager006-2" src="https://user-images.githubusercontent.com/11873759/41537295-552055d4-7308-11e8-8b54-cff58df3d7b6.png">

I'm able to replicate this on a test site, and it's happening across browsers. I'm not able to replicate this in other themes I checked, so it appears to be specific to this theme.

* User report: https://en.forums.wordpress.com/topic/cookie-banner-covers-elements-when-dismissed/
* User's site: https://voyager006.wordpress.com/

**Comment by KokkieH** [comment]
Just had another report of this in https://en.forums.wordpress.com/topic/cookies-privacy-block/

Theme: Sidekick

![__a_proud_and_active_member_of_philippine_wood_producers_association](https://user-images.githubusercontent.com/11873759/41835334-8050c870-7857-11e8-9b16-6e8e017ef27d.png)

Site: https://patecowebsite.wordpress.com/

cc @rclations in case this is something that should be fixed on the widget/banner itself, rather than the theme, as it appears more than one theme is affected.

**Comment by rclations** [comment]
The issue here is that the widget container remains after the banner is dismissed and the contents of the widget container are removed. So if you're using a theme that adds styling to the widget container, that would remain after the widget is dismissed.

One way around this would be to move the widget to a sidebar that doesn't style the widget container (if one is available).

The cookie banner really needs to be rewritten into a setting vs. a widget, (which would also fix this issue), but I don't think that work has been planned or assigned to any team.

**Comment by laurelfulford** [comment]
Orvis fixed in r48993-wpcom-themes.

**Comment by laurelfulford** [comment]
Sidekick fixed in r48994-wpcom-themes (by editing its parent theme, Superhero).

**Comment by KokkieH** [comment]
Thank you, @laurelfulford
