### ISSUE TITLE
Apostrophe 2: Can't delete the accordion block

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#1643]
## Steps to replicate

Add the accordion block (from the CoBlocks collection) to any page.
Publish and close the page.
Reopen the page, delete the accordion block, update and close the page.
Reopen the page, and the accordion block is still there.

(Whether there is content in the accordion block when you delete the block or not, same result.)

Tested in Chrome browser: 78.0.3904.70

(I took 2 screen recordings and neither saved for me - let me know if you'd like me to try again.)

## Result

The accordion block will not delete.

## Expected

That the accordion block would delete and remain gone.

* User report: #2468080-zd

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
