### ISSUE TITLE
Baskerville 2: Block editor figcaptions are unstyled

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#1648]
Image Captions using the block editor are not styled. 

## Steps to replicate

1. Create a post
2. Add an image block
3. Write a caption for the image

## Result

<img width="777" alt="Captura de Tela 2019-11-08 às 11 50 39" src="https://user-images.githubusercontent.com/1136160/68485407-02f35f80-021e-11ea-841e-88c921fac689.png">

## Expected

<img width="774" alt="Captura de Tela 2019-11-08 às 11 51 10" src="https://user-images.githubusercontent.com/1136160/68485454-1999b680-021e-11ea-8cad-94d202220e58.png">

We need to apply to `figcaption` the same style that is targeting captions on the classic editor:

```
.post-content .wp-caption-text,
.post-content .gallery-caption,
.widget-content .wp-caption-text,
.widget-content .gallery-caption {
	color: #999;
	font-size: .8em;
	font-weight: 700;
	padding-top: .5em;
	text-align: center;
}
```

For now, the workaround I'm using is:

```
/* Image Captions: center align */
.wp-block-image figcaption {
  color: #999;
  font-size: .8em;
  font-weight: 700;
  text-align: center;
}
```

## Similar reports

#403 and #767

***

Follow-up ticket: #2477678-zen

**Comment by ktyfuller604** [comment]
Reported here - #16928926-hc

**Comment by nagpai** [comment]
Reported here - #2523253-zen

**Comment by SiobhyB** [comment]
This was also reported by a user in both 2538900-zen and 17123224-hc

**Comment by kathrynwp** [comment]
Reported in 2551157-zen

**Comment by GeoJunkie** [comment]
Fixed upstream on r54868-wpcom-themes. (Baskerville-2)
