### ISSUE TITLE
Dara: Color Annotations

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#165]
**Steps to replicate**

1. Activate Dara.
2. Create post with link in it.
3. Go to Customize > Colors and Backgrounds and set background to another color such as #3a05a2 and publish.

**Result**

Links  will turn to #333, the same color as the surrounding non-linked text.

**Expected**

Links would retain a complimentary different color to differentiate them from surrounding text.

* User report: https://en.forums.wordpress.com/topic/links-227/#post-3128657
* User's site: https://westtblog.wordpress.com/category/westt-blog/ (can't see links in content with the purple background color).

Did not check to see if this is also the case in Sela, but it could be.

**Comment by thomasguillot** [comment]
I checked the site and they are using a palette that sets the link colour to #333. I wouldn't touch the colour annotation at this stage but to have the link more visible I will add an underline.

**Comment by thesacredpath** [comment]
Thank you @thomasguillot. I'll let the user know.
