### ISSUE TITLE
Redhill: Remove "Post Type" from Projects Archive title

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#1655]
![img](https://cld.wthms.co/7M3aoI+)

I think the custom post type archives shouldn't say "post type".

## Steps to replicate

View the archive page for the "projects" archive type

## Result

The text says: **Post Type Archives: Projects**

## Expected

It would be better to say **Archives: Projects**

Reported: 2485420-zd

**Comment by michaeldcain** [comment]
Fixed by #1658
