### ISSUE TITLE
Blask: Grey box remains after removing text from Site Title in Customizer

### ISSUE THREAD

**Issue by deancroyal** [Automattic/themes#166]
## Steps to replicate
1. Load Blask demo Customizer: https://blaskdemo.wordpress.com/wp-admin/customize.php
2. Click on Site Identity.
3. Remove the text from the Site Title field -- grey box remains (empty).
4. Click on Add Logo and apply any image from media library as logo image: http://cld.wthms.co/H6n2LV

## Result
End result should look something like this...

<img width="1440" alt="screen shot 2018-06-19 at 7 23 31 am" src="https://user-images.githubusercontent.com/13387217/41603403-b948e376-7391-11e8-80d0-83a7f1d34540.png">

## Expected
I expected the grey box to be completely removed if there was no text inside the Site Title field, but it remained.

* User report: [#hc-4288695](https://mc.a8c.com/support-stats/happychat/transcript.php?id=4288695)
* Follow-up ticket: [#1230425-zd](https://woothemes.zendesk.com/agent/tickets/1230425)
* User's site: [https://liliesinlove.blog/](https://liliesinlove.blog/)

**Comment by laurelfulford** [comment]
Fixed in r49004-wpcom-themes.

@deancroyal can you please follow up with the user who reported this? Thanks!
