### ISSUE TITLE
Radcliffe 2: Issues with instructions

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#1663]
## Steps to replicate

Check the theme's instructions on the showcase.

## Result

The "Make It Your Own" section seems broken, as follows:

![Radcliffe 2 Theme](https://user-images.githubusercontent.com/16104522/68762717-7964d880-05f5-11ea-9e8e-67018735ede1.png)

## Environment

Chrome 78.0.3904.97
OS X 10.13.6

**Comment by michaeldcain** [comment]
This is technically a Theme Showcase bug in Automattic/wp-calypso. The Showcase doesn't have styles for embedded galleries. I've switched the screenshots from a gallery to a table, which should fix it for this purpose (once the endpoint is re-indexed), but we should consider adding gallery support to the Showcase.
