### ISSUE TITLE
p2 Classic page and post editor do not load when using Block Editor

### ISSUE THREAD

**Issue by KristinaKay** [Automattic/themes#1667]
## Steps to replicate

- Create free site
- Activate p2 Classic Theme
- Open post or page in Editor

## Result

- Editor does not load. 
<img width="1828" alt="Screen Shot on 2019-11-15 at 09-06-13" src="https://user-images.githubusercontent.com/33169211/68957990-70584080-0788-11ea-8d5c-59a8c666dd06.png">

## Expected

Editor to load.

## Fixes (Temporary)

- Switching to Classic Editor in BRC allows the editor to load.
- Switching to newer theme allows Block Editor to load.
<img width="1772" alt="Screen Shot 2019-11-15 at 9 15 46 AM" src="https://user-images.githubusercontent.com/33169211/68958037-87972e00-0788-11ea-918f-b291683669c7.png">
* User report and follow

-up: [#2493815-zd

**Comment by cathymcbride** [comment]
retired theme. closing
