### ISSUE TITLE
Cubic: Intermittent background colour change on article tiles

### ISSUE THREAD

**Issue by aleone89** [Automattic/themes#1669]
## Steps to replicate

When visiting the homage of a site using Cubic, there'll be a random article where the top and bottom background colour will change to the same colour used in the customizer. 

This happens after a refresh of just by visiting a page - the articles changed are different each time. 

## Result

After a visit or refresh...

- https://cld.wthms.co/OZQiod 
- https://cld.wthms.co/w80FGb

## Expected

All colours to remain the same. 

* User report: hc-15575960
* Follow-up ticket: zen-2496959

**Comment by davipontesblog** [comment]
Please reply to the user when this is fixed. Closing the ticket here for now as there's no timeline for this fix. #2496959-zen

**Comment by danieldudzic** [comment]
@aleone89 I'm struggling to replicate this.

Can you perhaps share a screencast of this happening?

**Comment by aleone89** [comment]
It looks like the user has since switched themes.

I'm able to replicate on the theme demo, which makes wonder if there's something in the users content that could cause this. 

Can I gut check if it's a good idea to reach out to the user asking for an export of their content for testing purposes?
