### ISSUE TITLE
Varia: Inherited margins around cover block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1670]
@allancole Do you remember why we have these inherited margins?https://github.com/Automattic/themes/blob/master/varia/sass/blocks/cover/_style.scss#L6

This adds an extra side margin to the cover block when it's inserted in a column cell that has a side margin. Can we remove it?

<img width="1508" alt="Screenshot 2019-11-18 at 14 35 27" src="https://user-images.githubusercontent.com/908665/69061492-1c13c180-0a11-11ea-8682-1de43db96c6d.png">

**Comment by allancole** [comment]
I don’t remember _why_ thats there, but I do remember something breaking when it’s removed. I think it had something to do with nesting Cover Blocks inside `.alignwide` or `.alignfull` blocks, but not 100% sure. 

I’d say we can probably replace it with something like this so it doesn’t conflict with the column margins. 

```
.wp-block-cover,
.wp-block-cover-image {
  margin-top: inherit;
  margin-bottom: inherit;
}
```

**Comment by iamtakashi** [comment]
OK, that sounds like a good plan 👍

**Comment by allancole** [comment]
Yup, I’ll give it a try tomorrow and if it works, I’ll spin up a PR.
