### ISSUE TITLE
Most themes: Gutenberg: Image caption styling not applied with Block Editor

### ISSUE THREAD

**Issue by formosattic** [Automattic/themes#1673]
Edit by @arunsathiya: As discussed here p1574159858171000-slack-triage, I am moving the issue from Calypso repository to themes repository. This issue is reproducible with a lot of themes on https://wordpress.com/themes. @thehenrybyrd has a particular helpful comment https://github.com/Automattic/themes/issues/1673#issuecomment-555453912

---

#### Steps to reproduce
Create two posts with an image with caption, one post with the Block Editor, and the other with the Classic Editor.

#### What I expected
Caption should display the same styling from the theme, regardless of the editor used.

#### What happened instead

Tested with different themes (Twenty Nineteen, Karuna, Libretto).

The Classic Editor, will apply the theme styling:

<img width="847" alt="screen shot 2019-01-02 at 12 31 11" src="https://user-images.githubusercontent.com/15944096/50580514-553f5380-0e8a-11e9-9a80-953caf99ed69.png">

The Block Editor applies a different styling:

<img width="836" alt="screen shot 2019-01-02 at 12 31 44" src="https://user-images.githubusercontent.com/15944096/50580517-61c3ac00-0e8a-11e9-9909-0ed00c423b87.png">

#### Context / Source

Ticket: 1678324-zen

**Comment by bsanevans** [comment]
Another report: 23976514-hc
As user is on Personal plan, CSS workaround won't work.

**Comment by tbradsha** [comment]
3653977-zen, using Hemingway Rewritten.

Provided a simple CSS workaround:
```
figure figcaption {
  text-align: center;
}
```

**Comment by kisabelle** [comment]
I'm noticing today that on the Gutenberg editor the Gallery block caption appears to receive completely different styles than on the front end.

**Gutenberg editor:**

![Screen Shot 2021-03-01 at 9 27 56 AM](https://user-images.githubusercontent.com/1544652/109534731-7e5ecd00-7a70-11eb-93b3-84ed42ea7928.png)

![Screen Shot 2021-03-01 at 9 27 02 AM](https://user-images.githubusercontent.com/1544652/109534556-4f485b80-7a70-11eb-97df-efeb10cd7a67.png)

**Front-end styles:**

![Screen Shot 2021-03-01 at 9 28 22 AM](https://user-images.githubusercontent.com/1544652/109534748-8585db00-7a70-11eb-9b1b-f80a9bcb55b3.png)

![Screen Shot 2021-03-01 at 9 26 51 AM](https://user-images.githubusercontent.com/1544652/109534572-54a5a600-7a70-11eb-9b24-ce44af645be3.png)


Some consistency here would be much appreciated.

**Comment by KokkieH** [comment]
Another report for Hemingway Rewritten in https://wordpress.com/forums/topic/image-caption-not-aligning-center/?view=all

**Comment by Robertght** [comment]
I'm no longer able to replicate this issue with the themes mentioned as we have styling options for the captions:

![image](https://user-images.githubusercontent.com/6737345/163549073-27be155d-9fba-4419-8415-40f464a109b1.png)


![image](https://user-images.githubusercontent.com/6737345/163549106-baa2eff1-1578-4eef-861c-4e78e1a9e338.png)

I'm going to close this one for now, but please open it in case it needs more work.
