### ISSUE TITLE
Morden: Missing Title on Static Front Page

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#1675]
## Steps to replicate

1. Create a new page and set as the site's static front page
2. Activate the Morden theme

## Result

On a WordPress.com Business site, the site's title shows up on the front page, while on a Free site it doesn't.

Business:

![BizFrontPage](https://user-images.githubusercontent.com/16104522/69365248-ab6bdf80-0c72-11ea-98ba-26cba45fc31d.png)

Free:

![FreeFrontPage](https://user-images.githubusercontent.com/16104522/69365253-ae66d000-0c72-11ea-99c7-2d065fea67fe.png)

## Expected

To have the same behavior on sites with both plans.

**Comment by michaeldcain** [comment]
@carinapilar: does the business site not respect the "Hide homepage title" option in the Customizer?

**Comment by michaeldcain** [comment]
![homepage-title](https://user-images.githubusercontent.com/942359/71525958-42473f80-28a2-11ea-989c-2de098d11c9b.gif)

This works for me. Closing, but feel free to re-open if needed.

**Comment by carinapilar** [comment]
Ah, I see! It seems that the difference is actually that on a Free site the Hide option is marked by default, while on a Biz site it's not. It worked for me now! Thanks for looking @michaeldcain!
