### ISSUE TITLE
Lodestar: Remove white background for images added via image block

### ISSUE THREAD

**Issue by davoraltman** [Automattic/themes#1685]
## Steps to replicate

Add an image to the image block and it will have white background, even though the image is transparent.

![Screen Shot 2019-11-28 at 18 55 46](https://user-images.githubusercontent.com/10340370/69825785-babdd080-1210-11ea-8ed9-46649792bce2.png)

This doesn't happen when an image is added via URL.

But it happens again if the image block is linked to another URL. The workaround is to either add custom CSS:

.entry-content a img {
background: none;
box-shadow: none;
}

or add the link to the caption instead.

But overall, I'm not sure why a white background is added by default.

## Expected

Expected not to have a white background on transparent images added via image block.

* User report: 16976068-hc

cc @catkit

**Comment by nielslange** [comment]
@davoraltman I created the PR https://github.com/Automattic/themes/pull/1686 which fixed this issue. Feel free to the test that PR. 😀
