### ISSUE TITLE
Lodestar: Add Video header support

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#17]
Originally reported in 4502-wpcom-themes:

A user requested we add video header support to Lodestar. 

I think it's worth investigating, and given the theme's similarities under the hood to Twenty Seventeen (being the base for that theme) it seems like it'd be relatively straightforward.

* User report: 298600-hc
* Follow-up ticket: 3154396-t

**Comment by torres126** [comment]
Another user with the Lodestar theme hoping to use a video instead of an image in this thread too: https://en.forums.wordpress.com/topic/video-instead-of-image

**Comment by meegzy** [comment]
I would also like this feature with the Lodestar theme.

**Comment by davidakennedy** [comment]
I'm closing this issue because:

* We're mainly focused on new Gutenberg-enhanced themes and high-priority bug fixes in older themes. This enhancement doesn't fit that.
