### ISSUE TITLE
Maywood: Paragraph text can't be both bold and italicized

### ISSUE THREAD

**Issue by katiebethbrown** [Automattic/themes#1700]
## Steps to replicate

1. Highlight some text in a paragraph block on the Maywood theme.
2. Click the Bold option in the toolbar (text turns bold).
3. Click the Italics option in the toolbar (text loses bolding but shows italicized).

It has the same issue the other was as well.

1. Highlight some text in a paragraph block on the Maywood theme.
2. Click the Italics option in the toolbar (text is italicized).
3. Click the Bold option in the toolbar (text stays italicized, no bolding).

## Result

The text in both the editor and on the front end shows the italics, but not the bolding:

<img src="https://cdn-std.droplr.net/files/acc_680347/Ms8Fv0" width="50%">

The HTML `<strong>` tag is there, so it seems to be an issue with the styling:

<img src="https://cdn-std.droplr.net/files/acc_680347/oEV2DX" width="50%">

## Expected

For the text to be both bold and italicized.

User Report:
17153077-hc

**Comment by nielslange** [comment]
@katiebethbrown I've fixed this issue in https://github.com/Automattic/themes/pull/1702 and it does affect the Varia and all its child-themes, such as the Maywood theme.

**Comment by michaeldcain** [comment]
This has been deployed in 54964-wpcom-themes
