### ISSUE TITLE
Twenty Twenty: Mobile Menu does not work

### ISSUE THREAD

**Issue by KristinaKay** [Automattic/themes#1705]
## Steps to replicate

- View the [theme demo on WordPress.com](https://twentytwentydemo.wordpress.com/) or [my test site](https://anotherfreetestsite.wordpress.com/) or [this user's site ](https://riverrockchurch.com/)on any mobile device (not in mobile view on Desktop)
- Tap the menu

Video: https://d.pr/v/Nwkl0V

## Result

Nothing. The menu does not expand like it should.

## Expected

The menu should open like on the .ORG theme demo

* User report: [#16190599-hc]
* Follow-up ticket: [#2555057-z]

**Comment by kcswong** [comment]
Another report in 15519760-hc
Follow up ticket: 2555252-zen

**Comment by kathrynwp** [comment]
Sounds like this core bug: https://core.trac.wordpress.org/ticket/48601

Will let a dev confirm and close this as a duplicate if it's the same.

**Comment by tanjoymor** [comment]
I agree that it does sound like the same issue and it seems to be fixed for 5.3.1 - but anyone know when that's supposed to be released?

**Comment by tanjoymor** [comment]
Have learned that 5.3.1 has been released - however, the mobile menu on the Twenty Twenty theme still isn't working. Have asked the Themes team about this. See ticket #2555057-zen for more details.

**Comment by kathrynwp** [comment]
The latest version of Twenty Twenty has been deployed on WordPress.com. I'll let these users know.

@danieldudzic I'll let you close the ticket with the relevant PR.

**Comment by danieldudzic** [comment]
Twenty Twenty is now up to date on WordPress.com ( Revision 54887 ).
