### ISSUE TITLE
Radcliffe 2: The Blog Posts block is not properly displayed

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#1707]
## Steps to replicate

1. Activate the Radcliffe 2 theme
2. Add the Blog Posts block to a page and set the grid view
3. Publish the page

## Result

The posts are not displayed as a grid:

![Screen Shot 2019-12-16 at 07 32 39](https://user-images.githubusercontent.com/3696121/70907325-9286ed80-1fd6-11ea-9bdb-4e350c9f0cf1.png)

## Expected

For the posts to be displayed in a grid as with other themes:

![Screen Shot 2019-12-16 at 07 34 56](https://user-images.githubusercontent.com/3696121/70907331-987cce80-1fd6-11ea-80af-4b50a279feb3.png)

* User report: 16651806-hc
* Follow-up ticket: 2564840-zen

**Comment by ivan-ottinger** [comment]
User came back asking for an update. Do we have any specific estimates when this could be fixed? Thank you.

**Comment by ersatzpenguin** [comment]
Just throwing in another instance of this issue: 19377702-hc

I was able to fix it by forcing the articles in the block to have a specific max width. For example, if the block was set to display four columns:

```
.wpnbha.columns-4 article, .wpnbha.columns-4 article:last-of-type {
	max-width: calc(25% - 16px);
} 
```

This `calc` setting was based on what I was seeing for the flex-basis setting of the block—which seemed to not take effect on Radcliffe 2 for some reason. However, setting it as a max-width did the trick.

**Comment by kathrynwp** [comment]
Also reported in 22075900-hc

**Comment by nickpagz** [comment]
Reported here as well #19693228-hc

**Comment by mrsjaved** [comment]
Another report at #3094673-zen

**Comment by joweber123** [comment]
Another report here at 3189832-zen

**Comment by pfernandez** [comment]
Another note on 3189832-zen, although the CSS fix does correct the column widths, no images are loaded into the DOM at all. So CSS doesn't help there.

**Comment by sophiegyo** [comment]
Another report here: 3193098-zen
This person can't use CSS as they don't have Premium on dotcom. Had to suggest Redhill as an alternative.

**Comment by carinapilar** [comment]
It seems that the theme doesn't work well with the block. I got a similar report, but related to the images when on a list.

When having the following settings on the block:

![Screen Shot 2020-08-14 at 18 18 09](https://user-images.githubusercontent.com/16104522/90293492-8e0f1f00-de5a-11ea-9f86-d20f305aaddd.png)

The images are shown very small, even when selecting different sizes on the block's settings, here's how it looks like on the site:

![Screen Shot 2020-08-14 at 18 18 58](https://user-images.githubusercontent.com/16104522/90293532-ae3ede00-de5a-11ea-910a-60bb0fa579e3.png)

While it properly load on a different theme:

![Screen Shot 2020-08-14 at 18 19 45](https://user-images.githubusercontent.com/16104522/90293547-beef5400-de5a-11ea-8423-b63cefee5345.png)

Reported here: 3191179-zen

**Comment by vajrasar** [comment]
Another report here - #3283632-zen

**Comment by arcangelini** [comment]
I am not sure if this is specifically theme related. It looks like this could be something for newspack may need to address? I tested this in another themes that display the Blog page in full-width rows similar to Radcliffe and was seeing the same issue. 

## Examples

#### Intergalactic 2

[![Screenshot](https://d.pr/i/fLW8zb+)](https://d.pr/i/fLW8zb)

#### Radcliffe 2

[![Screenshot](https://d.pr/i/ukBNEJ+)](https://d.pr/i/ukBNEJ)

Added this issue to Newspack GH for more eyes on the issue.

**Related Issue**
https://github.com/Automattic/newspack-blocks/issues/587

**Comment by arcangelini** [comment]
Solved in newspack update: https://github.com/Automattic/newspack-blocks/pull/592
