### ISSUE TITLE
Varia: Entry meta in Blog Posts block stays in grey with background colour

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1708]
## Steps to replicate

* Add a Blog posts block to display some posts.
* Add a background colour to a container block.
* Notice the colour of entry meta on the front-end.

<img width="605" alt="Screenshot 2019-12-16 at 14 15 45" src="https://user-images.githubusercontent.com/908665/70915979-c8e25e00-2012-11ea-92a5-b3933b58383a.png">

All the child themes likely share the issue, and they should also be updated.

**Comment by michaeldcain** [comment]
Fixed in https://github.com/Automattic/themes/pull/1710
