### ISSUE TITLE
Affinity custom header/featured images zoomed in on iPad Pro 12.9"

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#171]
## Steps to replicate

User has posted screenshots in the forum thread linked below. On iPad Pro 12.9 (may also happen on 10.5") in landscape orientation, the featured image/custom header image is zoomed way in. After consulting with @laurelfulford in slack [https://a8c.slack.com/archives/C029FM1EH/p1530174532000299](url) she said it may be the `background-attachment: fixed` and `background-size: cover` in the `min-width: 65em` media query that is causing the issue. I tried on my iPhone 6s + and on my iPad Air 2, but do not see the issue on those devices, and my simulations did not show it either. Laurel said Browserstack was not showing it when she tested, so it will have to be viewed and tested on the actual device.

* User report: [https://en.forums.wordpress.com/topic/affinity-theme-pics-too-big-on-ipad/#post-3134067](url)
* User's site: [http://shawnjnichols.wordpress.com/](url)

**Comment by tanjoymor** [comment]
We've got another ticket created from a Live Chat follow-up with what sounds like a similar issue.

* https://woothemes.zendesk.com/agent/tickets/1438152

@senff suggested the following custom css:

```
.home .custom-header-image {
        background-attachment: initial;
    }
```

But the user is on a Personal Plan, so can't use custom css. Another HE suggested it might be a theme issue?

A few HEs were able to replicate the issue on the iPad Pro device.

**Comment by Robertght** [comment]
Confirming here on an iPad Pro: #1603245-zen

**Comment by danieldudzic** [comment]
Hey @laurelfulford 

It seems that you have went through a number of possible solutions in: https://core.trac.wordpress.org/ticket/38395 - and found the device checks to be cumbersome.

I'm comfortable with changing the breakpoint where the styles are being applied :)

**Comment by laurelfulford** [comment]
Cool, thanks for the second set of eyes on this, @danieldudzic! That sounds like the best way to proceed here, then :)

**Comment by mishivee** [comment]
@eduardozulian found a workaround in 2172297-zen 

Try to disable the background image scroll, which can be done from My Site > Design > Customize > Theme Options > General. There, uncheck this:

https://cld.wthms.co/5br809

**Comment by jeffikus** [comment]
Affinity has been retired.
