### ISSUE TITLE
Page Layouts: Screenshot contains cookie banner

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#1713]
I noticed that some of the screenshots of Page Layout in the sidebar have the cookie banner at the bottom. Since the screenshot is small already, it would be good to get rid of it, as it creates visual clutter, and the banner is mostly unreadable anyway.

#### Steps to reproduce
1. Start editing a page.
2. Click on the "Change layout" button in document settings under "Page Layout".
3. Take a look at the screenshots under "Homepage layouts". Some of them (for exampe Alves, Balasana, Barnsbury) have the cookie policy banner visible at the bottom.
![image](https://user-images.githubusercontent.com/4550351/71057821-0df0c680-21b2-11ea-94b2-d9e093f84aff.png)

4. Pick Balasana. Look at the screenshot in document settings on the right under "Page Layout". Notice the cookie policy banner on the screenshot
![image](https://user-images.githubusercontent.com/4550351/71057657-8e62f780-21b1-11ea-97d2-b3f5913e5868.png)
5. Repeat steps 3 and 4, but this time pick Hever. Note there's no cookie policy banner on the screenshot.

#dogfooding, #manual-testing

If this should be reported in wp-calypso, feel free to move.

**Comment by cathymcbride** [comment]
Change layout has been removed and I don's see this in the other images of this layout.
