### ISSUE TITLE
Morden: Blog Posts block: post titles show a white background when show media behind is selected

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#1715]
## Steps to replicate
1. Activate Morden theme
2. Add a Blog posts block to a page or post
3. Click on the Set media behind button.

## Result
![what-happened](https://user-images.githubusercontent.com/3521683/71111698-bbf77300-21a8-11ea-9019-10f8773a422f.jpeg)

## Expected

![expected](https://user-images.githubusercontent.com/3521683/71111716-c0239080-21a8-11ea-843a-bcd64beb19c6.jpeg)

* User report: #17395927-hc

**Comment by michaeldcain** [comment]
@catkit: this should've been fixed yesterday in https://github.com/Automattic/themes/pull/1710

<img width="928" alt="Screen Shot 2019-12-19 at 9 57 39 AM" src="https://user-images.githubusercontent.com/942359/71183546-2f02f700-2246-11ea-9513-146395f6acbc.png">

I'm going to close this, but if you find it isn't fixed for you, please re-open.

**Comment by michaeldcain** [comment]
Sorry for the weird image - it's from a Randy Savage bot GM project 🤣
