### ISSUE TITLE
Exford: Footer Menu Covered Up on Mobile

### ISSUE THREAD

**Issue by RealCarFax** [Automattic/themes#1717]
## Steps to replicate

View the site on mobile. Here are screenshots:
Chrome: https://cloudup.com/c89L6HCJ4mA
Safari: https://cloudup.com/czW4jR9Z07W

## Result

The Footer menu is covered up by the hovering WordPress.com menu with the ... icon

## Expected

You should see the menu and then below it the ... menu from WordPress.com, I believe

* User report: #17418212-hc]
* Follow-up ticket: No follow-up ticket created as I provided them CSS (to add a little padding below the menu on screens under 400px wide) to use in the meanwhile so they are happy for now.

**Comment by michaeldcain** [comment]
This seems to be an issue with the action bar (regardless of theme). I've opened a ticket for the plugin in 8190-wpcom
