### ISSUE TITLE
Template-first Themes: add ‘wp_body_open’ hook

### ISSUE THREAD

**Issue by michaeldcain** [Automattic/themes#1722]
From #1709:

> Starting from WordPress 5.2 a new function is added – wp_body_open() – that is used to trigger a wp_body_open action. The function should be placed inside of the tag immediately after it is opened.

ref: https://make.wordpress.org/themes/2019/03/29/addition-of-new-wp_body_open-hook/

Ideally, this would be an "all themes" ticket, but at minimum, we should patch the template-first Varia child themes that have a custom `header.php`.

**Themes:**
- [x] Varia
- [x] Stow
- [x] Morden
- [x] Coutoire
- [x] Stratford
- [x] Rockfield
- [x] Balasana
- [x] Rivington
- [x] Dalston

**Comment by nielslange** [comment]
Additional themes with `header.php`:

- [ ] Affinity
- [ ] AltoFocus
- [ ] Apostrophe 2
- [ ] Button 2
- [ ] Canard
- [ ] Dara
- [ ] Dyad
- [ ] Gazette
- [ ] Illustratr
- [ ] Independent Publisher 2
- [ ] Intergalactic 2
- [ ] Ixion
- [ ] Karuna
- [ ] Libre 2
- [ ] Libretto
- [ ] Lodestar
- [ ] Penscratch 2
- [ ] Photos
- [ ] Pique
- [ ] Publication
- [ ] Radcliffe 2
- [ ] Rebalance
- [ ] Scratchpad
- [ ] Shoreditch
- [ ] Sketch
- [ ] TextBook
- [ ] Toujours

**Comment by cathymcbride** [comment]
Looks like this was fixed with the mentioned PR. Closing.
