### ISSUE TITLE
Cubic: Blank Homepage on Mobile

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#173]
## Steps to replicate

1. Activate the Cubic theme on a simple site
2. Set Homepage Settings to Your Latest Posts
3. View site on a mobile device and it will be blank.

Tested on Samsung Galaxy 7 on Chrome browser app.

## Result

Site appeared blank as in this screenshot: https://cloudup.com/cy8JsHjsQ5r

## Expected

Site to show blog post feed.

* User report: #4665112-hc
* Follow-up ticket: #1252251-zen
* User's site: https://ridemusicblog.com/

**Comment by alaczek** [comment]
Hi!

I tested user site in browserstack today, and was not able to replicate. I tested on:
* Galaxy S7, Chrome
* Galaxy S8, Chrome 
* Galaxy S9, Chrome
The only thing I noticed, is that loading up the posts on Galaxy S7 took a bit longer. 
Could you try testing it again?

**Comment by donalirl** [comment]
Tested again and confirmed that it's not happening now. Strange!
