### ISSUE TITLE
Varia: iframes with style attributes have a max-width of 32px when window size is at least 560px wide

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#1732]
## Steps to replicate
Embed a Google Calendar on an AT site with a Varia-type theme as the active theme and a window size of 560px wide or greater. Below is Stow; I also tried on Dalston, Maywood, Shawburn, and Mayland.

![image](https://user-images.githubusercontent.com/32492176/71693199-12e47700-2d69-11ea-9fbd-5d567cbc3889.png)

This is the theme code in question in Stow:
```
@media only screen and (min-width: 560px) {
	.entry-content > iframe[style] {
		max-width: 32px !important;
	}
}
```

A specific override for Google Calendar is as follows:
```
@media only screen and (min-width: 560px) {
  .entry-content > iframe[src^="https://calendar.google.com"] {
    max-width: unset !important;
  }
}
}
```

* User report: 17642074-hc
* Follow-up ticket: 2600091-zen

**Comment by nagpai** [comment]
Also noticed in 
17595549-hc

This was an atomic site.  On Atomic sites i found this work around.

1. Add the calendar code as Custom HTML (not sure why it does not get converted to shortcode like in non atomic sites)
2. Click the three dots at top right corner of the block and `Convert to blocks`
3. This wraps the code within <figure> </figure>  tags which seems to fix the width as well as center aligns the Calendar

On Non Atomic sites:

The calendar code correctly changes to a shortcode which renders the calendar correctly. However it is pushed to the left border. It should ideally be center aligned:

![ Misaligned GCal Embed ](https://d.pr/i/oWW6rP+) 
- https://d.pr/i/oWW6rP

**Comment by nielslange** [comment]
@nagpai While your workaround works like charm, I went ahead and created a PR in https://github.com/Automattic/themes/pull/1735 so that the iframe also shows correctly without a workaround. 😀

**Comment by senff** [comment]
@nielslange If #1735 is for mobile devices (as it states in the title of the PR), it won't fix this particular issue, which is reported to be happening on screens that are 560 and up.

**Comment by tbradsha** [comment]
At a glance, it appears the PR removes the offending code causing this issue, as well as other items.

In my comment above I put a specific override for Google Calendar, as I assumed there was some forethought as to why the code was introduced (though I can't think of a specific reason), and wasn't sure as to the implications of outright dropping it...

**Comment by tbradsha** [comment]
Actually, based on the other references in the stylesheet, it was probably originally supposed to be `margin: 32px` instead of `max-width: 32px`.

**Comment by nielslange** [comment]
> @nielslange If #1735 is for mobile devices (as it states in the title of the PR), it won't fix this particular issue, which is reported to be happening on screens that are 560 and up.

I see. While the title is misleading, the PR actually solved the issue on my end for all devices.

**Comment by chaitanyamsv** [comment]
Another report in 18783999-hc

**Comment by tbradsha** [comment]
Same issue with a Spotify embed (18859348-hc).

A simple non-CSS solution: use a Custom HTML block and wrap the shortcode in a span:
![image](https://user-images.githubusercontent.com/32492176/75059407-21622b80-549a-11ea-820e-7d4811270430.png)

The errant CSS selector then no longer targets the iframe in question, and all is well.

**Comment by poojashetty18** [comment]
Another report on the child theme Redhill of Varia with Amazon iframe embed (hc-18797567)

**Comment by katiebethbrown** [comment]
Another report on 14618013-hc

Stow Theme

User added a custom HTML block that was using an iframe to embed something on the site and it was barely visible.

**Comment by mlaetitia** [comment]
New Report: 21689625-hc

**Comment by kjellr** [comment]
@allancole or @danieldudzic, would you mind taking a look at this? It looks like [we had a idea for a fix](https://github.com/Automattic/themes/pull/1735#issuecomment-594950083) a while back, but didn't implement.

**Comment by danieldudzic** [comment]
@kjellr I'm happy to work on a fix - @allancole would you mind sharing your thoughts on the responsive refactor and the things to be mindful of here?

**Comment by edequalsawesome** [comment]
Also reported in #21832898-hc, provided the `<span>` work around
