### ISSUE TITLE
Port: Image caption alignment issue

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#1733]
## Steps to replicate

On any site with the Port theme:

1. Create a new post
2. Add an image block
3. Add a caption to the image
4. Apply an alignment to the image: https://d.pr/i/BLvoVV

## Result

When you view the post the caption will be scrunched to the left in a column of single words.

Remove the alignment on the image and the caption spreads out more (though doesn't center under the image).

https://d.pr/i/sUQl4l

## Expected

I expected the caption to be evenly distributed with normal wrapping and centered under the image (the way it looks in the editor): https://d.pr/i/gPr9YU

(I also tested a random selection of other themes and didn't find the issue occurring on other ones.)

* User report: #17663151-hc
* Follow-up ticket: #2602291-zd

**Comment by cathymcbride** [comment]
Retired theme. Closing
