### ISSUE TITLE
Baskerville 2: Posts page not loading in Internet Explorer 11

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1734]
## Steps to replicate

View the demo site at https://baskerville2demo.wordpress.com/ in Internet Explorer

## Result

No posts appear, only the header and menu

## Expected

For the posts to be loaded in the grid layout.

* User report: https://en.forums.wordpress.com/topic/baskerville-2-theme-in-internet-explorer-11/

I was able to replicate this using Browserstack. Edge works fine.

**Comment by danieldudzic** [comment]
Hi @KokkieH,

This issue will be resolved when the following Newspack fix gets deployed: https://github.com/Automattic/newspack-blocks/issues/332
