### ISSUE TITLE
"Social Menu" with WhatsApp link doesn't show WhatsApp icon

### ISSUE THREAD

**Issue by JaviRpo** [Automattic/themes#1736]
## Steps to replicate
Add "social menu" with WhatsApp link. The whatsapp icon doesn't appear.
![image](https://user-images.githubusercontent.com/8562436/71775366-e0e03a00-2f4d-11ea-977d-6c2081f876d4.png)

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

## Result
![image](https://user-images.githubusercontent.com/8562436/71775377-08cf9d80-2f4e-11ea-9afe-6d5b97fd2567.png)

[What happened.]

## Expected
Show WhatsApp icon

[What you expected to happen.]

* User report: [shortlink to chat/forum thread/ticket, ie #12345-hc]
* Follow-up ticket: [shortlink to ticket, ie #12345-zd]

**Comment by nielslange** [comment]
@JaviRpo This issue is not related to Automattic's free themes, but to Jetpack and had been reported already in https://github.com/Automattic/jetpack/issues/10663. I'm going to close this issue here, but thanks for reporting this and feel free to keep an eye on the other issue. 😉
