### ISSUE TITLE
Twenty Twenty: Text Widget does not reflect base font selected in Customizer

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#1738]
Looks like the font annotation doesn't currently account for text widgets.

## Steps to replicate

- Add a text widget with some test to any widget area
- Go to Customize > Fonts, and select any font under Base Font
- View the widget on the front end

## Result

The widget does not display in the selected font

## Expected

The widget should be displayed in the selected font

* No user report, noticed on my own site, using Museo Sans as Base font - https://kpresner.com/
* I used a custom CSS workaround to fix the error on my site, which only has a paragraph tag to contend with at the moment:

```
.widget_text p {
 font-family: "museo-1", "museo-2", serif;
 font-style: normal;
 font-weight: 500
}
```

### Before custom CSS fix:

<img width="1216" alt="Kathryn Presner – Theme whisperer and professional cat cuddler-2" src="https://user-images.githubusercontent.com/7662449/71787317-36ffbc80-2fe4-11ea-85fd-71af65abb365.png">

### After custom CSS fix:

<img width="1234" alt="Kathryn Presner – Theme whisperer and professional cat cuddler-1" src="https://user-images.githubusercontent.com/7662449/71787306-16cffd80-2fe4-11ea-93c4-5a80654959bb.png">

**Comment by matiasbenedetto** [comment]
I'm not able to reproduce this issue.
I add a video showing my changes to widgets using Twenty Twenty with WP 5.8.2 and the current Gutenberg dev version:
https://user-images.githubusercontent.com/1310626/148117932-39671bbf-7881-4141-842a-82acdc4b9f98.mp4

**Comment by matiasbenedetto** [comment]
Potential fix: https://code.a8c.com/D72543

**Comment by matiasbenedetto** [comment]
~Possible fix here: D72543-code~

**Comment by matiasbenedetto** [comment]
Possible fix here: D72771-code

**Comment by scruffian** [comment]
Does this fix need to be pushed back to core?

**Comment by pbking** [comment]
> Does this fix need to be pushed back to core?

I don't think so since the font customizations on offer are those we've added for wpcom.

**Comment by pbking** [comment]
Deployed
