### ISSUE TITLE
Twenty Seventeen: Featured Images not displaying in frontpage content sections

### ISSUE THREAD

**Issue by sashastone** [Automattic/themes#174]
## Steps to replicate

1. Create Pages with Featured Images. 
2. Set the Homepage to a Static Page.
3. Go to My Site > Customize > Theme Options and select at least 2 pages for the Front Page content sections. Make sure the selected pages have featured images. 

## Result

- Only the section 1 displayed the featured image on the homepage. 
- Section 1 included a gray space below the featured image: https://d.pr/i/rT2eb4
- Section 2 was a blank gray space where the featured image should display: https://d.pr/i/61hs7R
- Section 3 was a blank gray space where the featured image should display: https://d.pr/i/zi0RkS

## Expected

- I expected all featured images of the selected pages to display on the homepage, as illustrated in the theme demo: https://wordpress.com/theme/twentyseventeen

* User report: [shortlink to chat/forum thread/ticket, ie #12345-hc]: #1253326-zen

* User's site: [link to user's site, including the specific page/post where issue is present]: https://billybryant.net/

The featured images for Section 2 and Section 3 of the user's site are PNG instead of JPEG. I thought this might be the issue, but when I tested the theme on a test site and used JPEG images, I had the same issue the user describes.

**Comment by alaczek** [comment]
Something similar has been reported in p1529476471000062-slack-themes, and it resolved itself, but we definitely should look into this.

**Comment by jessestu** [comment]
[It's affecting the theme demo](https://twentyseventeendemo.wordpress.com/).

I'm seeing this in a chat with a user: 2563156-hc

I also noticed it yesterday when a user asked to headstart Twenty-Seventeen. It affected their site. 4766785-hc

It's also probably related to #168 as, in that thread, the issue happens with video headers and without.

**Comment by laurelfulford** [comment]
I think this is the same issue as #168 -- my best guess is something changed in Webkit that caused this. 

Thanks for the reports, all! I'm moving these reports to that ticket and closing this one, so we have everything in one place.
