### ISSUE TITLE
Twenty Twenty: Inconsistency in widget heading styling

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1740]
## Steps to replicate

Add some widgets to one of the footer areas, including the Follow Blog widget

## Result

Most widgets have the widget heading sized to 4rem and bold weight (700)

The Follow Blog widget heading is sized at 1.6rem and normal weight (400)

![Customize__Twenty_Twenty_–_Just_another_WordPress_site](https://user-images.githubusercontent.com/11873759/71800250-3c025180-3060-11ea-8ad1-126de29318b8.png)

## Expected

For all widget headings to be sized the same.

* User report: https://en.forums.wordpress.com/topic/twenty-twenty-theme-follow-blog-widget-heading-not-bold-or-large/

**Comment by kathrynwp** [comment]
I reported this in Core Trac yesterday since the issue can be replicated on self-hosted sites, hoping it can be fixed in Core:

https://core.trac.wordpress.org/ticket/49137

**Comment by KokkieH** [comment]
I didn't even think to test this on the Core version. Thanks, Kathryn!

**Comment by KokkieH** [comment]
Looks like this was eventually fixed for WordPress.com via https://github.com/Automattic/jetpack/pull/15596, so closing
