### ISSUE TITLE
Gateway:  Featured image panel shows only a partial image in the Block Editor

### ISSUE THREAD

**Issue by chaitanyamsv** [Automattic/themes#1750]
## Steps to replicate

1. Open the post editor.
2. From the _Featured image_ panel on the right, click on the _Set featured image_.
3. Select an image from the media modal that opens.

## Result

The featured image shows only partially as shown in this screenshot: 
https://d.pr/i/jjArcQ

## Expected

The complete featured image should show up in the featured image panel in the editor.

## Notes

This doesn't affect the featured image displayed on the site. This issue is just in the editor > featured image panel. The site shows the full sized featured image.

* User report: 17886325-hc
* Follow-up ticket: 2639658-zd

**Comment by nielslange** [comment]
@chaitanyams The theme should not have any control of the metaboxes in Calypso and/or WP Admin. Have you verified that this issue only occurs in combination with the Gateway theme and not with any other theme? Or is it possible that the featured image shows the thumbnail and that the Gateway theme trims the thumbnail as seen in your referred screenshot?

**Comment by chaitanyamsv** [comment]
> Have you verified that this issue only occurs in combination with the Gateway theme and not with any other theme? 

I tested this again with a few other themes (like Hever, and Dara, and Portrait), and with all the themes the featured image panel is shown only partially as shown in the original screenshot
https://d.pr/i/jjArcQ

On looking further in GitHub, I found the following at https://github.com/Automattic/wp-calypso/issues/27691

`As for the other discrepancies between Calypso vs Gutenberg settings - for the first phase we are aiming to replicate the Core look so differences with Calypso's sidebar are expected.
`

So sounds like this is expected.

**Comment by nielslange** [comment]
What I was saying is that the size of the featured image is not controlled by the theme, thus, this issue cannot be fixed by adjusting the theme.

**Comment by chaitanyamsv** [comment]
Thanks for the comment @nielslange.

I paused further testing and follow ups on this low priority issue in preference to my other priorities.

**Comment by SiobhyB** [comment]
I've been able to replicate following a user report, and have created an issue on the Calypso repo here:

https://github.com/Automattic/wp-calypso/issues/40064

I'll close this one.
