### ISSUE TITLE
Shoreditch: border-bottom for a text link appears even for image links

### ISSUE THREAD

**Issue by sarahcada** [Automattic/themes#1752]
## Steps to replicate

- Activate Shoreditch theme on your site.
- Create/edit a post/page and add a transparent image with a link

## Result

There's a border-bottom for the link, showing up as a line overlapping with the image.
![SWCywbxm](https://user-images.githubusercontent.com/26526521/72602508-58509900-3952-11ea-9822-e37f67c3d595.jpeg)

## Expected

No border-bottom since there's no text.

* User report: [#17972805-hc]

If the image has an opaque background, the border-bottom gets hidden behind it. This is the workaround I've shared for this particular user. Folks with a Premium Plan can probably use a CSS workaround as well.

**Comment by nielslange** [comment]
@sarahcada Feel free to test my proposed PR https://github.com/Automattic/themes/pull/1756 😉
