### ISSUE TITLE
Varia: [Improvement] Add "Content options" to Varia and its Childs 

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#1754]
I have had some users asking to hide featured images or authors.

Other themes have this option, and not sure if that's something in the scope of Global Styles:

![Screen Shot 2020-01-18 at 10 36 18](https://user-images.githubusercontent.com/3696121/72666251-651ace80-39de-11ea-892c-cb06f520ac1f.png)

For Premium plan users we can give some CSS code. But the only option for Personal plan users is to pick a different theme.

**Comment by KokkieH** [comment]
Another request in https://wordpress.com/forums/topic/featured-image-to-display-or-not/

**Comment by Aurorum** [comment]
PR in #7518
