### ISSUE TITLE
Twenty Twenty: Can't click submenu over a Cover Block

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/themes#1762]
## Steps to replicate

* Activate Twenty Twenty Theme
* Create a page with a Cover Block at the top (full-width helps with making the menu get to it)
* Create a submenu that goes over the top of the Cover Block
* Try to use the menu

## Result

The menu is unclickable. When you mouse over the submenu, as soon as the intersection between the menu and the Cover Block are reached, the menu closes.

Screencast: https://d.pr/i/oM5uKl

## Expected

The menu should be clickable.

We were able to fix this using this CSS code:

```
#site-header {
z-index: 2;
}
```

This fixes the menu. Screencast: https://d.pr/i/eDbrej

(NOTE: The screencasts were too large and GH wouldn't show them. Direct links provided instead).

* User report: #17986632-hc
* Follow-up ticket: None. User had the Premium plan so we used the CSS code to work around the bug.

**Comment by kjellr** [comment]
I've reported this issue over in core Trac as well: https://core.trac.wordpress.org/ticket/49322

**Comment by GeoJunkie** [comment]
Just a note that it has more of a potential impact on WP.com users.  The screenshots were made by hiding the title, which is specific to WP.com sites as far as I can tell (couldn’t set that on a JN site)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by kjellr** [comment]
👍 I've submitted a patch that should take care of it: 
https://core.trac.wordpress.org/ticket/49322#comment:1

I'm going to close this ticket, since the core one is in the works.

**Comment by rickmgithub** [comment]
New case today here - #2924607-zen

The menu disappears when the mouse cursor moves over the cover block area

**Comment by kjellr** [comment]
Now that this was merged into core, I'm re-opening this issue to start migrating the new version of Twenty Twenty over from `trunk`. @allancole would you mind doing this when you have a moment?

**Comment by kjellr** [comment]
This one has been migrated over to WP.com, so marking this as closed for now. Thank you! 👍
