### ISSUE TITLE
Author Gravatar not shown on Posts Page on Simple Sites for Twenty Sixteen

### ISSUE THREAD

**Issue by bsanevans** [Automattic/themes#1765]
## Steps to replicate

1. Set posts page as homepage
2. Make sure authors info is ticked under Content Options
3. Author name and Gravatar shows on Atomic sites, but not Simple

## Workaround

Adding the following CSS fixes the issue, but only if the site is on a plan compatible with Custom CSS.

```
.byline {
	display: inline;
}
```

* User report: #2661612-zd

**Comment by danieldudzic** [comment]
The following code in style.css suggests that this is happening by design:

```
.sticky .posted-on,
.byline {
	display: none;
}

.single .byline,
.group-blog .byline {
	display: inline;
}
```

However, I do not know the full context of how it's suppose to work.

**Comment by danieldudzic** [comment]
Fix: D62531-code

**Comment by jeffikus** [comment]
@danieldudzic are there any blockers to this being deployed?

**Comment by kaitohm** [comment]
@danieldudzic Just checking... Has this been deployed now?

**Comment by kspilarski** [comment]
I had a user with the same issue, and I was also able to replicate the issue on my test site.

**Comment by fstath** [comment]
I got another report.

https://wordpress.com/forums/topic/my-profile-no-appears-on-my-sites-front-page/

**Comment by danieldudzic** [comment]
Apologies for this taking so long. It has been deployed now.
