### ISSUE TITLE
Pique: Logo zooming in and out on Firefox when hovering

### ISSUE THREAD

**Issue by eoinsav** [Automattic/themes#1770]
## Steps to replicate

1. Go to the Pique theme demo site using Firefox: https://piquedemo.wordpress.com/
2. Hover over the logo with your cursor.

GIF of the zooming:

https://cldup.com/-TLTqwJqgO.gif

## Result

The logo zooms in and out, making it hard to click.

## Expected

The logo should stay as it is.

This CSS seems to be causing it:

```
.site-branding .site-logo-link:hover {
transform: scale(5%);
}
```

This CSS prevents it from happening:

```
.site-branding .site-logo-link:hover {
transform: none;
}
```

* User report: [#3522963-hc]
* Follow-up ticket: [#2668950-zd]

**Comment by melchoyce** [comment]
Yeah, this is pretty bananas. Unsure why the animation is there at all, since it doesn't seem to do anything in Chrome or Safari. I think we can safely remove the CSS.

**Comment by nielslange** [comment]
@eoinsav & @melchoyce I've fixed this issue in PR https://github.com/Automattic/themes/pull/1775. Feel free to test it and let me know if it needs some adjustment. 😉

**Comment by mendezcode** [comment]
Fix deployed in **r55211-wpcom-themes**.
