### ISSUE TITLE
Illustratr: Unable to display posts in a grid using the Blog Post block

### ISSUE THREAD

**Issue by SiobhyB** [Automattic/themes#1774]
## Steps to replicate

1. Add [the Blog Posts block](https://en.support.wordpress.com/wordpress-editor/blocks/blog-posts-block/) to a new page.
2. Tweak the settings of the Blog Posts block so that posts will display in a three-column grid.
3. View the page.

## Result

Posts displayed in one-column, despite the settings to display the posts in a three-column grid.

## Expected

I expected posts to display in a three-column grid, as per the block's settings. 

It seems the `flex-basis` is not working as expected in the CSS, but I'm not sure why.

<img width="1669" alt="Screenshot 2020-01-30 at 23 54 54" src="https://user-images.githubusercontent.com/2998162/73501025-48a66b00-43bc-11ea-8ff1-485262e78b53.png">

I've provided the user with the following CSS workaround for now:

```
@media only screen and (min-width: 782px) {
    .wpnbha.columns-3 article {
        width: calc(33.333% - 16px);
    }
}
```

* User report: #2668727-zen

**Comment by nielslange** [comment]
@SiobhyB I just fixed this issue in https://github.com/Automattic/themes/pull/1776. Feel free to test the PR and let me know if it works for you.

**Comment by SiobhyB** [comment]
@nielslange, apologies for the delay! Thank you so much for looking into this, the change works for me and I approved it.

**Comment by lakellie** [comment]
Another user report in 21433427-hc. I provided them with the CSS workaround above

**Comment by tavilla61** [comment]
Another user with the same issue - 22793987-hc. I gave them the CSS fix above and it worked for them.
