### ISSUE TITLE
Colinear: site-title font weight not respected

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#178]
## Steps to replicate
Under My Site > Customize > Fonts > Headings choose a font (this user picked Allegra Sans) and set change its weight.

## Result
Note the site-title font weight is set accordingly, but only on the front page. Posts and individual pages have a different weight.

<img width="605" alt="screen shot 2018-07-04 at 2 55 29 pm" src="https://user-images.githubusercontent.com/3476361/42294298-fba84ae2-7f9c-11e8-8c7c-c2a8ae1e91af.png">
<img width="619" alt="screen shot 2018-07-04 at 2 55 14 pm" src="https://user-images.githubusercontent.com/3476361/42294299-fbc7caac-7f9c-11e8-8263-f9eeeed444ec.png">
<img width="1354" alt="screen shot 2018-07-04 at 2 54 20 pm" src="https://user-images.githubusercontent.com/3476361/42294300-fbe7d798-7f9c-11e8-8620-e1e471e00951.png">

## Expected
User expects site-title weight to remain consistent. It does not.

* User report: https://en.forums.wordpress.com/topic/colinear-theme-blockquote-border-color/ (Wherein the user also complains about border colors not being changed with different pallets) 
* Follow-up ticket: Same thread
* User's site: https://sottolequerce.wordpress.com/

**Comment by laurelfulford** [comment]
The font weight is fixed in r49014-wpcom-themes; I added a follow-up comment in the forum thread.
