### ISSUE TITLE
Independent Publisher 2: Heading is incorrectly aligned with image in Block Editor

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/themes#1785]
## Steps to replicate

In the Block Editor with Independent Publisher 2 active if you left- or right-align an image a heading block below it will incorrectly appear in the editor with the same vertical alignment on the opposite side, but on the front-end the header will appear below the image.

Another theme I tested, Twenty Sixteen, did not experience this issue. 

In the editor:

<img width="902" alt="Screen Shot 2020-02-06 at 8 48 55 PM" src="https://user-images.githubusercontent.com/1900444/73994047-2499db00-4922-11ea-8431-cd043c6ea0b4.png">

Front end:

<img width="424" alt="Screen Shot 2020-02-06 at 8 49 03 PM" src="https://user-images.githubusercontent.com/1900444/73994053-2a8fbc00-4922-11ea-8e79-af27c8d12ae0.png">

## Result

The heading an image were aligned differently than shown in the editor. 

## Expected

For the front-end alignement to match what's shown in the editor. 

* User report: #2694410-zen

**Comment by nielslange** [comment]
@kriskarkoski I've addressed this issue in https://github.com/Automattic/themes/pull/1790, thus, feel free to test this PR. 😉
