### ISSUE TITLE
Independent Publisher 2: Image styles not displayed on front-end

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/themes#1786]
## Steps to replicate

In the Block Editor with Independent Publisher 2 active applied image styles are not properly displayed on the front-end. This appears to affect both Default and Rounded, though it's more obvious with the latter. 

Here's a default image in the editor with pointed corners:

<img width="744" alt="Screen Shot 2020-02-06 at 8 55 02 PM" src="https://user-images.githubusercontent.com/1900444/73994286-02548d00-4923-11ea-8187-c8e1ea1a154e.png">

Here it is with the rounded style:

<img width="804" alt="Screen Shot 2020-02-06 at 8 52 29 PM" src="https://user-images.githubusercontent.com/1900444/73994295-0da7b880-4923-11ea-9228-cdda4f0a34ce.png">

And here's how it appears on the front-end for both with slightly rounded corners:

<img width="751" alt="Screen Shot 2020-02-06 at 8 52 44 PM" src="https://user-images.githubusercontent.com/1900444/73994313-1bf5d480-4923-11ea-9c5a-165037f20f2f.png">

## Result

The front-end image styling did not match the editor and was unaffected by what was set there.

## Expected

For the front-end styling to match what's shown in the editor. 

* User report: #2694410-zen

**Comment by nielslange** [comment]
@kriskarkoski I addressed this issue in https://github.com/Automattic/themes/pull/1789, thus, feel free to test that PR. 😉
