### ISSUE TITLE
Dara: Blog Posts Block meta CSS

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#1787]
## Steps to replicate

1. Create Blog Posts Block in a page
2. Enable any of the post meta data
3. View page

## Result
Post meta is overlapped by following post
<img width="779" alt="Screen Shot 2020-02-07 at 6 14 48 pm" src="https://user-images.githubusercontent.com/2031017/74008940-48b6f400-49d6-11ea-95dd-5dc9ad85acc5.png">

Due to CSS on regular blog posts:
<img width="326" alt="Screen Shot 2020-02-07 at 6 14 35 pm" src="https://user-images.githubusercontent.com/2031017/74009105-9df30580-49d6-11ea-891a-1ea45ede3464.png">

## Expected
Meta display below post, but not be overlapped

* User report: 2696088-zd

**Comment by nielslange** [comment]
@kristarella I addressed this issue in https://github.com/Automattic/themes/pull/1788. Feel free to test this PR. 😉

**Comment by edwinho89** [comment]
Similar issue reported in 2718164-zen

**Comment by alshakero** [comment]
Hi! There is a new complaint about this and the user doesn't seem particularly happy. 2790814-ZD. It's the same user and they're complaining that it's been a month and their site still looks off.
