### ISSUE TITLE
Twenty Nineteen: Full width blocks extends beyond editor

### ISSUE THREAD

**Issue by jacoswan** [Automattic/themes#1793]
## Steps to replicate

1. Activate TwentyNineteen;
2. Create a new page;
3. Insert a block that has full-width options (cover block, gallery block, image block, video block, etc)
4. Notice how they overshoot the editor/browser boundries

Browser (Chrome 79.0.3945.130, Safari 13.0.4, Firefox 72.0.2)
Plans: Free, Personal, Premium, BIZ Simple, BIZ AT - but **not** WPORG. 

Cover block (when selected, Firefox):

![image](https://user-images.githubusercontent.com/15178758/74163053-76947680-4c2a-11ea-9e6f-e22cebe4ef81.png)

Cover block (when selected, Safari):
![image](https://user-images.githubusercontent.com/15178758/74163292-cf640f00-4c2a-11ea-8138-dd7adf50c7f5.png)

Cover Block (top, when block is selected, Chrome)
![image](https://user-images.githubusercontent.com/15178758/74161219-439cb380-4c27-11ea-8e7b-1843196080e6.png)

Gallery Block (top, when block is selected, Chrome):
![image](https://user-images.githubusercontent.com/15178758/74162621-b9a21a00-4c29-11ea-8a6a-244e823b054f.png)

Gallery Block (bottom, when block is selected, Chrome):
![image](https://user-images.githubusercontent.com/15178758/74162675-cfafda80-4c29-11ea-910e-0159acf0817d.png)

Image Block (when block is selected, Chrome):
![image](https://user-images.githubusercontent.com/15178758/74162750-f706a780-4c29-11ea-977e-19f6dff0b86d.png)

Works on WPORG - Firefox, WP Version 5.3.2, no other plugins active. 

![image](https://user-images.githubusercontent.com/15178758/74163693-6b8e1600-4c2b-11ea-8f42-8a2043d09ab2.png)

## Result

In full-width mode, blocks overshoot browser/editor boundary, and not matter how big you expand the browser window, it doesn't recover. Exiting the editor and re-entering doesn't make a different. 

## Expected

Something similar to the last screen-shot, with selectors visible. 

* Similar, possibly related to "[FSE: Full width blocks wider than page editor](https://github.com/Automattic/wp-calypso/issues/39155)"
* User report: [#2704054-zd]
* Follow-up ticket: [#2704054-zd]

**Comment by kjellr** [comment]
👋 This is reported in Core, and there's a patch going for it already, slated to land in WP 5.4. I'm going to close this issue so we can continue tracking over there: 

https://core.trac.wordpress.org/ticket/48526
