### ISSUE TITLE
Twenty Twenty: Custom Fonts not Applied to Widgets

### ISSUE THREAD

**Issue by macmanx2** [Automattic/themes#1795]
## Steps to replicate

Choose a custom font in the Customizer.

## Result

Custom font is applied to the content area, but not the widget areas.

## Expected

Custom font applies to entire site.

* User report: https://en.forums.wordpress.com/topic/twenty-twenty-font-style-not-changing-in-widget-area/

**Comment by allancole** [comment]
This is now fixed in 56485-wpcom-themes :-)
