### ISSUE TITLE
Varia: Bottom margin override missing for Blog Posts block grid view  

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1797]
## Steps to replicate

* Make sure you have a few posts with a featured image.
* Add a blog posts block, and make sure the Grid view and the Show media behind are selected.
* Notice the last item is taller than others.

![Screenshot 2020-02-12 at 14 11 27](https://user-images.githubusercontent.com/908665/74343726-6653d700-4da3-11ea-92e2-8e9d459fb811.png)

Varia and its child themes override the bottom margin accordingly to the vertical rhythm, but it seems we've missed one selector and the default value of `1em` trumps.

**Comment by KokkieH** [comment]
A user report in https://wordpress.com/forums/topic/css-bug-in-blog-post-block-with-background-featured-images/, for Hever

**Comment by pbking** [comment]
This was an issue in the block and has been addressed via [this PR](https://github.com/Automattic/newspack-blocks/pull/766) in that project.

**Comment by danieldudzic** [comment]
Since this isn't a theme issue, I'm happy to close.
