### ISSUE TITLE
Varia: Shortcodes block is not centered

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#1799]
## Steps to replicate

1. Add a shortcodes block
2. Add a shortcode like a Scribd link
3. Publsh

## Result

The shortcode content is moved all the way to the left:

![Screen Shot on 2020-02-12 at 11:35:03](https://user-images.githubusercontent.com/3696121/74356061-baeb5800-4d8b-11ea-8431-c6f0bba13b26.png)

Link to test site: https://atrumtest01.wordpress.com/2020/02/12/testing-scribd-shortcode/

## Expected

For the content to be centered like on other themes. I found a workaround by placing the shortcode inside a Group block

* User report: 18626806-hc

**Comment by Robertght** [comment]
Cannot replicate this anymore. Closing.
