### ISSUE TITLE
 Gazette: Featured content image thumbnails not centered

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#18]
This ticket was originally filed by @KokkieH in 4630-wpcom-themes:

In the featured content section, featured image thumbnails are off-centre, which is inconsistent with featured image thumbnails of posts in the main feed, and the single-post view. It's more noticeable with bigger featured images, it seems. 

![](https://cldup.com/7CGFnU6ktB-3000x3000.png)

* User report: 864890-f
* User's site: https://livetsljussite.wordpress.com/

**Comment by sixhours** [comment]
Looks like the customer's site was deleted by the user. I'm going to wontfix this to avoid disrupting the positioning of images on existing sites.
