### ISSUE TITLE
Toolbox: Add theme to repo

### ISSUE THREAD

**Issue by lulalala** [Automattic/themes#1802]
I'd like to request for your [toolbox theme](https://themeshaper.com/2010/07/02/toolbox-html5-starter-theme/) to be added here too. Though it is old, it is easy and flexible to build themes on top of it. By doing so, we might be able to update to fit the 2020-html5.

**Comment by cathymcbride** [comment]
retired theme. Closing...

**Comment by lulalala** [comment]
@cathymcbride @nielslange 
Instead, could this theme be licensed to MIT/GPL so we can fork it? Thanks.

**Comment by lulalala** [comment]
@cathymcbride @nielslange
Instead, could this theme be licensed to MIT/GPL so we can fork it? Thanks.
