### ISSUE TITLE
Varia: Menu button appears for primary menu on mobile even when menu is empty.

### ISSUE THREAD

**Issue by ersatzpenguin** [Automattic/themes#1808]
## Steps to replicate

1. Set site to use Varia or one of the Varia child themes (tested with Maywood, Mayland, and Exford).
2. Set an empty menu in the "Primary" menu location.
3. View site on mobile.

## Result

A menu button appears for the empty primary menu, allowing you to click to expand—nothing :).
![exford mobile empty menu button](https://d.pr/i/rhJKe6+)

## Expected

For the page to display without a menu button on mobile—because the menu is empty.

## Temporary Fix/Workaround

Making sure that nothing is set to display in the "Primary" menu location removes the button.

## Comment
The fix/workaround that exists for this is somewhat less than intuitive—users do not generally understand that this is an option, and assume that if they empty out the menu, the button will disappear. This was opened previously in https://github.com/Automattic/themes/issues/1331 and then closed for priority. However, this is the fifth time I've encountered this issue as an HE, and with more folks using our Varia-based themes, it seems like it *might* be worth looking at. But feel free to tell me I'm wrong :).

* User report: #18676186-hc is my most recent example.

**Comment by nielslange** [comment]
@ersatzpenguin Similar to @iamtakashi's comment in https://github.com/Automattic/themes/issues/1331#issuecomment-536006551 I also don't understand why a customer would create an empty custom menu. If no menu had been created, no menu will be shown both on mobile and desktop. 

<table>
<tr>
<td valign="top">WP Admin → Appearance → Menus:
<br><br>

![#1331-backend](https://user-images.githubusercontent.com/3323310/74606807-ecef1800-5105-11ea-991f-79de62db9d07.png)
</td>
<td valign="top">Frontend (iOS X):
<br><br>

![#1331-frontend-mobile](https://user-images.githubusercontent.com/3323310/74606805-eb255480-5105-11ea-9f07-535d85fe0b9b.png)
</td>
</tr>
</table>

**Comment by ersatzpenguin** [comment]
I think it’s a fair point that an empty menu, for someone who is familiar with WordPress and how to manage menus, is a bit of a strange thing to create *on purpose*. Especially if we’re talking about using the WP-Admin menu options (which, it should be said, most of our users do not know about).

The issue is that each time this has come up, the user has not *created* an empty menu per se—they’ve removed items from an existing menu that was already set to display in the primary menu area. Their belief, from what I have gathered in working directly with them on this issue, is that by removing the items, the menu will disappear. And it does. On desktop it disappears, and when they’re making these changes in Customizer (as they almost always are if they’re on WP.com) it immediately previews their desired change. For them, this is confirmation that the menu is gone, and they are then surprised and frustrated when a button shows up on mobile. Because the behavior on mobile in this case is quite different—showing an entire button that doesn’t appear on desktop.

For a novice user, whether or not the HTML structure is there on desktop, whether the WP-Admin menu options make menu locations more obvious etc., isn’t on their radar. So, the existing behavior doesn’t match with their expectations, nor with the cues they’re getting via Customizer.

You could say, and you would not be totally wrong, that this “bug” isn’t strictly a theme bug—rather, it’s the result of various potential areas of improvement (in Customizer, new user orientation, etc.) in concert with a specific theme and novice user expectations. However, I’ve never encountered this issue with a non-Varia theme. 🤷🏻‍♀️

I would never claim that this is a high-priority bug, but it does seem like something worth looking at.

**Comment by nielslange** [comment]
@ersatzpenguin I totally understand your point as well and I'm happy to create a fix for this issue to prevent that the menu button becomes visible in case of an empty menu. 😉

**Comment by nielslange** [comment]
@ersatzpenguin I just created a PR for this issue in https://github.com/Automattic/themes/pull/1810, thus, feel free to test the fix on your end.

**Comment by scruffian** [comment]
I can't replicate; I think this has been fixed. Closing.
