### ISSUE TITLE
Radcliffe 2: Excessive Title Tags

### ISSUE THREAD

**Issue by macmanx2** [Automattic/themes#1809]
## Steps to replicate

View source on any Radcliffe 2 page, like the reported https://ameritoproofingcontractor.wordpress.com/roofing-contractor-in-reidsville-nc/ or the theme's demo https://radcliffe2demo.wordpress.com/services/

## Result

The `<title>` tag is used excessively for headers, 21 times on both the reported page and the demo page.

## Expected

Google's Search Console considers having more than 1 `<title>` tag to be an "urgent SEO issue" so we should probably find some way to abide by that.

* User report: https://en.forums.wordpress.com/topic/different-page-for-each-location/

**Comment by nielslange** [comment]
@macmanx2 I looked up this issue and all `<title>` tags, except of the first one, belong to SVGs and according to https://developer.mozilla.org/en-US/docs/Web/SVG/Element/title this seems to be legit. Also, https://validator.w3.org/nu/?doc=https%3A%2F%2Fameritoproofingcontractor.wordpress.com%2Froofing-contractor-in-reidsville-nc%2F does not mark these additional `<title>` tags as invalid, as they belong to the SVGs.

**Comment by macmanx2** [comment]
Interesting, it wouldn't be the first time a Google checker tool struggled to understand context. Thanks!
