### ISSUE TITLE
Maywood: Bold Formatting Issue

### ISSUE THREAD

**Issue by joweber123** [Automattic/themes#1812]
## Steps to replicate

- Select Merriweather as the base font in Global Styles.
- Add 'Bold' styling to a word/words in a paragraph block.
- Preview or Publish and view the page.

## Result
The `<strong></strong>` tag is being applied to the selected words but the font-weight is not increased enough to make any visual difference.   The base font-weight is set to 300 while the strong tag's font-weight is set to 500.  Changing this to 600 or higher does make this visually different.  I have found that this does not happen when the theme's default font style is selected.  

![Bold_Editor_selection](https://user-images.githubusercontent.com/24914028/74791419-bd0a6500-52fd-11ea-9a35-05f8a340a154.png)

![bold_font](https://user-images.githubusercontent.com/24914028/74791439-c72c6380-52fd-11ea-9cb2-5db1331619b7.png)

## Expected

I would expect that the theme's strong font-weight would be visually different than the base font. 

* Ticket: #2722376-zd

**Comment by nielslange** [comment]
@joweber123 I've addressed this issue in https://github.com/Automattic/themes/pull/1814 and also fixed two other Varia child themes (Coutoire & Stow) which showed the similar issue. I've assigned @mendezcode & @allancole as reviewers to the PR, but feel free to test the PR as well, if you like to. 😉

**Comment by joweber123** [comment]
Wonderful.  Thank you!

**Comment by aleone89** [comment]
Hello there! I've got a report of this via hc-19438249 

This time the base font being used was "work sans". During the chat I add a custom design subscription and added the CSS to take that from weight: 500 to weight: 800.

**Comment by benchilcote** [comment]
Another case reported on Maywood Theme.  User is using Roboto font in Global Fonts and bold does not work on paragraph blocks.  For now, I have employed a CSS workaround for the user:

> b, strong {
> 	font-weight: 600;
> }

#28769030-zen

**Comment by mikeicode** [comment]
Similar issue 3265453-zd Coutoire theme - Coutoire theme

**Comment by allancole** [comment]
This is probably an issue with the entire Varia system. I’ll start a PR to fix this all of the Varia child themes at once.

**Comment by sdnunca** [comment]
Another issue reported here zen-3300865 - varia theme
The ticket requires follow-up once the issue is fixed, pinging @aleone89

**Comment by samvaidya** [comment]
Another issue reported here:  [24922890-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=24922890) - Stow theme.  Font used:  Playfair display via Global Styles

I provided them with the following CSS workaround for now: 

`strong {
	font-weight: bold;
}`

This ticket requires a follow-up once this bug is fixed:  https://woothemes.zendesk.com/agent/tickets/3411720
