### ISSUE TITLE
Maywood: empty menu button shows on mobile

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/themes#1813]
## Steps to replicate

1 - Create an empty menu
2 - Assign it to the main location
3 - Save your changes

## Result

The menu doesn't appear on the desktop as expected. However, a **Menu +** toggle button appears on mobile.

## Expected

I would expect the menu not to show on mobile if it's empty. Or at least, I expected the same behavior both on mobile and desktop.

* User report: #18589958-hc
* Follow-up ticket: None - we deactivated menu in chat

**Comment by nielslange** [comment]
@cecilearkay This issue had been reported in https://github.com/Automattic/themes/issues/1808 and I've created a PR for it in https://github.com/Automattic/themes/pull/1810. As Maywood is a child theme of the Varia theme, merging https://github.com/Automattic/themes/pull/1810 would solve the issue for the Varia and all it's child themes, thus, also for the Maywood theme. 😀

**Comment by cecilearkay** [comment]
Oops! Thank you @nielslange!

**Comment by nielslange** [comment]
No worries, @cecilearkay!

**Comment by scruffian** [comment]
I think this has since been fixed. Closing.
