### ISSUE TITLE
Twenty Nineteen: Layout Grid, in editor, flows offscreen to the left

### ISSUE THREAD

**Issue by spencerberry** [Automattic/themes#1816]
## Steps to replicate
1. Add a layout grid to a page
2. It immediately is placed off screen, to the left side:
![GridBLOCKtwenty19](https://user-images.githubusercontent.com/1162736/74976285-50ff2e00-53dd-11ea-913f-62c3e6bcb92b.png)
3. If you use another theme, like twenty twenty, it remains within the editor (same exact page, no changes)
![GridBLOCKtwenty20](https://user-images.githubusercontent.com/1162736/74976330-61afa400-53dd-11ea-9cfd-85c19736ebd5.png)

It looks fine on the live site, but makes it very hard to edit the content of the leftmost column block.

This is on Chrome 79, Mac 10.15.3

* User report: #18837997-hc
* Follow-up ticket: #2732105-zen

**Comment by kjellr** [comment]
I _believe_ this can be resolved by just syncing Twenty Nineteen on WP.com with the version in WordPress `trunk`. cc @allancole to take a look at and test.

**Comment by detlefholtz** [comment]
Is there any solution for non-AT sites? I have a Prem Plan site that is also having this issue.

**Comment by kjellr** [comment]
@danieldudzic synced WP.com up with the latest version of Twenty Nineteen. On its face, this Grid Block problem appears fixed: 

![Screen Shot 2020-04-03 at 9 35 49 AM](https://user-images.githubusercontent.com/1202812/78366893-35b44080-758f-11ea-8977-9e623c588b4a.png)

... however clicking into it introduces some issues: 

![Screen Shot 2020-04-03 at 9 42 54 AM](https://user-images.githubusercontent.com/1202812/78367071-8330ad80-758f-11ea-88ef-0a9eedf32806.png)

I'm not seeing this issue with any other blocks. I'm wondering if there's something special that the Grid block does that we need to hook into... cc @jasmussen or @allancole in case you happen to know a little about that?

**Comment by jasmussen** [comment]
Yes there's an onselect behavior to the grid that we need to remove.

It's editor only, and intended to make the side UI available, and with g2 that's no longer an issue. So we'll see about addressing that! Thanks for the ping.

**Comment by jeyip** [comment]
Hi @jasmussen. I'm currently organizing the maintenance backlog and wanted to check in. Is this issue still something that is being actively addressed?

**Comment by jasmussen** [comment]
> Is this issue still something that is being actively addressed by the team? If not, I'm happy to prioritize it on our board.

Hello @jeyip, thanks for the ping. I believe this ticket can be closed, because as of version 1.2.2 (or 1.2.1?) the Layout Grid block doesn't anymore have the onselect resizing that makes it bigger, as is shown in the screenshot.

However there's still a bug in TwentyNineteen itself, where all fullwide blocks are wider than the canvas, causing a horizontal scrollbar:

<img width="1222" alt="Screenshot 2020-06-24 at 07 55 02" src="https://user-images.githubusercontent.com/1204802/85506179-25d95500-b5f0-11ea-8089-67c97dfabae2.png">

That is not layout grid specific, but nevertheless worth fixing. @kjellr may know if there's already a fix underway.

**Comment by kjellr** [comment]
> there's still a bug in TwentyNineteen itself, where all fullwide blocks are wider than the canvas, causing a horizontal scrollbar

Yeah, that's likely the same issue that [we attempted to address here](https://core.trac.wordpress.org/ticket/49843) (but which never got merged). We need to get back on that before 5.5 is released, but I haven't had the time.

**Comment by jasmussen** [comment]
It would be nice to get fixed before 5.5, but even after the fact we can still push theme updates, right? Just as a buffer.

**Comment by kjellr** [comment]
Yeah, that's true — but it seems like a pretty annoying bug.

**Comment by jasmussen** [comment]
Yep, purely thinking of maintaining the human balance here. We all have stuff, these days.

**Comment by david-szabo97** [comment]
Hi @kjellr ! Do you know any updates regarding this?

Looks like fullwide blocks are still wider.
![image](https://user-images.githubusercontent.com/2256104/91990098-9bb91580-ed31-11ea-94fa-003352b02a69.png)

**Comment by kjellr** [comment]
This is fixed in core, but it doesn't look like the latest version of Twenty Nineteen hasn't been ported over to WP.com yet. cc @jeffikus

**Comment by jeffikus** [comment]
Will follow up on this.

**Comment by david-szabo97** [comment]
Just tested this again just to confirm this is still an on-going issue.

**Comment by Addison-Stavlo** [comment]
> This is fixed in core, but it doesn't look like the latest version of Twenty Nineteen hasn't been ported over to WP.com yet.

Testing now this **seems** to be fixed.  I cannot get the grid to flow off the screen no matter how i set it up or select it.  

Will close, but please feel free to test as well and re-open if there is still an issue.
