### ISSUE TITLE
Twenty Twenty: Base Font "Small Size" is larger than "Normal Size"

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#1817]
## Steps to replicate

- go to Design > Customize > Fonts 
- in Base Font, select any font style 
- under size, select "Normal Size" 
- then select "Small Size" (to compare) 

## Result

"Small Size" is larger than "Normal Size". 

Base font:  
- Normal: _2.1rem_
- Tiny: _0.72em_  
- Small: _1.26em_

**Normal Size:** 

<img width="1062" alt="Screen Shot 2020-02-22 at 2 49 39 PM" src="https://user-images.githubusercontent.com/36863633/75093515-b5a7bd80-5582-11ea-8e5a-66800cc439d5.png">

**Small Size:** 

<img width="1066" alt="Screen Shot 2020-02-22 at 2 49 53 PM" src="https://user-images.githubusercontent.com/36863633/75093511-aaed2880-5582-11ea-87ab-9a8690c87b4a.png">

**Screen recording:** https://recordit.co/sxb0ORqP35

## Expected

"Small Size" should be smaller than "Normal Size". 

* User report & Follow-up ticket: 2735618-zd

**Comment by kspilarski** [comment]
Same case for 2850284-zd.

**Comment by frostedechoes** [comment]
This bug caused me to just let my Wordpress.com account lapse and find another blogging platform. The default text size is so big on a desktop browser but you can’t make it small. It’s pretty bad that a font size bug on the flagship theme for this year just goes untouched.

**Comment by jacklenox** [comment]
A fix for this is currently under review: https://code.a8c.com/D51686

If all looks good I'll get this committed and deployed tomorrow.

**Comment by scruffian** [comment]
Fix deployed
