### ISSUE TITLE
Ixion: Widget background color issue

### ISSUE THREAD

**Issue by automattic-ian** [Automattic/themes#1819]
## Steps to replicate

set a custom color for the background. 

## Result

when setting a custom background color, the widgets remain a patchy white due to the following  `.footer-widgets .widget {
    background: 
    #fff;
    font-size: 16px;
    padding: 0;
}`

## Expected

color to be applied consistently. 

##Workaround

Thanks to the wonderful @kathrynwp the following css workaround can fix it. 

```
/* Footer widget background / xxxxx-hc kp */
.footer-widgets .widget {
  background: transparent;
}
```
* User report:  #12899259-hc

**Comment by nielslange** [comment]
@automattic-ian Good catch and I've just addressed this issue in PR https://github.com/Automattic/themes/pull/1825. 😀

**Comment by nielslange** [comment]
@automattic-ian This issue had been fixed and merged and you should be able to remove the custom CSS from the customers site again. 😉
