### ISSUE TITLE
AltoFocus: Homepage does not appear in IE 11

### ISSUE THREAD

**Issue by JessBoctor** [Automattic/themes#1827]
## Steps to replicate

-> On Windows 7, open IE 11
-> Navigate to https://altofocusdemo.wordpress.com/

## Result

-> The theme homepage is blank

![screenshot](https://d.pr/i/zSDAaG+)

-> As you scroll, your cursor changes as it comes across links, but clicking when the cursor changes does not lead anywhere

There is a screencast here: https://d.pr/v/IWwDwk

-> There is a `foreach` error in the JS console

![error](https://d.pr/i/rC39ON+)

## Expected

-> The home page should load as shown in the themes showcase

![expected](https://d.pr/i/2wc8A3+)

* User report: [#2733420-HC](https://woothemes.zendesk.com/agent/tickets/2733420)

**Comment by achyuthajoy** [comment]
@JessBoctor I've tried testing the demo site on a Windows 7 VM (Internet Explorer 11). The demo site loads fine for me.

**Comment by JessBoctor** [comment]
I am closing this since we will not be supporting IE 11 much longer anyways.
