### ISSUE TITLE
Publication: Blog Posts block overlaps with sidebar

### ISSUE THREAD

**Issue by spencerberry** [Automattic/themes#1828]
## Steps to replicate

1. Publish a page using the Blog Posts block.
2. Make sure you have a widget in both sidebars
3. Make sure you have a post published with enough text content to fill the row, or use the browser's inspector to notice that the blog content overlaps the sidebar:
![Screen Shot 2020-02-28 at 09 17 49](https://user-images.githubusercontent.com/1162736/75570109-5119b200-5a0b-11ea-95a3-4869933a638b.png)

I think it may be a conflicting class?
```
@media screen and (min-width: 1416px)
.entry-wrapper, .site-content, .site-header-inner, .site-info {
    width: 1320px;
}
```

* User report: #19028650-hc
* Follow-up ticket: #2751560-zd

**Comment by nielslange** [comment]
@spencerberry I've addressed this issue in https://github.com/Automattic/themes/pull/1831, thus, feel free to test the PR. 😉
