### ISSUE TITLE
Aperitive: Font change doesn't reflect in preview or live page

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/themes#1836]
## Steps to replicate

* Create or edit an existing page.
* Add some text in a paragraph block with say *Normal* font size.
* Preview the page or access the front end and observe the font size.
* Go to browser inspector and you'll see the *class has-normal-font-size* and the *font-size* attribute is struck out.
* Change the font size to say *Huge* from the block settings.

## Result

* Preview the page or access the front end. Note that the font size hasn't changed.
* Go to browser inspector and you'll see the class *has-huge-font-size* and the *font-size* attribute is still struck out.

## What happened.

* The font size change should have reflected in preview or on live site but it doesn't change.

## Expected

* Font size should change to reflect the change made.

## What you expected to happen.

* Font size should have changed to reflect the change made.

Note: I was able to duplicate this issue using the Aperitive theme on one of my test sites. This happens for both pages and posts.

* User report: #2754824-zen
* Follow-up ticket: NA

**Comment by nielslange** [comment]
@mriyazuddin This [theme had been retired](https://wordpress.com/theme/aperitive) and is not part of this repo. I'm afraid, this issue will not get fixed.

cc: @allancole

**Comment by cathymcbride** [comment]
retired theme. Closing...
