### ISSUE TITLE
Varia: Menu items with anchor links and submenu items have persistent unstyled submenus

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#1843]
## Steps to replicate
1. Install and activate Varia or any child theme. 
2. Add a few items to your primary menu. One of them should be a Custom Link with either a single # or a complete anchor link, and at least one submenu item. Publish your changes.
3. Head to the site and click on that menu item. 

## Result

The drop-down menu persists even after you move your mouse away, unless you click on the item again.

On some of the child themes, it's particularly apparent that the persistent drop-down isn't styled the same as the one that appears on hover. Hever and Morden are examples. 

Tested on WordPress.com Premium (Hever, Morden, Stow); WordPress.com Business (Morden, see user report); self-hosted (Varia). 

No images/video because I'm having trouble with screen capturing at the moment - I'll edit with images once that resolves. 

## Expected

The drop-down appears when the parent item is clicked on, but does not persist (or, if this is intentional, persists styled the way the hover version is).

* User report: #17888781-hc
* Follow-up ticket: #2773404-zd

**Comment by allancole** [comment]
> The drop-down menu persists even after you move your mouse away, unless you click on the item again.

The menu needs to persist here to allow for proper accessibility support. You can also click anywhere outside of the menu to collapse the dropdown. 

> On some of the child themes, it's particularly apparent that the persistent drop-down isn't styled the same as the one that appears on hover. Hever and Morden are examples.

Happy to take a look at these as individual design issues. Each child theme manipulates the Varia default styles differently. If you could file separate issues (with screenshots) it’ll help us isolate these issues to get them fixed more easily.

**Comment by goblinartificer** [comment]
Thank you, I'll file those separately!
