### ISSUE TITLE
"Hide Homepage Title" setting is ignored in editor

### ISSUE THREAD

**Issue by WunderBart** [Automattic/themes#1846]
Originated from https://github.com/Automattic/wp-calypso/issues/37509

## Steps to replicate

1. For your WP.com site set one of the themes that support the ["Hide Homepage Title"](https://github.com/Automattic/themes/blob/908d3df766691fa9294dd2868e3fdedf3dfe2401/varia/inc/wpcom.php#L35) setting, e.g. TwentyTwenty or any Varia-based one.
2. Go to Customizer > Homepage Settings and make sure that the "Hide Homepage Setting" is on.
3. Open your Homepage in the editor.

## Result

The Homepage title in the editor is still visible, even though it was set to be hidden.

## Expected

The Homepage title should be hidden in the editor when the "Hide Homepage Title" setting is on.

### Notes / Findings

Varia and a few other themes (e.g. TwentyTwenty, TwentyNineteen or Business) register the `hide_front_page_title` setting, which seems to be respected only in the front-end. It is not true for a WP.com site editor for a few different reasons.

For example in Varia, there is a [`hide-homepage-title` class added to the editor body](https://github.com/Automattic/themes/blob/908d3df766691fa9294dd2868e3fdedf3dfe2401/varia/inc/wpcom.php#L122), which is good, but the enqueued styles target class that is not there ([`.post-content__block`](https://github.com/Automattic/themes/blob/908d3df766691fa9294dd2868e3fdedf3dfe2401/varia/inc/style-editor-wpcom.css#L1)), leaving the title visible. I guess these styles are this way because [we're adding the `post-content__block` when the `dotcom-fse` is (was?) active](https://github.com/Automattic/wp-calypso/blob/8ba6796028f2d54ade7d828c021ff6042b4991b1/apps/full-site-editing/full-site-editing-plugin/dotcom-fse/blocks/post-content/index.js#L47). When exactly is that (sub)plugin active, @noahtallen?

In case of TwentyTwenty and other themes that support the setting, the `.hide-homepage-title` doesn't seem to be added and there are no styles that would hide the title in the editor.

~

The most optimal fix here seems to be updating the Varia styles to target correct class (possibly by removing the `post-content__block` step) and copying necessary parts to other, non-Varia based themes for consistent support. What do the theme experts think? 😄

**Comment by noahtallen** [comment]
> When exactly is that (sub)plugin active, @noahtallen?

When the simple site is stickered with `full-site-editing`, or was stickered with that when it was transferred to Atomic.

In practice, about 10% of sites created by new user accounts in the English locale between October and December 2019. (i.e. sites enrolled in the dotcom-FSE A/B test)

**Comment by jeffikus** [comment]
Tested with Varia + children, and Twenty Twenty, this seems to be fixed in https://github.com/Automattic/wp-calypso/pull/39702 above.
