### ISSUE TITLE
Sophisticated Business: Full Width Breaks Editor

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#1847]
## Steps to replicate

1. Create a new page
2. Add a Column block with 2 columns, add content on both
3. Set the Column block alignment to Full Width
4. Add a new Column block with 2 columns, add content on both
5. Select the Column block and Group it
6. Set the Group alignment to Full Width

## Expected

To be able to normally edit the page.

## Result

You can't edit the left column from the Column block anymore. All the content in there gets hidden on the left, you can't scroll to that area and even see the block's settings.

And for the Group block, the live page also doesn't have a left margin.

Here's what happens on the editor:

![SophisticatedBusiness1](https://user-images.githubusercontent.com/16104522/76409622-65e03900-636d-11ea-820b-e00eceacca67.png)

And here's what happens on the site:

![SophisticatedBusiness2](https://user-images.githubusercontent.com/16104522/76408991-8f4c9500-636c-11ea-8ace-48a80a691135.png)

* User report: #19306173-hc

**Comment by tijosh** [comment]
As a child theme of TwentyNineteen, I think this would be fixed when this issue closes: /Automattic/themes/issues/1816

@kjellr can you confirm if this is right?

**Comment by kjellr** [comment]
Yes, that's correct. 👍

**Comment by kjellr** [comment]
@danieldudzic merged the latest version of Twenty Nineteen into WP.com — would you mind re-testing? 

Thanks!

**Comment by carinapilar** [comment]
@kjellr, the issue still happens on the Sophisticated Business, maybe because it's a retired theme? Would it be possible to fix on it too?

I tested on the Twenty Nineteen theme and there's only one issue left with the Group block, it doesn't show a padding on the left in the editor, while it works on the site. It seems it's an issue on the editor though, since I was able to replicate on other themes. I'll report on the editor's GH.

**Comment by kjellr** [comment]
Thanks. I'm looking into this — turns out there's a larger issue with full alignment compatibility with the new Gutenberg UI changes in the plugin. It'll require a core patch, which I'm getting started now. Will keep this ticket up to date when that's submitted. 👍

**Comment by cathymcbride** [comment]
retired theme. Closing...
