### ISSUE TITLE
Lingonberry: Cookie banner cannot be dismissed on mobile Safari

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#185]
## Steps to replicate

View a free site with the theme active in Safari on an iPhone.
Try to dismiss the cookie banner by tapping the Close and Accept button

## Result

The banner cannot be dismissed

## Expected

That the banner can be dismissed.

I'm not able to replicate the issue in Responsive Mode in Safari on desktop, but @thesacredpath confirmed this in Safari on a iPhone 6S Plus, and a forum volunteer was also able to confirm on an iPhone 6.

* User report: https://en.forums.wordpress.com/topic/cookie-privacy-accept-button-on-mobile-view-not-working/
* User's site: https://tpsracingteam.wordpress.com/

**Comment by laurelfulford** [comment]
Fixed in r49017-wpcom-themes, and I added a comment to the forum thread.

**Comment by KokkieH** [comment]
Thank you!
