### ISSUE TITLE
Twenty Twenty: Comment box is left-aligned

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#1854]
As one can see below, the "Leave a reply" title is centered, but the comment box is not:

![image](https://user-images.githubusercontent.com/32492176/76547165-5b4b9f80-6452-11ea-9564-8a273e0e0c9a.png)

**Comment by tbradsha** [comment]
Reported in 19355308-hc.

Right now it has `margin: 0`, so here's a workaround to override that:

```
#respond form {
  margin: auto;
}
```

**Comment by lancewillett** [comment]
Hi @tbradsha — just to help speed up debugging reports like this, could you link to a live example? A URL of a test site is fine (not showing personal data from a customer).

I confirmed on https://twentytwentydemo.wordpress.com/2019/10/15/hello-world/ — theme demo site by turning on comments just for that one post.

<img width="1380" alt="Screen Shot 2020-03-12 at 14 51 26" src="https://user-images.githubusercontent.com/66797/76569691-f5224500-6470-11ea-82a9-827c6c992ed5.png">

**Comment by fresatomica** [comment]
Also reported here: https://wordpress.com/forums/topic/twenty-twenty-comment-box-alignment/

Apart from being left-aligned, if you're not logged in, the data also does not display correctly, example: https://basil83.wordpress.com/2020/04/05/%eb%8c%93%ea%b8%80-%ec%82%ac%ec%9a%a9%ec%97%90-%eb%8c%80%ed%95%98%ec%97%ac/

![Screen Shot on 2020-04-07 at 11-19-58](https://user-images.githubusercontent.com/40177971/78652263-cbb6d680-78c1-11ea-830f-7fd780152754.png)

**Comment by allancole** [comment]
This issue should be fixed on wpcom now. 

See here: r55847-wpcom-themes
