### ISSUE TITLE
Multiple: CoBlocks Button Styles Not Applied (Atomic)

### ISSUE THREAD

**Issue by tijosh** [Automattic/themes#1855]
## Steps to replicate

1. Activate affected theme on an Atomic site
2. Create a page and add a button
3. Apply the "3D" or "Shadow" effect to the button (CoBlocks extension)

## Result

The 3D effect is not applied

## Expected

The 3D effect is applied

Known themes affected based on testing:

- Lodestar
- Libre 2
- Shoreditch
- Publication

* User report: #19447738-hc

**Comment by tijosh** [comment]
CSS workaround:

```
.is-style-3d .wp-block-button__link {
box-shadow: inset 0 -3px 0 0 rgba(0,0,0,0.25);
}
```

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
