### ISSUE TITLE
Hever: AMP errors while adding a new post or page

### ISSUE THREAD

**Issue by pranali333** [Automattic/themes#1857]
## Summary

- The user is getting AMP errors when adding a new post or page to the site from Automattic themes.

Parent theme: https://wordpress.com/theme/varia

Child theme: https://wordpress.com/theme/hever

- User's query:

>It say there is a java script error an that it is in the <body> tag and from the
files in the Varia template
>It doesn't affect the site layout or anything and is the only error currently.
>I found this section in Varia functions.php at lines 278-280

- User is getting below error:

Screenshot 1: https://d.pr/i/rWPz85
Screenshot 2: https://d.pr/i/swB4oi

- User is using Standard Template Mode (WP Admin > AMP > General).

* Follow-up ticket: [2800043-zen]

Thanks!

**Comment by jordesign** [comment]
As we've since had a new version of the AMP plugin, and multiple updates to the Hever and Varia themes - I'm going to close this single instance issue. If we get more reports of something similar we can re-evaluate.
