### ISSUE TITLE
Varia & Varia Child Themes: Jetpack Related Post Margin Broken

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/themes#1862]
Related Posts are appearing on the far left for sites using the Varia theme or a Varia Child theme from WordPress.com.

This was previously reported and resolved for Twenty Twenty on https://github.com/Automattic/jetpack/issues/14020

However, this will need to be fixed on the theme side as suggested on https://github.com/Automattic/jetpack/issues/15089#issuecomment-602748851

## Steps to replicate

1. Activate Varia or a Varia child theme on a self-hosted or WordPress.com Business plan site (with hosting configuration features enabled).
2. Go to `/wp-admin/admin.php?page=jetpack#/traffic` or My Site > Tools > Marketing > Traffic and ensure that Related posts are activated
3. Ensure your site has posts to populate the related posts module.
4. View a post, see error.

## Result
Related posts are to the left due to the margin styles for `#jp-relatedposts`

## Expected
For the related posts to be centered.

#### Screenshot
![image](https://user-images.githubusercontent.com/4887830/77342066-05a2ad00-6d06-11ea-8266-d8a57984c7e5.png)

## WordPress.com Themes Impacted (edited by @nielslange)

- [x] Varia → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Alves → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Balasana → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Barnsbury → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Brompton → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Coutoire → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Dalston → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Exford → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Hever → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Leven → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Mayland → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Maywood → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Morden → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Redhill → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Rivington → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Rockfield → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Shawburn → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Stow → may be fixed with https://github.com/Automattic/themes/pull/1885
- [x] Stratford → may be fixed with https://github.com/Automattic/themes/pull/1885

* User report: 19193605-hc
* Follow-up ticket: 2802653-zen

**Comment by nielslange** [comment]
@JoshuaGoode Given the fact that my weekend just started and I don't have any travel plans, I'm more than happy to work on this issue. 😀

**Comment by nielslange** [comment]
@JoshuaGoode I totally missed the points that the listed themes are all Varia child-themes. Therefore, if PR https://github.com/Automattic/themes/pull/1885 for Varia gets merged, all child-themes will be fixed as well. Thus, this issue was way less effort than expected. 😁BTW, feel free to test https://github.com/Automattic/themes/pull/1885.

**Comment by ivan-ottinger** [comment]
Hey everyone! 👋 I have had several users encountering this issue. Do we know when it could be fixed? Thanks so much!

**Comment by scruffian** [comment]
This no longer seems to be an issue. I think this line fixes it:

https://github.com/Automattic/themes/blob/trunk/varia/sass/blocks/utilities/_style.scss#L64
