### ISSUE TITLE
Hever: Homepage button hyperlink not updating properly

### ISSUE THREAD

**Issue by annezazu** [Automattic/themes#1863]
## Steps to replicate

Video: https://cloudup.com/czNMwJk0Syh

- Create a new site on WP.com
- Select the Hever theme
- Edit the homepage and try to change the button hyperlink in place
- If you change they hyperlink using the block "Link Settings", the hyperlink doesn't update. The previous hyperlink remains in place. 

## Result

Hyperlink was not properly updated. 

## Expected

Hyperlink would be updated using the block's "Link Settings" section.

**Comment by annezazu** [comment]
Update: this happened with a CTA action on a different page as well. This seems to be a problem with general CTA.

**Comment by jordesign** [comment]
Can no longer recreate this error - Call to action buttons now correctly update to the new URL
