### ISSUE TITLE
Scratchpad: List Block too far left in the editor

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/themes#1866]
Tested in both Safari and Chome.  

## Steps to replicate

1. Activate the **Scratchpad theme** on any site
2. Create a Page or Post and add a **List block** to it 
3. Resize the browser window to be wider and watch the list items cling to the left side of the page or post like this https://d.pr/v/sprTM0

## Expected

I expect the List block to be indented a bit to right in the editor like it shows the list on the live page here: https://d.pr/i/Hjzdwr 

* User report: [#19697351-hc]
* Follow-up ticket: [#2818536-zd]

## Other affected themes (added by @nielslange)

- [x] Affinity → may be fixed with https://github.com/Automattic/themes/pull/1870
- [x] AltoFocus → may be fixed with https://github.com/Automattic/themes/pull/1871
- [x] Apostrophe 2 → may be fixed with https://github.com/Automattic/themes/pull/1872
- [x] Canard → may be fixed with https://github.com/Automattic/themes/pull/1873
- [x] Dara → may be fixed with https://github.com/Automattic/themes/pull/1874
- [x] Intergalactic 2 → may be fixed with https://github.com/Automattic/themes/pull/1875
- [x] Ixion → may be fixed with https://github.com/Automattic/themes/pull/1876
- [x] Karuna → may be fixed https://github.com/Automattic/themes/pull/1877
- [x] Libretto → may be fixed with https://github.com/Automattic/themes/pull/1878
- [x] Publication → may be fixed with https://github.com/Automattic/themes/pull/1879
- [x] Rebalance → may be fixed with https://github.com/Automattic/themes/pull/1880
- [x] Toujours → may be fixed with https://github.com/Automattic/themes/pull/1881

**Comment by nielslange** [comment]
@ash1eygrace I've fixed this issue on https://github.com/Automattic/themes/pull/1867, thus, feel free to test it. 😀

**Comment by ash1eygrace** [comment]
Hey there! Thanks for working on this! Looks like the issue is only happening with unordered lists now and works properly with numbers lists. Here's another video: https://d.pr/v/vvhb2q

**Comment by mikeicode** [comment]
@nielslange This issue also happens in the 'Apostrophe 2' theme, do we need a new issue for that or will this fix resolve both?

![img](https://d.pr/i/IBygMx+)

**Comment by nielslange** [comment]
@mikeicode Thanks for pointing this out. https://github.com/Automattic/themes/pull/1867 only addresses the issue for the Scratchpad theme. I'll check all other themes, to see which other themes are affected by this issue and will create separate PRs for the other themes, so that they can be merged independently.

**Comment by kjellr** [comment]
@danieldudzic would you mind reviewing these PRs from @nielslange when you have a moment? Looks like they're all the same fix, so should be pretty quick.

**Comment by eduardozulian** [comment]
Just got one of the affected users on a ticket now. Pinging @danieldudzic in case we can review those PRs.

Thank you!

**Comment by KristinaKay** [comment]
This was reported here: [#2818536-zd] and the ticket placed on hold. Came back around so posting here to close the loop.

**Comment by allancole** [comment]
This issue is getting _auto-closed_ as I merge all these related PRs. After they’re all merged to master I’m going to re-open the issue and close it only _after_ the code is deployed to Dotcom.

**Comment by allancole** [comment]
This issue is now fixed and deployed on Dotcom. 

Closing this issue :-)
