### ISSUE TITLE
"Social Menu" RSS icon on all URLs with string "feed"

### ISSUE THREAD

**Issue by ezebecke** [Automattic/themes#1869]
## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

Add a social menu item with a URL containing the word `feed` somewhere on the slug. Example: https://instagram.com/testfeed/ or https://twitter.com/feedtest

## Result

![Screen Shot 2020-03-26 at 22 26 43](https://user-images.githubusercontent.com/24919469/77718436-f1cea380-6fb0-11ea-930a-03a982a6013b.png)

Instead of the social network icon, the RSS feed icon appears.

## Expected

To see the social network icon. 

![Screen Shot 2020-03-26 at 22 30 19](https://user-images.githubusercontent.com/24919469/77718653-76212680-6fb1-11ea-9052-b688027348dc.png)

* User report: #19672577-hc
* Follow-up ticket: #2822148-zd

I couldn't figure out if it's a Jetpack issue. Pardon me if this needs to be reported on Jetpack.

**Comment by nielslange** [comment]
@ezebecke This issue is caused by Jetpack, thus, I moved your reported issue to https://github.com/Automattic/jetpack/issues/15162. Thanks for reporting this issue, though. 😉
