### ISSUE TITLE
Varia: Unclosed brackets in SCSS

### ISSUE THREAD

**Issue by nathanhannig** [Automattic/themes#1883]
## Steps to replicate

Trying to use the Prepos editor to process the Sass files for the Stow theme, however, it reports errors with the SCSS files under Varia theme.

Line 44 & 45
https://github.com/Automattic/themes/blob/master/varia/sass/components/pagination/_next-previous.scss

Line 21 & 22
https://github.com/Automattic/themes/blob/master/varia/sass/vendors/woocommerce/components/_pagination.scss

## Result

Error, expected ")".

It is not properly closing the calc() method.

## Expected

No errors

**Comment by nathanhannig** [comment]
If you can also explain to me how is the Stow theme's CSS file build properly if the Valia theme has these issues?

**Comment by nathanhannig** [comment]
@nosolosw  ... Informing most recent PR author, though issue is not your fault

**Comment by nielslange** [comment]
@nathanhannig I just addressed this issue in https://github.com/Automattic/themes/pull/1884. This problem affects the Varia theme and all its child themes as seen on https://wordpress.com/theme/varia, thus, also the Stow theme. 

> If you can also explain to me how is the Stow theme's CSS file built properly if the Valia theme has these issues?

On my end, when running `npm run build` within the Stow theme folder, the CSS files of the Stow theme are generated including the closing brackets. Do you see the missing brackets within the Stow theme CSS files on your end?

**Comment by pwvpwv** [comment]
Awesome, I do not see the missing parenthesis in the css file, interesting that the npm build can handle this without throwing an error. Something must be correcting it before processing.

I will have to give the npm build steps a try. I just found out I could also use Prepos app to also build the css file yesterday so still new to it all :)

**Comment by nathanhannig** [comment]
Awesome, I do not see the missing parenthesis in the css file, interesting that the npm build can handle this without throwing an error. Something must be correcting it before processing.

I will have to give the npm build steps a try. I just found out I could also use Prepos app to also build the css file yesterday so still new to it all :)

**Comment by nielslange** [comment]
I’m not familiar with https://prepros.io/, but ‘npm‘ is not too complicated and gives you more control than any app. I can strongly recommend learning the basics of ‘npm‘. 😉
