### ISSUE TITLE
TwentySeventeen weird header image position on frontpage (depending on use of posts/static page)

### ISSUE THREAD

**Issue by cabotine** [Automattic/themes#1887]
I am currently working on a blog for my students and I am using twenty seventeen.
My goal is to place a transparent image in the header on the frontpage. (the problem also exists without the added image).

Now twenty seventeen shows some funny behaviour (in safari 10  under ios 10.3 on a ipad) when you set it on show a static page as a frontpage (path2in.uni-bremen.de/example.png).
There is no problem when you use the posts (path2in.uni-bremen.de/exampleb.png) instead of a static page.

Expected behaviour 
It should look the same wether you use posts or static page for your frontpage.

Dont know where there right place to post this issue is. Posted it also on:
https://wordpress.com/forums/topic/twentyseventeen-header-image-scrolling-issue-on-safari-on-ipad/

**Comment by nielslange** [comment]
Hello @cabotine 👋 Thanks for reporting this issue. As the Twenty Seventeen theme is a so-called core theme, it's best to create a ticket for this issue directly via https://make.wordpress.org/core/reports/. A core developer can then pick it up and address this issue. This repository here is specifically for WordPress.com themes, not for WordPress.org core themes. 😀
