### ISSUE TITLE
Alves: Set Site Content Top Padding to Zero on Smaller Screens

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#1889]
## Steps to replicate

Open a page (with or without Page Title visible) on a mobile device (with small screen size).

## Result

See substantial and unnecessary padding at the top ( `32px` for a Page with no title visible such as Homepage and `64px` for Pages with a title visible).

![Alves_32px](https://user-images.githubusercontent.com/39308239/78030785-eee20300-7362-11ea-9a14-8bd8e4032aac.png)

![alves_64px](https://user-images.githubusercontent.com/39308239/78030801-f6091100-7362-11ea-9e47-0b71d867f08b.png)

## Expected

See zero padding at the top ( `padding-top: 0px`) as it unnecessarily shifts the main content down. The menu already has enough padding at the bottom.

![Alves_0px](https://user-images.githubusercontent.com/39308239/78030826-fe614c00-7362-11ea-94f3-cc0e0276191c.png)

#dogfooding #testing

**Comment by nielslange** [comment]
@zdenys I've created a PR for this issue in https://github.com/Automattic/themes/pull/1892, thus, feel free to run a test. 😀

**Comment by zdenys** [comment]
Thank you so much @nielslange! I have never tested PRs. Is there any guidance that would help me get started?
