### ISSUE TITLE
Dara: Author name in Authors widget is center aligned only if author has written posts.

### ISSUE THREAD

**Issue by brezocordero** [Automattic/themes#190]
## Steps to replicate

Add authors widget on a site that is using Dara and has authors with posts and without posts.

## Result

Alignment of author's name is centered on Author's name with posts because it is a link. Author's names without posts are left-aligned.

![screen shot 2018-07-07 at 08 53 10](https://user-images.githubusercontent.com/8002881/42407862-39f47082-81c3-11e8-83c9-77bcc869bc95.png)

## Expected

Same alignment.

* User report: #1265454-zen
* Follow-up ticket: #1265454-zen
* User's site: footer on https://highlanderherald.wordpress.com

**Comment by alaczek** [comment]
Hi! The issue is fixed now on the user site.
