### ISSUE TITLE
Coutoire: Provide Fixed Header Option

### ISSUE THREAD

**Issue by damiannep** [Automattic/themes#1901]
The Coutoire theme provides a scrolling header. This sometimes results in text over text.

Screenshot from Demo:

![screenshot](https://d.pr/i/CUfXXf+)
*Full link: https://d.pr/i/CUfXXf*

We've had a request from a user to add an option to make the header fixed. We can use CSS, but that's no an option with plans below Premium.

Request in 2848772-zen

**Comment by ianstewart** [comment]
This has also popped up as an issue when we use Coutoire as a blog theme in onboarding flows. There's a related issue in https://github.com/Automattic/themes/issues/1838 as well.

It doesn't seem unexpected that someone would pick it and then be surprised by the scrolling effect in the same way it doesn't seem unexpected for someone to pick the theme and then be delighted or intrigued by it. In other words, I can see the choice there being valuable for a user. (I think in the future I'd expect that to be an option on a header template parts in Gutenberg.)

I think it makes sense when it's used as a blog theme to have this turned off by default. And in more artistic or fashion-oriented settings to have it on by default but with the option for people to turn it off.

I think there are two solutions to getting that. The first is forking and relaunching the theme so there are literally two options to pick from for both users and our onboarding flows.

But for another option, I know in similar instances in the past we've back-ported options by …

1. Introducing an option in the theme via the customizer. 
2. Checking, in functions.php, if the theme has been used before by looking at options or theme mods.
3. If the theme has not been used before setting one option as a default and if the theme has been used before leave that setting as is. 

That would let users (and onboarding flows) use the defaults they think are best for the content they add to their sites. I believe there's prior art for that solution in our theme repo(s)?

**Comment by kjellr** [comment]
> But for another option, I know in similar instances in the past we've back-ported options by …
> 
> 1. Introducing an option in the theme via the customizer. 
> 2. Checking, in functions.php, if the theme has been used before by looking at options or theme mods.
> 3. If the theme has not been used before setting one option as a default and if the theme has been used before leave that setting as is. 

This seems like a reasonable option to me.

**Comment by tbradsha** [comment]
21076172-hc:
>I would really like to get rid of the sticky menu
>the header with my website name, it is static. so when you scroll down the page you can always see it

**Comment by tbradsha** [comment]
Another case in 23609687-hc.

This CSS is a possible workaround (color and border can be changed as desired):
```
.site-header {
  background-color: rgba(255,255,255,0.9);
  border-bottom: 1px black solid;
}
```

**Comment by kriskarkoski** [comment]
I had another case in https://mc.a8c.com/support-stats/happychat/transcript.php?id=25181071

**Comment by KokkieH** [comment]
Another request in https://wordpress.com/forums/topic/how-i-can-fix-moving-logo-and-tag-line-along-the-post-page/

**Comment by antonis** [comment]
Hello 👋 ,
We reproduced this issue when previewing home page designs on mobile.
Leaving this comment here to close the [related mobile issue](https://github.com/wordpress-mobile/gutenberg-mobile/issues/3045) when this is fixed.

**Comment by kjellr** [comment]
@scruffian this is a longstanding request that would be great to take care of. I think it has a general path forward, [as described here](https://github.com/Automattic/themes/issues/1901#issuecomment-630361066). This would be a change similar to those header updates to Varia themes from late last year — it would introduce a new option and would only apply to new sites.

**Comment by scruffian** [comment]
I'll add to the list

**Comment by soderlind** [comment]
@scruffian is it still on the list? .. or is a fix soon available (on worpress.com)?

**Comment by scruffian** [comment]
It's still on the list (it's a long list!) I hope we'll get to it soon.

**Comment by Aurorum** [comment]
PR for this issue in #4041 - it seeks to implement @ianstewart's recommendations above. :)

**Comment by aisajib** [comment]
Another request here: https://wordpress.com/forums/topic/making-a-heading-unsticky/?view=all

**Comment by csonnek** [comment]
Another report here: https://wordpress.com/forums/topic/rossies-go-roaming-title-moves-with-text-on-tablet/?view=all

**Comment by scruffian** [comment]
We looked into this and it would be too difficult to maintain backwards compatibility. Let's close as wontfix.
