### ISSUE TITLE
Sub menus not working on IE11

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#1906]
## Steps to replicate

URL: cjcphotophotography.wordpress.com
Theme: Maywood

PROBLEM:
According to the user, the nav bar drop down menus don't work on IE 11 and Edge but it does work on other browsers like Chrome and Firefox

WHAT I FOUND:
* Tested on Browserstack. Drop downs don't work on  IE 11 but do on Edge for me.

* User report: #19157818-hc (please note the original thought they had a different "retired" theme but when I checked it was Maywood not Wayfarer)
* Follow-up ticket: #2855286-zd

**Comment by ChrisCrowley2020** [comment]
Your answer that the drop down Submenus from the Navigation Block worked for you on Edge confused the heck out of me, since they were definitely still NOT working for me...
     But I believe that I have puzzled out the more complete answer that I needed:   Even though I updated Windows 10 just last January, I checked yesterday that the MS Edge installed on both my desktop and laptop was Version 44.  Until digging for possible updates yesterday, I was totally unaware that  a.) Edge has been massively reworked in about the last 6 months  (e.g. Version 81) & b.) that updates to Edge no longer occur automatically with Windows updates, as in the past.  After manually downloading & updating to Edge Version 81, the drop down menus do indeed work, just as you report.
     Knowing what I know now, I'm OK.  But I wonder how many other people could really use this information about Edge and were never alerted?

**Comment by cathymcbride** [comment]
User upgraded browser which fixed the issue. Closing.
