### ISSUE TITLE
Syntax: Menu button hidden behind large custom header image

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#191]
## Steps to replicate

In the Customizer, add a custom header for the site.

In the cropping step, crop the image to have a much higher height than the suggested dimensions

## Result

The image appeared as it was cropped, obscuring the menu button in the process. The button only becomes visible after some amount of scrolling.

![tamara_jefferies___freelance_copywriter__editor__playwright___inform__uplift__encourage__give_hope_](https://user-images.githubusercontent.com/11873759/42418333-04ea2d9c-829e-11e8-8838-6e561aa89c88.png)

## Expected

For the menu button to be pushed down below the header image, or for the image to still display at the custom header dimensions for this theme of 2500 × 250 pixels, regardless of how it was cropped.

* User report: Discovered while investigating https://en.forums.wordpress.com/topic/custom-menu-problems/
* User's site: https://freelancementalhealthandspiritualitycopywriter.wordpress.com/ - also confirmed on a test site.

**Comment by alaczek** [comment]
This is a bit of an edge case - the theme does recommend using images 250px high. At it's core, this seems to be a z-index issue - the header has z-index of 100, while the toggle button is 98. If we swap z-index around, things will look a bit off though, with the button overlapping the title. So we'd need to move the site title a bit to make some space.

![image](https://user-images.githubusercontent.com/4550351/50810804-98546780-135f-11e9-9b93-156b694cc151.png)

As a side note, the customer deleted the blog, and we had no other reports of this issue.

**Comment by alaczek** [comment]
Given the age of the theme, and the isolated nature of the issue, I'm suggesting a `wontifix`.

**Comment by laurelfulford** [comment]
I agree with @alaczek - given the age of the theme, the fact the original reporter no longer has a site, and that it only happens when the header is taller than recommended, it makes sense to wontfix this one.
