### ISSUE TITLE
Baskerville 2: FOUT (Flash Of Unstyled Text) for Site Title When Choosing A Custom Font

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#1911]
## Steps to replicate

For the Headings choose a font different from the default one in **WordPress.com > My Sites > Design > Customize > Fonts**

Visit the site and observe the site title. 

## Result

The default font appears briefly before loading the chosen font. 

https://d.pr/v/7gs7Xz

## Expected

See the chosen font loading directly.

It could be resolved with some custom CSS but on Personal and lower Plans it's not possible.

* User report: 2855398-zen
* Follow-up ticket: 2855398-zen

**Comment by kathrynwp** [comment]
I don't think this is a theme-specific issue, FOUT is an issue everywhere with the older Customizer-based Font panel.

**Comment by zdenys** [comment]
@kathrynwp Do you think it's best to move it to https://github.com/Automattic/wp-calypso then? I haven't tested it with all the themes that have the older Customizer-based Font panel. But if it applies to all of such older themes, it may actually belong here in my understanding, am I missing something?

**Comment by kathrynwp** [comment]
It's not a Calypso either either, as the Customizer is not part of Calypso.

FOUT affects all implementations of the old Fonts panel in the Customizer. As this method was phased out in favour of the newer Global Styles, I don't think it's going to be revisited, so I don't think it needs to be reported anywhere.

**Comment by kathrynwp** [comment]
See also 247-gh-custom-fonts

**Comment by zdenys** [comment]
Considering the above, I'm closing this one as a `wontfix`.
