### ISSUE TITLE
Hever: drop-down menu styling

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#1912]
## Steps to replicate

1. Make a drop-down menu with an anchor link (mine are blank) as the parent item. 
2. Click on the parent item, then move away from the drop-down. 

## Result

The appearance of the drop-down changes when hovered over. There's a GIF [here](https://d.pr/i/y5dbwb).

## Expected

The drop-down stays consistent with theme styling while it's open.

## Notes

It looks like the theme has different styling for `.main-navigation > div > ul > li > .sub-menu` (white background, shows up without hover) and for `.site-header .main-navigation > div > ul > li:hover li > a` (blue background, shows up on hover).

This was originally #1843 but is theme-specific :) I'm working my way through the other Varia child themes - let me know if reports for each one that does this is actually helpful, or I can make a note in the comments of this issue (or just leave it if it's intended)!

**Comment by jordesign** [comment]
Can no longer recreate this behaviour - so closing this issue
