### ISSUE TITLE
Baskerville 2: Infinite Scroll Does Not Work On Atomic Sites

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#1914]
## Steps to replicate

1. Activate Infinite Scroll on an atomic site with the Baskerville 2 theme active.
2. Set the blog to display a small number of posts per page under Settings → Writing (I set it to 2).
3. Publish enough posts that they don't all load when you visit the blog at first (I needed 11 posts published).
4. Scroll down to trigger infinite scroll.

## Result

New posts did not load. Instead, a spinning loading icon appears but never loads the posts. Screenshot:

![image](https://user-images.githubusercontent.com/30727666/79060969-6eaa8e80-7cce-11ea-9c8b-fcacfe007906.png)

## Expected

I expected more posts to load.

* User report: #8050904-hc
* Follow-up ticket: [shortlink to ticket, ie #2868698-zd

**Comment by kathrynwp** [comment]
I also mentioned this here, not sure if it's related: 
https://github.com/Automattic/jetpack/issues/15348#issuecomment-612243418

**Comment by jeherve** [comment]
This is indeed most likely the same Jetpack issues. Do you think you could test with the "Bleeding edge" option set in the Jetpack Beta plugin? This issue has already been fixed in the development version of Jetpack, so that should help.

Let me know how it goes!

Internal reference: p9F6qB-53N-p2

**Comment by kathrynwp** [comment]
Thanks @jeherve - "bleeding edge" with Jetpack Beta (8.5-alpha-353-g35d8b21) fixed the issue in Baskerville 2 on a localhost test site.
