### ISSUE TITLE
Varia-based themes: Submenu items of Submenu items appear on same level as parent

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#1915]
If you create a submenu item with its own submenu items, the submenu's child items appear at the same level as the parent instead of on the next level.

## Steps to replicate
1. Activate Rockfield (or Maywood or Dalston)
2. Add several menu items
3. Make two levels of submenus under one of the items as shown here: 
![screenshot](https://d.pr/i/bORwS7+)
Image URL: https://d.pr/i/bORwS7
4. Save your menu

## Result
The two submenu items, **Jellyfish** and **Sailing**, displayed at the same level as their parent **First Child**:

![screenshot](https://d.pr/i/pyRTDn+)
Image URL: https://d.pr/i/pyRTDn

## Expected
I expected the two submenu items, **Jellyfish** and **Sailing**, to be accessible only by clicking on the parent **First Child**.

## Temporary CSS fix:

This will add some space indentation for nested items.

```
.main-navigation > div > ul ul {
    padding-left: 20px;
}
```

* User report: 2867430-zd

**Comment by formosattic** [comment]
+1 3619592-zd-woothemes

Updated main post with a temporary CSS fix.

**Comment by mikeicode** [comment]
I've had multiple requests for the sub-sub menus, it'd be nice to improve how this works. Themes like Dara, Didi, Twenty Twenty have actual sub-sub menus.

30778340-hc

**Comment by Robertght** [comment]
This is no longer an issue from my testing.
