### ISSUE TITLE
Syntax: Menu button unresponsive with ads enabled on the site.

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#192]
## Steps to replicate

View theme on a free site that's set to public, so that ads will be shown on the site.

Try to click the menu button

## Result

Nothing happens when clicking the menu button.

## Expected

For the menu to appear.

The loading indicator in my browser also kept spinning no matter how long I viewed the site, so suspecting it might be related to #108, I tried disabling ads on the site. The page immediately reloaded, and with ads disabled the menu button works correctly. Also confirmed on a test site.

* User report: https://en.forums.wordpress.com/topic/custom-menu-problems/#add-note
* User's site: https://freelancementalhealthandspiritualitycopywriter.wordpress.com/

**Comment by laurelfulford** [comment]
I haven't been able to recreate this on my test site with ads, but it seems similar -- the theme's using `$(window).on('load')` for the menu, which was the bit we had to change in fixing the themes in #108. I'm going to circle back and try recreating it again in a bit!

**Comment by desnum** [comment]
A customer with the Syntax theme is seeing both a perpetual loading wheel in the browser tab, and his menu won't open on Firefox and Safari, though both issues appear to be a non-issue in Chrome and IE. He has a free site with no custom CSS, and no plugins (so no plugin incompatibilities)

Links:

- Ticket: 514487-zen
- Slack chat: p1540500875000100-slack-themes (includes a screenshot)
- Theme: https://wordpress.com/theme/syntax
- User's Site: https://wallywoodministries.com/

crunnells theorizes:

> "There's an issue with certain JS implementations, where the ads code prevents the page from ever "finishing" it's loading, so the `onload` JS event never fires. Which is probably what initializes the menu"

Also, there are some warnings in the web developer console

## Steps to replicate

1. Open https://wallywoodministries.com/ in Firefox
2. Make sure you don't have adblock on

## Result

When the ad is displayed, the tab is perpetually loading and the site menu will not open.

## Expected

The menu should still open. The page should finish loading.

**Comment by laurelfulford** [comment]
I'm still unable to recreate this issue, in Firefox, Safari or Chrome, with adblockers disabled.

It looks like the first site reporting has been deleted, and the second is not showing ads for me at all (though it's possible they were turned off as a work-around!). 

On a test site, I was able to get ads showing with Syntax, but the menu worked as expected in Safari and Firefox: 

https://cloudup.com/cvsSdXmECc1

@KokkieH or @desnum, are you still able to recreate this problem on other sites?

**Comment by KokkieH** [comment]
@laurelfulford not able to replicate on my test site any more either, so looks like whatever was causing this has been fixed.

**Comment by laurelfulford** [comment]
Thanks @KokkieH! I'll close this up then - we can always reopen if this mysterious issue returns! :)
