### ISSUE TITLE
Canard: Blog Posts blog shows black boxes in grid view

### ISSUE THREAD

**Issue by yamphoenix** [Automattic/themes#1926]
## Steps to replicate

1. Activate the Canard theme.
2. Publish some posts and add the featured image.
3. Create a page and add the Blog Posts block. Select Grid View for the block.
4. In the grid view, black boxes display below the features images. And the post excerpt is jumbled up.

## Result

Black boxes below featured image - 
![Black box](https://d.pr/i/3zYhiV+)

Post excerpt jumbled up-
![jumbled](https://d.pr/i/kbuTfQ+)

[Link to video screencast of the issue](https://d.pr/v/kFdpi0)

## Expected

The Blog Posts Block to appear properly.

* Site: http://shrimpchips.blog
* Follow-up ticket: #2882677-zen

**Comment by goblinartificer** [comment]
I've been working with this user. The reason this happens is that Canard has this: 

```
/* Post Thumbnail */
.post-thumbnail {
	background: #000;
	display: block;
	height: 100%;
	position: relative;
	width: 100%;
```


That `height: 100%` sets the thumbnail in the Blog Posts block to 100% of the allocated height for the entire `.post-has-image` element in the Blog Posts block, causing the black box and the gnarly overlap.

A quick fix (not for this user as they're not on Premium) is `.post-thumbnail {
    height: auto;
}`

**Comment by AtrumGeost** [comment]
Got another report here: 2938357-zen (The CSS fix is not an option here since they have the Personal plan)

**Comment by mikeicode** [comment]
Same issue 3202552-hc they are also on Personal so can't use CSS.

**Comment by JoshuaGoode** [comment]
Encountered on 21445670-hc

**Comment by kspilarski** [comment]
Same case as 23068267-hc. Follow-up ticket at 3190375-zd.

**Comment by jonnyruzek** [comment]
25110116-hc

**Comment by MaggieCabrera** [comment]
Related to https://github.com/Automattic/themes/issues/2504

**Comment by MaggieCabrera** [comment]
Reported this to the block repo in order to get a more global fix https://github.com/Automattic/newspack-blocks/issues/618

**Comment by scruffian** [comment]
Since this is an issue in the Newspack block, I'm going to close this issue.
