### ISSUE TITLE
Canape: Testimonial Archive Page Title not Translated

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/themes#1928]
## Steps to replicate

1. Start with a site using the Canape theme, that has at least one testimonial created to generate the testimonial archive page ( e.g https://happyash.co/testimonial <-- My test site)
2. Change the language of the site (via wp-admin > Settings ) to any language other than English

## Result

The title of the Testimonial Archive Page https://happyash.co/testimonial does not translate on the live site. It stays in English. Also, the correct translation of the title shows in the customizer, but the live site is not translating.

Video demonstrating the translation in the customizer vs. the live site: https://d.pr/v/cI1bjr

## Expected

I expect the title to be translated into the site's language settings selected in wp-admin. 

Tested with other themes and the language of the Testimonial archive page translates as expected. Also, I tested multiple languages in the wp-admin, including Spanish, French, and Italian, none of which translate. 

* User report: hc-20040401
* Follow-up ticket: #2858965-zd

As a temporary fix I gave them the following CSS to hide the page's title and replace it with the correct translation:

```
/* Hide & add custom title on Testimonial page */
.post-type-archive-jetpack-testimonial .entry-title{
display: none;
}
.post-type-archive-jetpack-testimonial #testimonials::before{
content: "Témoignages";
font-size: 3.6rem;
}
/* end */
```

**Comment by nielslange** [comment]
@ash1eygrace The testimonials title can be edited within the Customizer via 

`{SITE-URL}/wp-admin/customize.php → Testimonials → Testimonials Archive Title`

<table>
<tr>
<td>Backend:
<br><br>

![#1928-backend](https://user-images.githubusercontent.com/3323310/79985710-39275180-84d5-11ea-9ada-f4dff497650c.png)
</td>
<td>Frontend:
<br><br>

![#1928-frontend](https://user-images.githubusercontent.com/3323310/79985704-375d8e00-84d5-11ea-93eb-9be6fe32b664.png)
</td>
</tr>
</table>

I looked up the site as mentioned in #2858965-zd and saw that the title had been corrected within the customizer. When removing the CSS code, the title as provided within the customizer becomes visible then.

**Comment by ash1eygrace** [comment]
> The testimonials title can be edited within the Customizer via

Wow! That was hidden well! :laughing: I'll check after my chat shift and let the customer know! Thanks!

**Comment by ash1eygrace** [comment]
Checked and it indeed works! Thanks for the TIL! :) I must have missed it since it was in a different language!
