### ISSUE TITLE
Independent Publisher 2: Logo on mobile theme not resizing correctly

### ISSUE THREAD

**Issue by Jstachurski** [Automattic/themes#193]
## Steps to replicate

The user has uploaded a .png image for their logo and it looks great on desktop and tablet view. However, when viewed on mobile, the .png isn't resizing correctly and is hanging over the background image.

http://cld.wthms.co/mXBNuJ

## Expected

The image should be resizing to fit the screen but not being cut off. 

I provided the user with some custom CSS that fixes it for now:

`@media screen and (max-width: 480px) {
	.custom-logo {
		max-width: 250px;
	}
}`

http://cld.wthms.co/cZBaWU

* User report: #1267583-zen

* User's site: https://pocketchronicles.com/

**Comment by alaczek** [comment]
This fixes it for both users. @Jstachurski I used a different method to solve this, but your CSS can be left in place.
