### ISSUE TITLE
Twenty Twenty: Overlapping comment form fields for logged-out users

### ISSUE THREAD

**Issue by jeryj** [Automattic/themes#1934]
## Steps to replicate

* Create a site  on WPcom with Twenty Twenty
* Go to a post in an incognito window so you are logged out
* Try to leave a comment

## Result

* Comment fields are overlapping
* "Notify me of new comments via email" checkbox is a line instead of a normal checkbox input

**Live example:** https://oaktest.blog/2019/11/20/example-post/

<img width="890" alt="Screen Shot 2020-04-17 at 3 38 15 PM" src="https://user-images.githubusercontent.com/967608/79867473-03368000-83a4-11ea-98b0-f1ac85c3b7c5.png">

## Expected
* Form fields should be laid out nicely and able to be selected with the cursor

Mentioned here: https://github.com/Automattic/themes/issues/1854#issuecomment-610276689

**Comment by mrsjaved** [comment]
another report here #2902068-zen

**Comment by rezzap** [comment]
Another report in 2897064-zen where the fields can't actually be selected. Replicated this in Chrome and Firefox and also in Firefox and Internet (Samsung browser) on a Samsung Tab A.

**Comment by allancole** [comment]
This issue should be fixed on wpcom now. 

See here: r55847-wpcom-themes
