### ISSUE TITLE
Varia: Support Search block better

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1936]
Search block needs some love in Varia and the child themes.

It looks unstyled in the editor.

<img width="485" alt="Screenshot 2020-04-22 at 16 59 37" src="https://user-images.githubusercontent.com/908665/80004795-ada0c700-84ba-11ea-80c9-8f3988c13a18.png">

When the block is set to centre-aligned, only the label becomes centre-aligned and everything stays the same in the editor.

<img width="883" alt="Screenshot 2020-04-22 at 17 02 39" src="https://user-images.githubusercontent.com/908665/80005162-1b4cf300-84bb-11ea-96f5-4695e4aacc6f.png">

One the front of the site, the block is centred, but the position of the label is odd.

<img width="707" alt="Screenshot 2020-04-22 at 17 03 58" src="https://user-images.githubusercontent.com/908665/80005463-83033e00-84bb-11ea-90e5-962c309816be.png">

cc @ianstewart @alaczek

**Comment by danieldudzic** [comment]
Fixed via #3986
