### ISSUE TITLE
Radcliffe 2: Social Icons Block display incorrect when alignment is set

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#1941]
## Steps to replicate

Add a Social Icons block to a post or page using Radcliffe 2, and set a left or right alignment for the block

## Result

The social icons will be shown stacked in a column instead of as a row:

[![Left Alignment](https://d.pr/i/isZqgs+)](https://d.pr/i/isZqgs)

[![Right Alignment](https://d.pr/i/0iLnmn+)](https://d.pr/i/0iLnmn)

## Expected

The icons would be shown the same way as the default alignment, but aligned to the right (if right alignment is selected):

[![Default Alignment](https://d.pr/i/RHrXB3+)](https://d.pr/i/RHrXB3)

The following CSS can be provided to fix the issue:

```
/* fix social links icon block display when block is aligned to the right or left | #XXXXXX-hc/zen */
.wp-block-social-links[class*="align"] {
	display: flex;
}
```

* User report: #20512744-hc

**Comment by nielslange** [comment]
@edequalsawesome I applied your suggested CSS code and the fix works as expected. Feel free to test the PR https://github.com/Automattic/themes/pull/1942 to see if it works on your end as well. 😀

**Comment by kathrynwp** [comment]
I noticed this same issue happening in Fortune, a premium theme, as well. Since it's affecting multiple themes, wonder if this should be fixed in the block itself rather than patching individual themes?

**Comment by kjellr** [comment]
Looks like this happens when a theme has defined a `display` property for aligned items ([like Radcliffe 2 does here](https://github.com/Automattic/themes/blob/0bff9da40595b98a294ac48b51fca73aa772b028/radcliffe-2/style.css#L985)). Fortune probably needs its own patch to fix it. 👍
