### ISSUE TITLE
Apostrophe 2: Featured image display issue on Blog Posts block

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#1943]
This theme has an option in the Customizer to hide the featured images on pages. This causes an issue if you add the Blog Posts block to a page and choose to display the featured images in the block, the images won't display on the page because of the setting in the Customizer.

## Steps to replicate

* Make sure the featured image setting is off in the Customizer
* Add a Blog Posts block to a page, choose to display featured images
* View published page

![img](https://d.pr/i/iWYqMj+)

## Result

* Featured images do not display on the page within the block

Images display in admin:

![img](https://d.pr/i/E0czIl+)

Images hidden on page:

![img](https://d.pr/i/hqJgwh+)

## Expected

* Featured images should display on the page within the block

* User report: 20553869-hc

**Comment by Aurorum** [comment]
I believe that this is a wider issue being tracked in Automattic/newspack-blocks#399

**Comment by sophiegyo** [comment]
I suspect this is a theme issue, not a Newspack/Blog Posts block issue. We've replicated it on another site that uses the Latest Posts block too:

[Screenshot here](https://d.pr/i/yck9sF)

User report - 3313909-zen

**Comment by sophiegyo** [comment]
EDIT: This is definitely a theme issue, not a block issue - I didn't even notice but this report concerns the Latest Posts block instead. When I realised, I tested the Blog Posts block instead - same result. 

Here's another report in 3875159-zen

Block in the editor: https://d.pr/i/ezXPrg
Block on the front page with Apostrophe 2 active (notice the missing image in the HTML): https://d.pr/i/NDGODJ
Block on the front page in the Customizer (same missing image in the HTML)

To compare with any other theme where the featured images are fine - 

Dalston in the Customizer preview (try & customize): https://d.pr/i/KwzXpW
Altofocus, as it's a similar classic theme: https://d.pr/i/ipyNs1
Penscratch 2: https://d.pr/i/Qj0737
