### ISSUE TITLE
Cubic: Cookie Banner div remains after accepting cookies.

### ISSUE THREAD

**Issue by BrookeDot** [Automattic/themes#197]
In the Cubic theme the main `.widget_eu_cookie_law_widget` div remains on top of the action bar making it difficult to get to the action bar actions.

## Steps to replicate
1) Select Cubic as your theme on a site where the Cookie Banner will appear (for example a Free WordPress.com site)
2) Try to click on the action bar three-dot menu. Notice you can't. So far so good based on `z-index`
```
.widget_eu_cookie_law_widget {
    z-index: 50001;
}

div#actionbar {
    z-index: 50000;
}
```

3)  Accept and close the Cookie Banner. 

4) Try to click on the action bar and notice you can only click in the very bottom.

5) Inspect the element and notice that `.widget_eu_cookie_law_widget"` div still appears on top of the action bar.

![peek 2018-07-11 18-22](https://user-images.githubusercontent.com/150348/42607759-61747156-8539-11e8-885c-cfbe7633c9b9.gif)

## Result
Action bar items difficult to click on. 

## Expected
For Cookie Widget to be hidden. 

--- 
* User report: https://en.forums.wordpress.com/topic/edit-button-works-no-longer/
* Slack discussion: p1531358351000216-slack-ads
* User's site: https://sherlockgosig.wordpress.com/

cc: @rclations

**Comment by thesacredpath** [comment]
Also posted to Jetpack: https://github.com/trewknowledge/GDPR/issues/209

I added a link to this issue to the Jetpack issue as well.

**Comment by rclations** [comment]
After looking into this further, I think it's something we can fix on the widget side of wpcom.
Patch in review at D16045-code

**Comment by alaczek** [comment]
@rclations I tested your fix, and it's working as expected for me. Not sure if you need more reviewers or not.

**Comment by rclations** [comment]
thanks @alaczek! Just deployed 👍

**Comment by KokkieH** [comment]
Reopening as it appears this is not fixed yet:

1. Open site, https://sherlockgosig.wordpress.com/
2. Try using action bar - action bar completely unresponsive
3. Dismiss cookie banner
4. Try using action bar again - now it works
5. Click through to single post
6. Try using action bar - action bar again completely unresponsive
7. Return to home page
8. Try using action bar - action bar still unresponsive

**Comment by rclations** [comment]
There's some padding on the widget div that's overlapping the action bar.

```
@media screen and (min-width: 768px)
.widget {
    padding-bottom: 48px;
}
```

**Comment by laurelfulford** [comment]
Thanks for reopening this @KokkieH! 

I can recreate this issue.

**Comment by cathymcbride** [comment]
Still an issue, but action bar can be used. The hit target is small and offset. Since this is a workaround, and no further comments since 2018, setting pri to low

**Comment by Robertght** [comment]
I cannot replicate this anymore. Closing
