### ISSUE TITLE
Lodestar: Masonry block showing a bullet list on Front Page Panel

### ISSUE THREAD

**Issue by formosattic** [Automattic/themes#1973]
Issue happens only on atomic sites.

The Masonry block looks fine on the page itself:
<img width="1166" alt="Screen Shot 2020-05-04 at 11 28 01" src="https://user-images.githubusercontent.com/15944096/80934343-5d9afc00-8dfa-11ea-9bf2-d5803cb64628.png">

When the page is set as one of the front page panel, the Masonry block will show in a bullet list format:

<img width="610" alt="Screen Shot 2020-05-04 at 11 29 26" src="https://user-images.githubusercontent.com/15944096/80934386-87ecb980-8dfa-11ea-8b54-f4f8915b1b10.png">

* User report: #2942709-zd

**Comment by ktyfuller604** [comment]
I have a report of the issue here - 21204817-hc

**Comment by eduardozulian** [comment]
Another case in 3452552-zen . More info in p2EDhh-1c0-p2

As a workaround, I think we can use this code shared by @Nic-Sevic:

```
.blog .coblocks-gallery--item {
    float: left;
}
```

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH

cc @jeffikus
