### ISSUE TITLE
Dyad 2: Headstart Does Not Match Theme Demo

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#1977]
## Steps to replicate

Headstart a site with the Dyad 2 theme

## Result

The site is populated with one demo post about cars.

## Expected

I expected the site to look like the demo site here: https://wordpress.com/theme/dyad-2

i.e. https://dyad2demo.wordpress.com/

* User report: #17702437-hc
* Follow-up ticket: none needed.

**Comment by blackjackkent** [comment]
I looked some into this today and tried to generate a new annotation for Dyad based on the demo site. It crashed with a bunch of errors (mostly relating to none of the demo site's posts having block editor content and most of the images being too big). I'm assuming this means this will entail a more manual approach so I will take a look into that tomorrow.

**Comment by kwight** [comment]
@blackjackkent Connect with @sixhours too if you're getting blocked at all, she has experience with annotations.

**Comment by sixhours** [comment]
> I looked some into this today and tried to generate a new annotation for Dyad based on the demo site. It crashed with a bunch of errors (mostly relating to none of the demo site's posts having block editor content and most of the images being too big). I'm assuming this means this will entail a more manual approach so I will take a look into that tomorrow.

I've run into this, too. I skipped the preflight checks with `--skip-preflight-check` when generating new annotations because I'm not planning to import the huge images or do a complete 1:1 copy of the demo, I just cherry pick the elements I want to add to the existing annotation from the generated file.

**Comment by blackjackkent** [comment]
Thank you for the help, @sixhours !

Diff open at D61635-code for this update.

**Comment by sixhours** [comment]
Annotations were deployed in D61635-code
