### ISSUE TITLE
Goran:  Slideshow theme/text is different on site to Reader

### ISSUE THREAD

**Issue by markx2** [Automattic/themes#198]
## Steps to replicate

https://workforsc.org/2018/07/11/one-website-so-much-information/

You will see black text on the slideshow

https://wordpress.com/read/feeds/52737987/posts/1921421381

You will see white text on the slideshow

Site is on the Personal plan, so no CSS involved.

* User report: #4966818-hc
* Follow-up ticket: needs doing
* User's site: see above.
![white](https://user-images.githubusercontent.com/7057656/42637917-3d23b914-85e4-11e8-9ae7-c7aecb98134f.png)
![black](https://user-images.githubusercontent.com/7057656/42637927-4205f8c0-85e4-11e8-8716-a59759c33131.png)

**Comment by alaczek** [comment]
Fixed in r49060-wpcom-themes -- I matched the styling on the site to the one in the reader.
