### ISSUE TITLE
Twenty Eleven: YouTube embeds not showing in columns on Chrome

### ISSUE THREAD

**Issue by fresatomica** [Automattic/themes#1980]
## Steps to replicate

1. Create a post with two columns
2. Add YouTube embed to one of the columns

## Result
The video displays correctly on Firefox, Safari and Opera:
![Screen Shot on 2020-05-05 at 12-36-40](https://user-images.githubusercontent.com/40177971/81057681-2e08f400-8ecd-11ea-8cb1-db553f5c5812.png)

The video flashes briefly and white space is displayed on Chrome
![Screen Shot on 2020-05-05 at 12-32-50](https://user-images.githubusercontent.com/40177971/81057497-ce124d80-8ecc-11ea-9401-d90c71b51fb0.png)

## Expected

The video should be displayed across all browsers.

* User report: https://wordpress.com/forums/topic/youtube-videos-invisible/

**Comment by KokkieH** [comment]
Did you test this on a self-hosted site as well? As Twentyeleven is a default theme, bug reports should go to the Core trac on WordPress.org, unless the issue is definitely specific to WordPress.com only.

**Comment by fresatomica** [comment]
I clicked the link to report the bug directly from Super Admin menu.
But I think I might have been in too much hurry in opening this issue. I was now trying to reproduce this and I'm not able to. I'll close this for now as there seems to be more factors at play.
