### ISSUE TITLE
P2: Text disappears when checklist items in comments are edited

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/themes#1981]
## Steps to replicate

This report refers to the p2 checklist syntax (`o`) and occurs in posts/comments created with the classic or block editor. Example checklist:

```
o Item 1
o Item 2
o Item 3
```

1. In a comment on a p2 post, add a checklist (like the example above).
2. Click on one of the checklist items.
3. Select "Edit."
4. Notice that the checklist item text disappears.

![p2-checklists](https://user-images.githubusercontent.com/8658164/81077126-77187280-8ee4-11ea-9e47-e421591216ac.gif)

## Result

When I add a checklist to a p2 post, editing a checklist item works as expected. The item's text is retained and I can make changes to it.

However, when I add a checklist to a p2 comment, editing the checklist item erases all the item's text content.

## Expected

I expect that when I add a checklist to a p2 post or comment, I will be able to click on each checklist item and edit the text.

Source: Dogfooding/testing (no external report)
Tested on macOS 10.15.4, Chrome 81.0.4044.129.

**Comment by nielslange** [comment]
Hello @rachelmcr 👋 This repo only contains the free Automattic themes which can be found on https://wordpress.com/themes/free. I moved your report over to https://github.com/Automattic/o2/issues/190 and will close this issue here for now. Thanks for reporting this issue though! 🙏

**Comment by rachelmcr** [comment]
@nielslange This issue occurs on any site using the P2 theme (available at https://wordpress.com/theme/p2-breathe) which is why I filed it here.

**Comment by nielslange** [comment]
Thanks for clarifying this, @rachelmcr. I've just reopened this issue.

**Comment by cathymcbride** [comment]
retired theme. Closing...
