### ISSUE TITLE
Varia: Font size are different between in the editor and the front of the size 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1984]
Gutenberg 8.0 landed in WP.com, and now the font size presets don't seem to be respected on the front of the site.

<img width="2502" alt="Screenshot 2020-05-06 at 02 43 52" src="https://user-images.githubusercontent.com/908665/81132031-f2aa0c00-8f44-11ea-8592-6c78f16b5843.png">

**Comment by jffng** [comment]
Tested and verified the font sizes when set via presets now match in the editor and front.
