### ISSUE TITLE
Independent Publisher 2: No visual indication of links in the editor.

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/themes#1986]
## Steps to replicate

With the theme Independent Publisher 2 activated, open any page or post, and add a link to some words. 

## Result

Once the link is added, there is no visual representation of the link in the editor indicating that a link was added to the page/post. 

## Expected

I expect the linked words in the editor to change to the color blue and have a visual indication that there's a link on the page/post. 

Video of what happens: https://d.pr/v/onD374

* User report:  #20887007-hc
* Follow-up ticket: 2951059-zd

**Comment by ash1eygrace** [comment]
After some further testing, this is only happening on my .com site. It works as expected on my self-hosted pressable site.

**Comment by nielslange** [comment]
Related to https://github.com/Automattic/themes/issues/1990 and reported in https://github.com/WordPress/gutenberg/issues/22221

**Comment by kjellr** [comment]
Thanks for the report! This is fixed in Gutenberg, and will be sorted out when WordPress.com migrates to the next release. 👍 https://github.com/WordPress/gutenberg/issues/22221#issuecomment-626667480
