### ISSUE TITLE
Twenty Seventeen: No ability to set fonts as "base font" in the Customizer if site is in Hebrew

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/themes#1987]
This was found when helping a WordPress.com user with a site on the Premium plan, set to Hebrew as the site language. They are using the Hebrew font “Alef”, on the theme Twenty Seventeen.

Here is the odd stuff going on:
- The fonts on the site which are selected in the customizer are “Alef” for Heading and Base Font: 
![Screen Shot on 2020-05-06 at 14-33-15](https://user-images.githubusercontent.com/31009008/81216955-d12f3b80-8fa9-11ea-8f34-a26465ead191.png)
- The site is not able to use the font for base fonts, only Headings. You see this in the customizer when actually using the font picker - it’s not changing at all on the site preview.
- The CSS stylesheet for the theme is overriding the selected base font with Arial Hebrew, which can be seen in the Chrome Inspector here:
<img width="1178" alt="Screen Shot on 2020-05-06 at 16-09-31" src="https://user-images.githubusercontent.com/31009008/81223483-0ccf0300-8fb4-11ea-9e40-2a625faf518f.png">

@kjellr mentioned the following in a chat in Slack:

> This looks like a WP.com-specific issue — I imagine it actually exists with all the recent default themes....
> The long answer is that most of the recent default themes incorporate language-specific font fallbacks for non-latin fonts. They rely on checking for a html tag that has that language attribute, and update to match. On WP.com, looks like our custom font styles don’t override that. 

* User report: #2945352-zen

**Comment by kathrynwp** [comment]
Noting that since this issue can't be replicated on a self-hosted site – because the Fonts panel in the Customizer is a WP.com-specific feature – I won't be opening a corresponding issue in Core Trac.

In addition, since the ability to change fonts site-wide in newer themes was moved into Global Styles, since there's only been a single report on this issue, and since the user was provided with a CSS workaround (see below), I'm going ahead and closing this as a wontfix.

```
/* Setting font "Alef" as the base font on the site #2945352-zen DP*/
html[lang=he-IL] body, html[lang=he-IL] button, html[lang=he-IL] input, html[lang=he-IL] select, html[lang=he-IL] textarea { 
    font-family: "Alef",sans-serif;
}
```
