### ISSUE TITLE
Argent: Blog Post block doesn't display "grid view" properly

### ISSUE THREAD

**Issue by xpurichan** [Automattic/themes#1989]
## Summary

The Argent theme doesn't display the blog post block's grid view. It will only display the posts in the list view, even if we select the grid view option.

Screenshot of how this appears (properly) in the editor when using the Argent theme:
https://d.pr/i/4sDHHj

Screenshot of how this appear when we preview/visit the page on the Argent theme:
https://d.pr/i/wqJwBq

## Steps to replicate

1. Activate the Argent theme
2. Create a new page and add the "Blog Posts" block to it
3. You can choose "list view" or "grid view" in the setting icons which appear above the block, note what each view looks like
4. Select the "grid view"
5. Save the page and preview or view it on the website, note how it's still being displayed in "list view" despite your selection.

## Result

The blog posts block will only display list view on the Argent theme, even when the grid view option is chosen.

## Expected

Argent should display the grid and list views properly, since both are an option for this block and the display works correctly in the post editor.

* User report: #20920771-hc
* Follow-up ticket: #2955164-zd

**Comment by rinazrina** [comment]
Another user report: #3159635-zen

**Comment by MaggieCabrera** [comment]
This should be fixed by the block. Reported here: https://github.com/Automattic/newspack-blocks/issues/619

**Comment by scruffian** [comment]
Since this is an issue in the Newspack block, I'm going to close this issue.
