### ISSUE TITLE
Libretto: Swiping over gallery on mobile opens slideshow

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/themes#199]
## Steps to replicate
When viewing a site using the Libretto theme on any page containing a gallery (homepage with post containing a gallery, single post, single page) swiping on top of the gallery opens the slideshow/lightbox as if the image has been tapped. Confirmed on my iPhone 8 in Safari. The margin on this theme is quite narrow, so this issue makes it quite hard to scroll down the page on mobile when a gallery is present. 

I also tested on Twenty Sixteen and Independent Publisher 2 and was not able to replicate it on those. 

The issue can be seen on my test site currently at https://k2testblog.wordpress.com (home page and /gallery)

![img_1072](https://user-images.githubusercontent.com/1900444/42646498-0a7f8f7a-85cf-11e8-9f73-22eaa0c644c1.jpeg)

![img_1073](https://user-images.githubusercontent.com/1900444/42646504-0df6b6d8-85cf-11e8-8f25-e762e3e15950.jpeg)

## Result

Swiping on top of the gallery opened the slideshow, instead of just scrolling down the page.

## Expected

To be able to scroll down the page over the gallery without the slideshow opening

* User report: #1256158-zen
* User's site: https://zlatarnicerodic.com/nausnice/

**Comment by laurelfulford** [comment]
I can recreate this with Libretto; I also tried Twenty Sixteen, and I can't recreate it even when I'm mashing my fingers all over the gallery when I scroll. I can't be certain without most testing, but that makes me wonder if something else in Libretto is causing this, not just the narrow margins?

**Comment by KokkieH** [comment]
This is still a problem - had a new report in https://en.forums.wordpress.com/topic/photos-issue/, and I can replicate in Chrome and Firefox on Android.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- I tested this with an iPhone 13 and Chrome, Firefox and Safari and I couldn't replicate it. 
- As there have been no further reports since Dec 2019, I'm closing this. Please reopen if reocurrs.

📌 ACTIONS
- Closed as could not replicate, please reopen this issue if it reoccurs
