### ISSUE TITLE
Hever: CORS error due to incorrect Google Fonts URL requested

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#1994]
## Steps to replicate

Open Hever theme demo and view the CSS CORS error:
![image](https://user-images.githubusercontent.com/32492176/81421495-cfcb5380-910e-11ea-95d8-e34f5f90ab96.png)

Despite the CORS message, the real issue is that the URL is over-encoded. It's requesting this URL:
`https://fonts.googleapis.com/css?family=PT%2BSans%3A400%2C400i%2C700%2C700i&subset=latin%2Clatin-ext`

But instead should be requesting this:
`https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&subset=latin,latin-ext`

* User report: 2946904-zen

**Comment by aleone89** [comment]
Another report in hc-30663567
Theme: Exford

**Comment by jordesign** [comment]
Unable to recreate this in the Exford or Hever theme demos
