### ISSUE TITLE
Twenty Twenty: PDF Embed Height Is Too Short

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/themes#1995]
## Steps to replicate
- In the block editor, paste the URL to a PDF onto a new line. (example: https://cldup.com/bdjeA9IaTO.pdf)
- Publish and view the page/post

## Result
- The result will  be a short embed that makes it difficult to read the pdf content.

![image](https://user-images.githubusercontent.com/3505172/81437920-82141280-9131-11ea-9b5e-f1b13842fb5e.png)

## Expected
- The embed window should be taller. Here is the same page with the Barnsbury theme enabled:

![image](https://user-images.githubusercontent.com/3505172/81438087-cbfcf880-9131-11ea-98db-123822f804cd.png)

* User report: 20888924-hc

* Follow-up ticket: 2954316-zd

**Comment by danieldudzic** [comment]
I'm closing this in favor of: #1919
