### ISSUE TITLE
Penscratch 2: links in block editor aren't visually differentiated from normal text

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#1996]
## Steps to replicate
Add a link to some text in the block editor.

## Result
It's impossible to tell what is a link (there's no underline and no color change).

Block editor:
![image](https://user-images.githubusercontent.com/32492176/81476249-2350a680-91ce-11ea-96cc-aad37699766e.png)

Live site:
![image](https://user-images.githubusercontent.com/32492176/81476257-2b104b00-91ce-11ea-9ac5-5edee29e7357.png)

* User report: 20927794-hc

**Comment by nielslange** [comment]
Related to #1990 and reported in WordPress/gutenberg#22221

**Comment by nielslange** [comment]
@tbradsha I forgot to mention that if this issue appears on an AT site, deactivating Gutenberg will solve this issue for now. 😉

**Comment by kjellr** [comment]
Thanks for the report! This is fixed in Gutenberg, and will be sorted out when WordPress.com migrates to the next release. 👍 https://github.com/WordPress/gutenberg/issues/22221#issuecomment-626667480
