### ISSUE TITLE
Twenty Fifteen: Padding missing in form block phone field [input type=tel]

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/themes#1998]
## Steps to replicate

1. Create a new post on the site using Twenty Fifteen theme.
2. Add a form block and add the fields like Name, Tel, email address.

## Result

You'll see that the input field with [input type=tel] has a lesser vertical height compared to all other fields. This seems like the theme CSS is missing this specific input type field where it declares the padding for the form fields. 

![download (1)](https://user-images.githubusercontent.com/40609190/81487668-117a0c80-927d-11ea-9dcd-e9ad4bb02940.png)

<img width="423" alt="Screenshot at May 10 05-15-00" src="https://user-images.githubusercontent.com/40609190/81487684-3d958d80-927d-11ea-882d-b7d4247bd4ba.png">

## Expected

Expected all the form fields to be of the same height, checked a few other themes and they give expected result.

* User report: 20876716-hc
* Follow-up ticket: 2949870-zen

**Comment by kathrynwp** [comment]
Looks like this issue with the Jetpack contact form in Twenty Fifteen is no longer present. I was unable to replicate on a self-hosted site, so going ahead and closing this.

Twenty Fifteen 3.2 
WordPress 6.0.1
Jetpack 11.1.2
No other plugins active

Screenshot:
![Self-hosted_Test](https://user-images.githubusercontent.com/7662449/181082078-42e6a81c-6b59-4fb7-ad7c-d1a6da79377d.jpg)
