### ISSUE TITLE
All Themes: improve the visual appearance of contact forms

### ISSUE THREAD

**Issue by designsimply** [Automattic/themes#2]
Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Pages.
1. Add a page with a form containing each field type and publish it.
1. View the page on the front end.

<strong>Result:</strong> forms come out looking pretty crappy/poorly designed/laid out, especially where radio buttons are involved.

![screen shot 2018-02-14 at wed feb 14 10 20 24 am](https://user-images.githubusercontent.com/1119271/36219946-41231d12-1176-11e8-98e5-361b358a2d5a.png)
<sup>Seen at https://design5279.wordpress.com/contact-form-test/ (Dara theme) using Firefox 58.0.2 on macOS 10.13.3</sup>

/hat tip 🤠 @beaulebens for reporting this issue at p4k3M4-2uX-p2. #dogfooding #painpoint

**Comment by sixhours** [comment]
I'm going to take a stab at some minor stylistic improvements to radio buttons/checkboxes in our active themes.

**Comment by sixhours** [comment]
Illustratr looks good; leaving this out of my updates.

**Comment by sixhours** [comment]
All themes have been updated, with the exception of the Twenties.
