### ISSUE TITLE
Pique: no styline for input[type="tel"]

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#200]
Have a Pique user on WordPress.org that reported that when they inserted a contact form using Contact Form 7, and included a Telephone field, that field had no styling. Since the Jetpack Contact form doesn't have a Telephone field type, I suspect we just didn't think of adding it.

Can we please add `input[type=’tel’]` to the theme's CSS on a future update? It could be added in a future update for something else since I don't see this as a high priority issue.

* User report: [https://wordpress.org/support/topic/contact-form-7-tel-field-no-css-formatting/#post-10489248](url)
* User's site: [http://www.mrburrows.com.au/contact/](url)

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
