### ISSUE TITLE
Varia/Mayland/Barnsbury: Video block alignment issues

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#2004]
## Steps to replicate

With the Barnsbury theme activated, add a video block.
Set the alignment on the video block to full width. 

## Result

1) the video goes left aligned in the preview
2) the toolbar control buttons go missing
Recording: https://d.pr/v/BSKiVV

(Similar issue when set to wide width.)

## Expected

I expected the video to go full width.
I expected to still get the toolbar to be able to change the alignment options.

* User report: #21046785-hc
* Follow-up ticket: #2968979-zd

**Comment by alaczek** [comment]
I could replicate the same issue with Mayland, so I suspect this might be the case for all Varia child themes.

**Comment by danieldudzic** [comment]
This seems to be working fine now.

<img width="1559" alt="editor" src="https://user-images.githubusercontent.com/905781/107636664-416f9980-6c6d-11eb-88cd-30304a1f81d9.png">
<img width="1302" alt="front" src="https://user-images.githubusercontent.com/905781/107636673-43d1f380-6c6d-11eb-9b77-7f724bb8edb6.png">
