### ISSUE TITLE
Stow: Bold styles are not properly applied

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#2006]
## Steps to replicate

1. Add some text inside the editor
2. Apply bold styles to parts of the text and publish/update
3. Compare the editor and the result/front-end

## Result

The theme uses a "bolder" style that won't be as thick as the "bold" style. In the following video you'll notice that applying the "bold" style makes a big difference:

![Screen Capture on 2020-05-12 at 17-12-55](https://user-images.githubusercontent.com/3696121/81751149-75b2f100-9474-11ea-8776-8e4cde018ddd.gif)

For the test, I used the Libre Baskerville font that makes the issue more evident.

## Expected

For the bold style to look the same both in the editor and on the published page/post

* User report:  20755481-hc

**Comment by nielslange** [comment]
@AtrumGeost This issue had been fixed with https://github.com/Automattic/themes/pull/1814 on February 19, 2020, but hasn't been reviewed and merged yet.

**Comment by AtrumGeost** [comment]
Thank you @nielslange, in that case, I'll mark this bug as closed :)

**Comment by zdenys** [comment]
I just wanted to report another case where it was brought up by the user 3049581-zen. Looking forward to seeing it fixed in https://github.com/Automattic/themes/pull/1814
