### ISSUE TITLE
Varia & Varia Child Themes: Comments author avatar size issue

### ISSUE THREAD

**Issue by deepaklalwani97** [Automattic/themes#2009]
## Steps to replicate

Check the comments section of any post in AMP mode and check the author's avatar.

## Result

Comment author avatar size is enlarged on the AMP page. Also, the reply link is also not working because of the overlying image.

![81372719-ae6f6500-9118-11ea-81b1-7c48c1fe8fa5](https://user-images.githubusercontent.com/1139853/81587707-0a661200-93d5-11ea-9e31-f244daa967a2.png)

## Expected

Gravatar size should be the same as the Non-AMP version. Refer to the screenshot below.

![81372899-19b93700-9119-11ea-8e79-ff4e6751d4bb](https://user-images.githubusercontent.com/1139853/81587726-1225b680-93d5-11ea-93ec-5056e7b7fe1b.png)

## Status of theme compatibility
Issue exists on all the following themes. 
- [x] Varia
- [x] Maywood
- [x] Exford
- [x] Shawburn
- [x] Alves
- [x] Balasana
- [x] Barnsbury
- [x] Coutoire
- [x] Dalston
- [x] Hever

**Comment by allancole** [comment]
Same as #2011, In the future, when you find a systematic Varia issues like this, it’s a little cleaner to solve these in a single PR with separate commits that address each theme. Thanks!
