### ISSUE TITLE
Varia & Varia Child Themes: Interpolation issue in WooCommerce password strength padding style

### ISSUE THREAD

**Issue by mangesh** [Automattic/themes#2011]
## Issue

The padding is missing around the error message.
There is an Interpolation issue in `password-strength-meter` style. It produces incorrect CSS for padding on `woocommerce-password-strength` class because of incorrect interpolation in SASS files.

## Result

Missing passing and invalid style rule. Please check the following screenshot.

![before-2](https://user-images.githubusercontent.com/246559/81593615-574de680-93dd-11ea-9143-bdf6732beeec.png)

## Expected

Correct padding and style rule.

![after-2](https://user-images.githubusercontent.com/246559/81593687-7187c480-93dd-11ea-87d0-5dcbf617ce8e.png)

## Status of theme compatibility

The issue exists on all the following themes. 

- [x] Varia
- [x] Maywood
- [x] Exford
- [x] Shawburn
- [x] Alves
- [x] Balasana
- [x] Barnsbury
- [x] Coutoire
- [x] Dalston
- [x] Hever

**Comment by allancole** [comment]
Hi @itowhid06 and @mangesh, thanks for contributing here! 

I’m going to go ahead and merge the many PRs that fix this issue. 

In the future, when you find a systematic Varia issues like this, it’s a little cleaner to solve these in a single PR with separate commits that address each theme. Thanks!

**Comment by allancole** [comment]
Re-opening this issue to re-compile _all_ the child themes with this interpolation improvement.
