### ISSUE TITLE
Twenty Fifteen: List block misaligned in the Block editor

### ISSUE THREAD

**Issue by fstath** [Automattic/themes#2013]
## Steps to replicate

Insert a List block and enter a few items.

## Result

The list is misaligned. Gets far to the left of the editor window. However, when saving the post and visiting the site, the list is correctly aligned.

Misaligned list in the Block editor:
![Screenshot 2020-05-14 at 2 29 36 PM](https://user-images.githubusercontent.com/32326882/81929938-84beae00-95f0-11ea-8729-d195b21eb665.png)

Correctly aligned when viewing the published post:
![Screenshot 2020-05-14 at 2 31 03 PM](https://user-images.githubusercontent.com/32326882/81929995-999b4180-95f0-11ea-9bd4-16a80e6e6b4b.png)

## Expected

For the list to be aligned with the rest of the blocks.

* User report: https://wordpress.com/forums/topic/no-longer-wysiwyg-other-issue/

**Comment by kathrynwp** [comment]
I was unable to replicate on a:

- self-hosted site
- WordPress.com Atomic site
- WordPress.com Simple site

The list was correctly aligned in the editor in all three scenarios.

**Simple Site screenshot:** 

![Add_New_Post_‹_Global_Styles_Demo_—_WordPress](https://user-images.githubusercontent.com/7662449/181084348-501c17c7-75a2-4909-9550-2f056f627535.jpg)

On self-hosted, tested with:

Twenty Fifteen 3.2
WordPress 6.0.1
No plugins active

Similar to https://github.com/Automattic/themes/issues/2178

Closing this out but if anyone can still replicate, please leave a comment with any details that would help reproduce.
