### ISSUE TITLE
Twenty Fifteen: Applied text color not visible in Block editor

### ISSUE THREAD

**Issue by fstath** [Automattic/themes#2014]
## Steps to replicate

Select some text and apply a color.

## Result

The selected text's color doesn't change. However, when viewing the published post the color is correctly displayed.

Color selection in the editor:
![Screenshot 2020-05-14 at 2 50 06 PM](https://user-images.githubusercontent.com/32326882/81931165-5510a580-95f2-11ea-8f29-623e41a9f266.png)

Published post:
![Screenshot 2020-05-14 at 2 50 26 PM](https://user-images.githubusercontent.com/32326882/81931127-47f3b680-95f2-11ea-9b31-c863c3611cbf.png)

## Expected

I expected for the selected color to be visible in the editor.

* User report: https://wordpress.com/forums/topic/no-longer-wysiwyg-other-issue/

**Comment by kathrynwp** [comment]
Noting that the option to apply colour to text in a Paragraph block has moved under the inverted carat, and is now called Highlight.

I'm not able to replicate this with:

- Self-hosted site (Twenty Fifteen 3.2, WordPress 6.0.1, no plugins active)
- WordPress.com Simple site
- WordPress.com Atomic site

WordPress.com Simple site screenshot:

![Edit_Post_‹_My_Blog_—_WordPress_com](https://user-images.githubusercontent.com/7662449/181092908-7b981c6a-449b-44b4-90ca-3410bc86b167.jpg)

Closing this out but if anyone can still replicate, please leave a comment with any details that would help reproduce.
