### ISSUE TITLE
Dyad 2: Social Links

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#2019]
## Steps to replicate

Create a page using the Contact page template or the About page template.

## Result

Social icons are vertically stacked https://cloudup.com/cE8afU7icFx

## Expected

Social icons should be horizontally aligned.

**Comment by kjellr** [comment]
Looks like Dyad 2 adds a `display: inline` rule to `alignleft` blocks. This overrides the `flex` style for the social icons block. I'm not sure that the rule is needed.

**Comment by kjellr** [comment]
Fixed in #2034
