### ISSUE TITLE
Dyad 2: WooCommerce plus preset color pallet moves header logo

### ISSUE THREAD

**Issue by benchilcote** [Automattic/themes#202]
## Steps to replicate

1. Activate Dyad2 on Atomic site
2. Activate WooCommerce
3. Insert a logo
4. Choose any preset color pallette in customize > Colors & Backgrounds

## Result

When a preset color pallette is selected, the site logo shifts to the right.  When the default colors are used, the logo shifts back to the left, into the correct position.

Demonstration when WooCommerce NOT active
![dyad2-with wc not active](https://user-images.githubusercontent.com/11636210/42707432-2b884458-86a8-11e8-8d44-6974d4e7d3e2.gif)

Demonstration when WooCommerce IS active
![dyad2-with wc active](https://user-images.githubusercontent.com/11636210/42707422-20a8d35e-86a8-11e8-90f6-691c797b5de5.gif)

Note: This does not occur when the site title is used.  This only occurs with the site logo. 

## Expected

The logo should not move when a preset pallette is chosen.

* User report / follow up:  #1270172-zd
* User's site: https://northend.org/

**Comment by laurelfulford** [comment]
This has been fixed in r49075-wpcom-themes. 

I'll follow up when the changes have been applied to the user's site.

**Comment by laurelfulford** [comment]
Confirmed that this is now fixed on my business site with WooCommerce.

@benchilcote it looks like the ZD ticket is closed, so I can't comment on it -- could you please follow up with the user to let them know this has been fixed? Thanks!
