### ISSUE TITLE
Dyad 2 Syntax Errors

### ISSUE THREAD

**Issue by rezzap** [Automattic/themes#204]
## Steps to replicate

Install the Dyad-2 theme from Customize > Themes on an atomic site and then go to WP-Admin > Appearance > Editor. 

At the bottom of the page, you'll get the notice that 'There are 2 errors which must be fixed before you can update this file'. 

![image 2018-07-16 at 4 18 36 pm](https://user-images.githubusercontent.com/10325627/42767072-f63a4d28-8913-11e8-89ed-6200fc4ef3a3.png)

## Result

I don't believe these errors are causing anything to break, but a user has asked us to fix these anyway. 

## Expected
Errors are on line 587:

`th {
	font-size: 85%;
	letter-spacing: 0.1em;
	padding: ;
	text-transform: uppercase;
}
`

Padding is missing a value

and on line 2007:

`.is-singular .site-content:before.
.is-singular .site-content:after {
	content: "";
}
`
The . at the end of before should be a comma I assume. 

* User report: #278170-zd
* User's site: https://fatherhanly.com/wp-admin/theme-editor.php (atomic site requiring SSP access)

**Comment by pauljacobson** [comment]
@rezzap It looks like there's an incomplete `padding` declaration on line 587. Would adding a value not resolve that issue?
