### ISSUE TITLE
Twenty Sixteen: Unable to Change Header Color With Block Editor

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/themes#2050]
## Steps to replicate

* Activate Twenty Sixteen
* Create a post with a header block in Calypso
* Change the color of the text
* Note that it's still black

![2020-05-18_12-47-51 Published Text or Heading Color Does Not Work](https://user-images.githubusercontent.com/22805865/82456013-a81aaa80-9a81-11ea-9bab-ce086daa61fc.jpg)

## Result

Header text stayed black rather than change to the desired color

## Expected

Header text should be the selected color

* User report: 2985810-zen

**Comment by kathrynwp** [comment]
I'm not able to replicate this on a:

- Self-hosted site
- Simple WP.com site - spot-checked with several colour schemes via Appearance > Customize > Colors & Backgrounds
- Atomic WP.com site

Going to close but feel free to comment if anyone is still able to replicate.
