### ISSUE TITLE
Toujours: Featured Image does not display on pages.

### ISSUE THREAD

**Issue by rezzap** [Automattic/themes#2056]
## Steps to replicate

Create a new page and set a featured image to this page. 
Publish the page.

<img width="1055" alt="Image 2020-05-22 at 9 30 39 am" src="https://user-images.githubusercontent.com/10325627/82648070-10e35d80-9c0f-11ea-850f-3fb242b5051d.png">
<img width="1034" alt="Image 2020-05-22 at 9 30 59 am" src="https://user-images.githubusercontent.com/10325627/82648092-1771d500-9c0f-11ea-9f7f-17a5e8ace430.png">

## Result

The featured image displays in the page settings in the editor, but it does not show on the published page. 

## Expected

I would expect that setting a featured image would have the image show on the published page on the site. 

* User report: #2988663-zd

**Comment by danieldudzic** [comment]
Hi @rezzap!

Toujours does not support displaying Featured Images on pages.

If you want to display the image on the page, you should add the image again to the content, as a regular image.
