### ISSUE TITLE
Photos: Audio block is not visible on Google Chrome on Photos theme 

### ISSUE THREAD

**Issue by vinnykaur** [Automattic/themes#2057]
## Steps to replicate

1. Add a new page/post
2. Add an [audio block](https://en.support.wordpress.com/wordpress-editor/blocks/audio-block/) and add audio to it.
3. Publish the page/post.

## Result

The audio player wasn't visible on Google chrome but visible on other browsers (Firefox, Safari)

Here's a screen recording of it: https://d.pr/v/P5rVfp

Here's a screenshot:

![Screen Shot 2020-05-22 at 20 15 01](https://user-images.githubusercontent.com/49183855/82679782-02c22b00-9c69-11ea-9dff-1f85f53d5118.png)

_Click on this link if the image doesn't load_: https://d.pr/i/jpECdr

## Expected

Audio should be visible on Google chrome including other browsers.

* User report: [2964459-zd](https://woothemes.zendesk.com/agent/tickets/2964459)
* Slack thread: [Slack](https://a8c.slack.com/archives/CJDUN89L1/p1590152222037700)

## Additional

- Checked on other themes and it seems visible.
- On further investigation found a related [thread](https://a8c.slack.com/archives/C03TY6J1A/p1568911335067000)
- Checked and found out `height: auto` isn't working for the audio block. 
- As a workaround, shared the below CSS snippet to the user:

```
.wp-block-audio audio {
    min-height: 100px;
}
```

**Comment by nielslange** [comment]
@vinnykaur Thanks for reporting this issue. I've addressed it in https://github.com/Automattic/themes/pull/2058m, thus, feel free to run a test.

@kjellr I've marked this issue with `[Pri] High` as adding CSS to the site alone will not solve this issue, as the Audio Block is also not visible in the editor and admin styles can only be added when using the business plan. It's a rather small change, though. 😀

**Comment by rinazrina** [comment]
I got another report about this issue on #3234239-zen
Provided the CSS as a workaround.

**Comment by MaggieCabrera** [comment]
I see two solutions for this issue:

* We remove `height: auto;` from the theme. This will fail for any other themes that have this same rule
* We add `height: revert;` to the audio block. Apparently Chrome does not like `height: auto;` at all for the audio element and the block is forcing the width already (the height of the element is different across browsers, we shouldn't use a fixed height for this issue). I'm still a little hesitant about using revert, so I'd like a second opinion. Seems like a Chrome bug to me.

**Comment by scruffian** [comment]
> We remove height: auto; from the theme. This will fail for any other themes that have this same rule

This what I'd do. I always prefer less code!

You're right we will also need to remove this from other themes. We should check:
- Varia
- Seedlet
- TwentyTwentyOne

Other are a lower priority IMO

**Comment by kjellr** [comment]
> We remove height: auto; from the theme. This will fail for any other themes that have this same rule

Agreed. I had a PR for this forever ago that you're welcome to pick up if you'd like: #2060

If this effects any of those other themes, we should do it there too.
