### ISSUE TITLE
Shawburn: Homepage scrolls horizontally

### ISSUE THREAD

**Issue by KristinaKay** [Automattic/themes#2063]
## Steps to replicate

- Activate the Shawburn theme
- Create, if needed, then view the default homepage

## Result
The page is wider than the browser size even when browser is full-screen on a 48" monitor.

[Video of Homepage scrollling horizonatlly](https://d.pr/i/Vxq6P1)

## Expected

The screen should not scroll horizontally.

*#20815477-hc
* #3006138-zen

**Comment by kristarella** [comment]
More details:
- this is present in the Shawburn home page layout, whether or not the page is set as the front page
- the issue is present on the [theme demo](https://shawburndemo.wordpress.com/) and other test sites

**Comment by kathrynwp** [comment]
In ran into a Quick Start user experiencing this as well.

**Comment by rickmgithub** [comment]
Just wondering if there was any luck on this as the query popped up again here - #3006138-zen

**Comment by gwensmithx** [comment]
Any ETA on this?

**Comment by eduardozulian** [comment]
Just to let folks know that it should be possible to "fix" this with some custom CSS:

```
/* Global: fix the horizontal scroll */
#page {
  overflow-x: hidden;
}
```
