### ISSUE TITLE
DARA: Image block, bottom and top wave style not honored on Atomic sites.

### ISSUE THREAD

**Issue by TheSteveK** [Automattic/themes#2068]
## steps to reproduce
Add an image block to a page on a site using Dara, select the bottom wave or top wave style from the block sidebar (note simple sites only show the round or default styles, Atomic sites with coblocks enabled show all 4 options.)

<img width="1630" alt="Screen Shot 2020-05-27 at 10 39 57 AM" src="https://user-images.githubusercontent.com/12895386/83035950-14f4ee00-a008-11ea-8ce3-6d2c18eac304.png">

Publish or preview the page

<img width="675" alt="Screen Shot 2020-05-27 at 10 41 03 AM" src="https://user-images.githubusercontent.com/12895386/83035986-1faf8300-a008-11ea-8261-699ac4a711e5.png">

I was able to recreate this issue on my test site crashteststeve.com
## Result

Image will still be shown in default style or Rounded style on the live page.
Additional note: if you took an existing rounded image and changed it to wave, the original round CSS class will still be listed in the blocks and will need to be removed.

Screenshots from editing a page using the about template with the round style:
<img width="1207" alt="Screen Shot 2020-05-27 at 10 40 10 AM" src="https://user-images.githubusercontent.com/12895386/83036455-a06e7f00-a008-11ea-9461-8c02847a0f3f.png">
<img width="312" alt="Screen Shot 2020-05-27 at 10 40 36 AM" src="https://user-images.githubusercontent.com/12895386/83036486-a95f5080-a008-11ea-94ee-693dbe6dca82.png">

## Expected

The images to display the selected styles

* User report: #21434307-hc
* Follow-up ticket: [#3010470-zd]

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
