### ISSUE TITLE
Radcliffe 2 : Blog Posts Block List View - Text Overlay On Image Goes Past Block Width

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/themes#2073]
## Steps to replicate
1. Use Radcliffe 2 theme
2. Have some blog posts with paragraphs of text as the first blocks and a featured image (no excerpt)
3. Create a separate page and add the Blog Posts block and display in list format
4. Set the Images to display behind the text
5. Preview this page - you will see the text goes past the background image and past the set block width

## Result
- text goes past the block boundaries but in the editor it looks fine (as expected)
- this only happened with the Radcliffe 2 theme and I was able to replicate on my test AT site

Editor: 
![Screen Shot 2020-05-30 at 6 54 20 PM](https://user-images.githubusercontent.com/5779512/83342146-e2b5eb80-a2a8-11ea-8ceb-91bd63160802.png)

Preview: 
![Screen Shot 2020-05-30 at 6 54 12 PM](https://user-images.githubusercontent.com/5779512/83342152-f3666180-a2a8-11ea-8886-b8cb14a10d54.png)

## Expected
- expected the preview and published page to look like it does in the editor, respecting the block width

* User report: #8755916-hc
* Follow-up ticket: #3020701-zd

**Comment by gwensmithx** [comment]
I was able to use a workaround to fix the issue in the meantime:

`.wpnbha.image-alignbehind .post-has-image .entry-wrapper {
        max-width:100%;
}`

**Comment by rachelwinspear** [comment]
Another report on Personal plan #3661833-zen

**Comment by katiebethbrown** [comment]
Another report 3743644-zd-woothemes

**Comment by formosattic** [comment]
+1 4287980-zd-woothemes

Related issue and CSS fix at https://github.com/Automattic/themes/issues/2220#issuecomment-653601130

```
.wpnbha.image-alignleft .post-thumbnail,
.wpnbha.image-alignright .post-thumbnail {
    flex: 1 0 50%;
}

.wpnbha.image-alignleft .entry-wrapper,
.wpnbha.image-alignright .entry-wrapper {
    min-width: calc(100% - 50%);
}
```

**Comment by jordesign** [comment]
Scrubbed and confirmed - Radcliffe 2 is very widely installed (1,972,319 sites) so I'd say this is a higher priority fix to add proper support for the Blog Posts block.
