### ISSUE TITLE
Possible BUG on load comments logic.

### ISSUE THREAD

**Issue by Salamander3** [Automattic/themes#209]
## Steps to replicate

PHP coding error. When you disable "allow comments"...

## Result

Comments still show up.

## Expected

Disabling Allow comments shouldn't load comments form.

On page.php you wrote:

```
// If comments are open or we have at least one comment, load up the comment template.
				if ( comments_open() || get_comments_number() ) :
					comments_template();
				endif;
```
However, get_comments_number returns the number of comments. If there are no comments it returns 0, not FALSE but a 0 that equals TRUE.

So in other words i think this logic is wrong. You should check if get_comments_number() > 0. Not if it’s FALSE, it’s never FALSE. Comments are always loaded.

Cheers.

**Comment by laurelfulford** [comment]
Thanks for reporting this, @Salamander3!

A couple questions:

Can you please confirm what theme you are using? 

Can you please provide a link to your site?

Also, comments can be opened and closed on a site-wide level, and also on individual posts. Can you confirm that the post that is still showing the comment form does not have comments enabled on it when you check it in Edit mode? There are some steps for how to do that here:

https://en.support.wordpress.com/enable-and-disable-comments-for-published-posts-and-pages/

Any additional information would be a big help - thanks!

**Comment by laurelfulford** [comment]
I'm going to close this, as we can't move it forward without additional information. 

@Salamander3 if you're still experiencing this, and can provide some more information based on the above questions, we'd be happy to take a look! In that case, please reopen. Thank you!
