### ISSUE TITLE
Non-Varia Themes: Default Solid Colour Palettes not displaying in Editor.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2097]
Editor Styles appear to be missing for the Media and Text Block in older themes. The following screenshot is from Independent Publisher 2. Note the settings in the block inspector.

![image](https://user-images.githubusercontent.com/545779/83547083-4f0e3600-a4c7-11ea-868e-893a86b7a230.png)

Here's what it looks like on the front end in Independent Publisher 2.

![image](https://user-images.githubusercontent.com/545779/83547174-6fd68b80-a4c7-11ea-966b-3774fecf082d.png)

cc @davipontesblog

**Comment by ianstewart** [comment]
Works as expected with gradients.

![image](https://user-images.githubusercontent.com/545779/83547558-0905a200-a4c8-11ea-8b87-7243b17822c5.png)

**Comment by ianstewart** [comment]
Cover Blocks work as expected. Paragraph and Group Blocks do not.

![image](https://user-images.githubusercontent.com/545779/83547948-934e0600-a4c8-11ea-8649-1c1b7ab45537.png)

**Comment by ianstewart** [comment]
Should be resolved by this PR for Gutenberg: https://github.com/WordPress/gutenberg/pull/22356

**Comment by jffng** [comment]
Fixed in Gutenberg, just tested and verified with IP2.
