### ISSUE TITLE
 Pique: Introduce option for displaying tagline on mobile 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#21]
This was originally reported by @SiobhyB in 4867-wpcom-themes:

If you activate Pique on any WordPress.com site then add a site title and tagline, you'll notice that the tagline is hidden when viewing the site on mobile.

This is due to the following in the theme's style.css:

```
@media (max-width: 767px) {
    .site-logo-link + .site-title, .site-description {
        display: none;
    }
}
```

The site owner loves the theme but the tagline is very important to them and they don't want it to be hidden on mobile. They want the option to display the tagline on mobile without having to upgrade or switch themes.

* User report: 880427-f

**Comment by sixhours** [comment]
Rather than adding an option, I'd suggest redoing Pique and ensuring the tagline stays present for less confusion. Suggesting wontfix.

**Comment by sixhours** [comment]
Wontfixing, since this isn't something we will change in the theme at this time. Definitely worth considering in a v2, however, and I will let the customer know.
