### ISSUE TITLE
Stratford: Logo image scales poorly and looks blurry.

### ISSUE THREAD

**Issue by happychait** [Automattic/themes#2100]
## Steps to replicate

1. Activate Stratford theme.
2. Add a site logo over ~300px and crop it while setting it as the logo.
2. Check the logo on the site.

## Result

The logo looks blurry.

## Expected

The logo should be crisp.

This is similar to https://github.com/Automattic/themes/issues/1287 and it seems it was only fixed for some themes like Redhill and  Dalston as mentioned in https://github.com/Automattic/themes/pull/1703

This issue is affecting Stratford (as mentioned [here](https://github.com/Automattic/themes/issues/1287#issuecomment-539072087)) and Exford (as mentioned in https://github.com/Automattic/themes/issues/1363).

* User report: #21492700-hc
* Follow-up ticket: #3032949-zen

**Comment by zdenys** [comment]
I had a user in 26355222-hc who is still experiencing the issue on Redhill theme, even on the demo site Pb8PuN-9-p2

**Comment by Robertght** [comment]
I'm unable to replicate the logo blurriness anymore at this point and what remains a noticeable problem is this: https://github.com/Automattic/themes/issues/2066
