### ISSUE TITLE
Independent Publisher 2: Some tables broken after recent update

### ISSUE THREAD

**Issue by lakellie** [Automattic/themes#2119]
A recent update regarding table cell width has impacted tables created in the classic editor. A user reported their table was broken, as seen here: https://d.pr/i/pnodGf

This was resolved by adding this CSS:

```
table {
table-layout: fixed;
}
```

* User report: #14447114-hc
* Follow-up ticket: #3056117-zd
* Slack discussion: p1591910220107900-slack-themes

**Comment by jordesign** [comment]
Closing this a single instance > 12 months ago without further reports
