### ISSUE TITLE
Varia: words get cut randomly in table block

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/themes#2120]
This happens to Varia and child themes.

## Steps to replicate

* Add a table block with some content, say 1 row, 3 cells.
* Publish, and see how words get cut.

Note that using the fixed-cell feature prevents this from happening.

## Result

Words get cut randomly at the end of the cell.

![Screen Shot 2020-06-12 at 17 13 15](https://user-images.githubusercontent.com/16645645/84517853-1e50ac80-acd0-11ea-8ac4-e35558bd3b75.png)

## Expected

Instead of getting cut, words should go to the next line.

It was reported in #3037564-zd and I was able to reproduce it.

**Comment by cecilearkay** [comment]
It was also reported in #21937107-hc

**Comment by jacklenox** [comment]
That PR didn't close this. I'm preparing another one now that will.
