### ISSUE TITLE
Affinity: Panel-page navigation conflict with Testimonials shortcode

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#2122]
## Steps to replicate
- Add Jetpack
- Add a shortcode to a front-page panel, give it a title
- Publish
- Add that page as one of the front-page panels under Customize > Theme Options

## Result
- Note the menu on the right does not show the proper panel title for Testimonials.
https://cloudup.com/cJ4eV_niER3

(ignore my testimonials content - that was from a different test)

## Expected
The correct panel title should appear

* User report: https://wordpress.org/support/topic/conflict-with-jetpack-testimonials-shortcode/
* Follow-up ticket: Same

**Comment by cathymcbride** [comment]
Retired theme. Closing.
