### ISSUE TITLE
Seedlet: Add starter content

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#2125]
The theme will need starter + headstart content.

**Comment by ianstewart** [comment]
@jffng ping me when you have the seedletdemo.wordpress.com site set up just right and I can walk through what I remember knowing about how Headstart works. (It's relatively simple to generate annotations.)

**Comment by jffng** [comment]
With the help of @ianstewart and some good docs, I figured out how to write / test the headstart annotations. 

But it brings up some questions:
- What dotcom flows today trigger headstart? In other words, which users will see this content?
- With headstart, should we re-create the demo site content, or do something more generic like populate the site with existing dotcom page layouts e.g. About, Contact.

**Comment by ianstewart** [comment]
> What dotcom flows today trigger headstart?

- Signup from theme logged-out theme showcase
- The current "update your homepage on theme switch" feature (which we intend to pause and improve on dotcom)
- HE tools for setting up sites to look like the demos
- At one time signup used it as well

> With headstart, should we re-create the demo site content, or do something more generic like populate the site with existing dotcom page layouts e.g. About, Contact.

My personal opinion is that there's an art to it. A theme demo site should have "just enough" content to show off the theme and look like a real website. If sub-pages help that, yes. I think it's better than sub-pages that show off various elements like a test of the stylesheet.

With the "botany" demo I might have a nice blog on the homepage, maybe an about, and contact page.
