### ISSUE TITLE
Baskerville 2: The last post drops to a new line at the blog.

### ISSUE THREAD

**Issue by LauraSWP** [Automattic/themes#2131]
## Steps to replicate

1. Go to https://patissereat.com/
2. Scroll down to find the last item of the blog.

## Result

Using Chrome and a screen of 17 inches, you will see this:

It looks like the last item of their blog drops to a new line instead of being next to the other as the first posts.

![image](https://user-images.githubusercontent.com/63611065/84804389-fbd9ce80-b002-11ea-932e-586b46874f3f.png)

## Expected

The posts should look like this:

![image](https://user-images.githubusercontent.com/63611065/84805477-9e468180-b004-11ea-9018-b7b8d3b8c9c5.png)

One next to the other.

* User report: [20151983-hc ](https://mc.a8c.com/support-stats/happychat/transcript.php?id=20151983)
* Follow-up ticket: [3067283-zen](https://woothemes.zendesk.com/agent/tickets/3067283)

**Comment by rachelwinspear** [comment]
User has reported this is now resolved and working correctly. I will close issue.
