### ISSUE TITLE
Seedlet: Fix failing Theme Check review

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2136]
Running the Theme Check plugin throws up a handful of REQUIRED errors. These all need to be fixed for a 1.0 release: 

## Required

- [x] REQUIRED: Found a Customizer setting called "`seedlet_$variable[0]`" in `seedlet/classes/class-seedlet-custom-colors.php` that did not have a sanitization callback function. Every call to the `add_setting()` method needs to have a sanitization callback function passed.
- [x] REQUIRED: Could not find `wp_body_open`action or function call at the very top of the body just after the opening body tag. See: [`wp_body_open`](https://developer.wordpress.org/reference/functions/wp_body_open/)
- [x] REQUIRED: A menu without a theme_location was found in `seedlet/functions.php`.
- [x] REQUIRED: A menu name is being used for a menu in themes/dotcom/seedlet/functions.php. By using menu name, the menu would be required to have the exact same name in the WordPress admin area. Use a theme_location instead.
- [x] REQUIRED: `postcss.config.js` PostCSS config file found. This file must not be in a theme.

## Warning

- [x] WARNING: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
The domains found are `seedlet`, `en`
- [x] WARNING: Found a translation function that is missing a text-domain. Function `esc_html__`, with the arguments `This color combination may be hard for people to read. Try using a brighter background color and/or a darker foreground color.`
- [x] WARNING: Found a translation function that is missing a text-domain. Function `__`, with the arguments `seedlet`

## Recommended

- [x] RECOMMENDED: Possible variable `$variable` found in translation function in `seedlet/classes/class-seedlet-custom-colors.php`. Translation function calls must NOT contain PHP variables (Line 194)
- [ ] RECOMMENDED: No reference to `add_theme_support( "custom-header", $args )` was found in the theme. It is recommended that the theme implement this functionality if using an image for the header.
- [ ] RECOMMENDED: No reference to `add_theme_support( "custom-background", $args )` was found in the theme. If the theme uses background images or solid colors for the background, then it is recommended that the theme implement this functionality.

There's also a note that the theme will need to undergo an a11y check, since it's using the `accessibility-ready` tag. We'll want to double check that we're [passing all those rules](https://make.wordpress.org/themes/handbook/review/accessibility/) too.

**Comment by kjellr** [comment]
I'm pretty sure those last two "Recommended" tags are safe to ignore.

**Comment by kjellr** [comment]
> REQUIRED: postcss.config.js PostCSS config file found. This file must not be in a theme. 

@jffng, we can obviously remove this before we submit, but do we even use this file right now?

**Comment by jffng** [comment]
> do we even use this file right now?

**Comment by kjellr** [comment]
> No, we have yet to implement the IE fallback for CSS variables.

Ok. For now, would you prefer that we just remove this entirely? Or keep it and then remove it before submission to the DotOrg repo?

**Comment by kjellr** [comment]
> - REQUIRED: A menu without a theme_location was found in seedlet/functions.php.
> - REQUIRED: A menu name is being used for a menu in themes/dotcom/seedlet/functions.php. By using menu name, the menu would be required to have the exact same name in the WordPress admin area. Use a theme_location instead.

@allancole, this is being thrown off by this function: 

https://github.com/Automattic/themes/blob/30d597b799075d5d9643eb279d43710ad9308f50/seedlet/functions.php#L365-L373

Any ideas for how to get that to pass?

**Comment by kjellr** [comment]
> There's also a note that the theme will need to undergo an a11y check, since it's using the accessibility-ready tag. We'll want to double check that we're passing all those rules too.

I double checked these rules, and I'm fairly confident the theme passes all of these. The only thing I'm not 100% sure about is focus styles — it appears we're just relying on the default browser treatment (usually an outline of some kind) for these. We did design focus styles, so we should build these in.

![Screen Shot 2020-06-17 at 3 55 28 PM](https://user-images.githubusercontent.com/1202812/84943852-f89e1b80-b0b2-11ea-8e1d-585f6683706d.png)

 I've added #2140 to track that.

**Comment by jffng** [comment]
>Or keep it and then remove it before submission to the DotOrg repo?

I realized that we do use the `focus-within` postCSS package in a handful of places. Let's keep the config for now and remove it for submission.

**Comment by kjellr** [comment]
Just noting that although some of the linked PRs have merged, I'm going to wait to deploy these changes to WP.com until we tackle all the items on this list, since we're so close. 👍

**Comment by allancole** [comment]
> Any ideas for how to get that to pass?

Ugh, that one is annoying, @kjellr . It’s just a performance consideration that checks to see if the primary menu is actually populated to determine if we should load the `'seedlet-primary-navigation-script'` or not. We can remove the conditional check, and just load the menu JS file at all times if its just a matter of getting it past the check.

**Comment by allancole** [comment]
> RECOMMENDED: Possible variable $variable found in translation function in seedlet/classes/class-seedlet-custom-colors.php. Translation function calls must NOT contain PHP variables (Line 194)

https://github.com/Automattic/themes/blob/30d597b799075d5d9643eb279d43710ad9308f50/seedlet/classes/class-seedlet-custom-colors.php#L194

This should do the trick:

```
'label'     => $variable[2], 
```

**Comment by kjellr** [comment]
> It’s just a performance consideration that checks to see if the primary menu is actually populated to determine if we should load the 'seedlet-primary-navigation-script' or not. We can remove the conditional check, and just load the menu JS file at all times if its just a matter of getting it past the check.

Ah, ok. I'll remove it for now, and open a new issue so we can re-assess at a later date. 

> This should do the trick:

Yep, I got that one taken care of in https://github.com/Automattic/themes/pull/2137 ✅

**Comment by kjellr** [comment]
The issues in this list should be all set, so closing for now. 👍
