### ISSUE TITLE
Seedlet: Fix array to string conversion error in class-seedlet-custom-colors.php

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2141]
On a fresh activation with `wp_debug` active, Seedlet throws the following error: 

> <b>Notice</b>:  Array to string conversion in <b>/Users/kjell/Sites/valet/dotcomthemes/wp-content/themes/dotcom/seedlet/classes/class-seedlet-custom-colors.php</b> on line <b>216</b>

Here's the line in question: 

https://github.com/Automattic/themes/blob/30d597b799075d5d9643eb279d43710ad9308f50/seedlet/classes/class-seedlet-custom-colors.php#L216

![Screen Shot 2020-06-17 at 4 03 51 PM](https://user-images.githubusercontent.com/1202812/84944673-23d53a80-b0b4-11ea-94b4-8dbf74c1202f.png)

**Comment by jffng** [comment]
I should have a fix for this + #2142 up shortly.
