### ISSUE TITLE
Alves: Color settings in Gutenberg don't work correctly

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#2146]
## Steps to replicate

1. Make sure the Alves theme is activated.
2. Add a block that has color settings, e.g. Cover or Group.
3. Try to change the colors - either in the block toolbar or in the right sidebar.
4. Observe.

## Result

![Screen Capture on 2020-06-18 at 13-07-39](https://user-images.githubusercontent.com/25105483/85013389-c51bc980-b164-11ea-80a6-cead8146cd67.gif)

## Expected

It is possible to change colors without any issues.

* User report: #20907309-hc
* Follow-up ticket: #3073640-zen

**Comment by kjellr** [comment]
Should be all set now! Thank you for filing the issue. 🙌
