### ISSUE TITLE
Alves, Coutoire, Rivington: When custom colors are active, extra color swatches appear in block placeholders.

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2148]
To reproduce: 

1. Activate Alves, Coutoire, or Rivington.
2. Visit the Customizer, activate a custom color palette.
3. Visit the editor, add a Cover block. 
4. Notice that the color palettes in the placeholder include extra duplicate colors. 

These are manually hidden in the sidebar, but it might be worth reducing the specificity of those rules so that they work elsewhere too. 

## Screenshot

![Screen Shot 2020-06-18 at 8 19 40 AM](https://user-images.githubusercontent.com/1202812/85019251-83772880-b13c-11ea-8f18-1fd809a796dd.png)

**Comment by allancole** [comment]
Ahhhh, I totally forgot about the palettes even existing there. Looking at the PR now…
