### ISSUE TITLE
Twenty Twelve: Ad space is blank

### ISSUE THREAD

**Issue by lizkarkoski** [Automattic/themes#215]
Add the Twenty Twelve theme to a test site with Ads enabled. There's blank white spaces where the ads should be displayed. You can still see the "report this ad" links, but no ad. Replicated on test site. 

User site is: https://professionalcongressorganizer.wordpress.com/

Forum thread: https://en.forums.wordpress.com/topic/my-free-wordpress-blog-does-not-show-the-advertisements-properly-why-how-can-i-fix-it/#add-note

<img width="1437" alt="screen shot 2018-07-29 at 7 29 35 am" src="https://user-images.githubusercontent.com/16867830/43366067-09c72cb2-9305-11e8-940d-493ecb82179d.png">
<img width="1417" alt="screen shot 2018-07-29 at 7 30 15 am" src="https://user-images.githubusercontent.com/16867830/43366071-1d6fa5e6-9305-11e8-8008-264acea19944.png">

I would expect for there to be an add in that blank ad space on the user's site. 

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

## Result

[What happened.]

## Expected

[What you expected to happen.]

* User report: [shortlink to chat/forum thread/ticket, ie #12345-hc]
* Follow-up ticket: [shortlink to ticket, ie #12345-zd]
* User's site: [link to user's site, including the specific page/post where issue is present]

**Comment by KokkieH** [comment]
I don't think this is a theme issue - ads load fine for me using Twenty Twelve on a test site, and on the user's site I don't see ads even if I use Theme Butler to view the site with a different theme applied.

More likely related to p5UegX-b1-p2

**Comment by BandonRandon** [comment]
Closing as resolved per the thread linked above by @KokkieH
