### ISSUE TITLE
Independent Publisher 2: Lazy loading breaks the Masonry block layout on AT sites

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#2157]
## Steps to replicate

1. Create a AT site and activate Independent Publisher 2
2. Add a masonry gallery and make sure the Lazy loading is turned on from Jetpack->settings.
3. Publish the page.

## Result
![Automattic - Agent 2020-06-20 08-57-20](https://user-images.githubusercontent.com/6737345/85193839-22825880-b2d4-11ea-84e3-255916edc10d.png)

The images are overlapping and are badly cropped.

## Expected

This is a screenshot after we turned off the lazy loading:

![Contents – Parliament Square, Edinburgh 2020-06-20 08-58-45](https://user-images.githubusercontent.com/6737345/85193971-6c6b3e80-b2d4-11ea-8270-97eb7beb178e.png)

I wanted to refer to this issue: https://github.com/godaddy-wordpress/coblocks/issues/837 however, it's not being looked into anymore.

* User report: 3067167-zen

**Comment by jordesign** [comment]
Confirmed this behaviour is still in place.

This specifically related to CoBlocks + JP Lazy load - and there's no additional reports in > 12 months. 
Questioning if it is worth keeping open.

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
