### ISSUE TITLE
Baskerville 2: lazy-loaded search results ignore excerpt settings

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#2158]
## Steps to replicate
1. On an Atomic or WordPress.org site, activate Baskerville 2. Enable infinite scroll, and set "post excerpts" in Content Options.
2. Set up at least 10 posts which are long enough to trigger the excerpts.
3. Search for any term which brings up more posts than will load per page

## Result

I actually couldn't replicate this bug, but on a user site, posts which lazy load are displayed in full. Site is linked from the transcript or discussion below.

## Expected

All posts display excerpts like they do on the home page. 

* #20192695-hc
*  Possibly related to 4953-wpcom-themes
* Please have a look at discussion at p1591075800281100-slack-themes which has the most context!

**Comment by nerdysandy** [comment]
Reported on  # 22700225-hc

Follow up: # 3152108-zen

**Comment by jeffikus** [comment]
Fix committed to svn - if the issue persists beyond tomorrow, please reopen the issue and assign to me. Thanks!
