### ISSUE TITLE
Lodestar: Small Typo Issue

### ISSUE THREAD

**Issue by acwagner** [Automattic/themes#216]
## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

## Result

[What happened.]

## Expected

Could you put a space after "Typ" at the project site, please? 
Thanks a lot. Anja

* User report: [shortlink to chat/forum thread/ticket, ie #12345-hc]
* Follow-up ticket: [shortlink to ticket, ie #12345-zd]
* User's site:https://frolleinflow.com/portfolio/sketchnoting-basics/
![screenshot 2018-07-29 at 17 10 51](https://user-images.githubusercontent.com/6354289/43367813-52b47774-9353-11e8-8b1e-d331491de1b5.png)

**Comment by alaczek** [comment]
Hi @acwagner ! Thank you for reporting the issue. It should be fixed now on your website.
