### ISSUE TITLE
Seedlet: selecting stripe gradient for group blocks crashes the block.

### ISSUE THREAD

**Issue by kavyagokul** [Automattic/themes#2161]
## Steps to replicate
1. Create or edit a post/page
2. Insert a Group block
3. In the block settings, go to Color settings, and choose Gradient under 'Background color'
4. Select one of the "stripe" gradient options (see gif)

![Peek 2020-06-22 10-14](https://user-images.githubusercontent.com/1659416/85249390-4202b800-b471-11ea-9bea-7ad47a310799.gif)

## Result
Error message
> This block has encountered an error and cannot be previewed.

Error messages from browser console in text file
[error.txt](https://github.com/Automattic/themes/files/4811208/error.txt)

## Expected

Stripe gradient background is set.

**Comment by kjellr** [comment]
👋 Thanks for the report! What version of Gutenberg are you running? [This was an issue](https://github.com/WordPress/gutenberg/issues/21831), but it should be [fixed as of Gutenberg v8.2](https://github.com/WordPress/gutenberg/pull/22239).

**Comment by kavyagokul** [comment]
Some tinkering suggests that using hexadecimal colors in gradients is not supported by Gutenberg. That PR linked above only fixes literal color names. I've tested with Gutenberg 8.2.1, 8.3, and 8.4.0-rc.1(git master) on a local `wp-env` environment, as well as the latest available version on WordPress.com simple and Atomic sites. I'm able to consistently reproduce this behaviour.

If I change the default values for the theme colors in `functions.php` from hex to rgb or rgba, it works fine.

A potential fix would be to change the colors to rgb in the theme, or fix the issue in the editor here
https://github.com/WordPress/gutenberg/blob/92672bd469abc8d189517212b79ae80d5fee2ffd/packages/components/src/custom-gradient-picker/serializer.js#L10

**Comment by kjellr** [comment]
Hmm — that's odd. All of our bundled gradients use hex values. 

It appears that all of the gradients work except for ones with hard horizontal stripes. Can you confirm that too? 

![gradients](https://user-images.githubusercontent.com/1202812/85290938-cfd9a580-b467-11ea-8ac2-11dc7a3faca4.gif)

**Comment by kavyagokul** [comment]
Yes, only the hard horizontal ones are causing the issue.

**Comment by kavyagokul** [comment]
I tested this with a fresh gutenberg-starter-theme, and I could reproduce the issue there. I have filed a bug 
https://github.com/WordPress/gutenberg/issues/23361

**Comment by kjellr** [comment]
Thank you! 🙌

**Comment by kjellr** [comment]
I'll close this issue for now, since the  problem lies upstream in Gutenberg. 👍

**Comment by kavyagokul** [comment]
Just to confirm, this will block the release of this theme on WP.com until the editor bug is resolved and released. That might take some time. :thinking:

**Comment by kjellr** [comment]
The PR for this is already approved, so I think it should land soon. We don't expect Seedlet to be live for all users on .com for at least a few weeks. With that in mind, I don't think it makes sense to rewrite things on our end. 

cc @jffng for a second opinion though.

**Comment by jffng** [comment]
Yep refactoring to rgb is not a great solution for us. Thanks @kavyagokul for highlighting this issue and working up the PR!
