### ISSUE TITLE
Colinear: No "Content Options" in Customizer for Jetpack sites while it works for WP.com sites

### ISSUE THREAD

**Issue by htdat** [Automattic/themes#217]
## Steps to replicate

1. Activate https://wordpress.com/theme/colinear on a Jetpack site.
2. Try to customize the site with "Customizer" 

Note: on WordPress.com sites, "Content Options" works well. See this comment https://github.com/Automattic/themes/issues/217#issuecomment-410114098

## Result

There is no "Content Option". 

![image](https://user-images.githubusercontent.com/10045087/43380052-a3dd0a8e-93f9-11e8-88cf-380d0967e31a.png)

## Expected

I should see "Content Option". 

* Follow-up ticket: 1312772-zen

**Comment by codestor4** [comment]
user asks for an update here: 1312772-zen
cc: @htdat any clue who we should ping?

**Comment by htdat** [comment]
Asking on p1533198474000099-slack-themes

**Comment by htdat** [comment]
This is from my testing WordPress.com site. It displays normally. 

![image](https://user-images.githubusercontent.com/10045087/43618893-3d5927ee-96f5-11e8-8270-f3f3b8204be9.png)

**Comment by alaczek** [comment]
I switched this to an enhancement ticket, but I totally missed that Colinear does support Content Options already, BUT the .zip file for download for self-hosted users has not been updated. I re-generated the the .zip now. I'm not sure though if the user will be able to just update from dashboard, or if they will have to download it manually from the showcase ([link at the bottom of this page](https://wordpress.com/theme/colinear)) and install.

Let us know if this does not fix the issue, and sorry about the confusion!

**Comment by htdat** [comment]
@alaczek - thanks a lot. I can update the new version on my Jetpack site and confirm that "Content Options" displays in Customizer. 

Replied to the user and closing this issue.
