### ISSUE TITLE
Seedlet: Build IE11 fallback for CSS variables

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2171]
In the mold of https://github.com/Automattic/themes-workspace/pull/15. 

Will most likely use a postcss plugin to find all custom properties and turn them into static values, placing a "duplicate" style rule before the custom property.

**Comment by jffng** [comment]
After doing some more research, I can think of two approaches to doing this.

1. Have a single stylesheet that contains fallbacks for IE11. The benefit to this is that the front-end styles remain a single stylesheet; there is no conditional loading of a secondary script necessary. The drawback is that the stylesheet grows substantially in size. 

2. Have an IE11 specific stylesheet. The benefit to this is that we can maintain a much smaller stylesheet for most users. The drawback is that we have to conditionally load an IE11-specific stylesheet. I haven't come across a clean example doing this yet.

**Comment by kjellr** [comment]
> Have an IE11 specific stylesheet. The benefit to this is that we can maintain a much smaller stylesheet for most users. The drawback is that we have to conditionally load an IE11-specific stylesheet. I haven't come across a clean example doing this yet.

This seems like a much better solution if we can swing it — there's no need for most folks to load all those extra styles.

**Comment by kjellr** [comment]
Reopening this issue, because I _think_ we need to also bundle in an IE-specific version of `style-editor.css`.

**Comment by jffng** [comment]
>  I _think_ we need to also bundle in an IE-specific version of style-editor.css.

To do this, we have to bundle the editor styles + variables together so that the plugin can process the stylesheet correctly. I'm not sure how this will impact our custom color logic, since [we enqueue the editor variables separately in our custom color class](https://github.com/Automattic/themes/blob/a52a6aa758e06aeaefc7ea51c1cdfbce13a7bf2c/seedlet/classes/class-seedlet-custom-colors.php#L267-L272), but I can try it out.

**Comment by scruffian** [comment]
We did this with a pony fill in the end, so I think we can close this.
