### ISSUE TITLE
Seedlet: Audit the Readme

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#2172]
The readme.md hasn't been updated in awhile, except for replacing the references to Varia. Let's use this issue to discuss what we want to show there.

If we just wanted to make updates to the existing structure, these are some of changes I'd make:

- [x] Update the description
- [ ] A deeper dive into the project structure ("What's Here") 
- [ ] Update the Quick Start guide
- [x] Remove the child theme instructions until we have an example
- [x] Migrate the relevant to-dos to issues if they are still relevant

If others have ideas or references on how to structure the readme, please chime in.

cc @kjellr @allancole

**Comment by kjellr** [comment]
Would you mind doing a quick pass at updating the description and trimming out anything that might be irrelevant or outdated? That way we can link to the GitHub repo when we first submit to .org. 

We can then follow through with the more complicated items in your list here, like the quick start instructions and project structure, etc.

**Comment by jffng** [comment]
Going to close this one since block based theming has matured and we want to invest more time / documentation efforts there.
