### ISSUE TITLE
Varia: Twitch embed alignment issue

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#2175]
Twitch shortcode embeds do not stay inside the content area on pages in Varia child themes.

## Steps to replicate

Add a [Twitch shortcode](https://wordpress.com/support/videos/twitch-tv-shortcode/) into a Shortcode block.

View published page. 

## Result

Embed is on the edge of the screen, outside the content area.

![https://d.pr/i/EYlsZb](https://d.pr/i/EYlsZb+)

## Expected

Should be inside the content area.

Not sure if this is the best solution but is resolves the issue:

```
iframe {
  display: block;
}
```

![https://d.pr/i/3k5bYN](https://d.pr/i/3k5bYN+)

**Comment by danieldudzic** [comment]
This seems to be working fine now:

<img width="1071" alt="Twitch" src="https://user-images.githubusercontent.com/905781/107226734-c616a980-6a1a-11eb-99ef-d3c4beba5374.png">

I'm confused why the Embed block does not support Twitch, but that's a different conversation.
