### ISSUE TITLE
Twenty Sixteen: lists fall outside the normal document margins in the block editor

### ISSUE THREAD

**Issue by designsimply** [Automattic/themes#2178]
## Steps to replicate

1. Activate the Twenty Sixteen theme.
1. Create a new post.
1. Add a title and some content including a list block.
1. Observe the list block doesn't stay inside normal margins compared to the other content.
1. Save or publish the post.
1. Activate the Twenty Twenty theme.
1. Re-open the same post.
1. Observe that the list block is not offset too far to the left as it was with the Twenty Sixteen theme active.

<img width="49%" alt="Screen Shot 2020-06-24 at Jun 24 5 09 57 PM" src="https://user-images.githubusercontent.com/1119271/85636954-1e8d6800-b63f-11ea-9985-cd56985dfc54.png"> <img width="49%" alt="Screen Shot 2020-06-24 at Jun 24 5 11 15 PM" src="https://user-images.githubusercontent.com/1119271/85636961-22b98580-b63f-11ea-85be-6683bc889194.png">

## Result

Lists appear too far to the left in the editor, outside the margins, when the Twenty Sixteen theme is active.

## Expected

I expected lists to appear in the normal flow of the document and not offset further to the left compared to other content.

<p style="clear:both;"><sup>Found while beta testing WPDesktop 6.0.0-beta3 and confirmed the problem also happens on the web.</sup></p>

**Comment by eduardozulian** [comment]
This also confused a user in 19759782-hc

**Comment by kathrynwp** [comment]
I am not able to replicate this on:

- self-hosted site
- WordPress.com Atomic site
- WordPress.com Simple site

Lists are correctly aligned in all three:
![Self-hosted_Test_–_not_just_another_fake_company](https://user-images.githubusercontent.com/7662449/181049252-17412b85-9ec5-4b3c-88c5-8ee1a11a71cd.jpg)

Closing this out but if anyone is still able to replicate this, feel free to comment with details.
