### ISSUE TITLE
AltoFocus: Problems with Older Posts button

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#2179]
## Steps to replicate

1. Activate theme on a site containing 20+ posts.
2. Make sure Infinite Scroll is switched off
3. View the front/posts page, and scroll to the bottom
4. Click the Older Posts button to load more posts.

## Result

Additional posts loaded, but the Older Posts button remained stuck in its original position below the first batch of posts, instead of remaining at the bottom of the page:

<img width="984" alt="Screenshot_2020_06_25__06_20" src="https://user-images.githubusercontent.com/11873759/85653075-c7be7780-b6ac-11ea-82f2-2d50e7e414f7.png">

This can be observed on the demo site.

## Expected

For the button to always appear at the bottom of the posts page, below the last visible post.

* User report: Reported [via Twitter](https://twitter.com/vossbrink/status/1275878181237673991)

**Comment by chaitanyamsv** [comment]
7441092-hc

**Comment by donalirl** [comment]
Another case in #15451250-hc. I also want to note that when older posts are loaded, they stack on top of existing posts instead of showing underneath:
<img width="662" alt="altofocus" src="https://user-images.githubusercontent.com/30727666/86185988-25563680-bb7b-11ea-90be-a551ddaa81b9.PNG">

**Comment by JessBoctor** [comment]
We had two more users report this issue in #3107734-ZEN and #3106720-ZEN

**Comment by asheliza29** [comment]
Another user reported this problem to us today. Ticket #3110662-ZEN

**Comment by formosattic** [comment]
+1 in 3106378-zen

**Comment by KristinaKay** [comment]
Another report here: #3103983-zen

**Comment by eamcgill90** [comment]
Reported here 22455777-hc

**Comment by marutim** [comment]
Another user reported the issue here 22487968-hc

**Comment by RealCarFax** [comment]
Another user has reported this issue here: 16369178-hc

**Comment by fresatomica** [comment]
Another report: https://wordpress.com/forums/topic/overlapping-blog-posts/

**Comment by kcswong** [comment]
Followed up user report after chat here: 3158830-zen

**Comment by tavilla61** [comment]
Another instance here: 22790749-hc
Screenshot from the user showing the overlapping posts: https://www.dropbox.com/sh/fxl4jknrxtfdztu/AAAHAVTMrul4gqbLr_-CT_6Aa?dl=0&preview=Screen+Shot+2020-07-21+at+12.24.04+PM.png

**Comment by KokkieH** [comment]
Report from a Personal Plan user in the .org forums: https://wordpress.org/support/topic/overlapping-posts-6/

**Comment by benchilcote** [comment]
Another report from 22873301-hc
Follow up: 3170501-zen

**Comment by KokkieH** [comment]
another report in https://wordpress.com/forums/topic/overlapping-images/

**Comment by KokkieH** [comment]
Report from the forum that the Older Posts button now completely disappears in some cases: https://wordpress.com/forums/topic/altofocus-older-posts-button-now-disappears/

**Comment by smithkyle45** [comment]
I received a report of this issue in 22215852-hc
Generated a follow up: 3198470-zen

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/website-problems-18/

**Comment by rachelwinspear** [comment]
Another report: #20542419-hc
Follow up: #3203143-zen

**Comment by KokkieH** [comment]
https://wordpress.com/forums/topic/overlapping-blog-posts-2/

**Comment by jordesign** [comment]
Another report - #320529-zen

**Comment by lakellie** [comment]
Another report in 23250050-hc

**Comment by danieldudzic** [comment]
This has been now fixed in https://github.com/Automattic/themes/pull/2264 (https://wpcom-themes.trac.automattic.com/changeset/56815/altofocus)

**Comment by ramonjd** [comment]
Another report today 3230392-hc

https://cldup.com/KwRWwfFlWD.mp4

I can reproduce in Safari (Desktop and iOS mobile), fairly reliably. Sometimes the bug doesn't appear, but it does after a while.

I clicked on "older posts" and scrolled upwards to view the loading images. 

Maybe the JS post height calculation isn't waiting for the images to load?
