### ISSUE TITLE
Canard: Post carousel block not appended to the correct header element

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#2186]
## Steps to replicate

1. Activate Canard
2. Add some content to the post and add a post carousel(make sure there are existing posts)
3. The post title .entry-title and .entry-meta is being appended to the .entry-header-inner instead of the block itself.

## Result

Overlapping elements:

<img width="1193" alt="Testing some things - Bobs shop 2020-06-25 23-21-48" src="https://user-images.githubusercontent.com/6737345/85791616-cdfb3500-b73a-11ea-9875-d46eab2f1073.png">

## Expected

To have the info displayed in the post carousel.

Note that the screenshot can be a bit confusing because of some existing CSS, however, the HTML remains the same.

* User report: #20697472-hc
* Follow-up ticket: #3092092-zd

**Comment by kosiew** [comment]
Workaround - ensure the post containing the carousel is not itself included in the carousel.
This can be done by removing the featured image of the post

**Comment by pmciano** [comment]
In our last reply, we told the user:

> I tried creating an entirely new test page by copying the page code across and this one actually seemed to work - https://wordpress.com/block-editor/post/womanuniverse.it/6087?authWpAdmin=true
>
> While I realize, this doesn't fix the issue and we clearly need to investigate are you able to use that test page content in your original post? It seems to work on my end as a private published post.

They have replied:

> If you insert the featured image in the article, and try to see a preview or poublish it, you see the bug.
I try just now in your test article, it have the same issue.
