### ISSUE TITLE
Rowling: Submenus layout broken on mobile in RTL languages

### ISSUE THREAD

**Issue by guicmazeredo** [Automattic/themes#219]
Submenus layout is broken on mobile when using Bottom Header Menu with the Hebrew language (and likely all RTL languages). 

## Steps to replicate

1. Install Rowling Theme.
2. Create a menu and set it as Bottom Header Menu.
3. Add parent and Child items. 
4. Access WP Admin  > Settings >  General and select "He" in the language dropdown.
5. Access the website using a mobile device or simule a mobile screen using a web browser. 
6. Open the hamburger menu.

## Result

This is how the menu looks like: http://cld.wthms.co/2rfxkJ

## Expected

The same layout displayed when the site is set to a non-RTL language: http://cld.wthms.co/Bc9CK5
___________

* User report: [#5439987-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=5439987)
* Follow-up ticket: [#1321891-zd](https://woothemes.zendesk.com/agent/tickets/1321891)
* User's site: b-azz.org

**Comment by Robertght** [comment]
I can confirm this is still an issue. As a workaround:

```
@media screen and (max-width: 768px){
 .rtl .header-bottom-menu > li {
    float: none;
 }

 .rtl .header-bottom-menu ul a {
    padding-right: 10%;
 }
}
```

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
