### ISSUE TITLE
Seedlet: Add support for spacing overrides

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2191]
Varia child themes have a few classes built-in that help to control the spacing:
* margin/padding-top/bottom/left/right-none
* margin/padding-top/bottom/left/right-half
* margin/padding-top/bottom/left/right-default

These come in really handy when designing patterns and layouts. Could we have those in Seedlet too?

**Comment by kjellr** [comment]
@alaczek Can you share some usage samples?

**Comment by alaczek** [comment]
Sure thing! We use those classes quite a bit in our block patterns, usually to bring text or text and image a little bit closer together.

Here are some examples:
![image](https://user-images.githubusercontent.com/4550351/86194301-7e30c980-bb91-11ea-8a81-b72351fc6832.png)

In this one `margin-bottom-half` and `margin-top-half` are used to bring the image and text closer.

----

![image](https://user-images.githubusercontent.com/4550351/86194517-057e3d00-bb92-11ea-9e97-82f9710eaad0.png)

In this one `margin-top-none` and `margin-bottom-none` are used to minimize the spacing between separator and text.

----

![image](https://user-images.githubusercontent.com/4550351/86194624-568e3100-bb92-11ea-8098-220c0eeae6b6.png)

In this one `margin-top-half` and  `margin-bottom-half` are used to reduce the spacing between the stars, the testimonial, and the signature.
