### ISSUE TITLE
Rebalance: Move WordPress.com attribution to the bottom of Footer Widget Area 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#22]
This was originally reported by @liviopv in 4875-wpcom-themes:

Currently, Rebalance displays the WordPress.com attribution on the left of the Footer widget area.

While this looks great when the user has only a handful of widgets (like the theme demo), it creates some unsettling white space on the left when the site has multiple or big widgets, especially when using the WordPress.com logo option for the attribution.

![](https://cldup.com/nHK9ZAIKsO.png)

By pushing the attribution to the bottom of the footer and displaying the widgets across a 3-column grid, we would also be aligning the theme with the behavior found on other theme's footers.

**Comment by sixhours** [comment]
I don't think this is something we should change in the current version of the theme. Suggesting wontfix for now, and we can revisit in a v2.

**Comment by laurelfulford** [comment]
I agree with wontfixing -- changing it now could change the appearance of existing sites in a noticeable way.
