### ISSUE TITLE
Rowling: Tapping parent menu item open new page instead of dropdown on mobile

### ISSUE THREAD

**Issue by kriskarkoski** [Automattic/themes#220]
## Steps to replicate

1) View rowlingdemo.wordpress.com on a mobile device
2) Tap the "A Parent Page" menu item

## Result
The browser opens rownlingdemo.wordpress.com/a-parent-page instead of expanding the menu dropdown to view the children items, which happens on hover on desktop

## Expected

The menu to expand to reveal the children menu items 

* User report: #5410205-hc
* Follow-up ticket: #1323696-zen
* User's site: finanzasamedida.com, Mercados Financieros item

**Comment by davidakennedy** [comment]
I'm closing this issue because:

* This theme is outside of the 30 or so we're focused on in this repository.
* The likelihood of us making a fix to a theme outside of the focused ones that isn't a security issue or bad visual bug is not high.

**Comment by Robertght** [comment]
Another report in #2678356-zen. @davidakennedy should we leave them open for better visibility perhaps? 

As a workaround, I recommended using empty links for the parent menu.
