### ISSUE TITLE
Sketch: Requires more than one featured post to display homepage slider

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/themes#221]
## Steps to replicate

1) Create a home page, using the "Portfolio page template."
2) Go to Customize and set that home page as the Front Page.
3) Create a new portfolio project and add the "featured" tag to it. (Be sure to use the regular Tag field, not the "project tag" field.)
4) Publish.

## Result

You'll see the home page but without the featured content slider. However, if you create another portfolio project and add the "featured" tag to it, the slider will appear. 

## Expected

I expected to be able to see the featured post slider even with just the one project. 

@laurelfulford was kind enough to test this out and figure out what the issue was and asked me to report it here. 

Not sure if this is a bug or as expected, but it doesn't seem to be consistent with the way other themes display featured content sliders. If it *is* expected behavior, please update the theme info documentation to indicate that. Thanks!

For reference, here's the theme info page:

https://wordpress.com/theme/sketch

Slack conversation: https://a8c.slack.com/archives/C029FM1EH/p1533580865000223

* User report: n/a (concierge session)
* Follow-up ticket: #1329065-zen
* User's site: https://tinacantelmiartist.com/

**Comment by alaczek** [comment]
I was able to fix the issue, but the customer switched themes, so not sure if this needs following up or not. Leaving it up to you @Lochlaer

**Comment by Lochlaer** [comment]
Thanks so much! I'll follow up now just to let her know we did address this. :-)
