### ISSUE TITLE
Seedlet Blocks: Layout Grid columns not lining up horizontally in the editor

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2211]
## Steps to replicate
1. With Seedlet Blocks active add Layout Grid block to a post or a page. Pick two or more columns configuration.
2. Notice how in the initial empty state of the block the first column outline is a little higher than others.
3. Add content to each column. The first column is still sitting a bit higher than others.
4. Save and preview. Notice that the issue does not affect the front end.

Editor - initial state of the Layout Grid block

![image](https://user-images.githubusercontent.com/4550351/86299613-12f3ff80-bc44-11ea-8787-cf938e7ffe05.png)

Editor - Layout Grid block with content added to each column

![image](https://user-images.githubusercontent.com/4550351/86299671-2e5f0a80-bc44-11ea-803b-c3e68935411b.png)

Page preview - no issues.

![image](https://user-images.githubusercontent.com/4550351/86299753-5babb880-bc44-11ea-9389-a65f2d40c7cd.png)

Tested in Chrome 83.0 / macOS 10.15.5

**Comment by jffng** [comment]
This issue is caused by these spacing overrides:

https://github.com/Automattic/themes/blob/7d84a62a77863e35cab835d3ad34d1a8458f285b/seedlet/assets/sass/blocks/utilities/_editor.scss#L158-L174

@kjellr do you remember what these are for? Is it primarily to add some extra margins to every block in the editor to make them easier to select?

**Comment by kjellr** [comment]
That's the regular top/bottom spacing supplied for all blocks. Gutenberg provides one, and Seedlet overrides it. We make that present on the front end too so the spacing matches up nicely: 

https://github.com/Automattic/themes/blob/9f03a09e56f0ccf50d8c38f06a17f4c472a7cf5d/seedlet/assets/sass/structure/_vertical-margins.scss#L131-L152

In this case, we may need to write special rules to make sure these apply properly in the layout grid block. Do we have this issue in the Columns block too? If not, we should look into why.

**Comment by alaczek** [comment]
Nope, this is not happening in the Columns block.
