### ISSUE TITLE
Seedlet Blocks: Gradient background breaking blocks

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2213]
## Steps to replicate
1. With Seedlet Blocks active add a Group block to a post or a page.
2. In the Color settings switch Background to the gradient option.
3. Try applying different settings. Some of them will work correctly, while Horizontal, Horizontal Inverted, and Stripe break the block.

![zRt7pciAiW](https://user-images.githubusercontent.com/4550351/86301785-19857580-bc4a-11ea-9974-ad0184e16abc.gif)

Tested in Chrome 83.0 / macOS 10.15.5

**Comment by kjellr** [comment]
Thanks @alaczek! This is a Gutenberg bug, and is [fixed in Gutenberg 8.5](https://github.com/WordPress/gutenberg/pull/23363) (coming out next week). I'm going to close for now, since we don't expect to launch this before that version is on WP.com.
