### ISSUE TITLE
Radcliffe 2: Blog Posts Block List View does not show Featured Images

### ISSUE THREAD

**Issue by otpidusprime** [Automattic/themes#2220]
## Steps to replicate

1. Activate Radcliffe 2 theme
2. Edit post/page using the Block Editor (you should have posts with Featured Images)
3. Add Blog Posts Block
4. Click "List View" and "Show Media on Left or Right".
    ![Screen Shot on 2020-07-03 at 21:00:27](https://user-images.githubusercontent.com/29238672/86482837-58ade680-bd70-11ea-8e94-b445079d330b.png)
5. Click "Preview" on the top right corner

## Result

It does not show Featured Image on the site, _tho on the Editor, it previews fine_.

#### On site:
![Screen Shot on 2020-07-03 at 21:03:45](https://user-images.githubusercontent.com/29238672/86483015-c5c17c00-bd70-11ea-97cc-4f20c6afbafd.png)

#### On Editor:
![Screen Shot on 2020-07-03 at 21:04:05](https://user-images.githubusercontent.com/29238672/86483043-d245d480-bd70-11ea-9d00-f697e15860b7.png)

## Expected

Render Featured image in List View on site:

![Screen Shot on 2020-07-03 at 21:05:55](https://user-images.githubusercontent.com/29238672/86483138-01f4dc80-bd71-11ea-9be2-be8a06d3abd5.png)

**Note:** The issue is only on the List View(Featured Image on Left or Right) in Radcliffe 2.

* User report: [hc-19920357](https://mc.a8c.com:443/support-stats/happychat/transcript.php?id=19920357)
* Follow-up ticket: [zd-3111537](https://woothemes.zendesk.com/agent/tickets/3110545)

**Comment by otpidusprime** [comment]
As a temp. workaround for sites under Premium plan or above, we can use this CSS to fix this:

```
.wpnbha.image-alignleft .post-thumbnail,
.wpnbha.image-alignright .post-thumbnail {
    flex: 1 0 50%;
}

.wpnbha.image-alignleft .entry-wrapper,
.wpnbha.image-alignright .entry-wrapper {
    min-width: calc(100% - 50%);
}
```

For what its worth, I noticed that if we set the `flex-shrink` value `1`, the feature image disappears.

**Comment by brookewp** [comment]
For a Personal plan site, I had them change the width to wide or full width which also helped the problem (zd-3336925)
