### ISSUE TITLE
Lodestar: Form field loads "Type 'About' into Cortana search" value in browsers not signed into WordPress.com

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#2227]
One of our customers asked about a line of text that appears to be a form field's default value in one of the form fields in the Form Block on their site's homepage, like this:

![Screen Shot 2020-07-05 at 16 40 05](https://user-images.githubusercontent.com/2912202/86534625-62eff200-bee2-11ea-9457-fd4cce905fd0.png)

### Steps to replicate

I tested this in the following browsers on my macOS 10.15.5 laptop:

* Firefox Developer Edition v79.0b3;
* Chrome Version 83.0.4103.116;
* Microsoft Edge Version 83.0.478.58;
* Brave Version 1.10.97 Chromium: 83.0.4103.116; and
* Safari Version 13.1.1.

Each browser displays the text when the browser is not signed in (I opened a private/incognito window to test this).

I searched OpenGrok to see if I could find the string `Cortana` and wasn't able to find any results (unless my search was flawed in some way).

### Result

The text, "Type 'About' into Cortana search", only seems to appear as a value in browsers that are **not** signed into WordPress.com. Specifically, the text appears as a value in this element:

```
<input type="text" name="g71-excelversion" id="g71-excelversion" value="Type 'About' into Cortana search" class="text">
```

I can't find a source for this text, or how to remove it (except to be signed into WordPress.com when the `value` property is `""`).

### Expected

No value where this is not provided for in the theme itself.

* User report: 3116236-zen

**Comment by pauljacobson** [comment]
To add to my report, the user came back to us and said that they're using Chrome v83 on Windows 10.

**Comment by kjellr** [comment]
This doesn't appear to be a Theme issue. I'll follow up directly. 👍
