### ISSUE TITLE
Seedlet: Add the option to hide title on the homepage

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2235]
Varia child themes have a very handy option to hide the page title on the homepage. To see it in action activate Mayland or Maywood and go to Customize > Homepage Settings. Could we have the same option in Seedlet?

![image](https://user-images.githubusercontent.com/4550351/86713878-e126d280-c061-11ea-9878-012689c55df0.png)

**Comment by kjellr** [comment]
I think this was taken care of in https://github.com/Automattic/themes/pull/2196. @alaczek can you confirm when you have a moment? 

Thank you!

**Comment by alaczek** [comment]
Yep, it is working for me. Thanks!
