### ISSUE TITLE
Dara: Blog page switches to a narrow format

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#2241]
## Steps to replicate

The main site looks like this - https://d.pr/i/LOc67F
The blog page looks like this - https://d.pr/i/kWYZnz
So it is narrower on the blog page and causes the words to wrap around

WHAT I TRIED:
* Tried changing the page template on the blog page by deselecting the page as a blog page in home page settings. Then changing the page template on the blog page to "full width no sidebar" and reselecting it again in home page settings. No change
* Tried the same but this time selecting the "default page" template. Still narrow.
* This ticket pointed to a need to have a sidebar widget installed to expand the site properly  #1759360-zd
* However, I was able to set up a test site myself with Dara again and the width didn't change on the blog page at all
* Tried creating two new pages with different templates on the user's site but both showed narrow pages again.

## Expected
The blog page to match the width of the main site with or without a sidebar.

* User report: #16685121-hc
* Follow-up ticket: #3126749-zd

**Comment by kathrynwp** [comment]
Unfortunately this issue was marked as a `wontfix` by the developer when I first reported it shortly after Dara came out several years back.

See #4831-wpcom-themes.trac.automattic.com for details.

**Comment by Robertght** [comment]
Thank you @kathrynwp  I've made the user aware of this and share the CSS workaround for now

**Comment by Robertght** [comment]
Marking this as a wontfix again as I got a confirmation from @kjellr. 

In case someone wants to use the workaround:

```
/*Workaround for widths | XX-xxxxxx-hc/zen */
.no-sidebar .site {
  max-width: 1180px;
}

@media screen and (min-width: 1000px) {
  .content-wrapper .content-area {
    max-width: 100%;
  }
}
```
