### ISSUE TITLE
Alves: Cover blocks using the "Background" background color swatch are not correct on the front end

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2252]
## Steps to replicate

1. Using Alves and a custom color palette, make a cover block. 
2. Change the background color of the cover block to the "Background" color swatch: 

![Screen Shot 2020-07-13 at 3 16 46 PM](https://user-images.githubusercontent.com/1202812/87344536-a4a11e00-c51c-11ea-885d-875dfc9e5cce.png)

3. View in the front end. 

## Result

The background color of the cover block is correct in the back end, but not in the front end. 

![Screen Shot 2020-07-13 at 3 19 48 PM](https://user-images.githubusercontent.com/1202812/87344651-cf8b7200-c51c-11ea-9694-265525ae87bd.png)
![Screen Shot 2020-07-13 at 3 19 58 PM](https://user-images.githubusercontent.com/1202812/87344653-d0240880-c51c-11ea-9da6-68e0e02004f5.png)

**Comment by Gustavo-Hilario** [comment]
Issue reported here: 4448278-zd-woothemes

I was able to replicate it on a test site so I'm reopening this issue for now.

**Comment by kavyagokul** [comment]
> Issue reported here: 4448278-zd-woothemes
> 
> I was able to replicate it on a test site so I'm reopening this issue for now.

It's possible this is actually this issue instead
https://github.com/Automattic/wp-calypso/issues/57711

**Comment by kspilarski** [comment]
4448278-zd - I had the same user in chat. 

I gave CSS as a workaround to set text color to the color they want.

**Comment by eduardozulian** [comment]
Bumping the priority of this one since Automattic/wp-calypso#57711 is affecting several users.

**Comment by jordesign** [comment]
Closing this once again - as the original issue is different to the one being reported now (text color VS background color. Closing in favour of https://github.com/Automattic/wp-calypso/issues/57711
