### ISSUE TITLE
Independent Publisher 2: Changing Text Color in Paragraph Block Reflected on Frontend but not Backend

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#2256]
## Steps to replicate

Select any text inside [Paragraph Block](https://en.support.wordpress.com/wordpress-editor/blocks/paragraph-block/) and change its color via block's toolbar.

## Result

The text doesn't change color in the Editor (back end) but in changes in Preview or on Published site (front end).

![](https://d.pr/i/7NsCq0+)
_Link: https://d.pr/i/7NsCq0_

## Expected

See the text color change in the Editor

* User report: 12375333-hc

**Comment by jordesign** [comment]
No longer able to recreate this in AT or Simple sites. The new 'highlight' tool in GB works correctly.
