### ISSUE TITLE
Varia: Premium Content block content doesn't have correct margins

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#2257]
## Steps to replicate

1. Activate Varia, or any Varia-based theme
2. Add a Premium Content block to a post or page
3. Add content to the Premium Content block
4. Publish the page or post

## Result

The spacing for the elements in the Premium Content block is incorrect:

[![Premium and Regular Content](https://d.pr/i/8WSpWL+)](https://d.pr/i/8WSpWL)

This happens because the Premium Content block doesn't have an `inner-container` class, so the margins from this CSS don't apply:

```
.site-footer > *, 
.site-main > article > *, 
.site-main > .not-found > *,
.entry-content > *, 
[class*="inner-container"] > *, 
.widget-area > * {
	margin-top: 21.312px;
	margin-bottom: 21.312px;
}

@media screen and (min-width: 560px) {
	.site-footer > *, 
	.site-main > article > *, 
	.site-main > .not-found > *,
	.entry-content > *, 
	[class*="inner-container"] > *, 
	.widget-area > * {
		margin-top: 32px;
		margin-bottom: 32px;
	}
}

```

## Expected

The content in the Premium Content block would be spaced like other elements in the post or page content:

[![With CSS Applied](https://d.pr/i/OeYa6c+)](https://d.pr/i/OeYa6c)

This CSS will resolve the issue:

```
/* fix content margins in premium content block */
.entry-content .wp-block-premium-content-container [class*="wp-block-premium-content-"] > * {
	margin-top: 21.312px;
	margin-bottom: 21.312px;
}

/* unset button margins in premium content block */
.entry-content .wp-block-premium-content-container [class*="wp-block-premium-content-"] > .wp-block-buttons > * {
	margin-top: 0;
	margin-bottom: unset;
}

/* fix content margins in premium content block for larger screens */
@media screen and (min-width: 560px) {
	/* fix content margins in premium content block */
	.entry-content .wp-block-premium-content-container [class*="wp-block-premium-content-"] > * {
		margin-top: 32px;
		margin-bottom: 32px;
	}
}
```

Originally reported here: #21827539-hc

**Comment by iamtakashi** [comment]
+1. This is not a blocker for patterns directly, but they will surface the issue with it. cc @ianstewart

**Comment by ianstewart** [comment]
> This happens because the Premium Content block doesn't have an inner-container class, so the margins from this CSS don't apply

Is this a theme issue or a block issue? Can we add the class or the inner container to the block?

**Comment by iamtakashi** [comment]
I think it'd be easier to fix in the themes. Seedlet shares the issue as well. It works expected in Twenty Twenty.

**Comment by jeffikus** [comment]
This looks like it's related to #2281
