### ISSUE TITLE
Seedlet-blocks custom-line-height support opt-in now required.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/themes#2265]
I ran into this change while working on some FSE blocks and testing with the Seedlet-Blocks theme.  Perhaps this is already on your radar but I figured it would be worth a heads-up.  (@kjellr - I hope you don't mind but since you authored the Seedlet p2 post I figured you would be the right person to ping.)

## Steps to replicate
* Run Gutenberg master with seedlet blocks theme.
* In the editor select a post and look to customize the Line Height.
* Verify this option is no longer available.

Recent changes in Gutenberg have made the block level custom line hight options require a theme level opt-in.  That is, the "Line Height" option we used to have for blocks such as Paragraph:

![Screen Shot 2020-07-16 at 2 28 57 PM](https://user-images.githubusercontent.com/28742426/87708438-bc70e000-c770-11ea-94a1-c724b77e3bcc.png)

Is no longer present on Gutenberg master while using Seedlet Blocks.  For this to be available again, we will need to add `add_theme_support( 'custom-line-height' )` to the theme (https://github.com/WordPress/gutenberg/pull/23044#issuecomment-659475699).

**Comment by kjellr** [comment]
Thanks for the heads up!
