### ISSUE TITLE
Nucleare: Social Links Menu: Instagram shows generic icon

### ISSUE THREAD

**Issue by jessestu** [Automattic/themes#227]
## Steps to replicate

1. Activate Nucleare on simple or Atomic site.
2. Edit Social Links menu to include this Instagram address: https://www.instagram.com/feedyourselfwithlove_/

## Result

The Instagram icon shows as a generic icon. It works when I test my personal Instagram handle, https://www.instagram.com/jessestu.art/

Here's a GIF showing the two in action, as well as how the icon looks loading only instagram.com itself:

![screen capture on 2018-08-13 at 16-35-25](https://user-images.githubusercontent.com/32908730/44059420-f08f81ae-9f16-11e8-8e5f-d3c31418291a.gif)

## Expected

I expect the icon to show the Instagram graphic for any URL beginning with `https://www.instagram.com`, such as happens with Twenty Sixteen theme:

![screen capture on 2018-08-13 at 16-37-56](https://user-images.githubusercontent.com/32908730/44059530-4e7d5caa-9f17-11e8-97db-7b7902b039b6.gif)

* User report: 5683088-hc
* Follow-up ticket: 1345508-zen
* User's site: https://feedyourselfwithlove.blog/

**Comment by jessestu** [comment]
This is my first theme bug reported using GitHub. Please let me know if I needed to add any Labels or other elements to the report.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
