### ISSUE TITLE
Seedlet Blocks: Missing WPcom-specific footer-filtering

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2271]
WPcom uses a plugin, filter, and boilerplate code in footer templates for traditional WordPress themes to add custom text to the footer of every WP.com site like the following example from a Varia-based theme:

![image](https://user-images.githubusercontent.com/545779/87960767-622a9480-ca7a-11ea-9b37-1b316f6ff7ee.png)

This filtering is not currently happening with Seedlet-Blocks:

![image](https://user-images.githubusercontent.com/545779/87960850-825a5380-ca7a-11ea-9916-8c933ff0318b.png)

What I expected:

The same, "Create a free website or blog at WordPress.com." message in the footer of Seedlet Blocks.

**Comment by apeatling** [comment]
The "Proudly powered by WordPress" is in the footer.html block template part in the seedlet blocks theme: https://github.com/Automattic/themes/blob/master/seedlet-blocks/block-template-parts/footer.html

Filters can't be run here, so I imagine the idea would be to provide a different footer block template part for WordPress.com?

**Comment by ianstewart** [comment]
I almost think we wouldn't the "footer-credit" (let's call it that for short) in the template part? But instead always append it to the footer template part? Or perhaps, I suppose it could be a custom footer-credit block in the footer that was "locked" for all roles? Or had deletion alone locked?

**Comment by noahtallen** [comment]
We've discussed adding custom footer credit blocks for wordpress.com. But yeah, the core functionality based on "can't change it without a plan" won't work without a custom block like that. There is also this issue about dynamic content in template parts which may see some progress in the coming months: https://github.com/WordPress/gutenberg/issues/21932

**Comment by ianstewart** [comment]
> won't work without a custom block like that

Yeah, perhaps a custom block that was locked https://developer.wordpress.org/block-editor/developers/block-api/block-templates/#locking in some way?

**Comment by noahtallen** [comment]
Funnily enough, I already have some basic foundation for this site of block from our dotcom-fse explorations: https://github.com/Automattic/wp-calypso/pull/37012

**Comment by ianstewart** [comment]
This reminds me, because I pulled up an old FSE test site the other day, if we make these sorts of blocks (that is, if that's the solution) we should make sure they can't be broken in the code editor view of an Editor. (I found out I could break my FSE test site that way in some instances.)

**Comment by noahtallen** [comment]
Yeah, totally. We haven't integrated code editor into the site editor yet because it's a tricky problem -- currently it's only designed to work with a single entity (post) and not a ton at the same time :/

**Comment by MaggieCabrera** [comment]
We fixed this directly in the credits plugin for all block themes
