### ISSUE TITLE
Seedlet Blocks: Missing Front-end "Edit" Links

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2274]
Here's a visual example of an Edit link in a traditional theme.

![2020-07-20 11 31 43](https://user-images.githubusercontent.com/545779/87962348-a74fc600-ca7c-11ea-92df-3f431b5a09c9.gif)

This is the `edit_post_link` template tag in action. It's one of the template tags mentioned in [a core issue for covering template tags for FSE](https://github.com/WordPress/gutenberg/issues/22724).

Note about priority for Seedlet Blocks and WPcom FSE:

I don't (currently) think of this template tag as a blocker for testing FSE on WPcom in production. Though I do (currently) think we should have it in block-based themes.

**Comment by apeatling** [comment]
What would be the expectation for this block? Should it actually be a block in the editor? I started building it, but I'm trying to understand the reason for it appearing in the editor. Would a user want to edit the design or link text?

Another option would be to render it automatically on the front end at the end of the `post-content` block.

**Comment by apeatling** [comment]
I guess users may also want to move the position of the edit link too?

**Comment by ianstewart** [comment]
Great question. Perhaps it doesn't even need to be a block? Our activity bar (I think you built that?!) does have an edit link — although I personally find it hard to find.

> I started building it

Note my note about priority. :D

**Comment by MaggieCabrera** [comment]
There was a conversation about this link and [the consensus](https://github.com/WordPress/gutenberg/issues/22724#issuecomment-782353923) was that it's not something we need or want to replicate
