### ISSUE TITLE
Coutoire (or Varia?): Disparity between front-end and Editor Styles with Bowen Starter Design

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2279]
## Steps to replicate

1. Create a site with the Bowen Starter Design (it uses Coutoire) at wp.com/new.
2. Compare the front-end result with the back end.

## Result

![image](https://user-images.githubusercontent.com/545779/88079905-f44a9f80-cb43-11ea-9360-53d7afd729c5.png)

## Expected

Expectation: the Editor styles getting much closer to the Front-End.

**Comment by ianstewart** [comment]
Here's the blocks used.

![image](https://user-images.githubusercontent.com/545779/88080446-b1d59280-cb44-11ea-898b-9d820ae394c5.png)

**Comment by jffng** [comment]
Hi @ianstewart — I believe this issue has been resolved via other block style improvements and fixes in Varia: 

<img width="1904" alt="Screen Shot 2021-02-09 at 2 16 10 PM" src="https://user-images.githubusercontent.com/5375500/107415475-69ca8d00-6ae1-11eb-91ac-b7365bcb785c.png">

Please re-open if I'm mistaken, and we can look into any specific issues that are still there.
