### ISSUE TITLE
Varia Themes: Blocks nested inside the Premium Content block missing margins

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2281]
## Steps to replicate

1. On a site with Premium plan, add Premium Content block to a post or a page.
2. Add some content to both subscriber and non-subscriber view. Use a heading, paragraph and buttons.
3. Go to preview (note it will only show the subscriber content. To see non-subscriber content you need to open the page while logged out of WordPress.com, and the post/page needs to be published first). Note the missing margins between blocks inside the Premium Cotnent.
4. Replicated in Stratford, Mayland, Maywood.

## Result

Premium Content block  / subscriber view/ editor:

![image](https://user-images.githubusercontent.com/4550351/88137761-998e7200-cc2f-11ea-93c2-248e67f89b78.png)

Premium Content block  / subscriber view/ preview:

![image](https://user-images.githubusercontent.com/4550351/88137784-a3b07080-cc2f-11ea-8585-8783f382a171.png)

Premium Content block  / non-subscriber view/ editor:

![image](https://user-images.githubusercontent.com/4550351/88137852-cc386a80-cc2f-11ea-8a23-478b604699ce.png)

Premium Content block  / non-subscriber view/ preview:

![image](https://user-images.githubusercontent.com/4550351/88137904-ea05cf80-cc2f-11ea-9626-b65083c7c452.png)

**Comment by iamtakashi** [comment]
+1. This is a blocker for releasing patterns for Premium Content cc @ianstewart 

For example:
![Screenshot 2020-09-28 at 14 49 15](https://user-images.githubusercontent.com/908665/94440695-d760c700-0199-11eb-9475-535d99580367.jpg)
