### ISSUE TITLE
Seedlet: link color overridden in the editor

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#2283]
As of Gutenberg 8.5.1, the default link color is overridden in the editor:

<img width="246" alt="Screen Shot 2020-07-22 at 12 30 51 PM" src="https://user-images.githubusercontent.com/5375500/88203270-e9f9d580-cc17-11ea-8daa-b3bb34da5005.png">

<img width="310" alt="Screen Shot 2020-07-22 at 12 37 57 PM" src="https://user-images.githubusercontent.com/5375500/88203695-35ac7f00-cc18-11ea-860b-726da267a215.png">

This perhaps has something to do with the `experimental-link-color` feature that was recently introduced. Disabling it doesn't solve this issue, however.

**Comment by kjellr** [comment]
Will this be fixed by https://github.com/Automattic/themes/pull/2275?

**Comment by Copons** [comment]
> Will this be fixed by #2275?

Yes!
This line here is how I'm fixing it: https://github.com/Automattic/themes/pull/2275/files#diff-7031c648a477f7ce6558aea53b8a1478R20

I'm not extremely happy about increasing the specificity for such generic rule, though, but I can't think of a better way.
The Guten link color is inlined last (at least in my test environment), and so has precedence over anything else with the same specificity.
`.wp-block a` shouldn't be a big deal, though, considering that 1) we are targeting blocks anyway; 2) most block-specific override are generally more specific.

**Comment by jffng** [comment]
Closed by #2275.
