### ISSUE TITLE
Baskerville 2: Footer floating into the content area or not visible in Firefox, IE, and Vivaldi

### ISSUE THREAD

**Issue by sashastone** [Automattic/themes#229]
## Steps to replicate

- Viewed user's site https://lasaluteintasca.com/ in Chrome and footer appeared at the bottom of the site as expected: https://d.pr/i/ngstiv
- Viewed their site in Firefox, and the footer floated into the content area: https://d.pr/i/9broX
- Activated Baskerville 2 on a test site https://smshetest039.blog/. Footer appeared at the bottom when viewed in Chrome, and not at all when viewed with Firefox: https://d.pr/i/clXQf8

## Result

- Results are inconsistent, as per this Slack thread: p1534280972000100-slack-livechat
- Other HEs noted that when they refreshed their browser window the issue was corrected. I was not able to replicate this. 

## Expected

- My expectation is for the footer to remain at the bottom of the site regardless of the browser in use. 

* User report: #5402479-hc
* Follow-up ticket: #1347909-zen
* User's site: https://lasaluteintasca.com/

**Comment by laurelfulford** [comment]
I was able to recreate this on the user's site -- I seemed to have more success when my adblocker was enabled, but I don't know if that's actually related.

**Comment by alaczek** [comment]
I was also able to re-create this on user site, but I only seemed to have success with my **ad block disabled**.  I wasn't able to fully figure it out, but it looks like the masonry container (`#posts`) has wrong height calculated and added inline. I think ads, and the font size changing to large while the site is being loaded is what might be tripping it up - maybe the masonry script is executed before those finish loading resulting in wrong container height? 

This required more investigation. In the short term I think two things could help:
* changing the font size to normal
* disabling the ads on the homepage
I'd try the fonts first, and if that doesn't do the trick, try disabling ads on the homepage next.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
