### ISSUE TITLE
Seedlet: Theme URI invalid in style.css

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#2290]
https://github.com/Automattic/themes/blob/19d951099f96e9a64af7a52659f9ea120938b996/seedlet/style.css#L3

https://github.com/Automattic/themes/seedlet is not a valid link and goes to 404.

Unless we are planning to change it to a demo site link anyway, this should be changed to:

https://github.com/Automattic/themes/tree/master/seedlet

**Comment by kjellr** [comment]
😄 That's weird! @jffng, please wrap that into your updates in #2285 — we'll need that right for when we resubmit.

**Comment by kjellr** [comment]
👍 Thanks!
