### ISSUE TITLE
Varia: Latest Posts block discrepancy between Read More link

### ISSUE THREAD

**Issue by fstath** [Automattic/themes#2294]
## Steps to replicate

Add the Latest Posts block and enable the Excerpt option.

## Result

On the Editor, it displays _Read More_ whereas on the published page it displays _Continue Reading_

Editor:
![Screenshot 2020-07-24 at 4 35 03 PM](https://user-images.githubusercontent.com/32326882/88396876-cf685d80-cdcb-11ea-9806-8862fa63677b.png)

Published page:
![Screenshot 2020-07-24 at 4 35 44 PM](https://user-images.githubusercontent.com/32326882/88396912-dc854c80-cdcb-11ea-9fe4-35afaedbe988.png)

## Expected

For the wording (Read More/Continue Reading) to be consistent between the editor and the published page/post.

* User report: https://wordpress.com/forums/topic/latest-posts-block-excerpt-display-discrepancy/

**Comment by arcangelini** [comment]
I think this may have been a Block related issue that has since been resolved with the "Read more text" option:

[![Screenshot](https://d.pr/i/tFi39y+)](https://d.pr/i/tFi39y)

[![Screenshot](https://d.pr/i/gTFxWF+)](https://d.pr/i/gTFxWF)

**Comment by danieldudzic** [comment]
@arcangelini the setting does allow to overwrite the default 'buggy' behavior, but the issue should be fixed nevertheless.

I have reported it now, in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/28969
