### ISSUE TITLE
Hever: iframe inside custom HTML block gets shrunk and aligned to the left

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#2295]
## Steps to replicate

1. Add a custom HTML block
2. Paste an iframe code inside. The code I tested is from an Amazon ad
3. Publish

## Result

The iframe was shrunk:

![Screen Shot 2020-07-26 at 07 45 28](https://user-images.githubusercontent.com/3696121/88479342-02b60400-cf14-11ea-9a7a-3d182cc02baa.png)

## Expected

For the iframe to be properly displayed and aligned. A workaround was to place the Custom HTML block inside a Group block:

![Screen Shot on 2020-07-26 at 07:47:12](https://user-images.githubusercontent.com/3696121/88479363-3bee7400-cf14-11ea-80a3-921e553c25e9.png)

---

I confirmed this didn't happen on all Varia themes. However, the issue is similar to this one: https://github.com/Automattic/themes/issues/1732

* User report: 3104103-zen
* Follow-up ticket: 3104103-zen

**Comment by jordesign** [comment]
Unable to recreate any more - it appears this has been resolved.
