### ISSUE TITLE
Spun: Portfolio Type archive pages show incorrect page title

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#230]
## Steps to replicate

1. Create a new portfolio project, and assign it a portfolio type.
2. Publish and view the archive page for that portfolio type.
3. Edit the project and assign a post format other than standard
4. Update and view the archive page for the portfolio type

## Result

With no post format assigned to a project, the portfolio type page simply lists "Archive" as the title. With post formats assigned, the post format of the most-recently published project is shows as the title for the archive page.

![advertisingmarketing_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/44140968-09ad7612-a07c-11e8-9fff-98dc1ed3eac7.png)

This screen shot from a page with the URL `/project-type/advertisingmarketing/` on a test site - two projects in that type with the most recent one set to the Quote post format.

## Expected

For the portfolio type to be displayed as the page title at all times, as it is on category, tag and author archive pages.

* User report: https://en.forums.wordpress.com/topic/how-to-not-show-post-format-on-portfolio-feature/
* User's site: https://tuangstudio.com/project-type/interactive-art-installation-art/

User currently has custom CSS provided by a forum volunteer to hide the title from displaying completely.

**Comment by laurelfulford** [comment]
Unfortunately, this exposes another issue: the ability to select post formats in Portfolios was removed from Jetpack, but it was not synced up on .com:

https://github.com/Automattic/jetpack/issues/1066

I've reported that here: #8098-wpcom. I'm not sure if that change now will have a negative impact; in the meantime, it does seem odd that the theme would be picking up the post format in any case, and could be worth a closer look. It could also be good to caution the user that the post format bit isn't working correctly, too.

**Comment by KokkieH** [comment]
Just a note the user appears to have since switched to the Awesome theme.

**Comment by alaczek** [comment]
Given that this is a retired theme, and the issue seem to be an edge-case, I'm suggesting a `wontfix` on this one.

**Comment by laurelfulford** [comment]
Good call, @alaczek -- I agree! Closing as such.

**Comment by KokkieH** [comment]
Thanks for looking. Not following up as the user also isn't using this theme any more.
