### ISSUE TITLE
Blask: No top margin on images in Thumbnail Grid gallery

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#231]
## Steps to replicate

1. Add a gallery of a few images to a post, page or portfolio project
2. Set the gallery type as Thumbnail Grid - number of columns don't appear to matter.
3. Publish

## Result

Images in the gallery are flush against each other at the top and bottom, unless images with different vertical dimensions are in the same row of the gallery:

![gallery_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/44149444-6c1ab934-a09c-11e8-81a3-306b9e247f2e.png)

## Expected

For there to be some space between gallery rows, as when I view the resulting post using a different theme.

Looking in the browser inspector, it appears the `figure` element has a top margin of both 0 and 1em, with 0 being the value used - if I disable that rule in the inspector the other one becomes active and the images display with the correct spacing, though with a multi-column gallery that also causes the gallery to display with one column fewer than specified.

![gallery_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/44149610-07a36932-a09d-11e8-9020-b28beb9ec32f.png)

* User report: https://en.forums.wordpress.com/topic/blask-and-thumbnail-gallery-spacing/#add-note
* User's site: Private site. Link in staff notes on forum thread.

**Comment by alaczek** [comment]
Fixed in r50194-wpcom-themes. Replied to the forum thread as well.

**Comment by KokkieH** [comment]
Thank you!
