### ISSUE TITLE
Twenty Twenty: Color annotations not working properly for site-title, menu and subtitles.

### ISSUE THREAD

**Issue by allancole** [Automattic/themes#2318]
## Steps to replicate

A recent change in color-annotations in Twenty Twenty caused some disruption in the site-title, menu and subtitles. 

## Result

When customizing the body font, the site-title, menu and subtitles are changed to the body font.

## Expected

The site-title, menu and subtitles should not change with the body-font.

* User report: #3188113-zd

## Related tickets:

https://github.com/Automattic/themes/issues/2049

**Comment by allancole** [comment]
Cc @kdevnel to close the loop when this issue is closed :-)

**Comment by allancole** [comment]
Fixed in #56490-wpcom-themes

**Comment by kdevnel** [comment]
Awesome, I've closed the loop. Appreciate the quick work here 🥇
