### ISSUE TITLE
Wilson: Border on Images with Alignment

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#2320]
## Steps to replicate
1. Create a post and add an Image block
2. Select an image with some external white area
3. Select an alignment for the image on the block toolbar:

![ImageBordersAlign](https://user-images.githubusercontent.com/16104522/89074151-3fd62800-d352-11ea-9186-35f981bd2583.png)

## Result

When an image has an alignment, it shows with a border on the site:

![ImageBorders](https://user-images.githubusercontent.com/16104522/89073979-de15be00-d351-11ea-9012-981b9e1db127.png)

## Expected

To show without borders, as it is when the image has no alignment.

Shared this CSS as a workaround:

```
img.alignleft, .alignleft img, img.aligncenter, .aligncenter img, img.alignright, .alignright img {
   border: none;
}
```

* User report: #23059160-hc

**Comment by jordesign** [comment]
I can still recreate this - and it seems like a stylistic choice by the theme. With no further reports in 12 months, and the fact Wilson is only installed on ~73k sites - I'm going to close this for now.

**Comment by jordesign** [comment]
Added this CSS solution to Theme Quirks:
p5nmAP-1b2-p2
