### ISSUE TITLE
Independent Publisher 2: Sidebar text/custom HTML widget titles aren't bold

### ISSUE THREAD

**Issue by kdevnel** [Automattic/themes#2322]
## Steps to replicate
* Activate theme on any site plan
* Add a text widget or custom HTML widget to the sidebar

## Result
You will see the issue is that the widget title won't be bold like the other widget types are.

![Screen Shot on 2020-08-01 at 08:52:24](https://user-images.githubusercontent.com/22053773/89096131-6b015b80-d3d4-11ea-9270-bbba7ff48ebe.png)

## Notes
It looks like there is a CSS styling conflict between some styles for `wf-active .widget_text h1` which is overriding the standard selector `.widget .widget-title, .widget .widgettitle`.

**Comment by kathrynwp** [comment]
@kdevnel Heya - which theme is this bug report for? Please add theme name to the beginning of the topic, and also select it under Milestone.

**Comment by kdevnel** [comment]
Oops! Sorry for the oversight 😅 
This is for **Independent Publisher 2**

**Comment by jordesign** [comment]
Closing this as no longer relevant with the new Block Widget editor - unable to insert the HTML widget or recreate.
