### ISSUE TITLE
Color annotations for Varia themes - the Block editor doesn't render the proper colors

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/themes#2328]
I was helping a user today using Balasana in a QS session, and we changed the color annotations in the Customizer, in Design > Customize > Colors and Backgrounds. Then went to edit the homepage and the editor doesn’t show the colors you selected, it shows the “standard” colors the blocks were designed with… it’s weird. Take a look:

## Result

<img width="1339" alt="Screen Shot 2020-08-05 at 15 23 11" src="https://user-images.githubusercontent.com/31009008/89456091-55bc6200-d731-11ea-8fde-5e442a71f6b2.png">

It’s even weirder that the Cover block in that snapshot shows that the primary color is blue (coming from the theme colors changed in the Customizer).

## Expected

<img width="1320" alt="Screen Shot on 2020-08-05 at 15-23-20" src="https://user-images.githubusercontent.com/31009008/89456112-5ead3380-d731-11ea-91c4-81c458044121.png">

Is there a way we can fix the editor to show the correct colors?

**Comment by ianstewart** [comment]
@allancole is this related to our custom colours work? And/or a recent Gutenberg update?

**Comment by chrisfromthelc** [comment]
Another report on this in #23613384-hc

**Comment by nagpai** [comment]
Another report here 
#25033306-hc

**Comment by ccwalburn** [comment]
Another report here: 3435526-zen

**Comment by ianstewart** [comment]
@davipontesblog I wasn't able to reproduce this today in testing with @ccwalburn is this still reproduce-able for you? Here's what I see in the Editor with Balasana active on a new page.

![image](https://user-images.githubusercontent.com/545779/97627332-3c0d7c80-19f9-11eb-89f4-c30964cde779.png)

**Comment by davipontesblog** [comment]
@ianstewart I believe this might be related to https://github.com/Automattic/themes/issues/2360.
I tried replicating the steps on a post on my test site today and the issue persisted, showing incorrect colors in the editor. Then I went into the Customizer, cleared the color palette back to Default, and selected a new palette, then saved the changes in the Customizer. Once I did that, the editor showed the correct colors.

**Comment by MaggieCabrera** [comment]
I believe there's two problems going on here:

* ~~The editor color palette issue: Some of the Varia children themes don't have dynamic colors on the editor color palette (they will always show the default colors no matter what we have selected on the customizer). An example of this is Stow, on the other hand Alves does have the dynamic implementation.~~ Disregard that, those themes with static editor color palettes are the ones that don't have color annotations implemented yet!
* The cover block issue: I think that one should be related to https://github.com/Automattic/themes/issues/2360 and that's proven much harder to debug. 

Let's tackle the first problem on this issue and leave the second to https://github.com/Automattic/themes/issues/2360

**Comment by jffng** [comment]
Hi @davipontesblog — I was unable to reproduce this issue. Here are the steps I followed:

- Activated Balasana on a wpcom simple site
- Added a media and text block and a cover block that used background colors from the editor palette.
- Chose new custom colors via the Customizer.
- Refreshed the editor, the custom colors are reflected correctly in the palette and in the blocks.

Is this still an issue or am I missing a step in the reproduction?

**Comment by davipontesblog** [comment]
> Hi @davipontesblog — I was unable to reproduce this issue. Here are the steps I followed:
> 
> * Activated Balasana on a wpcom simple site
> * Added a media and text block and a cover block that used background colors from the editor palette.
> * Chose new custom colors via the Customizer.
> * Refreshed the editor, the custom colors are reflected correctly in the palette and in the blocks.
> 
> Is this still an issue or am I missing a step in the reproduction?

Thanks for testing again @jffng ! It may be that now that https://github.com/Automattic/themes/issues/2360 is fixed and closed, this is now fixed as well. I am going to close this for now, we can reopen if more reports come in :)
