### ISSUE TITLE
Scrawl: Missing enhancements.js file in WordPress.org version of the theme.

### ISSUE THREAD

**Issue by BandonRandon** [Automattic/themes#233]
In the latest version of Scraw 1.0.12 admin attempts to load `plugin-enhancements.php` in `plugin-enhancements.js` 

```
    // Adds our JS file to the queue that WordPress will load
        wp_enqueue_script( 'scrawl_jetpack_admin_script', get_template_directory_uri() . '/inc/plugin-enhancements.js', array( 'jquery' ), '20160624', true );
```

However, this file is not found in the theme folder:
https://themes.trac.wordpress.org/browser/scrawl/1.0.12/inc

I've created a patch for adding the file at:
https://gist.github.com/BandonRandon/a445b2a9c0c8340a38a604e4778d5d1f

This was my first time using `git SVN` so hopefully the patch works.

## Steps to replicate
Install the theme, visit a page in WP-Admin then open the browser inspector.

## Result
A JavaScript error appears in the browser when a `404` page is loaded instead of the `plugin-enhancements.js` file

## Expected

The file to load :)

* User report: https://wordpress.org/support/topic/plugin-enhancements-js/

**Comment by laurelfulford** [comment]
I think this must've been an issue in our WP.org submission tool at one point -- that file _should_ be added automatically, but it's not there. 

I regenerated the zip for Scrawl and tested it, and the file is present and loading correctly. So I've uploaded a new version of Scrawl to WordPress.org (v.1.0.13, https://themes.trac.wordpress.org/ticket/58854), and followed up in the forum thread.
