### ISSUE TITLE
Hever: Featured Image Not Appearing On Page When Set

### ISSUE THREAD

**Issue by susanjanec** [Automattic/themes#2330]
## Steps to replicate / Result

A user reported when adding a featured image on the Hever theme, the image is nowhere to be seen on the page when viewing the live page.

Replicated this on my own test site, using the About template.

Although the featured image does show in a social media preview, but not sure if this is a bug on the theme that the featured image doesn't appear on the page.

## Expected

The Featured Image set would show on the live page.

* User report: [22118057-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=22118057)
* Follow-up ticket: [3197868-zd](https://woothemes.zendesk.com/agent/tickets/3197868)

**Comment by MaggieCabrera** [comment]
This looks intentional to me and it's happening on Varia and all its children. Not sure if this is actually a bug. @kjellr what do you think about this issue?

**Comment by kjellr** [comment]
Hmm. Yeah, featured images are not always supported by default for pages. It looks like Varia and Seedlet do not enable them. <strike>When I test pages locally, I do not see the featured image option at all, so I wonder if something on WP.com is enabling that globally for pages, even if the theme doesn't render them? </strike>

In any case, the omission of featured images for pages seems arbitrary to me. I tend to think we should just include featured images on page templates for both Varia and Seedlet (and their children). Though I know that may end up being a little surprising for existing sites if they have added a featured image already and it hasn't appeared. 

cc @melchoyce for your opinions on that too.

**Comment by MaggieCabrera** [comment]
I do see the option locally, so that's really strange

**Comment by kjellr** [comment]
Whoops, it is there. 🙃 Not sure how I missed that.

**Comment by kelasante** [comment]
Another report in 3880840-zen. Since this has been closed, does this mean the issue is fixed?
