### ISSUE TITLE
Varia (and other themes): Full width VideoPress setting doesn't make videos full width

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#2333]
This affects multiples themes. If you add a VideoPress video to a page and choose the Full Width video it should be full browser width. It shows as full width in the editor, but not on the published page.

This was an issue on these themes that I tested (Varia, Ovation, Twotone, Dyad 2), those were the only ones I tested so it probably affects other themes.

Twenty Twenty was the only theme that I found that does make it the correct size.

## Steps to replicate

* Add a VideoPress video to the page, choose full width:

![https://d.pr/i/bMbdeg](https://d.pr/i/bMbdeg+)

## Result

It is not full width on the published page (YouTube is on the bottom, which shows full width):
![https://d.pr/i/Ao61s0](https://d.pr/i/Ao61s0+)

## Expected

Should be full width like Twenty Twenty:

![https://d.pr/i/aovqid](https://d.pr/i/aovqid+)

Other themes like Dyad 2 make it full width but the height is not increased which isn't ideal:

![https://d.pr/i/e9Lq78](https://d.pr/i/e9Lq78+)

* User report: 3204733-zen

I provided this solution (this was for the Twotone theme):

```
.alignfull iframe {
width: 100%;
}
```

It appears something like this might work better for Varia:

```
.alignfull .wp-block-embed__wrapper {
    position: relative;
    padding-bottom: 56.25%;
    height: 0;
}

.wp-block-video.alignfull iframe {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
}
```

**Comment by tanjoymor** [comment]
Another report: #3317097-zd with the Lodestar theme. The above CSS options didn't fix the problem.

**Comment by katiebethbrown** [comment]
Report in 3449198-zd-woothemes as well.

Theme is Ovation. None of the above CSS resolves. Even though the block in the editor is set to full width the block on the live page doesn't have the `alignfull` class like the other full-width elements:

<img width="381" alt="KXHT8o" src="https://user-images.githubusercontent.com/42279181/97818822-ff908980-1c61-11eb-8ce9-1659c2296b73.png">

**Comment by ivan-ottinger** [comment]
Possible workaround: Enclose the Video block inside "gutter-less" one-column Layout Grid block.

I have suggested it to the user in 3449198-zd-woothemes. It seems to work well to me.

**Comment by scruffian** [comment]
I think this is an issue with the block, rather than something we should fix our themes: https://github.com/Automattic/jetpack/issues/17714

**Comment by scruffian** [comment]
I also raised an issue with the core video block: https://github.com/WordPress/gutenberg/issues/26700

**Comment by formosattic** [comment]
+1 26324523-hc

Thanks @ivan-ottinger, the Layout Grid workaround worked, although in the editor, I've kept having to recover the block.
