### ISSUE TITLE
Rivington: Navigation block is not visible due to color combination

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#2343]
## Steps to replicate

1. Add the Navigation block
2. Add menu items

## Result

It is very difficult to see the navigation menu items:

![89736190-425d0f80-da2d-11ea-8c44-c6cdbfebcc81](https://user-images.githubusercontent.com/3696121/89815661-c507cc80-db0a-11ea-8fce-947f8411bb3b.png)

## Expected

To see the menu items using the same link color that's displayed on the actual site

**Comment by scruffian** [comment]
I think this should be fixed in the block itself, see: https://github.com/WordPress/gutenberg/pull/26698

**Comment by scruffian** [comment]
Since this is an issue in Gutenberg I'll close this.
