### ISSUE TITLE
AltoFocus: Footer is floating on top of the content

### ISSUE THREAD

**Issue by fresatomica** [Automattic/themes#2347]
## Steps to replicate

Activate AltoFocus and enable the WordPress.com branding in the footer.
Visit your site and scroll up and down.

## Result

The branding from the footer is floating on top of the page content and is fixed to the bottom
Screenshot: https://d.pr/i/sELqol

## Expected

The WordPress.com branding should only be seen once you've scrolled to the very bottom.

* User report: https://wordpress.com/forums/topic/altofocus-new-footer-oddity/

**Comment by kathrynwp** [comment]
@danieldudzic - could this be related to the recent PR for this issue? #2179
