### ISSUE TITLE
Ixion: Social Links menu not being displayed

### ISSUE THREAD

**Issue by thabotswana** [Automattic/themes#2353]
## Steps to replicate

1. Go to *Design ▸ Customize ▸ Menus*
2. Create a Social Links menu
3. Select **Social Menu** in **Menu Locations**
4. Add links to social media profiles using **Custom Links**

![Screen Shot 2020-08-13 at 17 17 55](https://user-images.githubusercontent.com/35628116/90153295-132a0380-dd89-11ea-9b39-927ef913c251.png)

## Result

Social Links menu is not being displayed.

## Expected

A Social Links menu should appear in the header.

* User report: 23185168-hc
* Follow-up ticket: 3222034-zen
* User’s site: https://biglittlefishweb.wordpress.com/

**Comment by Gilmoursa** [comment]
Another instance of this bug at:
http://dcmtransport.wordpress.com
