### ISSUE TITLE
Twenty Twenty: Embed Block - PDF embeds are small in height

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#2355]
## Steps to replicate

1. Create a page/post.
2. Add your pdf file through an Embed block
3. Check the height of the PDF file.

## Result

They are small in height

## Expected

To have the height which is inline in the code.

I have used this as a workaround:

```
/* Temp fix pdf file embed | ZZ-xxxxxx-zen */
.wp-block-embed.is-type-rich .wp-block-embed__wrapper object {
    height: -webkit-fill-available;
}
```
Other themes follow the height correctly.

* Follow-up ticket: #3213971-zen

**Comment by danieldudzic** [comment]
I'm closing this in favor of: https://github.com/Automattic/themes/issues/1919
