### ISSUE TITLE
Argent: Post titles broken on mobile

### ISSUE THREAD

**Issue by ehti** [Automattic/themes#236]
## Steps to replicate

* Activate Argent
* Open blog page on mobile - e.g. https://argentdemo.wordpress.com/blog/

## Result

Post titles that go beyond a few words are broken/split, looks really bad.

## Expected

For titles to show up either below or above the featured image on mobile.

Issue was in #5773037-hc , it's fixed for the user now using this custom CSS so no follow-up needed:

```
/* Fix post titles on mobile */
@media only screen and (max-width: 767px) {
.post-thumbnail {
display: block;
width: 100%;
}
}
```

**Comment by kristarella** [comment]
Another report here: 4931337-hc

**Comment by alaczek** [comment]
Fixed by adding the above CSS in r50191-wpcom-themes
