### ISSUE TITLE
Pictorico: posts per page not being respected

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#2368]
According to https://web.archive.org/web/20181122022348/https://pictoricodemo.wordpress.com/, Pictorico used to display 12 posts. Somehow, now the theme is showing only 8, which is the default number for the Jetpack Infinite Scroll button.

## Steps to replicate
1. Activate the theme on a site with more than 8 posts
2. Make sure the posts per page is set to more than 8 posts

## Result

I see only 8 posts, always.

## Expected
To see the predefined number.

* User report: #3216595-zd

**Comment by scruffian** [comment]
This is being tracked here: https://github.com/Automattic/jetpack/issues/16471
