### ISSUE TITLE
Espied: Portfolio Item appearing and disappearing

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#237]
## Steps to replicate

* With the Espied theme installed ensure you have a number of Portfolio items that are both an odd number, and also 1 _more_ than the number of item being shown per page.
(eg. posts-per-page = 10 & no. of portfolio posts = 11 OR posts-per-page = 8 & no. of portfolio posts = 9).

* Appears to happen _both_ with 'Infinite Scroll' enabled and disabled.

*view the site at a width below 910px. Bug was witnessed in both Safari 11.1.2 and Chrome 68.0.3440.

*Testing site with setup already recreating bug - https://lamontjordan.blog/portfolio/

* Scroll to the bottom of the page

## Result

![espied_bug](https://user-images.githubusercontent.com/1842363/44342421-47d28f80-a4ce-11e8-9c33-d702d2bc5d8f.gif)

The final item appears when infinite scroll is triggered (or next page is clicked) but then disappears again shortly after. It then loops through this behaviour as the browser stays scrolled at the bottom of the page.

## Expected

The final image _should_ appear and then remain displayed

* User report: 5645995-hc (a short term fix in place on the user site - so bug is no longer visible there)
* Follow-up ticket: [shortlink to ticket, ie #1350387-zd]
* User's site: https://loulayorke.com/portfolio/

**Comment by kosiew** [comment]
https://woothemes.zendesk.com/agent/tickets/1350387

pinging for update :-)

**Comment by kosiew** [comment]
https://woothemes.zendesk.com/agent/tickets/1350387

pinging for update :-)

**Comment by Robertght** [comment]
This ticket came in the queue again.

**Comment by madhattermattic** [comment]
Ticket popped up again, pinging for update. Thanks!

**Comment by kriskorn** [comment]
Another report in 2213741-zen.

**Comment by jordesign** [comment]
This appears to be resolved in my testing now - so marking this as closed.
