### ISSUE TITLE
Pique: core/Jetpack gallery blocks are broken

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/themes#2371]
## Steps to replicate

- On a new or existing site, make sure to activate the theme Pique.
- Set a homepage / static page
- On this page, add a gallery block (not CoBlocks ones). It can be the "Gallery" or "Tiled Gallery" block from what I've tested. Make sure there is some text on the page too just for testing and to replicate the bug.
- Publish the page, check live page.

## Result

The gallery is showing on top of the other page content:

<img width="752" alt="Screen Shot 2020-08-20 at 10 47 06 AM" src="https://user-images.githubusercontent.com/31009008/90787238-845e3f00-e2d2-11ea-967b-a109dc7db062.png">

tested on my test site test375739965.wordpress.com
Gutenberg: 8.7.1
CoBlocks: 1.23.0
wpcom-FSE: 212251766

and also seen on a user site - divaboxoffice.wordpress.com - see info below.
Gutenberg: 8.7.1
CoBlocks: 1.23.0
wpcom-FSE: 212251766

## Expected

Gallery to show in line where the editor has it placed:

<img width="880" alt="Screen Shot on 2020-08-20 at 10-50-45" src="https://user-images.githubusercontent.com/31009008/90787747-0e0e0c80-e2d3-11ea-8351-4fe24bb75e59.png">

* User report: #22522540-hc]

**Comment by davipontesblog** [comment]
I was able to isolate this to Pique by changing the theme on my test site to a different WordPress.com classic theme, such as Lodestar.

**Comment by jeffikus** [comment]
@scruffian can you take a look at this one please?

**Comment by scruffian** [comment]
I added a PR to fix this here: https://github.com/Automattic/themes/pull/2393/files
