### ISSUE TITLE
Shawburn: table blocks aren't wrapping correctly

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#2375]
## Steps to replicate
1. Create a table block with fixed column widths and long, wrapping lines
2. Visit the page in IE11

I believe this is due to inconsistent browser implementation of `word-break: break-word`, which is deprecated:
https://www.w3.org/TR/css-text-3/#valdef-word-break-break-word
https://caniuse.com/#feat=word-break

## Result
Text seems to `break-all`:

![image](https://user-images.githubusercontent.com/32492176/90822560-e0848b80-e2f1-11ea-9aa4-a003a06b533b.png)

## Expected
![image](https://user-images.githubusercontent.com/32492176/90823107-ad8ec780-e2f2-11ea-974b-1f964d303230.png)

As a bonus, if the table block is set to NOT have fixed column widths, it does `break-all` on all browsers. Not sure if that's intended behavior or not.

* User report: 23497642-hc
* Follow-up ticket: 3243763-zen

**Comment by tbradsha** [comment]
See also #2005.

**Comment by jacklenox** [comment]
That PR didn't close this. I'm preparing another one now that will.
