### ISSUE TITLE
Seedlet: Reynolds FSE block editor content styles do not match frontend styles 

### ISSUE THREAD

**Issue by jeyip** [Automattic/themes#2379]
## Steps to replicate

1. Start the Horizon FSE flow https://horizon.wordpress.com/new?flags=gutenboarding/site-editor
2. Select the Reynolds (FSE) design
3. Create the site
4. Visit the site editor
5. Compare frontend styling with styling in the block editor
6. Note the distinct differences, like button border-color

<img width="1002" alt="Screen Shot 2020-08-21 at 2 46 33 AM" src="https://user-images.githubusercontent.com/5414230/90877306-b5815280-e358-11ea-86b0-826282d93f8b.png">
<img width="1005" alt="Screen Shot 2020-08-21 at 2 46 17 AM" src="https://user-images.githubusercontent.com/5414230/90877323-b9ad7000-e358-11ea-9380-d6e65b803796.png">

## Result
Content in the block editor is styled differently than in the frontend of the site

## Expected
I expect the content styling I see in the block editor to resemble what is eventually displayed in the frontend of the site.

**Comment by noahtallen** [comment]
The Reynolds design was removed from the flow, so I'm closing this out.
