### ISSUE TITLE
Baskerville 2: Infinite scroll changing the placement of the latest posts

### ISSUE THREAD

**Issue by galakhyati** [Automattic/themes#239]
## Steps to replicate

Case 1:
1. Have infinite scroll enabled with latest posts on the homepage.
2. The user has 22 published posts.
3. When scrolling through the page, the older posts replace the placement of the latest posts on the top of the page.

Here is a screenshot the user shared in chat: https://imgur.com/a/RIY0wFl

Case 2:
1. Disable Infinite Scroll with latest posts on the homepage.
2. Click on Older Post on the homepage, the older posts show fine with the latest on the top.
3. Click on the Older Post button the second time, the older post replaces itself with the latest post on top. And within a second it shows the latest post in its place too.
Screencast from the user's site: http://cld.wthms.co/HTJcdt

Note: On activating the Infinite Scroll again on the user's site, I was unable to replicate the issue again, here is a screencast I recorded on their site on enabling the setting again: http://cld.wthms.co/bxL0AX

I have also asked the user to try and replicate the issue again and share a screencast with us.

## Result

Case 1:
The older posts replaced the latest posts on top.

Case 2:
The older posts replaced the latest post on 2nd click on the Older Post button, but within few seconds got fixed too.

## Expected

Case 1: The latest posts should stay as is on top and the older posts should load below it.

Case 2: Again, the latest posts should stay as is on top and the older posts should load below it for all the times and stay as is.

* User report: #2540864-hc
* Follow-up ticket: #1361022-zen
* User's site: https://letrannguyenlam.com/

**Comment by laurelfulford** [comment]
I can recreate this issue on a test site; might be related to #208.

**Comment by ajaykj** [comment]
The issue came up in `Play` mode. I have sent a message to the user and put it on `on-hold` again.

**Comment by coder-karen** [comment]
Any updates on this? As it's been two weeks I've again sent a message to the user, ticket on-hold again.

**Comment by Jstachurski** [comment]
There was another report of this here: #1455469-zen

**Comment by Robertght** [comment]
A new request from the user in here: #1488276-zen

**Comment by lamosty** [comment]
A new request from the user in here: #1597846-zen.

**Comment by laurelfulford** [comment]
I think the fix in #208 should also take care of this, but like the comment there, would appreciate a few sets of eyes on it before following up with users. 

It's already deployed, since it's a pretty low key change; I'm just not sure it's taking care of all these odd cases folks are running into!

**Comment by laurelfulford** [comment]
It looks l like the fix for #208 is doing the trick, so I'm also going to consider this one fixed. 

It looks like the ZD tickets are all closed, so I can't comment on them. 

@galakhyati, can you please follow up on the initial report 1361022-zen?
And @Jstachurski , can you please follow up with the other new report added in 1455469-zen?

Given the inconsistent nature of this issue, in #208 I suggested adding a caveat to the follow up, just in case I've missed some case where the issue still happens. In the forums, I used the following:

> However, we’ve found this issue presents itself inconsistently, so it’s possible we missed a specific case where it can be replicated. If you do continue to experience this problem after clearing your browser cache, please don’t hesitate to let us know!

.... but pretty much anything that captures the spirit of that would do it! 

If any issues do come back about this, or if you have any questions, please let me know!
