### ISSUE TITLE
Shoreditch: Shop Page not displaying all WooCommerce products 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#24]
This issue was originally reported by @rossanafmenezes in 4994-wpcom-themes:

The user was trying to display more items on his page ​https://multihatclub.com/shop/ Which is only displaying 6 out of 7 at the moment.

Switching the theme to Argent fixed the issue. 

@danieldudzic investigated and found the following:

>  This issue occurs in multiple themes and is not exclusive to Shoreditch.
> 
> I believe it happens when a theme:
> 
> * Includes the duplicate products fix: `shoreditch_woocommerce_jetpack_duplicate_products` function (​https://github.com/Automattic/jetpack/issues/1135) 
> * Overrides number of products per page in Jetpack infinite scroll: `shoreditch_woocommerce_jetpack_products_per_page`
> * Overrides the number of products per page: `shoreditch_woocommerce_products_per_page` 
> 
> Shoreditch sets the number of products per page to 6.
> 
> But you can test this with Karuna for example. Karuna overrides the number of products per page to 12.
> 
> Make sure you have:
> 
> * 13 products
> * Set Reading Settings > Blog pages show at most to 13
> * Infinite scroll enabled 
> 
> You should be able to replicate, Karuna only loading 12 products, and failing to load the 13th one.
> 
> I've tried a number of things, but wasn't able to find a solution.
> 
> I suspect that the issue might have to do with the code in `karuna_woocommerce_jetpack_duplicate_products` but definitely need a second pair of eyes on this. 

* User report: 1731173-hc
* Follow-up ticket: 943682-zd
* User's site: https://multihatclub.com/shop/
* Related Slack chat: p1517915463000285-slack-livechat

**Comment by automattic-ian** [comment]
- new report from a different user in 2060659-hc
- user on sela theme 
- site: http://alicialytle.com
