### ISSUE TITLE
P2 Breathe: CSS causes font to become progressively larger within nested lists

### ISSUE THREAD

**Issue by sixhours** [Automattic/themes#240]
## Steps to replicate

Add a nested list with multiple levels to a P2 post or comment, something like:

- First item
-- Second item
--- Third item
---- Fourth Item

Font size becomes progressively larger with each `ul` or `ol`, due to the following CSS:

```
p, ul, ol {
  font-size: 1.05em;
}
```

Noticed this on several internal P2s. Ping me in Slack for a screenshot if you need one. :)

## Expected

Font size should stay the same.

No follow-up necessary for this, it was brought up internally.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
