### ISSUE TITLE
Coutoire: Headings bolded inside the Editor are not shown as bold on the live site

### ISSUE THREAD

**Issue by silvio-meter** [Automattic/themes#2415]
## Steps to replicate

Add the Heading Block to a post or a page inside the Editor.

![Optional alternative text if image doesn't load](https://testsite257com.files.wordpress.com/2019/12/heading-bold.png)
--

## Result

The headings aren't bold on the live site.

![Optional alternative text if image doesn't load](https://testsite257com.files.wordpress.com/2020/08/heding-2.png)

I also tested this with the Twenty Twenty theme and it works as expected.

## Expected

Heading should be bold on the live site as well. I managed to fix it with this CSS:

```
/*Making the titles blod -23319836-hc - SM*/
strong {
font-weight: bold;
}
```

* User report: [ #23319836-hc]

**Comment by MaggieCabrera** [comment]
This was fixed in #2462
