### ISSUE TITLE
Seedlet: load default editor palette on site creation

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#2416]
When I create a new site on wpcom and set its theme to Seedlet, the site does not load Seedlet's default editor palette:

<img width="1904" alt="Screen Shot 2020-08-31 at 2 49 04 PM" src="https://user-images.githubusercontent.com/5375500/91755907-e142da80-eb99-11ea-9625-6e943eaca3ce.png">

**Comment by jffng** [comment]
cc @jeffikus @kjellr if you're able to replicate, that would be helpful.

**Comment by jeffikus** [comment]
@jffng tested the PR, LGTM!

**Comment by jffng** [comment]
closed by #2418
