### ISSUE TITLE
Seedlet: Block Styles are not loading on WordPress.com

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2419]
## Steps to replicate

As noted in https://github.com/Automattic/themes/issues/2406#issuecomment-684796649, none of Seedlet's block styles show up on WordPress.com.

Seedlet ships with [two block styles](https://github.com/Automattic/themes/blob/e1403c15aa82615ac3d9fdb421a5ec3e7d2b5115/seedlet/inc/block-styles.php#L15-L30): 

- Alternating Grid (Latest Posts Block)
- Alternating Grid (Blog Posts Block)

The former is also available by loading the ["Alternating Grid of Latest Posts" block pattern](https://cloudup.com/cLEVSGj9-Kn). This pattern is still available, and it correctly loads the block styles. However, it's impossible to switch away from the block style, since the UI is not available. 

## Screenshots

Latest Posts Block

Self-Hosted|WordPress.com
---|---
<img width="354" alt="Screen Shot 2020-09-01 at 7 58 36 AM" src="https://user-images.githubusercontent.com/1202812/91848916-3679fd00-ec29-11ea-8d54-a34878287a93.png">|<img width="347" alt="Screen Shot 2020-09-01 at 7 59 54 AM" src="https://user-images.githubusercontent.com/1202812/91848922-38dc5700-ec29-11ea-900f-ba8e40c912d5.png">

Blog Posts Block

Self-Hosted|WordPress.com
---|---
<img width="324" alt="Screen Shot 2020-09-01 at 8 02 31 AM" src="https://user-images.githubusercontent.com/1202812/91849099-83f66a00-ec29-11ea-9089-1d7df7b62070.png">|<img width="325" alt="Screen Shot 2020-09-01 at 8 02 14 AM" src="https://user-images.githubusercontent.com/1202812/91849110-8658c400-ec29-11ea-98c2-993551d6cec0.png">

**Comment by kjellr** [comment]
cc @jeffikus + @jffng. 

Also maybe @Automattic/cylon in case you're aware of anything .com-specific that might be hiding the block styles.

**Comment by pbking** [comment]
Evaluating today, the block pattern for "Latest Posts" block seems to be loading as expected on .com. The Block Pattern "Alternating Grid" is available both in the side panel and the selection mechanism pictured.

![image](https://user-images.githubusercontent.com/146530/105744349-ff272800-5f0a-11eb-8bce-5b903edbdc17.png)

For the "Blog Posts" block I also saw the Alternating Grid option in the side panel, switching to it worked as expected.  However bringing up the menu pictured in the description caused a Gutencrash.  I believe that to be a separate issue than this though I can't say what.

@kjellr can you confirm that the block patterns are back on .com?

**Comment by kjellr** [comment]
Yeah, they're working for me! I think it's ok to close.
