### ISSUE TITLE
Seedlet: Re-assess the theme's wrapper elements

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2426]
The current DOM structure of Seedlet's pages involves a series of wrapper elements: 

- [`.site-content`](https://github.com/Automattic/themes/blob/742fe236223694e579ad3ee2365081e195df0938/seedlet/header.php#L114)
- [`.content-area`](https://github.com/Automattic/themes/blob/742fe236223694e579ad3ee2365081e195df0938/seedlet/index.php#L19)
- [`.site-main`](https://github.com/Automattic/themes/blob/742fe236223694e579ad3ee2365081e195df0938/seedlet/index.php#L20)

Based on a cursory chat with @allancole, it sounds like these layers may not be necessary. We should dive back in and clean these up so we aren't outputting unnecessary wrappers on each page.

**Comment by scruffian** [comment]
This matches what we do in Varia. Now the theme has been in production for a while I think it would be risky to make changes so I suggest we just close this.
