### ISSUE TITLE
Twenty Twenty: Font size setting for Headings changing font size for base font on mobile

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#2427]
If you set a custom font for headings and base, and adjust the font size for headings, it will change the font size for the base font on screen/window widths 700px and narrower. 

## Steps to replicate

1. Set heading font
2. Select font size for heading other than Normal
3. View on mobile and body font will show very small. Screenshot: https://cloudup.com/czWzGA6yoX8
4. Set heading font back to Normal size and the base font size corrects. Screenshot: https://cloudup.com/cvIzY2eHctM

The font size setting here, when commented out fixes the issue for the base font when the heading font is set for fonts other than normal, but this might not be the actual cause of the issue. Browser web inspector shows Noto Sans font family declaration is overridden.

`.wf-active html, .wf-active body {
    font-family: "Noto Sans",sans-serif;
    font-size: 81.25%;
    font-style: normal;
    font-weight: 400;
}`

## Expected

Expect that font size setting for heading would not change the displayed font size for the base font.

* User report: #12657910-hc
* Follow-up ticket: #3279536-zd

**Comment by MaggieCabrera** [comment]
This issue is not related to the theme itself, but the customizer instead

**Comment by mikeicode** [comment]
@MaggieCabrera This might be somewhat theme related. We ran into this on a site which was using Twenty Twenty. I tracked the issue with the body text font size on mobile down to the customer having a custom font set and the "Large" font size set for the heading. I tested this on another theme (Radcliffe 2) to see if the same Customizer font settings would cause the same issue which it didn't:

Twenty Twenty (the issue): 

![https://d.pr/i/bJ74k8](https://d.pr/i/bJ74k8+)


Radcliffe 2 (no issue): 

![https://d.pr/i/7U45Ai](https://d.pr/i/7U45Ai+)

**Comment by nerdysandy** [comment]
Reported on 25595907-hc

**Comment by kathrynwp** [comment]
Another font annotation bug for this theme: #2814

**Comment by MaggieCabrera** [comment]
Looks similar to https://github.com/Automattic/themes/issues/1817

**Comment by danieldudzic** [comment]
This should be now fixed via r58006
