### ISSUE TITLE
Pique: Masonry Gallery Displays Inline in Theme Panel 

### ISSUE THREAD

**Issue by ash1eygrace** [Automattic/themes#2428]
## Steps to replicate

1. Have a Static Frontpage already setup
2. Create a new page, and add a Masonry Gallery block to this page and then Publish. 
3. Add the newly created page with the Masonry Gallery block to a Theme Panel via Site > Design > Customize > Theme Options.  

## Result

The Masonry Gallery block is displayed inline on the homepage panel.

<img width="1598" alt="Screen Shot 2020-09-02 at 2 11 51 PM" src="https://user-images.githubusercontent.com/29527450/92031700-44fa0e80-ed26-11ea-8e0d-412fec0d3a5e.png">

## Expected

I expect the Masonry Gallery to be displayed in a grid

Gave the user CSS as a workaround: 

```
/*Allow coblocks gallery on homepage to be a grid | X-hc sb*/
.home .coblocks-gallery ul {
  display: flex;
  flex-wrap: wrap;
}
```

* User report: [5393126-hc]

**Comment by Thelmachido** [comment]
Same problem on this site https://zlandflyfishing.wordpress.com/. 

![Capture](https://user-images.githubusercontent.com/41231764/96487121-48494b00-123d-11eb-915f-bdd11fbe8cfa.PNG)


Other gallery types are not affected, it's only the Masonry Gallery. CSS code from @ash1eygrace worked on site. Thanx :) 

* User report and follow-up ticket: https://woothemes.zendesk.com/agent/tickets/3417906

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
