### ISSUE TITLE
Seedlet: Missing translation function for the comment form heading

### ISSUE THREAD

**Issue by carolinan** [Automattic/themes#2429]
## Steps to replicate

See https://github.com/Automattic/themes/blob/master/seedlet/comments.php#L74

```
	comment_form( array(
		'logged_in_as'	=> null,
		'title_reply'	=> esc_html( 'Leave a Comment', 'seedlet')
	) );
```

`esc_html()` is used instead of `esc_html__()`.

## Result
The comment form heading can not be translated.

**Comment by kjellr** [comment]
Closed via #2430
