### ISSUE TITLE
TextBook: Tiny Books in Goodreads Widget

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#243]
## Steps to replicate
- Enable Textbook theme
- Add a Goodreads widget to the sidebar
- Populate with a goodreads ID
- Choose Currently Reading

## Result
The widget appears, but the book cover images appear extremely small (just a few pixels wide and about twice that for the height).  This seems to be because the theme is adding padding around the book image.

## Expected
I expect a small but still discernible image of the book cover.

* User report:
https://en.forums.wordpress.com/topic/goodreads-widget-not-displaying-correctly/#add-note

* Follow-up ticket:
(same)

* User's site:
https://donjimmyreviews.wordpress.com/
![screen shot 2018-08-27 at 11 30 57 am](https://user-images.githubusercontent.com/3476361/44676187-c314d380-a9ef-11e8-99ce-29a42e790572.png)

**Comment by supernovia** [comment]
Noting on my own test site, the following CSS produces a more reasonable looking widget:

`
div[class^=gr_custom_book_container] {
	box-sizing: content-box;
}

.widget_goodreads>div>div>div:before {
   border-bottom: 0px;
}`

**Comment by laurelfulford** [comment]
I was able to reproduce this on my test site.
