### ISSUE TITLE
Twenty Twenty: CoBlocks Dynamic HR Block broken style

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/themes#2432]
## Steps to replicate

- On a WordPress.com Simple site add Twenty Twenty theme. 
- Create a page or post and add the Dynamic HR Block from CoBlocks
- Set it to the Line Style
- View the post

## Result

- The styling is broken and does not display properly.
<img width="1570" alt="Screen Shot 2020-09-05 at 9 30 35 AM" src="https://user-images.githubusercontent.com/1326294/92305114-7b1fd400-ef5a-11ea-8901-336577cf87c3.png">

## Expected

- The block should display as a line instead of the broken style in the screenshot above.

## More information

- This only happens on Simple sites
- This seems to be a known issue that was resolved by CoBlocks here but doesn't apply on Simple Sites
https://github.com/godaddy-wordpress/coblocks/pull/1109

* User report: #3288038-zd

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
