### ISSUE TITLE
Seedlet: media & text block image repeats if set to crop

### ISSUE THREAD

**Issue by sirbrillig** [Automattic/themes#2434]
## Steps to replicate

- Add a "Media & text" block to a page.
- Add an image to the media side.
- Enable "Crop image to fill entire column" in the block options.
- Notice that when the image height is taller than the image, the image repeats.

<img width="834" alt="Screen Shot 2020-09-06 at 12 24 20 PM" src="https://user-images.githubusercontent.com/2036909/92413538-93d8e700-f11e-11ea-93c1-5d8ddf86e9a8.png">

**Comment by sirbrillig** [comment]
Hm... I think this actually might be a bug with the block. I was just able to reproduce it on TwentyTwenty as well. 🤔  Not sure where to report that. Any ideas?

**Comment by jffng** [comment]
Hey @sirbrillig this looks like an issue to report in the Gutenberg repo and someone will hopefully add the appropriate labels noting that it's a bug with the media & text block: https://github.com/WordPress/gutenberg/issues?q=is%3Aissue+is%3Aopen+media+text+label%3A%22%5BBlock%5D+Media+%26+Text%22
