### ISSUE TITLE
Seedlet: Search block support updates needed

### ISSUE THREAD

**Issue by apeatling** [Automattic/themes#2443]
## Issues

The search block now includes options for showing different layouts, including hiding the title. Currently the block renders incorrectly when using Seedlet. Here's a list of issues:

1. The title renders inline with the search form, it should render above:

<img width="736" alt="Screen Shot 2020-09-09 at 12 50 31 PM" src="https://user-images.githubusercontent.com/1464705/92646307-14245700-f29b-11ea-9097-4218a6ec9bda.png">

2. The "button inside" option renders a button that looks incorrectly sized:

<img width="728" alt="Screen Shot 2020-09-09 at 12 51 12 PM" src="https://user-images.githubusercontent.com/1464705/92646362-2b634480-f29b-11ea-9d28-5fa16efa3bcc.png">

3. Icon button height does not match the input height:

<img width="703" alt="Screen Shot 2020-09-09 at 12 51 40 PM" src="https://user-images.githubusercontent.com/1464705/92646425-43d35f00-f29b-11ea-8a82-2e6b3af9c81a.png">

4. Adjusting the search block width does not work, seems to be overridden or something to do with flex:

<img width="987" alt="Screen Shot 2020-09-09 at 12 52 27 PM" src="https://user-images.githubusercontent.com/1464705/92646506-682f3b80-f29b-11ea-8ad8-96b3a9dcc24c.png">

**Comment by danieldudzic** [comment]
This issue has been reported over 3 months ago, and it seems to be fixed now:

<img width="1772" alt="fixed" src="https://user-images.githubusercontent.com/905781/105434240-7171e100-5c5b-11eb-93b6-635b87b63446.png">
