### ISSUE TITLE
Dyad 2: Featured product overrides featured content

### ISSUE THREAD

**Issue by GeoJunkie** [Automattic/themes#245]
## Steps to replicate

- Create a site with Dyad 2 theme and WooCommerce
- Add featured content to the theme
- Add a product without a featured image (so far everything is OK):
![screen shot on 2018-08-28 at 13_43_55](https://user-images.githubusercontent.com/7596032/44740460-849f1780-aac8-11e8-9f16-97e86db48ed5.png)
- Add a featured image to the product

## Result
The featured content is replaced with the product's featured image:

<img width="1257" alt="screen shot on 2018-08-28 at 13_46_19" src="https://user-images.githubusercontent.com/7596032/44740581-d21b8480-aac8-11e8-9aff-69e0f61caacf.png">

This appears to always use the featured image from the first listed product:

![dyad glitch](https://user-images.githubusercontent.com/7596032/44741390-e52f5400-aaca-11e8-8d1a-5b93bdf81f97.gif)

## Expected

Featured content shouldn't be affected by the products

* User report: 5949102-hc
* Follow-up ticket: None. 
* User's site: gemstonegoddess.co (User has switched themes, though. I've recreated the error on tacotestwoo1.blog )

**Comment by laurelfulford** [comment]
I can recreate this, but only when I set my shop page to be the static front page, under WooCommerce > Settings, on the Products tab.

I can also recreate it without Featured Content -- the image replaces the fallback featured image used in the header area, too.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
