### ISSUE TITLE
Shoreditch: Sharedaddy placeholder caused featured image loading issue

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/themes#246]
When a page or post with a featured image on the Shoreditch theme loads, the image first contracts and then expands to fill the space for the featured image. It happens on every page load.

Screen Capture of Issue: https://cld.wthms.co/t5bwId

It appears that this happens due to a placeholder for the Sharedaddy widget. There's a loading box that shows up before the actual `iframe` is loaded, and it's slightly larger than the actual `iframe`, so it bumps the page height a little, then bumps it back down when the loading block disappears.

As such, when the "Like this" button is disabled from wp-admin > Jetpack > Settings > Writing and then toggling the Like button switch, the loading problem stops. 

Is there anything that can be done with CSS to hide the loading of the placeholder, or is there anything that can be done so the placeholder loads in a different order and this doesn't happen? Or, is this something for the Jetpack repo?

* User report: #6081908-hc
* Follow-up ticket: #1383174-zd
* User's site: https://idsprofit.com/about/

**Comment by laurelfulford** [comment]
I can recreate this, but only on pages that use the Panel Page template, not on posts and not on pages that use the default template.

Steps I used to recreate:

1. Turn 'Likes' on.
2. Apply the panel page template to a page.
3. Add a featured image to that page.
4. Publish and view; watch as the page loads. 

@sstabrizi Just let me know if I'm missing something to recreate this on posts or pages without the panel template -- thank you! 

I think the issue may be related to both the placeholder and the actual Like button being briefly visible at the same time, but it needs further testing to confirm.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
