### ISSUE TITLE
Illustratr: Social Icon block overshoots column block when right aligned 

### ISSUE THREAD

**Issue by nagpai** [Automattic/themes#2463]
## Steps to replicate

* Create a test site and install Illustratr theme
* Create a page, add a columns block with 50-50 proportion
* In the left column, add a social icons block
* Add a couple of social media handles in the block and right-align the whole block . 
* Add a image to the right column. It should look like this in the editor

![image](https://user-images.githubusercontent.com/4162931/93365269-36077600-f867-11ea-88a4-bd70ef052e05.png)

## Result

When you browse to the front-end view of the page, you do not see the social icons. They are actually hidden behind the image on the right side. Screenshot:
![image](https://user-images.githubusercontent.com/4162931/93365649-af9f6400-f867-11ea-8f87-5099bbe21e23.png)

On screens narrower than 1200px, we see the social icons piled vertically:
![image](https://user-images.githubusercontent.com/4162931/93366164-63a0ef00-f868-11ea-99fe-5823cf3b1633.png)

## Expected

Expect to see the icons right-aligned within the same left column like this:
![image](https://user-images.githubusercontent.com/4162931/93365816-e5444d00-f867-11ea-81d4-20fc5f47c6f4.png)

## Cause and Workaround

The issue seems to be happening due to this CSS:

```
@media screen and (min-width: 1220px) {
.alignright {
    margin-right: -130px;
}}
```

There is also a `display: inline;` property of generic alignright selector that makes the icons go vertical. 

The following specific CSS workaround seems to work for now:

```
/* Correct right align for social links block within column block */

.wp-block-social-links.alignright {
    margin-right:  unset;
    display: flex;
}
```

* User report: #15448584-hc
* Follow-up ticket: None since user was happy center-aligning the block for the moment.

**Comment by scruffian** [comment]
I'm looking at this, but I'm struggling to understand the function of this line:
```
@media screen and (min-width: 1220px) {
.alignright {
    margin-right: -130px;
}}
```

What happens if we remove this line?

**Comment by scruffian** [comment]
The same thing happens with other blocks, for example:

<img width="878" alt="Screenshot 2020-10-23 at 10 57 34" src="https://user-images.githubusercontent.com/275961/96990156-a4062380-151e-11eb-82b8-d6424930b6e8.png">

**Comment by scruffian** [comment]
I think we should just remove these margins, as per: https://github.com/Automattic/themes/pull/2784
