### ISSUE TITLE
Radcliffe 2: Blog Posts block grid view broken

### ISSUE THREAD

**Issue by sandymcfadden** [Automattic/themes#2466]
## Steps to replicate

- Create a page and add the Blog Posts block
- Choose grid view
- Set multiple columns 
- Use posts with longer titles.

## Result

- The titles force each post in the grid to be too wide so they appear one over the other instead of in a grid layout.

## Expected

- The posts to show in a grid instead of stacked on top of each other.

* User report: #3319559-zd

**Comment by hacchism** [comment]
Another report: #23938515-hc

It seems this happens no matter if post titles are long or not.

**Comment by rinazrina** [comment]
Similar report: #3427940-zen

The Blog Posts block is displayed as stacked though it's set in a grid view. Also, the featured images are showing on the editor, but missing on the preview and on the published version.

I suggested using the Latest Posts block for now as a workaround.

**Comment by MaggieCabrera** [comment]
Reported this to the block repo in order to get a more global fix https://github.com/Automattic/newspack-blocks/issues/616

**Comment by scruffian** [comment]
Since this is an issue in the Newspack block, I'm going to close this issue.
