### ISSUE TITLE
Seedlet: Block Patterns show placeholders

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2474]
It looks like the Seedlet Blocks Patterns previews are showing placeholders. cc @iamtakashi who noticed it.

![image](https://user-images.githubusercontent.com/545779/93504935-caadba80-f8df-11ea-8ab9-b76d5e80784b.png)

**Comment by kjellr** [comment]
The "correct" way to include images here would be to bundle the images in the theme, and then use them here by default, but that's not possible until a solution to https://github.com/WordPress/gutenberg/issues/21932 is merged.

In the near term, the only other reasonable solution would be hotlinking to the image elsewhere. This is what we do for block pattern on WP.com, but it does seem a little weird to do so for self-hosted users.

**Comment by kjellr** [comment]
Nevermind, @MaggieCabrera pointed out that since patterns are declared in PHP, it works fine to use `get_template_directory_uri()`. 😄 

Bundling these images and linking to them that way seems like the most reasonable solution for now, and would make a good PR. 👍
