### ISSUE TITLE
Organization: Background image setting missing on AT sites

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#2475]
## Steps to replicate

1) On an AT site, set the theme to Organization
2) Go to the Customizer > Colors & Background

## Result

Select image option is missing: https://d.pr/v/hvoGz8

## Expected

For the select image option to be available the same as it is on a Simple site: https://d.pr/i/1CelVJ

* User report: #3326455-zd

**Comment by jeffikus** [comment]
Closing this here, please report this in the premium theme trac.
