### ISSUE TITLE
Scrawl:  menu icon not show on free sites (sites without a plan upgrade)

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#2476]
The hamburger menu icon does not show on "free" sites on WordPress.com

## Steps to replicate

- Activate Scrawl on test site
- Ensure the site has no active WordPress.com "plan" upgrades

## Result
- When logged in as the site owner, the "hamburger" menu appears as normal, both when visiting the site front end and within the site customizer
- If the site is viewed in an incognito window, or by a user that is not a site admin or not logged in to WordPress.com, no menu icon is present.

Screenshot
![Markup 2020-09-17 at 16 16 20](https://user-images.githubusercontent.com/1967448/93547633-348a8c00-f901-11ea-8a9d-9d91396534e5.png)

This behavior is also visible on the [theme demo site on](https://scrawldemo.wordpress.com/) WordPress.com. Screenshot:  
![Markup 2020-09-17 at 16 18 16](https://user-images.githubusercontent.com/1967448/93547729-6dc2fc00-f901-11ea-8d91-83811f5a6945.png)

In my testing, the menu appears normally on sites that use a WordPress.com Upgrade Plan of some kind, seems to only affect free sites.

## Expected

Menu icon to be visible regardless of upgrade status.

* User report: https://wordpress.com/forums/topic/menu-disappeared/

**Comment by MaggieCabrera** [comment]
Hi, this is because of the marketing banner on top. See this post about it: https://themedevp2.wordpress.com/2020/09/17/the-wp-com-marketing-banner-update-and-its-theme-implications/

I think you should ask someone from ajax to disable the marketing bar for this theme until there is a fix for this issue.

**Comment by jordesign** [comment]
I've left a comment here to ask for this theme to be excluded from the Marketing Bar.
https://wp.me/p7DVsv-9gv#comment-31173

**Comment by cpapazoglou** [comment]
Deployed r213865-wpcom which excludes `scrawl` from showing the marketing bar
