### ISSUE TITLE
Morden: Pullquote block background color not affecting frontend

### ISSUE THREAD

**Issue by nielslange** [Automattic/themes#2485]
## Steps to replicate

1. Create a new page or post
2. Add the [Pullquote Block](https://wordpress.com/support/wordpress-editor/blocks/pullquote-block/)
3. Set the background color to blue

## Result

The background color of the pullquote is red, as defined in https://github.com/Automattic/themes/blob/18f104e1f33a2b51a81289a44115a845299cd5e0/morden/style-editor.css#L882-L884

## Expected

The background color of the pullquote is blue. It seems that due to CSS Specificity, the color selected by the customer is overwritten by the default color of the pullquote block.

* User report: 24249027-hc
* Follow-up ticket: 3331007-zen

**Comment by MaggieCabrera** [comment]
This is affecting other Varia children (I have tested Coutoire. Looking into this.

**Comment by MaggieCabrera** [comment]
This is affecting more than one block from Varia and its children. I'm looking into making a PR to fix this directly in Gutenberg, like this PR: https://github.com/WordPress/gutenberg/pull/25291

**Comment by rinazrina** [comment]
Another report here #3326590-zen 

Theme: Stow
