### ISSUE TITLE
Professional Business: Broken Media & Text Block

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#2489]
## Steps to replicate

1. Create a new page
2. Add the Media & Text block

## Result

To be able to use the block.

## Expected

You can't add an image or edit the text on the block. You can't select anything on it.

Here's a screencast showing the issue:

![MediaTextBlockIssue](https://user-images.githubusercontent.com/16104522/93822790-1e4d3a80-fc37-11ea-979c-772bcbf65bc1.gif)

* User report: #24301611-hc

**Comment by cathymcbride** [comment]
retired theme. Closing...
