### ISSUE TITLE
Goran: Media queries overriding user defined color palette

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/themes#249]
Users can setup a custom color palette when customizing Goran.  This sets a `background-color` in `custom-colors-css.`

Additionally, Goran's responsive design includes a 1020px media query breakpoint within style.css.
`@media screen and (min-width: 1020px) {`

Within this is a series of selectors that modify various items. In this case, we are focusing on background.
```
.main-navigation ul ul a {
		padding: 10px 8px;
		width: 244px;
		background: #e74f4e;
		border: 0;
	}
```

This breakpoint is overriding the user-defined color palette. In this specific case, the drop-down navigation background.

## Steps to replicate
Latest (9/3/2018) Chrome and Firefox.

The image below is of a browser window over 1020px with user defined color palette set.  The color is set using the Calypso's Cutsomize > Color & Backgrounds > Palettes. This targets, amongst many other selectors, `.large-screen .main-navigation ul ul a` and sets the color I have selected `background-color: #27a8e0`
![image](https://user-images.githubusercontent.com/4887830/45003982-1968b000-afb6-11e8-9fa1-c00d9b97fb2a.png)

## Result

This is the same site but set below the 1020px breakpoint. Amongst some other visual changes, the navigation background color reverts to what is defined within the media query. `background: #e74f4e;`
![image](https://user-images.githubusercontent.com/4887830/45004119-b546eb80-afb7-11e8-9903-8295da81d764.png)

## Expected

The expectation is for the design to maintain the defined color palette throughout resizing. In this case, the navigation background color unexpectedly changes from the user-defined palette color to the default, `background: #e74f4e;` set in the 1020px media query.

* User report:  p1536013239000100-slack-css-help , 6173178-hc 
* Follow-up ticket: pending
* User's sites: https://goodetesting.wordpress.com, https://mercersprocleaners.com/

**Comment by jeffikus** [comment]
Goran has been retired.
