### ISSUE TITLE
Redhill: Excerpts not displayed

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#2493]
## Steps to replicate

- activate Redhill theme 
- in WP-admin > Setting > Reading > select "Summary"
- in your post, enter an excerpt and update 

## Result

Even an excerpt is added to the post and even "Summary" is selected in Settings > Reading > For each article in a feed, show: "Summary", excerpts are not displayed, and still displays the full post. 

Setting: https://d.pr/i/pxleHC
Excerpt: https://d.pr/i/TCa1vK 
Blog page (full post display): https://d.pr/i/cUa8qU 

## Expected

It will display the excerpt. 

* User report: 24213466-hc 
* Follow-up ticket: 3339005-zd

**Comment by kathrynwp** [comment]
Hi! The Feed settings is related **only** to the site's RSS feed, and has no effect on whether an excerpt or full post is displayed on the site itself.
