### ISSUE TITLE
Varia themes: Custom unit support

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#2497]
I thought Varia themes have already the custom unit support like Seedlet #2408 at some point, but that seems no longer true. It'd be great if we can add it back (I hope I wasn't dreaming 🤔)

![Screenshot 2020-09-22 at 23 46 48](https://user-images.githubusercontent.com/908665/93944970-ebd23900-fd2d-11ea-9f1d-8f1f7ba0610e.jpg)

**Comment by kjellr** [comment]
Not sure how that disappeared, but custom units should be [enabled by default](https://github.com/WordPress/twentytwentyone/issues/14#issuecomment-694118522) for all themes via the Gutenberg plugin now.

**Comment by MaggieCabrera** [comment]
> Not sure how that disappeared, but custom units should be [enabled by default](https://github.com/WordPress/twentytwentyone/issues/14#issuecomment-694118522) for all themes via the Gutenberg plugin now.

I just checked this and I had to add `add_theme_support( 'custom-units' );` to the theme for it to work on my local install. It doesn't work on .com either. Who should we inform about this?

**Comment by kjellr** [comment]
@Automattic/cylon do one of you happen to know about that availability of custom units on .com?

**Comment by noahtallen** [comment]
@Automattic/good-mountain might know more?

The only thing I'm personally aware of is that we enabled [custom line height by default](https://github.com/Automattic/wp-calypso/pull/44772) for all themes on WordPress.com simple/atomic. Perhaps we need to add more code to do custom units?

**Comment by sirreal** [comment]
I believe it was enabled by default in Gutenberg 9.1 which is currently in RC.

In my testing, a WordPress.com Simple site running 9.1 (edge) this feature works. It does not work with the 9.0 version currently in production.

I see explicit support for `custom-units` for Seedlet and Sidekick, but not other themes on WordPress.com.

**Comment by kjellr** [comment]
Cool, we'll test again when 9.1 makes it into production on .com. 👍

**Comment by iamtakashi** [comment]
> In my testing, a WordPress.com Simple site running 9.1 (edge) this feature works

I can see the custom unit with 9.1 (edge) too. Thank you!
