### ISSUE TITLE
Shoreditch: Prevent Content Options from affecting Panel Page Template

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#250]
## Steps to replicate

1.    Make a new page with the Panel Page template
2.    Give the page a featured image and content
3.    Also assign some child pages with their own featured images and content.
4.    Publish
5.    Open the Customizer
6.    Go to Content Options
7.    Uncheck the “Display on pages” option under “Featured Images”

## Result

The featured image set as background for the parent page panel disappears, but featured images set as background for the child page panels remain

## Expected

For either all images to remain or disappear, with a preference for remain - while the Content Options setting is strictly speaking doing what it's supposed to do here, it's reasonable to expect that it won't affect the panel page given the unique way this page works. That's also why I'm filing this as an enhancement request rather than a bug.

* User report: Issue reported in the [self-hosted forum for the theme](https://wordpress.org/support/topic/bug-content-options-break-expectation-of-panel-page/).
* User's site: No link provided, but I was able to replicate the issue, and also on the dotcom version of the theme

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
