### ISSUE TITLE
Affinity: Blog feed page does not show featured image as header image

### ISSUE THREAD

**Issue by jessestu** [Automattic/themes#251]
## Steps to replicate

1. Activate Affinity.
2. Set a page to Blog feed in Customize → Homepage Settings.
3. Choose any custom image in Customize → Header Image.
4. Set a different Featured Image for the blog feed page set in Homepage Settings.

## Result

The Featured Image does not display. Only the image in → Header Image shows.

![ezgif com-optimize](https://user-images.githubusercontent.com/32908730/45118963-9e230d80-b11f-11e8-8696-a5397c2b24b4.gif)

## Expected

I expect that the featured image would change the header image like it does on other pages with Affinity and in other themes:

![screen capture on 2018-09-05 at 15-18-35](https://user-images.githubusercontent.com/32908730/45118835-3ff62a80-b11f-11e8-80bf-be0efee48edc.gif)

* User report: 2925766-hc
* Follow-up ticket: 1395336-zen
* User's site: https://jenaleelaroy.com/journal-2/

**Comment by jessestu** [comment]
I communicated a workaround to the user: set the image they want for their blog page in Customize → Header Image, then set Featured Images for all other pages that will overwrite the Header Image.

**Comment by alaczek** [comment]
Since this is the designed behaviour (as explained in #226), I'm marking this as an enhancement.

**Comment by jessestu** [comment]
Excellent! Thank you, @alaczek.

**Comment by susanjanec** [comment]
The same steps to replicate, result and expected that were listed above also applies to this user.

A user reported they added the Featured Image on their Blog/News page that is set as their blog page and instead an image from their Header Image is showing.

This is the image on their Blog page:
![screen shot on 2019-01-24 at 16-40-01](https://user-images.githubusercontent.com/16828966/51710831-52063600-1ff8-11e9-983b-a80073e9f2d9.png)

This is the image they have set as their featured image:
![screen shot on 2019-01-24 at 16-47-14](https://user-images.githubusercontent.com/16828966/51710901-942f7780-1ff8-11e9-8679-eb2e37fc9cdb.png)

- User report: 9819895-hc
- Follow up ticket - 1746543-zen
- User's site: https://jetadvisory.com

**Comment by jeffikus** [comment]
Affinity has been retired.
