### ISSUE TITLE
Typo: Sketch theme showcase page

### ISSUE THREAD

**Issue by inaikem** [Automattic/themes#2513]
Please visit this theme's showcase page here: [https://wordpress.com/theme/sketch](https://wordpress.com/theme/sketch)

Next, scroll to the penultimate sentence in the section "Portfolio Page Template". There's an extra "a" in this sentence before "Custom Menu":

_"If you’d like to add your portfolio archive page to your **a** Custom Menu, create a custom link using the portfolio archive URL."_

 I don't appear to have edit rights on this page, so raising here as a ticket.

**Comment by kathrynwp** [comment]
Hi there - thanks for the cath! This repo is for themes themselves, not for documentation. Please ping for help in Slack and someone can show you where to edit the documentation. Thanks!

**Comment by kathrynwp** [comment]
Actually I just went ahead and made the fix myself. :)

**Comment by inaikem** [comment]
Thanks Kathryn!
