### ISSUE TITLE
Goran: Logo appears above site title instead of on the side

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/themes#252]
Hi - When adding a logo, not matter how small, it'll appear on top of the site title, instead of on its left side, as shown in the showcase page.

## Steps to replicate

- Have Goran activated on site
- Go to the Customizer > Site Identity
- Add a logo, and see how it appears above the site title

## Result

- The logo appears above the site title. Here's a screenshot:

<img width="986" alt="capture d ecran 2018-09-06 a 17 34 12" src="https://user-images.githubusercontent.com/16645645/45168262-1f9b9e00-b1fb-11e8-9949-6dc640767853.png">

## Expected

- I was expecting for the logo to appear on the left-hand side of the site title, as shown in on the theme showcase page. Here's a screenshot:

![goran-site-logo](https://user-images.githubusercontent.com/16645645/45168317-46f26b00-b1fb-11e8-98f1-dbba62543962.png)

* User report: #6216701-hc
* Follow-up ticket: None, the user is changing themes
* User's site: User is changing themes, but you can see the issue here: https://cecilesfreetestsite.wordpress.com/

**Comment by alaczek** [comment]
Based on the font differences between the screenshot and the demo, I think in the docs both the icon and the text are a part of one logo image. I also looked at the history of changes, and can't see anything suggesting that this behaviour has changed somewhere down the road.  

I can see how that image in the docs can be misleading, so I'll remove it.

As for the customer, the issue could be addressed with custom CSS:
```
.site-branding {
display: flex;
align-items: center;
}
.site-logo-link {
margin-right: 10px;
}

**Comment by cecilearkay** [comment]
Oh! That makes sense now. I'll add the CSS to the Theme Quirks site in case other HEs are wondering. Thanks!
