### ISSUE TITLE
Goran: Display bug in the Customizer after adding logo

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/themes#253]
Hi - When adding a logo to a site using Goran, there's a display issue in the preview window of the Customizer. It pushes the header overlay down the page, however, it looks fine on the live site.

## Steps to replicate

- Have Goran activated on the site
- Have a static front page activated on the site
- Go to Customize > Site Identity
- Add a logo and see how the header overlay gets pushed down

Here's a recording: https://cld.wthms.co/1erooP

## Result

In the Customizer, the overlay moves down and a solid color block appears where the logo was added. However, it looks as expected on the live site.

## Expected

I expected the overlay would remain where it was, and the logo would appear on top of the overlay.

* User report: #6216701-hc
* Follow-up ticket: None, the user is changing themes
* User's site: User is changing themes but their site is shadowble.com

**Comment by alaczek** [comment]
I tired replicating, but was not able to. I wonder though if it's a matter of image size and/or the presence of menu. This needs a second pair of eyes.

**Comment by laurelfulford** [comment]
I found there's kind of an odd breakpoint where I can recreate this:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/177561/45589973-e7bfe500-b8e3-11e8-948a-169242299a19.png">

 It happens both in the Customizer and on the front end, but when you're in the Customizer the site is narrower, so if it happens there and then you publish the page, it will seem fine when you look on the front-end.

You also don't need to add a logo, but the taller the header is, the more pronounced it is. So adding a logo can make it look a lot worse. 

You can see the gap in one of the screenshots in another open  Goran issue: #249.

**Comment by jeffikus** [comment]
Goran has been retired.
