### ISSUE TITLE
Baskerville 2: Videos missing on posts page if excerpts are enabled

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#254]
## Steps to replicate
- Enable Baskerville II
- Create a post with a video. We put a video link at the top and some text under it.
- Create another post (if you'd like) with the same thing, and set this one's post type to video.
- Note they both display on the front page
- Head to Customize > Content options and opt to display excerpts on the posts page, instead of displaying the full article.

## Result
We just see a link to the video and some text; it's picking up ONLY the excerpt and it looks bad.

## Expected
I expected to still see the videos, like we do in the demo.

* User report: [#](https://en.forums.wordpress.com/topic/problema-cu-formatul-postarilor/)
* Follow-up ticket: same
* User's site: https://magiepegeea.wordpress.com/2018/09/06/18875/ is a private test post.

![image](https://user-images.githubusercontent.com/3476361/45190268-59b87000-b1fa-11e8-92c6-a14beea1362f.png)

![image](https://user-images.githubusercontent.com/3476361/45190285-6dfc6d00-b1fa-11e8-93f9-8557828869ef.png)

**Comment by alaczek** [comment]
The way excerpts work in core, is they strip all formatting from the content - this means not displaying things like images or videos too. 
Baskerville 2 demo site displays full post, not excerpts - this is why the video is visible on the homepage. I know this excerpt behaviour is frustrating, but is not something we can fix in the theme.

**Comment by alaczek** [comment]
Oh, I just remembered about a workaround, although not sure it will work for this customer.
You could set content options to display full posts, and then in the post content insert the video, and read more tag right after it. This way everything before the more tag will be displayed on the homepage, and you'll keep videos, images, and text formatting.

**Comment by alaczek** [comment]
No problem! Closing.
