### ISSUE TITLE
Responsive: Gallery widget, slideshow not loading, "jQuery.browser is undefined"

### ISSUE THREAD

**Issue by formosattic** [Automattic/themes#2543]
## Steps to replicate

1. Activate Responsive theme (now retired)
2. Add a Gallery widget, with the slideshow type

## Result

Gallery widget doesn't load, shows message that it requires JavaScript.
![image1](https://user-images.githubusercontent.com/15944096/95068906-896b3680-0738-11eb-810a-7dfc5eabcfe8.png)

In the Console, message that `jQuery.browser is undefined`:
![Markup on 2020-10-05 at 12:39:10](https://user-images.githubusercontent.com/15944096/95041028-1ba71680-0708-11eb-8b3c-cff38167b6a3.png)

Notes:

* discussed in https://github.com/Automattic/jetpack/issues/16715
* internal: p1601888887370100-slack-themes, pointed out that `jQuery.browser` has been removed from jQuery v1.9 and onwards, that may be the cause: https://jquery.com/upgrade-guide/1.9/#jquery-browser-removed 

User report: 3363437-zen

**Comment by pbking** [comment]
This has been addressed in this change: https://code.a8c.com/D52184

**Comment by pbking** [comment]
Looks like this was never deployed.  Setting it back to 'Reviewer Approved' until it has been.

**Comment by pbking** [comment]
This has now been deployed.  I have verified that the site on which the issue was raised is working as expected.
