### ISSUE TITLE
Mayland: Buttons Block Predefined Colors Issue

### ISSUE THREAD

**Issue by Sandkorner** [Automattic/themes#2549]
## Steps to replicate

1. Activate Mayland theme
2. Insert a Buttons block into a page/post
3. Choose predefined colors for fore- and background

## Result

Editor:
![Button Block Color Settings](https://user-images.githubusercontent.com/71094068/95120390-21c3e400-0756-11eb-9f0a-ecb1de364354.png)

Front-end:
![Front-end](https://user-images.githubusercontent.com/71094068/95120401-27212e80-0756-11eb-828b-8e6d3ead8870.png)

Mayland CSS file:
![Mayland CSS](https://user-images.githubusercontent.com/71094068/95119745-20de8280-0755-11eb-8a1a-edd165dbbe50.png)

## Expected

I expected the button to show the colors from the picked predefined color settings on the front-end, but it seems the CSS selectors are overwritten or not specific enough in the Mayland CSS file.
The front-end screenshot shows the CSS file line numbers, which are overwriting the chosen color.

**Comment by kriskorn** [comment]
#2548 Duplicate. Closed.
