### ISSUE TITLE
Rebalance: Images with caption on pages cannot be centered

### ISSUE THREAD

**Issue by kylemcph** [Automattic/themes#255]
## Steps to replicate
- Add an image to a page within the visual editor of Calypso. 
- Add caption to image.
- Center image

## Result
The image stays aligned to the left, as you can see here `http://cld.wthms.co/OuPcYZ` and `http://cld.wthms.co/lJLxyd`

## Expected
- The expected result is that the image would be centered.

- The current workaround was to add `<div class="post"></div>` around the image, to trick it to believe it was within a post.

- I was also able to replicate this on a test site of mine.

* User report: #5481717-hc
* Follow-up ticket: #1399727-zd
* User's site: `https://felixheininger.com/biography/`

**Comment by laurelfulford** [comment]
Confirmed this issue; the styles to continue centring an image with a caption are too specific to be applied to pages (they include the selector `.post`).

**Comment by alaczek** [comment]
Removed the `.post` from the selector.
