### ISSUE TITLE
Seedlet: pullquote text size when left/right aligned is not matching the editor

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2552]
## Steps to replicate

* Create a pullquote aligned to the left or right

## Result
The font size does not look the same as the editor's. They also don't seem to be aligned vertically.

Editor: 

<img width="846" alt="Screenshot 2020-10-06 at 09 28 10" src="https://user-images.githubusercontent.com/3593343/95171791-b8c08880-07b6-11eb-9092-94b010ddbe00.png">

Frontend:

<img width="881" alt="Screenshot 2020-10-06 at 09 28 42" src="https://user-images.githubusercontent.com/3593343/95171799-bb22e280-07b6-11eb-92e5-2e126f5b318c.png">

## Expected

I expected the frontend to look like the editor does.

This is also affecting TT1.

**Comment by danieldudzic** [comment]
This seems to be working fine now.

However, there is a different issue, this time with the default alignment:

**Editor:**
<img width="1510" alt="editor" src="https://user-images.githubusercontent.com/905781/104951093-30ab6b00-59c2-11eb-9591-cd11b25d4681.png">

**Front end:**
<img width="1509" alt="front" src="https://user-images.githubusercontent.com/905781/104951213-68b2ae00-59c2-11eb-9077-7e255c8cf2a3.png">
