### ISSUE TITLE
Seedlet: Full width video is aligned to the left instead

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2553]
## Steps to replicate

Embed a video using the Wordpress embed blocks. Align it to full width. Go to the frontend.

## Result

Editor:

<img width="1428" alt="Screenshot 2020-10-06 at 09 47 44" src="https://user-images.githubusercontent.com/3593343/95173587-28d00e00-07b9-11eb-9053-ddf9382876c7.png">

Frontend:

<img width="1623" alt="Screenshot 2020-10-06 at 09 47 22" src="https://user-images.githubusercontent.com/3593343/95173613-31284900-07b9-11eb-8bad-d7ed3772ef25.png">

## Expected

I expected the frontend to look like the editor and for the video to be full width.

**Comment by MaggieCabrera** [comment]
Also affecting TT1

**Comment by danieldudzic** [comment]
Duplicate Issue: https://github.com/Automattic/themes/issues/2830

**Comment by danieldudzic** [comment]
> Also affecting TT1

@MaggieCabrera It seems to be working fine for me in TT1. Can you please confirm whether you can still replicate this issue?

**Comment by MaggieCabrera** [comment]
can confirm it works fine now on TT1, thanks @danieldudzic
