### ISSUE TITLE
Varia: New gutenberg options for search bar are broken on frontend

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2560]
## Steps to replicate

* Install Gutenberg 9.1
* Insert a Search Bar block
* Choose "toggle search label"
* Change button position to inside 
* Click "Use button with icon"

## Result

Editor:

<img width="850" alt="Screenshot 2020-10-06 at 19 56 41" src="https://user-images.githubusercontent.com/3593343/95246779-43d06b80-0815-11eb-893e-6a0d2def9ae7.png">

Frontend:

<img width="942" alt="Screenshot 2020-10-06 at 19 53 32" src="https://user-images.githubusercontent.com/3593343/95246789-48951f80-0815-11eb-87c3-a8ac38bfccca.png">

## Expected

I expected the frontend to look like the editor

**Comment by MaggieCabrera** [comment]
This is a gutenberg issue that I reported here: https://github.com/WordPress/gutenberg/issues/25902

**Comment by scruffian** [comment]
This is now fixed for Seedlet and Spearhead.

**Comment by scruffian** [comment]
Possibly connected to #1936
