### ISSUE TITLE
Independent Publisher 2 : Long links add white space on small screens

### ISSUE THREAD

**Issue by suyogyashukla** [Automattic/themes#257]
## Steps to replicate

- Activate Ryu theme on your test site.
- Add a very long link like :
- > https://www.dailyfx.com/forex/analyst_picks/todays_picks/daniel_dubrovsky/2018/09/07/Dovish-RBNZ-Bullish-Reversal-Formation-Paves-Way-for-AUDNZD-Long.html
- Try viewing the site on mobile and scrolling it to the left.

## Result

- There is extra white space added on the right side on mobile devices.

## Expected

- No extra white space on mobile devices.

* User report: #1395807-zd
* User's site: sueyangfxplus.wordpress.com

I tested by temporarily changing themes on user's site to Independent Publisher 2. Same issue as #256

**Comment by laurelfulford** [comment]
Noting that the above user doesn't need to be followed up with when this is fixed; their site is using Ryu, they just need to be followed up with for #256.

**Comment by laurelfulford** [comment]
I can't actually recreate this one now, though I think I could before. But it looks like Independent Publisher 2 has the correct styles in place -- `word-wrap: break-word` -- to prevent issues with too-long strings.

I'm going to close this for now, but if the issue crops again we can always reopen.
