### ISSUE TITLE
Spearhead: Post meta should be adjusted to match comps

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2588]
Current post meta: 

<img width="886" alt="Screen Shot 2020-10-13 at 9 45 36 AM" src="https://user-images.githubusercontent.com/1202812/95869047-f3876b00-0d38-11eb-8ddc-f726c5a87758.png">

Recommended: 

<img width="789" alt="Screen Shot 2020-10-13 at 9 46 06 AM" src="https://user-images.githubusercontent.com/1202812/95869036-eff3e400-0d38-11eb-97b1-7ac8dab39653.png">

On single post pages, we can display the categories/tags/comments if we'd like. But they should be hidden on archive pages, to more closely match the design. Might also consider changing the date format to match the original theme if it's not too much hassle ("Sept 14 2020" Instead of "September 14, 2020")

**Comment by kjellr** [comment]
In addition, the spacing above the post meta should be reduced. In my testing it looks decent if all the margin and padding is essentially removed completely: 

Before|After
---|---
<img width="946" alt="Screen Shot 2020-10-13 at 9 58 39 AM" src="https://user-images.githubusercontent.com/1202812/95870880-026f1d00-0d3b-11eb-8d20-c56111c0f9f4.png">|<img width="942" alt="Screen Shot 2020-10-13 at 9 59 56 AM" src="https://user-images.githubusercontent.com/1202812/95871039-33e7e880-0d3b-11eb-9733-0d7d462daee8.png">

**Comment by MaggieCabrera** [comment]
Actually also working on this for https://github.com/Automattic/themes/issues/2576 

Should I add the Edit button on the search results or hide it there?

**Comment by kjellr** [comment]
I think it's fine to leave the edit button there.
