### ISSUE TITLE
Spearhead: Widgets need some visual refinement

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2590]
- [x] The search box and button are gigantic: 

<img width="866" alt="Screen Shot 2020-10-13 at 9 49 19 AM" src="https://user-images.githubusercontent.com/1202812/95869671-a1931500-0d39-11eb-819f-ffc465db143c.png">

------

- [x] List-based widgets shouldn't inherit the default `ul` left padding. If it's removed, they look much nicer: 

Before|After
---|---
<img width="674" alt="Screen Shot 2020-10-13 at 9 52 06 AM" src="https://user-images.githubusercontent.com/1202812/95869790-c38c9780-0d39-11eb-9999-804510dedfd5.png">|<img width="545" alt="Screen Shot 2020-10-13 at 9 50 11 AM" src="https://user-images.githubusercontent.com/1202812/95869793-c4bdc480-0d39-11eb-8d9f-e01647c14b10.png">

**Comment by MaggieCabrera** [comment]
The first item I'm working on it myself on https://github.com/Automattic/themes/issues/2576

**Comment by scruffian** [comment]
The second item is done here: https://github.com/Automattic/themes/pull/2607

**Comment by kjellr** [comment]
Awesome, this one's all set then. Thank you!
