### ISSUE TITLE
Spearhead: Spacing adjustments

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2593]
There are a handful of areas of Spearhead where the spacing doesn't match the comps: 

- [ ] Horizontal spacing between menu items: Should be 16px, is currently 12px. 

<img width="304" alt="Screen Shot 2020-10-13 at 9 29 08 AM" src="https://user-images.githubusercontent.com/1202812/95867134-d2257f80-0d36-11eb-85ed-6ec72c849d07.png">

------

- [ ] Top padding above the header should be 35px, is currently 60. 

<img width="1267" alt="Screen Shot 2020-10-13 at 9 37 42 AM" src="https://user-images.githubusercontent.com/1202812/95867997-c4bcc500-0d37-11eb-8a7d-9aff2ef74dfe.png">

------

- [ ] Site title bottom margin is 17.5, should be 4px. 

<img width="319" alt="Screen Shot 2020-10-13 at 9 39 48 AM" src="https://user-images.githubusercontent.com/1202812/95868315-15342280-0d38-11eb-9bb6-8c174e7f5b65.png">

------

- [ ] Spacing above post titles on single post pages is far too much.

Current|Spearhead Site
---|---
<img width="1266" alt="Screen Shot 2020-10-13 at 9 36 31 AM" src="https://user-images.githubusercontent.com/1202812/95868504-49a7de80-0d38-11eb-8c1f-962b2af3c334.png">|<img width="1266" alt="Screen Shot 2020-10-13 at 9 36 19 AM" src="https://user-images.githubusercontent.com/1202812/95868514-4d3b6580-0d38-11eb-95a2-7541fa3c8349.png">

------

- [x] "Continue Reading" link should be left aligned.

<img width="846" alt="Screen Shot 2020-10-13 at 10 07 33 AM" src="https://user-images.githubusercontent.com/1202812/95871728-fafc4380-0d3b-11eb-814f-07a1cdc5f80b.png">

**Comment by jffng** [comment]
>  "Continue Reading" link should be left aligned.

This should be addressed by #2575
