### ISSUE TITLE
Maywood: Icons in the bloc toolbar are not visible when using color scheme with dark background

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2599]
## Steps to replicate
1. Activate Maywood.
2. Open Customizer > Colors and Background, and select the color palette with a dark background
![image](https://user-images.githubusercontent.com/4550351/95927606-f6eb2700-0e0a-11eb-99d8-0b02d8d27dd1.png)
3. Go back to the dashboard and start editing a page (or create a new one).
4. Add any block. Note that the icons in the block toolbar are not visible. The icons in the sub-menu are visible though.

I tried a couple of other Varia child themes, as well as Seedlet, and I could not replicate the issue.

Here's a quick demo:
![l67Yhq1Sdr](https://user-images.githubusercontent.com/4550351/95927877-b809a100-0e0b-11eb-8120-0c4bc8ddb64d.gif)

No user report found through my own testing.

**Comment by scruffian** [comment]
I think this has been fixed. Please reopen if you see it again.
