### ISSUE TITLE
Nucleare: Bullets for list aren't visible in comments

### ISSUE THREAD

**Issue by rachelmcr** [Automattic/themes#26]
This issue was originally reported by @krutidugade in 8015-wpcom:

## Steps to replicate

1. Go to ​https://wordpress.com/ > My Site(s) > Comments
2. Edit a comment
3. Create a list with help of `<ul> <li>` tags
4. Update the comment

## Result

When you create a list in comment, the bullets aren't displayed as theme Nucleare has this CSS

`comment-list li { list-style: none; }`

## Expected

This CSS should be fixed in Nucleare theme so that the bullet points are visible in comments.

* User report: 984044-zen
* User's site: https://andrealazzarotto.com/2012/11/24/guardare-e-scaricare-i-video-di-rai-tv-e-rai-replay-anche-con-linux/comment-page-55/#comment-54337

**Comment by sixhours** [comment]
Since this theme isn't in this repo, I've made the fix via SVN directly in r47950.
