### ISSUE TITLE
Rockfield: Social icons wrong color in the editor

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2604]
## Steps to replicate
1. On a site using Rockfield theme edit a post or a page.
2. Add cover block, and use image or a just solid color overlay.
3. Inside the cover block add the social icons block. Pick Logos Only style for the block.
4. Note that the icons all have uniform color (dark or white depending on background color), but if you go to preview, every icon will be a different color.

![8liNI5zd18](https://user-images.githubusercontent.com/4550351/96075364-9afdcc80-0ef6-11eb-965a-403572a909c7.gif)

## Result
Icons in the editor should be the same color as in the preview.

I was able to replicate the bug in Maywood as well, so this could be happening in other Varia child themes too.

**Comment by scruffian** [comment]
I think this was recently fixed in Varia. Please reopen if you still see issues.
