### ISSUE TITLE
Twenty Eleven: can not use dropdown menus in mobile devices

### ISSUE THREAD

**Issue by htdat** [Automattic/themes#261]
This is for a default WordPress theme. I am not sure where we should report for this as it affects both WordPress.com and self-hosted sites. 

## Steps to replicate

1. Go to https://twentyelevendemo.wordpress.com/ by using a mobile device. 
2. Try to access the sub-menu items under "A Parent page" - not possible. 

## Result

It's always redirecting to https://twentyelevendemo.wordpress.com/a-parent-page/

## Expected

I can expect the sub-menu items like https://twentyelevendemo.wordpress.com/a-parent-page/another-child-page/a-grandchild-page/

* Follow-up ticket: 1420994-zen
* User report: 
* * 1420994-zen 
* * https://wordpress.org/support/topic/issue-with-drop-down-menus-on-mobile-devices-2/
* * https://wordpress.org/support/topic/top-level-of-mobile-menu-doesnt-work/

**Comment by laurelfulford** [comment]
Hey @htdat! If this is affecting self-hosted sites, too, it should be reported in the Core Trac. Once it's fixed there, the update will be ported over to WP.com. There's some more info about this in the FG. 

This existing issue sounds similar -- are you only seeing the above on Android devices?

https://core.trac.wordpress.org/ticket/38982

I'm going to close this copy of the ticket, but just let me know if you have any questions at all about the above!

**Comment by htdat** [comment]
Perfect! Thank a lot. 

> are you only seeing the above on Android devices?

I tested with the device mode in the browser console. 
No issue with iPhone, so I think the trac ticket is correct :)
