### ISSUE TITLE
Spearhead: Contact form

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2613]
Looking at the demo site, I think the contact form page needs some work.

<img width="1432" alt="Screenshot 2020-10-16 at 10 09 20" src="https://user-images.githubusercontent.com/3593343/96233144-75c19a80-0f98-11eb-9498-36decfb395bd.png">

**Comment by MaggieCabrera** [comment]
The form actually looks like this with the changes from the search block branch that's yet unmerged in master:

<img width="412" alt="Screenshot 2020-10-16 at 10 26 35" src="https://user-images.githubusercontent.com/3593343/96234788-309e6800-0f9a-11eb-9d94-f85a387545bc.png">

**Comment by MaggieCabrera** [comment]
Spearhead is basically mimicking what Seedlet does:

<img width="970" alt="Screenshot 2020-10-16 at 15 06 50" src="https://user-images.githubusercontent.com/3593343/96261843-3eb3af00-0fc1-11eb-9fda-65b32a32ad53.png">

 This template is using 2 columns in an align wide container (Spearhead's align wide width is bigger than Seedlet's). The only "bug" that I see here is the fact that the inputs are not using the full width of the column. Here is a screenshot with that fixed:

<img width="934" alt="Screenshot 2020-10-16 at 15 08 06" src="https://user-images.githubusercontent.com/3593343/96262111-a4a03680-0fc1-11eb-83c4-3e1e54deecd2.png">

The rest comes down to design decisions, what do you think about this, @kjellr? Should I just fix the width of the inputs or should we make further changes?

**Comment by MaggieCabrera** [comment]
For reference check https://theamdemo.wordpress.com/contact/

**Comment by kjellr** [comment]
Thanks for the ping! I do think it would make sense to have the form fields extend the full width in both Seedlet and Spearhead. 

![Screen Shot 2020-10-16 at 9 19 44 AM](https://user-images.githubusercontent.com/1202812/96263241-c7febd80-0f90-11eb-89a2-78c937e0f269.png)

**Comment by MaggieCabrera** [comment]
After studying this, it seems like our demo site was missing a class for the form. This might have been fixed by the block maintainers because when creating a new page with the same exact setup, this class that was missing appears and the problem is no longer there. I'm considering this fix as it is not reproducible anymore and I'm updating the demo site.
