### ISSUE TITLE
Multiple themes: Update themes to work with the new marketing bar

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2629]
This issue is here to centralize the work needed on multiple themes to fit the new marketing bar. This is a work in progress, the list of themes affected:

- [x] ‘seedlet’ -> https://github.com/Automattic/themes/pull/2627 **DEPLOYED**
- [x] ‘twentyfourteen’ -> D51501-code **DEPLOYED**
- [x] ‘twentyseventeen’ - D51630-code **DEPLOYED**
- [x] ‘[twentytwenty](p7DVsv-9gv-p2#comment-31049)’ - D51555-code **DEPLOYED**
- [x] ‘boardwalk’ -> D51394-code **DEPLOYED**
- [x] ‘gateway’ - D51568-code **DEPLOYED**
- [x] ‘dyad-2’,  -> #2637 // D51402-code **DEPLOYED**
- [x] ‘cubic’ -> D51466-code **DEPLOYED**
- [x] ‘coherent’ -> D51471-code **DEPLOYED**
- [ ] ‘rockfield’ - I don't see issues with this theme
- [ ] ‘stratford’ - I don't see issues with this theme
- [x] ‘pique’ - #2641 **DEPLOYED**
- [x] ‘[scrawl](https://href.li/?https://github.com/Automattic/themes/issues/2476)’ -> D51502-code **DEPLOYED**

#### How to test:

* Update your sandbox with the contents of the specific PR or diff for the theme you want to test
* Modify the following file on your sandbox:
`https://opengrok.a8c.com/source/xref/trunk/wp-content/blog-plugins/marketing-bar.php`
* If your site is older than 2018-05-16 change this line:
`const SHOW_MARKETING_BAR_FOR_BLOGS_REGISTERED_ON_OR_AFTER = '2018-05-16';`
* If modulo of your user id is not 7, change the `!===` to `==`
`if ( is_user_logged_in() && 7 !== (int) $blog_owner % 10 ) {`

#### Screenshots:

Seedlet, with wp admin bar:

![](https://d.pr/i/yKzTY2+)

Seedlet, without wp admin bar:

![](https://d.pr/i/0o4xTD+)

**Comment by MaggieCabrera** [comment]
Boardwalk:

Diff: D51394-code

Boardwalk with wp admin bar:

![](https://d.pr/i/x1K7PC+)

Boardwalk without wp admin bar:

![](https://d.pr/i/Jq5qX8+)

**Comment by MaggieCabrera** [comment]
Dyad 2:

Diff: D51402-code

**Comment by MaggieCabrera** [comment]
Cubic:

Diff: D51466-code

Cubic with wp admin bar:

![](https://d.pr/i/d8dqWR+)

Cubic without wp admin bar:

![](https://d.pr/i/XX2aBo+)

**Comment by MaggieCabrera** [comment]
Coherent:

Diff: D51471-code

Coherent with wp admin bar:

![](https://d.pr/i/9kfl2n+)

Coherent without wp admin bar:

![](https://d.pr/i/JTvpB1+)

**Comment by MaggieCabrera** [comment]
Twenty Fourteen:

Diff: D51501-code

Twenty Fourteen with wp admin bar:

![](https://d.pr/i/kl6rHf+)

Twenty Fourteen without wp admin bar:

![](https://d.pr/i/RH2ZxE+)

**Comment by scruffian** [comment]
Scrawl: D51502-code
![scrawl2](https://user-images.githubusercontent.com/275961/96615180-e0583a80-12f8-11eb-9499-17286c9f9e0d.gif)
![scrawl](https://user-images.githubusercontent.com/275961/96615197-e4845800-12f8-11eb-8341-b43714ee4254.gif)

**Comment by MaggieCabrera** [comment]
Twenty Twenty:

https://code.a8c.com/D51555

<img width="1663" alt="Screenshot 2020-10-21 at 12 27 29" src="https://user-images.githubusercontent.com/3593343/96708622-c589d280-1399-11eb-906e-00b4c6fc2451.png">
<img width="670" alt="Screenshot 2020-10-21 at 12 27 35" src="https://user-images.githubusercontent.com/3593343/96708628-c7539600-1399-11eb-8135-098754724e28.png">
<img width="708" alt="Screenshot 2020-10-21 at 12 27 41" src="https://user-images.githubusercontent.com/3593343/96708630-c7ec2c80-1399-11eb-8d82-abd14c7e1959.png">

**Comment by scruffian** [comment]
I added a fix for Gateway here: D51568-code

**Comment by MaggieCabrera** [comment]
Fixed 2017: D51630-code

<img width="888" alt="Screenshot 2020-10-22 at 10 23 06" src="https://user-images.githubusercontent.com/3593343/96845434-fed14980-1450-11eb-8a39-f3d7c1a4de81.png">
<img width="824" alt="Screenshot 2020-10-22 at 10 22 50" src="https://user-images.githubusercontent.com/3593343/96845445-02fd6700-1451-11eb-9a43-87868e25a2c1.png">
<img width="1485" alt="Screenshot 2020-10-22 at 10 25 23" src="https://user-images.githubusercontent.com/3593343/96845447-0395fd80-1451-11eb-90bb-eeb2d83710b7.png">
<img width="1515" alt="Screenshot 2020-10-22 at 10 25 30" src="https://user-images.githubusercontent.com/3593343/96845451-04c72a80-1451-11eb-8b33-d647f6398224.png">

**Comment by scruffian** [comment]
These are all fixed, let's close
