### ISSUE TITLE
Ixion: Images with Captions Have Incorrect Margins

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#263]
## Steps to replicate

When adding an image with a caption, the `.wp-caption` class removes any margin between the image and the text, resulting in the text bumping up against the image with the caption.

## Result

There's no margins between the text and the captions:

![Test Site Images with Captions](http://cld.wthms.co/133w22+)

## Expected

When I disable the `margin: 0` in the `.wp-caption` class, the images are spaced correctly:

![Test Site Images with Corrected Margins](http://cld.wthms.co/Ic1wqM+)

* User report: #1418573-zen
* Follow-up ticket: #1418573-zen
* User's site: [https://finding-the-thread.com/](https://finding-the-thread.com/)

**Comment by GeoJunkie** [comment]
Ran into this on site caseywagar.com in 6509435-hc

The user had captioned images that they'd set as centered, but they weren't centering, because of the `margin: 0` in the `.wp-caption` class.

I was able to override that and allow the image to center using this Custom CSS:
```
figure.wp-caption.aligncenter {
margin: auto;
}
```

**Comment by alaczek** [comment]
This is fixed now, so custom CSS can removed.
