### ISSUE TITLE
Ever After: Image blocks don't format captions

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#2636]
## Steps to replicate
- Using this theme, create a post in the classic editor with a captioned image.
- Create a post in the block editor with a captioned image.

## Result
Notice the captions are not consistent:

### Block Editor Caption:
![Screen Shot 2020-10-19 at 4 37 38 PM](https://user-images.githubusercontent.com/3476361/96519142-918f9f80-1229-11eb-8cf8-68543de2c81e.png)

### Classic Editor Caption:
![Screen Shot 2020-10-19 at 4 38 32 PM](https://user-images.githubusercontent.com/3476361/96519240-c7348880-1229-11eb-84e5-236410d169f8.png)

## Expected
I'd expect the image caption styles to be the same regardless of editor.

* User report: https://wordpress.com/forums/topic/caption-font-size-problems-while-using-block-editor/
* Follow-up ticket: same

I advised the user the theme is retired and may not be fixed. Suggested switching to something newer. But I mentioned I would note the bug as well.

**Comment by cathymcbride** [comment]
retired theme. Closing.
