### ISSUE TITLE
Spearhead: Add dark mode note or checkbox to customizer panel

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2642]
Spearhead currently uses a dark mode palette if the user has the default palette selected. This is not reflected in the Customizer unfortunately, and it can be jarring to select the default palette, but then have the site appear using totally different colors when you close the panel: 

![dark-mode](https://user-images.githubusercontent.com/1202812/96724975-64a0d100-137e-11eb-9b1f-34d6318f1578.gif)

Suggestions: 

- At the very least, it would be great to display a message in the Customizer panel when the user has the default palette active. Something like: "This theme's default palette will display a dark mode automatically for users who have dark mode enabled on their devices. The preview here is only showing the light mode. [Learn more]" (with a link to a new support page about the feature). 
- Alternatively, we could display a checkbox to enable/disable dark mode if they have the default palette active.

**Comment by jffng** [comment]
Both of these suggestions are implemented in TT1, so we could roughly use it as an example. TT1 uses a slightly different logic (checking luminance of the background color rather than if it's the default palette) for when to activate dark mode, but Spearhead's can be simpler.

> it would be great to display a message in the Customizer panel when the user has the default palette active

https://github.com/WordPress/twentytwentyone/pull/616

> We could display a checkbox to enable/disable dark mode if they have the default palette active.

https://github.com/WordPress/twentytwentyone/pull/615

**Comment by MaggieCabrera** [comment]
I think this comment is relevant to this issue:

> Customizer > Colors and Backgrounds – When changing “primary color”, you lose dark mode theme and goes white in customizer preview, despite not changing the background color. [Video for reference. ](https://href.li/?https://d.pr/v/JQPHFN/7IGNbSyygo)

**Comment by supernovia** [comment]
👋  Could this feature be added to our .org version of Spearhead? See this thread:
https://wordpress.org/support/topic/disable-light-mode/
