### ISSUE TITLE
Spearhead: Submenu padding feels cramped. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2645]
The current submenu padding in Spearhead feels cramped on the left/right sides. THere's more padding on the top and bottom of the menu than there is on the sides: 

![Screen Shot 2020-10-21 at 9 38 10 AM](https://user-images.githubusercontent.com/1202812/96727796-759f1180-1381-11eb-89c5-a251356739d0.png)

We should even that out by setting the left/right padding for the menu to `calc(2 * var(--primary-nav--padding))` instead of just `var(--primary-nav--padding)`:

![Screen Shot 2020-10-21 at 9 39 37 AM](https://user-images.githubusercontent.com/1202812/96727875-8cddff00-1381-11eb-8a0d-cfb6a798ed88.png)

**Comment by melchoyce** [comment]
It's also weird that the "Page Title" there is wrapping onto two lines.

**Comment by kjellr** [comment]
Yeah, I remember seeing that issue in Seedlet too. There's something about the width calculation that makes that happen sometimes.
