### ISSUE TITLE
Spearhead: Author's "More posts" link should be smaller, include arrow. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2648]
The "View more posts" link in the author bio should be visually a little more like the "Read more" links. 

- Smaller text.
- Arrow after it. 

Current:

![Screen Shot 2020-10-21 at 9 51 10 AM](https://user-images.githubusercontent.com/1202812/96729488-3245a280-1383-11eb-8cba-e9886085254f.png)

Recommended:

![Screen Shot 2020-10-21 at 9 51 49 AM-2](https://user-images.githubusercontent.com/1202812/96729752-805aa600-1383-11eb-836f-4140677b51bb.png)

**Comment by scruffian** [comment]
Will be closed by https://github.com/Automattic/themes/pull/2685

**Comment by scruffian** [comment]
Fixed by #2685
