### ISSUE TITLE
Multiple Themes: Broken logo image on the new post notification email

### ISSUE THREAD

**Issue by fashuvo** [Automattic/themes#2649]
## Steps to replicate

1. Publish a new post on a Free/Personal/Premium plan site.

2. Check out the email post notification.

## Result

We see a blank icon in the new post notification emails. Screenshot:

<img width="1071" alt="Image 2020-10-19 at 12 34 58 PM" src="https://user-images.githubusercontent.com/6534920/96728651-22a37980-13d6-11eb-85e5-5179474c8b7f.png">

I was able to replicate the same issue on multiple Free/Personal/Premium plan sites of mine.

I got the image source links for the broken icons and they show 404 errors. Here are the source links:
https://s2.wp.com/wp-content/themes/pub/varia/img/logo-p2.svg
https://s2.wp.com/wp-content/themes/pub/twentyten/img/logo-p2.svg

## Expected

The new post notification should display the logo instead of the broken logo image on the top-right corner.

* User report: #24700189-hc
* Follow-up ticket: #3400193-zen

**Comment by mlaetitia** [comment]
One more report: 3461113-zd

**Comment by scruffian** [comment]
Moved here: 1327-gh-Automattic/p2
