### ISSUE TITLE
Spearhead Premium content margins issues

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2663]
## Steps to replicate

Premium Block content does not have the correct margin bottoms the rest of the site does.

Same issue as #2257 (for Varia) with PR open #2654

In this case I noticed the heading has the same problem with the margin. This is probably happening in Seedlet too.

## Result

<img width="829" alt="Screenshot 2020-10-22 at 09 37 48" src="https://user-images.githubusercontent.com/3593343/96840324-93847900-144a-11eb-9097-e683ade6db0d.png">

## Expected

Expected to have the same margin bottoms as the regular content

**Comment by pbking** [comment]
This is likely addressed here: https://github.com/Automattic/themes/issues/2281 which addressed the issue at the block, rather than theme, level.

**Comment by pbking** [comment]
Confirmed to be fixed by #2281
