### ISSUE TITLE
Spearhead: Dark mode mobile menu

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2668]
@kjellr Should we have the menu on mobile be dark on dark mode?

<img width="411" alt="Screenshot 2020-10-22 at 12 22 20" src="https://user-images.githubusercontent.com/3593343/96859066-58417480-1461-11eb-9615-28b033227259.png">

**Comment by kjellr** [comment]
Hmm. That's a good question! In "light" mode, it's dark, so I see why it's "Light" here. But it does feel very different from the rest of the theme. So yes, maybe we can use the lighter gray color from the homepage under the sticky post? The links can be white in that case:

![Screen Shot 2020-10-22 at 11 06 02 AM](https://user-images.githubusercontent.com/1202812/96891382-9b4a1a80-1456-11eb-82e8-11637355cd6a.png)
