### ISSUE TITLE
Lovecraft: Missing quote marks on Mobile

### ISSUE THREAD

**Issue by markx2** [Automattic/themes#267]
## Steps to replicate

Go to https://lovecraftdemo.wordpress.com/html-elements/ on Desktop. Scroll down to the Blockquote section

Go to https://lovecraftdemo.wordpress.com/html-elements/ on Mobile. Scroll down to the Blockquote section

## Result

The red quotes are missing from the mobile version

## Expected

That the red quote marks are present on the mobile version

* User report: #6656001-hc
* Follow-up ticket: Needs doing
* User's site: Not required - demo shows the issue.

**Comment by alaczek** [comment]
Hi Mark! I looked at the code, and the red quote mark is deliberately hidden on screens narrower then 600px. This is done to conserve the available space, but admittedly the horizontal margins are quite large on the blockquote, and perhaps could be removed, in favour of bring back the quote mark.

**Comment by alaczek** [comment]
Fixed in r50175-wpcom-themes. The changes should be visible once this is deployed, which should happen sometime on Tuesday.
