### ISSUE TITLE
Spearhead: Design improvements to the social menu

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2676]
We should add some enhancements to the navigation design: 

## On Desktop

- [Ensure that the site title baseline is aligned with the menu](https://cloudup.com/cPTOG38l-vd).
- If active, place the social menu underneath the main menu. 
- If active, place the cart to the right of the main menu. 

Before: 

![Screen Shot 2020-10-22 at 2 11 06 PM](https://user-images.githubusercontent.com/1202812/96914198-add24d00-1472-11eb-9ff9-9e7d609bf76a.png)

After: 

![recommended](https://user-images.githubusercontent.com/1202812/96914714-57194300-1473-11eb-9558-8a13a1f24b56.png)

## On Mobile

- Place the social menu inside of the opened menu. 

Before: 

![Screen Shot 2020-10-22 at 2 15 16 PM](https://user-images.githubusercontent.com/1202812/96915146-e7f01e80-1473-11eb-9607-30e0978fa63b.png)

After: 

Closed|Opened
---|---
![recommended-closed](https://user-images.githubusercontent.com/1202812/96915173-ef172c80-1473-11eb-8f06-f0de6a7f7dec.png)|![recommended-opened](https://user-images.githubusercontent.com/1202812/96915185-f2aab380-1473-11eb-8fe3-251e0f5fa6f7.png)

---

I'm a little torn about how to handle the Woo shopping cart on mobile. @melchoyce/@beafialho do you think one of these options is stronger? Folks like to view their cart at a glance, so I don't think it makes sense to hide it inside the Menu button on mobile. 

Option 1|Option 2
---|---|---
![cart-mobile](https://user-images.githubusercontent.com/1202812/96915337-1e2d9e00-1474-11eb-9a8f-54b407754263.png)|![two](https://user-images.githubusercontent.com/1202812/96915495-4ddca600-1474-11eb-99f6-5664b3a415a9.png)

**Comment by scruffian** [comment]
We should also handle this at the same time: https://github.com/Automattic/themes/issues/2712

**Comment by scruffian** [comment]
This was fixed by #2720
