### ISSUE TITLE
Seedlet:  No way to "hide site title" after logo is added.

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#2680]
## Steps to replicate

In the [documentation for Seedlet](https://wordpress.com/theme/seedlet) I see that we note the following when setting a custom logo

> 5. If your logo includes your site’s name or you prefer the header only to display your logo, you can hide the site title by unchecking the box next to Display Site Title.

However, the option does not appear in the site customizer when viewing the site identity settings:

![Screenshot on 2020-10-25 at 13-16-30](https://user-images.githubusercontent.com/1967448/97121705-69d68680-16c4-11eb-9220-aa51834fcf33.png)

For reference here is how the option would normally appear (Hever theme in this case) [screenshot at this link](https://d.pr/i/QcT65v)

Are we moving to a new option for hiding site titles?

Reported in:  https://wordpress.com/forums/topic/website-title-when-linking-is-no-name

**Comment by arcangelini** [comment]
I am not sure if this issue has been passively resolved, but I have not been able to replicate it.

## On local test site with WPCOM version:
[![Screenshot](https://d.pr/i/pifWfe+)](https://d.pr/i/pifWfe)

## On local test site with WPORG version:
[![Screenshot](https://d.pr/i/vhICyg+)](https://d.pr/i/vhICyg)

## On Simple Site:
[![Screenshot](https://d.pr/i/sFpx57+)](https://d.pr/i/sFpx57)

**Comment by scruffian** [comment]
Closing this as it looks like its been fixed. @jerrysarcastic please reopen if you're still seeing this.
