### ISSUE TITLE
Sela: list bullets are displayed when theme is activated without any menu set to the Social Menu location

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#269]
I was able to reproduce it at my test site following these steps

## Steps to replicate

1. Emptied my test site
2. Activated Sela.

## Result
The bullets of an empty list appeared in the footer. 

## Expected

No bullets should appear.

## More info
I set an existent menu to the Social Menu location and unset it right away without publishing the changes. This seems to have fixed the bullets.

When I tried to reproduce the issue at my test site again to make screenshots for this ticket, I wasn't able to reproduce it anymore.

As a workaround we provided a CSS code for the user to hide the bullets. I removed the code in order to make this screencast:

![sela-bug](https://user-images.githubusercontent.com/3521683/46044636-bae4ac80-c0f1-11e8-898f-0be632a73863.gif)

I inspected the empty list and it seemed that the list isn't empty, it's showing links to the site's pages, it's not the same menu set in the Primary location though.

* User report: #6191860-hc
* Follow-up ticket: no ticket yet.
* User's site: https://drthiagocostaribeiro.wordpress.com/

**Comment by alaczek** [comment]
It looks like the menu in the footer is actually all pages menu - a default fallback for `wp_nav_menu()` function. The whole thing is wrapped in `has_nav_menu ( 'social' )` check, so this should not be happening. In any case, I'm going to set fallback to false and see if that helps.

**Comment by alaczek** [comment]
Fixed in r50190-wpcom-themes
