### ISSUE TITLE
Balasana: Conflicts with the Editor Styles, Page Layouts, and Dark Colour Scheme.

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2690]
It looks like there are some strange interactions with Balasana, Editor Styles, Page Layouts, and the dark colour scheme offered.

Somewhat related older issue for background: https://github.com/Automattic/wp-calypso/issues/42679#issuecomment-716755093

On a test site I've switched to the Balasana theme and chosen the dark colour scheme offered.

![image](https://user-images.githubusercontent.com/545779/97216466-e71cfc80-1793-11eb-9912-0ba85a6b6064.png)

New, empty pages and posts do not display the dark colour scheme selection in the Editor.

![image](https://user-images.githubusercontent.com/545779/97216637-23e8f380-1794-11eb-911e-f42bd26af115.png)

When use the Add New Page screen on WP.com to create a new page however, I do see that dark colour scheme in the Editor Preview here when selecting a page layout.

![image](https://user-images.githubusercontent.com/545779/97216780-52ff6500-1794-11eb-97d1-e86897a60282.png)

![image](https://user-images.githubusercontent.com/545779/97216818-627eae00-1794-11eb-9ff9-bc9fad61a8f9.png)

The page appears to display correctly on the front-end of my site once published.

![image](https://user-images.githubusercontent.com/545779/97216896-7aeec880-1794-11eb-90d1-ef969116da2e.png)

For comparison, here's what one would see using the default colour scheme in Balasana.

![image](https://user-images.githubusercontent.com/545779/97217029-a40f5900-1794-11eb-9b16-eb5205072143.png)

**Comment by jffng** [comment]
Here's what I discovered in my testing using Balasana.

The editor styles are correctly reflecting the color palette selection, as well as the front-end and preview:

<img width="1266" alt="Screen Shot 2021-02-10 at 9 53 21 AM" src="https://user-images.githubusercontent.com/5375500/107526655-12322d00-6b86-11eb-9f20-b7535201b5ac.png">

<img width="1259" alt="Screen Shot 2021-02-10 at 9 59 50 AM" src="https://user-images.githubusercontent.com/5375500/107527451-d0ee4d00-6b86-11eb-9328-7b442ae56115.png">

The add page editor preview is not showing the color palette selection. Tested with multiple themes:

<img width="1269" alt="Screen Shot 2021-02-10 at 9 56 51 AM" src="https://user-images.githubusercontent.com/5375500/107526929-56253200-6b86-11eb-9a28-388cdc821f15.png">
 
The page preview is also not loading the fonts. I believe these issues are covered by https://github.com/Automattic/wp-calypso/issues/49742 and https://github.com/Automattic/wp-calypso/pull/49661, so going to close this. Please re-open if there is something the theme can do to help resolve!
