### ISSUE TITLE
Spearhead: Long titles in the editor get cut off

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2698]
When a title in the editor is more than one line long it gets cut off:
<img width="853" alt="Screenshot 2020-10-27 at 11 46 00" src="https://user-images.githubusercontent.com/275961/97302363-dc746d00-1850-11eb-9695-09bf2374eee2.png">

**Comment by jffng** [comment]
I can only recreate this on wpcom. 

It looks like the height of this textarea is calculated dynamically and added inline: 

Inspector | Editor
------ | ------
<img width="1392" alt="Screen Shot 2020-10-27 at 12 12 25 PM" src="https://user-images.githubusercontent.com/5375500/97330284-6f5fd800-184e-11eb-8473-7b57d6b283d0.png"> | <img width="1860" alt="Screen Shot 2020-10-27 at 12 12 28 PM" src="https://user-images.githubusercontent.com/5375500/97330294-74248c00-184e-11eb-89e3-45d99f25e22b.png">

Clicking on the textarea to edit the site title causes it to re-render at the appropriate height: 

<img width="1860" alt="Screen Shot 2020-10-27 at 12 18 44 PM" src="https://user-images.githubusercontent.com/5375500/97330395-93bbb480-184e-11eb-9fd4-d72f086b27d4.png">

Should this be reported in Calypso then? Feels like some kind of race condition where the font sizes and title aren't loaded after the height is calculated.

**Comment by scruffian** [comment]
Yeah looks like this isn't theme specific. I'll report it elsewhere...
