### ISSUE TITLE
Spearhead: Jetpack Subscription block input field is too large

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#2702]
The Jetpack subscription input field has a much too large padding: 

<img width="1113" alt="Screen Shot 2020-10-27 at 9 34 27 AM" src="https://user-images.githubusercontent.com/5375500/97309079-f786b300-1837-11eb-9817-7d26fdfeffa7.png">

This isn't a blocker for launch, but it will appear on every headstarted site's "Home" page.

**Comment by MaggieCabrera** [comment]
This is related to https://github.com/Automattic/themes/issues/2488

Since the block lets the user add/remove padding to the input I think we should remove the styles that are being added from Seedlet to this block so that it works "as is"
