### ISSUE TITLE
Spearhead: Spacing between sticky post and first post should match

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#2703]
The padding between the bottom of the sticky post and the top of the first post should match: 

<img width="883" alt="Screen Shot 2020-10-27 at 9 35 22 AM" src="https://user-images.githubusercontent.com/5375500/97310080-35380b80-1839-11eb-8cf8-6d90a2b946bd.png">

**Comment by scruffian** [comment]
I think this is deliberate, see https://github.com/Automattic/themes/pull/2696

**Comment by scruffian** [comment]
cc @kjellr

**Comment by kjellr** [comment]
Hmm. It _should_ be the same. I can't reproduce... this is what I see on my local site: 

![Screen Shot 2020-10-27 at 2 55 53 PM](https://user-images.githubusercontent.com/1202812/97348533-a640e880-1864-11eb-82f5-606d637fb600.png)

... and on the theme demo: 

![Screen Shot 2020-10-27 at 2 56 28 PM](https://user-images.githubusercontent.com/1202812/97348543-ab059c80-1864-11eb-9816-bd0f1e8a6ff2.png)

**Comment by MaggieCabrera** [comment]
This is happening on Chrome and FF but not on Safari, I'm picking this up
