### ISSUE TITLE
Spearhead: Menu button missing when the demo site banner shows

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2709]
The "Start using this theme on your site" banner hides the menu button:
<img width="762" alt="Screenshot 2020-10-27 at 16 20 09" src="https://user-images.githubusercontent.com/275961/97330630-5ec05980-1870-11eb-991c-be48ab3f3de4.png">

I'm not sure if we do anything special for other themes to avoid this? If we don't then I suggest we don't make an exception for Spearhead.

**Comment by jacklenox** [comment]
I think this is actually a problem with the colour of the menu in the dark colour scheme. In the light, things look as expected:
![Screenshot from 2020-10-28 15-50-30](https://user-images.githubusercontent.com/751476/97461211-71e92d00-1935-11eb-8e8d-e509de3c74a5.png)

**Comment by jacklenox** [comment]
I'm looking into why this is happening in the dark now.

**Comment by jacklenox** [comment]
Fixed yesterday. Now looking good:
![Screenshot_2020-10-28 Spearhead(1)](https://user-images.githubusercontent.com/751476/97462767-fdaf8900-1936-11eb-9214-b151223cede9.png)
