### ISSUE TITLE
Independent Publisher 2: Contrast on submenu items when on submenu item page

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#271]
With IP2 on test site, add submenu item and then click on that page to visit it and go back to menu and hover over top level item that the current page is on and you will see that the contrast between the background and text is not what it should be.

Screenshot
https://cldup.com/XrmkViHgDJ.png

Can we adjust the contrast on this, please?

hattip to @crunnells for noticing this on another issue I asked about in Themes Slack channel.

* User report: NA
* Follow-up ticket: NA
* User's site: [https://thebeadenmillerfamilyhistory.wordpress.com/](url)

**Comment by allancole** [comment]
Fixed this issue here: https://github.com/Automattic/themes/commit/89a679f4f6cad8a892eab346d6dcf2acdb6f2443
