### ISSUE TITLE
Spearhead: Menu button hidden.

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2710]
The "Start using this theme on your site" banner hides the menu button:
<img width="762" alt="Screenshot 2020-10-27 at 16 20 09" src="https://user-images.githubusercontent.com/275961/97330630-5ec05980-1870-11eb-991c-be48ab3f3de4.png">

I'm not sure if we do anything special for other themes to avoid this? If we don't then I suggest we don't make an exception for Spearhead.

**Comment by MaggieCabrera** [comment]
Seedlet has the same issue:

<img width="521" alt="Screenshot 2020-10-27 at 18 05 09" src="https://user-images.githubusercontent.com/3593343/97336160-fe84e400-187e-11eb-95f3-88e711e05f16.png">

TT breaks when the menu opens:

<img width="544" alt="Screenshot 2020-10-27 at 18 06 08" src="https://user-images.githubusercontent.com/3593343/97336296-2411ed80-187f-11eb-96c9-d3a91635b4f1.png">

Varia doesn't have an issue with it

**Comment by MaggieCabrera** [comment]
So about this bar:

* It doesn't appear on some blacklisted demos that cause problems with the combination of the bar and the theme
* It doesn't appear on mobile due to this check:

`if ( ! jetpack_is_mobile() && ! wpcom_is_vip() && $this->demo_site_supports_activation_bar( $blog_id ) ) {`

**Comment by MaggieCabrera** [comment]
Jeff added some css on the demo site to fix it the menu when the bar appears and I tweaked it so it doesn't apply if the 'demo.site' class is present. This is fixed.
