### ISSUE TITLE
Spearhead: Site logo in customizer

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2712]
We don't have any CSS to handle a site logo in Spearhead, so it looks like this:
<img width="676" alt="Screenshot 2020-10-27 at 17 46 58" src="https://user-images.githubusercontent.com/275961/97341301-cbd9ec00-187c-11eb-848b-28b76be6833b.png">

We should probably just align this left...

cc @kjellr

**Comment by scruffian** [comment]
When this issue is complete we need to add a screenshot to the theme showcase page.

**Comment by kjellr** [comment]
Yeah, just align the logo left and I think that's fine for now. 👍

**Comment by kjellr** [comment]
On second thought... it looks pretty bad when the logo is there (at least... when it's paired with the site title and tagline). If possible, I'd prefer we borrowed an approach from Twenty Twenty-One. In that theme, the logo moves up to the top if it's displayed along with a title and tagline. 

Is this something we can pursue for Spearhead? 

## Screenshots:

Site Title/Tagline: 

![Light Mode-1](https://user-images.githubusercontent.com/1202812/97349532-f7051100-1865-11eb-93b7-099e7f85e522.png)

![Frame 2](https://user-images.githubusercontent.com/1202812/97350021-962a0880-1866-11eb-91e2-511f9de14a38.png)

Site Logo Only: 

![Light Mode-2](https://user-images.githubusercontent.com/1202812/97349560-fec4b580-1865-11eb-842e-58edb5a7d867.png)

![Frame 3](https://user-images.githubusercontent.com/1202812/97350024-9924f900-1866-11eb-8191-d11f2550e167.png)

Site Title/Tagline _and_ Logo: 

![Light Mode-3](https://user-images.githubusercontent.com/1202812/97349579-06845a00-1866-11eb-91db-e56f71f449d7.png)

![Frame 4](https://user-images.githubusercontent.com/1202812/97350033-9b875300-1866-11eb-843e-8dd23723fccb.png)
