### ISSUE TITLE
Spearhead: In archive pages, body post text should be --global--color-secondary

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2724]
In archive pages (and the blog posts block), post text excerpts should be `--global--color-secondary`, to match spearhead.co. 

The body text for the sticky post should remain darker (the way it is now). 

Current|Recommended
---|---
![Screen Shot 2020-10-28 at 12 03 04 PM](https://user-images.githubusercontent.com/1202812/97463178-dac0ad00-1915-11eb-9936-0ddc4852139c.png)|![Screen Shot 2020-10-28 at 12 04 23 PM](https://user-images.githubusercontent.com/1202812/97463206-deecca80-1915-11eb-8df8-147497ddfa12.png)

**Comment by MaggieCabrera** [comment]
But sticky pages only happen on the home page, right?

**Comment by kjellr** [comment]
Right — the sticky should be the way it is now, but I'm talking about the body text for all the other excerpts here.

**Comment by kjellr** [comment]
One caveat to this: The text should only be lighter if the user is showing excerpts on the homepage/archive pages. If they're showing the full post content, we should use the same color we're using right now.
