### ISSUE TITLE
Luxury: Grid style for Block Posts Block is broken

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/themes#2728]
## Steps to replicate

- Create a page, add a Blog Posts block
- Set the block to show Grid layout, and with three columns
- Click Preview

## Result

It shows a two-column layout

<img width="918" alt="Screen Shot 2020-10-28 at 1 23 21 PM" src="https://user-images.githubusercontent.com/31009008/97472952-c930d280-1920-11eb-8cd6-7a68a2f15537.png">

## Expected

Expected to see the layout as shown in the editor - three columns.

<img width="1191" alt="Screen Shot 2020-10-28 at 1 22 56 PM" src="https://user-images.githubusercontent.com/31009008/97472970-ccc45980-1920-11eb-940f-df66d0f8950d.png">

* User report: 3445721-zd-woothemes

**Comment by scruffian** [comment]
Moved to Trac
