### ISSUE TITLE
Rebalance: The portfolio template is not displaying all the portfolio items

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#273]
## Steps to replicate

1. Add portfolio items to your site
2. Set the "Portfolio Page" template to a page
3. Compare the portfolio page template with the portfolio archive page:
For example:

- Portfolio page template: https://rebalancedemo.wordpress.com/portfolio-template/
- Portfolio archive page: https://rebalancedemo.wordpress.com/portfolio/

## Result

You will notice that the archive page has an "Older projects" button but the portfolio template page doesn't.

## Expected

To see the same number of portfolio items and the "Older projects" button.

* User report: 1436408-zen
* User's site: 
Portfolio template page:

https://mueblesantiguosislasbaleares.com/acerca-de/

Portfolio archive page:

https://mueblesantiguosislasbaleares.com/portfolio/

**Comment by laurelfulford** [comment]
I can recreate this on my test site.

**Comment by AtrumGeost** [comment]
You can directly check that on the demo site:

https://rebalancedemo.wordpress.com/portfolio/

You'll notice that the Portfolio Archive has an "Older projects" button. While the Portfolio Template doesn't:

https://rebalancedemo.wordpress.com/portfolio-template/

**Comment by laurelfulford** [comment]
This should now be committed to WordPress.com in r53323-wpcom-themes.

It looks like the original ZD ticket is closed -- @AtrumGeost, can you please follow up with the original reporter? Thanks!
