### ISSUE TITLE
Seedlet: Mobile menu not clickable when WooCommerce activated

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#2739]
When you have WooCommerce activated on a site using Seedlet there is a mobile menu toggle and a mobile WooCommerce cart toggle. The regular mobile menu toggle is not clickable on all devices.

## Steps to replicate

* Activate WooCommerce on a site using Seedlet
* View the site on mobile
* Try to open the regular menu
* Open the cart 

## Results

* The regular menu can't be clicked/opened.

![https://d.pr/i/RE5OYQ](https://d.pr/i/RE5OYQ+)

* The cart opens but there is a toggle overlap issue.

![https://d.pr/i/uLKtL3](https://d.pr/i/uLKtL3+)

## Expected

Both menus should be opened with no overlap issues.

I used the following to resolve but I think there's probably a more complete solution for whatever the actual issue is.

_Is the close button supposed to be on the right side for both menus, or should it be on the left for the cart toggle?_

```
body:not(.primary-navigation-open) #primary-open-menu  {
	position: relative;
	z-index: 1;
}

body.primary-navigation-open #woo-open-menu {
    display: none;
}
```

![https://d.pr/i/cNc8cU](https://d.pr/i/cNc8cU+)

* User report: 25257093-hc
* Follow-up ticket: 3448417-zd-woothemes

**Comment by samiff** [comment]
Another in 3487292-zd-woothemes

Gave workaround CSS code for now, but will want to follow-up once issue is resolved.

**Comment by vinnykaur** [comment]
Another one in 3597535-zd

Provided the workaround.
