### ISSUE TITLE
Lovecraft: Different title font on Follow Blog Widget

### ISSUE THREAD

**Issue by vparkhere** [Automattic/themes#274]
## Steps to replicate

1) Activate theme.
2) Add Follow Blog widget to sidebar and another one like Categories widget to see comparison.
3) Notice difference in title fonts.

<img width="443" alt="screen shot 2018-10-02 at 4 16 03 pm" src="https://user-images.githubusercontent.com/11635760/46374409-ac047980-c65e-11e8-8200-afd194d2cc5d.png">

## Result
This Follow Blog widget has CSS for `label` that changes the font family, size, weight, rather than using the CSS for `widget-title`.

## Expected

Expected title for Follow Blog widget to be in the same font as all other widgets on the site.

* User report: #6906979-hc
* Follow-up ticket: #1460115-zen
* User's site: https://priscillazimmermann.com/

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
