### ISSUE TITLE
Seedlet: Align WooCommerce widget cart menu item

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#2740]
The WooCommerce menu widget cart menu item gets added below the main menu on desktop, this should be inline.

## Steps to replicate

* Activate WooCommerce on a site using Seedlet
* View menu on desktop

## Result

It's below the main menu.

![https://d.pr/i/rRbvNz](https://d.pr/i/rRbvNz+)

I assume this is not intended, the cart itself is right aligned so it doesn't look correct:

![https://d.pr/i/Hk2DLZ](https://d.pr/i/Hk2DLZ+)

## Expected

Should be inline with the other menu items, like on Varia themes:

![https://d.pr/i/tSJOXm](https://d.pr/i/tSJOXm+)

I realized this while debugging an issue with the cart on hover:

https://github.com/Automattic/themes/issues/2738

**Comment by scruffian** [comment]
Should be fixed by https://github.com/Automattic/themes/pull/2746
