### ISSUE TITLE
Coutoire: logo larger than recommended size causes large gap in the homepage.

### ISSUE THREAD

**Issue by sourourn** [Automattic/themes#2741]
This may be related to this issue: https://github.com/Automattic/themes/issues/1838

## Steps to replicate

1) In the customizer, insert a logo that is larger than the recommended 100 x 96px
I used this image: 
![cropped-banner-leah-cioth-e1603746183311-7](https://user-images.githubusercontent.com/39188945/97632227-9c57ea80-1a08-11eb-9da0-cc8499a36eca.png)

## Result

There is a large white gap on the homepage
<img width="1402" alt="Screen Shot on 2020-10-29 at 17-04-19" src="https://user-images.githubusercontent.com/39188945/97632461-e8a32a80-1a08-11eb-9302-298773282ba3.png">

The gap disappears when the browser window gets resized: 

<img width="1370" alt="Screen Shot on 2020-10-29 at 17-06-26" src="https://user-images.githubusercontent.com/39188945/97632614-24d68b00-1a09-11eb-9764-8dc2cb010991.png">

## Expected

Content is displayed below the logo with no gap.

* User report: [#1108317-hc]
* Follow-up ticket: [#3449308-zd]

**Comment by danieldudzic** [comment]
Hi @sourourn,

I'm struggling to reproduce the problem:

![can_t_reproduce](https://user-images.githubusercontent.com/905781/107961702-8e71a980-6fa6-11eb-88bf-b75e01519a46.png)

Would you mind checking, if it persists? If it does, feel free to re-open this issue.

**Comment by sourourn** [comment]
Yes it appears to be fixed on my end as well. 👍
