### ISSUE TITLE
Spearhead: Inform users about the Parent theme

### ISSUE THREAD

**Issue by navjotjsingh** [Automattic/themes#2742]
The https://wordpress.com/theme/spearhead doesn't have any mention of the fact that Spearhead theme requires Seedlet theme installed for it to work. An average user will keep wondering why installing just the Spearhead theme doesn't work because there is no index.php in its directory.

This needs to be mentioned on the theme page.

**Comment by jffng** [comment]
Thanks @navjotjsingh — this has been addressed in the "Downloading the Theme" section.
