### ISSUE TITLE
Varia themes: Font weight and Global Styles

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2744]
## Steps to replicate

When using Global Styles with Stow (for example), when you select a custom font the bold tags no longer work. This is due to a combination of factors.

1. `strong` tags are styled using a `bolder` declaration rather than just `bold`
2. The default font-weight is `300`, and for these custom fonts there is no discernible difference between `300` and `400`

## Solution

There are two possible solutions to this:
1. Change the declaration for `strong` tags to be `bold` rather than just `bolder`
2. Change the default font weight in Varia themes to `400`.

Both of these changes will have small visual implications to all 18 Varia child themes.

* User report: p1603996693264000-slack-C029FM1EH

**Comment by kjellr** [comment]
> Change the declaration for strong tags to be `bold` rather than just `bolder`

This is the way to go. If a theme already uses a bold weight somewhere, we may need to add a more specific weight to override that when bold is active. But we can handle that on a case by case basis.

**Comment by scruffian** [comment]
This was fixed by #1814
