### ISSUE TITLE
Publication: Some resolutions hide Simple Payment buttons in widget sidebar

### ISSUE THREAD

**Issue by samiff** [Automattic/themes#275]
## Steps to replicate

* Activate Publication theme.
* Add Simple Payment widget to sidebar widget area.

## Result

* On desktop resolutions, the payment button options don't display:

![screen shot 2018-10-03 at 11 15 57 am](https://user-images.githubusercontent.com/15803018/46420727-9e9ecc00-c6fe-11e8-8751-66f4010cccb3.png)

* On mobile resolutions, the payment button options display as expected:

![screen shot 2018-10-03 at 11 16 45 am](https://user-images.githubusercontent.com/15803018/46420728-9e9ecc00-c6fe-11e8-891d-fd51b06f96d8.png)

## Expected

* Payment button options should display on all resolutions.

* User report: 1460558-zen
* User's site: http://viewfromthemorg.com/

**Comment by laurelfulford** [comment]
I can recreate this: when I add the widget to the Sidebar 1 spot, I see the above (the button is only visible on mobile screens, but is missing on desktop).

When I add it to Sidebar 2, the entire widget isn't visible on desktop. 

I think it may have to do with Publication moving the widget markup via JavaScript, but not 100% sure.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
