### ISSUE TITLE
Bari: "Load more" button disappears after clicking once

### ISSUE THREAD

**Issue by fashuvo** [Automattic/themes#2750]
## Steps to replicate

1. Open this page:
https://velasyvikingos.com/category/cultura/

2. Click the "Carger Mos" (load more) button. Screenshot:

<img width="1362" alt="Image 2020-10-31 at 5 38 03 PM" src="https://user-images.githubusercontent.com/6534920/97778251-32724900-1ba0-11eb-9623-8b95b786c5f8.png">

## Result

The load more button disappears once we have clicked the button once. Here's a screen recording:
https://a.cl.ly/nOunJr0b

## Expected

User has chosen 10 posts to display per page. As they have 36 posts in that category, they should be able to click the load more button at least 3 times.

* User report: #3447962-zen
* Follow-up ticket: #3447962-zen

**Comment by scruffian** [comment]
Moved to Trac

**Comment by danieldudzic** [comment]
This has now been fixed.
