### ISSUE TITLE
Independent Publisher 2: Current page drop-down menu items are invisible on mobile

### ISSUE THREAD

**Issue by sjaved87** [Automattic/themes#276]
When visiting a page on mobile, if it is in the menu, its subpages will not be visible. 

## Steps to replicate

1. Visit the site demo https://independentpublisher2demo.wordpress.com on a mobile device.

2. Open the Menu; note the items listed (Home, About me, Photography on the top level, with Adventures with an SLR camera as a sub menu of Photography)

3. Click on Photography.

4. Reopen the menu.

## Result

See, the child/submenu items of the current page are hidden because of the white color.

http://cld.wthms.co/bBWVA6

The culprit:
```
 .main-navigation>div>ul>li.current-menu-item>ul>li a, .main-navigation>div>ul>li.current_page_item>ul>li a {
    color: #fff;
}
```

## Expected

It should display the sub-menu items. Like this -> http://cld.wthms.co/VVp82a

* User report: #1465160-zen
* Follow-up ticket: #1465160-zen
* User's site: https://sanatanadhara.wordpress.com/ Issue can't e viewed there. Because as a workaround I gave them following CSS code. 

* However, you can see the issue on my test site: https://sjtesterblog.wordpress.com/about/
```
 .main-navigation>div>ul>li.current-menu-item>ul>li a, .main-navigation>div>ul>li.current_page_item>ul>li a {
    color: #00aadc;
}
```

**Comment by shreeshylahs** [comment]
May i know was the above mentioned css manually added through Dashboard?

**Comment by sjaved87** [comment]
It looks like this one:

```
 .main-navigation>div>ul>li.current-menu-item>ul>li a, .main-navigation>div>ul>li.current_page_item>ul>li a {
    color: #fff;
}
```

Is coming from theme style.css.

I gave the following to add through dashboard to fix/workaround:

```
 .main-navigation>div>ul>li.current-menu-item>ul>li a, .main-navigation>div>ul>li.current_page_item>ul>li a {
    color: #00aadc;
}
```

**Comment by sjaved87** [comment]
I see, thank you and I am glad we were able to figure out. 👍

**Comment by shreeshylahs** [comment]
I think there might be many other places which would need a fix.

**Comment by laurelfulford** [comment]
Committed to WP.com in 53224-wpcom-themes.
