### ISSUE TITLE
Twenty Seventeen: CoBlocks Carousel breaks in Front Page Sections

### ISSUE THREAD

**Issue by otpidusprime** [Automattic/themes#2760]
## Steps to replicate

1. Activate Twenty Seventeen
2. Create a new Page and add Carousel Block (needs CoBlocks plugin)
3. Go to Customizer → Theme Options
4. Set the page created in Step 2, as one of the Front Page Sections

## Result

The Carousel Block breaks in Front Page Section _(the Images appear one below another)_, but works on single pages.

**Here's the comparision:**

| Front Page Section  | Single Page |
| ------------- | ------------- |
| <img width="659" alt="Screenshot 2020-11-03 at 8 59 59 PM" src="https://user-images.githubusercontent.com/29238672/98005899-9488b380-1e17-11eb-94d9-bc8aa6119ae4.png">  | <img width="657" alt="Screenshot 2020-11-03 at 9 01 40 PM" src="https://user-images.githubusercontent.com/29238672/98006120-e3364d80-1e17-11eb-9cec-5f67eb802ff7.png">  |

## Expected

The Carousel should work on Front Page Sections, like it works on the single pages.

* User report: #3444047-zd
* Related P2: https://wp.me/p9F6qB-659

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
