### ISSUE TITLE
Isola: Default header colors loading in Customizer but not on live sites

### ISSUE THREAD

**Issue by tmontg1** [Automattic/themes#278]
## Steps to replicate

1) Go to Customizer
2) Click 'Colors & Backgrounds'
3) Make a change to the color palette + publish
4) Change back to "default" + publish

## Result

At that point, the default colors are restored in the customizer but not on the live site. 

## Expected

In this case, the default colors should be restored in the customizer as well as on the live site. 

* User report: 618190-hc
* Follow-up ticket: 1484540-zen
* User's site: https://goranpehrson.se/

**Comment by laurelfulford** [comment]
Hi @tmontg1! Were you able to recreate this on a test site? It's possible this is a caching issue if it's only happening on this one site.

**Comment by MindyPostoff** [comment]
@laurelfulford I was able to use the colors just fine on my test site, so I looked more closely into the user's site. The user has added a TON of custom CSS, which is overriding the color functionality of the theme. Removing the custom CSS allows the theme's color scheme to work as expected.

Closing issue.

**Comment by tmontg1** [comment]
Thanks @MindyPostoff and @laurelfulford 

At the time of testing, I confirmed there was no custom CSS in the user's customizer. They removed it during our chat. It is possible they have added it back since. 

When I go to https://goranpehrson.se/ now I see the hamburger menu, site title, and search icon are all black. As you'll see via the demo site (https://isolademo.wordpress.com/) the theme's default header color for the menu, site title, and search icons is grey. 

When you go to the customizer on the user's site (https://goranpehrson.wordpress.com/wp-admin/customize.php) > click 'Colors & Backgrounds' > then click 'default' you'll notice the theme defaults back to the grey color in the customizer preview. After clicking 'Publish' and going back to the live site, you'll still see the black hamburger menu, site title, and search icon though. 

I was able to replicate a similar issue with the 'default' reset working in the customizer but not on the live site using my test site. I'm using Chrome, maybe a browser related issue?

**Comment by laurelfulford** [comment]
Thanks for digging into this more, @MindyPostoff, and for the extra information, @tmontg1! 

Sometimes the custom colours caching gets a bit too aggressive, and the colours get "stuck" (for lack of a better word). We can manually clear these in a couple ways:

1. Append `?clear-colors-cache` at the end of the site's URL will usually do it.
2. If it doesn't, ping someone in the theme team, and we can try a second option that needs a sandbox; I've done that on this site, and the header text is now displaying as grey.

Just let me know if you have any questions about this!

**Comment by tmontg1** [comment]
That did the trick! Thanks so much, @laurelfulford! I'll let the user know.
