### ISSUE TITLE
Varia: Additional WhatsApp Block Colour Schemes Display Incorrectly

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2780]
The WhatsApp Block has a few different colour schemes available with it. Here's what they look like with Spearhead active.

![image](https://user-images.githubusercontent.com/545779/98291776-4ab3e080-1f71-11eb-9cf6-8ccc12ab2446.png)

There appear to be some issues with how those additional colour schemes display in the Mayland theme.

![image](https://user-images.githubusercontent.com/545779/98292025-a7af9680-1f71-11eb-84b6-71bd9775b450.png)

There may be issues with other Varia themes as well. Here's what Maywood looks like.

![image](https://user-images.githubusercontent.com/545779/98292167-e7767e00-1f71-11eb-9098-c0e2e4c5a420.png)

**Comment by danieldudzic** [comment]
This seems to be working fine now:

![varia](https://user-images.githubusercontent.com/905781/107530980-adde9000-6bbc-11eb-8a31-63d218c42055.png)

![spearhead](https://user-images.githubusercontent.com/905781/107530999-b20aad80-6bbc-11eb-880e-ecbf98b83dfd.png)

![Maywood](https://user-images.githubusercontent.com/905781/107531006-b46d0780-6bbc-11eb-90d6-ecb65953aa38.png)
