### ISSUE TITLE
Apostrophe 2: Newspack Post Carousel block not working

### ISSUE THREAD

**Issue by ajaykj** [Automattic/themes#2788]
## Steps to replicate
1. Activate Apostrophe 2 theme
2. Add a Newspack Post Carousel block to a page/ post

![Markup on 2020-11-08 at 19:12:12](https://user-images.githubusercontent.com/35197279/98466570-582dcc80-21f6-11eb-8dad-cf806fe12c5a.png)

## Result

The page/ post appears without the carousel block. There is an error in the console `Uncaught TypeError: s() is not a function` referring to `/wp-content/plugins/full-site-editing/newspack-blocks/dist/carousel-block-view.js` file.

![Markup on 2020-11-08 at 19:17:54](https://user-images.githubusercontent.com/35197279/98466741-72b47580-21f7-11eb-8734-0a5de5f62215.png)

## Expected

The post/ page to appear with the carousel block. If I switch the theme to a different theme, the carousel appears without any issues.

![Markup on 2020-11-08 at 19:26:58](https://user-images.githubusercontent.com/35197279/98466894-6381f780-21f8-11eb-9003-25db0f1c672c.png)

* User report: #25486869-hc
* Follow-up ticket: #3472738-zd

**Comment by susanjanec** [comment]
User reported similar issue 3706911-zen - they also have the Apostrophe 2 theme active and the Post Carousel is not displaying on their homepage but is showing fine within the edit page.

**Comment by AtrumGeost** [comment]
Sharing HC Report: pbEMJv-x1-p2

**Comment by druesome** [comment]
@ajaykj @susanjanec @AtrumGeost this is likely due to the Featured Images > Display on pages option being unchecked in the Customizer > Content Options.  Checking the box will resolve the issue.

**Comment by AtrumGeost** [comment]
That's a cool TIL. Thank you @druesome ! Should we close this issue?

**Comment by druesome** [comment]
@AtrumGeost yup! I'll go ahead and close this.
