### ISSUE TITLE
 Another round of CSS bug fixes in WooCommerce compatible themes

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#28]
<p>While continuing WooCommerce integration reviews I have stumbled upon a few more CSS bugs.</p>
<p>For the sake of consistency and general niceness, it would be beneficial to fix the following:</p>

<p><h3>Pay for Order page - Payment Methods lacking styling</h3></p>

![screenshot](https://cldup.com/qYxCKSlAtJ.png)

<p>List of themes needing the fix:</p>

* ~~Button 2~~
* ~~Small Business~~
* ~~Dyad 2~~
* ~~Independent Publisher 2~~
* ~~Karuna~~
* ~~Libre 2~~
* Lodestar
* Pique
* Radcliffe 2
* Shoreditch

<p><h3>My Account &gt; Orders - No space between the Pay, View and Cancel buttons (sometimes this also causes the table to bleed into the sidebar)</h3></p>

![screenshot](https://cldup.com/0KG9oMBTsC.png)

<p>List of themes needing the fix:</p>

* ~~Button 2~~
* ~~Small Business~~
* ~~Dara~~
* ~~Dyad 2~~
* ~~Independent Publisher 2~~
* ~~Karuna~~
* ~~Libre 2~~
* ~~Lodestar~~
* ~~Pique~~
* ~~Radcliffe 2~~
* ~~Shoreditch~~

**Comment by kathrynwp** [comment]
Moved Small Business into 2299-wpcom-themes
