### ISSUE TITLE
Brompton: Header semicircle z-index issue

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#2800]
There is an issue with the top semicircle in the header, it appears behind the Masthead so the red line is visible.

## Steps to replicate

* Add Brompton theme to a site
* View the semicircle in the header above the branding

## Result

Top border is visible:

![https://d.pr/i/vEQXau](https://d.pr/i/vEQXau+)

## Expected

No red line (like it was previously):

![https://d.pr/i/bHHxtR](https://d.pr/i/bHHxtR+)

Appears to be caused by:

```
#masthead {
  z-index: 2;
}
```

* User report: 3479798-zd-woothemes

We used the following to resolve:

```
#masthead {
  z-index: unset;
}
```

**Comment by supernovia** [comment]
Noting another case here: https://wordpress.com/forums/topic/bug-in-the-brompton-theme/

**Comment by Putoljupka** [comment]
The bug reported above has been fixed, but a new one has appeared, even worse. Now under the logo and the name of the blog is a black semicircle, which obscures half the menu.

https://putoljupka.wordpress.com/

**Comment by mikeicode** [comment]
@Putoljupka Can you refresh your browser on the site now? The issue was the color of the lower semicircle, which should now be resolved:

![https://d.pr/i/LdERFd](https://d.pr/i/LdERFd+)

I used `?clear-colors-cache=1` to clear the cache to resolve, since you have a custom color palette.

Related issue: https://github.com/Automattic/themes/issues/2360

**Comment by Putoljupka** [comment]
Now it's O.K. Thank you all!
