### ISSUE TITLE
Seedlet: Social icon misaligned in Editor

### ISSUE THREAD

**Issue by melchoyce** [Automattic/themes#2801]
## Steps to replicate

1. Add a Social Icons block to the editor
2. Add some icons to the block
3. See that the first icon in the list is misaligned within the Editor
4. Preview the post or page and see that the list appears correctly on the front-end

## Result

![image](https://user-images.githubusercontent.com/2846578/98836982-635c4480-2410-11eb-98b8-1043c0fed14c.png)

## Expected

All of the icons are aligned correctly, as they are on the front-end.

**Comment by ryelle** [comment]
This was also an issue in Twenty Twenty-One https://github.com/WordPress/twentytwentyone/issues/716. In that case it has to do with how margin is added to child blocks. It was fixed with this PR https://github.com/WordPress/twentytwentyone/issues/726.

**Comment by iamtakashi** [comment]
I have opened an issue about this here: #2727

**Comment by jffng** [comment]
Closing this as a duplicate.
