### ISSUE TITLE
Rowling: Social icons block alignment issue

### ISSUE THREAD

**Issue by nagpai** [Automattic/themes#2806]
## Steps to replicate

1. Install the theme and create a post with social icons block
2. Add a few dummy social icons to the block. Four or more to get a good feel of the issue.
2. Test the block with left and center alignment.

## Result
The icons are misaligned

Left Align: The first icon appears to have a top margin. 

![rowling-bug-2](https://user-images.githubusercontent.com/4162931/98887269-ac1d0780-24bb-11eb-9047-98003bf817e8.jpg)

[---]
Center align: Icons are strung vertically. 

![rowling-bug-1](https://user-images.githubusercontent.com/4162931/98887304-bccd7d80-24bb-11eb-810c-3622cd6dfcea.jpg)

## Expected
Correct alignment - all icons on the same horizontal line. 

## Custom CSS workaround given to user

> ul.wp-block-social-links.aligncenter {
> display: flex;
> justify-content: center;
> align-items: center;
> }
> 
> li.wp-social-link.wp-social-link-facebook.wp-block-social-link {
> margin-top: 0;
> }
> 
> .wp-block-social-link:last-child {
> margin-top: -0.5em;
> }

* User report: #25554288-hc
* Follow-up ticket: [shortlink to ticket, ie #12345-zd]

**Comment by rosepajaroja** [comment]
I encountered the same issue today. 

With Rowling theme: 

![Alt text](https://d.pr/i/oHRy0n/wUzoIGpwls+)

With Twenty Twenty theme: 

![Alt text](https://d.pr/i/bEylUL/WZJpFJ5oun+)

In the meantime, I shared CSS from Nagesh (thank you! 😊 ). 

ZD-4622805

**Comment by MaggieCabrera** [comment]
@madhusudhand I see your fix solved the problems when the icons are left aligned, but when centered aI see them like this:
<img width="717" alt="Screenshot 2022-03-01 at 10 50 16" src="https://user-images.githubusercontent.com/3593343/156146224-f9574240-1291-4e70-a135-11e946f97dc6.png">

**Comment by madhusudhand** [comment]
@MaggieCabrera  I have configured different alignments and vertical orientation in sidebar. But I could not replicate the mentioned behavior.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/1935113/156149355-dc20ab17-ac80-42ea-9221-7f15ccccd3d2.png">

Could you please provide me steps?
Also, is this issue in sidebar or other areas?

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera I have configured different alignments and vertical orientation in sidebar. But I could not replicate the mentioned behavior.
> 
> <img alt="image" width="338" src="https://user-images.githubusercontent.com/1935113/156149355-dc20ab17-ac80-42ea-9221-7f15ccccd3d2.png">
> 
> Could you please provide me steps? Also, is this issue in sidebar or other areas?

I tried this inside the actual post content, which, looking at the screenshots on the original issue, is where the user was trying too

**Comment by madhusudhand** [comment]
Social icons in a post

<img width="556" alt="image" src="https://user-images.githubusercontent.com/1935113/156170219-af3c66f5-a2a5-45b8-9610-4217dc7f5157.png">

**Comment by MaggieCabrera** [comment]
Closed via D75840-code
