### ISSUE TITLE
Clean Home: Buggy Infinite Scroll

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#281]
## Steps to replicate
Visit a site with plenty of posts
Note which dates to expect (not knowing makes it tougher to spot problems)
Scroll down

## Result
Swaths of posts are missing, sometimes. For example, if I go to
https://shariblaukopf.com/page/4/
I see a post for July 31, but the next one down is in May 1, even though there are several posts in between.

Other times I can see the posts between

## Expected
Given that there aren't sticky posts, I expect to see all posts in reverse chronological order, but didn't.

User report: https://twitter.com/0xabad1dea/status/1050782325544505344
Follow-up ticket: https://reply.buffer.com/conversations/W8DRX_eIbAABuEOn
User's site: https://shariblaukopf.com/ <- the user reporting does not likely own this site. They just noticed issues on it and reported it, along with another site with a similar theme, on twitter.  I've filed an issue for that theme as well:
https://github.com/Automattic/themes/issues/280

**Comment by laurelfulford** [comment]
Similar to #280, this is an issue that involves an older theme (retired in 2015), using an older infinite scroll method.

I'm going to leave this one open and mark as `needs testing` for now, to rule out that it's something to do with how older themes implement infinite scroll, and not a wider issue. Unfortunately, most non-security issues that only happen in retired themes are `wontfix`es, but it would be good to make sure that's where this is restricted to.

**Comment by laurelfulford** [comment]
Given the age of the theme, I think it does make sense to close this one. We haven't had additional reports of infinite scroll issues like this outside of #280.
