### ISSUE TITLE
Bug in the Brompton Theme

### ISSUE THREAD

**Issue by Putoljupka** [Automattic/themes#2812]
From yesterday the Brompton theme has a bug. A colored line appeared above the logo and title, which should not be there. The problem is not only on my blog, but in general on all blogs and websites that use this theme, including even a Live Demo of this theme.

https://bromptondemo.wordpress.com/

**Comment by kathrynwp** [comment]
Hi there - this issue was already reported in #2800 and the developers will look at it. Thanks for the report.

**Comment by Putoljupka** [comment]
O.K. Thanks.
