### ISSUE TITLE
Twenty Twenty: Selecting Font Variant for Headings Changes Base Font

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#2814]
## Steps to replicate

1. Go to Customize > Fonts
2. Select a custom font for Headings
3. Select Bold, Italic, or Bold Italic

## Result

The base font turns bold/italic/bold italic – not just headings.

## Expected

Selecting a font variant for headings should **not** affect text other than headings.

This looks like a problem with the theme's font annotation on WordPress.com.

No user report, discovered on my own site.

![Customize__Kathryn_Presner_–_Theme_whisperer_and_professional_cat_cuddler](https://user-images.githubusercontent.com/7662449/99004526-3b9ed680-250d-11eb-9960-fe6caa2f5130.jpg)

**Comment by kathrynwp** [comment]
Another font-annotation bug for this theme: #2427 2427

**Comment by thabotswana** [comment]
Another report here: 3824752-zen

**Comment by danieldudzic** [comment]
This should be now fixed via r58006
