### ISSUE TITLE
Radcliffe 2: Shape Divider block won't display

### ISSUE THREAD

**Issue by happychait** [Automattic/themes#2824]
## Steps to replicate

1. Activate Radcliffe 2 theme on a site.
2. From the block editor, add a CoBlocks' Shape Divider block to a page or post.

## Result

The Shape Divider block is not visible on the site: https://d.pr/i/kcrkFB

## Expected

Shape Divider block to show up on the site as shown in this screenshot: https://d.pr/i/vr2WoY

This CSS workaround helped:

```
.wp-block-coblocks-shape-divider {
    display: inherit;
}
```

* User report: #7907359-hc
* Follow-up ticket: #3490572-zd

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
