### ISSUE TITLE
Some Child Menu Items Missing in Canape

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/themes#2829]
The sub-menu items won’t all show when the plugin is activated, and the customer can’t re-order the items, but they can when the plugin is disabled. 

Some sub-sections work, such as Savoury and Loose Leaf Teas, but others such as sweet do not show

![screenshot](https://d.pr/i/AnXdaH+)

They do show on the site, however:

![screenshot](https://d.pr/i/2Xz2tc+)

@katiebethbrown also tested and found the same saying:

```
When coblocks is off, there's a Menu Section Header at the top of the Food Menus page called -- Sweet.
When I enable CoBlocks again the -- Sweet section title no longer shows, but it looks like all the other items are still there. I can also move both sections and items around still.
So it looks like just the top section title is missing. I think that's related to this notice:

NOTICE: wp-includes/class-wp-list-util.php:185 - Undefined index: name
require_once('wp-admin/admin-header.php'), do_action('admin_enqueue_scripts'), WP_Hook->do_action, WP_Hook->apply_filters, coblocks_localize_layout_selector, coblocks_layout_selector_categories, apply_filters('coblocks_layout_selector_categories'), WP_Hook->apply_filters, CoBlocks_Block_Patterns->load_categories, wp_list_pluck, WP_List_Util->pluck
```

It seems like the items on this page are using a custom post type of nova_menu_item and the Coblocks Plugin is trying to enqueue the layout selector but something (name?) is missing somewhere.

Note - The post type nova_menu_items comes from Jetpack, so it could be something non-theme specific. 

This appears to be similar to https://github.com/Automattic/jetpack/issues/2012 but not exactly it. 

* User report: #3494972-zd

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
