### ISSUE TITLE
AltoFocus: theme demo page header issues

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#283]
## Steps to replicate

1. On a non-logged browser (Safari, Chrome, or FF), visit https://altofocusdemo.wordpress.com/
2. Check the header

## Result

It looks like the `demosite-header` is breaking how the theme header it was supposed to look. Here's how I see it with the header:

<img width="1375" alt="captura de tela 2018-10-12 as 17 09 34" src="https://user-images.githubusercontent.com/1136160/46891831-a0c10300-ce41-11e8-84e6-ae4219c84d82.png">

## Expected

Here's how it looks like when logged into WordPress.com:

<img width="1428" alt="captura de tela 2018-10-12 as 17 10 44" src="https://user-images.githubusercontent.com/1136160/46891861-c817d000-ce41-11e8-8209-e2ced13d7353.png">

* User report: 2167914-hc
* Follow-up ticket: 1488537-zen (no need to follow-up on this one)

**Comment by laurelfulford** [comment]
Fixed via some custom CSS on the demo site.
