### ISSUE TITLE
Button 2 - Mobile Menu button not expanding

### ISSUE THREAD

**Issue by smithkyle45** [Automattic/themes#2831]
## Steps to replicate

1. Activate _Button 2_ theme on an Atomic site
2. View site on a mobile device (it works as expected on a narrow browser window or in the preview)
3. Click "Menu" button to expand & view menu items

I have a working example of this on my own test site here: https://templeofkyle.wpcomstaging.com/

I tested this on a simple site using the Premium site plan to help compare and it was also working as expected. Here's a working example: https://cloudtracing.com/

## Result

The "Menu" button does not expand.
I tested this in Chrome (86.0.4240.198) & Firefox (82.1.3) on my mobile.

* User report: 25682877-hc
* Follow-up ticket: 3500752-zen

**Comment by happychait** [comment]
Another report in 11660736-hc

**Comment by TeniCola** [comment]
Another report in 12112669-hc (follow up 3664428-zen), and this time on a simple site. Setting on hold for now to ask the team about the best advice for users who encounter this.

**Comment by kvvsi** [comment]
Just received a report in 27405626-hc (follow up 3709265-zen) for this issue. Seems like the only solution right now is to have customers choose another theme, which can result in additional work for them.

**Comment by openfist** [comment]
#3710131-zen problem with menu still persists

site - janeldasmusic.com

**Comment by sourourn** [comment]
Another report: #20940197-hc

**Comment by kathrynwp** [comment]
See also #3201

**Comment by kwight** [comment]
Possibly related: https://github.com/Automattic/themes/issues/3201

**Comment by jordesign** [comment]
Closing in favour of #3201
