### ISSUE TITLE
Barnsbury: Featured Images not appearing on any page

### ISSUE THREAD

**Issue by adelineyaw** [Automattic/themes#2836]
## Steps to replicate

1). Edit any page
2). Add a Featured Image
3). View the page (in either preview or front-end)

## Result

Featured Image doesn't appear on the page.
I've tested on both Atomic and simple sites and both produced the same results.

## Expected

When a Featured Image is added it should appear near the top of the page. This only appears to work on posts as seen in this screenshot:

![Featured Image on post](https://d.pr/i/iFjr5h+)
Image link: https://d.pr/i/iFjr5h

* User report: #25762399-hc
No ticket created as the user has switched themes.

**Comment by danieldudzic** [comment]
This has been now addressed by:

- https://github.com/Automattic/themes/pull/3195
- https://github.com/Automattic/themes/pull/3220
