### ISSUE TITLE
Luxury theme: Missing components on Safari mobile and SeaMonkey browser

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/themes#2845]
## Steps to replicate
1. Activate the Luxury theme along 
2. Check your site on Safari mobile
    - Head to Settings> Safari > Advanced > Experimental Features > Disable Intersection Observer. 
    - Site Title, menu, etc will be missing.

Same issue on the SeaMonkey browser

With Intersection Observer Enabled:
![IMG_9778](https://user-images.githubusercontent.com/44837596/99902438-47418880-2cd7-11eb-8d00-00b8e0d6ec76.PNG)

With Intersection Observer Disabled:
![IMG_2A5684B7FC48-1](https://user-images.githubusercontent.com/44837596/99902443-51fc1d80-2cd7-11eb-8224-7e34a225242b.jpeg)

* User report: #24405605-hc User does not see the site name, menu, the home page slider, and the login/register page checkboxes 
* Follow-up ticket: #3510764-zd

**Comment by scruffian** [comment]
Moved to Trac
