### ISSUE TITLE
Storefront: homepage changes to displaying posts after editing the site title from wp-admin > Settings > General

### ISSUE THREAD

**Issue by daria2303** [Automattic/themes#2846]
## Steps to replicate

- install Storefront theme (Business WordPress.com plan)
- set home page to display a page in Customizer, not posts
- change site's title in wp-admin/options-general.php

## Result

- home page set up comes back to posts display

## Expected

- home page still displays page

* User report: #3510587-zen

**Comment by kathrynwp** [comment]
Hi @daria2303 Storefront is managed by the WooCommerce team in this repo, so could you please move this issue there? Thanks!

https://github.com/woocommerce/storefront/

**Comment by daria2303** [comment]
Sure, sorry!

**Comment by kathrynwp** [comment]
Issue filed here: https://github.com/woocommerce/storefront/issues/1543
