### ISSUE TITLE
Add AMP meta to compatible themes as reader themes.

### ISSUE THREAD

**Issue by milindmore22** [Automattic/themes#2847]
## Steps to replicate

following themes which are compatible with AMP and can be used as reader themes, it can be achieved by adding 
`AMP:true` metadata in themes style.css

[reference](https://amp-wp.org/documentation/playbooks/adding-reader-themes/)  

- [x] Varia
- [x] Alves
- [x] Balasana
- [x] Barnsbury
- [x] Brompton
- [x] Exford
- [x] Hever
- [x] Leven
- [x] Mayland
- [x] Maywood
- [x] Morden
- [x] Redhill
- [x] Rivington
- [x] Shawburn
- [x] Stow

## Result

Themes can be selected as reader themes.

## Expected

Themes can be chosen as reader themes.

**Comment by cathymcbride** [comment]
Closing b/c merged PR
