### ISSUE TITLE
Seedlet: Unable to Activate

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#2853]
## Steps to replicate

**In a simple site:** 

- activating Seedlet in Calypso shows _"Unable to activate theme. Contact support."_ 
- In WP-admin > Appearance, activating Seedlet shows _"Error: Current WordPress version does not meet minimum requirements for Seedlet."_ 
- when previewing the theme it shows "Cannot Activate" in the Customizer. 

<img width="284" alt="Screen Shot 2020-11-23 at 5 09 45 PM" src="https://user-images.githubusercontent.com/36863633/99986202-3106fb80-2daf-11eb-8d50-b76e331aa5c5.png">

**In an AT site:** Seedlet can be activated. 

## Result

Unable to activate Seedlet theme in a simple site. 

## Expected

Clicking "Activate" should activate the theme on simple sites as well. 

* User report: #23208137-hc 
* Follow-up ticket: #3514179-zd

**Comment by jffng** [comment]
Thanks for reporting! Closed in #2854.
