### ISSUE TITLE
Rowling: Images with Captions Displaced

### ISSUE THREAD

**Issue by dkmyta** [Automattic/themes#286]
## Steps to replicate
The issue occurs in both posts and pages.

Create a new page, embed an image and add a caption to the image.

[Regular Image vs Image with Caption](http://prntscr.com/l8gj8k)

Using the most up to date version of Chrome on a Mac Pro.

## Result

Images with captions added are displaced to the right of the content area and aligned awkwardly with the remaining elements on the page. This only displaces the image with the caption added, nothing else on the page is displaced, all else remains aligned as it would normally.

## Expected

I expected the images would remain in the same alignment as normal only with the addition of the caption below.

* User report: 1506472-zen
* Follow-up ticket: 1506472-zen
* User's site: User was using a test site: pamv7Z-f-p2 and responding for an inquirer of a forum thread here: https://en.forums.wordpress.com/topic/photos-are-aligned-right-and-cropped-in-blog-posts/

**Comment by laurelfulford** [comment]
It looks like the culprit is the right and left margins on the `figure` element.

**Comment by spencerberry** [comment]
This may need another issue opened (let me know if you'd like me to create it), but there is another issue with captioned images. 

If you center the image, the caption no longer takes up the full width, as shown here:
![Screen Shot 2019-12-06 at 07 33 55](https://user-images.githubusercontent.com/1162736/70334700-c43fcd80-17fa-11ea-9b80-8d2fda6b5763.png)

**Comment by kathrynwp** [comment]
Ran into this in 2542733-zen / 17150609-hc 

Gave user this CSS as a workaround: 

```
/* Rowling - fix caption display / 17150609-hc kp */
.wp-block-image .aligncenter > figcaption {
display: block;
}
```

**Comment by eoinsav** [comment]
Reported here too: 21478044-hc

No Premium plan to apply CSS though unfortunately.

**Comment by silvio-meter** [comment]
Run into this again: 3361899-zen

Provided CSS workaround:

```
/* Rowling - fix caption display -3361899-zen - SM */
.wp-block-image .aligncenter > figcaption {
	display: block;
	text-align: center;
}
```

**Comment by AtrumGeost** [comment]
Adding report from HC:

pbEMJv-ti-p2

**Comment by lakellie** [comment]
Another report: 3872281-zen

**Comment by reginabally** [comment]
Another report: 3953341-zd-woothemes. The site is on a WordPress.com Personal plan so unable to apply the CSS workaround.

**Comment by sixhours** [comment]
Diff at D62202-code

**Comment by sixhours** [comment]
Fixed in r59029-wpcom-themes
