### ISSUE TITLE
Exford: Default Secondary Color Doesn't Reflect on the Site

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#2862]
## Steps to replicate

1. Activate Exford theme and go to Customize → Colors & Backgrounds
2. Notice that secondary color (fourth circle) is the default #0963c4
3. However, the site elements are not this color. Hover over a button to see that the button hover color is not #0963c4
4. Change secondary color to something else
5. Notice the hover color now takes effect

Video of this in action: https://share.getcloudapp.com/4guOb5x1

## Expected

I expected the color of the circle to match the secondary color on the site. Myself and the customer I was working with were looking all over the site for the #0963c4, not realizing we had to change the color setting to something else for it to take effect.

This doesn't seem very logical and it would be helped to make the default secondary color on the site match what's in the circle no matter what.

* User report: #25865827-hc
* Follow-up ticket: N/A

**Comment by pbking** [comment]
Part of this seems to be fixed by https://github.com/Automattic/themes/pull/3209

**Comment by scruffian** [comment]
Thanks for reporting. I agree that this is confusing. It's a legacy feature of how these color annotations were set up. The same issue in on other Varia themes too. Changing this is quite a lot of work whichever way we do it, and it will mean making changes to users current sites which they will probably not thank us for.

My suggestion is that we leave things as they are, but make sure that things work properly in the new color annotations we create. We don't anticipate using this plugin for new themes quite soon, and hope to retire it. 

I'm going to close this as "wontfix".
