### ISSUE TITLE
Varia + Child Themes: Color Labels Missing on Atomic Sites

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#2863]
## Steps to replicate

1. Go to Customize → Colors and Backgrounds
2. Select a color

The label for each color that is present on simple sites:
<img width="230" alt="simple color label" src="https://user-images.githubusercontent.com/30727666/100264652-375dc900-2fa3-11eb-95d6-d1a7a5643eb9.PNG">

is missing on atomic sites:

![Annotation on 2020-11-25 at 16-18-44](https://user-images.githubusercontent.com/30727666/100264637-30cf5180-2fa3-11eb-9ee2-e691ceec60e8.png)

Seen on Varia, Barnsbury, Mayland, and Exford.

## Expected

I expected to see a label to indicate what the color is.

* User report: #25865827-hc
* Follow-up ticket: N/A

**Comment by donalirl** [comment]
A nice user quote on this that I thought might inform future design iterations:

"I was wondering what those Olympic rings did!!"

**Comment by arunsathiya** [comment]
Ran into this while troubleshooting 3636264-zen with @krutidugade here - p1610257074096300/1610256106.092000-slack-C03TY6J1A.

**Comment by jffng** [comment]
I believe this issue has been resolved, see: https://github.com/Automattic/wp-calypso/issues/48773#issuecomment-759732444

I have also tested on an atomic site and verified the labels appear when using a Varia theme.
