### ISSUE TITLE
Photographer: Pricing Table Alignment Issue

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#2864]
## Steps to replicate

1. Activate the _Photographer_ theme
2. Add the _Pricing Table_ block and fill in its details
3. Save the page and observe the result in front-end

## Result

The columns are misaligned:

![Markup on 2020-11-26 at 11:12:56](https://user-images.githubusercontent.com/25105483/100338038-66426200-2fd8-11eb-889f-5eda934f0699.png)

## Expected

Here is how the pricing table should be aligned:

![Markup on 2020-11-26 at 11:14:02](https://user-images.githubusercontent.com/25105483/100338175-8d992f00-2fd8-11eb-99c8-51702ae78c9d.png)

User report: 25865101-hc

In the meantime, the issue can be fixed by the following CSS (h/t @donalirl).

The code is for the pricing table with three columns, medium gutter. 

```
/* fix issue with Pricing Tables wrapping to next line -- XXXXXXXX-hc (DOC) */
.wp-block-coblocks-pricing-table__inner.has-columns {
  flex-wrap: nowrap;
}

@media (max-width: 959px) {
  .wp-block-coblocks-pricing-table__inner.has-3-columns.has-medium-gutter>*:not(.block-editor-inner-blocks):nth-of-type(3) {
    margin-top: 0;
    flex-basis: 50%;
  }
}
```

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
