### ISSUE TITLE
Dyad 2: "Invisible" Jetpack cookie widget messing up footer widget display

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#287]
## Steps to replicate

This only happens on the self-hosted version of this theme:

1. Install Dyad 2 and Jetpack on a self-hosted site.
2. Visit the Customizer and add four widgets to the footer - all four widgets should display next to each other on a standard computer screen.
3. Change the visibility settings of one widget to not show on the front page (or just delete one widget) - note the width of all remaining widgets increase so that the widget area as a whole still takes up the full width of the page.
4. Add the Jetpack Cookies and Consent Banner widget.

## Result

The widget area adjusts to show the widget area in four columns again, with the last column completely empty:

![customize__my_core_sandbox_ _just_another_wordpress_site](https://user-images.githubusercontent.com/11873759/47348583-133ba980-d6b2-11e8-92c5-065dd6eefe4c.png)

Noting it's always the last column that remains empty, no matter the actual position of the cookie widget in the widget area.

## Expected

The cookie widget is an active widget being loaded on the page, so on the one hand it makes sense that the theme would adjust the widget area based on that. But on the other, this is an invisible widget in the sense that it doesn't actually load in the widget area, so it's reasonable to expect that it won't affect the display of the widget area either.

* User report: https://wordpress.org/support/topic/cannot-centre-footer-widgets-if-less-than-four/
* User's site: https://www.stopbyinworthing.co.uk/center-widgets/ (page they created for troubleshooting this - issue not currently visible there as they've disabled the cookie banner as part of their testing.

**Comment by laurelfulford** [comment]
I can recreate this on a self-hosted site, and WP.com, too, when I manually add a Cookies & Consent widget (rather than when the banner appears there automatically).

We might need to rework Dyad 2's footer to fix -- right now it counts widgets to figure out whether they should be 100%, 50%, 33% or 25% wide; as is we'd have to somehow get it to exclude the cookie widget (and others, like Mailchimp).

**Comment by laurelfulford** [comment]
This was committed to WP.com in r53324-wpcom-themes.

I also re-zipped the theme to make the update available to self-hosted sites, and added a comment to the forum thread to follow up.

**Comment by torres126** [comment]
Noting that it looks like this may have caused some confusion? https://en.forums.wordpress.com/topic/folter-columns/

**Comment by ashercantrell** [comment]
Yeah, I've got a user in 1789105-zen who is seeing all of their widgets in a single column now, even on desktop. You can take a look at the site here: https://opaskitchen.blog/

**Comment by laurelfulford** [comment]
Thanks @torres126 & @ashercantrell! Yeah, looks like I got a little too clever with the fix 😬 Apologies! Sorting out in #589, and will add follow ups to those reports!
