### ISSUE TITLE
Passenger: Author name on posts is hidden with CSS

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#2870]
## Steps to replicate

1. Activate the _Passenger_ theme.
2. Publish a post and open it in the front-end.

## Result

The author name is hidden with CSS:

![Markup on 2020-11-30 at 12:43:08](https://user-images.githubusercontent.com/25105483/100606757-32ce4300-330a-11eb-87d0-11ce4bae6bf8.png)

## Expected

Author name is properly displayed.

* User report: 26000358-hc

CSS workaround:

```
/* Passenger theme fix / io / #XXXXXXX-hc */
.multi-author-false .post-meta-data .byline {
	display: inline;
} 
```

**Comment by scruffian** [comment]
Moved to Trac
