### ISSUE TITLE
Spearhead: TRT issues

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#2875]
We received feedback on Spearhead from the Theme Review Team here: https://themes.trac.wordpress.org/ticket/91317

This issue captures remaining feedback to be addressed.

- [ ] functions.php
  - L226 Please add: if ( is_admin() ) return $more;
    - you should probably use `&hellip`;
- [x] Please read the screenshot requirements carefully.
  - please change the site description
- [ ] Keyboard navigation - not ok
  - mobile menu: links in it are unreadable on focus, black on black
- [ ] Links within content must be underlined - not ok
  - Please check the content of your posts (the_content()), excerpts (the_excerpt()), comments content, text widgets, custom options with large blocks of texts.

**Comment by jffng** [comment]
@kjellr the focused state of the mobile link is a dark grey on black making it difficult to read — do you have a recommendation on a different color for the focus state here? 

![image](https://user-images.githubusercontent.com/5375500/101091905-ce6be780-3586-11eb-8cff-c6da24d3a149.png)

**Comment by kjellr** [comment]
I'd suggest copying the treatment for the desktop menu items: 

![Screen Shot 2020-12-03 at 6 10 29 PM](https://user-images.githubusercontent.com/1202812/101099558-e0538780-3592-11eb-9269-86455c9b70fc.png)

Looks like it's a lighter gray there? Otherwise the primary red color could work.

**Comment by kjellr** [comment]
Actually I see now that this is an issue with light mode — in that case, I think we should just have the menu items turn red on focus.
