### ISSUE TITLE
Veni: Text within Form fields on Cover blocks not visible

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#2877]
If you add a form on top of a Cover block the text with the fields are not visible.

## Steps to replicate

* Add a Form block on top of a Cover block
* View page, type into fields

## Result

Text is white, caused by this CSS:

```
.wp-block-cover .wp-block-cover__inner-container {
    color: #fff;
}
```

From this CSS file:

`/wp-content/plugins/gutenberg/build/block-library/style.css`

![https://d.pr/i/7skoBB](https://d.pr/i/7skoBB+)

## Expected

Appears that there needs to be specific color set for these forms when they are on a Cover block. Something like this:

```
.wp-block-cover .contact-form input,
.wp-block-cover .contact-form textarea { 
    color: #000;
}
```

![https://d.pr/i/SexRX9](https://d.pr/i/SexRX9+)

* User report: 25774970-hc

**Comment by scruffian** [comment]
Moved to Trac
