### ISSUE TITLE
Seedlet Blocks: Add support for theme options

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2882]
We should add theme support for all the newest theme options, e.g. custom padding:

https://developer.wordpress.org/block-editor/developers/themes/theme-support/

cc @iamtakashi @ianstewart

**Comment by MaggieCabrera** [comment]
Is this still relevant or did you mean it for Seedlet instead?

**Comment by scruffian** [comment]
I'm pretty sure it was meant for Seedlet. Let's close it and see if anyone asks again :)
