### ISSUE TITLE
Hever and others: error massage when creating a page and clicking on the layout.

### ISSUE THREAD

**Issue by daria2303** [Automattic/themes#2884]
## Steps to replicate

Install Hever (It's the same for few other themes, including twenty twenty)
Premium plan
New Page
Click layout different than default

## Result

Sometimes error massage appears here https://d.pr/i/4X6XTl or you need to click on the layout page on the right.
Sometimes it works fine, but repeated few times for me.

## Expected

No error massage.

* User report: [24708264-hc]
* Follow-up ticket: [3538658-zd-woothemes, 3538658-zd]

**Comment by lakellie** [comment]
This is a known issue and it will be fixed in https://github.com/WordPress/gutenberg/pull/27445

**Comment by shohanhossainnab** [comment]
Another report:
HC: 26154805
ZD Follow-up: 3553650

**Comment by daria2303** [comment]
Another report
HC: 26174708
ZD: 3554329

**Comment by daria2303** [comment]
Another report:
HC: 23197551
ZD: 3554580

**Comment by eurello** [comment]
This does not seem to be specific to this theme, rather related to [this issue here](https://href.li/?https://github.com/WordPress/gutenberg/pull/27445).

**Comment by katiebethbrown** [comment]
Another report in 26138877-hc.

Should we perhaps move this to wp-calypso instead of the themes repo?

**Comment by eduardozulian** [comment]
This is being checked in p7DVsv-a0v-p2 so I think it's ok to close this. As @eurello mentioned, it's a broader issue.

A possible workaround is to avoid hovering over the layout preview when selecting the template. This shouldn't trigger the error.

Feel free to reopen this report if needed!
