### ISSUE TITLE
Passenger: Choosing a custom background color makes submenu items transparent on mobile

### ISSUE THREAD

**Issue by kaitohm** [Automattic/themes#2885]
## Steps to replicate

1. Activate the Passenger Theme
2. Create a Custom Menu with Sub Menu items
3. Change the background color from Customizer > Colors & Backgrounds
4. The background color for submenu items on mobile is now transparent
5. Restore to default colors, and the color returns

## Result

Menu behavior on default colors: 
![default-colors](https://user-images.githubusercontent.com/49054298/100980528-b301dc00-3588-11eb-9ffb-a0c46ce2cc93.png)

Menu behavior with custom colors: 
![custom-colors](https://user-images.githubusercontent.com/49054298/100980546-ba28ea00-3588-11eb-875e-bbef91629acd.png)

## Other Info

* This was first reported internally here: pbEMJv-mm-p2

The following code seems to be the culprit:

```
@media only screen and (max-width: 782px) {
​
  .site-container .masthead .menu li ul, .site-container .masthead .menu li.current-menu-item>a, .site-container .masthead .menu li ul li.current-menu-item>a {
    background-color: transparent;
  }
}
```

* User report: 3528921-zd-woothemes

**Comment by scruffian** [comment]
Moved to Trac
