### ISSUE TITLE
Venture: No header image on product pages

### ISSUE THREAD

**Issue by xpurichan** [Automattic/themes#2894]
## Steps to replicate

1. Activate the Venture theme
2. Install and activate WooCommerce
3. Setup a WooCommerce product with a product image
4. Note that the header image on the product page is empty, it doesn't display the product image

## Result

The product image doesn't display in the header image area of the theme. This seems inconsistent as other theme pages and blog posts will use the featured image to display in the header area.

## Expected

We expected to see selected product image populate in the header image area.

* User report: 26022067-hc
* Follow-up ticket: [shortlink to ticket, ie #12345-zd]

For anyone else experiencing this you might find this CSS code helpful, just make sure to add a page ID to it to specify the page:

```
div#primary-header {
    background-image: url(INSERT-IMAGE-URL);
}
```

**Comment by scruffian** [comment]
Moved to Trac
