### ISSUE TITLE
Mayland: Colour scheme loads incorrectly in canvas, bleeds into Editor UI

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2896]
It looks like there are some strange interactions with colour schemes and the Editor with Mayland.

![image](https://user-images.githubusercontent.com/545779/101407795-0afa5480-38a1-11eb-9b72-c614053556df.png)

- Background colour from colour scheme only appearing in button.
- Accordian menu in sidebar gets a strange background colour when selected.
- Colour scheme not loading fully in editor canvas.

**Comment by ianstewart** [comment]
Here's a look at the front-end, editor, and customizer for debugging purposes.

![image](https://user-images.githubusercontent.com/545779/102267904-29cf9b00-3ee0-11eb-9d15-6bb60c441b11.png)

**Comment by ianstewart** [comment]
Another example here.

![image](https://user-images.githubusercontent.com/545779/102268134-8632ba80-3ee0-11eb-85cc-1085df24dcd1.png)

**Comment by scruffian** [comment]
I think there are two issues here. One is that the colors aren't loading in the editor. I think that one is now fixed. The other is that the colors are bleeding into the editor. I am unable to reproduce this - @ianstewart can you still see it?

**Comment by ianstewart** [comment]
@scruffian I can no longer reproduce the colour-bleed in the editor UI. Closing.
