### ISSUE TITLE
Purpose: unable to set an image background on Atomic Sites

### ISSUE THREAD

**Issue by liviopv** [Automattic/themes#2897]
## Steps to replicate

1. On a Atomic site, go to My Sites > Design > Customize > Colors & Backgrounds
2. Under Background, click on "Change"

## Result

Unlike on simple sites, the Customizer shows options to change the palette, individual colors or select a pattern, but none to upload your own image

## Expected

An option to upload a background image should show up

**Atomic**
![Screenshot](https://d.pr/i/saLfpQ+)
Screenshot: https://d.pr/i/saLfpQ

**Simple**

![Screenshot](https://d.pr/i/9XYQHp+)
Screenshot: https://d.pr/i/9XYQHp

## Other

If the user already had a custom background image before going Atomic, they are able to keep that.

* User report: #26068014-hc

**Comment by liviopv** [comment]
This also affects Obsidian #2930

**Comment by scruffian** [comment]
Moved to Trac
