### ISSUE TITLE
Ippo: Content not loading with WordAds enabled on mobile devices

### ISSUE THREAD

**Issue by samiff** [Automattic/themes#290]
## Steps to replicate

1. Enable theme `Ippo` for a site with blog posts on homepage.
2. Enable WordAds to display ads.

## Result

1. When WordAds are enabled, on mobile devices, the site content below the header doesn't load.
    * On my Android device, when I hit stop loading in the Chrome browser, all the content magically appears.
2. Upon disabling WordAds, observe that site content loads as expected.

## Expected

1. Site content should load as expected on mobile device with WordAds enabled.

## Meta

* User report: #7568524-hc
* Follow-up ticket: #1521008-zd
* User's site: vanessarenae.com

**Comment by alaczek** [comment]
Hi! Ippo is a premium theme, so moving this report to Trac: 2514-wpcom-premium-themes
I'd probably check in with Ads team as well, they might have some insight into this issue.
