### ISSUE TITLE
Prosperity: Full Width Images in Columns = Broken Columns

### ISSUE THREAD

**Issue by scosgro** [Automattic/themes#2903]
## Steps to replicate

1. Activate Prosperity
2. Add a Columns Block to the page - 3 columns, equal width.
3. Add an Image Block (with an image in it) to each column. 
4. Make one (or multiple) of the image blocks Full Width.

![image](https://user-images.githubusercontent.com/30731356/101835925-5efb7800-3af1-11eb-99d9-c12a4e47abc4.png)

5. Publish, and view the page.

## Result

The Full Width image breaks the columns. So what looks like this:

![image](https://user-images.githubusercontent.com/30731356/101835820-34a9ba80-3af1-11eb-92ad-30f9e2eaa4c5.png)

Turns into this:

![image](https://user-images.githubusercontent.com/30731356/101835844-3e332280-3af1-11eb-8075-84f9efeff370.png)

With the image not being full width, the columns display properly:

![image](https://user-images.githubusercontent.com/30731356/101835895-51de8900-3af1-11eb-95a2-639e7b506cd4.png)

## Expected

The Columns Block to not be broken by the full-width images. 

* User report: [shortlink to chat/forum thread/ticket, ie #12345-hc]
* Follow-up ticket: [shortlink to ticket, ie #12345-zd]

**Comment by scruffian** [comment]
Moved to Trac
