### ISSUE TITLE
Multiple Themes: Mailchimp Block Button cannot be centered on old themes. Styling broken on newest themes

### ISSUE THREAD

**Issue by scosgro** [Automattic/themes#2904]
**Per Slack comment, I've reposted to Create in Calypso, here:** 
https://github.com/Automattic/wp-calypso/issues/48392

## Steps to replicate

1. Add a Mailchimp Block to a page, click on the button, and center it. Publish the page. 
2. Activate an older theme (pre-Gutenberg). For example: Prosperity, Colinear, Revelar, Canape, Venture, Veggie, Appetite, Maisha, etc...
3. Refresh the page. The button will not be centered.
![image](https://user-images.githubusercontent.com/30731356/101844853-37f97200-3b02-11eb-81df-8029cef8f051.png)

4. Activate a newer theme (block-based). For example: Balasana, Maywood, Rivington, Barnsbury
5. Refresh the page. The button will be centered (as it is in the editor):

![image](https://user-images.githubusercontent.com/30731356/101845106-ae966f80-3b02-11eb-8102-895affe31d53.png)

6. Try an even newer theme. For example, Twenty Twenty, Seedlet, or Spearhead, and they'll come with their own formatting/stylistic issues for that same block:

![image](https://user-images.githubusercontent.com/30731356/101845220-03d28100-3b03-11eb-92a6-e39947220940.png)

## Result

Different results, depending on the themes. Older themes can't center the button. Newer themes look altogether broken.

## Expected
The Mailchimp Block to appear styled as it does in the editor for the page.

**Comment by scruffian** [comment]
This block lives in [Jetpack](https://github.com/Automattic/jetpack) so it probably should be logged there, sorry for the confusion.
