### ISSUE TITLE
Libretto: Search bar overlaps menu items

### ISSUE THREAD

**Issue by fresatomica** [Automattic/themes#2906]
## Steps to replicate

Add more than 3 items to the menu, and click on the search icon.

## Result

The search bar overlaps the menu items, and it isn't easy to see what one is writing.

![Screen Capture on 2020-12-11 at 09-49-00](https://user-images.githubusercontent.com/40177971/101882983-e9e27e00-3b96-11eb-83d6-fa61d2953019.gif)

* User report: https://wordpress.com/forums/topic/libretto-search-bar/

**Comment by hngdny** [comment]
New request for Simple Site : 4259965-zen

**Comment by Gustavo-Hilario** [comment]
Another instance of this issue here: 5259908-zen
