### ISSUE TITLE
Dyad 2: Featured Content post title cut-off on some mobile devices

### ISSUE THREAD

**Issue by nickpagz** [Automattic/themes#291]
## Steps to replicate

* Create a post with a longer title.
* Set that post as 'featured content' so it shows up in the slideshow.
* Set the headings font size to **Huge**
* View in Chrome developer tools using **Galaxy S5** view mode. (Also visible on actual mobile devices).
 
## Result

Title gets cut-off.
https://cld.wthms.co/UUbGaA

## Expected

The title text should resize to fit the view.

* User report: #1524251-zd
* Follow-up ticket: #1524251-zd
* User's site: [https://domoregood.blog/]

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
