### ISSUE TITLE
Independent Publisher 2: Can't Edit Home Page Title

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#2911]
## Steps to replicate

1. Set theme to Independent Publisher 2
2. Create page and add a title "My Home"
3. Publish the page
4. Edit the page and the title displays and allows me to place a cursor there:

![screenshot](https://d.pr/i/eV8YVw+)
Image URL: https://d.pr/i/eV8YVw

5. Go to Homepage Settings in the Customizer and set "My Home" as the home page.
6. Edit the "My Home" page 

## Result
The title is gone:

![screenshot](https://d.pr/i/yK8Tg5+)
Image URL: https://d.pr/i/yK8Tg5

## Expected
I expected it to be there like this:

![screenshot](https://d.pr/i/eV8YVw+)
Image URL: https://d.pr/i/eV8YVw

* User report: #26080174-hc
( I had the user temporarily change their homepage so they could update the title)

**Comment by jordesign** [comment]
No longer able to recreate this.
