### ISSUE TITLE
Multiple Themes: Image Block Captions Misaligned

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#2912]
*Note: This bug applies to [Adventure](https://wordpress.com/theme/adventure), [Collective](https://wordpress.com/theme/collective), [Connect](https://wordpress.com/theme/connect), [Luxury (on Firefox)](https://wordpress.com/theme/luxury), [Natural](https://wordpress.com/theme/natural), [Organization](https://wordpress.com/theme/organization), [Photographer](https://wordpress.com/theme/photographer), and [Purpose](https://wordpress.com/theme/purpose)*

## Steps to replicate

Add an Image block to a post or page, and give the Image block an alignment of left, right, or center

## Result

On the published page, the captions for the image are misaligned -- you can see that in these screenshots:

* Adventure: [https://d.pr/i/tucGPy](https://d.pr/i/tucGPy)
* Collective: [https://d.pr/i/dBPNle](https://d.pr/i/dBPNle)
* Connect: [https://d.pr/i/sPQDRf](https://d.pr/i/sPQDRf)
* Luxury (on Firefox): [https://d.pr/i/syCI9x](https://d.pr/i/syCI9x)
* Natural: [https://d.pr/i/eHzqSE](https://d.pr/i/eHzqSE)
* Organization: [https://d.pr/i/QLXd8z](https://d.pr/i/QLXd8z)
* Photographer: [https://d.pr/i/Thm913](https://d.pr/i/Thm913)
* Purpose: [https://d.pr/i/pByC0t](https://d.pr/i/pByC0t)

## Expected

This is because the `<figcaption>` element is set to `display: table-caption`, but the parent `<figure>` is set to `display: block` -- using this CSS allow the captions to appear as expected:

```
/* fix captions for images and image blocks with alignments | #XXXXXX-hc/zen eD */
img[class*="align"], 
.wp-block-image [class*="align"] {
	display: table;
}
```

* Adventure: [https://d.pr/i/zIQWwN](https://d.pr/i/zIQWwN)
* Collective: [https://d.pr/i/ZaKwFL](https://d.pr/i/ZaKwFL)
* Connect: [https://d.pr/i/pFyi7y](https://d.pr/i/pFyi7y)
* Purpose: [https://d.pr/i/P4Mkld](https://d.pr/i/P4Mkld)

For Luxury, Natural, Organization, and Photographer, you also need to unset the width of the captions, which are set to 100%, which can be done with this CSS:

```
/* unset 100% width for captions | #XXXXXX-hc/zen eD */
.wp-caption-text, 
.wp-caption figcaption,
 .wp-block-image figcaption, 
 [class*="wp-block"] figcaption, 
 .blocks-gallery-caption {
	width: auto;
}
```

Screenshots for the results of that additional CSS are below:

* Luxury (on Firefox): [https://d.pr/i/bDkUKA](https://d.pr/i/bDkUKA)
* Natural: [https://d.pr/i/gWm3JN](https://d.pr/i/gWm3JN)
* Organization: [https://d.pr/i/01N253](https://d.pr/i/01N253)
* Photographer: [https://d.pr/i/SnL8hy](https://d.pr/i/SnL8hy)

**Comment by scruffian** [comment]
Thanks for the report. Moved to the premium themes trac...
