### ISSUE TITLE
Spearhead/Seedlet: Visual issues with Social Links Block in Editor

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2914]
There are a few issues with the Social Links Block in the Editor in Spearhead.

Here's the block in a column inside a group.

![image](https://user-images.githubusercontent.com/545779/102138750-748add80-3e22-11eb-80f9-97b1c288b42d.png)

Note that the individual icons are no longer wrapped in circles.

When selected all the circles stretch to form strange pill shapes …

![image](https://user-images.githubusercontent.com/545779/102138804-8ec4bb80-3e22-11eb-835d-106d67e0592e.png)

**Comment by kjellr** [comment]
Just noting that this occurs in Seedlet as well. I think it needs to be fixed there:

![Screen Shot 2021-01-08 at 8 46 29 AM](https://user-images.githubusercontent.com/1202812/104022219-01a92400-518e-11eb-9043-e589ba32aa41.png)

I've updated the issue title to reflect that.

**Comment by jacklenox** [comment]
This will be fixed by the change made in #3017 once it's propagated to the child themes.
