### ISSUE TITLE
Spearhead: Editor Styles hiding default placeholder text

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2915]
**What I saw:**

In Chrome, MacOS, I see the following entirely blank canvas when creating a new post with Spearhead active.

![image](https://user-images.githubusercontent.com/545779/102139269-3b9f3880-3e23-11eb-99a8-5e22df54581a.png)

**What I expected:**

To see the title and paragraph placeholders similar to this example with Mayland active.

![image](https://user-images.githubusercontent.com/545779/102139350-5a9dca80-3e23-11eb-8fa7-59cffef853e6.png)

**Comment by jffng** [comment]
Alas, while I kind of like the simplicity of a blank canvas, this is fixed by #3011.
