### ISSUE TITLE
Dicot: Social Links items that point to unsupported service / URL doesn't display any icon

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#2917]
## Steps to replicate

1. Add a new menu item that points to an unsupported URL / icon, e.g. `https://patreon.com`:

![Markup on 2020-12-15 at 15:33:37](https://user-images.githubusercontent.com/25105483/102228403-f34b4d80-3eea-11eb-917d-dd53e200f2ac.png)

2. Save the changes and observe:

![Markup on 2020-12-15 at 15:35:02](https://user-images.githubusercontent.com/25105483/102228565-22fa5580-3eeb-11eb-97dd-5fd334b5ac2d.png)

## Result

No link is displayed.

## Expected

Generic link character should be displayed - e.g. 🔗

* User report: 26355098-hc
* Follow-up ticket: 3576374-zd-woothemes

As a workaround, I suggested to the user to add extra `patreon` class to the menu item and use the following CSS code:

```
li.menu-item.patreon a:before {
    content: "Patreon";
}
```

The default font the theme is using doesn't seem to have the 🔗 character available.

**Comment by scruffian** [comment]
Moved to Trac
