### ISSUE TITLE
Maxwell: LaTeX Code Not Visible with Black Background

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#2920]
## Steps to replicate

1. Create a new page
2. Add the LaTeX code: `$latex frac{1}{2}$`
3. Publish the page

## Result

To be able to see the LaTeX content.

## Expected

With the Maxwell theme, it shows with a black background and text, so you can't see the content, as shown on this screenshot:

![LatexOnMaxwell](https://user-images.githubusercontent.com/16104522/102476283-b0e45680-4039-11eb-8ac6-2bdfdd57c51f.png)

While this is what you get with a different theme:

![LatexOnMaxwell2](https://user-images.githubusercontent.com/16104522/102476442-dbceaa80-4039-11eb-99cd-73ce13eae57f.png)

As a workaround, we sent the user a code that changes the background to white: `$latex frac{1}{2}&bg=ffffff&fg=000000$`

* User report: #3581225-zd

**Comment by scruffian** [comment]
Moved to Trac
