### ISSUE TITLE
Consistency with Label and Milestone on GH

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#2921]
I opened a [GH issue for the Maxwell theme](https://github.com/Automattic/themes/issues/2920) and noticed that it didn't automatically add the theme Milestone - there isn't one for Maxwell, so it wasn't showing on [the search for its issues](https://github.com/Automattic/themes/issues/?q=is%3Aissue+is%3Aopen+milestone%3A%22Maxwell%22), which is the _"View open tickets"_ link that shows on the theme overlay:

![ThemeOverlay](https://user-images.githubusercontent.com/16104522/102478848-daeb4800-403c-11eb-96a1-ddb3818acacf.png)

Not sure if it's the same issue, but I noticed that there are lots of GH issues missing the theme Milestone, making it difficult to check if the issue was already reported.

Here's an [example for Mayland](https://github.com/Automattic/themes/issues/2918), another one [for Libretto](https://github.com/Automattic/themes/issues/2906), and [this one for Spearhead](https://github.com/Automattic/themes/issues/2915). On the latter, I noticed that it was added a label related to the theme.

I was wondering how we could guarantee that the GH issues are properly tagged with the right Milestone, so it's easier to find all the reported issues.

**Comment by carinapilar** [comment]
Adding here that I also didn't find a Milestone or Label for the Broadsheet theme.

**EDIT:** we manually created the Broadsheet Milestone, since we had to open [this issue](https://github.com/Automattic/themes/issues/2955), and now with the Milestone other HEs will be able to find it.

**EDIT 2:** also created for the Goodz Magazine theme, for [this issue](https://github.com/Automattic/themes/issues/2937).

**Comment by carinapilar** [comment]
Also wanted to note it here too that there are about [307 GH issues with no Milestone](https://github.com/Automattic/themes/issues?q=is%3Aissue+is%3Aopen+no%3Amilestone), most of them are for specific themes, that won't be visible when using that _"View open tickets"_ link on the theme overlay.

**Comment by scruffian** [comment]
Closing. See https://github.com/Automattic/themes/issues/2956.
