### ISSUE TITLE
Patch: When "Resize for Smaller Devices" is Enabled for YouTube Embed, Embed Appears Over Post Content

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#2923]
## Steps to replicate

When the "Resize for Smaller Devices" option is enabled for the YouTube block, the published YouTube embed appears over the text of the post -- this is how it appears in the editor: 

[![Editor](https://d.pr/i/mDW2h2/i82AAPqzjF+)](https://d.pr/i/mDW2h2/i82AAPqzjF)

## Result

This is how the embed appears on the published page:

[![Published](https://d.pr/i/rtYa0a/qw5rnKX2Tp+)](https://d.pr/i/rtYa0a/qw5rnKX2Tp)

## Expected

I would have expected the embed to appear like this:

[![Correct Embed](https://d.pr/i/79TuY8/nygVEJ5K15+)](https://d.pr/i/79TuY8/nygVEJ5K15)

Using the following CSS will resolve this issue:

```
/* -- fix issue with responsive youtube embed in patch theme | #XXXXXX-hc/zen -- */
/* remove responsive embed top padding */
.wp-embed-responsive .wp-embed-aspect-16-9 .wp-block-embed__wrapper:before {
	padding-top: 0;
}

/* set responsive youtube embed position to relative */
.wp-embed-responsive .is-provider-youtube.wp-has-aspect-ratio .jetpack-video-wrapper iframe.youtube-player {
	position: relative;
}
/* -- / fix issue with responsive youtube embed in patch theme | #XXXXXX-hc/zen -- */
```

* User report: #3190955-zen, #3460926-zen, #23399112-hc

**Comment by scruffian** [comment]
Moved to Trac

**Comment by Greatdane** [comment]
I have just experienced this bug on a third-party theme called 'Aperitive' - it is active and available to users.

Providing CSS like the following or turning off Resize for Smaller Devices fixed the issue. 

See: p1629685347257100-slack-C03TY6J1A and 4241326-zd-woothemes
