### ISSUE TITLE
Nikau: Post with Manual Excerpt and No Featured Image Displays Title Incorrectly

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#2924]
## Steps to replicate

* Create a new post without a featured image
* Set a manual excerpt
* View the single post page

## Result

[![Post with Excerpt and No Featured Image - Before CSS](https://d.pr/i/0X7gv4+)](https://d.pr/i/0X7gv4)

## Expected

[![Post with Excerpt and No Featured Image - Before CSS](https://d.pr/i/OYXxnT+)](https://d.pr/i/OYXxnT)

The following CSS can be applied in the Customizer to get the post to display correctly:

```
/* -- fix for post title on single post page when post excerpt is used | XXXXXX-hc/zen  */
/* unset title position styles */
.single-post.big-thumb.no-thumb .title-wrap {
	width: unset;
	margin-left: unset;
	margin-right: unset;
	bottom: unset;
	padding-bottom: unset;
	background: unset;
	position: unset;
}

/* unset title color style */
.single-post.big-thumb.no-thumb .entry-header h1.entry-title,
.big-thumb .entry-header .intro p {
	color: unset;
}

/* set entry meta margin */
.single-post.big-thumb.no-thumb .hentry .entry-meta {
	margin-top: 20px;
}
/* -- /fix for post title on single post page when post excerpt is used | XXXXXX-hc/zen -- */
```

* User report: #23034554-hc

**Comment by scruffian** [comment]
Moved to Trac
