### ISSUE TITLE
Colors Set in Customizer Don't Show in Editor

### ISSUE THREAD

**Issue by sdixon194** [Automattic/themes#2925]
I have a case where colors set in the customizer don't appear in the editor. 

## Steps to replicate

- Go to My Sites > Design > Customize > Colors and Backgrounds and set a custom background
- Save Changes
- Open a page in the block editor

![Screen Shot on 2020-12-17 at 12:58:51](https://user-images.githubusercontent.com/33553323/102525776-c15ff580-4068-11eb-9dd0-9f41519ef3e8.png)

## Result

- The editor is showing the theme's default color instead of the custom set one.
![Screen Shot on 2020-12-17 at 13:05:16](https://user-images.githubusercontent.com/33553323/102525741-aee5bc00-4068-11eb-8b7e-7a56d9ed6f44.png)

## Expected

- The editor to show the color I set.

This works correctly on my test site, so I think there is something specific about this one site that somehow got their color-wires crossed.

* User report: 26411258-hc

* Follow-up ticket: 3582972-zen

**Comment by nagpai** [comment]
#26596894-hc

**Comment by scruffian** [comment]
I think this will be fixed. Please reopen if you see this issue again.
