### ISSUE TITLE
Lens: Blocks with Full Alignment Not Shown Correctly on Mobile

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#2926]
## Steps to replicate
Blocks that are set to be `alignfull` aren't displayed correctly on mobile devices, and go off the left edge of the screen

## Result

[![Lens - Display Before CSS Applied](https://d.pr/i/b3AKA7+)](https://d.pr/i/b3AKA7)

## Expected

[![Lens - Display After CSS Applied](https://d.pr/i/S1MRLh+)](https://d.pr/i/S1MRLh)

 Because the theme is using `margin-inline-start` to set the starting point for the `alignfull` class, and that's not a valid property in the Customizer for simple sites, it's been a bit tough to override it, but this will work:

```
/* fix alignfull blocks on mobile devices | #XXXXXX-hc/zen */
@media screen and (max-width: 600px) {
	.page .alignfull,
	.post .alignfull{
		margin-right: calc(50% - 50vw);
		margin-left: calc(50% - 50vw);
	}
}
```

**Comment by scruffian** [comment]
Moved to Trac
