### ISSUE TITLE
Maisha: Table Block Formatting Bug

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#2927]
## Steps to replicate

- Add a Table
- Uncheck "Fixed width table cells"
- View Published page 

[![View in Editor](https://d.pr/i/YXhJMN/KW8RkXjohU+)](https://d.pr/i/YXhJMN/KW8RkXjohU)

## Result

Even with the fixed-width setting disabled, the Table still shows fixed-width columns:

[![Before CSS is Applied](https://d.pr/i/03unSv+)](https://d.pr/i/03unSv)

## Expected

The columns in the Table block would adapt to the size of the content:

[![After CSS is Applied](https://d.pr/i/bWkyGX/uD2vfbNOE6+)](https://d.pr/i/bWkyGX/uD2vfbNOE6)

This CSS will resolve the issue:

```
/* unset table block column width | XXXXXX-hc/zen (MI) */

.wp-block-table table:not(.has-fixed-layout) {
    table-layout: auto;
}
```

**Comment by scruffian** [comment]
Moved to Trac
