### ISSUE TITLE
Carbon: Like and Ratings appear in the header for posts with an excerpt

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#2931]
## Steps to replicate
1. Activate the theme
2. Create/edit a post
3. Add a featured image
4. Add an excerpt
5. Make sure that at least Likes are enabled in My Sites > Marketing > Sharing Buttons

## Result

I saw Likes on my Atomic site:

<img width="919" alt="Captura de Tela 2020-12-18 às 18 55 52" src="https://user-images.githubusercontent.com/1136160/102665290-62cb7200-4163-11eb-950f-0b18afd5242d.png">

And Ratings on a simple WordPress.com site (disregard the post title mentioning Ippo, another theme):

<img width="1160" alt="Captura de Tela 2020-12-18 às 18 58 26" src="https://user-images.githubusercontent.com/1136160/102665305-6e1e9d80-4163-11eb-9488-875784a004c7.png">

## Expected

To see nothing but title, excerpt, and entry meta.

* User report: 3582932-zen

**Comment by scruffian** [comment]
Moved to Trac
