### ISSUE TITLE
Hammer: Playlist Dropdown Menu Doesn't Work on Atomic Sites

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/themes#2933]
## Steps to replicate

1. Activate the Hammer theme on an atomic site.
2. Navigate to My Site > Design > Customize > Theme Options.
3. Upload and/or select audio files for the playlist.

## Result

When clicking on the playlist menu button, the dropdown does not appear.

## Expected

The playlist dropdown menu should appear.

In order to get it working, the jQuery Migrate Helper plugin must be installed and the jQuery version must be set to "Legacy 1.12.4-wp".

* User report: #26455950-hc
* Follow-up ticket: #3587681-zen

**Comment by scruffian** [comment]
Moved to Trac
