### ISSUE TITLE
Natural: Image Block Caption Misaligned

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#2938]
## Steps to replicate

1. Add an Image block and add caption.
2. Observe in the front-end.

## Result

The caption is aligned to the left like this:

![Markup on 2020-12-22 at 17:11:54](https://user-images.githubusercontent.com/25105483/102909169-daa5df00-4478-11eb-9fed-3fca20204b2b.png)

## Expected

The caption is properly aligned - centered.

Possible workaround until the bug is fixed:

```
/* Natural theme image caption alignment fix / io / #xxxxxxxx-hc */
.wp-block-image .aligncenter>figcaption {
	margin-left: auto;
	margin-right: auto;
	display: block;
}
```

* User report: 18853515-hc

**Comment by scruffian** [comment]
Moved to Trac

**Comment by kylemcph** [comment]
Another report via 29883060-hc.

What I found was the image captions only displayed incorrectly when the image was set as to "Align center". When we changed alignment to "None", the captions displayed correctly. 

We also found that the images were displayed correctly via Firefox, but incorrectly via Chrome and Safari.

**Comment by sophiegyo** [comment]
We had another report in 4874308-zen (site was Simple, using Hemingway Rewritten)

I wasn't able to use the remove-alignment workaround, it had no effect.

I suggested making a caption-like paragraph block using superscript to make the letters smaller and raised.
