### ISSUE TITLE
Sketch: Blurry Feature GIFs on high res screens

### ISSUE THREAD

**Issue by ezebecke** [Automattic/themes#294]
## Steps to replicate

- Only monitors with high DPI.
- Chrome or Firefox
- Use portfolio feature to show projects on a page. Set the page template to "Portfolio Page Template"
- Add portfolio projects using a GIF as a feature image.

## Result

GIFs load at full resolution then it flashes and the GIF downgrades quality.
You can only see the quality downgrade if you are using a high DPI screen.

## Expected

The GIFs should maintain full resolution.

* User report: 7661729-hc
* Follow-up ticket: 1530774-zen
* User's site: [https://alietteplatiau.com/]

**Comment by laurelfulford** [comment]
Thanks for the report, @ezebecke!

Out of curiosity, could you recreate this issue with another theme? I'm not sure what Sketch would be doing that other themes wouldn't that would cause this (I'm guessing the culprit is scaling the image down, and just the odd quality of gifs).

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
