### ISSUE TITLE
Twenty Twenty: alignment can't be changed properly with RTL language

### ISSUE THREAD

**Issue by Nic-Sevic** [Automattic/themes#2941]
## Steps to replicate

1. With the site language set to English, add 2 posts that includes RTL text. 
2. Manually align the text on one post to right so it displays as intended.
3. Change the site language to Hebrew and review changes
4. Refresh Editor > 
    a. the page that now **displays correctly on the live site** (right alinged) still appears as **left** aligned in the editor 
    b. the page that **displays incorrectly on the live site** (left aligned) still appears as **right** aligned in the editor
5. If you change alignment in editor to display correctly (rtl) for post a, will no longer display correctly on live site
6. if you change alignment in editor (to left to mimic correctly displayed post) on post b, continues to display align to left
7. If you try to set page back to english and then manually change alignment to default (left aligned) then set site language back to Hebrew, content stays left aligned
    a. You can toggle the alignment settings as many times as you want here and it will continue to show aligned right

## Result

When the site is set to English and the alignment is not manually changed (i.e. left alinged) you can change the site language to Hebrew and the alignment will flip as expect.
If you manually align right while the site is set to english and then later change to Hebrew, the text will display left aligned and you cannot change it regardless of the alignment settings.

**Settings in editor:**
<img width="898" alt="editor settings" src="https://user-images.githubusercontent.com/47717887/108840087-89cc7700-75de-11eb-8c90-2253dc35f3c7.png">

**Display:**
<img width="756" alt="display" src="https://user-images.githubusercontent.com/47717887/108840105-8f29c180-75de-11eb-8489-fc3d93dc9ce7.png">

**Should display as:**
<img width="820" alt="should display as" src="https://user-images.githubusercontent.com/47717887/108840127-92bd4880-75de-11eb-8de7-8dc5457b384b.png">

## Expected

You can manually change the alignment of the text at all times, regardless of the starting position of the text or the starting language of the site.

* User report: #26521753-hc
* Follow-up ticket: #3595166-zd

**Comment by jinnypark** [comment]
Similar issue found here: #3714793-zd. 
This user specified they _did not_ change the language settings, and the site was changed to LTR 4 days ago. Is there an update on this?

**Comment by poojashetty18** [comment]
Another report on #3721011-zen

**Comment by nicelyj2** [comment]
#27620210-hc

**Comment by danieldudzic** [comment]
Hi @Nic-Sevic @jinnypark @poojashetty18 @nicelyj2 

Thank you for reporting this issue. There was an RTL bug with Gutenberg on WP.com. The fix has been deployed today, so please let me know if the issue persists.
