### ISSUE TITLE
Redhill: Custom colors do not apply to active/hover menu color on Atomic sites

### ISSUE THREAD

**Issue by lakellie** [Automattic/themes#2942]
## Steps to replicate

1. Activate Redhill on an Atomic site
2. Set custom colors in the Customizer

## Result

The red background color still appears on the menu for both the active and hover menu items: https://d.pr/i/4X1Vl2

## Expected

For the hover and active color to change, like it does on simple sites.

* User report: 3598267-zen

**Comment by jffng** [comment]
Tested and confirmed this is closed by 22-gh-Automattic/custom-colors
