### ISSUE TITLE
Runo Lite: Cookie widget cannot be dismissed on mobile

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#295]
## Steps to replicate

1. Activate theme on site
2. Make sure site is set to public
3. View in a browser on a mobile device (mobile/responsive view in browser dev tools will also work)

## Result

When clicking the Accept button on the cookie banner, the button jumps to the top of the banner and back to it's regular position, without dismissing the banner.

![cookie](https://user-images.githubusercontent.com/11873759/47774933-06910400-dcf7-11e8-952e-696c53ea3b06.gif)

## Expected

For the banner to disappear once the button is clicked.

I was able to replicate this on a test site, so it's unrelated to the site language. Also used Theme Butler to view the user's site in a different theme, and it works as it should then.

* User report: https://en.forums.wordpress.com/topic/%e9%9a%b1%e7%a7%81%e6%ac%8a%e8%88%87cookie%e7%9a%84%e9%80%9a%e7%9f%a5%e5%9c%a8%e6%89%8b%e6%a9%9f%e6%88%96%e5%b9%b3%e6%9d%bf%e4%b8%8a%e7%84%a1%e6%b3%95%e9%bb%9e%e6%93%8a%e9%97%9c%e9%96%89-privacy-and-c/
* User's site: https://iampageblog.wordpress.com/

**Edited to add:** I've explained to them this is a retired theme so this might be a wontfix.

**Comment by KokkieH** [comment]
User has changed to a different theme, but leaving this open for now.

**Comment by laurelfulford** [comment]
Thanks @KokkieH!

As you said, given that the theme is retired, and that the site has been switched to a different theme, I'm going to mark this one as `wontfix`. 

Looking at the forum thread, I don't think any followup is needed, but please let me know if that's not the case!

**Comment by KokkieH** [comment]
Thank you for looking. I agree we don't need further follow-up in this case.
