### ISSUE TITLE
Maisha: Alignfull Column Block Responsive Alignment Bug

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#2951]
## Steps to replicate

* Create a page or post that includes a Columns block that is set to `alignfull`
* Publish the page

## Result

The Column block is off-center, and the content is overflowing the viewable area of the screen:

![Maisha - Alignfull Column Block Responsive Alignment Bug - Before](https://user-images.githubusercontent.com/4000628/103417745-ed47a480-4b59-11eb-8b74-13078010337a.png)

## Expected

That the `alignfull` Column block would be shown fully in the viewable area of the screen:

![Maisha - Alignfull Column Block Responsive Alignment Bug - After](https://user-images.githubusercontent.com/4000628/103417727-dbfe9800-4b59-11eb-8b8b-b3f47e104edf.png)

This is happening because there's CSS adding a 20px margin to the right and left of the `alignfull` Column block on line 5241 of the theme's style.css that isn't contained in a media query to apply it to larger screens -- adding this CSS will resolve the issue:

```
/* fix alignfull columns block margins on smaller screens | XXXXXX-hc/zen eD */
@media screen and (max-width: 954px) {
	.wp-block-columns.alignfull .wp-block-column {
		margin-left: auto;
		margin-right: auto;
	}
}
```

* User report: 26648295-hc

**Comment by scruffian** [comment]
Moved to Trac
