### ISSUE TITLE
Broadsheet: Header date showing previous year

### ISSUE THREAD

**Issue by ajaykj** [Automattic/themes#2955]
## Steps to replicate

1. Activate Broadsheet theme on any site (premium plan or higher)
2. Visit the site

## Result

The header date shows the previous year e.g. `SATURDAY, JANUARY 2ND, 2020`

<img width="1192" alt="Markup 2021-01-02 at 19 39 39" src="https://user-images.githubusercontent.com/35197279/103459056-5f72e180-4d32-11eb-856b-f3398b845085.png">

## Expected

The header date to show the current year e.g. `SATURDAY, JANUARY 2ND, 2021`

* User report: 3615213-zd
* Follow-up ticket: #3615213-zd
* Internal discussion: p1609592298439400-slack-C03TY6J1A

**Comment by ajaykj** [comment]
It was reported by @allanftd. The issue is the following code in the theme's functions.php file:

```
/**
* Display current date.
*
* The date is localised to the sites defined language.
*/
function broadsheet_display_date() {
 
	$time = '';

 	$date_format = get_theme_mod( 'broadsheet_date_format', 'l, F jS, o' );

	if ( ! empty( $date_format ) ) {
		// Use date_i18n for localized dates.
		$time = date_i18n( $date_format );
 	}

	// Display the time.
 	if ( ! empty( $time ) ) {
		echo '<span class="header-date">' . esc_html( $time ) . '</span>';
 	}

}
```

As per [PHP date-time format](https://www.php.net/manual/en/datetime.format.php), 

> `o` = ISO-8601 week-numbering year. This has the same value as Y, except that if the ISO week number (W) belongs to the previous or next year, that year is used instead.

It seems that the first week of 2021 belongs to the previous year so the function is returning the previous year. This can be resolved by replacing `o` with `Y` in the function listed above or the following code:

```
/**
* Display current date.
*
* The date is localised to the sites defined language.
*/
function broadsheet_display_date() {
 
	$time = '';

 	$date_format = get_theme_mod( 'broadsheet_date_format', 'l, F jS, Y' );

	if ( ! empty( $date_format ) ) {
		// Use date_i18n for localized dates.
		$time = date_i18n( $date_format );
 	}

	// Display the time.
 	if ( ! empty( $time ) ) {
		echo '<span class="header-date">' . esc_html( $time ) . '</span>';
 	}

}
```

This code also needs to be updated in the following theme files:

1. customizer.php
2. headstart > en.json

**Comment by ajaykj** [comment]
Week numbers for 2021 as per Epoch Converter site:

![Markup on 2021-01-02 at 20:27:39](https://user-images.githubusercontent.com/35197279/103460028-16725b80-4d39-11eb-9cd5-6eb131735bcc.png)

**Comment by scruffian** [comment]
Thanks for this. I have moved the report to the premium themes trac, so I'll close it here.
