### ISSUE TITLE
Theme Overlay Adjustments

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#2956]
Also related to [this other issue](https://github.com/Automattic/themes/issues/2921), about consistency between Labels and Milestones on GH theme issues, it would be great if we could update how issues are created from the theme overlay screen:

![ThemeOverlay](https://user-images.githubusercontent.com/16104522/103460400-ae018b00-4cf4-11eb-9c7b-67f60265b3a9.jpg)

When clicking on the _"Create a new ticket"_ link, it seems it has the `bug` label on the URL, but it's not being added to issues since the Label changed to `[Type] Bug`.

**Comment by scruffian** [comment]
This is now fixed. We are using labels not milestones going forwards.

**Comment by carinapilar** [comment]
> We are using labels not milestones going forwards

I have a couple of questions about this. Would the _"Create a new ticket"_ link automatically add the label? It doesn't seem to be doing that. How would the process look like, would it be added by the theme's team? And we would rely on the search for the theme's name when looking for issues with it? Thanks!

**Comment by scruffian** [comment]
The "Create a new ticket" link adds the labels when they exist. At some point we should go through and add Labels for all themes, but we are expecting changes to this repo imminently, so its not been a priority.

When you click on "View open tickets" it searches for all issues with this name, so even if the label is missing, they should be found.
