### ISSUE TITLE
Headstart Annotation Missing for Fortune Theme

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#2964]
## Steps to replicate

Attempt to headstart a site with the Fortune theme and no content is added.

## Expected

I expected the demo content from https://fortunedemo.wordpress.com/ to be added to the site. Fortune is a theme with a more complicated setup and we regularly assist users with a headstart, but it hasn't been working for some time.

#26727364-hc
#20142782-hc
#25744790-hc

**Comment by donalirl** [comment]
Came up again in #17013378-hc. It seemed to add the Hever demo content! 

@ramonjd Is this something you can take a look at?

**Comment by ramonjd** [comment]
It looks like there's no headstart annotation file in `premium/fortune/inc/`

I've done this for free but not premium themes. Not sure if there's a different process.

According to PNEWy-5u2-p2 we have to lodge a ticket in the tracs repo. I tried to but I don't have access :(

cc @Automattic/theam for tips/tricks/chips/dips/code/whips

**Comment by ramonjd** [comment]
Just for fun I tried to generate the annotation myself according to these instructions PNEWy-7BG-p2 but received a ton of errors, and the process failed. Mainly `Convert the content to block editor format.` 🤷 So we might have to lean on the themes dev crew for this one.

**Comment by scruffian** [comment]
This is a premium theme so we should ask the Theme Shop to do it

**Comment by ianstewart** [comment]
> This is a premium theme so we should ask the Theme Shop to do it

I'm not sure if they have access to the same scripts as Automatticians. If so, they'd be unable to do this.

>  Mainly Convert the content to block editor format.

I'd wager that what's missing is clicking "convert to blocks" on posts and pages in the theme demo.

**Comment by kwight** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/52757
