### ISSUE TITLE
Resonar: Sidebar Toggle Empty with Cookies and Consent Widget

### ISSUE THREAD

**Issue by scosgro** [Automattic/themes#297]
## Steps to replicate

Theme: Resonar

1. Customize
2. Widgets - +Add a Widget - Cookies and Consent Banner
3. Make sure that the only widget added is the Cookies and Consent Banner widget.
4. Publish changes.
5. Visit site and click on Sidebar toggle (three dots to the right of the menu in the top right corner).

## Result

The sidebar toggle appears because a widget has been added, but since the cookies and consent widget doesn't add content, the sidebar is a giant white screen that covers up the homepage without any content on it.

Sidebar not toggled: https://cloudup.com/cXXUfrKlIUT
Sidebar toggled: https://cloudup.com/cwVYDiLLs5p

## Expected

Widgets that provide function instead of content, or provide content outside of the widget location (like the Cookies and Consent Banner), shouldn't trigger the sidebar toggle if they're the only widget added.

With no widgets added, the toggle does not appear. 

* User report: #1540171-zd 
* Follow-up ticket: #1540171-zd  
* User's site: https://hanasmith.co.uk/

**Comment by laurelfulford** [comment]
Whatever fix we go with here, we should also use for the Mailchimp widget, which would cause the same issue.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
