### ISSUE TITLE
Rockfield: Button styles bleeding into launch banner

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2970]
Button styles appear to be bleeding into the launch banner …

![image](https://user-images.githubusercontent.com/545779/103694932-59af1300-4f61-11eb-9111-cd70965170e6.png)

… producing these disparate button styles.

![image](https://user-images.githubusercontent.com/545779/103694983-69c6f280-4f61-11eb-9898-22c6ec1556bb.png)

**Comment by simison** [comment]
I'll grab this to Create focus from Theme team, I think it's best to harden the button styles in the banner against themes leaking to it.

**Comment by Addison-Stavlo** [comment]
Fix for the launch banner button at D56656-code.

**Comment by Addison-Stavlo** [comment]
Fix is live, so it should be back to normal now:

![Screen Shot 2021-02-08 at 4 58 54 PM](https://user-images.githubusercontent.com/28742426/107286729-f8ca9d00-6a2e-11eb-9f0f-4e84fa7ec20f.png)

Noting any styles that are not specifically defined for these buttons (like in this case `outline`) may bleed through from themes defining more global button css.  Most styles should be taken care of, but if there are future issues we should be able to fix them with definitions in the launch banner css.
