### ISSUE TITLE
Varia Themes: Incorrect Front-End colours with Cover, Headings, and Background Images, without Opacity

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2971]
## Steps to replicate

1. Visit wp.com/new
2. Select the "Reynolds" design featured there (see screenshots below) which uses the "Rockfield" theme
3. Create a new site
4. Compare the front end of site with editor

Or …

Paste the following sample block content into the code editor view a test site.

```
<!-- wp:cover {"url":"https://iantesting363831624.files.wordpress.com/2021/01/pexels-photo-5383782.jpeg","id":23,"dimRatio":0,"align":"full"} -->
<div class="wp-block-cover alignfull" style="background-image:url(https://iantesting363831624.files.wordpress.com/2021/01/pexels-photo-5383782.jpeg)"><div class="wp-block-cover__inner-container"><!-- wp:heading -->
<h2>This is a heading in a cover block</h2>
<!-- /wp:heading --></div></div>
<!-- /wp:cover -->
```

- Cover Block with image background
- Heading inside
- Overlay opacity at 0

## Result

**Editor view of cover block**

![image](https://user-images.githubusercontent.com/545779/103695695-b232e000-4f62-11eb-99b4-5277bffaecdc.png)

**Front-end view of cover block in Rockfield**

![image](https://user-images.githubusercontent.com/545779/103695771-cf67ae80-4f62-11eb-89bd-4d58f3806dd6.png)

**Front-end with Maywood**

![image](https://user-images.githubusercontent.com/545779/103695879-fd4cf300-4f62-11eb-89b0-202e32d4580c.png)

**Front-end with Shawburn**

![image](https://user-images.githubusercontent.com/545779/103695916-0fc72c80-4f63-11eb-883d-1b6352983d9a.png)

## Expected

**Front-end with Seedlet**

![image](https://user-images.githubusercontent.com/545779/103696016-400ecb00-4f63-11eb-99e0-4575188b089b.png)

**Front-end with Spearhead**

![image](https://user-images.githubusercontent.com/545779/103696066-587ee580-4f63-11eb-9b6d-b007ec578244.png)

**Front-end with Twenty Twenty**

![image](https://user-images.githubusercontent.com/545779/103696133-73e9f080-4f63-11eb-8539-66bdc6a288e9.png)

**Sample block content result in Maywood**

![image](https://user-images.githubusercontent.com/545779/103711595-6f323600-4f7d-11eb-8517-89f4dfd853d3.png)

**Comment by ianstewart** [comment]
Updated the reproduction instructions with some sample content that I think isolates the issue.

**Comment by simison** [comment]
@scruffian I couldn't replicate this anymore, did it get fixed?

**Comment by scruffian** [comment]
It's possible. We've fixed a few Varia bugs this week, so this one might have been fixed accidentally. Maybe @ianstewart could confirm?

**Comment by ianstewart** [comment]
I could replicate this today in a PR that added some of the patterns above back into wp.com/new. Not sure now if theme issue or wp.com/new issue with the PR that added the patterns back.

**Comment by simison** [comment]
@scruffian would there be any estimation on when this could be fixed? It's pretty longstanding bug that forced us to remove one of the designs from wpcom. You can replicate here: https://github.com/Automattic/wp-calypso/pull/49608
