### ISSUE TITLE
Site title and tag line properties do not appear in browser tabs

### ISSUE THREAD

**Issue by charliescheer** [Automattic/themes#2972]
## Steps to replicate
I am not sure if this was intentional or not, but with the Moka theme, when you set the site title and tagline they do not appear in the browser tab.  What continues to be there is the site address

For most themes I have setup they show the title/tagline instead of the address, and it would be nice if this theme did the same.

To test:
Set a site to the Moka Theme
Confirm in the customizer that your site has set the title and tagline

## Result
When the site is visited, in the browser tab you will see the url

## Expected

I would expect that you will see the title and tag line

**Comment by scruffian** [comment]
Moved to Trac
