### ISSUE TITLE
Eris theme: Gallery post format results in no featured image

### ISSUE THREAD

**Issue by selectedselections** [Automattic/themes#2974]
## Steps to replicate

1. Create a new blog post 
2. Assign the gallery format: https://d.pr/i/xKSOJ9
3. Add a gallery block to the post
4. Add a featured image to the post
5. No featured image is displayed on the blog page 

## Result

There is no gallery icon (as shown in the theme demo here: https://d.pr/i/CW240L ) and there is also no featured image displayed within the blog page. 

This is how my test site displays this: https://d.pr/i/BvrfPP

A user reported this, and they are using the classic block with a gallery added to it on their site (as the theme demo site uses for a gallery format post: https://d.pr/i/vluEck ) which results in the gallery being shown as the featured image instead 

## Expected

I expected the "Gallery" post format to be honored here and for the gallery icon and a singular featured image to be displayed on the blog page as shown within the theme demo for the "Photography at its Highest" post here: https://erisdemo.wordpress.com/blog/

* User report: #3624123-zd
* Follow-up ticket: #3624123-zd

**Comment by scruffian** [comment]
Moved to Trac
