### ISSUE TITLE
Business: Mailto links in social icons menu shows link icon, not envelope icon

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/themes#298]
## Steps to replicate

1. Create a new menu.
2. Add a custom link menu item with a mailto link in the URL.

## Result

A link icon appears on the site.

## Expected

I would expect an envelope icon similar to what appears on other themes. Is this expected?
Discussed in p1541277861205700-slack-themes

* User report: #1539729-zen
* User's site: https://mancelos.com/

**Comment by alaczek** [comment]
This is fixed now. Initially we implemented a custom social menu, but it has been switched to Jetpack social menu.
