### ISSUE TITLE
Twenty Twenty One: Fix Comment form for wpcom

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2982]
## Steps to replicate

On Wordpress.com open a single post page and click on the comments textarea

## Result

<img width="713" alt="Screenshot 2021-01-07 at 15 12 36" src="https://user-images.githubusercontent.com/3593343/103909041-80a54a80-5103-11eb-98ef-732db1dba575.png">

## Expected

Expected a similar style as Twenty Twenty shows:

![](https://d.pr/i/HkiweV+)

**Comment by MaggieCabrera** [comment]
The diff to test this is here: D55006-code

**Comment by MaggieCabrera** [comment]
The fix looks like this, maybe @melchoyce or @kjellr you have any opinions about this?

<img width="755" alt="Screenshot 2021-01-07 at 17 02 58" src="https://user-images.githubusercontent.com/3593343/103924560-7d678a00-5116-11eb-8b69-d79a083053f0.png">

<img width="401" alt="Screenshot 2021-01-07 at 18 31 17" src="https://user-images.githubusercontent.com/3593343/103924596-8d7f6980-5116-11eb-92a7-5fa51fe680ac.png">

**Comment by scruffian** [comment]
This was fixed in r57562-wpcom-themes
