### ISSUE TITLE
Multiple Themes: Global Styles fonts are not loading until the page is refreshed

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#2989]
This seems to be a problem with many themes — I've tried Seedlet, Varia (and a few of their child themes). When you select new fonts via global styles, the change is not reflected in real time: 

![Kapture 2021-01-08 at 08 59 53](https://user-images.githubusercontent.com/1202812/104023773-21414c00-5190-11eb-807f-584d9987abdf.gif)

When you save you setting and refresh the page, the font has been updated. But there's no way to preview the change before you save it anymore. 

Not sure if this is a theme problem or a Global Styles problem, but logging here to start.

**Comment by kjellr** [comment]
In case it's related: we encountered this problem when we began implementing Seedlet, and @jffng [solved it by changing the way the variables were enqueued](https://github.com/Automattic/themes/pull/2217#pullrequestreview-444214897). I'm not sure that's relevant here though, since it's effecting Varia themes too.

**Comment by pbking** [comment]
This should be fixed by https://github.com/Automattic/wp-calypso/pull/49216
