### ISSUE TITLE
Didi: Form Block phone field 

### ISSUE THREAD

**Issue by silvio-meter** [Automattic/themes#2990]
## Steps to replicate

1. Activate the Didi theme
2. Create a new page and added the Form Block (make sure that you add the phone field)

## Result

The phone field inside the Contact Form looks different from other fields.

Screenshot:

![Optional alternative text if image doesn't load](https://testsite257com.files.wordpress.com/2021/01/screenshot-on-2021-01-08-at-15_42_39.png)

Temporary CSS fix:

```
input[type="tel"] {
	background: transparent;
	border: unset;
	border-bottom: 2px solid black;
}
input[type=tel]:focus {
	border-width: 4px;
	outline: none;
}
```

## Expected

The phone field should look similar to other fields inside the Form block.

* User report: [#26866933-hc]

**Comment by scruffian** [comment]
Moved to Trac
