### ISSUE TITLE
Coutoire: Unexpected results in Colour Schemes for Cover Block Overlay

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2994]
## Steps to replicate

1. Visit WP.com/new and select the Bowen design
2. Create a site.
3. Compare the cover block colour styles in the Editor vs the Front-End

## Result

![image](https://user-images.githubusercontent.com/545779/104060558-b2c6b300-51bc-11eb-89bf-e187251ec164.png)

## Expected

The Editor style colours to match the front-end.

**Comment by pbking** [comment]
I was just poking around in #2994 (not enough to know what’s up really) but I noticed that “background” and “foreground” as {background} colors work as expected, however if I use “primary” or “secondary” as {background} those values do NOT work as expected.

**Comment by pbking** [comment]
The classes for "primary" and "secondary" aren't present in the view.
(And due to the known bug of the color/background-color ALWAYS being applied as a style all 4 colors work in the editor even without the necessary classes).
