### ISSUE TITLE
Promenade: TABLE block column widths don't adjust

### ISSUE THREAD

**Issue by kaitohm** [Automattic/themes#2997]
A user has reported the same issue as https://github.com/Automattic/themes/issues/1383 , but happening on theme Promenade.

## Steps to replicate

1. Create a new table with cell data of varying widths
2. Publish

## Result

The columns in the table do not respect the widths of the data inside them, even with 'fixed width table cells' disabled in the table block settings.

## Expected

I expected the column widths to conform to the data inside.

## Workaround

Adding the following CSS fixes the issue:

> table{
 table-layout: auto; 
}

User report: 25903091-hc

**Comment by scruffian** [comment]
Moved to Trac
