### ISSUE TITLE
Twenty Eleven: Custom background option disappeared

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#2998]
## Steps to replicate

1. Enable Twenty Eleven
2. Visit the Customizer and click on Colors and Backgrounds

## Result

I only see options to change custom colors on the site. The option for a custom background the theme used to have has disappeared. On sites that had a custom background image set, it has apparently disappeared, as per the user report.

## Expected

To be able to set a custom background image as before.

* User report: https://wordpress.com/forums/topic/my-background-image-disappeared/

Ping @danieldudzic, as it appears you made some changes to this theme a few hours ago.

**Comment by scosgro** [comment]
Another report in #3635208zd

**Comment by scosgro** [comment]
Another report in 3636008zd. This user had a specific background color that got erased, and replaced with Palettes only.

**Comment by danieldudzic** [comment]
Hi @KokkieH & @scosgro,

Thanks for reporting.

My bad indeed. Apologies! - it should be fixed now.
