### ISSUE TITLE
Wanderer: Centered YouTube Block Aligns to the Left

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#3000]
## Steps to replicate

1. Activate the Wanderer theme.
2. Add the YouTube block and center it.
3. Observe the result in the front-end.

## Result

The video is left-aligned.

## Expected

The video is centered.

* User report: #26900699-hc
* Follow-up ticket: 3637032-zd-woothemes

## Possible workaround

Add the Columns block with three columns and move the YouTube block into the middle column.

**Comment by scruffian** [comment]
Moved to Trac

**Comment by danieldudzic** [comment]
This has been fixed now.
