### ISSUE TITLE
Eris Theme: Featured Content Slider Not Visible In Customizer

### ISSUE THREAD

**Issue by theabhig** [Automattic/themes#3002]
## Steps to replicate

1. Open Design > Customize > Customizer from WordPress.com account (https://d.pr/free/v/hQGXxc)

## Result

Blank space shows on page where 'Featured' slider should load. The slider content still works and is clickable, but is not visible on the page. (https://d.pr/free/i/KKU1Po)

Possible javacript issue (Javascript console errors: https://d.pr/free/i/oZ99Ug)

## Expected

The slider should still be visible in the customizer screen. 

* User report: #3624123-zd
* Follow-up ticket: #3624123-zd

**Comment by scruffian** [comment]
Moved to Trac
