### ISSUE TITLE
Eris Theme: Posts tagged as featured that should not be displayed still show in portfolio

### ISSUE THREAD

**Issue by theabhig** [Automattic/themes#3003]
## Steps to replicate

1. Upload portfolio item and tag it as 'featured' so it displays in theme's featured slider
2. Uncheck box that says "Also display tagged posts outside the Featured Content area."
3. Review portfolio further down on page. No posts tagged to be in featured content should show up.

## Result

Featured content continued to show in portfolio. 
Vider: https://d.pr/free/v/VpXYEt
Screenshot: https://d.pr/free/i/VS8hNn

## Expected

Posts tagged as featured should no longer be visible in the home page portfolio.

* User report: #3624123-zd
* Follow-up ticket: #3624123-zd

**Comment by scruffian** [comment]
Moved to Trac
