### ISSUE TITLE
Eris: Image Comparison block breaks with "split layout" portfolio setting

### ISSUE THREAD

**Issue by xpurichan** [Automattic/themes#3009]
## Summary

If we enable Eris' "Display single project in Split Layout" portfolio setting it creates a conflict which doesn't allow the [Image Compare block](https://wordpress.com/support/wordpress-editor/blocks/image-compare-block/) to work, and it will instead show the two images from this block one above the other and with no comparison feature.

## Steps to replicate

1. Visit https://wordpress.com/settings/writing/ and enable the "Portfolio Projects" content type.
2. Visit the theme customizer.
3. Go to: Theme Option > Portfolio Layout Settings.
4. Check/enable the "Display single project in Split Layout" option, and save.
5. Create a new portfolio project.
6. Add the Image Compare block with two images in it.
7. Use the Image Compare block's settings to set the orientation setting to "Side by Side".
8. Note how the image compare block functions properly in the editor.
9. Preview the page and note that, with the split layout, the theme doesn't load the block properly. Instead it loads images one above the other with no "comparison" feature.
10. If you now go back to step 4 and disable the "Display single project in Split Layout" setting then you can return to your test page and find the Image Compare block working properly.

Screenshot from step 8:
![Screen Shot 2021-01-12 at 10 37 10 AM](https://user-images.githubusercontent.com/33190975/104344132-6633ee00-54c2-11eb-9a17-03913059e7d5.jpg)

Screenshot from step 9:
![Screen Shot 2021-01-12 at 10 37 25 AM](https://user-images.githubusercontent.com/33190975/104344144-69c77500-54c2-11eb-88e7-ceaabc9922de.jpg)

Screenshot from step 10:
![Screen Shot 2021-01-12 at 10 38 42 AM](https://user-images.githubusercontent.com/33190975/104344172-6f24bf80-54c2-11eb-93bb-8399be607a01.jpg)

## Result

Using the "Display single project in Split Layout" setting and creating an image comparison on a portfolio page conflicts, resulting the in the image comparison block displaying incorrectly and not functional.

## Expected

The image comparison block should work the same in preview mode as it does when we're in the editor.

--

* User report: 3624123-zd
* Follow-up ticket: 3624123-zd

**Comment by scruffian** [comment]
Moved to Trac
