### ISSUE TITLE
Seedlet: Subscription form block's text input does not stretch all the way to the button

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3012]
In the front end, the WP.com Subscription Block's text input field does not stretch all the way to the button. The border and text color for the form field do not match either. The appearance in the editor seems correct. 

## Screenshots

Front end: 

![Screen Shot 2021-01-12 at 3 32 14 PM](https://user-images.githubusercontent.com/1202812/104369417-6d232680-54eb-11eb-8999-e784605acc94.png)

Editor: 

![Screen Shot 2021-01-12 at 3 34 03 PM](https://user-images.githubusercontent.com/1202812/104369549-9ba10180-54eb-11eb-85d0-437999d51002.png)

**Comment by jffng** [comment]
I believe this is related to #2913. I will try to address both issues at once.
