### ISSUE TITLE
Spearhead/Blank Canvas: Non-wpcom custom colors implementation has no effect.

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3016]
When testing locally or on a self-hosted site, these themes inherit Seedlet's custom colors implementation. Unfortunately, the default colors are incorrect, and changing them has no effect on the site. 

To test: 

1. Load Spearhead or Blank Canvas on a self-hosted site.
2. Open Customizer > Colors.
3. Select "Custom"
4. Note that the colors there are from Seedlet.
5. Modify the colors. Note that this has no effect on the preview on the right. 

## Screenshot

![Screen Shot 2021-01-13 at 8 09 15 AM](https://user-images.githubusercontent.com/1202812/104456556-d7cd7400-5576-11eb-8853-376cbdba786c.png)

**Comment by scruffian** [comment]
This might be fixed by #2701

**Comment by scruffian** [comment]
I think this was fixed by #2701. If it's still an issue please reopen.

**Comment by supernovia** [comment]
This still seems to be an issue on my .org instance with a fresh copy of Spearhead today.

**Comment by pbking** [comment]
I tested this and the only portions of the Spearhead that I was unable to customize were the BACKGROUND color of Sticky Posts (and other elements referenced in #3105).  I opened #3199 to address that shortfall (#3105 addressed it for the .com color customizer, #3199 should address it for .org)

I evaluated the fix in both LIGHT and DARK mode.  

All other aspects of Spearhead color customizations were working as expected for me.

**Comment by scruffian** [comment]
I think there's still more work needed here. When I load spearhead color settings they are still the Seedlet colors:

<img width="317" alt="Screenshot 2021-02-09 at 12 20 04" src="https://user-images.githubusercontent.com/275961/107362801-26682280-6ad1-11eb-949c-0ed080561986.png">
