### ISSUE TITLE
Verity: Submenu items do not appear fully when longer page/menu titles are used with Site Layout set to Full Width

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/themes#3023]
## Steps to replicate

* Activate the Verity theme for the site.
* In Design > Customize > Theme Options > Site Layout, choose Full Width. Box Layout seems to have no issues though.
* Create menus with longer titles so the menus bar will appear below the site title (by default the menu with shorter titles appears to the right of site title).
* Add submenus to the first menu item.
* Now visit the site and try to access the submenu for the first menu item.

## Result

* Part of the submenu, hides behind the screen. ([Screenshot](https://d.pr/i/Cexsbw))

## Expected

* The submenu should have appeared fully making the menu labels readable.

* User report: #26126096-hc
* Follow-up ticket: #3648395-zd

**Comment by scruffian** [comment]
Moved to Trac
