### ISSUE TITLE
Seedlet: Full-width YouTube embeds do not appear full-width in the front end. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3032]
Potentially a problem with [responsive embeds](https://developer.wordpress.org/block-editor/developers/themes/theme-support/#responsive-embedded-content)? 

## Steps to replicate

1. Add a YouTube embed. 
2. Make it Full-width.
3. Note that it looks correct in the editor.
4. View the post on the front end, note that the video is small and in the upper left corner of where it should be. 

## Screenshots

Editor

![Screen Shot 2021-01-14 at 5 36 08 PM](https://user-images.githubusercontent.com/1202812/104657592-371ea780-568f-11eb-9799-89c2eee8ca40.png)

Front End

![Screen Shot 2021-01-14 at 5 35 52 PM](https://user-images.githubusercontent.com/1202812/104657596-39810180-568f-11eb-9f1a-6714f9d7137f.png)

**Comment by arcangelini** [comment]
Looks like this was fixed with a recent PR. Should be resolved on WPCOM with version bump?

**Comment by kjellr** [comment]
Yes, this appears to be fixed now. 👍
