### ISSUE TITLE
Blank Canvas: Built in optional opt-in for header and footer areas on single post pages. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3033]
Allow users to opt-in to having a header and footer area. This would let users grow with the same theme, rather than forcing them to switch when they want that functionality. 

I envision this as a customizer opt-in control that we could add post launch.

**Comment by kjellr** [comment]
Here's how I think this should work: 

The theme should have a new customizer option. Not sure where it should live... maybe Content Options? Here's a draft of what we should show: 

![Screen Shot 2021-01-25 at 9 45 33 AM](https://user-images.githubusercontent.com/1202812/105721012-1574ba00-5ef2-11eb-8261-9a836d419045.png)

Basically, these should each revert things back to what Seedlet does by default for each of these areas. But here's a more technical list:

### Show post and page titles.

These are not currently rendered by the theme. If this option were active, we would need to add code to display them in `page.php` and `single.php`. Regardless of the setting here, I suggest we continue removing the ["Hide Front Page Title" setting](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/inc/wpcom.php#L10-L16) to avoid confusion. 

### Enable site header and navigation. 

Checking this box should: 

- Adjust `header-content.php` so that it adds the site logo, site tagline, header navigation, and social links navigation areas to all header templates. (basically, it needs to reproduce the 
- Register the `primary` and `social` [nav menu areas](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L78-L81). 
- Enqueue the [Seedlet nav scripts and styles](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L85-L94). 
- Show the [menus section](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L109-L110) in the customizer. 
- Remove [the customizer message](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L124-L125) and [custom stylesheet](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L171-L177) used in the site branding display options.

### Enable site footer menu and widgets. 

Checking this box should: 

- Adjust `footer-content.php` so that it adds the widgets and footer navigation areas to all pages.
- Register the `footer` [nav menu area](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L78-L81). 
- Show the [menus section](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L109-L110) in the customizer if it isn't already shown. 
- Add [theme support back in](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L76) for `customize-selective-refresh-widgets`. 
- [Register the widgets area](https://github.com/Automattic/themes/blob/2cb6e3efbd7390d418effbebda4ea259e329465b/blank-canvas/functions.php#L96-L102).

**Comment by scruffian** [comment]
I think this means we'll need to always show the Menus section in the customizer. If we try to manage the visibility of that section based on the selection of the header/footer visibility users will need to reload the customizer to make the menus show.
