### ISSUE TITLE
Twenty Twenty One: Reduce Page Title size on Mobile

### ISSUE THREAD

**Issue by noteeth** [Automattic/themes#3036]
## Steps to replicate

Activate Twenty Twenty One theme.  Open a page on mobile screen.

<img width="293" alt="Screen Shot 2021-01-12 at 7 11 18 PM" src="https://user-images.githubusercontent.com/16570939/104668665-603e3880-568d-11eb-8eeb-66bd24c083e6.png">

## Result

Page title takes up half of the initial screen

## Expected

Anticipating user's may expect a smaller title.  It would be nice to have the page title height reduced a bit for mobile screens.

**Comment by scruffian** [comment]
@melchoyce any thoughts on this one?

**Comment by melchoyce** [comment]
I'd be cool with something like https://css-tricks.com/fitting-text-to-a-container/, but I don't think I'd want to otherwise change it.

**Comment by scruffian** [comment]
I think we should close this and see if we get any requests from users about this. Thanks for raising it @noteeth.
