### ISSUE TITLE
Varia: css variable approach to color annotations

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#3038]
Implement the same approach to color annotations used in https://github.com/Automattic/themes/pull/3025 

Move the javascript file that handles color annotations from Hever to Varia as suggested by this comment: https://github.com/Automattic/themes/pull/3025#discussion_r558140479

Make sure that Hever is inheriting correctly from Varia and the color annotations work for both themes so we can start rolling these changes to the rest of the themes missing color annotations.

**Comment by scruffian** [comment]
Hopefully this will also address: 
#2895
#2896

**Comment by scruffian** [comment]
Slight change of plan here - let's just add color annotations using CSS variables for the 5 varia themes that don't have them:

Rockfield, Shawburn, Stratford, Morden and Stow

**Comment by scruffian** [comment]
Still todo: Stratford, Shawburn and Morden

**Comment by scruffian** [comment]
Done!
