### ISSUE TITLE
Natural: Video block mobile height issue

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#3040]
Videos added with the Video block are not responsive in the Natural theme, resulting in the videos being too tall on mobile.

## Steps to replicate

* Activate Natural
* Add a Video block, no extra settings
* View video on small screens

![https://d.pr/i/cqOWkC](https://d.pr/i/cqOWkC+)

## Result

The video height is not responsive:

![https://d.pr/i/NcIqK0](https://d.pr/i/NcIqK0+)

## Expected

The video height should be responsive on all browser widths. Varia does this correctly:

![https://d.pr/i/AzQSuY](https://d.pr/i/AzQSuY+)

* User report: 27025529-hc
* Follow-up ticket: 3652193-zd-woothemes

**Comment by scruffian** [comment]
Moved this to Trac. Closing...
