### ISSUE TITLE
Aquene: Customizer hide Author Bio doesn't work

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#3041]
There is an option to hide the Author Bio on single posts within the Customizer via  **Content Options > Author Bio >  Display on single posts**. This feature doesn't actually hide the bio on single posts.

## Steps to replicate
* Activate Aquene
* Shut off the option in the Customizer
* View post

![https://d.pr/i/iep2eu](https://d.pr/i/iep2eu+)

## Result

Author bio is still visible:

![https://d.pr/i/i45vac](https://d.pr/i/i45vac+)

## Expected

Should be removed. We used this as a solution:

```
.entry-author {
  display: none;
}
```

* User report: 27026714-hc

**Comment by scruffian** [comment]
Moved to Trac
