### ISSUE TITLE
Independent Publisher 2: Images are no longer wide since version 2.1.10

### ISSUE THREAD

**Issue by devNigel** [Automattic/themes#3048]
Since the latest update to version 2.1.10, the images added on the editor are missing the class `size-big`. This is a breaking change for users who chose this theme for its wider image width.

## Steps to replicate

* Go to Editor, switch to Classic Block and add an image.
* The image should be having class `size-big` that made it a little wider than normal.

The latest commit ac4759d shows that code related to the addition of class `size-big` was removed.

## Result

Images are no longer wider.
![](https://cdn-std.droplr.net/files/acc_1121510/gxSqvw)

## Expected

Screenshot from web.archive.org on how it used to look: 

![](https://cdn-std.droplr.net/files/acc_772785/nRuTOM)

* User report: #24125801-hc
* Follow-up ticket:  #3654498-zen

**Comment by scruffian** [comment]
@sgomes are you able to look at this?

**Comment by sgomes** [comment]
Thank you for looping me in, @scruffian! This is probably a bug introduced by my code. Investigating.

**Comment by sgomes** [comment]
This should be a simple fix: #3055. Please double-check that it's working correctly!

**Comment by scruffian** [comment]
@sgomes did you deploy this too?

**Comment by sgomes** [comment]
@scruffian Yes, I submitted and deployed (57632). The fix should be live and working 👍

**Comment by scruffian** [comment]
Great, thank you :)
