### ISSUE TITLE
Promenade: Bottom Border in Header Overlays Featured Images

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/themes#3049]
**Steps to replicate**
In a Premium Plan Site with the Promenade Theme Active
Create a new Page, add a Title and a Featured Image
Publish
Result
The Bottom Border below the Page Title header will overlay the featured image. 

**Expected**
I expected the header bottom border to not show, or to be on top of the image. 

![screenshot](https://d.pr/i/RBcE60+)
[Direct Link](https://d.pr/i/RBcE60)

**Workaround**
Adding the following CSS fixes the issue by removing the bottom border:

header.entry-header {
  border-bottom: none !important;
}

#3655302-zd

**Comment by scruffian** [comment]
Moved to Trac
