### ISSUE TITLE
Opti: Verse, Preformatted and Code blocks cannot be edited in Safari

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#3051]
## Steps to replicate

1. Activate the Opti theme
2. Add one of these blocks: _Verse_, _Preformatted_ or _Code_
3. Try to add content to the block

## Result

It is not possible to click to the block, not add any content into it. The block has a dark background in the editor.

![Screen Capture on 2021-01-18 at 10-43-21](https://user-images.githubusercontent.com/25105483/104898525-0afa7380-597a-11eb-9717-3fd704ead87f.gif)

## Expected

It is possible to use the block, add content to it. Also, I believe that the block should have white background - as it has in the front-end.

Browser version where we were able to reproduce the issue: Safari 14.0.2 (16610.3.7.1.9)
I could reproduce the issue in Safari only, but the user mentioned that the issue is present in their Chrome as well.

* User report: 27082381-hc
* Follow-up ticket: 3659358-zd-woothemes

**Comment by scruffian** [comment]
Moved to Trac.

**Comment by danieldudzic** [comment]
This has been now fixed!

**Comment by ivan-ottinger** [comment]
I have informed the user.
