### ISSUE TITLE
Luxury: Pricing Table block is broken

### ISSUE THREAD

**Issue by hacchism** [Automattic/themes#3059]
## Steps to replicate

1. Create a page and add a Pricing Table block.
2. Avoid using "One Pricing Table". Instead, use Two or Three or Four.
3. Click Preview.

## Result

It shows up with one column:

![Screen Shot on 2021-01-19 at 11:26:30](https://user-images.githubusercontent.com/32432463/104980135-3bf5a980-5a49-11eb-9b61-218ac18cf832.png)

## Expected

Expected it to show items side by side:

<img width="713" alt="Screen Shot 2021-01-19 at 11 27 49" src="https://user-images.githubusercontent.com/32432463/104980215-6a738480-5a49-11eb-9709-376dc9b2191b.png">

* User report: #27100737-hc

**Comment by hacchism** [comment]
## The CSS code I used as a workaround:

```
@media (min-width: 600px) {
.has-columns.has-2-columns>*:not(.block-editor-inner-blocks) {
          flex-basis: 42%;
     }
}
```

**Comment by scruffian** [comment]
Moved to Trac. Closing...
