### ISSUE TITLE
Restaurant: WooCommerce Shopping Cart Does Not Display on Mobile

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/themes#3077]
## Steps to replicate
1. Activate the Restaurant Theme.
2. Install and activate the WooCommerce plugin
3. Visit site from mobile device

Tested on iPhone 11 Pro in Safari — iOS 14.3. Also tested in Google Chrome 87's responsive mode on macOS 10.15.7.

## Result

The WooCommerce shopping cart icon is not visible in the header

## Expected

The WooCommerce shopping cart icon should be visible near menu

* User report: 27121611-hc
* Follow-up ticket: 3667626-zd-woothemes

**Comment by scruffian** [comment]
Moved to Trac
