### ISSUE TITLE
Canard: Blog Posts block - "Show Author" settings doesn't work as expected

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#3080]
## Steps to replicate

1. Activate the _Canard_ theme.
2. Add a _Blog posts_ block.
3. Enable the _Show Author_ setting.

## Result

Author name is displayed in the editor, but not in the front-end.

Backend:

![Markup on 2021-01-21 at 16:07:28](https://user-images.githubusercontent.com/25105483/105369472-dfd68500-5c02-11eb-92e9-def88f52a241.png)

Front-end:

![Markup on 2021-01-21 at 16:07:08](https://user-images.githubusercontent.com/25105483/105369505-e95fed00-5c02-11eb-9f19-c90558430261.png)

## Expected

Author name should be displayed in the front-end as well.

* User report: 27165309-hc
* Follow-up ticket: 3669607-zd-woothemes

**Comment by cecilearkay** [comment]
I think it goes beyond that, there must be some setting somewhere that's preventing the meta elements to be hidden. In my case, the user's front page is set to latest blog posts, like in the demo, as opposed to your case where you add the _Blog Posts_ block to a page.

If you look in the CSS any post is set to have `display:none` on several on the entry meta:

**Sticky posts:**
<img width="378" alt="Screenshot 2022-04-13 at 10 56 30" src="https://user-images.githubusercontent.com/16645645/163141442-94f6034a-e20f-443f-b1d0-f16457110e62.png">

**Regular posts:**
<img width="417" alt="Screenshot 2022-04-13 at 10 57 34" src="https://user-images.githubusercontent.com/16645645/163141530-91e6e938-2729-49bb-93d1-8ee32c6b44f2.png">

There's also this CSS that may be getting in the way:
<img width="406" alt="Screenshot 2022-04-13 at 10 58 12" src="https://user-images.githubusercontent.com/16645645/163141576-7441e404-a59b-476c-9a4f-81c839ecca79.png">

I checked the logs quickly for the theme and I couldn't find anything that would cause the issue - especially when it's working fine on the demo site for Canard (https://canarddemo.wordpress.com/):

<img width="963" alt="Screenshot 2022-04-13 at 11 10 46" src="https://user-images.githubusercontent.com/16645645/163146939-94462023-c789-4302-afdb-13d70d29ba02.png">

My thinking is maybe `display:none` was expected for Sticky posts? And that it got applied everywhere?

Edit: kudos to @kettultim for the detective work!

**Comment by ivan-ottinger** [comment]
That's a good find!

I looked into the Canard theme `style.css` CSS and there's this section (reflecting the same CSS class visible in one of your screenshots):

```css
1957 .byline, 
1958 .updated:not(.published) { 
1959 	display: none; 
1960 }
```

That's probably the root cause hiding the byline section from the places where it shouldn't be applied.

**Comment by mikachan** [comment]
Fixed by https://github.com/Automattic/themes/pull/5981
