### ISSUE TITLE
Anemone: Custom fonts not applying to Recent Posts widget

### ISSUE THREAD

**Issue by benchilcote** [Automattic/themes#3081]
## Steps to replicate

1. Add a Recent Post widget to the sidebar
2. Change both the base font and heading font to a custom font
3. Publish the changes

<img width="1364" alt="Screen Shot 2021-01-21 at 10 21 18" src="https://user-images.githubusercontent.com/11636210/105372330-78551100-5bd3-11eb-9b1b-d85a62106479.png">

## Result

The post titles in the Recent Post widget do not change to reflect either custom font.  It is displayed in a default Times font

<img width="1269" alt="Screen Shot 2021-01-21 at 10 22 09" src="https://user-images.githubusercontent.com/11636210/105372363-8440d300-5bd3-11eb-863e-3f8e033e06d6.png">

## Expected

I would expect the Custom Heading Font setting to be applied to the post titles.  This is the case for the Anemone: Post List widget, but not the Recent Post widget

<img width="1334" alt="Screen Shot 2021-01-21 at 10 23 15" src="https://user-images.githubusercontent.com/11636210/105372533-af2b2700-5bd3-11eb-9d43-f14c2f376f50.png">

* User report: #18459839-hc
* Follow-up ticket: #3669626-zd

**Comment by scruffian** [comment]
Moved to Trac
