### ISSUE TITLE
Independent Publisher 2: YouTube Block Not Rendering properly

### ISSUE THREAD

**Issue by annbingle** [Automattic/themes#3085]
## Steps to replicate

The user is trying to embed YouTube videos in Grid format on their Homepage.

They are adding Youtube embed block within the Columns block but it will not render properly on the livesite.

Steps to replicate.
1. Open a page, add a columns block.
2. Within the columns in columns block add a Youtube embed block and click on Embed.

## Result

1. Once added, here's how it will look like.
<img width="967" alt="Screen Shot on 2021-01-22 at 06-07-54" src="https://user-images.githubusercontent.com/40605613/105421633-5e700880-5c7d-11eb-99dd-15ec8d23a134.png">

2. Click on Preview to see how it looks like on the live site. Here's how it will look like on the Livesite and Preview.
<img width="961" alt="Screen Shot on 2021-01-22 at 05-55-26" src="https://user-images.githubusercontent.com/40605613/105421794-a3943a80-5c7d-11eb-867e-afc5e0e47503.png">

## Expected

The YouTube videos should render within the size of the columns block and display exactly how it is in the page editor.

* User report: 26489072-hc
* Follow-up ticket:  #3671144-zd

**Comment by danieldudzic** [comment]
Hi @annbingle 

I'm struggling to reproduce the issue.

It works fine for me with Independent Publisher 2
<img width="1779" alt="independent_publisher_2" src="https://user-images.githubusercontent.com/905781/107222996-ee4fd980-6a15-11eb-8df5-4400771b3ac1.png">

Would you mind sharing the block code?

**Comment by danieldudzic** [comment]
Please re-open the issue if the problem persists.
