### ISSUE TITLE
Carmack: Long URLs need wrapping styles on home page

### ISSUE THREAD

**Issue by chad1008** [Automattic/themes#3087]
## Steps to replicate

1. Starting from WordPress.com/post create a post with a long URL (for example to a file for a user to download) OR add an audio embed (for example, if you were publishing a podcast) at the beginning of the post content
3. Ensure the post is properly tagged to appear under Featured Posts on the homepage.
4. Ensure this post will be the 6th, 7th, or 8th Featured Post (the issue appears when the post is displayed below the slider)
5. Publish the post, and visit the home page

## Result

The URL will extend over the neighboring post:

<img width="890" alt="Screen Shot 2021-01-22 at 2 44 44 PM" src="https://user-images.githubusercontent.com/13856531/105537950-b67c2e80-5cc0-11eb-8613-41271f8dddf8.png">

Note, this also happens in the "Latest Posts" section lower on the homepage at small enough breakpoints.

## Expected

The URL text should wrap, to preserve formatting. `word-break: break-word` is a possible fix.

This was discovered during some proactive outreach: #3674012-zd

**Comment by scruffian** [comment]
Moved to Trac
