### ISSUE TITLE
Stow: Social Menu Not Displaying

### ISSUE THREAD

**Issue by annbingle** [Automattic/themes#3090]
## Steps to replicate

1. Create a Social Menu in Customizer.
2. Select the box "Social Links Menu" under Menu Location, click Save Changes.

## Result

The Social Menu link will not appear on their site.
<img width="1380" alt="Screen Shot 2021-01-23 at 05 29 24" src="https://user-images.githubusercontent.com/40605613/105564653-1d9bf080-5d5e-11eb-9985-027f27da69ab.png">

However, if you select the Primary or Footer Menu, the change will render like below.
<img width="1380" alt="Screen Shot 2021-01-23 at 05 30 13" src="https://user-images.githubusercontent.com/40605613/105564688-3dcbaf80-5d5e-11eb-9c4b-69922a272a01.png">

## Expected

The social menu should appear below the Navigation section just like in the screenshot below.
<img width="657" alt="Screen Shot on 2021-01-23 at 09-36-27" src="https://user-images.githubusercontent.com/40605613/105564752-8aaf8600-5d5e-11eb-994e-95841dfcb994.png">

* User report: [26306545-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=26306545)
* Follow-up ticket:  [3674267-zd](https://woothemes.zendesk.com/agent/tickets/3674267)

**Comment by fashuvo** [comment]
Another user reported this in #3673415-zen.

**Comment by fashuvo** [comment]
Another report in #3677466-zen.

**Comment by mrsjaved** [comment]
Another report of similar issue #22790004-hc
