### ISSUE TITLE
Spearhead: Add support for group block's border radius setting

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3093]
It would be awesome to integrate the fresh-off-the-press [setting for border-radius](https://github.com/WordPress/gutenberg/pull/27665) on Group block. We've got a couple of Spearhead-based podcasting layouts to be launched shortly that would immediately benefit from this, but it's a very handy design tool in general and we would love to start taking advantage of it as soon as possible.

**Comment by scruffian** [comment]
I don't think we can do this in Spearhead as it's a Classic theme. Adding an experimental-theme.json file to the theme will make this a Block theme...

**Comment by scruffian** [comment]
Actually what I said is incorrect, it should be possible to add the file without enabling FSE...
