### ISSUE TITLE
Spearhead: Custom colors on outline-style buttons not working

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3094]
Selecting a color from the theme color palette for the Button block is not being applied in the preview. This seems to be happening only when the Button block is using the outline style.

## Steps to replicate
1. With Spearhed theme active, add Buttons block to post or a page.
2. Create a Button and select Outline style in the Styles section.
3. Switch the text color to black or white from the pre-defined color palette.
4. The color is being applied in the Editor.
5. Save & Preview the page. The color is not being applied in the preview.

This does not seem to happen when using a color selected via the color picker.

## Result

Editor settings:
![spearhead_button_1](https://user-images.githubusercontent.com/4550351/105658469-9c3d8d00-5f1a-11eb-8cf2-e5140c82b141.jpg)

Preview:
![image](https://user-images.githubusercontent.com/4550351/105658496-ab243f80-5f1a-11eb-8179-67dc24b18f61.png)

**Comment by pbking** [comment]
I wasn't able to reproduce this.  The Button is following the color choices (either from the palette or from the color picker) and is reflecting on both the Editor and the Page.  I validated the functionality for both foreground and background colors as well as Fill and Outline styles.

**Comment by scruffian** [comment]
Also unable to replicate. @alaczek can you have another look?

**Comment by alaczek** [comment]
Oh yeah, it does seem to be working for me now. ¯\_(ツ)_/¯
Thanks for looking!
