### ISSUE TITLE
Spearhead: Default link color bleeding into hover state of Social Icons block

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3095]
## Steps to replicate

1. With Spearhead theme active, add Social Icons block to a post or a page.
2. Add one or more social icons.
3. Save and preview. Hover over the icons and note the color change.

The same thing happens with other block styles as well.

This is a preview of the Social Icons block:
![xoTBaOaQgv](https://user-images.githubusercontent.com/4550351/105659280-7adda080-5f1c-11eb-961f-d23aeaeb1ed7.gif)

(also note the slightly jerky animation and how the Edit link below jumps when hovering over the icons, and the fact that all the icons are enlarged when hovering)

You can see the effect live on https://gilbertstarter.wordpress.com/

Here's how Social Icons block should behave for comparison:
![VFE53TVKN7](https://user-images.githubusercontent.com/4550351/105659602-3e5e7480-5f1d-11eb-8732-7fd03ab44a9c.gif)

No user ticket found through my own testing.

**Comment by scruffian** [comment]
We _could_ solve this with this change: https://github.com/Automattic/themes/pull/3107

But its pretty dirty. Instead I suggest we add a class to Gutenberg like this: https://github.com/WordPress/gutenberg/pull/28494

I'd like a second opinion though :)

**Comment by pbking** [comment]
My $0.02... make it simpler: #3109
