### ISSUE TITLE
Business: Gutenberg: Title and content block on editor not aligned

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#310]
## Steps to replicate

- Activate Business theme on a WordPress.com site or install on a local/WordPress.org site
- Open a new post/page editor

## Result

The title and content blocks are not aligned. One can notice that the `Add title` and `Write your story` sections are not aligned.

And, on clicking the content block region makes the alignment appear fine.

<img width="876" alt="screenshot 2018-11-06 at 10 02 56" src="https://user-images.githubusercontent.com/18581859/48044702-494d5300-e1b3-11e8-8637-5ec74e91f491.png">
<div align="center"><sup>Image indicating the view at the start</sup></div> 
<img width="870" alt="screenshot 2018-11-06 at 10 03 04" src="https://user-images.githubusercontent.com/18581859/48044703-494d5300-e1b3-11e8-8d80-1b2676184a6a.png">
<div align="center"><sup>Image indicating the view on clicking the content block</sup></div> 
<img width="876" alt="screenshot 2018-11-06 at 10 03 12" src="https://user-images.githubusercontent.com/18581859/48044704-494d5300-e1b3-11e8-8002-31e2aeddc5bf.png">
<div align="center"><sup>Image indicating the view on clicking outside of the content block</sup></div> 

## Expected

The title and content block alignments are fine, right from the start.

**Comment by laurelfulford** [comment]
@arunsathiya just to double-check, did this come from a support request, or something you noticed on your own? Just want to make sure we follow up if we need to.

Assigning to @mendezcode because I believe this will be fixed with work he's been doing with the Business theme. (Ernesto, just let me know if that's not the case!)

**Comment by arunsathiya** [comment]
@laurelfulford This did not come from a support request. I noticed this on one of my test sites.

**Comment by laurelfulford** [comment]
Thanks for verifying!

**Comment by mendezcode** [comment]
This has been fixed as part of the [editor styles rewrite](https://github.com/Automattic/default-small-business-theme/commit/b39bb05a191fd2177c8e547089843dcf6cd40806).
