### ISSUE TITLE
Eris Theme: Featured Image Slider Not Changing Images

### ISSUE THREAD

**Issue by joweber123** [Automattic/themes#3102]
## Steps to replicate
Create a slider by adding the `featured` tag to portfolio items with featured images.

## Result
The slider is not updating the CSS in order to switch the current image to the center of the screen. 

![Markup on 2021-01-26 at 14:52:45](https://user-images.githubusercontent.com/24914028/105805832-30285b00-5fe6-11eb-99b3-aa9acb7e5858.png)

## Expected
I expected that by pressing the forward and backward arrows the featured image slider would change images. 

##Temporary Fix
The following CSS will resolve this issue but it is not a permanent fix.

```
.slick-current{
    left: 0!important;
}
```

* User report: [ #21348738hc]
* Follow-up ticket: [#3683384-zd]

**Comment by danieldudzic** [comment]
I have now reported this to the theme author via Trac.

**Comment by joweber123** [comment]
Another report here -  [ #22190017-hc]
