### ISSUE TITLE
Nikau: Submenu Items Not Displayed

### ISSUE THREAD

**Issue by thabotswana** [Automattic/themes#3104]
## Steps to replicate

* Create a custom menu with a dropdown submenu

![Annotation on 2021-01-26 at 13-45-57](https://user-images.githubusercontent.com/35628116/105841251-fc950300-5fdc-11eb-9522-ba414304265a.png)

## Result

When viewing site on a mobile device, the mobile menu does not display submenu items. Even clicking the parent menu item will not display the submenu item.

![tempFileForShare_20210126-134955](https://user-images.githubusercontent.com/35628116/105841669-a8d6e980-5fdd-11eb-87c6-1d5dda77ad72.jpg)

## Expected

The submenu items should be visible even in the mobile menu.

* User report: 27274056-hc
* Follow-up ticket: 3684037-zen

**Comment by scruffian** [comment]
Moved to Trac
