### ISSUE TITLE
Eris Theme: Duplicate image captions on split layout portfolio setting

### ISSUE THREAD

**Issue by ezebecke** [Automattic/themes#3108]
## Steps to replicate

1. Visit https://wordpress.com/settings/writing/ and enable the "Portfolio Projects" content type.
2. Visit the theme customizer.
3. Go to: Theme Option > Portfolio Layout Settings.
4. Check/enable the "Display single project in Split Layout" option, and save.
5. Create a new portfolio project.
6. Add image blocks with captions.
7. Preview the page and note that captions are getting duplicated and are being shown on 

## Result

<img width="1585" alt="captions" src="https://user-images.githubusercontent.com/24919469/105899486-5814c000-5fe0-11eb-9c41-a2266697c35d.png">

## Expected

To see the captions below each image only. 

* User report: #27249841-hc
* Follow-up ticket: #3684613-zd

**Comment by scruffian** [comment]
Moved to Trac
