### ISSUE TITLE
Eris: Carousel images get pushed way off screen to the far left

### ISSUE THREAD

**Issue by CompChris** [Automattic/themes#3112]
## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

Create at least a couple featured posts (use featured tag and add featured image). 

![Markup on 2021-01-26 at 17:17:46](https://user-images.githubusercontent.com/6847710/105913511-f01fa300-5ffa-11eb-8150-a82a67225312.png)

Test site to reproduce: https://testtest320881531.wordpress.com/

## Result

These get pushed left of the carousel.

![Markup on 2021-01-26 at 17:22:19](https://user-images.githubusercontent.com/6847710/105913610-19403380-5ffb-11eb-9530-94647d9e5113.png)

## Expected

These should be centered.

* User report: #10534323-hc
* Follow-up ticket: N/A - Workaround with CSS
Slack - C03TY6J1A/p1611698286408200?thread_ts=1611696923.399500&cid=C03TY6J1A

**Comment by kriskorn** [comment]
Another one: 3684431-zen

This seems to fix the issue, although with a slight jump from the title:

```
@media only screen and (min-width: 750px) {
.featured-slider article:not(.slick-active) {
	height: 60vh;
}
}
```

_Media query added from below code._

**Comment by desnum** [comment]
Another case: hc-27307024
I used the workaround CSS above. Thanks @kriskorn ! I wrapped it in a @media rule so that it only applies to desktop (the workaround impacted the mobile view negatively).

Here's my mod:

```
/* Eris Featured Content Fix | 3684431-zen (KK) */
@media only screen and (min-width: 750px) {
.featured-slider article:not(.slick-active) {
	height: 60vh;
}
}
```

**Comment by detlefholtz** [comment]
Got another case like this: 
3688380-zd

Added the CSS and it worked. 

Also worth noting this is happening on the demo of the theme support doc too: 
https://wordpress.com/theme/eris

**Comment by kriskorn** [comment]
> Also worth noting this is happening on the demo of the theme support doc too:
> https://wordpress.com/theme/eris

How very odd that the issue is present in the iframe, but not when I open the demo in a new tab:
https://erisdemo.wordpress.com/

**Comment by scruffian** [comment]
Moved to Trac
