### ISSUE TITLE
Seedlet: Follow form has white text on a white background

### ISSUE THREAD

**Issue by aerych** [Automattic/themes#3113]
## Steps to replicate
Configure the Seedlet theme by choosing the Pallet with the dark background and light text.
<img width="732" alt="Screen Shot 2021-01-26 at 5 25 49 PM" src="https://user-images.githubusercontent.com/1435271/105919905-0bd77900-5ffc-11eb-8529-f1f7285f5246.png">

While logged out, tap the Follow button on the site home screen to view the subscription form.
<img width="328" alt="Screen Shot 2021-01-26 at 5 26 02 PM" src="https://user-images.githubusercontent.com/1435271/105920039-3cb7ae00-5ffc-11eb-9d36-c55e6d21f226.png">

Try typing some texts into the form.
<img width="321" alt="Screen Shot 2021-01-26 at 5 26 08 PM" src="https://user-images.githubusercontent.com/1435271/105920070-4d682400-5ffc-11eb-8abf-e320aff6a19a.png">

## Result
The form has a white background, and the white text of the chosen pallet can not be read. 

## Expected
For the form to either preserve it's own text color, or to adopt the full color scheme of the chosen pallet.

* User report: #3686236-zd

**Comment by danieldudzic** [comment]
This seems to be a bug in the Actionbar. I have now reported the issue: https://github.com/Automattic/actionbar/issues/1
