### ISSUE TITLE
partner-annotum-base: Blank page on new post/pages on WordPress.com Simple

### ISSUE THREAD

**Issue by xknown** [Automattic/themes#3116]
## Steps to replicate

- Activate the `partner-annotum-base` theme.
- Go to `yourtestsite.wordpress.com/wp-admin/post-new.php?post_type=post` (or try site 35251040)

## Result

A blank page is loaded, along with a JS error logged on the browser console:
```
(Uncaught TypeError: $(...).live is not a function), pointing to this line $('.anno-user-remove').live('click', function() {
```

## Expected

Load the post/page without any issues.

* Follow-up ticket: #3682443-zd

**Comment by scruffian** [comment]
I thought I had fixed all these (pNEWy-d2V-p2) but it looks like I missed this one, and possibly some others
- p2
- untitled
- stay
- superhero
- sundance

**Comment by danieldudzic** [comment]
This has been fixed now.
