### ISSUE TITLE
Theme color palette in Coutoire appears to be overridden with bright colours

### ISSUE THREAD

**Issue by andrewserong** [Automattic/themes#3121]
#### Steps to reproduce

1. Starting at URL: wordpress.com/new
2. Select the "Bowen" design and create a new site
3. Go to change the colours on a block, and look at the primary, secondary, foreground and background colours (a Button block is a good one for testing this)

#### What I expected

I expected the colours to use the theme's colour palette from the Customizer

#### What happened instead

Bright, unexpected colours are used instead

#### Screenshot / Video

Screenshot of a Button block selected in the editor, with unfortunate colours (this is from bowenstarterdesign, but any site created with Bowen design will show this):

![image](https://user-images.githubusercontent.com/14988353/93424221-f5593c80-f8fa-11ea-9901-678cb0e2f7c4.png)

#### Context / Source

Issue raised in D49646-code, which ensures that the headstart annotation for Bowen isn't applying these colours to any of the blocks in the annotation. However that change doesn't fix the issue, and it sounds like other themes might be affected too (p7DVsv-8MQ-p2#comment-31010)

**Comment by simison** [comment]
Moved issue to themes repo, thanks @scruffian for such a quick fix!
