### ISSUE TITLE
Blank Canvas: Built in optional opt-in for post comments.

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3126]
Similar to #3033, but for comments. 

We took comments out to ensure simple pages. Since we're adding other options in, let's consider adding an opt-in Customizer checkbox for comments too.

**Comment by pbking** [comment]
Hey @scruffian this is in 'Needs review' but there are no PR's associated.  Is there something somewhere that needs 👀 ?

**Comment by kjellr** [comment]
@pbking yeah, this will be closed by https://github.com/Automattic/themes/pull/3115.

**Comment by pbking** [comment]
Oh, I see.  It just also takes care of the comments too.  Don't think it was doing that when I reviewed earlier.  Thanks @kjellr

**Comment by scruffian** [comment]
Yep, this can be closed now :)
