### ISSUE TITLE
Rivington: Duplicate Meta on Single Post

### ISSUE THREAD

**Issue by codydh** [Automattic/themes#3128]
## Steps to replicate

It's possible this is intentional, but it looks like a bug/oversight to me. On Rivington, when in an Archive/post list view, the meta for a post is displayed below the post content. 

<img width="1434" alt="Screen Shot 2021-01-28 at 7 24 16 AM" src="https://user-images.githubusercontent.com/11252/106138331-0122fe00-613a-11eb-9d06-85c0c0c99045.png">

However, when viewing a single post, it shows both above and below the content. This looks strange when the post is short, and also breaks the schema of meta being below the content as in the post list. 

<img width="1434" alt="Screen Shot 2021-01-28 at 7 24 21 AM" src="https://user-images.githubusercontent.com/11252/106138415-1d269f80-613a-11eb-8d55-ba75e245c2ca.png">

## Result

Meta is displayed both above and below content in the single post view, but not in the post list view.

## Expected

Meta to be displayed below content consistently.

**Comment by scruffian** [comment]
@kjellr do you think this is intentional?

**Comment by kjellr** [comment]
Yes, my understanding is that it was intentional. The theme design squad does not think this is a good design pattern though, so we avoided it in Seedlet and will continue to do so in future themes. 

I don't recommend changing for existing themes, since it's worked that way for so long on existing sites.

**Comment by scruffian** [comment]
Thanks @kjellr closing as wontfix.
