### ISSUE TITLE
Eris: Older portfolio projects are not displaying

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#3143]
## Steps to replicate

We couldn't reproduce the issue since it seems to affect projects that were published in the past.

## Result

The portfolio projects don't display in Calypso, WP Admin, nor front-end of the site.

<img width="1098" alt="Markup 2021-02-01 at 15 40 46" src="https://user-images.githubusercontent.com/25105483/106477629-a4607400-64a8-11eb-85c5-3a1ee0c708b3.png">
<img width="757" alt="Markup 2021-02-01 at 15 41 26" src="https://user-images.githubusercontent.com/25105483/106477633-a62a3780-64a8-11eb-9030-27a723234445.png">
<img width="1166" alt="Markup 2021-02-01 at 15 42 19" src="https://user-images.githubusercontent.com/25105483/106477637-a62a3780-64a8-11eb-9a73-534fdf3cd41b.png">

## Expected

The portfolio projects display properly everywhere.

* User reports / Follow-up tickets: 3701767-zd-woothemes, 3697422-zd-woothemes

**Comment by yashitamittal11** [comment]
Another one - #3701068-zen

**Comment by retnonindya** [comment]
Another one: 3700573-zd-woothemes

**Comment by Nic-Sevic** [comment]
another > advised user to switch theme for now
3705092-zen

**Comment by tbradsha** [comment]
For the sites that are broken, the API request itself returns no posts. Have we confirmed switching themes fixes it?

**Comment by retnonindya** [comment]
Another report: 3706854-zd-woothemes

Still no news back about switching theme.

**Comment by retnonindya** [comment]
One of the users replied -- and I can confirm -- switching theme to theme Twenty Twenty resolved the issue. When the theme switched to theme Twenty Twenty, all published projects reappear.

**Comment by scruffian** [comment]
Moved to Trac.

**Comment by carladoria** [comment]
@scruffian  can we get the link of where this was moved so HEs can follow progress and notify the user?

**Comment by scruffian** [comment]
HEs can't access the Trac that Premium shops use, sorry :(. We're hoping to move to a new system soon.

We will update here when the issue is resolved.

**Comment by nerdysandy** [comment]
Reported on #17400133-hc

**Comment by Robertght** [comment]
I landed on one of the tickets linked here.

@scruffian Is there any update on this one? If not, should we keep the issue close and monitor here until we get an answer? Thanks!

**LE: The user in #3697422-zen can see the projects in the backend but not in the frontend. I tested this on my end and the proejcts showed up without a problem, but the issue remains on their site.**

**Comment by scruffian** [comment]
Update from the theme shop:

> Hello, This was not an issue with past portfolio projects, it's featured projects that are missing. That is normal if you are on the front-end of the site and if customizer Featured Content > Also display tagged posts outside the Featured Content area is not checked. But they should always be visible in admin area, and that is fixed now.
