### ISSUE TITLE
Investigate replacing Color Annotations with Global Styles in the customizer in Seedlet

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3146]
Moved to issue for better technical discussion.

Investigate replacing [this](https://github.com/Automattic/themes/blob/trunk/seedlet/classes/class-seedlet-custom-colors.php) (and [other](https://github.com/Automattic/themes/blob/trunk/seedlet/inc/wpcom-colors-utils.php)?) portions of seedlet theme with definitions in a theme.json file potentially as prototyped [here](https://github.com/WordPress/theme-experiments/pull/173).

**Comment by pbking** [comment]
There is no mechanism in the Global Style system in Gutenberg to manage color variables in the way classic themes manage color variables.  

Anything that we do here will just be a layer on top of Global Styles that provides CSS variable definitions based on theme.json.  Something that ACTS LIKE but IS NOT Gutenberg Global Styles.

**Comment by scruffian** [comment]
There's a summary of some ideas here: pNEWy-dBv-p2

Lets close this for now and revisit in the furture.
