### ISSUE TITLE
Stow: Button Text Color Different in Editor & Page

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#3150]
## Steps to replicate

1. Open a page or post. 
2. Insert button block. 
3. Add texts in the button. 
4. Change texts color (to any color except white) and publish.
5. Check the page preview and published page. 

## Result

The button text color in the editor changes to the set color, while preview and published page shows the button text color in white. 
Changing theme fixes the button text color issue. 

**Editor (button text color is set to pink):** 

<img width="1476" alt="Screen Shot 2021-02-01 at 9 52 11 PM" src="https://user-images.githubusercontent.com/36863633/106517141-5feccc80-64d8-11eb-9a71-0da30758a83e.png">

**Preview & published page (button text color is white instead of pink):** 

<img width="1056" alt="Screen Shot 2021-02-01 at 9 52 26 PM" src="https://user-images.githubusercontent.com/36863633/106517419-bfe37300-64d8-11eb-9161-86c8a0c4650d.png">

## Expected

Button text color will be the same in the editor, preview and published page. 

* User report: 3700147-zd (and testing on personal site, where I was able to replicate). 
* Follow-up ticket: 3700147-zd

**Comment by scruffian** [comment]
Fixed by https://github.com/Automattic/themes/pull/3185
