### ISSUE TITLE
Mayland: Custom link color bleeding to Editor

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3152]
I noticed that when I set a custom link color in the Customizer, it bleeds to various links and hover states in the Editor.

## Steps to replicate
1. Activate Mayland and open the Customizer.
2. Go to Colors & Backgrounds tab and set custom colors. My settings here were:
 - Background: #f0f2e8
 - Link & Text: #bf462c
 - Secondary: #1a1a1a
3. Open up the Editor and explore the interface. Note the red color on hover over various elements.

Here are a few screenshots:

![image](https://user-images.githubusercontent.com/4550351/106536042-b5ae8c80-654b-11eb-94a3-d756041bbabe.png)

![mayland_color_bleed](https://user-images.githubusercontent.com/4550351/106536629-f0fd8b00-654c-11eb-8c2d-bbfbd61f2c4c.png)

You can also see this issue live when you go to edit the home page of https://balanstarter.wordpress.com/

No user report, found through my own testing.

Browser: Chrome 87.0

**Comment by scruffian** [comment]
I think this now fixed. Please reopen if you still notice issues.
