### ISSUE TITLE
Mayland: Custom link color interfering with social media icons

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3156]
## Steps to replicate

1. Activate Mayland and open the Customizer.
2. Go to Colors & Backgrounds tab and set custom colors. My settings here were:
 - Background: #f0f2e8
 - Link & Text: #bf462c
 - Secondary: #1a1a1a
3. Add a new post or a page and insert a social icons block, and add a few icons.
4. Note the square, red background when you hover an icon in the Editor.
5. Preview the site. Note the inside of the social icons is using the custom link color, instead of white.

## Result
Editor view, hover over an icon:
![image](https://user-images.githubusercontent.com/4550351/106544482-b94a0f80-655b-11eb-8700-4e4ddea098ef.png)

Preview:
![image](https://user-images.githubusercontent.com/4550351/106544527-ca931c00-655b-11eb-8410-4b1fb7483f5c.png)

No customer report, found through my own testing.

**Comment by jffng** [comment]
Closed by #3189, but will ship with a bundle of updates next week.
