### ISSUE TITLE
Blank Canvas: Starter Content Not Applied When Activating from Theme Info Page

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#3164]
## Steps to replicate

* Set up a site using a different theme
* Go to Blank Canvas's Theme Showcase page here: https://wordpress.com/theme/blank-canvas
* Activate Blank Canvas for your site
* Select the option to use Blank Canvas's starter content

## Result

The site still continued to use the previous theme's starter content

[![Video of the original starter content that was active on the site applied after selecting the "Use Starter Content" option](https://d.pr/i/vGMySb+)](https://d.pr/i/vGMySb)

## Expected

The theme's starter content would be applied

**Comment by kjellr** [comment]
Blank Canvas doesn't come with any starter content (since it's empty), so we've discussed turning off this modal for the theme. I'll close this issue in favor of tracking that effort over here: https://github.com/Automattic/wp-calypso/issues/49317
