### ISSUE TITLE
Blank Canvas: Site Title Displayed Incorrectly When Changed in the Customizer

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#3165]
## Steps to replicate

* Set site's theme to Blank Canvas
* Allow headers and menus to be shown from the Content Options panel
* Change the title of the site in the Site Identity panel

## Result

In the Customizer, the site title is displayed differently than it had been previously:

[![Video showing the site title being displayed incorrectly in the Customizer](https://d.pr/i/Ae5ZQv+)](https://d.pr/i/Ae5ZQv)

## Expected

The site title would be shown the way it was when the change was published and live on the site:

[![Site title shown as expected on published site](https://d.pr/i/aA4nb2+)](https://d.pr/i/aA4nb2)

**Comment by scruffian** [comment]
I can't replicate this. I wonder if it was fixed by https://github.com/Automattic/themes/pull/3173. Please let me know if you can still see it.

**Comment by edequalsawesome** [comment]
Yep, looks like that fixed it -- thanks, @scruffian!
