### ISSUE TITLE
Resonar: featured/sticky posts do not show at top of posts page

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#3171]
## Steps to replicate

1. Set the homepage to show latest posts.
2. Make a post sticky.

## Result

The post does not show anywhere:

![image](https://user-images.githubusercontent.com/32492176/106801708-50c46680-661f-11eb-86de-c879aef940a0.png)

## Expected

The theme should show the sticky post at the top of the theme in a "featured" format, like this "First Sunday Cooking" post:

![image](https://user-images.githubusercontent.com/32492176/106801654-3f7b5a00-661f-11eb-932e-25d58f91076b.png)

Per the docs:
>Each post displays a full-screen Featured Image, which helps to visually tell your story. The large Featured Image is also used for a Sticky Post on your blog’s homepage. It works best at 2000px wide and 1500px high.

Also likely related, the featured image and post title on single posts don't load.

* User report: 26630735-hc

**Comment by retnonindya** [comment]
Another report: 27443457-hc -- follow up: 3710853-zen

Feature image is missing from every single post and page on the website.

**Comment by benchilcote** [comment]
Another report: #2472781-hc | Follow up: 3711960-zen

**Comment by arcangelini** [comment]
Fixed in r57711

https://github.com/Automattic/themes/issues/2910
