### ISSUE TITLE
Gateway: Featured images aren't showing on single posts

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#3183]
## Steps to replicate

1. Create a post with a featured image.
2. Ensure `Display on blog and archives` is enabled in *Design → Customize → Content Options*.

## Result

The featured image on the single post page doesn't load.

## Expected

The featured image on the single post page should load. Possibly similar to #3171, in which featured images aren't showing on single post pages in the Resonar theme.

* User report: 27511745-hc

**Comment by danieldudzic** [comment]
Hi @tbradsha,

Gateway does not support displaying the Featured Image on the post itself.

If you want to show the image in the post, you should add the Image again to the content of the post, as a regular image.

**Comment by tbradsha** [comment]
Ah, it looks like I misunderstood the feature. Thanks!
