### ISSUE TITLE
Colour Scheme issues with Mayland Theme

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#3186]
There appears to be some Editor Colour Scheme issues with Cover Blocks and the Mayland Theme.

![image](https://user-images.githubusercontent.com/545779/106950403-f812cd80-66f3-11eb-8848-1a8f578a4156.png)

I'll update the issue as I try and narrow down exactly what's happening. :)

**Comment by ianstewart** [comment]
The custom colour here doesn't appear to be loading correctly.

![image](https://user-images.githubusercontent.com/545779/106953635-36aa8700-66f8-11eb-88c1-5ebefc91057a.png)

**Comment by ianstewart** [comment]
I'm able to update the colour in the editor and get the desired custom colour to appear — but when I reload the post the custom colour will no longer load.

The front-end is not affected.

**Comment by p-jackson** [comment]
I'm temporarily hiding the Brice design here Automattic/wp-calypso#49728, so that new users don't get a broken experience for the time being.

**Comment by scruffian** [comment]
I think this is a Gutenberg on WordPress.com issue.

**Comment by WunderBart** [comment]
> I'm able to update the colour in the editor and get the desired custom colour to appear — but when I reload the post the custom colour will no longer load.
> 
> The front-end is not affected.

I'm unable to replicate this. I can set the custom color for the background of the Cover block (Brice SPT on Mayland theme), save, reload the page, and it's still there as expected. I can see that the background color on your [screenshot](https://user-images.githubusercontent.com/545779/106950403-f812cd80-66f3-11eb-8848-1a8f578a4156.png) is black despite the block settings panel indicating differently. Do you see any console errors there?

**Comment by ianstewart** [comment]
I can no longer reproduce it — either. So no console errors to report. I think we can close this out. Perhaps related to Gutenberg updates over the past two weeks as suggested by @scruffian. cc @p-jackson.

**Comment by p-jackson** [comment]
@ianstewart is there a maintenance task to re-enable Brice? Or is @Automattic/view-engineering re-enabling?

**Comment by simison** [comment]
@p-jackson @ianstewart PR: https://github.com/Automattic/wp-calypso/pull/49985
