### ISSUE TITLE
Blank Canvas: CSS does not load during editing and viewing

### ISSUE THREAD

**Issue by arcangelini** [Automattic/themes#3198]
## Steps to replicate

I have noticed this from a few locations and it is often intermittent but recurring. The only place I can get it to consistently happen is in the Customizer by toggling the "Display Site Title" option. The CSS styling for the theme does not load at all it seems.

I was able to replicate this on multiple Simple sites with Blank Canvas and Seedlet, but not Spearhead.

1. Activate Blank Canvas
2. Go to customizer and add a title/tagline if its not already set.
3. Toggle the "Display Title and Tagline" option.
4. The reloaded preview will show without any CSS.

## Result
[![Screenshot](https://d.pr/i/7sBvmL+)](https://d.pr/i/7sBvmL)
[![Screenshot](https://d.pr/i/mzLiXl+)](https://d.pr/i/mzLiXl)

[![Screenshot](https://d.pr/i/rv5Xa9+)](https://d.pr/i/rv5Xa9)
[![Screenshot](https://d.pr/i/xVBbBO+)](https://d.pr/i/xVBbBO)

[![Screenshot](https://d.pr/i/rq8Ua4+)](https://d.pr/i/rq8Ua4)
[![Screenshot](https://d.pr/i/AWWWrK+)](https://d.pr/i/AWWWrK)

## Follow-up

This was not discovered by any user so there is no follow-up currently.

**Comment by jffng** [comment]
Hey @arcangelini thanks for reporting — I tried to replicate on my simple site with Blank Canvas and Seedlet, but could not.

Also the screenshots in the issue are broken links. Going to close this but please re-open if it persists.
