### ISSUE TITLE
Varia/children: RTL sites have unaligned content aligned left by default

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#3203]
## Steps to replicate

Hello! This seems to have come up in the last few days all of a sudden, specifically on WordPress.com (which doesn't seem to be using the style-rtl.css files).

1. Start a WordPress.com site with a Varia child theme and set the site language to a RTL language. 
2. Add some paragraphs that are not explicitly aligned one way or the other, in any language.

## Result

These blocks are left-aligned on the live site - this is true of *Blog Posts* blocks and other divs as well as everything in paragraph tags. Inspect element shows that the `text-align: left` rule is active for the body element.

## Expected

Right-alignment should be the default (and is on .org, at least on Varia and Redhill).

* User report: a few, but #3717158-zd among others - affected themes on user sites include Redhill, Maywood and Hever

**Comment by katiebethbrown** [comment]
Another report in 3717158-zd-woothemes
Theme: Redhill

**Comment by Nic-Sevic** [comment]
Another issue here with Maywood
3713375-zen

**Comment by allanftd** [comment]
Adding two more tickets with the same issue:
3721011-zen - Hebrew site (Twenty Twenty theme)
3714714-zen - Arabic site (Brompton theme)

**Comment by danieldudzic** [comment]
@goblinartificer @katiebethbrown @Nic-Sevic Thank you for reporting this issue. There was an RTL bug with Gutenberg on WP.com. The fix has been deployed today, so please let me know if the issue persists.
