### ISSUE TITLE
Morden: Blog archive pages are LTR even if site language is set to an RTL language

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#3205]
## Steps to replicate

- Set site to RTL language
- view any blog archive page (categories, tags, main blog feed) it displays in LTR even though the other elements on the page display (correctly) in RTL
- 
## Result

![Markup 2021-02-07 at 11 05 30](https://user-images.githubusercontent.com/1967448/107159523-adcc5f00-6934-11eb-9281-5f8445c406e5.png)

## Expected

Expected all elements to be RTL

* User report: https://wordpress.com/forums/topic/%d7%a2%d7%99%d7%a6%d7%95%d7%91-%d7%90%d7%aa%d7%a8/

**Comment by danieldudzic** [comment]
Hi @jerrysarcastic 

Thank you for reporting this issue. There was an RTL bug with Gutenberg on WP.com. The fix has been deployed today, so please let me know if the issue persists.
