### ISSUE TITLE
Spearhead: Add a toggle to disable automatic switching to dark mode

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3213]
We've run into some issues with our podcasting patterns and Spearhead running in dark mode. Basically, we have two starter designs [Gilbert](https://gilbertstarter.wordpress.com/) and [Riley](https://rileystarter.wordpress.com/), and they are designed with white (or at least light) background in mind. So when you preview them with dark mode on, they look quite broken. In theory, we could design a set of alternate dark patterns, but there's no way to automatically switch to them. 

Would it be possible to have an option to turn off the automatic switching to dark mode in Spearhead?

## Steps to replicate

1. Go to system preferences > general and pick Dark appearance.
2. Preview [Gilbert](https://gilbertstarter.wordpress.com/) and [Riley](https://rileystarter.wordpress.com/) starter sites.

## Result
Gilbert:
![image](https://user-images.githubusercontent.com/4550351/107299767-4c3ef880-6acc-11eb-9c21-0c101ee423f6.png)

Found through my own testing.

**Comment by mreishus** [comment]
Beyond the preview, any site created using Gilbert or Riley is illegible when browsing from a browser that follows the `@media (prefers-color-scheme: dark) {` rules.

**Comment by alaczek** [comment]
Do you have any idea when this will be deployed to .com?

**Comment by pbking** [comment]
I believe it has already been deployed to .com @alaczek 
I see it there now.

**Comment by alaczek** [comment]
> I see it there now.

Where is that? :) I'm looking in Customizer > Colors & Background and no toggle there.

**Comment by pbking** [comment]
Do you see the "dark mode" comment at all?  That is what changed to a check box.
If you don't see either then likely you have made modifications to the colors via the customizer and the control will not show (and dark mode should be effectively disabled anyway).  Return all color selections to default via the [ Default ] button.  You may need to Save and reload the Customizer for the control to appear once you have defaulted the colors.

![image](https://user-images.githubusercontent.com/146530/108294754-76478900-7164-11eb-9d0c-b464e43abe3a.png)

**Comment by alaczek** [comment]
I had the default colors on the site, but I still had to select "Default", Save, and refresh to see the setting. It's working now.

I also just created a new site using Spearhead, to be sure I didn't touch the color settings, and the toggle is still not visible.

**Comment by scruffian** [comment]
This should now be fixed.
