### ISSUE TITLE
Hever: Cover image Color Overlay not Applied

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#3216]
## Steps to replicate

1. Activate Hever theme 
2. Add a Cover block to a page or post 
3. Add color overlay in Cover block 
4. Update / Publish
5. Compare page editor with the published page. 

## Result

Color overlay set to the cover block is applied only in the editor, but not in the published page:

<img width="1575" alt="Screen Shot 2021-02-09 at 9 41 21 AM" src="https://user-images.githubusercontent.com/36863633/107338677-1c87f480-6abc-11eb-8480-a1ef05f30dfa.png">

Published page (color overlay not applied): 

<img width="1201" alt="Screen Shot 2021-02-09 at 9 42 29 AM" src="https://user-images.githubusercontent.com/36863633/107338705-26a9f300-6abc-11eb-830e-1f40da4522bd.png">

## Expected

Color overlay selected will be applied to the cover block image in both the editor and published page. 

* User report: [27004780-hc]
* Follow-up ticket: [3724602-zd]

**Comment by scruffian** [comment]
This seems to have been a wordpress.com bug that is now fixed. Please reopen if it continues to be a problem.
