### ISSUE TITLE
Hemingway Rewritten: Hebrew language breaks submenus

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#323]
## Steps to replicate

1. Create a menu with submenus on the site.
2. Change the site language to Hebrew

## Result

All the submenus are displayed at the same time:

![screen shot 2018-11-07 at 15 40 29](https://user-images.githubusercontent.com/3696121/48159749-12a33580-e2a4-11e8-81bb-37b8773aea51.png)

## Expected

The menu to work properly as with the English language

* User report: 7880741-hc

* Blog ID: 104378951

I was able to replicate the same behavior on a test site

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
