### ISSUE TITLE
Mayland: Color palette in the editor looks broken

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3231]
The theme color palette swatches in the editor are all the same.

## Steps to replicate
1. On a site with Mayland theme active, create a post or a page.
2. Add a block with color options, for example, Buttons, Paragraph, or Group. 
3. Look at the color settings panel in the sidebar. Note all the color swatches are the same (black).

![image](https://user-images.githubusercontent.com/4550351/107453673-8927ef80-6b9f-11eb-813a-84e23791b5f0.png)

Found through my own testing.

**Comment by scruffian** [comment]
This is what I see:
<img width="314" alt="Screenshot 2021-02-10 at 15 34 23" src="https://user-images.githubusercontent.com/275961/107532158-80daaf00-6bb5-11eb-8a7d-0eb2b0b2b048.png">

When you change the colors in the customizer then you get more options. What site do you see the above on?

I'm going to close this as a I can't replicate this, but feel free to reopen if its still an issue.

**Comment by alaczek** [comment]
This is the site, and it has no color customizations: https://hannahstarter.wordpress.com

I would say your screenshot looks broken as well because I expected each swatch to be a different color. If the default color scheme is black and white, could we have just those two color swatches instead of the four we have now?

**Comment by alaczek** [comment]
There's also weirdness when you click on any of the color swatches, where they all get selected:

![dM44wd7bcZ](https://user-images.githubusercontent.com/4550351/107604078-f3fe2700-6c82-11eb-95ab-c8bd6842d299.gif)

**Comment by MaggieCabrera** [comment]
This only happens to me if I never select a palette from the customizer and go with the default colors, as soon as I pick one and save, the editor palette works correctly.

**Comment by scruffian** [comment]
@alaczek how can I create my own site using the Hannah starter template?

**Comment by alaczek** [comment]
It's not in signup flow just yet, but you could go to the source site and copy the whole homepage content and paste on your site. But the content of that site is not relevant to the issue AFAIK. Just create a new site using Mayand design in signup, and you should be able to see it. The key seems to be that it has to be a new site, or at least one where Customizer color settings haven't been touched at all.

> This only happens to me if I never select a palette from the customizer and go with the default colors, as soon as I pick one and save, the editor palette works correctly.

This might be the key, as the sites where it happened for me were new sites where I haven't changed any of the Customizer settings. But even if selecting a color palette in the Customizer fixes this, I still think it's an issue that color swatches look and behave broken out of the box. This does not happen for me in other themes.

**Comment by scruffian** [comment]
> Just create a new site using Mayand design in signup, and you should be able to see it. 

I created scruffianmayland.wordpress.com using the /new flow and I don't see it there. What flow are you using?

**Comment by alaczek** [comment]
I just created a new site starting at https://wordpress.com/new?ref=calypso-selector
I picked Mayland in the signup, and the color palette on this fresh site does look different, but still, I'm seeing 3 swatches of black in there:
![image](https://user-images.githubusercontent.com/4550351/107745698-cc818a00-6d68-11eb-850b-c4f010840a41.png)

While on this site: https://onepagetest391584497.wordpress.com (feel free to check out this site and poke around) I'm seeing four black color swatches, like in the initial report.
