### ISSUE TITLE
Varia: Allow self-hosted sites to hide the site title.

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3234]
As noted in https://github.com/Automattic/themes/issues/2174#issuecomment-775779517, Varia only allows the site title to be hidden on WordPress.com. This seems arbitrary, so we should consider moving that function and style rule into the main `customizer.php` file instead.

**Comment by scruffian** [comment]
Just noting that these themes aren't on .org, so this is probably a low priority.

**Comment by cbatson** [comment]
See also https://github.com/WordPress/gutenberg/issues/28564.

**Comment by scruffian** [comment]
This doesn't make sense as a theme issues, closing in favour of https://github.com/WordPress/gutenberg/issues/28564.
