### ISSUE TITLE
Seedlet: Experimental link color isn't working correctly.

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#3243]
In Seedlet when you select a link color from the palette, it doesn't work:

<img width="1186" alt="Screenshot 2021-02-11 at 17 00 57" src="https://user-images.githubusercontent.com/275961/107671595-e8fbc480-6c8b-11eb-88df-b8a58b0ba605.png">

**Comment by pbking** [comment]
Fixed in #3271 and refactored for Gutenberg 9.9 in #3274

**Comment by scruffian** [comment]
This was fixed in #3325
