### ISSUE TITLE
Varia + children: Links and Outline Buttons same color as primary background

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#3250]
## Steps to replicate

1. Varia or a child theme active
2. In post or page, add a block with background color set to primary color (e.g. cover, group, or media & text block)
2. Inside block add a regular link, or a button with outline (otherwise default colors)

## Result

The link and button are invisible because they are also showing the primary color.

Screenshot with Barnsbury:

![barnsbury-button-color](https://user-images.githubusercontent.com/2031017/107727722-12762800-6d40-11eb-9015-3e14f98a83fa.png)

Screenshot with Exford:

![exford-button-color](https://user-images.githubusercontent.com/2031017/107727737-1c982680-6d40-11eb-89c6-981437e69e9e.png)

Can be seen on my test site:
https://badaboomtest.wordpress.com/testing-colors/?theme=pub%2Fvaria
https://badaboomtest.wordpress.com/testing-colors/?theme=pub%2Fbarnsbury
https://badaboomtest.wordpress.com/testing-colors/?theme=pub%2Fexford

## Expected

The link and button color should contrast the background so it can be seen.

From what I can see, the themes all adjust the regular text colors for elements with background color using CSS such as:
```
.has-primary-background-color:not(.has-text-color),
.has-primary-background-color.has-background-dim:not(.has-text-color) {
	color: white;
}
```
but there is no corresponding CSS for links and buttons to override the primary color being applied to links and buttons in this situation.

A possible fix may be to just include links in the above CSS:

```
.has-primary-background-color:not(.has-text-color),
.has-primary-background-color:not(.has-text-color) a,
.has-primary-background-color.has-background-dim:not(.has-text-color),
.has-primary-background-color.has-background-dim:not(.has-text-color) a {
	color: white;
}
```

* User report: 27566071-hc

Maybe related to these issues, but not sure:
https://github.com/Automattic/themes/issues/2582
https://github.com/Automattic/themes/issues/3232

**Comment by scruffian** [comment]
May be fixed by #3236

**Comment by carinapilar** [comment]
Got one today on 3732807-zd-woothemes with Barnsbury too. I have white as the background color in the Customizer, and setting a Buttons block with a white background doesn't work:

![Screen Shot 2021-02-12 at 15 44 04](https://user-images.githubusercontent.com/16104522/107808945-283c1b00-6d49-11eb-83cb-e8d76976b1f2.png)

Editor shows white background and green letters, but the site shows the above.

**Comment by kathrynwp** [comment]
Ran into this issue today with Morden, in chat 27743107-hc

![8_Steps_to_Making_Redundancies_–_186hr](https://user-images.githubusercontent.com/7662449/107898343-7ef05300-6f09-11eb-9c54-f939cd4021f5.jpg)

I provided this custom CSS as a workaround to make the links visible again:

```
.has-primary-background-color:not(.has-text-color) a {
  color: #ffffff;
  text-decoration: underline;
}
```

**Comment by danieldudzic** [comment]
@scruffian I have done some investigating and it seems that this is the commit that broke links: d50b3b6132bd56d9c8d77f491e6c26f04d90f502
