### ISSUE TITLE
Twenty Seventeen: Menu code exposed to Google and displayed in search results

### ISSUE THREAD

**Issue by benchilcote** [Automattic/themes#3258]
## Steps to replicate

- Find an existing WordPress.com website built on the Twenty Seventeen theme 
- The website must have sub menu items
- Search for the website in Google and view search engine results

## Result

Google displays elements that should not be displayed including:
- Expand child menu
- Collapse child menu

## Expected

I would expect these elements to not be indexed and displayed by Google. 

## Examples

Original website from this report: https://vmwarecode.com

<img width="700" alt="Screen Shot 2021-02-12 at 08 05 02" src="https://user-images.githubusercontent.com/11636210/107810663-09368c80-6d3b-11eb-8541-ac7ba1a44e90.png">

Other websites:

indayinteriordesign.com
<img width="630" alt="Screen Shot 2021-02-12 at 09 47 27" src="https://user-images.githubusercontent.com/11636210/107810759-2c613c00-6d3b-11eb-8194-6710cce4aa12.png">

mikhailoparin.blog
<img width="711" alt="Screen Shot 2021-02-12 at 09 51 27" src="https://user-images.githubusercontent.com/11636210/107810806-43079300-6d3b-11eb-8fcd-c796f3ec341e.png">

isiktercume.wordpress.com
<img width="667" alt="Screen Shot 2021-02-12 at 09 56 54" src="https://user-images.githubusercontent.com/11636210/107810858-531f7280-6d3b-11eb-93cd-78e74c288ab2.png">

* User report: 27068422-hc
* Follow-up ticket: 3734270-zen

**Comment by kathrynwp** [comment]
I'm no longer seeing this issue on any of the above referenced sites.

![site_https___vmwarecode_com_-_Google_Search](https://user-images.githubusercontent.com/7662449/179606404-7536e771-440d-4e21-a140-70e95e45cd61.jpg)

![site_https___mikhailoparin_blog_-_Google_Search](https://user-images.githubusercontent.com/7662449/179606487-5125cd07-c7fc-4832-b0b4-b32a294d2530.jpg)

![site_https___indayinteriordesign_com_-_Google_Search](https://user-images.githubusercontent.com/7662449/179606589-95d78fb6-1bcb-43ee-864c-dcf9b2e90629.jpg)

![site_https___isiktercume_wordpress_com_-_Google_Search](https://user-images.githubusercontent.com/7662449/179606691-489053c2-79ea-450c-a169-180b284778d2.jpg)

Closing as fixed.
