### ISSUE TITLE
Multiple themes: Social icons background color not working

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3263]
Core recently introduced [color options for Social Icons block](https://github.com/WordPress/gutenberg/issues/21605), but they don't seem to be working in a few themes I tested.

## Steps to replicate
1. On a site with Blank Canvas active, create a post or a page.
2. Add social icons block and a few links.
3. Go to Social icons block settings and select any color for the background (I tried both from theme color palette, and custom). Note the color is applied in the editor. 
4. Preview the site. Note the color is not applied and the icons are invisible.

Tested with Blank Canvas/Seedlet, Mayland, Maywood.

Editor view:
![image](https://user-images.githubusercontent.com/4550351/107894275-4db46900-6f83-11eb-820c-62300290d77e.png)

Preview:
![image](https://user-images.githubusercontent.com/4550351/107894295-5c9b1b80-6f83-11eb-96dc-518a71f5cb4a.png)

Found through my own testing.

**Comment by ivan-ottinger** [comment]
I have encountered the same issue with the Ovation theme: 3768890-zd-woothemes

Also could reproduce with Exford, TheFour and Radcliffe 2 for example.

**Comment by vajrasar** [comment]
I checked this report [here](https://github.com/Automattic/wp-calypso/issues/50171#issuecomment-1099305423) and could not replicate it on any theme.

**Comment by mikachan** [comment]
Thanks for checking and confirming @vajrasar. I'll close this issue then, but please feel free to open again if needed.
