### ISSUE TITLE
Blank Canvas Theme - comments enabled but not working 

### ISSUE THREAD

**Issue by tavilla61** [Automattic/themes#3276]
## Steps to replicate

- Checked all comment related settings under Settings > Discussion, nothing should be preventing comments on the site
- Screenshot of user's Discussion settings: https://d.pr/i/fB0se6
- Allow Comments is checked on their post (post is published) 
- Site is currently set to Private, but the user made it Public while we were testing and it still didn't allow comments. 

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

## Result

- Even though settings should have been set to allow comments, they weren't working. 

## Expected

Comments to be enabled and allowed. 

* User report: [shortlink to chat/forum thread/ticket, ie 27762571-hc]
* Follow-up ticket: [shortlink to ticket, ie 3742086-zen]

**Comment by kjellr** [comment]
@tavilla61 in order to retain its blank slate by default, Blank Canvas requires users to opt-in to comments via the "Enable Comments" checkbox in `Customizer > Content Options`. 

![wordpress com_customize_kjellreigstad wordpress com_](https://user-images.githubusercontent.com/1202812/107992103-fa9fdd80-6fa5-11eb-8306-0f82edd1ab20.png)

https://wordpress.com/theme/blank-canvas#expand

**Comment by kylemcph** [comment]
Hi @kjellr! I can confirm that both on the user's site, as well as my test site, comments still do not appear even when the Enable comments box is checked. 

Are you able to repo as well, or do you see comments displayed on pages?

**Comment by Robertght** [comment]
The user reached us again today and they aren't happy using another theme for now. I can see there's a Pull done by @danieldudzic so I'm wondering if we can set some expectations around it? Thanks!

**Comment by jffng** [comment]
This fix was deployed.

**Comment by dcoleonline** [comment]
I've notified the customer in 3742086-zen and can confirm that the comments field appears on a page and post on their site.
