### ISSUE TITLE
Mayland: Social icons have square background

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3281]
Social icons have a square background in the editor only, affecting all block styles.

## Steps to replicate
1. On a site with Mayland active, create a post or a page.
2. Add social icons block, and add a few icons.
3. Note the black, rounded background for each icon. 
![image](https://user-images.githubusercontent.com/4550351/108000517-3f775300-703e-11eb-9418-8ebb4f3d3ad1.png)
4. Take a look at the block styles and note all of them have the black background:
![image](https://user-images.githubusercontent.com/4550351/108000565-57e76d80-703e-11eb-84e8-d93487c27088.png)
5. Preview the page. Note the icons are displayed properly.
![image](https://user-images.githubusercontent.com/4550351/108000600-70578800-703e-11eb-94be-d4de59345b7c.png)

Found through my own testing.

**Comment by danieldudzic** [comment]
It seems to be working fine in my sandbox:

![social_icons](https://user-images.githubusercontent.com/905781/109091181-95ba5500-7714-11eb-9c3f-e3794d220649.png)

**Comment by alaczek** [comment]
Oh, then it was probably ironed out in the interim :)
