### ISSUE TITLE
Twenty Twenty One: Pinterest icon not showing

### ISSUE THREAD

**Issue by kosiew** [Automattic/themes#3289]
## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

This was fixed in [PR 681](https://github.com/Automattic/themes/pull/681) but I just encountered another case for https://www.pinterest.es/mariadejuan1 

![Screenshot](https://d.pr/i/qJMHQu+)
*if image does not load, please click on this link  : https://d.pr/i/qJMHQu*

## Expected

Pinterest icon to display

* User report: 3744300-zen

**Comment by danieldudzic** [comment]
Hi @kosiew,

This should now be fixed on WP.com (r57780).
