### ISSUE TITLE
Intergalactic 2: Image captions are left aligned in published posts, but centered in the editor

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#3299]
Image captions are left aligned in Preview or published versions of posts where they should be centered as represented in the editor.

### In the editor

<img width="825" alt="Markup 2021-02-18 at 09 28 13" src="https://user-images.githubusercontent.com/2912202/108320762-e9381a80-71cb-11eb-905b-a6c74ff9c54d.png">

### Published post

<img width="756" alt="Markup 2021-02-18 at 09 28 46" src="https://user-images.githubusercontent.com/2912202/108320806-f5bc7300-71cb-11eb-8563-ee229d89315b.png">

### Editor details

Gutenberg: v9.9.3
CoBlocks: 2.5.3
Editing Toolkit: 2.19

## Result

Image captions are aligned to the left when a post is published.

## Expected

Image captions are centered in the block editor, so should be centered on the published post.

* User report: 3746490-zen

**Comment by pauljacobson** [comment]
On what may be a related issue, our customer also pointed out that the editor view doesn't use the same dark mode that the theme does.

**Comment by marcuswisecaesar** [comment]
The user shared an example of the Post Titles not centering as they do in the Theme example:

Users Example: 
![screenshot](https://woothemes.zendesk.com/attachments/token/w7hMy8QHckqWjnAUrQtL5ZMmB/?name=Screen+Shot+2021-02-18+at+11.27.25+AM.png+)
[Direct Link](https://woothemes.zendesk.com/attachments/token/w7hMy8QHckqWjnAUrQtL5ZMmB/?name=Screen+Shot+2021-02-18+at+11.27.25+AM.png)

Theme Example: 
![screenshot](https://woothemes.zendesk.com/attachments/token/wyBddmzbddTXDpeuILTIAcKJy/?name=Screen+Shot+2021-02-18+at+11.28.13+AM.png+)
[Direct Link](https://woothemes.zendesk.com/attachments/token/wyBddmzbddTXDpeuILTIAcKJy/?name=Screen+Shot+2021-02-18+at+11.28.13+AM.png)

**Comment by mikeicode** [comment]
Reported 3778929-zd-woothemes this was Intergalactic (not 2), but same issue. I used this to resolve:

```
/* Centered captions */

.aligncenter > figcaption {
  display: block;
  text-align: center;
}
```

**Comment by Robertght** [comment]
~I'm not going to close this yet as we're waiting for a review on https://github.com/Automattic/themes/pull/5953~

Waiting for a review on https://github.com/Automattic/themes/pull/5953

cc @jeffikus @MaggieCabrera

**Comment by bobmatyas** [comment]
Closed via https://github.com/Automattic/themes/pull/5953
