### ISSUE TITLE
Gateway:  Setting Base font to "small" or "tiny" breaks posts page layout

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#33]
When a custom font is selected for the body copy on a site using the Gateway theme, and the user selects either the "small" or "tiny" font size, the layout of the posts page (blog page) appears broken, with post title breaking awkwardly, and the excerpt no longer floating to the right.

Screencast video at this link:  https://cloudup.com/cSQi9WxXwsN

## Steps to replicate

- Activate Gateway on test site (or visit demo site if you have admin access)
- Visit the customizer and click on blog page (in the site preview) so you can see the issue
- Click on the fonts tab, and choose a custom body font, and the "small" or "tiny" as the font size
- View funky page layout breakage!  :)

## Expected

Same layout, with a smaller font size.  Larger font sizes work as expected.

* User report: #1973260-hc
* Follow-up ticket: #997690-zen
* https://luciaduval.com/blog/

**Comment by sixhours** [comment]
Fixed in r48372-wpcom-themes
