### ISSUE TITLE
Mayland: Long Tagline won't jump into the next line on small screens

### ISSUE THREAD

**Issue by fresatomica** [Automattic/themes#3300]
## Steps to replicate

1. Add a long tagline.
<img width="470" alt="Screen Shot on 2021-02-18 at 09-47-30" src="https://user-images.githubusercontent.com/40177971/108330964-8b590200-71ce-11eb-8f86-47fd74b597e3.png">
2. Check the site on a mobile device (Android, iPhone, you can even observe it changing device on desktop).

## Result

Instead of creating two lines of text on small screens, it wraps up and covers the beginning.

<img width="435" alt="Screen Shot on 2021-02-18 at 09-49-32" src="https://user-images.githubusercontent.com/40177971/108331208-d246f780-71ce-11eb-8db0-c53f52cc1539.png">

## Expected

The text would display in two lines.

* User report: https://wordpress.com/forums/topic/the-alphabet-being-double-when-it-shows-on-iphone/.

**Comment by danieldudzic** [comment]
The customer set the `line-height` to `0` for the `Paragraph` block which broke the `word-wrap`.
