### ISSUE TITLE
Seedlet Blocks: Layout Grid block not working properly

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3364]
## Steps to replicate
1. Set up local WP install with Gutenberg plugin, Seeldet Blocks, and Layout Grid plugin (or set up a new site on WP.com using FSE test environment)
2. Open site editor, and add layout grid block to the Post Content.
3. Set up the layout grid block to full-width, 1 column, offset 0, span 8. Insert an image inside, and set it to full-width as well.
4. The layout grid should look properly in the editor:
![image](https://user-images.githubusercontent.com/4550351/109237624-09985280-7826-11eb-919a-f8bc93ef3ec5.png)

5. Save & preview the site. Note none of the Layout Grid block settings are being applied.
![image](https://user-images.githubusercontent.com/4550351/109237694-33517980-7826-11eb-99cf-599f19b988dd.png)

This issue is blocking us from creating robust layouts and patterns for FSE.

**Comment by alaczek** [comment]
The same thing is happening in Mayland Blocks.

**Comment by alaczek** [comment]
This might not be a theme issue after all: https://github.com/Automattic/block-experiments/issues/170

**Comment by pbking** [comment]
Indeed this is fixed [here](https://github.com/Automattic/block-experiments/pull/177) and will address the issue in all of the block-based themes.

**Comment by MaggieCabrera** [comment]
Can confirm that https://github.com/Automattic/block-experiments/pull/177 fixes this issue. Closing.
