### ISSUE TITLE
Radcliffe 2: Cover block child blocks extend beyond top and bottom of block with multiple taller blocks

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#3366]
User added heading, paragraph, image block (portrait image) and then a contact form to a cover block and due to the combined height of the blocks, they extended above and below the cover block top and bottom edges.

**User screenshot**: https://d.pr/i/HGhsPg/TOOvxXGUwJ

**Test page created by user for us to see**: https://onemoto.in/test-page-for-wp-team/

I gave user the following CSS to fix the issue on their site, but a previous HE suggested it was a theme bug, which I am not convinced of. The cover block has a height of 75vh set in the CSS, and there was just too much content added within the cover block. I'll leave it up to you as to whether this is worthy of a fix or not.

**CSS added**:
`/* force cover block height to auto so it adjusts to height of child elements inside 3743644-zd rs */
.wp-block-cover-image.alignwide, .wp-block-cover.alignwide, .wp-block-cover-image.alignfull, .wp-block-cover.alignfull {
    height: auto;
}`

On the test page user set up, you can see the results of my CSS, and can comment it out to see what happened previously.

## Result

Items extend above and below cover block

## Expected

User expected cover block to expand vertically to accommodate the blocks within

* User report: Chat: (Previous HE did not add link to chat transcript)
* Follow-up ticket: 3743644-zd

**Comment by Gustavo-Hilario** [comment]
- [ ] Another instance of this issue here: 7476641-zen

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Could Not Replicate
- 
📌 FINDINGS/SCREENSHOTS/VIDEO
The theme seems to use the minimum height value as the maximum on Simple Sites

Simple, Radcliffe 2
![CleanShot 2023-12-28 at 13 12 01@2x](https://github.com/Automattic/themes/assets/14153300/3d43bde3-589b-481a-8a3b-a581ddb81917)

Simple, TT4
![screencapture-liviopremium-wordpress-1246-2-2023-12-28-13_13_35](https://github.com/Automattic/themes/assets/14153300/a326ef78-7011-40d7-922f-fc1114e53198)

Atomic, Radcliffe 2
![screencapture-atlivio-wpcomstaging-radcliffe-2-cover-block-2023-12-28-13_16_42](https://github.com/Automattic/themes/assets/14153300/4d1ed0f1-0950-4dcf-ba36-1a3e42da500a)

📌 ACTIONS
- Triaged

**Comment by mmtr** [comment]
Not sure what the original issue was since both the user screenshot and the test page no longer work.

But I cannot see any difference between Simple and Atomic sites, so maybe this issue has been solved?

Simple | Atomic
--- | ---
![Image](https://github.com/user-attachments/assets/b9ea23d1-07ba-4031-9767-5679e11b2613) | ![Image](https://github.com/user-attachments/assets/b609eaa7-802d-4774-b611-47c1eaa353cb)

Feel free to re-open if that's not the case.
