### ISSUE TITLE
Twenty Twenty: Jetpack Video block with Portrait-oriented Video is superimposed

### ISSUE THREAD

**Issue by jinnypark** [Automattic/themes#3370]
## Steps to replicate
1. In a self-hosted WordPress site with Premium Jetpack subscription, (via Pressable) activate Twenty Twenty theme.
2. Create a new post and add Jetpack Video, including at least one portrait-oriented video.
3. Find overlapping layout of theme around the portrait-oriented video(see screenshot)

## Result

Portrait-oriented Jetpack Video block overlaps with existing content, such as sharing buttons or landscape videos.

[Screenshot 1: landscape + portrait video](https://d.pr/i/LuMs7y)

[Screenshot 2: portrait + landscape video](https://d.pr/i/zbD5Ul)

[Link to the staging site](https://jayparktest.mystagingwebsite.com/2021/02/24/video-or-videopress/)

## Expected
I expected there would be enough margin and non-overlapping layout of the portrait-oriented videos.

## Notes
- I tried with different themes (Twenty Nineteen, Twenty Twenty One) and found out this issue is limited to Twenty Twenty theme. 
- I tried with regular Video blocks on WP.COM sites, and did not have issues with portrait-oriented videos.

**Comment by danieldudzic** [comment]
I definitely see the issue on the staging site, but I'm also clueless as to what's causing it.

An hour of trying to debug this yielded no results.

@jeffikus ?

**Comment by danieldudzic** [comment]
Together with @jeffikus, we were able to pinpoint the culprit - and it seems to be a bug in Jetpack.

Closing in favor of: https://github.com/Automattic/jetpack/issues/20001
