### ISSUE TITLE
Seedlet-Blocks: Navigation block in Header Template Part is hard to recognize

### ISSUE THREAD

**Issue by jeyip** [Automattic/themes#3373]
## Steps to replicate

There was some site editor feedback regarding the navigation block in Seedlet-Blocks.

> I did not immediately recognize that the site navigation block was for a menu. It said home so I figured it was a page title

When I first played with Seedlet-Blocks, I found this to be a problem for me as well. I wonder if other newer users might also be confused. In TT1-Blocks, the navigation block is more obvious because we provide other nav links, like "Blog", or "Contact". Maybe it's worthwhile to add similar placeholders to Seedlet-Blocks Header template part?

### Seedlet-Blocks
<img width="1279" alt="Screen Shot 2021-02-26 at 2 20 43 PM" src="https://user-images.githubusercontent.com/5414230/109361764-728bc480-783e-11eb-8b06-694369e08400.png">

### TT1-Blocks
<img width="1281" alt="Screen Shot 2021-02-26 at 2 28 35 PM" src="https://user-images.githubusercontent.com/5414230/109362027-0f4e6200-783f-11eb-9093-8fc0c78b230f.png">

**Comment by alaczek** [comment]
There are a few issues arguing for the opposite - removing those "dead" links in TT1 blocks.
See https://github.com/WordPress/gutenberg/issues/28711 and https://github.com/WordPress/theme-experiments/issues/214
Between those issues, an idea was floated to use the placeholder state of the Navigation block instead, which allows users to pick from existing menus, or create a menu from all existing pages, or start empty.

**Comment by scruffian** [comment]
We now use a location attribute, so I think we can close this.
