### ISSUE TITLE
Seedlet Blocks - Font Family Support

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/themes#3374]
Similar to how tt1-blocks supports a Font Family setting:

![Screen Shot 2021-02-26 at 8 37 45 PM](https://user-images.githubusercontent.com/28742426/109371355-7cc7b600-7872-11eb-83fa-02a374a4a392.png)

Seedlet blocks does not give us this option:

![Screen Shot 2021-02-26 at 8 38 11 PM](https://user-images.githubusercontent.com/28742426/109371373-936e0d00-7872-11eb-95a2-2c2ba77d5507.png)

We should consider updating seedlet blocks to support font family selection.

**Comment by MaggieCabrera** [comment]
This one has been fixed from Blockbase
