### ISSUE TITLE
Mayland Blocks: Issues with the footer

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3379]
I found a couple of issues with the footer in Mayland blocks:
1. There is no WordPress.com credit (screenshot from a simple site)
2. I noticed the stats smiley face at the bottom.
3. Under the post/page content sharing buttons are being displayed (these are not visible in the editor).

<img width="465" alt="mayland_footer" src="https://user-images.githubusercontent.com/4550351/109454210-d5cc5f80-7aa7-11eb-9e33-85275412ba6b.png">

**Comment by alaczek** [comment]
I'm also seeing a broken image icon in the footer on sites using Mayland Blocks:
![image](https://user-images.githubusercontent.com/4550351/112560741-eca46e80-8e27-11eb-9ee3-4f57f3989311.png)

**Comment by MaggieCabrera** [comment]
I think these are all solved now, we removed the smiley icon for all themes, changed the credits for all block themes as well and I don't see the sharing buttons any more but I believe it's something you can deactivate on Jetpack.
