### ISSUE TITLE
Mayland Blocks: Distorted images

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3382]
Images inserted via Image block and Media & Text are distorted in preview (but appear correctly in the editor).

## Steps to replicate
1. Create a site with Full Site Editing and Mayland Blocks active.
2. Open the site editor and add an Image block into the post content (upload new, select from the media library, or from Pexels).
3. Save and preview the site in a new tab. Note the image is distorted.

https://cloudup.com/c-OFkzuESqb

Found through my own testing.

**Comment by alaczek** [comment]
This can be seen on https://maylandblockstarter.wordpress.com/
I also noticed this does not happen when the images are linked, not uploaded to the site.

**Comment by jeffikus** [comment]
I'll add this to our board for next week, thanks @alaczek !

**Comment by jffng** [comment]
Images are missing reset styles, like this: https://github.com/Automattic/themes/pull/3450

**Comment by simison** [comment]
If I understood the issue right, it might get sorted by upstream fix in https://github.com/WordPress/gutenberg/pull/30092
