### ISSUE TITLE
Seedlet Blocks: Contact form missing styling

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3390]
I wasn't sure if this is a Contact block issue, if so I'm happy to move the ticket.

## Steps to replicate
1. On a site with Mayland Blocks active, open the site editor and add a Contact form block to the post content.
2. Add Name, Email, Select or Radio, and Message type fields.
3. Note how the form looks like in the editor (grey background in text fields, numbered list for Select / Radio, Message text field not stretching full width.
4. Save and preview. Note how there's no vertical spacing.
5. Compare to the form on the Maywood demo site: https://maywooddemo.wordpress.com/

Editor view:
![image](https://user-images.githubusercontent.com/4550351/109756320-d4cc3700-7c3b-11eb-9b21-39304e2c91a4.png)

Preview:
![image](https://user-images.githubusercontent.com/4550351/109756367-e8779d80-7c3b-11eb-8072-7d6372843639.png)

You can see this live on: https://fsemaywood.wordpress.com/

**Comment by MaggieCabrera** [comment]
I don't see this happening anymore on the linked site, feel free to reopen if needed!:

<img width="695" alt="Screenshot 2021-09-08 at 16 01 20" src="https://user-images.githubusercontent.com/3593343/132523892-92640080-600e-4552-a56f-dccc0d38fe88.png">
