### ISSUE TITLE
Support Site Theme: Jetpack Search Overlay formatting

### ISSUE THREAD

**Issue by msilbers** [Automattic/themes#3393]
## Steps to replicate

Jetpack search was recently updated, and the update makes the formatting on the support site's search look visually odd. The overlay used to cover the full window and no longer does, and could use some touching up, especially for the text on the left sitting up against the edge of the overlay and the search field.

https://wordpress.com/support/

<img width="830" alt="Screen Shot 2021-03-03 at 11 13 55 AM" src="https://user-images.githubusercontent.com/31680407/109856488-89a82900-7c27-11eb-861d-9412882e4c0f.png">

This is not browser-specific, but due to the update to search I believe. I see the same behavior in Chrome, Firefox, and Safari.

**Comment by msilbers** [comment]
There's also some messy overlapping text when no results are found:

<img width="657" alt="Screen Shot 2021-03-03 at 3 29 07 PM" src="https://user-images.githubusercontent.com/31680407/109868129-45bc2080-7c35-11eb-89b3-e0b372025a27.png">

**Comment by jsnmoon** [comment]
@msilbers: This should be fixed with our upcoming changes for Jetpack 9.6!

**Comment by bluefuton** [comment]
Both of the issues above now appear to be resolved 👍
