### ISSUE TITLE
Seedlet Blocks: Navigation Block font size does not change

### ISSUE THREAD

**Issue by mattwiebe** [Automattic/themes#3395]
## Steps to replicate

1. Have or [create](https://horizon.wordpress.com/new?flags=gutenboarding/site-editor) a new site with Seedlet Blocks and FSE active
2. Add a Navigation block (or select one if it's active)
3. Try to change the font size

https://user-images.githubusercontent.com/195089/109867365-03daac80-7c2c-11eb-95f4-1123646fe306.mov

This is true in both the Site Editor and on the frontend.

## Result

Font size does not change

## Expected

Font size to change

**Comment by eduardozulian** [comment]
Also experience this during an Empathy Flow testing p9b1hy-1Fq-p2

**Comment by pbking** [comment]
The theme's parent (BCB) implements a lot of styles for the navigation in the "custom" space instead of the "style" space.  We should see how much of that should be refactored out to better support this.

**Comment by MaggieCabrera** [comment]
I could not reproduce this (either locally or on dotcom). On an existing site:

FSE:

<img width="1709" alt="Screenshot 2021-07-05 at 14 44 53" src="https://user-images.githubusercontent.com/3593343/124473535-bddf5200-dd9f-11eb-92de-93f4a60e6345.png">

Frontend:

<img width="1748" alt="Screenshot 2021-07-05 at 14 45 33" src="https://user-images.githubusercontent.com/3593343/124473537-bf107f00-dd9f-11eb-958b-b1ab85c0615b.png">

On a new test site created using the horizon flow:

<img width="1832" alt="Screenshot 2021-07-05 at 14 48 36" src="https://user-images.githubusercontent.com/3593343/124473904-28908d80-dda0-11eb-8bfb-6cf774f1c6ed.png">

**Comment by scruffian** [comment]
I also can't replicate this. Please reopen if you still have issues.
