### ISSUE TITLE
Mayland Blocks: Cover block styles not working

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3397]
The Bottom Wave and Top Wave styles of the Cover block are not displaying properly both in style preview and in the editor.

## Steps to replicate
1. On a site with Mayland Blocks active, open the site editor and add a Cover block to the post content.
2. Look at the block settings - notice the style preview does not show a wave.
3. Select Top or Bottom Wave style - note the wave is not visible in the editor.
![image](https://user-images.githubusercontent.com/4550351/109908292-1fab8480-7cf8-11eb-836e-41b55db8a9e6.png)

4. Save and preview site - the wave is visible.
![image](https://user-images.githubusercontent.com/4550351/109908342-35b94500-7cf8-11eb-8821-9ef2b5394c4c.png)

The same thing happens in Seedlet Blocks.

**Comment by MaggieCabrera** [comment]
This has been solved with the latest changes to both themes
