### ISSUE TITLE
Publication: Menu won't display unless widgets are active

### ISSUE THREAD

**Issue by Jstachurski** [Automattic/themes#340]
## Steps to replicate

The site has a main menu selected and in place. However, it is not visible.

<img width="684" alt="screen shot 2018-11-13 at 1 52 26 pm" src="https://user-images.githubusercontent.com/8549154/48435873-6f429c80-e74b-11e8-84f5-c4e2b510fe57.png">

No steps to replicate. The menu was working, now it's not. 

I took a look at recent changes made and it looks like there were some made recently. I'm wondering if this might have been the culprit:

51310-wpcom-themes

@laurelfulford made that change. This happens on the demo site as well. If you remove the widgets, the menu disappears.

* User report: #8029686-hc
* Follow-up ticket: #1564909-zd
* User's site: https://peaceandharmonyministry.org

**Comment by laurelfulford** [comment]
This should now be fixed on WP.com in r51346-wpcom-themes! I'll add a comment to follow up on the ZD ticket.

**Comment by Jstachurski** [comment]
Super fast! Thank you!
