### ISSUE TITLE
Hever - Sub Sub Menu doesn't indent

### ISSUE THREAD

**Issue by susanjanec** [Automattic/themes#3408]
## Steps to replicate

Go to Design > Customize > Menu > Primary and create a menu with a 2 level sub menu.

<img width="296" alt="Markup 2021-03-07 at 10 53 03" src="https://user-images.githubusercontent.com/16828966/110245947-7f41a400-7f33-11eb-8863-036b288099f4.png">

## Result

When creating a sub sub menu (2 level submenu) the menu items don't seem to indent and are showing as a sub menu item.

![Screen Capture on 2021-03-07 at 10-53-50](https://user-images.githubusercontent.com/16828966/110245949-85378500-7f33-11eb-8415-482f49bd65b8.gif)

## Expected

The sub sub menu should appear indented.

* User report: 3798853-zen

**Comment by jordesign** [comment]
Closing this as no longer reproducible. 

Sub menu items are now shown with additional hyphens at the beginning:
<img width="296" alt="Screen Shot 2021-11-24 at 5 32 49 pm" src="https://user-images.githubusercontent.com/1842363/143186943-6ec1560c-4e2f-42a5-8fdf-cd9c58ecf3d2.png">
