### ISSUE TITLE
[Blank Canvas Blocks] Evaluate Blocks

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3413]
Ready the following blocks for Blank Canvas Blocks (A Ponyfill theme)

For each of the following blocks:

Evaluate "Blank Canvas Blocks" against "Blank Canvas"

If something can be achieved with Gutenberg theme.json styling for that block then leverage that first.

If something is expected to be achievable in Gutenberg, adjust the theme.json's "custom" block to express that opinion and add custom SASS to `/sass/blocks` consume those variables expressing that opinion.

 ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/))

- [x] audio ([theamdemo](https://theamdemo.wordpress.com/2019/06/26/gutenberg-audio/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/26/gutenberg-audio/))
- [x] button ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/gutenberg-button/?theme=pub/blank-canvas))([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/gutenberg-button/))
- [ ] calendar
- [x] code ([theamdemo](https://theamdemo.wordpress.com/2020/03/05/gutenberg-misc-formatting/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2020/03/05/gutenberg-misc-formatting/))
- [x] columns ([theamdemo](https://theamdemo.wordpress.com/2018/10/24/gutenberg-columns/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2018/10/24/gutenberg-columns/))

- [x] cover ([theamdemo](https://theamdemo.wordpress.com/2019/06/24/gutenberg-cover/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/24/gutenberg-cover/))
- [x] file ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/gutenberg-file/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/gutenberg-file/))
- [x] gallery ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/gutenberg-gallery/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/gutenberg-gallery/))
- [x] group ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/group/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/group/))
- [x] heading ([theamdemo](https://theamdemo.wordpress.com/2019/06/24/gutenberg-heading/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/24/gutenberg-heading/))
- [x] image ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/gutenberg-image/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/gutenberg-image/))
- [x] latest-comments ([theamdemo](https://theamdemo.wordpress.com/2021/03/11/gutenberg-latest-comments/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2021/03/11/gutenberg-latest-comments/))
- [x] latest-posts ([theamdemo](https://theamdemo.wordpress.com/2021/03/13/gutenberg-latest-posts/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2021/03/13/gutenberg-latest-posts/))
- [ ] legacy 
- [x] list ([theamdemo](https://theamdemo.wordpress.com/2021/03/09/gutenberg-list/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2021/03/09/gutenberg-list/))
- [x] media-text ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/gutenberg-media-text/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/gutenberg-media-text/))
- [x] navigation
- [x] paragraph ([theamdemo](https://theamdemo.wordpress.com/2019/06/24/gutenberg-paragraph/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/24/gutenberg-paragraph/))
- [x] posts-list ([theamdemo](https://theamdemo.wordpress.com/2021/03/13/gutenberg-posts-list/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2021/03/13/gutenberg-posts-list/))
- [x] pullquote ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/gutenberg-pullquote/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/gutenberg-pullquote/))
- [x] quote ([theamdemo](https://theamdemo.wordpress.com/2019/06/24/gutenberg-quote/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/24/gutenberg-quote/))
- [x] search ([theamdemo](https://theamdemo.wordpress.com/2020/10/16/gutenberg-search-block/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2020/10/16/gutenberg-search-block/))
- [x] separator ([theamdemo](https://theamdemo.wordpress.com/2019/06/24/gutenberg-paragraph/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/24/gutenberg-paragraph/))
- [x] slideshow ([theamdemo](https://theamdemo.wordpress.com/2019/06/27/jetpack-slideshow/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/27/jetpack-slideshow/))
- [x] spacer ([theamdemo](https://theamdemo.wordpress.com/2021/03/10/gutenberg-spacer/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2021/03/10/gutenberg-spacer/))
- [x] table ([theamdemo](https://theamdemo.wordpress.com/2020/03/05/gutenberg-misc-formatting/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2020/03/05/gutenberg-misc-formatting/))
- [ ] utilities 
- [x] verse ([theamdemo](https://theamdemo.wordpress.com/2021/03/10/gutenberg-verse/)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2021/03/10/gutenberg-verse/))
- [x] video ([theamdemo](https://theamdemo.wordpress.com/2019/06/25/gutenberg-video/?theme=pub/blank-canvas)) ([bcb demo](https://blank-canvas-blocks.mystagingwebsite.com/2019/06/25/gutenberg-video/))

**Comment by jffng** [comment]
Should we consider certain FSE blocks too e.g. site title & tagline, post meta, tag cloud.

**Comment by pbking** [comment]
I think we should.

Do we have representation of that in Theamdemo?  That would be a healthy addition if not.

**Comment by MaggieCabrera** [comment]
I think we should totally add them to Theamdemo. I did add the "Archives" block to it because I needed it for another issue, so having the rest will be very helpful. This is a list of all the blocks on Theamdemo that need updating: https://github.com/Automattic/themes/issues/3350

**Comment by pbking** [comment]
While evaluating the buttons block I discovered this error which will be a blocker: https://github.com/WordPress/gutenberg/issues/29675

**Comment by pbking** [comment]
Core blocks evaluated, styled and ponyfilled where necessary.

Closing this up; additional singular changes can be opened as needed.
