### ISSUE TITLE
[Blank Canvas Blocks] Add block patterns

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3415]
Evaluate each of the block patterns available in Blank Canvas and determine which can be made available in Blank Canvas Blocks without adding any additional custom CSS to the theme.

**Comment by kjellr** [comment]
> ⚠️ EDIT: I left more up-to-date comments in the PR: https://github.com/Automattic/themes/pull/3514#issuecomment-805844014. 

I took a look at the existing Blank Canvas patterns, and they're looking way off at this point: 

A few obvious bugs: 

- Full-width doesn't go full width, there are other content-width errors throughout.
- The page title is present. (Should I be switching to a different template here? Not sure how that is supposed to work)
- The theme colors used in the original theme don't match up with those in BCB. This makes some text unreadable, and changes a bunch of the button colors. (Might make sense to hardcode the colors in the patterns instead?)
- The spacing between blocks is different or wrong. 
- Font weights don't match. 

Here's [the test content](https://gist.github.com/kjellr/9bacbfda03531d2e2e570dc471906ec8) taken right from the original Blank Canvas. 

I'm going to hold off on testing again until this is in a closer state, but please let me know if you have any design questions about that stuff. 

Blank Canvas|Blank Canvas Blocks
---|---
![dotcomthemes test__p=1040](https://user-images.githubusercontent.com/1202812/112319697-b24e9c00-8c84-11eb-8944-adfb2b787e6d.png)|![dotcomthemes test__p=1040](https://user-images.githubusercontent.com/1202812/112319708-b4b0f600-8c84-11eb-94a4-ae0347a88f25.png)

**Comment by MaggieCabrera** [comment]
Closed via #3514
