### ISSUE TITLE
[Blank Canvas Blocks] Configure Base Typography

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3418]
Configure the HEADER and BODY typefaces for Blank Canvas Blocks including loading them via function.php and configuring them via theme.json

They should match Blank Canvas ([example](https://theamdemo.wordpress.com/2019/06/24/gutenberg-paragraph/?theme=pub/blank-canvas)).

**Comment by jffng** [comment]
We should probably get this in place first so that we don't end up having to configure font-family unnecessarily for many blocks, like I'm doing here: https://github.com/Automattic/themes/pull/3421/files#diff-6b32b96741b2b4b9e621f53f3709cb5e5dcbb41c0467f83a2f30c99577f724b8R184-R186

**Comment by scruffian** [comment]
In the end we didn't need to queue any fonts in functions.php since Blank Canvas doesn't use custom fonts. I feel like we should add that scaffolding in though to make it easier for child themes to override. We should also look at https://github.com/Automattic/themes/pull/3309

**Comment by pbking** [comment]
What do you mean by that scaffolding?  Is that something that can be successfully derived exclusively from theme.json?  Will that be some boilerplate in the function.php to get that kicked off?

----

In the change we also eliminated the header font configuration.  The 'body' font looks to the --font-base variable but not the --font-headings for headers.

If that font selection tool won't be used with Blank Canvas than that's cool and we can probably eliminate the usage of that --font-base variable as well.

Otherwise we might want to include the headings variable, even though it's the same font (by default) so that the headings are (bulk) configurable.

**Comment by scruffian** [comment]
I'm thinking about the boilerplate code we need to load the font files themselves, which is in functions.php

**Comment by MaggieCabrera** [comment]
> I'm thinking about the boilerplate code we need to load the font files themselves, which is in functions.php

Things like this are why BC needs to be a parent theme and not a plugin. It's very hard to have it be **just** CSS.

**Comment by scruffian** [comment]
I made a suggestion for how to achieve this here: https://github.com/Automattic/themes/pull/3447

**Comment by scruffian** [comment]
Closed by #3447
