### ISSUE TITLE
[Blank Canvas Blocks] Configure Alignment & evaluate alignment polyfill

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3419]
Ensure that the alignment ponyfill that exists is appropriate and correct.

Ensure that the "full/wide" values in the theme.json match the opinion of blank-canvas.

**Comment by pbking** [comment]
This was (at least partially) addressed in #3449.  Editor styles still do not reflect the view and to finalize that work will need to be accomplished.

There was still some [ongoing discussion](https://github.com/Automattic/themes/pull/3449#discussion_r591921696) of "default block alignment in wide/full group blocks we may need to revisit.

Not closing this until we understand both the timeline and ramifications of ["Rethink FSE alignments"](https://github.com/WordPress/gutenberg/pull/29335). It may eliminate most of the custom alignment styles OR it might be a while coming (hope not) and the work we have done thus far will need to stand.

**Comment by pbking** [comment]
A few notes about an experiment combining BCB with "Rething FSE alignments"

**Comment by jffng** [comment]
Closed by #3459 mostly.
