### ISSUE TITLE
Alves: "Launch your site" banner obscures mobile menu

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3475]
## Steps to replicate
1. Using a mobile device create a new site and select Doyle starter design during signup. Do not launch the site.
2. Preview the site and click on the "Menu" button to open the mobile nav menu.
3. Note that the menu is hidden below the "Launch your site banner". To view the menu (and close it) the banner needs to be dismissed first.

**Expected behavior:**
I think in this instance the mobile menu overlay should either appear over the banner (cover it), or below it (the same way site content is pushed down by the banner).

Here's a quick video: https://cloudup.com/cPNVvpzD2bF

**Device/Browser**
iOS 14.4.1 / Safari

Found through my own testing.

**Comment by jordesign** [comment]
Closing this as no longer reproducible with the new 'Coming Soon' banner
