### ISSUE TITLE
Twenty Twenty: Quote Block is left-aligned in the backend (editor) but is centered on the frontend

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#3484]
## Steps to replicate

Add a [Quote Block](https://wordpress.com/support/wordpress-editor/blocks/quote-block/) into a Page or Post

## Result

Quote Block is left aligned

![](https://d.pr/i/u23Hor+)
_Link: https://d.pr/i/u23Hor_

## Expected

Quote Block should be centered, just like it's appearing on the front-end:

![](https://d.pr/i/2naj3U+)
_Link: https://d.pr/i/2naj3U_

#dogfooding

**Comment by zdenys** [comment]
If I understand correctly, the responsible CSS may be this one:

```
.editor-styles-wrapper .wp-block-quote {
    margin: 20px 0;
}
```

When I remove it, the Quote Block appears aligned as expected:

https://user-images.githubusercontent.com/39308239/135291951-1a890f8d-2199-41b6-b5ec-f4d5495c7ea4.mov

**Comment by jeffikus** [comment]
I've added this one to the board for next week. I'll reassess the items listed [here](https://github.com/Automattic/themes/milestone/112) as well. Perhaps we need to do a bug scrub again on these items.

**Comment by danieldudzic** [comment]
PR: D68212-code

Co-authored-by: @mikachan

**Comment by scruffian** [comment]
Fix looks good. Do we need to push it back up to core too?

**Comment by danieldudzic** [comment]
@scruffian Thanks for the reminder.

It seems that the Core version doesn't need this, as it doesn't specify the left and right margins at all:
```
.editor-styles-wrapper .wp-block-quote {
	border-color: #cd2653;
	border-style: solid;
	border-width: 0 0 0 2px;
	margin-top: 20px;
	margin-bottom: 20px;
	padding: 5px 0 5px 20px;
}
```

**Comment by scruffian** [comment]
I bet that's because core has already fixed it, so we should change our fix to align with theirs and also consider updating the theme from core.

**Comment by jeffikus** [comment]
We need to update the theme to be in line with core.

**Comment by danieldudzic** [comment]
Sync update: D68971-code

**Comment by scruffian** [comment]
This has been fixed
