### ISSUE TITLE
Google Apps shortcode not aligning in 2021

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#3496]
PROBLEM:
The Custom HTML block on sDW2C-test-p2 shows Google Apps aligned to the left. It only happens on the 2021 theme

WHAT I FOUND:
* They are using a GoogleApps shortcode in a custom HTML block like this - https://wordpress.com/support/google-docs/

WHAT I DID:
* On a test site I tried 2021 with the same embed code and it also goes directly to the left of the page - (screenshot) https://d.pr/i/Mr4mhO
* Tried 2 other different themes and it worked fine. Although on 2020 it shows in a long vertical block (screenshot) - 
https://d.pr/i/aP9ol9

## Expected
The block to align with the content of the page

* User report: 3827558-zen

**Comment by kathrynwp** [comment]
User also reported in Core Trac: https://core.trac.wordpress.org/ticket/52828

**Comment by kathrynwp** [comment]
Closing, as this is being handled in Core Trac.
