### ISSUE TITLE
illustratr theme: Sections on the home page overlapping

### ISSUE THREAD

**Issue by Thelmachido** [Automattic/themes#3500]
## Steps to replicate

1. If you add the [ILLUSTRATR theme](https://illustratrdemo.wordpress.com/)  to your site, some of the sections on the home page will be cutoff/overlapping - https://d.pr/i/APQo8v. 

<img width="1540" alt="Screen Shot on 2021-03-20 at 14-58-26" src="https://user-images.githubusercontent.com/41231764/174938250-e6d41b0f-e162-42ea-b80b-bb14c12b910d.png">

## Expected

Expected content to fit properly on the page. 

* User report: [26219287-hc]
* Follow-up ticket: [3839344-zen]

**Comment by silvio-meter** [comment]
The issue seems to affect only Columns Blocks with Wide Width alignment:


![Optional alternative text if image doesn't load](https://groovytestingsite.files.wordpress.com/2021/03/screenshot-on-2021-03-25-at-12-05-13.png)
--

Changing the alignment to Full Width works as a temporary fix.

**Comment by bobmatyas** [comment]
I investigated this issue and it seems to now only affect columns within other blocks (i.e. cover or group blocks).
