### ISSUE TITLE
Varia children, Blank Canvas, Seedlet, Spearhead - Mobile menu same page jump links don't work

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#3520]
Certain themes have a mobile menu that overlays the content of the page. Page jumps to anchor links on the same page don’t work within the mobile menu. The URL changes in the browser bar but the menu doesn’t close and the page doesn’t scroll down.

## Steps to replicate

* Activate Hever on a test site
* Add a heading lower on a page with an anchor link. 
* Create a custom link in the menu to this anchor. `https://example.blog/#anchor`
* Test the link on the desktop and mobile menu (from the same page the anchor is on)

## Result

On mobile the URL changes but the menu doesn’t close and the page doesn’t scroll down.

Desktop:

![https://d.pr/i/GGPrAc](https://d.pr/i/GGPrAc+)

Mobile:

![https://d.pr/i/oITxS7](https://d.pr/i/oITxS7+)

## Expected

Menu should close and jump down the page like desktop.

## Notes

Tested Firefox and Chrome on Mac, Safari on iOS.

I’ve found this issue on the following themes:

`Hever, Barnsbury, Dalston, Mayland, Rivington, Alves, Morden, Blank Canvas, Seedlet, Spearhead`

The main Varia parent theme as well as these Varia children themes have different styles for the mobile menu and the scroll does work correctly. 

`Maywood, Balasana, Shawburn, Exford, Rockfield, Stratford, Coutoire, Stow, Leven, Brompton, Redhill`

In case it helps `Twenty Twenty-One` has a similar overlay style for the mobile menu but it does function correctly for the anchor links.

This only happens for jump links on the same page. They work correctly when you try the same link from another page.

* User report: 3840299-zd-woothemes

As a temporary workaround I found that if you create a short link https://bitly.com of the URL `https://example.blog/#anchor` and use that as your custom link it will work.

**Comment by goblinartificer** [comment]
3897030-zen as well, using Barnsbury

**Comment by rachelwinspear** [comment]
Another report #3901556-zen - Hever theme

**Comment by lizswafford** [comment]
Another report #3934935-zen, using Barnsbury

**Comment by Robertght** [comment]
Another one in #21701497-hc using Hever

**Comment by isocialtish** [comment]
Another user report using Hever 29678721-hc

**Comment by sajmes** [comment]
Another report here for Hever 29698414-hc (same user as [this comment above](https://github.com/Automattic/themes/issues/3520#issuecomment-844301943)). 

Was able to offer a workaround by unchecking 'display mobile menu on the side' in customizer > menus > mobile settings. Menu is now functioning as expected on mobile for user and when I test on Safari on iOS.

**Comment by blackjackkent** [comment]
Opened a diff to fix this at D62296-code.

**Comment by kwight** [comment]
Fixed by @blackjackkent in D62296-code

**Comment by nicolynramos** [comment]
I'm seeing this same behavior again- 5204564-zd
Able to reproduce on all FSE themes with overlay menu enabled, no change on mobile vs desktop

**Comment by nicolynramos** [comment]
Noticed it's only on FSE/Blockbase themes, closing this report out and will create new one.
