### ISSUE TITLE
Argent: Guide for Project Gallery Carousel Needs Updating

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/themes#3531]
Line to be updated: 

```
2 . Insert an image gallery from the editor. The position of a gallery inside the project doesn’t matter; the first gallery will always be displayed in a carousel directly below the project title.
```

The guide seems to work for Classic Editor. While we found a workaround to use a Classic Block - it would also be helpful for users if it's clear that the Gallery must be added in a Classic Block (or have the theme updated for Gallery Block instead). It also seems like the feature only works for "Tiled Mosaic" if used on Classic Block. 

## Steps to replicate

![Alt text](https://d.pr/i/FYe76N/xRlYJRFmzR+)

Step # 2 says to add an **Image Gallery** to display the Carousel in full-width. 
Add "Gallery" block with images. 

## Result

Full-width Carousel won't display, instead it will only display the Gallery block created. 

![Alt text](https://d.pr/i/mwyslU/U8C7z2JAyZ+)

## Expected

The gallery will display in full-width carousel like this: 

![Alt text](https://d.pr/i/QXvEGW/cVRiDx2Hl3+)

**Comment by thesacredpath** [comment]
This is the follow-up ticket with the user. I have let them know to use the classic block for now. I would vote for an update to the theme to make the gallery blocks work and display the slider rather than updating the docs to indicate using classic block.

I don't know though how near retirement this theme is, so up to theme developers on which way to go.

Follow-up ticket: 3852319-zen

**Comment by jp-imagines** [comment]
Had a user that was very confused by this issue in 36822353-hc. 
Adding a Gallery _block_ just forces the images to appear in full size, left aligned, at the top of the project. Switching to a Classic block gallery resolves things, but there's no way to know that's a requirement (and ideally the Classic block shouldn't _be_ a requirement these days).

**Comment by Robertght** [comment]
For now, I've updated the guide to say it needs to be used with the Classic block, as I don't know when/if this will be fixed.

Opened a new issue here: https://github.com/Automattic/themes/issues/6528
