### ISSUE TITLE
Blank Canvas Blocks: Remove hover states for outlined buttons with a custom color

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3538]
The original version of Blank Canvas (and Seedlet) removes the hover treatment for outlined buttons when they have a custom color assigned. 

We need to replicate that for Blank Canvas Blocks in order to prevent broken-looking button hovers. 

Blank Canvas|Blank Canvas Blocks
---|---
![hover-bc](https://user-images.githubusercontent.com/1202812/112650506-d4315580-8e21-11eb-94a6-04cc18c0b152.gif)|![hover-bcb](https://user-images.githubusercontent.com/1202812/112650518-d5fb1900-8e21-11eb-86a1-b0038411d704.gif)

Related: https://github.com/Automattic/themes/issues/3110

**Comment by jffng** [comment]
Closed by #3556
