### ISSUE TITLE
Dyad 2: Featured Image in Posts are unstable in Microsoft Edge

### ISSUE THREAD

**Issue by ezraalamsyah** [Automattic/themes#354]
## Steps to replicate

Open one of the posts with Featured Image set with Chrome and Microsoft Edge. For example: https://dyad2demo.wordpress.com/2015/05/19/this-is-a-sticky-post/

## Result

When opened in Chrome, scrolling up and down the post will leave the Featured Image as static. However, when opened in Microsoft Edge, the Featured Image is jumpy and unstable.

## Expected

The Featured Image should be stable and static as well in Microsoft Edge

* User report: 8094630-hc
* User's site: [#](https://href.li/?http://sociallyweb.wordpress.com)

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
