### ISSUE TITLE
Didi: Bold text displays normal in Chrome

### ISSUE THREAD

**Issue by daria2303** [Automattic/themes#3545]
## Steps to replicate

Install Theme Didi
Create a Page
Set text to Bold https://d.pr/i/otYCLk

## Result

Texts set up to bold in Chrome display as normal, in Safari correctly as Bold
https://d.pr/i/F5znxS

## Expected

Bold text displays as bold in Chrome

* User report: https://mc.a8c.com/support-stats/happychat/transcript.php?id=28698493
* Follow-up ticket: https://woothemes.zendesk.com/agent/tickets/3862980

**Comment by susanjanec** [comment]
I landed on this ticket and when viewing the page, the text mentioned in Safari does appear to show bold - https://d.pr/i/RSqQyf

Wanted to confirm before replying to the user to see if this is indeed a bug in Safari.

**Comment by kristarella** [comment]
I can't replicate. Safari and Chrome look the same to me. The difference between bold and normal text is present in both.

Letter spacing is a bit different in Safari, but bold seems the same https://d.pr/i/LVhK21

**Comment by daria2303** [comment]
I think the issue may be in the display - in Chrome the bold is hardly visible in relation to Safari. 
Maybe I didn't get that - sorry for bothering if that's the case.
User got help in another chat and ticket is closed, so I am closing here too.

**Comment by daria2303** [comment]
It looks like there is an issue actually with bold in Chrome on Mac: https://stackoverflow.com/questions/37793086/why-is-the-font-style-bold-not-correctly-applied-in-chrome-on-this-website/60799683#60799683
