### ISSUE TITLE
Blockbase: Add default styles for comments block.

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#3546]
We need to add default styles for the Post comments and Post comments form blocks for BCB and children:

Logged in:

<img width="729" alt="Screenshot 2021-03-29 at 17 23 05" src="https://user-images.githubusercontent.com/3593343/112859851-86338080-90b3-11eb-903c-a267f72a246d.png">

Logged out:

<img width="725" alt="Screenshot 2021-03-29 at 17 24 26" src="https://user-images.githubusercontent.com/3593343/112859959-a8c59980-90b3-11eb-80b7-ba15f4c3a5a8.png">

**Comment by jffng** [comment]
Partially addressed in #3553, also depends on https://github.com/WordPress/gutenberg/pull/30382

**Comment by scruffian** [comment]
This is unblocked now

**Comment by jffng** [comment]
Is there a design target for this now that the above PRs were merged? cc @kjellr 

Current state:
<img width="729" alt="Screen Shot 2021-05-27 at 11 35 30 AM" src="https://user-images.githubusercontent.com/5375500/119855332-a9698900-bec6-11eb-9219-e9031cb45fbe.png">

**Comment by kjellr** [comment]
Not yet. In general, I think the sorts of font size changes we made in Quadrat should be moved back here, but I'll take a closer look.
