### ISSUE TITLE
Textbook: Unable to have full-width static homepage

### ISSUE THREAD

**Issue by richardmtl** [Automattic/themes#355]
This came up in chat 5939376-hc

With Textbook, the documentation says "TextBook comes with two widget areas. The right sidebar widget area lives on the right side of all posts, pages, and archives"; however, if I set a Static Homepage, I'm unable to show a full-width version without getting rid of all of my widgets. Based on that text, it feels like there should be a full-width template available for a static homepage (unless it's counted as a "page"), but I wasn't able to find one. Is there a full-width template? If there isn't, then my  chatter requests one. :)

**Comment by laurelfulford** [comment]
Hey @richardmtl! Textbook does not come with a full-width template. 

Would widget visibility work for this customer, if they just wanted to hide the widgets on the front page? We can also look into adding a template, but with just the one request, it will be a lower priority. 

Also, can you please include the shortform links to anything we need to follow up with here (eg. 12345-zd, or 12345-hc)? Thanks!

**Comment by laurelfulford** [comment]
Hi @musicmegga!

> I think widget visibility would work.

Great! Let's give it a shot and find out :) It's a setting that you can turn on yourself. I'm not sure if you have a WordPress.com site, or a self-hosted site, so I'll run through how to get to it on both:

**WordPress.com**

On WordPress.com, widget visibility is a built-in setting. If you navigate to My Site> Customize > Widgets and add or edit a widget there, you should see a Visibility button in the bottom-right corner of the open widget:

![image](https://user-images.githubusercontent.com/177561/50530104-86490e00-0aaf-11e9-85b4-6051eaae755a.png)

Clicking it will open a little panel where you can pick whether to Show or Hide the widget in certain cases. To hide on the front page, you'd pick "Hide" if "Page" is "Front Page":

![image](https://user-images.githubusercontent.com/177561/50530126-a973bd80-0aaf-11e9-90e6-12465d02bb31.png)

... then click 'Publish' to save the setting, and the widget will be visible on all pages except the front page.

**Self-hosted WordPress site**

On a self-hosted WordPress site, the same widget visibility feature is available as part of the [Jetpack plugin](https://en-ca.wordpress.org/plugins/jetpack/). 

Once the plugin is installed and activated, you still may need to activate the widget visibility module.  There's a page on the Jetpack site here that explains the steps with some screenshots -- it's a bit odd, so they're helpful! 

https://jetpack.com/support/control-jetpacks-modules-on-one-page/

Or you can update the following URL to use your site's web address to go to the page directly:

[http://www.yourwebsite.com]/wp-admin/admin.php?page=jetpack_modules  

Once there, the module that needs to be activated is Widget Visibility, well near the bottom: 

![image](https://user-images.githubusercontent.com/177561/50530271-adeca600-0ab0-11e9-9343-2be2ec175a6a.png)

Once activated, you should see the same "Visibility" button when you edit a widget in the Customizer, and be able to use the same settings as you would on WordPress.com to hide widgets just on the front-page: 

![image](https://user-images.githubusercontent.com/177561/50530292-e7bdac80-0ab0-11e9-9164-db0ec3e96e59.png)

I know this is a bit of a wall of text, so just let me know if you have any questions about the above!

**Comment by musicmegga** [comment]
Thanks, Laurel. This worked. It was a little confusing to "access all modules" but Widget Visibility is on and I added the rule to hide sidebar widgets if Page is Front Page. 
Self-hosted Site is located at coachapproachtraining.com
Mary Ellen

**Comment by laurelfulford** [comment]
@musicmegga Great, I'm glad that worked! :) (And that you found the setting -- I know it's pretty buried!)

I'm going to close this ticket for now, but it can be reopened if we get more requests and need to revisit this enhancement.
