### ISSUE TITLE
Orvis: Conflict on portfolio items when aligning images with Gutenberg

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#356]
## Steps to replicate

1. Activate the Orvis theme and Gutenberg
2. Create a portfolio item and add images to its content
3. Use the "align center" option:
 
![screen shot 2018-11-16 at 15 12 12](https://user-images.githubusercontent.com/3696121/48644937-1de81680-e9b2-11e8-9475-c94b771a8281.png)

4. Publish the changes

## Result

The space between images is removed:

![screen shot on 2018-11-16 at 15 13 53](https://user-images.githubusercontent.com/3696121/48644991-496b0100-e9b2-11e8-8498-1ad1c737e327.png)

## Expected

The images to keep the same space they have when they are not aligned:

![screen shot on 2018-11-16 at 15 15 38](https://user-images.githubusercontent.com/3696121/48645058-7e775380-e9b2-11e8-9439-1f6f76969298.png)

For a better context please see p1542393500598200-slack-themes.

* User report: 1571243-zen
* User's site: https://domainspractice17.blog/portfolio/project-1-2/ (My own test site)

**Comment by laurelfulford** [comment]
Orvis's current behaviour on portfolio projects -- using JavaScript to separate text from images into two columns -- doesn't feel like a great fit for the new block-based editor. You can't preview how it looks, and the block based editor makes things like creating columns in the editor itself possible.

Given that there's a work-around in this case (not centring the image), and that trying to get the block based editor and this JavaScript behaving nicely together could cause a lot of headaches, I'm going to mark this one as a `wontfix`. 

@AtrumGeost it looks like the ZD ticket is closed, so I can't add a comment there. Could you please follow up with the user if needed? Thank you!
