### ISSUE TITLE
Post-meta template-part doesn't work in index.html block template.

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3581]
The template part `post-meta.html` isn't working when you load a page with index.html.

Change the theme to 'Seedlet Blocks (BCB)' and set the homepage to be "your latest posts" so that index.html is used for the home page.

Note that `Template part has been deleted or is unavailable: post-meta` is shown (however the template part is defined in the template).

**Comment by jffng** [comment]
Related — https://github.com/WordPress/gutenberg/issues/28814 and https://github.com/WordPress/gutenberg/pull/30416

**Comment by pbking** [comment]
This has indeed been addressed (presumably by [30416](https://github.com/WordPress/gutenberg/pull/30416))
