### ISSUE TITLE
Seedlet Blocks: Style Comment Block

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3582]
I don't believe this was ever done for BCB.

Current:
![image](https://user-images.githubusercontent.com/146530/113051130-a32f8880-9173-11eb-840b-f748836eda1c.png)

Target:
![image](https://user-images.githubusercontent.com/146530/113051164-ab87c380-9173-11eb-8325-b8a9dbf96cf2.png)

**Comment by danieldudzic** [comment]
We should probably style this, accounting for the following PR getting merged, right: https://github.com/WordPress/gutenberg/pull/30382 ?

**Comment by jffng** [comment]
PR for BCB here: https://github.com/Automattic/themes/pull/3553, but I think Seedlet Blocks needs more specific comment form CSS.
