### ISSUE TITLE
Site Logo is not centered

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3583]
If you go to the Site Editor and assign the site logo it will be correctly rendered in the Site Editor.

However when rendering the page the logo is aligned left.

Current:
![image](https://user-images.githubusercontent.com/146530/113051642-35d02780-9174-11eb-8b03-e4d59bbae75a.png)

Site Editor:
![image](https://user-images.githubusercontent.com/146530/113051704-47193400-9174-11eb-9ee3-e9e83008550c.png)

**Comment by jffng** [comment]
Fixed in https://github.com/Automattic/themes/pull/3608
