### ISSUE TITLE
Style Latest-Post block

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#3595]
Target: 
![image](https://user-images.githubusercontent.com/146530/113172090-1984c700-9216-11eb-8cbb-902d4caedf4f.png)

Current:
![image](https://user-images.githubusercontent.com/146530/113172197-328d7800-9216-11eb-9e41-855fbfda1e27.png)

**Comment by jffng** [comment]
In Seedlet, we create this using a [block style variation](https://github.com/Automattic/themes/blob/4e17dacd511ef01cc4a87f508c7bfbb615733026/seedlet/assets/sass/blocks/latest-posts/_style.scss#L98-L132). 

Is a block style variation still the way to go? 

Two alternatives would be creating a block pattern or making it the default style for the latest posts block.

**Comment by pbking** [comment]
Block Style created, and a Block Pattern with that style also added.  I think all the bases are covered.
