### ISSUE TITLE
Hever: Extra white space / margin in the Block editor 

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#3599]
## Steps to replicate

1. Activate Hever on a Simple site
2. Open any page for editing and observe

## Result

<img width="1701" alt="Markup 2021-04-01 at 09 41 45" src="https://user-images.githubusercontent.com/25105483/113265504-7fd01f00-92d4-11eb-9d1f-015be9d5ecf5.png">

## Expected

The editor is loaded correctly.

---

It looks like the issue could have been triggered by the recent Gutenberg update. For now only the Simple sites are affected.

* User report: 3872131-zd-woothemes

**Comment by kavyagokul** [comment]
Another report in 28760447-hc

Apart from the layout, the width and alignment options are also gone.

**Comment by Sandkorner** [comment]
I had a user with the Balasana theme. Everything was pushed to the left in the editor. On live the site looked fine. 
Might be connected. (3872248-zen)

**Comment by galakhyati** [comment]
Similar issue with a site on Hever theme and using Columns block where the Columns block was missing the alignment option. (28761314-hc)

**Comment by WunderBart** [comment]
> It looks like the issue could have been triggered by the recent Gutenberg update. For now only the Simple sites are affected.

Gutenberg on Simple sites has been reverted to v10.2.0 because of this issue. Please follow p1617267873288500-slack-C7YPUHBB2 for more info.

**Comment by fullofcaffeine** [comment]
This was fixed in D59674-code + the release of GB 10.3.1 in WPCOM simple sites.
