### ISSUE TITLE
Floral: featured images not visible in Blog Posts block or Post Carousel block on published posts or pages

### ISSUE THREAD

**Issue by lettergrade** [Automattic/themes#3609]
## Steps to replicate

1. Activate Floral theme.
2. Add a Blog Posts block or Post Carousel block to post or page edit screen
3.  For Blog Posts block, enable 'Show Featured Image' setting. (Featured image is default behaviour for Post Carousel, so no need.)
4. See your featured images show up in both blocks in the edit screen: [screen1](https://snipboard.io/I1ZzP5.jpg) and [screen2](https://snipboard.io/HJWrUh.jpg)
5. Preview or Publish and view your post. 

## Result

No featured images show on Blog Posts block: https://snipboard.io/0NRjJF.jpg 
Post Carousel won't show at all, as it's so dependent on featured image: https://snipboard.io/NkluHD.jpg

## Expected

I expected featured images to show on the Blog Posts block, and for the Posts Carousel to show.

I replicated on a test site and changed the theme on the site to test this behaviour. Featured images showed up as expected using:

Twentytwentyone: [screen1](https://snipboard.io/6qPEVj.jpg) and [screen2](https://snipboard.io/kTFJ3I.jpg)
Spearhead: [screen1](https://snipboard.io/nL2cGp.jpg) and [screen2](https://snipboard.io/VgdZDc.jpg)

## Reported in

3872936-zen

**Comment by lettergrade** [comment]
Just wanted to note that it was mentioned in p1617314904228300-Slack-themes

**Comment by danieldudzic** [comment]
@lettergrade Thanks for reporting!

I can't replicate the Blog Posts block issue:
<img width="1780" alt="blog_posts" src="https://user-images.githubusercontent.com/905781/114020494-f12d4600-986f-11eb-9034-24809c015c7d.png">

I was able to replicate the Post Carousel issue - but it also occurs for me with Twenty Twenty One - there seems to be a JS error: 
<img width="1774" alt="carousel" src="https://user-images.githubusercontent.com/905781/114021421-f76ff200-9870-11eb-9fce-af98bef7858a.png">

**Comment by formosattic** [comment]
I couldn't replicate either. And Floral is a now a retired Premium theme. Seems safe to close this?

**Comment by erricgunawan** [comment]
Just noting that this might be related to:

https://github.com/Automattic/newspack-blocks/issues/399

If the "Display on pages" option in the Customizer > Content Options are enabled, the images will be displayed.
