### ISSUE TITLE
Blank Canvas - Customizer Colors Not Applying Correctly

### ISSUE THREAD

**Issue by ersatzpenguin** [Automattic/themes#3614]
## Steps to replicate

1. Activate Blank Canvas on a site (simple or atomic—it seems to affect both).
2. Set as custom color in Customizer—particularly, the custom secondary color.
3. Set some text in the editor to have this secondary color.
4. View the front-end version of the page.

## Result

The secondary color set in the customizer is overridden by the theme's default secondary color. Apparently due to this CSS in the theme which is using `!important`:

`.has-secondary-color {
    color: #007cba !important;
}`

Example:
![image](https://user-images.githubusercontent.com/10101587/113450934-89d24a80-93c6-11eb-8b2f-7779e8e3fbf2.png)

Editor settings:
![image](https://user-images.githubusercontent.com/10101587/113451427-94411400-93c7-11eb-8cd2-8efcf5f36105.png)

## Expected

I expected the secondary color set in Customizer to apply to the site, and to the editor. It looks like we've already reported the color not showing in the editor here: https://github.com/Automattic/themes/issues/3316 but this seems like a separate issue since it also impacts the front-end.

* User report: p1617391544285300-slack-C03TY6J1A
* Follow-up ticket: N/A

**Comment by jffng** [comment]
Hi @ersatzpenguin — we just deployed a fix for this on simple sites D59701-code, would you mind verifying if it addressed this issue? Thank you!

**Comment by jffng** [comment]
https://href.li/?D59960-code is being proposed as a potential fix for this cc @MaggieCabrera

**Comment by jffng** [comment]
D59960-code is being proposed as a potential fix for this cc @MaggieCabrera

**Comment by MaggieCabrera** [comment]
@jffng after talking to @scruffian we thought that that Diff is not worth pursuing and we should focus on just a fix for BC/Seedlet/Varia

**Comment by scruffian** [comment]
I believe this is fixed on Simple sites. There is a fix for Atomic sites here: 24-gh-Automattic/custom-colors

**Comment by daria2303** [comment]
I got a case where palette update is not visible is not reflected in the editor (it's old one, not black)
29302961-hc
3948055-zd-woothemes

**Comment by scruffian** [comment]
This should now be fixed on Atomic sites.
