### ISSUE TITLE
Blocks aligned right in editor but are properly aligned when pages are previewed

### ISSUE THREAD

**Issue by danmaze** [Automattic/themes#3618]
## Steps to replicate

Once the theme is installed on a test site:

- Go to My Sites > Pages > Home to edit the demo Home page.
- Scroll down to the section for scheduling a consultation or the testimonials section.

See screenshots below:

![schedule-session-editor](https://user-images.githubusercontent.com/50293775/113725392-2cead300-96eb-11eb-86f9-4d5c1a0deea1.JPG)

![testimonials-editor](https://user-images.githubusercontent.com/50293775/113725440-38d69500-96eb-11eb-9516-b1e960c01a41.JPG)

## Result

While the blocks are properly centralized and take up the full width when previewing the page, they are aligned right in the editor as shown in the screenshots above. See the screenshots below showing the sections with proper alignment when the page is previewed:

![schedule-session-preview](https://user-images.githubusercontent.com/50293775/113725781-910d9700-96eb-11eb-8d06-2a8e5b943048.JPG)

![testimonials-preview](https://user-images.githubusercontent.com/50293775/113725811-9965d200-96eb-11eb-9136-f1b4867697ac.JPG)

## Expected

The editor should correctly reflect the selected options and should equally mirror the final result displayed on the previewed page. 

* Related Zendesk ticket: 3883570

**Comment by danmaze** [comment]
**Update:**

Initially replicated the issue with the Brompton theme but the user says they're experiencing this on all the themes they've tried. Confirmed that this is also the case with the Alves theme. So, it appears to be a broader issue, perhaps with the editor itself.

**Comment by fresatomica** [comment]
@danmaze were they/you testing the same Brompton's demo page on another theme, rather than creating a brand new one?

**Comment by danmaze** [comment]
@fresatomica It looks like they were testing the same demo page on another theme. I, on the other hand, tested Alves' demo home page (a different demo page on another theme). Same thing.

**Comment by Robertght** [comment]
I'm not able to replicate this anymore. Closing.
