### ISSUE TITLE
Twenty Twenty-One: Headings unreadable on mobile

### ISSUE THREAD

**Issue by azollafox** [Automattic/themes#3619]
## Steps to replicate

1. Open https://twentytwentyonedemo.wordpress.com/ on an mobile device
2. Scroll down a bit to try to read all the Heading text

## Result

Long words get cut off
![](https://blogmcblogghome.files.wordpress.com/2021/04/wp-1617720149585.png)
(Image link: https://blogmcblogghome.files.wordpress.com/2021/04/wp-1617720149585.png )

## Expected

I expected our theme demo content to be fully readable

**Comment by NoHopeRadio** [comment]
Another report in this ticket: 3944592-zen

**Comment by danieldudzic** [comment]
I have added a fix via r59017 

Review request: @MaggieCabrera @jeffikus

**Comment by pbking** [comment]
This change has been deployed.  Further changes are needed to also include HUGE font size.  (Update forthcoming here.)

**Comment by pbking** [comment]
A further change including "HUGE" font size can be found here: D62262-code using the size:
`'min(max(38px, 6vw), 96px)',`

Before:
![image](https://user-images.githubusercontent.com/146530/120671662-9bd07800-c45f-11eb-99bb-03742dcdee1b.png)
![image](https://user-images.githubusercontent.com/146530/120671780-b73b8300-c45f-11eb-9b96-1c82dfd14182.png)


After:
![image](https://user-images.githubusercontent.com/146530/120671339-498f5700-c45f-11eb-834b-998dcfe572c0.png)
![image](https://user-images.githubusercontent.com/146530/120671379-5318bf00-c45f-11eb-80cc-e2f5cca4adef.png)

**Comment by pbking** [comment]
A design eye would be appreciated with these font size changes: @kjellr

**Comment by kjellr** [comment]
This seems fine — you should consider sharing this change upstream to the main theme.

**Comment by pbking** [comment]
Good that you mentioned that @kjellr.  We had that exact conversation while we were doing the work...

Thank you for the eyes on it.

**Comment by danieldudzic** [comment]
This has been now reviewed and deployed
