### ISSUE TITLE
Maywood: Cover Block aligns text right in editor

### ISSUE THREAD

**Issue by rachelwinspear** [Automattic/themes#3626]
## Steps to replicate

1. Activate the theme Maywood, add home layout for Maywood
2. Cover Block content appears to the right in the editor, but does show correctly in page preview and front end.

Editor: 
![Screenshot](https://d.pr/i/qtA80l+)

Frontend:
![Screenshot](https://d.pr/i/zWXAcM+)

## Result

Content within the editor can not be moved to the left in the Cover Block.

## Expected

I expected the alignment of the text to be as shown on frontend, not to the right of the page within the editor.

Simple site / Personal plan
Gutenberg: v10.3.1-with-autocomplete-fix
CoBlocks: 2.5.3
Editing Toolkit: 3.3976
WP AMP: 1.4.2

Possible related case: https://github.com/WordPress/gutenberg/issues/25937

* User report: #3884334-zen

**Comment by rachelwinspear** [comment]
Another report of text in Cover Block loading to the right in Editor, this time in theme Barnsbury: #3883437-zen

**Comment by danmaze** [comment]
@rachelwinspear I opened a similar issue yesterday: #3618, User report: #3883570-zen. I'm thinking we should reconcile these issues and perhaps, merge them into one.

**Comment by Robertght** [comment]
I'm not able to replicate this anymore.
