### ISSUE TITLE
Twenty Twenty: Pullquote Block has wrong font family, weight, and size in the Editor vs frontend

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#3628]
## Steps to replicate

1. Add a [Pullquote Block](https://wordpress.com/support/wordpress-editor/blocks/pullquote-block/) to a post/page
2. Preview the post/page
3. (Optional/additional) Set the Pullquote block width to `Wide width` or `Full width`

## Result

The font family, weight, and size on the frontend is different from the one in the backend (editor)

Backend | Frontend
--- | --- 
![](https://d.pr/i/UdTMeE+) _Link: https://d.pr/i/UdTMeE_ | ![](https://d.pr/i/hUbsP0+) _Link: https://d.pr/i/hUbsP0_

## Expected

See the same font on frontend and backend

#dogfooding

**Comment by danieldudzic** [comment]
This has been now fixed via r58999
