### ISSUE TITLE
Twenty Twenty-One: Mobile menu transition is not smooth

### ISSUE THREAD

**Issue by devNigel** [Automattic/themes#3631]
## Steps to replicate

1. Switch to Twenty Twenty-One theme or access the theme demo https://twentytwentyonedemo.wordpress.com/ on mobile view.
2. Open and close the mobile menu by clicking on the hamburger icon.

Screen recording: https://d.pr/i/RNhn4v

## Result

The mobile menu looks glitchy upon closing.

## Expected

The transition should be smooth when closing the mobile menu.

* User report: 28864058-hc
* Follow-up ticket: 3890196-zen

**Comment by devNigel** [comment]
User asked to be informed once the issue is fixed.

**Comment by kathrynwp** [comment]
@devNigel Have you tested to see if this can be replicated on a self-hosted site? If so, this issue should be reported in [Core Trac](https://core.trac.wordpress.org/query?status=!closed&component=Bundled+Theme) if it hasn't been already, as that's where the development of core themes like Twenty Twenty One happens. Use the Component "Bundled Theme."

**Comment by devNigel** [comment]
Hi @kathrynwp , I tested it on self-hosted site and I notice it also has this "issue". The menu items seem to stay a fraction of a second longer after it closes.

But I feel we are nitpicking on this. I guess we could close this.

**Comment by danieldudzic** [comment]
Proposed fix via r59021 

Review request: @jeffikus @MaggieCabrera 

A further improvement would be to hide the stats smiley, which now will be visible during the transition (https://github.com/Automattic/themes/issues/3833#issuecomment-852020843)

**Comment by pbking** [comment]
This change has been deployed.  If further changes are necessary please reopen this issue.
