### ISSUE TITLE
Mayland Blocks: Distorted images

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3635]
The issue previously reported in #3382 has resurfaced again. This might be related to making it a child theme of Blank Canvas Blocks.

**Steps to replicate**

1. Create a site with Full Site Editing and Mayland Blocks active.
2. Open the site editor and add an Image block into the post content (upload new, select from the media library, or from Pexels).
3. Save and preview the site in a new tab. Note the image is distorted.

You can see the issue live on [https://maylandblockstarter.wordpress.com/](https://maylandblockstarter.wordpress.com/)

**Comment by jffng** [comment]
I just tried to replicate by creating a new site, and the images appear correctly with the reset styles (which [were not removed in the recent update](https://github.com/Automattic/themes/blob/trunk/mayland-blocks/style.css#L60-L63
)). 

Site Editor | Front end
------- | -------
<img width="1556" alt="Screen Shot 2021-04-08 at 11 00 32 PM" src="https://user-images.githubusercontent.com/5375500/114122529-4768ac00-98a5-11eb-9ac9-4abeb6e3d3e4.png"> | <img width="1556" alt="Screen Shot 2021-04-08 at 11 01 10 PM" src="https://user-images.githubusercontent.com/5375500/114122633-8991ed80-98a5-11eb-8c84-207a2ea8eedc.png">

> You can see the issue live on PcTiN4-f-p2

It appears that the maylandblockstarter site is not loading the stylesheet at all. 

We declare a dependency `blank_canvas_blocks-ponyfill` to load the stylesheet, but I do not know why it would impact that starter site differently.

**Comment by jffng** [comment]
The issue has resolved on the starter site, so going to close this. Please re-open if it comes up again!

<img width="1392" alt="Screen Shot 2021-04-09 at 9 25 27 AM" src="https://user-images.githubusercontent.com/5375500/114187077-74947900-98fc-11eb-9ea1-5228f5d9d43e.png">

**Comment by alaczek** [comment]
I just switched themes to Blank Canvas Blocks and back to Mayland Blocks again. That seems to have cleared up the distorted images issue. But I noticed something else - there is no spacing added when content is wrapped in a group block with background set. Was that something special added in Varia themes?

**Comment by alaczek** [comment]
🤦‍♀️ I forgot we have padding controls for that now :)

**Comment by alaczek** [comment]
I wanted to reopen this issue as it's happening again. I was just updating Mayland Blocks demo and starter sites to use Columns + Images instead of Coblocks Masonry Gallery, and this is what I'm seeing:

* https://maylandblockstarter.wordpress.com/
* https://maylandblocksdemo.wordpress.com/

![image](https://user-images.githubusercontent.com/4550351/131444574-6fe7706f-f3f7-4bc2-b548-0c64a8f6ae40.png)

**Comment by MaggieCabrera** [comment]
The demo site for Mayland blocks was not loading the theme correctly. I don't know about the started one, but after changing themes and going back to Mayland blocks, it fixed the image issue and some other problems that the site had. I'm closing this, feel free to reopen if it's still happening to you
