### ISSUE TITLE
Varia: add Content Option checkbox to show/hide featured images on posts

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#3637]
Could users have a Content Option to hide featured images on posts, much like the option to hide or [show featured images on pages](https://github.com/Automattic/themes/pull/3220)? I would recommend defaulting to "on" since that's the current behavior.

We're often asked us how to either hide or resize post featured images using CSS. Support and volunteers have always just given the users the CSS needed to hide the images (or told them they'd have to upgrade to do that) but perhaps it would be better to give users an option they can find on their own.

This came up today for a user [in this thread](https://wordpress.com/forums/topic/maywood-and-balasana-content-option-featured-image/) who thought our themes were buggy, since the Content Options checkbox did not affect posts. I can see how they would misunderstand.

**Comment by supernovia** [comment]
Another request here, for Hever:
https://wordpress.com/forums/topic/remove-featured-image-3/

**Comment by liviopv** [comment]
Another user request where I had to provide custom CSS: #31229471-hc

**Comment by Aurorum** [comment]
PR in #7518 :)
