### ISSUE TITLE
Independent Publisher 2: Premium Content Block buttons center alignment

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#3638]
## Steps to replicate

1. Add Premium Content block, set buttons section to be center aligned.
2. In editor, they are shown as center aligned.
3. Publish post and then visit it in incognito window and buttons are not left aligned (logged out view).

Screenshot editor: https://d.pr/i/x3p85T

## Result

Buttons show as left-aligned.

Screenshot incognito: https://d.pr/i/gUnf58

Screenshot: 

## Expected

Expect buttons to be center aligned.

It appears that there isn't any center alignment CSS class being added to `.wp-buttons-block` for Premium Content Block when set to center in editor. Adding this, `justify-content: center;` for `.wp-block-buttons` fixes the issue.

Site: http://konabareng.com/ (Personal Plan)

* User report: 3892174-zen
* Follow-up ticket: use above

**Comment by jordesign** [comment]
I'm seeing Premium Content buttons as properly center aligned in testing now. Closing this issue.
<img width="660" alt="Screen Shot 2021-11-12 at 8 00 32 am" src="https://user-images.githubusercontent.com/1842363/141368401-b77c576f-0c9f-4737-a8cd-0dabe608e0e1.png">
