### ISSUE TITLE
Quadrat: Implement typography & color 

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3640]
Design here: https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A766

Final color, typography and button styles: https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/Quadrat?node-id=760%3A112

- [x] Headings
- [x] Paragraphs
- [x] Blockquotes
- [x] Lists 
- [x] Tables
- [x] Code
- [x] Buttons

**Comment by MaggieCabrera** [comment]
We may want to wait https://github.com/WordPress/gutenberg/pull/30791 out (I'm not sure if it's going to be ready soon or not) for the tables.

**Comment by jffng** [comment]
I think just the button styles need to be audited and then we can close this?

**Comment by scruffian** [comment]
This is now done.
