### ISSUE TITLE
Quadrat: Post Header

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3641]
The post header should look like this 

No Featured Image | Incl featured image
--------- | -----------
<img width="395" alt="Screen Shot 2021-04-12 at 11 44 30 AM" src="https://user-images.githubusercontent.com/5375500/114422647-51bbcc00-9b6b-11eb-91f6-eefca7f27058.png"> | <img width="516" alt="Screen Shot 2021-04-12 at 11 43 09 AM" src="https://user-images.githubusercontent.com/5375500/114422512-3486fd80-9b6b-11eb-9ebd-b7f832bad7e5.png">

Figma here: https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A158

**Comment by kjellr** [comment]
[As noted here](https://github.com/Automattic/themes/issues/3643#issuecomment-819455713), the header treatments here are not required from a design perspective.

**Comment by jffng** [comment]
Sounds good, what do you think about just showing the featured image (no special treatment) if there is one?

**Comment by kjellr** [comment]
Yeah, we should do that. You can place it full-width + just under the post title, like we do in Seedlet: 

![Screen Shot 2021-04-15 at 11 57 33](https://user-images.githubusercontent.com/1202812/114741334-a8b2d400-9d18-11eb-89fd-3d228511820c.png)

**Comment by scruffian** [comment]
This was closed by #3741
