### ISSUE TITLE
Quadrat: Block Patterns

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3642]
Quadrat should ship with the following block patterns: 

- [x] [Illustrated Promo](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A11) https://github.com/Automattic/themes/pull/3662/
![image](https://user-images.githubusercontent.com/5375500/114431592-82543380-9b74-11eb-8313-fe6f67f0f6d8.png)

- [x] [CTA](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A11) https://github.com/Automattic/themes/pull/3662/
![image](https://user-images.githubusercontent.com/5375500/114431475-5fc21a80-9b74-11eb-9130-3b94a85f0c84.png)

- [x] [Text over rhombus](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A11) https://github.com/Automattic/themes/pull/3676
![image](https://user-images.githubusercontent.com/5375500/114431384-4c16b400-9b74-11eb-8294-84e21d546d76.png)

- [x] [Latest Episodes](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A11) https://github.com/Automattic/themes/pull/3665
![image](https://user-images.githubusercontent.com/5375500/114431632-926c1300-9b74-11eb-8749-10577dc167b7.png)

- [x] [Episode](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A11) https://github.com/Automattic/themes/pull/3695
![image](https://user-images.githubusercontent.com/5375500/114431688-a31c8900-9b74-11eb-90ec-e17523c7ba02.png)

- [x] [Join](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A11)
![image](https://user-images.githubusercontent.com/5375500/114431798-c0515780-9b74-11eb-8356-214b3dd0d7e5.png)

- [x] [Headline and button](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A158) https://github.com/Automattic/themes/pull/3744
![image](https://user-images.githubusercontent.com/5375500/114431756-b4659580-9b74-11eb-8e5e-5c52542ca84f.png)

- [x] [Listen to the Podcast](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A158)
<img width="537" alt="Screen Shot 2021-04-12 at 11 54 41 AM" src="https://user-images.githubusercontent.com/5375500/114424277-cc391b80-9b6c-11eb-9cf2-3f81fd7c9bc4.png">

- ~[ ] [Text + Image Cover CTA](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A158)~

**Comment by jffng** [comment]
@beafialho did you imagine any other aspects of the theme to be bundled as a block pattern?

**Comment by beafialho** [comment]
I think these are all the block patterns we had thought for the theme. We could probably remove the one with Photography in "Text + Image Cover CTA" and leave only the one with Illustration, what do you think @kjellr?

**Comment by kjellr** [comment]
Yeah, I agree, we should just the one with the illustration there. 

I think the audio player one might not be possible yet, but we can give it a try.

**Comment by MaggieCabrera** [comment]
For the Alternating Promos block pattern:

We can't make it a Query Block pattern because:

- Alternating layouts… this is currently possible by using multiple query blocks with offsets. I guess we can do this, but it’s a little weird.
- Those “Learn more” buttons. I guess those are technically “Read more” links, but they appear as buttons.

They can be made using Latest Posts / Jetpack Blog Posts and if we can't use buttons on those either we can ignore them  (the buttons) for the time being

Related GB issue about the read more link as a button: https://github.com/WordPress/gutenberg/issues/25450

**Comment by scruffian** [comment]
These are all done, I think we can close this one.
