### ISSUE TITLE
Quadrat: templates

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3643]
The following templates should be available in Quadrat:

- [x] post
<img width="334" alt="Screen Shot 2021-04-12 at 12 39 20 PM" src="https://user-images.githubusercontent.com/5375500/114430428-44a2db00-9b73-11eb-8b56-6e20fc38a58c.png">

- [x] page
<img width="506" alt="Screen Shot 2021-04-12 at 12 42 27 PM" src="https://user-images.githubusercontent.com/5375500/114430561-68feb780-9b73-11eb-99d1-b8e5f902d06b.png">

- ~search~

- [x] index 
<img width="344" alt="Screen Shot 2021-04-12 at 12 39 03 PM" src="https://user-images.githubusercontent.com/5375500/114430469-508e9d00-9b73-11eb-972b-3499258fbe95.png">

- [x] 404
<img width="339" alt="Screen Shot 2021-04-12 at 12 39 12 PM" src="https://user-images.githubusercontent.com/5375500/114430449-49678f00-9b73-11eb-9db3-326bc56f8005.png">

Figma here: https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/?node-id=50%3A158

**Comment by kjellr** [comment]
Just a heads up that while it's fine to implement these if you'd like, they are not all the required templates for a MVP launch. [Please refer to the "Small Theme" section of the file](https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/Quadrat?node-id=443%3A4), which includes the only required page template: 

![Page Layout](https://user-images.githubusercontent.com/1202812/114705005-3ed50300-9cf5-11eb-9fde-e2fef36bbac5.png)

Other pages can follow this template, and posts can follow the default Seedlet post and archive templates, shared across all "small" themes.

**Comment by jffng** [comment]
Thanks @kjellr!

> follow the default Seedlet post and archive templates

From a design perspective that makes sense. But since this won't be a Seedlet child theme I was thinking that we still need to add them — then they can be duplicated across our "small themes". 

I think we can nix the search template. So that leaves the following:

- index
- page
- post (supports featured image + pagination + comments) 
- archive
- 404

Thoughts?

**Comment by kjellr** [comment]
That sounds about right to me. Once you build them once, you likely won't need to make many adjustments to them — they should be more or less the same across all of the small themes.

**Comment by jffng** [comment]
Having merged #3721, these templates are in place and should load correctly. There are plenty of adjustments to be made but I think we should close this issue and open up more detailed follow up issues, e.g. #3737
