### ISSUE TITLE
Quadrat: Hover effect

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3644]
The theme has a neat effect when hovering over post links. A slightly rotated block appears behind it:

<img width="310" alt="Screen Shot 2021-04-12 at 12 43 50 PM" src="https://user-images.githubusercontent.com/5375500/114430808-aa8f6280-9b73-11eb-87e9-8607c66e4297.png">

We should determine a good approach for when and how this effect is applied.

**Comment by MaggieCabrera** [comment]
This could be a neat effect for the query block. I did something like this using block styles for blue note here (in that case the block styled was "latest posts"): https://github.com/Automattic/gutenberg-block-styles/tree/blue-note-posts

**Comment by MaggieCabrera** [comment]
After talking with @beafialho and @kjellr this is not part of the small theme version of the design and we are leaving them out initially. We can still create the block style as an option but I'd leave it to last then.

**Comment by jffng** [comment]
Let's remove this from the milestone since it's not a part of the small theme version.

**Comment by MaggieCabrera** [comment]
I'm very keen on getting this in for Quadrat. I think this should be a Query block block style + Block pattern so it's easier for users to insert and reuse:

<img width="1145" alt="Screenshot 2021-07-05 at 15 32 54" src="https://user-images.githubusercontent.com/3593343/124479285-67c1dd00-dda6-11eb-89f3-a20047301d27.png">

We could have the 3 squares styles repeat every 3 other posts in the cases where the users want to use more than 3 per loop. What do you think @kjellr @beafialho ? How does the animation work, does the square fade in or fade in + rotate or something like that?  Also, what happens on mobile?

**Comment by kjellr** [comment]
I'm interested in @beafialho's input too, but my initial thought is: 

- A query block pattern makes sense. 
- This should be on hover only, and only on desktop (since there's no hover on mobile).
- I'd love some sort of light spin + fade-in when it appears.

**Comment by beafialho** [comment]
Thanks for dedicating some time to this! While I understand the light spin idea, I think a smooth fade-in works better. 

Another detail is the post titles would be underlined on hover, like we have on ["Blog" posts](https://quadratdemo.wordpress.com/category/blog-posts/), the reverse of what's currently happening.

https://user-images.githubusercontent.com/65220155/125426676-1cea5c4d-f8c5-4822-8bec-a9287a39b51e.mov

<img width="1057" alt="Captura de ecrã 2021-07-13, às 10 22 26" src="https://user-images.githubusercontent.com/65220155/125427061-28c52939-038e-4115-80c2-6e78671115b5.png">
