### ISSUE TITLE
Spearhead: when activating the theme homepage content is not added from demo site but from Hever theme

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#3650]
## Steps to replicate

1. Choose `Activate`
2. Select `Use Spearhead's homepage content and make my existing homepage a draft.` 
![](https://d.pr/i/CbfBMQ+)
_Link: https://d.pr/i/CbfBMQ_
3. Click `Activate Spearhead`
4. Click `Edit homepage` 
![](https://d.pr/i/tsFqej+)
_Link: https://d.pr/i/tsFqej_

## Result

Homepage content is actually from Hever theme

![](https://d.pr/i/Q96iUz+)
_Link: https://d.pr/i/Q96iUz_

## Expected

See the content from Spearhead's demo site: crEms-p2

## Context

Encountered during a Quick Start session 3907093-zd-woothemes

**Comment by ianstewart** [comment]
Closing this one in favour of https://github.com/Automattic/wp-calypso/issues/52799
