### ISSUE TITLE
Quadrat: translation

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3653]
There are a few strings in the theme's block templates that we should figure out what to do with:

- [x] 404.html
- [x] footer.html
- [x] query.html (query navigation labels)
- [x] search.html

**Comment by jffng** [comment]
After discussing with the team, I don't think this within the realm of the theme to solve, especially not for v1.

Gutenberg needs to eventually expose a mechanism to translate strings inside block templates, strings + labels that are rendered by FSE blocks, etc. ~This is a known and tracked stream of work.~

_Edit_
I'm not sure where i18n of FSE is on the roadmap or but here are a couple related issues:

https://github.com/WordPress/gutenberg/issues/27402
https://github.com/WordPress/gutenberg/issues/21932

**Comment by scruffian** [comment]
Removing this from TODO as it blocked.

**Comment by scruffian** [comment]
Another attempt: https://github.com/WordPress/gutenberg/pull/33217

**Comment by jeffikus** [comment]
Tested this with @MaggieCabrera - marking as closed.
