### ISSUE TITLE
Quadrat: launch stuff

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3660]
There are a few launch related tasks we need to do for all new theme launches:

- [x] Update theme screenshot
- [x] Create a theme demo site
- [ ] Create a theme showcase entry
- [x] Draft a call for testing 
- [ ] Generate a headstart annotation PCYsg-7cr-p2

~It may be pre-mature to do most of these.~  It is no longer pre-mature to these :)

cc @kjellr @jeffikus in case you can think of any others that might fall under this bucket, or how the approach for a "small theme" might be different for any of these items.

**Comment by kjellr** [comment]
We'll need to write a theme description and probably a launch post, though I agree it's too early to worry about those things. 

Although this is a "small" theme, it's our first small theme of this type, so I'm not sure the launch process is going to be much more streamlined than usual.

**Comment by scruffian** [comment]
@kjellr @beafialho are these things you'd be able to help us with?

**Comment by kjellr** [comment]
Yes definitely. We'll work on the theme description next week. Do we have have a launch (or call for testing) date in mind?

**Comment by scruffian** [comment]
I'm hopeful we can post a call for testing early next week.

**Comment by beafialho** [comment]
Worked on the theme description:

_Quadrat is a simple, versatile WordPress theme, designed for blogs and podcasts. Inspired by squared shapes and colourful, minimalist flat illustrations, Quadrat bundles a set of images you can use on your site with the theme’s default color palette. Quadrat’s default styles are bold and playful, relying on a simple sans-serif font and a strong color scheme that you can customize._

**Comment by scruffian** [comment]
I created new cards for the remaining tasks here, so closing this.
