### ISSUE TITLE
Quadrat: customize the theme colors

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3661]
We should identify what options are available to users of Quadrat via the Customizer, bearing in mind these will likely be carried through to other small themes.

I'm not suggesting we add support for all (or any!) of these, but I want to at least have the discussion. 

- Colors 
- Excerpt settings
- Hide the page title on the home page

Do you have thoughts about these options? Can you think of any more?

cc @kjellr @beafialho

**Comment by kjellr** [comment]
In addition to that list, we should also include the option to hide the header and footer on the homepage, like we do in all the Varia + Seedlet themes.

**Comment by beafialho** [comment]
I agree with the customisation options you both mentioned.

I was wondering if it's possible to give users the option to choose which meta they wish to display. Like this:
<img width="287" alt="Captura de ecrã 2021-04-15, às 17 59 00" src="https://user-images.githubusercontent.com/65220155/114908742-4808c180-9e14-11eb-87ee-e69b4d3c565a.png">

One other thing is to have an option of choosing the blog's layout between 'Grid' or 'Stack', like this:
<img width="289" alt="Captura de ecrã 2021-04-15, às 17 56 54" src="https://user-images.githubusercontent.com/65220155/114908498-11cb4200-9e14-11eb-9a2d-9416a1d795a1.png">

**Comment by scruffian** [comment]
My concern about adding these options is that they won't carry over into the site editor. So any customizations I add here will be lost once the version of WordPress is updated

**Comment by kjellr** [comment]
I agree with that concern. The same goes for the other way around: any adjustments you make in the site editor won't carry through if you were to (somehow) revert back to the customizer. 

Even so, I do think that the color control at least is very necessary — especially since the theme has such an opinionated purple + pink palette by default. Maybe we can start with that?

**Comment by scruffian** [comment]
I think going in the reverse direction is less of a concern - that will only happen through user intervention, whereas with auto updates, most users will end up in the Site Editor without doing anything.

I think colors is a good idea. @pbking do you think we can use some of your prior art to hook into theme.json?

**Comment by beafialho** [comment]
Good points. I agree, color control is necessary here.

**Comment by pbking** [comment]
I have SO MUCH prior art for that!
Yes, I can build a thing...

**Comment by jffng** [comment]
I've updated this issue to reflect the primary concern for customization — being able to change theme colors via the customizer or FSE.
