### ISSUE TITLE
Edin: third level menu links cut off on the right

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/themes#368]
## Steps to replicate

1. With Edin activate, create a menu with the following structure:
> Top level page
>> Second level page
>>> Third level page

2. Publish the menu and then try to access third level menu items.

## Result

The third level menu background is cut off on the right — shorter links are displayed in full but not those containing longer or multiple words.

![edin-cut-off](https://user-images.githubusercontent.com/11627765/48767262-43289d80-ecae-11e8-9c80-b2996df6c618.jpg)

## Expected

I expected the third level menu links to adapt to fit the available screen space.

* User report: https://wordpress.org/support/topic/can-i-solve-3-navbar-niggles-with-css/
* User's site: https://ir101.co.uk/

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
