### ISSUE TITLE
Libretto: Site Logo Link Overlaps Menu Items

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/themes#369]
## Steps to replicate

- Change a site's theme to Libretto
- Add a site logo in the Customizer
- Add a handful of links to the menu in the header

## Result

When viewing the site in at a laptop-sized viewport width (I tested at 1440 wide) the link on the site logo overlaps with the menu, making some menu items un-clickable.

Tested in Safari, Chrome, and Firefox on macOS Mojave.

## Expected

The site logo link is constrained to only be clickable on the image itself
or
The menu switches to the mobile menu when the two items overlap.

* User report: 1576392-zen
* User's site: https://demonnier.com/ (visible on homepage)

## Screenshot/GIF

![screen recording 2018-11-20 at 9 52 15 am mov](https://user-images.githubusercontent.com/42454301/48781519-2db17480-ecaa-11e8-80af-927e4f1b65ad.gif)

<img width="1552" alt="screen shot 2018-11-20 at 9 54 43 am" src="https://user-images.githubusercontent.com/42454301/48781617-5a658c00-ecaa-11e8-934f-51194a264486.png">

**Comment by laurelfulford** [comment]
This has been committed to WP.com in r53281-wpcom-themes.

@mdrockwell It looks like the original ZD ticket is closed, so I can't add a comment there - can you please follow up with the user if needed? Thanks!

**Comment by mdrockwell** [comment]
Thanks for the heads up @laurelfulford, I created a follow-up ticket and let them know there.

1787595-zen
