### ISSUE TITLE
Mayland Blocks: No wide width block setting

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3692]
I was working with FSE and Mayland Blocks, and I noticed that there is no support for wide/full-width block settings, and all the blocks including Paragraph and Heading are using full-width by default.

## Steps to replicate
1. Create a site via the FSE flow, select Mayland in the design step.
2. Remove everything inside the Post Content block.
3. Add a Heading, a Paragraph, and Cover block.
4. Note Heading and Paragraph block widths are not limited.
5. Note Columns and Cover don't have wide/full-width alignment settings.

Here's a screenshot from Mayland Blocks + FSE:
![maylandblocks_wide](https://user-images.githubusercontent.com/4550351/115806800-c673ed80-a42a-11eb-87f7-ee1518da184a.jpg)

Compare to Mayland (no FSE):
![mayland_wide](https://user-images.githubusercontent.com/4550351/115806825-d1c71900-a42a-11eb-87b5-2d81c6126786.jpg)

**Comment by alaczek** [comment]
Ok, so I figured that setting Post Content to Inherit default layout mostly fixes the above issues.
![image](https://user-images.githubusercontent.com/4550351/115816734-b7963680-a43c-11eb-9c79-2c2f19a11d55.png)

One thing I need help troubleshooting is the width of text (Paragraph, Heading) inserted into the Cover block. It's stretching the full-width even with Inherit default layout selected.

![image](https://user-images.githubusercontent.com/4550351/115816785-d72d5f00-a43c-11eb-8a56-364022932bfb.png)

**Comment by alaczek** [comment]
I also noticed something that might be related - Columns block, when placed inside Cover or Group block does not have the wide / full-width  settings.

Columns block on its own:
![image](https://user-images.githubusercontent.com/4550351/115820088-7d7c6300-a443-11eb-9b70-7f9bd85d9658.png)

Columns block inside Group block:
![image](https://user-images.githubusercontent.com/4550351/115820212-b74d6980-a443-11eb-94cd-1efaff21f268.png)

**Comment by MaggieCabrera** [comment]
I think maybe we should have the inherit layout by default. We hadn't because the home page was designed to be full width, but I think we can refactor the actual content to be full width and the rest of the layout to just inherit. I'm not sure what's causing the cover issue or if it's related to that, we'd have to investigate. Thanks for reporting this.
