### ISSUE TITLE
Quadrat: code quality

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3694]
This issue is to capture a few code quality to-dos:

- [x] Break block patterns into separate PHP files
- [x] Refactor to use `gutenberg_block_template_part`
- [x] Refactor theme.json files to have variables on alphabetical order
- [ ] Identify areas that can be migrated to BCB eventually and add comments

**Comment by MaggieCabrera** [comment]
The utility classes can be moved to BCB when we refactor the block patterns.

**Comment by MaggieCabrera** [comment]
Refactor theme.json files to have variables on alphabetical order

**Comment by MaggieCabrera** [comment]
I'm going to remove this one from the v1 milestone. I already moved the utility classes to BCB but I don't know if there's anything else we potentially want to move to BCB so that's why I'm not closing this.

**Comment by MaggieCabrera** [comment]
I'm going to close this as the last point should be an ongoing thing
