### ISSUE TITLE
Quadrat: Navigation

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3696]
We need a way to render the menu in a classic theme so there is a sensible upgrade path to FSE while still allowing users to edit their menu in the customizer. 

We have three approaches so far:

- Change the way the nav block works to consume a classic menu by specifying a "location" attribute: https://github.com/WordPress/gutenberg/pull/30852
- Render using `wp_nav_menu` + `add_theme_support( 'block-nav-menus' )` in the theme: https://github.com/Automattic/themes/pull/3654/
- Create a reusable block and load in the header template (no PR yet, related: https://make.wordpress.org/themes/2020/07/05/using-the-block-editor-for-theme-parts/)

**Comment by jffng** [comment]
We merged https://github.com/Automattic/themes/pull/3714 while we push for a solution in Gutenberg / the navigation block.

**Comment by MaggieCabrera** [comment]
We need to think about the responsive version of the navigation in particular, if the theme launches on dotcom before https://github.com/WordPress/gutenberg/pull/30047 lands

**Comment by pbking** [comment]
The ponyfill in BCB gets the current navigation solution (#3714) (or, the [location-on-block solution](https://github.com/WordPress/gutenberg/pull/30852)) close-ish as-is for mobile.  I think some adjustments either in BCB or Quadrat will get us to useable until that Gutenberg issue lands.  

![image](https://user-images.githubusercontent.com/146530/117156596-dc1ed680-ad8b-11eb-9b39-12cd495a75f3.png)

**Comment by MaggieCabrera** [comment]
Oh I forgot about that! cool then, thanks Jason!

**Comment by MaggieCabrera** [comment]
I think we can close this one since we already have an issue for the mobile menu (https://github.com/Automattic/themes/issues/3789). We can revisit this if/when the GB PR for the navigation block lands.
