### ISSUE TITLE
Mayland Blocks: Pre-activation Live Preview causes Fatal Error

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#3698]
This may be related to my testing environment but live preview pre-activation with Mayland Blocks causes a fatal error. This does not happen with Classic Themes in the same environment.

![image](https://user-images.githubusercontent.com/545779/115898526-45652800-a423-11eb-8090-b566eb3ad0ee.png)

**Comment by ianstewart** [comment]
Closing this issue because the error is PEBKAC. :)

**Comment by scruffian** [comment]
I think this is a genuine issue

**Comment by jffng** [comment]
Yeah we could provide a check here to ensure the class we're calling exists:

https://github.com/Automattic/themes/blob/trunk/blank-canvas-blocks/functions.php#L63
