### ISSUE TITLE
Mayland Blocks: No left-margin/padding on header

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#3699]
![image](https://user-images.githubusercontent.com/545779/115899350-4185d580-a424-11eb-932a-e5a7a748e436.png)

![image](https://user-images.githubusercontent.com/545779/115899591-89a4f800-a424-11eb-838b-14e674da6383.png)

Expected: left margin/padding on site title.

**Comment by alaczek** [comment]
I was wondering if this was a theme issue as well, then I noticed Header has padding controls. In that case, do you still feel it's a theme issue?

**Comment by MaggieCabrera** [comment]
> I was wondering if this was a theme issue as well, then I noticed Header has padding controls. In that case, do you still feel it's a theme issue?

yes it's a theme issue, the original design had the padding, so the block should have it. Luckily now the user can also fix it within the editor too. We'll get to it and fix it, thanks for reporting!
