### ISSUE TITLE
Karuna: Full-Width Footer not full-width unless home page set to Full-Width page template

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#37]
## Steps to replicate

The Full-Width Footer widget does not render full-width unless the Page designated as the homepage is set to the "Full-Width" Page Template.

![screen shot on 2018-03-12 at 13 39 41](https://user-images.githubusercontent.com/2912202/37281789-ea54532c-25fa-11e8-9231-9645da5950cc.png)

User's site was set to "Default Template"

## Result

The Full-Width Footer widget seemed to take on a narrower width and align to the left when the homepage Page template was set to "Default".

![screen shot on 2018-03-12 at 13 42 58](https://user-images.githubusercontent.com/2912202/37281951-62dacaf6-25fb-11e8-938e-ab9f26f1836f.png)

## Expected

The Full-Width Footer widget should be rendered full-width regardless of the applicable Page Template for the homepage Page. Either that or this requirement should be documented in the theme guide and widget configuration settings.

* User report: 2034075-hc
* User's site: akayindustries.nl

**Comment by sixhours** [comment]
This was reported in #34 as well, and moved to Automattic/jetpack#6968. I've added the user info to the Jetpack ticket for follow-up.
