### ISSUE TITLE
Mayland Blocks: Comments are not styled

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#3700]
Comments are not styled in Mayland Blocks.

![image](https://user-images.githubusercontent.com/545779/115900532-aa218200-a425-11eb-99f8-24f96c2f4deb.png)

![image](https://user-images.githubusercontent.com/545779/115900801-f8cf1c00-a425-11eb-9d21-fea1cacec89d.png)

**Expected:** 

- No visible ordered list styles.
- Styles for threading.
- Styled comment form.

**Comment by MaggieCabrera** [comment]
Closing this one in favor of https://github.com/Automattic/themes/issues/3590
