### ISSUE TITLE
Mayland Blocks: Theme palette produces strange effect with Navigation Block

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#3701]
## Steps to replicate

1. Insert nav block into header with Site Editor.
2. Change background colour of nav block to Black using Theme palette.
3. Change text colour to White using Theme palette.

## Result

![image](https://user-images.githubusercontent.com/545779/115901636-0fc23e00-a427-11eb-8292-9406909cb601.png)

## Expected

Something more like this effect produced with custom colours.

![image](https://user-images.githubusercontent.com/545779/115901731-2ec0d000-a427-11eb-8d05-6e222862b586.png)

**Comment by alaczek** [comment]
Yep, I encountered the same thing in Mayland Blocks and Seedlet Blocks (but not in TT1 Blocks).

With Seedlet I also noticed weird styling on the Site Title:

Editor:
![image](https://user-images.githubusercontent.com/4550351/116644941-07827980-a9b8-11eb-9d16-71ab07477178.png)

Preview:
![image](https://user-images.githubusercontent.com/4550351/116644969-1b2de000-a9b8-11eb-853c-d963b387c736.png)

**Comment by alaczek** [comment]
Also, for the record, I was able to replicate the issue with both colors from the theme color palette, and random colors selected with the color picker.
