### ISSUE TITLE
Penscratch 2: No-Sidebar layout is off center at 55em

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#371]
## Steps to replicate
- Enable theme
- Remove sidebar widgets
- Adjust screen width to about 55em

## Result
![screen shot 2018-11-20 at 2 21 15 pm](https://user-images.githubusercontent.com/3476361/48803587-965f1800-eccf-11e8-9313-57428d78f7fa.png)

## Expected
![screen shot 2018-11-20 at 2 23 48 pm](https://user-images.githubusercontent.com/3476361/48803702-e76f0c00-eccf-11e8-9469-c31949f3094b.png)

* User report: https://en.forums.wordpress.com/topic/how-to-hide-the-side-bar-when-full-screen/
* Follow-up ticket: (same is OK)
* User's site: https://totoko.fr/

Noting the user already has custom CSS to fix it.

**Comment by laurelfulford** [comment]
Committed to WP.com in r52757-wpcom-themes.

It looks like the original reporter has since switched to Illustratr, but I'll add a follow up comment in the forum thread to let them know it's fixed!
