### ISSUE TITLE
Quadrat: comments

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#3737]
Does Quadrat support post comments? If so, how should those look?

We could style the comments more specifically in BCB also.

**Comment by jffng** [comment]
We should also identify what a fallback would be since post comment-related blocks will not make it in 5.8.

**Comment by beafialho** [comment]
Yes @jffng, here's what I thought for post comments.

**Desktop**
<img width="1049" alt="Captura de ecrã 2021-05-04, às 10 46 50" src="https://user-images.githubusercontent.com/65220155/116987283-c5fb1280-acc6-11eb-9129-847b9edfb200.png">
https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/Quadrat?node-id=177%3A2

**Mobile**
<img width="289" alt="Captura de ecrã 2021-05-04, às 10 51 33" src="https://user-images.githubusercontent.com/65220155/116987310-cc898a00-acc6-11eb-8c74-4f7b9b7bc2e8.png">
https://www.figma.com/file/EDoXTvsZt4lMHItzOczFQw/Quadrat?node-id=50%3A537
