### ISSUE TITLE
Quadrat: "Cover Block with Heading" pattern bugs

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3738]
Followup to #3676. Two small observations on the Cover Block with Heading pattern: 

1. To match the comps, the default background color should be "Blue" instead of "Dark Blue".
2. I'm seeing some weirdness on select in the editor: The square gets darker, and the text color is different. See the GIF below: 

![test](https://user-images.githubusercontent.com/1202812/116901655-30994900-ac08-11eb-807b-ee2c91e79df0.gif)

**Comment by MaggieCabrera** [comment]
Note to future self: this is most probably the opacity options of the block
