### ISSUE TITLE
Chateau: Related Posts div overlaps Sharing Buttons, making them unclickable

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#374]
It appears under certain circumstances the Related Posts section on a post overlaps the sharing buttons, rendering the sharing buttons unclickable.

## Steps to replicate

1. Use a site with several posts published so that Related Posts will load on single posts.
2. Go to My Site ->Settings ->Traffic and enable Related Posts. It doesn't matter whether they show thumbnail images or not.
3. Go to My Site ->Sharing ->Sharing buttons and make sure there are sharing buttons configured for the site and set to display on single posts.
4. Edit a post and make sure that Sharing buttons are enabled, but that the Like button is disabled.
5. View the post

## Result

The sharing buttons load properly below the content, and Related Posts below that, but the buttons are not clickable. Checking the browser inspector shows the `jp-relatedposts` div overlapping the sharing buttons:

![regular_post___shift_to_the_left](https://user-images.githubusercontent.com/11873759/48832724-7b99ab80-ed82-11e8-8e97-94ac593ba632.png)

It also appears the `sharedaddy` div has a height of 0 for some reason, though I can't see where that's coming from:

![regular_post___shift_to_the_left](https://user-images.githubusercontent.com/11873759/48832840-c9aeaf00-ed82-11e8-8913-b07b0734f1eb.png)

## Expected

For the sharing buttons to be clickable.

* User report: https://en.forums.wordpress.com/topic/share-buttons-dead-only-on-posts/
* User's site: https://hbooyens.wordpress.com/2014/02/24/amabhulu-the-blog/

I've explained to them that this is a retired theme, and that it would be better long term to just update to a current theme.

**Comment by laurelfulford** [comment]
Yeah, unfortunately given Chateau's retired status, I'm going to mark as a `wontfix`.

@KokkieH it looks like the user has resolved the issue on their site by removing the related posts; in my testing I found that enabling the Like or Reblog button also does the trick. Not sure if that's worth a follow up in this case, just let me know if it makes sense to follow up with that!
