### ISSUE TITLE
Quadrat: Adjust pullquote text size and line height

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#3743]
The pullquote text currently doesn't feel balanced. Citation text size is ok as it is but here's what I think can be adjusted:

1. Change font to Medium instead of Regular Italic for the quote.
2. Change text size to 50pt and line height to 1,3.
3. Change Regular Italic to Regular in citation.
4. Remove the divider line at the bottom, leave only the one at the top.

How it looks:
<img width="734" alt="Captura de ecrã 2021-05-04, às 09 54 47" src="https://user-images.githubusercontent.com/65220155/116999278-4e81af00-acd7-11eb-8cda-9ff5a482f52c.png">

How it should look:
<img width="842" alt="Captura de ecrã 2021-05-04, às 12 53 28" src="https://user-images.githubusercontent.com/65220155/116999618-c2bc5280-acd7-11eb-8c5c-0fea70332372.png">

**Comment by jffng** [comment]
Closed by #3780
