### ISSUE TITLE
Quadrat: Reconsider the text hover effects

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3782]
I think the background color hover effect we're using ends up being a little too prominent for my taste when it's applied to large headings: 

<img width="656" alt="Screen Shot 2021-05-07 at 12 51 29 PM" src="https://user-images.githubusercontent.com/1202812/117483135-52117200-af33-11eb-90eb-cb5a83e474f7.png">

Also, I think it's a little weird that we have a different hover state for one portion of the header vs. another: 

![hovers](https://user-images.githubusercontent.com/1202812/117483689-057a6680-af34-11eb-8382-d7318a8f8d7a.gif)

So I recommend a few changes: 

1. Use the background color hovers _only_ for links within body text. 
2. Use underlines for all other hovers. 

@beafialho what do you think of that approach? I think another idea would be to just use underlines everywhere, and remove the background-color treatment entirely. 

(If we do keep the background color hovers, I think we also need to be sure to remove the underline whenever the background color hover is active.)

**Comment by beafialho** [comment]
> @beafialho what do you think of that approach? I think another idea would be to just use underlines everywhere, and remove the background-color treatment entirely.

Thanks @kjellr, I share the same thoughts on hover being too prominent in large titles. I think we can use underlines everywhere and remove the background-color entirely.
