### ISSUE TITLE
Quadrat: Body text size is incorrect. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3785]
As per the figma file, the default body size should be 18px, with a line height of 1.6. Instead, the current font size is 20px, with a line height of 1.7. 

Comps|Development
---|---
![Frame 2](https://user-images.githubusercontent.com/1202812/117486390-91da5880-af37-11eb-80ae-edcb67b858b5.png)|![current](https://user-images.githubusercontent.com/1202812/117486396-930b8580-af37-11eb-9566-b73f79ea1811.png)

While we're making this change, I think a line height of 1.65 or 1.7 might actually be a bit more comfortable. @beafialho do you have a preference there? Either way, the font size definitely should be updated.

**Comment by beafialho** [comment]
I think a body size of 18px and a line height of 1.7 feels the most comfortable.
