### ISSUE TITLE
Quadrat: Default font weight is incorrect. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3786]
Most of the site's text is currently set to a 300 weight, but it should be Normal/400 to match the Figma file. 

- Navigation
- Body text
- Post pagination
- Page footer
- etc.

Current Dev|Comps
---|---
<img width="313" alt="Screen Shot 2021-05-07 at 1 31 07 PM" src="https://user-images.githubusercontent.com/1202812/117487145-b3880f80-af38-11eb-8aed-0f9491b3cdc5.png">|<img width="309" alt="Screen Shot 2021-05-07 at 1 32 27 PM" src="https://user-images.githubusercontent.com/1202812/117487149-b420a600-af38-11eb-8127-82282a3c2d3a.png">

**Comment by MaggieCabrera** [comment]
This will be fixed with #3824
