### ISSUE TITLE
Twenty Fourteen: Post Carousel Block author and date impossible to read

### ISSUE THREAD

**Issue by fresatomica** [Automattic/themes#3799]
## Steps to replicate

1. Add Post Carousel Block
2. Toggle on Show author and Show Date options

## Result

On the published site, the post metadata is white on white background and so impossible to read:
<img width="605" alt="Screen Shot on 2021-05-10 at 13-51-26" src="https://user-images.githubusercontent.com/40177971/117656156-483c7880-b198-11eb-817a-c55afa96a94f.png">

## Expected

Author and Date should be visible, like in the preview:
<img width="622" alt="Screen Shot on 2021-05-10 at 13-53-17" src="https://user-images.githubusercontent.com/40177971/117656232-64401a00-b198-11eb-8894-13164a6d4385.png">

* User report: https://wordpress.com/es/forums/topic/problema-con-autor-en-tabla-de-entradas/

**Comment by danieldudzic** [comment]
Fixed via r58998
