### ISSUE TITLE
Pique: Submenu links cannot be clicked on tablet

### ISSUE THREAD

**Issue by sixhours** [Automattic/themes#38]
Moving from 5020-wpcom-themes /cc @Piyopiyo-Kitsune 

When you have a sublinks for this theme, they cannot be clicked while on a tablet because clicking the parent link to unveil the sublinks takes you to that parent link's page.

Workarounds: Make the parent link a custom link with # for the URL.

Ideally, you can tap once on the parent link to display the sublinks and then navigate to those.

The bug was reported by a user whose site is: faribaalai.blog

I was able to replicate this on my test site: wp20170811.com

Steps for reproduction:
1. Activate the Pique theme
2. Set a parent link with a real URL in the customizer
3. Add sublinks to that parent link in the customizer
4. Try to access a sublink while on a tablet.

**Comment by sixhours** [comment]
@Piyopiyo-Kitsune is there a ticket/chat link for reference or follow-up purposes?

**Comment by Piyopiyo-Kitsune** [comment]
@sixhours Yes there is! :) 1985214-hc

**Comment by sixhours** [comment]
Looks like the code is there, but it's written to target devices smaller than 768 pixels in width, which isn't most tablets. I'm not sure the reasoning behind this, but we use a different method targeting touch devices in _s:

https://github.com/Automattic/_s/blob/master/js/navigation.js

We should consider refactoring the menu to use the _s method rather than the custom script.

**Comment by allancole** [comment]
The above commit fixes this on tablet devices: https://github.com/Automattic/themes/issues/38#ref-commit-b5ed7ad

Closing ticket.
