### ISSUE TITLE
Quadrat: Featured Image doesn't extend full-width if the image is small

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3805]
When you insert a full-width image into a post, it extends to the edge of the screen all the time, even if the image needs to be scaled up to do so. 

This isn't the case with our full-width featured images though. They max-out at their intrinsic width, and appear left-aligned: 

<img width="2228" alt="Screen Shot 2021-05-10 at 12 28 38 PM" src="https://user-images.githubusercontent.com/1202812/117693129-b0d12880-b18b-11eb-8ff3-8e946d92721c.png">

To reproduce: 

- Add a small-ish featured image.
- View the post in a large window. 

(This one may end up being a Gutenberg bug)

**Comment by jffng** [comment]
This should be addressed by https://github.com/WordPress/gutenberg/pull/32070

**Comment by kjellr** [comment]
👍 Thanks, I'll close for now.
