### ISSUE TITLE
Quadrat: Large quote needs a line height adjustment

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3812]
Large quote line height should be 1.4

Before|After
---|---
<img width="769" alt="117698034-37d4cf80-b191-11eb-96b2-c9fe17ac8d92" src="https://user-images.githubusercontent.com/1202812/117710624-5393a200-b1a0-11eb-91db-bb6d8854a633.png">|<img width="740" alt="117698037-386d6600-b191-11eb-8ceb-3a0c4f9364f2" src="https://user-images.githubusercontent.com/1202812/117710625-5393a200-b1a0-11eb-8d3d-2b2219301060.png">

cc @beafialho for a second opinion.

**Comment by beafialho** [comment]
I also mentioned pullquote adjustments in #3743

**Comment by kjellr** [comment]
Oh great, I missed that! I'll remove the pull quote stuff from this issue, so it focuses on just the Quote block instead.
