### ISSUE TITLE
Independent Publisher 2: Drop Shadow Issue 

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/themes#3813]
## Steps to replicate

1. Open theme - https://independentpublisher2demo.wordpress.com/
2. Open page in latest version of Firefox, Chrome, or Safari on MacOS
3. Mouseover photo at the top of page 

## Result

* Drop shadow is off

See screenshot:
https://d.pr/i/JFyZvk

## Expected

* Drop shadow should display properly

* User report: 3974643-zen

**Comment by kathrynwp** [comment]
Posting GIF directly instead of to Droplr (removes the need for a click to see it, also preserves it here in case your Droplr account can't be accessed)

![Screen Capture on 2021-05-10 at 13-23-04](https://user-images.githubusercontent.com/7662449/118044719-043aa680-b345-11eb-9dcc-1d4ff5d508a1.gif)

**Comment by jordesign** [comment]
Confirmed this behaviour still in place - the drop shadow on the Gravatar image when hovered is definitely out of place.
