### ISSUE TITLE
Quadrat: Consider renaming the default "Blue" colors

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3815]
I think the last two colors in our palette are solidly in the "Purple" range. I was just a little confused to see them labeled "Blue" and "Dark Blue". @melchoyce, @beafialho what do you think?

<img width="222" alt="Screen Shot 2021-05-10 at 3 16 01 PM" src="https://user-images.githubusercontent.com/1202812/117712686-a2dad200-b1a2-11eb-85e6-92f9b6502950.png">

**Comment by melchoyce** [comment]
IMO, it is leaning more towards blue than purple. Maybe indigo? 

<img src="https://user-images.githubusercontent.com/2846578/117724483-d1ac7480-b1b1-11eb-8d2e-2a58866e8d5f.png" width="300" /><img src="https://user-images.githubusercontent.com/2846578/117724501-da04af80-b1b1-11eb-9403-fff8db507056.png" width="300" />

**Comment by beafialho** [comment]
I also think both of these both fall more in the "Blues" range than the "Purples". I searched for similar tones in a [named colors list](https://htmlcolorcodes.com/color-names/) and Indigo is closer to purple:

<img width="1405" alt="Captura de ecrã 2021-05-11, às 09 51 02" src="https://user-images.githubusercontent.com/65220155/117787938-d5d2a380-b23e-11eb-8cd3-d1b8bbe80596.png">
<img width="1304" alt="Captura de ecrã 2021-05-11, às 09 51 24" src="https://user-images.githubusercontent.com/65220155/117787950-d9662a80-b23e-11eb-91bf-5a6b608d3ff3.png">

Not sure if "Midnight Blue" is too weird, but I don't see a problem with "Dark Blue".

**Comment by kjellr** [comment]
👍 We can leave as-is then. Thanks for the second opinions!
