### ISSUE TITLE
Blockbase: Style position of Dotcom Stats Smiley

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#3833]
This stats smiley could perhaps be centered?

![image](https://user-images.githubusercontent.com/545779/117873312-3ffe3f00-b265-11eb-88e9-708b8420205a.png)

**Comment by danieldudzic** [comment]
@ianstewart Is there a deeper reason for this alignment preference?

I have checked Twenty Twenty One and Twenty Twenty and the Smiley is left aligned. In Varia it's hidden.

**Comment by danieldudzic** [comment]
Perhaps we could just hide it like in Varia / Seedlet.

```
img#wpstats {
	position: absolute !important;
	clip: rect(0, 0, 0, 0);
	padding: 0 !important;
	border: 0 !important;
	height: 0 !important;
	width: 0 !important;
	overflow: hidden;
}
```

**Comment by ianstewart** [comment]
If hiding it doesn't affect the performance of the stats smiley then hiding it works for me. (I don't know if hiding it affects it.)

> Is there a deeper reason for this alignment preference?

Subjective aesthetic reasons: It looks strange. :)

**Comment by scruffian** [comment]
Also note that on Quadrat this creates an unfortunate space:
<img width="1440" alt="Screenshot 2021-06-14 at 15 30 02" src="https://user-images.githubusercontent.com/275961/121908982-65c7a980-cd25-11eb-8e18-5a0dfd14adea.png">
