### ISSUE TITLE
Ixion: Pullquote block custom border colors don’t work

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#3851]
The Pullquote block has a setting for custom colors, which should change the border color. It does in the editor, but doesn’t on the live page.

## Steps to replicate

* Add a Pullquote block to a page
* Add a custom color for the border
* View published page

## Result

Page:

![https://d.pr/i/kMrZru](https://d.pr/i/kMrZru+)

## Expected

Editor:

![https://d.pr/i/cm381x](https://d.pr/i/cm381x+)

## Notes

It appears the theme adds the border to the blockquote, instead of the surrounding `figure.wp-block-pullquote`

![https://d.pr/i/pxqxDH](https://d.pr/i/pxqxDH+)

* User report: 27853524-hc (used CSS to resolve)

**Comment by KirkwallDay** [comment]
Another instance here: 4732376-zen

Used a workaround involving changing the border color of the block to a non-theme default. Also used this CSS to remove the line that shows up in the block:

```
/* Remove line on pullquote blocks JC | 4732376-zen */
.wp-block-pullquote blockquote {
    border-top: unset;
    border-bottom: unset;
    margin-bottom: unset;
```

**Comment by syedshaon** [comment]
Another Issue: 4752134

**Comment by wprhunt** [comment]
Reporting another. On the Stow theme:
hc-28766166
