### ISSUE TITLE
Quadrat: Change Links Focus States

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#3868]
Might be related to #3782, currently the focus state for links looks like this:

<img width="931" alt="Captura de ecrã 2021-05-17, às 13 10 46" src="https://user-images.githubusercontent.com/65220155/118486386-71698580-b711-11eb-942a-f2322d4699fb.png">

Here's how it should look with a dotted border:

<img width="796" alt="Captura de ecrã 2021-05-17, às 15 21 27" src="https://user-images.githubusercontent.com/65220155/118504615-923ad680-b723-11eb-8243-9b915400abae.png">

<img width="985" alt="Captura de ecrã 2021-05-17, às 15 22 54" src="https://user-images.githubusercontent.com/65220155/118504857-cca47380-b723-11eb-8fde-10e96f3dbe56.png">

**Comment by jffng** [comment]
What is the default state of a link that appears inside the body / post content?

**Comment by beafialho** [comment]
On post content, I imagine the reverse would happen: a link is underlined and the underline disappears on hover. Focus state is the same as described above.
