### ISSUE TITLE
Editor: Different Font Loads At First

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#3876]
## Steps to replicate

- Activate Editor theme 
- visit your site 

Screen recording: https://d.pr/i/WfkH3Z

![font](https://d.pr/i/WfkH3Z+)

## Result

- a different font will appear first, before displaying the actual site font.

## Expected

Site will load with the font set, instead of another font. 

* User report: [3998084-zd] and self-testing.
* Follow-up ticket: [3998084-zd]

**Comment by kathrynwp** [comment]
Hi there - this is not theme-specific, but instead a phenomenon called FOUT - Flash of Unstyled Text.

There are a few potential CSS workarounds for this, such as:

```
/* Global: Remove the flash of unstyled text (FOUT) */
visibility: hidden;
}
```

Closing as this is not a theme issue.
