### ISSUE TITLE
Quadrat: margins on mobile

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#3878]
It looks like on mobile all the content goes straight to the edge of the viewport:

<img width="389" alt="Screenshot 2021-05-18 at 17 12 38" src="https://user-images.githubusercontent.com/3593343/118677202-5b84bf00-b7fc-11eb-9fae-301ab9dfe8c9.png">

**Comment by scruffian** [comment]
This was fixed by #3961
