### ISSUE TITLE
Spearhead: Menu doesn't respond as expected to small viewport

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#3880]
![image](https://user-images.githubusercontent.com/545779/118700008-c7a0fc00-b7d7-11eb-9615-39d6629f97ae.png)

Assumed the menu would be in the top right of the header. 

Note: the theme might be leaking CSS in the toolbar as well (note my avatar in the screenshot) or there could be something else going on.

**Comment by zdenys** [comment]
Encountered in 5232581-zd-woothemes (where the user shared a video recording) with the side effect of the menu not responding to multiple clicks correctly on mobile device

![image](https://user-images.githubusercontent.com/39308239/170049839-836738ad-31d4-4966-8af9-a8fc312b21da.png)
