### ISSUE TITLE
Blank Canvas Blocks: Turn into a more generic "starting point" theme

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3895]
👋 I took a look at Blank Canvas Blocks with the idea of turning it into a more generic starting point for a block-based/universal theme. Here are the steps I think we should take to get there: 

- [x] **Header/Navigation Template Parts:** Replace with the slim ones used in Quadrat. 
- [x] **Index template:** Left-align all post titles, add a featured image block below the title. 
- [x] **Current Singular Template:** Make the current "post content only" singular template into a custom page template instead, so folks can optionally choose to use start blank for certain pages. (I'm not sure we need to do this given the template stuff coming in 5.8?)
- [x] **New Singular Template:** Add a new singular template with the header template part, post title, wide-width featured image, post content, and post date. Also include comments + the page footer template part. 
- [x] **Block Patterns:** Remove all bundled block patterns.
- [x] **New Theme Screenshot:** Provide a new theme screenshot to reflect these updates.

We'll likely need to go back in and adjust some margin/padding after these updates, but we can handle that when we get there. 

Rough screenshots of the new template updates: 

Index|Singular
---|---
![Screen Shot 2021-05-21 at 10 42 27](https://user-images.githubusercontent.com/1202812/119000695-55f0bb80-b959-11eb-99a0-020dec2e750a.png)|![Screen Shot 2021-05-21 at 10 48 11](https://user-images.githubusercontent.com/1202812/119000712-58ebac00-b959-11eb-8f70-2f422eb26705.png)

**Comment by jffng** [comment]
4/5 items addressed by #3908. 

> **Current Singular Template**

Do we need this one or is it be covered by the template creation feature?

**Comment by kjellr** [comment]
I think it's covered by the template creation feature, though I haven't personally tested that in a block-based theme. Will it produce a totally blank template there?

**Comment by jffng** [comment]
Tested with blockbase just now. It looks like creating a new template from a post / page will produce a template that pulls in the header, separator, post title, and post content (no footer, which is weird):

<img width="1282" alt="Screen Shot 2021-05-25 at 9 49 19 AM" src="https://user-images.githubusercontent.com/5375500/119509619-a5523580-bd25-11eb-92f7-9ddb5a610b86.png">

You can delete the blocks pretty easily from there. But I find it strange that the template editor doesn't copy exactly the `singular` template by default.

**Comment by kjellr** [comment]
Yeah, that's weird. Might be worth an issue? I think a blank template option is warranted in this case. 

Also, I added a new checklist item here to provide a new theme screenshot. I'll work on that later today.

**Comment by jffng** [comment]
> Might be worth an issue? I think a blank template option is warranted in this case.

https://github.com/WordPress/gutenberg/issues/32211
