### ISSUE TITLE
Pique: Traditional "Home" button functionality with anchor menu setting.

### ISSUE THREAD

**Issue by thebud15** [Automattic/themes#39]
The user likes how the "anchor menu" in Theme Options takes visitors to panels on the main page, however he doesn't like that this excludes a traditional "Home" button to take you to the very top of the site (not just a Home panel _near_ the top of the site).

We worked on a workaround in Slack that amounts to re-creating the menu using custom links to each of the panel items and a custom link for the Home button. The user wasn't satisfied with this workaround and wanted to request that the feature be available to have a traditional Home menu button in conjunction with the anchor menu setting. 

Thanks for hearing the suggestion, Theam!

Slack discussion with KP: p1520893893000437-slack

* User report: 1761720-hc
* Follow-up ticket: 1013510-zd
* User's site: https://albionrock.com and gbdgolf.wordpress.com

**Comment by sixhours** [comment]
It's unlikely we'd add this feature to Pique at this point in its life cycle, although it's something we can keep in mind for Pique 2.

One potential solution for the customer's self-hosted site is to create a child theme with a function that adds this functionality.

I'd suggest wontfixing.

**Comment by kathrynwp** [comment]
I agree with a wontfix. This is the only request we've had for such a feature in the several years since the theme is out, and the one-time workaround for each site is quite simple.

**Comment by sixhours** [comment]
Updated the internal note in the ZD ticket. Marking as wontfix.
