### ISSUE TITLE
Quadrat: Comments form on top of footer polygon

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#3903]
Right now the header and footer polygons are visible on every page, this causes some overlap on single pages when the comment form is visible and I think it makes the textarea not very accesible. We could hide the footer polygon on single pages or make changes to the form so that it stands out more. @beafialho @kjellr I'd love your input on this issue, thank you!

<img width="1246" alt="Screenshot 2021-05-21 at 09 15 33" src="https://user-images.githubusercontent.com/3593343/119097600-38812780-ba15-11eb-900c-730ba01c46c8.png">

**Comment by beafialho** [comment]
I think we can remove the shape in the footer, as it also simplifies it for pages where there's little content.

**Comment by MaggieCabrera** [comment]
> I think we can remove the shape in the footer, as it also simplifies it for pages where there's little content.

Should we leave it only on the home page then?

**Comment by beafialho** [comment]
Yes, let's leave the polygon in the footer only in the home page and keep the polygon in the header on all pages.
