### ISSUE TITLE
Twenty Twenty: Fonts chosen in Customizer not being applied to Form Block labels

### ISSUE THREAD

**Issue by sajmes** [Automattic/themes#3910]
## Steps to Replicate

1. Go to customize > fonts and select custom fonts for Headings and Base Font. (in this case headings = overpass and base font = open sans)
2. Add a form block to a page on the site.
3. Preview page.

## Result

The font used on the form labels appears correct while editing but does not match custom font when previewing. The font reverts to the form default of Hoefler Text on preview. 

**While editing form**
![](https://d.pr/i/ZoRhCo+)

**While Previewing same form in new tab**
![](https://d.pr/i/4HnhVr+)

## Expected

Expected styles applied to site in customizer to apply to form block text. 

* User report: 4004140-zd

**Comment by danieldudzic** [comment]
This has been now fixed via r58997
