### ISSUE TITLE
Varia: Update text and link when there are no published posts

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#3913]
As per #3887 - can we please update the content that is shown when a user has 'Latest Posts' selected for the Front Page, but no published posts.

### Steps to reproduce the behavior

1. Make sure your site has no public posts (no posts, or all posts set to be drafts)
1. Set Customizer > Home Page Settings to 'Show Latest Posts'

When previewing the front end of the site - text is shown which is a little confusing - stating 'Nothing Found'. This can be very confusing for users who either:

* Have draft posts created (they think they have lost them)
* Have created a home page - but don't have it set to show

<img width="549" alt="Screen Shot 2021-05-23 at 2 16 40 pm" src="https://user-images.githubusercontent.com/1842363/119248036-aeca8900-bbd1-11eb-8256-621c13e8b3c1.png">

**Comment by jordesign** [comment]
I have a PR prepared for this in #3914

**Comment by sixhours** [comment]
It looks like the corresponding PR was merged, so I'm going to close it out. Nice work @jordesign !
