### ISSUE TITLE
Blockbase: styles are not loaded correctly in Atomic sites

### ISSUE THREAD

**Issue by Aljullu** [Automattic/themes#3932]
## Steps to replicate

1. Create a Business site in .com.
2. Create a page with an HTML block like these and verify it looks correct (see screenshot below):
```HTML
<!-- wp:html -->
<table style="background: #eee; width: 100%">
<tr>
<td>Lorem</td>
<td>Ipsum</td>
</tr>
<tr>
<td>Input:</td>
<td><input type="text" /></td>
</table>
<!-- /wp:html -->
```
3. Once the site is created, install an extension. I tried with WooCommerce and Yoast SEO.
4. It will tell you the domain will change from `wordpress.com` to `wpcomstaging.com`.
5. Refresh the page you created in step 2 and notice styles are not loaded correctly.

| Step 2 | Step 5 |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/119466795-43092d00-bd45-11eb-98af-ff6b454055aa.png) | ![imatge](https://user-images.githubusercontent.com/3616980/119466826-48667780-bd45-11eb-867e-6f92f48084fe.png) |

**Comment by Aljullu** [comment]
Heads-up that I was able to reproduce as well with Seedlet Blocks, so this might not be related to the theme but to the process of converting the site to Atomic?

| Before installing a plugin | After installing a plugin |
| --- | --- |
| ![imatge](https://user-images.githubusercontent.com/3616980/119953266-1c91fe80-bf9e-11eb-8d4a-3706911b21cc.png) | ![imatge](https://user-images.githubusercontent.com/3616980/119953307-2451a300-bf9e-11eb-8b81-1c5cf9f8e560.png) |

**Comment by MaggieCabrera** [comment]
Hi @Aljullu is this still happening to you? I think this might have happened at some point during development but I'm not sure it's the case anymore. I have https://theamshopdemo.wpcomstaging.com/ setup with Blockbase and tested it with Quadrat too and styles are loading fine.

**Comment by mikachan** [comment]
Hey @Aljullu. I've also just tried this out with a new business site using Blockbase, and I couldn't replicate the issue. The styles loaded fine for me and my test page looked the same both before and after installing the Woocommerce plugin and the Yoast SEO plugin.

I agree with @MaggieCabrera, this probably happened sometime during development but it's fine now.

**Comment by MaggieCabrera** [comment]
I'm closing this, thanks @mikachan for testing. If it happens again, please let us know!
