### ISSUE TITLE
Blockbase: More block appears out of alignment

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3951]
On the front end, the more block appears out of alignment with there rest of the text: 

<img width="1637" alt="Screen Shot 2021-05-26 at 9 01 04 AM" src="https://user-images.githubusercontent.com/1202812/119664107-026ee980-be01-11eb-8951-f4a8439063d3.png">

**Comment by jffng** [comment]
I just tried to recreate, but it seems to be fixed:

<img width="786" alt="Screen Shot 2021-05-27 at 11 32 41 AM" src="https://user-images.githubusercontent.com/5375500/119854733-2c3e1400-bec6-11eb-819b-eee7a977a08a.png">

 I think this was resolved by recent alignment refactors in Gutenberg + blockbase.

Closing but please re-open if it's still an issue.
