### ISSUE TITLE
Blockbase: Replace theme screenshot

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3952]
A subset of #3895. 

We have a few options for replacing this image, and I'd like to get some thoughts from @melchoyce and @beafialho. Since the theme is meant to be as barebones as possible, it is not shipping with any block patterns at all. What do you think of these options? Any other recommendations? I kind of lean towards the simplicity of that last one, though I worry it may lead folks to believe it's a "just" portfolio theme. It _could_ be that if a user wanted it to be, though it's simple enough that it's really very flexible. 

## Option 1: Simple Posts

![Screen Shot 2021-05-27 at 09 09 44](https://user-images.githubusercontent.com/1202812/119665201-254dcd80-be02-11eb-84a9-ffaf4018b34f.png)

## Option 3: Single Post with Image

![Screen Shot 2021-05-27 at 09 29 56](https://user-images.githubusercontent.com/1202812/119668186-f2f19f80-be04-11eb-8a6b-d49015510edc.png)

## Option 2: Gallery

![Screen Shot 2021-05-27 at 09 20 28](https://user-images.githubusercontent.com/1202812/119666738-a35ea400-be03-11eb-84c3-cebc71c92cac.png)

**Comment by beafialho** [comment]
The most inviting would be Option 3 but like you said and well, it can look like a portfolio, so perhaps something in between like Option 2 but with an appealing image, with more color. Maybe even in a blue like the accent color, could look good:

<img width="952" alt="Captura de ecrã 2021-05-26, às 16 32 27" src="https://user-images.githubusercontent.com/65220155/119688623-0d953a00-be40-11eb-8d23-117fcc7f7c63.png">

**Comment by kjellr** [comment]
Yeah, now that you mention it, the image is definitely not appealing. 😄 I'll do some more digging.

**Comment by melchoyce** [comment]
A simple, colorful image seems like a good direction to help it stand out — especially when looking at https://wordpress.org/themes/, where a lot of the top themes use muddier or more complicated images. Having a clear focal point could also help, I think.

Some other ideas:

- https://stocksnap.io/photo/maldives-couple-Z2FVSJZAEN
- https://stocksnap.io/photo/husky-animal-LN2XAPQLBI
- https://stocksnap.io/photo/hibiscus-flower-MZ6G5MIJRP
- https://stocksnap.io/photo/jellyfish-water-KCUKTUPDC3
- https://stocksnap.io/photo/bird-beak-YRHJ3KQLM7
- https://stocksnap.io/photo/plant-fern-IRQ7ESFXU7
- https://stocksnap.io/photo/Matterhorn-clouds-RDTROOMH1P
- https://stocksnap.io/photo/water-pool-DROOJGOJTE

![image (1)](https://user-images.githubusercontent.com/2846578/119701497-65bd4380-be22-11eb-8ecf-cb89d08055f3.jpg)

**Comment by melchoyce** [comment]
Chatted a bit with @kjellr and @beafialho about this, and we decided to use public domain artwork instead of photography. Here are two options:

[The Water Fan](https://www.rawpixel.com/image/3044775/free-illustration-image-ship-water-man) | [Mount Fuji From Mizukubo](https://www.rawpixel.com/image/3064491/free-illustration-image-japanese-japanese-art-japan)
------------ | -------------
![image](https://user-images.githubusercontent.com/2846578/119726660-5993af00-be3f-11eb-95c3-c4d8f9e6505e.png) | ![image](https://user-images.githubusercontent.com/2846578/119726690-60babd00-be3f-11eb-8405-6b457809f95d.png)

**Comment by beafialho** [comment]
I love that we're using artwork here, IMO "The Water Fan" seems to blend better with the accent color.

**Comment by kjellr** [comment]
Great, thanks! Let's use the Winslow Homer one. I'll open a PR shortly.
