### ISSUE TITLE
Ixion: No padding in the Group block

### ISSUE THREAD

**Issue by happychait** [Automattic/themes#3957]
### Steps to reproduce the behavior

1. Activate Ixion theme.
2. Add a page 
3. Choose a page template that has a Group block. Or Group some blocks and set the background color.
4. Publish the page.

#### What I expected to happen

Some padding between the borders of the Group block and content.

#### What actually happened

Content sticks to the border of the Group block.

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/1519466/119758884-64ac1500-befb-11eb-9ec2-c1bdf35b455e.png)

#### User report

26433379-hc

**Comment by ClassicRKR27** [comment]
I have another report of this here: 36474823-hc

Screenshot: ![HtKrkW.png](https://user-images.githubusercontent.com/51870544/191261201-f6db287a-a062-4688-89c0-5cd46aa2ec02.png)
