### ISSUE TITLE
Blank Canvas Block: Navigation block collapses to the left when selected

### ISSUE THREAD

**Issue by Aljullu** [Automattic/themes#3975]
## Steps to replicate

Reported in pca54o-1mt-p2#comment-1886.

> The navigation area shows placeholder menu graphic (when no menu is assigned yet). This menu graphic was on the right side of the page, however, when I checked on it to edit it, it moved to the left, and after I assigned a menu item to it, it again moved to the right.
> 
> ![Screen Capture on 2021-05-27 at 19-12-29](https://user-images.githubusercontent.com/3616980/119958453-59142900-bfa3-11eb-834d-3c16c9d39555.gif)

I was able to reproduce this as well:

_Navigation block unselected:_
![](https://user-images.githubusercontent.com/3616980/119958701-9082d580-bfa3-11eb-8c3f-dbd245534b62.png)

_Navigation block selected:_
![](https://user-images.githubusercontent.com/3616980/119958750-9d9fc480-bfa3-11eb-912c-4333acc249c8.png)

## Expected

I expected the Navigation block to stay in the same position when selected and unselected.

**Comment by maharzan** [comment]
I can confirm this to Blockbase too

**Comment by maharzan** [comment]
It looks like this is a gutenberg issue and when the + sign appears, the justify-content: space-between; property automatically puts equal spaces around the previous element thus it looks like its pushed to the left. I tried this css in the theme and it seems to fix it but I think it won't be a solution that fixes all..

    .block-editor-block-list__block .block-list-appender {
	margin: 0;
    }

    .editor-styles-wrapper .site-header {
	justify-content: flex-end;
    }

    .wp-block-navigation {
	margin-left: auto;
    }

**Comment by pbking** [comment]
This seems to happen in all themes and is an issue on the Navigation Block and should be [reported there](https://github.com/WordPress/gutenberg/labels/%5BBlock%5D%20Navigation) instead.

**Comment by Aljullu** [comment]
I opened an issue in Gutenberg about this: https://github.com/WordPress/gutenberg/issues/32539.
