### ISSUE TITLE
Rosalie: Reading Time Calculation

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/themes#3984]
## What happened:

A user came on chat mentioning that the Reading time calculated on their posts are not accurate and it seems to display more time as compared to the Reading time on LinkedIn for the same posts.

## Expected

On checking the theme code, it looks like the $words variable actually splits more stuff up than words in the code and counts all white space as well (/\s+/)

* User report: 29885720-hc

**Comment by nielslange** [comment]
Hello @poojashetty18 👋 As the Rosalie theme is a premium theme from a 3rd party developer, I moved your report to https://wpcom-premium-themes.trac.automattic.com/ticket/3356.
