### ISSUE TITLE
Business: Gutenberg: Cover image goes to the left when making it fullwidth

### ISSUE THREAD

**Issue by gpmw** [Automattic/themes#399]
Testing in Calypsoified Gutenberg page editor on a Simple site with a Premium plan upgrade with no custom domain using the Business theme.

#### Steps to reproduce
1. In the Calypsoified Gutenberg page editor, add a Cover image block.
2. Add an image
3. Make the image full width
4. The cover image block is pushed to the left.
5. Change image to any other alignment and it works as normal

#### What I expected
The image should be displayed as fullwidth in the editor

#### What happened instead
The cover image block is pushed to the left

#### Browser / OS version
Google Chrome Version 70.0.3538.102 (Official Build) (64-bit)
Mac OS Mojave Version 10.14.1(18B75)

#### Screenshot / Video
http://cld.wthms.co/1xMPEe

Previously posted here: [#](https://github.com/Automattic/wp-calypso/issues/28809#issuecomment-441148517)

**Comment by torres126** [comment]
WordPress/gutenberg#11848

**Comment by laurelfulford** [comment]
Thanks for the report, @gpmw! Is there a ticket or chat link for follow-up? 

I've assigned this to @mendezcode because he's been doing a lot of work on Business, and this may be included in his upcoming fixes; Ernesto, if that's not the case, please feel free to unassign!

**Comment by gpmw** [comment]
This was on one of my test sites so there is nothing to follow up on. Just with me :)

**Comment by laurelfulford** [comment]
@gpmw Cool, thank you! :)

**Comment by mendezcode** [comment]
This has been fixed as part of the [editor styles rewrite](https://github.com/Automattic/default-small-business-theme/commit/b39bb05a191fd2177c8e547089843dcf6cd40806).
