### ISSUE TITLE
Varia: Related posts alignment issue

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#3991]
Some Varia themes (Exford and Hever have been tested) show the Related posts aligned to the left, not centered.

## Steps to replicate

* Activate Related posts on a site using Exford or Hever
* View alignment on post

## Result

![https://d.pr/i/mk1oxK](https://d.pr/i/mk1oxK+)

## Expected

Should be centered, used this to resolve:

```
/* Related posts alignment */

div#jp-relatedposts {
  margin-left: auto;
  margin-right: auto;
}
```

* User report: Hever: 29475004-hc
* User report: Exford: 29364803-hc

**Comment by scosgro** [comment]
Another report in 4080292-zd.

In my testing, I could only replicate on AT.

**Comment by formosattic** [comment]
+1 with Exford, 32304036-hc
The CSS fix worked.

Similar reports for:

* Goodz Magazine, https://github.com/Automattic/themes/issues/2937
* Blank Canvas, https://github.com/Automattic/themes/issues/4374

Also, this is possibly related to AMP? See https://github.com/Automattic/newspack-theme/issues/1290

**Comment by formosattic** [comment]
+1 33429033-hc

**Comment by lizswafford** [comment]
Similar issue with Morden theme on AT. 5341605-zd. 
The CSS fix worked.

**Comment by zyousafi** [comment]
Another report here: 5352563-zen (Barnsbury)
The CSS fix worked

**Comment by bobmatyas** [comment]
I could replicate this on self-hosted, it isn't limited to just Atomic.
