### ISSUE TITLE
Blockbase "Getting started" suggestions

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3999]
Hi folks! I spent a little bit of time this evening testing out Blockbase as a child theme, and I struggled a little bit during setup. Here are some issues that I ran into while trying it out: 

- A command line tool for generating a child theme would be wonderful. Today, our instructions require you to do some copy/paste from existing themes.
- Currently, we say the theme requires "package.json, style.css, and empty index.php files" for setup. But in practice, I needed a block template in block-templates before WordPress would recognize this as a block theme. In addition, the build scripts didn't work unless I'd already added a child-theme.json file to the child theme.
- Also — while it's probably obvious to some — the build steps require requires the child theme and `blockbase` to both to be in the same directory. They also require you to first run `npm install` in the both the `blockbase` and child theme folders. We should make that a bit more clear.

**Comment by pbking** [comment]
I think a generator script would be a super idea and would really cover all of the things you mention; positioning the parent/child correctly, ensuing all of the files are in place for an initial build out-of-the-box.  The generator script in theme-experiments copying emptytheme is something I used VERY heavily for a while so there's great advantage to that.
