### ISSUE TITLE
Dara: Theme Credit Displaying in Footer (LOCALE: ES)

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#4]
Originally reported by @rantoncuadrado in 4553-wpcom-themes:

## Steps to replicate

Apply Dara theme to a website Under Settings, change language to Spanish.

## Result

There is theme information on the footer:

"BLOG DE WORDPRESS.COM. TEMA: DARA POR AUTOMATTIC." 

## Expected

There is no theme information on the footer, like when the site is using English.

This was reported for a couple themes using Dara:
* https://resuniconbarna.com/
* https://sersolar.cl/

It's also happening with this theme on sites set to French (reported by @rwaynick):
* User's site: https://lecoinbusiness.com
* Slack discussion: p1497900926804373-slack-themes

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883

**Comment by eduardozulian** [comment]
A similar case in 38019835-hc but with `de` locale instead.
