### ISSUE TITLE
Intergalactic 2: Image Captions in editor are invisible/white

### ISSUE THREAD

**Issue by formosattic** [Automattic/themes#4002]
In the editor (live page is ok), image captions are white, as if invisible, looks like the .is-dark-theme is applied when it shouldn't:

```
.is-dark-theme .wp-block-image figcaption {
    color: hsla(0,0%,100%,.65);
}
```

![image](https://user-images.githubusercontent.com/15944096/120751464-9bf17600-c53a-11eb-8efb-796143126054.png)

* Follow-up ticket: 4042339-zd-woothemes

**Comment by ericamQA** [comment]
Duplicate of #53422

**Comment by ericamQA** [comment]
Closed in favor of https://github.com/Automattic/wp-calypso/issues/53422
