### ISSUE TITLE
Toujours: Image attachment pages do not display image

### ISSUE THREAD

**Issue by bornaware** [Automattic/themes#402]
## Steps to replicate
1. Upload an image without attaching to a post
-or-
Detach an attached image.

2. View the attachment page.

## Result

No image displayed on the page.

## Expected

Image displayed on the page.

* User report: #8357027-hc
* Follow-up ticket: #1599456-zd
* User's site (**user has changed themes**): https://chloesamericangirl.com/img_3326-595x335-2/

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
