### ISSUE TITLE
Coutoire: Option to unstick menu

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#4022]
Just noting requests we've seen from folks who love Coutoire but want an option for the menu to scroll off page. We currently encourage them to switch themes, and keep the front page layout if they like that.

* User report: https://wordpress.com/forums/topic/how-to-do-changes-in-theme-options/

**Comment by supernovia** [comment]
Another: https://wordpress.com/forums/topic/help-how-to-turn-off-sticky-header-in-coutoire-theme/

**Comment by supernovia** [comment]
https://wordpress.com/forums/topic/menu-288/

**Comment by supernovia** [comment]
https://wordpress.com/forums/topic/removing-sticky-title-and-menu/

**Comment by supernovia** [comment]
https://wordpress.com/forums/topic/menu-locked-in-place/

**Comment by supernovia** [comment]
https://wordpress.com/forums/topic/hi-there-32/

**Comment by Aurorum** [comment]
PR for this issue in #4041. :)

**Comment by supernovia** [comment]
Woohoo! Thank you!

**Comment by supernovia** [comment]
I'm gonna request a review on that PR, since I see another instance of this today. :)
https://wordpress.com/forums/topic/site-header-moving/

**Comment by jordesign** [comment]
Flagging this as high priority seeing as there is a PR in place for it already.

**Comment by scruffian** [comment]
We looked at this and decided that it would be too big a change to the theme, so closing this as wontfix, sorry :(
