### ISSUE TITLE
Baskerville 2: Gutenberg Images blocks can't be centered

### ISSUE THREAD

**Issue by spencerberry** [Automattic/themes#403]
## Steps to replicate

Publish a gutenberg post or page with a centered image block.

## Result
![screen shot 2018-11-29 at 12 13 23 pm](https://user-images.githubusercontent.com/1162736/49249078-343d9b80-f3d0-11e8-8035-a238aad7348e.png)

## Temporary Fix

- use a Classic block

OR

- use this CSS to fix it:
```
.wp-block-image .aligncenter {
  text-align: center;
}
```

* User report: #8320024-hc
* Follow-up ticket: #1607315-zen
* User's site: https://bookgeeksunc.com/2018/11/26/skyward-skyward-1/ (temporarily fixed with appended CSS)

**Comment by laurelfulford** [comment]
Hey @spencerberry! This sounds like it might be this issue, which is affecting more than one theme:

https://github.com/Automattic/wp-calypso/issues/28756

I'm going to close this theme-specific issue, but if you have any questions please let me know!

**Comment by laurelfulford** [comment]
Actually, scratch that, I misspoke -- I think the issues in that other thread are theme-related :| 

It looks like it happens when a theme applies the style `display: block` to elements with the class `.aligncenter`. The image block uses `display: table`, so the display block messes that up.

**Comment by edwinho89** [comment]
Reported with similar issue: #9967532-hc

To align image captions under the image block, we can apply the following below:

```
.wp-block-image .aligncenter>figcaption {
    display: block;
}
```

**Comment by torres126** [comment]
From https://github.com/Automattic/wp-calypso/issues/28756#issuecomment-459014528

> Another case, on a site with the Baskerville 2 theme:
> 
> When the image is resized and centered in the editor, it shows as left-aligned in the frontend.
> We added display:block; to the CSS as a temporary workaround.
> hc-9976478

**Comment by laurelfulford** [comment]
Switching the priority on this one, since Baskerville doesn't have Gutenberg styles in the theme yet.

**Comment by laurelfulford** [comment]
Another report here, from #595 (hat tip @scosgro!):

* User report:  1795750-zen
* Follow-up ticket:  1795750-zen

**Comment by jessestu** [comment]
This came up in 10230156-hc

**Comment by rezzap** [comment]
Another report of this here: 1919494-zen

**Comment by formosattic** [comment]
+1 7649849-hc

In case user doesn't have Custom CSS, can suggest using Classic block.

**Comment by thabotswana** [comment]
Another report of this here: #497193-hc

**Comment by torres126** [comment]
#719

**Comment by eamcgill90** [comment]
Reported here too: #1953372-hc

Any chance somebody could post the CSS workaround here? I am unable to find it. It may be a suitable solution for this user for now.

**Comment by christianboyce** [comment]
Here you go, with instructions: Go to Appearance, then Customize, then Additional CSS. Add this to whatever is there:

`.wp-block-image .aligncenter>figcaption {
    display: block;
}`
Also add this:
`.wp-block-image .aligncenter {
  text-align: center;
}`

That works for me on my site, https://oneminutemacman.com. Good luck!

**Comment by aleone89** [comment]
Another report in #13689395-hc

**Comment by kristarella** [comment]
FWIW I came across this again today #9210244-hc

**Comment by rinazrina** [comment]
Another report in #11463287-hc 
Follow up #2240805-zen

**Comment by GeoJunkie** [comment]
Reported in #15980481-hc. Gave the above CSS as a workaround

**Comment by mendezcode** [comment]
✅ Fixed upstream on r54559-wpcom-themes.

**Comment by msilbers** [comment]
Provided CSS workaround to user in #2528694-zd, appears to still be an issue

**Comment by suyogyashukla** [comment]
Another case: #2541997-zen. The user is on Personal Plan and can't use CSS.

**Comment by mendezcode** [comment]
✅ Fixed upstream on **r54868-wpcom-themes.** (Baskerville-2)

**Comment by selectedselections** [comment]
Came up again in #22123076-hc for the Natural theme

Needed to provide code above for .alignleft and .alignright elements as well
