### ISSUE TITLE
Blank Canvas: Improve user experience when adding logo if headers are disabled

### ISSUE THREAD

**Issue by kwight** [Automattic/themes#4036]
It's possible to see the logo UI and add a logo when the "show header" setting is false (the default). The logo should only be available if a user turns on headers.

See: p58i-aJq-p2

**Comment by DanielSmithMichigan** [comment]
Posing a question to the team, how should this problem be solved ideally?

Discussion is here: pd2qbF-7C-p2

**Comment by DanielSmithMichigan** [comment]
Created a diff: D62950-code

**Comment by ianstewart** [comment]
Looks like we missed closing this one!
