### ISSUE TITLE
Libre 2: Smaller images in image blocks can't be aligned centre

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#404]
Moved from here: https://github.com/Automattic/wp-calypso/issues/28756#issuecomment-441827549

When you centre a small image block, it doesn't actually display as centred on the front-end. The issue looks to be related to these styles here setting the margins to 0, but it needs investigating: 

https://github.com/Automattic/themes/blob/master/libre-2/css/blocks.css#L78-L83

## Steps to replicate

1. Using a site that has Libre 2, add an image block.
2. Add an image to that block, and if it's not small, scale it down.
3. Centre the block. 

## Result

The block is centred in the editor, but not on the front-end.

* User report: https://en.forums.wordpress.com/topic/centering-images-4/
* User's site (with example of issue):  https://silverwilderness.wordpress.com/2018/11/28/romance-in-ya-is-not-realistic/

**Comment by selectedselections** [comment]
Hi there! This was reported by another user here zd-1633145
I was also able to reproduce the issue on my own test site.

**Comment by laurelfulford** [comment]
This was committed in r52700-wpcom-themes.

**Comment by laurelfulford** [comment]
Followed up on the forum thread.

@selectedselections it looks like that ZD ticket is now closed, so I can't leave a comment there. Could you please follow up with the user?  Thanks!
