### ISSUE TITLE
Quadrat: Inconsistency in blocks - frontend and editor:

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4048]
## Steps to replicate

There are some minor style issues with some blocks in the front-end and in the Editor.
![image-2](https://user-images.githubusercontent.com/275961/121685059-6529db80-cab7-11eb-88d2-5f47f93726b7.png)
![image-3](https://user-images.githubusercontent.com/275961/121685067-665b0880-cab7-11eb-923a-cb36844aa13c.png)
![image-4](https://user-images.githubusercontent.com/275961/121685073-678c3580-cab7-11eb-84a2-a3129d0a236f.png)

From pNEWy-dYW-p2#comment-53274

**Comment by pbking** [comment]
The HTML block editor should be taken care of by #4117.

**Comment by pbking** [comment]
The Table styles are taken care of in #4139

**Comment by pbking** [comment]
(FWIW the Facebook URL used in the above example is [this one](https://www.facebook.com/CDC/photos/a.184668026025/10158548370376026).)

Considering that the Facebook widget create an iframe I'm not sure what can be done regarding the darker hard-to-read text shown in the view.

**Comment by scruffian** [comment]
This was fixed by #4139 and #4117.
