### ISSUE TITLE
Quadrat: Contact styles mismatch between Frontend and Editor

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#4049]
## Steps to replicate

From a quick glance at the demo site, it seems the Contact textarea does not have the same styles in editor and front-end. Additionally, the submit button is not styled either.

## Result

Editor:

![contact-editor](https://user-images.githubusercontent.com/937325/121685202-ee451080-cabf-11eb-911a-7bdea89d3f96.png)

Frontend:

![contact-front-end](https://user-images.githubusercontent.com/937325/121685225-f4d38800-cabf-11eb-8ada-0c71527d2eba.png)

## Expected

The frontend and editor should be the same.

**Comment by pbking** [comment]
Page in question is here: Pd4MHQ-14-p2

**Comment by scruffian** [comment]
Fix here: https://github.com/Automattic/jetpack/pull/20234
