### ISSUE TITLE
Sync changes with wp-core default themes

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4052]
Sync changes from core themes to .com public themes.

PNEWy-cvG-p2

Theme | Diff | Change Approved | Change Deployed 
-------|------|-----|-------
TwentyTwentyOne | D62690-code |
TwentyTwenty  | D62708-code |
TwentyNineteen | D62715-code |
TwentySeventeen | D62693-code |
TwentySixteen | D62694-code |
TwentyFifteen | D62696-code |
TwentyFourteen | D62698-code |
TwentyThirteen | D62701-code |
TwentyTwelve | D62705-code |
TwentyEleven  | D62706-code |

**Comment by pbking** [comment]
A number of the above changes are resulting in an error when applying the patch seemingly related to the addition of images.  More details can be found on the TwentyTwelve patch: D62705-code

**Comment by scruffian** [comment]
Were there no changes for twenty eighteen?

**Comment by MaggieCabrera** [comment]
> Were there no changes for twenty eighteen?

2018 has no default theme :D

**Comment by scruffian** [comment]
😱

**Comment by scruffian** [comment]
I have reviewed all of these. most are ready to be deployed.

**Comment by pbking** [comment]
Moving this back to in-progress until:

* This missing(ish) images issue noted in the 2021 patch (D62705-code) (and happening in all of the diffs with additional images) has been resolved.

* The themes changes coming in CORE for 5.8 have settled so that they might be brought in (as more stable versions).

**Comment by pbking** [comment]
This has since been synced.
