### ISSUE TITLE
Quadrat: Query Block not working

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4060]
While trying to replicate the post cards design as shown below, the query block isn't showing up.

<img width="826" alt="Captura de ecrã 2021-06-15, às 10 32 37" src="https://user-images.githubusercontent.com/65220155/122029791-18027e00-cdc5-11eb-981a-30da8338fba3.png">

Weirdly, this is what shows up instead:
<img width="1526" alt="Captura de ecrã 2021-06-15, às 10 36 20" src="https://user-images.githubusercontent.com/65220155/122030336-9a8b3d80-cdc5-11eb-80b9-9b2cc4da3d4b.png">

Can be seen [live here](https://quadratdemo.wordpress.com).

**Comment by jffng** [comment]
👋  @beafialho 

We created those post card layouts as media & text block patterns actually. It is not a pattern for the query block yet, we could add consider how to do this but I'm not sure we will get to it for v1.

Are you still seeing the issue where the query block doesn't show up at all though?

**Comment by jffng** [comment]
I removed that query block from the demo site because it seemed like it was using an old version of it / the block markup was strange, and added some block patterns instead.  

I discovered a new bug related to those patterns, opened an issue here: #4119

**Comment by beafialho** [comment]
👋 @jffng I see, I had thought of those three cards as the latest posts, so I'll update those.

> Are you still seeing the issue where the query block doesn't show up at all though?

No, I just checked and I can now see them!
