### ISSUE TITLE
Quadrat: Make posts featured images content width

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4063]
Currently, we have featured images on posts looking like this:

![Frame 10](https://user-images.githubusercontent.com/65220155/122079006-ec978780-cdf4-11eb-964d-4ee7ae8eb49c.png)

The problem is that squared images like the one above get so big that we have to scroll a lot to get to content, which is not cool. 

I had checked with @kjellr that we'd established having images be full width, but the solution didn't seem ideal either when I tried it, at least for posts:

![DM Sans-1](https://user-images.githubusercontent.com/65220155/122079638-82331700-cdf5-11eb-96bb-521548da0c5a.png)

So I suggest we keep featured images the same width as text, as exemplified below. They're still there but don't get in the way of content.

![DM Sans](https://user-images.githubusercontent.com/65220155/122079246-2072ad00-cdf5-11eb-82d5-dd1d49658107.png)

**Comment by kjellr** [comment]
That sounds good to me. 👍
