### ISSUE TITLE
Quadrat: Social Menu not appearing when assigned

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#4080]
### Steps to reproduce the behavior

1. go to the Customizer
2. assign a menu with items to the 'Social' location

#### What I expected to happen

Social menu to appear in some location

#### What actually happened

No menu appearaed

#### Does this happen on simple or atomic sites or both?

Simple

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

<img width="1749" alt="Screen Shot 2021-06-22 at 12 51 39 pm" src="https://user-images.githubusercontent.com/1842363/122855550-be67f980-d358-11eb-801f-f73689d220b9.png">

**Comment by MaggieCabrera** [comment]
@kjellr @beafialho I only see the social links designed on the figma for mobile:

<img width="493" alt="Screenshot 2021-06-30 at 13 20 30" src="https://user-images.githubusercontent.com/3593343/123952256-0a90ea80-d9a6-11eb-83f3-ef78862923db.png">

I'm also not sure how much we can do at the moment with the navigation block to make the mobile menu look like that. 

Where should we have the social links on desktop?

**Comment by kjellr** [comment]
I suggest we "start small" and not include a social links navigation at all for now. 

When folks use this as a block-based theme, there will be lots of opportunities to add one in ([and we can leverage patterns to make that easier](https://themeshaper.com/2021/06/25/theme-patterns-for-the-site-editor/)). But in the meantime, I think implementing it will be more trouble than it's worth. 

If users want to link to social media while using the classic version of this theme, they can do so with text links in their standard navigation and I think that's a fine compromise.

**Comment by pbking** [comment]
Per @kjellr 's comments I've removed the social menu location so there isn't confusion as to why it isn't showing up anywhere.

**Comment by happychait** [comment]
Another report in 33569409-hc

**Comment by pbking** [comment]
Checked this again prompted from the HC report.  Found it to still be working as-expected:

![image](https://user-images.githubusercontent.com/146530/148781720-55885d75-1cdb-4b20-8758-bc24db5169b4.png)

![image](https://user-images.githubusercontent.com/146530/148781786-4e8cdc7f-dce1-406a-8a67-bb358591d3ff.png)

![image](https://user-images.githubusercontent.com/146530/148781807-0be999d9-9d72-47e9-a15e-e586c00eae17.png)
