### ISSUE TITLE
Fortune: Theme style increasing padding in the separator block

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#4085]
## Steps to replicate

1. Activate the Fortune theme on a simple or AT site
2. Add the Separator block
3. In the Separator block settings set a color 

## Result

The padding for the Separator block is increased:

![Screen Shot 2021-06-22 at 11 49 59](https://user-images.githubusercontent.com/3696121/122967346-fc145480-d34f-11eb-80b8-896b0afaa7ba.png)

## Expected

For the padding to remain the same even when adding colors:

![Screen Shot 2021-06-22 at 11 50 32](https://user-images.githubusercontent.com/3696121/122967420-0f272480-d350-11eb-896f-6e2fce764725.png)

## Context

I noticed this CSS code from the theme styles causes the issue:

`[class*="has-background"]`

I shared this code with the user as a temporary fix:

```
/* Fix for separator due to theme bug | XXXX-zen */
.wp-block-separator.has-background {
  padding: unset;
}
```

* User report: 4087042-zd-woothemes

**Comment by danieldudzic** [comment]
This issue has been now fixed via r39430-wpcom-premium-themes

**Comment by davipontesblog** [comment]
It doesn't seem like the fix has been applied to atomic sites yet.

**Comment by davipontesblog** [comment]
Sent the CSS workaround to the user here while waiting for atomic deploy: 4091590-zd-woothemes
