### ISSUE TITLE
Aquene:  New padding on .has-background visually breaking Separator blocks.

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/themes#4091]
After a recent update, Aquene now sets padding on any block with .has-background.

This might be impacting more but, so far, I've only encountered it impact Separator blocks.

This makes all new and past separator blocks with `.has-background` appear very large.

This was included in WPCOM premium theme changesets 39418 (39417 included updates on the editor side which don't seem to be causing issues):

```
[class*="has-background"]{
    padding:2rem;
}
```

## Steps to replicate

1. Activate Aquene
2. Add a Separator block and set a color. 
3. Preview or view the page. 

## Result

![image](https://user-images.githubusercontent.com/4887830/123160857-abc6f080-d43c-11eb-9155-521b7f6233f9.png)

## Expected

![image](https://user-images.githubusercontent.com/4887830/123160898-bf725700-d43c-11eb-9f52-131729130670.png)

## Workaround

To work around this, we can unset the padding. There are various ways to do that. 

For example:

hr.has-background {
    padding: unset;
}

* User report: 26309284-hc

**Comment by danieldudzic** [comment]
This has been now fixed via r39429-wpcom-premium-themes
