### ISSUE TITLE
Quadrat: Mobile Menu Styles

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4103]
With the usage of the new `__unstableLocation` block attribute Quadrat lost mobile navigation block support.

This is because the block attributes expressed on the navigation block in the header.html template file (specifically `"isResponsive":true`) aren't passed to the block renderer when using `__unstableLocation`.

![image](https://user-images.githubusercontent.com/146530/123455849-2e23f180-d5b0-11eb-9e96-0395fec2a560.png)

[This was intended to fix this very problem ](https://github.com/WordPress/gutenberg/pull/31911)but doesn't seem to be working as expected.  The fix is likely related in some way though.

While this is specifically problematic for Quadrat with the introduction of __unstableLocation to all BB themes the attributes on the block are lost resulting in incorrect alignment (in Seedlet-Blocks) and the loss of mobile navigation support in all themes should that navigation population method be used.

**Comment by pbking** [comment]
This is addressed in [this Gutenberg issue](https://github.com/WordPress/gutenberg/pull/33043).

**Comment by scruffian** [comment]
The Gutenberg issue is merged so we can close this
