### ISSUE TITLE
Affinity: Long site titles overlaps menu button on mobile devices

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#412]
## Steps to replicate
1. Activate theme
2. Set a long site title (more than 24 characters with Raleway font for example)

## Result

![image](https://user-images.githubusercontent.com/3521683/49652054-14355a00-fa18-11e8-93c1-89f90f70b7bd.png)

## Expected

[What you expected to happen.]
![image](https://user-images.githubusercontent.com/3521683/49652304-dbe24b80-fa18-11e8-84c2-87dc5fe90e1b.png)

* User report: #8645607-hc
* Follow-up ticket: #1628124-zd
* User's site: https://elisabethhillinger.com/

**Comment by Gilmoursa** [comment]
Mentioned by another user in:
#1737197-zd

**Comment by laurelfulford** [comment]
Merged into WP.com in 53225-wpcom-themes.

@catkit and @Gilmoursa -- it looks like the ZD tickets are now closed, so I can't add a comment to them. Can you please follow up with the users as needed? Thanks!
