### ISSUE TITLE
Independent Publisher 2: Audio Widget Play Button hidden

### ISSUE THREAD

**Issue by rezzap** [Automattic/themes#4120]
## Steps to replicate

Add an audio widget to the sidebar and activate the Independent Publisher 2 theme. I haven't been able to replicate this with any other theme in the meantime. 

The button still works, but it is hidden from view. 

![Image 2021-06-29 at 3 41 44 pm](https://user-images.githubusercontent.com/10325627/123818160-a6f8b580-d8f0-11eb-9626-ab0d26f6d210.jpg)

## Result

The play button or pause button do not display in the widget. 

## Expected

I'd expect the widget to display the play button as it does for other themes. 

* User report: 30385407-hc
* Follow-up ticket: 4103293-zen

**Comment by rezzap** [comment]
As a temporary workaround, the following CSS seems to work:

```
#media_audio-3 #mep_0 .mejs-playpause-button button{
background: transparent url(/wp-includes/js/mediaelement/mejs-controls.svg);
font-size: 0;
}
```

From @sarahfg 
p1624977656443300-slack-C4WC5LYM6

**Comment by JessBoctor** [comment]
Had a report of this in #30638810-HC

The button styling has now changed to look like different buttons entirely. 

<img width="807" alt="Screen Shot 2021-07-14 at 2 19 36 PM" src="https://user-images.githubusercontent.com/12505355/125694526-886f90e5-fc27-472d-a1db-251298a1e15c.png">

Here is the CSS I used as a workaround I used: 

```
/* Fix audio player button */
.mejs-button button, .mejs-button .button, .mejs-button input[type="button"] {
    background: transparent url(/wp-includes/js/mediaelement/mejs-controls.svg);
    border: 0;
    cursor: pointer;
    display: block;
    font-size: 0;
    height: 20px;
    line-height: 0;
    margin: 10px 6px;
    overflow: hidden;
    padding: 0;
    position: absolute;
    text-decoration: none;
    width: 20px;
    color: #fff;
}
```

**Comment by Gustavo-Hilario** [comment]
I tested this issue with a local and on a WordPress.com Simple site, but I couldn't replicate this issue. I think this is fixed now.
