### ISSUE TITLE
Quadrat: Submenu items appear to be the wrong color

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4133]
## Steps to replicate

- Populate Quadrat's navigation block (I did so while using it as a block-based theme)
- Ensure there are submenu items. 
- View on desktop — see that the items appear as black on white. 
- View on mobile — see that the items appear black against the dark purple background. 

## Result

Desktop|Mobile
---|---
<img width="303" alt="Screen Shot 2021-06-30 at 8 18 44 AM" src="https://user-images.githubusercontent.com/1202812/123959461-3008fe80-d97c-11eb-9f4b-2b9add5a1dd0.png">|<img width="474" alt="Screen Shot 2021-06-30 at 8 18 26 AM" src="https://user-images.githubusercontent.com/1202812/123959457-2f706800-d97c-11eb-83a3-43511f76a472.png">

## Expected

Desktop|Mobile
---|---
<img width="245" alt="Screen Shot 2021-06-30 at 8 27 48 AM" src="https://user-images.githubusercontent.com/1202812/123960300-2338da80-d97d-11eb-8e59-16e5bf14d160.png">|<img width="419" alt="Screen Shot 2021-06-30 at 8 28 03 AM" src="https://user-images.githubusercontent.com/1202812/123960302-23d17100-d97d-11eb-8990-39ff0bc79cfb.png">

**Desktop:**
 
Background: `var(--wp--custom--color--background)`
Border: `1px solid var(--wp--custom--color--secondary)`
Text Color: `var(--wp--custom--color--foreground)`

**Mobile:** 

Text Color: `var(--wp--custom--color--foreground)`

**Comment by pbking** [comment]
That mobile design isn't what was expected at all.  The mobile menu should (and does for me) look more like this:
<img src="https://user-images.githubusercontent.com/146530/123966462-72820980-d983-11eb-9d26-fb0b49b567a0.png" width=300>
<img src="https://user-images.githubusercontent.com/146530/123966939-ddcbdb80-d983-11eb-9ccd-59e5372ea7af.png" width=500>

I wasn't able to reproduce the above testing in 'Classic' mode or in 'FSE' mode.

**Comment by kjellr** [comment]
@pbking I just tried again on a fresh site and got the same result. Here's how I did it: 


https://user-images.githubusercontent.com/1202812/123983425-da3f5100-d991-11eb-82cf-8196a48a062b.mp4


1. Start a fresh WP site, install the Gutenberg plugin. 
2. Go to the Pages section of your new site, add some pages and subpages. 
3. Add an `index.html` so the theme loads in FSE mode. 
4. Upload the theme, activate it. 
5. Open the site editor. 
6. Click on the nav block, choose to "Add all pages".
7. Hover over these items, notice the incorrect colors.

**Comment by kjellr** [comment]
(Either way, I'd like for us to update the submenu border in your screenshots so it is `var(--wp--custom--color--secondary)` instead of the pink)

**Comment by pbking** [comment]
Update:
Debugging [here](https://rear-six.jurassic.ninja/) I found that the submenu container is styled with `class="submenu-container"` while locally it's using `wp-block-navigation-link__container`.

It shouldn't be a matter of how the navigation block is constructed (with __unstableLocation or building it out via FSE) as in both scenarios the Navigation block is doing the rendering...  So I'm not sure why the above is happening in the given environment.  Delving deeper, just updating my findings thus far.

**Comment by pbking** [comment]
Ah HAH!  The difference is that the situation in question was using the `page-list` block which (unfortunately) creates different markup than if you added `page-link` blocks individually.

I can address this with a slight CSS change, however I believe that the correct fix lies in the block.  I'll look into both.

**Comment by kjellr** [comment]
Thanks for tracking that down!

**Comment by pbking** [comment]
[This item in Gutenberg](https://github.com/WordPress/gutenberg/issues/31879), once resolved, will eliminate the need for multiple classes.
