### ISSUE TITLE
Lodestar: Rotating iPad orientation on portfolio creates varying levels of brokeness

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#416]
A user reported that when they viewed their porfolio on an iPad 2, and changed the orientation, the layout got messed up, with projects overlapping.

I was able to replicate this on an iPad 2; going from horizontal to vertical created a lot of overlap. Going from vertical to horizontal just created a lot of gappiness.

@supernovia and I were also both able to recreate in Browserstack and on the iOS Simulator; the effect seems worse the smaller the tablet screen is (you can see it in iPad Pros, but it's a lot less overlap/spacing).

It doesn't seem to affect Android devices -- the issue couldn't be recreated on a Pixel II -- but that could use more testing. 

## Steps to replicate

1. Load up a page using the portfolio template and the Lodestar theme on an iPad. (eg.https://lodestardemo.wordpress.com/work/)
2. Start with the iPad vertically oriented, then turn to horizontal. Note the appearance.
3. Refresh the page while still horizontal. Now switch it back to vertical.

## Result

It's a bit of a mess:

Starting with horizontal and going vertical:
![img_0098](https://user-images.githubusercontent.com/177561/49670399-780c5280-fa19-11e8-8734-89122cd7fe60.PNG)

![img_0099](https://user-images.githubusercontent.com/177561/49670360-54490c80-fa19-11e8-8cb8-be06bc398071.PNG)

Starting with vertical and going horizontal:

![img_0100](https://user-images.githubusercontent.com/177561/49670396-7478cb80-fa19-11e8-85d8-ecc745ac9d4b.PNG)
![img_0102](https://user-images.githubusercontent.com/177561/49670397-7478cb80-fa19-11e8-86c8-62bb14ea1ee1.PNG)

## Expected

The layout would update to fill the space.

* User report: https://en.forums.wordpress.com/topic/lodestar-portfolio-project-not-working/
* User's site: amazinggardendesign.wordpress.com

**Comment by laurelfulford** [comment]
Looking at the browser, I can actually recreate this by resizing it down around tablet-size too -- there's something not working quite right with the theme's JavaScript on resize event.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
