### ISSUE TITLE
Blockbase: Color customizations caching

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4173]
## Steps to replicate
In Blockbase, change colors in the customizer, and reload the front end. Notice that it takes some time for the new colors to show. I think this is a caching issue.

**Comment by pbking** [comment]
The same is true for Global Styles panel in the FSE.  It starts with the default colors for a few seconds before switching to the customized colors. This was before I saw the content render. This was especially noticeable on my sandbox but also noticed locally.

**Comment by scruffian** [comment]
i can no longer replicate this either. Closing for now.
