### ISSUE TITLE
Varia: Buttons block custom color hover issue 

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#4179]
Buttons which have custom colors set using the preset colors (the circles) don't correctly use the same custom text color on hover. This can result in the text not being visible on hover (or just the wrong text color even if it is visible). I've tested this on top of Cover blocks and outside the Cover blocks and the issue happens in both cases.

## Steps to replicate

Add a Buttons block to a page. Choose a custom background and text color using preset colors (the circles). View the page, hover over the button.

<img width="880" alt="Screen Shot 2021-07-07 at 11 25 50" src="https://user-images.githubusercontent.com/10353785/124787660-a8d8ff00-df16-11eb-881c-d126dc94d05b.png">

## Result

Text isn't visible on hover.

![Screen Capture on 2021-07-07 at 11-30-47](https://user-images.githubusercontent.com/10353785/124787844-d32abc80-df16-11eb-9175-2204a5945b9b.gif)

## Expected

Text should be visible on hover.

This appears to be the issue:

```
.wp-block-button__link:active,
.wp-block-button__link:focus,
.wp-block-button__link:hover,
.wp-block-button__link:visited {
	color: #fff;
}
```

Using a custom color instead of a preset color works since the color is then added inline.

* User report: 28759492-hc

**Comment by jordesign** [comment]
I can no longer recreate this issue - but it seems to have been replaced by another one with custom button colors:
https://github.com/Automattic/themes/issues/5202

Closing this now.
