### ISSUE TITLE
Quadrat: Some widget blocks use dark gray text

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4188]
The following widget blocks display their secondary content using a dark gray text. This is difficult to read against the theme's gray background, and I recommend we change it to the default text color instead. 

## Latest Posts (with Author Name and Post Date turned on) 

<img width="207" alt="Screen Shot 2021-07-08 at 7 41 25 AM" src="https://user-images.githubusercontent.com/1202812/124915981-273dab80-dfc0-11eb-8999-5fea7a408ae6.png">

## RSS (with Author and Date turned on) 

<img width="484" alt="Screen Shot 2021-07-08 at 7 41 31 AM" src="https://user-images.githubusercontent.com/1202812/124916123-4e947880-dfc0-11eb-8e14-c9c087abe715.png">

(While we're in here, I recommend we turn off the bullets, so the display matches the Latest Posts block.)

## Tag Cloud (with Show Post Counts turned on)

<img width="144" alt="Screen Shot 2021-07-08 at 7 41 41 AM" src="https://user-images.githubusercontent.com/1202812/124916233-6ff56480-dfc0-11eb-8fa5-02cc46049b95.png">

(This one only happens in the editor — [the front-end](https://cloudup.com/cJPTeT6Lbxg) has the right text color)

**Comment by scruffian** [comment]
Fix for the tag cloud portion of this here: https://github.com/WordPress/gutenberg/pull/33289

**Comment by scruffian** [comment]
I can't replicate the issue with Latest Posts:
<img width="173" alt="Screenshot 2021-07-08 at 14 41 20" src="https://user-images.githubusercontent.com/275961/124931981-9afcaa00-dffa-11eb-9d18-c348cd1bfaeb.png">

**Comment by scruffian** [comment]
The RSS change is here: https://github.com/WordPress/gutenberg/pull/33294

**Comment by scruffian** [comment]
Latest posts fix here: https://github.com/WordPress/gutenberg/pull/33325#issuecomment-877074816

**Comment by beafialho** [comment]
I noticed this happening in the Subscription Form block as well.

<img width="563" alt="Captura de ecrã 2021-07-13, às 14 51 05" src="https://user-images.githubusercontent.com/65220155/125463745-71579814-d306-434e-8e4d-7af0de1d98fb.png">

**Comment by scruffian** [comment]
Thanks, we are tracking that here: https://github.com/Automattic/jetpack/issues/17590
