### ISSUE TITLE
Varia: Text color on "Image showcase portfolio layout" pre-defined layout doesn't match editor

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#4189]
The text color in the first section of the "Image showcase portfolio layout" pre-defined layout shows white text in the editor but it's dark on the published page.

## Steps to replicate

Add the "Image showcase portfolio layout" pre-defined layout:

![Screen Shot on 2021-07-08 at 08:08:14](https://user-images.githubusercontent.com/10353785/124918997-b00a1680-dfc3-11eb-8821-f2a839ac45fa.png)

View "Introduce yourself.." text in the editor and the live page.

## Result

Editor:

![Screen Shot on 2021-07-08 at 08:10:16](https://user-images.githubusercontent.com/10353785/124919284-0bd49f80-dfc4-11eb-9be6-de3fd686bc34.png)

Live page:

![Screen Shot on 2021-07-08 at 08:09:48](https://user-images.githubusercontent.com/10353785/124919314-12fbad80-dfc4-11eb-9d72-3672d3b42364.png)

## Expected

The text should be white. The issue appears to be this CSS:

```
.wp-block-cover-image h1:not(.has-text-color),
.wp-block-cover-image h2:not(.has-text-color),
.wp-block-cover-image h3:not(.has-text-color),
.wp-block-cover-image h4:not(.has-text-color),
.wp-block-cover-image h5:not(.has-text-color),
.wp-block-cover-image h6:not(.has-text-color),
.wp-block-cover-image p:not(.has-text-color),
.wp-block-cover h1:not(.has-text-color),
.wp-block-cover h2:not(.has-text-color),
.wp-block-cover h3:not(.has-text-color),
.wp-block-cover h4:not(.has-text-color),
.wp-block-cover h5:not(.has-text-color),
.wp-block-cover h6:not(.has-text-color),
.wp-block-cover p:not(.has-text-color) {
	color: inherit;
}
```

Temporary solution is to choose a preset color:

![Screen Shot on 2021-07-08 at 08:12:53](https://user-images.githubusercontent.com/10353785/124919479-535b2b80-dfc4-11eb-8754-4b0ecd512f49.png)

The text on the thumbnail from the layout chooser also shows the incorrect dark color:

![Screen Shot on 2021-07-08 at 08:14:29](https://user-images.githubusercontent.com/10353785/124919756-961d0380-dfc4-11eb-90ba-ae895dc1dabd.png)

* User report: 4123398-zd-woothemes

Rockfield was the reported theme, I've tested multiple Varia child themes and they all have the issue.

**Comment by jamiepalatnik** [comment]
It looks like this is a larger issue with all Cover blocks on Varia themes. I can recreate this.

Screenshot of editor view:
<img width="1327" alt="Editor view Varia color bug" src="https://user-images.githubusercontent.com/30788962/144457998-75f12ffe-7662-4b23-a822-0b2d994ffa5e.png">

Screenshot of live view:
<img width="1337" alt="live view Varia color bug" src="https://user-images.githubusercontent.com/30788962/144458010-2070ae98-8ad0-4b30-b2d1-f83a9b3feb44.png">

**Comment by jordesign** [comment]
Closing this issue - as this particular pattern is no longer in use in the page layput selector. Definitely worth following along with https://github.com/Automattic/wp-calypso/issues/58846 for related cover block issues
