### ISSUE TITLE
Nikau: Tag Cloud Widget font size small in sidebar compared to other widgets/site fonts

### ISSUE THREAD

**Issue by sajmes** [Automattic/themes#4196]
A user reported that they found the font size when adding a Tag Cloud widget to the sidebar in Nikau to be disproportionately small compared to the other font sizes in the theme. 

It looks like the font currently displays as 8px, while other widgets such as Categories added in the same place have a larger font. 

![nikau](https://user-images.githubusercontent.com/76757079/125099487-0e0f2a80-e0a6-11eb-8286-4a0e40dadc56.jpg)

* User report: 4124523-zd-woothemes

**Comment by jordesign** [comment]
This theme is now retired and has only 2,593 active installs. Based on the severity of the issue, and no further reports in ~6 months I'm going to close this for now. Happy to discuss and re-open it if it seems needed.
