### ISSUE TITLE
Blockbase: Fonts

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4198]
The font weights/styles in [this file](https://github.com/Automattic/themes/blob/486aa30fbea19f695faae18460747b6b5041ace9/blockbase/inc/wp-customize-fonts.php) are probably not the best options. We should replace them with a normal, bold and italic option.

cc @kjellr

**Comment by kjellr** [comment]
Can you clarify this a little further? I recall mentioning that we should probably go through and verify that we're using correct "normal", "bold" weights for each of these fonts — is that what this issue is tracking?

**Comment by scruffian** [comment]
Yes exactly, that was never done :)

**Comment by kjellr** [comment]
Cool thanks. I'll assign myself and take care of this (hopefully) this week.

**Comment by kjellr** [comment]
In general, these should all be changed to: 

400 (Normal)
700 (Bold)

And we should load the italic variant of each of those weights. Libre Baskerville does not include a bold italic weight (unfortunately), so we shouldn't look for one in that case. 

If we tie into these appearance options, we'd want to pull in a more full set of weight variations:

<img width="277" alt="Screen Shot 2021-07-13 at 2 26 35 PM" src="https://user-images.githubusercontent.com/1202812/125505487-717e7206-3378-4710-8b9c-2a3d71766fb1.png">

But I'm not entire sure how that is supposed to work? Do we need to pull in every single weight for every font and also specify which ones we want for each font?

**Comment by scruffian** [comment]
I think so yes, if those options are surfaced in the editor.
