### ISSUE TITLE
P2 Breathe - change default font to `em` or `rem` base instead of `px` for better accessibility

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#42]
## Steps to replicate

Some P2s are configured with a fixed font, such as `14px`. I noticed this on some internal Automattic P2s. For example:

![](http://cld.wthms.co/WTbPt+)

## Result

This setting ignores a user's browser font preferences, and delivers what could be a small font for users who prefer larger text. 

## Expected

Changing the default `font-size` setting to something like `em` or `rem` should improve accessibility for users who prefer larger font sizing.

**Comment by davidakennedy** [comment]
This is a great suggestion. However, changing the font units on an older design active on so many sites could have unintended consequences. So I'm going to close this. We should address this type of feedback in a P2 redesign in the future.
