### ISSUE TITLE
Opti: Header Color changes are not saved

### ISSUE THREAD

**Issue by aisajib** [Automattic/themes#4204]
This was first reported in the forums: https://wordpress.com/forums/topic/header-background-not-changing-colour/

However, I wasn't able to replicate it on test sites. The issue is apparently reproducible on that have had the Opti theme active for a while. Both the user's site and the theme demo site (that have had the theme active for some time) showed the issues. 

## Steps to replicate
1. Open a site that has had the Opti theme active for some time.
2. Go to Customizer → Colors & Backgrounds → Palettes → Header, Footer (third circle) 
3. Choose a different color (Notice the new color is shown in the customizer preview). 
4. Click Save Changes.

## Result

No changes took place in the header background color. 
Reload the Customizer. The header background color reverts to what it was before the change. 

<img src="https://user-images.githubusercontent.com/2541844/125198433-a4e50e00-e283-11eb-9954-0b97fd94c930.gif" width="400">

## Expected

I expected the new header background color to be reflected on the live site. 

* User report: https://wordpress.com/forums/topic/header-background-not-changing-colour/

**Comment by jordesign** [comment]
This theme is now retired (and has ~2000 active installs). With no further report in ~6 months this is likely to remain very low priority. If this particular user contacts us again - the best course of action would be for them to change to a non-retired theme. 

I'm going to close this - but am happy to discuss and re-open if it seems needed.
