### ISSUE TITLE
Seedlet: Post excerpt block does not include the correct line height

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4208]
The post excerpt block has incorrect line height in the editor. 

## Steps to replicate

1. Add a "Post Excerpt" block. 
2. Save your post or page, view it on the front end.

## Screenshots

Editor|Front-end
---|---
<img width="631" alt="Screen Shot 2021-07-12 at 10 53 48 AM" src="https://user-images.githubusercontent.com/1202812/125309568-de5b5f00-e2ff-11eb-95e8-27ea806c61c7.png">|<img width="641" alt="Screen Shot 2021-07-12 at 10 53 54 AM" src="https://user-images.githubusercontent.com/1202812/125309569-def3f580-e2ff-11eb-95e3-9351ea765f9e.png">

**Comment by MaggieCabrera** [comment]
This is only happening on dotcom. On my local install with the latest GB from trunk and WP 5.8 I see it correctly. There's a missing p tag wrapping the excerpt text.

Dotcom | Local
--- | ---
<img width="749" alt="Screenshot 2021-07-21 at 16 08 33" src="https://user-images.githubusercontent.com/3593343/126502906-c9040724-7120-4f99-b724-33a03f14c1d0.png"> | <img width="1400" alt="Screenshot 2021-07-21 at 16 04 44" src="https://user-images.githubusercontent.com/3593343/126502915-7793b566-5d1b-452c-a2b1-a6aeb78a286c.png">

**Comment by MaggieCabrera** [comment]
Looking at the code of the block, I don't see that the p tag is being added at all in the editor, while it is present explicitly on the frontend. I'm going to put this one on hold until dotcom has the latest version of the editor and then go back to this, but if it's still happening, the fix belongs on the editor, not the theme.

**Comment by pbking** [comment]
Tested this again, it's still happening exclusively on .com.  The appropriate elements are rendered using any version of the plugin locally.  I haven't been able to determine what about that installation is causing it but again confirming that it's something specific there.

**Comment by mikachan** [comment]
I don't know if I'm over-simplifying this, but it seems this could be because the post excerpt isn't rendered as a paragraph in the editor (it's a div instead), whereas on the front end it is. I've opened a GB PR for this: https://github.com/WordPress/gutenberg/pull/37412

**Comment by mikachan** [comment]
This will be fixed with WordPress/gutenberg#37412, which is due to go into GB 12.3, so I think this can be closed.
