### ISSUE TITLE
Quadrat: Add example illustrations to the  media library as starter content

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4211]
As noted in [Quadrat's theme description](https://github.com/Automattic/themes/issues/3660#issuecomment-844228407), we intended for the theme to ship with the following illustrations added to he media library along with its starter content: 

<img width="855" alt="Screen Shot 2021-07-12 at 1 01 36 PM" src="https://user-images.githubusercontent.com/1202812/125327606-4bc3bb80-e311-11eb-8653-4bd4318a5ea3.png">

This can be done with both [starter content](https://make.wordpress.org/core/2016/11/30/starter-content-for-themes-in-4-7/), as well as headstart on dotcom. 

The compressed images can be found here: 
https://cloudup.com/cXwPqOGB6mr

**Comment by MaggieCabrera** [comment]
Closed via https://github.com/Automattic/themes/pull/4213
