### ISSUE TITLE
Quadrat: Clip-path polygons are bleeding weirdly on wide screens on Firefox

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4215]
## Steps to replicate

On a very wide screen, on Firefox the polygons on the header and the footer are acting strangely:

<img width="2494" alt="Screenshot 2021-07-13 at 13 06 16" src="https://user-images.githubusercontent.com/3593343/125441701-7a2831a5-1a9a-4239-8c0d-43fe56ff03f1.png">

**Comment by MaggieCabrera** [comment]
I narrowed it down to a [FF bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1707154) on screens that are doing some scaling. I think we should close this since hopefully it will be fixed on the browser and it's an edge case that will affect very few users.

**Comment by pbking** [comment]
I went very very wide (spanning both pretty-wide monitors) and couldn't reproduce.
Regardless of reproducibility I 2nd closing it.

**Comment by MaggieCabrera** [comment]
Yeah, it's not just the wide screen but you need to have the resolution scaled down. In my case I see it because I'm using a very wide monitor and I'm using Mac OS auto scaling, that's why I think it's a very edge case. It was important to confirm that it wasn't our code at fault. Closing then!
