### ISSUE TITLE
Twenty Twelve: Gutenberg: image blocks do not inherit full-width size

### ISSUE THREAD

**Issue by jruud** [Automattic/themes#422]
## Steps to replicate

1. Activate Twenty Twelve
2. Create new page & select Full-Width template
3. Save Draft or Publish
4. Add image block

## Result

The image block inherited a max width of 625px.

## Expected

I expected the image block to span the full width of the page (925px).

* User report: #1632933-zd
* Follow-up ticket: #1632933-zd
* Screenshot from test site using full-width page template: 
<img width="1019" alt="screen shot 2018-12-10 at 12 01 16 pm" src="https://user-images.githubusercontent.com/35117248/49748325-632afb80-fc73-11e8-9edf-48b75d597999.png">

**Comment by laurelfulford** [comment]
Thanks for reporting this issue, @jruud! 

This doesn't appear to be theme-specific -- I can recreate the same thing using the full-width template in Sketch. The block-based editor appears to use the theme's default `$content_width` to set the default image width, and doesn't adjust it for different templates (even though the theme will change that `$content_width` depending on template). 

I'm not sure this is editor-specific, or something just in the Calypso version -- I could recreate this on my sandbox, but on my localhost site, the default image size always seems to be set to 1024. I'm not sure if that's just something weird in my setup -- can you test and see if that matches your experience, too?

As a work around, it is possible to manually change the image size in the sidebar of the editor:

<img width="268" alt="image" src="https://user-images.githubusercontent.com/177561/49751201-aed4a980-fc61-11e8-9595-10611b890ff4.png">

**Comment by jruud** [comment]
@laurelfulford I had tested it on Shoreditch to see if it was theme-specific, and in that theme on Calypso the image is placed at 900px even without the full width template selected:

<img width="1477" alt="screen shot 2018-12-10 at 3 10 01 pm" src="https://user-images.githubusercontent.com/35117248/49758712-ae520800-fc8d-11e8-9310-0cc6ac6ef08a.png">

Since it behaved as expected there, I assumed it was just an issue with Twenty Twelve.

**Comment by laurelfulford** [comment]
> Since it behaved as expected there, I assumed it was just an issue with Twenty Twelve.

Understood! It appears to only be an issue in themes that have different `$content_width` settings in different contexts. Twenty Twelve does this for its full-width template(default is set [here](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwelve/functions.php#L26) and is updated [here](https://core.trac.wordpress.org/browser/trunk/src/wp-content/themes/twentytwelve/functions.php#L527); so does Sketch (default and full width are set back to back [here](https://github.com/Automattic/themes/blob/master/sketch/functions.php#L11)).

Shoreditch just appears to have the one `$content_width` ([#](https://github.com/Automattic/themes/blob/master/shoreditch/functions.php#L127)) so it works a-ok.

**Comment by laurelfulford** [comment]
Just to close the loop, this issue has been moved here: https://github.com/Automattic/wp-calypso/issues/29296

I'm going to close this issue, since it doesn't seem to be theme-specific.
