### ISSUE TITLE
Blockbase: Opt-in to support for border controls

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4220]
Blockbase should opt-in to custom border controls, as per [the notes in this comment](https://github.com/WordPress/gutenberg/issues/21540#issuecomment-829928480): 

```
	"settings": {
		"defaults": {
			"border": {
				"customColor": true,
				"customRadius": true,
				"customStyle": true,
				"customWidth": true
			}
		}
	}
```

**Comment by MaggieCabrera** [comment]
Yeah, I thought I remembered adding these controls. The thing is not all blocks surface them the same way but these settings [are already on Blockbase](https://github.com/Automattic/themes/blob/8630adc945503f187dae4b66aadf47e25069f4a2/blockbase/theme.json#L35). You can test them on the Group block:

<img width="283" alt="Screenshot 2021-07-14 at 09 30 44" src="https://user-images.githubusercontent.com/3593343/125581515-c0fa7cc9-0998-4f09-9851-7fe5fb336ad4.png">

**Comment by pbking** [comment]
Indeed, just tested in Quadrat too and it's working nicely as expected.  Interestingly I see a slightly different panel layout that pictured above but it works smashingly.  I didn't even know it was there. :P

I believe that the blocks will pick up the controls as support is expressed for them.  I don't believe there's anything more to do here.  It's already awesome!

Closing this as done.  Please reopen if I missed something!
