### ISSUE TITLE
Cannot activate Mayland blocks via theme showcase on wpcom

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#4229]
## Steps to replicate

1. Go to the theme showcase and filter by the Block Templates feature e.g. https://wordpress.com/themes/filter/block-templates/jffngsimple.wordpress.com
2. Try to activate Mayland blocks
3. Verify that you get an error

## Result

Inspecting the error returned from the API, I see a 500 error: `theme_php_incompatible`.

## Expected

I expect to be able to switch to Mayland blocks.

* User report: p1626290441464300-slack-C029FM1EH

**Comment by jffng** [comment]
I poked around a bit and if I set [this variable](https://opengrok.a8c.com/source/xref/trunk/wp-includes/theme.php?r=227606#917) `$compatible_php` to `true` instead of checking the requirements, I am able to activate Mayland blocks.

**Comment by pbking** [comment]
This is addressed in #4232.
