### ISSUE TITLE
Relevar: Question on Status

### ISSUE THREAD

**Issue by mrwweb** [Automattic/themes#423]
I'm currently trying to figure out whether Revelar makes sense to use on a project. I came here to see if a Gutenberg update is in the works and was surprised that I couldn't even find the theme at all. Is Revelar still being actively developed? If so, will it be updated for Gutenberg?

**Comment by laurelfulford** [comment]
Hi @mrwweb! Right now we're not planning on adding Gutenberg support to all themes on WordPress.com, but are focused on adding support to a select few of our older ones, as well as creating new ones. 

Our entire free theme collection (including Revelar) is [stored in SVN](https://wpcom-themes.svn.automattic.com/), and we still offer basic support and maintenance for all themes on WordPress.com.
