### ISSUE TITLE
Stratford/Varia: First color change from default colors produces unexpected results

### ISSUE THREAD

**Issue by DanielSmithMichigan** [Automattic/themes#4231]
### Recreation steps

1. Create a new site with stratford as the theme
1. Go to the customizer
1. Go to "Colors & Backgrounds"
1. Note that the site title and menu are blue
1. Change the "secondary color" from blue to red
1. Note that the site title and menu are dark gray now

### Example 1: Site title

![image](https://user-images.githubusercontent.com/10274366/125695890-7ab98d93-9a97-4e37-a38e-9911d7be0820.png)

### Example 2: Site menu

![image](https://user-images.githubusercontent.com/10274366/125695911-abcb97f4-c0f9-4a90-bf2a-94612b6f75cc.png)

### Problem

Even if the user only changed the background color, the primary-hover and secondary-hover colors are abandoned and recomputed using a different formula on every color change.

![image](https://user-images.githubusercontent.com/10274366/125696013-5cc7efbd-f544-4336-85c9-591bdbbf18f3.png)

Once you change ANY of the colors, primary-hover and secondary-hover are recalculated according to a formula:

primary-hover = primary + 10 luminosity
secondary-hover = secondary + 10 luminosity

See [this file for more information](https://github.com/Automattic/themes/blob/trunk/varia/inc/color-annotations-preview.js).

The default color scheme was not computed using this formula. So the first color update is surprising.

![image](https://user-images.githubusercontent.com/10274366/125696070-e9fba6dd-3ba6-4db7-a488-1589395512ef.png)

**Comment by kwight** [comment]
@DanielSmithMichigan Can this be closed now?
