### ISSUE TITLE
Quadrat: Menu looking off on Mobile

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4235]
When checking out the demo site on mobile, I noticed that the menu is stacking weirdly under the site title. Can we get it looking like the mockup?

Currently | Mockup
------------ | -------------
<img width="375" alt="Mobile Menu2" src="https://user-images.githubusercontent.com/65220155/125760768-551af88f-34e4-46b7-9327-a654e08d0f2c.png"> | <img width="414" alt="Mobile Menu" src="https://user-images.githubusercontent.com/65220155/125762365-4508fff7-bc5f-4f92-a6b6-96fdb912127a.png">

**Comment by pbking** [comment]
This is working as expected for me.  Not sure if recent Gutenberg or theme changes corrected but I'm unable to reproduce locally or on https://quadratdemo.wordpress.com/

![image](https://user-images.githubusercontent.com/146530/125786972-08745d71-8b59-4f82-9f4a-4b4b8747eabf.png)

**Comment by beafialho** [comment]
It is now working fine to me as well 👍
