### ISSUE TITLE
Rebalance: Embedded videos display uneven spaces in masonry grid

### ISSUE THREAD

**Issue by guicmazeredo** [Automattic/themes#426]
## Steps to replicate

1. Embed a Youtube video into a post.
2. Publish enough posts in order to display items below the post with the video on a blog page or archive page. 
3. Access the blog page or an archive page and check the space below the post with the embedded video. 

I used a Chrome Version 70.0.3538.110 (Official Build) (64-bit).

## Result

There is a big blank space below posts with embedded videos on the blog page or archive pages:

http://cld.wthms.co/YFIQKU

## Expected

I expected to see an even space in between posts like posts without embedded videos do. 

* User report: [#8250923-hc]
* Follow-up ticket: [#1640894-zd]
* User's site: https://rosegirl.blog/
* Page with the issue: https://rosegirl.blog/category/videos/

**Comment by kathrynwp** [comment]
User came back to confirm that theyve tested with VideoPress embeds and did **not** get the gaps.

**Comment by kathrynwp** [comment]
Noting that I do not see the issue in Firefox 63.0.3, so the issue seems browser-specific as well.

**Comment by laurelfulford** [comment]
I can recreate this in both the classic editor and classic block; for some reason using an embed block for the YouTube video doesn't cause the same issue.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
