### ISSUE TITLE
Quadrat: Hide query pagination divider if there's no pagination

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4268]
If there's no pagination available, we should not display the horizontal divider line for the Query Pagination: 

<img width="1247" alt="Screen Shot 2021-07-22 at 7 52 50 AM" src="https://user-images.githubusercontent.com/1202812/126635129-ab40d3f9-7bb4-4c83-89e9-79430b2765ff.png">

<img width="1247" alt="Screen Shot 2021-07-22 at 7 52 47 AM" src="https://user-images.githubusercontent.com/1202812/126635138-f551a79a-cfea-4de7-b96f-c5b78cbc1a1f.png">

**Comment by jffng** [comment]
I wonder if this should ultimately be addressed in the block.

That is, if there is no pagination, an empty div should not be rendered. I will take a look at fixing it there.

**Comment by kjellr** [comment]
@jffng I'm not 100% sure, but I believe this happens with many other blocks too — for example, if there's no post title, an empty div for post title still shows up on the front end.

**Comment by jeffikus** [comment]
This needs retesting.

**Comment by scruffian** [comment]
This is waiting for GB on dotcom to be updated.
