### ISSUE TITLE
Rebalance: ads showing on every post

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#43]
## Steps to replicate

Activate WordAds on a site + Rebalance theme

## Result

- Ads show below every post
- Page is quite slow to load due to so many ads/external resources

Screenshot from user's site:
https://cloudup.com/c9g4ZNqb2Tf

## Expected

- Ads normally only show below first post on the blog/home page

* User report: #2088348-hc
* Follow-up ticket: TBA
* User's site: https://dealsfinders.blog/ & replicated on https://kristenistesting.com/

Will also report to adopsp2 incase issue is with them.

**Comment by kristarella** [comment]
https://adopsp2.wordpress.com/2018/03/19/ads-showing-on-every-post-rebalance-home/

**Comment by liviopv** [comment]
I found the same issue on other themes too (Karuna, Eventbrite Multi Event, Confit and Designer), so I don't think it's a theme issue.

Updated: https://adopsp2.wordpress.com/2018/03/19/ads-showing-on-every-post-rebalance-home/#comment-3487

**Comment by allancole** [comment]
Looks like this probably isn’t a theme specific issue. There was a fix applied for this here: https://adopsp2.wordpress.com/2018/03/19/ads-showing-on-every-post-rebalance-home/#comment-3490

Did that do the trick for you @liviopv or @kristarella ?

**Comment by alaczek** [comment]
Looks like this issue has been resolved by the Ads team, so closing this one.
