### ISSUE TITLE
Skatepark: Page templates: index

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4306]
![Home](https://user-images.githubusercontent.com/3593343/126954326-067a5971-585f-4225-9e3a-e61fc4bbe6f4.jpg)

**Comment by MaggieCabrera** [comment]
The design from figma shows an index template that is loading a page with all the block patterns but we should also consider the possibility of an index template that shows the list of posts. I don't see that on the figma designs and this is how it looks like right now:

![Screenshot 2021-08-11 at 10-25-46 free – Just another WordPress site](https://user-images.githubusercontent.com/3593343/128997465-105a0cb8-9b46-48ef-ae6e-aaebea5869a7.png)

@melchoyce anything we can improve on this one?

**Comment by melchoyce** [comment]
I was originally thinking a masonry grid might be cool here:

![image](https://user-images.githubusercontent.com/2846578/129222492-aeb95363-fba4-4c4b-9d2d-ef645edcd8ec.png)

Maybe set up like this using the query block:

```
<!-- wp:query {"queryId":29,"query":{"perPage":6,"pages":0,"offset":0,"postType":"post","categoryIds":[],"tagIds":[],"order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"exclude","inherit":false},"displayLayout":{"type":"flex","columns":3},"align":"wide"} -->
<div class="wp-block-query alignwide"><!-- wp:post-template -->
<!-- wp:group {"style":{"spacing":{"padding":{"top":"30px","right":"30px","bottom":"30px","left":"30px"}}},"layout":{"inherit":false}} -->
<div class="wp-block-group" style="padding-top:30px;padding-right:30px;padding-bottom:30px;padding-left:30px"><!-- wp:separator {"className":"is-style-wide"} -->
<hr class="wp-block-separator is-style-wide"/>
<!-- /wp:separator -->

<!-- wp:post-featured-image /-->

<!-- wp:post-title {"isLink":true,"fontSize":"normal"} /-->

<!-- wp:post-excerpt /-->

<!-- wp:post-date /--></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:query-pagination -->
<div class="wp-block-query-pagination"><!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-numbers /-->

<!-- wp:query-pagination-next /--></div>
<!-- /wp:query-pagination --></div>
<!-- /wp:query -->
```

**Comment by MaggieCabrera** [comment]
that looks really cool! But the query pagination block would need some design too, since it's not a "load more posts" button but a next/prev page and page number links.

**Comment by melchoyce** [comment]
Based on the editor preview I think the pagination block looks mostly okay as-is, just maybe some additional spacing around the numbers:

![image](https://user-images.githubusercontent.com/2846578/129228580-311d3241-8b1c-47fa-8161-8565c2e6d4c2.png)

(I just threw on 10px of padding and removed the margin in inspector to demo)
