### ISSUE TITLE
Skatepark: Block patterns 

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4308]
Skatepark should ship with the following block patterns:

- [x] Full-width image with aside caption https://github.com/Automattic/themes/pull/4396
<img width="598" alt="Screenshot 2021-07-26 at 09 42 11" src="https://user-images.githubusercontent.com/3593343/126951747-ce4bca0b-7ff1-4112-83c9-03573079cb36.png">

- [x] Text list with button https://github.com/Automattic/themes/pull/4390
<img width="578" alt="Screenshot 2021-07-26 at 09 43 01" src="https://user-images.githubusercontent.com/3593343/126951785-eef22d7f-7f68-4188-8701-13c2b737f122.png">

- [x] Columns in container https://github.com/Automattic/themes/pull/4449
<img width="517" alt="Screenshot 2021-07-26 at 09 44 05" src="https://user-images.githubusercontent.com/3593343/126951880-3550edc0-96d8-403d-8b36-bf2300fdaa3c.png">

- [x] Mixed media in container #4403
<img width="569" alt="Screenshot 2021-07-26 at 09 45 07" src="https://user-images.githubusercontent.com/3593343/126951987-f56ab4c9-b47a-4c01-b172-a906aa7b80bb.png">

- [x] Testimonial https://github.com/Automattic/themes/pull/4380
<img width="575" alt="Screenshot 2021-07-26 at 09 46 34" src="https://user-images.githubusercontent.com/3593343/126952391-776743c9-f1aa-421b-907d-db2bae48cd50.png">

- [x] Paragraph with quote https://github.com/Automattic/themes/pull/4414
<img width="579" alt="Screenshot 2021-07-26 at 09 46 38" src="https://user-images.githubusercontent.com/3593343/126952376-1af27891-b527-428c-be56-f077e520d72e.png">

- [x] Two columns of text https://github.com/Automattic/themes/pull/4397
<img width="582" alt="Screenshot 2021-07-26 at 09 46 41" src="https://user-images.githubusercontent.com/3593343/126952352-cbbea399-50d1-4d33-a52a-64910a502b27.png">

- [x] Footer https://github.com/Automattic/themes/pull/4343
<img width="581" alt="Screenshot 2021-07-26 at 09 46 51" src="https://user-images.githubusercontent.com/3593343/126952335-a2ac28b9-000d-42bd-98ab-ba650c4cb338.png">

**Comment by MaggieCabrera** [comment]
@melchoyce looking at the patterns that we still need to work on I see that:
- **Columns in container** needs both real copy and an alt text for the image
- **Mixed media in container** also needs copy and alt text
- **Paragraph with quote** needs real text

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/129242606-1ce1ea0a-f4ac-449e-84c7-0af6b96338b7.png)

Copy:

```
Learn to skate
Skatepark welcomes youth of all ages and experience levels. Whether you’ve never been on a board before, or you can already do tricks, there’s a place for you and something to learn.

Make new friends
Skateboarding is a social sport! Come hang out and meet some new friends to cheer you on while you skate. We have a strict no-bullying policy and maintain a supportive environment.

Skateboarding can teach people discipline, patience, and resiliency. It’s a great sport for kids with a lot of energy! We’ll help build up some structure and support in your life, all while you meet new people and have a ton of fun learning how to skateboard.
```

Alt:

```
Close-up of a person riding a skateboard, focusing on their feet and the board. One foot is on the board, while the other foot is up, in motion. A skatepark is blurred in the background.
```

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/129244227-c910a7a8-ea75-4152-bd64-d638f68af2ec.png)

Copy:

```
Why camp?
Skateboarding can teach people discipline, patience, and resiliency. It’s a great sport for kids with a lot of energy! We’ll help build up some structure and support in your life, all while you meet new people and have a ton of fun learning how to skateboard. Just think of all the cool tricks you’ll learn!

Discipline
Skateboarding can teach people discipline, patience, and resiliency. It’s a great sport for kids with a lot of energy! We’ll help build up some structure and support in your life, and you’ll have fun.

Friendship
Skateboarding is a social sport! Come hang out and meet some new friends to cheer you on while you skate. We have a strict no-bullying policy and maintain a supportive environment.

Mentoring
Work 1:1 with our team of coaches to learn how to skate. They’ll be your mentors and guides while you’re at camp. Plus, many of our older campers will mentor the younger skaters.
```

Alt:
```
A skateboard laying on its side on top of concrete.
```

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/129255444-c51b95b2-5a3d-4341-bac5-ad1d79c29d4a.png)

Copy:

```
Why come to Skatepark?
Skateboarding can teach people discipline, patience, and resiliency. It’s a great sport for kids with a lot of energy! We’ll help build up some structure and support in your life, all while you meet new people and have a ton of fun learning how to skateboard.
Skateboarding is a social sport! Come hang out and meet some new friends to cheer you on while you skate. We have a strict no-bullying policy and maintain a supportive environment for all camp attendees. Plus, you’ll work 1:1 with our team of coaches to learn how to skate. 

I learned how to do a kick flip and made a bunch of new friends. Can’t wait to go back!
– Jane Doe, 11
```

**Comment by melchoyce** [comment]
![image](https://user-images.githubusercontent.com/2846578/129255818-2cbf2c92-1076-4d7c-9cb5-376058830341.png)

Copy:
```
Rodney Mullen. Paul Rodriguez. Bucky Lasek. Bob Burnquist. Tony Hawk. Ryan Sheckler. Eric Koston. Bam Margera. Chris Cole. Andrew Reynolds. The are all skateboarding icons. Some of them even have video games you may have played.

Skateboarding can teach people discipline, patience, and resiliency. It’s a great sport for kids with a lot of energy! We’ll help build up some structure and support in your life, all while you meet new people and have a ton of fun learning how to skateboard.
Skateboarding is a social sport! Come hang out and meet some new friends to cheer you on while you skate. We have a strict no-bullying policy and maintain a supportive environment for all camp attendees. 
Work 1:1 with our team of coaches to learn how to skate. They’ll be your mentors and guides while you’re at camp. Plus, many of our older campers will mentor the younger skaters.
```

**Comment by melchoyce** [comment]
Let me know if this fake copy works!

**Comment by MaggieCabrera** [comment]
I'm closing this since all patterns have been merged. Thank you all for your hard work!
