### ISSUE TITLE
Skatepark: theme.json: Color palette

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4309]
Add the main color palette to the theme:

<img width="432" alt="Screenshot 2021-07-27 at 13 02 44" src="https://user-images.githubusercontent.com/3593343/127143660-870376e2-6913-4263-89ca-469b0ef659a4.png">

**Comment by MaggieCabrera** [comment]
@melchoyce from what I see on figma Skatepark has only 2 colors: background and body text. We need a color for when text is selected, ideally a different shade of the background color. We will need that for all of the alternative palettes as well

**Comment by melchoyce** [comment]
Are we shooting for AA contrast? cc @kjellr

**Comment by MaggieCabrera** [comment]
For reference, in Quadrat we are using the darker blue for that.

**Comment by kjellr** [comment]
> Are we shooting for AA contrast? cc @kjellr

I don't think we need that for text selection.

**Comment by melchoyce** [comment]
Could we reverse the background and foreground for the text highlight?

![image](https://user-images.githubusercontent.com/2846578/127025749-f775fb22-5e33-4134-a1d0-fc60eedfe53e.png)

**Comment by MaggieCabrera** [comment]
Yeah, we can do that, thanks @melchoyce !

**Comment by kjellr** [comment]
I worry it may end up being too prominent in practice, but let's give it a try.
