### ISSUE TITLE
Skatepark: Templates:Header template part (including mobile)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4313]
**Desktop:**
<img width="1051" alt="Screenshot 2021-07-23 at 16 19 41" src="https://user-images.githubusercontent.com/3593343/126817182-07f93890-3541-4222-8c12-068a785a2ccc.png"> 

**Mobile:**
<img width="687" alt="Screenshot 2021-07-23 at 16 20 25" src="https://user-images.githubusercontent.com/3593343/126817174-f5b46c00-a5f1-4695-a0c1-008fef6900c8.png">

**Comment by MaggieCabrera** [comment]
@melchoyce the mobile version of the theme wasn't on the _Small theme_ page in figma, I grabbed this from _Page Mockups_ Let us know if that design is not up to date.

**Comment by melchoyce** [comment]
Good catch, thanks!

**Comment by melchoyce** [comment]
Moved the mobile mocks over to the Small Theme page and double-checked all the spacing
