### ISSUE TITLE
Skatepark: Comment form styles (dotcom and dotorg) (if needed)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4317]
**Dotorg comments:**

<img width="624" alt="Screenshot 2021-07-23 at 19 10 57" src="https://user-images.githubusercontent.com/3593343/126817563-69cf8e5e-ff55-4e3e-ae9a-a59060da3716.png">

**Comment by MaggieCabrera** [comment]
@melchoyce this one is also coming from _Blog Mockups_.

**Comment by MaggieCabrera** [comment]
The dotcom comments look like this, I think they are mostly fine (besides the button styles, those need fixing overall for the whole theme):

Logged out | Logged in
--- | ---
<img width="783" alt="Screenshot 2021-08-03 at 12 34 08" src="https://user-images.githubusercontent.com/3593343/128001816-f083811a-8864-486d-b7cd-a1b51bdf2645.png"> | <img width="741" alt="Screenshot 2021-08-03 at 12 33 48" src="https://user-images.githubusercontent.com/3593343/128001820-e49a6592-3599-4e09-9e5e-9c09c79387fb.png">
