### ISSUE TITLE
Skatepark: Create a demo site on dotcom

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4320]
Deploy the theme on dotcom and create a demo site that uses Skatepark.

Set [Theamdemo](https://theamdemo.wordpress.com/) to use Skatepark too for block testing.

**Comment by MaggieCabrera** [comment]
- [x] Created demo site: PdgTYS-2-p2
- [x] Set Theam demo to use skatepark for testing
- [ ] Add content to demo site

**Comment by MaggieCabrera** [comment]
@melchoyce I deployed yesterday all of our latest changes and updated the demo site. We are still missing a couple of important things such as the [single/page templates](https://github.com/Automattic/themes/pull/4438) (pending review) and [some of the block patterns](https://github.com/Automattic/themes/issues/4308) but I think we can start working on adding content to the demo site. I've gone ahead and pasted the block patterns that are already on trunk on to the homepage and I've setup the menu with the same pages the design is suggesting. 

Please feel free to tinker with the demo site as much as you want and let us know if you see something off.

**Comment by MaggieCabrera** [comment]
Just a suggestion: the design is not including a "blog" link on the menu so there's no direct way to check the list of posts, maybe we should add one

**Comment by scruffian** [comment]
> maybe we should add one

Done.
