### ISSUE TITLE
Skatepark: Core block settings (if needed)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4321]
Once the main theme styles are in place, review with the designers in case any core block need adjusting specific to Skatepark

**Comment by MaggieCabrera** [comment]
I made screenshots of every block on Theamdemo:

![Screenshot 2021-08-23 at 17-51-09 Gutenberg Archives](https://user-images.githubusercontent.com/3593343/130479867-55d69459-844e-4fd6-90b7-4762c41e8727.jpg)
![Screenshot 2021-08-23 at 17-51-22 Gutenberg Audio](https://user-images.githubusercontent.com/3593343/130479869-540a4518-f1f3-41b2-b782-61814690830a.jpg)
![Screenshot 2021-08-23 at 17-51-30 Gutenberg Button](https://user-images.githubusercontent.com/3593343/130479873-b2039777-2573-468a-961c-85b5a74690fe.jpg)
![Screenshot 2021-08-23 at 17-51-39 Gutenberg Columns](https://user-images.githubusercontent.com/3593343/130479877-a564e199-1b97-42c4-aa9d-702c389f1a73.jpg)
![Screenshot 2021-08-23 at 17-52-06 Gutenberg Cover](https://user-images.githubusercontent.com/3593343/130479881-4619bc88-aa36-44bf-b5f4-7ce2cd3432db.jpg)
![Screenshot 2021-08-23 at 17-52-44 Gutenberg File](https://user-images.githubusercontent.com/3593343/130479885-a76db381-0d41-40e0-b339-f77068ebff3e.jpg)
![Screenshot 2021-08-23 at 17-52-59 Gutenberg Group](https://user-images.githubusercontent.com/3593343/130479889-4d9a783c-b31f-4ac1-95fd-e5191cbef0b2.jpg)
![Screenshot 2021-08-23 at 17-53-09 Gutenberg Heading](https://user-images.githubusercontent.com/3593343/130479894-8a0c3c7d-d271-45ac-8fa3-86ba4735d59e.jpg)
![Screenshot 2021-08-23 at 17-53-52 Gutenberg List](https://user-images.githubusercontent.com/3593343/130479895-114f2c5e-732d-42e1-ae95-cf711c89a2a6.jpg)
![Screenshot 2021-08-23 at 17-54-09 Gutenberg Media Text](https://user-images.githubusercontent.com/3593343/130479897-a5f8cb04-e3c0-4092-82e6-1b4c87fc12d4.jpg)
![Screenshot 2021-08-23 at 17-54-24 Gutenberg Misc Formatting](https://user-images.githubusercontent.com/3593343/130479900-dafeba93-0c9a-4cc5-833c-1c6be05ec121.jpg)
![Screenshot 2021-08-23 at 17-54-41 Gutenberg Paragraph](https://user-images.githubusercontent.com/3593343/130479901-2161fa3e-8b0e-46cc-8bbc-e66045681b40.jpg)
![Screenshot 2021-08-23 at 17-54-54 Gutenberg Pullquote](https://user-images.githubusercontent.com/3593343/130479903-7929ed20-103d-42cd-a7ad-f7e04a428ace.jpg)
![Screenshot 2021-08-23 at 17-55-00 Gutenberg Quote](https://user-images.githubusercontent.com/3593343/130479905-5fd12843-fe38-42c3-b547-4b912b8f71e9.jpg)
![Screenshot 2021-08-23 at 17-55-09 Gutenberg Search Block](https://user-images.githubusercontent.com/3593343/130479907-e7d665da-ff09-4c4e-a993-9e69c0fcd8e1.jpg)
![Screenshot 2021-08-23 at 17-55-17 Gutenberg Spacer](https://user-images.githubusercontent.com/3593343/130479909-32133444-8ffa-4b8a-bd4a-4852890f21ae.jpg)
![Screenshot 2021-08-23 at 17-55-25 Gutenberg Verse](https://user-images.githubusercontent.com/3593343/130479910-33253a06-18d9-4ac4-983e-79afa492b30a.jpg)
![Screenshot 2021-08-23 at 17-55-40 Gutenberg Video](https://user-images.githubusercontent.com/3593343/130479912-870ddd25-cd5f-423d-9afd-5d43de0485cc.jpg)
![Screenshot 2021-08-23 at 18-00-03 Gutenberg Widgets](https://user-images.githubusercontent.com/3593343/130479917-18052897-1c9b-447f-b2b5-13dd29e8e15c.jpg)
![Screenshot 2021-08-23 at 18-00-50 Gutenberg Image](https://user-images.githubusercontent.com/3593343/130479919-977372fe-9f5e-4810-a8ea-fb792ad15106.jpg)

**Comment by MaggieCabrera** [comment]
@kjellr @melchoyce in case you see something you think we've got to change (theamdemo.wordpress.com is the url of the demo site with all the blocks)
