### ISSUE TITLE
[Apostrophe & Button 2] Blog Posts Block: not showing featured image in preview and published page

### ISSUE THREAD

**Issue by daria2303** [Automattic/themes#4324]
### Steps to reproduce the behavior

1. Premium site
2. Create posts with featured images
2. Create page with Blog Posts Block
3. Show featured image option enabled

#### What I expected to happen

Featured images are visible like in the editor: https://d.pr/i/7m1rwG

#### What actually happened

In the preview and published page images do not display: https://d.pr/i/ipx00v

#### Browser / OS version
Chrome, Big Sur

#### Is this specific to the applied theme? Which one?

No, checked in 2 themes Apostrophe and Button 2 

#### Does this happen on simple or atomic sites or both?

Only on simple, reproduced in Premium 

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
one report 3897867-zd-woothemes

#### Screenshot / Video: If applicable, add screenshots to help explain your problem. 
above in the links

**Comment by sbathompson-he** [comment]
Reported here. 29657106-hc
I didn't realize it was a Bug until it was mentioned to me in CSS Requests

**Comment by adelineyaw** [comment]
Another report: 32119462-hc (Theme: Heart and Style)
Follow up: 32119462-zen

**Comment by erricgunawan** [comment]
Just noting that this might be related to:

https://github.com/Automattic/newspack-blocks/issues/399

If the "Display on pages" option in the Customizer > Content Options are enabled, the images will be displayed.

**Comment by sophiegyo** [comment]
Report in #5022296-hc

I suggested the workaround of checking "display on single pages" in Content Options, or suggested switching to another theme in the meantime.

**Comment by Robertght** [comment]
Going to close this in favor of https://github.com/Automattic/newspack-blocks/issues/399
