### ISSUE TITLE
Skatepark: Duotone theme-level configuration

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4329]
Skatepark includes in its design the application of duotone filter on the images it provides. The theme should apply this filter to all relevant blocks by default.

This will require https://github.com/WordPress/gutenberg/issues/33642 to be addressed, which will allow us to set a filter as default (and we should consider changing the default filter when the user changes the theme color as well).

**Comment by MaggieCabrera** [comment]
Duotone apparently doesn't support css variables, so I'm looking into it to see if I can submit a patch for it

**Comment by MaggieCabrera** [comment]
Apparently it's not trivial to make the duotone filters dynamic, so I opened an [issue](https://github.com/WordPress/gutenberg/issues/33905) about it on GB and contacted the devs on top of duotone so that this is on their radar as an enhancement.

**Comment by jeffikus** [comment]
@MaggieCabrera and I spoke about this, and we're going to pause on this, as it's non blocking. For v1, the customer can make changes in the editor, but changing the global colors won't apply to all instances of the block. We can overcome this initially with head start and patterns, and this can be improved in the block in future.

**Comment by pbking** [comment]
Added this to track [allowing a user to control the application of duotone](https://github.com/Automattic/themes/issues/4434) to all blocks.
