### ISSUE TITLE
Twenty Nineteen: Missing fonts panel on Customizer

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#433]
#### Steps to reproduce 

- Start with a WordPress.com site or a self-hosted WordPress (WordPress.org) site 
- Install Twenty Nineteen theme on the site, either using the `Activate theme` button on [this page](https://wordpress.com/theme/twentynineteen), or download from that page and upload on WordPress.org site
- Visit Customizer at `{example.com}/wp-admin/customize.php`

#### What is expected 

The `Fonts` tab is available on the Customizer.

#### What happens instead 

The `Fonts` tab is missing on the Customizer.

#### Extra notes

All other WordPress.com themes have the `Fonts` tab on the Customizer, or at least from what I have seen so far. I would also expect it to be available on all themes, going by this [support document](https://en.support.wordpress.com/custom-fonts/) - `Head to the Customizer’s Fonts panel to check out our collection of free Google Fonts, available to all sites`

**Comment by crunnells** [comment]
I'm re-opening this for now to track requests for this feature.

https://en.blog.wordpress.com/2018/12/19/twenty-nineteen/#comment-410755
https://en.blog.wordpress.com/2018/12/19/twenty-nineteen/#comment-410786

**Comment by thehenrybyrd** [comment]
Request in #1665910-zen
The ability to change fonts is a pretty common expectation, particularly for WordPress.com Premium plan folks who have "Advanced Customization".

**Comment by zdenys** [comment]
Another user #1675318-zen, in love with Twenty Nineteen, but misses the Font customization.

**Comment by KokkieH** [comment]
Request from the [forums](https://en.forums.wordpress.com/topic/fonts-option-not-appearing-in-customizer/)

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883

**Comment by zdenys** [comment]
This user was surprised to find no way to change fonts globally 4628384-zd-woothemes
