### ISSUE TITLE
Atomic: Custom Color option for buttons interfering with button color for Editor

### ISSUE THREAD

**Issue by hacchism** [Automattic/themes#4330]
When a theme has Custom Color option for buttons, the color set interferes with the color for all buttons in Editor.

### Steps to reproduce the behavior

1. Make sure to use Atomic site
2. Activate a theme that has Custom Color option for buttons (i.e. **Independent Publisher 2**)
3. Go to "Appearance > Customize > Colors & Backgrounds"
4. Change button color to black for example and save the change

![Screen Shot on 2021-07-25 at 09:38:21](https://user-images.githubusercontent.com/32432463/126884188-7f5069a5-ed74-41ec-bc72-f27a5f050625.png)

5. Open a page editor

#### What actually happened

All the buttons in editor shows up with black.

![Screen Shot on 2021-07-25 at 09:36:58](https://user-images.githubusercontent.com/32432463/126884170-18f39461-028f-4dd7-a1a5-6b8ab4683d22.png)

#### Is this specific to the applied theme? Which one?

I reproduced this on **Independent Publisher 2** so far. I didn't have time to find other themes that have Custom Color option for buttons. But I believe this is reproducible even on other themes that have the button color option. 

#### Does this happen on simple or atomic sites or both?

Only Atomic.

**Comment by synora** [comment]
I can replicate this on Independent Publisher 2, but not on other themes such as Ryu or Tonal.

**Comment by sixhours** [comment]
Looks like Independent Publisher, Independent Publisher 2, and Franklin themes all have very broad button selectors in their stylesheets and color annotations which is causing these styles to bleed into the editor:

```
button:not(.menu-toggle),
input[type="button"],
input[type="reset"],
input[type="submit"]
```

It appears Simple sites don't enqueue custom color styles when viewing the editor, but Atomic sites do (they show up as `#custom-colors-editor-css-inline-css` in the header)

I'm debating between making the existing color annotation rules more specific, or whether custom color styles showing in the Atomic editor is a bug in itself.

**Comment by sixhours** [comment]
I'm seeing stuff in `/wp-content/mu-plugins/colors/colors.php` (like ` print_block_editor_css()`) that suggests we do want to enqueue custom color styles in the editor so I'm going to figure out how to make the selectors behave in these themes.

**Comment by sixhours** [comment]
`button:not(.menu-toggle)` is the troublemaker; it's targeting allllll the buttons because they don't have `.menu-toggle` as a class and overriding more specific selectors like `.components-button`. I think I can tweak that rule in IP2 without breaking users' existing annotations. Franklin does not appear to be affected because it's using a more specific variation of `button:not(.menu-toggle)`

**Comment by sixhours** [comment]
Started a diff in D65100-code for the WP.com side -- I can't seem to push a branch to this repo, I'll try resetting everything locally.
