### ISSUE TITLE
All Themes: Button block styles not working in themes with Gutenberg styles & support

### ISSUE THREAD

**Issue by ahmadbaig1** [Automattic/themes#434]
Note: this issue originally specified the Shoreditch theme, but this was overlooked in any theme that we added block styles and supports to. 

## Steps to replicate

- Activate the Shoreditch theme on your site.

- Edit a Post in the Gutenberg editor. 

- Add a button block, try to select the different button styles using the option in the right sidebar- "outlined" and "squared", and they do not reflect either on the button or on the button preview like they do in other themes.

Storeditch theme-
<img width="1200" alt="screen shot 2018-12-15 at 3 28 05 pm" src="https://user-images.githubusercontent.com/40609190/50041963-f785cb80-0082-11e9-8209-5b696cce801b.png">

TwentySeventeen theme-
<img width="1200" alt="screen shot 2018-12-15 at 3 29 13 pm" src="https://user-images.githubusercontent.com/40609190/50041968-066c7e00-0083-11e9-81f4-b4346f46e8c5.png">

## Result

The button style is not changing to either to the "Outlined" or the "Squared" button type, neither on the actual button on the block nor on the preview buttons which are clicked to select the styles, on the right sidebar.

## Expected

I expected the buttons to change styles, but they do not change and stay like the default style.

* User report: [8777635-hc]
* Follow-up ticket: [1642719-zd]
* User's site: [[https://sebastianschick.com](https://sebastianschick.com)]
* User Post: [ [post/page]( https://sebastianschick.com/wp-admin/post.php?lang=en&action=edit&post_type=page&post=2342)]

**Comment by laurelfulford** [comment]
Unfortunately, I know that we didn't consider the button styles in the other themes we added block editor styles to, either. 

I've updated the ticket to be more general.

**Comment by jamiepalatnik** [comment]
Reported for Gazette theme in 8117471-hc.

**Comment by gwwar** [comment]
@laurelfulford is any integration work here needed or do we need theme updates? Asking since, the screenshots appear to be Atomic sites.

**Comment by laurelfulford** [comment]
@gwwar It's all theme updates :)

In all the themes, we followed the theme's original design for buttons... but should have deferred to Gutenberg's default rounded styles, since most of them aren't. On top of that, in a lot of cases, the theme's CSS is too specific and it's overriding the styles Gutenberg's trying to add on top, so all the options look the same.

**Comment by gwwar** [comment]
Gotcha, I'll assume you have this covered. Let us know if you need a hand otherwise 👍

**Comment by laurelfulford** [comment]
Another report of this, for Lodestar specifically: #1732421-zen

**Comment by laurelfulford** [comment]
I've circled through and tested affected themes -- here's the list of the theme's we've added Gutenberg styles to, and the button styles that don't work, for tracking:

* Affinity - not rounded; outline doesn't work
* Altofocus - outline doesn't work
* Apostrophe 2 - not rounded; is outlined by default :|
* Button 2 - not rounded, outline doesn't work
* Canard - not rounded, outline doesn't work
* Dara - not rounded, outline doesn't work, has text underline
* Dyad 2 - not rounded, outline doesn't work, has text underline
* Gazette (reported above) - not rounded, outline works but is white text on white
* Illustratr - not rounded; outline completely white
* IP2 - outline no border
* Intergalactic 2 - not rounded; is outlined by default :|
* Ixion - not rounded; outline completely white
* Karuna - outlined by default
* Libre 2 - no background by default (text with underline)
* Libretto - not rounded, outline doesn't work
* Lodestar (reported above) - not rounded; outline completely white
* Penscratch 2 - not (really) rounded; outline doesn't work
* Photos - Square doesn't work
* Pique - square doesn't work; outline is all white
* Publication - not rounded; outline completely white
* Radcliffe 2 - square doesn't work; text decoration on hover
* Rebalance - not rounded; outline by default
* Scratchpad - not rounded; outline by default
* Shoreditch (reported above) - outline is all white; square doesn't work
* Sketch - not rounded; outline by default
* Textbook - square doesn't work; outline by default
* Toujours - not rounded; outline is all white

**Comment by laurelfulford** [comment]
These should all be fixed 😅 

I added a comment to the Lodestar ZD ticket.

@jamiepalatnik - can you please follow up with the person who reported this for Gazette?

@ahmadbaig1 can you please follow up with the person who originally reported this for Shoreditch? It looks like that ticket is closed, so I can't comment on it.

Thanks!
