### ISSUE TITLE
Perle: Sharing buttons showing up on top of the content of the pages

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#4345]
### Steps to reproduce the behavior

1. Go to Tools > Marketing and make sure Pages is selected. Have the "Icon & Text" seelected.
2. Have a few sharing buttons added.
3. Have content added on the page. I used a two-column layout with an image on the right one to make them.

![image](https://user-images.githubusercontent.com/6737345/127547127-d8bf0980-a5e2-4c4d-a67c-5602b9078890.png)

#### What actually happened

The icons appear on top of the content of the page

### Context

User report 4182948-zen

#### Browser / OS version
Chrome 92

#### Is this specific to the applied theme? Which one?

Perle

#### Does this happen on simple or atomic sites or both?
Tested on Simple

#### Is there any console output or error text?
No

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.

![image](https://user-images.githubusercontent.com/6737345/127547127-d8bf0980-a5e2-4c4d-a67c-5602b9078890.png)

**Comment by sixhours** [comment]
I can reproduce this, but there's not an easy fix. Perle is an older theme and doesn't support full-width or wide-width blocks. The theme is designed to show post and page content in multiple columns, which puts the sharing buttons in areas where wide or full width blocks may overlap:

<img width="1224" alt="Screen Shot 2021-08-03 at 3 50 49 PM" src="https://user-images.githubusercontent.com/2124984/128077491-7ed9e5ec-570d-4222-8ab8-762f4b053090.png">

The best workaround is to give the user some Custom CSS to hide or move the sharing links, use separator blocks in the post content to shift wide blocks down below the sharing links, or switch to a newer, block-ready theme.
