### ISSUE TITLE
Skatepark: Hover states

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4346]
@melchoyce how should links and buttons behave on their hover states? Are there any exceptions (like links on the header/site title, post title block, etc)?

Button Style 1 | Button Style 2 | Links
--- | --- | ---
<img width="315" alt="Screenshot 2021-07-30 at 10 23 43" src="https://user-images.githubusercontent.com/3593343/127624313-13e4ff68-e33e-4831-bbe8-972830f8b334.png"> | <img width="309" alt="Screenshot 2021-07-30 at 10 23 39" src="https://user-images.githubusercontent.com/3593343/127624320-3c2ffdde-251d-4af8-a017-2183486fc777.png"> | <img width="287" alt="Screenshot 2021-07-30 at 10 23 23" src="https://user-images.githubusercontent.com/3593343/127624324-44965c9c-410d-4ea3-bc1a-79194540bc0b.png">

**Comment by MaggieCabrera** [comment]
Another question related to links: the underline of the links seems to be 2px wide, this can be achieved with `text-decoration-thickness` but the mockups show a separation between the text and the underline that cannot be controlled when using text-decoration. Should we use borders instead of text-decoration or should we leave the underline sitting a little closer to the text @melchoyce ?

**Comment by melchoyce** [comment]
> Another question related to links: the underline of the links seems to be 2px wide, this can be achieved with `text-decoration-thickness` but the mockups show a separation between the text and the underline that cannot be controlled when using text-decoration. Should we use borders instead of text-decoration or should we leave the underline sitting a little closer to the text @melchoyce ?

Let's use `text-underline-offset` for the spacing and let it progressively degrade on browsers that don't support the property.

I'll get you a chart for link/button styles!

**Comment by melchoyce** [comment]
Does this work?

![image](https://user-images.githubusercontent.com/2846578/127677822-cf0ea03b-5077-47ff-8291-77470d95fbbd.png)
https://www.figma.com/file/CA8Gb16mt9yYNWOiVLAWak/Skatepark?node-id=1851%3A2101

**Comment by MaggieCabrera** [comment]
Yeah, that's great, thanks @melchoyce. So I'm thinking this would be like Quadrat, where we only underlined links that are inside the post content and for the post titles inside the query loop we had them behave the opposite way (underlined only on hover). Check https://quadratdemo.wordpress.com/blog/ to see those.

Things like navigation menu links and the header site title link would have no underline or hover effects, right?

**Comment by melchoyce** [comment]
Yeah, exactly like Quadrat. 

> Things like navigation menu links and the header site title link would have no underline or hover effects, right?

👍👍
