### ISSUE TITLE
Nikau: More Button in Share this Module does not work on Atomic sites. 

### ISSUE THREAD

**Issue by nickpagz** [Automattic/themes#4348]
## Steps to replicate

On an Atomic site, in **Tools > Marketing > Sharing Buttons**, ensure a **More** button is added and has at least one additional button added to it.

On a live post, mouse over the **More** button.

## Result

Nothing. Nothing happened. Nothing happened at all.

## Expected

For additional sharing options to pop-up, the same way it does on every other theme.

* User report: #4173777-zen

**Comment by kathrynwp** [comment]
As this is a retired theme, it's not a critical bug, and there's been only one report of the issue, I'm closing this as a wontfix.
