### ISSUE TITLE
Radcliffe 2: Dropdown menu for current page (page jumps)

### ISSUE THREAD

**Issue by nagpai** [Automattic/themes#435]
## Steps to replicate

* Install the Radcliffe 2 theme on any test site
* Create a few pages 
* Create a menu and in any one of them add dropdown pages. 
* In the dropdown pages. repeat the same page three or four times, or add a custom link with a page jump within any page already in the dropdown. (so that you have atleast three items with the same main URL)
* Publish the changes, and within the dropdown click on any one of the appearances of the page repeated thrice (or page jumps)

## Result

<img width="552" alt="screenshot 2018-12-16 at 3 56 10 pm" src="https://user-images.githubusercontent.com/4162931/50052531-8e1dbf80-014b-11e9-9b12-8931da500da2.png">

## Expected

<img width="426" alt="screenshot 2018-12-16 at 4 01 46 pm" src="https://user-images.githubusercontent.com/4162931/50052565-fec4dc00-014b-11e9-90de-a9c246c96a4c.png">

Issue seems to be happening due to 

https://github.com/Automattic/themes/blob/master/radcliffe-2/style.css#L2576
```
.main-navigation li.current-menu-item ~ li.current-menu-item > a {
		background: transparent;
		color: #222;
	}
```

Fixed it temporarily with the following Custom CSS in user's site:

```
/*fix background color of dropdown menu - norman */
@media screen and (min-width: 768px) {
	.main-navigation li.current-menu-item ~ li.current-menu-item > a {
		color: #fff;
		background: #222;
	}
	
	.main-navigation li.current-menu-item ~ li.current-menu-item > a:hover {
		background: #ca2017;
	}
}

```

User's issue is resolved for now. However wanted to notify here, since the issue would occur with anyone wanting to add a dropdown with page jump links.

* User report: #8608383-hc
* Follow-up ticket: #1649256-zen
* User's site: https://rheumatologyact.wordpress.com

**Comment by laurelfulford** [comment]
This has been fixed in 53227-wpcom-themes.
