### ISSUE TITLE
wpcom footer credits for block-based themes

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4351]
The wpcom footer credits plugin doesn't correctly manage the content of the footer block.  It needs to be changed to:

* run in more situations (to either replace [free sites] or remove [business sites])
* MODIFY the footer block content with a user's credit selection (if valid credit content is found in the footer).  This modification might be to REMOVE the existing credit value.
* APPEND TO the footer block content a user's credit select (if no valid credit content is found)
* enable the footer customizer tools for block-based themes

No additional changes should be needed to any theme footer template parts.

Changes made by the user to the footer template parts (to eliminate the original credit content) should still result in the content chosen by the user in the customizer.

The original change to add the plugin can be found here: D59022-code
The current change can be found here: D65052-code

**Comment by pbking** [comment]
WIP: D65052-code
So far this change executes the REPLACEMENT of content of the credits.  The regex used might be too brittle but this demonstrates the concept I was going for.

To evaluate :
* Load up a CLASSIC theme sandboxed on a simple site.  
* Change the footer credits to something memorable using the customizer.  
* Switch theme to Blockbase.
* Observe that the footer credits aren't the original footer credits but instead the value chosen in the customizer.

**Comment by MaggieCabrera** [comment]
I'm commenting here because it's easier than on phabricator :D 

This looks fine ~~though I was expecting that the customizer options would show up on the block themes too, is that intended by the plugin or just missing functionality?~~ (apparently I forgot how to read!) It's a great start anyway.

I have tested all block themes and all look fine except Seedlet blocks. Apparently the markup is very different from the original Seedlet blocks footer:

Before | After
--- | ---
<img width="1556" alt="Screenshot 2021-08-02 at 20 36 05" src="https://user-images.githubusercontent.com/3593343/127908091-7dd75c72-83e5-42d6-89ce-eb60ca7f0b41.png"> | <img width="1563" alt="Screenshot 2021-08-02 at 20 36 25" src="https://user-images.githubusercontent.com/3593343/127908085-46402050-afc0-46d1-aede-4457ab429ef7.png">

**Comment by pbking** [comment]
Thank you @MaggieCabrera I would indeed prefer to continue discussions here. :)

I think that what you found justifies changing the default seedlet footer credits.  The plugin is (currently) looking for a `<p>` tag with an `<a>` tag that links to WordPress dot something so we just need to change it to something like that.  Thank you for pointing that out.

**Comment by pbking** [comment]
Additional progress on D65052-code.

With this change the content is better replaced allowing the font decisions expressed in the theme footer template part to remain.  (The html contents of a `<p>` tag with a wordpress anchor are replaced.

Additionally the logic runs with fewer "should there be content" checks in `should_show_footer_credits`, since this will ALWAYS need to be ran: for sites that should NOT show footer credits this will have to actively remove them and for those that do this replaces them.

**Comment by pbking** [comment]
Finalized the first pass for footer credits refactor: D65052-code

With this last change I think it's ready for an external review.

**Comment by pbking** [comment]
@ramonjd I noticed that you were the originator of this plugin and hope to spare some of your time to review this change.

**Comment by ramonjd** [comment]
Thanks for working on this! 

It not an easy one, especially to balance the flexibility that comes with the Site Editor and also current Customizer behaviour.

I tested according to the test description in the diff using Blockbase and TT1, and things work as described. 👍 

I think it's great that we removed all the complex exceptions, and are aligning things with Simple sites in terms of the upgrades required to hide the footer. 

Here's what I'm seeing (just noting down to confirm that's what's expected):

If there's no link to Wordpress.com|org we append the Customizer selection. So when editing the footer credit link to a 3rd-party site e.g., automattic.com the frontend shows a double footer credit on the frontend. 

<img width="504" alt="Screen Shot 2021-08-04 at 11 29 07 am" src="https://user-images.githubusercontent.com/6458278/128108433-4e78fb8e-9006-4f71-8fcf-26e191b9013f.png">

When there's a link to WordPress.com or WordPress.org in the footer credit in the site editor, the frontend replaces the footer credit with the one specified in the Customizer value.

<img width="707" alt="Screen Shot 2021-08-04 at 11 25 56 am" src="https://user-images.githubusercontent.com/6458278/128108495-c391ca7e-00ed-4207-84a9-6c0122681618.png">

I think the above behaviours form a reasonable compromise: that we enforce the WordPress.com footer credit regardless of the content of the footer template part.

Originally we were trying to allow Site Editor users to add whatever they wanted, so long as there was a link to WordPress.com|org. Maybe that was granted a little too much flexibility.

On the other hand, while hiding the footer also works when I upgrade to business, I'm no longer able to add my own footer with a link to Wordpress.com or WordPress.org.

<img width="652" alt="Screen Shot 2021-08-04 at 11 58 15 am" src="https://user-images.githubusercontent.com/6458278/128109778-96233f61-0654-4cd9-9875-828becbedf03.png">

Do you think that's a reasonable feature for eligible accounts to expect? I would have thought that we'd remove all restrictions for these users, that is, that they'd be able to add whichever content to their footer. 

It might also be good to check in with DotCom folks for business/Site Editor opinions too, as I'm a bit out of touch. There might be some plans afoot for Footer Credits block . cc @simison (sorry if you're not the right person to ping, but I know you know everyone and everything :D )

Also, I know it's WIP, but after you've finalized things, it'd be great to update the unit tests as well.

Thanks!

**Comment by MaggieCabrera** [comment]
To this I just want to add that I tested on all block themes and they worked fine in terms of appearance except when choosing the logo option:

<img width="1532" alt="Screenshot 2021-08-04 at 09 46 54" src="https://user-images.githubusercontent.com/3593343/128142579-4c1f511d-81f4-44ca-8773-55cb62c8f25e.png">

**Comment by pbking** [comment]
> Do you think that's a reasonable feature for eligible accounts to expect? I would have thought that we'd remove all restrictions for these users, that is, that they'd be able to add whichever content to their footer.

The limitation for eligible accounts is that if they intend to link to wordpress.com in the footer that it be one of the selections from the customizer. I can see this restriction, and even the way in which this is managed will change in the coming months.  A credit block would probably (mostly?) replace this plugin and offer better control, but for the moment I do think it's a reasonable expectation. Especially in order to cover both "classic" and "FSE" situations of our universal block themes reasonably well.

**Comment by pbking** [comment]
No longer a WIP I humbly submit the patch for a final review.

Unit tests were changed pretty substantially but were super important to make sure that the regex that was replaced is indeed doing what I thought it was supposed to (it wasn't quite).

🤞

**Comment by MaggieCabrera** [comment]
> To this I just want to add that I tested on all block themes and they worked fine in terms of appearance except when choosing the logo option:
> 
> <img alt="Screenshot 2021-08-04 at 09 46 54" width="1532" src="https://user-images.githubusercontent.com/3593343/128142579-4c1f511d-81f4-44ca-8773-55cb62c8f25e.png">

This is still happening to me with the current patch

**Comment by MaggieCabrera** [comment]
The logo works great now, thank you @pbking !

**Comment by scruffian** [comment]
This has been fixed.
