### ISSUE TITLE
Varia, Seedlet and children: Add support for Tiktok in social menu 

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#4355]
## Steps to replicate

1. Open the Customizer and create a social menu
2. Add a TikTok link to the menu

## Result

A generic link icon appears in the menu instead of the TikTok logo

## Expected

For the TikTok logo to appear - support for that logo was added to Jetpack social menus in Automattic/jetpack#18563, and it works as expected in TwentyTwenty, for example. But according to the comment in https://github.com/Automattic/wp-calypso/issues/50927#issuecomment-891220658, these themes use their own social menu implementations rather than Jetpack's, so support for the logo has to be added to the themes separately.

Confirmed it's not working in these themes:

* Seedlet
* Spearhead
* Varia
* Leven
* Brompton
* Hever
* Dalston

### Known user reports:

* 29847928-hc
* https://wordpress.com/forums/topic/page-headers-tiktok-link-logo/

**Comment by mikeicode** [comment]
Stow (we used CSS to add an icon) 31159608-hc

**Comment by jordesign** [comment]
Flagging this for consideration - Varia Child themes and Blockbase Child themes _could_ do with the TikTok logo being supported in Social Menus (Jetpack has added support for the Social Icons).

For FSE in the future - I expect we'll be encouraging the use of Social Icons block - so this functionality will become redundant. But is it worth thinking about including in Varia - to then flow down to the child themes?
