### ISSUE TITLE
Independent Publisher 2: Category Page Header Does Not Respect Font Selection in Customizer

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/themes#437]
## Steps to replicate

1. Change site's theme to Independent Publisher 2.
2. Change heading font setting in Customizer.
3. View category page.

## Result

<img width="1233" alt="screen shot 2018-12-18 at 5 47 50 pm" src="https://user-images.githubusercontent.com/42454301/50187766-2010fe00-02ed-11e9-833a-7a048e522e2e.png">

Category heading does not change with the heading font style setting.

## Expected

The category header text should respect the heading font setting in Customizer.

* User report: #8466935-hc
* Follow-up ticket: #1655475-zd
* User's site: https://toserendipityandbeyond.com/
* Post where issue is present: https://toserendipityandbeyond.com/category/australia/

**Comment by jordesign** [comment]
Confirmed this behaviour is still present - the automatic 'Category' title does not respect the custom font setting.

**Comment by danieldudzic** [comment]
Fix: D72122-code

**Comment by mikachan** [comment]
The fix (D72122-code) has now been deployed to live.
