### ISSUE TITLE
Blank Canvas: Related Posts are left aligned

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#4374]
## Steps to replicate

1. Make sure that Jetpack Related Posts are active on a [self-hosted](https://jetpack.com/support/related-posts/) or a [WordPress.com site](https://en.support.wordpress.com/related-posts/)
2. Visit a post with related posts

## Result
The Related Posts section doesn't respect the theme's width and is aligned to the left:

![Screen Shot on 2021-08-09 at 14:02:19](https://user-images.githubusercontent.com/1136160/128745241-62b8fa52-01f2-45cb-bd31-f30d4d510b6b.png)

To fix this, a CSS workaround is needed:

```
/* Related Posts: Center-align the content */
.entry-content #jp-relatedposts {
	margin: 0 auto;
}
```

* User report: None, dogfooding

**Comment by jordesign** [comment]
Closing in favour of #5202 3991

**Comment by eduardozulian** [comment]
For the sake of cross-posting things, #3991, the second number is the right issue!
