### ISSUE TITLE
Skatepark: Page template - singular

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4387]
![Screenshot 2021-08-11 at 10-27-07 Gutenberg Group – free](https://user-images.githubusercontent.com/3593343/128996396-d1258a7e-4b96-4e27-bb94-0739bbd777c6.png)

This is what it looks like right now on trunk. @melchoyce do you think we should change something about this template for Skatepark? Right now it's inheriting Blockbase's singular template.

**Comment by MaggieCabrera** [comment]
@melchoyce is this what we are aiming for?

![Blog_ Post with less content](https://user-images.githubusercontent.com/3593343/129362879-7ad4d851-ef7c-4549-bcf9-3adeab170db0.jpg)

**Comment by melchoyce** [comment]
Talked briefly about this on Slack; we should use this design for posts, and for pages, remove all the meta/commenting blocks.
