### ISSUE TITLE
Skatepark: Page/post titles should be wide-width

### ISSUE THREAD

**Issue by melchoyce** [Automattic/themes#4416]
## Steps to replicate

Look at a published post or page

## Result

The title is the content width

![image](https://user-images.githubusercontent.com/2846578/129599943-942d5a6c-0414-4de0-9530-999a38bbcc3c.png)

## Expected

The title should be wide-width

![image](https://user-images.githubusercontent.com/2846578/129599974-36fcf055-267a-4eed-b691-7d12dc79c1bf.png)

**Comment by MaggieCabrera** [comment]
Closed via https://github.com/Automattic/themes/pull/4438
