### ISSUE TITLE
Skatepark: Site logo appears misaligned

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4419]
When you add a site logo, the left side of the menu appears very misaligned with the right: 

<img width="1485" alt="Screen Shot 2021-08-16 at 3 09 19 PM" src="https://user-images.githubusercontent.com/1202812/129616941-792f87bd-beb0-4b4f-b081-29a15b2c759c.png">

@melchoyce do we have a design for how this is supposed to look?

**Comment by melchoyce** [comment]
Apparently I started thinking about this previously but didn't go anywhere with it:

![image](https://user-images.githubusercontent.com/2846578/129622265-0e25bb7e-35d3-4c71-b437-f3454a7c00af.png)

https://www.figma.com/file/CA8Gb16mt9yYNWOiVLAWak/Skatepark?node-id=2021%3A2233

How does something like this feel instead?

**Comment by kjellr** [comment]
I think it's a little weird to have the logo/title appear below the menu/social nav on mobile — while it's nice to have the menu button in the actual top left, this also swaps the hierarchy from what it is on desktop. Have you tried it the other way?

**Comment by MaggieCabrera** [comment]
hey @melchoyce should we do the logo below or on top of the menu on mobile? In case it helps, this is how Quadrat does it:

<img width="391" alt="Screenshot 2021-08-25 at 15 42 08" src="https://user-images.githubusercontent.com/3593343/130801593-98e97b8e-2649-4423-8a4f-2ac85fb022ac.png">

**Comment by melchoyce** [comment]
Let's try above, per @kjellr's suggestion 👍
