### ISSUE TITLE
Skatepark: Group blocks with "Inherit default layout" set are not properly aligned on the front end

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4426]
## Steps to replicate

1. Add a group block, set it to "Inherit default layout". 
2. View on the front end: 

## Screenshots

Editor|Front End
---|---
<img width="1440" alt="Screen Shot 2021-08-17 at 9 13 01 AM" src="https://user-images.githubusercontent.com/1202812/129733042-b14902a8-0af7-4868-9d38-da12fb01e96e.png">|<img width="1440" alt="Screen Shot 2021-08-17 at 9 13 32 AM" src="https://user-images.githubusercontent.com/1202812/129733219-bd585288-b339-4ca0-8fc2-03895bb3c3ed.png">

## Sample markup:

```
<!-- wp:group {"backgroundColor":"primary","textColor":"background","layout":{"inherit":true}} -->
<div class="wp-block-group has-background-color has-primary-background-color has-text-color has-background"><!-- wp:paragraph -->
<p>This is a group block with "inherit default layout" turned on.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

**Comment by MaggieCabrera** [comment]
Closed via https://github.com/Automattic/themes/pull/4459
