### ISSUE TITLE
Skatepark: Header template part appears stacked in the site editor

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4427]
The site header appears stacked in the site editor, not side-by-side as it does on the front end: 

Editor|Front End
---|---
 <img width="1440" alt="Screen Shot 2021-08-17 at 9 13 32 AM" src="https://user-images.githubusercontent.com/1202812/129734091-1b13c82e-48ad-40e6-8d75-8901690c4897.png">|<img width="1440" alt="Screen Shot 2021-08-17 at 9 05 31 AM" src="https://user-images.githubusercontent.com/1202812/129734209-2dcd1b49-3888-4d5a-b42e-b6c9b62a84da.png">

Related: #4419, #4407

**Comment by MaggieCabrera** [comment]
I think this one has been fixed via https://github.com/Automattic/themes/pull/4459 

I don't see this happening anymore.
