### ISSUE TITLE
Skatepark: Singular template always shows a comments message

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4428]
## Steps to replicate

1. Add a new page, let it use the singular template.
2. In Page > Discussion settings, ensure that "Allow comments" is unchecked (this is the default for pages). 
3. Publish & visit the front-end.
4. Note that a "Comments are closed." message appears just above the footer. 

## Expected

If comments were never on for the post, there should be no message that appears. (This may be an upstream Gutenberg bug?). It looks like there's currently no way to turn this off other than changing the page template. 

## Screenshot

<img width="646" alt="Screen Shot 2021-08-17 at 9 31 43 AM" src="https://user-images.githubusercontent.com/1202812/129735723-fa868835-fe42-467c-a9e9-756184b31a16.png">

**Comment by MaggieCabrera** [comment]
Yes, this was a bug, but it's fixed via https://github.com/Automattic/themes/pull/4438
