### ISSUE TITLE
Business: Classic editor doesn't respect image size and shows images as fullwidth

### ISSUE THREAD

**Issue by sanjeev00733** [Automattic/themes#443]
Create a post in classic editor and add an image in content and area and resize the image, publish the page and the image would appear fullwidth in frontend.

Editor Screenshot: http://cld.wthms.co/vOOQLO
Frontend: http://cld.wthms.co/6EFpFm

Note: Works fine with the gutenberg editor.

* User report: #8918225-hc
* Follow-up ticket: #1655792-zen
* User's site: https://scottyandaphrodite.wordpress.com/2018/12/19/adam-and-eve-i/ . (Issue won't be visible as I have added some CSS code to fix this.)

**Comment by laurelfulford** [comment]
Thanks for the report, @sanjeev00733!

I'm having a hard time recreating this issue. Here are the steps I followed - please let me know if I'm missing something!

1. Add a large image to the Classic editor.
2. Edit the image and pick a smaller size (I picked Thumbnail). 
3. Publish the post. 

How the image looks in the editor:

![image](https://user-images.githubusercontent.com/177561/50531514-155e2200-0ac0-11e9-809c-9fd7fc99c324.png)

How the image looks on the front-end:
![image](https://user-images.githubusercontent.com/177561/50531525-36267780-0ac0-11e9-8f4b-1043db8c7efd.png)

I tried this on a post and a page and got the same result.

Is there something I'm missing to get it displaying as full-width?

**Comment by sanjeev00733** [comment]
Hi @laurelfulford ,

Thanks for looking into this. I did this in Calypso interface but I tested in wp-admin as well and I am able to replicate the issue.

Looks like you selected the image thumbnail which was already resized. Please try resizing image by dragging it by corners and then save the post. 

Also, I further found it only happens when the image is **center aligned** http://cld.wthms.co/UU6yWT

Please see results for above http://cld.wthms.co/RqF68n

**Comment by laurelfulford** [comment]
Thanks for the extra context, @sanjeev00733!

The centring of the image seems to be the key here -- I could also recreate by using the + and - buttons in Calypso (rather than resizing by dragging a corner), so long as it was centred.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
