### ISSUE TITLE
Perennial: Accordion block arrows do not display

### ISSUE THREAD

**Issue by msilbers** [Automattic/themes#4432]
### Steps to Reproduce

1. On a WOA site, add an Accordion block on any page
2. Switch to the Perennial Premium theme
3. View the page with the Accordion block (a Coblocks block, available only on Atomic sites)

### What I expected to happen

There should be an arrow indicating you can click for more details, which does show on other themes

### What actually happened

No arrow displays

The block with Twenty Twenty active:

<img width="838" alt="Screen Shot 2021-08-15 at 12 02 41 PM" src="https://user-images.githubusercontent.com/31680407/129484826-1394c49c-16df-4241-b4c2-8a3a73b43e48.png">

The block with Perennial active:

<img width="982" alt="Screen Shot 2021-08-15 at 12 06 27 PM" src="https://user-images.githubusercontent.com/31680407/129484861-bdde81ed-4cec-41ac-b722-a30a209ac142.png">

### Context

Customer report, in 4221369-zen

Example on my test site: https://writemiss.wpcomstaging.com/1172-2/

### Operating System

macOS

### Browser

Chrome/Chromium

### Browser Version(s)

happens in Chrome, Firefox, and Safari

### Is this specific to applied theme? If so, what is the theme name?

Perennial

### Simple/Atomic

Atomic

### Number of Users Impacted

One user

### Reproducibility

Consistent

### Other information

The arrows do seem to display on mobile devices only, the customer said:

> On iOS devices, arrows display fine (Safari and Chrome)

**Comment by inaikem** [comment]
@jeffikus, @Robertght 👋 Would it be possible to get an idea of if/when we'll be able to look at this? It's a retired 3rd party theme, and the block is provided by a 3rd party plugin (Coblocks). Any input would be appreciated!

**Comment by kylemcph** [comment]
Another report in 4712135-zen.

**Comment by Robertght** [comment]
Going to close this for now as CoBlocks isn't an option anymore on our sites.

Slack ref: p1651059474355319-slack-C029FM1EH 

cc @jeffikus
