### ISSUE TITLE
Add User-Configurable Duotone option to Customizer

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4434]
So that a user can control the Global Duotone options they should be presented with an option to enable/disable the duotone usage on all of the images.

* Enabling it applies the primary/background colors to the duotone attribute of all relevant blocks.
* Disabling it removes all colors from the duotone attribute of all relevant blocks.
* When a user changes Primary/Background colors using the customizer (and the option is enabled) those Primary/Background colors should be applied to all relevant blocks' duotone attributes. (Note: If we are able to accomplish [this issue](https://github.com/WordPress/gutenberg/issues/33905) then this item can be simplified by just using the `--primary` and `--background` CSS variables.)
* Determining if the control is enabled or disabled should be done comparing values in the User Theme JSON rather than via theme_mod values.

<img src="https://user-images.githubusercontent.com/146530/129772719-ee6cb4f1-dce1-48d5-afae-8ed54c1be9d1.png" width=300>

The "FSE" equivalent will be to manually set the duotone values of the blocks in question in the FSE Global Styles panel.

**Comment by pbking** [comment]
This will MOST LIKELY be accomplished by adjusting the User Theme JSON block styles of all of the image blocks to have the same values of `color.duotone` as `primary` and `background`.

**Comment by MaggieCabrera** [comment]
I'm totally onboard with Global Styles booleans, wish we could have them! This looks like a good approach to me

**Comment by MaggieCabrera** [comment]
This one isn't actually closed
