### ISSUE TITLE
Lodestar: Project type archives not loading the rest of the projects with a grid layout

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#444]
## Steps to replicate

1. Add a few projects and assign it to one project type.
2. Reach to the Project type archive in question and click on the "Older Posts" button.
3. The rest of the loaded projects will be loaded but won't respect the grid layout of the ones above.

## Result
The rest of the projects didn't keep the same grid layout
https://monosnap.com/file/7FoikFaolljLtIugadVJ8QRu5de4j2

## Expected
To have the same layout on load.

* User report: 8895005-hc
* Follow-up ticket: 1653607-zen
* User's site: https://projectmanifest.org/project-type/orchestra/

Same thing happened on my end. I had to increase the number of projects shown per page as workaround.

**Comment by laurelfulford** [comment]
This has been committed to WP.com in r53327-wpcom-themes.

It looks like the related ZD ticket has been closed; @Robertght can you please follow up with the original reporter? Thanks!

**Comment by vanemmerikbv** [comment]
Looks like it's still not working, @laurelfulford...

I applied the changed code to all 3 files, but 'filters' (or paging) still doesn't sort the desired effect.

Pretty time-consuming issue, any help will be much appreciated!

example here: [www.vanemmerikbv.nl/projecten](url) (site in Dutch...)
