### ISSUE TITLE
Build Alignment Test Case page for Theamdemo

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4457]
We test alignments in our themes a lot, especially as we work through things like #4456.  
While unit tests would be coolest at a minimum we should document and have an example of all of the alignment scenarios that need to be evaluated for correctness. 

Adding a page on Theamdemo with all of those expectations outlined would be immensely helpful.

Long ago I [started on a page ](https://wordpress.com/post/theamdemo.wordpress.com/1339) that had the "test scenario" documented in a paragraph.  Expanding that (or something like it) could help us to quickly evaluate our themes as well as make block markup available for easy reproduction in bug reports, etc.

**Comment by MaggieCabrera** [comment]
Can we close this one, @pbking ?

**Comment by pbking** [comment]
Yup.  The page reflects at least most of what I think we were looking fore re: alignments.
Hopefully it will get added to as we find additional cases to review (columns, flex, etc) but it's done for now.
