### ISSUE TITLE
Blockbase: invalid Google Fonts API call when System Font selected

### ISSUE THREAD

**Issue by RavanH** [Automattic/themes#4458]
## Steps to replicate

In the Customizer, select "System Font" for both the Body and Header fonts.

## Result

The page head will include `<link rel='stylesheet' id='blockbase-fonts-css'  href='https://fonts.googleapis.com/css2?display=swap' type='text/css' media='all' />` which will generate a 404 response from Google.

## Expected

No blockbase-fonts-css stylesheet at all.

**Comment by MaggieCabrera** [comment]
Closed via #4489
