### ISSUE TITLE
Rowling: galleries in block editor do not left-align flush with theme's CSS

### ISSUE THREAD

**Issue by jessestu** [Automattic/themes#447]
## Steps to replicate

1. User the block editor on a site with Rowling theme.
2. Create an image gallery.
3. Publish the page.

## Result

`.post-content ul { margin-left: 1.5em; }` causes the entire gallery to indent. This CSS seems to be in the theme.

Image: 
![screen shot 2018-12-20 at 12 01 10](https://user-images.githubusercontent.com/32908730/50317074-4ff00b00-047f-11e9-967d-d4d8c464a6de.png)

## Expected

I expected the gallery to align with the left with 0 margin. This CSS override fixes the issue:

```
.post-content ul.wp-block-gallery {
  margin-left: 0;
}
```

* User report: 1659287-zen
* Follow-up ticket: 1659287-zen (no followup needed as they have the CSS workaround)
* User's site: https://forcinduct.in/2018/12/20/lambo-aventador-svj/

**Comment by alaczek** [comment]
Fixed in r53230-wpcom-themes
