### ISSUE TITLE
Blockbase: Child theme custom Google font always loaded

### ISSUE THREAD

**Issue by RavanH** [Automattic/themes#4487]
## Steps to replicate

Create a child theme with custom Google font set in the theme.json with a "google" attribute. Par example Mayland Blocks, see [mayland-blocks/theme.json](https://github.com/Automattic/themes/blob/e4fd001134863ab16246fbaf47dee42a687372fb/mayland-blocks/theme.json#L342) or [skatepark/theme.json](https://github.com/Automattic/themes/blob/e4fd001134863ab16246fbaf47dee42a687372fb/skatepark/theme.json#L387) for example.

## Result

The child theme font will be loaded ALWAYS instead of only when there is no user data (after first activation of the  theme) or if the user has expressly selected the font in Typography settings.

## Expected

Font to be added to the googlefonts api call only when it is actually used (default settings or user selected).

**Comment by MaggieCabrera** [comment]
Closed via #4489
