### ISSUE TITLE
Blockbase: duplicate font in Google fonts URL

### ISSUE THREAD

**Issue by RavanH** [Automattic/themes#4488]
## Steps to replicate

In the Customizer, select both for Body and Header fonts the same Google font and save settings.

## Result

In the page source, the URL parameters in the call to https://fonts.googleapis.com/css2 will contain the same font twice.

## Expected

One font in the URL.

Please note: this does not change the response from Google so it is not a defect, just something that can be fixed easily :)

**Comment by MaggieCabrera** [comment]
Closed via #4489
