### ISSUE TITLE
Twenty Twelve: Submenu not visible on tablet view

### ISSUE THREAD

**Issue by edwinho89** [Automattic/themes#449]
## Steps to replicate

When viewing Twenty Twelve themed sites on tablet, it displays the primary menu well. However, submenus aren't clearly visible, and can be missed from reader's perspective.

When you view the theme's demo on https://twentytwelvedemo.wordpress.com/ , you'll see that there are submenus under "A Parent Page", however difficult to navigate on tablet.

On mobile view however, submenus are listed so it is still visible.

## Expected

A way to see that submenu exists when viewed on tablet.

* User report: 4040964-hc
* Follow-up ticket: 1670751-zen
* User's site: twentytwelvedemo.wordpress.com

**Comment by edwinho89** [comment]
Hi @laurelfulford !

Good point! Looking at Core Trac - looks like this has been reported already: https://core.trac.wordpress.org/ticket/41822

I'm going to give a go at closing this thread. Feel free to adjust this otherwise. :)

**Comment by laurelfulford** [comment]
Awesome - good find @edwinho89! :) Thanks!
