### ISSUE TITLE
Sketch: sub-menus are not being styled using the Navigation Menu widget

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#45]
## Steps to replicate

1. Activate the theme
2. Add a menu widget
3. Select a menu that has sub-menu items.
4. See the result in your widget area.

## Result

<img width="339" alt="captura de tela 2018-03-19 as 13 56 01" src="https://user-images.githubusercontent.com/1136160/37610011-52876b6e-2b7d-11e8-95e5-cbd25db02e1a.png">

## Expected

A visual difference between parent items and sub-menus:

<img width="336" alt="captura de tela 2018-03-19 as 13 58 14" src="https://user-images.githubusercontent.com/1136160/37610141-9a94251e-2b7d-11e8-9ff3-c5e022a37149.png">

* User report: #988826-zen
* Follow-up ticket: #988826-zen

**Comment by allancole** [comment]
Marking this as an enhancement, since the widget isn’t necessarily broken and the links are still accessible.

**Comment by laurelfulford** [comment]
Fixed in r48992-wpcom-themes.

**Comment by laurelfulford** [comment]
@eduardozulian can you please follow up with the user? The ZD ticket is closed. Thanks!
