### ISSUE TITLE
Sketch: Adding project tags no longer populates Featured Content slider after WordPress 5.x update

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#451]
## Steps to replicate

The user previously added portfolio projects to the featured content slider by tagging portfolio projects with the `featured` tag (much like other themes populate the featured content slider with tagged posts).

![](http://cld.wthms.co/ysKtqQ+)

The user said that this stopped working after the recent WordPress 5.x update (they referred to the "interface" change).

I checked the demo theme, and the projects featured in the featured content slider are tagged, just as the user's projects are tagged.

## Result

Tagged projects are no longer populating the site's featured content slider.

## Expected

When projects are tagged with the same tag added to the Featured Content section in the Customizer, the relevant projects should be added to the site's featured content slider.

* User report: 5878446-hc
* Follow-up ticket: 1670953-zen
* User's site: https://denisbettio.com/

**Comment by laurelfulford** [comment]
Thanks for reporting this, @pauljacobson! 

It seems odd that this stopped working with the upgrade -- and I can't see any tags on the projects when I visit the site's /wp-admin.

When I view a project in the new editor, it doesn't even seem to have the option to add regular tags, just project tags, which makes me think I'm missing something silly :| 

Were you able to recreate this? Where did you see the users projects tagged?

**Comment by laurelfulford** [comment]
Thanks @KristinaKay!

I think the issue I was running into was a Calypso/Gutenberg one -- the Tags section was no longer showing up on pages or portfolio projects on themes that added them to featured content:

https://github.com/Automattic/wp-calypso/issues/28975

More info here: p7jreA-20e-p2

This looks like it's now fixed, but I'll leave this ticket open this user confirms it's working for them with Sketch.

**Comment by laurelfulford** [comment]
It looks like the user has followed up and verified that this is fixed, so I'm going to close this ticket!
