### ISSUE TITLE
Social icons block on sidebar under Penscratch 2 Theme,  shows narrowed Icons

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/themes#4519]
### Steps to Reproduce

1. Site needs Penscratch 2 theme
2. Under Customize - Widgets, enter the sidebar and create a Social Icons blocks
3. The icons won't appear circular (as expected) but rather deformed / narrowed

### What I expected to happen

Social icons should appear circular.
(See expected on the left, what happens at the right - https://d.pr/i/jwiu5U/bNV5xSecXf)

![image](https://user-images.githubusercontent.com/79575219/131153966-bb58b5ea-e4ec-4303-b6ec-1d1f57e8420a.png)

### What actually happened

Social icons appeared deformed. 
(See expected on the left, what happens at the right - https://d.pr/i/jwiu5U/bNV5xSecXf)

![image](https://user-images.githubusercontent.com/79575219/131153975-6b20bee3-1d8c-4f11-8e19-9f7812d42624.png)

### Context

Request from customer in 19269213-hc

### Operating System

macOS

### OS Version

11.3.1

### Browser

Chrome/Chromium

### Browser Version(s)

Version 92.0.4515.159 (Official Build) (x86_64)

### Is this specific to applied theme? If so, what is the theme name?

Seems so: Penscratch 2

### Simple/Atomic

Simple, Atomic

### Number of Users Impacted

One user

### Available Workarounds

Other themes display those icons without problem. Another option is to use the Social Icons widget instead of the block:

![image](https://user-images.githubusercontent.com/79575219/131154617-23acbb0a-c195-4094-a449-c4a8bc89dfcf.png)

### Reproducibility

Consistent

**Comment by DavidSaladu** [comment]
Notify customer 4252867-zd-woothemes when solved. Thanks!

**Comment by zdenys** [comment]
This is affecting various other themes:
- https://github.com/Automattic/themes/issues/2806
- https://github.com/Automattic/themes/issues/5565
