### ISSUE TITLE
Quadrat: Mobile header spacing bug

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4527]
The Quadrat header appears incorrectly placed on mobile viewports:

Current|Intended
---|--- 
![current](https://user-images.githubusercontent.com/1202812/132033909-9890f486-c9cb-4aa5-a4d5-ca997aa6d5a7.png)|![new](https://user-images.githubusercontent.com/1202812/132033911-d8f23560-13c9-451f-81b1-81c3a91a176d.png)

The issue is both the spacing on top of the title/menu button, and also the spacing in between the title and the tagline.

**Comment by jeffikus** [comment]
@pbking can we close this?

**Comment by kjellr** [comment]
I'm now seeing this issue on the demo site: 

<img width="374" alt="Screen Shot 2021-10-01 at 9 39 25 AM" src="https://user-images.githubusercontent.com/1202812/135629633-5ee246a7-ed99-4db8-a80f-c2f833036ef1.png">

**Comment by kjellr** [comment]
Today the demo site looks a little different, but still not as intended: 

<img width="573" alt="Screen Shot 2021-10-04 at 8 47 29 AM" src="https://user-images.githubusercontent.com/1202812/135854096-d4066a97-4cd1-4960-912d-f49f2ad57ae0.png">

**Comment by scruffian** [comment]
This is what I see on the demo site after the latest round of changes, so closing this.
<img width="514" alt="Screenshot 2021-10-06 at 14 19 10" src="https://user-images.githubusercontent.com/275961/136210173-cb0666c6-c058-4e0a-bafe-c6a864c4ea23.png">

Feel free to reopen if that's not correct still :)
