### ISSUE TITLE
Skatepark: Post/page editor text appears closer to the divider than it does on the front end

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4528]
Editor|Front End
---|---
<img width="1324" alt="Screen Shot 2021-09-03 at 12 37 36 PM" src="https://user-images.githubusercontent.com/1202812/132039646-2a09ce5a-1ed2-4599-88e3-1eb19755d05a.png">|<img width="1325" alt="Screen Shot 2021-09-03 at 12 37 18 PM" src="https://user-images.githubusercontent.com/1202812/132039645-3cb316c0-45ad-4d39-89c4-7545551d490b.png">

The title and line area also not wide-width. @melchoyce would you mind mocking up the intended spacing there when there's no featured image? I don't think we have a comp for that.

**Comment by melchoyce** [comment]
How does 90px above and below the divider feel?

![image](https://user-images.githubusercontent.com/2846578/132363361-87a1f6df-d968-4677-b9ca-5e85899109eb.png)

**Comment by kjellr** [comment]
That looks comfortable to me!
