### ISSUE TITLE
Quadrat: Layouts misaligned in different occasions

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4529]
Not sure if this is a bug from the theme or from Gutenberg, but I was hoping someone could look into it. While testing Quadrat on my [test site](https://testinginthewind.mystagingwebsite.com/), in which I was trying to customize as much as I could, I found some issues.

When I click "Inherit default template" in the Query Loop, this is what it looks like:

| Editor      | Site |
| ----------- | ----------- |
|  <img width="1534" alt="Captura de ecrã 2021-09-03, às 17 22 31" src="https://user-images.githubusercontent.com/65220155/132038626-4f0750df-11f5-4c01-b80b-38eb41b2bfc8.png">   | <img width="1535" alt="Captura de ecrã 2021-09-03, às 17 22 18" src="https://user-images.githubusercontent.com/65220155/132038585-9b4578f8-2ccd-42fc-bd9d-9b3be7ee9911.png">       |

This also happens though, if I unselect "Inherit default template" and set the widths myself.

| Editor      | Site |
| ----------- | ----------- |
| <img width="1534" alt="Captura de ecrã 2021-09-03, às 17 19 32" src="https://user-images.githubusercontent.com/65220155/132038852-43100af0-4965-4743-bb75-961477ccfeb7.png"> |   <img width="1534" alt="Captura de ecrã 2021-09-03, às 17 19 16" src="https://user-images.githubusercontent.com/65220155/132038877-831f45fe-d95b-4bb5-8750-580774a6842a.png">    |

I've tried Blockbase as well and this doesn't happen there. Any idea why this block may be aligning to the left?

**Comment by tinjure20** [comment]
Hello team! I am also experiencing similar to @beafialho after Gutenberg 11.4 update. In my very quick tests, all three Blockbase child themes (Quadrat, seedlet block and mayland block) behave similarly but not the Blockbase (screenshot below below).
I didn't report the other day when I tested wondering whether it was proper place to report. In one of my personal site that I use Quadrat - I revert back to v11.3 and it just works fine. Thanks

![image](https://user-images.githubusercontent.com/59660253/132044991-39967a1e-d5bb-4dba-8812-b8cf63ba60ee.png)
![image](https://user-images.githubusercontent.com/59660253/132045022-9bbfbe4c-fea1-4a6c-9f7b-d7521713f131.png)

**Comment by MaggieCabrera** [comment]
I think the latest version doesn't have these issues, we will update the dotorg version soon

**Comment by jeffikus** [comment]
Lets retest this one, and close if necessary.

**Comment by danieldudzic** [comment]
I've tested this with the latest version but wasn't able to replicate.

**Comment by MaggieCabrera** [comment]
Can confirm this has been fixed, we will update the dotorg version of the theme asap
