### ISSUE TITLE
Geologist: enhancements and code quality

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4531]
After a bit of discussion on slack with @scruffian there's a few things we can polish for Geologist. Right now the theme is directly duplicating Quadrat's css and that could be improved. There's three immediate areas we could work on:

- The header styling could live in Blockbase by [unifying these themes header styles](https://github.com/Automattic/themes/pull/4482). 
- The buttons styles for Skatepark and Quadrat+Geologist are a design pattern that is very popular. We could include that css in Blockbase without importing it to the main stylesheet, so that the parent theme provides the possibility to import these button styles without adding to the original theme's stylesheet.
- We should remove the Quadrat block pattern's CSS that is unused in Geologist. @kjellr will Geologist have patterns of its own?

**Comment by kjellr** [comment]
> We should remove the Quadrat block pattern's CSS that is unused in Geologist. @kjellr will Geologist have patterns of its own?

It probably will, but we haven't designed them yet. I'll add it to my todo list. 👍

**Comment by MaggieCabrera** [comment]
I'm closing this, since the only thing left is the header issue and that is being tracked already
