### ISSUE TITLE
Seedlet blocks: button styles

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4533]
The Button block styles are not working on the frontend:

Editor:
<img width="701" alt="Screenshot 2021-09-07 at 12 12 57" src="https://user-images.githubusercontent.com/3593343/132327861-21ab4a07-99f6-4bd4-943f-89516abe4297.png">

Frontend:

<img width="758" alt="Screenshot 2021-09-07 at 12 13 02" src="https://user-images.githubusercontent.com/3593343/132327860-be982d6a-76e9-4656-a752-0f159394fcd3.png">

**Comment by pbking** [comment]
Currently working OK for me:
![image](https://user-images.githubusercontent.com/146530/132539595-42d39100-694e-4392-b74c-927c198720fb.png)
![image](https://user-images.githubusercontent.com/146530/132539624-1769418e-1010-4219-95eb-8461f1e6d4bb.png)

**Comment by MaggieCabrera** [comment]
Yep, must have been my env, it works fine now!
