### ISSUE TITLE
Singl: Update "child page" link in documentation

### ISSUE THREAD

**Issue by deancroyal** [Automattic/themes#4555]
## Steps to replicate

1. Visit Theme's documentation on WordPress.com: https://wordpress.com/theme/singl/
2. Scroll down to "Set up your site like Singl‘s demo"
3. The last sentence within the first step: "We also added a child page (“The Deep Web Tour”)."

## Result

"child page" from that sentence links to the following support guide: https://wordpress.com/support/pages/#create-sub-pages-page-order

That support guide reference appears to no longer exist.

## Expected

I expected the link to point to this support guide page: https://wordpress.com/support/pages/page-options/#parent-page

* User report in WordPress.com Forums thread: https://wordpress.com/forums/topic/singl-theme-where-to-start-confused-lost/#post-3728764

**Comment by kathrynwp** [comment]
I made this edit. FYI @deancroyal all Happiness Engineers are welcome to make theme-documentation fixes directly, they should have access. :)

It seems to be possibly cached here: https://wordpress.com/theme/singl/

I will close this for now but check it again in a while to make sure it "took."
