### ISSUE TITLE
Skatepark: Remove border between post title and excerpt on blog list

### ISSUE THREAD

**Issue by melchoyce** [Automattic/themes#4558]
## Steps to replicate

Add a new post that doesn't contain any content that would be output into an excerpt to see the issue at its worst.

## Result

![image](https://user-images.githubusercontent.com/2846578/132570484-7e417d5a-cb8e-48c0-a64a-9f94d41cf4ae.png)

## Expected

Any way to remove the border that appears between the title and excerpt, and move the content closer to the post title? For example:

![image](https://user-images.githubusercontent.com/2846578/132571100-faa0aa26-92d3-4b42-9d1f-6b7d63a5bd96.png)

**Comment by danieldudzic** [comment]
#4561 addresses this ✅
