### ISSUE TITLE
Libretto: Unable to Add Text Content After Moving Block to First Position

### ISSUE THREAD

**Issue by wpericam** [Automattic/themes#458]
## Steps to replicate

Using Safari (Version 12.0.2) and the Libretto theme. Create a paragraph block in the first position in the post or in the second position and try to add content. 

## Result

When Paragraph block is moved to the first position, you can no longer add content. User shared a video of the behavior here. https://www.dropbox.com/s/5rkot0o1v5lw6nr/Amy%20Parkes%20-%20Wordpress%20Support%20Vid.mov?dl=0 

## Expected

You would expect to be able to add text to a Paragraph block regardless of it's position. 

We have been able to replicate the issue only when using both Safari (Version 12.0.2) and the Libretto theme. 

## Additional Info & Follow Up 
* P2 here: p2EDhh-Bi-p2
* Site http://notyourmothersbookshelf984114138.wordpress.com/
* Original ticket: #1620897-zd
* Follow up Ticket: #1676565-zd

**Comment by laurelfulford** [comment]
I think the issue may be Libretto's fancy first letter/first line styles, like here: 

https://github.com/Automattic/themes/blob/master/libretto/css/editor-blocks.css#L445-L460

A good fix might be to override unless on focus (similar to how the block-based editor applies the drop cap styles), or it might need to be removed entirely.

**Comment by torres126** [comment]
Just noting that I can recreate something similar, but not identical, without Safari. Using Chrome (version 49) still causes an issue for me I can imagine it being especially frustrating if you're trying to start a block by using **/** too. I can add text, but it still sort of messes up...this shows it better than I can explain:

![ezgif-2-042f05991cd0](https://user-images.githubusercontent.com/43215253/50567634-194ba780-0d3f-11e9-9fb8-078274ae585b.gif)

**Comment by laurelfulford** [comment]
Have a patch in progress in #468; need to circle back tomorrow and make sure it works for the Chrome issue, too, before it's ready!
