### ISSUE TITLE
Skatepark: Header does not have intended top margin

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4585]
The margin above the header is incorrect on [the WP.com demo site](https://skateparkdemo.wordpress.com). 

Current|Intended
---|---
<img width="989" alt="Screen Shot 2021-09-14 at 2 00 01 PM" src="https://user-images.githubusercontent.com/1202812/133309649-a73ca5f6-fef5-4461-9b1f-141bebaa9ed3.png">|<img width="989" alt="Screen Shot 2021-09-14 at 1 59 42 PM" src="https://user-images.githubusercontent.com/1202812/133309651-a8bf6b94-65f9-4bdb-a3ef-e7e04e3d3e04.png">

cc @melchoyce I think the design said this should be [45px margin above there](https://cloudup.com/cWVBBK7xNEj), but I think 30px total seems more comfortable since that matches the left/right margins. What do you think?

**Comment by melchoyce** [comment]
30px seems okay 👍
