### ISSUE TITLE
Skatepark: Submenu background color is incorrect

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4586]
<img width="301" alt="Screen Shot 2021-09-14 at 2 05 15 PM" src="https://user-images.githubusercontent.com/1202812/133310375-d3efeff1-f1d8-4e58-9ce5-9196a7462e37.png">

The background color here should be the same as the page background. Also, all menu items are missing hover states. I believe these should just receive an underline, but @melchoyce can you confirm?

**Comment by melchoyce** [comment]
How's this?

![image](https://user-images.githubusercontent.com/2846578/133321726-80633746-fe3e-4cc3-a399-2fe710da8f99.png)

**Comment by kjellr** [comment]
Looks great. 👍
