### ISSUE TITLE
Skatepark: Mobile menu appears underneath the admin bar when expanded

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4587]
When this happens, the close button is unreachable behind the admin bar: 

![mobile](https://user-images.githubusercontent.com/1202812/133310774-e6b79de5-cf2a-4632-939a-95466f020611.gif)

**Comment by danieldudzic** [comment]
I'm unable to replicate

![4NgCY692IR](https://user-images.githubusercontent.com/905781/134044308-4a6bf2fa-c7be-48fa-b7ea-1b70761edb2a.gif)

**Comment by pbking** [comment]
I'm unable to reproduce this one:
![image](https://user-images.githubusercontent.com/146530/134058932-810827f1-8086-4b5c-bcc9-92d6a1e1473b.png)

though my admin bar looks different so maybe I'm not testing the same thing...:
![image](https://user-images.githubusercontent.com/146530/134058981-33b2f8ad-b6b1-4f44-912d-48469ed358e5.png)

**Comment by danieldudzic** [comment]
Wasn't able to replicate locally, but you can replicate on WP.com.

Same thing happens in Blockbase - will push a PR now.

**Comment by danieldudzic** [comment]
Please review D67129-code

**Comment by scruffian** [comment]
Deployed in r232057-wpcom
