### ISSUE TITLE
Skatepark: Default posts template gap is incorrect

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4589]
The gap between individual posts in the default posts template is much wider than in the original mockups. Please reconsult the Figma file for this one: 

Development|Mockup
---|---
<img width="647" alt="Screen Shot 2021-09-14 at 2 15 38 PM" src="https://user-images.githubusercontent.com/1202812/133311843-ac7a33ad-738a-45ab-b4d7-e64551504ace.png">|<img width="515" alt="Screen Shot 2021-09-14 at 2 15 23 PM" src="https://user-images.githubusercontent.com/1202812/133311837-c7dec04b-f338-4e20-9411-5eb9e2fe2f4b.png">

**Comment by pbking** [comment]
I believe this has been addressed in #4665

**Comment by scruffian** [comment]
> I believe this has been addressed in #4665

Is that the right PR? I still see the same issue in #4665

**Comment by scruffian** [comment]
This wasn't fixed by #4665
