### ISSUE TITLE
Skatepark: Mobile spacing around social menu is incorrect

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4591]
Current|Intended
---|---
![current](https://user-images.githubusercontent.com/1202812/133313655-be11e739-f06f-4bc7-b759-4c93a8782255.png)|![iPhone 8 - 19](https://user-images.githubusercontent.com/1202812/133313665-9eb11ee1-b71c-4ee5-8388-74d11986ce5f.png)

Intended margins: 

![iPhone 8 - 19](https://user-images.githubusercontent.com/1202812/133313976-18cf17b4-3c50-4b8c-b198-8279292b6f0b.png)

**Comment by danieldudzic** [comment]
I don't want to add a CSS fix, as this calls for a `theme.json` setting. Hoever, I can't find one. I'm not even sure how to target the Social Icons menu. It's not the `Social Links` block, right?

**Comment by kjellr** [comment]
This is still an issue — the spacing below the tagline is incorrect even when the social menu is inactive:

Current|Design Comp
---|---
<img width="373" alt="Screen Shot 2021-11-02 at 3 24 37 PM" src="https://user-images.githubusercontent.com/1202812/139935371-f53a8e33-ac44-4966-826d-0c93a946d86e.png">|![iPhone 8 - 22](https://user-images.githubusercontent.com/1202812/139937498-2a4bc33f-9bcf-4a88-9c04-87a97fde7bfc.png)
