### ISSUE TITLE
Quadrat: If a post has no title, we should collapse the space that the title would usually take up

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4592]
Before|After
---|---
<img width="745" alt="Screen Shot 2021-09-14 at 2 40 03 PM" src="https://user-images.githubusercontent.com/1202812/133315224-ac075c3d-9611-480a-81cd-14bfc369b202.png">|<img width="700" alt="Screen Shot 2021-09-14 at 2 41 11 PM" src="https://user-images.githubusercontent.com/1202812/133315264-d0dbc255-f73f-47dd-b5c6-91407179b165.png">

**Comment by danieldudzic** [comment]
<img width="890" alt="spacer" src="https://user-images.githubusercontent.com/905781/133814867-68158863-d3d9-44f6-bbfe-43d01442f974.png">

There's a spacer in the `single.html` template which accounts for the majority of this space. I'm wondering if there's a way to target an empty title via CSS - I can't think of one. Can't use a PHP check in the template either.

The only thing that comes to my mind is removing the spacer, and somehow trying to add some additional spacing to the post title part of the markup? Any ideas?
