### ISSUE TITLE
Quadrat: Site Logo right margin should match spacing between title & tagline

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4597]
On desktop, the right margin on the site logo should match the spacing between the title and tagline (20px). 

Before|After
---|---
<img width="519" alt="Screen Shot 2021-09-14 at 3 04 37 PM" src="https://user-images.githubusercontent.com/1202812/133318643-a296b76e-d97c-4352-b3bd-e468d2a13558.png">|<img width="496" alt="Screen Shot 2021-09-14 at 3 04 29 PM" src="https://user-images.githubusercontent.com/1202812/133318649-7f059739-e63f-4ed4-b822-f1487e20c91b.png">

**Comment by pbking** [comment]
This was addressed successfully in #4692
