### ISSUE TITLE
Quadrat: On mobile, site logo bottom margin is incorrect

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4598]
On mobile, the site logo bottom margin should match entire spacing between site logo and top of site.

Before|After
---|---
<img width="319" alt="Screen Shot 2021-09-14 at 3 06 43 PM" src="https://user-images.githubusercontent.com/1202812/133319092-28ccda7a-2cb1-4054-a96b-ebdd63c52d55.png">|<img width="317" alt="Screen Shot 2021-09-14 at 3 07 37 PM" src="https://user-images.githubusercontent.com/1202812/133319096-bff9b749-f455-42d3-ba7a-284404a5cd4a.png">

Measurements:

![spacing](https://user-images.githubusercontent.com/1202812/133319282-1ed1e9e9-ce7d-4bc8-991f-6a16d9ae3d1a.png)

**Comment by danieldudzic** [comment]
@kjellr Since Quadrat is already styling this via CSS, do you think we can keep this approach?
