### ISSUE TITLE
Sela: allow randomly ordered testimonials in the front page

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#46]
Currently, users can't randomize their testimonials on the front page. We're using the menu order as a way to make them appear, but there's no way to make them shuffle on each new visit to the website.

Sela already has a Customize > Testimonials area, so we could also add a _Randomize posts in the front page_ option in there.

Marking this as an enhancement for the future.

* User report: #2110049-hc
* Follow-up ticket: 
* User's site: https://mykindnutrition.com

**Comment by alaczek** [comment]
Sela is quite old, and we would not make this kind of change at this point. There is a replacement theme available though - [Dara](https://darademo.wordpress.com/), and it has an option in the Customizer to display random testimonials on the front page.
