### ISSUE TITLE
Sela: Product images don't display on WooCommerce shop page, only default placeholder images

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#460]
## Steps to replicate

The user created a WooCommerce store, and activated the Sela theme. They added product images to each product, and the product images display on single product pages. They don't display on the shop page, though:

![](http://cld.wthms.co/EyJmP6+)

We tested this in Storefront and Dara, and the product images displayed correctly in those themes.

## Result

Product image thumbnails don't display on the shop page. Sela opts for a default, placeholder image instead. For example:

```
<a href="https://beautyandthesurgeon.com/product/quick-doll-session/" class="woocommerce-LoopProduct-link woocommerce-loop-product__link"><img src="https://i0.wp.com/beautyandthesurgeon.com/wp-content/plugins/woocommerce/assets/images/placeholder.png?resize=300%2C225&amp;ssl=1" alt="Placeholder" class="woocommerce-placeholder wp-post-image" scale="0" width="137" height="103"><h2 class="woocommerce-loop-product__title">Quick Doll Session</h2>
	<span class="price"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">$</span>99.99</span></span>
</a>
```

## Expected

Product images should display on the shop page.

* User report: 9146815-hc
* Follow-up ticket: 1678877-zen
* User's site: https://beautyandthesurgeon.com/shop/

**Comment by alaczek** [comment]
I see the product images showing on the user site now. Can you confirm @pauljacobson ?
We had this issue pop up a couple of times, and it was usually because of Content Options - if featured images were turned off for archive pages, they would not show up on the shop page either, but IU believe that was fixed a while back.

**Comment by danieldudzic** [comment]
Sela has been now retired. I'm closing this.
