### ISSUE TITLE
Quadrat: Menu links have no spacing in Safari

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4604]
Here's how they look:

<img width="229" alt="Captura de ecrã 2021-09-15, às 10 52 39" src="https://user-images.githubusercontent.com/65220155/133412403-cf1b91a8-f830-4286-8226-131d5607a893.png">

<img width="330" alt="Captura de ecrã 2021-09-16, às 17 48 34" src="https://user-images.githubusercontent.com/65220155/133652785-52a8a098-e3cf-4d66-a18e-471fe7dea90b.png">

**Comment by kjellr** [comment]
I can't reproduce this. Is it still an issue?

**Comment by beafialho** [comment]
Yeah, I've tried in other devices and still seeing this.

**Comment by kjellr** [comment]
Are you seeing this in the editor or in the front end?

**Comment by beafialho** [comment]
I'm seeing this in the front end. It seems to happen in a lot of sites, Blockbase too. I wonder if this has to do with my browser.

<img width="608" alt="Captura de ecrã 2021-09-28, às 14 48 54" src="https://user-images.githubusercontent.com/65220155/135100076-22e50457-7cc9-4ce8-aff0-9a392ef3741a.png">

**Comment by beafialho** [comment]
I have solved this by updating Safari!

**Comment by supernovia** [comment]
Older versions of Safari, like the ones folks might be using on older phones or iPads, do not support flexbox gaps. 

https://github.com/Automattic/themes/issues/5353

**Comment by MaggieCabrera** [comment]
> Older versions of Safari, like the ones folks might be using on older phones or iPads, do not support flexbox gaps.
> 
> #5353

This is a core issue not specific to this theme. The block supports only gap without a fallback. Any patches to bring compatibility should be done in Gutenberg, not on the themes
