### ISSUE TITLE
Quadrat: Remove folder icon from post meta

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4605]
We should remove the folder icon from the post date and separate the date and categories with a dot `·`

| Currently      | Intended |
| ----------- | ----------- |
| <img width="360" alt="Captura de ecrã 2021-09-15, às 10 58 14" src="https://user-images.githubusercontent.com/65220155/133413317-4271b3ed-d0db-4d70-8647-051badef7f14.png">  | <img width="540" alt="Captura de ecrã 2021-09-15, às 10 58 06" src="https://user-images.githubusercontent.com/65220155/133413269-d70b605a-b71b-4181-9fc4-371cf9d88da3.png"> |

**Comment by mikachan** [comment]
This was fixed with https://github.com/Automattic/themes/pull/4695 so I'm going to close this issue.
