### ISSUE TITLE
Quadrat: Add padding to Post Meta

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4606]
Currently, Post Meta is too close to the Post Title which makes the layout feel more constrained.

Adding 50px padding to the post meta area feels reasonable and more comfortable.

<img width="1031" alt="Captura de ecrã 2021-09-15, às 11 16 43" src="https://user-images.githubusercontent.com/65220155/133416361-33696edb-7f67-42ce-82ac-b8b825bddd56.png">

| Current      | Intended |
| ----------- | ----------- |
| <img width="893" alt="Captura de ecrã 2021-09-15, às 11 17 15" src="https://user-images.githubusercontent.com/65220155/133416240-56a98162-7ee4-46e4-961e-652945e51e64.png">  |  <img width="1031" alt="Captura de ecrã 2021-09-15, às 11 16 52" src="https://user-images.githubusercontent.com/65220155/133416292-f8db9680-4a23-430d-9a89-1ca1151625b6.png">  |

**Comment by kjellr** [comment]
In addition, the category icon shouldn't be there. Instead, we should have a little dot divider when there are categories. Here's an example from the comps: 

<img width="324" alt="Screen Shot 2021-09-21 at 2 39 55 PM" src="https://user-images.githubusercontent.com/1202812/134228797-bd5bf5d3-eead-4844-a293-8aaa59ae880c.png">

EDIT: Tracked here: https://github.com/Automattic/themes/issues/4605

**Comment by beafialho** [comment]
@kjellr also mentioned that here: #4605

**Comment by kjellr** [comment]
Ah thanks, I missed that one.

**Comment by danieldudzic** [comment]
> In addition, the category icon shouldn't be there. Instead, we should have a little dot divider when there are categories. Here's an example from the comps:
> 
> <img alt="Screen Shot 2021-09-21 at 2 39 55 PM" width="324" src="https://user-images.githubusercontent.com/1202812/134228797-bd5bf5d3-eead-4844-a293-8aaa59ae880c.png">
> 
> EDIT: Tracked here: #4605

@kjellr Does this apply to other meta as well? I'm assuming we want dots to replace all the Blockbase icons?

<img width="1260" alt="tags" src="https://user-images.githubusercontent.com/905781/134392057-153421f5-55c8-4dfb-beae-7a78c90df329.png">

Sidenote: the font-size doesn't look correct :)

**Comment by danieldudzic** [comment]
All of the extra meta need additional styling. They probably have slipped through the cracks as they are not present in the default template, but can be added via FSE.
<img width="899" alt="Button_–_themes" src="https://user-images.githubusercontent.com/905781/134395567-252b353a-4ae8-420b-bb82-8453238130a2.png">

**Comment by kjellr** [comment]
Quadrat's templates are not designed to display the tags or author blocks at all, so those should not appear by default.

If users add those blocks manually, we should make sure they display correctly though.

**Comment by beafialho** [comment]
That's right.

Dots should replace the icons and separate all the extra meta eventually added by a user. Every meta should be in the same font size as the date and categories.
