### ISSUE TITLE
All Themes: Sign-up Prompt Overlaps with Mailchimp on Mobile

### ISSUE THREAD

**Issue by torres126** [Automattic/themes#461]
## Steps to replicate

1. Create a WordPress.com site 
2. Add a[ Mailchimp pop-up](https://en.support.wordpress.com/mailchimp/)
3. Visit the site in an incognito tab (so that the sign up to WordPress.com prompt appears) on a mobile device, or use Dev Tools to set your screen to that of a smaller device
4. Click "Subscribe" 
5. See issue

## Result

![screenshot_20181231-085807](https://user-images.githubusercontent.com/43215253/50557190-c04a2800-0cda-11e9-9c40-bb43f171dce1.jpg)

Upon clicking "Subscribe", there's no way to dismiss the sign up form. 

![screenshot_20181231-085823](https://user-images.githubusercontent.com/43215253/50557195-c7713600-0cda-11e9-9bc4-b0e3ef8a8be7.jpg)

## Expected

There should be a way to dismiss the Mailchimp pop-up. For comparison, here's how it's like on a larger screen. 

![screenshot_20181231-085842](https://user-images.githubusercontent.com/43215253/50557239-49615f00-0cdb-11e9-9b05-46297b640fa8.jpg)

Either the sign up to WordPress.com prompt should be removed completely when the Mailchimp Widget appears, or it should be out of the way. 

I haven't tested with other themes (it's a pain to get the Mailchimp Widget working - it even needs your address!), but the it was reported this happens with any site, and I imagine that would be the case too. 

* User report: https://en.forums.wordpress.com/topic/wp-add-and-mailchimp-popup-overlapping/
* User's site: http://kinobarut.wordpress.com/

**Comment by laurelfulford** [comment]
Thanks for reporting this, @torres126!

This looks like something that should be fixed in the widget itself, rather than in individual themes. I've moved this report to an existing ticket: 7862-wpcom.

**Comment by torres126** [comment]
Oops, thank you! :)
