### ISSUE TITLE
Blockbase: Sub-menu can flow off screen

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#4611]
## Steps to replicate

When you add a third menu level, it flows off the edge of the screen:

![image](https://user-images.githubusercontent.com/1645628/133465581-ef3c5c12-4acb-4d16-92ba-13bd5282a50a.png)

This is how Seedlet handles the same menu:

![image](https://user-images.githubusercontent.com/1645628/133450546-ef104a64-fd6b-4d53-b471-2f01af82c2b2.png)

**Comment by danieldudzic** [comment]
@kjellr Would mind providing some guidance on this. Do you think we need to support more than 1 level of depth for submenus?

**Comment by kjellr** [comment]
We should, but this seems like a Gutenberg problem (after all, the menu here is just the standard Navigation block), and I'm not sure it makes sense to build in too many theme-specific overrides in Blockbase. We should fix directly in Gutenberg.

**Comment by danieldudzic** [comment]
This seems to be potentially related: https://github.com/WordPress/gutenberg/pull/35077

**Comment by MaggieCabrera** [comment]
+1, this should be addressed on the editor

**Comment by danieldudzic** [comment]
Closing this in favor of the Gutenberg issue: https://github.com/WordPress/gutenberg/pull/35077
