### ISSUE TITLE
Skatepark/Quadrat: Comments are not displaying on page with comments 

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#4614]
## Steps to replicate

The comments are not displayed on a page that has comments. I can see this happening on both Skatepark and Quadrat but I haven't checked any other child themes, so it's probably worth checking the others as well. It works fine on Blockbase.

![image](https://user-images.githubusercontent.com/1645628/133461813-309f3d0c-bdab-4d50-9acf-73bee3d24439.png)

**Comment by adelineyaw** [comment]
It looks like the comments field doesn't appear on Pages for Blockbase and Blank Canvas ('Allow comments' has been selected). This was originally reported here: pd4QKa-sk-p2

User reports: 
- 4711319-zd-woothemes
- 4717621-zd-woothemes
