### ISSUE TITLE
Blockbase: Missing centered image alignment (classic editor)

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#4619]
## Steps to replicate

This image appears on the left instead of correctly being centered:

![image](https://user-images.githubusercontent.com/1645628/133472371-4c66fd64-cddb-4f43-8967-3bbddc57448f.png)

Example markup (classic editor):

```
<p><img class="size-full wp-image-906 aligncenter" title="Image Alignment 580x300" src="https://sarahnorrissandbox2.files.wordpress.com/2021/09/8a21e-image-alignment-580x300-1.jpg" alt="Image Alignment 580x300" width="580" height="300" /></p>
<p>The image above happens to be <em><strong>centered</strong></em>.</p>
```

**Comment by pbking** [comment]
🤔 
I don't think we have much tested or considered non-block markup like this.  Definitely valid, but it's mixing block layout techniques with non-block content.  (The above being an image tag rather an image block whos markup would instead look like this:

```
<div class="wp-block-image"><figure class="aligncenter "><img src="file.jpg"></figure></div>
```

As far as I know we have pretty good coverage of BLOCKS on [themedemo](crugM-p2), however there isn't a good representation of content built thusly.  Would there be value in adding some?

**Comment by mikachan** [comment]
> Definitely valid, but it's mixing block layout techniques with non-block content.

Yes exactly... I wasn't sure how common/normal or important this was. This issue was raised as part of the recent call for testing on Skatepark and Quadrat, and was spotted by running through the content from the [Theme Unit Test](https://codex.wordpress.org/Theme_Unit_Test).

There's a couple of other issues from the same round of testing that are marked with 'classic editor' in the title. We could maybe include the Theme Unit Test content (or some other non-block content) on themedemo to catch these types of issues?
