### ISSUE TITLE
Quadrat: Text unreadable in Code Block while editing

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4625]
Though it shows up correctly on the front end, in the editor the text is currently looking too dark. It should be pink to pass contrast.

<img width="839" alt="Captura de ecrã 2021-09-16, às 15 27 17" src="https://user-images.githubusercontent.com/65220155/133649611-860f7734-ce45-448a-84a5-db054ad78203.png">

**Comment by danieldudzic** [comment]
I can't replicate, seems to be working fine for me :)
![87jhtcvrHy](https://user-images.githubusercontent.com/905781/135309866-8883bdb1-4173-4d22-a607-c41e1688430a.gif)

**Comment by danieldudzic** [comment]
I was able to replicate on WordPress.com

**Comment by scruffian** [comment]
This is fixed by D67673-code
