### ISSUE TITLE
videomaker: Templates: Page templates - 404

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4642]
@beafialho does this look OK for a 404 page?
<img width="1440" alt="Screenshot 2021-09-20 at 16 51 09" src="https://user-images.githubusercontent.com/275961/134033153-25ce7fd1-51a8-4026-ba87-ca34632a5361.png">

**Comment by beafialho** [comment]
Sorry I missed this one.

It looks ok. Can the _"Oops! That page can't be found"_ be in a larger size, for instance with the Extra Large Paragraph?

**Comment by scruffian** [comment]
How's this?

<img width="1440" alt="Screenshot 2021-09-29 at 14 47 23" src="https://user-images.githubusercontent.com/275961/135281283-325277f5-cc36-4949-a759-4dcc0b4d9273.png">

**Comment by beafialho** [comment]
Looks good to me 👍
