### ISSUE TITLE
videomaker: Comment form styles (dotcom and dotorg) (if needed)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4646]
@beafialho how is this for the comment form
![localhost_4759__p=1](https://user-images.githubusercontent.com/275961/134036091-1ba565ab-0042-43d0-a03a-686295c9ff67.png)
?

**Comment by beafialho** [comment]
I think this looks good, the only thing looking weird is the spacing between the tick square and the "Save my name". Maybe make it closer to the square.

**Comment by scruffian** [comment]
Done in https://github.com/Automattic/themes/pull/4788
