### ISSUE TITLE
videomaker: Templates: Header template part (including mobile)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4651]
The videomaker nav should look like this:
<img width="265" alt="Screenshot 2021-10-14 at 19 16 30" src="https://user-images.githubusercontent.com/275961/137373470-52b05c04-472b-4b5d-857c-ee67b4ed71b1.png">
<img width="385" alt="Screenshot 2021-10-19 at 15 24 10" src="https://user-images.githubusercontent.com/275961/137930284-4e37cb84-1927-4acb-a81e-18f4061fd454.png">

Also the navigation in the header shouldn't be UPPERCASE, only in the patterns.

**Comment by mikachan** [comment]
Re-opened this to work on the following from @beafialho:

![image](https://user-images.githubusercontent.com/1645628/138112425-a95a8598-b696-4579-9ef2-2c77d3a653bd.png)

<img src="https://user-images.githubusercontent.com/1645628/138112476-69073aa6-5f6b-4e8a-b392-adfe1419458f.png" width="300"/>
