### ISSUE TITLE
videomaker: Core block settings (if needed)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4652]
Button styles need some tweaks:
<img width="786" alt="Screenshot 2021-09-20 at 14 58 06" src="https://user-images.githubusercontent.com/275961/134015042-89caba2b-96e4-479f-bab4-f1f193625af3.png">

**Comment by pbking** [comment]
Focus style doesn't match:
![image](https://user-images.githubusercontent.com/146530/134189192-7c398630-db05-47f1-81b7-cee81fb98a55.png)

I think all the buttons need is a 700 font weight to match.

**Comment by scruffian** [comment]
@kjellr @beafialho should we try to modify the user-agent default for focus styles?

**Comment by kjellr** [comment]
For the button styles, or in general? In general, we want to match the same focus styles as Quadrat here.

**Comment by scruffian** [comment]
Focus styles were added in https://github.com/Automattic/themes/pull/4684

**Comment by scruffian** [comment]
This has now been done.
