### ISSUE TITLE
videomaker: Pre-launch: readme.txt

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4653]

**Comment by scruffian** [comment]
@beafialho do we have a description for Videomaker?

**Comment by beafialho** [comment]
Here it is:

> _Videomaker_ is a free, minimalistic WordPress theme ideal for film directors and video creators. 
> 
> It features a variety of block patterns created specifically for film releases and video portfolios, and allows the traditional blogging experience with a single column layout for blog posts.
> 
> With simple, customizable typography, and alternative color palettes, _Videomaker_ lets your videos stand out both on desktop and mobile devices.

**Comment by MaggieCabrera** [comment]
I wonder if we should add any comment in the description regarding the use of the Videopress plugin. People who download this theme from dotorg are going to need the plugin for the theme to work as intended

**Comment by beafialho** [comment]
That's a good point, @kjellr what do you think?

**Comment by kjellr** [comment]
Would one of you mind double checking the theme directory rules for that? I know themes aren't supposed to _require_ a plugin, and there are strict rules about promoting one. But there may be an acceptable way for us to mention it.

**Comment by scruffian** [comment]
> 6. Plugins
> Themes may only recommend plugins that are hosted on WordPress.org.
>
> Plugins may only be installed by user action, not automatically.
>
> Do not:
> 
> Include zip files or plugins in the theme folder, or download plugins automatically.
> Include plugin functionality.

**Comment by kjellr** [comment]
Ah ok, that's not bad! Then sure, might as well mention that the theme is designed to work alongside the VideoPress plugin. 👍

**Comment by MaggieCabrera** [comment]
We do this on Mayland blocks, it requires a plugin for the gallery block on the homepage. We didn't get any warnings for that, but we didn't mention it on the description. I think it's a good idea to give a heads up to the user before install, but I couldn't find a mention to that in the handbook

**Comment by kjellr** [comment]
Is there any way we can build a fallback? So like: If the VideoPress block exists, use these videos, if not, use a standard video block?

**Comment by scruffian** [comment]
I think that's how the video block works. The problem we have is that when the block is converted to a videopress block the markup changes, so in the patterns we need to have one or the other.

We could use different patterns when Videopress is enabled and not.

**Comment by kjellr** [comment]
Might be worth it? While VideoPress makes a ton of sense for dotcom, maybe not for dotorg. It's not a great experience if someone installs the theme and the patterns don't work without installing a plugin. 😕

**Comment by scruffian** [comment]
The patterns would work, since the videos point to the files hosted on VideoPress. The only difference would be that if they update the files the previews would no longer have the large play button.

**Comment by kjellr** [comment]
Ah ok, I think that's acceptable.

**Comment by jeffikus** [comment]
Does VideoPress filter the video block somehow? I mean, if it doesn't then we should do the check for the presence of VideoPress for the patterns. Otherwise I agree with @kjellr
