### ISSUE TITLE
videomaker: Navigation (if needed)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4656]
The Videomaker navigation looks like this:
<img width="280" alt="Screenshot 2021-09-22 at 14 29 04" src="https://user-images.githubusercontent.com/275961/134352737-0866d059-fb99-445e-948d-da873f1a3177.png">

<img width="441" alt="Screenshot 2021-09-22 at 14 29 18" src="https://user-images.githubusercontent.com/275961/134352733-a1d5f2ab-81c1-408e-a672-854ea9812f11.png">

We need to wait for https://github.com/WordPress/gutenberg/issues/34783 to merge before we can achieve all of this.

**Comment by scruffian** [comment]
This will be fixed by https://github.com/Automattic/themes/pull/4832

**Comment by kjellr** [comment]
I don't think the mockups above are relevant any longer, but I do think we need to make some adjustments to the way the navigation appears on desktop. Currently, the menu items are small and way over on the left edge of the page. This is easy to miss on medium-to-large screens. 

![menu](https://user-images.githubusercontent.com/1202812/141474872-97ab8696-c4c9-4c1c-8700-175eabb0e1e2.gif)

The theme mockups have these aligned more to the center column, so I think we should give that a try:

![Menu Expanded-1](https://user-images.githubusercontent.com/1202812/141475054-680048a8-8d9e-4692-8207-ee89c363956e.jpg)
![Menu Expanded](https://user-images.githubusercontent.com/1202812/141475057-d091e16e-1fc6-4c04-9363-4f180233be92.jpg)

cc @beafialho

**Comment by beafialho** [comment]
> The theme mockups have these aligned more to the center column, so I think we should give that a try:

Definitely, this looks more obvious 👍
