### ISSUE TITLE
videomaker: Block styles (if needed)

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4657]

**Comment by pbking** [comment]
@scruffian or @beafialho are there any block styles needed for this theme?
I perused the figma but didn't really come across anything that seemed to require alternative block styles.

**Comment by beafialho** [comment]
I don't think so, unless this is considered a block style:

<img width="967" alt="Captura de ecrã 2021-10-14, às 18 00 18" src="https://user-images.githubusercontent.com/65220155/137363335-e605ec48-5104-4e16-82b7-5a777d8c64f0.png">

I think I've mentioned this somewhere but can't remember where.

**Comment by scruffian** [comment]
No block styles needed, we can close this.
