### ISSUE TITLE
Geologist: Use identical spacing above and to the left/right of the header. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4687]
**The padding on the top, left, and right of the header should always be identical.** 
Right now there's more space on the top than there is on the sides. This has come up for multiple themes — I think this might be an issue with Blockbase. 

On desktop, please use the larger measurement here (`min(30px, 5vw)`). On small screens you can use the smaller measurement (`min(20px, 5vw)`). The left/right padding here would also apply to the entire page. 

Current:
<img width="1136" alt="Screen Shot 2021-09-22 at 2 31 16 PM" src="https://user-images.githubusercontent.com/1202812/134401399-458a49d3-931e-4b55-bf96-7a348b27f3f3.png">

Preferred:
<img width="1134" alt="Screen Shot 2021-09-22 at 2 31 06 PM" src="https://user-images.githubusercontent.com/1202812/134401406-d1e2bb90-b6bb-4e02-81fe-ad474bf06b1f.png">

**Comment by danieldudzic** [comment]
The current setting for the `padding-top` is `min(30px, 5vw)`. Making spacing identical above and to the left/right of the header would require changing the left and right padding. Is this the correct way of approaching this?

**Comment by kjellr** [comment]
> The current setting for the padding-top is min(30px, 5vw). Making spacing identical above and to the left/right of the header would require changing the left and right padding. Is this the correct way of approaching this?

Yes! On small breakpoints though, we should continue to use `min(20px, 5vw)` like we do now, but also apply that to the top.
