### ISSUE TITLE
Geologist: Tidy up mobile spacing between site header and site description

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4688]
The vertical spacing between the site header and the site description should be decreased to match Quadrat: 

Geologist|Quadrat
---|---
<img width="319" alt="Screen Shot 2021-09-22 at 2 44 11 PM" src="https://user-images.githubusercontent.com/1202812/134403397-81743b02-c586-4f8b-94e7-50f4cb5ec9b7.png">|<img width="413" alt="Screen Shot 2021-09-22 at 2 45 05 PM" src="https://user-images.githubusercontent.com/1202812/134403398-e40462ba-a002-4483-9974-be0230775004.png">

**Comment by danieldudzic** [comment]
I believe this has been fixed now in https://github.com/Automattic/themes/commit/946394db41364c5aa9cb1fe43802d51deb20b1ca

<img width="498" alt="geologist" src="https://user-images.githubusercontent.com/905781/134757105-d76338d9-1765-4f5a-b534-2fc2a6ed28dd.png">
