### ISSUE TITLE
Skatepark: Extra Large Font Size smaller than expected.

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#4689]
## Steps to replicate

I was testing my changes in #4683 and I noticed that Skatepark extra large font size seems wrong. You can see this here https://theamdemo.wordpress.com/2019/06/24/gutenberg-paragraph/ (Skatepark is currently active).

## Result

<img width="958" alt="Screenshot 2021-09-22 at 22 08 13" src="https://user-images.githubusercontent.com/937325/134414664-b24aa94a-1043-4ebe-ae01-ba455ccd7f68.png">

It looks like the font sizes from the design are missing a "Huge" size. It looks like the value for "extra large" has been applied to the "Huge" size.

## Expected

I expected these font sizes:

<img width="202" alt="Screenshot 2021-09-22 at 22 13 02" src="https://user-images.githubusercontent.com/937325/134415261-d764df89-e8b1-41a8-844b-5ce3aa0ae037.png">

**Comment by danieldudzic** [comment]
Is it necessary to include a "Huge" size?
