### ISSUE TITLE
AltoFocus: Images stacking on top of each other

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#47]
(moving from 5021-wpcom-themes)
When you click "load more" on the user site, some of images stack on top of each other. Replicated in Chrome 65.0/Mac High Sierra. The issue was also discussed in this thread: pNEWy-9cT-p2

* Ticket: 1027160-zen
* User's site: https://oscar.hougaz.com/

**Comment by allancole** [comment]
Fixed in: https://github.com/Automattic/themes/commit/ca0e06a765f434dbd84d775d0abc7d0faee163a8

**Comment by alaczek** [comment]
I tested on my sandbox and it's working! \o/

I left a note on the ticket, although it looks like the user switched themes already.
