### ISSUE TITLE
Twenty Nineteen: Inconsistent spacing with infinite scroll

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#470]
## Steps to replicate

1. Apply Twenty Nineteen to a WordPress.com site.
2. Turn on infinite scroll, and set to click-to-load more.
3. Load a few pages of posts.

## Result

The very first post in each "page" of posts sits closer to the one before it than the spacing normally is.

In this screenshot, the spacing between Classic Editor Block and the post meta above it is normal; the Alignments post is the first in the next "page" of posts and is quite a bit closer. I assume there's some `:last-child` or `:last-of-type` styles here we'll need to override. 

![image](https://user-images.githubusercontent.com/177561/50655609-8b8dd900-0f45-11e9-8475-9618c409f866.png)

## Expected

The spacing would be consistent. 

No related report - noticed on my own while merging Core updates.

Note: this may need to be fixed in the Twenty Nineteen-related code and styles in Jetpack, just recording here for now to have the bug logged and so it can be investigated.

**Comment by allancole** [comment]
Got a PR submitted for this here: https://github.com/Automattic/jetpack/pull/11293

Leaving this issue open until the code is merged and released in a future version of Jetpack.
