### ISSUE TITLE
Blockbase + children: Simplify parent/child code now that we have GB support

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4703]
Since https://github.com/WordPress/gutenberg/pull/34354 merged we will have support for child themes in Gutenberg (maybe 11.6). We can probably simplify our child themes quite a bit and remove some code which will be inherited from Blockbase. We can also simplify the scripts for creating new themes.

**Comment by pbking** [comment]
Child themes have been simplified (child-theme.json files removed, etc)

Scripts creating new themes can be tracked in #5010 or in the new [Create Blockbase Child](https://github.com/Automattic/create-blockbase-theme) project.

This tracking issue can be closed.
