### ISSUE TITLE
Blockbase: Separator block height issue

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#4710]
I noticed that when I use a custom color on the separator block its height increases significantly.

## Steps to replicate
1. On a site using Blockbase theme (on WordPress.com) add the separator block to a post or a page content.
2. Note the separator height - it's 1px tall (although in the style picker preview it is much thicker).
3. Go to the settings panel and change the color to any custom color (from the color palette or random).
4. Note how the height of the block changes.

## Expected

I expected that the height of the separator block would not change when I picked a custom color.

Here's a quick video: 
https://cloudup.com/cxGWiqhSJ8m

**Comment by jeffikus** [comment]
@danieldudzic looks like @mikachan approved, I've moved it into the Reviewer Approved column.

**Comment by metabreakr** [comment]
When a separator block is set to dots, the dots aren't aligned in a row: 

<img width="1180" alt="Markup 2022-03-03 at 09 13 16" src="https://user-images.githubusercontent.com/39252765/156605249-9f1b083a-311c-4993-82d4-2aa306c411c7.png">

Tested in Blockbase in both simple and atomic. 

Re-opening this issue, though let me know if you would prefer a new one opened instead.

**Comment by madhusudhand** [comment]
@metabreakr 
Issue is with `width` and `letter-spacing`. 
Block takes default width for Dots style and it is too less for the content with given letter-spacing. Hence they split into multiple lines.

It is worth creating a new issue to track the changes.

**Comment by metabreakr** [comment]
Thanks @madhusudhand , I'll create a new issue.

**Comment by madhusudhand** [comment]
Thanks @metabreakr. Closing this issue.
