### ISSUE TITLE
Blockbase: Transparent background on input elements

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#4718]
## Steps to replicate
1. Insert a group block and pick a background color.
2. Inside the group block add a contact form block.
3. Save & preview. Note that both in the editor and in preview the form input elements have a transparent background and depending on background color can be barely visible.

## Result
Preview:
![image](https://user-images.githubusercontent.com/4550351/134998230-ee517bf2-ba77-4e75-8ee1-c38fe4080442.png)

Editor:
![image](https://user-images.githubusercontent.com/4550351/134998277-4b5f73dd-b98a-4144-af5a-b7bc085a8c56.png)

**Comment by RavanH** [comment]
Hi, is that a Jetpack form? Blockbase itself sets `background: var(--wp--custom--form--color--background);` for input fields globally (in ponyfill.css) but a form plugin may override that with its own styling.

Try a Search block inside a group with background color for example...

**Comment by danieldudzic** [comment]
Hi @RavanH,

I have tested this, and I believe this is not due to an overwrite, but rather, it's Blockbase not handling it gracefully. The padding is off too.

Blockbase explicitly sets the form background to transparent:


<img width="1125" alt="theme_json_-__com_Sandbox" src="https://user-images.githubusercontent.com/905781/136459084-60c3897a-8e2d-43df-a7b0-f3c1150df8e5.png">

2021 has the following style to handle padding:
```
.wp-block-group.has-background {
    padding: var(--global--spacing-vertical);
}
```

**Comment by RavanH** [comment]
@danieldudzic you are right, setting the background to transparent while fixing the foreground and border colors is not very graceful. A form over a black background becomes unusable when the theme foreground color is set to black too. 

Setting either `"background": "var(--wp--custom--color--background)"` or `"text": "inherit"` would make more sense. In the last case, maybe also `"border": { "color": "currentColor", ...` (or --wp--custom--button--border--color as I use in a child theme to match the submit button) 

About padding: Gutenberg now has a user setting for padding(default none) on the Group block.

**Comment by MaggieCabrera** [comment]
I'm more inclined to go with `"background": "var(--wp--custom--color--background)"` since we know it's always going to contrast with the foreground color on the text

**Comment by RavanH** [comment]
Yes, while `"text": "inherit"` is more in line with the form label text color (also inherited) and depends on the user setting a contrasting text color to go with the custom background color on the parent element... Or a semi-transparent background maybe? ;)
