### ISSUE TITLE
Rebalance: Embedded videos displays large thumbnails on post page

### ISSUE THREAD

**Issue by edwinho89** [Automattic/themes#472]
User reported video thumbnails on site used to be similar and same sized as the thumbnails on https://www.youtube.com/ , however found out it has been larger recently.

## Steps to replicate

- "Customize > Content Options > Blog Display" set to "Full post"
- Create a new post
- Add a Youtube link at the start of post. (Example: https://www.youtube.com/watch?v=ssfHW5lwFZg)
- Publish and visit post page

## Result

![image link](https://cldup.com/taTjxTjXIp-3000x3000.png)
image link: https://cloudup.com/coF61yYPiEW

## Expected

Self-hosted site like does not seem to be affected -https://edwintestecommerce.wpcomstaging.com/

* User report: #9233783-hc
* Follow-up ticket: #1688724-zen
* User's site: https://heyfeez.com/
* Test site: edwinhrxtesttheme.wordpress.com/blog/ , edwintestecommerce.wpcomstaging.com

**Comment by edwinho89** [comment]
It seems to have some similarity on #426 , but if you preview http://cld.wthms.co/YFIQKU , the video displays video on smaller thumbnails.

**Comment by laurelfulford** [comment]
This looks like it's fixed for me now, both on my test site and the user's site -- I think it may have been related to this issue (Jetpack responsive videos disabled for themes with Gutenberg support):

https://github.com/Automattic/jetpack/issues/11097

I'm going to close this issue; @edwinho89 it looks like the original ZD ticket is closed. Can you please follow up with the user letting them know it should be okay now? Thanks!

**Comment by edwinho89** [comment]
@laurelfulford It took me awhile, but I've just sent user a message on #1823755-zen . Thanks for checking out - appreciate it! :)

**Comment by laurelfulford** [comment]
Thanks @edwinho89! :)
