### ISSUE TITLE
Blockbase: Under-header margin is incorrect

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4722]
The spacing between a the site header and the page/post title (when there is one title) should be 80px. When you click through from the first post in a blog feed to the post itself, the title should remain in the same place. 

Blog/Archive:

Current|Intended
---|---
![Screen Shot 2021-09-28 at 09 44 04](https://user-images.githubusercontent.com/1202812/135099251-4c1c8a11-c666-4118-ac36-0eac9824cbe4.png)|![Screen Shot 2021-09-28 at 09 42 35](https://user-images.githubusercontent.com/1202812/135099303-8f90f40a-9239-4789-8163-74de8f1172b6.png)

Single Post: 

Current|Intended
---|---
![Screen Shot 2021-09-28 at 09 43 44](https://user-images.githubusercontent.com/1202812/135099387-cae1c008-75e4-4c23-83fa-7638f7b60569.png)|![Screen Shot 2021-09-28 at 09 43 13](https://user-images.githubusercontent.com/1202812/135099532-1a4fbfea-2828-4675-a98b-85f75a66def0.png)

**Comment by kjellr** [comment]
I'm still seeing a vertical jump in the page title position when I visit a single post vs. the archive page. Then title should be in the same spot in both places. (I believe the spacing on the single post page looks more correct to me)

![jump](https://user-images.githubusercontent.com/1202812/135276050-0e11e8f0-eb19-4a99-aca0-5f2b28f37006.gif)

**Comment by scruffian** [comment]
Closed by #4738.
