### ISSUE TITLE
Affinity: Gallery Gutenberg Block Is Wonky When Images Linked To Media Files

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/themes#473]
## Steps to replicate

1. Create a page and add a gallery block through Gutenberg
2. Under Block Settings for gallery, select columns to be 2 
3. Under Block Settings choose Link To - Media File and publish the page
<img width="1520" alt="screen shot 2019-01-04 at 11 05 19 am" src="https://user-images.githubusercontent.com/25575134/50697609-b3963e80-1010-11e9-871a-42f6153c3676.png">
4. Make sure the Affinity theme is active and visit the page on mobile and desktop
5. The images are sizing wonky on a page: 

<img width="1321" alt="screen shot 2019-01-04 at 11 07 56 am" src="https://user-images.githubusercontent.com/25575134/50697717-0a037d00-1011-11e9-9a67-ba2c352f082a.png">

<img width="399" alt="screen shot 2019-01-04 at 11 08 28 am" src="https://user-images.githubusercontent.com/25575134/50697739-17206c00-1011-11e9-896a-c95fa4efc533.png">

## Expected

The images will be sized correctly. 

**More details:**
- When I switch Link To - None or Link To - Attachment Page for the Gallery Block Settings, the images are sized correctly. 

Settings Screenshot:

<img width="1332" alt="screen shot 2019-01-04 at 11 13 02 am" src="https://user-images.githubusercontent.com/25575134/50698027-dd039a00-1011-11e9-9f50-a67e4b101a9d.png">

Screenshot of the page:

<img width="1003" alt="screen shot 2019-01-04 at 11 12 56 am" src="https://user-images.githubusercontent.com/25575134/50698038-e42aa800-1011-11e9-99eb-e5ac30ff6557.png">

Tested with another theme such as Karuna and the gallery block works as expected when the settings is selected for Link To - Media File. Screenshot from Karuna:

<img width="1069" alt="screen shot 2019-01-04 at 11 15 47 am" src="https://user-images.githubusercontent.com/25575134/50698131-2358f900-1012-11e9-98b4-169908c8ae93.png">

This issue might be similar: https://github.com/WordPress/gutenberg/issues/10150

* User report:  #92463035-hc
* User's site: https://ingelaandchris.com/

**Comment by laurelfulford** [comment]
Noting that I can recreate this in Chrome, but not Firefox.
