### ISSUE TITLE
Canard - Blog Posts Block background and height

### ISSUE THREAD

**Issue by silvio-meter** [Automattic/themes#4730]
## Steps to replicate

1. Activate the Canard theme
2. Create a new page and add a Blog Posts Block (grid view).

## Result

The post excerpt shows the black background and there's a height issue as well.

Screenshot: 

![Optional alternative text if image doesn't load](https://groovytestingsite.files.wordpress.com/2021/09/annotation-on-2021-09-28-at-19-28-55.png)
--

##Expected

There shouldn't be any issues with post thumbnails and excerpts while adding the Blog Posts Block.

[What you expected to happen.]

* User report: [#4332912-zen]
* Follow-up ticket: [#4332912-zen]

**Comment by vinnykaur** [comment]
The user followed up about the progress again. For now, I have shared the below CSS with them after adding a Custom Design subscription as a one-time exception:

```
figure.post-thumbnail {
    height: auto;
}
```

**Comment by AtrumGeost** [comment]
Got another report here:

33586519-hc

**Comment by benchilcote** [comment]
Another case here: 34336354-hc - Gave CSS as temporary workaround.

**Comment by thesacredpath** [comment]
Another report here: 34449061-zen Gave CSS as temp workaround.

Follow up: 4824166-zen

**Comment by Greatdane** [comment]
4877496-zd-woothemes

**Comment by jp-imagines** [comment]
Another report in 35151362-hc. Gave user the [CSS workaround](https://github.com/Automattic/themes/issues/4730#issuecomment-967772245).

**Comment by mikachan** [comment]
Fixed by https://github.com/Automattic/themes/pull/5986

**Comment by arunsathiya** [comment]
I have followed up with all customers.
