### ISSUE TITLE
Quadrat: episode pattern regression

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4735]
The episode pattern now shows an extra padding that shouldn't be there:

<img width="1170" alt="Screenshot 2021-09-29 at 09 31 39" src="https://user-images.githubusercontent.com/3593343/135223245-601208ac-886c-4094-8e81-ec2f39d335d8.png">

This is being caused by this rule:

```
.has-background:not(.wp-block-separator) {
    padding: var(--wp--custom--gap--vertical) var(--wp--custom--gap--horizontal);
}
```

I don't know if I agree that everything with background color needs a padding. And if some blocks do, shouldn't this be something that GB does?

**Comment by scruffian** [comment]
There's a GB issue abut this: https://github.com/WordPress/gutenberg/issues/34588

The code was added in https://github.com/Automattic/themes/pull/4629

I'm not 100% sure I like the approach though, and this issue does show some of the problems with it. I'd be happy to remove those lines altogether but I'd be interested to hear from others...

**Comment by MaggieCabrera** [comment]
I'd either remove the lines or add them only to the offending block (in this case group). But I'm more in favor of removing it myself and working something out directly in GB.
