### ISSUE TITLE
Lovecraft: Last gallery item doesn't follow the same styling as the others

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#474]
## Steps to replicate

1. Create a gallery and make sure you have at least 4 images.
2. Set it so it shows on 2 columns
3. Publish the post and check the last image in the gallery. It should be slightly larger because of this rule:

.entry-content *:last-child { margin: 0; }

## Result
It should be something like this:
https://monosnap.com/file/PQ2EVIhDqXd8oFOfzuukrq4zhfV2Ui

Workaround I used:

.entry-content .wp-block-gallery li:last-child{
    margin: 0 16px 16px 0;
}

* User report:1688685-zen
* User's site: https://jimsdiningguides.com/?p=2133

**Comment by mdrockwell** [comment]
Another user reported this issue here: 10676047-hc

**Comment by grvrulz** [comment]
Another user report in 2347012-zen.

**Comment by danieldudzic** [comment]
This has been now fixed in: https://wpcom-themes.trac.automattic.com/changeset/54384
