### ISSUE TITLE
Quadrat: Slight offset in tagline and post meta

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4748]
I was checking Quadrat on mobile and there's a slight offset in tagline and post meta. 

The spacing is also too tight between post meta and the post title.

<img width="362" alt="Captura de ecrã 2021-09-30, às 12 34 59" src="https://user-images.githubusercontent.com/65220155/135448274-71a7a3de-5d43-4c72-90a1-0414123aa297.png">

The misalignment is also happening in larger screens:

<img width="1270" alt="Captura de ecrã 2021-09-30, às 13 02 54" src="https://user-images.githubusercontent.com/65220155/135451790-e9e66023-50da-42cc-851b-169888465177.png">

**Comment by jffng** [comment]
Regarding the meta misalignment: it looks like the theme.css (which shouldn't be enqueued but is on wpcom) is overriding the mask.

<img width="358" alt="Screen Shot 2021-09-30 at 9 55 17 AM" src="https://user-images.githubusercontent.com/5375500/135468860-d973c542-f3a0-4ba1-85af-9610fda5fb42.png">

@beafialho do we want the post date icon to appear like this? 

<img width="765" alt="Screen Shot 2021-09-30 at 9 51 59 AM" src="https://user-images.githubusercontent.com/5375500/135468263-82e3c15d-bc8a-42fe-8a26-dddf9612afae.png">

**Comment by beafialho** [comment]
@jffng the post date shouldn't have an icon.

**Comment by jffng** [comment]
I see, then the pseudoelement can just be hidden via CSS cc @danieldudzic.

**Comment by danieldudzic** [comment]
Committing now.

**Comment by scruffian** [comment]
The gap should be fixed by D67673-code
