### ISSUE TITLE
Color Edits in the Colinear Theme Don't Show in Editor

### ISSUE THREAD

**Issue by ChrissiePollock** [Automattic/themes#4754]
### Quick summary

The customer came in saying _when I change the color of certain text, it doesn't show in editing mode, but does appear when I preview the page._

They are using the Colinear theme. I was able to replicate on my test site.

### Steps to reproduce

1. Use a theme that is not Colinear. 
2. Add a paragraph in the editor.
3. Highlight a word and change the color of the word.
4. Notice that the word color is changed.
5. Switch the theme to Colinear. 
6. Refresh your page in the editor and highlight a word and change the color.
7. Note the changes don't show.

### What you expected to happen

I expected the color of the word to change as it does with other themes.

### What actually happened

The color remains the same in the editor.

### Context

This was reported in 25529272-hc

**Comment by jordesign** [comment]
With the new 'highlight' tool active in Gutenberg I can no longer recreate this - closing as resolved.
<img width="447" alt="Screen Shot 2021-12-10 at 7 04 23 am" src="https://user-images.githubusercontent.com/1842363/145467826-da0c089a-03c0-4ed2-9990-84b1fcc67c61.png">
