### ISSUE TITLE
Quadrat: Vertical position of the post meta + title should be consistent

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4757]
When navigating from the main blog page to a single post, the vertical position of the first title + post meta should be identical. Currently, it is not. The title on single post pages should align to this same vertical position as well. \

The spacing on the single post page is the correct spacing to use in all three cases. 

## Screenshots of the issue currently:

Blog Index: 
<img width="1293" alt="Screen Shot 2021-10-01 at 9 32 38 AM" src="https://user-images.githubusercontent.com/1202812/135628532-d04c6b91-ddd9-4a75-8632-deb880d19f8f.png">

Single Post:

<img width="1294" alt="Screen Shot 2021-10-01 at 9 32 16 AM" src="https://user-images.githubusercontent.com/1202812/135628501-1271f6bc-900f-4f66-9af7-4789cac09da1.png">

Page: 

<img width="1293" alt="Screen Shot 2021-10-01 at 9 32 52 AM" src="https://user-images.githubusercontent.com/1202812/135628559-82298c1a-3ee9-4978-9aa7-212782d67689.png">

(This is also happening in Geologist: https://github.com/Automattic/themes/issues/4758)

**Comment by MaggieCabrera** [comment]
Make this change to Geologist too :D

**Comment by mikachan** [comment]
Fixed with https://github.com/Automattic/themes/pull/4783.
