### ISSUE TITLE
Hemingway Rewritten: Gutenberg: Remove page template for blog posts

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#476]
## Steps to replicate

- Start with a WordPress.com site
- Activate `Hemingway Rewritten` theme
- Open https://wordpress.com/page to create a new page. Notice that the `Page attributes` section appears on sidebar
- Open https://wordpress.com/post to create a new post. Notice that the `Page attributes` section does not appear on sidebar
- Opt-in for WordPress Editor/Gutenberg from the WordPress.com editor
- Open https://wordpress.com/block-editor/post 

## Result

The page attributes are shown. Trying to choose full width template for this blog post fails, as this theme supports the template only for pages.

## Expected

The page attributes are not shown for blog posts on the new WordPress Editor/Gutenberg

## Notes

The page attributes are not affected for pages on this theme, with the new WordPress Editor/Gutenberg

* User report: NA
* Follow-up ticket: 1694323-zen
* User's site: https://oasistrekkers.com/

**Comment by torres126** [comment]
Automattic/wp-calypso#29788

**Comment by arunsathiya** [comment]
Thanks for referencing that issue, @torres126. It does seem to be one that affects all themes with page templates and specific to Gutenlypso. Not a theme specific one. I am closing this report in favour of the tracker at https://github.com/Automattic/wp-calypso/issues/29788
