### ISSUE TITLE
Affinity: Add block CSS to the editor so that colors work as expected

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#4763]
## Steps to replicate

Details of the issue in https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-925353089

1. Confirm that the issue exists with Affinity as well.
2. Apply the Rebalance fix and see if that solves the issue.

## Related Issues:

https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-925353089
https://github.com/Automattic/themes/pull/4756

**Comment by danieldudzic** [comment]
Hmm, I can't seem to replicate the issue in Affinity 🤔

**Comment by mikachan** [comment]
I can replicate this, but I can't see which stylesheet the colours are coming from. They're not in `blocks.css`, they're in the inline `global-styles-inline-css`.  Do these inline styles need to be copied into the editor stylesheet (or maybe just the ones for colours)?

**Comment by scruffian** [comment]
I believe this will be fixed by https://github.com/WordPress/gutenberg/pull/35514.
