### ISSUE TITLE
Gateway: Add block CSS to the editor so that colors work as expected

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#4764]
## Steps to replicate

Details of the issue in https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-927963963

1. Confirm that the issue exists with Gateway as well.
2. Apply the Rebalance fix and see if that solves the issue.

## Related Issues:

https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-927963963
https://github.com/Automattic/themes/pull/4756

**Comment by danieldudzic** [comment]
Same as with Isola, I'm missing the **Text color** option when Gateway is active - and I can't replicate the issue.

<img width="790" alt="Edit_Page_‹_This_is_a_site_title_super_long_—_WordPress_com" src="https://user-images.githubusercontent.com/905781/136391419-aecd837e-f07a-4930-bcfe-de43425d16c5.png">

**Comment by scruffian** [comment]
I believe this will be fixed by https://github.com/WordPress/gutenberg/pull/35514.
