### ISSUE TITLE
Lovecraft: Add block CSS to the editor so that colors work as expected

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#4766]
## Steps to replicate

Details of the issue in https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-930541164

1. Confirm that the issue exists with Lovecraft as well.
2. Apply the Rebalance fix and see if that solves the issue.

## Related Issues:

https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-930541164
https://github.com/Automattic/themes/pull/4756

**Comment by danieldudzic** [comment]
For some reason I can't access the **Text Color** setting when testing with Lovecraft - and I can't replicate the issue when using the 'Highlight' or 'Color' block setting.

**Comment by scruffian** [comment]
I believe this will be fixed by https://github.com/WordPress/gutenberg/pull/35514.
