### ISSUE TITLE
Baskerville 2: Add block CSS to the editor so that colors work as expected

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#4767]
## Steps to replicate

Details of the issue in https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-930612799

1. Confirm that the issue exists with Baskerville 2 as well.
2. Apply the Rebalance fix and see if that solves the issue.

## Related Issues:

https://github.com/Automattic/wp-calypso/issues/54990#issuecomment-930612799
https://github.com/Automattic/themes/pull/4756

**Comment by scruffian** [comment]
I believe this will be fixed by https://github.com/WordPress/gutenberg/pull/35514.
