### ISSUE TITLE
Twenty Fifteen: Logo not displaying on Atomic

### ISSUE THREAD

**Issue by jessestu** [Automattic/themes#477]
## Steps to replicate

I'm using Chrome, 71.0.3578.98.

1. Activate Twenty Fifteen on an Atomic site.
2. Go to Customize → Site Identity, select a logo.

## Result

The logo does not show up in the theme. Screenshot: 
![screen shot on 2019-01-06 at 21 33 02](https://user-images.githubusercontent.com/32908730/50747703-f61b6f00-11fa-11e9-90e8-e41d0c2e20d4.png)

## Expected

I expected the logo to show up like it does on the simple site.

Screenshot: 
![screen shot on 2019-01-06 at 21 37 36](https://user-images.githubusercontent.com/32908730/50747770-53afbb80-11fb-11e9-863a-a133f7520832.png)

_Notice this option is showing the Logo section twice, and notice the second time the language of the button is different than the top variation of the option._

* User report: 9251047-hc
* Follow-up ticket: 1697029-zen
* User's site: https://salimaskitchen.com/

**Comment by laurelfulford** [comment]
Thanks for this report @jessestu -- I think I messed something up when merging the latest changes into the theme late last week. Taking a look at this now!

**Comment by laurelfulford** [comment]
This should be fixed in r52851-wpcom-themes.

Theme updates are pushed to AT sites twice a week, so this should be fixed on https://salimaskitchen.com/ in a day or two. I'll keep an eye on the site and will follow up when it's fixed there; I'll leave this issue open in the meantime.

**Comment by jessestu** [comment]
Thank you, @laurelfulford! I last let the user know this would be resolved when this bug gets addressed, so all is lined up now for you to send the confirmation when it pushes.

And if you'd rather me do it, ping me and let me know it's done and I'll take it from there!

**Comment by jessestu** [comment]
@laurelfulford, in checking over open cases before my weekend, I see the user got further help from another HE and ended up switching themes, so I will go ahead and close this issue as they won't need a followup. Thank you!
