### ISSUE TITLE
Maxwell: Follow blog widget button styles

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#4782]
The button within the Follow blog widget now has the class **wp-block-button__link**, this results in the button styles on the block being changed, the text is now illegible.

I'm not sure if this class being added was intentional, if it was the theme should have CSS updated for this button.

Related issue on another theme:

https://github.com/Automattic/themes/issues/4580

## Steps to replicate

* Add the Follow blog widget to the site
* View button styles on site

## Result

The class **wp-block-button__link** changes the background color, making the text illegible.

![Screen Shot on 2021-10-04 at 13:50:08](https://user-images.githubusercontent.com/10353785/135899662-82ff22bc-cf1d-4d52-9fe9-4ecfc5d70749.png)

## Expected

Previously the button looked like this:

![Screen Shot on 2021-10-04 at 13:50:32](https://user-images.githubusercontent.com/10353785/135899674-271c8430-d680-4662-a82e-38d94747cdf8.png)

* User report: 31684031-hc

Used this to make the text legible:

```
/* Subscribe button */

#subscribe-submit .wp-block-button__link {
  color: #fff;
}
```

**Comment by tavilla61** [comment]
Another example in this ticket: #4426895-zen. 
CSS fix was sent to the user.

**Comment by jordesign** [comment]
Closing in favour of https://github.com/Automattic/themes/issues/4580 where things are being tracked centrally
