### ISSUE TITLE
Theme: Twenty Twenty not respecting custom font-sizes in Paragraph Block

### ISSUE THREAD

**Issue by inaikem** [Automattic/themes#4792]
### Quick summary

- This appears to be a theme-related bug for Twenty Twenty on Simple sites only.
- When setting a custom font size in a paragraph block on the above theme, setting the theme to a "small" font such as 18px results in the font rendering as 13px on previewed/live content.
- On Atomic/self-hosted sites, the font size set in the editor is respected.

### Steps to reproduce

1. Create/edit a page on a Simple site.
2. Add a paragraph block.
3. Set the block's font size to `18px`. 
4. The block's "Font size" dropdown will change to "Small".
5. Save/preview the page.

### What you expected to happen

I expected the set font size to be respected.

### What actually happened

The font size appears much smaller than set: 13px vs 18. Screenshot:
&nbsp;

![Markup on 2021-10-05 at 13:19:09 copy](https://user-images.githubusercontent.com/66711744/135964866-2ff74420-67ec-477f-9ddb-40efd8a8f970.png)

### Context

4348533-zen

### Theme-specific issue?

Twenty Twenty

### Available workarounds?

No but the platform is still usable

### Workaround details

I provided the user with this workaround for their homepage's blocks only:

```
body.home .entry-content .wp-block-column .has-small-font-size {
    font-size: 18px!important;
}
```

**Comment by jeffikus** [comment]
@zdenys - this seems to be a very old issue which I tested now and it works for me; screenshots below:

**Editor - size set to small 18px**
<img width="898" alt="Screenshot 2022-04-22 at 13 27 31" src="https://user-images.githubusercontent.com/937325/164764763-36c41a20-02f2-4cde-a2c5-11221ea8ce36.png">

**Frontend - computes to 18px**
<img width="643" alt="Screenshot 2022-04-22 at 13 27 54" src="https://user-images.githubusercontent.com/937325/164764769-67266704-160d-4395-bc06-c9f9d0fc98e1.png">

Let me know if I'm misunderstanding, and reopen the issue.
