### ISSUE TITLE
Libretto: Site Title not Hidden on Mobile

### ISSUE THREAD

**Issue by jacoswan** [Automattic/themes#480]
## Steps to replicate
1. Go to Customize > Site Identity add a site title and a tag, and untick `Display Site Title and Tagline`
2. Expected behavior, as shown in Customizer, is that both site title and tagline are hidden. 
3. In Customizer, select mobile view to confirm this works as expected. 
4. Save and view on the front end. Reduce viewport to less than 640px. 
5. Notice that the site title is now visible next to the hamburger menu in the menubar. 

Customizer view (Note there's nothing inline with the hamburger menu icon):

<img width="384" alt="screenshot 2019-01-08 at 14 53 34" src="https://user-images.githubusercontent.com/15178758/50831943-44448580-1355-11e9-85dc-f656c251562b.png">

Front end (notice "jCo Personal" appears next to hamburger menu icon):

<img width="546" alt="screenshot 2019-01-08 at 14 53 52" src="https://user-images.githubusercontent.com/15178758/50831950-50304780-1355-11e9-986f-eb442ee8f12d.png">

## Result
Site title is hidden in all widths in Customizer, but on the front end site title appears when width is less than 641px.

## Expected
Site title should be hidden in all widths both in the Customizer and on the front end. 

* User report: [shortlink to chat/forum thread/ticket, ie #7976269-hc]
* Follow-up ticket: https://woothemes.zendesk.com/agent/tickets/1701065
* User's site: http://lilyllewellyn.com (issue occurs site wide)

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
