### ISSUE TITLE
Quadrat: open in a new tab not working for menu links

### ISSUE THREAD

**Issue by escapemanuele** [Automattic/themes#4813]
## Steps to replicate

- Checked “Link Target” in advanced menu properties in the Customizer: https://d.pr/i/tqgq4Z

![image](https://user-images.githubusercontent.com/52076348/136774354-d8dfbda2-7c36-4ae1-89c5-362667a08947.png)

- Checked “Open link in a new tab” in the menu element: https://d.pr/i/8qxhI5

![image](https://user-images.githubusercontent.com/52076348/136774374-e36a0815-70a7-411a-a25a-ceb13f110ef9.png)

## Result

- Clicking on the link, the linked page opens in the same tab
- With a different theme this does not happen

## Expected

Setting a menu item to open in a new tab should result in the linked page opening in a new tab

* User report: 4366104-zd-woothemes

**Comment by mikachan** [comment]
I can replicate this in Blockbase & Co and I think it's a Gutenberg issue, but I don't know Gutenberg well enough to know how to debug this properly.

The menu in the header template doesn't render with a `target="_blank"` or a `title`:

![image](https://user-images.githubusercontent.com/1645628/137041242-da264f69-b358-4b21-a782-af0e644a76c2.png)

However, if I add a Navigation block through the editor and specify a menu, the links will be added as individual blocks, like this:

```
<!-- wp:navigation -->
<!-- wp:navigation-link {"label":"Home","type":"page","id":8,"url":"/home/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"FAQs","type":"page","id":127,"opensInNewTab":true,"url":"/faqs/","title":"FAQTitle","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Cover Block Spacing","type":"page","id":103,"url":"/cover-block-spacing/","kind":"post-type","isTopLevelLink":true} /-->

<!-- wp:navigation-link {"label":"Group Border Test","type":"page","id":33,"url":"/group-border-test/","kind":"post-type","isTopLevelLink":true} /-->
<!-- /wp:navigation -->
```

This markup includes `opensInNewTab` and `title` in the navigation-link blocks. With these, the missing attributes are rendered correctly:

![image](https://user-images.githubusercontent.com/1645628/137041347-98730eb9-928d-43b0-b475-a5da1d6be28d.png)

So I'm guessing this is a GB issue with the way it renders a menu either specified by location or whenever a menu is rendered with only the `<!-- wp:navigation ...` markup on its own. I'd appreciate someone else taking a look too in case I've misunderstood!

**Comment by danieldudzic** [comment]
@mikachan I have tested this with [Tove](https://wordpress.org/themes/tove/) and the blank target link works fine. I have no idea what in Blockbase might be causing this, though.

**Comment by mikachan** [comment]
Ah OK. I've just tried with Tove too but it looks like that theme doesn't register any menu locations. This means when you go to add the menu to the header, you have to manually add the menu items in the block editor, which means it adds each navigation-link block individually with the `opensInNewTab` etc attributes as above (with individual `wp:navigation-link` blocks with all the required attributes).

I've also tried this with [Mebae](https://wordpress.org/themes/mebae/), which adds the menu exactly the same as Blockbase. That includes just the `wp:navigation` block with `"__unstableLocation":"primary"`. There is a primary menu location registered with `register_nav_menus()`. This doesn't add the target or title attributes on the front end either, which is what makes me think it's a GB issue.
