### ISSUE TITLE
Geologist: Allow long titles to wrap the same way on post pages and on the index

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4815]
Quadrat has[ had a change](https://github.com/Automattic/themes/pull/4796) to address long titles and other spacing issues.

The same should be replicated for Geologist.

**Comment by MaggieCabrera** [comment]
I don't think we need it for geologist, since its singular template doesn't have a wide aligned featured image like quadrant does.

**Comment by pbking** [comment]
Cool, I didn't realize there was a difference there but I see what you mean.  Thanks @MaggieCabrera .
