### ISSUE TITLE
Business: Button block's background color not respected, is always set to blue

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#482]
## Steps to replicate

- On a Business site, add a button block
- Choose a background color for it

<img width="1424" alt="screenshot 2019-01-10 at 11 37 01" src="https://user-images.githubusercontent.com/18581859/50949414-12a1fa80-14cc-11e9-98ea-6c01ee0e7cd3.png">

## Result

The button's background color appears in blue.

<img width="526" alt="screenshot 2019-01-10 at 11 31 34" src="https://user-images.githubusercontent.com/18581859/50949387-fdc56700-14cb-11e9-97ac-c4bf12e742cc.png">

## Expected

The chosen background color appears

The block works fine with other themes like Twenty Nineteen, Dara, Sela

<img width="721" alt="screenshot 2019-01-10 at 11 31 04" src="https://user-images.githubusercontent.com/18581859/50949380-f9994980-14cb-11e9-9452-65d0c1df13fc.png">
<img width="384" alt="screenshot 2019-01-10 at 11 30 40" src="https://user-images.githubusercontent.com/18581859/50949381-f9994980-14cb-11e9-8ac2-93ad4304b371.png">
<img width="450" alt="screenshot 2019-01-10 at 11 29 53" src="https://user-images.githubusercontent.com/18581859/50949382-f9994980-14cb-11e9-9448-f264f1daad45.png">

* User report: #9352811-hc
* Follow-up ticket: NA (I haven't offered to followup)
* User's site: `thepumpmeeting.com`

**Comment by mendezcode** [comment]
This has been fixed as part of the [editor styles rewrite](https://github.com/Automattic/default-small-business-theme/commit/b39bb05a191fd2177c8e547089843dcf6cd40806).

**Comment by rinazrina** [comment]
Reopening this as I got a similar report, and I can reproduce this on my test site. 

Choosing any other default theme color is not respected. The button background color is always set to blue/purple-ish and the text color is white. The color is changed on the editor, but not on the published version. 

The workaround is to set a custom color and choose a slightly different hex code. 

User report: #35200688-hc
