### ISSUE TITLE
Blockbase: Broken margins for buttons in a group.

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4842]
## Steps to replicate
When buttons are in a group block their alignment is off:
<img width="544" alt="Screenshot 2021-10-14 at 18 49 59" src="https://user-images.githubusercontent.com/275961/137370153-a2036c9c-6ba5-4afc-9d2a-be17befdd6c6.png">

This is probably caused by this line:
```
.wp-block-group :first-child {
	 margin-top: 0;
}
```

This might not be needed since we added block gap fixes to Gutenberg.

**Comment by pbking** [comment]
Seems to only be a thing in the editor...

<img src="https://user-images.githubusercontent.com/146530/137379012-ee30867b-d9b3-421d-93df-9ce491ee9195.png" width=200>

<img src="https://user-images.githubusercontent.com/146530/137379083-572c934f-8b86-4449-96da-900efca67a30.png" width=200>

and removing it fixes things there:

<img src="https://user-images.githubusercontent.com/146530/137380087-9cca6199-1f39-4efa-ab20-3122f5605ec7.png" width=200>
 
but highlights the inconsistency in editor and view

<img src="https://user-images.githubusercontent.com/146530/137380167-fdb20672-cb57-426a-98a6-5a08e2a687c3.png" width=200>

**Comment by pbking** [comment]
Actually I wasn't on the lastest Gutenberg.  Updating and I no longer see the issue (with the `margin-top` still in place).  Though I do still see a discrepancy between editor and view...

Editor:
<img src="https://user-images.githubusercontent.com/146530/137381008-72477905-93a5-42d1-806c-d5f963b931e6.png" width=200>

View:
<img src="https://user-images.githubusercontent.com/146530/137381043-dae9c126-35b4-4e4b-a9b2-2dfac71cb944.png" width=200>

And I'm not sure what the expectations are for the paragraphs in the group.  Are margins expected at the top/bottom in the screenshot or no?

**Comment by pbking** [comment]
This is with NONE of the styles for paragraphs in _text.scss and seems to be the correctest to me...

<img src="https://user-images.githubusercontent.com/146530/137382983-84ba0884-1243-4779-a198-7b349fb6959e.png" width=200>

**Comment by scruffian** [comment]
I also don't see it on the latest GB. My preference would also be to remove the extra styles if they aren't needed.
