### ISSUE TITLE
Apostrophe 2: Vimeo video is overlapping the images

### ISSUE THREAD

**Issue by yashitamittal11** [Automattic/themes#485]
## Steps to replicate

Add a Vimeo video and then some images below it. The images and the video overlap each other.
We have been able to replicate this on Safari browser on iPhone 5.

* Screenshots- 
![screenshot 2019-01-12 at 9 08 32 am](https://user-images.githubusercontent.com/21078987/51068834-d8f6fe00-1649-11e9-8048-913adca0682f.png)

![screenshot 2019-01-12 at 9 08 47 am](https://user-images.githubusercontent.com/21078987/51068838-ea400a80-1649-11e9-81fd-16495a70a479.png)

## Result

The Vimeo video and the images overlap each other on Safari browser on iPhone 5.

## Expected

The video and images should not overlap.

* User report:- #1693803-zen
* Follow-up ticket: same
* User's site: https://edwinhrxtest.wordpress.com/
* Slack link: _[internal Slack link redacted]_

**Comment by laurelfulford** [comment]
I can't replicate this issue in Safari on my computer or phone (iPhone 6). But I wonder if this was incidentally fixed with this issue:

https://github.com/Automattic/jetpack/issues/11097

@yashitamittal11 can you verify if you're still seeing this issue? Thanks!

**Comment by yashitamittal11** [comment]
I am also not able to replicate this issue on my iPhone 6. I asked for help on channels, but it seems nobody has iPhone 5 to test this out. I have followed up with the user to check if this issue is resolved for them. I will update this thread once I receive a reply.

**Comment by yashitamittal11** [comment]
The video is not overlapping now. But the images are overlapping each other.
The same is happening with the other set of images further down on the page.

![img_8812](https://user-images.githubusercontent.com/21078987/52546442-4df25a80-2de5-11e9-95f3-7a104545dbb5.PNG)

**Comment by cathymcbride** [comment]
Closing. iPhone 5's represent less than 2% of active iphones.
