### ISSUE TITLE
Blockbase: ponyfill p margins rules create unexpected behavior

### ISSUE THREAD

**Issue by RavanH** [Automattic/themes#4851]
The following rule in ponyfill.css which creates unexpected top margins for paragraphs:
```
p.wp-block.wp-block-paragraph, *[class^="wp-container"] > * + p, p {
    margin-top: 1em;
    margin-bottom: 1em;
}
```

## Steps to replicate

Create a new post with Title and three paragraphs. Then place one of the paragraphs inside a group block and move it to different positions in respect to the other two paragraphs.

## Result

When the group block is in position two or three, the margins are different from when in first position or when no group block is used:

![top-margin-ponyfill](https://user-images.githubusercontent.com/1184853/137483905-73565dd2-7584-4342-9bc6-c4c88c41425e.gif)

## Expected

Margins to be constant, as happens when the above ponyfill style rule is disabled:

![top-margin-default](https://user-images.githubusercontent.com/1184853/137483970-517de1d5-24e1-48dd-89f0-af6e5dc69f90.gif)

**Comment by RavanH** [comment]
Another example of unexpected behavior caused by these rules:
Add a column block with two columns and a title in each column. Now place a 10px spacer above the title in the second column. You'd expect the difference between the two titles to be 10px, but it is much more than that: 10px + var(--wp--custom--gap--vertical) = 40px.

With ponyfill rule `.wp-block-column :first-child, .wp-block-group :first-child { margin-top: 0; }` enabled:
![column-titles-ponyfill](https://user-images.githubusercontent.com/1184853/137486914-e5221425-88b8-4fa9-ae4d-f7d05e0e5ded.png)

Without that rule, the difference is the expected 10px:
![column-titles-default](https://user-images.githubusercontent.com/1184853/137486984-daec73eb-9bce-4db3-a680-9239b38ee1c4.png)

**Comment by scruffian** [comment]
We removed this code so I think we can close this. Thanks for reporting.

**Comment by RavanH** [comment]
Ah ok... I had not verified the latest dev version. Great :)

**Comment by RavanH** [comment]
Ah no, hang on...

The rule
```
p.wp-block.wp-block-paragraph,
*[class^="wp-container"] > * + p,
p {
	margin-top: 1em;
	margin-bottom: 1em;
}
```
is still there in trunk. This one is responsible for the effect in the first example...

I've updated the original report (title and content) to reflect the remaining issue.

**Comment by pbking** [comment]
Related to [comments](https://github.com/Automattic/themes/pull/4845#issuecomment-943776207) on [this](https://github.com/Automattic/themes/pull/4845#issuecomment-944300092) issue.
