### ISSUE TITLE
 Blockbase & Child themes: Logo size option 

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#4852]
### What

Ideally there would be a way to increase the logo size which is set at `64px`.

### Why

Blockbase (parent theme), Quadrat (child theme), and potentially future Blockbase child themes set the logo height to 64px. This could be considered small, some users may want larger logos.

### How

Perhaps a Customizer option.

For Blockbase & Quadrat CSS can be used for now.

```
/* Site logo */

.wp-site-blocks .site-header .wp-block-site-logo a>img {
	height: 100px;
}
```

Before:

![logo1](https://user-images.githubusercontent.com/10353785/136075528-ac687cc9-d884-419f-bbee-f67e1c5bfc82.png)

After:

![logo2](https://user-images.githubusercontent.com/10353785/136075548-0000bb15-b264-434c-b03f-e781548061ff.png)

**Comment by kosiew** [comment]
Hi @mikeicode ,

Thanks for reporting this and the detailed steps.
Triaging for developers' further investigation.

**Comment by formosattic** [comment]
+1 for Russell, 4604186-zd-woothemes

CSS fix:

```
/* hide site log */
.wp-site-blocks .site-header .wp-block-site-logo a > img {
    visibility: hidden;
}
 
/* replace site logo*/
.wp-site-blocks .site-header .wp-block-site-logo a {
    background: url('https://IMAGE-URL.png');
    background-size: contain;
    background-repeat: no-repeat;
    display: block;
    height: 30px;
    width: 222px;
}
```

**Comment by pbking** [comment]
The logo can be resized in the Site Editor.  If resizing is needed but the Site Editor is not available then the CSS workaround noted above would be the only option.  This isn't something we are able to allow customizations for in a Blockbase/Universal theme.
