### ISSUE TITLE
Independent Publisher 2: Dark Palettes Affect Visited "Continue Reading" Buttons

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/themes#486]
## Steps to replicate

1. Activate "Independent Publisher 2" theme
2. Select in Customize - Colors & Backgrounds - Palettes

<img width="512" alt="screen shot 2019-01-12 at 10 52 28 am" src="https://user-images.githubusercontent.com/25575134/51075353-3d20be80-1658-11e9-8976-d55568ac06fe.png">

3. Choose the first or second dark palette

<img width="382" alt="screen shot 2019-01-12 at 10 53 08 am" src="https://user-images.githubusercontent.com/25575134/51075359-490c8080-1658-11e9-81fe-efcf8fddce0b.png">

4. Under "Content Options", select Blog Display - Post Excerpt:

<img width="575" alt="screen shot 2019-01-12 at 10 54 08 am" src="https://user-images.githubusercontent.com/25575134/51075370-6fcab700-1658-11e9-9385-0cbf86a7d9f7.png">

5. Go to blog archive page and click on "Continue Reading" under a blog post and then return back to a blog archive page

## Result

The text on visited "Continue Reading" button got blended in with the button background:

<img width="1025" alt="screen shot 2019-01-12 at 10 56 23 am" src="https://user-images.githubusercontent.com/25575134/51075397-bf10e780-1658-11e9-9fff-dfa595b68e7f.png">

## Expected

The text on visited "Continue Reading" remains visible.

## Note

The issue happens only with first two dark palettes. 

* User report: #1712133-zen
* User's site: https://theerrantmoon.com/

Please note I added some custom CSS to user's site to fix the issue temporarily.

**Comment by laurelfulford** [comment]
This has been committed to WP.com in r53320-wpcom-themes.

It looks like the original ZD ticket has been closed; @katinthehatsite can you please follow up with the user if needed? Thanks!

**Comment by katinthehatsite** [comment]
Created and sent a follow-up ticket 1787755-zen
