### ISSUE TITLE
Blockbase header layout gathers to the left.

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#4860]
Many of the Blockbase headers layout seems off.

Quadrat:
![image](https://user-images.githubusercontent.com/146530/137775401-f1b18797-ccdc-4114-90ed-9a0ab585a232.png)

Blockbase:
![image](https://user-images.githubusercontent.com/146530/137775464-16a9d86e-2c23-4dff-a0c5-3fb416d25d23.png)

This seems to be caused by the addition of `width: 100%` [here](https://github.com/WordPress/gutenberg/blame/024f7eab3359ebd355873ae57534cbba710c681c/packages/block-library/src/navigation/style.scss#L515) made in [this change](https://github.com/WordPress/gutenberg/pull/35568).

**Comment by tinjure20** [comment]
In my Quadrat testing, I reproduced what @pbking described above.  In addition to header, I also notice pagination layout problem on index page too but not on single page layout. These problems appeared immediately after I updated GB to recent v11.7.

Quadrat:
![screenshot-quadrat](https://user-images.githubusercontent.com/59660253/137799059-2a1a24cd-f25b-49de-8365-c93e603b339c.png)

**Comment by scruffian** [comment]
The pagination issue is solved by https://github.com/Automattic/themes/pull/4805

**Comment by pbking** [comment]
Comments [here](https://github.com/WordPress/gutenberg/issues/35742#issuecomment-946744435) as to how to create this layout as-is leveraging nested rows.

2022 does the same and this looks like the best way to address this.

**Comment by scruffian** [comment]
This is fixed in https://github.com/WordPress/gutenberg/pull/35913
