### ISSUE TITLE
Blockbase: npm run create:child throwing error

### ISSUE THREAD

**Issue by jshwlkr** [Automattic/themes#4875]
## Steps to replicate

On OSX 10.15.7
After grabbing the theme folder from the repo I try to run `npm run create:child themetest`. 

## Result

It appears something about `node-sass` is causing the process to error. Not sure if this is on my end or not, I can't tell what I'm looking at anymore. 
[2021-10-19T19_19_27_070Z-debug.log](https://github.com/Automattic/themes/files/7376151/2021-10-19T19_19_27_070Z-debug.log)

**Comment by jshwlkr** [comment]
I, seemingly, fixed this issue by bumping node-sass to 6 in the generated child theme package.json.

**Comment by kathrynwp** [comment]
Glad you got it fixed, closing this.
