### ISSUE TITLE
Hever conflict with Code Snippet Plugin?

### ISSUE THREAD

**Issue by apload-gmbh** [Automattic/themes#4880]
## Steps to replicate
Our customer uses the Word Press theme hever: www.mvn-info.ch and we should implement some script for a cookie consent tool. To implement we use the WP Plugin Code Snippet https://wordpress.org/plugins/code-snippets/, 
![grafik](https://user-images.githubusercontent.com/80830352/138123090-167d477f-e971-4461-9684-c9fbff3ad407.png)

## Result

but the script of the cookie consent tool is not rendered / no in the html code.

## Expected

according our investigations probably Hever doesn't support to use Code Snippet. Is that possible

* User report: [shortlink to chat/forum thread/ticket, ie 12345-hc]
* Follow-up ticket: [shortlink to ticket, ie 12345-zen]

**Comment by jordesign** [comment]
Hi @apload-gmbh 
I don't expect the theme in use would effect whether or not a Code Snippet would be added to the site. Are you able to test some further scenarios to see if the problem arises in other cases?

* Can you include *other* code snippets (like the demo snippets from the plugin)
* Does the issue with the Cookies snippet happen with other themes active?

I'm going to close this issue (for now) as it seems unlikely the plugin/snippet would be effected by the theme - but feel free to reopen with more details if you continue having problems.

**Comment by apload-gmbh** [comment]
The reason was finally another Plugin for AMP and not your Theme Hever.
