### ISSUE TITLE
Videomaker: Trailing slash when no category set

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4882]
## Steps to replicate

When posts don't have a category, the slash between category and date looks kind of weird:
<img width="552" alt="Screenshot 2021-10-20 at 20 41 29" src="https://user-images.githubusercontent.com/275961/138161217-658a4007-138c-4e31-a8f8-76c4f444704b.png">

Any thoughts on this one @beafialho

**Comment by beafialho** [comment]
If only the post date is showing, the slash shouldn't be there.
