### ISSUE TITLE
Videomaker: Demo videos not loading

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4883]
## Steps to replicate
A couple of the demo videos for Videomaker, which are used in patterns, aren't loading:
<img width="610" alt="Screenshot 2021-10-20 at 20 45 01" src="https://user-images.githubusercontent.com/275961/138161362-3045e6ec-0641-4c27-aaee-4170639298ab.png">
<img width="634" alt="Screenshot 2021-10-20 at 20 44 56" src="https://user-images.githubusercontent.com/275961/138161364-7531b8be-3d53-46b3-933f-7b0eb82484f6.png">

We'll probably need to try adding them again from pexels (see pdmazJ-O-p2)

**Comment by pbking** [comment]
Not sure what to review here...

These are showing up in the pattern browser:
<img src="https://user-images.githubusercontent.com/146530/138900370-6bb5e3b6-9f9b-4e56-bebf-1608db1bc4e7.png" width=300>

and also look fine on the demo site (referenced in description).

**Comment by scruffian** [comment]
Thanks, this was closed by https://github.com/Automattic/themes/pull/4901
