### ISSUE TITLE
Videomaker: Playback button

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4884]
## Steps to replicate

On this (pdmazJ-O-p2) demo site the playback button is big:
<img width="541" alt="Screenshot 2021-10-20 at 20 47 49" src="https://user-images.githubusercontent.com/275961/138161795-a2fc0cb8-db8a-4cd8-88c7-300a2ba9ee94.png">

However on WordPress.com it looks like this:
<img width="744" alt="Screenshot 2021-10-20 at 20 49 07" src="https://user-images.githubusercontent.com/275961/138161879-1e1bb5de-fb88-44ab-9fb5-b1b484a2d39a.png">

I'm not sure of the reasons for the difference but it would be good if it looked like the first example.

**Comment by kjellr** [comment]
This is a VideoPress bug. It was addressed once, but could still be refined: https://github.com/Automattic/videopress/pull/389

**Comment by scruffian** [comment]
Actually there's something else going on here...

The patterns use core video blocks, so they don't display these blocks because they aren't VideoPress videos.

I can see several options here:
1. Just use the core video block and accept that we won't see the big playback button
2. Use VideoPress videos, which means that we have to reference the hosted video files in the patterns we submit to dotorg. That's something we've been avoiding as we don't like to reference external sources in themes.
3. Use core videos blocks unless VideoPress is installed, in which case use VideoPress videos. This still requires us to references external videos in the theme, but only when we are confident that VideoPress is installed already.

@beafialho what do you think?

**Comment by kjellr** [comment]
This theme will be positioned (on WP.com at least) as a pair to VideoPress, so I think it makes sense to use VideoPress embeds there at the very least. 

I don't think it's necessarily an issue to link to the external VideoPress files, since they're basically just embeds. The videos in here are not promotional in nature, so I don't think they'd run afoul to the theme review guidelines.
