### ISSUE TITLE
Orvis: tiled gallery images stacked in portfolio projects (block editor)

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/themes#489]
The tiled gallery layout does not work on portfolio projects when the block editor is enabled.

## Steps to replicate

Enable the new editor and the portfolio content type.

1. Go to My Sites > Portfolio > Add
2. Click `+` to add a new block
3. Select Tiled Gallery
4. Select Media Library (or upload) and choose several images
5. Click insert
6. Publish
7. View the project on the front end

## Result

Tiled gallery images are stacked on top of each other in portfolio projects. They do not use the tiled gallery layout.

![orvis-tiled-stack](https://user-images.githubusercontent.com/11627765/51128457-ce8e5d00-181f-11e9-8cdc-c71f4aba60d1.jpg)

_Note: The tiled gallery layout does work on portfolio projects when the classic editor is enabled (no layout issues in posts or pages when using the classic editor)._

## Expected

The images to be displayed in the tiled gallery format in varying shapes and sizes — as displayed in the editor:

![orvis-tiled-editor](https://user-images.githubusercontent.com/11627765/51128430-b9193300-181f-11e9-8c32-71936e9e9eb1.jpg)
_Tiled gallery in the editor (portfolio project)_

## Browsers
Issue occurs in all browsers.

* User report: https://en.forums.wordpress.com/topic/orvis-theme-tile-gallery-gallery-images-not-working/
* User's site: https://testsitetravelcabral.wordpress.com/portfolio/test-page/

**Comment by gemmagarner** [comment]
Another report in [this thread](https://en.forums.wordpress.com/topic/getting-slideshows-to-work-with-orvis-theme/).

**Comment by laurelfulford** [comment]
Changed the priority, since Orvis doesn't have Gutenberg support built in.

I'm leaning towards `wontfix` for this one -- Orvis changes the layout of portfolio projects with JavaScript, separating the text and images. This kind of really opinionated behaviour in a theme doesn't really work well with Gutenberg.

**Comment by crunnells** [comment]
This issue is a likely #wontfix candidate because Orvis _doesn't_ have block editor support, and we have no plans to add it at this time.

**Comment by alaczek** [comment]
Yep, agreed. The special treatment in Orvis is... special :) Because of this unfortunately it won't suit everyone - I'd suggest another theme for this customer. Closing as wontfix.

**Comment by KokkieH** [comment]
Just noting another report in https://en.forums.wordpress.com/topic/tiled-gallery-posts-as-single-column/ with some extra info:

1. Adding a tiled gallery in the classic editor block causes a regular tiled gallery to display, even on portfolio projects.

2. In testing this a volunteer added a tiled gallery block, followed by a gallery in a classic editor block. However, the site displayed the gallery from the classic block first, followed by the stacked images from the tiled gallery block.

I'm guessing the theme doesn't even try to extract the images from the classic block as it does with the tiled gallery block or galleries added to the classic editor itself.

**Comment by ChrissiePollock** [comment]
Noting a similar report on #12955432-hc. This person was adding a slideshow, and had to switch to the classic editor to add one.

**Comment by syedshaon** [comment]
Similar report #3470397-zd.

**Comment by jwktje** [comment]
Where is this theme's git repo located? I'd be glad to build a PR as a customer of mine has this exact problem and I want to provide a fix.

**Comment by csabarakasz** [comment]
Another report here: 

- [ ] 498528-hc

It is sad this is a won't wix.
