### ISSUE TITLE
Hemingway Rewritten: Site font isn't displayed in the editor

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#4903]
## Steps to replicate
1) Activate this theme. Note the sans-serif body font (at least on my system)

2) Go to wordpress.com/post; note the block editor shows a serif font.

## Result
The block editor displays a different font.

## Expected
I know newer themes show the right font in the block editor. I'm not sure whether this one is supposed to, but figured I'd file this request.

* User report: https://wordpress.com/forums/topic/setting-font-displayed-in-writer-editing-screen/
* Follow-up ticket: (same)

**Comment by jordesign** [comment]
Hey @supernovia  - I'm unable to recreate this on the user's test site.
it *may* have been related to an earlier issue with GB where certain themes weren't using the Theme's styles in the editor. 

If you're able to confirm this is resolved with the user - I think we can close this.

**Comment by supernovia** [comment]
Thanks! And sorry I missed this ping. Last week was something else. I'll let you know what I find.

**Comment by jordesign** [comment]
Hey @supernovia  - just wanted to check in to see if you've been able to recreate this again?
I see we haven't heard back from the user again in 2 weeks - so I'm going to close this for now.

We can always open it again if we need.

**Comment by supernovia** [comment]
Sorry! I was AFK 1.5 days. It looks OK now. :) Thank you!

**Comment by wiesenhauss** [comment]
Another user reported the issue - 5448546-zen
User said the issue appeared "suddenly this week," but Hemingway Rewritten was activated 6 months ago.

Editor view: 
<img width="146" alt="Markup 2022-08-03 at 09 33 08" src="https://user-images.githubusercontent.com/99455043/182615713-edbdabea-259a-4f4c-b1d7-21a4424c06a4.png">

Frontend view:
<img width="164" alt="Markup 2022-08-03 at 09 33 29" src="https://user-images.githubusercontent.com/99455043/182615773-2080f043-71bf-47ee-97d9-db4568832914.png">
 
Site is using "Default theme font" in Customizer.
