### ISSUE TITLE
Intergalactic 2: Blog Posts Block - Featured Images has 0px wide (so not visible) on Published Page

### ISSUE THREAD

**Issue by erricgunawan** [Automattic/themes#4904]
## Steps to replicate

1. Activate Intergalactic 2 theme
2. Create posts with featured images
3. Create page with Blog Posts Block
4. Show featured image option enabled
5. Choose "Show media on left" or "Show media on right"

## Result

Featured Images got "squished" to 0 px wide. 

![Intergalactic2BlogPostsBlockFeaturedImages](https://user-images.githubusercontent.com/1813857/138843200-6868ec25-503c-4773-afe6-fcc8585b3dc3.png)

## Expected

[What you expected to happen.]
It should look good and aligned as in the Editor.

For example:

![image](https://user-images.githubusercontent.com/1813857/138843432-e9410649-bf1c-4640-9ed8-ae5ab7b9065d.png)

## Additional Note

This was mentioned [here](https://github.com/Automattic/newspack-blocks/issues/399#issuecomment-628855129).

I also took the screenshot from @ccwalburn (thank you for taking it in advance!)

I just got a report from the user which matched what @laurelfulford described [here](https://github.com/Automattic/newspack-blocks/issues/399#issuecomment-632358003).

Since this is different from the linked report above, and  I didn't see it's being reported, I did one here.

## User Report

* User report: 32394023-hc 
* Follow-up ticket: 4404657-zen

**Comment by bobmatyas** [comment]
@kathrynwp Did you try to replicate this one? I tested on a self-hosted site and Atomic and it appears resolved:

<img width="1420" alt="Screenshot on 2022-08-09 at 13-36-58" src="https://user-images.githubusercontent.com/45246438/183722751-948709bb-5571-469b-80e0-cada120c19ea.png">

**Comment by kathrynwp** [comment]
@bobmatyas I did not try to replicate, I only added the missing tags when I happened to notice them while working on another project. :)

I just tested now on a Simple site, and it's fixed there as well. Since you already tested Atomic & self-hosted, I'll go ahead and close this now. Thanks!
