### ISSUE TITLE
Sync default themes on dotcom with dotorg

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#4905]
- [x] twentytwentyone
- [x] twentytwenty
- [x] twentynineteen
- [x] twentyseventeen
- [x] twentysixteen
- [x] twentyfifteen
- [x] twentyfourteen
- [x] twentythirteen
- [x] twentytwelve
- [x] twentyeleven
- [x] twentyten

**Comment by scruffian** [comment]
@danieldudzic how are you getting on with this?

**Comment by danieldudzic** [comment]
@scruffian It was on the back burner, but picking it up again

**Comment by danieldudzic** [comment]
PR to review: twentytwentyone - D70474-code

**Comment by danieldudzic** [comment]
PR to review: twentynineteen - D70478-code

**Comment by danieldudzic** [comment]
PR to review: twentyseventeen - D70572-code

**Comment by danieldudzic** [comment]
PR to review: twentysixteen - D70587-code

**Comment by danieldudzic** [comment]
PR to review: twentyfifteen - D70629-code

**Comment by danieldudzic** [comment]
PR to review: twentyfourteen - D70631-code

**Comment by danieldudzic** [comment]
PR to review: twentythirteen - D70633-code

**Comment by danieldudzic** [comment]
PR to review: twentytwelve - D70634-code

**Comment by danieldudzic** [comment]
PR to review: twentyeleven - D70635-code

**Comment by danieldudzic** [comment]
PR to review: twentyten - D70636-code

**Comment by mikachan** [comment]
These should all be reviewed now.

**Comment by danieldudzic** [comment]
Deployed
