### ISSUE TITLE
Blockbase : block-template width isn't savez

### ISSUE THREAD

**Issue by jbonlinea** [Automattic/themes#4906]
## Steps to replicate

Hi there, 
I've create a blockbase child theme folowing the instructions provided on the theme page, and so far so good.
I can edit child-theme.json or add scss nicely. That's sweet, but this is mentionned to support that the child theme is well set, and I've then removed any custom code before opening this issue to have a "fresh start" for debuging.

In the theme editor, when we select a block template, the setting column on the righ offers the possibility to set the bloc layout width ; in blockbase, we can either use the toggle to inherit the setting, or type in a custom value.

However in my case, the change is never saved, I can click on the toggle, or type a custom value, the template is never saved, it stay stuck like this 
![Capture d’écran du 2021-10-26 12-37-27](https://user-images.githubusercontent.com/23659411/138861632-0505c8ed-e588-4635-961f-cec74da40e25.png)

 

## Result

well, on front end, width is not changing, and when I reload the theme editor, the block layout settings are reverted to the values before the (unfortunately not saved) change

## Expected

Ok, I expect the value I set to be saved, and thus the block template to have the width set.

Actually, I want to design my theme as a "fixed width" set to 1200px max, and then fluid on smaller width until it reach the default breakpoint and switch to mobile mode (for menu and such)

EDIT : few word change for clarification and typo

**Comment by jbonlinea** [comment]
Hi, 

Small update on this

as mentionned above clicking save won't save the template.

BUT

I can still edit the template part... on once I do a simple edit, the "save button" is back active.

In practice,  if I do a "layout edit" for instance add a paragraph block (to the index template, or the footer template), and then save, both changes are applied, the width is then saved and tacken into account ?!

Note that a typography change, for instance changing the font color will re-enable the "save button", save the font-color change, but not the width ?!

Regards

**Comment by pbking** [comment]
Thank you @jbonlinea for the report.  I've found this to be an issue with Gutenberg and have opened an issue reporting that [here](https://github.com/WordPress/gutenberg/issues/36409).

**Comment by jbonlinea** [comment]
Ok, great to see you nailed the source ! 
thank's
