### ISSUE TITLE
Videomaker: Post Terms icons not visible on the page

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#4925]
Works fine in Blockbase, but in Videomaker the icons aren't showing:

<img width="1710" alt="tags-2" src="https://user-images.githubusercontent.com/905781/139097383-fb4aeac0-1a16-452c-82fe-dc6d678e4265.png">

**Comment by MaggieCabrera** [comment]
I don't think Videomaker uses icons at all, looking at the figma I don't see any: XnDSyzD9cBG5kbDaVZn9yG-fi-68%3A968

**Comment by scruffian** [comment]
Yeah this is deliberate :)
