### ISSUE TITLE
Canard, Twenty Sixteen, Boardwalk: Padding issue on <mark> element when using inline colors 

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#4934]
### Quick summary

Inline colors use the `<mark>` HTML element (a recent Gutenberg change). Some themes have CSS to add padding to this element but that results in spaces between text.

### Steps to reproduce

1. Create a line of text with no spaces
2. Add inline colors to the text
3. View published page

### What you expected to happen

The published page should have no spaces, like the editor view.

![Screen Shot on 2021-10-26 at 12:52:53](https://user-images.githubusercontent.com/10353785/138925977-9eaa79ec-e1b1-4a63-a26f-6181689f0154.png)

### What actually happened

Padding added by the theme gives the appearance of spaces.

![Screen Shot on 2021-10-26 at 12:56:14](https://user-images.githubusercontent.com/10353785/138925699-13f10d53-9cec-45a2-80bc-5ff099d64206.png)

### Context

32204955-hc

Used this to resolve:

```
/* Mark spacing fix */

mark.has-inline-color {
  padding: unset;
}
```

### Operating System

macOS

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Multiple themes have this. Of around 10 random themes I chose these had the issue:

Canard, Twenty Sixteen, Boardwalk

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

If the site can use CSS:

```
/* Mark spacing fix */

mark.has-inline-color {
  padding: unset;
}
```

**Comment by Robertght** [comment]
I've seen this in a few cases recently as well.  Can this be looked into in the near future?

cc @jeffikus / @scruffian

**Comment by jeffikus** [comment]
@Robertght thanks for reporting. I'll triage this tomorrow and add to the board if we have capacity next week.

**Comment by KokkieH** [comment]
Another report for Twenty-Sixteen: https://wordpress.com/forums/topic/changing-font-color-causes-text-to-shift-to-right/?view=all

**Comment by mikachan** [comment]
Fixed by https://github.com/Automattic/themes/pull/5997
