### ISSUE TITLE
Videomaker: "Wide" width should align with the header edges

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4938]
Right now, when we set content to be wide, it has a set width limit. Can we change that to make it as the example shown?

Currently:

<img width="1520" alt="Captura de ecrã 2021-10-28, às 15 33 09" src="https://user-images.githubusercontent.com/65220155/139278989-3e7001fe-4627-4f63-ac63-9ffb48f758e0.png">    

Intended:

<img width="772" alt="Captura de ecrã 2021-10-28, às 15 40 49" src="https://user-images.githubusercontent.com/65220155/139279173-1a537fbe-2052-457e-aa3c-293dabeba752.png">

**Comment by pbking** [comment]
That looks like "full width, but with margins".  I'm not sure that we would want to either "have full width have margins" or "have wide with be full width not be a static width value".

That design target could be achieved by putting the content into a full-width group, would that suffice for pattens and such?

![image](https://user-images.githubusercontent.com/146530/139282194-3a8dd52f-9874-4eb4-a9eb-39f6baee9147.png)

**Comment by pbking** [comment]
That said...
Setting the theme.json value of `wideWidth` to `100%` does achieve exactly what you're looking for.  I'll leave it to others to determine if we should...

**Comment by MaggieCabrera** [comment]
mmh, is this not a problem of the header being full width instead of wide here? maybe I'm misunderstanding. I think Bea means this should be like Skatepark's header:

<img width="1553" alt="Screenshot 2021-10-28 at 17 15 32" src="https://user-images.githubusercontent.com/3593343/139285460-4aebf5e3-92a4-41c9-98ce-295149196766.png">

**Comment by beafialho** [comment]
Thanks @pbking, the group set to full-width solution achieves the intended effect indeed. I applied it to the demo site. Though, I wonder if we want to leave that as an option for users or set it as the theme's layout. Would like to know @kjellr's thoughts.

**Comment by beafialho** [comment]
@MaggieCabrera the header in Videomaker is perfect as it is 👌

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera the header in Videomaker is perfect as it is 👌

I misunderstood then!

**Comment by kjellr** [comment]
> Thanks @pbking, the group set to full-width solution achieves the intended effect indeed. I applied it to the demo site. Though, I wonder if we want to leave that as an option for users or set it as the theme's layout. Would like to know @kjellr's thoughts.

The header + top image on the demo site looks good. That should be the default used in the pattern on the homepage. Since we can already create this effect, I don't think https://github.com/Automattic/themes/pull/4939 is necessary.

I think that the content below that (the grid of 4 videos) should remain the width it was previously. I think it gets a little difficult to parse the grid when it's full-width on larger screens.

**Comment by kjellr** [comment]
I was looking through the original comps again, and I wonder if we're actually approaching this the wrong way. In the original mockups, the width of the top item was the same as the width of the bottom items. But we've broken that now. 

[This mockup (set to "Scale down to fit width")](https://www.figma.com/proto/XnDSyzD9cBG5kbDaVZn9yG/Videomaker?page-id=68%3A968&node-id=68%3A1068&viewport=241%2C48%2C0.45&scaling=scale-down-width&starting-point-node-id=68%3A1838) looks good on both small and large screens for me. Its header and the first top item do _not_ go full width on larger screens. They max out at the max-width, and let in in some black bars on the sides when you make the screen too big. I think that's probably the better approach here:

![scale](https://user-images.githubusercontent.com/1202812/139489059-1958957b-c0f1-466a-9948-21b79d3d552e.gif)

Can we try that out and see how it feels?

**Comment by scruffian** [comment]
So you mean set the header to be wide width?

**Comment by scruffian** [comment]
Like this? https://github.com/Automattic/themes/pull/4956

**Comment by beafialho** [comment]
This solution looks good to me 👍
