### ISSUE TITLE
Videomaker: Tighten up space between the H4 and paragraph on the homepage pattern. 

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4950]
In the block pattern used on the homepage, we should tighten up the space between the video titles and the date below them: 

Before|After
---|---
![current](https://user-images.githubusercontent.com/1202812/139485282-796c34f2-60ce-4a74-95bb-2f13b82c9b44.png)|![intended](https://user-images.githubusercontent.com/1202812/139485281-133af50c-ba84-4d98-87fd-548d08fc041e.png)

`calc(0.5 * var(--wp--style--block-gap))` looks right to me.

(Also, I'm not sure if this is what happens in the pattern natively, but on the demo site it looks like we're using the post date block for the dates, but that doesn't make sense since these are not individual posts? cc @beafialho)

**Comment by beafialho** [comment]
I agree @kjellr, tightening up spacing here is necessary

**Comment by pbking** [comment]
#5012 addresses the spacing issue you raised @kjellr, however it isn't clear what the content should be regarding your comment:

> it looks like we're using the post date block for the dates, but that doesn't make sense since these are not individual posts?

It is set that way in the pattern.  What value should it be if not the post date?  (Which I agree doesn't make much sense...)

**Comment by kjellr** [comment]
We're addressing that in https://github.com/Automattic/themes/issues/4892#issuecomment-967116923.
