### ISSUE TITLE
Videomaker: Top navigation menu is misaligned, Site tagline should be 16px

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4951]
<img width="1251" alt="Screen Shot 2021-10-29 at 2 38 11 PM" src="https://user-images.githubusercontent.com/1202812/139485717-50af3618-c687-4dec-ab62-693a0ff4c291.png">

Also, I took a look at the comps, and it appears that all the text up here is supposed to be `20px`, not `18px`. @beafialho can you confirm?

**Comment by beafialho** [comment]
That's right @kjellr, I totally missed the misalignment, I kept in mind that the hamburger icon would eventually replace the menu items.

The Site Title is supposed to be `20px` and links `18px`. Now that I look at this again, I think the tagline could be `16px`. It looks good to me, but is it weird having different sizes for all elements?

<img width="1338" alt="Captura de ecrã 2021-11-01, às 09 49 47" src="https://user-images.githubusercontent.com/65220155/139653692-eadafc04-2b8f-4c91-84cd-412ca200a2b0.png">

**Comment by kjellr** [comment]
Yeah, that's too many sizes for one small area. It doesn't look like we use 20px text elsewhere either. So I suggest we do:

**Site title:** 18px (This is already the case)
**Site tagline:** 16px
**Nav:** 18px (This is already the case)

I'll update the issue description to make note of this.

**Comment by beafialho** [comment]
That looks good to me!
