### ISSUE TITLE
Videomaker: Post pagination is incorrect width and is missing arrows

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4952]
The post pagination as originally designed is the just slightly wider than the post content: 

![Single Post](https://user-images.githubusercontent.com/1202812/139490814-167ed88c-08af-4ae6-8523-34e9d8cca4b8.jpg)

As currently developed, it it significantly wider than this: 

<img width="1909" alt="Screen Shot 2021-10-29 at 3 23 26 PM" src="https://user-images.githubusercontent.com/1202812/139490891-2ce69b32-4d16-4e01-9414-1e8bc874415c.png">

If we can't get it to display as originally designed, I think making it the same width as the content would be truer to the original design intent. 

In addition, the pagination is missing its arrows. These should match the arrows from the query pagination. 

cc @beafialho

**Comment by beafialho** [comment]
> If we can't get it to display as originally designed, I think making it the same width as the content would be truer to the original design intent.

Agree 👍

**Comment by danieldudzic** [comment]
I think it would make sense for the post pagination to be matching, style-wise, the query pagination:
https://github.com/Automattic/themes/pull/4933 - it also should probably use the same, core arrows.

Unfortunately, it does seem that the `paginationArrow` attribute is only supported by the Query Pagination - @scruffian do you think it's worth opening a Gutenberg issue for this? (or am I mistaken about this entirely?)

**Comment by scruffian** [comment]
There's already a GB issue: https://github.com/WordPress/gutenberg/issues/35954

**Comment by jeffikus** [comment]
Closing in favour of duplicate #4893
