### ISSUE TITLE
Videomaker: Navigation is missing underlines on hover, is unreadable in its active state

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4959]
These links should be underlined on hover, and their active states should have black text against the white background. 

![active-states](https://user-images.githubusercontent.com/1202812/139862513-66954c1b-d8c8-43b0-8941-38d8381c8410.gif)

(Also, this menu should use the hamburger on desktop. It didn't look like there's another issue for that?)

cc @beafialho

**Comment by mikachan** [comment]
It looks like the menu will change to use the hamburger on desktop when #4832 can be merged.
