### ISSUE TITLE
Videomaker: Footer should be wide width

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4960]
Currently, the footer is sticked to the edges of the screen, but it should behave similarly to the header and be wide width too.

<img width="1530" alt="Captura de ecrã 2021-11-02, às 15 38 39" src="https://user-images.githubusercontent.com/65220155/139879666-276e6bce-cd17-4fe4-a910-d6890da08f23.png">

**Comment by kjellr** [comment]
The footer still shows up as full-width in my testing. 

Here's the demo: 
<img width="1218" alt="Screen Shot 2021-12-03 at 8 11 30 AM" src="https://user-images.githubusercontent.com/1202812/144608100-7ed4a059-4775-4fc4-88ab-bc0e28538201.png">



And a fresh site: 

<img width="1218" alt="Screen Shot 2021-12-03 at 8 09 45 AM" src="https://user-images.githubusercontent.com/1202812/144608042-75ea065b-92fb-444d-9028-e26ffe298af9.png">
