### ISSUE TITLE
Videomaker: Remove period and align footer credit to links

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4962]
The footer credit seems to be misaligned to the footer links.

<img width="1348" alt="Captura de ecrã 2021-11-02, às 15 54 44" src="https://user-images.githubusercontent.com/65220155/139887361-abf02c7c-ca69-4253-a52c-400004fcb78d.png">

Let's also remove the period and replace "Blog" by "Website".

<img width="242" alt="Captura de ecrã 2021-11-02, às 15 50 36" src="https://user-images.githubusercontent.com/65220155/139884232-aaeaa6a6-fa77-400b-98e0-d90188d447a1.png">

**Comment by mikachan** [comment]
As far as I know, the footer credit text automatically has a period at the end, and the content can only be one of these options from the Customizer:

![image](https://user-images.githubusercontent.com/1645628/141847858-f4cd0755-ac64-4e59-beee-45459c937844.png)

I've changed the demo site so it uses, "Website Built with WordPress.com". It was set to 'default' previously.

I've opened up a PR for the link alignment: https://github.com/Automattic/themes/pull/5034
