### ISSUE TITLE
Skatepark: Spacing between menu items is incorrect

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4963]
Current Dev|Mockup
---|---
<img width="387" alt="Screen Shot 2021-11-02 at 3 15 33 PM" src="https://user-images.githubusercontent.com/1202812/139938699-01f50d48-d6ed-4bcd-8cb0-d8e33f192613.png">|<img width="259" alt="Screen Shot 2021-11-02 at 3 30 37 PM" src="https://user-images.githubusercontent.com/1202812/139938375-287a4faf-f7cd-4802-bc5d-32de01c893f4.png">

**Comment by kjellr** [comment]
Also since we're here: is it possible to underline the current item, as designed?

**Comment by scruffian** [comment]
I believe @mikachan just got a Gutenberg PR merged which now makes this possible!
