### ISSUE TITLE
Blockbase: warnings when saving color or font changes

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4970]
## Steps to replicate

I've seen this on trunk, using skatepark and changing the color palette, on my PHP error_log file I see warnings like this:

<img width="1972" alt="Screenshot 2021-11-03 at 12 28 01" src="https://user-images.githubusercontent.com/3593343/140052591-0c91a94f-1618-41ef-82f1-0652afb4956b.png">

/cc @scruffian

**Comment by MaggieCabrera** [comment]
It's also happening when I do font changes.

**Comment by scruffian** [comment]
Oh funny I think i've just been working on a fix for this. I'll create a PR.

**Comment by scruffian** [comment]
Try https://github.com/Automattic/themes/pull/4972
