### ISSUE TITLE
Skatepark: Add more spacing between featured image and post content

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4976]
There should be more spacing between the featured image and the post content. According to the [Figma file](https://www.figma.com/file/CA8Gb16mt9yYNWOiVLAWak/Skatepark?node-id=2691%3A2220), the first paragraphs on posts should also have `184px` indentation. Here's how it should look:

| Currently      | Mockups |
| ----------- | ----------- |
| <img width="1533" alt="Captura de ecrã 2021-11-03, às 17 08 13" src="https://user-images.githubusercontent.com/65220155/140137422-6beba288-4e55-45d3-ab97-f620496d20e0.png">    |  <img width="1360" alt="Captura de ecrã 2021-11-03, às 17 08 45" src="https://user-images.githubusercontent.com/65220155/140137982-83842df5-5599-41d3-a871-41c03df93a64.png"> |    

cc: @kjellr

**Comment by danieldudzic** [comment]
<img width="1360" alt="140137982-83842df5-5599-41d3-a871-41c03df93a64" src="https://user-images.githubusercontent.com/905781/142429558-3d97b98f-913e-4475-a0cb-ed78c49c88e6.png">

I understand that the above indentation is a design choice, but it seems excessive to me. I believe users will flag it as a bug.

Additionally, I don't believe Gutenberg provides a way to change the default indentation just yet.

**Comment by MaggieCabrera** [comment]
> I understand that the above indentation is a design choice, but it seems excessive to me. I believe users will flag it as a bug.
> 
> Additionally, I don't believe Gutenberg provides a way to change the default indentation just yet.

The indentation was something we tried and discarded, this issue should be just about the vertical space between the text and the image

**Comment by beafialho** [comment]
Sounds good 👍 I wasn't aware of previous discussions around indentation.
