### ISSUE TITLE
Skatepark: Add "Next Post" and "Previous Post" to post navigation

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4977]
Currently the post navigation is looking like this:

<img width="1529" alt="Captura de ecrã 2021-11-03, às 17 09 27" src="https://user-images.githubusercontent.com/65220155/140148035-627388bd-4e95-4efb-bb39-91e80688f1f4.png">

It should look as shown in the [Figma comp](https://www.figma.com/file/CA8Gb16mt9yYNWOiVLAWak/Skatepark?node-id=258%3A2085). Post navigation terms should be `H6` and post titles should be size Extra Small `14px` in Medium weight.

<img width="1505" alt="Captura de ecrã 2021-11-03, às 17 09 34" src="https://user-images.githubusercontent.com/65220155/140148176-d813aef8-6d88-46e2-a660-f784d407b35d.png">

cc: @kjellr

**Comment by MaggieCabrera** [comment]
We didn't do this originally because the block didn't allow it, I think that has changed so we can revisit this

**Comment by pbking** [comment]
While we can add labels via block attribute since block-templates aren't yet localizable the content "PREVIOUS POST" and "NEXT POST" would instead need to leverage something like the [pattern block](https://github.com/WordPress/gutenberg/pull/33217).
