### ISSUE TITLE
Hever: Full-width layout block overlaps featured image

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#4978]
## Steps to replicate
Create a new post
Add a featured image
Add a Layout Grid block - keep it on full alignment
Put content in each column
Save and view the post on its own (not in a list of posts)

## Result
The layout block gets a -64px margin, only on .single, and only when the layout is full (which is default).

On pages, it looks awkward. On posts, the first line is unreadable if the post has a featured image.
<img width="1494" alt="Screen Shot 2021-11-03 at 11 09 17 AM" src="https://user-images.githubusercontent.com/3476361/140143446-2d68d6d7-dc7a-476e-b9c3-b8cca70e6260.png">

<img width="1494" alt="Screen Shot 2021-11-03 at 11 08 47 AM" src="https://user-images.githubusercontent.com/3476361/140143076-8f10b1bb-3c55-4c9e-8140-8827cbd06761.png">

## Expected
Here's how it looks if I set the alignment to none: the margin appears and the content looks more normal.

<img width="1494" alt="Screen Shot 2021-11-03 at 11 15 40 AM" src="https://user-images.githubusercontent.com/3476361/140144447-d8208917-03ec-4b0f-acad-252ae307d3b6.png">

<img width="1494" alt="Screen Shot 2021-11-03 at 11 08 15 AM" src="https://user-images.githubusercontent.com/3476361/140145944-a757dde9-4bd7-4d29-a283-05be540559de.png">

I suspect this is in place to deal with people using full-width cover images at the top of pages, since that looks more normal:

<img width="1494" alt="Screen Shot 2021-11-03 at 11 26 27 AM" src="https://user-images.githubusercontent.com/3476361/140154179-ecc0ba50-4052-4a64-978e-712aced3d761.png">

* User report: https://wordpress.com/forums/topic/layout-grid-block-issues/
(note this has _multiple_ issues; I'm going to try to get those untangled)

* Follow-up ticket: https://wordpress.com/forums/topic/layout-grid-block-issues/

**Comment by supernovia** [comment]
[Here's the offending CSS:](https://github.com/Automattic/themes/blob/trunk/hever/style.css)

`@media only screen and (min-width: 560px) {
	.singular .hentry .entry-content > *:first-child.alignfull {
		margin-top: -64px;
	}
}`

If there's a way to say it doesn't apply to layout blocks, that'd do. :)

**Comment by jordesign** [comment]
Confirmed this is still reproducible on Hever.
