### ISSUE TITLE
Quadrat, Zoologist, Geologist: Header elements misaligned.

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#4982]
## Steps to replicate
1. Go to the demo site of Quadrat, Zoologist, or Geologist (so far any Blockbase child that has site title, description, and nav in one row).
2. Note title + description and navigation are slightly misaligned:

![image](https://user-images.githubusercontent.com/4550351/140199575-f81d729d-aa74-44a4-a6c7-2ed7febd0831.png)

![image](https://user-images.githubusercontent.com/4550351/140199611-11473b48-9a91-414f-8ebe-2af4fdad1042.png)

This seems to be because the nav menu has a top margin applied, but not the other header elements.

![image](https://user-images.githubusercontent.com/4550351/140199786-ba3151af-3c67-489f-9cb3-258050da49cc.png)

**Comment by mikachan** [comment]
I think this should be fixed by #5038, where we removed the top margin on the nav menu [here](https://github.com/Automattic/themes/pull/5038/files#diff-7f1b848395a59a5b8c1b0ab7f66d7b20acfc11e75bf27a681898cd60715695cfR8). But let us know if you still see the issue!
