### ISSUE TITLE
Videomaker: When adding the patterns, videos fail on their first attempt

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4991]
## Steps to replicate
When you add a pattern with videos in it seems to fail and require the user to click "try again" on the embed blocks.

This seems to only happen on WordPress.com. This is probably not a theme bug.

See pNEWy-es0-p2#comment-53845

**Comment by scruffian** [comment]
I can't replicate this anymore. Please can someone else check - if you can't replicate either then we can close!

**Comment by mikachan** [comment]
I've just tried adding the 'Header, Description and Grid of Projects' and 'Grid' patterns both locally and on my sandbox, and the videos loaded fine. I'm pretty sure I can't replicate this either!
