### ISSUE TITLE
Pique: Theme Info displaying in footer on AT French Site

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#5]
Originally reported by @jenlynnemc in #4794-wpcom-themes:

## Steps to replicate

Set a site to use the theme Pique, and change the language to French.

## Result

The footer credit now includes theme information.

![](https://cldup.com/jwgchZfW-Z-3000x3000.png)

## Expected

The footer credit would not include theme information, like it does when the site is set to English.

Note: The credit is currently being hidden with Custom CSS as a work-around.

* User report: #597631-hc
* User's site: https://the-adintime-agency.com

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
