### ISSUE TITLE
Twenty Seventeen: Social Icons widget hover styles need love

### ISSUE THREAD

**Issue by sixhours** [Automattic/themes#50]
(Opening this here rather than core since it's related to one of our widgets.)

## Steps to replicate

1) Activate Twenty Seventeen.
2) Add a Social Links widget to the footer and add few links to it.
3) View the site and hover over one of the social links.

## Result

On hover, there's no contrast between the icons and the background, and there's an increased bottom border on the circles, which makes them look pretty funky:

https://cloudup.com/c7tulLdkMS0

## Expected

Better contrast between the icon and background, without the extra bottom border.

No user report or follow-up required, noticed on my own as I was looking at a customer site:

* User's site: https://tombolphotoworkshops.com

**Comment by laurelfulford** [comment]
Fixed in r48538-wpcom-themes.
