### ISSUE TITLE
Twenty Seventeen: Borders are showing for linked transparent images

### ISSUE THREAD

**Issue by devNigel** [Automattic/themes#5018]
### Quick summary

Bottom borders are showing up for linked transparent images in Simple sites. Previously, that was not the case. 

### Steps to reproduce

1. With Twenty Seventeen theme active, upload an image with a transparent margin on all sides. Sample image is uploaded here: 
![image](https://user-images.githubusercontent.com/33957570/140730152-41810de0-a734-44ff-a3b7-ff09618b9c0e.png)
2. Add a link to the image.
3. Visit the page, you will notice an underline or bottom border for the image.

### What you expected to happen

The image should render as seen in the editor. There are no borders or underlines for linked image in the editor view.

Editor view: 
![image](https://user-images.githubusercontent.com/33957570/140731136-0c497b1f-9b5f-4063-b120-4c1254e095f3.png)

### What actually happened

The linked image had underline / border bottom. Was not able to reproduce the issue on atomic sites.

Live page view: ![image](https://user-images.githubusercontent.com/33957570/140730922-0468981b-4da4-4af6-92fd-e2f3d8fe2a8e.png)

### Context

User report: 4437513-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Twenty Seventeen

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, difficult to implement

### Workaround details

Will need to either use CSS code to override the border or use a jpg image.

**Comment by jordesign** [comment]
This is happening when the image is linked due to these styles:

```
.entry-content a, .entry-summary a, .comment-content a, .widget a, .site-footer .widget-area a, .posts-navigation a, .widget_authors a strong {
    -webkit-box-shadow: inset 0 -1px 0 rgb(15 15 15);
    box-shadow: inset 0 -1px 0 rgb(15 15 15); 
    -webkit-transition: color 80ms ease-in,-webkit-box-shadow .13s ease-in-out;
    transition: color 80ms ease-in,-webkit-box-shadow .13s ease-in-out;
    transition: color 80ms ease-in,box-shadow .13s ease-in-out;
    transition: color 80ms ease-in,box-shadow .13s ease-in-out,-webkit-box-shadow .13s ease-in-out;
}
```

**Comment by danieldudzic** [comment]
Fix: D71937-code

**Comment by mriyazuddin** [comment]
Another issue here: 4555627-zen

**Comment by mikachan** [comment]
The fix (D71937-code) has now been deployed to live.

**Comment by scruffian** [comment]
Does this need to be pushed back to core?

**Comment by mikachan** [comment]
> Does this need to be pushed back to core?

Ah yeah good shout, this probably does need adding to core as well.

**Comment by omgmajk** [comment]
This is happening for me as well. 
![2022-05-26 21_14_49-AFFRA se – HARDWARE IN THE LOOP ENGINEERING](https://user-images.githubusercontent.com/10681392/170560561-cf6c1915-64a4-40dc-989b-14ef21f7df4d.png)
