### ISSUE TITLE
Blockbase: fatal when Gutenberg is inactive

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5028]
If the Gutenberg plugin is inactive, we get the following fatals:

![](https://cloudup.com/ccwN0OtaYXO+)

I tried a solution at https://github.com/Automattic/themes/pull/4983 but that won't work on dotcom simple sites because Gutenberg is loaded differently. This needs a different solution.

**Comment by jeffikus** [comment]
@MaggieCabrera is the constant check here - https://github.com/Automattic/themes/pull/4983/files#diff-c1ec8d6a5b44921aad8992feffbff8a51d7a2ce7c5a3ab8cafebd09b535fcfceR240 - finding it or is that not even present?
