### ISSUE TITLE
Button 2: Blog Post Block not displaying featured image thumbnails on frontend

### ISSUE THREAD

**Issue by Thelmachido** [Automattic/themes#5037]
## Steps to replicate

1. Add the [Button 2](https://wordpress.com/theme/button-2) theme to a simple site.
2. On any page add the [Blog Posts Block](https://wordpress.com/support/wordpress-editor/blocks/blog-posts-block/) to display a few posts.

## Result

The posts displayed will show featured image thumbnails in the editor and not the frontend. 

**_Screenshot of the Blog Posts Block in the editor_** 

![Screenshot on 2021-11-16 at 11_38_25](https://user-images.githubusercontent.com/41231764/141961748-57035918-461b-46f9-89e6-2940a10059a2.png)

**_Screenshot of the Blog Posts Block on the frontend_** 

![Screenshot on 2021-11-16 at 11_38_03](https://user-images.githubusercontent.com/41231764/141961959-58b11183-ca35-44fb-ac36-fd58158a6335.png)

## Expected

I expected the Blog Post Blog to look similar and display the posts featured images in the editor and on the frontend.

* User report: [32650586-hc]
* Follow-up ticket:  [4459289-zen]

**Comment by ccwalburn** [comment]
This was reported here: https://github.com/Automattic/newspack-blocks/issues/399

**Comment by Thelmachido** [comment]
Thank Catherine, closing this one.
