### ISSUE TITLE
Libretto: Dropdown form fields do not display correctly on desktop

### ISSUE THREAD

**Issue by lakellie** [Automattic/themes#504]
Issue occurs both in forms created using the Calypso classic editor, and Gutenberg form block.

Reported by a user and duplicated on my own test sites.

## Steps to replicate

Classic Editor
1. Add a form to a post or page via Add > Contact Form
2. Add a "dropdown" field to the form

Gutenberg
1. Add a form block
2. Add a "select" field

## Result

The dropdown box does not display in the right location: http://cld.wthms.co/O3eEm8

## Expected

I expected the dropdown box to display in the correct location, like it does on mobile: http://cld.wthms.co/gWnSQu

* User report: #1710300-zen
* User's site: https://concorsocittamurata.com/2018/10/29/festival-citta-murate-2019-prenotazione-biglietti-eventi/
(We will be providing them with CSS as a temporary workaround).

**Comment by laurelfulford** [comment]
Noting that I can see the above in Safari, but in Firefox, the dropdown displays below the label:

![image](https://user-images.githubusercontent.com/177561/52237494-81c9ff00-287e-11e9-8c1e-3b66b67d1fe2.png)

... which also isn't quite right.

**Comment by torres126** [comment]
@laurelfulford Oops, the PR I proposed for this in #508 assumes that the dropdown is intentionally meant to be beneath the label on desktop (not mobile) devices. Am I correct in saying that it should be inline with the label, similar to how it displays on mobile?

![screenshot_20190204-211628](https://user-images.githubusercontent.com/43215253/52237700-30436380-28c2-11e9-81c9-9ab6137a68ff.jpg)

(Excuse the horrible screenshot...)

**Comment by laurelfulford** [comment]
Ah good catch! I think it is suppose to be like the other fields, with the label on the left, and the input/select/etc on the right, like in my screenshot above.

**Comment by torres126** [comment]
Thanks @laurelfulford! One more question, centre or aligned beneath the box? 

![ssdfsdafsdafdfs](https://user-images.githubusercontent.com/43215253/52239911-75b65f80-28c7-11e9-8630-68280b717e91.png)

**Comment by laurelfulford** [comment]
This has been committed to WP.com in 53244-wpcom-themes.

@lakellie Can you please follow up with the user, if needed? It looks like the form they originally linked to is no longer there, but the styles added also make the form a little narrower than it is normally, I don't want to mess anything up by removing it. Thanks!
