### ISSUE TITLE
Videomaker: Remove tags and increase spacing in Blog

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#5042]
In the default template let's adjust two things, as [shown](https://www.figma.com/file/XnDSyzD9cBG5kbDaVZn9yG/Videomaker?node-id=68%3A1223) in the Figma file:
- Omit tags and only show them in the posts
- Increase spacing between post title, featured image and excerpt to match the mockups (perhaps `45 px`)

Currently:
<img width="504" alt="Captura de ecrã 2021-11-16, às 17 07 37" src="https://user-images.githubusercontent.com/65220155/142031937-75b6d600-fb1a-40a5-a30c-b914ff27da27.png">

Intended:
<img width="616" alt="Captura de ecrã 2021-11-16, às 17 05 47" src="https://user-images.githubusercontent.com/65220155/142031835-a8c34ea9-ae40-4cf2-a1f3-5909348837bd.png">

**Comment by mikachan** [comment]
Closed with #5057
