### ISSUE TITLE
Afterlight: Simple Payments button quantity toggle not working

### ISSUE THREAD

**Issue by thebud15** [Automattic/themes#505]
## Steps to replicate

1. Opened a new page on the Afterlight theme
2. Added a Simple Payments button (tested with both the classic and new editors)
3. Include the option to allow buyers to purchase multiple items. 
4. Publish and head to that page on the live site. 

## Result

The toggle option for quantity of items cannot be selected. Here's a video of this: ![screen capture on 2019-01-21 at 20-19-55](https://user-images.githubusercontent.com/29046778/51512374-7ecd0a00-1dba-11e9-8fdb-879968451a2c.gif)

## Expected

I expected to be able to change the number of items being used. I tested this on other themes, and the problem appears to be specific to this one, in both editors. 

* User report: #2885466-hc
* Follow-up ticket: #1737841-zd
* User's site: https://amythinksoutloud.com/junkyardgraffiti/ (the user has since changed theme)

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
