### ISSUE TITLE
Blockbase: Editor alignment styles do not apply to site header

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5066]
## Steps to replicate

- Activate Blockbase
- Edit the header block in the Editor by aligning the items to the right or center
- The items do not change alignment

https://user-images.githubusercontent.com/1645628/142636423-30240657-eb7c-4e8e-b519-5c951cf07409.mov

It looks like this is because of two styles in _header.scss:

`justify-content: start;` ([here](https://github.com/Automattic/themes/blob/cdb5883c518ce7bc282998ffb6d5e4a2786841fb/blockbase/sass/base/_header.scss#L2)) & `flex-grow: 1;` ([here](https://github.com/Automattic/themes/blob/cdb5883c518ce7bc282998ffb6d5e4a2786841fb/blockbase/sass/base/_header.scss#L7))

**Comment by tinjure20** [comment]
I could also see similar misaligned header navigation in Blockbase and it's child Quadrat.

Blockbase:
![blockbase-header](https://user-images.githubusercontent.com/59660253/142773655-7cb6810b-b9b1-4123-afba-7471051b4a55.png)
Quadrat:
<img width="1034" alt="quadrat-header" src="https://user-images.githubusercontent.com/59660253/142773672-5d58867e-a64b-4e17-99f2-d93c9a300b7a.png">

Local testing environment:
- WordPress 5.8.2
- Gutenberg 11.9.1
- Blockbase 1.4.3
- Quadrat 1.1.3

**Comment by matiasbenedetto** [comment]
#5093 should fix this issue

**Comment by scruffian** [comment]
Closing in favour of https://github.com/Automattic/themes/issues/5119
