### ISSUE TITLE
Videomaker: Patterns issues

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5070]
## Background Video

I recommend we replace this with standard text instead, just like we did with the grid patterns. I think we can simplify it too, so it's more of a general-use pattern and less of a site-building one. 

- Change Post Title block to a H2 that says "Plenty of Fish In The Sea". 
- Change date and categories to static text that reads "A film about finding what you’re looking for."
- Remove the page header, navigation blocks, columns. Position text at the bottom left of the cover. 
- Ensure all text is white. 

[Gist of new markup for example.](https://gist.github.com/kjellr/53f8032aced47fe8ee5623a4370ee60c)
 
_Currently:_
<img width="566" alt="Screen Shot 2021-11-22 at 3 42 49 PM" src="https://user-images.githubusercontent.com/1202812/142932903-9b65603c-d221-4946-9551-92ff8a3de3da.png">

_Target:_
<img width="1127" alt="Screen Shot 2021-11-22 at 3 50 36 PM" src="https://user-images.githubusercontent.com/1202812/142933457-5ee888a3-6788-4d27-84b3-c7514cbda232.png">

## Film Poster

Missing image.

_Currently:_
<img width="585" alt="Screen Shot 2021-11-22 at 3 43 21 PM" src="https://user-images.githubusercontent.com/1202812/142932599-399bca40-83e8-410d-8e77-e4f970bbfa77.png">

## Header, Description, and Grid of Projects

Can we adjust this one so that this last one never falls out of alignment because of the line break below? Might need to rebuild using multiple, stacked columns blocks.  

<img width="464" alt="Screen Shot 2021-11-22 at 3 54 39 PM" src="https://user-images.githubusercontent.com/1202812/142934103-ce13b76a-b949-4254-8103-2bb9a8c45ca3.png">

## Grid of Projects

Can we swap "I love you" for another video that has the same aspect ratio as the rest? Currently, this doesn't line up correctly: 

<img width="1324" alt="Screen Shot 2021-11-22 at 3 55 03 PM" src="https://user-images.githubusercontent.com/1202812/142934380-a07071f5-0fae-4f1d-bd41-31397e02cc98.png">

Alternatively, we could just remove that last row of videos for now, to match what's on the homepage. 
(Even if we do that though, this problem will be noticeable in the "Header, Description, and Grid of Projects" pattern above.)

---

cc @beafialho

**Comment by beafialho** [comment]
> Can we swap "I love you" for another video that has the same aspect ratio as the rest? Currently, this doesn't line up correctly:

Yes, like I have suggested in #5071, here's a video we can swap for this one:
- https://www.pexels.com/video/black-and-white-video-of-busy-street-854141/
