### ISSUE TITLE
Videomaker: Add image + video source information

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5071]
https://github.com/Automattic/themes/blob/8cfaa36188533c67167689d158e2a8865f12bf3a/videomaker/readme.txt#L39-L44

cc @beafialho can you pull these links together?

**Comment by beafialho** [comment]
Yes! Here are the links to the videos used in the patterns:

- https://www.pexels.com/video/video-of-school-of-fish-854012/
- https://www.pexels.com/video/watercrafts-docked-853917/
- https://www.pexels.com/video/boats-floating-at-the-sea-853856/
- https://www.pexels.com/video/man-working-during-dawn-854069/
- https://www.pexels.com/video/mixing-cocktail-drinks-854128/

We'll have to replace these two videos in the theme as they are not CC0.
<img width="632" alt="Captura de ecrã 2021-11-23, às 15 24 47" src="https://user-images.githubusercontent.com/65220155/143052599-22d63a62-3cb1-4cda-9254-abc5e9258917.png">
<img width="481" alt="Captura de ecrã 2021-11-23, às 15 24 38" src="https://user-images.githubusercontent.com/65220155/143052612-89c1fe45-3a03-403a-b953-e08c00356075.png">

Here are two replacement suggestions:
- https://www.pexels.com/video/close-up-video-of-a-red-flower-854015/
- https://www.pexels.com/video/black-and-white-video-of-busy-street-854141/

![Homepage](https://user-images.githubusercontent.com/65220155/143054272-e3018089-1c29-47dd-84ae-a302c4554d09.jpg)

Demo site & patterns photos:
- https://pxhere.com/en/photo/559804
- https://stocksnap.io/photo/people-hands-91UQMKOMCW
- https://stocksnap.io/photo/camera-lens-0RG77S4ZNE
- https://stocksnap.io/photo/people-man-NSV3ZCAJXT
- https://stocksnap.io/photo/people-man-6O7JXC5DC5
- https://stocksnap.io/photo/camera-gopro-IOO3SM5ZEH

Demo site video:
- https://www.pexels.com/video/snow-falling-on-water-853812/

**Comment by kjellr** [comment]
Here's a full list of the ones we're using: 

Videos (All CC0)
https://www.pexels.com/video/video-of-school-of-fish-854012/
https://www.pexels.com/video/watercrafts-docked-853917/
https://www.pexels.com/video/boats-floating-at-the-sea-853856/
https://www.pexels.com/video/man-working-during-dawn-854069/
https://www.pexels.com/video/mixing-cocktail-drinks-854128/
https://www.pexels.com/video/black-and-white-video-of-busy-street-854141/

Images (All CC0)
https://pxhere.com/en/photo/559804
https://stocksnap.io/photo/people-hands-91UQMKOMCW
https://stocksnap.io/photo/camera-lens-0RG77S4ZNE
https://stocksnap.io/photo/people-man-NSV3ZCAJXT
https://stocksnap.io/photo/people-man-6O7JXC5DC5
https://stocksnap.io/photo/camera-gopro-IOO3SM5ZEH
