### ISSUE TITLE
Quadrat: changing justify settings in Header -> Row block has no effect

### ISSUE THREAD

**Issue by vindl** [Automattic/themes#5078]
## Steps to replicate

1. Activate the Quadrat theme on your test site.
2. Activate Gutenberg plugin to enable the Site Editor.
3. Open the Site Editor and select `Header` -> `Row` block on the homepage.
4. Toggle the justify settings (left, center, right, space between).

## Result

Nothing happened.

## Expected

Nested Row items to move to the designated position.

**Comment by matiasbenedetto** [comment]
[#5093](https://github.com/Automattic/themes/pull/5093) should fix this issue

**Comment by pbking** [comment]
I believe this should be appropriately addressed in https://github.com/Automattic/themes/pull/5145 and can be retested.

**Comment by scruffian** [comment]
Confirmed
