### ISSUE TITLE
Blockbase: Menu won't work in FSE if no menu assigned to primary location

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5086]
I found this when I started testing on a fresh site with no content at all. To reproduce:

- Make sure you have no menus defined for the site in the customizer
- Go to the Site Editor, click on the header and add a few links to the navigation block
- Check the frontend: no menu shows up

<img width="304" alt="Screenshot 2021-11-24 at 12 37 02" src="https://user-images.githubusercontent.com/3593343/143231793-ba221910-a4b7-4081-9212-19d20b13a744.png">

<img width="1219" alt="Screenshot 2021-11-24 at 12 37 32" src="https://user-images.githubusercontent.com/3593343/143231791-7c0059cd-90e4-4fd4-bed4-91983dbc755d.png">

<img width="1425" alt="Screenshot 2021-11-24 at 12 37 46" src="https://user-images.githubusercontent.com/3593343/143231783-c4286824-8592-4ad1-8264-89f0b0d74d39.png">

**Comment by scruffian** [comment]
This is fixed by https://github.com/WordPress/gutenberg/pull/36863
