### ISSUE TITLE
Blockbase: Add alternative Header template parts which span full width

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#5087]
## Steps to replicate

When editing a site with Blockbase - set a background color on the Header template part

## Result

The Header is not full width within the page - so the background remains contained with the content width.

![image (2)](https://user-images.githubusercontent.com/1842363/143231365-b85e3b71-9001-4f3e-bb9b-475e66cf6c59.png)

## Expected

I hoped/expected to be able to place a background on the Header template part - and have it be applied full width.

Could we consider adding other Header parts that users could choose from - that would allow this?

**Comment by jordesign** [comment]
Pinging @kjellr  and @beafialho based on discussion in Slack.

**Comment by kjellr** [comment]
As noted on slack, we should aim to build these header template parts in such a way that if the user applied a background, it'll "just work" and be full width.

**Comment by supernovia** [comment]
Can we do the same with cover blocks? I can't think of many cases where people want cover blocks (whether in the template or not) to leave margins when they're full width.

**Comment by MaggieCabrera** [comment]
> Can we do the same with cover blocks? I can't think of many cases where people want cover blocks (whether in the template or not) to leave margins when they're full width.

Cover blocks that are set to full width are supposed to go all the way to the edges of the viewport: pcrugM-lB-p2

**Comment by supernovia** [comment]
Oh, you're right -- it is just when the cover block is in the header or footer that it's stuck with funny margins.

**Comment by supernovia** [comment]
Would we also consider allowing the header to be wide width, while we're at it? Just in case someone needs that for their design.

**Comment by supernovia** [comment]
(I've tried adding items to columns or groups and setting wide width on that, but can't)

**Comment by scruffian** [comment]
Closing in favour of https://github.com/Automattic/themes/issues/5119
