### ISSUE TITLE
Radcliffe 2: Headstart text should not reference the theme directly

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#509]
## Steps to replicate

1. Create a new WordPress.com site that starts out with Radcliffe 2 installed
2. Observe the demo text that is populated, referencing Radcliffe 2 and linking to the theme showcase
3. Switch to any other theme and the Radcliffe 2 text is still there.

## Screenshot

http://cld.wthms.co/VTmjGF

## Expected

Theme headstart text should not be theme-specific. It should apply to any theme.

Could we change this text to something that does not specifically mention a theme, since the text remains when the user switches?

* Follow-up ticket: none, just my observation

**Comment by torres126** [comment]
I recall a few threads of confusion over this in the forums, here's one: https://en.forums.wordpress.com/topic/wrong-theme-13/

**Comment by torres126** [comment]
I wonder if the link should be updated to https://learn.wordpress.com

**Current:**

> For a starter guide to WordPress.com and to learn more about this theme go to:
> 
> https://wordpress.com/themes/radcliffe-2
> 
> You're now ready to make the text on this page your own. Open this page by clicking the 'Edit' button 👇 below to change the text on this page.

**Possible:**

> For a starter guide to WordPress.com, head to:
> 
> https://learn.wordpress.com
> 
> You're now ready to make the text on this page your own. Open this page by clicking the 'Edit' button 👇 below to change the text on this page.

I'm not too sure though, does this repo allow for a copy review? 

(cc @michelleweber, @clucasrowlands, @kristastevens)

**Comment by michelleweber** [comment]
It's generally fine, though I'd love to tweak it just a little bit:

> You're ready to add your own words and images to this page! Open the editor by clicking the Edit button below, and make this page your own. (And for a general WordPress.com get-started guide, head to learn.wordpress.com.)

**Comment by laurelfulford** [comment]
Thanks @torres126 and @michelleweber!

**Comment by laurelfulford** [comment]
The text still says 'below' which isn't always the right spot for the edit link, so reopening!

**Comment by torres126** [comment]
@laurelfulford Happy to propose a PR done for this unless you intend to already, is this just a matter of removing  the word "below"? The Edit button already seems fairly easy to find without that additional guidance.

Nothing that I can't reproduce a scenario without the Edit button being anywhere other than below though.

**Comment by laurelfulford** [comment]
I've committed a fix for this on WP.com in r53328-wpcom-themes.

> Nothing that I can't reproduce a scenario without the Edit button being anywhere other than below though.

Thanks for offering to look at this one, @torres126! The text isn't an issue when a site is using Radcliffe 2, but the headstart content isn't automatically overwritten when someone switches themes. So the 'below' works with Radcliffe 2 but not necessarily all other themes.
