### ISSUE TITLE
Resonar: Images aren't aligned at galleries with size set to full

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#510]
## Steps to replicate

- Create a page and add a one column gallery with size set to full in the classic editor, like:

`[gallery columns="1" size="full" ids="5204,2996,5697"]`

## Result

<img width="1280" alt="captura de tela 2019-01-25 as 11 32 13" src="https://user-images.githubusercontent.com/3521683/51749921-cf34b800-2097-11e9-85e9-8e99f328cb95.png">

## Expected

<img width="1280" alt="captura de tela 2019-01-25 as 11 55 14" src="https://user-images.githubusercontent.com/3521683/51750056-1d49bb80-2098-11e9-8aba-85807593b182.png">

* User report: #1746840-zd
* Follow-up ticket: #1746840-zd

**Comment by laurelfulford** [comment]
This looks like an issue with the theme's JavaScript to make images larger -- in the function `bigImageClass()`it doesn't check if an image is in a gallery, only that it has the `.size-full` class.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
