### ISSUE TITLE
Blockbase & related Universal Themes:  Site Logo block does not resize in the header.

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/themes#5118]
I originally encountered this on Geologist, but was able to reproduce on Blockbase as well.

When running the theme in FSE mode (Toggle "Appearance" -> "Site Editor" to ON in your local wordpress install), the site logo block is not resizable when it is inside the row block inside the header.  This seems like it may be the result of over-restrictive CSS that does not play well with user controls available in FSE.

Site logo in its default position inside the row block in the header is not resizable:
![Screen Shot 2021-11-29 at 2 03 38 PM](https://user-images.githubusercontent.com/28742426/143927316-abf3af11-574c-400f-a38a-dfd0b2704b6d.png)

Once moved outside of this specific area, it resizes as expected:
![Screen Shot 2021-11-29 at 2 03 54 PM](https://user-images.githubusercontent.com/28742426/143927357-3fe3dbfa-9750-4b29-aaf2-58831d53aea9.png)

**Comment by pbking** [comment]
I believe this has been address by https://github.com/Automattic/themes/pull/5145 and can be retested.

**Comment by scruffian** [comment]
Confirmed.
