### ISSUE TITLE
Blockbase & Related universal themes:  Header is not full width / alignment unchangeable

### ISSUE THREAD

**Issue by Addison-Stavlo** [Automattic/themes#5119]
In Blockbase and related child themes the header does not fill the width of the screen in-editor nor in the rendered front end. 
 MORE IMPORTANTLY, this style seems hardcoded and can not be edited by the user in the block editor.  This can easily be seen if we customize our header with a background color (or similarly with the recent removal of block specific styles for the template part; the background color of a group, row, or other internal block wrapping the entire content):

![Screen Shot 2021-11-30 at 6 56 12 AM](https://user-images.githubusercontent.com/28742426/144043091-376b39ae-d46a-4017-a5cb-37a58f31fbac.png)
![Screen Shot 2021-11-30 at 6 57 32 AM](https://user-images.githubusercontent.com/28742426/144043276-5ac64745-8d02-4c0d-9ed5-19e3e26d704c.png)

### Expected Behavior

Header width should not be hardcoded or restricted by CSS and should be customizable by the user.  If the design requires space on either side of the header, then the header block should be inside a group block which can be used to control this alignment on the template.

### Example with tt1-blocks.

The default header with a background color set is full width:
![Screen Shot 2021-11-30 at 7 04 07 AM](https://user-images.githubusercontent.com/28742426/144044116-4e43f7b2-0c71-4b33-91a6-a1793e0fd74d.png)

Wrapping the header in a group block can achieve this non-full width design of Blockbase, while still giving the user the ability to change this setting:

![Screen Shot 2021-11-30 at 7 05 43 AM](https://user-images.githubusercontent.com/28742426/144044315-42e48e12-8eab-4fc7-a2e2-8d9adc697de0.png)

**Comment by MaggieCabrera** [comment]
Related to https://github.com/Automattic/themes/issues/5087 and https://github.com/Automattic/themes/issues/5078

**Comment by Addison-Stavlo** [comment]
> Related to #5087 and #5078

Thanks @MaggieCabrera !  
To elaborate a bit:  

>  #5087

I think this problem is less about adding more template parts, and more about using blocks and block settings to achieve the initial styles we want where appropriate over any hard coded CSS (I believe [this issue](https://github.com/Automattic/themes/issues/5118) may have a similar cause as well).  This alignment issue should be resolvable for everyones needs without relying on additional template parts.

> #5078

May be another symptom of this cause.

**Comment by matiasbenedetto** [comment]
A potential fix for the width issue: https://github.com/Automattic/themes/pull/5121

**Comment by matiasbenedetto** [comment]
A potential fix for the justification issue: https://github.com/Automattic/themes/pull/5120

**Comment by scruffian** [comment]
This was closed by #5145
