### ISSUE TITLE
Blockbase: Fatal error with WP5.9 beta-1

### ISSUE THREAD

**Issue by tinjure20** [Automattic/themes#5130]
While I was exploring [WP 5.9 Beta-1](https://wordpress.org/news/2021/11/wordpress-5-9-beta-1/) and testing Blockbase 2.0.0, I detected fatal error. Thought to share with team.
## How I Tested

- Installed fresh WordPress site  with WP 5.9 beta 1
- Installed and activated Blockbase 2.0.0

## Result

- Blockbase installation and activation showed no error.
- Front end (Chrome, Firefox) shows the following fatal error (screenshot below)
- WP5.9 beta-1 bundled TT2 shows no error and works as expected.

My testing environment (windows 10, WP5.9 beta 1, PHP 7.4.1, Blockbase 2.0.0, TT2 bundled)

Error Screenshot:
![bbwithwp5 9](https://user-images.githubusercontent.com/59660253/144286298-16452ad2-2701-48da-a90e-a0292773849b.png)

**Comment by kathrynwp** [comment]
Hi @tinjure20 - thanks for the report, and apologies for the belated reply.

I tested the latest version of Blockbase, v. 2.0.38 – with WordPress 6.0 and no plugins active.

I spot-checked my test site, but I'm not seeing any fatal errors. Could you please confirm that everything looks OK to you as well? 

If you still get a fatal, could you please provide full steps to replicate? I'll be glad to take another look. Thanks!

**Comment by pbking** [comment]
Thank you for checking up on this @kathrynwp. We addressed this a bit ago, I believe we can close this.  We are now checking for the activated gutenberg plugin before trying to [manipulate the navigation block](https://github.com/Automattic/themes/blob/trunk/blockbase/functions.php#L156).  I'm going to go ahead and close this one but @tinjure20 please re-open if we've missed something.
