### ISSUE TITLE
WP Admin > Appearance shows Editor (Beta) link twice. 

### ISSUE THREAD

**Issue by bph** [Automattic/themes#5131]
## Steps to replicate
Howdy, I just noticed on my test site, that when Geologist theme is installed and the Gutenberg plugin is active on a WordPress 5.9 beta site, the Appearance menu has the Editor (beta) link twice. 

## Result

<img width="178" alt="Screen Shot 2021-12-01 at 5 36 52 PM" src="https://user-images.githubusercontent.com/39980/144326315-c7257d51-b640-46b4-b0fa-945fc9ff5b5a.png">

## Expected
to only see it once :-)

## Version: 
WordPress 5.9-beta1-52296 
Gutenberg Nightly (trunk from today) 
Geologist 1.0.15

**Comment by courtneyr-dev** [comment]
I had the same experience today with 5.9 RC1, Blockbase Version: 2.0.4, Gutenberg Nightlies Version 12.4.20220105

**Comment by bph** [comment]
It also happens with 
WordPress 5.9 RC1 
Gutenberg 12.3 plugin installed

**Comment by courtneyr-dev** [comment]
I just noticed the differences in the links to Editor (beta).

1. wp-admin/site-editor.php
2. wp-admin/themes.php?page=gutenberg-edit-site

**Comment by courtneyr-dev** [comment]
Tested with WP 5.9 RC2 and Gutenberg Nightlies Version 12.4.20220111. There is now only one instances of Editor and it uses the link wp-admin/themes.php?page=gutenberg-edit-site. 

![image](https://user-images.githubusercontent.com/5519705/149146918-c00d8630-2e05-476c-bf31-377ca9d83199.png)
