### ISSUE TITLE
Barnsbury: Widgets in footer appear in a single left-aligned column.

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#5132]
## Steps to replicate
1 - Activate Barnsbury
2 - Add a few widgets

## Result
The widgets are all lined up on the left side of the screen at 50% width

## Expected
Given that they are only 50% of the screen width, it looks like they were supposed to either sit in the center, or be arranged in some sort columns.
<img width="1061" alt="Screen Shot 2021-12-01 at 8 07 42 PM" src="https://user-images.githubusercontent.com/3476361/144350613-dc9d7c93-9e06-458e-a5c2-9f0e98a91b7a.png">

A user in this thread tried to set up their own three-column widget using blocks, and that was squished to the left, too.
<img width="1064" alt="Screen Shot 2021-12-01 at 7 56 09 PM" src="https://user-images.githubusercontent.com/3476361/144349421-8e0034b9-5863-4e2c-9cf0-53c662d6eeb0.png">

* User report: https://wordpress.com/forums/topic/my-footer-isnt-full-width-and-im-not-sure-why/
* Follow-up ticket: ^ same

**Comment by jordesign** [comment]
Scrubbed and confirmed this behavior. Seems specific to Barnsbury (not present in Varia parent theme).

Barnsbury has 272,974 installs.

**Comment by poeticabdul** [comment]
Reported here 4791633-zen

**Comment by the-misha** [comment]
User report: 2201689-hc

User requests follow-up when issue is resolved: 4939615-zd-woothemes
