### ISSUE TITLE
Move Payton and Kerr from /pub to /premium

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5140]
## Tracking notes for the task.

For the themes Payton & Kerr...
* Remove from SVN /pub
 Remove Payton from /pub: D71006-code
 Relmove Kerr from /pub: D71010-code

* Add to SVN /premium
Add Payton to /premium: D71005-code
Add Kerr to /premium: D71011-code

* Remove from GITHUB
https://github.com/Automattic/themes/pull/5142

**Comment by pbking** [comment]
Note that I have REMOVED the scss files used to build the `theme.css` files.  Those resources are quite small in both themes and my understanding is that they are intended to be changed manually as-needed.  The presence of the /scss files likely just complicated things unnecessarily in this case.  If they should be returned please let me know and I'll get them into the /premium repository.

**Comment by alaczek** [comment]
I'm having trouble testing the patches on my sandbox, so I wasn't able to test-drive this. Removing the scss files makes sense to me, but I think there's one more change needed - the `Template` in style.css needs to be `pub/blockbase`, not `blockbase`.

**Comment by pbking** [comment]
@alaczek my understanding was that these themes couldn't be activated and evaluated until they are deployed at least once, so I was unable to test-drive that either; at least until the themes are transitioned.  I'm specifically concerned with the `Template` value as well but expected that any changes to make that work with the parent theme being in another folder could happen after the changes are at least topically confirmed as correct.

**Comment by alaczek** [comment]
I deployed the changes to Payton and updated the path to template. It looks clear, so I'll do the same with Kerr now.

**Comment by alaczek** [comment]
Kerr is now moved as well. This is good to close.
