### ISSUE TITLE
Blank canvas: post comment block alignment issue

### ISSUE THREAD

**Issue by simison** [Automattic/themes#5146]
## Steps to replicate

- Blank canvas theme
- Add Comments block in page content, publish
- Look at the site's frontend

## Result

Alignment is broken, see demo site https://nyiriland.wordpress.com/

<img width="1067" alt="Screenshot 2021-12-03 at 23 51 12" src="https://user-images.githubusercontent.com/87168/144677597-680a370a-15d0-4c98-b192-28584986fc0f.png">

## Expected

Comments should look like they do without using the block:

<img width="774" alt="image" src="https://user-images.githubusercontent.com/87168/144677745-b37971ae-61f4-4912-b4dd-82fe9981de9e.png">

* Originally reported at p4Kr4c-3Z5-p2/#comment-21178 by @Nyiriland

**Comment by cbravobernal** [comment]
Hi there!

It seems that we have a couple of styles on the Editor that is interfering. As they add a previous class, inheritance is taking the editor as the main one.

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-comments/style.scss#L32

https://github.com/WordPress/gutenberg/blob/trunk/packages/block-library/src/post-comments/style.scss#L50

Attach a screenshot about how it would be if we disable those styles:
<img width="1558" alt="Screenshot 2021-12-03 at 23 06 18" src="https://user-images.githubusercontent.com/37012961/144679161-f4567de3-aab7-4386-bddc-69adf1569a34.png">

What would be the best way to proceed there?

**Comment by simison** [comment]
Thanks for the quick fix! Note that this caused some follow-up needs described in https://github.com/Automattic/themes/issues/5225 🙂
