### ISSUE TITLE
Geologist: Create color variation themes

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5156]
We should create four color & font variations of the Geologist Theme. (We already have one White color variant, which is named Zoologist)

## Yellow

Color:

- Primary: `#000000`
- Secondary: `#333333`
- Background: `#FFF975`
- Tertiary: `#FFFFFF`

Font: 

- "Helvetica Neue", "Helvetica", "Arial", Sans-serif

Other Settings

- Heading, Post Title blocks:
    - Font Weight: Bold (700)

Screenshot: 

![yellow](https://user-images.githubusercontent.com/1202812/145056419-4db86a79-89c9-49b5-9366-62697d5e9786.png)

## Blue 

Color:

- Primary: `#F5F0E5`
- Secondary: `#FFFFFF`
- Background: `#424CBF`
- Tertiary: `#383E89`

Font: 

- "IBM Plex Mono", "Courier New", "Courier", monospace

Other Settings: 

- Site Title: 
    - Text transform: None
- Heading, Post Title blocks:
    - Font Style: Italic
    - Font Weight: Normal

Screenshot:

![blue](https://user-images.githubusercontent.com/1202812/145056747-6883c5a1-d1e3-443f-9c0e-c96a6b29473b.png)

## Cream 

Color:

- Primary: `#000000`
- Secondary: `#333333`
- Background: `#FFFAED`
- Tertiary: `#FFFFFF`

Font: 

- "Source Serif Pro", serif

Other Settings: 

- Site Title: 
    - Text transform: None
- Heading, Post Title blocks:
    - Font Style: Italic
    - Font Weight: Normal

Screenshot: 

![cream](https://user-images.githubusercontent.com/1202812/145056891-b967786d-0b86-452e-a634-80413fce6e8f.png)

## Slate 

Color:

- Primary: `#FFFFFF`
- Secondary: `#FEF6B2`
- Background: `#192833`
- Tertiary: `#000000`

Font: 

- "Rubik", sans-serif

Other Settings: 

- Global Link Color: Secondary
- Heading, Post Title blocks:
    - Font Weight: Light (300)

Screenshot: 

![slate](https://user-images.githubusercontent.com/1202812/145057030-55be7af6-f0c3-4de6-9a09-935c75516ad6.png)

**Comment by scruffian** [comment]
@kjellr these variations don't have foreground colors and I think they need them. I've added #FFFFFF for now.

**Comment by kjellr** [comment]
Oh that's weird. For all of these, `Primary` should be the same as `Foreground`. 

FWIW, I defined the colors based on the palette names I saw here. Geologist doesn't have a Foreground color listed: 
 
<img width="300" alt="Screen Shot 2021-12-10 at 9 39 10 AM" src="https://user-images.githubusercontent.com/1202812/145591296-91ffa017-0461-4152-9008-b36d3cb7a128.png">

**Comment by pbking** [comment]
`foreground` is just mapped to `primary` in geologist's theme.json file.  But so is `secondary` which means that secondary is never used in Geologist.  Which seems wrong.  If that's the intent of Geologist then we should just remove secondary.  Otherwise we should fix that mapping.  The Geologist children should be fine to have those same colors.

**Comment by kjellr** [comment]
Some of the children may use Secondary, so I wouldn't remove it entirely.

**Comment by pbking** [comment]
In the variations change secondary is now appropriately mapped (in Geologist and thus all of the variations) and 'foreground' takes the 'primary' color so those variations also don't list a "foreground" color.
