### ISSUE TITLE
All blockbase children should use single/page.html rather than singular.html

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5157]
Seedlet uses a `singlular.html` block template, however -  because of how child themes operate - a single/page.html template is always available from blockbase so no blockbase child will ever be able to use a singular.html template.

The only difference I can see between blockbase's `single.html` and `page.html` is the presence of the `post-meta-icons` template part and the comments block.  That might be reason enough to introduce the limitation, but in that case Seedlet-blocks should be refactored to no longer use `singular.html` templates.

**Comment by kjellr** [comment]
I think in general, we should probably move away from using `singular.html` templates — it doesn't make sense to include (for example) post date, categories, or tags blocks on a template used for pages.

**Comment by pbking** [comment]
Groovy.  Sounds good, thanks for confirming @kjellr.  That makes sense to me too.  I've already changed Seedlet in [another issue](https://github.com/Automattic/themes/pull/5145) so if that lands we can close this.
