### ISSUE TITLE
Alto Focus theme has full-width template tag in error

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/themes#5161]
## Steps to replicate
Open Alto Focus theme page ( https://wordpress.com/theme/altofocus/mariaianne.com ).  Scroll to the bottom and see Full Width Template listed under features.

Install and activate Alto Focus.  Go to a page and try to change the template to full-width.

## Result

No templates exist.

## Expected

Templates should exist, in particular the full width. 

* User report: hc-33103599 but also in 2018 in this forum post: https://wordpress.com/forums/topic/alto-focus-theme-full-width-gallery-page/
* Follow-up ticket: none

**Comment by jordesign** [comment]
Good catch @paxblueribbon !

I've changed this so the 'Full-Width Template' tag no longer shows
