### ISSUE TITLE
Zoologist: Accented/special characters and emojis are broken in site menus

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/themes#5162]
### Steps to reproduce

1. Activate the Zoologist theme
2. Edit an existing menu item with an accented character (such as é) or an emoji (such as 🙂 ).
3. _Alternatively_, add a special character/emoji to a page's title and then add that page to your site's menu.

### What you expected to happen

Accented characters and emojis should display as entered:
![Screen Shot 2021-11-30 at 17 59 22](https://user-images.githubusercontent.com/5630717/144127555-ec9aa6d4-a330-4349-9ad1-35ad0bcd3dde.png)

### What actually happened

Accented characters and emojis are broken: 
<img width="492" alt="Markup 2021-11-30 at 16 04 02" src="https://user-images.githubusercontent.com/5630717/144127832-11bfb5d6-ecbd-42b2-8087-3c4f79c271b9.png">

### Context

4557764-zen

### Theme-specific issue?

Zoologist theme

### Browser, operating system and other notes

Note: I _was not_ able to reproduce this on a test site of my own, but another HE was with a similar setup. See p1638304987112100-slack-C03TY6J1A.

### Reproducibility

Consistent

### Severity

Some (< 50%)

**Comment by Greatdane** [comment]
Update; It actually seems to be related to the newer themes, not sure if they are all a child.
They did not render on; **Zoologist, Russell, Quadrat, Geologist**

**Comment by daria2303** [comment]
This is a case with Russel theme 4580608-zd-woothemes
