### ISSUE TITLE
Blockbase: initial menu state confusing

### ISSUE THREAD

**Issue by creativecoder** [Automattic/themes#5177]
## Steps to replicate

- Activate Blockbase or one of it's children
- Open the Site editor

## Result

The menu has placeholders rather than pages.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1699996/145463434-003f05bd-467c-4468-9a19-5bcd3284e20c.png">

Clicking into the block offers these choices, which were confusing in user testing

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1699996/145463540-50d7ebcf-efcb-4cca-a99a-ae363159ad80.png">

## Expected

The menu shows a list of page links. (The state after you choose "Add all pages", then "Edit" in the toolbar to convert to links.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/1699996/145464414-ba988c1d-3129-4977-aba7-9d9148e09d9e.png">

---

Could we set up the theme to start with the menu as a set of page links?

Should this be at the theme level or something we do with starter content on WP.com?

User reports: 
- paYE8P-1ek-p2#confusion-about-the-initial-state
- aYE8P-p2?p=4882&preview=true#idea-3

**Comment by Addison-Stavlo** [comment]
Noting that now with placeholder changes the initial state looks like this:
![Screen Shot 2022-06-23 at 7 46 42 AM](https://user-images.githubusercontent.com/28742426/175291563-69325018-580f-4e76-898a-18286f134f8f.png)

Its a bit more clear from the non-selected placeholder side, and the setup interaction seems more friendly.

I think this is fair to close given the above changes, the lack of recent activity on the issue, the focus towards building more block (non-universal) themes, etc.
