### ISSUE TITLE
Varia Themes: Multuple issues with handling of Cover Block colors

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#5182]
This is an umbrella issue to gather multiple open issues related to the current handling of Cover blocks by Varia. 

1. At some point it appears that the default text color display of Varia themes became different between the editor (where it appears white) and the front end (where it appears dark grey). The symptoms of this are reported in 2 different issues:

o https://github.com/Automattic/themes/issues/5181
o https://github.com/Automattic/themes/issues/4993

2. It appears that Varia themes don't adjust the font color for contrast when the opacity of the cover overlay changes, or the darkness of the background color itself changes.. 

o https://github.com/Automattic/themes/issues/5051

**Comment by jordesign** [comment]
I've got a test page/site up specifically for this if it helps
PdA1qf-f-p2

**Comment by scruffian** [comment]
I think we can fix this by removing the extra code that is targeting cover blocks as part of color annotations. The problem is that it will change the frontend for some users, so I'm not sure if its a good idea...
