### ISSUE TITLE
Professional Business: missing download file at setup page

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#519]
## Steps to replicate

Go to the theme setup page and look for the download theme button
https://wordpress.com/theme/professional-business

## Result

Link is broken, 404 page.
Link: https://downloads.wordpress.org/theme/professional-business.zip

* User report: #1753298-zd

**Comment by laurelfulford** [comment]
This has been resolved! 

 https://downloads.wordpress.org/theme/professional-business.zip will continue to return a 404 (this is normal for all themes), but the Download button on the showcase now will download a copy of the theme.
