### ISSUE TITLE
Radcliffe 2: Headstart message confusing when users switch themes

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#521]
## Steps to replicate

1. Activate Radcliffe 2 on a new site.
2. Switch to another theme

## Result

Default text linking to Radcliffe 2 showcase page is still visible:

![hundaholmi](https://user-images.githubusercontent.com/7662449/51925548-54cca680-23bd-11e9-913a-e2fec65784e6.jpg)

## Expected

There should not be Radliffe 2-specific info visible when the active theme is no longer Radcliffe 2.

This has tripped up many users and could be easily fixed by updating the Headstart file.

Latest report in 1758648-zd

**Comment by torres126** [comment]
Wasn't this fixed in #511? (Duplicate of #509 btw, though that's closed due to #511)

**Comment by kathrynwp** [comment]
Thanks! I looked for open tickets but missed the closed one. The user in 1758648-zd created their site prior to the Headstart update 4 days ago. Glad to see this has been fixed.
