### ISSUE TITLE
[Livre] Design and implement drop-cap

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5216]
Drop caps are currently turned off for Livre. That's just a remnant of some Twenty Twenty-Two code though. I need to work on re-enabling that and ensuring that drop caps appear as intended.

**Comment by sharonlaker19** [comment]
Hey @kjellr or @scruffian is it intentional for the Twenty Twenty-Two theme to not have drop caps? I'm working on a site in 5167660-zen that doesn't have this option under Typography and I am able to replicate on my test site as well. Should I file a new bug report?

**Comment by scruffian** [comment]
It looks like it was a deliberate decision
