### ISSUE TITLE
[Livre] Look into using small caps instead of italics

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5217]
Look into opportunities to use small caps in Livre.

**Comment by kjellr** [comment]
I tried out a few options here, and I think using all caps for _just_ the site title seems like the best route: 

Current|🌟 Recommended
---|---
![Screen Shot 2022-01-04 at 14 10 56](https://user-images.githubusercontent.com/1202812/148111389-3a896d70-3fc5-472d-a153-dbce57174637.png)|![Screen Shot 2022-01-04 at 14 06 53](https://user-images.githubusercontent.com/1202812/148111402-f6773071-f18f-42c5-b7c1-154d5d8371d1.png)

I would've preferred to use a small caps variant instead of all-caps, but Newsreader doesn't have one. I think this works pretty well though. 

I also tried using all-caps for the post date, but I thought it was a little too much:

![Screen Shot 2022-01-04 at 14 08 45](https://user-images.githubusercontent.com/1202812/148111487-461d4dff-b265-494d-8725-2e11af57d863.png)

We could consider changing the comments headers to be all-caps, but I'm not sure I like it: 

<img width="785" alt="Screen Shot 2022-01-04 at 2 20 20 PM" src="https://user-images.githubusercontent.com/1202812/148112456-29fef1de-f315-439b-b1ee-b0eef70d35bd.png">

So for now, I think just changing the site title makes sense. @beafialho what do you think?

**Comment by beafialho** [comment]
I agree, changing just the site title looks elegant. Everywhere else I really like how italics look 👍
