### ISSUE TITLE
Blank Canvas 2: Rename to Blank Canvas Blocks

### ISSUE THREAD

**Issue by jeyip** [Automattic/themes#5219]
Per our discussions in P2s and slack, we want to settle on a common slug for all FSE versions of themes. We've decided to add a trailing `-blocks` suffix. Because of this, we should rename `blank-canvas-2` to `blank-canvas-blocks`.

- pNEWy-exw-p2#comment-53986
- p1639648911155000/1639573034.112300-slack-C029FM1EH

**Comment by creativecoder** [comment]
@jeyip @zaguiini I think only the slug was supposed to change to `blank-canvas-blocks`, and the theme name should be the same as the previous one, "Blank Canvas". This theme will be available to non-FSE beta sites, so I think having "Blocks" in the name will be quite confusing for those users.

@scruffian @jeffikus  @kjellr for confirmation.

**Comment by scruffian** [comment]
Done here: https://github.com/Automattic/themes/pull/5230
