### ISSUE TITLE
Baskerville 2: Text-Shadow Value Error Found Through W3C Validator

### ISSUE THREAD

**Issue by darnelldibbles** [Automattic/themes#522]
## Steps to replicate

The user found errors while running their site through the [W3C Validator](https://jigsaw.w3.org/css-validator/validator?uri=www.imageearthtravel.com&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en) for her Baskerville 2 theme:

`Value Error : text-shadow Too many values or values are not recognized `

## Result

I reported it through Kathryn (p1548800215112100-slack-css-help) who thought that it [may be a bug](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow). Verified that it indeed was a bug (p1548802067991000-slack-themes) and to report it.

* User report: [forum thread](https://en.forums.wordpress.com/topic/baskerville-2-w3c-validation-error-warnings/)
* User's site: http://imageearthtravel.com/

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
