### ISSUE TITLE
Blockbase: add additional block-based footer layouts

### ISSUE THREAD

**Issue by creativecoder** [Automattic/themes#5227]
Blockbase has only one footer layout, and needs additional footer layouts.

When there are multiple options for a template part, the Template Part block toolbar will show a replace button, making it easy to replace the default layout with another one.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/1699996/146702647-e1ba31aa-8ab9-4085-81e0-49939edb5fbb.png">

However, that interface doesn't show when only one layout is packaged with theme.

I saw users struggle to design a footer layout in the Site editor in recent testing. Most often, they seem to want to add additional columns to the footer.

What about adding 2-3 additional footer layouts with different column options? This would provide additional footer layout options for all our universal themes.

**Comment by MaggieCabrera** [comment]
This is a good idea, I think we could bring Skatepark's footer to Blockbase too as a 3 column example. Keen to hear design ideas @kjellr and @beafialho

**Comment by kjellr** [comment]
Yeah — we should add more. We can probably borrow from Twenty Twenty-Two as well. But I think they should actually be patterns, not template parts.

**Comment by creativecoder** [comment]
> But I think they should actually be patterns, not template parts.

For me, the important part is that the flow for changing the existing template part is easily discoverable, like the screenshot with the replace button in the issue description. I don't think patterns get us that discoverability right now, but I haven't tested.

**Comment by kjellr** [comment]
Yeah, pattern discovery at the moment is limited. But there are already explorations to try and improve that: https://github.com/WordPress/gutenberg/issues/31747#issuecomment-948601592

**Comment by MaggieCabrera** [comment]
I'm closing this one since we already included multiple footers and headers for Blockbase
