### ISSUE TITLE
Videomaker: check Blockgap usage after GB change

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5228]
After https://github.com/WordPress/gutenberg/pull/37459 was merged there are a few instances where we are overriding the theme's blockGap that won't work anymore:

Before | After
--- | ---
<img width="1759" alt="Screenshot 2021-12-20 at 09 56 11" src="https://user-images.githubusercontent.com/3593343/146739990-93e0635b-3364-4f58-97cc-9d3451bc749a.png"> | <img width="1479" alt="Screenshot 2021-12-20 at 09 55 52" src="https://user-images.githubusercontent.com/3593343/146739996-1617cb74-c117-4063-a95c-b9b143388017.png">

It also looks like the Footer's markup is invalid, I think this is related to blockGap but not to the PR mentioned before:

<img width="890" alt="Screenshot 2021-12-20 at 09 53 18" src="https://user-images.githubusercontent.com/3593343/146739634-42f916de-1cc8-4150-9fae-4e6f7d00de31.png">

**Comment by MaggieCabrera** [comment]
Related to the patterns that use the Columns block: https://github.com/WordPress/gutenberg/pull/37436

**Comment by jeffikus** [comment]
Let's try;
- Regenerate Videomaker Headstart from the demo.
- Regenerate Videomaker White Headstart from the demo.

**Comment by scruffian** [comment]
I don't see any issues here. Please could you confirm?

**Comment by MaggieCabrera** [comment]
yeah I don't see the issues, we can close this
