### ISSUE TITLE
Baskerville 2: Improvement—Add an option to disable the black overlay in the header

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#524]
## Steps to replicate

To replicate this please add a header image by clicking on "My Site" > Customize > Header Image.

## Result

You'll notice a black overlay on the image.

## Expected

To see an option to enable/disable the overlay.

* User report: 3023893-hc

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
