### ISSUE TITLE
Lodestar: Images break when displayed in two columns in panel

### ISSUE THREAD

**Issue by yashitamittal11** [Automattic/themes#525]
When a page with both the text and the images is displayed in two columns, the images breaks between the two columns.

 **Steps to replicate**
1. Go to My Sites >> Site Pages >> Add and create a page
2. Create a paragraph block and add some text to it
3. Create a Gallery block beneath the paragraph block and add 3-4 images to it or you can also add two Gallery blocks consecutively and add two images in each.
4. Publish the page
5. Go to My sites >> Customize >> Theme Options >> Panel 1
6. Select the above-created page and select *Two Column* in Panel Layout and publish the changes.
7. View the front page on the site

## Result

The images in the Gallery doesn't display properly and breaks between the two columns. The top of the image is in one column, and the rest of the image has moved to the second column.

![front page](https://cloudup.com/cURtdnt5nuU+)

## Expected

The images should display in the second column and the top of the images should not be cut off.

Discussion on Slack - p1548933054037300-slack-themes
Ticket - 1763529-zd
Chat - 9995766-hc
User's site- https://aarushgopal.com/

**Comment by allancole** [comment]
Yup, I can replicate this one. 

![image](https://user-images.githubusercontent.com/709581/52230024-5c3ff400-2884-11e9-8fa6-007a281a9bb7.png)

**Comment by laurelfulford** [comment]
Adjusting the priority, since this isn't an issue isn't Gutenberg blocks specifically, but Lodestar's own two column option in the Customizer -- it would break up regular images, too.

**Comment by allancole** [comment]
Ahh, got ya 👍

**Comment by alaczek** [comment]
I've found a solution and will be committing shortly. The only downside I'm seeing, is it might create unbalanced columns, like these, but I don't think there's much we can do about that:
![image](https://user-images.githubusercontent.com/4550351/52314617-a00f3680-2a07-11e9-9222-331e6a102b68.png)

![image](https://user-images.githubusercontent.com/4550351/52314644-bd440500-2a07-11e9-991e-15ddf3887f4b.png)
