### ISSUE TITLE
Duotone: Overlay not showing as expected on the front end. 

### ISSUE THREAD

**Issue by sstabrizi** [Automattic/themes#5259]
### Quick summary

Duotone is working properly when added to a cover block in the editor. However, when looking at the cover block on a live site duo tone is not applied at all. 

### Steps to reproduce

1. Add Cover block.
2. Add Duotone of choice.
3. Update the page.
4. View the page live and see that Duotone isn't applied.

### What you expected to happen

Duotone settings should be the same on the live site as they are in the editor.

### What actually happened

Duotone shows one way in the editor, but is not applied on the front end. 

### Context

- Two reports of this: 4634506-zen, 4634686-zen
- We've confirmed that this is the case on at least 3 themes: Arcane, Seedlet, and Hever. 

### Simple, Atomic or both?

Simple

### Reproducibility

Consistent

**Comment by lizkarkoski** [comment]
Another  instance of duotone failing to display outside of the editor. Site is using seedlet theme. 
https://wordpress.com/forums/topic/duotone-now-not-working-on-my-site-suddenly/?view=all#post-3773186

**Comment by zdenys** [comment]
Another case: 4652083-zd-woothemes with theme Illustrar.

**Comment by zdenys** [comment]
The core issue is here: https://github.com/WordPress/gutenberg/issues/37598

**Comment by jordesign** [comment]
As this isn't a core issue - I'm closing it in favour of the WP-Calypso issue we'll use to track the core issue
https://github.com/Automattic/wp-calypso/issues/59787

**Comment by metabreakr** [comment]
https://wordpress.com/forums/topic/duo-tone-image-setting-doesnt-show-on-front-end/
