### ISSUE TITLE
Label Theme doesn't show Pay With Paypal block in sidebar.

### ISSUE THREAD

**Issue by KirkwallDay** [Automattic/themes#5274]
## Steps to replicate

Have a site with the Label Theme active, and then put a Pay With Paypal block in the sidebar widget area.

Widget Settings:
![Screen Shot 2022-01-05 at 9 31 46 AM](https://user-images.githubusercontent.com/49131029/148253864-b3311b58-e3f6-42b0-bcc4-30b6504149c3.png)

Live site:
![Screen Shot 2022-01-05 at 9 32 44 AM](https://user-images.githubusercontent.com/49131029/148253880-2844cc9a-1c07-48a2-8e02-0534933bc1da.png)

## Result

The block does not show up on the sidebar widget area.

## Expected

The block to show up in the sidebar widget area.

* User report: 4661014-zen

**Comment by ghost** [comment]
User report: 28214520-hc
We checked with TwentyTwentyOne and Shawburn too and the block does not show up both for the user's site and my test site too.

Suggesting workaround: There is another way user can add PayPal payments to their sidebar and footer. If they're comfortable copying and pasting a bit of code from PayPal's website, they can use the method outlined here: https://wordpress.com/support/paypal/

**Comment by KirkwallDay** [comment]
Another one here with the Arcane theme: 4679630-zen.

**Comment by aleone89** [comment]
Hello, there's another report here:  zen-4755526 with the natural theme. 

I also stumbled across this GH too: https://github.com/Automattic/wp-calypso/issues/58535

Are these the same issue:

**Comment by syedshaon** [comment]
Another issue: zd#4795194, Apostrophe 2 theme

**Comment by KirkwallDay** [comment]
Looks like it was the same issue as https://github.com/Automattic/wp-calypso/issues/58535 and the fix there has fixed this one too. I can no longer duplicate. Closing this.
