### ISSUE TITLE
Lodestar: Theme ignoring button block styling classes

### ISSUE THREAD

**Issue by nickpagz** [Automattic/themes#529]
User reporting that adding rounded corners (or other styling, such as outline) to buttons in the button block still show as squared (and without oultines if added) in preview and when published. 

Was able to replicate on a test site with the Lodestar theme.

## Steps to replicate

- Create a new post using the new editor
- Add a button block and create a new button. 
- Click on styles, and choose **Rounded**
- Save post (or page), and click on Preview.

Post edit view:
[![oops - image missing](https://cld.wthms.co/MGlNfj+)](https://cld.wthms.co/MGlNfj)

Published post view:
[![oops - image missing](https://cld.wthms.co/5Gsh59+)](https://cld.wthms.co/5Gsh59)

## Result

Square buttons, no outline.

## Expected

Rounded buttons (with outline)

* User report: #1732421-zen

**Comment by laurelfulford** [comment]
Thanks for this report, @nickpagz!

We have a broader issue for this here, since it's pretty wide-spread: #434.

I'm going to close this issue in favour of that one, & will move your report over!
