### ISSUE TITLE
Scratchpad: Header Text Color (self-hosted WP sites) 

### ISSUE THREAD

**Issue by ntpixels** [Automattic/themes#53]
A user has gotten in touch unable to make changes to their `Header Text Color` permanently save through the Customizer.

## Steps to replicate

1. Go to site's Admin Dashboard > Appearance > Customizer > Colors. The default color for `Header Text Color` is `#ffffff`
<img width="1440" alt="screen shot 2018-03-27 at 2 24 33 pm" src="https://user-images.githubusercontent.com/3965153/37995997-2386978c-31cb-11e8-8aac-d12b945c2cc7.png">

2. Edit color to `##3f3f3f`. The change registers in live preview mode + Inspect Element area as `element style {color: rgb(63, 63, 63); }`
<img width="1440" alt="screen shot 2018-03-27 at 2 24 54 pm" src="https://user-images.githubusercontent.com/3965153/37996045-3d84831a-31cb-11e8-9971-030ea40ab1cd.png">

3. Publish the change. It is still registering in the live preview mode.
<img width="1440" alt="screen shot 2018-03-27 at 2 25 08 pm" src="https://user-images.githubusercontent.com/3965153/37996101-621c446a-31cb-11e8-8399-2e346425232e.png">

4. Refresh the Customizer page. The `header color` is still set to `##3f3f3f`, however, the live preview has reverted to `#ffffff` and the Inspect Element area is now showing `.site-title a { color: #3f3f3f; }` as crossed out.
<img width="1440" alt="screen shot 2018-03-27 at 2 25 36 pm" src="https://user-images.githubusercontent.com/3965153/37996428-741a27bc-31cc-11e8-8ca0-99dc3d50d714.png">

## Result

The change to the header text color did not save. But it did register when inspecting the element.

## Expected

The change to the header text color to save.

For the meantime, I've sent the following to allow the user to change the color manually:

```
#masthead .site-title a {
    color: #fff;
}
```

* User report: concierge call / #1046397-zd
* User's site: http://mediacanary.com/ (self-hosted site behind coming soon page)

**Comment by laurelfulford** [comment]
Scratchpad was resubmitted to WP.org here: https://themes.trac.wordpress.org/ticket/52830

The fix will be in v 1.0.6.
