### ISSUE TITLE
Blockbase: Use the Global Styles rest API in the customizer

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#5308]
In  https://github.com/WordPress/gutenberg/pull/35801 a Global Styles API was introduced. We should reconsider the implementation of our Customizer/Global Styles bridge, to take advantage of this new API.

Alternatively we could just use the new style switcher in Gutenberg.

From https://github.com/Automattic/themes/pull/5307

**Comment by MaggieCabrera** [comment]
I agree. Skatepark could have different variations with and without duotone and avoid the customizer route altogether
