### ISSUE TITLE
Snaps: ISSUU embed (iframe) bleeds out of container

### ISSUE THREAD

**Issue by sjaved87** [Automattic/themes#532]
## Steps to replicate

1. Create a post. 

2. Add ISSUU embed link in the post either using the classic block or embed block. 

3. For example, you can use this link from the user site: https://issuu.com/paolasimoni/docs/pif-antinfortunistica as explained [here](https://en.support.wordpress.com/issuu-embeds/ ). 

It works on the page though, where the container width is more than post width. But responsive layout also does not work for mobile.

## Result

On desktops/laptops. This is how it looks: http://cld.wthms.co/3TQjnR, the second page of the embed is cut off and no next previous buttons. 

Same on mobile.

## Expected

It should display like this -> http://cld.wthms.co/TdZwVr

* User report: #10070132-hc
* Follow-up ticket: #1774210-zd

It seems, this issue is related to this one -> https://github.com/Automattic/themes/issues/478

**Comment by laurelfulford** [comment]
Thanks for reporting this issue, @sjaved87!

This isn't just an issue with Snaps -- I was able to recreate some display issues with Twenty Sixteen as well -- it's running into the sidebar:

![image](https://user-images.githubusercontent.com/177561/52282099-6a3d5580-2914-11e9-8aba-9e727907b0e1.png)

It sounds like it's related to this issue with the embed itself: 7766-wpcom.

I'm going to move this report there.

**Comment by sjaved87** [comment]
Hi Laurel,

Thanks for triaging the issue. I forgot to mention that, it worked with TwentySeventeen and Baskerville 2 theme.

But thanks again for moving it to the right place.
