### ISSUE TITLE
Twenty Sixteen: Cookie notice displays border 

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#5340]
## Steps to replicate

* Enable Twenty Sixteen on a free site
* Make sure site is set to public, and not hidden from search engines.
* View site in an incognito browser tab (just to make sure the cookie notice appears)

## Result

A thick black border appears about half a centimetre above the cookie notice, making it appear that a random line is being drawn across the site. Disappears when the notice is dismissed.

![Shift_to_the_left_–_This_is_the_tagline_and_New_Issue_·_Automattic_themes_and_kokkieh_—_-zsh_—_80×24](https://user-images.githubusercontent.com/11873759/149727630-61de2a63-561a-4f65-aba8-384884ba47c1.png)

## Expected

For the notice to appear without the border.

It looks like it's caused by the following CSS being applied to the cookie banner:

`.widget {
 border-top:4px solid #1a1a1a;
 margin-bottom:3.5em;
 padding-top:1.75em
}`

This theme adds a black border above every widget, but this shouldn't be added for the cookie notice.

This does not appear when using the Cookies & Consent widget on a paid site. Only with the default cookie notice that's displayed on free sites.

* User report: https://wordpress.com/forums/topic/display-error-black-line-over-text/?view=all

**Comment by jerrysarcastic** [comment]
This appears to have been fixed in #5349 so closing this issue.
