### ISSUE TITLE
Quadrat: Outdated version in the .org repository

### ISSUE THREAD

**Issue by fresatomica** [Automattic/themes#5342]
## Steps to replicate

Download the theme version from the .org repository.
On a test site, use a non-Latin (Cyrillic) alphabet in the menu.

## Result

The Cyrillic does not display, letters are replaced by other signs. 
When downloading the theme from the WordPress.com library, everything works as expected.

## Expected

On .org you can download the v 1.1.31 of the theme, while on .com 1.1.33 is offered. The .org version should be updated for Quadrat and other block-based themes.

* User report: [link to forum thread](https://wordpress.org/support/topic/errors-2-in-the-quadrat-theme/)

**Comment by scruffian** [comment]
We should automate this: https://github.com/Automattic/themes/issues/5013

cc @pbking

**Comment by scruffian** [comment]
This seems to be fixed now
