### ISSUE TITLE
Various themes: Social icon block padding issue

### ISSUE THREAD

**Issue by i11za** [Automattic/themes#5345]
### Quick summary

Icons in Social Icons Block appear distorted when added to footer widgets area. 

### Steps to reproduce

1. Activate Twenty Seventeen (although got a similar result on Twenty Nineteen) on either a Simple or Atomic site. If on Premium plan and higher make sure there's no Additional CSS related to Social Icons block.  
2. Add a **Social Icons** block under *Appearance → Widgets → Footer 1* or *Footer 2* 
3. Add any social links (one is enough to see the issue, I've been adding two). 
4. Icons appear distorted in both the Customizer and on live site. 

### What you expected to happen

The icons should follow the styles illustrated here: https://wordpress.com/support/wordpress-editor/blocks/social-links-block/

![image](https://user-images.githubusercontent.com/84193945/149654733-2290c383-dc11-44bc-9407-f5fd144a028f.png)

### What actually happened

Icons appear distorted, seems to be two scenarios: 

### Vertical Distortion

In user report (Twenty Seventeen, Personal plan): 
![image](https://user-images.githubusercontent.com/84193945/149654318-a0461540-cf04-4ee1-88a9-5f3d8c886121.png)

On a test Business Atomic site:

![image](https://user-images.githubusercontent.com/84193945/149654483-ef240ff9-49ec-47f8-9d11-679403b844c5.png)

### Horizontal Distortion

Getting a different distortion Personal and Premium plan on test sites: 

![image](https://user-images.githubusercontent.com/84193945/149654339-e7f4c5a4-3984-4b30-9be8-fa83ec4b7a3a.png)

### Context

- **Customer report**: 4689122-zen
- **Internal discussion**: p1642322784296200-slack-C03TY6J1A

### Simple, Atomic or both?

Both

### Theme-specific issue?

Doesn't seem to be theme-specific, able to replicate this on Twenty Seventeen (all plans, both Simple and Atomic), and Twenty Nineteen (Personal plan) as well:

![image](https://user-images.githubusercontent.com/84193945/149654426-43231577-7431-431e-8175-8cce0ead509a.png)

### Error

When attempting to edit the widgets directly via *Appearance → Widgets* in 4689122-zen, the editor crashes consistently, getting the error below. I was unable to replicate this on any of my test sites, so not sure if relevant to the icon style issue:

![image](https://user-images.githubusercontent.com/84193945/149655094-cdd851a7-797f-42a4-891f-ba6e1f666b84.png)

```
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at Sh (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:7:34065)
    at Qj (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:8377)
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302)
    at eb (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:6339)
    at gf (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:8:2335)
    at https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12524
    at unstable_runWithPriority (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react.min.755b0ae9.js?m=1624062436h:5:3609)
    at Za (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12302)
    at $g (https://s0.wp.com/wp-content/plugins/gutenberg-core/v12.3.2/vendor/react-dom.min.edd8b7a6.js?m=1624062436h:6:12470)
```

### Possible Theme Style Issue

Seems to be this padding is the problem: 

![image](https://user-images.githubusercontent.com/84193945/149655210-1809eb91-8d43-4aa4-9dba-bbba1e40372c.png)

The following fixes in console (but not in customizer): 

```
.widget ul li {
	padding: 0;
}
```

Theme stylesheet could be at fault, however the issue doesn't seem to be theme-specific:

![image](https://user-images.githubusercontent.com/84193945/149655255-e8199090-8f26-4130-a709-0b54e66e3a18.png)

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

Easy to implement, but doesn't seem to work consistently, or may not be available depending on plan/theme/etc. 

1. Suggesting to use [Social Links Menu](https://wordpress.com/support/menus/social-links-menu/) when possible as an alternative. 

2. CSS works in browser inspector console (Chrome), but doesn't seem to work when in Customizer → Additional CSS: 

```
> .widget ul li {
> 	padding: 0;
> }
```

**Comment by Robertght** [comment]
I found another case with Lodestar. #4695996-zen

I'm not sure this is theme-specific anymore. 

CC @jeffikus for a second look ( or @chad1008 in case this is more widespread)

**Comment by chad1008** [comment]
Thanks for the report. In my testing (specifically on Twenty Seventeen) I found a few things:

- The distortion appears in the front end, but not the Customizer.
- I'm only able to reproduce the vertical distortion, at no point could I reproduce the horizontal distortion shown above, but I can see how it'd be dependent on an individual theme's styling
- This also happens locally in vanilla WP, it's not WPCOM specific. **[I've reported it in core here](https://github.com/WordPress/gutenberg/issues/38043)**.
- Going back multiple Gutenberg versions (I tested as far as v11.9) I can still reproduce this locally, so it's not new if it's a Gutenberg problem
- The issue appears to stem from the fact that the block applies the background color directly to the `li` element. That element's padding is controlled at the theme level, so if a theme adds CSS to make taller, spaced-out lists (as shown in the screenshots of the original issue above), it leads to the vertically distorted view.

**Comment by i11za** [comment]
Another report here (they reached out regarding something else): 4734838-zen 
Theme: Storefront
Workaround CSS didn't work.

**Comment by happychait** [comment]
33992968-hc

Used the workaround CSS.

**Comment by kylemcph** [comment]
Another report here: 4757850-zen

Used the workaround CSS.

**Comment by i11za** [comment]
Another report here: 34090325-hc and follow up 4761736-zen 

Theme: Twenty Seventeen

Workaround above didn't work, also they wanted to use 'Logo only' style, the CSS below seems to work:

```
.widget ul li, .widget ol li {
    border-bottom: 0;
    border-top: 0;
	  padding: 0;
}
```

**Comment by hacchism** [comment]
Another report here: 34947824-hc
Theme: Twenty Seventeen
Used the workaround CSS.

**Comment by kathrynwp** [comment]
I was able to replicate this with:

WP 6.0.1 - local install
No plugins active
Twenty Seventeen 3.0

I reported the above in the Gutenberg ticket here:

https://github.com/WordPress/gutenberg/issues/38043

I was **not** able to replicate in Twenty Nineteen 2.3, however:

![Self-hosted_Test_–_not_just_another_fake_company](https://user-images.githubusercontent.com/7662449/178781763-e1c43bd7-1abf-4ea0-87e4-9d7082d95ddd.jpg)

**Comment by kathrynwp** [comment]
I'm adding "Core fix needed" as this looks like a Gutenberg issue affecting multiple themes, and should ideally be fixed at the block level rather than theme by theme.

**Comment by i11za** [comment]
One more report here: 5479054-zd-woothemes
Theme: Plane
User the workaround CSS.

**Comment by poeticabdul** [comment]
Reported here 6496192-zen 

Workaround helped.

**Comment by csabarakasz** [comment]
6505405-zd-woothemes
