### ISSUE TITLE
Twenty Nineteen: Comma in footer credit won't "hide"

### ISSUE THREAD

**Issue by Lochlaer** [Automattic/themes#536]
In the Twenty Nineteen theme, the footer credit automatically includes the Site Title in addition to the WPCOM credit, separated from each other with a comma. This in turn affects all the style variations based on this theme (Elegant, Calm, Friendly, Professional, Modern, Sohpisticated).

When a user has a Business plan and activates that theme, and then "hides" the footer credit, the comma doesn't "hide", though, making for awkward footer text.

Screenshot: https://cld.wthms.co/b6YyAP

Note: This appears to happen on all the new "[style] Business" themes. 

## Steps to replicate

1) Activate the Elegant Theme on a Business plan site. 

2) Go to CUSTOMIZE -> SITE IDENTITY -> Hide the footer credit

## Result

The footer credit itself goes away, but the comma does not.

## Expected

The site title to remain but without the extra comma. 

* User report: from concierge chat
* Follow-up ticket: #1776872-zen

**Comment by laurelfulford** [comment]
I made the description more generic since this is an issue with Twenty Nineteen, and so, all the business variations as well.

There's some discussion around it in the comments here, for context: pNEWy-clT-p2

**Comment by crunnells** [comment]
@Lochlaer I fixed the issue in r53276-wpcom-theme; can you please follow-up with the customer to let them know the problem is resolved? I'll leave a note on the ticket as well.
