### ISSUE TITLE
Blank Canvas: Marketing banner prevents closing Navigation Block on mobile

### ISSUE THREAD

**Issue by eoinsav** [Automattic/themes#5392]
### Quick summary

The marketing banner on free sites is preventing the Navigation Block from closing on mobile (site in screenshot using "Blank Canvas" theme):

<img width="400" alt="Screen Shot 2021-12-02 at 1 27 16 PM" src="https://user-images.githubusercontent.com/35590156/144505765-5b3312c1-d194-4b53-8644-d5bd9371f97f.png">

### Steps to reproduce

1. Add a Navigation Block to the top of a free site and open the site on mobile.
2. Open the Navigation hamburger menu.
3. Try to close it using the X.

### What you expected to happen

The "X" to close the mobile menu should be visible.

### What actually happened

The "X" to close the mobile menu is hidden behind the marketing banner added to free sites.

### Simple/Atomic

Simple

### Reproducibility

Consistent

**Comment by eoinsav** [comment]
Similar to this issue: https://github.com/Automattic/wp-calypso/issues/47827

**Comment by Greatdane** [comment]
Thanks @eoinsav, I can also reproduce it on that example site. 

Moving to themes as it seems to be a Blank Canvas only issue.

**Comment by mmtr** [comment]
I'm closing this one out, because I cannot reproduce it (see video below) and I believe the Blank Canvas theme was retired in favor of the new Assembler theme.


https://github.com/user-attachments/assets/5233e8f7-2aa6-4230-bfe0-da66876194e3



Feel free to re-open if the issue still persists!
