### ISSUE TITLE
Blank Canvas Blocks: PHP error in self-hosted version of theme

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#5399]
## Steps to replicate

* Install Blockbase 2.0.15 and Blank Canvas Blocks 0.0.4 on a self-hosted WordPress site - can use either the WordPress.com themes showcase via Jetpack, or download and install manually on a non-Jetpack site.
* Activate Blank Canvas

## Result

A PHP error appears in both the dashboard and the front end of the site. When I first encountered it, it also gave me a critical error on the front end, though I'm not able to replicate that.

![Manage_Themes_‹_My_Core_Sandbox_—_WordPress](https://user-images.githubusercontent.com/11873759/151156211-d02e73f1-8b07-4240-8488-3508b93e22a5.png)

![My_Core_Sandbox_–_Just_another_WordPress_site](https://user-images.githubusercontent.com/11873759/151156290-7bcc7289-0011-4add-8f36-dc88d2c06b39.png)

Error only appears if Blank Canvas is enabled. If I switch to Blockbase or any other theme, it goes away.

I can replicate on a Jetpack-connected Pressable site, and on a local install. Local install has no plugins at all, so it's not related to Jetpack.

It does not appear to be affecting Atomic at the moment.

## Expected

For there to not be errors :)

* User report: none - discovered it while trying to replicate another issue

**Comment by KokkieH** [comment]
New user report in https://wordpress.com/forums/topic/theme-errors-2/

**Comment by KokkieH** [comment]
I've just run into the same error when activating Russell on a self-hosted site

It also appears to break the Jetpack connection/XML-RPC.

**Comment by MaggieCabrera** [comment]
Looks like the theme downloads script is failing and we are not generating the correct zips for the themes on Jetpack.

Might be related: https://github.com/Automattic/themes/issues/5150

**Comment by MaggieCabrera** [comment]
Running `php bin/themes/theme-downloads/build-theme-zip.php --stylesheet=pub/russell --themeversion=0.0.18` in my sandbox seemed to be generating the zips correctly but the manual tool is not working. The original problem with the PHP error is persisting on a Pressable site.

**Comment by MaggieCabrera** [comment]
Steps to reproduce this: 

- Create a jurassic ninja site
- Link your WordPress.com account with Jetpack for the site
- on WordPress.com select the Russell theme for the jurassic ninja site

This shows up on the frontend:
<img width="1155" alt="Screenshot 2022-04-08 at 13 05 47" src="https://user-images.githubusercontent.com/3593343/162424033-32d2a6d2-2876-4112-8839-57143d121ab4.png">

**Comment by MaggieCabrera** [comment]
Opened https://github.com/Automattic/themes/issues/5832 to sort the problem with the zip creation tool separately.

**Comment by MaggieCabrera** [comment]
ok I found out more! looks like lib/theme-downloads.php on dotcom is adding this include to the functions.php files of themes, but russell doesn't have a functions.php file so instead of simply adding the lines to the end of the file, it needs to open the PHP tags as well for the include to work and not just be printed to the frontend

**Comment by MaggieCabrera** [comment]
D78439-code might solve this

**Comment by pbking** [comment]
D78439-code has been deployed.
