### ISSUE TITLE
Dyad 2: Tagline ignores setting to not display

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#540]
## Steps to replicate

1. Have the front page set to display latest posts
2. Make sure there are no featured or sticky posts, so the front page slider does not display
3. Go to Customizer ->Site Identity and set a tagline
4. Uncheck box to hide site title and tagline

## Result

The title disappeared, but the tagline remains displayed as a heading over the custom header image

![shift_to_the_left_ _this_is_the_tagline](https://user-images.githubusercontent.com/11873759/52320367-a38ac980-29d7-11e9-98f5-28b661c6dd78.png)

## Expected

For both the title and tagline to disappear as in other themes

* User report: Reported via [Twitter](https://twitter.com/bixmediocre/status/1092909375654551553)

**Comment by laurelfulford** [comment]
Oof, this is a bit of a tough one.

I agree that the behaviour isn't correct, based on the label on the checkbox. But unfortunately this is one of those things that, in changing it, could affect existing sites in unwanted ways.

I'm leaning towards updating the label on the checkbox to be more accurate, rather than changing the theme's behaviour, but I'd appreciate a second opinion!

**Comment by allancole** [comment]
As Laurel suggested, I think we may have to try to alter the label in the Customizer for this one, especially since the theme implements the site-description in an uncommon way. Users can always hide the site-description by removing the text, so maybe we could add a note about that method?

**Comment by KokkieH** [comment]
That sounds reasonable, yes.

**Comment by alaczek** [comment]
I tried adding this line in inc/customizer.php, inside the `dyad_2_customize_register` function
`$wp_customize->get_control( 'header_text' )->label = __( 'Display Site Title', 'dyad-2' );`
but it gives me a warning:
`Warning: Creating default object from empty value in /dyad-2/inc/customizer.php on line 13`
Not sure what am I missing? We used the same bit of code to change the label of this control in Professional Business with no issues :|

**Comment by torres126** [comment]
I'm not sure why it's different but I had a look, and a slightly different line gave me success:

`$wp_customize->get_control( 'display_header_text' )->label = __( 'Display Site Title', 'dyad-2' );`

PR proposing it in #707 :)
