### ISSUE TITLE
Revelar: Captioned images are not full-width

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#541]
## Steps to replicate

Add a captioned image to a post in the Classic Editor.

## Result
The image does not fill the full width of the column

![test](https://user-images.githubusercontent.com/7662449/52354957-65a19b80-29ff-11e9-907d-252bb8e5f7e3.png)

## Expected

The image should fill the whole width of the column, as it did pre-Gutenberg.

This CSS seems to be the culprit:
```
.caption-big .size-big 
    min-width: 100% !important;
 }
```

Gave user this custom CSS temporarily via complimentary Custom Design upgrade. The upgrade should be removed once this is fixed.

```
@media screen and ( min-width: 1280px ) {
  .caption-big .size-big {
    max-width: inherit !important;
  }
}
```

Ticket: 1760081-zd

**Comment by laurelfulford** [comment]
Thanks for this report @kathrynwp!

I don't think this is Gutenberg-related -- it looks like the max-width that's restricting the captioned image is coming from the theme itself, which doesn't have Gutenberg styles (the classes also don't match anything Gutenberg spits out).

It doesn't look like Revelar's styles have been updated in over a year -- I wonder if this just managed to sneak under the radar this whole time?

**Comment by kathrynwp** [comment]
Maybe, Laurel! The thing is that the user said this just started happening. Is there any way to fix?

**Comment by laurelfulford** [comment]
> The thing is that the user said this just started happening.

Oh, super strange! It should be fixable by changing the max-width in the theme at the breakpoint you have in the Custom CSS. It doesn't seem to serve a purpose on larger screens.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
