### ISSUE TITLE
2022: New Post action shows Template: 404 on WP.com

### ISSUE THREAD

**Issue by zandyring** [Automattic/themes#5410]
## Steps to replicate

1. Go to a WP.com site that has 2022 enabled.
2. Posts > Add New.
3. See the Template in Post Settings.
<img width="282" alt="Screen Shot 2022-01-28 at 12 53 35 PM" src="https://user-images.githubusercontent.com/7304712/151597266-e5e458f5-8ab0-4a11-9c32-c68dbafb1c80.png">

4. After posting, the template shows up properly.
<img width="292" alt="Screen Shot 2022-01-28 at 12 45 47 PM" src="https://user-images.githubusercontent.com/7304712/151597328-53e35fa8-5309-4fef-bc3c-99c269b26038.png">

This is happening in Firefox 95.0.2 (64-bit).

## Result

Template name seems to be 404-ing. Doesn't seem to affect anything, however. No errors posting that are visible on the site itself (I did not check the inspector, I'm sorry).

## Expected
I'd expect the Template name to be correct.

**Comment by KokkieH** [comment]
A user report in https://wordpress.com/forums/topic/blockbase-theme-defaults-to-404-template/?view=all, using Blockbase

**Comment by Thelmachido** [comment]
I test this on Blockbase & Twenty Twenty Two theme but I wasn't able to reproduce this with the new release. 

<img width="1710" alt="Screenshot 2022-06-29 at 12 17 57" src="https://user-images.githubusercontent.com/41231764/176416154-1307e230-0fd2-40a3-966f-6fcb545c37ce.png">

Closing the issue for now.
