### ISSUE TITLE
Archeo: Create a demo site on dotcom

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5420]

**Comment by scruffian** [comment]
@kjellr I started the demo site here: https://archeodemo.wordpress.com/

We can circle back to this when the patterns are done.

**Comment by mikachan** [comment]
All the updated patterns and latest changes are now available on .com, so I've added a couple of patterns to the pages on the [demo site](dIkqP-p2), and made sure the home template is showing correctly.

@beafialho @kjellr (or anyone else who can answer): How do we normally decide on the content for the demo site?

**Comment by beafialho** [comment]
Thanks @mikachan! Typically we add the content that's mocked up in Figma comps, if there isn't any we add it directly to the demo site. Should we start adding it?

**Comment by mikachan** [comment]
Ah OK, thanks! Yeah, I think now is a good time to add some content if possible.

**Comment by kjellr** [comment]
Great, thanks! @beafialho and I will start setting up the demo site next week.

**Comment by beafialho** [comment]
Content has been added to the [demo site](https://archeodemo.wordpress.com).

**Comment by kjellr** [comment]
This should be all set now, so marking as closed.
