### ISSUE TITLE
Archeo: Block patterns

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5429]
- [x] 1. Headline over dark image: https://github.com/Automattic/themes/pull/5464

![image](https://user-images.githubusercontent.com/1645628/152005776-f3af2644-4ff4-42cc-af9f-d1e05d24ca1b.png)

- [x] 2. Image with headline and description: https://github.com/Automattic/themes/pull/5467

![image](https://user-images.githubusercontent.com/1645628/152006096-347a0016-bb0c-4065-8e36-8b3446105535.png)

- [x] 3. Image with headline and separate description: https://github.com/Automattic/themes/pull/5470

![image](https://user-images.githubusercontent.com/1645628/152006275-777c8a4d-0682-42a2-9b9d-787af9797116.png)

- [x] 4. Image with description: https://github.com/Automattic/themes/pull/5479

![image](https://user-images.githubusercontent.com/1645628/152006467-c5e230fa-2325-48ea-b977-05512c708a4e.png)

- [x] 5. Simple list of posts: https://github.com/Automattic/themes/pull/5480

![image](https://user-images.githubusercontent.com/1645628/152006610-248cd256-2a9e-4bc2-b55b-521ff796f785.png)

- [x] 6. Image with description and right-aligned headline: https://github.com/Automattic/themes/pull/5487

![image](https://user-images.githubusercontent.com/1645628/152006669-3e78f5e2-c120-46eb-ba55-24cf764259bd.png)

- [x] 7. Image with headline on dark background: https://github.com/Automattic/themes/pull/5474

![image](https://user-images.githubusercontent.com/1645628/152006842-62513d11-5379-4ea1-8c51-b3b26198f0bc.png)

- [x] 8. Layout with two images and text: https://github.com/Automattic/themes/pull/5486

![image](https://user-images.githubusercontent.com/1645628/152007018-47cb581e-7903-4980-b51d-e31852374f7f.png)

- [x] 9. Layered images with headline: https://github.com/Automattic/themes/pull/5468

![image](https://user-images.githubusercontent.com/1645628/152007247-4ee6f386-6607-47d8-b59c-5b553475ce3f.png)

**Comment by MaggieCabrera** [comment]
@beafialho @kjellr can we get some names for these? Also some alt texts and file names for the images will be needed too. Thank you!

**Comment by MaggieCabrera** [comment]
Opened https://github.com/WordPress/gutenberg/issues/38498 for Pattern 5, we can do that with CSS pretty easily and I don't think the GB issue will get a fast solution since it's not something properly built-in at the moment. I'll keep a close eye on it though.

**Comment by kjellr** [comment]
Here are some titles. Feel free to adjust as you see fit: 

1. Headline over dark image
2. Image with headline and description
3. Image with headline and separate description
4. Image with description
5. Simple list of posts
6. Image with description and right-aligned headline
7. Image with headline on dark background
8. Layout with two images and text.
9. Layered images with headline.
