### ISSUE TITLE
Archeo: Core block settings

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5434]
- [x] Pullquote
- [x] Comments
- [x] Separator

**Comment by scruffian** [comment]
@kjellr @beafialho is there anything specific we need for this? For example is this how quote blocks should always look?
<img width="817" alt="Screenshot 2022-02-04 at 12 48 11" src="https://user-images.githubusercontent.com/275961/152531788-034344fa-d4b9-4bde-b985-b34d9cfd401a.png">

**Comment by kjellr** [comment]
The standard Quote block can look just like it does by default, but let's use this design target for a left-aligned Pullquote. I'm not sure we'll be able to get 100% of the way there, but it's worth a shot.
