### ISSUE TITLE
Blockbase Color customizations show as new "custom palette"

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5448]
## Steps to replicate

Using WP 5.9 and Gutenberg /trunk
Activate a Blockbase theme
Customize the colors using the Customizer
Load the FSE and view the GS color palette.
Note that the colors edited in the customizer are represented as CUSTOM.

<img src="https://user-images.githubusercontent.com/146530/152217906-abdaa115-4d0b-4efa-86bf-a403812ac708.png" width=300>

Originally they changed the colors shown under "Theme"

This is due to the differences as to how the colors are being persisted between Customizer and FSE GS as noted [here](https://github.com/Automattic/themes/issues/5387).

**Comment by scruffian** [comment]
I pushed a fix for this to https://github.com/Automattic/themes/pull/5492 - we now save the colors on the theme key.

**Comment by pbking** [comment]
That fix was [removed](https://github.com/Automattic/themes/pull/5492#issuecomment-1039440192) from #5492.  Moving this back to "TODO" for another solution.
