### ISSUE TITLE
Classic block: Can not order images in gallery in the Classic Editor

### ISSUE THREAD

**Issue by aleone89** [Automattic/themes#5451]
## Steps to replicate

1. Go to My Sites > Pages > select Classic View from screen options
2. On a page that's already created > edit with Classic editor 
3. Add Media > Create Gallery 
4. Select images > Add to gallery 
5. Click and "Drag and drop to reorder media files."

## Result

It's possible to click and move images, but they will not slot into the order. 

## Expected

Expected to "Drag and drop to reorder media files."

* User report: zen-4732157

**Comment by Gustavo-Hilario** [comment]
Another report here: 4744278-zen

They are using a third-party theme. I could also reproduce this issue using themes that we own, so I don't think this is related to a specific theme.

**Comment by rw-ye** [comment]
I've closed 4744278-zd-woothemes for now. Please follow up when a fix has been deployed or when we have more information to share with the user.

**Comment by aleone89** [comment]
Another report here: zen-4746097 , this time with the Sketch theme.

**Comment by aleone89** [comment]
Closing this in favour of: https://github.com/Automattic/themes/issues/5451

**Comment by kathrynwp** [comment]
@aleone89 Your link above seems to link back to this same ticket?

**Comment by fstath** [comment]
Reported in the Greek forum as well:
https://wordpress.com/el/forums/topic/drag-and-arrange-images/

**Comment by kingsleyinfo** [comment]
Here is another report 33889631-hc
