### ISSUE TITLE
Archeo: Can we improve the Chivo font weights?

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5478]
There are several differences between the Chivo font weights in the Archeo comps compared to the browser. We did a lot of work on this [here](https://github.com/Automattic/themes/pull/5452), but we're still seeing some differences.

An example can be seen in [this pattern](https://github.com/Automattic/themes/pull/5468), but we should run through each pattern and font style to see if we can improve them.

Chivo font: https://fonts.google.com/specimen/Chivo

**Comment by MaggieCabrera** [comment]
There's a 100 weight [here](https://www.omnibus-type.com/fonts/chivo/). I had the same questions when I worked on that.

**Comment by mikachan** [comment]
Oh thanks! I'll take a look.
