### ISSUE TITLE
Archeo: Update all text in patterns

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5484]
Once all patterns (https://github.com/Automattic/themes/issues/5429) have been merged, replace all the text with English and ensure the text is consistently matched to the images across all patterns.

**Comment by beafialho** [comment]
I took a close look at the images and their descriptions and translated the patterns to English - they can be found translated [here](https://www.figma.com/file/28iXII44cLy2oKwyHLgTdi/Archeo?node-id=817%3A1626).

![Pattern-8](https://user-images.githubusercontent.com/65220155/154527047-08a0f496-5e79-4ae0-9497-9633fe3cb791.jpg)

![Pattern-7](https://user-images.githubusercontent.com/65220155/154527065-fdfa85aa-5291-4f30-93c6-c59273153888.jpg)

![Pattern-6](https://user-images.githubusercontent.com/65220155/154527068-bb34aec0-997a-4d4f-a0cf-b14a16bed9be.jpg)

![Pattern-5](https://user-images.githubusercontent.com/65220155/154527070-90e671e3-8dcc-4f61-b55f-fac459f12fce.jpg)

![Pattern-3](https://user-images.githubusercontent.com/65220155/154527078-e3550454-e6a1-4bba-b208-95b9e81d6474.jpg)

![Pattern-2](https://user-images.githubusercontent.com/65220155/154527079-8725fc55-40c0-452f-abba-dddfb40ea798.jpg)

![Pattern-1](https://user-images.githubusercontent.com/65220155/154527083-40bc06df-c92e-4458-9e21-2103244252f8.jpg)

In this one, this bit of text was added **"On the right: Governor’s Palace, detail of the main gate"**:

![Pattern-4](https://user-images.githubusercontent.com/65220155/154527076-ec0b95a9-8c25-418a-9d12-9e27857ce13a.jpg)

**Comment by mikachan** [comment]
Thanks so much @beafialho! I can pick this up from here 👍
