### ISSUE TITLE
Twenty Twenty One: If Blog Posts Block is nested within the Group Block, the `Load more posts` button text is invisible

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#5488]
## Steps to replicate

1. Add [Group Block](https://wordpress.com/en/support/wordpress-editor/blocks/group-block/) to a page
2. Add [Blog Posts Block](https://wordpress.com/en/support/wordpress-editor/blocks/blog-posts-block/) within it
3. Activate `Load more posts` button in the right-side panel 
![image](https://user-images.githubusercontent.com/39308239/153211032-66936ad8-ddd9-410a-a59b-75de0d0e77e9.png)
4. Preview the page

## Result

The `Load more posts` button text is invisible unless hovered over

![Screen Capture on 2022-02-09 at 15-30-53](https://user-images.githubusercontent.com/39308239/153211247-61c68727-3da6-4f62-8b52-549e1de2d67d.gif)

## Expected

The `Load more posts` button text should be visible

---

* User report: 4764329-zd-woothemes

**Comment by jffng** [comment]
Thanks for reporting, I'm unable to replicate this issue. Adding a Blog Posts block inside a group on TT1 gives me the following:  
 
https://user-images.githubusercontent.com/5375500/155016135-0326e133-4dc7-4ecc-a3bb-e8291d463e0b.mp4

If the issue persists, the workaround you suggested to remove this from a group block seems sufficient. Closing this one for now.
