### ISSUE TITLE
Remote: Create a demo site on dotcom

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5496]
https://remotedemo.wordpress.com/

**Comment by MaggieCabrera** [comment]
I added some content, but I think it needs another pass @kjellr @beafialho 
Since we are still using headstarts, maybe we should reduce the number of posts to 3? Or maybe we can just cut the amount of posts from the headstart file itself, your call!

**Comment by kjellr** [comment]
I think trimming the amount of posts from the headstart file would be good if that's not too much of a hassle. Since the post list is such a prominent feature, it benefits from having a bunch in the demo. We'll give the demo a review soon!

**Comment by kjellr** [comment]
I created a bunch of small issues, but the demo site itself is all set. So marking this as closed for now. 👍 

Related:

- https://github.com/Automattic/themes/issues/5777
- https://github.com/Automattic/themes/issues/5776
- https://github.com/Automattic/themes/issues/5775
-  https://github.com/Automattic/themes/issues/5774
- https://github.com/Automattic/themes/issues/5773
