### ISSUE TITLE
Remote: theme.json: Alternative color palettes

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5500]

**Comment by matiasbenedetto** [comment]
Moving back to pending following @kjellr 's suggestion: "I don’t think that’s critical for launch — I’m not confident launching alternate theme.json palettes yet, until the feature is more developed."

**Comment by MaggieCabrera** [comment]
@beafialho do you think we should add some style variations to Remote for 6.0? We have a few color variations on Figma

**Comment by beafialho** [comment]
> @beafialho do you think we should add some style variations to Remote for 6.0? We have a few color variations on Figma

I don't see why not, we're also working on some for Pendant. I'll iterate on it 👍

**Comment by beafialho** [comment]
@MaggieCabrera @madhusudhand I've worked on some style variations for Remote and I'm feeling pretty good about them. Added them [here](https://www.figma.com/file/S382KokJxg0G043wsNoFQj/?node-id=1623%3A342).

<img width="1021" alt="Captura de ecrã 2022-04-28, às 12 59 55" src="https://user-images.githubusercontent.com/65220155/165747415-806590b2-8866-4fcd-ac07-1b4b16c901e8.png">

**Comment by madhusudhand** [comment]
@beafialho updated the PR with typography changes and other design adjustments. Can you review.

@MaggieCabrera Observed some of the font sizes for headings are not set properly (h1 is set 42px instead of 72px sometimes because incorrect min,max computation). Updated them to right values.
