### ISSUE TITLE
Remote: Comment form styles (dotcom and dotorg) (if needed)

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5501]
@kjellr @beafialho the form is currently looking like this:
![image](https://user-images.githubusercontent.com/1310626/155189203-7638124c-ac44-45dd-9c7d-fda8a1d1aeca.png)

**Comment by matiasbenedetto** [comment]
@kjellr @beafialho Looking like this for non-authenticated users: 

![image](https://user-images.githubusercontent.com/1310626/155193023-55eb051e-94f7-4242-8e00-6597b296acd3.png)

**Comment by beafialho** [comment]
Sorry it's taken us this long to reply. I've added a mockup [here](https://www.figma.com/file/S382KokJxg0G043wsNoFQj/Remote?node-id=1291%3A114) with visual changes that apply to both forms:

<img width="852" alt="Captura de ecrã 2022-02-23, às 11 58 38" src="https://user-images.githubusercontent.com/65220155/155315179-2678c860-9c8f-4071-b627-5d7202b8b4ce.png">
