### ISSUE TITLE
Remote: Pre-launch: screenshot.png

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5502]
@kjellr @beafialho I don't think we have a screenshot for Remote

**Comment by beafialho** [comment]
Here's the screenshot for Remote. I believe these are the correct dimensions of the image, let me know if they're not.

![remote_screenshot](https://user-images.githubusercontent.com/65220155/158844665-acf87424-05a0-4d1d-ab9a-9b65da9263d2.png)
