### ISSUE TITLE
Remote: Block patterns (if needed)

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5504]
- [x] Introduction https://github.com/Automattic/themes/pull/5553

![Block Pattern_ Introduction](https://user-images.githubusercontent.com/3593343/153411039-27174290-c9c7-4f12-8dda-74ada10d1f9f.jpg)

- [x] Posts list

![Block Pattern_ Posts List](https://user-images.githubusercontent.com/3593343/153411038-dd2f5d8f-66c4-498f-9344-d5b1e7af9d19.jpg)

- [x] Posts Grid https://github.com/Automattic/themes/pull/5533

![Block Pattern_ Posts Grid](https://user-images.githubusercontent.com/3593343/153411035-685ef9b7-6020-4390-9aee-63b566f7a1ef.jpg)

- [x] ??? https://github.com/Automattic/themes/pull/5665

![Block Pattern_ Posts Grid(1)](https://user-images.githubusercontent.com/3593343/153411032-11230296-d558-4af9-b639-39033da9fed6.jpg)

- [x] Tags

![Block Pattern_ Tags](https://user-images.githubusercontent.com/3593343/153411030-332a8221-14b7-4319-996e-e0266a401c6e.jpg)

- [x] Large Quote https://github.com/Automattic/themes/pull/5696

![Block Pattern_ Large Quote](https://user-images.githubusercontent.com/3593343/153411028-2300800f-2694-445c-95b4-e2aa4498f019.jpg)

- [x] Small Quote https://github.com/Automattic/themes/pull/5703

![Block Pattern_ Small Quote](https://user-images.githubusercontent.com/3593343/153411025-44be9406-dac3-4644-a166-07dc13ebdc46.jpg)

- [x] Categories

![Block Pattern_ Categories](https://user-images.githubusercontent.com/3593343/153411023-6732f942-10e9-4848-a079-9472c04a0f02.jpg)

- [x] Subscribe (Jetpack block) https://github.com/Automattic/themes/pull/5714

![Block Pattern_ Subscribe](https://user-images.githubusercontent.com/3593343/153411019-aa99abba-2d22-474b-8821-a0527ea2743b.jpg)

**Comment by MaggieCabrera** [comment]
@kjellr @beafialho I think Remote is in a good place for a design review now. All templates and patterns are done and merged and the next steps are launch tasks only.

**Comment by kjellr** [comment]
Wonderful, thank you! We'll review alongside the demo site.

**Comment by kjellr** [comment]
I opened some related issues with these patterns. Since those are logged elsewhere, I think it's fine to close this issue for now: 

- https://github.com/Automattic/themes/issues/5774
- https://github.com/Automattic/themes/issues/5775 
- https://github.com/Automattic/themes/issues/5778
- https://github.com/Automattic/themes/issues/5779
- https://github.com/Automattic/themes/issues/5780
