### ISSUE TITLE
Remote: Templates: Header template part (including mobile)

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5508]
<img width="1200" alt="Screenshot 2022-02-10 at 13 49 54" src="https://user-images.githubusercontent.com/3593343/153411876-7b23be7b-6cf7-4667-ace5-9026b178023f.png">

@kjellr should we add the tagline or the site logo to the template part? Or leave that for users to do?

**Comment by beafialho** [comment]
@MaggieCabrera I think we can leave it like that, as users will eventually have access to other header patterns.
