### ISSUE TITLE
Remote: Pre-launch: readme.txt

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5511]
We need to include any licensing information to the readme file as well as adding the changelog. We also need a theme description @kjellr @beafialho

**Comment by beafialho** [comment]
Here's the Remote description:

_Remote is a dark, minimal block theme ideal for bloggers. Its default styles - a sans-serif font and dark background - contribute for a comfortable, immersive reading experience. It features a set of bold block patterns such as a large posts list and bordered categories and tags._

**Comment by MaggieCabrera** [comment]
I reviewed the file and I think it's good as it stands
