### ISSUE TITLE
Zoologist: Next Page within Pagination Block has the overlapping arrow in the Editor

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#5520]
## Steps to replicate

Create a free plan site with Zoologist theme at https://wordpress.com/start and observe the

## Result

The right arrow that should appear after the words `Next Page` appears overlapped over the word `Next` instead. This happens only in the Editor, not on the frontend.

![image](https://user-images.githubusercontent.com/39308239/153432401-790626b4-ff83-421a-b11b-c6b7ebb7af17.png)

![image](https://user-images.githubusercontent.com/39308239/153432413-5189919c-391d-406e-94f0-782b9a9613a6.png)

## Expected

See the right arrow to the right of the word `Page`.

**Comment by pbking** [comment]
This is also happening in Geologist (and its variations)
