### ISSUE TITLE
Shoreditch: Paragraph block, Highlight preset color isn't showing in the editor

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/themes#5524]
### Quick summary

Changes aren't being applied when highlighting text in the `Paragraph` block. However, if we preview the page/post, we will see the color was set correctly. 

### Steps to reproduce

1. Activate the `Shoreditch` theme.
2. Add a new page or post.
3. Add a `Paragraph` block and text.
4. Select a portion of this text and apply Highlight by selecting one of the preset color.
5. Changes won't be applied to the editor. However, if you preview the page, you'll see the changes were made correctly.

### What you expected to happen

I was expecting to see the inline color changes in the Editor.

### What actually happened

Inline color changes aren't being applied, or it uses a white color.

| Editor view  | Live Preview |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/153740929-77bcee8c-a6da-4afa-96a6-817081a1d73d.png) | ![image3](https://user-images.githubusercontent.com/15944096/153740925-e86a9d45-bc68-4821-8ac5-af2a5df9d09a.png)  |

![image2](https://user-images.githubusercontent.com/15944096/153740969-49076454-95e9-450d-938d-adfe66bcbe5d.png)

### Context

User report: 4747647-zen 

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

I could only reproduce it with the `Shoreditch` theme.

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

When this bug applies a white color to the highlighted text, I found a workaround by using the theme hexadecimal color. However, if the color doesn't change, this workaround might not work.

https://user-images.githubusercontent.com/15944096/153741150-b9b727ff-62ea-458b-adb2-bed7fc34b714.mov

_No response_

**Comment by formosattic** [comment]
Updated the initial report with some screenshots.

Transferring to Themes.
