### ISSUE TITLE
Archeo: Consolidate patterns images

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#5527]
In Archeo we have some similar images in patterns:

uxmal.jpg:
![uxmal](https://user-images.githubusercontent.com/275961/153913647-f70b0b89-3b94-4dab-9666-9eb39a86ab9e.jpg)

palais-du-gouverneur.png:
![palais-du-gouverneur](https://user-images.githubusercontent.com/275961/153913661-521526a9-c8c1-4b17-95bc-dda1d25e6e52.png)

palais-du-cirque-bg.png:
![palais-du-cirque-bg](https://user-images.githubusercontent.com/275961/153913713-db741b41-67dd-4eb3-848b-490cd6151720.png)
palais-du-cirque.jpg:
![palais-du-cirque](https://user-images.githubusercontent.com/275961/153913720-8a7aec16-56c4-4198-a0a7-1ba5d22d3cec.jpg)

Is it worth trying to use the same images in these cases?

**Comment by kjellr** [comment]
- Let's remove `uxmal.jpg` and use `palais-du-gouverneur.png` in place of it. I don't think that should have any significant impact on the appearance of the pattern(s) that use it. 
- We should also have no need to include `palais-du-cirque-bg.jpg`. We can re-use the foreground image for the background too there, and implement an overlay color. 

If you folks wouldn't mind making those changes to the patterns, I can go ahead and fine-tune things when I re-generate the images as part of #5477.
