### ISSUE TITLE
Byrne Theme: Related Posts not Displaying Categories or Tags

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#5552]
### Quick summary

Byrne theme: In Reading Settings, even _"Show context (category or tag)"_ is selected, related posts do not show categories or themes. 

### Steps to reproduce

1. Activate Byrne theme 
2. Go to Settings > Reading 
3. Scroll down to Related Posts and select _"Show context (category or tag)"_
4. Save
5. View a post and check the related posts below. 

### What you expected to happen

Related posts will show the categories or tags they have. 

### What actually happened

Posts under related posts do not have categories or tags. 

### Context

User report: 4752744-zd and self-testing. 

### User's site and settings: 

<img width="1070" alt="Screen Shot 2022-02-05 at 5 19 35 PM" src="https://user-images.githubusercontent.com/36863633/152650835-f12ddfba-b7d4-40a6-bad7-39aac315d44a.png">

Related posts do not have categories or tags below the post title:

<img width="1388" alt="Screen Shot 2022-02-05 at 5 22 32 PM" src="https://user-images.githubusercontent.com/36863633/152650854-f8118c85-ce62-4462-a8a4-d722e183a0dd.png">

---

### My test site 

Using Byrne, related posts are not displayed at all: 

<img width="1307" alt="Screen Shot 2022-02-05 at 5 45 38 PM" src="https://user-images.githubusercontent.com/36863633/152650873-68b0c9df-4111-4e43-b481-0c270d5a7707.png">

However, using other themes with related posts feature like Rockfield and Canape, the posts and categories are displayed: 

<img width="690" alt="Screen Shot 2022-02-05 at 5 44 13 PM" src="https://user-images.githubusercontent.com/36863633/152650895-515c6c16-18b1-4bbe-873a-674b8075f41f.png">

<img width="837" alt="Screen Shot 2022-02-05 at 5 42 50 PM" src="https://user-images.githubusercontent.com/36863633/152650906-f16d3ae1-ff71-4035-9735-3b75692b6503.png">

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Byrne

### Browser, operating system and other notes

Firefox 96,  macOS 12.2. 

### Reproducibility

Intermittent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

Use Rockfield or Canape theme. Or add related posts block in the post.

**Comment by Robertght** [comment]
I can confirm both issues appear to be happening on my end as well.

1. The related posts do not show up on either Simple or Atomic sites 
2. The categories/tags do not show up on the user's site: https://ericarobbin.com/roasted-tomato-and-garlic-soup/

The first one also appears to be related to this issue: https://github.com/Automattic/themes/issues/5264

However, I'm not entirely sure I understand how the related posts section shows up on their site, but not our test ones. As this is a Jetpack feature, is there something we could try to force the section show up? Pinging @jeherve for a second look

**Comment by jeherve** [comment]
> I'm not entirely sure I understand how the related posts section shows up on their site, but not our test ones.

When using a block theme, you would have to add a Related Posts Block to the single post template if you wanted the related posts to be displayed there.

Can you tell what the block settings are on that specific site? Is the block set to display context (categories / tags)? That toggle is not checked by default, so it could be that the site owner did not check it yet?

**Comment by Robertght** [comment]
>When using a block theme, you would have to add a Related Posts Block to the single post template if you wanted the related posts to be displayed there.

This is key. After adding the block and setting the block to show up the context/featured image, the related posts section shows up as expected.

![image](https://user-images.githubusercontent.com/6737345/157227706-d1b103b4-79aa-4eac-887b-13a667af9488.png)

Finally, I think we should make this clearer within our docs: https://wordpress.com/support/related-posts/

@donalirl would it be ok to add a piece of information in the doc above to support the users going forward?

**Comment by Sandkorner** [comment]
Hey. 

Not sure if I should post it here, as this is something different, but I guess Kel forgot to mention that there was another issue with comment being left aligned, so that you cannot see them correctly. 

For example the same post: https://ericarobbin.com/roasted-tomato-and-garlic-soup/

<img width="1540" alt="Screenshot 2022-03-09 at 19 00 16" src="https://user-images.githubusercontent.com/71094068/157492158-fbeda8d3-5727-4252-a9c3-b96ecdfb1706.png">

Let me know if this is already added somewhere as a bug or if I should open a new one. :)

**Comment by jeherve** [comment]
@Sandkorner That is different indeed, it may be worth opening a new issue for this. Thank you!

**Comment by Robertght** [comment]
@Sandkorner this one might be similar: https://github.com/Automattic/themes/issues/5622 but I can see that site uses Byrne.

**Comment by Robertght** [comment]
I have made a request to update the Related posts doc so I'm going to close this one for now.
