### ISSUE TITLE
Karuna: Social Icons Block misalignment and distortion if added in the footer widget

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#5565]
## Steps to replicate

Add [Social Icons Block](https://wordpress.com/en/support/wordpress-editor/blocks/social-links-block/) to the Footer widget area with at least a few icons

## Result

Icons are distorted or misaligned

![image](https://user-images.githubusercontent.com/39308239/154707811-98fdd1e4-f406-4c23-97e3-60e593bad22a.png)

## Expected

See the icons normally as in the editor

## CSS workaround

```
/* fix alignment of social links in widget | XXXXXXX-hc eD */
.widget > ul.wp-block-social-links li {
	margin: 0;
	padding: 0;
}
```

---

Related: 

- https://github.com/Automattic/themes/issues/2806

**Comment by zdenys** [comment]
User report: 34263528-hc 

![image](https://user-images.githubusercontent.com/39308239/154708667-7fd5fd5f-95be-4313-a492-df2f008e30c8.png)

**Comment by MaxPhilip** [comment]
Misaligned icons in theme 'Twenty Twenty'  footer widget as well. Reported in 4829367-ZD.

![2022-03-04_10-58-12](https://user-images.githubusercontent.com/56555220/156742074-e7cefc18-dd60-46cc-9f41-1c7f9e5c6641.jpg)
