### ISSUE TITLE
Pique: Font Awesome icons no longer work

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#558]
## Steps to replicate

1. Visit Font Awesome at https://fontawesome.com/icons?from=io and copy the code for an icon
2. On a post or page, paste that code into an HTML block (if using the classic editor, the code gets stripped out automatically - see https://core.trac.wordpress.org/ticket/28940 for more details and a workaround)
3. Publish and view the post.

## Result

The icon does not appear.

## Expected

For the icon to appear.

It seems the 4.7 version of Font Awesome the theme is using has been retired, and they've released a completely redesigned version 5 which uses new codes for the various icons. More info in https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

* User report: https://wordpress.org/support/topic/mobile-menu-font-awesome-header-text-overlap/

Report was via the self-hosted forums, but I've confirmed this on a dotcom simple site as well.

**Comment by allancole** [comment]
Yup, I can replicate this.

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
