### ISSUE TITLE
Blockbase/Byrne Theme: Separator Block with "Dots" style appears misaligned in editor

### ISSUE THREAD

**Issue by cuemarie** [Automattic/themes#5582]
### Quick summary

Dots style separator displays the 3 dots on 2 lines instead of all parallel in the editor:

<img width="1383" alt="Markup 2022-02-09 at 09 35 53" src="https://user-images.githubusercontent.com/27249804/153265419-7dacca07-d3a7-443b-9f49-aff4c715cff7.png">
 

Dots appear fine on live site.

### Steps to reproduce

1. Activate Theme Byrne on a simple site
2. Add Separator Block to page or post
3. Set "Style" to "Dots"

### What you expected to happen

Dots should appear all in 1 line & parallel, like they do in other themes or the live site.

**Live Site:**

<img width="1225" alt="Screen Shot 2022-02-09 at 11 28 26 AM" src="https://user-images.githubusercontent.com/27249804/153266234-3d5f4032-858d-4414-ac8e-9cf7225e3c2b.png">

### What actually happened

The dots in the editor are misaligned.

<img width="1272" alt="Screen Shot 2022-02-09 at 11 28 55 AM" src="https://user-images.githubusercontent.com/27249804/153266813-b807500a-95d1-4932-923c-09517a777e2b.png">

### Context

Found during team testing

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Byrne

### Browser, operating system and other notes

Was able to reproduce on both FSE-enabled and FSE-disabled site, with Byrne theme

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

There is no user impact

### Workaround details

No problem on live site - just a quirk

**Comment by Robertght** [comment]
I can confirm this happens on AT sites as well.

**Comment by formosattic** [comment]
Was able to reproduce it with Geologist, Quadrat.

It's also happening on self-hosted, I tested with:
* Blockbase: https://pcm.wordpress.org/themes/blockbase/
* Quadrat: https://pcm.wordpress.org/themes/quadrat/

Other reports listed at https://github.com/Automattic/wp-calypso/issues/61853

cc @mikeicode  @metabreak

**Comment by MaggieCabrera** [comment]
This is a blockbase issue with the separator width CSS

**Comment by mikeicode** [comment]
It'd be nice to fix this since it apparently affects all Blockbase child themes. I run into it when I try to use Russell on DIFM-L sites as reported here:

https://github.com/Automattic/wp-calypso/issues/61853#issuecomment-1067116249

**Comment by mikeicode** [comment]
Looks like this will work as a temporary solution.

```
/* Dots separator spacing fix */

.wp-block-separator.is-style-dots::before {
	letter-spacing: 1em;
	padding-left: 1em;
}
```

Animation showing before & after:

![Screen Capture on 2022-03-21 at 13-28-55](https://user-images.githubusercontent.com/10353785/159331043-0ac67c78-b426-47e4-a454-85be1e928c87.gif)

**Comment by matiasbenedetto** [comment]
Potential fix: https://github.com/Automattic/themes/pull/5964
