### ISSUE TITLE
Stewart: Archive Page Isn't Filtering By Tag/Category

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#5606]
### Quick summary

The archive page on the Stewart theme is showing all posts, not filtering by tag/category.

### Steps to reproduce

1. Activate the Stewart on a site with a couple posts, in different tags or categories
2. Check an archive page - a tag or category page

### What you expected to happen

The archive page should show posts only from the specific category/tag.

### What actually happened

The archive pages are showing all posts.

### Context

Reported here: 4778564-zd-woothemes

It seems to be an issue with this setting on the Query Loop block on the Archive template - it's deactivated on this theme, but only works when activated:

![ArchiveTemplateIssue](https://user-images.githubusercontent.com/16104522/154817195-094332f6-5681-4cc5-874a-3100a4172389.jpg)

### Workaround details

You need to edit the Archive template from the site editor, and enable that option shown on the screenshot above.

**Comment by kerrynicl** [comment]
Another report here -  4814713-zen

**Comment by metabreakr** [comment]
Another report with the Pendant theme here: https://wordpress.com/forums/topic/pendant-theme-category-pages/

Re-opening this issue.

**Comment by helenaartmann** [comment]
Another report with the Pendand theme: 5474633-zd - the workaround above didn't work.

**Comment by supernovia** [comment]
We have another report with Pendant here. Does this need a separate issue because it's a different theme, @mikachan ?
https://wordpress.com/forums/topic/categories-block-not-working-all-posts-showing/

**Comment by mikachan** [comment]
Yes, it would be best to have another issue for Pendant. We can use the same description, as it seems to be the same issue with the archive template.

**Comment by supernovia** [comment]
> Yes, it would be best to have another issue for Pendant. We can use the same description, as it seems to be the same issue with the archive template.

Thanks! I've made a new issue here: https://github.com/Automattic/wp-calypso/issues/66659 (using the proper bug tools / procedures)

**Comment by ccwalburn** [comment]
I got a report from a user with the Byrne theme so I created another bug report here: https://github.com/Automattic/themes/issues/6778

5784450-zen

**Comment by pbking** [comment]
This issue seems to have remained open for other themes (Byrne and Pendant) but Stewart seems to be working as expected.  I'm closing this as it seems to have been fixed some time ago for Stewart.
