### ISSUE TITLE
Stewart: h3 is larger than h2

### ISSUE THREAD

**Issue by ramonjd** [Automattic/themes#5608]
Maybe this is an intentional part of the design, but in Stewart, the h2 font size is smaller than the h3 font size.

In Stewart's [theme.json](https://github.com/Automattic/themes/blob/trunk/stewart/theme.json#L310
), the h3 element's fontSize is defined as the following:

`"fontSize": "var(--wp--preset--font-size--huge)"` 

"huge" is `38px`.

The h2 element has a hardcoded fontSize of `32px`.

Should h3 be `--wp--preset--font-size--extra-large` (32px) and h2 `--wp--preset--font-size--huge` (38px) instead ?

## Steps to replicate

Insert two Heading Blocks in the editor. Assign one as H2 and the other has H3.

<img width="451" alt="Screen Shot 2022-03-02 at 3 36 40 pm" src="https://user-images.githubusercontent.com/6458278/156296011-6f0e4b0f-b764-403e-873e-697f5c1ddbdb.png">

<img width="488" alt="Screen Shot 2022-03-02 at 3 36 21 pm" src="https://user-images.githubusercontent.com/6458278/156296007-7e7e38f4-27e2-4b84-a6f1-2bb6807de328.png">

## Result
The h2 font size is smaller than the h3 font size.

## Expected

The h2 font size is larger than the h3 font size.

If it's intentional, please feel free to close 😄

**Comment by MaggieCabrera** [comment]
@kjellr if you could clarify this? I don't see a typography section on the figma file for the theme

**Comment by kjellr** [comment]
Yeah, I think switching these makes sense. We should just be sure that the post titles stay the same size they are today.
