### ISSUE TITLE
package.json not included in zip

### ISSUE THREAD

**Issue by boxadesign** [Automattic/themes#5615]
## Steps to replicate

When you download this theme the package.json file is not included. Has to be manually created. 
## Result

[What happened.]

## Expected

[What you expected to happen.]

* User report: [shortlink to chat/forum thread/ticket, ie 12345-hc]
* Follow-up ticket: [shortlink to ticket, ie 12345-zen]

**Comment by pbking** [comment]
If development of the project is desired I think working with the repository and [downloading the zip from here](https://github.com/Automattic/themes/archive/refs/heads/trunk.zip) is the best bet.  I'm not sure that the sass should be included in the zip in the theme repository either.
