### ISSUE TITLE
Blockbase: Paragraph block is not respecting Block Spacing setting

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#5616]
## Steps to replicate

* Add a Group block that contains a block and a paragraph block.
* Set the block spacing to 0 for the Group block.
* See the spacing between the two elements in the Group block.

For example:
```
<!-- wp:group {"style":{"spacing":{"blockGap":"0px"}}} -->
<div class="wp-block-group"><!-- wp:heading -->
<h2 id="heading">Heading</h2>
<!-- /wp:heading -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id arcu aliquet, elementum nisi quis, condimentum nibh. Donec hendrerit dui ut nisi tempor scelerisque.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```

## Result

The top margin for the paragraph is still there on the front end. In the editor, the margin isn't there as expected. The CSS for the Quote block seems to be interfering.

**Front-end**
<img width="2560" alt="Screenshot 2022-03-03 at 17 13 03" src="https://user-images.githubusercontent.com/908665/156616400-b53180a0-52c3-4f3d-a27a-ec28da8ee2f0.png">

**Editor**
<img width="2560" alt="Screenshot 2022-03-03 at 17 19 10" src="https://user-images.githubusercontent.com/908665/156617068-0f6c4206-fc24-4645-a77c-e2ce7099715c.png">

## Expected

There shouldn't be any gap between the elements in the front-end.

**Comment by iamtakashi** [comment]
Hi @MaggieCabrera! This is me trying to get attention to this :) Is this also a side effect of [this change](https://github.com/Automattic/themes/pull/5104)?

**Comment by MaggieCabrera** [comment]
Possibly! I'll add this to our board, I don't like these rules, but we can't break people's sites so we need to see how we can fix both this and the original issue.

**Comment by pbking** [comment]
This would be addressed if we bring in #5811

**Comment by pbking** [comment]
This should be addressed now.  @iamtakashi are you able to confirm?

**Comment by iamtakashi** [comment]
Yes, I can confirm the issue has been fixed. Thank you all so much!!
