### ISSUE TITLE
Quadrat: Post Comments Block not aligning and cutting off footer on AT sites

### ISSUE THREAD

**Issue by wprhunt** [Automattic/themes#5622]
### Quick summary

Adding the Post Comments block to the Single Posts template in Full Site Editor when in use with the Quadrat (black) theme, the block does not stay in alignment with the rest of the content (margin missing on both sides regardless of block alignment or if the block is in a group or columns block) and it seems to cause the rest of the page below it to be cut off and you can view the footer of the site and it shows the comment field cut off:

![Uploading EP003 – Local Talent 2022-02-28 14-49-20.jpg…]()

### Steps to reproduce

1. On a site with the Quadrat (black) theme (and there may be other themes) go to the Full Site Editor
2. Edit the Single Post (or possibly any page) template
3. Add the Post Comments block to the bottom of the post template
4. View a blog post on the front end

### What you expected to happen

Alignment of the block should not overlap the footer

### What actually happened

Cuts off the footer and does not align with the content on the rest of the page (left aligned)

### Context

#34427726-hc

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Quadrat (black)

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

This was the workaround we came up with as a CSS rule:

```
.wp-block-post-comments {
    margin-bottom: 50px;
    margin-left: auto !important;
    margin-right: auto !important;
}

#commentform iframe {
    width: 664px !important;
}
```

**Comment by Robertght** [comment]
It looks like we could need more details about this. The screenshot didn't seem to have been saved properly. Could you please re-upload it @wprhunt ?

I can confirm this is an issue only on Atomic sites and affects all Quadrat themes.

**Comment by matiasbenedetto** [comment]
Hi, @wprhunt @Robertght, thanks for the bug report.

Currently, I'm not able to reproduce this. I'm getting this:
![image](https://user-images.githubusercontent.com/1310626/156819186-456f25dc-92a0-48a9-90e2-a4093f03b789.png)

:question:  Could you add a screenshot and confirm if this is still a problem, please?

**Comment by Robertght** [comment]
Thank you for looking into this @matiasbenedetto ! 

This is what I see on my end:

![image](https://user-images.githubusercontent.com/6737345/156873716-f2127a56-fc03-43b7-bf88-6c4bd540eca7.png)

**Comment by MaggieCabrera** [comment]
> Hi, @wprhunt @Robertght, thanks for the bug report.
> 
> Currently, I'm not able to reproduce this. I'm getting this: ![image](https://user-images.githubusercontent.com/1310626/156819186-456f25dc-92a0-48a9-90e2-a4093f03b789.png)
> 
> ❓ Could you add a screenshot and confirm if this is still a problem, please?

@matiasbenedetto if you are looking a sandboxed site then it's a simple site. You need to test it on atomic, which is a bit trickier. [This](https://www.loom.com/share/f6e9efb5232d4931b8f5c7966e3b244b) is how you make a simple site atomic.

**Comment by ai2n** [comment]
Just a note for others, this workaround fixed things for me when there were both comments and pingbacks involved, it also uses max-width instead of width to be responsive-friendly.

```
.wp-block-post-comments .comment-meta {
    margin-left: unset;
}

.wp-block-post-comments .commentlist .comment {
    padding-left: unset;
}

.wp-block-post-comments {
    max-width: 664px !important;
    margin-left: auto !important;
    margin-right: auto !important;
}
```

**Comment by pbking** [comment]
This doesn't seem to be limited to Quadrat but instead seems to be true of every Blockbase theme.

<img width="854" alt="image" src="https://user-images.githubusercontent.com/146530/161610729-2817cc73-67b8-4344-b58e-1b80d429a544.png">

This is due to some grid code used to style "unauthenticated users" form:
<img width="715" alt="image" src="https://user-images.githubusercontent.com/146530/161610852-97c24a83-67b4-4473-83f8-b1e1fea3825b.png">

instead of the default:
<img width="717" alt="image" src="https://user-images.githubusercontent.com/146530/161610966-e8b83544-817d-42a4-ba57-3f421a04d66b.png">

Working through if it's possible to achieve that design while not affecting wpcom comment forms.
