### ISSUE TITLE
[Archeo] Small screen fixes

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5631]
Archeo has a few areas of its mobile templates that need adjustment: 

---

- [x] `home.html` top area https://github.com/Automattic/themes/pull/5645: 

The two areas indicated in pink should use the equivalent of 48px of padding.  

<img width="372" alt="Screen Shot 2022-03-07 at 3 32 36 PM" src="https://user-images.githubusercontent.com/1202812/157113858-56fdfbfc-1404-445b-a632-31dda07193d7.png">

---

- [x] Post lists: https://github.com/Automattic/themes/pull/5638

The spacing above each author name should be moved below it, so that the authors appear associated with the correct post titles on small screens: 

Before|After
---|---
<img width="371" alt="Screen Shot 2022-03-07 at 3 38 27 PM" src="https://user-images.githubusercontent.com/1202812/157114168-891bef37-72f7-4bee-a34f-ef369612edf6.png">|<img width="371" alt="Screen Shot 2022-03-07 at 3 38 19 PM" src="https://user-images.githubusercontent.com/1202812/157114169-a7305e43-2356-4f0a-bf5d-34061f146eb8.png">

---

- [x] Footer menu https://github.com/Automattic/themes/pull/5640:

The spacing and alignment of this footer menu looks like a bug. Can this be left aligned? Can we remove the vertical `blockGap`? 

<img width="374" alt="Screen Shot 2022-03-07 at 3 39 57 PM" src="https://user-images.githubusercontent.com/1202812/157114353-edc779d6-1019-4d90-82b5-2c19996524be.png">

---

- [x] Mobile menu (expanded) needs a little work too. Would it be possible to use the `large` preset size? And to decrease the `blockGap` value? https://github.com/Automattic/themes/pull/5644

Before|After
---|---
<img width="371" alt="Screen Shot 2022-03-07 at 3 42 09 PM" src="https://user-images.githubusercontent.com/1202812/157115076-dcfea691-40a1-4d9f-b5b8-76fd6d99d574.png">|<img width="371" alt="Screen Shot 2022-03-07 at 3 44 59 PM" src="https://user-images.githubusercontent.com/1202812/157115082-de8c69a9-3cef-48ef-a77e-f3654b9bde92.png">

**Comment by kjellr** [comment]
I'm re-opening this one because that second one appears to be broken again: 

Current|Recommended
---|---
<img width="415" alt="Screen Shot 2022-03-22 at 2 14 46 PM" src="https://user-images.githubusercontent.com/1202812/159548361-a7ef838a-3aae-452b-a858-0db0094f3cfc.png">|<img width="420" alt="Screen Shot 2022-03-22 at 2 12 43 PM" src="https://user-images.githubusercontent.com/1202812/159548381-3227dc43-0e45-4718-a705-3de6c4fd195a.png">

**Comment by mikachan** [comment]
Ah good spot, looks like it's been accidentally overwritten. I've brought that change back in here: https://github.com/Automattic/themes/pull/5731
