### ISSUE TITLE
Archeo: Navigation block blockgap not working

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5632]
While working on remote I was going over the Archeo block navigation markup and I think that it is wrong and it's not being applied.

**Comment by mikachan** [comment]
I think `blockGap` is being applied correctly, although the value is about to be changed in this PR: https://github.com/Automattic/themes/pull/5640

Was it just `blockGap` that didn't seem to be working, or was there anything else?

**Comment by MaggieCabrera** [comment]
just blockgap, I changed the value while pairing with Matias and nothing seemed to be happening

**Comment by mikachan** [comment]
Oh! It seems to be working now, or at least it is for me 😅

**Comment by pbking** [comment]
Blockgap is working as expected for me.  Adjusting the blockGap value on navigation block in the `header.html` template part changes the rendering of the desktop menu items.

Closing.  Please reopen if this persists after #5640 lands.
