### ISSUE TITLE
Blockbase: There is no default vertical padding for a Group block with a background colour

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#5642]
## Steps to replicate

* Add a Group block with a background colour
* Add an image and a paragraph

Example:
```
<!-- wp:group {"backgroundColor":"cyan-bluish-gray"} -->
<div class="wp-block-group has-cyan-bluish-gray-background-color has-background"><!-- wp:image {"id":12502,"sizeSlug":"large","linkDestination":"none"} -->
<figure class="wp-block-image size-large"><img src="https://iamtakashi.files.wordpress.com/2021/10/tom-crew-t9srlyizfiq-unsplash.jpg?w=1024" alt="" class="wp-image-12502"/></figure>
<!-- /wp:image -->

<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin id arcu aliquet, elementum nisi quis, condimentum nibh. Donec hendrerit dui ut nisi tempor scelerisque.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group -->
```
## Result

There is no default vertical padding in the Group block, so the image and the paragraph bump the Group block.

**Editor:**
<img width="718" alt="Screenshot 2022-03-09 at 15 08 44" src="https://user-images.githubusercontent.com/908665/157469649-c7646d74-22fe-4bdd-b3aa-4ee136430f64.png">

**Front of the site:**
<img width="738" alt="Screenshot 2022-03-09 at 15 08 36" src="https://user-images.githubusercontent.com/908665/157469702-19810845-a582-40c0-89b4-b64891930bdd.png">

## Expected

I expected there would have been equal default paddings for all the sides. Or no padding at all for all the sides—one could argue that there should be no padding unless it's specified in the padding control in the sidebar.

This is what TT2 does. It's still strange that the side paddings are so large, but I suppose that's the theme style.

 <img width="749" alt="Screenshot 2022-03-09 at 15 15 57" src="https://user-images.githubusercontent.com/908665/157471652-31510c33-3d17-40f4-8190-8a53ea1abfc3.png">

**Comment by pbking** [comment]
Interestingly, I have found that with TwentyTwentyTwo activated a group block with a background has padding added via styles provided by Gutenberg:
```
:where(.wp-block-group.has-background){padding:1.25em 2.375em}
```

However, this is not true of Blockbase.  I can't find a setting or anything that should cause that CSS to be added for TTT but not Blockbase (nor the inverse of finding anything in Blockbase that should cause that to be excluded), nor why the values of 1.25em or 2.375em are used.  I would have expected the Blockgap value to be used which in TTT is `1.5rem`

**Comment by mikachan** [comment]
I think I've managed to track this down to Blockbase not supporting default block styles, which TwentyTwentyTwo does (and a couple of our other themes).

With `wp-block-styles` enabled, that `.wp-block-group.has-background` padding CSS is included (more info on what's included [here](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-support/#default-block-styles)).

I've opened up a PR to try this out in Blockbase: https://github.com/Automattic/themes/pull/5792

**Comment by scruffian** [comment]
I wonder if a better solution would be to move these group block styles from the theme.css to the style.css so they ship for all group blocks?

**Comment by pbking** [comment]
> I think I've managed to track this down to Blockbase not supporting default block styles, which TwentyTwentyTwo does (and a couple of our other themes).

At least that explains the difference!  Thanks for tracking that down @mikachan 

> I wonder if a better solution would be to move these group block styles from the theme.css to the style.css so they ship for all group blocks?

That (a different padding value when there is a background color) feels like opinion to me, which is what you're asking for with `wp-block-styles`.

Adding that opinion to Blockbase wouldn't be hard, and if that is the only opinionated styles we want from `wp-block-styles` then perhaps we should consider just adding that to the ponyfill.
