### ISSUE TITLE
Remote: Tag cloud looks wrong on dotCom

### ISSUE THREAD

**Issue by matiasbenedetto** [Automattic/themes#5649]
## Steps to replicate
Add a tag cloud block to a site and look at how it is rendered on dotCom.

## Result
![image](https://user-images.githubusercontent.com/1310626/157643295-c382d5f6-8213-40d7-a525-e5f8e269f474.png)

## Expected
![image](https://user-images.githubusercontent.com/1310626/157643314-4fff9e57-69f2-42e1-baa9-94d6fc230306.png)

It should look like the expected image.

**Comment by matiasbenedetto** [comment]
Potential fix: D76470-code

**Comment by jffng** [comment]
Landed the above fix.
