### ISSUE TITLE
Blockbase theme: body text does not scale to browser default settings

### ISSUE THREAD

**Issue by SamuelMiller** [Automattic/themes#5659]
In Chrome, under Appearance in Settings, change the font size to large or very large. Body text (text in the main section of the webpage) does not scale when the default font size in the browser is changed, which is poor for accessibility. 

I can correct it by adding "body {font-size:100%;}" in the Blockbase's ponyfil.css file.  Alternatively, defining the body element as font-size:1.2rem, for example, also appears to work. Normally, one would put the 100% font size in the HTML tag; however, in this case, it doesn't do anything. Also, one has to make sure that the header and footer template parts are defining the font sizes in rem/em in the editor, not px., so that the text in this section also changes appropriately.

In addition, looking at Blockbase's theme.json font sizes, starting line 375, are being defined in px rather than rems. 

For example, 
         fontSizes": [
				{
					"name": "Small",
					"size": "16px",
					"slug": "small"
				}, 

etc..

In contrast, the Twenty Twenty Two Theme defines font-size with rem:

"fontSizes": [
				{
					"size": "1rem",
					"slug": "small"
				},

The site https://richtabor.com/standardizing-theme-json-font-sizes/ suggests standardizing font sizes in rems as in the following:

```
{
"settings": {
    "typography": {
	"fontSizes": [
		{
			"name": "Tiny",
			"size": "0.64rem",
			"slug": "tiny"
		},
		{
			"name": "Small",
			"size": "0.8rem",
			"slug": "small"
		},
		{
			"name": "Normal",
			"size": "1rem",
			"slug": "normal"
		},
		{
			"name": "Large",
			"size": "1.25rem",
			"slug": "large"
		},
		{
			"name": "Extra Large",
			"size": "1.563rem",
			"slug": "extra-large"
		},
		{
			"name": "Huge",
			"size": "1.953rem",
			"slug": "huge"
		},
		{
			"name": "Gigantic",
			"size": "2.441rem",
			"slug": "gigantic"
		}
	]
    }
}
}

**Comment by MaggieCabrera** [comment]
This is a good point, I think we should consider this
