### ISSUE TITLE
Blockbase: Navigation block shows underlines on links in Site Editor, but not on live site

### ISSUE THREAD

**Issue by jordesign** [Automattic/themes#5670]
## Steps to replicate

* Activate Blockbase or a child theme
* In the Site Editor - add a menu to the Navigation block in the header. Confirm it shows underlines on the links/items.
*  View the live site.
<img width="1190" alt="Screen Shot 2022-03-16 at 3 13 40 pm" src="https://user-images.githubusercontent.com/1842363/158515717-ff479b9e-53c6-44d4-9dda-91dd62f7209c.png">

## Result

Links show without underlines

<img width="1192" alt="Screen Shot 2022-03-16 at 3 13 25 pm" src="https://user-images.githubusercontent.com/1842363/158515735-2a35ff79-89d5-42eb-999e-3e53ffbbec83.png">

## Expected

I expected the display of the menu items to be consistent between Site Editor and live site

**Comment by bjr70** [comment]
We have this same issue. Looking for a solution.
