### ISSUE TITLE
Pendant: Pre-launch: readme.txt

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5678]
Verify and include the correct version of WordPress required for this theme.  Also include any requirements of the Gutenberg plugin.  
(These values should also be updated in style.css if they need to change).

Remove any changelog values that may have been inserted during development and include simply:
```
= 1.0.0 =
* Initial release
```

Include links to any 3rd party resources for attribution.

**Comment by WeCreos** [comment]
I don't understand the problem here.

**Comment by pbking** [comment]
@beafialho where did the pictures for the design/patterns originate so that we might attribute the source?

**Comment by beafialho** [comment]
I'll gather all the pictures links and post them here @pbking

**Comment by beafialho** [comment]
I believe these are all:

Gallery Pattern
https://stocksnap.io/photo/people-girl-TDP31WN0WB
https://stocksnap.io/photo/mystery-woman-5G7JGBR9E0
https://stocksnap.io/photo/I08C8XDJ6J
https://stocksnap.io/photo/people-girl-O6MBP1UB5X
https://pxhere.com/en/photo/775017

Our Picks
https://www.metmuseum.org/art/collection/search/248813
https://www.metmuseum.org/art/collection/search/452273?ft=ring&amp;offset=0&amp;rpp=40&amp;pos=13
https://www.metmuseum.org/art/collection/search/243039?ft=earrings&amp;offset=0&amp;rpp=40&amp;pos=24

Latest Articles
https://pxhere.com/pt/photo/41666
https://www.si.edu/object/wristwatch-hour-angle-lindbergh-king-collection:nasm_A20040287020
https://www.metmuseum.org/art/collection/search/256970
https://www.metmuseum.org/art/collection/search/236772

Pages
https://stocksnap.io/photo/blonde-woman-S6JWBGXSUM
https://stocksnap.io/photo/wall-white-3TA5332IJ4
https://stocksnap.io/photo/smiling-woman-W6GFOSFAXA
https://stocksnap.io/photo/smiling-woman-OQWE4BR8SP
https://stocksnap.io/photo/man-smiling-MKVSGM8TO9
https://stocksnap.io/photo/shaking-hands-GEKK2UOHCY
https://stocksnap.io/photo/hand-jewelry-VHIX76K7EH
https://www.metmuseum.org/art/collection/search/242952

**Comment by pbking** [comment]
Fixed in #5950
