### ISSUE TITLE
Pendant: Global Styles: Margin/spacing/layout

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5685]
From [figma](JdntsOfLqo8Vy0d5uTWHTI-fi-650%3A2):

Content width: 820
Wide width: ?? (unable to determine)

Block gap appears to be about 30px (29?)

Page horizontal gap seems to be 100px on desktop and 20px on mobile (so should leverage a dynamic value)

**Comment by pbking** [comment]
These bits seem to be addressed while working on the [header](https://github.com/Automattic/themes/pull/5725).  

We should be able to evaluate details once that lands.

**Comment by pbking** [comment]
The latest has landed and I think we look good for: 
* Content width (800) 
* wide width (1000px) 
* the horizontal gap along the edge (dynamic clamp() value, discussed working on the header) for full-width 
* The global block-gap value (also dynamic, with a maximum of 30px scaling down to 5vw ~ 18px @ iphone size)"
* Line height of body text (1.6)

Wide view:
<img width="1592" alt="image" src="https://user-images.githubusercontent.com/146530/159988254-81dae34c-bba4-4bfd-9baa-75d7853814b1.png">

Narrow view:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/146530/159988357-f09460d7-9abd-458e-b2de-258a7446d57b.png">

**Comment by beafialho** [comment]
Thanks @pbking, overall this looks good to me. 

Just to note that some elements should look completely full-width, such as quotes. Would that be possible with the current settings?

<img width="882" alt="Captura de ecrã 2022-03-25, às 16 30 22" src="https://user-images.githubusercontent.com/65220155/160162146-562164b7-bf7e-4c9e-89c6-c6be8fbbbec7.png">

**Comment by pbking** [comment]
> Thanks @pbking, overall this looks good to me.

Thanks for looking it over.  I'll close this and we can iterate on anything related that may creep up.

> Just to note that some elements should look completely full-width, such as quotes. Would that be possible with the current settings?

I don't think that we could "full width" them by default.  It should be relatively easy to configure them such that in their default state when they are setup to be full width in the content it looks like the above.

And probably more specifically to your point full-widthing something with a background color will still take us to the edge:

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/146530/160167028-1ceaa65b-6ae6-4751-9c26-a2ff9e8e7681.png">
