### ISSUE TITLE
Pendant: Pre-launch: style.css tags

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5689]

**Comment by MaggieCabrera** [comment]
Test to see if the Stale label goes away

**Comment by pbking** [comment]
It has not yet gone away... perhaps because of the limited number of items the action works on?  And since we started at the bottom and worked our way back up?

**Comment by MaggieCabrera** [comment]
Looking at the actions it seems like it's always processing the same batch of issues, so I'm going to see what's going on with that
