### ISSUE TITLE
Pendant: Variations

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5692]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/146530/162965967-0d8708e2-7f25-44b1-af84-1034862b408f.png">

**Comment by pbking** [comment]
@beafialho do you expect these Color Studies to resolve in alternate color palettes for Pendant?

<img width="623" alt="image" src="https://user-images.githubusercontent.com/146530/159981736-c3370a97-4241-4225-8f9c-5ff1e680f9d2.png">

**Comment by beafialho** [comment]
@pbking no, everything under "Drafts" is old explorations. I'm going to work on some alternate color palettes for Pendant and will let you know.

**Comment by pbking** [comment]
Coolio, thank you.

**Comment by beafialho** [comment]
@pbking since we will be no longer limited to color variations in themes, I added a few Style Variations to [the Figma file](https://www.figma.com/file/JdntsOfLqo8Vy0d5uTWHTI/?node-id=1729%3A50) that are fewer but accomplish totally different design moods.

**Comment by pbking** [comment]
I believe all of the variations have been completed.  Closing this.

Any further variation changes that are needed should be opened as new items.
