### ISSUE TITLE
Livro: FATAL error in WP-Admin

### ISSUE THREAD

**Issue by markhowellsmead** [Automattic/themes#5704]
## Steps to replicate

Line 63 in functions.php causes a fatal error because the function `livro_editor_styles` isn't defined

## Result

Fatal error when trying to load WP admin.

## Expected

No fatal error :)

**Comment by KokkieH** [comment]
Noting via https://wordpress.org/support/topic/fatal-error-in-wordpress-admin-2/ this appears to happen as soon as v1.0.8 of the themes is activated.

v1.0.7, available via the wpcom theme showcase/Jetpack, does not cause any errors.

**Comment by pbking** [comment]
I didn't get the fatal error myself, however I see that it's referencing a function previously removed.  The hook has been removed.

**Comment by Piyopiyo-Kitsune** [comment]
The Admin is not fatal-erroring, but I still see `( ! ) Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'livro_editor_styles' not found or invalid function name in /Users/X/Local Sites/X/app/public/wp-includes/class-wp-hook.php on line 307` in the admin.

**Comment by KokkieH** [comment]
I don't see any errors any more if I activate v1.0.9 of the theme. Thanks for the quick fix!
