### ISSUE TITLE
Dyad 2 / Dyad: Social Icons block | Icon styles are swapped

### ISSUE THREAD

**Issue by LauraSWP** [Automattic/themes#5706]
## Steps to replicate

1. Activate the Dyad 2 theme
2. Add a Social Icons block to a widget area
3. Add an icon to the block
4. Try changing between the “default” and “pill shape” styles

## Result

The “pill shape” setting makes the icon “round” (aka “default”). Also, comparing the block behavior in the Editor and the Customizer, the pill shapes are different (one is vertical, the other horizontal).

## Expected

That choosing “pill shape” would make the icon “pill shaped”.

* User report: https://wp.me/pd4QKa-vv

![imagen](https://user-images.githubusercontent.com/63611065/158989172-8a16948b-c6d6-4436-bfea-cf41443729af.png)

**Comment by Robertght** [comment]
Thank you for reporting this @LauraSWP ! Please use Bugomattic to report further theme issues as it'll help us triage them faster.

**Comment by fetenlakhal** [comment]
I think the same thing is happening with Dara theme.

**Comment by bobmatyas** [comment]
I confirmed the same behavior in Dara:

<img width="939" alt="Screenshot on 2022-07-13 at 15-29-04" src="https://user-images.githubusercontent.com/45246438/178815978-577b0790-130b-4ac7-a1d4-7dd197ca9df6.png">
