### ISSUE TITLE
Editor theme: Marketing banner obscures theme elements

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#5726]
### Quick summary

The marketing banner shown on free WordPress.com sites obscures some elements of the theme, namely the menu, featured content and widget controls.

### Steps to reproduce

1. Enable Editor on a completely free site that has never been upgraded
2. Make sure site is launched and set to public
3. View the site (the marketing banner doesn't always show while logged in, so try logging out if it doesn't appear)

### What you expected to happen

For the marketing banner to show at the top, with any theme elements only appearing below it.

### What actually happened

The marketing banner obscures the theme controls which appear at the very top-left.

Without banner:
<img width="682" alt="Cursor_and_Editor___Simply_beautiful_publishing_powered_by_WordPress_" src="https://user-images.githubusercontent.com/11873759/158325948-c1ae4fcd-ef91-4dbf-87c2-65cde2c08047.png">

With banner:
<img width="919" alt="Cursor_and_boogeefse" src="https://user-images.githubusercontent.com/11873759/158326028-ffaec610-4dbe-4de6-9105-b24382cf6958.png">

### Context

Reported in https://wordpress.com/forums/topic/wordpress-banner-hides-the-menus-of-my-blog/

This is also similar to an issue I reported some time ago with the banner obscuring controls for the theme-info overlay for superadmins in Automattic/wp-calypso#47827

### Theme-specific issue?

Editor

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

To prevent this site needs to be upgraded/the No Ads upgrade applied, in which case we no longer display the banner.

**Comment by KokkieH** [comment]
Thank you :)

**Comment by mmtr** [comment]
Prepared a fix for this: D156983-code
