### ISSUE TITLE
Blog Posts Block: Load More Posts button doesn't have the same styling as seen in editor

### ISSUE THREAD

**Issue by mriyazuddin** [Automattic/themes#5739]
### Quick summary

The Load More Posts button on the Blog Posts Block seems to appear fine in the editor but on the front end it appears like the old school push button.

### Steps to reproduce

1. Create a page and add Blog Posts Block.
2. Enable Load More posts button using the settings sidebar of the Blog Posts Block.
3. The button appears fine in the editor but not on the front end.

### What you expected to happen

The Load More button should have had the same styling as seen in the editor.

<img width="1440" alt="Markup 2022-03-23 at 16 53 39" src="https://user-images.githubusercontent.com/49064126/159688810-6eec5c43-e48e-4433-acc5-725efe4d680a.png">

### What actually happened

The Load more button appears like the old school push button.

<img width="1440" alt="Markup 2022-03-23 at 16 55 50" src="https://user-images.githubusercontent.com/49064126/159689094-c3645f94-fb15-420a-846f-772f6d26bb9a.png">

### Context

#34822388-hc | #4884923-zd

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

On AT sites I was able to duplicate this issue with the Dorna theme. On other themes on AT sites the button appears fine.

On simple sites, I was able to duplicate this issue regardless of the theme.

### Browser, operating system and other notes

Googel Chrome Version 99.0.4844.83 (Official Build) (x86_64)
macOS Monterey 12.2.1 (21D62)

**Comment by TPilgs** [comment]
Another instance here #35163695-hc

**Comment by sharonlaker19** [comment]
+1 at 35559561-hc, shared the CSS workaround.

**Comment by mikeicode** [comment]
Ran into this using the theme Meraki, used CSS to resolve. pdEkSe-xG-p2

**Comment by sguzovskaia** [comment]
Another case: 35462717-hc/5281306-zen, shared the CSS workaround.

**Comment by IoanaAMuresan** [comment]
Another instance 5277070-zen - free site so no CSS workaround for them.

**Comment by pbking** [comment]
> Transferring this to the Themes repo, since the styling for the button element would need to be added to the themes!

Rather this seems to be in issue with the 'Block Posts' block which leverages a `<button>` element rather than a `Button Block` which would be styled as expected.  Otherwise changes to button styles via Global Styles wouldn't be picked up by this button.

I believe this should be closed and the [newspack block item mentioned above](https://github.com/Automattic/newspack-blocks/issues/357) re-opened to address the underlying issue.

**Comment by Gustavo-Hilario** [comment]
Another report here: 5286779-zen

**Comment by pbking** [comment]
Closing this as it needs to be fixed in the [`Blog Post` block](https://github.com/Automattic/newspack-blocks/issues/357).
