### ISSUE TITLE
Archeo: incorrect positioning of featured images with short post titles

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5743]
## Steps to replicate

Add a featured image to a post on the homepage template. Make sure the post title is quite short, e.g. "Fossils"

## Result

If the title is short enough, the featured image will sit in line with the title rather than underneath it:

![image](https://user-images.githubusercontent.com/1645628/159970111-4cffcb94-0dda-4a3c-b1d0-02cce0fae6bb.png)

## Expected

Ideally, all featured images in the post query should sit below the title.

![image](https://user-images.githubusercontent.com/1645628/159970578-8e26d8ca-4f5d-43da-8c6b-d37ba2ea1a62.png)

* User report: p7DVsv-e9p-p2#comment-40071

**Comment by MaggieCabrera** [comment]
I don't think this is a theme issue, more a matter of how the user has modified the home template. The theme by default doesn't include the featured image on the home page for the query block so we can't really fix this in the theme, merely give this user the correct code to use on their site.

In this case this would be the query block for that specific user:

```
<!-- wp:query {"queryId":3,"query":{"pages":0,"offset":0,"postType":"post","order":"desc","orderBy":"date","author":"","search":"","exclude":[],"sticky":"","inherit":false,"perPage":3},"displayLayout":{"type":"list","columns":3}} -->
<div class="wp-block-query"><!-- wp:post-template -->
<!-- wp:group {"className":"simple-list-of-posts","layout":{"type":"flex","allowOrientation":false,"orientation":"vertical"}} -->
<div class="wp-block-group simple-list-of-posts"><!-- wp:post-title {"isLink":true,"style":{"typography":{"lineHeight":"1.2","fontStyle":"normal","fontWeight":"100"},"spacing":{"margin":{"top":"1.25rem"}}},"fontSize":"huge"} /-->

<!-- wp:post-featured-image {"isLink":true,"width":"80%","height":""} /-->

<!-- wp:post-excerpt /--></div>
<!-- /wp:group -->
<!-- /wp:post-template -->

<!-- wp:spacer {"height":"40px"} -->
<div style="height:40px" aria-hidden="true" class="wp-block-spacer"></div>
<!-- /wp:spacer -->

<!-- wp:query-pagination {"paginationArrow":"chevron","layout":{"type":"flex","justifyContent":"space-between"}} -->
<!-- wp:query-pagination-previous /-->

<!-- wp:query-pagination-next /-->
<!-- /wp:query-pagination --></div>
<!-- /wp:query -->
```

**Comment by mikachan** [comment]
Thanks @MaggieCabrera, that makes sense! 

I'll close this for now, but happy to re-open if this doesn't fix the issue.
