### ISSUE TITLE
Pendant: Templates: About Page

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5745]
This page will consist of four patterns: 

<img width="326" alt="image" src="https://user-images.githubusercontent.com/146530/159976951-969ed660-84f0-499e-9a9a-d86142954d7c.png">
 
* Media & Text
* Image and Quote
* Team 

Once the design of the page and contained blocks is approved we'll extract the patterns from it.

**Comment by beafialho** [comment]
@pbking I also added a mobile [mockup](https://www.figma.com/file/JdntsOfLqo8Vy0d5uTWHTI/Pendant?node-id=1597%3A216) for the About page.
