### ISSUE TITLE
Apostrophe 2: Follow Blog Widget Unreadable Again 

### ISSUE THREAD

**Issue by torres126** [Automattic/themes#575]
## Steps to replicate

1. Use the Apostrophe 2 theme and the default colour pack 
2. Add a Follow Blog Widget to the Secondary Widget option

## Result

![screenshot_20190208-084113](https://user-images.githubusercontent.com/43215253/52467483-9d365200-2b7d-11e9-9a3d-ebc99959e1a1.jpg)

## Expected

For the "Follow" button to be easier to see in its normal state 

* User report: https://en.forums.wordpress.com/topic/apostrophe-2-odd-glitch-with-the-follow-button-on-email-subscription-widget/

Probably a defect of #537, user mentioned it was a recent change

**Comment by torres126** [comment]
#496

**Comment by laurelfulford** [comment]
🤦‍♀️ Gah, thanks for catching this. 

A fix has been committed to WP.com in r53319-wpcom-themes; I'll follow up in the forum thread!

**Comment by laurelfulford** [comment]
Ah, nevermind, already done! 😄

**Comment by torres126** [comment]
Oops, already posted in the thread. :sweat_smile:

Thanks for the fix!
