### ISSUE TITLE
Twenty Twenty Two: Missing font options

### ISSUE THREAD

**Issue by Gustavo-Hilario** [Automattic/themes#5756]
## Steps to replicate

1. Activate the `Twenty Twenty Two` theme.
2. Go to the Site Editor.
3. Got to the Styles options in the top-right corner.
4. Select `Typography` > `Text`.
5. You will see no options to change the site font. 

If you go to the Customizer, you won't see any options there too.

<img width="355" alt="Markup 2022-03-26 at 09 23 24" src="https://user-images.githubusercontent.com/50875131/160243810-f2ae98ef-e2ea-48d2-9ac7-378f91ec837c.png">

## Result

We can only see the default options there.

## Expected

I'd expect to see much more options there.

* User report: 4892433-zen. The user here said that yesterday (2022-03-25), they could select the `Libre Baskerville` font there.

**Comment by Robertght** [comment]
Thank you for reporting this @Gustavo-Hilario and @edequalsawesome for the ping!

I've looked into this and at the moment the behavior is consistent regardless of the hosted site.

Upon further investigation, with some help from @MaggieCabrera, it appears this will be an[ option available](https://github.com/Automattic/jetpack/pull/23045) in a future release of Jetpack(10.8). Will this be implemented on .com as well at the same time, @jeherve ? 

Internal ref: paYE8P-1pA-p2

**Comment by jeherve** [comment]
@creativecoder would know more, but I believe that before we enable it for everyone on WordPress.com, we'll need to address some potential performance issues.

**Comment by pbking** [comment]
I believe this can be closed now.  The Jetpack item noted above is available to all and I see the font options on TwentyTwentyTwo (and I think all Block themes?)

<img width="337" alt="image" src="https://user-images.githubusercontent.com/146530/180456969-889b14d0-c1f5-4820-8f29-5db55ca81663.png">

If you can confirm this can be closed.

**Comment by Gustavo-Hilario** [comment]
Yep. Tested this on Simple and AT sites with `Twenty Twenty Two` and other blockbased themes, and this seems to be working again.
