### ISSUE TITLE
[Remote] Contact form button hover state increases the button's size

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5776]
Not sure if this is a theme issue or not, but when you hover over the Contact form's button, it increases its size, pushing other items on the team down the page: 

![hover](https://user-images.githubusercontent.com/1202812/160414670-bcb13141-fc92-42cb-90e2-dd7fb72303d2.gif)

This is visible in the theme demo: https://remotedemo.wordpress.com/about/

**Comment by jffng** [comment]
It looks like Jetpack CSS sets a `border: inherit;` on the `wp-block-jetpack-button-button` class which is of higher specificity than `wp-block-button` (because it loads after global styles) but lower than the hover state, so it causes the border width to change across states.

**Comment by MaggieCabrera** [comment]
After discussing this with @kjellr, let's fix this one on the theme since we are providing hover effects for the button

**Comment by jffng** [comment]
After looking into this more, I think we should remove the CSS in Jetpack that is overriding Core + theme's default button styles: https://github.com/Automattic/jetpack/pull/23734

**Comment by MaggieCabrera** [comment]
Closing since this was resolved upstream
