### ISSUE TITLE
Pendant: use rem unit for fonts instead of px for better a11y

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#5794]
For better a11y, use `rem` units for fonts in `theme.json`.

Steps:
* In browser settings update font size to small or large
* observe that page content doesn't get effected with this setting when `px` units used.

**Comment by MaggieCabrera** [comment]
We could probably do this for Archeo, Livro, Stewart and Remote too.

**Comment by pbking** [comment]
Thank you @madhusudhand good call.

This was addressed with other changes to font sizes [here](https://github.com/Automattic/themes/commit/7aaeda4aafa2d326067548e9597529f0dbb4734b).

**Comment by madhusudhand** [comment]
> We could probably do this for Archeo, Livro, Stewart and Remote too.

Created https://github.com/Automattic/themes/pull/5801 for other themes.
