### ISSUE TITLE
Shoreditch: Windows 7 users see blank dropdowns with default color palette.

### ISSUE THREAD

**Issue by spncrb** [Automattic/themes#58]
## Steps to replicate

1) Choose Shoreditch
2) Retain the default color palette
3) Add a widget with a dropdown, like google translate to the footer.
4) Check it out on Windows 7/Chrome:
![screen shot 2018-04-03 at 3 09 17 pm](https://user-images.githubusercontent.com/8921630/38278630-b28357dc-3751-11e8-9c48-89bf08d1b3d9.png)

## Result
White on white text.

## Expected

If you change to any other palette, it has enough contrast:
![screen shot 2018-04-03 at 3 03 45 pm](https://user-images.githubusercontent.com/8921630/38278641-c2f2968c-3751-11e8-8454-9b6108a76e06.png)

* User report: #1050975-zen
* User's site: https://lascolinasproperty.com/

**Comment by laurelfulford** [comment]
It looks like the original ZD ticket is closed, so I'm unable to leave a comment.

@spncrb Can you please follow up with the customer to let them know this is fixed? Thank you!

**Comment by spncrb** [comment]
Updated user in #1137566-zd - thank you!
