### ISSUE TITLE
Zoologist headstart bug

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5809]
It looks like Zoologist headstart is carrying a bug that was already fixed on the code of the theme. Mainly the extra div around the query pagination that was removed by https://github.com/Automattic/themes/pull/4805 but the headstart was never updated with this change.

To reproduce this I created a new site, starting with Zoologist as default theme and no other content than the default hello world post. I was never printed if I wanted the demo content at all and I see the double line caused by the unwanted div:

<img width="800" alt="Screenshot 2022-04-04 at 10 53 43" src="https://user-images.githubusercontent.com/3593343/161509955-051ec954-abfa-4e9a-9a6b-1504a311e609.png">

This is likely to be affecting all Blockbase children, and any other markup that we are not updating on headstarts will make bugs persistent. We also can't simply re generate headstarts since some have been through some kind of manual editing to trim the number of posts or any other type of change. In this case the error is not breaking sites, just a minor visual bug, but this could lead to problems when you can't solve the bug for existing user sites if the site has been created through headstart.

**Comment by jeffikus** [comment]
Sounds like a small change. Let's keep this on the board. @pbking and I are going to work on the headstart for Pendant next week so I could perhaps look at this at the same time.

**Comment by pbking** [comment]
The change for this can be found here: D85662-code

I looked at all of the themes changed in #4805 and only Zoologist and Quadrat seemed to need adjusting.

I have modified only the `en.json` version.  Do all languages need to be changed?

**Comment by mikachan** [comment]
Closing this as D85662-code has been deployed 🎉
