### ISSUE TITLE
Cubic: spacing missing between gallery blocks

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5814]
## Steps to replicate

Since https://github.com/WordPress/gutenberg/pull/38164 has merged, there will now be no default margin set between gallery blocks. This will affect themes that were relying on the margin on the gallery images to provide a gap between galleries, rather than actually setting a top margin to separate the blocks. As GB has switched from using margin to gap to separate the images in a gallery this removes this default separation.

Cubic is impacted by this:

Before|After
------|-----
<img width="653" alt="image" src="https://user-images.githubusercontent.com/1645628/161716038-5e9c34fa-7318-4f67-b56f-aac101d25d30.png">|<img width="654" alt="image" src="https://user-images.githubusercontent.com/1645628/161716355-4ee23a55-d2c7-4f4e-a4f9-fa98e6112c2f.png">

We could apply a CSS patch to fix this, for example:

```
figure.wp-block-gallery.has-nested-images {
    margin-top: 16px;
}
```

User report: p1649072900167279-slack-C029FM1EH

**Comment by madhusudhand** [comment]
Parent theme `boardwalk` also impacted.

**Comment by pbking** [comment]
I see the potential fix can be found here: D78763-code

Looks like a situation isn't covered by that fix (yet) though. (`.wp-block-gallery:not(.has-nested-images`) and needs another look-see.  Moving back to in-progress for some more tweaking.

**Comment by madhusudhand** [comment]
Changes deployed and verified.
