### ISSUE TITLE
Remote: pre launch tasks

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5815]
Tasks left to do to launch Remote on dotcom:

- [x] Headstart annotation D78187-code
- [x] Submit the annotation to linguine after deploy
- [x] Glotpress project D78189-code
- [x] Showcase page

**Comment by MaggieCabrera** [comment]
@kjellr @beafialho I created the showcase page but we are missing the images for it, as well as any tags you all want associated with the theme, if you could review it when you can it would be ace

**Comment by kjellr** [comment]
I'll pull together the images today. 👍

**Comment by kjellr** [comment]
Images should be all set. I took a look at the tags, and I think they're fine too. Should be all set!

**Comment by MaggieCabrera** [comment]
Thank you @kjellr !
