### ISSUE TITLE
 Style Desktop Version of Navigation Overlay

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#5818]
<img width="867" alt="image" src="https://user-images.githubusercontent.com/146530/161790872-d083b999-3728-40c4-905a-495ab8c772e5.png">

or

<img width="841" alt="image" src="https://user-images.githubusercontent.com/146530/161790907-f4a57905-d420-4ded-90ec-2b99453e65a6.png">

Make sure the [mobile navigation](https://github.com/Automattic/themes/pull/5800) design stays put.

**Comment by beafialho** [comment]
Just to clarify, the second mockup is an example of what the menu would look like without subitems, and it should be vertically centered.
