### ISSUE TITLE
Blockbase + block themes: comments block

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5833]
The new comments block is already in GB, we should start a PR to implement it on Blockbase and see how much CSS we can remove from it. The block will make it to 6.0 so we should update the required version accordingly.

https://github.com/WordPress/gutenberg/pull/40186

This goes for any of the block themes that may have extra CSS just for the comment block too

**Comment by jeffikus** [comment]
@MaggieCabrera would we need to wait for 6.0 to ship first before shipping updates to the themes, or can we ship in preparation for this?

**Comment by MaggieCabrera** [comment]
We've discussed about breaking changes on Blockbase that require Gutenberg and decided against them for the parent theme (but they are ok for child themes). We want to keep Blockbase working without the plugin, since it's been used as a parent theme for production sites outside our own child themes.

**Comment by MaggieCabrera** [comment]
Please note that the Comments form block is not going to make it to 6.0, but it's good that we start opening the PRs in any case.

**Comment by MaggieCabrera** [comment]
More on this: https://github.com/WordPress/gutenberg/issues/40521

**Comment by jp-imagines** [comment]
Just noting that this came up in 5279831-zd-woothemes, as the depreciated _Post Comments_ block's "notify by email" checkboxes overlap, and switching to the _Comments_ block resolves that. Informed the user how to update to the newer _Comments_ block, as an eventual switch here won't have affected them since they already made edits to their _Single Post_ template (per p1654700804534859-slack-C029FM1EH).

![Markup on 2022-06-08 at 11:30:19](https://user-images.githubusercontent.com/5630717/172656840-a8c8d860-de96-4b75-85e8-8ee5742554a4.png)

**Comment by pbking** [comment]
Considering that the comments block isn't in 6.0, and that our aim for Blockbase is to be limited to what features are available in core-sans-gutenberg this change isn't likely there yet.

Do we know when we can expect this comments block to head into Core?

Is there something we can/should to with CSS to address that overlap in the meantime?

That said, I don't think we need to hold any of the child themes to that standard so we can begin to update the rest of those themes.

**Comment by MaggieCabrera** [comment]
> Considering that the comments block isn't in 6.0, and that our aim for Blockbase is to be limited to what features are available in core-sans-gutenberg this change isn't likely there yet.
> 
> Do we know when we can expect this comments block to head into Core?
> 
> Is there something we can/should to with CSS to address that overlap in the meantime?
> 
> That said, I don't think we need to hold any of the child themes to that standard so we can begin to update the rest of those themes.

I think the query loop made it, just not the forms block, and we can keep using the legacy one for that. So told me the frontity people during WC, which are the ones leading the Comments block effort
