### ISSUE TITLE
Blockbase: audit ponyfill for 6.0

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#5847]
Now that 6.0 is near, we should review Blockbase's CSS and see if we can remove more stuff (and bump the WP required version as we do so).

- Comments block https://github.com/Automattic/themes/issues/5833
- Separator block changes https://github.com/Automattic/themes/pull/5834
- We could add variations that mirror the palettes we are providing in the customizer options. This will show theme developers how variations are handled via FSE.
- If https://github.com/WordPress/gutenberg/pull/39926 makes it to 6.0 we can remove the alignments styles too

Any other changes come to mind?

**Comment by jeffikus** [comment]
Nice work creating this 'overview' issue.

**Comment by MaggieCabrera** [comment]
tagging @beafialho for opinion on adding variations to some of our other themes (maybe livro, archeo, stewart?)

**Comment by beafialho** [comment]
@MaggieCabrera this makes sense to me. I'm curious to know your thoughts on adding style variations to all themes from now on, similarly to what we did with patterns? Would like to know @mtias thoughts too.

**Comment by MaggieCabrera** [comment]
> @MaggieCabrera this makes sense to me. I'm curious to know your thoughts on adding style variations to all themes from now on, similarly to what we did with patterns? Would like to know @mtias thoughts too.

yes, I think style variations are a great idea, we can add them to the theme as part of the release or afterward like we are doing for other themes like remote, I don't have a preference.

**Comment by beafialho** [comment]
I'll add it to my list to create some style variations for Livro, Archeo and Stewart :+1:

**Comment by mtias** [comment]
What are these variations about?

**Comment by beafialho** [comment]
@mtias these are [style variations](https://github.com/WordPress/gutenberg/issues/39700), as in the TT2 theme.

**Comment by mtias** [comment]
Ah, I misread it as block style variations!
