### ISSUE TITLE
Pendant: "Our Picks" pattern adjustment to align with page's content

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#5863]
_Related to #5690_

In the demo site, I noticed this pattern wasn't vertically aligned with the rest of the content, as it is on Figma. 

To achieve that, I used the columns block instead of the row block but I'm not sure that's a good alternative because it doesn't scale very well. Could someone look into what the best alternative is to achieve the design?

<img width="1531" alt="Captura de ecrã 2022-04-14, às 09 30 55" src="https://user-images.githubusercontent.com/65220155/163346626-9de935d8-ebc6-49d7-bb68-03c66f397ecc.png">

Smaller screen:
<img width="704" alt="Captura de ecrã 2022-04-14, às 09 35 35" src="https://user-images.githubusercontent.com/65220155/163347101-018347bc-f8c2-4b80-9fea-140e52557dc4.png">

Markup using columns:

```
<!-- wp:group {"backgroundColor":"tertiary","layout":{"inherit":true}} -->
<div class="wp-block-group has-tertiary-background-color has-background"><!-- wp:columns {"verticalAlignment":"center","align":"wide","style":{"spacing":{"padding":{"top":"60px","bottom":"60px"}}}} -->
<div class="wp-block-columns alignwide are-vertically-aligned-center" style="padding-top:60px;padding-bottom:60px"><!-- wp:column {"verticalAlignment":"center","width":"40%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:40%"><!-- wp:heading {"textAlign":"left","level":4} -->
<h4 class="has-text-align-left">Our Picks</h4>
<!-- /wp:heading --></div>
<!-- /wp:column -->

<!-- wp:column {"verticalAlignment":"center","width":"60%"} -->
<div class="wp-block-column is-vertically-aligned-center" style="flex-basis:60%"><!-- wp:group {"layout":{"type":"flex","justifyContent":"right"}} -->
<div class="wp-block-group"><!-- wp:image {"id":54,"width":190,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="https://pendantdemo.files.wordpress.com/2022/04/necklace_1.png" alt="" class="wp-image-54" width="190"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":53,"width":190,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="https://pendantdemo.files.wordpress.com/2022/04/earrings.png" alt="" class="wp-image-53" width="190"/></figure>
<!-- /wp:image -->

<!-- wp:image {"id":55,"width":190,"sizeSlug":"full","linkDestination":"none"} -->
<figure class="wp-block-image size-full is-resized"><img src="https://pendantdemo.files.wordpress.com/2022/04/ring.png" alt="" class="wp-image-55" width="190"/></figure>
<!-- /wp:image --></div>
<!-- /wp:group --></div>
<!-- /wp:column --></div>
<!-- /wp:columns --></div>
<!-- /wp:group -->
```

**Comment by pbking** [comment]
@beafialho I worked on that very problem for a while. :(

I was able to achieve the desired desktop design using `justify: space between`.  However as you have noted the smaller screen doesn't work out.

using `justify: center` makes the layout work on smaller screens but (as you have noted) doesn't align as desired on the desktop.

If both can be achieved (without custom CSS and breakpoints) I've not been able to figure out how. :(

**Comment by beafialho** [comment]
I see. I think by removing the Row block I managed to get it scaling down a little better:

https://user-images.githubusercontent.com/65220155/163787201-331c10d9-814a-4cda-968a-f5b64e77f111.mp4

The only thing that bugs me is the heading not being centered on mobile. Is that something we can adjust with CSS?

**Comment by pbking** [comment]
> The only thing that bugs me is the heading not being centered on mobile. Is that something we can adjust with CSS?

Yes.  I can apply a special class to the pattern.  The pattern will only be aligned as expected when used in Pendant though; That is the only issue, though I consider it a biggish one.

If the pattern requires Pendant be activated to look as intended then it probably shouldn't be in the pattern registry.  And if that's the case then perhaps it shouldn't be a pattern. And if it isn't available as a pattern maybe we need not make it a part of the page.

The [similar solution for the post page navigation](https://github.com/Automattic/themes/pull/5887) feels like a different beast because it's not expected that the pattern in play will be available via the pattern picker and thus the scenario only available in that template which is only available when Pendant is activated.

I'll see if I can get something together using just blocks that better fits what you're aiming for in both scenarios.

**Comment by pbking** [comment]
And I have failed again.

I can make it look good on mobile or desktop but not both.  I advocate against custom CSS for a pattern so perhaps we could try something else?

Would a design something like this work out OK @beafialho?

Desktop:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/146530/164093976-ddc30687-391e-4a68-af20-1ba9b5b98546.png">

Mobile:
<img width="300" alt="image" src="https://user-images.githubusercontent.com/146530/164094078-1802d2d9-624a-4207-b3a5-8ef6354e690e.png">

Or does the original design (with the label not centering on mobile) better suit the design?

Or maybe some solution I haven't figured out!

**Comment by beafialho** [comment]
Yes @pbking always centered seems like the best way. Thanks!
