### ISSUE TITLE
Pendant: Adjust spacing and alignment in desktop menu

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#5865]
The desktop menu should be horizontally centered and the space between items should be tighter. 

| Currently      | Intended |
| ----------- | ----------- |
|  <img width="1529" alt="Captura de ecrã 2022-04-14, às 09 56 35" src="https://user-images.githubusercontent.com/65220155/163350944-8bee5d62-ea3c-4a16-8073-0384f29a7884.png">   |    <img width="1105" alt="Captura de ecrã 2022-04-14, às 09 58 02" src="https://user-images.githubusercontent.com/65220155/163351027-724b7179-db05-4da3-8934-48a6239379b5.png">   |

Also, when I test the theme locally, I see this menu white by default instead of black. Any idea why?
<img width="1536" alt="Captura de ecrã 2022-04-14, às 10 06 21" src="https://user-images.githubusercontent.com/65220155/163352572-c4e6b121-098b-420f-9cf0-31e8053b44bf.png">

**Comment by pbking** [comment]
@beafialho I wasn't able to reproduce the color inversion you provided a screenshot of.  Is that still reproducing for you?

**Comment by beafialho** [comment]
No, not anymore. It's looking accurately now!
