### ISSUE TITLE
Pendant: Post template refinements

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#5867]
**1. Add padding to post category.** Here I added 15px padding.

https://user-images.githubusercontent.com/65220155/163361830-98558826-489d-4896-9b53-68c09e165216.mp4

**2. Adjust post titles, H1, H2 and H3's line heights to 1.2**

| 1.5      | 1.2 |
| ----------- | ----------- |
|   <img width="1246" alt="Captura de ecrã 2022-04-14, às 10 51 25" src="https://user-images.githubusercontent.com/65220155/163360966-dc6180b2-9de7-4cad-9b87-93d1ea843d06.png">  |  <img width="1170" alt="Captura de ecrã 2022-04-14, às 10 51 18" src="https://user-images.githubusercontent.com/65220155/163360994-e25602df-069d-4ad9-91bb-575413e39cab.png">  |

**3. Post date should be closer to the post title.**

| Currently      | Intended |
| ----------- | ----------- |
|    <img width="742" alt="Captura de ecrã 2022-04-14, às 11 01 20" src="https://user-images.githubusercontent.com/65220155/163362741-76feaa7f-81f5-44a0-b372-c9fa5cc621db.png">  | <img width="743" alt="Captura de ecrã 2022-04-14, às 11 01 13" src="https://user-images.githubusercontent.com/65220155/163362694-6c7ac3df-d943-420d-9407-f998d05f7ce0.png">      |

**4. H5 and H6 don't seem to be using Jost Medium.**

| Currently      | Intended |
| ----------- | ----------- |
| <img width="531" alt="Captura de ecrã 2022-04-14, às 11 13 41" src="https://user-images.githubusercontent.com/65220155/163364685-09c5b260-b640-48f0-9875-7406e0c6162d.png">  |  <img width="724" alt="Captura de ecrã 2022-04-14, às 11 14 23" src="https://user-images.githubusercontent.com/65220155/163364743-e93a8cad-bbeb-4c0c-85f2-fb0ba2f1f2d5.png"> |

**5. Posts are missing this post navigation section.**

<img width="890" alt="Captura de ecrã 2022-04-14, às 11 11 36" src="https://user-images.githubusercontent.com/65220155/163364323-70847048-45e0-437a-af54-045741e8f973.png">

**Comment by pbking** [comment]
Interestingly I'm unable to reproduce the H5/H6 weight issue noted above.  What is rendering for me is clearly darker than the screenshots you've created though.   If it remains a problem perhaps we can open a separate issue to get to the bottom of it.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/146530/163448514-44da7904-5927-4bcf-b5cf-819361909bf2.png">
<img width="354" alt="image" src="https://user-images.githubusercontent.com/146530/163448583-ec365c8c-27d0-46d9-b526-1060c2b1e248.png">

**Comment by beafialho** [comment]
> 3. Post date should be closer to the post title.

Thought I'd reopen this because the post date is currently looking a bit too tight compared to the intended.

| Current      | Intended |
| ----------- | ----------- |
|  <img width="1126" alt="Captura de ecrã 2022-04-19, às 10 21 53" src="https://user-images.githubusercontent.com/65220155/163973303-5a4aca6e-0838-4a76-8cd0-23f07bff202d.png">    |      <img width="1103" alt="Captura de ecrã 2022-04-19, às 10 22 19" src="https://user-images.githubusercontent.com/65220155/163973346-0e82c08a-a0fc-445e-9f5e-8821fceb2912.png"> |
