### ISSUE TITLE
Block themes: update templates to use Comments Query Loop

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#5880]
Now that the Comments Query Loop has mostly landed in Gutenberg, I think we should update our block themes' templates to use this block + the Post Comments Form block, instead of the deprecated Post Comments block. 

- [ ] Blockbase
- [ ] Archeo
- [ ] Skatepark
- [ ] Quadrat
- [ ] Videomaker
- [ ] Stewart
- [ ] Zoologist
- [ ] Livro
- [ ] Pendant

**Comment by MaggieCabrera** [comment]
Also https://github.com/Automattic/themes/issues/5833

Please note that the Comments form block is not going to make it to 6.0, but it's good that we start opening the PRs in any case

**Comment by jffng** [comment]
Oops, I should have checked for an existing issue first. Closing this one so we track using one issue.
