### ISSUE TITLE
Dyad 2: Footer widgets do not stack

### ISSUE THREAD

**Issue by jonnyruzek** [Automattic/themes#589]
## Steps to replicate

A user reported that they noticed on February 9 the appearance of their footer widgets changed and are no longer side-by-side; they are stacked.

## Result

The theme demo on WordPress.com (https://dyad2demo.wordpress.com/) is showing the widgets stacking, in full-width:

![screen capture on 2019-02-09 at 12-23-50](https://user-images.githubusercontent.com/39252765/52525393-5e2ffb80-2c66-11e9-8df2-c957d94f1848.gif)

## Expected

Reviewing the version of Dyad 2 on WordPress.org (https://wordpress.org/themes/dyad/), the footer widgets are in 4 columns, side-by-side: 

<img width="1361" alt="screen shot 2019-02-09 at 12 21 10 pm" src="https://user-images.githubusercontent.com/39252765/52525387-33de3e00-2c66-11e9-956c-e1546f611ad4.png">

* Follow-up ticket: #1788926-zd

**Comment by laurelfulford** [comment]
Apologies, @jonnyruzek! I caused this trying to fix another issues.

Another updated has been committed in r53348-wpcom-themes - I'll add a comment to the Zendesk ticket for follow-up.
