### ISSUE TITLE
Dorna, Hari, etc: Comment form labels overlap on mobile

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#5894]
### Quick summary

The labels in the Leave a Reply area overlap on mobile devices.
<img width="338" alt="Screen Shot 2022-04-17 at 8 14 58 PM" src="https://user-images.githubusercontent.com/3476361/163743947-7fef14ef-2106-4d12-8ef9-20e6a45c17d5.png">

### Steps to reproduce

1. Start with a site that has posts.
2. Enable Dorna.
3. Use a mobile phone to find a post, then scroll down and look at the comments area. 

### What you expected to happen

I want to be able to see the different fields of the reply box, like this does if I uncheck the offending CSS:

<img width="648" alt="Screen Shot 2022-04-17 at 8 14 26 PM" src="https://user-images.githubusercontent.com/3476361/163744146-f353af2e-0796-45ea-9c51-162ae993b03c.png">
 

### What actually happened

I get a jumble of text.
<img width="648" alt="Screen Shot 2022-04-17 at 8 14 20 PM" src="https://user-images.githubusercontent.com/3476361/163744168-ab33a00c-27d7-4a87-a479-6888d72dc74e.png">

### Context

Customer report here:
https://wordpress.com/forums/topic/overlapping-text-problem-with-leave-a-reply-on-apple-mobile-phone/

### Theme-specific issue?

Dorna, Hari, likely related themes

### Browser, operating system and other notes

I've tested on my phone (iPhone SE) as well as with Chrome's inspect element.  The user who reported this also uses an iPhone.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Workaround details

This CSS snippet would work, but as we're discouraged from handing out snippet fixes, we'll need to say there is not a workaround.

```
.wp-block-post-comments form>* {
    grid-area: unset;
}
```

**Comment by Robertght** [comment]
Thank you @supernovia ! I believe this may be somewhat related:

https://github.com/Automattic/themes/issues/5880

cc @jffng for a second look

**Comment by jamiepalatnik** [comment]
Another report: 22366560-hc

Winkel theme. I can recreate on a test site.

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/overlapping-text-at-comment-section

View when logged in as site admin:

![screenshot_20220523-220631](https://user-images.githubusercontent.com/1967448/169911989-25fc821c-95b2-4c99-8603-d2b9d0e99c21.png)

When viewed by logged-out site visitor
![Image from iOS (27) (1)](https://user-images.githubusercontent.com/1967448/169912011-2ef3e3e3-3171-460c-ab48-78c2985a831a.png)

**Comment by Jaykame** [comment]
5250435-zd 

User on this site also reported this happening on their form comment labels.

**Comment by KirkwallDay** [comment]
> 5250435-zd
> 
> User on this site also reported this happening on their form comment labels.

In this instance, the bug is due to the Post Comments block in FSE, and seems to only occur on AMP pages, which means the CSS fix above wouldn't work here. I did advise them to try replacing it with the more updated Comments block as the Post Comments block is depreciated. I'll reply back here when they do this if it helps or not.

**Comment by sajmes** [comment]
5289121-zd-woothemes

Replacing Post Comments block with Comments block appears to have resolved it when I tested.

**Comment by crazytonyli** [comment]
This issue is also reported in 5367819-zd-woothemes. The user is using Russell theme though.

**Comment by pbking** [comment]
Closing this as fixed.  Blockbase 3 [ships with the Comments Block ](https://github.com/Automattic/themes/pull/6080)which fixes this problem for Blockbase and all of the child themes.
