### ISSUE TITLE
Pendant: with many popular topics, Latest Interviews section has huge blank space

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#5898]
## Steps to replicate

when there are topics > 10, observe that page creates blank space.

## Result

![pendant-fullpage](https://user-images.githubusercontent.com/1935113/164177286-80998cbc-b487-498d-864f-ef5623a2e60e.png)

## Expected

Topics should be limited.

**Comment by beafialho** [comment]
Good catch @madhusudhand! What do you suggest to limit the categories? Something like a "See All" button?

**Comment by madhusudhand** [comment]
Yes. We can limit the categories to a maximum of 10-12 (that fits in the given height) and add "See All" button.

**Comment by pbking** [comment]
I don't believe we should limit what categories are included.  It would be confusing to find that some of your categories are missing.  Adding "see all" is outside of the scope of what we can offer as a pattern.

This feels like a situation where the user could make necessary changes within the bounds of the theme to support a situation like this.  It may be that the content alongside this block is enough to fill the gap of a lot of space like that.  More likely, though, is that there are much fewer categories than what is shown above.

I'm going to close this.  However we can re-open if discussion needs to continue.
