### ISSUE TITLE
Multiple Themes: update changelogs

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#5902]
We've recently [merged a change](https://github.com/Automattic/themes/pull/5889) that will help keep our theme changelogs up to date going forwards, however, a lot of themes are still missing historical changes from their changelogs.

Should we update all/most/some of our theme changelogs? 

My thinking at the moment is that at the very least we should probably update the changelogs for our most recent themes (block themes and Blockbase themes?) But I realise this is time-consuming! Maybe we should start with adding information for major changes/bug fixes to reduce the amount of work (this might already be covered in a lot of themes.)

Here's a list we can use for tracking:

- [ ] Archeo
- [ ] Blockbase
- [ ] Geologist & variations
- [ ] Livro
- [ ] Quadrat & variations
- [ ] Remote
- [ ] Skatepark
- [ ] Stewart
- [ ] Videomaker & variation
- [ ] Zoologist

**Comment by pbking** [comment]
Hrm.  This got me thinking and tinkering and I might have a small change to the work you did in theme-utils.mjs that would allow us to create these missing changelogs.  Or at least get them mostly created and make the process a bit faster...

**Comment by mikachan** [comment]
That sounds amazing!
