### ISSUE TITLE
Photos: Custom Header option no longer available

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#591]
## Steps to replicate

The Photos theme doesn't appear to have an option to add or edit a Custom Header in the Customizer. The [theme guide](https://wordpress.com/theme/photos) promotes this option with the following:

>The Custom Header Image in Photos sits below the header and above the content. To set a header image, navigate to Customize → Header Image and choose one of our default header images, or upload your own!

Despite this, the option isn't available in the Customizer. 

## Result

When opening the Customizer, there's no option to add or edit a Custom Header image. These are [the available options](http://cld.wthms.co/vaVqia):

![](http://cld.wthms.co/vaVqia+)

I noticed that the Customizer list jumps when I switch between pages. It looks like it starts to load the option, and then removes it, [like this](http://cld.wthms.co/Ymfb1T):

![](http://cld.wthms.co/Ymfb1T+)

I **was** able to reproduce this issue on a test site.

## Expected

I expected to see a Customizer option for the Custom Header.

* User report: 1792535-zen

**Comment by laurelfulford** [comment]
I'm betting I caused an issue here, with my fix for #319 -- looking into it!

**Comment by laurelfulford** [comment]
This should now be fixed on WP.com in r53359-wpcom-themes.

I've added a comment to the ZD ticket for follow up!
