### ISSUE TITLE
Curator: Styles: Buttons

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#5919]
Add default button styles for the theme and ensure they are applied correctly:

- [x] Button block
- [x] Search (in this case, I don't think we want the default button styles to apply to the search button)

**Comment by madhusudhand** [comment]
@beafialho 

![image](https://user-images.githubusercontent.com/1935113/166188609-91009792-a56c-4399-9c19-3eeac63278d1.png)

Buttons doesn't have a background in figma. It isn't going well for blocks such as `search`
Can you add more details.

![image](https://user-images.githubusercontent.com/1935113/166189028-2df6eb1c-a07f-4833-b0f3-b054fa5a8962.png)

**Comment by beafialho** [comment]
We should use a solid background for Search buttons:

<img width="1478" alt="Captura de ecrã 2022-05-02, às 09 58 25" src="https://user-images.githubusercontent.com/65220155/166209991-966258c4-961d-42af-8309-edf23f07f9aa.png">
