### ISSUE TITLE
Vivre: Pre-launch: Showcase Entry

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#5927]

**Comment by jffng** [comment]
@beafialho would you be able to provide a devices mockup for Vivre for its showcase entry?

**Comment by beafialho** [comment]
@jffng sorry for the delay, here's the devices screenshot:

![Vivre](https://user-images.githubusercontent.com/65220155/179803365-cd155863-3ee8-4d1b-af3d-553b6c8ea5db.jpg)

**Comment by jffng** [comment]
Thank you @beafialho ! This is done.
