### ISSUE TITLE
Curator: Pre-launch: Screenshot, readme.txt & description

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#5930]
@beafialho would you be able to provide the screenshot and description?

**Comment by beafialho** [comment]
Here's the description:

_Curator is a bold, opinionated blogging theme, heavily inspired by fashion and lifestyle magazines and websites.
With large heavy sans-serif paired with a light elegant serif font, it sets the tone to a refined reading experience._

And the screenshot:

![Curator Screenshot](https://user-images.githubusercontent.com/65220155/175971783-2b677377-fc1d-4c00-a1ce-46562e1eab40.png)

**Comment by jffng** [comment]
Do you think it's okay to still leave Cult in the screenshot even though we renamed the theme?

**Comment by beafialho** [comment]
Oh, you're totally right, I missed that.

![Curator Screenshot](https://user-images.githubusercontent.com/65220155/176135529-0f0e9608-145b-489b-8cf3-067c098c4d92.png)
