### ISSUE TITLE
Curator: Templates: Single

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#5931]
**With featured image**

![Single Post](https://user-images.githubusercontent.com/5375500/166974415-b5dd8216-90b2-4a35-bee3-0a2fe1ade1b7.png)

**Without a featured image**

![image](https://user-images.githubusercontent.com/1935113/167620717-855a3dac-0bdd-4e43-90f2-1f00dfba5ca0.png)

**Comment by PeterNdomano** [comment]
Is there a design concept for this template file?

**Comment by jffng** [comment]
@PeterNdomano just updated the issue with a screenshot for the design here 🙂

**Comment by PeterNdomano** [comment]
> @PeterNdomano just updated the issue with a screenshot for the design here 🙂

@jffng Would you please review my PR on this here #5987
Thanks.
