### ISSUE TITLE
Baskerville 2: Image Block Center Alignment Breaks Caption Alignment

### ISSUE THREAD

**Issue by scosgro** [Automattic/themes#595]
## Steps to replicate

1. Activate Baskerville 2
1.5. Make sure Gutenberg is active in Calypso.
2. Create a Blog Post
3. Add some content to that post.
4. Add an Image Block
5. Add a caption to that image. 
6. Click on the image, and center align it. 
7. Add some content underneath the image/caption
8. Publish.

## Result

With a center alignment, the image caption aligns to the left in a small vertical column, not placed under the image. 

## Expected

The image and the caption to align center, and the image caption to appear underneath the image. 

## Gif showing workflow/results:

https://cloudup.com/cTqorEVntcM

* User report:  #1795750-zd
* Follow-up ticket:  #1795750-zd

**Comment by laurelfulford** [comment]
Thanks for this report, @scosgro! 

It looks like there's already an issue for this, so I'm going to move your report to #403 and close this one.
