### ISSUE TITLE
Blockbase: allow child theme headers to override parent headers

### ISSUE THREAD

**Issue by colinduwe** [Automattic/themes#5956]
## Steps to replicate

Copy header-default.html from Blockbase to a child theme and edit copied header file.

## Result

The theme continued to display the version of header-default.html from Blockbase

## Expected

The child theme version of the file should be displayed.

Here's a fix: https://github.com/Automattic/themes/pull/5955

**Comment by Thelmachido** [comment]
Closing this issue in favor of [#5955](https://github.com/Automattic/themes/pull/5955) since the issue is being discussed there at the moment.
