### ISSUE TITLE
Scrawl: Galleries in posts created in Gutenberg display incorrectly

### ISSUE THREAD

**Issue by thesacredpath** [Automattic/themes#596]
## Steps to replicate

In Scrawl, when galleries are put into posts and pages in Calypso or the Classic editor, the galleries extend out past the left and right margins of the theme so that the galleries are larger. When a gallery block and gallery are used in Gutenberg, the gallery images are pulled to the left, but not to the right, so the gallery aligns with the right edge of the content area, and outside of the left content area margin.

CSS that is pulling Gutenberg galleries outside left margin:

`.tiled-gallery-wrapper, .jetpack-video-wrapper, img.size-big, .wp-caption.size-big {
margin-left: -158px;
}`

Screenshot from user's NYC Part 1.. post: https://cloudup.com/cbNjwG88VF

Example from Scrawl classic/calypso post: https://scrawldemo.wordpress.com/ (scroll down to Bold Color)

1. In Scrawl and Gutenberg editor, add gallery block and some images with captions (3?).
2. Add some text above or below that covers out to margins on content are for reference.
3. Preview post, or publish and then view on single post or blog page.
4. Gallery shifted outside left content margin, but not to outside of right content margin.

## Expected

Expect that galleries created with Gutenberg would show the same as those created in Calypso or Classic editor.

* User report: #10380274-hc 
* Follow-up ticket: #1799004-zen

**Comment by alaczek** [comment]
I removed the full URLs. There's a browser script that you can install, that turns #10380274-hc into actual link, so there's no need to post full URLs on GH :)

**Comment by alaczek** [comment]
Done in r53382-wpcom-themes. The images and galleries added with the new editor should now behave the same way as those added with the classic editor:
* galleries will be outdented
* images wider then 1000px will be outdented
