### ISSUE TITLE
Pendant header menu pattern expected behaviour

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#5969]
I should have foreseen this, and it may not be a huge issue given that you can change everything in the editor. But when a user adds more social links to the header, the Site Title will move to the center of the row block, which is the natural behaviour. 

However, if the intention is for the Site Title to continue in the middle, that doesn't happen. I think that as a user I'd expect that if I added more items the Site Title wouldn't move.

<img width="1534" alt="Captura de ecrã 2022-05-03, às 10 37 08" src="https://user-images.githubusercontent.com/65220155/166433618-2b11c918-3b3b-4b74-bf68-6f6ac9560951.png">

Do you think this is a problem and if so what would be a good solution?

**Comment by madhusudhand** [comment]
I did a quick css change, updating parent styles to `grid` with columns `repeat(3, 1fr)`, set third child justification to `flex-end`
It works well. I guess we need to use a custom class for this.
Any other thoughts?

**Comment by pbking** [comment]
I definitely agree that it's a problem.

My 'druthers would be to accomplish this without custom CSS if possible.  I don't believe that this header will find its way into the pattern directory, but using custom CSS would definitely eliminate the possibility.

I do like the grid CSS proposed though, it's a nice way to do that with CSS I think if CSS must be used.

We may also achieve this layout with columns instead.  Could we give that option a try?

**Comment by beafialho** [comment]
> I don't believe that this header will find its way into the pattern directory

Why not?

> Could we give that option a try?

We could give that a try.

**Comment by madhusudhand** [comment]
Removed the custom class and updated to column layout. Following is the final result

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/1935113/171349179-3df147a1-2bb2-46e9-8fd6-93264518cbbb.png">

**Comment by beafialho** [comment]
Thanks @madhusudhand! What does it look like if you add more social links to the right? That was what was causing the misalignment of the Site title in the first place.

**Comment by madhusudhand** [comment]
Yes. It works with more social icons too.

Single icon
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/1935113/171394454-2fbe33e8-98d7-4373-9467-169ccd941f04.png">
Multiple icons
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/1935113/171395985-df637053-e016-4c93-9ef5-0789f41e0e53.png">

When there are more icons, they wrap in mobile view 

<img width="486" alt="image" src="https://user-images.githubusercontent.com/1935113/171396299-2b3418a2-36b5-4630-84c4-a4df10c5e33f.png">

**Comment by beafialho** [comment]
Awesome, thanks everyone!

**Comment by pbking** [comment]
>> I don't believe that this header will find its way into the pattern directory

> Why not?

I thought that was a decision we made earlier in development and I don't remember why.  Something when we were defining which patterns would be shown, etc. It might have been because the original design required a fair bit of custom CSS. Maybe?  I don't actually recall. :)

**Comment by beafialho** [comment]
Ah, you're right. I also vaguely remember now we discussed which patterns would go and which wouldn't.
