### ISSUE TITLE
Incorrect theme URIs create invalid links in Calypso Activity Log

### ISSUE THREAD

**Issue by mattgawarecki** [Automattic/themes#5971]
## Steps to replicate

Several public themes have a theme URI of the form `https://github.com/Automattic/themes/tree/master/<name>`, which is no longer valid since the default branch name was changed to `trunk`. The correct URI would be `https://github.com/Automattic/themes/tree/trunk/<name>`.

Affected themes are as follows (repo maintainers, message me directly if you'd like to learn how I found them):

* `exford`
* `mayland`
* `mayland-blocks`
* `maywood`
* `remote`
* `rivington`
* `rockfield`
* `stow`
* `varia`

## Result

In the Activity Log on WordPress.com and Jetpack Cloud, any link to an affected theme does not take me to the correct theme home page, but instead to the main Themes repository root (`https://github.com/Automattic/themes/tree/trunk`) via a GitHub redirect.

## Expected

When a link to a theme inside an Activity is clicked, the browser directs me to that theme's home page.

**Comment by emiliogarza** [comment]
In looking for Good First Issues, the URL seems to properly redirect now to the default branch which is trunk. https://github.com/Automattic/themes/tree/master/maywood for example, redirects to https://github.com/Automattic/themes/tree/trunk/maywood with a message that says, "Branch not found, redirected to default branch."

**Comment by pbking** [comment]
I believe that the proper URI for themes to link to is `https://wordpress.com/theme/SLUG` rather than anything on github (master, trunk or otherwise).  All of the themes noted here have been addressed and I believe this item can be closed now.
