### ISSUE TITLE
Blockbase: Jumping Close Navigation Button

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#5975]
In Blockbase, [a part of the ponyfill CSS](https://github.com/Automattic/themes/blob/4ba24db18ee43ec5554fdd4cfb50ce3b380205b2/blockbase/assets/ponyfill.css#L490-L493) changes the position of the close navigation button. That seems to be making the button jump. 

![Screen Recording 5-5-2022 at 10 58 PM](https://user-images.githubusercontent.com/908665/167033122-b2cb03ef-d3fa-473e-9f3f-6e68a2723fe2.gif)

If I disable the part of CSS, it seems to resolve the issue.

![Screen Recording 5-5-2022 at 10 59 PM](https://user-images.githubusercontent.com/908665/167033242-cd52345d-a0b5-4e77-9c2e-73738c8b887a.gif)

Why do we need this? Is it a leftover fix that we needed before? Can we now get rid of it?

**Comment by mikachan** [comment]
I'm not sure why we added this originally, my guess is that it could've been to fix the position of the close button when the admin-bar is visible. I've opened up a Gutenberg PR to fix this: https://github.com/WordPress/gutenberg/pull/41664

Removing these styles in Blockbase seems to work fine. Opened up a PR for this too: https://github.com/Automattic/themes/pull/6082
