### ISSUE TITLE
Dara: Exclude featured images from lazy loading

### ISSUE THREAD

**Issue by cintacks** [Automattic/themes#5989]
### What

In the Dara Theme, the slideshow powered by featured images should not be lazy loaded by Jetpack. 

Example:

![image](https://user-images.githubusercontent.com/6737345/167682276-67a9cde4-21fd-4cd5-a8b7-15819dabd2fb.png)

### Why

Lazy loading the featured image slideshow creates a dark image flash/blank image (on slower connections) when first loading the site. This was easily replicable on my test site by:

1. Add a post with a large featured image
2. Add `featured` tag to post
3. Add `featured` tag to `Featured Content` in Customizer: 
![image](https://user-images.githubusercontent.com/6737345/167682340-f0c10062-3b55-450e-88d8-96d7eb11de33.png)

4. View homepage

### How

Test example:

https://user-images.githubusercontent.com/6737345/167682481-eaf52b1c-45c7-4796-b9e5-43d4566ea5a9.mp4

Customer example: https://smartdogpettraining.com/

**Comment by zachspears** [comment]
Tested and was able to reproduce the issue. Set Priority to Low as it has low user impact.
