### ISSUE TITLE
Dara: Featured Image doesn't load properly

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#6]
Originally reported by @gpmw in 4805-wpcom-themes:

## Steps to replicate

1. Go here on a mobile device: ​https://tmachurch.org

![](https://cldup.com/MoO1eSTX0_-3000x3000.png)

2. Turn the device to view the site in landscape mode. The featured image is small and off to the left. It is supposed to be full width.

![](https://cldup.com/dziugzZpyQ-3000x3000.png)
![](https://cldup.com/1y0mlBYXk9.PNG)

3. Refresh in landscape mode and the Featured image now shows full width. 

![](https://cldup.com/dziugzZpyQ-3000x3000.png)
![](https://cldup.com/1y0mlBYXk9.PNG)

## Testing

User was asked to deactivate a few of their plugins and the results were the same. The issue is now present on the demos site on mobile: ​https://darademo.wordpress.com/ 

The user has added a JavaScript workaround; they've disabled this script on a test page so the issue is still visible (linked below).

@sixhours had this feedback on the original ticket:

> It looks like Photon is only requesting the smaller image size when the page first loads. The image URL:
> 
> ​https://i2.wp.com/tmachurch.org/wp-content/uploads/2017/08/welcome6-001.jpg?zoom=3&resize=397%2C146&ssl=1
> 
> Note the dimensions in the URL, which doesn't change until the page is refreshed:&resize=397%2C146 means 397x146 is the size requested for smaller screens initially. 

* User report: 607654-hc
* Follow-up ticket: 658039-zd
* User followed up here: https://en.forums.wordpress.com/topic/dara-theme-featured-image-not-responsive?replies=1
* User's site: ​https://tmachurch.org/test/

**Comment by sixhours** [comment]
We're wontfixing this; it's not specific to the theme. The customer created a custom solution that refreshes the page after a window resize, which isn't something we'd implement in the theme for everyone. 

I'm able to reproduce this on the customer's site, but not on our WordPress.com demos. It's possible a fix was implemented and hasn't made it to Jetpack, or they need to update Jetpack.

I'll follow up in the forum thread.

**Comment by sixhours** [comment]
Oh, this may be related to https://github.com/Automattic/jetpack/issues/7291

Where the image is taking on the size of the containing element, not the theme's specified size or $content_width.
