### ISSUE TITLE
Canard: wrong height for featured content thumbnails

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/themes#6005]
## Steps to replicate

1 - Add Canard to your site
2 - Create a handful of blog posts, make sure they have a featured image and the `featured` tag
3 - Add `featured` tag to Customizer > Featured Content

## Result

4 - Visit site and noticed thick black line at the bottom of the thumbnails, due to a height issue:

<img width="1289" alt="Screenshot 2022-05-13 at 15 31 11" src="https://user-images.githubusercontent.com/16645645/168294585-a57a47fd-ef43-4ffa-85e4-93348bda1d1b.png">

## Expected

I expected a cover-like result for the thumbnails.

## Workaround

A quick fix can be achieved with CSS such as:

```
.featured-content .post-thumbnail {
	 height: 100%;
}
```

* User report: 35444065-hc

**Comment by MaggieCabrera** [comment]
yeah, this looks like a regression after https://github.com/Automattic/themes/pull/5986, I think we need to be more specific with the class we are targeting for the posts block fix

**Comment by cecilearkay** [comment]
Thanks @MaggieCabrera! I set the priority to High because it's affecting all sites, including the demo which the screenshot is from.
