### ISSUE TITLE
Baskerville 2: last image bottom border in a gallery is misaligned

### ISSUE THREAD

**Issue by catkit** [Automattic/themes#601]
## Steps to replicate

1. Create a post
2. Add an image gallery block
3. Set any number of columns

## Result

![misaligned](https://user-images.githubusercontent.com/3521683/52816455-6a61f180-3088-11e9-8e5c-f75a6320c6b8.jpeg)

* User report: #8718759-hc
* Follow-up ticket: #1803553-zen

**Comment by catkit** [comment]
There's a CSS code to fix:
```
.post-content ul>li.blocks-gallery-item:last-child {
margin-bottom: 16px;
}
```

**Comment by alaczek** [comment]
Fixed in r53384-wpcom-themes.
