### ISSUE TITLE
Curator: Add pagination in Archive and Search templates

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6059]
![image](https://user-images.githubusercontent.com/1935113/171864202-69b35e88-ff49-4513-a2be-b0152578470b.png)

**Comment by beafialho** [comment]
I think we can apply the same alignment as in the Index template with the page numbers always on the left:

<img width="994" alt="Captura de ecrã 2022-06-27, às 10 23 07" src="https://user-images.githubusercontent.com/65220155/175906710-64667e17-6e0f-4e73-b2ea-f85ac964f9f5.png">
