### ISSUE TITLE
Blockbase child themes: Links missing the underlining in live view on List/ Table blocks

### ISSUE THREAD

**Issue by csabarakasz** [Automattic/themes#6085]
### Quick summary

The underlining of links is showing in Editor, but not showing (everywhere) on the Live site:
Theme: Zoologist and Geologist for sure

In the Editor:
<img width="759" alt="CleanShot 2022-06-02 at 11 30 26@2x" src="https://user-images.githubusercontent.com/84539773/171602178-4dfb0b24-577d-4569-b26c-8cad98b4fa41.png">

Live view:
![CleanShot 2022-06-02 at 11 30 51@2x](https://user-images.githubusercontent.com/84539773/171602256-d072eaf1-7ed4-4534-a04c-f23254ef8a00.png)

Video

https://user-images.githubusercontent.com/84539773/171605274-e148d2cf-fddd-4304-b753-0bcb80b45393.mp4

### Steps to reproduce

1. Set theme to Zoologist
2. Create a home page with a few different texts, some with links, some without in different blocks (Paragraph, List, Table)
3. In Editor, links show underlining
4. In Live view, links don't show underlining when applied on a List or in a Table block
5. Switch to Geologist -> same
6. Link underlining only shows when hovering over

### What you expected to happen

Links would show up on all blocks.

### What actually happened

They are not!

### Context

user report: 5261518-zd-woothemes

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Yes, so far tested: Zoologist and Geologist

### Browser, operating system and other notes

Firefox

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

We can change the Link text color to be different. That applies to all links.

**Comment by Robertght** [comment]
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - No

📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- To clarify, the underline doesn't remain consistent between the editor and the live preview of that page/post. @csabarakasz  can you confirm this is the issue we're looking at?  Regarding the list or table block, I can see the behaviors are consistent with no underline in both, the editor and the frontend.
- Also, it appears to happen with other child themes, like Quadrat, but not with the parent, Blockbase or all child themes, like Arbutus.

📌 ACTIONS
- Transferred to XYZ external repo: themes

**Comment by csabarakasz** [comment]
>To clarify, the underline doesn't remain consistent between the editor and the live preview of that page/post. csabarakasz can you confirm this is the issue we're looking at? Regarding the list or table block, I can see the behaviors are consistent with no underline in both, the editor and the frontend.

@Robertght When links are added to the text within Lists or Tables, the underlining does not show up on the Live site, unless hovering over the text exactly. This makes links unidentifiable in Lists or in Tables. I hope that helps!
