### ISSUE TITLE
Vivre: add support for Button elements

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#6142]
As demonstrated in #6139, can we use the button element API on Curator to get rid of some CSS?

Specifically the search + file block button styles.

**Comment by beafialho** [comment]
I'm not sure if I should open a new issue or if this is related, but the Search and File buttons aren't looking as they should:

- The black outline should be removed
- The hover state shouldn't have an underline in the text

https://user-images.githubusercontent.com/65220155/177313639-d5523e74-084f-4945-b2c9-c1c97e98b05d.mov

https://user-images.githubusercontent.com/65220155/177313629-89c49720-3483-4fbc-9357-6ef4b1a28c8a.mov
