### ISSUE TITLE
Payton: Global Styles color overriding border color selected in Table block settings

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/themes#6158]
### Quick summary

It appears that Global Styles color is overriding the color selected for the border color in Table block settings, Payton theme. This does not seem to be the expected behavior. According to [support docs](https://wordpress.com/support/using-styles/#blocks), "The changes you make to blocks using Styles will affect every block of that type that you have added to your site, unless you have customized a block individually."

I think this may affect other FSE themes but the user report is for Payton theme and I was able to recreate on Payton theme.

### Steps to reproduce

1. Activate Payton theme on a site.
2. Add a Table block.
3. Choose a custom color for the border in the block settings.

### What you expected to happen

The border color on the live site should match the border color in the editor. 

### What actually happened

The selected custom color appears in the editor:

<img width="1205" alt="Border color in editor" src="https://user-images.githubusercontent.com/30788962/176019382-3cb523a5-9958-4f46-b295-3e916bae1194.png">

But not on the live site:

<img width="1047" alt="Border color on live site" src="https://user-images.githubusercontent.com/30788962/176019390-46a03e01-2199-4613-882a-f93ca5c35d57.png">

### Context

User report: 5312780-zd-woothemes

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Payton, possibly other FSE themes

### Browser, operating system and other notes

Tested on Chrome, simple site.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

It's possible to edit theme colors in Global Styles to match the desired colors, but this does not allow users to customize blocks with different colors than the theme colors.

**Comment by renata-franco** [comment]
📌 SCRUBBING

- Tested on Simple ✅ 
- Replicable on Core - No

------

📌 FINDINGS/SCREENSHOTS/VIDEO

I was not able to replicate it on a Simple site with Payton theme. For me, it was the whole way around. 

I see the colors I selected in the Global Styles in the Block Editor when creating the table. 

I can change the colors of the border but these are not displayed in the editor at all. 

However, they are applied in the table when previewing or when the post/page is published. 

See the video of what happened on my end: 


https://user-images.githubusercontent.com/81378719/177964537-44baf044-4ea7-491f-894b-b4fb8bb7b4ac.mp4



------

📌 ACTIONS
- Await author feedback


-------

📌 Message to Author

- Could you please record a video of the steps you take to create this result? I was not able to replicate that on my end. And a video would give us more information on all the steps.

**Comment by jamiepalatnik** [comment]
Sure, here is a screen recording:

![Table block](https://user-images.githubusercontent.com/30788962/178074364-03f5aa2f-067e-4d8c-af9a-38c87c2b2e60.gif)

**Comment by Robertght** [comment]
I cannot replicate this anymore and I've tried this on Simple and AT sites, with the default and a custom palette.

I believe this might've been fixed in the recent updates so I'm going to close it for now, but please reopen if needed.
