### ISSUE TITLE
Stewart: Blog post block does not show most recent post when used on a template

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#6161]
This was reported to us by a user in the wordpress.com forums, and I was able to replicate it on a test site.

Essentially, if you edit the Index template to remove the Query Loop block and replace it with the Blog Posts block (some site owners prefer the appearance of this block) it is somehow set to offset posts by 1, and never shows the most recent post.

Screenshot here shows Index template with Query Loop block (on the left) and Blog Posts block (on the right) where you can see that the version on the right skips the most recent post _Winter in Honolulu_ and shows the second post _Photowalk Friday_ instead.

![Stewart_blog-posts-block](https://user-images.githubusercontent.com/1967448/177436260-30d7fa01-1fd8-4fc3-83f3-0d1e244f94f3.png)

## Steps to replicate

1. Edit Index Template on Stewart theme to remove Query Loop and replace with Blog Posts block
2. Save changes and view site

## Result

Most recent blog post is not shown and instead feed is offset by 1

## Expected

Most recent blog post to be shown, as it is when the Query loop block is used.

* User report: https://wordpress.com/forums/topic/issue-with-last-article-in-homepage

**Comment by syds87** [comment]
The same issue with Stewart theme was reported here: https://wordpress.com/it/forums/topic/problema-ultimo-articolo-in-home/

**Comment by cuemarie** [comment]
I was able to replicate this in other themes beyond Stewart. Closing in favor of https://github.com/Automattic/wp-calypso/issues/69306
