### ISSUE TITLE
Remove any inner blocks from the `navigation` block

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#6163]
We should remove the `page-list` block (and any other inner blocks) as an inner block of the `navigation` block, prior to this GB PR being merged: https://github.com/WordPress/gutenberg/pull/42182.

> This change means that Themes should not be including inner blocks in their Navigation blocks in their templates/parts. The only exception to this would be if they wanted to opt out of some of the current / future menu picking optimisations and automations provided by the block (e.g. carrying across menus on Theme switch).

This only applies to block themes that have inner blocks inside the navigation block. These are the ones I can find, but it's worth double-checking:

- [ ] Archeo
- [ ] Livro
- [ ] Remote
- [ ] Skatepark
- [ ] Stewart

**Comment by pbking** [comment]
Wouldn't doing this mean that any site that has these themes activated, but hasn't defined a custom menu (thus is showing the pages) means that their navigation would be wiped with this change?

Definitely agree no future themes should do this, but are we sure it's the right call to remove these for existing themes?

It's a tough tradeoff 'cause if we don't then activating these themes wouldn't have the best user experience.

**Comment by getdave** [comment]
Great point.

The front of the site will still render the pages as a fallback. With this change only the _editor_ won't show anything.

However, in the (near) future we're proposing the _Editor_ also automatically shows a list of pages as a fallback. So ultimately it will work out.

Do you think we should try and ship both those things together to avoid the problem you highlight?

**Comment by pbking** [comment]
> Do you think we should try and ship both those things together to avoid the problem you highlight?

No, actually I hadn't realized that the view would continue to render pages as a fallback so that's good enough for me. 

Thank you for clarifying!

**Comment by getdave** [comment]
And just to be clear, currently only the _front_ of the site will continue to render pages as a fallback. We're yet to add that for the editor but it's a goal.
