### ISSUE TITLE
Comunicate Gutenberg Version Requirements

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6171]
## What problem does this address?

Some of the newer themes leverage features of Gutenberg that are not yet available in WordPress core.  This isn't communicated in the WordPress.org directory and the theme might seem broken.

## What is your proposed solution?

Those themes should be identified and that dependency communicated, likely in the readme.txt file.  While it's expected that every thing should WORK without the plugin it's reasonable that not every feature implemented will work as expected without the plugin activated.

A good example of this is the "elements" api changes that allow us to define styles for state selectors.  This is a particular boon for buttons and links and allows a lot less CSS to be used.  However the result is that unless Gutenberg is activated those styles won't be used.  

This situation should be communicated to anyone using the theme in the WordPress.org space.

Previously we tinkered with the idea of programmatically testing for the plugin, or testing for features and communicating that once the theme is activated (in wp-admin).  This was both heavy handed and didn't well communicate the situation.

Suggestion for inclusion in the theme `readme.txt` file:

```
This theme was developed using the Gutenberg plugin v13.0.0, some elements may not work or appear as expected without that version or higher installed
```

This could be removed once the latest version of WordPress contains the features.

**Comment by jffng** [comment]
Thanks for the background and context, useful to remind me why we removed the requires Gutenberg programmatic checks. 

I think adding a statement to the readme makes sense, though I'm not sure about adding it right in the description. 

What do you think about placing it here: https://github.com/Automattic/themes/pull/6164/files#diff-0b916d65cce624bd0913dfdd33184e0c7d447f9ae8cae0a6cb9695680e26e7f5R14-R17

**Comment by pbking** [comment]
Yea, I can get behind that.  I agree that putting it right in the description is probably more 'in your face' than necessary and would spread that bit of text further than is helpful.  I think that makes the most sense.

**Comment by pbking** [comment]
I'm mostly thinking about the elements API and the version requirements around that, but are there other features that we've leaned on Gutenberg for in recent releases that we should also tag in themes?

**Comment by jffng** [comment]
I feel like they are often one-off design tool additions we need to make a specific block look correct without adding CSS, for example:  

https://github.com/WordPress/gutenberg/pull/41378

**Comment by pbking** [comment]
Closing this as I no longer believe we need a standard way to communicate this and "latest" should be assumed enough.
