### ISSUE TITLE
Rainfall: Typography issues

### ISSUE THREAD

**Issue by adamziel** [Automattic/themes#6174]
## Description

These are the typography settings @scruffian and I [created for Rainfall](https://github.com/Automattic/themes/commit/d844263f225b67eeeee6e621576c74aaa369c49d):

<img width="895" alt="CleanShot 2022-07-10 at 13 35 05@2x" src="https://user-images.githubusercontent.com/205419/178143162-a83bfe27-c77e-4c93-b27e-db672df6ff32.png">

Here's the original design for reference:

<img width="807" alt="CleanShot 2022-07-10 at 13 35 44@2x" src="https://user-images.githubusercontent.com/205419/178143184-0aff06c0-b8b0-4fc5-994b-033acd0eec4b.png">

## Problems

1. Need to revisit the font selection: H3 and H5 use Helvetica Neue Condensed which isn't an open font
2. The font sizes we picked were loosely inspired by figma, we tweaked them arbitrarily to look good. Let's review that.
3. Most paragraphs in Figma have a line-height of 1.6 but one of them has a line-height of 1.8. We could probably ignore it for now, but having different  line-heights pre-set by a theme is a valid use case that Gutenberg doesn't support right now. [We filed a separate issue](https://github.com/WordPress/gutenberg/issues/42291).

@beafialho

**Comment by beafialho** [comment]
Thanks for working on this!

> Need to revisit the font selection: H3 and H5 use Helvetica Neue Condensed which isn't an open font

I wish I'd seen it wasn't open source earlier, that font really made a difference in the theme. But we can keep the **Helvetica Neue Bold** for these. With this change, the buttons and links should also be revisited, I left the correct ones on Figma in the "Styles" page:

<img width="714" alt="Captura de ecrã 2022-07-11, às 11 14 55" src="https://user-images.githubusercontent.com/65220155/178242522-b0736799-9f25-4cfe-a59b-711f2024eedd.png">

> The font sizes we picked were loosely inspired by figma, we tweaked them arbitrarily to look good. Let's review that.

Intended font sizes for the new font [here](https://www.figma.com/file/oz0a2czNn0UNt9onrh8T5a/Rainfall?node-id=107%3A878).

> Most paragraphs in Figma have a line-height of 1.6 but one of them has a line-height of 1.8.

Could you point me to which one? That could have been unintentional.

**Comment by scruffian** [comment]
> Could you point me to which one? That could have been unintentional.

It's the on Paragraph Medium one.

**Comment by scruffian** [comment]
Thanks for the feedback. I think we made these changes.  If you spot more issues feel free to raise them :)

**Comment by beafialho** [comment]
> It's the on Paragraph Medium one.

Oh ok, that was intentional. These 3 paragraphs should have the same line height.

<img width="617" alt="Captura de ecrã 2022-07-12, às 10 11 25" src="https://user-images.githubusercontent.com/65220155/178455001-fe933540-1061-478d-8001-fafe33f82015.png">
