### ISSUE TITLE
Rainfall: Comments template

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#6181]
@beafialho we added a comments template to rainfall, which looks like this:
![localhost_4759__p=373 (1)](https://user-images.githubusercontent.com/275961/178295441-935243b6-384f-48a2-9266-44d5fa758379.png)

How can we improve it?

**Comment by beafialho** [comment]
This looks pretty good! I actually made very small adjustments and left them on [Figma](https://www.figma.com/file/oz0a2czNn0UNt9onrh8T5a/Rainfall?node-id=815%3A292):

- Comment author and date not underlined by default
- "Reply" button in All Caps
- The comment fields not filled, with a stroke

<img width="715" alt="Captura de ecrã 2022-07-11, às 16 22 55" src="https://user-images.githubusercontent.com/65220155/178299811-d217f700-e454-4f92-b58a-9210547ad579.png">

The footer's background can be black only for the templates that have the comment section, right?

**Comment by scruffian** [comment]
> The footer's background can be black only for the templates that have the comment section, right?

Yeah that's what we've done.

**Comment by mikachan** [comment]
Thanks @beafialho, these changes are done now.
