### ISSUE TITLE
Vivre: cite image sources

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#6201]
In the readme, we need to cite the sources for the images bundled in the theme:

https://github.com/Automattic/themes/tree/trunk/vivre/assets/images

@beafialho would you be able to write those up or point me to where they are from?

**Comment by beafialho** [comment]
Sure, here are the sources for those images.

Smoothie: https://www.foodiesfeed.com/free-food-photo/peanut-butter-and-banana-smoothie/
Sundae: https://www.foodiesfeed.com/free-food-photo/coconut-and-dark-chocolate-treat/
Vermicelli: https://www.foodiesfeed.com/free-food-photo/plain-rice-noodles-in-a-black-bowl/
Wine tasting: https://stocksnap.io/photo/pouring-wine-6JMD0WXXTG
