### ISSUE TITLE
club: Templates: Header template part

### ISSUE THREAD

**Issue by matiasbenedetto** [Automattic/themes#6226]
![image](https://user-images.githubusercontent.com/1310626/180779786-cd5da156-9450-4fe4-afc6-0b99650a7dcd.png)

**Comment by madhusudhand** [comment]
Looking at the following designs, the border bottom seem to be not part of the header template. It is only there when there is posts list.

<img width="404" alt="image" src="https://user-images.githubusercontent.com/1935113/183346943-9bab6173-ba9d-444b-8ed6-7579b4e3d5f1.png">

<img width="387" alt="image" src="https://user-images.githubusercontent.com/1935113/183346980-e461f073-c0fc-4b22-b3db-148c65d72cc6.png">

And the hover effect of site-title needs updates.

* underline (default) ✅ , no underline (on Hover) ❌ 

Reopening the issue.
