### ISSUE TITLE
club: Pre-launch: Screenshot, readme.txt & description

### ISSUE THREAD

**Issue by matiasbenedetto** [Automattic/themes#6228]

**Comment by matiasbenedetto** [comment]
@beafialho would you be able to provide the screenshot and description for Club theme?

**Comment by beafialho** [comment]
Sure @matiasbenedetto:

> Club is a funky, vibrant, opinionated theme with a monospaced font.
Both its styles and spacing form an edgy aesthetic perfect for those looking to build a quirky website.

![Club Screenshot](https://user-images.githubusercontent.com/65220155/183861828-f505014a-3a4e-43f4-8e4c-cc68242a46c3.png)

**Comment by matiasbenedetto** [comment]
Thanks @beafialho!
