### ISSUE TITLE
Rainfall: Post template spacing & alignments

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#6246]
1. Post title and date would ideally be full width.

<img width="1535" alt="Captura de ecrã 2022-07-15, às 11 31 41" src="https://user-images.githubusercontent.com/65220155/179207543-2f5c7fb2-fa0a-4915-8329-8621222d3489.png">

2. Spacing between these two sections should be identical. The larger spacing is the correct one. Also, top and bottom padding of post navigation should be identical.

<img width="1536" alt="Captura de ecrã 2022-07-15, às 11 32 05" src="https://user-images.githubusercontent.com/65220155/179207601-dd601b7f-ef57-4f76-984f-c0470b39ad55.png">

3. Post featured image top and bottom padding and the date should be aligned at the bottom not on top.

<img width="1436" alt="Captura de ecrã 2022-07-15, às 11 40 43" src="https://user-images.githubusercontent.com/65220155/179207858-7b51fe22-5415-44ad-ba8e-6217c111a7ed.png">

4. This is also happening at a certain breakpoint.

<img width="1012" alt="Captura de ecrã 2022-07-15, às 11 51 08" src="https://user-images.githubusercontent.com/65220155/179209387-3f6e2bb2-f7bd-404c-b6b4-2cdec4e22f04.png">

5. Currently, the search field is much higher than it's intended:

| Test site | Mockup |
| ---- | ---- |
| <img width="336" alt="Captura de ecrã 2022-07-15, às 11 54 17" src="https://user-images.githubusercontent.com/65220155/179209840-3ea55b8f-f57f-44f2-95b0-869681f2b804.png"> | <img width="447" alt="Captura de ecrã 2022-07-15, às 11 54 07" src="https://user-images.githubusercontent.com/65220155/179209818-3a0e684c-5e62-4c1f-97b5-9b63743ddcb8.png"> |

Note that this one is supposed to be different than the search template one, which looks correct.

<img width="1323" alt="Captura de ecrã 2022-07-15, às 11 55 38" src="https://user-images.githubusercontent.com/65220155/179210007-3c9f410c-308d-4892-9462-65ff50d21df8.png">

**Comment by mikachan** [comment]
These issues should all be addressed by https://github.com/Automattic/themes/pull/6284.
