### ISSUE TITLE
Style variations missing in dotOrg published themes

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6248]
## Steps to replicate

Style variations in the published themes [Pendant](https://wordpress.org/themes/pendant/) and [Remote](https://wordpress.org/themes/remote) are missing in dotOrg.
There exists styles directory, but it is empty.

Style variations are available and working fine in dotCom

## Result

Style variations aren't working local installs.

## Expected

dotOrg theme source should include style variations.

**Comment by pbking** [comment]
The [assets excluded ](https://github.com/Automattic/themes/blob/blockbase-3/dotorg-exclude.txt#L6)from being packaged in the dotorg zip files include all json files while theme.json is [explicitly included](https://github.com/Automattic/themes/blob/blockbase-3/package-dotorg.sh#L14).

We need to either explicitly allow any *.json file in the /styles folder to be included or remove the *.json exclusion.  I'm not sure which is better.

**Comment by jeffikus** [comment]
@pbking sounds like quickest path the fixing this is allowing the *.json files in the /styles folder.

**Comment by madhusudhand** [comment]
Once the fix is merged, `Pendant` and `Remote` needs version bump.

**Comment by pbking** [comment]
As mentioned those themes need a version bump.  Done here: https://github.com/Automattic/themes/pull/6259

**Comment by madhusudhand** [comment]
Themes published to dotOrg now include style variations.
