### ISSUE TITLE
TextBook: Other elements obscure Featured Page content if ads active on site

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#625]
## Steps to replicate

1. Use a public site on the free plan, so ads will be displayed.
2. Set Latest posts as the front page
3. Apply a custom header image
4. Set a featured page under Theme Options

## Result

The ads appear under the Featured Page content, which is expected, but this causes the Featured Page area to expand upwards. Depending on the height of the viewport, this results in the Featured Page area to become hidden behind the site menu, or even to be pushed completely off the top of the page.

<img width="1340" alt="_ _ _ _ _ _ _ _ _" src="https://user-images.githubusercontent.com/11873759/52931737-20ae2b00-3356-11e9-8ac3-4e091ab8fd60.png">

Confirmed in both Firefox and Chrome.

## Expected

For the Featured Page content to always be visible, below the site menu.

* User report: https://en.forums.wordpress.com/topic/ads-in-the-middle/
* Site: https://chartografos.net/

**Comment by alaczek** [comment]
In this case I don't think ads should be displaying below featured content, the design does not really accommodate for anything longer then the excerpt. I believe in this case ads should not be disabled in this spot at all. @KokkieH could you bring this up with the Ads team?

**Comment by KokkieH** [comment]
I'll P2 it, yes.

**Comment by KokkieH** [comment]
p4x5kY-10a-p2

**Comment by laurelfulford** [comment]
Thanks @KokkieH!

It looks like a fix has been deployed for this, as a result of your post. I'm going to close this issue and will follow up in the forum thread.

**Comment by KokkieH** [comment]
Thank you :)
