### ISSUE TITLE
Apostrophe 2: display the social networks on small devices

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#628]
## Steps to replicate

1. Activate the theme
2. Create a social menu
3. Visit your site on mobile

## Result

No sign of the social icons on devices smaller than 767px.

## Expected

See the actual icons. Current we are offering workarounds like this following:

```
@media (max-width: 767px) {
  .main-navigation {
    position: relative;
  }
  .jetpack-social-navigation {
    display: block;
    position: absolute;
    top: 0;
    right: 0;
    width: 80%;
    height: 50px;
  }
  
  .jetpack-social-navigation ul li a {
      margin: 0 2rem 0 0;
    padding: .75rem 0 1.5rem;
    line-height: 45px;
  }
}
```

Result:
![see screen shot](https://cld.wthms.co/7LcUTm+)
_Link:_ https://cld.wthms.co/7LcUTm

I believe we are not prioritizing changes like this at the moment, but I wanted to report it anyway. Thank you!

* User report: 10560383-hc
* Follow-up ticket: no follow-up so far.

**Comment by torres126** [comment]
PR in #738 to add an option for this. :)
