### ISSUE TITLE
Payton: Font selection doesn't save in global styles > Text

### ISSUE THREAD

**Issue by kavyagokul** [Automattic/themes#6289]
## Steps to replicate

Start with a site on the Payton theme. 

1. Go to Apeparance > Edit
2. On the top right corner, click the global styles button
3. Select the Typography option, and then the *Text* option
4. Set the *Font family* to one of the available options apart from Default
5. Save changes, and reload
6. Go back to global styles > Typography > Text

## Result

The Default option is set under Font family

## Expected

The chosen font family is persisted in Font family option

* User report: 3392007-hc
* Follow-up ticket: 5427250-zen

**Comment by Robertght** [comment]
I'm going to close this in favor of https://github.com/Automattic/wp-calypso/issues/66037
