### ISSUE TITLE
Sync TwentyFifteen with core

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6296]
[This change](https://github.com/Automattic/themes/pull/6292) introduced the ability to (relatively painlessly) sync core theme changes from wporg to wpcom.

It worked well for all themes except for TwentyFifteen.  When using the utility the logs caused the command to uh... not work.  I wasn't able to discern why or how to get around it (short of not including the logs in the diff).

The highest priority is shipping TwentyFifteen, even if the logs have to be put in manually or aren't even present.

The second priority is to (if possible/necessary) adjust the script to account for whatever in the logs is tripping it up.

**Comment by mikachan** [comment]
TwentyFifteen has now been synced (D85306-code), and the issue with logs vs sync script was fixed here: https://github.com/Automattic/themes/pull/6310 🎉
