### ISSUE TITLE
Club: text decoration too thick

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#6378]
Currently, the links underline is much thicker than the mockups. It would be nice if it's the same thickness, probably `1px`. This is important because the typography is already quirky, which defies readability so we should minimize elements that can add noise.

|   Theme    | Mockups |
| ----------- | ----------- |
|   <img width="1017" alt="Captura de ecrã 2022-08-11, às 16 05 18" src="https://user-images.githubusercontent.com/65220155/184166036-a1429db2-366d-48fe-9a0b-620e06111813.png">  |    <img width="772" alt="Captura de ecrã 2022-08-11, às 16 05 27" src="https://user-images.githubusercontent.com/65220155/184165925-d673a726-a2f5-4bce-b2fa-3d746f19a6cc.png"> |

**Comment by matiasbenedetto** [comment]
I can confirm that this is happening in WebKit browsers (Safari and others) but not on Chrome or Firefox.

**Comment by beafialho** [comment]
You're right @matiasbenedetto, I saw that on Safari but not Chrome and Firefox.
