### ISSUE TITLE
Club: Pre-launch: Demo Site

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#6393]
Create the demo site on wordpress.com.

**Comment by jeffikus** [comment]
@beafialho do you have capacity to work on this this week?

**Comment by jffng** [comment]
I am happy to get it set up and then maybe @beafialho can review / edit the content as needed.

**Comment by beafialho** [comment]
> @beafialho do you have capacity to work on this this week?

Yes, I can work on it. Thanks @jffng for the help!

**Comment by beafialho** [comment]
**Update:** The [demo site](https://clubdemo.wordpress.com) is ready.
