### ISSUE TITLE
Disco: Pre-launch: Showcase Entry

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#6395]
@matiasbenedetto I'm happy to pair with you on this as well.

@beafialho would you be able to provide a devices mockup for Club for its showcase entry?

**Comment by beafialho** [comment]
Sure @jeffikus, here it is:

![club_devices](https://user-images.githubusercontent.com/65220155/184831280-44a104fb-87d7-49e5-81ca-122daf0cafe6.jpg)

**Comment by jeffikus** [comment]
I've updated the showcase entry with the above image.

**Comment by jffng** [comment]
This is done.
