### ISSUE TITLE
Affinity: Background color shows text in white on preview, while it's not white on live site

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#640]
## Steps to replicate

- Start with a WordPress.com site with Affinity theme
- Open https://wordpress.com/customize (Customizer) and click on `Colors & backgrounds`
- Choose a dark background color (do not work with palettes)

## Result

- Notice that the preview on the right shows text in white, to enable better readability with the dark background
- The live site does not show the text in white though and is dark, making is very hard to read.

| Customizer view | Live site |
|------|------|
| <img width="1595" alt="screenshot 2019-02-22 at 16 49 13" src="https://user-images.githubusercontent.com/18581859/53239381-e4fec280-36c1-11e9-9eee-1dec4e267043.png"> | <img width="1403" alt="screenshot 2019-02-22 at 16 49 34" src="https://user-images.githubusercontent.com/18581859/53239383-e5975900-36c1-11e9-8e61-e485dc8371c1.png"> | 

## Expected

The text color on Customizer preview and live site matches.

* User report: 6698850-hc
* Follow-up ticket: 1819433-zen

**Comment by torres126** [comment]
Possibly the same issue as #462?

> This sounds like a broader issue we have reported for custom colours - basically, free plans can use theme's custom palettes or change the background colour; other plans have access to more colour customization. However, the preview for free themes wrongly shows that the text colour will change to contrast against the background, when in reality, it doesn't. The issue is: 8119-wpcom.

**Comment by arunsathiya** [comment]
Good find, @torres126, thanks! Closing this in favor an internal report 8119-wpcom.
