### ISSUE TITLE
Apostrophe 2:Product images not displaying on Shop Page (Woo)

### ISSUE THREAD

**Issue by guicmazeredo** [Automattic/themes#641]
## Steps to replicate

Activate the Apostrophe 2 theme and set up a shop page with a few products and access the shop page.

## Result

The product images won't load. It shows a placeholder instead. 
https://cld.wthms.co/blEFMu

(the actual product page shows the images fine).

I was able to replicate the issue on a test site. Switching the theme fixes the issue. 

## Expected

I expected to see the images set as the *product image* on the shop page. 
 
* User report: #10654923-hc
* Follow-up ticket: #1824748-zd

**Comment by laurelfulford** [comment]
I can recreate this.

Under Content Options, Apostrophe 2 sets showing featured images on pages to false by default:

https://github.com/Automattic/themes/blob/master/apostrophe-2/inc/jetpack.php#L37-L43

Turning that to true makes the project images appear again. I'm not sure why -- the shop page is like an archive page, not a regular page, and there was already and issue around the control for featured images on the blog index and archive pages affecting the shop pages:

https://github.com/Automattic/jetpack/issues/8835

Going to do a little more digging and possibly report an issue to Jetpack. In the meantime, the user can get this working on their site by checking the box -- I've added a comment to the ticket to that effect, and will leave this open until I've ruled out the theme being a factor completely,

**Comment by laurelfulford** [comment]
Ok, so this is a super strange one. It's not Apostrophe 2 specific, but it only happens to themes that have content options and:

1. Have a control to toggle featured images on pages
2. Have that control set to false by default
3. Do not include support for WooCommerce.

Apostrophe 2 is the only theme of ours like this, but I can recreate the issue if I remove the WooCommerce support in Button 2 (another theme that meets criteria one and two).

**Comment by laurelfulford** [comment]
I've created a Jetpack issue here: https://github.com/Automattic/jetpack/issues/11404
