### ISSUE TITLE
Enable all wpcom themes to opt-in to `appearanceTools`

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6411]
Does a new `add_theme_support` need to be created to support this?

Can this be accomplished with a mu-plugin?

Can we limit this to Varia/Seedlet?

> It’s not great that themes as recent as TT1 lag behind features

**Comment by pbking** [comment]
I started working on this by allowing [appearanceTools to be enabled via a theme support](https://github.com/WordPress/gutenberg/pull/43337).  With that in place we could then probably simply `add_theme_support( 'appearance-tools' );` in a mu-plugin or perhaps more carefully per-theme (adding it to Varia would cover a lot of ground).

**Comment by mikachan** [comment]
Thank you for working on this! 

> With that in place we could then probably simply add_theme_support( 'appearance-tools' ); in a mu-plugin

This is also what I was thinking (but doesn't mean it's the best way..) Looking at adding it to specific themes sounds like a good plan too, especially for submitting to dotorg.

**Comment by jeffikus** [comment]
Thanks for taking the initiative on this. 

Could we not do a blanket mu-plugin approach for dotcom and then opt out on themes that report issues? We could still add the support for themes we ship to dotorg as well.

**Comment by pbking** [comment]
Yea.  My 'druthers would be to start with Varia themes and if there are no side effects ship the mu-plugin to update all the rest.  This way at least those Varia classic themes would be a public example of how to take advantage of the feature and give us a little time between "some known smallish number of themes" and "all the themes".

**Comment by simison** [comment]
Just asked the same about Lettre https://github.com/Automattic/themes/issues/6492#issuecomment-1233999159

And same could be done for Lynx (link-in-bio) theme, cc @alaczek

**Comment by pbking** [comment]
I suggest holding off a couple of days @simison.  I just deployed the change to provide this feature to all of the Varia themes and don't expect any issues.  I'm working on a separate mu-plugins solution that we should probably deploy early next week which would cover any remaining themes (both classic and block).

**Comment by pbking** [comment]
The mu-plugins implementation is here: D87048-code

**Comment by pbking** [comment]
The above diff has been abandoned.  A better solution is to enable this either in wpcomsh or ETK would be better than the previous change as it only encompasses simple sites.

However, determining if it should be enabled is still ongoing.

**Comment by simison** [comment]
> However, determining if it should be enabled is still ongoing.

Was it enabled and what was the technique at the end?

**Comment by pbking** [comment]
There were issues with some sites when this was enabled at a smaller scale (only Varia themes).  We weren't able to fully resolve those and the best scenario seems to be enabling "appearanceTools" on a per-theme basis for now.  Which is a different (and large) beast itself.

**Comment by apeatling** [comment]
@pbking Do you have any links to some of the issues you ran into when enabling this on Varia themes? Interested what you saw as we're going to see what we can do to help.
