### ISSUE TITLE
Professional Business: Links in Media & Text Block not working in Edge

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/themes#642]
## Steps to replicate

1. Create a Media & Text block on a page with the Professional Business theme.
2. Add text to the block, and then add a link to a portion of that text
3. Publish the block, and then open that page up in Edge.

## Result

The links are not clickable in Edge, but work in other browsers. I've narrowed this issue down to be theme related as my test site only showed this behaviour once I switched to the Professional Business theme.

## Expected

The links within the Media and Text blocks should be clickable in all browsers.

* User report:  #10603242-hc
* Follow-up ticket: #1824848-zen

**Comment by danieldudzic** [comment]
Professional Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Dalston: https://wordpress.com/theme/dalston
