### ISSUE TITLE
Rainfall: Pre-launch Tasks

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#6421]
These are the tasks required to launch Rainfall on wpcom:

- [x] Demo Site
- [x] Showcase Entry
- [x] Headstart Annotation (D91175-code)

**Comment by beafialho** [comment]
Theme description:

_Rainfall is a clean, objective blogging theme strongly inspired by Swiss Design.
Its minimalist functionality is balanced by a strong accent color, beautiful photography and post templates with sidebars._

**Comment by matiasbenedetto** [comment]
@beafialho Could you upload the showcase image for Rainfall, please?

**Comment by beafialho** [comment]
@matiasbenedetto is that the one with 1200 x 900px or a full page screenshot?

**Comment by matiasbenedetto** [comment]
>is that the one with 1200 x 900px or a full page screenshot?

@beafialho is this type of image: https://theme.files.wordpress.com/2022/08/disco-showcase.jpg

**Comment by beafialho** [comment]
Oh, that's right! I totally forgot this one 😄 Here it is:

![rainfall](https://user-images.githubusercontent.com/65220155/191791810-70003133-c536-4a37-877e-f808159651c0.png)

Here's one showing the patterns to include in the showcase entry:

![Rainfall Patterns](https://user-images.githubusercontent.com/65220155/191791751-da7f3d89-805d-4383-97de-f5e19fd9cba1.png)

**Comment by mikachan** [comment]
All these tasks are now complete 🎉
