### ISSUE TITLE
Ryu: improve formatting of Akismet privacy notice.

### ISSUE THREAD

**Issue by stephdau** [Automattic/themes#643]
## Steps to replicate

Users have the option to turn on an optional Akismet privacy notice under the comments form.

See under comment form at https://robotskirts.com/2019/02/24/smash-and-grab/

## Result

@cfinke brought up that it’s not looking great inside the (A8C-authored) Ryu theme: https://a8c.slack.com/archives/C029E4HPT/p1551067745055100

<img width="1420" alt="screen shot 2019-02-24 at 8 08 09 pm" src="https://user-images.githubusercontent.com/1891/53407391-05759800-39b4-11e9-9dca-6626337bf4d1.png">

Screenshot from https://robotskirts.com/2019/02/24/smash-and-grab/

I looked into it, and it’s because there is a lot if `max-width` magic being done on sub-elements of the comments area wrappers, instead of the latter, which means we’re not benefitting from it.

## Expected

Since it’s one of our themes, I figured maybe we could add a bit of CSS to make our privacy notice look a bit better in Ryu.

I've asked about it in the themes channel on Slack [here](https://a8c.slack.com/archives/C029FM1EH/p1551088383123200), and was told by @davidakennedy that opening an issue is indeed the right way to go.

* User report: https://a8c.slack.com/archives/C029E4HPT/p1551067745055100

**Comment by nielslange** [comment]
@stephdau I'll take a look at this issue later! ;)

**Comment by stephdau** [comment]
Thanks @nielslange :)

**Comment by nielslange** [comment]
@laurelfulford Is the Ryu theme maintained by its theme developer, as it’s not part of this repo?

CC: @stephdau

**Comment by laurelfulford** [comment]
@nielslange Hey! Any of our free themes that don't live here live in the free theme SVN repo. Actually, these themes do, too -- they live in both spots, and when PRs are merged here we also  have to move them to SVN, since that's where the themes are served up to WP.com.

There's a bit more info here: pNEWy-a9V-p2.

**Comment by nielslange** [comment]
Thanks, @laurelfulford. I'll check out the SVN repo. 😉

**Comment by danieldudzic** [comment]
Hi @stephdau,

I have now fixed the notice styling in r54709.
