### ISSUE TITLE
Rainfall: "Menu" term should be the same size has site title

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#6431]
Currently:

<img width="578" alt="Captura de ecrã 2022-08-23, às 10 46 58" src="https://user-images.githubusercontent.com/65220155/186127695-ad7cff29-0b86-4adb-88ec-40d388a1431e.png">

Intended:

<img width="437" alt="Captura de ecrã 2022-08-23, às 10 47 47" src="https://user-images.githubusercontent.com/65220155/186127802-9875dd51-0356-48b5-bff6-4503b41c1ca7.png">

**Comment by mikachan** [comment]
This should be fixed as part of https://github.com/Automattic/themes/pull/6417.
