### ISSUE TITLE
Rainfall: Featured Image shouldn't be full width on Single Post template

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#6433]
Currently:
<img width="1332" alt="Captura de ecrã 2022-08-23, às 10 57 16" src="https://user-images.githubusercontent.com/65220155/186129829-18fe3656-4db7-4de8-924b-37da15b6f52b.png">

Intended:

<img width="1046" alt="Captura de ecrã 2022-08-23, às 10 57 24" src="https://user-images.githubusercontent.com/65220155/186129925-e86c26a0-c074-4e56-b986-b359245b791a.png">

It would be great if the featured image could have a constrained height to avoid too much scrolling.

**Comment by yashitamittal11** [comment]
I started working on this issue. I made change to the rainfall/single.html template to test the fix on my localhost.

**Required changes**
This is the existing block markup for the Post Featured Image block -
`<!-- wp:post-featured-image {"align":"full"} /-->`

I edited the markup to change the alignment to wide and moved the block markup inside the wp:group  tag so the layout CSS for wide width applies to the post featured image block.

Layout CSS -

```
.wp-container-id > .alignwide {
   max-width: 1280px;
}
```

![rainfall- single](https://user-images.githubusercontent.com/21078987/186617147-ffcb421a-417f-4323-b8e2-295ec411102a.png)

**Comment by mikachan** [comment]
Hey @yashitamittal11, thanks so much for looking into this!

Looking at this issue, I believe we just need to replace the featured image markup with the 'align wide' version:

```
<!-- wp:post-featured-image {"align":"wide"} /-->
```

If we also move the image into the group block, the image does not align with the post title or date:

![image](https://user-images.githubusercontent.com/1645628/186637867-0a42b3a7-4d8f-4acd-af6d-5772eb1a2023.png)

This is how it looks without moving the featured image block, which I believe is what we want to achieve:

![image](https://user-images.githubusercontent.com/1645628/186638102-c05ef7e0-cb8b-4b9b-824d-06e1a2ea92ba.png)

**Comment by yashitamittal11** [comment]
Thanks @mikachan, initially I tested by replacing the featured image markup with the 'align wide' version, but it didn't work for me. 

![rainfall-debug](https://user-images.githubusercontent.com/21078987/186647625-995dfdf8-6094-4775-a542-bbd0fc55a8dc.png)

This is the first time I am working on the block theme code. Do let me know if I am missing anything. Thank you!

**Comment by mikachan** [comment]
> initially I tested by replacing the featured image markup with the 'align wide' version, but it didn't work for me.

Hmm, it would be good to get to the bottom of this, and perhaps find out why you couldn't see the align wide version.

> This is the first time I am working on the block theme code.

I think you're in a good place to learn! 🎉 For things like this issue, I'd suggest opening a PR in this repo with your proposed changes. That way, it's easier for us to comment on specific lines of code and hopefully see where you may be having issues on your side.

**Comment by csonnek** [comment]
We have a user in the forums having the exact same issue with the Russell theme: https://wordpress.com/forums/topic/how-can-i-make-the-featured-photo-in-russell-theme-smaller-size-i-upload/?view=all

They post portrait photos and on the single post template the images are enormous: 

Example: https://jadenicolebeals.com/2022/08/26/a-new-song-in-my-ears-sketching-til-noon-i-raised-the-chandelier/

Let me know if I need to open a separate issue for Russell.

**Comment by mikachan** [comment]
Hi @csonnek. Please open a separate issue for Russell. This issue is for another theme that hasn't been released, and the issue in question is more of a 'doesn't match the design' issue rather than a bug. Thank you!

**Comment by yashitamittal11** [comment]
I got busy and didn't get time to work on this issue. Thanks for helping @mikachan

**Comment by mikachan** [comment]
No worries, although please feel free to contribute to this theme or any other issues/themes that you'd like to work on!

**Comment by yashitamittal11** [comment]
@csonnek I have created an issue for Russell theme here- https://github.com/Automattic/wp-calypso/issues/67300

**Comment by csonnek** [comment]
@yashitamittal11 thank you! I was on vacation and was following up with GitHub notifications.
