### ISSUE TITLE
[Bug]: Lettre theme subscription input poor look at mobile

### ISSUE THREAD

**Issue by simison** [Automattic/themes#6436]
### Quick summary

Subscription block doesn't render nicely on mobile view:

![Screenshot 2022-08-24 at 14 06 07](https://user-images.githubusercontent.com/87168/186407533-2d61c168-c3b3-41d2-9717-686c2b2b1e19.png)

### Steps to reproduce

1. Create site via https://horizon.wordpress.com/setup/?flow=newsletter
2. Observe mobile preview of theme at final step

### What you expected to happen

Render similarly like higher up on the homepage:

![Screenshot 2022-08-24 at 14 29 57](https://user-images.githubusercontent.com/87168/186407653-6e8464d5-c8f7-4c5e-9a44-cc100d27800e.png)

### What actually happened

Rendered differently, presumably inside some container that creates too much padding/margin on mobile?

### Reproducibility

Consistent

**Comment by jffng** [comment]
Potential fix here: D86479-code
