### ISSUE TITLE
Slideshow block does not display when added to templates in the site editor

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#6439]
### Quick summary

Slideshow block displays correctly in the site editor (when editing theme templates) but is broken on the front end of the site when published.

### Steps to reproduce

- Edit page template in site editor to add slideshow block
- Observe that the block and slideshow images do display correctly in the editor view
- Publish the changes and view the template on the front end of the site
- The slideshow does not display correctly and appears to be empty (white) and has only one arrow showing on the left. 

### What you expected to happen

Slideshow to display as normal.

### What actually happened

Slideshow appeared to be broken on the published site.  

Screenshot of slideshow in the editor (left) and on the site (right)
<img width="2233" alt="Screen Shot 2022-08-24 at 4 12 16 PM" src="https://user-images.githubusercontent.com/1967448/186539566-7ab0843a-2783-4a30-aa58-9cc36a9b1e75.png">

### Browser

Google Chrome/Chromium

### Context

https://wordpress.com/forums/topic/slideshow-81

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Slide show block works fine on pages and blog posts, just not in the templates in the site editor.  It may be possible for some users to work around this by limiting themselves to adding slideshows in the post content area only.

**Comment by Robertght** [comment]
Thank you @jerrysarcastic !

This is a known issue with the Slideshow block and it's not fully compatible with the Site editor right now. 

in the future, please open the issues using Bugomattic. :) 

Closing in favor of this: https://github.com/Automattic/jetpack/issues/22834
