### ISSUE TITLE
Multiple themes: Hard coded column width for Media & Text Block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#644]
In Professional Business, Sophisticated Business, and Friendly Business, the column that has an image is set to 60% in CSS for > 768px so the resizing column option doesn't work as expected.

The image in the vertical content takes indeed 60%, but that's specified in the block setting, and there is no need to specify that in themes.

The following styles are the cause.

```
@media only screen and (min-width: 768px) {
	.entry .entry-content .wp-block-media-text {
		grid-template-columns: 60% auto;
	}
	
	.entry .entry-content .wp-block-media-text.has-media-on-the-right {
		grid-template-columns: auto 60%;
	}
}
```

```
.editor-styles-wrapper .wp-block-media-text {
	grid-template-columns: 60% auto;
}

.editor-styles-wrapper .wp-block-media-text.has-media-on-the-right {
	grid-template-columns: auto 60%;
}
```

**Comment by cathymcbride** [comment]
retired theme. Closing... (looks like there was a PR to fix it tho)
