### ISSUE TITLE
Pixl: Pre-launch: Showcase Entry

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6472]

**Comment by madhusudhand** [comment]
@beafialho can you attach screenshots for showcase entry here.

**Comment by beafialho** [comment]
Sure @madhusudhand, here it is:

![Pixl](https://user-images.githubusercontent.com/65220155/192556705-6d732bb8-9836-4bbe-99d7-1a0e704fefb0.png)

**Comment by beafialho** [comment]
The [demo site](https://pixldemo.wordpress.com) has been updated too.

**Comment by madhusudhand** [comment]
Created the showcase entry https://theme.wordpress.com/themes/pixl/
