### ISSUE TITLE
Issuu block is not responsive

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#649]
## Steps to replicate

Add Issuu block to a post or page and view at different screen sizes.

## Result

The embed is wider than the post content on mobile (tested in Argent and Twenty Nineteen)

In Argent theme it is wider even on desktop:
<img width="1440" alt="screen shot 2019-03-01 at 5 22 02 pm" src="https://user-images.githubusercontent.com/2031017/53620436-12f68080-3c47-11e9-9a18-bca8d2c6f7c3.png">

Argent mobile:
<img width="427" alt="screen shot 2019-03-01 at 5 22 35 pm" src="https://user-images.githubusercontent.com/2031017/53620441-17229e00-3c47-11e9-9800-0e14a79ac516.png">

## Expected

Embed should shrink to fit content area

I'm not sure if this is a theme-level issue, but it could be fixed in themes by adding this CSS:

```
.issuuembed.issuu-isrendered {
    max-width: 100%;
}
```

* User report: 10831576-hc
* Follow-up ticket: 1842528-zd

**Comment by crunnells** [comment]
Looks like this issue comes from core Gutenberg, so I've reported it here: https://github.com/WordPress/gutenberg/issues/14299

**Comment by cathymcbride** [comment]
Closing based on 👆
