### ISSUE TITLE
[Bug]: Lettre (newsletter theme) — long single word titles get cut easily

### ISSUE THREAD

**Issue by simison** [Automattic/themes#6492]
### Quick summary

Even a bit longer single word texts get cut out easily, and not split to multiple lines due lack of spaces:

![image](https://user-images.githubusercontent.com/87168/187874697-7aab7ee6-bfe2-4f43-9c81-1d0f64fd37c3.png)

<img width="410" alt="image" src="https://user-images.githubusercontent.com/87168/187876197-c69e58d5-4351-48b5-a9f7-52d5e9f2cc25.png">

Might not happen in English that often, but in some other languages (like Finnish, German, Swedish) where long words are common this could happen more frequently.

Is it worth making the text slightly smaller on narrow screens?

### Steps to reproduce

You can test longer terms in https://horizon.wordpress.com/setup/?flow=newsletter and check the mobile preview at launchpad.

### What you expected to happen

Smaller text or auto-hyphen.

Tested above example with [`hyphens: auto;`](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens) and `lang="fi"`, slightly better — could work better for English or German:

<img width="397" alt="image" src="https://user-images.githubusercontent.com/87168/187876571-ae962e66-c21d-4c1b-b766-c1c0bc888212.png">

### What actually happened

Cut out.

### Reproducibility

Consistent

cc @mtias

**Comment by simison** [comment]
Matías noted:

> Should probably just be using the new fluid type flag

**Comment by simison** [comment]
Similar issue with newsletter archive post titles on homepage:

<img width="404" alt="image" src="https://user-images.githubusercontent.com/87168/187882072-ec87523c-06ba-45b1-86d5-4140400c8ed4.png">

The mobile viewport width in examples is kinda extreme 320px, while higher end phones are wider than that. But still!

**Comment by mikachan** [comment]
I've created a potential fix for this here: D87131-code

**Comment by mikachan** [comment]
Closing as D87131-code has been deployed.

**Comment by mtias** [comment]
Thanks @mikachan !
