### ISSUE TITLE
Homestore theme: Below Header widgets overlap breadcrumb links

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/themes#6496]
### Quick summary

The Homestore theme (and possibly Storefront or its other child themes) displays the "Below Header" widget area widgets just above _and on top of_ the breadcrumb trail. This makes it impossible to click on the breadcrumb links to navigate through relevant shop pages.

### Steps to reproduce

1. Activate _Homestore_ on your site.
2. Add a widget to the "Below Header" area at _Appearance > Customize > Widgets > Below Header_. (Tested with an Image and Heading widget.) Save changes.
3. Visit the site and navigate to a product page.
4. Try to click on a breadcrumb link.

### What you expected to happen

The "Below Header" widgets should appear above the breadcrumb trail and not interfere with the links.

### What actually happened

The widgets overlap the breadcrumb trail visually, and prevent the breadcrumb links from being clicked on.

### Context

5490858-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

Tested on Homestore, unsure if this affects Storefront or other Storefront children.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Removing widgets from the "Below Header" widget area allows breadcrumb links to be clicked again. Some CSS can also be used to force the widget area behind the breadcrumb:

```
.header-widget-region {
    z-index: -1;
}
```

**Comment by jamiepalatnik** [comment]
📌 SCRUBBING : RESULT
- Tested on AT - Replicated
- Tested on Self-hosted - Replicated
- Replicable on Core - Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can replicate the issue on my AT site and self-hosted site with the Homestore theme active. Here's a screenshot:
<img width="593" alt="Below Header + breadcrumbs" src="https://user-images.githubusercontent.com/30788962/187971011-6ef56309-616f-4b08-9e10-c2fc5d383742.png">

- I cannot replicate on Storefront or child themes Bookshop or Galleria.
- Transferred to themes repo, but wondering if this should possibly go to woocommerce/storefront repo instead?

📌 ACTIONS
- Marked as Triaged for Quality Squad review

**Comment by Robertght** [comment]
I created a replica of this report in the Homestore theme repository and I'm closing this one for now.

cc @jamiepalatnik
