### ISSUE TITLE
Lettre: update link colors and add fluid typography

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#6512]
Lettre needs some updates: 

- [x] Links should not be set to the primary color by default: pNEWy-fia-p2#comment-54984
- [x] Implement fluid typography: pdtkmj-pL-p2#comment-851

**Comment by mikachan** [comment]
Fluid typography is hopefully covered with this diff: D87131-code

**Comment by mikachan** [comment]
Looks like the link colour issue has been handled with D87616-code, so I'm going to close this. Please re-open if I've misunderstood!
