### ISSUE TITLE
Orvis - Page Attributes Missing Portfolio Template option in Classic Editor

### ISSUE THREAD

**Issue by damiannep** [Automattic/themes#652]
Steps to Replicate
1. Activate Orvis
2. Make sure Classic Editor is enabled (not Block Editor)
3. Look for Page Attributes in Page Settings
4. No option for Portfolio Template
(Using Chrome Version 72.0.3626.119 (Official Build) (64-bit))
![screenshot](https://cld.wthms.co/F1Oj75+)

The option for Portfolio Template exists in WP Admin and with the Block Editor enabled.

* User report: #1844099-zen

**Comment by alaczek** [comment]
Hmm... I could not replicate this on a site with Classic editor and using Orivs theme. Can someone verify?

**Comment by damiannep** [comment]
Thanks for testing.  I checked on the same test site, with Orvis still active, where I took the screenshot earlier. I can no longer replicate this either. I'm going to go ahead and close this issue.
