### ISSUE TITLE
All Theme Variations: Horizontal paddings add too much space when inside full-width column blocks

### ISSUE THREAD

**Issue by allancole** [Automattic/themes#654]
## Steps to replicate

- Create a 3 Column Block, set it to `wide` aligned, publish and view it on the front end.

## Result

![image](https://user-images.githubusercontent.com/709581/53754825-11b19780-3e83-11e9-8914-1085d74bd0e3.png)

## Expected

The individual columns should be wider and stretch the full width of the site minus any horizontal margins. Instead, the horizontal padding is too generous and makes the columns appear too small.

## *EDIT

Turns out this issue effects all 6 theme variations, so I updated the title to reflect that. This issue also needs to be fixed in Twenty Nineteen—I’ll file a ticket on Trac if one doesn’t already exist

**Comment by crunnells** [comment]
Confirmed this is also present in the other `* Business` varians, in varying degrees. The padding comes from Twenty Nineteen, so it should be removed from there as well.
