### ISSUE TITLE
Decibel: Styles: Colors

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6545]
<img width="301" alt="image" src="https://user-images.githubusercontent.com/146530/189936512-b28a3e9f-8664-4c67-a67c-25ce1a59ad73.png">

Please reference the figma rather than the above image; the HEX values shown don't match the colors.

Figma: 1aQcwsAAmZOUOQqmdqP7kR-fi

**Comment by jffng** [comment]
Figma is not loading for me so removing my assignment until it does...

**Comment by vcanales** [comment]
The colors in the [current theme.json file](https://github.com/Automattic/themes/pull/6542/files#diff-c39a668465c7bbedc7caf7d523e7f8d7c38a812d21e420c5dc9be03bf7bd40e8R8-R30) already match those in Figma, so this was done in #6542.
