### ISSUE TITLE
Decibel: Styles: Links

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6548]
Style the link elements including the state selectors.

Inside Content Area:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/146530/189940229-8fa062f0-411d-474d-b01b-dfe6ac7e9e87.png">

Links OUTSIDE of the content area shouldn't have an underline text decoration in the default state but should show one on :hover.

**Comment by vcanales** [comment]
> Links OUTSIDE of the content area shouldn't have an underline text decoration in the default state but should show one on :hover.

@pbking Does this mean that we'd set the default link style to not have an underline, and then add an underline to links within post content? I can't seem to find this definition in the Figma doc.

**Comment by pbking** [comment]
I can't point to a conversation but I believe that different type of link style is common.

However, for the moment (especially since it's not noted anywhere but also because it's the fastest way to a useful change) let's just style the default link behavior to match the design.  If we need to limit the scope of that behavior to just the elements in `post-content` then we can refactor that down the road.

**Comment by pbking** [comment]
I remember why now. :)

The `link` styles target the site header and page links wheras we usually don't want that behavior.  Targeting only the elements in `post-content` allows those to be styled to our liking.
