### ISSUE TITLE
Decibel: Styles: Buttons

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6549]
Style 'em buttons.

Just the `element`, not the block.

Default         |         Hover             |      Focus         |             Active
![image](https://user-images.githubusercontent.com/1157901/190444359-b0879300-e007-41e5-a1ca-c124c47086a2.png)
There are TWO buttons styles in the design.

Neither of them are "outline" style.  Should we include one anyway?  Should we just call the second style "outline"?  Add a 3rd block style option for an "inverted button style"?

**Comment by pbking** [comment]
I actually don't see the 'default' button state used anywhere in the designs, only the darker version.

Let's drop that "default" state for now and instead implement the "alternate" as the default.  I think the stock outline button fits well; We don't need to wait for design approval to move ahead; there will be an opportunity to change it if needed later.

For now let's also lose the `focus` state styling.  I don't believe it's being applied and if we apply focus state design changes we'll likely need to do it elsewhere (css) and apply it broadly.

**Comment by vcanales** [comment]
This is in progress [here](https://github.com/Automattic/themes/pull/6567). Focus styles were applied to the buttons with theme.json; no extra CSS needed.

> I think the stock outline button fits well; We don't need to wait for design approval to move ahead; there will be an opportunity to change it if needed later.

Yeah, it's a close match. Henrique updated Figma, and the button should be filled with the primary color on hover; that and the focus style would be the only differences. I'm don't know if `:focus` can be applied to outline buttons through theme.json though.
