### ISSUE TITLE
Decibel: Styles: Layout & Padding

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6550]
Ensure the following matches the design:

The content width and wide width values 
the root padding gap (variable sized)
   Ensure responsive navigation matches.

Update (if necessary) spacing sizes so they can be used for padding values instead of explicit values.  
  
Build a "spacing content example" might be some good content to have to quickly/easily see the values calculated and demonstrated and add it to Theamdemo site. (For example a collection of group blocks labeled with the bottom/right border thickness assigned to different spacing values).

**Comment by jffng** [comment]
> Update (if necessary) spacing sizes so they can be used for padding values instead of explicit values.

Decibel does not specify a specific spacing scale, can we just go with the Gutenberg provided scale? Or were you thinking we should make a new fluid scale, like [TT3 does](https://github.com/WordPress/twentytwentythree/blob/trunk/theme.json#L83).

> Build a "spacing content example" might be some good content to have to quickly/easily see the values calculated and demonstrated and add it to Theamdemo site.

Good idea, I added something here: https://theamdemo.wordpress.com/2022/09/14/spacing-presets/ — is that what you meant?

**Comment by pbking** [comment]
> is that what you meant?

Yes exactly!  Thank you.

**Comment by pbking** [comment]
Decibel does not specify a specific spacing scale, can we just go with the Gutenberg provided scale? Or were you thinking we should make a new fluid scale, like [TT3 does](https://github.com/WordPress/twentytwentythree/blob/trunk/theme.json#L83).

If the spacing designed doesn't line up with the defaults we should change those like TT3 does we should change those to suit.  I haven't looked deeply at the spacing but I did notice a comment in the figma that noted that some spacing seemed inconsistent.  So ideally just tweaking those spacing values puts the theme where it needs to be.

**Comment by jffng** [comment]
I think this one needs some design input as well, should we add the tag here? Particularly:

- What are the default and wide widths
- What is the global padding value
- What is the spacing scale (if different from the Gutenberg default)

**Comment by pbking** [comment]
> I think this one needs some design input as well
...

I agree.  Let's bring in what we have but leave this issue open for review by design.  I'll illustrate the question better shortly.

**Comment by pbking** [comment]
Reopening for design review.

This picture illustrates the different width values we have configured.

Normal, wide and full.

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/146530/190495451-e191252b-8959-403c-bbcd-80be9f570e32.png">

It was difficult to ascertain from the comps WHY some things were as wide as they were.  Were the sizes intended to convey how far from the edge the content should be?  Or how large the content is allowed to get.

Currently we have (at wide width) a fairly large size padding that scales to pretty small on smaller screens.  However it may be the design intent that the content is instead constrained to "wide" mode instead of full width and those designs intend something we aren't implementing.

**Comment by henriqueiamarino** [comment]
@pbking @jffng Maybe I'll need to check a test site later but by these image above it looks fine to me.

**Comment by pbking** [comment]
Ok, I hope to have a demo site setup early next week, or you can test locally if you want to see it sooner.  The repo is pretty up-to-date.

I'll close this and we can create new issues if something doesn't work.

This confusion has shown us the need for some detailed "very wide" comps in our theme designs though to eliminate the ambiguity!
