### ISSUE TITLE
Loudness: Styles: Comments

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6551]
There are no designs for comments.

The "default" (Block Canvas) comments template was cleaned up in #6563 for this.

This is what it looks like unmodified.  Are there any design changes we should make?

<img width="691" alt="image" src="https://user-images.githubusercontent.com/146530/190220874-0a363098-7380-48a3-861d-8d36fea8e23a.png">

<img width="681" alt="image" src="https://user-images.githubusercontent.com/146530/190221002-4298d96b-1df3-46b4-8a69-8c448ac83432.png">

**Comment by henriqueiamarino** [comment]
Hey @pbking as I'm not sure about the spacing units that we are using I am fixing it as done in Pixl. It worked just fine! Let's set these spacing as related... layout, type and colors are good enough to go!

![response-feedback_decibel](https://user-images.githubusercontent.com/103748085/190594469-8d2232cd-3ec3-48a3-aacf-9a9fe13c37eb.png)

![response-feedback_figma](https://user-images.githubusercontent.com/103748085/190594504-7e67d964-b2e0-430c-b261-788c1f8faa73.gif)

**Comment by pbking** [comment]
I'm not sure how much control of some of the above spacing we (easily) have.  Gonna leave it as-is with this work as TBD and we'll see if we can tackle some of the spacing concerns you have down the road a bit.

**Comment by pbking** [comment]
I looked into the differences between Pixl and Loudness (and also Block Canvas).

While all of the templating and relevant style opinion seems to be the same between the themes the differences illustrated above still seem to persist and I can't quite figure out why.  There are different margins throughout and ¯\_(ツ)_/¯

More research is needed.  However I hoping that perhaps the existing layout is "good enough" to ship that that this issue doesn't hold up the release of Loudness if we can't get to the bottom of those differences.

**Comment by pbking** [comment]
Loudness is going to use the default spacing in the comments block so I'm going to close this issue.
