### ISSUE TITLE
Decibel: Styles: Navigation

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6552]
Here's the goal:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/146530/190007828-2adf4406-f9a7-487d-9928-b057c9dd4a27.png">

I wonder if/how we could style a navigation link to look like our standard button.  Does that make sense as a Block Style option?  

Also we do not currently have a design for the responsive menu.

**Comment by henriqueiamarino** [comment]
@pbking not sure if I got it right but I tried to style a navigation link just as our standard button. Also tested some responsive menu options, default and large sizes

![decibel_NavAlt](https://user-images.githubusercontent.com/103748085/190614674-b1738989-58e6-4e09-8712-c8727b0b141a.png)
![decibel_NavAlt_MobDefaultLarge](https://user-images.githubusercontent.com/103748085/190614912-040be15f-37fa-4f39-80b8-079f6437de38.png)

**Comment by pbking** [comment]
Oh that responsive menu looks great!  That's what we were looking for.  Not sure how sub-menu items will work there, if you have any ideas then please throw those up too.  Otherwise we'll do what looks good without too much customization and see how you like it.

Regarding the button I have been hoping to style the "Buy Tickets" button/link as was in the original design, but I'm not yet sure how that would look in the responsive menu (or even if styling that link that way is good/easy for the user).  Mixing the responsive menu button and menu options as you show above probably won't work though.  I'm not sure what the behavior is expected to be.  However, I like the look of that responsive menu button.  Maybe we can get it styled that way at least.
