### ISSUE TITLE
Loudness: Styles: Quote

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6553]
No Quote/Pullquote styles in design.  I believe we need some input:

By default:

Pullquote:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/146530/189986242-f0d8f3f0-e1a9-449b-82dd-62cd33933fe8.png">

Quote:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/146530/189986285-9d69ade0-bc81-4f2b-9248-329c848d115f.png">

**Comment by henriqueiamarino** [comment]
This default quotes are not bad at all @pbking. Anyway I create some following the style on patterns. All on Figma.

**Pullquote**
![decibel_Pullquote](https://user-images.githubusercontent.com/103748085/190605587-5fb713bf-b9a0-4b02-bd30-bb37f09eff69.png)
**Default**
![decibel_Default Quote](https://user-images.githubusercontent.com/103748085/190605614-834a37ac-1263-46ad-918a-009a357a8c61.png)
**Large**
![decibel_Large Quote](https://user-images.githubusercontent.com/103748085/190605628-64919b4d-520e-45b1-b528-ba1c18786a48.png)
