### ISSUE TITLE
Decibel: Styles: Variations

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6554]
There are some color experiments in the figma but no variation styles.  We should add some (I think lots of color variations for this theme could be extra-ordinary!)

**Comment by henriqueiamarino** [comment]
I believe those variations didn't make into the final theme as they are marked as Drafts. Just checked it with Bea and that's it. We can move on with no variations on Decibel.

**Comment by pbking** [comment]
Going to close this one now.

There are no variations planned for Decibel.  We'll open up a new issue should that change.
