### ISSUE TITLE
Decibel: Templates: Search, Category, Tag

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6555]
Default search page:
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/146530/190450951-1586a1da-ca7c-4928-9318-97d55682de1a.png">

Categories:
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/146530/190451086-0be775f1-f02a-4a50-8254-f22a133d3b6b.png">

**Comment by jffng** [comment]
I think this one also needs to be visited by design, it is basically the Archive template.

**Comment by henriqueiamarino** [comment]
@pbking @jffng lollowing an existing pattern I created an **Archive** page. I hope it can solve some of these problems. Design in Figma too.

![decibel_Archive](https://user-images.githubusercontent.com/103748085/190651859-add518f8-4902-4a23-93d8-089a8cc6fff0.png)
