### ISSUE TITLE
Decibel: Templates: Single

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6557]
There are currently no designs for this.  At the moment a featured image is full width with the following page heading:

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/146530/190005875-3f7b315e-4721-4c46-90a9-7be46be18772.png">
<img width="1201" alt="image" src="https://user-images.githubusercontent.com/146530/190006047-f07335e9-3ce4-4c66-adad-5b35ba66ba49.png">

We need some additional direction for pages.

**Comment by henriqueiamarino** [comment]
Single post design on Figma, as shown below with comments block.

<img width="1440" alt="decibel_Single" src="https://user-images.githubusercontent.com/103748085/190599830-91c6ee63-1ca9-48a3-9ce2-0c4250c267e6.png">
