### ISSUE TITLE
Loudness: Templates: Page

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6558]
Just as Single (posts?) needs design direction, so too does this page.  They currently look the same.  

https://github.com/Automattic/themes/issues/6557

**Comment by henriqueiamarino** [comment]
@pbking I gathered some elements and patterns from the file and defined a Page design in Figma. Also created a Single, slightly different.

<img width="1440" alt="decibel_Page" src="https://user-images.githubusercontent.com/103748085/190599350-f98de915-71fa-40ba-b995-ebccbd69de4f.png">

**Comment by pbking** [comment]
Looks like a super-simple page template.

The patterns we'll make to go into a page in the demo (in another issue), and the template we can just copy the existing `single.html` and pull out the comments portion and call it done.
