### ISSUE TITLE
Design improvement suggestions to Block Canvas

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#6592]
In order to improve Block Canvas as a starting point to build themes, there are a few improvements I suggest.

The first one is the theme links states. Here's a comparison between Blockbase and Block Canvas' hover states, Blockbase being what I consider to be ideal:

**Blockbase:**

https://user-images.githubusercontent.com/65220155/191051561-3ce6e70f-196b-4c27-914a-b1e76e189ded.mp4

**Block Canvas:**

https://user-images.githubusercontent.com/65220155/191051601-85b3232a-5749-49f5-8a76-7fdb8511ee33.mp4

That said, it would be nice if links in Block Canvas followed the described behaviour:
- **Post titles and post date:** no underline on default, underline on hover
- **Site title and navigation links:** no underline on default, underline on hover
- **Links within paragraphs, post tags and categories:** underline on default, no underline on hover

Additionally:
- in Post Meta I suggest **replacing "Post Author" with "Post Author Name"**: that link should not be underlined on default, but on hover

I've created a [Figma file](https://www.figma.com/file/W7jjWeU2cstPfJ36Knjbu2/Block-Canvas?node-id=0%3A1) with the templates to show a visual example.

[This theme](https://andersnoren.se/themes/beaumont/) is the reference for link states and also the underline thickness.

**Comment by madhusudhand** [comment]
@beafialho In addition to links, do you want the theme to have all the updates from figma such as botton styles, spacing, colors etc...?

**Comment by beafialho** [comment]
@madhusudhand yes, that would be great!
