### ISSUE TITLE
Loudness: Instructors pattern not rendering correctly

### ISSUE THREAD

**Issue by mikachan** [Automattic/themes#6653]
### Quick summary

The Instructors pattern in Loudness doesn't seem to render correctly on wpcom. The preview looks normal, but the actual pattern looks strange.

![image](https://user-images.githubusercontent.com/1645628/193347311-65ce280c-0f15-4d34-b9c3-088f9c982222.png)

![image](https://user-images.githubusercontent.com/1645628/193347331-9d3166fa-27bd-441d-a757-4e6192fa3e5e.png)

### Steps to reproduce

n/a

### What you expected to happen

n/a

### What actually happened

n/a

### Reproducibility

Consistent

**Comment by pbking** [comment]
This seems to have been caused by missing alignment classes which were added/corrected after Gutenberg 14.0

With Gutenberg 14.2 this is no longer happening and this can be closed.
