### ISSUE TITLE
P2 Classic: Comments not expanding on front page

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#666]
## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]
1. Activate P2-Classic on a self-hosted installation. Ensure comments are enabled and front page displays latest posts.
2. Try to comment on a post from the front page

## Result

Clicking Reply on a post or existing comment causes the post to reload in the single-post view.

Attempting to comment while logged in as a user on the site also generates a "could not connect to WordPress" error - I only see it using Firefox, though:

![P2](https://user-images.githubusercontent.com/11873759/54211848-a7d06800-44ea-11e9-8c09-208cd3007c6c.gif)

It does not appear to matter whether or not Jetpack is connected - I get the same result regardless.

## Expected

To be able to comment on the front page, and comments to update live without a page reload.

* User report: https://wordpress.org/support/topic/comment-form-not-work-in-wordpress-5-1/

User created a test site for us to see the issue in action: http://119.27.180.212/

But I was also able to confirm on a Pressable-hosted test site.

**Comment by cathymcbride** [comment]
retired theme. Closing...
