### ISSUE TITLE
Dara: WooCommerce Products per row, Rows per page settings missing in the Customizer

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#67]
I'm not able to set **Product per row** or **Rows per page** with Dara theme in **Customizer > WooCommerce > Product Catalog**:

![Screenshot](http://cld.wthms.co/OBwUPr+)
Screenshot: http://cld.wthms.co/OBwUPr

With default themes like Storefront or 2017 these settings show just fine:

![Screenshot](http://cld.wthms.co/VzoQph+)
Screenshot: http://cld.wthms.co/VzoQph

**Comment by alaczek** [comment]
cc @madeincosmos since you initially reported this issue. Is there a related support ticket/chat/forum thread?

**Comment by danieldudzic** [comment]
@alaczek Dara still uses pre-[WC 3.3](https://woocommerce.wordpress.com/2017/12/09/wc-3-3-will-look-great-on-all-the-themes/) legacy filters for columns and rows and needs to be updated to support the new Customizer options.

I suspect this might also be the case for other themes.

I can update Dara tomorrow (or early next week) and double check our other WooCommerce compatible themes, if that's ok with you.

**Comment by alaczek** [comment]
Sure, go for it! Thanks!

**Comment by madeincosmos** [comment]
Thanks @alaczek! This was reported in 1066903-zen
