### ISSUE TITLE
Pixl: font size differences in environments

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#6724]
Font sizes are larger on wpcom then they are self-hosted:

wpcom | self-hosted 
--- | ---
![wpcom](https://user-images.githubusercontent.com/5375500/201716520-fb2fc457-0009-4654-8d9a-7712531b8c36.png) | ![self-hosted](https://user-images.githubusercontent.com/5375500/201716556-e73a1efc-2759-431c-8fe4-6adf6f5f412a.png)

**Comment by madhusudhand** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/45536

**Comment by iamtakashi** [comment]
@madhusudhand Is #6727 also caused by the same reason?

**Comment by jffng** [comment]
Thanks @madhusudhand! Yes @iamtakashi it looks to be the same issue. We'll keep these open until the change lands on wpcom, which should be next week.

**Comment by madhusudhand** [comment]
@iamtakashi changes Landed. Pixl is now working good on dotcom. Can you verify other issues.

**Comment by iamtakashi** [comment]
@madhusudhand Yes, I can confirm the issue with Masu is resolved 👍
