### ISSUE TITLE
Rebalance: Wrong icon displaying for Pinterest in Social Media Menu

### ISSUE THREAD

**Issue by g47in** [Automattic/themes#673]
![PintresticonRebalance](https://user-images.githubusercontent.com/8768481/54353350-74154f80-465c-11e9-82d5-ec1cd5709461.png)

**Comment by torres126** [comment]
That chain logo looks like the default fallback logo by Jetpack with the social menu, and therefore not a theme issue, but is this just not a typo for Pinterest (https://pinterest.com) instead of "pintrest"?

**Comment by g47in** [comment]
It looks like that was the issue on my side. Thank you for your help. Sorry if I created any confusion.

**Comment by g47in** [comment]
The only thing is that Pinterest seems to be spelt correctly on this site.
![Be_creative__add_flavour_and_experiment__Ink_Sugar_Spice_is_full_of_recipes__skills_help__tips__advice_and_information__inspiration_and_crafts_for_a_beautiful_handmade_life_and_huawei__com_Info](https://user-images.githubusercontent.com/8768481/54384948-202b5a80-469e-11e9-9c8d-094d7b23650a.png)

**Comment by torres126** [comment]
I'm assuming that's because of not having a `.com` TLD.

@jeherve I thought that this was fixed last Jetpack release in Automattic/jetpack#11252, but it isn't on WordPress.com. Anything else that needs to be done? FWIW, Discord support also isn't added on WordPress.com.

**Comment by mdawaffe** [comment]
This is a theme issue, not a Jetpack/WordPress.com issue:

https://github.com/Automattic/themes/blob/66b2267ea74887b77f3876be8f7cc74958e5b468/rebalance/style.css#L1034-L1036

**Comment by torres126** [comment]
Ah, nice spot, thanks! Looks like this affects several themes in this repo which is why I could reproduce on several themes, not just Rebalance, I'll get a PR for them all soon.

**Comment by mdawaffe** [comment]
Many inherit from 2019, which also has the problem. Thanks for taking a look!
