### ISSUE TITLE
Eliminate __unstableLocation

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6738]
Some themes (namely Blockbase and children) leverage the `__unstableLocation` attribute of the navigation block.

This was initially done when Blockbase was considered a "universal" theme which allowed people to leverage the customizer to edit navigation.  Blockbase has left its universal roots behind and needs to transition to be a simpler parent block theme.  This has already happened with colors and fonts and now needs to happen with navigation.

The difficulty is that any user who is leveraging their classically defined menus would lose them if the attribute were simply removed.  So some kind of migration will be necessary to transition users from using `__unstableLocation` to the native usage of the navigation block.

**Comment by vcanales** [comment]
Now that #6759 and https://github.com/WordPress/gutenberg/pull/46415 are done, I'll be removing the usage of `__unstableLocation` from our themes to mitigate any breakage.
