### ISSUE TITLE
Hive: Gallery post automatic featured image from gallery content

### ISSUE THREAD

**Issue by iuravic** [Automattic/themes#674]
The user tried to create and publish a new Gallery post format. As found in the theme docs https://wordpress.com/theme/hive/setup:
_"The Gallery post format features the same elements as standard posts, except that the featured image is replaced with the first gallery image found in the post content. Learn more about working with Galleries and Slideshows."_,
they were expecting have the first gallery image found in the post content automatically used as the featured image for the post, and have that featured image visible on the front page, with the post excerpt.

However, the Gallery post type doesn't seem to push a gallery image from the post, to be seen as a featured image on the front page.

Worked live on the user's site:
- Site: https://hundaholmi.wordpress.com/
- SA: https://wordpress.com/wp-admin/network/admin.php?page=store-admin&action=search&username=hundaholmi

## Steps to replicate
- created a new post;
- entered title, inserted a gallery (with 3 test images);
- in the left options sidebar selected: + Gallery type, + Stick to front page, + added the "featured" tag;
- published the post.

Screenshot of the steps to replicate: https://pasteboard.co/I5oVCo9.jpg

Environment info:
- Browser: Firefox 65.0.2 Quantum
- OS: Debian 8

## Result

The post appeared on the front page, but there was no featured image:
https://pasteboard.co/I5oXLtT.jpg

## Expected

Expected to have the first image from the gallery, automatically used as the featured image on the post excerpt on the front page.

* User report: #11192005-hc
* Follow-up ticket: #1879312-zd

**Comment by alaczek** [comment]
Hi! We have a separate system for reporting bugs in premium theme, so I moved this ticket to 2654-wpcom-premium-themes.
