### ISSUE TITLE
[Bug]: Meraki download link in showcase doesn't tell self-hosters they need blockbase-wpcom

### ISSUE THREAD

**Issue by dsas** [Automattic/themes#6741]
### Steps to reproduce

1. Go to WordPress.com/theme/meraki
2. Follow the download links
3. Upload the zip to your self-hosted blog
4. Get a message saying the "blockbase-wpcom" parent theme is missing so the theme won't work

For bonus confusion, install blockbase from wporg which won't solve the problem.

### What you expected to happen

The download box to say I need to install blockbase-wpcom first and point me to where I can get it from. Kind of like Hever does:
![image](https://user-images.githubusercontent.com/93301/203306386-b4727337-f3a7-4ce9-9033-7ba7e7779b7b.png)

though that can have its own issues (p8HJWS-R1-p2)

### What actually happened

.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Download blockbase-wpcom from https://wordpress.com/theme/blockbase and install that before activating Meraki

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/73951
