### ISSUE TITLE
Sophisticated Business: menu in mobile version didn't suit the preferences

### ISSUE THREAD

**Issue by retnonindya** [Automattic/themes#676]
## Steps to replicate

![Datanist](https://cldup.com/OlNU8jjDfK.jpeg)

![Datanist](https://cldup.com/laFYBqrYju.jpeg)

iPhone 6S, Chrome 73.0.3683.68

## Result

Two menu items appeared with other two menu items (all of them are parent menu items) hidden. When the three dots (. . .) icon clicked, overlay module appeared with the rest of menu items but the texts are unclear and overlapped with the other menu items.

## Expected

The menu in mobile version will appear as dropdown/hamburger menu

* User report: #11227252-hc
* Follow-up ticket: #1880704-zd

**Comment by danieldudzic** [comment]
Sophisticated Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Rivington: https://wordpress.com/theme/rivington
