### ISSUE TITLE
[Bug]: Block Canvas: Comment pattern include in page template should be self-closing

### ISSUE THREAD

**Issue by bhdd** [Automattic/themes#6763]
The comments pattern include in the page template isn't self-closing currently, and should probably be.
https://github.com/Automattic/themes/blob/e5e5935bf6b2f927828ad3a98c8c0561787f653a/block-canvas/templates/page.html#L22

Should probably be:
```
<!-- wp:pattern {"slug":"block-canvas/comments"} /-->
```

Currently, it creates extra divs wrapped around the footer.

**Comment by mikachan** [comment]
Good spot, thanks!
