### ISSUE TITLE
Blockbase: Defer to Jetpack Fonts

### ISSUE THREAD

**Issue by pbking** [Automattic/themes#6765]
Recently wpcom has started proxying fonts from google fonts API.  This may be enough to consider using Jetpack Fonts (which supplies fonts from there) to be used in Blockbase themes.

To do so Blockbase will need to be changed to check for Jetpack Fonts Module and, if active, not attempt to supply it's own font collection.

Currently the font collection is supplied in theme.json though and that is processed automatically so this may also require Blockbase to supply those fonts in a more sophisticated way (as a Font Provider as was originally intended).  It may be that the technical blockers that originally prevented that have since been dealt with (I can't recall offhand what exactly those where).

This task is mostly a prompt to dig into this to see if this is possible.

**Comment by jffng** [comment]
Re-opening in case we want to revisit the approach.

**Comment by simison** [comment]
Question: what happens without all the disabling/enabling/checking functionality that the theme had before and the new PRs, and if fonts are simply defined in `theme.json` and no PHP? Would fonts appear as duplicates, would something break, or would they work fine along side Jetpack? Would either theme or plugin take a presedence when there's identical font name?

**Comment by pbking** [comment]
This is addressed in #6831

Closing
