### ISSUE TITLE
Retire Themes

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#6779]
Retire the following themes from dotcom

These themes should be repurposed later as a V2 with a new homepage template structure:
- [x] Farrow ( #6840 )
- [x] Heiwa ( #6838 )
- [x] Dorna ( #6836 )
- [x] Appleton ( #6835 )
- [x] Meraki ( #6843 )
- [x] Antonia ( #6834 )
- [x] Barnett ( #6833 )
- [x] Hari ( #6844 )

Retire without revisiting
- [x] Calvin
- [x] Ames

**Comment by ianstewart** [comment]
> These themes should be repurposed later as a V2 with a new homepage template structure:

See https://github.com/Automattic/themes/issues/6758

**Comment by alaczek** [comment]
I _think_ the following themes also suffer from the same issue, and should at least be looked at:

Premium
* Skivers (no replacement necessary)
* Baxter (no replacement necessary)

Free:
* Barnett
* Baker
* Jackson
* Kinglsey
* Bantry
* Bradford

(happy to check these myself, but I need to know what exactly am I looking for in the code)

**Comment by ianstewart** [comment]
I added Barnett to the list above after testing it. Here's what to look after selecting a theme in the the design picker that appears when creating a site from wp.com/start.

**A homepage set to a static page**

![image](https://user-images.githubusercontent.com/545779/211093315-600599b4-6538-48ed-8fda-00884a91db11.png)

![image](https://user-images.githubusercontent.com/545779/211093413-cd413ace-2966-4d1e-a321-88ce5da4af7e.png)

**A non-standard home page template**

![image](https://user-images.githubusercontent.com/545779/211093535-8428635d-2e00-48a6-86a6-25c7e22a6012.png)

**What should it look like?**

For future replacement, better discussed elsewhere, but just noted for comparison, this theme should have its homepage pattern set in the home.html or front-page.html template. No reading settings should be set by Headstart annotations.

**Comment by autumnfjeld** [comment]
Quadrat and Hari should be added to  the list because p1673620117224879/1673581702.323439-slack-C048CUFRGFQ
[Retiring and replacing non-standard block themes]  pNEWy-fQg-p2

**Comment by pbking** [comment]
> Quadrat [...] should be added to the list

Quadrat is in a different situation than the rest because unlike all the other themes on this list it is in the WordPress.org theme repository.  Versioning that to change the default content structure would be a lot more involved.  If we decide that we definitely need to do that with Quadrat I would at least like to disconnect that from these other themes to minimize the trouble of getting this particular item wrapped up.

**Comment by pbking** [comment]
These v2 themes might be good candidates for the "theme launch automation pipeline"

There doesn't seem to be much traction of getting them shipped right now though, so I'm moving this to "ToDo" for now.

**Comment by taipeicoder** [comment]
I've checked-off the themes that have been delisted, according to pekYwv-2d9-p2

**Comment by jeffikus** [comment]
Thanks @taipeicoder - marking as closed.
