### ISSUE TITLE
[Bug]: Pendant's hero image overflows in Site Editor when browsing style variations

### ISSUE THREAD

**Issue by fushar** [Automattic/themes#6783]
### Quick summary

In the Site Editor, when we open the Global Styles sidebar and click "Browse styles", the site will be previewed in a smaller width. On Pendant theme, however, the hero image will overflow to the right beyond the document width.

### Steps to reproduce

1. Activate Pendant.
2. Open Site Editor.
3. Open the Global Styles sidebar on the right.
4. Click Browse styles.

### What you expected to happen

The hero image still fits within the page width, similar to the live site

![image](https://user-images.githubusercontent.com/1525580/208080321-3ae05653-e049-4cfb-83e2-44495f8278f5.png)

### What actually happened

The hero image overflows to the right.

![image](https://user-images.githubusercontent.com/1525580/208080399-a33a78c7-4c79-46cc-877b-4625e63db377.png)

### Browser

Google Chrome/Chromium

### Context

Exploratory testing

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

None

**Comment by mikachan** [comment]
Reported this upstream: https://github.com/WordPress/gutenberg/issues/46612
