### ISSUE TITLE
Rebalance: posts on front page are overlapping

### ISSUE THREAD

**Issue by senff** [Automattic/themes#679]
## Steps to replicate
With the front page set to show recent blog posts, the posts intermittently overlap. Usually this doesn't happen on the first page, but only on pages that appear after you select "Older Posts".

## Result
See screenshot: https://cld.wthms.co/dd94ni

## Expected
Posts should be sorted properly.

## Interactions
* User report: #11256675-HC
* Follow-up ticket: #1882306-ZD

**Comment by torres126** [comment]
There's a report in this thread with a lot of information and screenshots: https://en.forums.wordpress.com/topic/problem-with-how-older-posts-show-on-mobile-for-rebalance-theme/

![img_0697](https://user-images.githubusercontent.com/43215253/54477558-f0e12e80-4800-11e9-816d-4f1d4d6cff65.png)

This is also an issue on the demo and it seems that any pre-iPhone 8s are facing it.

**Comment by gwensmithx** [comment]
I have another report of this here: #2318584-ZD. On Safari on iPhone X user is seeing overlap of blog posts images intermittently.

**Comment by fresatomica** [comment]
Another report here: https://en.forums.wordpress.com/topic/overlaped-images-and-text/

**Comment by gwensmithx** [comment]
Although there hasn't been any recent reports of this, this still appears to be an issue. I just checked on my customer's site and I'm still seeing overlapping posts. Are we able to get a status update on this?

**Comment by RealCarFax** [comment]
Another report in #22517847-hc. A work-around I found was to have the user add some text to the post, add a more block, and *then* add the Medium embed that they wanted there. That helped.

**Comment by carladoria** [comment]
also reported on #353702-hc 
Their latest posts were set to show "full post", changing to "excerpts" worked for them

**Comment by marcuswisecaesar** [comment]
Another report at #24255132-hc 

The user is ok with rolling with the delay and jumble for now, but it would be nice to see if we can make some headway on this.

**Comment by adelineyaw** [comment]
Another report #20195897-hc

Changing the blog display (in Customizer > Content Options) from 'full post' to 'excerpts' didn't work for the user and the overlapping still occurs.

**Comment by tanjoymor** [comment]
Another report here: #27883919-hc

**Comment by aisajib** [comment]
Just ahead of this bug's two-year anniversary tomorrow, I just got a report in #19684679-hc :(

**Comment by ktyfuller604** [comment]
Another report of this issue here #3987263-zen

**Comment by kriskorn** [comment]
Another report: #4215746-zen

**Comment by pdharris** [comment]
Another report: #4252254-zen

**Comment by aleone89** [comment]
Another report in the theme support  here:  https://wordpress.org/support/topic/homepage-entry-overlap-lazy-loading-off/

**Comment by jartes** [comment]
Another one on 32263220-hc

They already have the content options to show the except, and they were experiencing the issue.

**Comment by rickmgithub** [comment]
#4909768-zen

**Comment by eduardozulian** [comment]
Still happening. The workaround is to disable lazy load.

Report: 4948397-hc

**Comment by kelasante** [comment]
Another report in 35760048-hc. Disabling Lazy load fixed the issue.

**Comment by Robertght** [comment]
I tried to replicate this on Simple and Atomic sites, but the most consistent behavior I got was on Atomic sites.

I can confirm disabling the Lazy Loading for images helped.

Rebalance is currently active on at least 308,940 sites.

**Comment by thekingsprojects** [comment]
Another report here: 37009575-hc (Atomic)

Turning off lazy load helped.
