### ISSUE TITLE
Bibimbap: Launch tasks

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6801]
## Pre-Launch tasks for Bibimbap

- [x] Update description
- [x] Update readme.txt
- [x] Add image credits in readme
- [x] Screenshot for showcase entry
- [x] Create Showcase entry
- [x] Create demo site - https://bibimbapdemo.wordpress.com/
- [x] Create headstart annotation

## Post-Launch tasks

- [x] Update dotOrg deployment list - done in #6876

**Comment by madhusudhand** [comment]
@beafialho Thanks for your work on the theme. Changes are now merged here #6753
Could you add the details here related to above tasks.

**Comment by beafialho** [comment]
Thanks @madhusudhand the description and theme screenshot are in the theme's folder. Here is the other info:

**Image credits:** (I believe these are the only ones)

https://www.foodiesfeed.com/free-food-photo/korean-meal-from-above/
https://www.foodiesfeed.com/free-food-photo/korean-bibimbap-in-yamyam-berlin/

**Screenshot for showcase entry:**
![bibimbap_showcase](https://user-images.githubusercontent.com/65220155/210777281-32b8a85f-e849-4e47-ba0f-941c8210ba80.png)

**Comment by jeffikus** [comment]
@beafialho @madhusudhand any blockers to creating the demo site and getting this shipped on dotcom? Also, we now have the default headstart annotation pNEWy-g5E-p2 so @beafialho do you want a more specific annotation than the default ones? 

Changes are here D100234-code and D100602-code

**Comment by madhusudhand** [comment]
Created a demo site here https://bibimbapdemo.wordpress.com/
@beafialho can you review and update if required.

@jeffikus I will have to test how site looks with default headstart annotation. 
I guess we still need a custom headstart because this has a custom homepage template. Site would look different otherwise.
What do you think?

**Comment by jeffikus** [comment]
@madhusudhand are you talking about this file as the custom template? https://github.com/Automattic/themes/blob/trunk/bibimbap/templates/wp-custom-template-home.html 

I can help test the default headstart.

**Comment by ianstewart** [comment]
This template should be home or front-page:

![image](https://user-images.githubusercontent.com/545779/220946448-62f6ecdd-8f12-45e5-83b8-ba854937bf8e.png)

**Comment by madhusudhand** [comment]
> are you talking about this file as the custom template?

@jeffikus Yes.

> This template should be home or front-page:

Spun up a PR here: #6882

**Comment by jeffikus** [comment]
@madhusudhand what remains here in order to launch? Just the headstart?

**Comment by ianstewart** [comment]
@jeffikus looking at https://github.com/Automattic/themes/blob/trunk/bibimbap/templates/home.html I'd say it doesn't need headstart annotations.

**Comment by jeffikus** [comment]
Looks like everything is done here. Can we close this out @madhusudhand ?

**Comment by madhusudhand** [comment]
Yes. Closing this now.
