### ISSUE TITLE
[Bug]: Franklin theme - social icon block

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/themes#6817]
### Quick summary

The last icon of the social icon block is displayed lower than the rest of the icons. 
Screenshot of the issue:
https://d.pr/i/qTfH42

I was able to reproduce the issue on my test site.

### Steps to reproduce

1. Add social icon block.
2. Add multiple icons and save the changes

### What you expected to happen

All icons to be displayed in one line

### What actually happened

The last icon of the social icon block is displayed lower than the rest of the icons. 

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by maciejpilarski** [comment]
Ticket ZD5849776

**Comment by eduardozulian** [comment]
Got a similar case in 6206989-zen in which the first icon, for some reason, was taller (and not respecting the rounded shape) than others.

<img width="372" alt="Captura de Tela 2023-04-16 às 10 26 42" src="https://user-images.githubusercontent.com/1136160/232314576-23eb0932-2988-4815-a5bd-aaeb249b48f6.png">

The following CSS workaround should fix both scenarios:

```
/* Social Block Widget: Remove bottom padding and margin -- 6206989-zen (EZ) */
.widget .wp-block-social-links li {
  padding-bottom: 0;
  margin: 0;
}
```
