### ISSUE TITLE
Canard: Submenu getting overlapped/ hidden behind posts.

### ISSUE THREAD

**Issue by galakhyati** [Automattic/themes#682]
## Steps to replicate

1. Activate Canard theme.
2. Set the homepage to show the latest posts. No featured post content.
3. Add the menus which span most part of the menu such that it comes above post's featured image thumbnail area and add submenus to the first menu.
4. Make sure the first post has a featured image added to the post.

## Result

The submenu will be hidden behind the featured image since the z-index of the menu is lower than that of the featured image.

## Expected

Expected all the submenus to be displayed correctly. Here is a screenshot showing how it appeared on my test site as well as on the user's site.:

Test site: https://cloudup.com/cVq5yHe3g6I
User's site: https://cld.wthms.co/0vUsct

Since the user is on the Personal plan, this cannot be fixed using custom CSS. They require a fix added to the theme.

* Ticket #1886227-zd
User's site: ff-untergralla.at

**Comment by sixhours** [comment]
#716 was reverted due to reports in #3846, this needs a new solution.
