### ISSUE TITLE
[Bug]: Remove unnecessary items from Lettre headstart file.

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#6828]
Lettre headstart is adding several posts and pages that are no necessary. Let's remove them, the list is below.

**Comment by ianstewart** [comment]
I don't think we need to create any pages by default. If we wanted to create just one, perhaps just the Archive page.

**Comment by jeffikus** [comment]
@ianstewart so remove all the pages, so that when you activate it loads the homepage through the template and then the headstart loads the archive page?

**Comment by jeffikus** [comment]
@ianstewart thanks, I'm busy wrapping this up, for the Archive page, it shows a header, search box input, and list of posts. Those posts are generated by headstart. We could leave 1-3 posts as examples as is, or remove all.

<img width="1280" alt="Screenshot 2023-01-20 at 16 59 07" src="https://user-images.githubusercontent.com/937325/213813378-adace125-8d7d-44c1-aa57-717ded1bbfa1.png">

**Comment by ianstewart** [comment]
I have a strong opinion that we remove the Blood Wedding post. Leaving the Impresiones post would be OK for now, I think. Just so there's 1 thing there. (In some later iteration we need a better system for creating (and not creating) default posts across the board on WP.com.)

**Comment by jeffikus** [comment]
@ianstewart Ready for review: D98939-code
