### ISSUE TITLE
[Bug]: Blockbase: Fonts are not loaded on WP.com Personal plans

### ISSUE THREAD

**Issue by BogdanUngureanu** [Automattic/themes#6832]
### Quick summary

On WP.com Personal plans, the custom fonts loaded by Blockbase are not registered for fonts defined at a block level.

I believe this is caused because WP.com Personal plans have the custom CSS disabled (since it's only available to Premium or up plans).

After I debugged a bit the custom font implementation I believe the problem is from `inc/fonts/custom-fonts.php:193` (the function `enqueue_block_fonts`).

Based on my tests, it looks like `wp_add_inline_style( 'blockbase_font_faces', $font_css )` is indeed called on Personal plans, however the CSS is not applied to the site.

One possible solution would be to replicate the implementation from [Jetpack](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/google-fonts-provider/src/introspectors/class-blocks.php#L24)

Also, since I'm seeing a few PRs related to fonts, maybe it would be a good idea to investigate if we can use the [Jetpack Google fonts provider package](https://github.com/Automattic/jetpack/tree/trunk/projects/packages/google-fonts-provider), since the library can be used as a standalone library (since it doesn't have any Jetpack dependencies). 

### Steps to reproduce

1. Get a site with a WP.com Personal plan
2. Install a Blockbase theme
3. Go to Site editor
4. Check the font on a block (e.g. paragraph) and save the post
5. Go to the front-end and notice that the font isn't loaded

### What you expected to happen

The font should be loaded as a network resource and the paragraph should be displayed with that font

### What actually happened

It uses the system font. 

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

### Workaround details

The custom CSS is limited on Personal plans (and of course free sites).

**Comment by BogdanUngureanu** [comment]
cc @pbking since you are currently working on a PR related to fonts :) 

@connorhipps reported it in https://github.com/Automattic/wp-calypso/issues/71641#issuecomment-1402340646 after a user report.

**Comment by cuemarie** [comment]
_This report was found during a recent backlog sweep._

📌 SCRUBBING : RESULT - _Replicated / Could Not Replicate / Uncertain_
- Tested on Personal Plan Simple Site - Could not replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Activated **Zoologist** on my Personal Plan test site, and added text to the Index template with a paragraph block.  Both the default font and a custom chosen font load in the live site as expected:

![Markup on 2023-05-03 at 16:07:08](https://user-images.githubusercontent.com/27249804/236070828-d62f33b5-1712-48fd-b9e7-e39e9804eb9e.png)

![Markup on 2023-05-03 at 16:07:36](https://user-images.githubusercontent.com/27249804/236070887-7ef6d19d-701d-4e44-be9b-5c8d6d6a6e7f.png)

📌 ACTIONS
- Closed as not reproducible (please reopen if the issue reoccurs)
