### ISSUE TITLE
Veni: Unable to Activate Infinite Scroll despite there being no Footer Widgets

### ISSUE THREAD

**Issue by AMcGrady** [Automattic/themes#685]
## Steps to replicate

Activate Veni theme on site.
Make sure there are no Footer Widgets on site.
Go to Settings>Writing and attempt tp enable Infinite Scroll

## Result

Unable to Activate Infinite Scroll. See error:
"Your site has a "footer" widget enabled so buttons will always be used."

## Expected

To be able to activate Infinite Scroll

* User report: [[#11375405-hc]](https://mc.a8c.com/support-stats/happychat/transcript.php?id=11375405)
* Follow-up ticket: [[#1892423-zd]](https://woothemes.zendesk.com/agent/tickets/1892423)

**Comment by alaczek** [comment]
Hi! Veni is a premium theme, so I moved this report to 2663-wpcom-premium-themes
Let us know if you have any questions!
