### ISSUE TITLE
[Bug]: Marl: Changes made to footer template part are not saved on Simple sites

### ISSUE THREAD

**Issue by tellisbethel** [Automattic/themes#6851]
### Quick summary

 Changes made to footer template part are not saved on Simple sites

### Steps to reproduce

1. Select Marl theme on Premium plan site
2. Head to the Site Editor
3. Edit the footer template part and Save changes

### What you expected to happen

Changes should be seen on live site.

### What actually happened

Changes are not seen, and after leaving editor and coming back, saved changes are no longer there.

### Context

5918888-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

### Workaround details

I tried deleting the paragraph block with the footer credit and inserting a new paragraph block, and this appeared to have worked at first on several different test sites. Suddenly, however, things have reverted to only showing the original footer credit, even completely removing the original footer template part.

**Comment by eoinsav** [comment]
I'm experiencing the same thing using the Attar theme

**Comment by tellisbethel** [comment]
Confirming that this was tied to this larger issue which has been resolved: https://github.com/Automattic/wp-calypso/issues/72684
