### ISSUE TITLE
Ixion: Unable to set any tags on pages for featured content

### ISSUE THREAD

**Issue by retnonindya** [Automattic/themes#687]
## Steps to replicate

![ss](https://cldup.com/MBL6y0Rnd4.gif)
Direct link: https://cldup.com/MBL6y0Rnd4.gif

(For some reason, the .gif screenshot won't opened. You can click the direct link provided. I'm so sorry for the inconveniences!)

## Result
"Feature" tag, or any tag, turned into random set of numbers whenever the page is edited and/or updated.

## Expected
The tag stays so it will be reflected in the website -- especially for featured content; especially since it's stated in Ixion's setup page:
> With this theme, you can also tag pages to be displayed as Featured Content, in addition to posts.

https://wordpress.com/theme/ixion

* User report: #11384762-hc
* Follow-up ticket: #1893201-zd

**Comment by torres126** [comment]
This could be Automattic/wp-calypso#31279 instead of an Ixion issue.

**Comment by retnonindya** [comment]
Oh, thank you! Is it okay if I close this issue?

**Comment by arunsathiya** [comment]
Yes, @retnonindya, this can be closed in favor of the other report. 👍🏽
