### ISSUE TITLE
Calm Business: Post Meta Stacking Poorly On Mobile Views

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/themes#688]
## Steps to replicate

![Screenshot_20190320-104051](https://user-images.githubusercontent.com/1473618/54676190-6a7a6480-4b00-11e9-9e43-201c39cef126.png)

1. Activate Calm Business
2. View post with post meta on mobile (Tested with Chrome on Pixel 2)

## Result

The post meta is stacked oddly, taking up too much space.

## Expected

It should be similar to other variations on mobile views.

**Comment by jeffikus** [comment]
PR fix submitted. Thanks for reporting this @davidakennedy !

**Comment by alaczek** [comment]
I assume this can be closed now?
