### ISSUE TITLE
[Bug]: Cannot find Upsidedown theme preview content

### ISSUE THREAD

**Issue by bradhogan** [Automattic/themes#6880]
### Quick summary

It appears most theme authors either do not have content when you preview their theme in the wp directory (just shows the default Hello World post when previewing these themes in a new install).

However, it would appear some theme authors (specifically block themes) are now adding content to a front-page.html file in the theme templates folder so when the theme is previewed, "real" content appears (so the user can see a more live / realistic view of what the theme might look like with content.  This is great.

Unfortunately, having a front-page.html file makes for a confusing UX for the site admin if they set their front page to static and then try to edit their homepage.  They can't. They instead have to edit the front-page.html template.

It appears that your Upsidedown theme has the best of both worlds.  The user can see your preview content when doing the live preview of your theme, but after install, that content is no longer there because you do not have a front-page.html file.

### Steps to reproduce

My question (finally)... how are you achieving this?  i.e. How are you making it so in a brand new wp install a site admin can go to Appearance > Themes, find Upsidedown, click Live Preview and see your sample content (screenshot below), but then once they install the theme, this content is nowhere to be found in the theme files.  Would love some insight into this as I think it's useful for other theme authors to boost their downloads (and just provide a better experience for the site admins in general).

<img width="1515" alt="Screen Shot 2023-02-23 at 7 04 34 PM" src="https://user-images.githubusercontent.com/1781226/221074356-8fad2346-1983-4e53-9544-d18e61de1987.png">

### What you expected to happen

I'd expect to see the preview content in a template file.

### What actually happened

The preview content is nowhere to be found. 

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by carolinan** [comment]
This is the content that is in the database on WordPress.org. It is the same content for all themes. It is themes that do not show this content that are customized.

If you want to **test** it with you own theme locally, you can download the theme preview XML file here:
https://github.com/WPTT/theme-test-data

**Comment by bradhogan** [comment]
Thanks @carolinan
