### ISSUE TITLE
Epic: Optimize WC core theme stylesheets

### ISSUE THREAD

**Issue by that-mike-bal** [Automattic/themes#6886]
### Description

Tsubaki and Tazza, both themes provided in our WP.com plans to WooCommerce merchants for free, are based on the [TT2 stylesheet](https://href.li/?https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/client/legacy/css/twenty-twenty-two.scss) that’s bundled in WooCommerce Core. This stylesheet is enqueued with Twenty Twenty Two is is meant to provide basic WooCommerce support when the TT2 theme is in use. This stylesheet:

- Is not thoroughly optimized to provide a great shopper experience with WooCommerce Core as part of a paid solution-in-a-box like Woo Express. 
- Has not been previously tested and optimized for use with the Extensions bundled in Woo Express plans.
- The objective of this project is to review and improve the TT2 stylesheet to provide a beautiful experience with WooCommerce Core and all Extensions bundled with the current Woo Express plans.

As part of this work we will [set up a shopper experience map](https://wooxdemo.wpcomstaging.com/woo-express-feature-map/) over the coming weeks, covering all Woo Express features provided by Core, as well as Extension features that introduce new store elements.

**Comment by manospsyx** [comment]
Closing this out here as a dedicated PT was used to manage progress and all the moving parts/PRs in different repos. cc @warrendholmes
