### ISSUE TITLE
[Bug]: Zoologist theme inconsistent font size on mobile landscape mode.

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/themes#6927]
### Quick summary

In the mobile landscape mode, fonts with the same size are displayed in different sizes. Please see the examples below:

![IMG_2170](https://user-images.githubusercontent.com/9025643/226437574-4c4198e4-d224-4ba9-b1b0-b6655e9dd9e6.PNG)
![IMG_2169](https://user-images.githubusercontent.com/9025643/226437582-099b0565-4cca-4df2-a84f-94fe85f079d8.PNG)
![IMG_2168](https://user-images.githubusercontent.com/9025643/226437584-8f5ab4a8-2ddb-4395-97bb-d05f37c7300b.PNG)

### Steps to reproduce

1. Visit https://ottodesign.pl/oferta/ on a mobile device in landscape mode.
2. I was able to reproduce the issue on my test site https://yetisquad.cloud/oferta-test/

### What you expected to happen

All fonts to be displayed in the same size.

### What actually happened

Each paragraph font size is different no matter the font size selected in the block settings. 

### Context

ZD-6054610

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by maciejpilarski** [comment]
ZD-6054610

**Comment by ClassicRKR27** [comment]
Just an update - [the user is reporting](6563983-zd-woothemes) that this is happening on the `Blockbase` theme as well as some others so it looks like this is affecting all Site Editor themes. [I can replicate this on my test-site here regardless of which SE theme I try - attempted both `Issue` and `Didone` which are not `Blockbase` themes.](https://blakebays.wpcomstaging.com/landscape-testing/)

**Comment by Robertght** [comment]
I'm unable to replicate this on my end and all font sizes I tried look the same on mobile, landscape or portrait.

Since there are no other reports, I'm assuming this might've been fixed within an editor update so I'm closing it for now, but please re-open if needed.
