### ISSUE TITLE
Paimio: dotCom issues

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6929]
While the theme works as expected in local env, it has the following differences on dotCom

* fontWeight is higher for paragraphs
* search buttons have default border and outline

| Local | dotCom |
| --- | --- |
| <img width="358" alt="image" src="https://user-images.githubusercontent.com/1935113/226640855-50add7a5-2b25-497c-a585-e81fcd534656.png"> | <img width="358" alt="image" src="https://user-images.githubusercontent.com/1935113/226641140-e3bcee97-d83a-4e47-9c24-69ee0b4e7133.png"> |
| <img width="358" alt="image" src="https://user-images.githubusercontent.com/1935113/226641410-1d91c426-cdb4-4e11-911a-2988a8b200d5.png"> | <img width="358" alt="image" src="https://user-images.githubusercontent.com/1935113/226641488-9b04623e-3804-480d-ade0-cbd02143e817.png"> |

**Comment by beafialho** [comment]
> search buttons have default border and outline

Yes, @madhusudhand I was going to comment this one too! Although this seems to be happening in Block Canvas too.
