### ISSUE TITLE
Reblog button doesn't work

### ISSUE THREAD

**Issue by desnum** [Automattic/themes#694]
## Steps to replicate

1. Activate WorldView theme
2. In Sharing > Sharing Buttons, set the Reblog button to display on posts
3. Create a post; publish
4. Check the live post
5. See Reblog button at the bottom

<img width="559" alt="Screen Shot 2019-03-22 at 5 21 23 PM" src="https://user-images.githubusercontent.com/43796228/54853694-f50cc080-4cc6-11e9-824e-4c33b7a25c5d.png">

## Result

Reblog button doesn't function. There is no link set in inspector:

<img width="754" alt="Screen Shot 2019-03-22 at 10 35 57 AM" src="https://user-images.githubusercontent.com/43796228/54853542-90516600-4cc6-11e9-96f3-9a30ff3d3f83.png">

And errors in console:

<img width="363" alt="Screen Shot 2019-03-22 at 10 28 35 AM" src="https://user-images.githubusercontent.com/43796228/54853549-95aeb080-4cc6-11e9-8385-7491c9cebc01.png">

## Expected

Reblog button should reblog post when clicked.

* User report: [#11466978-hc]
* Follow-up ticket: [#1900093-zd]

**Comment by cathymcbride** [comment]
Retired theme. Closing.
