### ISSUE TITLE
[Bug]: Blockbase child themes & incompatible style variations

### ISSUE THREAD

**Issue by dsas** [Automattic/themes#6941]
### Quick summary

Jackson's Charcoal style variation has white background text and Jackson has a white background. This isn't easy to read.

Ruby wine | Charcoal
-------|------
<img width="1125" alt="" src="https://user-images.githubusercontent.com/93301/227045623-cd87591a-a80a-484c-99a8-ecc310b7d446.png"> | <img width="1125" alt="" src="https://user-images.githubusercontent.com/93301/227045820-ff98a0e5-ed44-42e6-8e77-d741567b45cf.png">

There are several more examples of this and similar issues with other blockbase child themes - skivers has the same style variations and they just change a thin button outline.

The style variations don't belong to the individual themes but rather their parent theme - blockbase. The variations were [added](https://github.com/Automattic/themes/pull/6167/commits/4cbb43dc10fd419f5334e0d7a768204a3c9af1dc) and [named](https://github.com/Automattic/themes/pull/6167/commits/d75c385c81f5710c77bf1073dddd8215fe8806a4) in #6167 but only started becoming visible in child theme after WP6.2 was merged to wpcom (see fbhepr%2Skers%2Sjcpbz%2Sjc%2Qvapyhqrf%2Spynff%2Qjc%2Qgurzr%2Qwfba%2Qerfbyire.cuc%3Se%3Qn8028o5p%23685-og & D104877-code for the merge and https://github.com/WordPress/gutenberg/pull/46554 for the initial GB change)

### Steps to reproduce

1. Activate the Jackson theme
2. In the site editor use the GS sidebar to set the style variation to charcoal

### What you expected to happen

To be able to read the text

### What actually happened

Couldn't read the text

### Browser

Mozilla Firefox

### Context

p1680136513400279-slack-C048CUFRGFQ passSY-5Al-p2#comment-11903

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

 * Don't use that style variation
 * Do use it and change the text colour

**Comment by autumnfjeld** [comment]
FYI on this @Automattic/lego . Discussed here https://a8c.slack.com/archives/C029FM1EH/p1680709030792759

**Comment by mmtr** [comment]
Solved in https://github.com/Automattic/themes/pull/6996 + D107265-code + D107818-code.

We added a new `optOutOfParentStyleVariations` GS setting so child themes can opt out of inheriting style variations from the parent theme, and enabled it on some Blockbase child themes (Jackson, Kingsley, Skivers, Varese) that had headstart content with conflicting styles.
