### ISSUE TITLE
iotix: style issues

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6946]
Found following issues in iotix.

Footer needs a closing tag to avoid block asking for recovery.
<img width="488" alt="image" src="https://user-images.githubusercontent.com/1935113/227513912-2b029bb6-1c3a-4e64-b4f9-7fa9886b7c05.png">

It requires Root padding
<img width="427" alt="image" src="https://user-images.githubusercontent.com/1935113/227514086-d6a7ef18-cf27-4131-97de-bd8df7a1d28c.png">

Archive page shows single column, but it is expected to have two columns.
<img width="1288" alt="image" src="https://user-images.githubusercontent.com/1935113/227514739-f4fec453-483a-4a88-a4b3-a85ed06ef085.png">

Search block when inserted in a post vs search template
<img width="408" alt="image" src="https://user-images.githubusercontent.com/1935113/227515021-cf829eb5-7302-4469-b8ba-280b271e476e.png">
<img width="536" alt="image" src="https://user-images.githubusercontent.com/1935113/227515160-670408c5-3c70-445a-84e9-da60a6a132f1.png">

CC: @jffng @beafialho

**Comment by jffng** [comment]
@madhusudhand 

> Archive page shows single column, but it is expected to have two columns.

I see two columns for the archive, do you mean on mobile? Shouldn't it collapse to one on mobile?

<img width="1624" alt="Screenshot 2023-03-28 at 12 22 24 PM" src="https://user-images.githubusercontent.com/5375500/228305508-87192b37-4792-48f1-b105-1a3d8789b345.png">

**Comment by jffng** [comment]
The search block issue is a bug upstream, reported here: https://github.com/WordPress/gutenberg/issues/48253#issuecomment-1487253007
