### ISSUE TITLE
[Theme] Lettre - /wp-admin/site-editor.php just keeps loading.

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/themes#6966]
### Quick summary

Site Editor keeps spinning while loading a blank page until a template is selected.

### Steps to reproduce

1. Install and activate Lettre theme
2. Click **Appearance → Editor**
3. Notice that until you manually select a template, it only shows an empty page that keeps loading.

![image](https://user-images.githubusercontent.com/129587477/229279613-526ce8d4-02f2-42eb-9f34-443e1516dc45.png)

the 

### What you expected to happen

For editor to load homepage unless a template is selected.the the 

### What actually happened

You have to manually select a template for the page to load

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes. Select a template from sidebar.

### Workaround details

You can manually select a template, and then continue working on the Editor without issues.

**Comment by AnjanaV93** [comment]
User reported in 6081846-Zen

**Comment by upwardmomentum84** [comment]
Also replicated this issue using Twenty Twenty Two. Work-around of choosing a template works. I also found setting a static page as the front page instead of "Default" works as well.

**Comment by wiesenhauss** [comment]
The issue appears when using Blank Canvas as well. 42743636-hc
Suggested work-around works for user (and me).

**Comment by d-alleyne** [comment]
Also occurs with the `Varese` theme 6223206-zd-woothemes

**Comment by mgozdis** [comment]
~~Another report here on various themes: 39595815-hc~~ Moved to https://github.com/Automattic/wp-calypso/issues/76105

**Comment by cat-og** [comment]
Another report here with the Pendant theme: 6224553-zd

**Comment by hrn1995** [comment]
same thing happens here: 6225315-zen and 6224849-zen

**Comment by trixxmanaty** [comment]
It's also happening here: 6224773-zen

**Comment by trixxmanaty** [comment]
similar issue here with the Pixl theme: 6225228-zen

**Comment by hrn1995** [comment]
same issue here: 6225245-zen

**Comment by upwardmomentum84** [comment]
Was happening here in their chat with us (this is the follow-up): 6223582-zd-woothemes

Theme: Blank Canvas

It's not happening currently though and the homepage is set to show "Default".

**Comment by trixxmanaty** [comment]
same issue here: 6225046-zen

**Comment by trixxmanaty** [comment]
another one here: 6225531-zen

**Comment by 74MR47** [comment]
The issue appears when using Zoologist, Pendant, and Quadrat White as well. ZD-6225932, ZD-6226084, and ZD-6225804 
Suggested workaround (manually select a template in the sidebar) works for me.

**Comment by cuemarie** [comment]
This appears to be the same as:

-  https://github.com/Automattic/wp-calypso/issues/76105 

which has been escalated for attention here: p1682186205979559-slack-C02FMH4G8

**Comment by hrn1995** [comment]
another issue with these tickets: 
6226040-zen
6226164-zen
6226162-zen
6225903-zen
6225845-zen

**Comment by cuemarie** [comment]
@heroinedarla @74MR47 @trixxmanaty @upwardmomentum84 @cat-og @wiesenhauss @d-alleyne @mgozdis 

Can you please check your customer's domain as well as the console logs they were running into in the editor, to determine if they are actually facing the issue reported here https://github.com/Automattic/wp-calypso/issues/76105?  This report was specific to one theme, and based on the timing I suspect your customers were actually experiencing the other issue:

- If they have the theme Lettre active, and/or **do not** have a custom domain as primary, then this may be the right place to report it.
- If they have a custom domain as primary on a simple site, and see the problem across browsers (bonus points if you can spot that CORS error in the Console), then please share the user interaction on https://github.com/Automattic/wp-calypso/issues/76105 instead, especially if the user is hoping for a reply about it in the future.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Tested the theme Lettre for problems in the site editor, and could not replicate.  This strongly suggests the pile up of issues here very likely are due to https://github.com/Automattic/wp-calypso/issues/76105 instead.

📌 ACTIONS
- Requested author feedback

📌 Message to Author
- @AnjanaV93 Can you also check if your user's details match the description of #76105 instead, and if so, add the user's ticket there?  Thinking this thread may get closed in favor of that one, since Letter does not appear to be causing the issue any longer.  Thanks!

**Comment by geekinthegirl** [comment]
A couple more sites with this issue here: 

6226729-zen
6226135-zen

**Comment by cuemarie** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/76105 since these reports seem to match that issue instead, and the theme Lettre seems to work fine outside of that issue's specifics.

Please report any further interactions on the active issue.
