### ISSUE TITLE
Lettre: nav is not visible on live sites

### ISSUE THREAD

**Issue by crisbusquets** [Automattic/themes#6970]

**Comment by crisbusquets** [comment]
The `nav` tag doesn't appear when checking the site live (but it's visible on the Editor):

![Image](https://user-images.githubusercontent.com/25607244/229489500-ce5975d3-438b-4417-910f-90656a7b0dab.png)

![Image](https://user-images.githubusercontent.com/25607244/229489522-58994f00-8c41-48d5-a153-5096089cc15e.png)

**Comment by ajlende** [comment]
Thanks for opening the issue! There's a fix in progress in https://github.com/WordPress/gutenberg/pull/48698.

For now, if you want to show the menu in the live site, you can work around the problem by creating a new menu with the page list block in the editor.

Select the navigation block. Click the three dots (︙) dropdown. Select "create new menu".

![location of the create new menu button](https://user-images.githubusercontent.com/5129775/229610172-6b5d5b00-4f05-46de-8b2d-6c010bf97445.png)

Then insert a page list block.

![location of the page list block to insert](https://user-images.githubusercontent.com/5129775/229611642-aa6a0f7c-1b03-4425-9177-a787f849a605.png)

Finally, to show the hamburger menu like your screenshot, you can choose to "always" show the overlay menu in the block settings (gear icon).

![location of the always show overlay menu toggle](https://user-images.githubusercontent.com/5129775/229612612-6dddee0a-7a69-4b06-abfd-8d015572eea0.png)

**Comment by draganescu** [comment]
I've open [Fix fallback not rendering](https://github.com/WordPress/gutenberg/pull/49576#top) as the bug fix for this problem. I hope to get it backported to the release happening Wednesday 15.5

**Comment by crisbusquets** [comment]
Thank you @draganescu and @ajlende 🙌🏼

**Comment by simison** [comment]
Works now at WP.com (we run GB v15.7, fix was in GB v15.5):

<img width="1174" alt="image" src="https://github.com/Automattic/themes/assets/87168/9a921c6f-aca4-4327-b02f-9bc4cd01ab0d">

<img width="896" alt="Screenshot 2023-05-09 at 14 39 42" src="https://github.com/Automattic/themes/assets/87168/020788ae-bc9a-4913-a72c-4736b1416d76">
