### ISSUE TITLE
Independent Publisher 2: 0 minutes time stamp on all posts

### ISSUE THREAD

**Issue by rahul020691** [Automattic/themes#699]
## Steps to replicate

1) Activate theme and write 2-3 posts

2) You will see all  show 0 minutes time stamp on the byline

## Result

Like this: https://cld.wthms.co/ODhJAa

* User report: [ #11343684-hc]
* Follow-up ticket: [ #1906000-zd]
User site: https://naprienko.blog/

**Comment by nielslange** [comment]
Issue had been fixed in https://github.com/Automattic/themes/pull/1185
