### ISSUE TITLE
Shoreditch: Unable to completely hide footer credits for lang de-DE

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#7]
Originally reported by @brandonpayton in 4807-wpcom-themes:

## Steps to replicate

1. Start with a site using the Shoreditch theme and a Business plan
2. Switch the site's language to German
3. Go to the Customizer and hide the footer credits

## Result

The footer credit would disappear.

## Expected

The footer credit still reads "von Automattic".

* User's site: ​https://gamefact.eu/

**Comment by erricgunawan** [comment]
I have one case of this from user on #1399079-zen. 

Just thought I mentioned here.

**Comment by aisajib** [comment]
I had this case on another site. 
Reference: #1343579-hc

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
