### ISSUE TITLE
Post Terms: remove underlines and make underlined on hover

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#7048]
Currently in Block Canvas categories and tags are underlined by default. We suggest these links behave like others such as Post Titles as we keep wanting to remove them for every theme.

**Behaviour now**

https://user-images.githubusercontent.com/65220155/235901558-661d8efc-e4b4-46aa-bba6-d5afd8817fd7.mp4

**Intended behaviour**

https://user-images.githubusercontent.com/65220155/235901572-cdb2098c-5de2-4c08-858f-4cf49acfa063.mp4

cc: @iamtakashi @iamarinoh

**Comment by mikachan** [comment]
Makes sense to me! I've opened https://github.com/Automattic/themes/pull/7058 to address this.
