### ISSUE TITLE
Independent Publisher/2: Print only shows up the first page in Edge&IE11

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#705]
## Steps to replicate

Browser: Edge + IE11
1. Write some text on a static page and set it as the front page.
2. Hit the Print button on the page(if enabled under sharing) or CTRL/CMD+P to have a print preview.

## Result 
It should show up only one page, therefore not printing the entire content

## Expected

It should show up multiple pages for more content - as it does in Chrome/Firefox.

* User report: #1907981-zen
  Slack ref: p1553838569029500-slack-C029FM1EH

**Comment by jordesign** [comment]
@Robertght Are you able to check this again when you have a moment? I'd be interested to know if it is still relevant

**Comment by Robertght** [comment]
Thank you for the ping @jordesign ! I can't replicate this anymore. 

Closing.
