### ISSUE TITLE
MC page: implement demo site creation

### ISSUE THREAD

**Issue by vcanales** [Automattic/themes#7051]
Ensure the following features are implemented:

- [ ] site is spun up
- [ ] blue flag to protect
- [ ] theme demo site blog sticker is added
- [ ] author has access as admin

**Comment by vcanales** [comment]
Steps that the current CLI tool goes through, in order:
- Validates the theme (checks output of wp_get_theme for errors)
- Checks if the site already exists. If it already exists, try a different name. You can also provide a custom name.
- Creates the site and assigns it to the ThemeDemos user — this step triggers headstart.
- Activate the theme, either the network-activated version, or a locally available one.
- Adds stickers.
  - Sticker format: `add_blog_sticker( 'theme-demo-site', $theme_path, 'themedemos', $new_blog_id ); // Notes should be exactly theme 'dir/slug' value.`
  - `graylist_update( $new_blog_id, 'blue', 'Theme demo site creation', 'themedemos' ); // Set "Blue" protected flag.`
- Updates blog description, sets comment settings.

**Comment by vcanales** [comment]
Diff for this work https://code.a8c.com/D109849

**Comment by vcanales** [comment]
Diff for this work on D109849-code

**Comment by madhusudhand** [comment]
Thanks for working on this. It is working as expected.

Updated the UI to fetch the demosite availability status and merged the diff.

<img width="650" alt="image" src="https://github.com/Automattic/themes/assets/1935113/6f157e7e-33dd-4414-ad48-2e3e261da1be">
