### ISSUE TITLE
Lettre: Fix weird alignment on mobile

### ISSUE THREAD

**Issue by simison** [Automattic/themes#7072]
Via p9Jlb4-787-p2

@crisbusquets wrote:

> Mobile navigation
>
> While the navigation is working on desktop, on mobile it has a weird alignmement —every third element seems to have different CSS (you can check this in [my demo site](https://href.li/?https://cbusquets1989.wordpress.com/)). Or maybe it’s just the navigation elements that are too long.
>
> ![Image](https://github.com/Automattic/themes/assets/87168/bbaffe74-e80b-48fb-a13c-329f65409d1c)
>
> A smaller font-size seems to do the trick, and it’s also easier to read:
>
> ![Image](https://github.com/Automattic/themes/assets/87168/6779f0e5-d2a8-4323-a6b0-4951e7d69065)

**Comment by simison** [comment]
@crisbusquets would this work better?

- Right-aligned the text
- Tightened line-height

<img width="464" alt="Screenshot 2023-06-07 at 14 04 48" src="https://github.com/Automattic/themes/assets/87168/d4f433f2-c6b1-4122-8835-83c51e9c6039">

Another option would be to adjust font-size for mobile, as it was the same as on desktop:

<img width="509" alt="Screenshot 2023-06-07 at 14 06 59" src="https://github.com/Automattic/themes/assets/87168/ba1d97ea-eae5-4947-9ebd-673ecad2e0b9">

Lemme know which you like better or if there's another solution.

**Comment by crisbusquets** [comment]
Thanks for sharing, @simison !

I prefer the second one, it's easier to read.
On mobile devices, we don't need fonts as big as the first screenshot.

**Comment by edanzer** [comment]
This was resolved in https://github.com/Automattic/themes/pull/7167
