### ISSUE TITLE
Professional Business: Not Loading Fonts in Editor

### ISSUE THREAD

**Issue by davidakennedy** [Automattic/themes#708]
## Steps to replicate

1. Activate theme.
2. View in Editor and on Front-End.

## Result

The font in the editor doesn't match the front end. See: https://cloudup.com/cMaUPW6QBK1

## Expected

The fonts should match.

* Reported internally from testing.

**Comment by alaczek** [comment]
I went through all the * Business themes, and found the same issue only in Elegant. I'm on fixing it now.

**Comment by alaczek** [comment]
Fixed.
