### ISSUE TITLE
Lettre: no avatar visible on comments

### ISSUE THREAD

**Issue by simison** [Automattic/themes#7087]
## Steps to replicate

On lettre site ([example post](https://cicerosletters.wordpress.com/2023/04/24/1st-issue/comment-page-1/)), when writing a comment, avatars don't show up.

## Result

<img width="757" alt="Screenshot 2023-05-19 at 12 01 09" src="https://github.com/Automattic/themes/assets/87168/9556c546-c8b6-469d-bd6d-ddf2e6ca1d94">

## Expected

[What you expected to happen.]

* User report: [shortlink to chat/forum thread/ticket, ie 12345-hc]
* Follow-up ticket: [shortlink to ticket, ie 12345-zen]

**Comment by edanzer** [comment]
This was resolved in https://github.com/Automattic/themes/pull/7166
