### ISSUE TITLE
The Twenty Sixteen theme's sub-items or drop-down items of Menu/Navigation do not function on the mobile version.[Bug]: 

### ISSUE THREAD

**Issue by Masterrafique** [Automattic/themes#7091]
### Quick summary

The Primary menu drop-down is not working on the Mobile version of the Twenty Sixteen theme.

### Steps to reproduce

1) Log in to WordPress.com 
2) Install Twenty Sixteen theme
3) Add Menu items and Sub items in the Primary Location of the Menu
Test the website on the Mobile version , sub-menu Items will not be shown.

### What you expected to happen

The mobile version of the website should display menu sub items in the same way as the desktop version.

### What actually happened

When we test the website and click on the icon that shows sub-items, nothing happens.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by john-legg** [comment]
Hey @Masterrafique 👋 Thanks for opening this bug! It looks like it was already reported just recently (https://github.com/Automattic/themes/issues/7092). I'll close this as a duplicate, so please follow the linked issue for more updates 😄 If you feel like this is a different issue, please feel free to reopen.
