### ISSUE TITLE
[Theme] Morden: Featured images and post thumbnails not scaling on Simple Sites

### ISSUE THREAD

**Issue by Neha93517** [Automattic/themes#7099]
_Note - this is slightly different than a similar issue where Varia child themes have enormous images **on mobile devices only**. Please be sure to report your interaction in the appropriate place._

- https://github.com/Automattic/themes/issues/7095

### Quick summary

Theme: Morden
Bug: The featured images and post thumbnails are appearing enlarged and exceed the container width with their actual dimensions.
- Featured images are shown in their original dimensions and not in the dimensions they should have
- I was able to replicate the issue when visited the site. Refreshing the page fixed it for the home page, but not the others. Installed theme on test site and was able to replicate the issue at the private window.

HE Mohammad Tanjid had a look and tested, they were able to replicate the issue as well.

Ticket: 6318148-zen

### Steps to reproduce

1. Installed Modern theme
2. Opened homepage - no issues
3. Opened a post page - Issue found, here's the link to my test site with the issue:
- https://nehaspretestsite.blog/2023/02/01/a-covert-of-coots/

_2023-03-23 updated steps to replicate from triaging:_

1. _Activate Morden on a simple site_
2. _Create a page with the Blog Posts block set to Grid, ensuring it is displaying posts with featured images_
3. _Publish and view page (observe size of .post-thumbnails)_
4. _View a single post page (observe size of featured image in a wide screen browser window)_

### What you expected to happen

The featured image should show in the container width

### What actually happened

Image size exceeding the container

### Impact

One

### Available workarounds?

Yes, easy to implement

### Logs or notes

Informed the user about the bug and suggested below code as a temporary workaround:

.post-thumbnail > img {width:100%;}

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate on my Simple site only, taking the following steps: 

1. Activate Morden
2. Create a page with the Blog Posts block set to Grid, ensuring it is displaying posts with featured images
3. Publish and view page

The result is the Blog Posts post-thumbnails are not restricted properly.  On Single Post pages, the featured images overflow past the max-width of the theme.

Interestingly, this single post page issue does **not** occur on the Morden live demo site, for example: https://mordendemo.wordpress.com/2019/08/08/mont-blanc/

I also activated Varia on the same site, and did not run into the same problem in that parent theme.

#### Screenshots/Recordings

https://github.com/Automattic/wp-calypso/assets/27249804/49e9603d-abfc-478b-b3ca-3986b4eed481


📌 ACTIONS
- Assigned to Themes

**Comment by cuemarie** [comment]
It's possible the following CSS might be impacting things on the single post pages: 

```
footer *, header *, main * {
  max-width: unset;
}
```
From: https://s0.wp.com/wp-content/themes/pub/morden/style.css?m=1684754137h&cssminify=yes


https://github.com/Automattic/themes/assets/27249804/b1e664ac-54b2-42db-82ad-0279cceb0e60

**Comment by AnjanaV93** [comment]
Same issue is seen in the Hever theme. 

Reported in 6325797-zen. Unchecking the max-width rule shared in the previous comment via developer console fixes this. 

```
footer *, header *, main * {
    max-width: inherit;
}
```

Seems to fix this.

**Comment by AnjanaV93** [comment]
Another report in 6320638-zen.

**Comment by rezzap** [comment]
Same issue in the Mayland theme.

Reported in 6326085-zen. The issue here is visible on mobile browser. 
![Screen Recording 2023-05-25 at 12 21 46 pm](https://github.com/Automattic/themes/assets/10325627/a8cb8a40-0697-4070-84c8-5b4581e78c59)

**Comment by afzalpansuvi** [comment]
Reporting a similar issue here: 6323443-HC
Theme: Morden 
The site is on the free plan so no CSS.

**Comment by Neha93517** [comment]
Another report:  6327096-zen 
Theme: Morden

> .post-thumbnail > img {width: 100%;}

The above code didn't work as a solution for the user here: 6318148-zen

New solution provided by HEs here: 6318148-zen

> * restrict post thumbnail widths, gh-77260  */
> .post-thumbnail img {
>     max-width: 100%;
> }
> 
> /* restrict post featured image width, gh-77260  */
> .post .post-thumbnail {
>     max-width: calc(782px - 32px)
> }

**Comment by cuemarie** [comment]
FYI to HEs - If the large image issue is only popping up on Mobile, please do not report on this thread, which is specific to Morden on desktop screens.  Instead see:

- https://github.com/Automattic/themes/issues/7095

**Comment by cuemarie** [comment]
This is one of several recent issues pointing to a very similar CSS problem, so I've escalated here: p1685056613665109-slack-C029FM1EH

**Comment by Neha93517** [comment]
Another report : 6325108-zen
theme Morden
User also mentioned switching to Hever and still having the same issue.

**Comment by mgozdis** [comment]
Another report here: 6318863-zd-woothemes Morden theme.
Simple site so no CSS workaround. Issue seems more prominent on Windows browsers. On Mac, sometimes the images only load incorrectly on initial load and refreshing the page will cause them to load correctly. Refreshing on Windows did not work in Chrome, Edge, or Firefox.

**Comment by afzalpansuvi** [comment]
Adding another ticket: 6328093-HC
Theme: Shawburn 
I was able to replicate the issue on my test site using the Shawburn theme: 
![image](https://github.com/Automattic/themes/assets/37059938/6828cba9-c704-4a2e-a6a6-f57929c9796d)

**Comment by mdtanjid0** [comment]
6321897-zen 
Theme: [Rockfield](https://wordpress.com/theme/rockfield)

**Comment by cardehngeh** [comment]
6317071 - zen
Theme: ALVES

**Comment by christianguerrag** [comment]
Same problem here 6316930-zen Alves theme.
The problem only appears if you are visiting the site while logged out of a WordPress.com account.

Shared CSS to uncheck the max-width.

**Comment by edwinho89** [comment]
6343667-zd-woothemes

**Comment by edwinho89** [comment]
6324399-zd-woothemes
Hever theme

**Comment by cardehngeh** [comment]
6336341-zen
Theme: Stow

**Comment by afzalpansuvi** [comment]
6340756-ZD
Theme: Hever

**Comment by jartes** [comment]
6345676-zd-woothemes
Shawburn theme.

**Comment by cuemarie** [comment]
Reported what seems to be the underlying issue here: 

- https://github.com/Automattic/wp-calypso/issues/77561

Please collect all future interactions on that report

**Comment by Neha93517** [comment]
Another report: 6331565-zen
Theme: Hever

**Comment by mdtanjid0** [comment]
Another one: 6349457-zen

And theme:  [Maywood](https://wordpress.com/theme/maywood)

**Comment by cuemarie** [comment]
A [fix has been deployed](https://github.com/Automattic/wp-calypso/issues/77561#issuecomment-1570917159)

**Comment by cuemarie** [comment]
A batch user reply will be sent out to all interactions noted above this comment. Please refer to main issue https://github.com/Automattic/wp-calypso/issues/77561 for updates on that process.
