### ISSUE TITLE
[Bug]: Multiple themes: replace add_theme_support( 'experimental-link-color' ); wilth add_theme_support( 'link-color' );

### ISSUE THREAD

**Issue by carolinan** [Automattic/themes#7178]
### Quick summary

`add_theme_support( 'experimental-link-color' );` was a theme support that was only partially supported in Gutenberg and  WordPress version 5.8.
In Gutenberg version **16.2**, there will be a doing it wrong message for this theme_support, encouraging switching to the new `add_theme_support( 'link-color' ); `

`add_theme_support( 'link-color' );` is also supported in WordPress version 6.3, without Gutenberg active.
https://core.trac.wordpress.org/ticket/58597

The list of themes that need updating includes Blockbase and Seedlet, Twenty Twenty-One.
https://wpdirectory.net/search/01H4D6TVH4ASH06T7QFN9VC14F

### Steps to reproduce

To see the doing it wrong warning in the admin area, activate the themes and either WordPress 6.3 beta or Gutenberg development version from GitHub.

### What you expected to happen

Using the new theme support will hide the warning.

### What actually happened

--

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by carolinan** [comment]
@mikachan @pbking @jeffikus I just want to highlight this so that it is not missed, Gutenberg 12.6 is planned to be released next week.

**Comment by mikachan** [comment]
Thank you for the nudge, we'll take a look at this ASAP!
