### ISSUE TITLE
Penscratch 2: Button Blocks not changing background color

### ISSUE THREAD

**Issue by kylemcph** [Automattic/themes#723]
## Steps to replicate

1. Start with a WordPress.com Simple **or** Atomic site, Penscratch 2 theme
2. Add a `Button` block to a post or a page
3. Change background color and any color
4. Publish post or page

![](https://cld.wthms.co/WiEhak+)
Direct link to image: https://cld.wthms.co/WiEhak

## Result

On Chrome, Opera, Safari and Vivaldi the button will be displayed with a grey, default, background color.

![](https://cld.wthms.co/7pZkH6+)
Direct link to image: https://cld.wthms.co/7pZkH6

On Firefox, the button will display with the selected color background.

![](https://cld.wthms.co/8TUTMH+)
Direct link to image: https://cld.wthms.co/8TUTMH

## Expected

- The button will change to selected color on all browsers, not just Firefox. 
- Button changed colors for all other themes tried, only Penscratch 2 produces this, from my testing.

![](https://cld.wthms.co/jUD39M+)
Direct link to image: https://cld.wthms.co/jUD39M

* User report: #11950217-hc
* Follow-up ticket: #1949265-zd

**Comment by annbingle** [comment]
Another user reported this here: 16493966-hc
Follow-up ticket: 2477337- zd

**Comment by arcangelini** [comment]
## Tested

This appears to be fixed. Closing.

[![Screenshot](https://d.pr/i/OqcxsF+)](https://d.pr/i/OqcxsF)
