### ISSUE TITLE
Lettre: increase number of posts at "archive" template and show pagination

### ISSUE THREAD

**Issue by simison** [Automattic/themes#7231]
In Lettre theme (created from [newsletter flow](https://wordpress.com/setup/newsletter)), there's an "archive" page by default.

Example: https://hildabastian.wordpress.com/archive/

We should list more pages on the archive, and fix broken pagination. Currently homepage lists all posts, and archive just few.

This was noted at public feedback about the experience https://absolutelymaybe.plos.org/2023/06/22/substack-versus-wordpress-newsletter-first-impressions-and-migration-tips/

**Comment by alaczek** [comment]
> We should list more pages on the archive, and fix broken pagination. Currently homepage lists all posts, and archive just few.

The homepage lists only 3 latest posts (via custom Query block setting), but the archive inherits from the site settings (10 by default), so it seems it's the other way around :) The navigation on archive pages is indeed missing - I'll go and add it.

**Comment by alaczek** [comment]
I added that pagination to the archives pages. I'm going to close this issue, if there's something wasn't addressed feel free to reopen.
