### ISSUE TITLE
Iotix: Style variations not looking accurately

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#7233]
Related to #7161

I just checked WordPress.com's showcase the style variations colors (the cover overlays, boxes, etc) aren't looking like the original zip file. I added a specific colors to the theme palette for the overlays. Can we make sure they look the same?

| **Currently on WordPress.com** | **Original adjustments to the theme** |
| ----- | ----- |
| <img width="1674" alt="Captura de ecrã 2023-07-12, às 16 30 14" src="https://github.com/Automattic/themes/assets/65220155/c918c182-f113-416f-ac2f-2067a275453d"> | <img width="1720" alt="Captura de ecrã 2023-07-12, às 16 34 03" src="https://github.com/Automattic/themes/assets/65220155/e1c103ad-943a-4542-b9df-d74bcb44173b"> |
| <img width="1670" alt="Captura de ecrã 2023-07-12, às 16 29 53" src="https://github.com/Automattic/themes/assets/65220155/855a2f2c-f610-4f21-b962-5bcbbddd95d1"> | <img width="1722" alt="Captura de ecrã 2023-07-12, às 16 33 23" src="https://github.com/Automattic/themes/assets/65220155/1743e7b5-ab66-42ce-a3ab-4a2e2737feac"> |
| <img width="1671" alt="Captura de ecrã 2023-07-12, às 16 30 21" src="https://github.com/Automattic/themes/assets/65220155/116fd452-8122-42e8-b1af-066745add237"> | <img width="1719" alt="Captura de ecrã 2023-07-12, às 16 33 31" src="https://github.com/Automattic/themes/assets/65220155/afff09d9-3d7d-4d99-b731-ecdd50f71772"> |
| <img width="1668" alt="Captura de ecrã 2023-07-12, às 16 30 02" src="https://github.com/Automattic/themes/assets/65220155/204a405f-e736-493d-a83f-f682b99fcc89"> | <img width="1723" alt="Captura de ecrã 2023-07-12, às 16 32 43" src="https://github.com/Automattic/themes/assets/65220155/755be0c6-f0f8-4824-a8e6-9fa0c84c4d4d"> |
| <img width="1671" alt="Captura de ecrã 2023-07-12, às 16 30 29" src="https://github.com/Automattic/themes/assets/65220155/9111a6e9-3a85-4d1c-97f0-fe5ce60304e8"> | <img width="1721" alt="Captura de ecrã 2023-07-12, às 16 32 51" src="https://github.com/Automattic/themes/assets/65220155/e95b84b0-d61a-4322-b5fe-31971fe9abc0"> | 
| <img width="1475" alt="Captura de ecrã 2023-07-12, às 16 44 20" src="https://github.com/Automattic/themes/assets/65220155/336eea20-1fcf-4da3-9da6-17e147b847d7"> | <img width="1722" alt="Captura de ecrã 2023-07-12, às 16 45 21" src="https://github.com/Automattic/themes/assets/65220155/57eb0436-79c8-4e71-8bc9-1821a0ecfe41"> |
| <img width="1474" alt="Captura de ecrã 2023-07-12, às 16 46 11" src="https://github.com/Automattic/themes/assets/65220155/bbd19c4a-c906-4886-ba2d-ea68ebf747fa"> | <img width="1721" alt="Captura de ecrã 2023-07-12, às 16 47 21" src="https://github.com/Automattic/themes/assets/65220155/70446c64-6994-4934-a699-fdb592424d8d"> |
| <img width="1474" alt="Captura de ecrã 2023-07-12, às 16 46 19" src="https://github.com/Automattic/themes/assets/65220155/0b0214a2-d748-4160-9be4-f1213795ac16">  | <img width="1725" alt="Captura de ecrã 2023-07-12, às 16 47 50" src="https://github.com/Automattic/themes/assets/65220155/d15a62ce-0a19-472c-9e04-065a494baa54"> |

**Comment by beafialho** [comment]
Oh, in fact this is also happening in the default variation: https://iotixdemo.wordpress.com

It seems to be the tertiary color not applied in those areas:
<img width="1878" alt="Captura de ecrã 2023-07-12, às 16 55 21" src="https://github.com/Automattic/themes/assets/65220155/62dc07f6-73a4-434b-9e87-d8c78ac61a05">

**Comment by jffng** [comment]
@beafialho did we end up resolving these issues in our triage together, or are there outstanding issues?

**Comment by beafialho** [comment]
No issues @jffng all seems to be working fine now!
