### ISSUE TITLE
Otis: template parts "unavailable" on simple sites

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#7243]
### Quick summary

Otis's header and footer do not appear upon activation on a simple site. In the code editor, the template parts have `"theme":"otis"` (missing) and not `"theme":"pub/otis"` (correct)

### Steps to reproduce

On a simple WordPress.com site, activate Otis and enter the site editor. 

### What you expected to happen

To be able to smoothly edit the theme home template without any issues.

### What actually happened

The header and footer template parts show a "has been deleted or is unavailable" message: 
![image](https://github.com/Automattic/themes/assets/1575367/23c15e19-5033-4525-aa40-880e9bef5c90)

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

@bluefuton surfaced this one, thank you! 

It only seems to happen on Simple sites. 

In the code editor, this is the broken header (and the same code works fine on Atomic): 
`<!-- wp:template-part {"slug":"header","theme":"otis","tagName":"header"} /-->`

And this is the working header: 
`<!-- wp:template-part {"slug":"header","theme":"pub/otis","area":"header"} /-->`

So it looks like the theme slug is just wrong for simple sites specifically :) 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Remove the template parts and manually re-add them, or edit the theme slug in the code editor.

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – **Replicated**
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- Replicated as described on a simple site created today.  Replacing "otis" with "pub/otis" in the code editor worked as a workaround for me as well.

#### Screenshots/Recordings

https://github.com/Automattic/themes/assets/27249804/41befd91-6dab-443c-b15c-9de46d5a05f2

![Markup on 2023-07-17 at 13:58:59](https://github.com/Automattic/themes/assets/27249804/44f85caf-313c-47ad-9346-0b75c4096ffd)

📌 ACTIONS
- Assigned to @Automattic/theam
