### ISSUE TITLE
Lodestar: Image Gallery Display Issue on older model of iPads & iPhones

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#727]
Picking up from [here](https://wpcom-premium-themes.trac.automattic.com/ticket/2675#comment:2):

We encountered two sites with image gallery display issues that only happens on older models of iPad.

Site 1
URL: BONNEYBOMBACH.COM Theme: Lodestar - ​https://wordpress.com/theme/lodestar

iPad Mini 2 iOS 8

Screenshot: ​https://systemsrequests.files.wordpress.com/2019/03/image-from-ios.jpg

* User report: #1953213-zen

**Comment by mikeicode** [comment]
I believe this is not a theme issue but an issue with the Gallery block, I have tested multiple themes and they all have the issue. I opened an issue here for this:

​https://github.com/Automattic/wp-calypso/issues/32864

**Comment by Robertght** [comment]
Closing here in favor of ​Automattic/wp-calypso#32864
