### ISSUE TITLE
Mpho: Hover links don't show default pointer cursor

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#7287]
### Quick summary

Hovered links are not showing the default cursor for me on Chrome and Firefox. Instead, it gives me the regular text selection cursor:

![text](https://github.com/Automattic/themes/assets/1136160/b3e34c03-6e84-47f5-b3e8-4c84ae3986a3)

### Steps to reproduce

1. Go to https://mphodemo.wordpress.com/
2. Hover over any of the links

### What you expected to happen

To see the default pointer cursor.

### What actually happened

We see the text selection cursor instead on Chrome and FF. Safari works fine.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

testing

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

**Comment by cuemarie** [comment]
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on https://mphodemo.wordpress.com/ – Replicated

📌 ACTIONS
- Assigned to @Automattic/theam

**Comment by Aurorum** [comment]
PR in #7479
