### ISSUE TITLE
Varia-Child Themes: Add Mastodon, Threads logos to Social Links Menu

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#7297]
We've got a number of themes based on Varia, using the Social Links Menu, which do not yet support Mastodon as a social icon. Can we add support for Varia-based themes?

I wasn't sure whether this needs to be in Jetpack instead, but adding here for now since these themes are a lot harder to "fix" manually.

From one of our long-time volunteers and highly respected community members:

> Like many here, I have an older theme ([Dalston](https://wordpress.com/theme/dalston)) on my website which displays the [Social Links Menu](https://wordpress.com/support/menus/social-links-menu/) at the top right of every post and page.

> While there’s been a big push to integrate Mastodon [since my previous post here](https://wordpress.com/forums/topic/mastodon-social-link-icon-menu/) (and thank you for that), sadly, there’s still no update of Dalston’s social links menu to include the Mastodon icon. The generic “link” icon displays instead.

> Since Mastodon is now “mainstream,” please retrofit the social links icons to include Mastodon on all our currently available themes.

**Comment by cuemarie** [comment]
📌 ACTIONS
- Feature request kept

**Comment by cuemarie** [comment]
> I wasn't sure whether this needs to be in Jetpack instead, but adding here for now since these themes are a lot harder to "fix" manually.

@jeherve is this something that Jetpack would be able to help with, or should we keep this where it is in the themes repo? Thanks for taking a peek!

**Comment by jeherve** [comment]
Those themes do not use Jetpack's Social Links, they ship with their own version. The SVG must consequently be added to the themes directly, like it was done for Tiktok in #5223. 

I'd recommend taking that opportunity to add the Threads logo as well.

One can pick SVG files from the automattic/social-logos package:
https://github.com/Automattic/social-logos

**Comment by cuemarie** [comment]
Thanks for your insight!  I'll update the title of the request to include Threads too!

**Comment by Aurorum** [comment]
PR in #7478 to sync Varia/Seedlet with the Jetpack Social Menu - that will add Threads, Mastodon, Pinterest, GitHub, Discord and more. :)
