### ISSUE TITLE
Dara: Tiktok block has blockquote formatting

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/themes#7341]
### Quick summary

Tiktok blocks are inserted as `<blockquote>` elements as mentioned in this Gutenberg issue: https://github.com/WordPress/gutenberg/issues/47104

For themes that apply specific styles to blockquotes, these styles also apply to Tiktok blocks specifically. Given the lack of movement on that Gutenberg issue, adding a fix into affected themes might be worth exploring.

### Steps to reproduce

1. Activate Dara theme. 
2. Insert a Tiktok block anywhere on the site.
3. View the site.

### What you expected to happen

The Tiktok embed should appear on its own as a standard embed.

### What actually happened

On Dara, the Tiktok block has extra left padding and a large opening quotation mark as if it's a Quote block. 

### Context

6663892-zd-a8c

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

CSS can act as a workaround for sites with the Premium plan or higher. Those without are forced to either switch themes or embrace the odd appearance.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – **Replicated**
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Atomic (Dara v1.2.10-wpcom) as well as on a self-hosted site with just Gutenberg 16.5.1 active, along with theme Dara v1.2.1

![Markup on 2023-08-31 at 15:29:01](https://github.com/Automattic/themes/assets/27249804/ffb8cdd1-dbf4-4a8e-a3f0-a284c514d05e)

📌 ACTIONS
- Triage complete

**Comment by Aurorum** [comment]
I'd prefer a Core fix for this, to be honest. But just in case that's not going to happen, here's a PR for fixing this specifically in Dara: #7481
