### ISSUE TITLE
Erma: The post editor doesn't have any padding

### ISSUE THREAD

**Issue by dsas** [Automattic/themes#7356]
### Quick summary

The post-editor is annoying to use with Erma as the theme because the post editor doesn't include any margins, it is right at the side of the browser window. On the front-end there is visually some spacing because that's how the template works.

Editor | Front-end
-------|------
 <img width="1631" alt="Screenshot 2023-09-11 at 13 34 08" src="https://github.com/Automattic/themes/assets/93301/a2d658cd-38bb-4d03-aa05-78e76d70b5bc"> | <img width="1631" alt="Screenshot 2023-09-11 at 13 35 05" src="https://github.com/Automattic/themes/assets/93301/ff285605-96e1-4006-93a8-e1ac56967cb6">

Unsure if this is actually an Erma specific bug or a Gutenberg bug 🤔 - what GB is doing might be technically correct - the post block in the template has not spacing or padding, but it doesn't make for a good experience.

### Steps to reproduce

1. Activate the Erma theme
2. Open the post editor

### What you expected to happen

There to be some margin/padding between the edges of the window and the editable part of the screen

### What actually happened

The editor is pushed right up against the window edges

### Browser

Mozilla Firefox

### Context

Forum report - https://wordpress.com/forums/topic/erma-theme/?view=all

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated** 
- Tested on Atomic – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated just as described:

![Markup on 2023-09-11 at 14:05:31](https://github.com/Automattic/themes/assets/27249804/69ed1b55-3c08-4d86-8c48-27b315b398a5)

📌 ACTIONS
- Added to Bug Scrub Planning

**Comment by dsas** [comment]
Discussed in slack: p1694466665879399-slack-C048GFLMBGD

**Comment by beafialho** [comment]
Hopefully #7565 should fix this.

**Comment by alaczek** [comment]
I can confirm this this no longer happening:

![Image](https://github.com/user-attachments/assets/860c6361-696f-4e1f-a69e-4104867d5337)
