### ISSUE TITLE
Multiple themes: Add side paddings to compensate the root paddings  

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#7361]
### Quick summary

The distribution logic for the root paddings has been changed in https://github.com/WordPress/gutenberg/pull/53259. The change makes sense and is good for the long term, but it's "broken" some themes. 

For example, see Ueno. The elements in the header and the footer now bump the screen edge because there are no root paddings around them anymore.

![uenothemedemo wordpress com__demo](https://github.com/Automattic/themes/assets/908665/a3b5ea5f-8c5b-417b-a4af-5da9931aacd4)

This was the PR that fixed the same issue for the Bute theme. https://github.com/Automattic/themes/pull/7347

These are the affected themes we need to fix (thanks to @beafialho and @henriqueiamarino for the help to compile the list.)
- [x] Artly https://artlydemo.wordpress.com/?demo
- [x] Lettre https://lettredemo.wordpress.com/?demo
- [x] Loudness https://loudnessthemedemo.wordpress.com/?demo
- [x] Rainfall https://rainfalldemo.wordpress.com/?demo
- [x] Tú https://tuthemedemo.wordpress.com/?demo
- [x] Ueno https://uenothemedemo.wordpress.com/?demo
- [x] Vetro https://vetrodemo.wordpress.com/?demo

@alaczek Let us know in this issue if you find your themes are also affected.

### Steps to reproduce

* Activate the affected themes to your test site.
* Check templates, template parts, and patterns that are affected

### What you expected to happen

The elements shouldn't bump to the screen edges.

### What actually happened

The elements bump to the screen edges.

**Comment by iamtakashi** [comment]
I'll start with Artly.

**Comment by iamtakashi** [comment]
Artly is done, I'm moving on to Lettre.

**Comment by iamtakashi** [comment]
I'm working on Loudness.

**Comment by iamtakashi** [comment]
Next Rainfall

**Comment by iamtakashi** [comment]
I'm working on Tú.

**Comment by iamtakashi** [comment]
Next Ueno.

**Comment by iamtakashi** [comment]
Last, Vetro!

**Comment by jeffikus** [comment]
Marking as closed. Props @iamtakashi and @pbking

**Comment by alaczek** [comment]
I think this can be closed now.
