### ISSUE TITLE
Covr: Hover links don't show default pointer cursor

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#7381]
### Quick summary

Hovered links are not showing the default cursor for me on Chrome and Firefox. Instead, it gives me the regular text selection cursor:

Similar to #7287

### Steps to reproduce

1. Go to https://covrdemo.wordpress.com/
2. Hover over any of the links

### What you expected to happen

We see the text selection cursor instead on Chrome and FF. Safari works fine.

### What actually happened

Google Chrome/Chromium, Mozilla Firefox shows the generic text cursor.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

testing

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described on both simple (the theme demo site) and on an Atomic test site with Cobr active.

📌 ACTIONS
- Triage complete
- Added to Bug Scrub Planning

**Comment by Aurorum** [comment]
PR in #7479
