### ISSUE TITLE
Creatio: Single template has no comments / comment form

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#7402]
### Quick summary

I wasn't sure whether to file this as an enhancement request or bug, but since Creatio isn't turning off comments for posts, I figure it's probably a bug not to have a comment form at all without editing the template to add one.

### Steps to reproduce

1. Use Creatio on any site
2. View a post that has comments open
3. Notice there is no comment form
4. Edit the Single template
5. Notice there is no comment form there either

### What you expected to happen

I would expect Single to have a comment form for posts, and be able to show comments, without requiring editing

### What actually happened

Users have to add their own comment form and comments. Since there's no simple insertion method for that, it's a bit of work for them to add those in.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Context

User report, volunteer report, this thread: https://wordpress.com/forums/topic/comments-box-15/?

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

User has to build the comments section, adding a form, comments, any needed spacers, etc.

I wouldn't say it's terribly hard for an HE, but it's a fair bit of work for an end user.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – **Replicated**

📌 FINDINGS/SCREENSHOTS/VIDEO
Activating Creatio on a simple site with default Comment settings removes the comments form on the Single Posts template.

https://github.com/Automattic/themes/assets/27249804/b4606e08-2078-48eb-b55b-db4eb99d0724

📌 ACTIONS
- Triaged
- Added to Bug Scrub Planning
- flagged on the Creatio Themedevs p2 post as well, as there's related feedback about this there: pNEWy-h3y-p2#comment-56685

**Comment by pak-cia** [comment]
+1 - 71239160-zen

**Comment by alaczek** [comment]
Hey @supernovia 👋 I have a PR that adds the comment form to single posts. Do you think it should also be added to page template?

**Comment by supernovia** [comment]
> Hey @supernovia 👋 I have a PR that adds the comment form to single posts. Do you think it should also be added to page template?

Apologies for missing this ping @alaczek !  Pages usually have comments off by default, so I doubt it's as important there; someone intent on enabling them could copy a nice comment form layout from single. We have another case with Ron theme, btw!

https://github.com/Automattic/themes/issues/7446

**Comment by alaczek** [comment]
Alright, I merged the PR 👍
