### ISSUE TITLE
Illustratr: Cover block set to full width breaks when fixed background active

### ISSUE THREAD

**Issue by deancroyal** [Automattic/themes#742]
## Steps to replicate
1. Create a new page.
2. Add a Cover block at the top.
3. Insert an image into the Cover block.
4. Set the Cover block to be full width: https://cld.wthms.co/tUGyvP
5. Turn Fixed Background on for the Cover block within Cover Settings: https://cld.wthms.co/rpZPE8
6. Preview the page.

## Result
The image is fixed, however, it loads only within the left half of the Cover block.

<img width="1379" alt="Screen Shot 2019-04-24 at 7 07 07 AM" src="https://user-images.githubusercontent.com/13387217/56665808-9b017100-665f-11e9-8b2c-054cbb8ec9ac.png">

A short video of this result: https://cld.wthms.co/JmeC6r

## Expected
I expected the image to load at full width within the cover block *and* to be fixed in the background.

Computer: Macbook Pro 13", Mojave, Ver. 10.14.4 (18E226)
Browser: Google Chrome, Ver. 73.0.3683.103 (Official Build) (64-bit)

* User report and follow up ticket: #1982622-zd

**Comment by Robertght** [comment]
@deancroyal I labeled the issue as a bug and set the Milestone to Illustratr now. I submitted a another bug report here: https://github.com/Automattic/themes/issues/743

Temp fix:

```
.wp-block-cover.has-parallax.alignfull {
max-width: 100vw;
width: 100vw;
left: 50%;
right: 50%;
margin-left: -50vw;
margin-right: -50vw;
transform: none;
}
```

**Comment by donalirl** [comment]
Another case in #12328303-hc

**Comment by scruffian** [comment]
I have a solution for this here: https://github.com/Automattic/themes/pull/2768
