### ISSUE TITLE
Dyad 2: Update Twitter Logo

### ISSUE THREAD

**Issue by fstath** [Automattic/themes#7428]
### Quick summary

We got asked by a user on Twitter (DM) if it's possible to update the Twitter logo on the footer.

User's message:
"I would like to update the old Twitter logo to the next x logo on my blog. It seems the template does not auto update the logo. Please advise."

### Steps to reproduce

-

### What you expected to happen

-

### What actually happened

-

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Visible on theme's demo site: https://dyaddemo.wordpress.com/

![Markup on 2023-10-16 at 14:51:35](https://github.com/Automattic/themes/assets/27249804/0334cb2e-1c22-4757-a3fd-bb98e5e47e18)

📌 ACTIONS
- Updating to Enhancement
- Enhancement request kept

**Comment by lizswafford** [comment]
Additional request to update the logo (8780236-zd)

**Comment by jeherve** [comment]
I would recommend updating the social link from `twitter.com` to `x.com`. The icon will change accordingly.
