### ISSUE TITLE
Independent Publisher 2: Gravatar not displaying in header

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#7433]
### Quick summary

The Gravatar is no longer displaying above the site title 

### Steps to reproduce

1. View Independent Publisher 2 theme demo site: https://independentpublisher2demo.wordpress.com/

### What you expected to happen

I expected the Gravatar to display above the site title as it does in the images on the theme showcase page: 
![Independent publisher](https://github.com/Automattic/themes/assets/32983813/897804e1-6158-4efa-8ba5-244b3d4eb442)

### What actually happened

The Gravatar did not display

### Context

Customer Report and can recreate on my test site
7180363-zd-a8c

### Platform (Simple, Atomic, or both?)
Simple and Atomic

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated as described - theme showcase itself doesn't show the gravatar anymore.

![Markup on 2023-10-19 at 12:39:59](https://github.com/Automattic/themes/assets/27249804/ccb57ede-f12c-40e2-9a0c-ff800cbf34ca)

📌 ACTIONS
- Triaged

**Comment by Aurorum** [comment]
This is actually a very simple fix - it's just that Gravatar has switched to only supporting SSL. :) 

PR in #7515
