### ISSUE TITLE
Programme: Century and Futury styles have illegible font colors

### ISSUE THREAD

**Issue by stephhjacq** [Automattic/themes#7435]
### Quick summary

The dark version of the Programme theme has font colours with very low contrast that cannot be read.

![Screenshot 2023-10-17 at 17-55-23 Programme Theme ‹ staging-97e5-cvukrainianculturalsociety wpcomstaging com — WordPress com (1)](https://github.com/Automattic/themes/assets/29288537/48d619fd-ef64-469e-9873-1bf0c5a9cfca)

### Steps to reproduce

1. Select Programme theme
2. Change to dark colour scheme

### What you expected to happen

Expect to be able to read text on page

### What actually happened

Cannot read text because it is charcoal on navy.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Do not use the dark colour scheme.

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicable from the theme's demo page: 

https://github.com/Automattic/themes/assets/27249804/8f1bb3ce-c37b-4255-8b0e-abc411bd9d98

📌 ACTIONS
- Triaged

**Comment by cuemarie** [comment]
Escalated here: p7DVsv-iVM-p2#comment-48037

**Comment by Aurorum** [comment]
PR in #7480 

| Before | After |
|--------|--------|
| <img width="1599" alt="Screenshot 2023-11-12 at 21 13 15" src="https://github.com/Automattic/themes/assets/43215253/9bf28461-0d81-4652-87d3-29432d937023"> | <img width="1612" alt="Screenshot 2023-11-12 at 21 03 44" src="https://github.com/Automattic/themes/assets/43215253/39f9d450-e324-44e3-923f-c0dbe6e3aa13"> |
| <img width="1585" alt="Screenshot 2023-11-12 at 21 13 20" src="https://github.com/Automattic/themes/assets/43215253/8db744f9-f2f6-4124-9902-441e6fc4a858"> | <img width="1606" alt="Screenshot 2023-11-12 at 21 03 50" src="https://github.com/Automattic/themes/assets/43215253/9d223ec5-8d75-480f-96c6-eccc1e3764eb">  |
| <img width="1587" alt="Screenshot 2023-11-12 at 21 13 25" src="https://github.com/Automattic/themes/assets/43215253/9c3bda94-a682-4f81-acf4-3f5c77698e92"> | <img width="1610" alt="Screenshot 2023-11-12 at 21 03 57" src="https://github.com/Automattic/themes/assets/43215253/79294dd4-897a-426a-a3b1-cb97dafe7d09"> |
