### ISSUE TITLE
[Bug]: Multiple themes are developed by A8C but are attributed to "The WordPress team"

### ISSUE THREAD

**Issue by dsas** [Automattic/themes#7437]
### Quick summary

Several themes are marked as being authored by or copyrighted by The WordPress Team, yet actually they're created by A8C (albeit often directly derived from work by The WordPress Team)

From a quick look this includes:
 * Raw
 * Leven
 * The Menu
 * DOS
 * Programme
 * Modern Business
 * Curriculum
 * Grammer One
 * Pieria
 * Varia
 * Screenplay
 * probably more

### Steps to reproduce

1. Visit https://github.com/search?q=repo%3AAutomattic%2Fthemes%20%22the%20wordpress%20team%22&type=code

### What you expected to happen

Not to find A8C-authored themes attributed to the WordPress team, only WordPress team authored themes such as TT2 variants

### What actually happened

The precise opposite

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by davemart-in** [comment]
@iamtakashi any thoughts on how we want to handle this?

**Comment by iamtakashi** [comment]
Pinging the theme designers as FYI. @beafialho @henriqueiamarino @alaczek 

A quick search in the repo, https://github.com/search?q=repo%3AAutomattic%2Fthemes++%22The+WordPress+Team%22&type=code&p=3

@davemart-in We should check all of the above and change them where necessary. But @beafialho, @henriqueiamarino, and I will be at a meetup next week. We can do it when we're back if this isn't an urgent issue.

**Comment by dsas** [comment]
FWIW https://github.com/Automattic/themes/pull/8068 is already in place to stop this happening again in future 👍

**Comment by henriqueiamarino** [comment]
Thanks, @iamtakashi. I'll create PRs to fix the following:
- MyMenu
- Olympique
- Alter
- Specials
- Inversum
- Massimo

All the others have newer versions and will be delisted, so I won't take any action. They are:
- Raw
- Stage
- Curriculum
- Pieria
- Overlaid
- The Menu
- Stage
- Issue
- Texty
- Ritratto
- Organize
- Programme
- GrammerOne
- Blogorama
- BoxedBio
- Messagerie
- Screenplay
- DOS

**Comment by andregardi** [comment]
> Thanks, iamtakashi. I'll create PRs to fix the following:

Hello @henriqueiamarino,
I am on groundskeeping and browsing open issues. Did you get to create the PR or this issue still have some work to be done?

**Comment by henriqueiamarino** [comment]
Hey @iamtakashi, we're wrapping up an effort to launch more than 50 themes. We are finally cleaning our backlog.
After that, I'll fix these issues — probably by December.

**Comment by iamtakashi** [comment]
I made a PR #8478. If there is no concern from the dotcom side, we can merge it.

> All the others have newer versions and will be delisted, so I won't take any action. They are:

@henriqueiamarino, I also changed those themes for simplicity, so we only mention `the WordPress team` where we need to.

**Comment by iamtakashi** [comment]
@henriqueiamarino, when everything is done, I'll bump up the versions for the following themes and update them in the dotorg repo.

```
inversum
massimo
mymenu
professio
specials
```

**Comment by henriqueiamarino** [comment]
Alright, thanks @iamtakashi. Please let me know if there's something I should do about it.
