### ISSUE TITLE
Radcliffe 2: Table block doesn't allow scrolling horizontally on mobile

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#7439]
### Quick summary

Wide tables added to pages using Radcliffe 2 are cut off on mobile and don't have a horizontal scrollbar that allows you to see the entire table.

### Steps to reproduce

1. Activate Radcliffe 2
2. Add a table to a page with several columns so it will be wider than a mobile screen
3. Preview in Mobile view and you will see the horizontal scrollbar
4. Publish the page
5. Open the page on mobile

### What you expected to happen

I expect to see the horizontal scroll bar and be able to scroll to the right and see the entire table.

### What actually happened

I don't see a horizontal scroll bar and cannot scroll to the right.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

- I was able to recreate with my own site on Radcliffe 2.
- If I change themes the same table will allow me to scroll (I tried Independent Publisher 2 and Twenty-Twenty three).

Reported by user: 7002005-zd-a8c

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
Replicated on Atomic as well.

https://github.com/Automattic/themes/assets/27249804/26a7635f-4114-44ac-8882-a55acc4716cd

📌 ACTIONS
- Triaged

**Comment by Aurorum** [comment]
PR in #7477
