### ISSUE TITLE
Business: Info page starts with private embedded youtube video

### ISSUE THREAD

**Issue by cuemarie** [Automattic/themes#7448]
### Quick summary

https://wordpress.com/theme/business/ contains an embedded YouTube video that's not watchable as it's set to Private.

### Steps to reproduce

1. Open https://wordpress.com/theme/business/
2. Scroll down

### What you expected to happen

A video explaining how to set up my homepage

### What actually happened

![Markup on 2023-10-30 at 16:34:52](https://github.com/Automattic/themes/assets/27249804/47bb868a-bbc8-46ab-afa6-b8d93f02a282)

### Browser

Firefox 119.0

### Context

Encountered while helping a customer in chat: 7225744-zen
I avoided directing the user to the theme info page for the majority of the chat as it wasn't as helpful with a broken video near the top.

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

I clicked around ~15 other classic themes, but couldn't see another theme info page that included this YT embed.

### Reproducibility

Consistent

### Available workarounds?

None needed

**Comment by cuemarie** [comment]
📌 ACTIONS
- Triaged
- Raised awareness here: p1698709460630079-slack-C029FM1EH

**Comment by alaczek** [comment]
Removed the video from the theme info page.
