### ISSUE TITLE
[Bug]: Livro theme - Typography size XXL is smaller than S

### ISSUE THREAD

**Issue by CacheMeOwside** [Automattic/themes#7456]
### Quick summary

Livro theme - Typography size XXL's font size smaller than size S in block settings

### Steps to reproduce

1. Activate the Livro theme.
2. Edit any post.
3. Add a `Paragraph` block.
4. Test the font size from `S` through `XXL` using the `Typography` section.

https://github.com/Automattic/themes/assets/64858136/3c6662fe-dd5e-4412-9550-8c0ca585739b

### What you expected to happen

Font size `S` should be the smallest and `XXL` should be the largest.

### What actually happened

Font size `XXL` is the smallest and `XL` is the largest.

Font sizes from largest to smallest in Livro theme:
XL > L > M > S > XXL

Unable to reproduce on self-hosted platform.

### Browser

Google Chrome/Chromium

### Context

Customer report

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

For now, users can set a custom size using the slider or text box in Typography settings.

<img width="288" alt="Screenshot 2023-11-02 at 9 25 10 PM" src="https://github.com/Automattic/themes/assets/64858136/7a4206f6-0726-40f0-94b4-23965e44ff15">

**Comment by Aurorum** [comment]
Please inform user in 7232883-zen when this is resolved.

**Comment by Aurorum** [comment]
PR in #7461 to hopefully close this. :)

**Comment by OmarFPG** [comment]
Comment from the user (7232883-zen):

> I see that you have done more than just fix this bug - I like the new enhancements.
> Could I make one observation? Would it not make more sense to list the size options in order of size?
![image](https://github.com/Automattic/themes/assets/122303439/1e3cdf3a-9781-4dd4-80ac-43f1ec59e3a2)

I told him this is a WIP, but I'd pass his comment along.
