### ISSUE TITLE
All Theme Variations: Consider removing spacers on the template from mobile. 

### ISSUE THREAD

**Issue by allancole** [Automattic/themes#746]
This deserves some thorough testing but on small screens, spacers take up too much screen space, especially when the spacer height has been set manually. To fix this, I think we should either remove the manually setting on mobile to be something standard, or hide the spacer entirely.

**Comment by iamtakashi** [comment]
I've added a special class `.desktop-only` to all the spacers in the homepage templates. Let's hide them below 786px.

**Comment by iamtakashi** [comment]
**Suggested Fix**

```
@media only screen and (max-width: 767px) {
	.wp-block-spacer.desktop-only {
		display: none;
	} 
}
```
