### ISSUE TITLE
Escutcheon: Custom colors not applied on single posts

### ISSUE THREAD

**Issue by jamiepalatnik** [Automattic/themes#7460]
### Quick summary

It seems custom colors selected in the Customizer are no longer applied on single posts on the Escutcheon theme. This seems to be affecting custom CSS as well.

### Steps to reproduce

1. Activate Escutcheon theme.
2. Go to Customize > Colors & Backgrounds and select custom colors.
3. Visit a single post.

### What you expected to happen

I woud expect my custom colors to be applied.

### What actually happened

The post title and other text are light blue, not the custom color.

### Browser

Google Chrome/Chromium

### Context

User report

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

It would be possible customize the colors with custom CSS, but this is not ideal.

**Comment by jamiepalatnik** [comment]
User reports: 
7257420-zd-a8c
7259148-zd-a8c

**Comment by cuemarie** [comment]
Possibly the same as https://github.com/Automattic/wp-calypso/issues/83982
Escalated here: p1699464090252049-slack-C02FMH4G8

**Comment by alshakero** [comment]
Hi! Can you confirm this is fixed now?

**Comment by Gustavo-Hilario** [comment]
I can see that the custom CSS code is working again for the site reported on #7257420-zen _(we can see that when turning the proxy off)_. I think we are good to close this for now.

**Comment by taipeicoder** [comment]
Closing via D128515-code. See related thread: p1699464090252049-slack-C02FMH4G8
