### ISSUE TITLE
Creatio 2: Navigation isn't working consistently

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#7471]
### Quick summary

From some pages (Page A, Page B, some others) the navigation bar links don't do anything when clicked.

### Steps to reproduce

 I'm not positive yet what conditions consistently produce the problem, but you can see it here:

1. Start here https://veldasthemetestsite.wordpress.com/
2. Click on the Lorem Ipsum link up top (note it works!)
3. Click on Page A (that link also works, for now)
4. Try to click back to any of the other links. (links stop working)

### What you expected to happen

I expect to be able to keep clicking through the site

### What actually happened

Top-level pages aren't clickable anymore, and second-level pages don't go anywhere when clicked, but if I hover over them, I get a blinking submenu I can't click on.

### Browser

Google Chrome/Chromium

### Context

Testing a process, but it could affect others

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

I have't tested this extensively tonight. What I did see though is that it's fine when I switched to another theme, so I'm reporting an issue with Creatio 2.

### Reproducibility

Intermittent

### Severity

One

### Available workarounds?

None

### Workaround details

I don't know of a workaround yet since the page template seems okay? I'm marking "ONE" for severity since I've only seen it here and don't have time to test further tonight, but I hope someone else will check it out.

**Comment by iamtakashi** [comment]
This doesn't seem to be a theme-specific issue. I can reproduce with other themes like TT3. I opened an issue in the wp-calypso repo. https://github.com/Automattic/wp-calypso/issues/84074
