### ISSUE TITLE
Update/Fix Theme RITRATTO

### ISSUE THREAD

**Issue by henriqueiamarino** [Automattic/themes#7485]
I need a fix on the [Ritratto](https://github.com/Automattic/themes/tree/cf5d5b443d0fcd43dcef91307160b538e4865678/ritratto) theme.

Issue
The variation had to be deleted. A color gradient works as a background for the hero group (where the photo sits), but its colors are not automatically updated as theme styles change.
![ritratto](https://github.com/Automattic/themes/assets/103748085/3e1e0ebf-c553-4891-95b1-3851d271f6ec)

Result
Theme Style variation was removed, and the theme is okay to show on the showcase.

Expected
This is the new theme zip file to replace the former one: [ritratto.zip](https://github.com/Automattic/themes/files/13365753/ritratto.zip)

**Comment by vcanales** [comment]
Which variation had to be deleted? I'm not seeing changes in the theme.json file.
Unfortunately, the new zip includes changes not related to this fix, so I don't know where to look exactly.

**Comment by henriqueiamarino** [comment]
There is only one style variation besides de Default. I removed it because this theme won't have a style variation.
