### ISSUE TITLE
All Theme Variations: Too much side padding on wide-width Media & Text block

### ISSUE THREAD

**Issue by allancole** [Automattic/themes#749]
Too much side padding on the text side of the Media & Text column when it’s stacked on mobile. 

Effects Elegant, Modern, Professional, Calm, Friendly.

![image](https://user-images.githubusercontent.com/709581/56924556-2e410900-6a9b-11e9-860e-3660b5224c6e.png)

**Comment by iamtakashi** [comment]
I'm closing this as I made per theme issue.
