### ISSUE TITLE
Twenty Twenty: Update Twitter Logo In Social Menu

### ISSUE THREAD

**Issue by synora** [Automattic/themes#7494]
We have a request in the forums to update the theme's Twitter logo to "X".

The user's message: 
"The Twenty-twenty theme has a clever social menu option, it automatically assigns icons for known social media networks, including the little bird for Twitter. Along with everyone else, I’m no fan of the X name or icon, but I guess it’s time!

Can this theme be upgraded so that links to x.com have the X logo?

Unfortunately I can’t seem to achieve this through CSS editing, as the social icons built into the theme are coded as SVGs, rather than using – say – an icon font.

To be clear, I’m talking about the social menu (in my case it’s built into the footer and the hamburger menu for mobile), not the share this menu at the end of a post (which does support the X logo)."

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 


📌 FINDINGS/SCREENSHOTS/VIDEO
![Image](https://github.com/Automattic/themes/assets/86028337/daa73229-9ddf-41b3-acc4-80fb84e4987f)


📌 ACTIONS
- Feature request kept

**Comment by jeherve** [comment]
I would recommend updating the social link from `twitter.com` to `x.com`. The icon will change accordingly.
