### ISSUE TITLE
Twentytwentythree: Jetpack Fonts not showing on live site

### ISSUE THREAD

**Issue by vparkhere** [Automattic/themes#7507]
## Steps to replicate

1. Activate Twenty Twenty Three theme.
2. Go into Editor > Styles and select a Google Font like `Poppins`.
3. Save changes and view live site.

## Result
The editor shows the chosen Google Font being implemented.  However, the live site continues to show `serif`.

EDITOR
<img width="1363" alt="Screenshot 2023-11-20 at 1 54 33 PM" src="https://github.com/Automattic/themes/assets/11635760/4f8b8c46-3df8-449f-b0b6-ef30d7c82e3e">

ATOMIC SITE
<img width="1148" alt="Screenshot 2023-11-20 at 1 52 37 PM" src="https://github.com/Automattic/themes/assets/11635760/31a7e16b-67f6-47d2-82f3-4b9172162007">

## Expected
I expected the chosen font, `Poppins`, to show up as the chosen font on the live site.

## Sites tested
Was able to reproduce on an Atomic and Pressable site with other Google Fonts.  The only theme affected seems to be Twenty Twenty Three.  Could not reproduce on a simple site, I believe there's some sort of conflict with Jetpack Fonts.  Disabled Gutenberg plugin, updated theme from version 1.1 to 1.3, but issue persisted.

* User report: p9F6qB-dMa-p2

**Comment by Nic-Sevic** [comment]
issue appears to be that `wp-fonts-local` isn't loading
On my test site I was able to get this to appear by cycling the theme

user site: 
![2023-11-23 at 15 23](https://github.com/Automattic/themes/assets/47717887/17f40339-7fdc-43a6-8567-36f85075c8cf)

my site: 
![2023-11-23 at 15 22](https://github.com/Automattic/themes/assets/47717887/d0e479c5-f06d-4cb8-a82c-9175571d84f2)

**Comment by liviopv** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/84611
