### ISSUE TITLE
Calm Business: Missing wide width separator styles

### ISSUE THREAD

**Issue by allancole** [Automattic/themes#751]
Calm Business is missing styles for the `.is-style-wide` which should make the separator stretch across the full width of the .entry-content column.

![image](https://user-images.githubusercontent.com/709581/56925363-26826400-6a9d-11e9-8a27-4055d5ca00e7.png)

![image](https://user-images.githubusercontent.com/709581/56925395-431e9c00-6a9d-11e9-96d2-4ea6b6241453.png)

**Comment by torres126** [comment]
PR in #769 :)

**Comment by jeffikus** [comment]
Fixed in branch 769-fixes_separator_missing_styles

**Comment by allancole** [comment]
Closing this since it was fixed in #804
