### ISSUE TITLE
Organizer: Archives template does not filter properly by category/tag

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#7519]
### Quick summary

Visiting a category or tag page does not correctly filter posts using the default Archives template. Instead it displays all posts.

### Steps to reproduce

1. Activate Organizer
2. Create a few posts in different categories
3. View category pages

### What you expected to happen

Category and tag pages should display only posts with that category or tag.

### What actually happened

Category and tag pages display all posts, regardless of whether or not they have the selected category or tag.

### Context

https://wordpress.com/forums/topic/when-i-select-a-specific-category-it-just-shows-every-post/

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

Similar to these other bug reports:

https://github.com/Automattic/wp-calypso/issues/66659
https://github.com/Automattic/themes/issues/5606
https://github.com/Automattic/themes/issues/6778

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

- Go to the All Archives template
- Select the Query Loop block
- Toggle on "Inherit query from template"

While the actual workaround is easy to implement, most users would not figure out how to fix this without contacting support.

**Comment by jp-imagines** [comment]
Ran into a case of this in 7392718-zd-a8c, though that was with the _Jaida_ theme, not _Organizer_.

Not certain if both themes need to be updated separately, or if there's a single underlying cause here. I can move this to a new report if needed.

**Comment by rickmgithub** [comment]
STEPS TO RECREATE:

* Set up simple or Atomic site
* Install the "Organizer" theme
* Create a few posts in different categories
* View category pages e.g. domainname.com/category/processes/
* Category and tag pages display all posts, regardless of whether or not they have the selected category or tag.

## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated on "Organizer" theme

https://github.com/Automattic/themes/assets/13706336/cb6210bc-ea1e-46d6-9c5e-f51a431f6116
 
- Tested on Atomic – Replicated again

- Tested on other themes - Couldn't recreate on Stratford

## 📌 ACTIONS ##
Triaged

**Comment by nazilya06** [comment]
8541850-zd-a8c 

The user is using a third-party theme.
