### ISSUE TITLE
Programme: No comments on Single Post template

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#7520]
### Quick summary

The single post template is missing a comment form. When someone writes a post and enables comments, it's helpful for those comments to actually display within the theme without the site owner having to make extensive template edits to add them.

### Steps to reproduce

1. Use a site with Programme active
2. Create a post and ensure comments are enabled
3. Publish the post; note there is no comments form
4. From the Site Editor, view the Single Post template
5. Note there is no comment form there either

And for extra credit:

6. See how long it takes to add a nice looking comment form and comments display section. It would be good if this came with the theme.

### What you expected to happen

I expect single posts templates to have comments.

### What actually happened

Single post template is missing comments.

### Context

Note in my own testing of new comments, but I've also spotted folks complaining comments don't display at all, and they're switching to classic themes to fix it.

### Other notes

I've seen this issue in other themes, too.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

User has to add their own comment form and comment display in the template, and format it so it looks nice with their theme. This may take an experienced user a few minutes, but for end users it's quite a lot of work.

**Comment by supernovia** [comment]
See also:
https://github.com/Automattic/themes/issues/7445
https://github.com/Automattic/themes/issues/7402

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated

## 📌 ACTIONS ##
Triaged
