### ISSUE TITLE
Multiple Themes: Unbalanced spacing on left and right Columns block at the 768 breakpoint.

### ISSUE THREAD

**Issue by allancole** [Automattic/themes#753]
Extra side margin in the last item of a Columns Block on screens below 768px. Effects Modern, Calm, Friendly, Sophisticated business.

Notice the unbalanced spacing on the left and right padding/margins:

![image](https://user-images.githubusercontent.com/709581/56927536-67c94280-6aa2-11e9-98a0-63fc39df8fff.png)

First column has no left-margin: 
![image](https://user-images.githubusercontent.com/709581/56928121-e70b4600-6aa3-11e9-9baf-63c49d5d47e9.png)

Last column should have no right-margin: 
![image](https://user-images.githubusercontent.com/709581/56928084-cb07a480-6aa3-11e9-83b8-e69939e5697c.png)

## Suggested Fix

Remove right margin from the right-most (or `:last-child`) column.

**Comment by allancole** [comment]
Looks like this issue has been fixed already in this commit: https://github.com/Automattic/themes/commit/f4efe1a85364f8057ff14bc23444a304f9e96d06#diff-5e9fa37ae8413cb9975637cf1c43a90a

I’ll close this issue after I deploy the code to `wpcom`.

**Comment by iamtakashi** [comment]
I've tested with the four themes. Now there is no space between 2nd and 3rd ones.

<img width="714" alt="Screen Shot 2019-05-09 at 23 07 58" src="https://user-images.githubusercontent.com/908665/57489930-7e944400-72af-11e9-9f06-c9e03a517592.png">

**Comment by allancole** [comment]
Give this PR #797  a test when you get a free moment @iamtakashi :-)
