### ISSUE TITLE
Eventual: Title field is transparent Page/Post Editor if the Title Block is removed from the template

### ISSUE THREAD

**Issue by liviopv** [Automattic/themes#7536]
### Quick summary

When the Title Block is removed from the Template, the Title Field becomes invisible in the Post/Page Editor, even if it's readded to the template.

The problem seems to be caused by the fact that the Title is inheriting the theme's base color, which is the same as the background

![CleanShot 2023-12-07 at 12 20 41@2x](https://github.com/Automattic/themes/assets/14153300/4aaf3212-a32f-4c24-bff1-7b23c87e143c)

### Steps to reproduce

1. Activate Eventual
2. Edit the Page or Single Posts Template in the Site Editor
4. Remove the Title Block and save
5. Exit the Site Editor
6. Open a new Page or Post from Pages/Post > Add new
7. The Title field will be transparent in the editor

### What you expected to happen

The title field should be visible regardless of the color defined by the theme

### What actually happened

The field is transparent

### Browser

Google Chrome/Chromium

### Context

Customer report

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

- Editing the page from the Site Editor
- Editing the title from WP Admin Quick Edit

**Comment by liviopv** [comment]
- [ ] 7418883-zd-a8c

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue:
![Markup 2023-12-13 at 00 31 06](https://github.com/Automattic/themes/assets/9025643/38ab5a97-50ba-49bb-9ee8-40abd38f85c2)


📌 ACTIONS
– Triaged

**Comment by alaczek** [comment]
This is a tricky one. The homepage has a dark background, while posts/pages have light bg, so each requires a different color, while we only have one default. If we changed it around and made post/page titles use contrast color by default, we would run into similar issue on the homepage, where once a post/page title is removed and re-added, it would be invisible.

By the way, the problem exists even before title is removed from post/page template, which I imagine is quite confusing, but makes it worthwhile to attempt a fix.

**Comment by alaczek** [comment]
This should be fixed now.
