### ISSUE TITLE
Covr theme: Post and page content not visible by default due to template setup

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/themes#7551]
### Quick summary

This is technically two issues in one:

1. The `Single Posts` template on the Covr theme uses the _Excerpt_ block instead of the _Content_ block, so post content isn't shown on individual posts. (Post content is also not included on the `Blog Home` template's default Query Loop.)
2. There is no `Pages` template, so pages default to the `Index` template, which has only a Query Loop (inheriting its query from the template), which then displays only that page's featured image and title.

### Steps to reproduce

1. Activate the _Cover_ theme.
2. View at least one post and one page on your site.

### What you expected to happen

The content added for the post and page should be visible on the individual post and page on the live site.

### What actually happened

No content is ever visible without having to make adjustments to the theme's default templates.

### Context

7446877-zd-a8c

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Workarounds for now:

1. Edit the `Single Posts` template and transform/replace the _Excerpt_ block with a _Content_ block.
2. Create a `Pages` template. Setting this up requires some manual effort, since the theme has no default pattern for it.

**Comment by beafialho** [comment]
This has been solved in #7560 so I'll close this issue.
