### ISSUE TITLE
Assembler: Issues on post-meta pattern and template part

### ISSUE THREAD

**Issue by miksansegundo** [Automattic/themes#7553]
## What
There are issues with the post-meta pattern and its template part because they were copied from [mpho theme](https://github.com/Automattic/themes/blob/b689c25fe5ccc635e5ce958334b72248a6b98b00/mpho/patterns/post-meta.php)

1. The post-meta template part uses the slug `mpho/post-meta`, which is wrong because it should be `assembler/post-meta`. See https://github.com/Automattic/themes/blob/b689c25fe5ccc635e5ce958334b72248a6b98b00/assembler/parts/post-meta.html#L1
3. The pattern should include a comment with `Inserter: no` because it's not meant to be listed in the inserter. @alaczek can you confirm this?
4. The pattern uses the wrong pattern category `post meta`. This category is not registered and is not meant to be used here. 

## Why
The first issue is the most important because the template is broken.
The second issue shows that pattern in the editor inserter as "uncategorized".
The third issue could fix the second issue if we use a valid category but I believe that pattern should not be in the inserter.

## How
1. use `assembler/post-meta` as the slug
2. add the comment `Inserter: no`
3. remove the comment `Categories: post meta`

**Comment by richtabor** [comment]
In https://github.com/Automattic/themes/pull/7538 I've removed the post meta (and a few other templates/parts) that are no longer necessary.

**Comment by alaczek** [comment]
It looks like @richtabor already addressed it! That PR should be good to merge.
