### ISSUE TITLE
Twenty Nineteen (And Child Business Themes): Comment Input Issues

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/themes#756]
## Steps to replicate

1. Set up a site to allow non-WPCOM users to comment on posts.
2. Utilize the Twenty Nineteen or [Child Name] Business themes.
3. Visit a post on the site in an incognito window or while logged out of WPCOM.
4. Attempt to input a comment.

## Result

The inputs will appear improperly.

![image](https://user-images.githubusercontent.com/4887830/56989144-c56f9480-6b5f-11e9-9477-16395bcc45ed.png)

## Expected

Proper form input.

![image](https://user-images.githubusercontent.com/4887830/56989211-efc15200-6b5f-11e9-9296-4e9f04df0a7c.png)

* User report: 12462117-hc
* Follow-up ticket: 1998908-zen
* Discussion: p1556651138235400-slack-themes

Reproduced on the following:
* Twenty Nineteen
* Professional Business
* Sophisticated Business
* Elegant Business
* Friendly Business
* Calm Business
* Modern Business

Opening issue for further investigation and to see if it's a conflict with Jetpack.

**Comment by fresatomica** [comment]
I've got another user report: 2142223-zen

**Comment by scosgro** [comment]
Another user report: 14164166-hc

**Comment by tijosh** [comment]
Another report of this in #2363222-zen

User noticed on iPads

It looks like this does not affect mobile at all—only medium and desktop screens

**Comment by reginabally** [comment]
Another report of this in #15232750-hc for Twenty Nineteen theme. User reported this on a desktop screen and I'm able to replicate this on my test site.

**Comment by tbradsha** [comment]
Reported in 3345341-zen (free WordPress.com site) and confirmed on my test site.

**Comment by tbradsha** [comment]
As a workaround, this CSS should override the errant float:

```css
@media only screen and (min-width: 768px) {
  .comment-form .comment-form-author, .comment-form .comment-form-email {
    float: unset;
  }
}
```

**Comment by serabi** [comment]
Reported in 27274967-hc - user would also like to be contacted when issue is fixed.

**Comment by pbking** [comment]
Fix can be found here: c-D62215

Note that in the above change there appear to be additional changes in style-rtl.css which (from what I can tell) are simply because changes to the .scss were not compiled into that file before.

Before:
![image](https://user-images.githubusercontent.com/146530/120537171-fb247e80-c3b2-11eb-94c8-67ebd4e7552b.png)

After:
![image](https://user-images.githubusercontent.com/146530/120537206-04ade680-c3b3-11eb-82ea-f7edb4d67245.png)

This also continues to look as expected in a non-wordpress.com environment:
![image](https://user-images.githubusercontent.com/146530/120537302-2018f180-c3b3-11eb-927e-7baa3d4db409.png)

**Comment by danieldudzic** [comment]
I'm still getting the following, after applying the patch:
![after_applying_the_patch](https://user-images.githubusercontent.com/905781/120868240-e521e400-c593-11eb-928b-0c7fe4ffde56.png)

**Comment by pbking** [comment]
I'm not sure I understand this comment: D62215-code#1280125

The screenshot noted looks appropriate to me.

**Comment by scruffian** [comment]
The screenshot is how it looks before this change :)

**Comment by pbking** [comment]
Ah, Ok.
Makes sense.  My method of testing that scenario was giving me a false positive.  TY

![image](https://user-images.githubusercontent.com/146530/121377879-b51a6e00-c910-11eb-9e98-36b0c6b64960.png)

**Comment by scruffian** [comment]
You should be able to copy my approach here: https://github.com/Automattic/themes/pull/4020

**Comment by pbking** [comment]
The change works for .org and .com now.

D62215-code

However, the change also introduces quite a lot of changes that should have been on the style-rtl.css already.  Considering the amount a carefull 👀 would be appreciated to ensure it's correct.
