### ISSUE TITLE
[Bug]: Twenty Twenty-One - PDF file does not preview

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/themes#7562]
### Quick summary

Embeding a PDF file preview shows up in the Editor, but not in the front end.

### Steps to reproduce

1. Use Twenty Twenty-One theme
2. Upload a sample PDF file using file block
3. Preview works fine in the Editor
4. You will only see an option to download and a link to the file in the frontend
    
    ![image](https://github.com/Automattic/themes/assets/129587477/62984ce8-dd43-45aa-8072-3e0007a52649)

5. Switch to a different theme and notice that the preview works fine

    ![image](https://github.com/Automattic/themes/assets/129587477/88bcc0b4-c42e-4042-8188-9ee52bece298)

### What you expected to happen

PDF preview to be visible in front-end

### What actually happened

Preview is only visible in Editor.

### Browser

Google Chrome/Chromium

### Context

7458612-zen

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by saginpj** [comment]
- [ ] 7464568-zen (Shawburn Theme)

**Comment by saginpj** [comment]
- [ ] 7471698-zen

**Comment by caitlindawn** [comment]
Encountered in 7486167-zen (Independent Publisher 2 theme)

**Comment by AnjanaV93** [comment]
Another report here: 7449298-zen (Independent Publisher 2 theme)

**Comment by liviopv** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/issues/85244
