### ISSUE TITLE
Multiple Themes - Missing Featured image in blog posts block and PDF previews

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#7580]
### Quick summary

Stratford theme missing featured images in the blog posts block and previews from embedded PDFs
I'm suspecting they may be related?

### Steps to reproduce

FEATURED IMAGES 

1. Atomic site
2. Ensure you have posts with featured images
3. Add Blog posts block to a page 
4. Within the editor the featured images are shown

![Markup on 2023-12-22 at 14-32-39](https://github.com/Automattic/themes/assets/13706336/bff70e25-0478-48eb-8d18-d92b726cd078)

6. On the public page they are not.
<img width="3856" alt="Markup 2023-12-22 at 14 33 40" src="https://github.com/Automattic/themes/assets/13706336/ef53d91d-77ed-400a-b2ad-28dc0b3a12e2">

PDF previews
1. Add a file block
2. Add a PDF file
3. The preview appears in the editor

![Markup on 2023-12-22 at 15-15-21](https://github.com/Automattic/themes/assets/13706336/b14dabbd-f426-4342-ac4b-92171a6d6f75)

4. But not on the public page
![Markup on 2023-12-22 at 15-16-06](https://github.com/Automattic/themes/assets/13706336/5001c538-a093-484c-8a46-6e75276f424f)

### What you expected to happen

The previews to show as per the editor

### What actually happened

They didn't show.

### Browser

Google Chrome/Chromium

### Context

7486069-zd

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
Tested on user site and 3 different own test sites.

## 📌 ACTIONS ##
Triaged

**Comment by hacchism** [comment]
Another report on 7484197-zen 

- The missing featured image issue
- Theme: Hever
- Atomic

**Comment by hacchism** [comment]
While testing the case above, I discovered that the featured image issue happens in the Query Loop Block too. So the QL block can't be suggested as a workaround.

**Comment by Aurorum** [comment]
> I'm suspecting they may be related?

I don't believe so. Unless I'm misunderstanding, the Featured Images issue is not theme specific, and it affects other themes too. It stems from Jetpack's Content Options settings overriding the block settings, and it's being tracked here: Automattic/jetpack#29286

The PDF issue also affects other classics themes, and it's being tracked here: Automattic/wp-calypso#85244

**Comment by Neha93517** [comment]
Another report: 7517864 - Zen

**Comment by Neha93517** [comment]
Another report: 7514543 - Zen
Two sites : 

- https://labriocheriedepascal.fr/
- http://evasioncars.fr/

 Theme: Rockfield (Free)

**Comment by mdtanjid0** [comment]
Another report - 

- [ ] needs to be followed up 7549696-zen 

Theme Hever.
