### ISSUE TITLE
[Bug]: Unable to download Kaze theme

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/themes#7585]
### Quick summary

The Kaze theme is not available for download at https://downloads.wordpress.org/theme/kaze.zip

### Steps to reproduce

1. Go to https://wordpress.com/theme/kaze
2. Select the site
3. Scroll to the Download links:
![image](https://github.com/Automattic/themes/assets/78526686/33fbfe11-e03a-44f8-b7ef-25852f80e9cb)

### What you expected to happen

The theme is available for download

### What actually happened

404
`{
    "error": "theme_not_downloadable",
    "message": "The specified theme is not downloadable"
}`

### Other notes

7533174-zen dotOrg

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Yes, easy to implement

### Workaround details

Download the theme manually from the Automattic/themes repo - https://github.com/Automattic/themes

Paste the theme folder here - https://download-directory.github.io/

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS 
-Tested on Atomic – Replicated 

📌 FINDINGS/SCREENSHOTS/VIDEO 
I was able to reproduce the issue, the download link points to https://downloads.wordpress.org/theme/kaze.zip - 404 File not found

At the same time, it's possible to activate the theme via the theme preview:
https://wordpress.com/theme/kaze/ 

📌 ACTIONS 
- Triaged

**Comment by taipeicoder** [comment]
Kaze is a premium theme so it's not available for download. The current UI does not show the download button either. Feel free to reopen in case there are further concerns.
