### ISSUE TITLE
[Bug]: Messagerie custom CSS not applying to header element

### ISSUE THREAD

**Issue by G3e** [Automattic/themes#7591]
### Quick summary

After applying the following to the header element under 'Additional CSS' in the WordPress Editor for the theme, it doesn't get applied. The original blur and background remain the same instead of going transparent. 

background-color: rgba(0,0,0,0.00);backdrop-filter: blur(5px);

### Steps to reproduce

1. Go to WordPress Editor, click 'Customise'
2. Select the Header and go to 'Styles' in the WordPress Editor.
3. Under 'Styles' for the Header, click 'Additional CSS'
4. Entered the following:
5. Save

### What you expected to happen

CSS for the element should be changed

### What actually happened

The header didn't apply the custom CSS I entered in the WordPress Editor.

### Browser

Google Chrome/Chromium

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

Could not replicate the issue.


📌 FINDINGS

The CSS will apply if we create a CSS class, as explained here: https://wordpress.com/support/wordpress-editor/adding-additional-css-classes-to-blocks/

This class needs to be created for the element that we want to edit.


📌 ACTIONS

Closing.

📌 Message to Author

@G3e

Thank you for your report.

I'm afraid the described steps would not work as this is not how CSS is added to elements via the site editor.

I recommend reading the following guides:

- https://wordpress.com/support/wordpress-editor/adding-additional-css-classes-to-blocks/
- https://wordpress.com/support/editing-css/#Access-the-CSS-Editor-(Global-Styles)
- https://wordpress.com/support/editing-css/#add-css-to-specific-block-types
