### ISSUE TITLE
All Theme Variations: Style enhancement for Mailchimp block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#760]
Currently, the input field is very short and looks strange.

Also, the concent text shouldn't have the same visual weight as a paragraph. Should use one or two smaller size in the font size variables.

<img width="770" alt="Screen Shot 2019-04-30 at 23 17 11" src="https://user-images.githubusercontent.com/908665/56996968-21590e00-6b9e-11e9-835c-60bd1a20f736.png">

<h2>Suggeste Fix</h2>
 Make the input width 100%. Use one or two smaller size in the font size variables.

**Comment by scruffian** [comment]
These fixes should probably be in the block

**Comment by Robertght** [comment]
Based on this https://github.com/Automattic/themes/pull/791, it appears it's related to the retired themes. 

Closing
