### ISSUE TITLE
Dyad 2 theme: Header overlaps content on mobile views

### ISSUE THREAD

**Issue by vajrasar** [Automattic/themes#7610]
### Quick summary

When using Dyad 2 theme and checking on mobile device, the header with its opacity cover the first content section.

![Without Logo and Single line Taglilne](https://github.com/Automattic/themes/assets/2210243/1f069a2f-2b1d-4dc5-8c61-4f6466460c67)

### Steps to reproduce

1. Activate Dyad 2 theme
2. Add Menu items
3. Insert a Site Logo, Title, and Tagline
4. Check the site on actual mobile device

### What you expected to happen

The header should be its own section.

### What actually happened

Header overlaps on the first content section

![With Logo](https://github.com/Automattic/themes/assets/2210243/cfa3dc47-aed0-41ad-88a8-c2cd237f9dd4)

![Without Logo and Double line tagline](https://github.com/Automattic/themes/assets/2210243/2e36adc1-4f71-4dbf-8cea-2806ae438521)

### Browser

Google Chrome/Chromium, Apple Safari

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

My test site themetestwpsite.wordpress.com

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by vajrasar** [comment]
- [ ]  zd-7553249

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
OP test site on Chrome for Android:

![CleanShot 2024-01-17 at 16 07 55@2x](https://github.com/Automattic/themes/assets/14153300/0d8beb91-1ca3-475f-90c3-346b4a743a4b)

https://liviofree.wordpress.com/ on Chrome for Android:

![CleanShot 2024-01-17 at 16 09 25@2x](https://github.com/Automattic/themes/assets/14153300/ad9650f3-aa92-4b80-8a6a-04b196fea1ef)


📌 ACTIONS
- Requested author feedback

📌 Message to Author
@vajrasar I think the issue could be browser-specific, I'm not seeing any overlapping on my end - the end of the header and the start of the content are clearly defined by a white line and the header remains visible.

What browser did you test this on?

**Comment by liviopv** [comment]
@vajrasar I'm closing this as couldn't replicate, please reopen as needed.
