### ISSUE TITLE
Kerr Theme: Paragraph Block text renders too small in the editor

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#7612]
### Quick summary

A user reported that the text size for Paragraph Block text suddenly looks very small on their site. I investigated further, and noticed that this affects text in a Paragraph Block in the editor itself. When I view the rendered text as a published post or page, the default size of the text is correctly proportioned.

By comparison, the text in a List Block that would render as the same size on the front-end looks correct in the editor. When rendered, text in both blocks render as `20.25px "Work Sans", sans-serif`.

### Steps to reproduce

1. Activate the Kerr premium theme
2. Add a List Block and a Paragraph Block to a new post or page
3. Add text to each block using the default typography options from the theme
4. Observe that the text in a Paragraph Block is smaller than text in a List Block in the editor
5. When you preview the post/page (or publish it and view it), both texts are the same size and style.

### What you expected to happen

I expected the text in a Paragraph Block when rendered in the editor to be the same as the List Block, much like this:

![CleanShot 2024-01-15 at 17 22 26@2x](https://github.com/Automattic/themes/assets/2912202/81ec0694-f145-46c2-a0a4-eb336713c7c5)

### What actually happened

Instead, the rendered text in the editor is disproportionately smaller, like this:

![CleanShot 2024-01-15 at 17 26 10@2x](https://github.com/Automattic/themes/assets/2912202/056f1ea6-6466-4fce-8e94-1eeaa90aa5e0)

### Browser

Microsoft Edge

### Context

Customer report in 7586518-zen

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

This affects the Kerr Premium theme

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

The only real option is to ignore how the text is rendered in the editor and verify the text size is correct by previewing the draft post or page.

**Comment by cat-og** [comment]
This appear to be an issue with all the Universal theme except Creatio 2. Closing in favor of duplicate report here: https://github.com/Automattic/wp-calypso/issues/86570
