### ISSUE TITLE
Karuna: Update Twitter Logo

### ISSUE THREAD

**Issue by essleeung** [Automattic/themes#7619]
### Quick summary

User wants to update the Twitter logo in the header of the theme. 

SImilar to these 2 other open requests: 
https://github.com/Automattic/themes/issues/7494
https://github.com/Automattic/themes/issues/7428

### Steps to reproduce

Open up Appearance > Customizer > Menus > Social Menus. There isn't a way to change the default social media logos.

### What you expected to happen

Change from Twitter to X logo.

### What actually happened

Shows old Twitter logo still

### Other notes

reported by user here 7612704-zd-a8c. (Technically this user is using a Karuna child theme)

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by jeherve** [comment]
I would recommend updating the social link from `twitter.com` to `x.com`. The icon will change accordingly.
