### ISSUE TITLE
Calm Business: Missing .is-style-wide CSS for separator block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#762]
Currently, wide style variation for the block display the same separator as short style.

<img width="1051" alt="Screen Shot 2019-04-30 at 23 49 09" src="https://user-images.githubusercontent.com/908665/56998339-dc83a600-6ba2-11e9-8991-7e3a741e5956.png">

Need a wider style :)

**Comment by torres126** [comment]
Duplicate of #751
