### ISSUE TITLE
Featured images not showing up anymore

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#7623]
### Quick summary

I've encountered quite a few cases in the past, where users claim the featured images magically vanished from their homepage/blog posts.

The solution was to enable "Display images on pages" from Appearance > Customize > Content options.

### Steps to reproduce

I don't have a past installation to compare/replicate.

### What you expected to happen

To see the featured images.

### What actually happened

The featured images vanished.

### Context

7596344-zd-a8c

### Other notes

One of the latest examples: 7596344-zd-a8c

Another one found by @Agepeuve here: p1705994257476489/1705993750.123789-slack-C03TY6J1A

Potentially related issues/merges:

https://github.com/Automattic/newspack-blocks/issues/399
https://github.com/Automattic/jetpack/pull/34805

I suspect this has Varia also as a common factor, but I can't confirm this yet.

I'll add the previous cases a bit later.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

The solution was to enable "Display images on pages" from Appearance > Customize > Content options. 

cc @Automattic/dotcom-product-ambassadors

**Comment by Aurorum** [comment]
https://github.com/Automattic/jetpack/pull/34805 was unintentionally reverted on Atomic sites, but this should now be fixed: https://github.com/Automattic/wp-calypso/issues/59280#issuecomment-1906697892.

**Comment by rickmgithub** [comment]
Issue resolved above. Please feel free to re-open if new issues are found.
