### ISSUE TITLE
Creatio 2 Bug: Form Button Text is incorrectly aligned

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#7635]
### Quick summary

On the Creatio 2 theme on atomic sites only, the form block's button text alignment is not respected.

### Steps to reproduce

1. On an **atomic** site, create a new page
2. Add a form block
3. In the form block's button block, adjust the width setting to 100%
4. Publish the page.

### What you expected to happen

I expected the button text to be centered.

### What actually happened

The button text is left aligned
![Screenshot 2024-02-04 at 17 11 21](https://github.com/Automattic/themes/assets/30727666/867d25d3-e85f-4baf-a072-323ade3b057b)

### Context

#7659692-zen

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

CSS fix:

```
button.wp-block-button__link {
  justify-content: center;
}
```

**Comment by cat-og** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic –  Could Not Replicate

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)
