### ISSUE TITLE
[Bug]: Bute Theme missing index.php 

### ISSUE THREAD

**Issue by hartonoda** [Automattic/themes#7644]
### Quick summary

When I install the theme wordpress says it's missing index.php

I tried to add a blank index.php but when I activated the theme all I got is a blank page

### Steps to reproduce

1. Install the theme it says missing index.php
2. created a blank index.php
3. installation successful
4. activate theme it shows blank white page

### What you expected to happen

Theme setup properly

### What actually happened

Blank page

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Simple – Uncertain
– Tested on Atomic – Uncertain

📌 FINDINGS/SCREENSHOTS/VIDEO
Unbale to reproduce the issue based on the information provided

📌 ACTIONS
– Requested author feedback

📌 Message to Author
Hi @hartonoda 👋 

Your bug report is incomplete. Please provide more details about the issue. What kind of WordPress.com subscription do you have? Did you check the theme zip file if it's not missing the index.php, before the upload?

**Comment by liviopv** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Simple: activated the theme, navigated to the site editor, everything works as expected
- Atomic: activated the theme, navigated to the site editor, everything works as expected
- Local: installed the theme, navigated to the site editor, everything works as expected


📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
@hartonoda please reopen if you have more information to share.
