### ISSUE TITLE
Sophisticated Business: Reduce the line height for cover image text

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#766]
Because of the large font size, the line height of `1.25` throw it off a little.

Currently:
<img width="934" alt="Screen Shot 2019-05-01 at 01 09 57" src="https://user-images.githubusercontent.com/908665/57000931-e4951300-6bad-11e9-98b1-f2960b71fd23.png">

With `line-height: 0.9;`
<img width="923" alt="Screen Shot 2019-05-01 at 01 11 58" src="https://user-images.githubusercontent.com/908665/57000994-2aea7200-6bae-11e9-937b-9812f49fa84e.png">

**Comment by torres126** [comment]
Is this change something for just the sign up in Calypso, or is it a change to be made for all sites using the theme?

**Comment by iamtakashi** [comment]
For all sites, please.

**Comment by iamtakashi** [comment]
Looked into this more. The line height appears to be too tall as we see in the first screenshot, but it was just due to the words in there :) When the heading contains descenders or apostrophes, it looks just fine.

<img width="1106" alt="Screen Shot 2019-05-07 at 17 14 20" src="https://user-images.githubusercontent.com/908665/57340429-9e9bfa00-712d-11e9-83b9-e03e4fbc97ea.png">

On that basis, I'm closing this for now.
