### ISSUE TITLE
[Bug]: Site title block color can't be changed on Eventual theme 

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/themes#7666]
### Quick summary

Changing the site title block color does not affect the frontend.

### Steps to reproduce

1. Use Eventual theme
2. Change the site title color in the template editor
3. Notice that it looks fine in the editor
4. But in front-end, the color is not updated (always blue)

### What you expected to happen

For color to change based on template edits.

### What actually happened

The color is always Blue for the site title block.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Context

7826992-zen

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Editor:

![image](https://github.com/Automattic/themes/assets/129587477/eae87ef0-c7ab-4177-9c3b-2862ff9774b5)

Frontend:
![image](https://github.com/Automattic/themes/assets/129587477/06273dc1-ec2a-4c7d-a49e-4005fc8c7b44)

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

CSS workaround is possible.

**Comment by mdtanjid0** [comment]
Similar case here:

- [ ]  7831131-zen (needs to be followed up)

Theme: Byrne

As a workaround, I shared this custom CSS: 

```
/* Adjust heading color bug - themes-issues-7666 | ( 7831131-zen ) MT */

.home .wp-block-cover h2 a{
    color: #FFF;
}
```

**Comment by Neha93517** [comment]
Same issue here: 7829689-zen
Theme: Eventual

**Comment by Jaykame** [comment]
Similar issue with 7837114-zen
Theme: Kigen
Platform: Simple site

Previously, CSS was given as a workaround.

**Comment by filipanoscampos** [comment]
📌 REPRODUCTION RESULTS

– Tested on Simple: Replicated 
– Tested on Atomic: Replicated  when the Gutenberg plugin is active only


📌 FINDINGS
Probably related to another bug, https://github.com/Automattic/wp-calypso/issues/88107#top


📌 ACTIONS
Report kept.

**Comment by dsas** [comment]
Can't reproduce, probably related to the [bug](https://github.com/Automattic/wp-calypso/issues/88107#top)  @filipanoscampos mentioned, which has also been resolved.
