### ISSUE TITLE
Creatio 2 theme DuoTone filter not working on mobile video header.

### ISSUE THREAD

**Issue by radtechgh** [Automattic/themes#7675]
### Quick summary

Creatio 2 theme, add Duotone filter to Cover block with video background. Duotone filter is not working when viewing on mobile, but it does on desktop.

### Steps to reproduce

1. Add Creatio 2 theme to site.
2. Add Video header pattern to header.
3. Add Duotone filter to Cover block with video background.
4. view on desktop.
5. view on mobile

### What you expected to happen

Duotone filter should show on both desktop and mobile.

### What actually happened

Video shows without any filter on mobile.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by radtechgh** [comment]
7826401-zen

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate 
- Tested on Atomic – Could Not Replicate 

## 📌 ACTIONS ##
- Author feedback
- Closed as could not replicate (please reopen if the issue reoccurs) 

##Message to author##
Thanks so much for the report. I couldn't replicate the issue with the same set up. Are you still able to produce this on a number of sites? Feel free to reopen if you can still replicate.
