### ISSUE TITLE
P2: sidebar widgets not displayed on mobile

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/themes#768]
The P2 theme does not display sidebar widgets underneath content on posts or pages, when viewing a site on a mobile device.

## Steps to replicate

With the P2 theme activated:
1. Go to My Sites > Manage > Settings > Writing
2. Scroll down to "Theme Enhancements" and toggle off that option
3. Go to My Sites > Design > Customise > Widgets
4. Select "Sidebar"
5. Add a widget (the number and type are irrelevant)
6. Publish
7. View the site on a mobile

## Result

No widgets are displayed below the content on posts or pages — they disappear.

## Expected

Widgets to move displayed underneath the content.

* User report: https://en.forums.wordpress.com/topic/layout-da-pagina-nao-se-ajusta-automatico-exemplo-celular/

**Comment by cathymcbride** [comment]
retired theme. Closing...
