### ISSUE TITLE
Apostrophe 2: No way to remove italics from image captions

### ISSUE THREAD

**Issue by cuemarie** [Automattic/themes#7701]
### Quick summary

Image captions are all italicized by default in theme Apostrophe 2; Gutenberg offers block tools to add bold or italics to captions, but this has no impact on the italicization of captions since it's there by default.  This means customers can only remove that italicization with CSS.

### Steps to reproduce

1. Activate **Apostrophe 2** on a WordPress.com site
2. On a page, add an image with a caption. (Observe the caption is italicized).
3. Try making the caption not italicized.

### What you expected to happen

For there to be any control over the italicized captions, especially given the block tools. 

### What actually happened

The block tools cannot remove italicization from the image captions. 

![CleanShot 2024-03-25 at 12 05 11@2x](https://github.com/Automattic/themes/assets/27249804/b59ee604-7126-4bf7-b929-be3aa5d54fa0)

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

![CleanShot 2024-03-25 at 12 04 00@2x](https://github.com/Automattic/themes/assets/27249804/dbcc8698-711e-4e0b-abe6-7a965fdb03cc)

Inspecting the image captions shows the following CSS being applied:

```
[class^="wp-block-"] figcaption {
  font-style: italic;
```

---

Customer report was on an AT site; I replicated on my own Simple Site

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

```
/* remove italicized captions with no-italics class | xxx-zen */
.no-italics .wp-element-caption {
    font-style: normal !important;
}
```

Then adding `no-italics` as an additional class to images, galleries, or groups containing either.

**Comment by cuemarie** [comment]
Customer Report: 7941491-zen

This customer did not want to use CSS to workaround, so they're rebuilding their content instead.  They would like a follow up if we resolve this. (feel free to ping me here or in slack if you close/fix, and I can follow up with them). Thanks!

**Comment by maciejpilarski** [comment]
📌 REPRODUCTION RESULTS
– Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to reproduce the issue.

📌 ACTIONS
– triaged

**Comment by Aurorum** [comment]
I'm not really sure how to go about this. Ideally, any changes wouldn't apply retrospectively and force users to re-italicise their captions. That could mean adding a setting in the Customizer to give users control of this, but that feels a little overkill for one request?

V curious for thoughts on different approaches here!

**Comment by mmtr** [comment]
Yeah, this one is not easy to address without affecting existing sites using this theme.

I agree that the italic controls in the block toolbar are confusing if they are enforced by the theme, but considering the low volume of users affected (we're only aware of just one case), I think I'll close this one for now.

We can re-evaluate later if needed.
