### ISSUE TITLE
Theme Adventurer: Demo content "Search" placeholder text

### ISSUE THREAD

**Issue by ezebecke** [Automattic/themes#7704]
### Quick summary

The value on the placeholder in the "Search" block demo content looks like "E.g. &quot;Botswana&quot;" on the editor.

I expect the value to be read as **E.g. "Botswana"** instead.

### Steps to reproduce

Active "Adventurer" theme and go to the theme editor. Scroll down to check the Search block.

### What you expected to happen

Search should read **E.g. "Botswana"**

### What actually happened

It reads as **E.g. &quot;Botswana&quot;**

![CleanShot 2024-03-27 at 11 05 03](https://github.com/Automattic/themes/assets/24919469/751a5237-c3ea-4209-906e-3f7523c7c85f)

Live view looks fine.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by rcrdortiz** [comment]
The issue is now solved.
