### ISSUE TITLE
Lativ theme: Adding "Pricing with two options" pattern crashes the page editor, throws blank screen in Site Editor on simple sites

### ISSUE THREAD

**Issue by zyousafi** [Automattic/themes#7705]
### Quick summary

With the Lativ theme active on my simple site, the page editor crashes when I add the "Pricing with two options" pattern.  When I add the pattern within the Site Editor, the screen goes blank

### Steps to reproduce

For Page Editor:

1. Activate Lativ theme on site
2. Open page editor by navigating to the "Pages" section of the dashboard and opening any page for editing
3. Click on the "plus sign", search for "Pricing with two options" pattern
4. Add "Pricing with two options" pattern to page

For Site Editor:

1. Activate Lativ theme on site
2. Open Site Editor by going to "Appearance > Editor" and then opening any template for editing
3. Click on the "plus sign", search for "Pricing with two options" pattern
4. Add "Pricing with two options" pattern to page

### What you expected to happen

I expected the "Pricing with two options" pattern to be added to the page or template

### What actually happened

In the page editor, I see the following error: `The editor has encountered an unexpected error.`

In the Site Editor, the screen goes blank and I have to refresh to get back to the editor; the changes aren't saved so I have to start back up again

### Browser

Google Chrome/Chromium

### Context

Customer report 7955012-zen

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Issue is on simple sites only; the "Pricing with two options" template is added on Atomic sites without any issues

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Could Not Replicate

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
* Spoke to OP as I couldn't find the "Pricing with two options" pattern. They also couldn't find it now. 
* I also couldn't find it here - https://wpcalypso.wordpress.com/patterns?s=Pricing+with+two+options
* Tried adding all the patterns with the name "pricing" but no error found. 
* OP found a screenshot

![Image](https://github.com/Automattic/themes/assets/13706336/bf626ca6-354a-4953-8217-987530a7c1ef)

* But as we're unable to currently replicate, closing. 

## ACTION ##
- Closed as could not replicate (please reopen if the issue reoccurs)
