### ISSUE TITLE
[Bug]: Page/Post title misalignment on Cubic theme

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/themes#7745]
### Quick summary

Page/Post title is aligned left on the editor, but on the front-end, the title is aligned center.

### Steps to reproduce

1. Activate Cubic theme
2. Create a page/post
3. Notice the title is left aligned by default in the editor
4. After publishing/updating the page/post, the title is center-aligned

### What you expected to happen

The title is to be aligned left. 

![image](https://github.com/Automattic/themes/assets/129587477/be2b40ce-12fc-4689-8835-0df71bbcf0ea)

### What actually happened

The title is center-aligned.

![image](https://github.com/Automattic/themes/assets/129587477/b79aa2f8-0697-4623-bb4a-95127eebd60a)

### Browser

Mozilla Firefox, Microsoft Edge, Apple Safari, iOS Safari, Android Chrome

### Context

8042205-zen

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Yes, easy to implement

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
Exactly as OP describes.

## 📌 ACTIONS ##
Triaged

**Comment by donnapep** [comment]
PR is here - 156509-ghe-Automattic/wpcom-themes

**Comment by jp-imagines** [comment]
@donnapep The theme's documentation (https://wordpress.com/theme/cubic) has sample screenshots from when the theme was first created showing that the titles of individual posts (and the titles on the default grid homepage) are intended to be centered.

The title in the post editor is _always_ left aligned to my knowledge, regardless of the theme's front-end design. (I could be wrong on that.) It seems to me this bug report may have been a misunderstanding of the theme's intended design and how that interacts with the appearance in the editor.

We also have a report from a user now concerned that post titles (especially on the homepage) are _not_ centered as they should be: 9177794-zd-a8c

Would it be worth reverting this PR?

**Comment by donnapep** [comment]
> Would it be worth reverting this PR?

@jp-imagines Yup, I can revert if you feel this issue was triaged in error.

**Comment by donnapep** [comment]
Reverted in 156515-ghe-automattic/wpcom-themes.

**Comment by jp-imagines** [comment]
Thanks @donnapep! I appreciate the speedy revert. 🙁

**Comment by aisajib** [comment]
Just adding that this came up on a user report here: 9174792-zd-a8c 

No further actions are necessary, as the user is happy that the title is center-aligned as before. :) ;
