### ISSUE TITLE
[HC] Radcliffe 2: Drop-down arrow on mobile menu has disappeared

### ISSUE THREAD

**Issue by caitlindawn** [Automattic/themes#7753]
### Quick summary

User reports that there used to be a drop-down arrow on the primary when viewed on mobile mode, but it has disappeared.

Able to replicate this on my simple and atomic test sites. #hc 

### Steps to reproduce

1. Activate Radcliffe 2.
2. Create a navigation menu and assign it to the site header.
3. Open the site on mobile.
4. Tap on the navigation menu to open it.

### What you expected to happen

The drop-down arrow should appear beside "Menu"

### What actually happened

There is a space on the left of "Menu" where the drop-down arrow reportedly used to be:
<img width="417" alt="image" src="https://github.com/Automattic/themes/assets/15062795/8e952ed2-044a-4a87-ad50-ac177a823c42">

### Context

8022233-zd

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by rickmgithub** [comment]
Related to https://github.com/Automattic/themes/issues/7744#issuecomment-2073437517
Closing in favour of that.
