### ISSUE TITLE
Payton: Default and Wide Line Separator block styles don't work

### ISSUE THREAD

**Issue by cecilearkay** [Automattic/themes#7774]
### Quick summary

The Default and Wide Line Separator block styles do not work. The only way to display the Separator block is to use the Dots styles.

### Steps to reproduce

1 - Activate the Payton theme.
2 - Create a page and add a Separator block.
3 - Try to use either the Default or Wide Line style.
4 - You'll see it displays in the editor as expected.

<img width="1505" alt="Markup 2024-04-26 at 20 23 24" src="https://github.com/Automattic/themes/assets/16645645/5aaa12d1-c3ae-46d6-af44-d631650fbabd">

5 - Publish the page and check it on the live site to see the Separator line isn't showing.

![Annotation on 2024-04-26 at 20-28-25](https://github.com/Automattic/themes/assets/16645645/f289d9a6-5e9b-4216-b48b-bb8ffab8d52d)

### What you expected to happen

I expected the line to display with all styles and not just the Dots style.

### What actually happened

The line from the Separator block doesn't show if it's the Default or Wide Line styles.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Yes, easy to implement

### Workaround details

It can be fixed with some CSS, such as:

```
.wp-block-separator {
    border-width: 2px;
}
```

**Comment by rickmgithub** [comment]
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated  
- Tested on Atomic – Replicated 


## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
Problem is exactly as OP says.
However on Simple sites, it doesn't show if it's set as default as well.

https://github.com/Automattic/themes/assets/13706336/c7292e12-c41c-46e4-a965-81b138cb0c53

There was a similar issue that was closed sometime ago - https://github.com/Automattic/themes/issues/5727

## 📌 ACTIONS ##
Very similar case here - https://github.com/Automattic/wp-calypso/issues/60108
Closing in favor of that case.
