### ISSUE TITLE
Dara: Update colour annotation to account for button block

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#781]
## Steps to replicate

- Using the block editor, add a button block to a page or post

- In the Customizer's Colors & Palettes panel, click "Palettes"
- Click the default turquoise circle and select another colour, like red

![Customize_ kpgutentester – and a tagline](https://user-images.githubusercontent.com/7662449/57229145-625c8280-6fe3-11e9-86d1-47c83cf480ee.png)

## Result

- The button remains the theme's default turquoise

![Excerpt Test – kpgutentester](https://user-images.githubusercontent.com/7662449/57229044-317c4d80-6fe3-11e9-92f9-a6c408a3a330.png)

## Expected

The button should take on the colour selected in the Customizer 

* Discovered during a WordPress.com Business Concierge session, no user follow-up needed

**Comment by danieldudzic** [comment]
Hi @kathrynwp,

This doesn't seem to be a bug.

When using Gutenberg, all Block color changes should be made via the editor (even if that's not possible just yet).

For Buttons, you can use the Block color settings.
![button](https://user-images.githubusercontent.com/905781/69193560-4a83c080-0b27-11ea-82f5-aa47364b1770.jpg)

The Customizer Colors & Palettes options are not really compatible with the Block editor.
