### ISSUE TITLE
All Business Theme Variations: Add HEX Color Picker

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#783]
## Steps to replicate

Applies to the themes Professional Business, Sophisticated Business, Elegant Business, Friendly Business, Calm Business, Modern Business.

1. Go to Customize → Colors
2. Select Custom as the Primary Color
3. Observe the color slider

There is no option to set an exact color with a HEX code. A HEX code input would be useful for site owners who have a specific brand guideline for their business that requires them to use specific colors. At the moment, site owners can only use the slider to get an approximate color that is not exact.

![Screen Shot on 2019-05-07 at 10_30_37](https://user-images.githubusercontent.com/30727666/57263189-390b2780-70b3-11e9-930a-eb7fc2e0f0bc.png)

* User report: #12584074-hc

**Comment by cathymcbride** [comment]
retired themes. Closing.
