### ISSUE TITLE
Coherent: Links Not Distinguishable

### ISSUE THREAD

**Issue by donalirl** [Automattic/themes#784]
## Steps to replicate

1. Open a free or Personal plan site with the Coherent theme
2. Create a page or post with some hyperlinked text
3. Go to Customize → Colors & Backgrounds and try all the color palettes available

## Result

Hyperlinked text is not in any way distinguishable with any of the available color palettes. A reader does not see that the text is a clickable link. The site owner has no option available on the free or Personal plan to make links distinguishable with another color.

![Annotation on 2019-4-2](https://user-images.githubusercontent.com/30727666/57266639-34993b80-70c0-11e9-818c-5d49103c9e08.png)
See this screenshot:  https://cld.wthms.co/3oVwYi

## Expected

As a site owner, I expected my text links to be visually obvious.

* User report: #2010765-zen

**Comment by danieldudzic** [comment]
@donalirl This has now been fixed in https://wpcom-themes.trac.automattic.com/changeset/54570
