### ISSUE TITLE
Baskerville 2: CSS broken for buttons - Follow Blog Widget and Contact Form

### ISSUE THREAD

**Issue by benchilcote** [Automattic/themes#785]
## Steps to replicate

1. Activate Baskerville 2 theme
2. Create a contact form and add a Follow Blog widget

## Result

The button style seems to be missing for each submit button for these 2 elements.  The "Older Posts" button does not seem to be broken.

![Annotation on 2019-4-2](https://user-images.githubusercontent.com/11636210/57298309-e116f580-709f-11e9-9718-eb01a793cbe9.png)

![Annotation on 2019-4-2(1)](https://user-images.githubusercontent.com/11636210/57298327-ed9b4e00-709f-11e9-9f89-64c0e419265c.png)

## Expected

I expected the buttons to be styled.

## Temporary Workaround

I provided this CSS that was grabbed from the original style sheet to apply manually, though it is not the complete code for buttons

> .pushbutton-wide, button {
> 	background: #3f4854;
> 	border: none;
> 	border-radius: 3px;
> 	color: #fff;
> 	font-family: "Roboto Slab", sans-serif;
> 	font-size: .9rem;
> 	line-height: 1;
> 	margin: 0;
> 	padding: 12px 16px;
> 	-webkit-appearance: none;
> }

* User report: #12439789-hc
* Follow-up ticket: #2011781-zd

**Comment by davipontesblog** [comment]
Another report here #3839617-hc. This is also true for Mailchimp subscription block in block editor, so I would think it's a styling issue for all buttons.

**Comment by adelineyaw** [comment]
Another report via #16421334-hc for unstyled CSS on the Contact Form for three sites.
Follow up ticket: #2472517-zd

**Comment by adelineyaw** [comment]
@benchilcote Thanks for providing the CSS as a temporary fix. I've also added the below to the CSS: 
`
cursor: pointer;
`

**Comment by eoinsav** [comment]
Reported in #23593533-hc

**Comment by philnick206** [comment]
Almost exact same issue reported with Blog Posts block in #4711112-zen

**Comment by davipontesblog** [comment]
@Robertght could you do a quick analysis of customer impact (number of sites using this Theme) on this one for wpcom please? @jordesign can lend a hand if you need any assistance.
Then we can probably prioritize accordingly with the Themes team once we have a better idea of customer impact here. Thanks!

**Comment by Robertght** [comment]
It looks like Baskerville 2 has 647,947 active installations at the moment and there are 26 open issues [open](https://github.com/Automattic/themes/milestone/44).

**Comment by davipontesblog** [comment]
> It looks like Baskerville 2 has 647,947 active installations at the moment and there are 26 open issues open.

Thanks @Robertght ! 

@jordesign I added the `Pri:High` label here, could you help bring this to Themes attention to prioritize in upcoming bug maintenance run?

**Comment by Robertght** [comment]
I pinged here: p1643188298169000-slack-C029FM1EH

**Comment by jffng** [comment]
Patch is ready for review in D74087-code.

**Comment by pbking** [comment]
Made a change in the patch to include `wp-block-button__link` class and pick up block buttons.  

Before:
<img src="https://user-images.githubusercontent.com/146530/151866038-d53d3c02-b9f4-467c-a7c5-23a920fa6918.png" width=300>

After:
<img src="https://user-images.githubusercontent.com/146530/151865877-47c2bb10-fb3a-4b61-b8bf-46d7a0ec1caf.png" width=300>

**Comment by jffng** [comment]
Committed in D74087-code, thanks everyone for reporting and triaging.
