### ISSUE TITLE
HTTP 500 error when trying to edit page/post with Spearhead (Classic) theme active

### ISSUE THREAD

**Issue by rw-ye** [Automattic/themes#7852]
### Quick summary

Currently, there is an issue preventing the page/post from being edited on simple sites when the [Spearhead (Classic)](https://wordpress.com/theme/spearhead/) theme is active.  When trying to edit a post/page, a `HTTP 500` error is displayed instead. 

https://github.com/Automattic/themes/assets/21261509/b6357711-4400-46a8-9de4-b3cc8c9896c1

### Steps to reproduce

1. Activate Spearhead (Classic). 
2. Try to edit any page/post
3. A `HTTP ERROR 500` is shown instead.

### What you expected to happen

To be able to edit the selected page/post, or create a new page/post.

### What actually happened

HTTP 500 error.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Workaround details

The Spearhead block theme works without issues.

**Comment by rw-ye** [comment]
Reported in forums: 8322700-zd-a8c

**Comment by vcanales** [comment]
Fixed in https://github.com/Automattic/themes/pull/7853, and delpoyed.

Would appreciate a confirmation.

**Comment by rw-ye** [comment]
@vcanales  Looks good to me! I tested on my simple site and I can edit pages/posts now :)

Thank you!
