### ISSUE TITLE
Lingonberry: Blockquotes in Comments don't have CSS styling 

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#786]
## Steps to replicate

Add a blockquote to a comment on a site using the Lingonberry theme.

## Result

There is no CSS styling on the blockquote:

![img](https://cld.wthms.co/sh6ifP+)

## Expected

You would expect to see CSS styling to make it different than the regular comment text. 

* User report: #225204-hc

**Comment by danieldudzic** [comment]
Hi @mikeicode,

Thank you for reporting.

This has now been fixed in r54704.
