### ISSUE TITLE
Hybrid themes with Global Styles: custom border images not displayed on the front end

### ISSUE THREAD

**Issue by jartes** [Automattic/themes#7896]
### Quick summary

This issue comes from this one, which is similar to #7873. 

When adding a custom border to an image with the block editor, it is displayed in the editor but not on the site's front end. 

This is happening with Hybrid themes with Global Styles support.

### Steps to reproduce

1. Make sure the site is using a hybrid theme.
2. Create a new post or page. 
3. Add an image
4. Add a border to it.

### What you expected to happen

Seeing the image on the live site with the border set displayed in the editor.

### What actually happened

The border from the image is not being displayed

![Markup on 2024-06-25 at 15:57:26](https://github.com/Automattic/themes/assets/1046943/023ef711-4416-49d7-bfb5-3ffce5736775)

![Markup on 2024-06-25 at 15:57:50](https://github.com/Automattic/themes/assets/1046943/bb2dc287-51b8-4c6d-8aaa-c7107daea9c8)

### Browser

Google Chrome/Chromium

### Context

Related issue and customer report

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

This can be fixed with some custom CSS code, but as this is affecting the `border-style` property, it will depend which type of border has been set. 

For example, if the border is the default one, the following CSS should work for images in post content: 
```
.entry-content .img {
    border-style: solid;
}
```

**Comment by jartes** [comment]
8326462-zd-a8c
8377644-zd-a8c

**Comment by miksansegundo** [comment]
I'll look into this later.

It seems that Varia theme is removing the border from images in https://github.com/Automattic/themes/blob/fea811917b84a1b40b67f8a1ff149cd3ad43403f/varia/style.css#L371

**Comment by miksansegundo** [comment]
Hi, I have just deployed a fix and confirmed it's fixed.

|EDITOR|FRONT SITE|
|-|-|
|<img width="1325" alt="Screenshot 2567-07-03 at 19 10 35" src="https://github.com/Automattic/themes/assets/1881481/b26f2ba1-d06d-4b5d-83e0-665bc53c0a83">|<img width="845" alt="Screenshot 2567-07-03 at 19 10 23" src="https://github.com/Automattic/themes/assets/1881481/03335a1c-5b1c-43f0-a154-0cf7dcfbc895">|
