### ISSUE TITLE
Stage: Color conflicts when switching theme style variations

### ISSUE THREAD

**Issue by richtabor** [Automattic/themes#7922]
The colors applied to blocks within the home page are not changing when you change a style variation. 

The colors should be moved and any changes necessary (say to links etc) would be best applied within the theme style variations; not the blocks. 

### Steps to replicate

Change theme style variations from the Site Editor, then view the home page. 

### Result

The colors applied to the columns on the home page are not adapting: 

![CleanShot 2024-07-03 at 11 16 21](https://github.com/Automattic/themes/assets/1813435/d4c5d8b9-2fc6-4047-be79-a58f58c0d126)

![CleanShot 2024-07-03 at 11 17 35](https://github.com/Automattic/themes/assets/1813435/ba9fda81-39b8-4fba-b9c5-320cbb5f1c7e)

### Expected

https://github.com/Automattic/themes/assets/1813435/0b9ea275-6dc4-44f4-9f9e-6fa5c0ff8da7

**Comment by richtabor** [comment]
![CleanShot 2024-07-03 at 11 42 04](https://github.com/Automattic/themes/assets/1813435/2712eaeb-65ed-4331-8582-10173d528f05)

**Comment by alaczek** [comment]
Stage has an updated version called OutNow, which fixes this issue.
We will be delisting Stage shortly.

**Comment by richtabor** [comment]
Will Stage remain in the repo here? Curious how this is all maintained. :)

**Comment by alaczek** [comment]
Yes, it will. We sync this with .com, and can't remove it there, because we have customer sites running on it.

**Comment by lsl** [comment]
Fixing this might be a breaking change for some users. If the theme is de-listed and a fix is in another theme I don't see any reason to work on this.
