### ISSUE TITLE
Error 500 when trying to edit post/pages in Seedlet theme

### ISSUE THREAD

**Issue by sanjeev00733** [Automattic/themes#7937]
### Quick summary

There is currently an issue preventing the editing of pages or posts on simple sites when the [Seedlet](https://wordpress.com/theme/seedlet/) theme is active. Attempting to edit a page or post results in an HTTP 500 error being displayed.

### Steps to reproduce

1. Activate Seedlet theme in any simple site
2. Try to edit any page/post
3. A HTTP ERROR 500 is shown instead.

### What you expected to happen

To be able to edit the page/post

### What actually happened

HTTP ERROR 500 is shown

### Context

Customer report 

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by radtechgh** [comment]
8453959-zen

**Comment by janmckell** [comment]
8452721-zd-a8c
