### ISSUE TITLE
Multiple themes: Remove copyright symbol

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#7970]
A few of our themes have a copyright and date inserted in the footer, as outline here: pekYwv-4ok-p2
This issue is to consolidate this task in one place.

The affected themes: https://github.com/search?q=repo%3AAutomattic%2Fthemes+%C2%A9+language%3APHP&type=code&l=PHP

- [x] Vitrum
- [x] Fontaine
- [x] Pendant
- [x] Bitacora
- [x] Jaida
- [x] Upsidedown
- [x] Course

**Comment by dsas** [comment]
Opened https://github.com/Automattic/themes/pull/7981 to deal with Course and Upside Down - they're the simplest cases as the copyright statement there didn't make any sense.

I'm not 100% clear on what we want to do with the others. Just remove the year (Fontaine, Pendant, Jaida, Bitacora), or remove the copyright para altogether (+vitrum)?

**If** removing the copyright para completely, then I think we'll want "Designed with WordPress" aligned differently, I've made suggestions below but maybe a design eye would have a better suggestion.




Theme | Design | Suggestion
-------|------|-----
Vitrum | <img width="1461" alt="Screenshot 2024-07-30 at 18 30 22" src="https://github.com/user-attachments/assets/548586b6-1cb0-4c9e-a1f5-1d160b185819"> | Move "Designed with" in place of copyright
Fontaine | <img width="731" alt="Screenshot 2024-07-30 at 18 33 13" src="https://github.com/user-attachments/assets/525ef6f3-1848-44d0-b50b-d4fbb04a86f3"> | Just remove copyright, leave everything else where they are.
Pendant | <img width="731" alt="Screenshot 2024-07-30 at 18 56 32" src="https://github.com/user-attachments/assets/6c999acf-2dcc-41ea-be94-dd2a3d4882d3"> | Just remove copyright, leave "Powered by" where it is
Bitacora | <img width="731" alt="Screenshot 2024-07-30 at 18 57 10" src="https://github.com/user-attachments/assets/4ca84b3a-bc07-4f80-8e04-416930459ac8"> | Centre align "Designed with"
Jaida | <img width="1461" alt="Screenshot 2024-07-30 at 18 31 34" src="https://github.com/user-attachments/assets/4ce19faf-7ffe-4892-861a-a28e317ca43e"> | Maybe center align "Designed with..." in the same row as the site title and social icons

**Comment by alaczek** [comment]
Your suggestions all make sense to me. I tapped @henriqueiamarino for his thoughts too.
With Jaida, I think we can't really go wrong. If in doubt I'd leave the "Designed with" where it is on the right and just remove the copyright, just so we're not changing the design.

**Comment by henriqueiamarino** [comment]
Regarding Vitrum, that's fine, @dsas and @alaczek. That's precisely how I am using in the Dotorg version. By the way, I created [Vitrum](https://wordpress.org/themes/vitrum/) to replace the existing Dotcom [Vetro](https://wordpress.com/theme/vetro). We don't need both in the trunk.
