### ISSUE TITLE
CELSIUS infinite scroll doesn't seem to work

### ISSUE THREAD

**Issue by DavidSaladu** [Automattic/themes#7983]
### Quick summary

The celsius theme has infinite scroll but doesn't seem to work and only displays the listed posts. If infinite scroll is disabled the button to load more posts appears but doesn't work either.

### Steps to reproduce

1. Create a site with a certain amount of posts (the issue was requested from the razonypolitica.org site which can be checked as example). 
2. Toggle ON infinite scroll through settings -> writing and check the page, once the amount of posts set up to be displayed is reached, no further posts will be loaded even if scrolling down.
3. Toggle OFF infinite scroll through settings -> writing and check the page, once the amount of posts set up to be displayed is reached, the load older posts button will appear but nothing will happen once clicked.

### What you expected to happen

In step 2, 7 additional posts should be loaded once the bottom of the page is reached.
In step 3 7 additional posts should be listed once the button is clicked.

### What actually happened

Nothing, there's a glimpse of something loading but nothing actually changes.

### Browser

Google Chrome/Chromium

### Context

Issue https://wordpress.com/es/forums/topic/falla-scroll-infinito/?view=all

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent, with other themes the options behave normally (tested with twenty seventeen)

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Showing more posts directly could be considered a workaround maybe.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I'm getting the following JS error in the console:
![xuk3p5.png](https://github.com/user-attachments/assets/f4c0d68a-9940-4b56-b17b-8ff763ae2b6f)

📌 ACTIONS
- Triaged
- Added priority

**Comment by mpkelly** [comment]
I have reproduced this just now. I am almost done for the day but can continue with it tomorrow unless someone else picks it up.

**Comment by arthur791004** [comment]
Proposing D159434-code & github-a8c-156379 to resolve the issue!

**Comment by miksansegundo** [comment]
Fix Deployed 🚀
