### ISSUE TITLE
Libre 2: Unable to completely hide footer credits for lang de-DE 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#8]
Originally reported by @donalirl in 4825-wpcom-themes:

## Steps to replicate

1. Test on a site using Libre 2 and a Business account.
2. Change the language to German.
3. Go to the Customizer and try to hide the footer credit.

## Result

The footer credit still displays.

## Expected

The footer credit should be hidden like it is when the site's in English.

The footer credit is currently being hidden using Custom CSS.

* User report: 691336-zd
* User's site: https://pharmakotherapie.blog

**Comment by nielslange** [comment]
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883
