### ISSUE TITLE
Assembler: patterns don't load while on self-hosted

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#8001]
## Steps to replicate

This is what I get with Assembler when it's active on self-hosted

## Result

![oPUnqP.png](https://github.com/user-attachments/assets/54b6bf3c-8993-4291-aa87-0bdb54596c0a)

## Expected

To see something similar to 2024:

![1tQfVZ.png](https://github.com/user-attachments/assets/62bfdf87-07c6-45b9-8f37-e46a757db819)

* User report: 8581809-zen
* Follow-up ticket: 8581809-zen

**Comment by dsas** [comment]
As discussed on slack:
This is expected. Unlike TT4, the Assembler theme doesn't include any patterns itself. The patterns you see when using Assembler on WordPress.com come from the shared dotcom pattern library which is also available on the web via wordpress.com/patterns.
