### ISSUE TITLE
Twenty Nineteen (and/or child themes): Add support & theme option for featured image captioning

### ISSUE THREAD

**Issue by mdrovdahl** [Automattic/themes#801]
## Proposal
The featured image is set into a `<figure class="post-thumbnail">...</figure>` element and could display a `<figcaption>` if support were added. Ideally, this could be toggled via the Customizer, perhaps by expanding the scope of the "Colors" menu to be "Colors & Images" (added benefit of using "Images" here is to provide users with yet another clue that this is the menu item under which one toggles the featured image overlay filter).

I suppose in an ideal world this would go into TwentyNineteen...but, perhaps it is also achievable via a filter in a child theme similar to the proposal in https://core.trac.wordpress.org/ticket/45945 but filtering `twentynineteen_post_thumbnail()` ([ref](https://themes.trac.wordpress.org/browser/twentynineteen/1.4/inc/template-tags.php#L142)) ?  

@kjellr perhaps this belongs better in https://core.trac.wordpress.org?

**Comment by kjellr** [comment]
👋 Yeah, this would be better placed on Trac if you don't mind. Some themes do support captioned featured images, but unfortunately it's not super common.

**Comment by mdrovdahl** [comment]
Closing in favor of a core trac ticket (to be created).
