### ISSUE TITLE
Alves: Update Twitter Logo

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/themes#8025]
### Quick summary

Alves is still showing the Twitter logo when a link to an X profile is added to the Social Links menu.

### Steps to reproduce

1. Go to Appearance > Menus. 
2. Select or create a Social Links menu.
3. Add a link to an X profile, for example,  https://x.com/wordpressdotcom
4. See issue.

### A clear and concise description of what you expected to happen.

An X logo should appear.

### What actually happened

An old Twitter logo shows instead.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Context: 8580230-zen

**Comment by TimBroddin** [comment]
📌 REPRODUCTION RESULTS

I could reproduce this.

📌 FINDINGS/SCREENSHOTS/VIDEO

This also happens on other Varia based themes. This is a list of themes I've found: Alves, Balasana, Barnsbury, Brompton, Coutoire, Dalston, Exford, Hever, Leven, Mayland, Maywood, Morden, Redhill, Rivington, Rockfield, Shawburn, Stow, Stratford, Varia

Fixing it should be easy: just update the icon in this file: https://github.com/Automattic/themes/blob/0c65de7f192ac26f39a3550c4160163ae4ffba98/varia/classes/class-varia-svg-icons.php#L356

📌 ACTIONS
Triaged

**Comment by TimBroddin** [comment]
@Automattic/t-rex Could you or someone else from Marvel take a look at this?

**Comment by miksansegundo** [comment]
I'm looking into this now

**Comment by miksansegundo** [comment]
Ready for review https://github.com/Automattic/themes/pull/8029
