### ISSUE TITLE
Calm Business: Content is too narrow for tablets

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#805]
Content seems too narrow between 768 - 1168. See the comparison.

<img width="2055" alt="Screen Shot 2019-05-16 at 12 28 16" src="https://user-images.githubusercontent.com/908665/57851067-8b48f880-77d7-11e9-87ca-b36f432826c1.png">

**Comment by jeffikus** [comment]
@iamtakashi ok so I've dug deep into this one - it's easy to solve this just for the tablet mode you specify above, but there's actually a bug with the structure of the width if we want to fix this properly. Let me know if you think it's worth pursuing changing the whole structure.

**Comment by iamtakashi** [comment]
I'm hesitant to change the whole structure, just because we don't have time until we start offering theses themes to wider people. So focus on fixing Calm in this ticket. Professional has similar pattern so looking at the theme should help you. The main thing I noticed was, the theme currently use 6 column when should be 8 columns. Please test with all the views including single post, archive etc.

**Comment by jeffikus** [comment]
@iamtakashi I've made a number of changes here, I think the changes might fix #806 as well. Testing that now. Please can you give this a test as it's a fairly large change. I've tested on the homepage demo, archives, search, single post & page.

**Comment by iamtakashi** [comment]
@jeffikus Thanks for the fix! It fixes the very issue. Let's merge your fix after making a PR with it.

BTW, #806 is about Sophisticated and Professional. Professional can be fixed in the same way as your fix for Calm, and Sophisticated can be fixed like Friendly or Elegant.
