### ISSUE TITLE
Olympique: Author link invisible

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#8059]
The post author link in the single post view is invisible:

<img width="415" alt="image" src="https://github.com/user-attachments/assets/c46700fd-088b-49c0-945e-536d9ecdaa2b">

<img width="418" alt="image" src="https://github.com/user-attachments/assets/449c3d08-aeaf-4848-a205-8b4ea97b18db">

cc @henriqueiamarino

**Comment by henriqueiamarino** [comment]
Thanks for fixing it, @alaczek.
