### ISSUE TITLE
Multiple Themes: Entry meta is too narrow for tablets

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#806]
Affected Themes: Sophisticated and Professional. See the comparison.

<img width="2051" alt="Screen Shot 2019-05-16 at 12 30 37" src="https://user-images.githubusercontent.com/908665/57851235-f4307080-77d7-11e9-8ee1-0c0b45288fe9.png">

**Comment by iamtakashi** [comment]
In Sophisticated, `entry-header` is also too narrow. It should be the same as Friendly or Elegant.

**Comment by jeffikus** [comment]
Related to #805
