### ISSUE TITLE
Dara: Content Options -  tag, author and date displays can appear out of alignment after being toggled on.

### ISSUE THREAD

**Issue by coder-karen** [Automattic/themes#8077]
### Quick summary

When using Dara and then also using Content Options in the site customizer, tags are not aligned on the main site page after removing and re-adding them (this is assuming a site with blog posts showing on the home page).

If a Featured Content section is added as well, then both date and author alignment are out of place after being removed and re-added via the Content Options section.

This is only an issue in the Customizer (not live site).

### Steps to reproduce

1. If testing on a self-hosted site, ensure Jetpack is installed and connected
2. Add a tag to a post
3. Visit the Customizer, open up Content Options
4. Toggle 'Display tags' and the tag will not be placed in alignment with 'Leave a comment'
5. Open up Featured Content and add the tag added to the post above, so that the Featured Content displays in the Customizer
6. Back in Content Options, toggle the author or name displays off and on. On re-appearing, these should be out of alignment with each other - unless both are done.

### A clear and concise description of what you expected to happen.

On toggling date, author and tag displays, I'd expect the displayed text to re-appear in exactly the same location it was previously.

### What actually happened

Text was out of alignment.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

Refreshing the customizer resolves the issue (which is present only in the customizer).

### Platform (Simple and/or Atomic)

Simple, Atomic, Self-hosted

### Logs or notes

Demo of the issue: 

https://github.com/user-attachments/assets/a80b0c06-e1d1-4a1f-a545-74eb289b1352

I tested several themes that make use of Content Options, but could only find the issue happening when Dara was active, so it seems it may be better to log this as an issue to (possibly) fix at the theme end vs Jetpack.

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- Followed the video in the original report.
- I couldn't replicate it with another theme either.

📌 ACTIONS
- Triaged

**Comment by inaikem** [comment]
Over 1million active installs. Bumping priority based on this -- /pc4f5j-4Yq. Checking on next steps.
