### ISSUE TITLE
Assembler: Move the style variation specific font families from the main theme.json to the variation json file.

### ISSUE THREAD

**Issue by matiasbenedetto** [Automattic/themes#8079]
## What?
Move the style variation specific font families from the main theme.json to the variation JSON file.

## Why?
Currently, the font families must be defined in the main theme.json file to load as expected in the editor when the style variation is switched. If this issue https://github.com/WordPress/gutenberg/issues/59965 is fixed (in progress https://github.com/WordPress/gutenberg/pull/65019), we could avoid this 'hack' that's producing the printing of not needed CSS in the frontend. So, this change would be a tiny performance improvement, and it could lead to simpler-to-define typography variations.

## Related
The same issue in TT5: https://github.com/WordPress/twentytwentyfive/issues/233

**Comment by alaczek** [comment]
OMG yes please! This will also make it easier to build Assembler-based themes without needing to remove a bunch of fonts from theme.json every time 🎉

**Comment by alaczek** [comment]
I moved the font family definitions out of theme.json to appropriate style variations. Please review and let me know if this is right.

While I was doing this, I noticed we have a few fonts registered in theme.json that are not used in any style variation:
* Bricolage Grotesque
* Vina Sans
* Rubik
* Cardo
* DM Serif Display
* Libre Baskerville

Shall we keep or remove them?

I also noticed missing font weights:
* in the 05-fahkwang.json the headings are supposed to use 200 font weight, but we only register 400 and 600. 
* in 01-figtree.json the headings are supposed to use 900 font weight, but we only register 400-700.

Shall I add the missing font family or update the headings definition?

cc @richtabor

**Comment by richtabor** [comment]
> Shall I add the missing font family or update the headings definition?

Let's remove, other than Rubik — I'll make a quick variation for it in https://github.com/Automattic/themes/pull/8421.
