### ISSUE TITLE
[DotCom Launch]: Moviescript

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8105]
### DotCom launch checklist

- [x] Create demo site
- [x] Create theme showcase
- [x] Delist Screenplay
- [x] Network activate
- [x] Launch theme

**Comment by MaggieCabrera** [comment]
[Pressable demo](https://moviescript.mystagingwebsite.com/)

**Comment by MaggieCabrera** [comment]
Created [demo](moviescriptdemo.wordpress.com), waiting on content @henriqueiamarino

**Comment by henriqueiamarino** [comment]
[goncharov.WordPress.2024-09-12.xml.zip](https://github.com/user-attachments/files/16979640/goncharov.WordPress.2024-09-12.xml.zip)
 
 Here you go, @MaggieCabrera.

**Comment by MaggieCabrera** [comment]
Renamed from Screenplay
