### ISSUE TITLE
[DotCom Launch]: Greenseed

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8107]
### DotCom launch checklist

- [x] Create [demo](https://greenseeddemo.wordpress.com/) site
- [x] Create [theme showcase](https://theme.wordpress.com/themes/greenseed/)
- [x] Network activate
- [x] Launch theme

The demo site has been created but the theme has been renamed (old Farmhouse), we need to delete the old one and activate the new one

**Comment by alaczek** [comment]
This issue is a blocker for launch: https://github.com/Automattic/themes/issues/8102

**Comment by iamtakashi** [comment]
#8102 fixes the missing image issue, and everything looks good on the front of the site. But, in the editor, the images are still down the page initially, and I think we'll need to fix it before launching it.

The trick the theme does is the group block with a custom CSS class `overlay` has an [absolute positioning](https://github.com/Automattic/themes/blob/trunk/greenseed/style.css#L70). That makes the wrapper's height (the group block with a sticky positioning) is zero, and everything else below comes at the top of the browser. That works well on the front of the site, but not in the editor at the moment.

Is there a way to add a custom style `position: absolute;` to the Stack block that has the `overlay` class **in the editor** like simulated in the screenshot?

![CleanShot 2024-09-17 at 19 17 00@2x](https://github.com/user-attachments/assets/d359e5eb-02c6-4b2d-b3ad-c58a92c1fa52)

**Comment by iamtakashi** [comment]
https://themes.trac.wordpress.org/ticket/188382

**Comment by iamtakashi** [comment]
There doesn't seem to be a way to fix it with the current approach. I'll work on the theme differently to achieve the effect.

**Comment by iamtakashi** [comment]
I fixed the theme by taking a different approach to achieve what Bea wanted. I'm launching and submitting this today.

**Comment by iamtakashi** [comment]
Launched on dotcom and submitted to dotorg https://themes.trac.wordpress.org/ticket/193734
