### ISSUE TITLE
[DotCom Launch]: Titleless

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8108]
### DotCom launch checklist

- [x] Create [demo](titlelessdemo.wordpress.com) site
- [x] Create theme showcase
- [x] Delist Texty
- [x] Network activate
- [x] Launch theme

[Pressable demo](https://titleless.mystagingwebsite.com/)
[Content export](https://github.com/user-attachments/files/16982207/titleless.WordPress.2024-09-12.xml.zip)

**Comment by MaggieCabrera** [comment]
@henriqueiamarino the export you linked doesn't seem to have content inside the pages Stories and Reviews, it looks like it has empty Query loops: https://titlelessdemo.wordpress.com/reviews/

**Comment by MaggieCabrera** [comment]
Renamed from Texty

**Comment by alaczek** [comment]
> the export you linked doesn't seem to have content inside the pages Stories and Reviews

I think these are meant to link to category archives, not static pages - I fixed it.
