### ISSUE TITLE
[DotCom Launch]: The jazzers

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8117]
### DotCom launch checklist

- [x] Create [demo](https://thejazzersdemo.wordpress.com/) site
- [x] Create [theme showcase](https://theme.wordpress.com/themes/the-jazzers/)
- [x] Network activate
- [x] Launch theme

[Pressable demo](https://thejazzers.mystagingwebsite.com/)
[Content](https://github.com/user-attachments/files/16982305/thejazzers.WordPress.2024-09-12.xml.zip)

**Comment by iamtakashi** [comment]
@alaczek Theme Tier? The info is blank on the showcase page at the moment.
