### ISSUE TITLE
[DotCom Launch]: Happening

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8118]
### DotCom launch checklist

- [x] Create https://happeningdemo.wordpress.com/ site
- [x] Create p5YS-dDO-p2
- [x] Delist Eventual
- [x] Network activate
- [x] Launch theme

[Pressable demo](https://happening.mystagingwebsite.com/)
[Content](https://github.com/user-attachments/files/16990637/thesunneversetsona8c.WordPress.2024-09-13.xml.zip)

**Comment by iamtakashi** [comment]
@alaczek As this looks identical to the Eventual theme, I think it'd make sense to delist the theme before activating it, but I'll defer to you and the dotcom folks.
