### ISSUE TITLE
[DotCom Launch]: JazzyGrid

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8119]
### DotCom launch checklist

- [x] Create https://jazzygriddemo.wordpress.com/ site
- [x] Create p5YS-dDU-p2
- [x] Delist BoxedBio
- [x] Network activate
- [x] Launch theme

[Pressable demo](https://jazzygrid.mystagingwebsite.com/)
[Content](https://github.com/user-attachments/files/16982250/jazzygrid.WordPress.2024-09-12.xml.zip)

**Comment by iamtakashi** [comment]
@alaczek As this looks identical to the Boxed Bio theme, I think it'd make sense to delist it before activating this, but I'll defer to you and the dotcom folks.
