### ISSUE TITLE
[DotCom Launch]: Brute

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8120]
### DotCom launch checklist

- [x] Create https://brutedemo.wordpress.com/ site
- [x] Create p5YS-dE2-p2
- [x] Delist Raw
- [x] Network activate
- [x] Launch theme

[Pressable demo](https://brute.mystagingwebsite.com/)
[Content](https://github.com/user-attachments/files/16982294/brute.WordPress.2024-09-12.xml.zip)

**Comment by iamtakashi** [comment]
@alaczek As this looks identical to the Raw theme, I think it'd make sense to delist it before activating this, but I'll defer to you and the dotcom folks.
