### ISSUE TITLE
[DotCom Launch]: Adonay

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8155]
### DotCom launch checklist

- [x] Create [demo](https://adonaydemo.wordpress.com/) site
- [x] Create [theme showcase](https://theme.wordpress.com/themes/adonay/)
- [x] Network activate
- [x] Launch theme

**Comment by iamtakashi** [comment]
@alaczek Theme Tier? The info is blank on the showcase page at the moment.
