### ISSUE TITLE
[DotCom Launch]: The Shore

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8164]
### DotCom launch checklist

- [x] Create [demo](https://theshoredemo.wordpress.com/) site
- [x] Create [theme showcase](https://theme.wordpress.com/themes/the-shore/)
- [x] Network activate
- [x] Launch theme

[theshore.WordPress.2024-09-16.xml.zip](https://github.com/user-attachments/files/17016641/theshore.WordPress.2024-09-16.xml.zip)

**Comment by iamtakashi** [comment]
@alaczek Theme Tier? The info is blank on the showcase page at the moment.

**Comment by alaczek** [comment]
I'll take care of theme tier. Could we please fix this issue before launch? https://github.com/Automattic/themes/issues/8168
