### ISSUE TITLE
[DotCom Launch]: Sprinkler

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#8165]
### DotCom launch checklist

- [x] Create [demo](https://sprinklerdemo.wordpress.com/) site
- [x] Create [theme showcase](https://theme.wordpress.com/themes/sprinkler/)
- [x] Network activate
- [x] Launch theme

**Comment by iamtakashi** [comment]
@alaczek Theme Tier? The info is blank on the showcase page at the moment.
