### ISSUE TITLE
Theme demo sites: Automate disabling likes and sharing buttons

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#8169]
### Quick summary

We now disable likes and sharing buttons on posts and comments on WP.com theme demo sites. Many demo site configurations are automated now, and it'd be helpful if it's automated.

C048GFLMBGD/p1726539864130299?thread_ts=1726514370.285619&cid=C048GFLMBGD-slack-themesdesign

cc @dsas

**Comment by dsas** [comment]
I'm not familiar with how these options work, or how the create theme demo site command works but there are probably two ways forward:
 1. Look at `wp theme-demo-site create` command and see if it can be added there. This seems like the simplest thing to do.
 2. Look at how "disabling likes and sharing buttons" is implemented, maybe there are filters we can activate if a site has a theme demo sticker (need to be careful to do this very efficiently).

**Comment by dsas** [comment]
It looks like the `wp theme-demo-site create` command already sets various likes and sharing options: fbhepr%2Skers%2Sjcpbz%2Sova%2Sjc%2Qpyv%2Qjcpbz%2Spbzznaqf%2Sgurzr%2Qqrzb%2Qfvgr.cuc%3Se%3Q40p351n3%23282-og @iamtakashi are you using this sandbox command to create demo sites?

The `wp theme-demo-site audit pub/THEME_SLUG` command can be ran after the site has been created to fix the settings too (it runs this fbhepr%2Skers%2Sjcpbz%2Sova%2Sgurzrf%2Sqrzb%2Qfvgr%2Qnhqvg.cuc%3Se%3Qno293150%23273-og)

**Comment by iamtakashi** [comment]
> are you using this sandbox command to create demo sites?

I have used it more than a few times, but lately, I have been using the link in the launcher.

![mc a8c com_themes_launch__slug=castcore](https://github.com/user-attachments/assets/b28ac968-f001-4798-b471-569c0fdedef1)

But if there is a better command that does more in the future, I wouldn't mind using it at all :)

**Comment by dsas** [comment]
It looks like the theme launch dashboard has the same logic: fbhepr%2Skers%2Szp%2Sgurzrf%2Synhapu%2Svapyhqrf%2Sqrzb%2Qfvgr.cuc%3Se%3Q0921o315%23219-og

Also the `theme-demo-site audit` command I mentioned above is ran daily, so it will catch anything missed.

The problem is that the logic in both places is wrong. I've got a fix ready for the theme launch dashboard but need to test it properly. @iamtakashi can you ping me next time you've got a theme demo site to create so that I can give it a try?

**Comment by iamtakashi** [comment]
@dsas, Sure! Thanks for looking into it.

**Comment by dsas** [comment]
CLI diff: D163125-code
Theme launch dashboard: in missioncontrol#158129 on the GHE instance
