### ISSUE TITLE
[DotCom Launch]: Impressionist

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#8189]
### DotCom launch checklist
- [x] Create and set up [the demo site](https://impressionistdemo.wordpress.com/)
- [x] Create [showcase page](https://theme.wordpress.com/themes/impressionist/)
- [ ] Network activate

**Comment by alaczek** [comment]
I deployed Impressionist to .com, and run the script to create the https://impressionistdemo.wordpress.com/, but I needs setting up.
For the tier I was thinking free.

**Comment by iamtakashi** [comment]
We don't have access to [the site](https://arttheme.mystagingwebsite.com/), which she initially worked on. It's blocked.

**Comment by iamtakashi** [comment]
I got access and populated the demo site.
