### ISSUE TITLE
[DotCom Launch]: Fictionary

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#8190]
### DotCom launch checklist

- [x] Create [demo site](https://fictionarydemo.wordpress.com/)
- [x] Create [theme showcase](https://theme.wordpress.com/themes/fictionary/)
- [x] Network activate
- [x] Launch theme

**Comment by iamtakashi** [comment]
@alaczek Theme tier for this theme?

**Comment by alaczek** [comment]
I set it to Personal.
