### ISSUE TITLE
[HC] Assembler: Link hover color not updating on Post titles

### ISSUE THREAD

**Issue by caitlindawn** [Automattic/themes#8193]
### Quick summary

Changes do not apply when changing the Hover color on Post titles in the Assembler theme.

#hc

### Steps to reproduce

1. Load up the Assembler theme.
2. Add the Query Loop block and choose any pattern.
3. Click on a Post Title and change the Link Hover color on block's Styles section.
4. Hover over the post title to see if the color changes.

### A clear and concise description of what you expected to happen.

Post title color should change when hovering over it.

### What actually happened

Post title color doesn't change.

<img width="820" alt="image" src="https://github.com/user-attachments/assets/e3d39b5a-8140-49f8-bd06-538044cfe372">

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

Reported in 8759313-zen

Tested this on another block theme (Dawson) but could not reproduce.

<img width="820" alt="image" src="https://github.com/user-attachments/assets/2e90f97f-615e-4f9e-b9a9-babff0c9f116">

**Comment by caitlindawn** [comment]
Reported in 8759313-zen

**Comment by ivan-ottinger** [comment]
This regressions was introduced just recently in https://github.com/Automattic/themes/pull/8027:

```
/* Make link colors match text colors. */
18 
19 h1 a, h2 a, h3 a, h4 a, h5 a, h6 a {
20     color: inherit !important;
21 }
```

`!important;` is overriding the hover color as well.

→ Asked Rich for context of the change: https://github.com/Automattic/themes/pull/8027/files#r1775178172.

---

Related code: fbhepr%2Skers%2Sjcpbz%2Qcho%2Qgurzrf%2Snffrzoyre%2Sfglyr.pff%3Se%3Q0621p8p5%2317%2Q21-og

**Comment by ivan-ottinger** [comment]
PR with the fix is now ready for review: https://github.com/Automattic/themes/pull/8206.

**Comment by ivan-ottinger** [comment]
Just noting that the fix has been merged and will be later deployed to production.
