### ISSUE TITLE
[DotCom Launch]: AlleyOop

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#8196]
### DotCom launch checklist

- [x] Create [demo site](https://alleyoopdemo.wordpress.com/)
- [x] Create [theme showcase](https://theme.wordpress.com/themes/alleyoop/)
- [x] Network activate
- [x] Launch theme

**Comment by alaczek** [comment]
Created the demo site: https://alleyoopdemo.wordpress.com/

**Comment by iamtakashi** [comment]
Since @henriqueiamarino is back now, I'm going to let him check the theme first before going any further.

**Comment by alaczek** [comment]
@henrique I noticed the HTML isn't escaped properly:

![Image](https://github.com/user-attachments/assets/c66ac01c-90a9-4b6c-86ef-1701da3e8ea9)

Also, could we please have page title included in the page template?

**Comment by henriqueiamarino** [comment]
Thanks, @alaczek. This theme was not ready to become a PR, but I'll prepare it now. After reviewing many themes, I noticed some issues that should be easily fixed here.

To offer context, I was creating my PRs individually before this batch of PRs was added. I told @iamtakashi I would thoroughly review them and let you guys know.

**Comment by alaczek** [comment]
Awesome, thank you @henriqueiamarino !

**Comment by iamtakashi** [comment]
@alaczek This should be ready to go after the latest updates get deployed to dotcom.
