### ISSUE TITLE
Message: SyntaxHighlighter Code block does not respect the container width

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#8247]
### Quick summary

When using the SyntaxHighlighter Code block the content expands outside its container width

### Steps to reproduce

1. Create a post
2. Add the SyntaxHighlighter Code block
3. Insert content in it
4. Check the results

### A clear and concise description of what you expected to happen.

The block should wrap the code

### What actually happened

It displayed like this generating a lot of horizontal scroll

![Image](https://github.com/user-attachments/assets/07996cca-6b39-4dd8-805e-f868b7ab0655)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

- I couldn't replicate this on a atomic site.
- This originated while testing this one https://github.com/Automattic/themes/issues/8239

**Comment by sixhours** [comment]
Started looking at this and `.syntaxhighlighter { width: 100% !important }` is clobbering all the theme's styles/restraints on width. We should probably fix that on the plugin side.

**Comment by sixhours** [comment]
Fix for this has been merged, just waiting on deployment to WP.com

**Comment by sixhours** [comment]
These changes have been deployed to WP.com!
