### ISSUE TITLE
Conference: bumping footer

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#8297]
### Quick summary

@henriqueiamarino, I realised the content in the footer still bumps to the edges of the window.

![Image](https://github.com/user-attachments/assets/95a6c67b-e6fa-4f5c-995a-66c1024db7d5)

And another footer has a slightly different issue, too.

![Image](https://github.com/user-attachments/assets/0781ac2c-e50a-42ee-8e6c-01c8442c7c67)

### Steps to reproduce

Open the site and see the footers.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by henriqueiamarino** [comment]
Fixed on #8298
