### ISSUE TITLE
Course theme: Horizontal scroll bar and extra spacing/margin/padding on a course page

### ISSUE THREAD

**Issue by philipsiwinski** [Automattic/themes#8334]
### Quick summary

On a WordPress site using the Course theme, when visiting a course created with the Sensei LMS plugin, there is a horizontal scroll bar and too much space on the right.

### Steps to reproduce

1. Go to the Sensei LMS Demo Site (or any WP with Sensei LMS and the Course theme)
2. Click on any course (try /course/sensei-101/)
4. See a horizontal scroll bar and extra padding on the right

### A clear and concise description of what you expected to happen.

No horizontal scroll bar, no extra space

### What actually happened

A horizontal scroll bar extra padding on the right, on any course page
![Image](https://github.com/user-attachments/assets/4f95230c-e025-4b41-a83d-b4dd6b20c20c)
![Image](https://github.com/user-attachments/assets/6f0db757-f658-4e71-b060-763986e4766c)

### Impact

All

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

Open /wp-admin/theme-editor.php?file=theme.json&theme=course
Search for: "right": "1.25rem",
Replace "right": "1.25rem", by "right": "0rem",
Replace "left": "1.25rem" by "left": "0rem"
Save the changes

![Image](https://github.com/user-attachments/assets/38304abc-e810-4566-8cb3-8b6a23afeb16)

### Logs or notes

PHP 8.1.20
WordPress 6.6.2
Sensei LMS 4.24.3
Course theme 1.3.9

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – Yes


📌 ACTIONS
- Triaged
- Leaving this as a high priority

**Comment by philipsiwinski** [comment]
Thanks a lot @renatho, I confirm this change in the Sensei LMS plugin fixes the issue.
