### ISSUE TITLE
Hover Reveal style from Dalston theme not fading the Cover layer

### ISSUE THREAD

**Issue by renatho** [Automattic/themes#8377]
### Quick summary

While working on https://github.com/Automattic/themes/pull/8376, I noticed that https://github.com/Automattic/themes/pull/1638 wasn't working.

It should have an effect in the Cover layer similar to the effect in the content being revealed.

Not sure if it's related to an old version of the Cover block, but currently the class `.has-background-dim` is not applied to the same element that has the class `.wp-block-cover`. It's a child element.

### Steps to reproduce

1. Create a cover block with the "Hover Reveal" style.
2. Add some content.
3. Add a gradient and opacity.
4. Check that only the content is hidden/revealed.

### A clear and concise description of what you expected to happen.

Based on the code, and on the https://github.com/Automattic/themes/pull/1638, it should have an effect in the layer before the content either.

### What actually happened

The effect is happening only in the content and not in the layer.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

- Theme: Dalston
- When working on it, also keep in mind the touch devices with the `dalson-in-viewport` classes. See https://github.com/Automattic/themes/pull/8376/files#r1831286076.

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 ACTIONS
- Triaged
- Lowered priority from High to Normal.
