### ISSUE TITLE
Dalston theme: Background disappears when hovering the text of a Cover block in the editor when it's using the "Hover Reveal" style

### ISSUE THREAD

**Issue by renatho** [Automattic/themes#8386]
### Quick summary

This is a bug with Dalston theme.

When we have a Cover block using gradient and "Hover Reveal" on WordPress 5.5, if we hover the text of the cover, the background with the gradient disappears.

### Steps to reproduce

1. Create a site using WP 5.5.
2. Install the Dalston theme.
3. Create a page and add a Cover block.
4. Add a text, an image, a gradient and the "Hover Reveal" style to the Cover block.
5. Hover the text, and see that the gradient disappears.

### A clear and concise description of what you expected to happen.

The background with the gradient should still be visible when hovering the text.

https://github.com/user-attachments/assets/c87578f4-0b69-4aeb-a551-16e45db3543f

### What actually happened

It's hidden.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

- WordPress 5.5
- Dalston theme

**Comment by renatho** [comment]
I already added a Low priority label to this issue because it's only with an old version of WordPress, only in the editor, and only using the specific configurations in the Cover block. So I don't think it should has a greater priority unless we hear from users facing this issue.

**Comment by alaczek** [comment]
Can we close this as fixed?

**Comment by Robertght** [comment]
WordPress 5.5 is pretty old compared to the current one, 6.7.1.

I don't believe we'll be able to accommodate a fix for this version, so I'm going to close this one for now. 

cc @alaczek and @dsas if you believe otherwise.
