### ISSUE TITLE
Loïc: syntax highlighter block breaks layout of page

### ISSUE THREAD

**Issue by davewhitley** [Automattic/themes#8387]
### Quick summary

When using the syntax highlighter block in Loic theme, the block is ~9000px wide for some reason.

Seen here https://barryblogstaging.wordpress.com/public-keys/

![Image](https://github.com/user-attachments/assets/4d55abcf-4e99-44c5-a717-9309070a074a)

### Steps to reproduce

1. Insert Syntax Highlighter block in a page

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

**Comment by Robertght** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I was able to replicate this on AT sites, however, there we can use the **SyntaxHighlighter Evolved** plugin to fix the issue.
- There's another similar case here: https://github.com/Automattic/themes/issues/8247#issuecomment-2420265785

📌 ACTIONS
- Triaged
- I'm changing this to High for now

**Comment by sixhours** [comment]
After some quick testing, I think this should be addressed by the plugin-level fix proposed in https://github.com/Automattic/syntaxhighlighter/pull/278
