### ISSUE TITLE
Intergalactic 2: Custom header zoomed in significantly on post/pages without featured image

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#84]
## Steps to replicate

1. In the Customizer, set a custom header image. Use the recommended cropping so the image is at the ideal dimensions.
2. View the front page/posts page and note the size of the header section, and also the zoom of the image.
3. Now view a static page or a post without a featured image set, so the site's custom header is used 

## Expected

For the image to look the same as on the front page

## Result

The header image section is almost three times higher than on the front page, and zoomed in significantly so only part of the image shows, and depending on the size of the original image, leading to a significant decrease in quality due to the high zoom level. It appears the header section expands horizontally to fill whatever space is available in the browser window, zooming and cropping the image at the sides as it expands in height.

The image color on the single post/page also appears darker than on the front page, though I can't seem to find anything in the browser inspector that would explain this. This is especially noticeable if a neutral color image is used as the site's custom header, as is the case with the user who reported this.

### Header on front page:

![posts_page_ _shift_to_the_left_and_slack_-_a8c](https://user-images.githubusercontent.com/11873759/38420990-ea47d976-39a5-11e8-9e67-aef4aed350ee.png)

### Header on single post/page:

![sandbox_post_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/38421017-006b1d80-39a6-11e8-876c-13612a852a9a.png)

I realise this theme is designed to work with big featured image headers on single posts and page, but given the dimensions it recommends for a custom header, shouldn't those dimensions be respected on posts/pages without a featured image set?

Also replicated this on a test site and the theme demo site. Issue is not browser-specific

* User report: #894777-f
* User's site: https://tibettruth.com/, https://tibettruth.com/what-is-tibets-cause-about/

**Comment by alaczek** [comment]
The problem here is, Intergalactic 2 uses images exclusively as a background, so there's no way for us to make it respect any particular dimensions. We had to settle on something in the custom header image configuration, but this size should be mostly taken as a guideline to use big images, not an exact measurement. I realize that this is not intuitive, and that customers would expect those to be respected. 

Perhaps we could remove the dimensions from the configuration - then users would not be asked about image cropping and things would be less confusing (I'm not 100% it won't have a negative impact on existing sites, so we'd need to test first). Do you think that would help?
Or we could add some clarifying text to the showcase page? Something like this:

> "Intergalactic 2 supports a Custom Header, shown at the top of each page of your site. The image will be cropped for small screens to fit the available space, which means not all of the header image will be visible on all screen sizes, so decorative background images may work best. Please start with an image that’s at least 1440 pixels wide by 460 pixels high."

**Comment by KokkieH** [comment]
I did prepare the user in this case that we might not be able to change how this works.

Clarifying how the theme treats the header will help, I think, though if I can nitpick a little:

> The image will be cropped for small screens to fit the available space

The issue here for the user is not cropping, but that the header area is so much bigger with a custom header set as opposed to without. The user actually has a completely neutral header image, as they want the site title to have a background color without applying it to the text area of the site as well, but on single pages it shows a massive orange title block instead of the neat strip as appears at the top of the front page.

So could we include in the clarifying text a mention that on posts and pages the custom header image will always fit to the full height of the screen available, and that it won't work the same as on the front page? Something like:

> Intergalactic 2 supports a Custom Header, shown at the top of each page of your site. On posts and pages the image will fill the height of the screen which might cause the edges to be cropped based on the image's dimensions. The image will also be cropped for small screens to fit the available space...

**Comment by laurelfulford** [comment]
Thanks @KokkieH! I've updated Intergalactic 2's docs accordingly. 

It looks like this was the one outstanding bit for this ticket, so I'm going to close it.

**Comment by KokkieH** [comment]
Thank you. Replied to the user in https://en.forums.wordpress.com/topic/intergalactic-2-suddenly-showing-change-to-display/ (the shortlink appears to no longer work after the forums upgrade)
