### ISSUE TITLE
Common: Slideshow block doesn't work in post template

### ISSUE THREAD

**Issue by supernovia** [Automattic/themes#8452]
### Quick summary

The Jetpack Slideshow block doesn't play correctly in posts when Common with default templates is active. Buttons don't seem to respond, and some or all of the images seem to be off-page.

### Steps to reproduce

1. On a site with another theme active, create a post with a Jetpack slideshow. I used images with different aspect ratios, but this may not matter
2. Note the slideshow works in the editor an on the site
3. Switch to the Common theme
4. Note the slideshow stops working on the site
5. If I edit the template to remove the content block from the columns, the slideshow appears appropriately

### A clear and concise description of what you expected to happen.

The slideshow should just work within its content box

### What actually happened

The slideshow seems to fall out of the content area and either not display at all, or not respond as expected.

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

One can edit the single post template to move the content area so its outside the column layouts, but then it looks different than the theme is intended.

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Tested on simple but I'm sure this happens on Atomic, too.

**Comment by supernovia** [comment]
Case here:
9083028-zd-a8c

**Comment by jartes** [comment]
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
![Image](https://github.com/user-attachments/assets/6a38f29e-df67-4471-832a-389311216f79)

📌 ACTIONS
- Triaged

📌 Message to Author
@supernovia Thanks for reporting this one! 

@Automattic/t-rex This is coming from a Customer Report. Please, can you take a look? Thank you!

**Comment by iamtakashi** [comment]
The issue has been fixed in #8463. It will be deployed to dotcom shortly (likely tomorrow).

**Comment by iamtakashi** [comment]
The fix has been deployed to dotcom. I can confirm that the slideshow works fine now.

![Image](https://github.com/user-attachments/assets/003e87a8-3e5c-4611-a886-c5ad836c7e10)
