### ISSUE TITLE
Twenty Twenty-Four, Twenty Twenty-Five: Contact Form Submit button not reflecting selected styles (Outline)

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/themes#8477]
### Quick summary

When using a contact form, if the button style is set to outline, nothing changes in the style. The CSS class `is-style-outline` shows in the code but appears to be overwritten. 

The issue was reported on the Twenty Twenty-Four theme, but I was able to reproduce it on the Twenty Twenty-Five theme as well. 

9116292-zd-a8c

### Steps to reproduce

1. Activate either Twenty Twenty-Four or Twenty Twenty-Five
2. Add a page with a form block
3. Customize the style of the submit button to use the outline option

### A clear and concise description of what you expected to happen.

I expect the button to use the same style as a buttons block that has the outline style applied to it.

### What actually happened

The default "fill" style is applied. 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

There might be a CSS workaround, but I have not found one yet.

**Comment by iamtakashi** [comment]
@ktyfuller604 Thanks for the report, but I believe this needs to be reported to Jetpack because this is not a theme-specific issue. If the issue occurs with multiple themes, it's more likely a block-specific issue. I'll close this issue, but let us know if we can help.
