### ISSUE TITLE
Tenku Theme: Styles button unresponsive in Editor

### ISSUE THREAD

**Issue by jossunzicker** [Automattic/themes#8508]
### Quick summary

The Styles button is unresponsive in the Editor for both simple and atomic sites that have the Tenku theme applied. 

### Steps to reproduce

1. Apply Tenku theme to site. 
2. Navigate to Editor
3. Click Styles 

### A clear and concise description of what you expected to happen.

The Styles button should pull up the Styles settings in a separate menu.

### What actually happened

Nothing happens when the Styles button is clicked. 

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

The user can still access global styles by clicking the Style Icon at the top right in the the editor.

**Comment by Robertght** [comment]
This appears to work ok on my end:

![Image](https://github.com/user-attachments/assets/6511bede-c85d-4b0b-b066-a977dab93e8d)

I also believe this may have been fixed here: https://github.com/WordPress/gutenberg/issues/67532

I'm closing this for now but feel free to re-open @jossunzicker if you're still seeing the issue.

**Comment by jossunzicker** [comment]
Looks to be working now! Thank you.
