### ISSUE TITLE
Kentwood: Default posts page doesn't load any posts.

### ISSUE THREAD

**Issue by devNigel** [Automattic/themes#8520]
### Quick summary

The Default posts page on Kentwood theme fails to load Query Loop posts from its Blog Home template. 

### Steps to reproduce

1. On a Simple or Atomic site, activate Kentwood. 
2. Ensure the site has published blog posts.
3. Ensure there is an empty "Blog" page.
4. Head to Settings > Reading and set the Default posts page to "Blog" and save the changes.
5. Once you do that, you will notice that the template active on "Blog" page changes to "Blog Home" template coming from the theme. This template contains a Query Loop of posts.
6. However, if you visit the Blog page on the live website, it does not load posts on the site.

### A clear and concise description of what you expected to happen.

The Default posts page should load the posts on the site.

### What actually happened

The Default posts page did not load the posts on the site.

Screenshots: 

Live page -
![Image](https://github.com/user-attachments/assets/365222d2-67ef-4194-86ab-97605fe4a16a)

Blog Home template - 

![Image](https://github.com/user-attachments/assets/ddee7dce-2564-4f99-ba7a-688e38da30ee)

Blog page editor - 

![Image](https://github.com/user-attachments/assets/3b9576c5-a4ad-4613-b447-037efcbf166a)

### Impact

All

### Available workarounds?

Yes, easy to implement

### If the above answer is "Yes...", outline the workaround.

As a workaround, to load posts, users can add Blog Posts block or Query Loop block on the page editor. 

### Platform (Simple and/or Atomic)

Atomic, Simple

### Logs or notes

User report: 9166015-zd-a8c

**Comment by Robertght** [comment]
While testing this, I was able to display the Query Loop block on the Blog Posts page, but I find the posts page assign weird, so I asked [here](p1734117826990519-slack-C07H21B2W59) to confirm the behavior.

@devNigel could you let me know if the issue is still happening on your end? If yes, please share a site example so we could take another look.

**Comment by devNigel** [comment]
@Robertght It iloads the content from the page editor. But for a page that is assigned as the Default Posts page, I believe it should be loading the content on the Blog Home template or automatically show all posts.

Feel free to check on the website https://1234223namesite.wordpress.com/blog/

**Comment by iamtakashi** [comment]
> Feel free to check on the website https://1234223namesite.wordpress.com/blog/

@devNigel When I looked at the site, I saw that the homepage was set to display your latest posts. ![Image](https://github.com/user-attachments/assets/3059d94f-b24e-47a8-b431-4af4c10d5eda)

If I change it to show a static page and assign the blog page as the posts page, the blog page shows the posts as expected. ![Image](https://github.com/user-attachments/assets/ecf9d029-b31f-484a-b073-d0c58325a483)
![Image](https://github.com/user-attachments/assets/27ace284-af53-43a4-a77f-9ccfb354cca5)

As far as I can see, the theme behaves as expected.

**Comment by devNigel** [comment]
@iamtakashi Thanks for checking! 

I was managing these settings from Calypso Reading settings. 

![Image](https://github.com/user-attachments/assets/6a2c5119-fb44-46b9-8d0b-090a8c7ef502)

It was not clear whether "Your homepage displays" should be changed from default. 

Anyhow,  after changing "Your homepage displays" from default to a static page, I can confirm that the blog page works as expected. 

I think we can close this issue. Thanks again!

**Comment by iamtakashi** [comment]
@devNigel, No worries! I can see the setting in Calypso is even more confusing :(
