### ISSUE TITLE
Baskerville 2: caption bunching left on centre aligned images

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/themes#854]
## Steps to replicate

1. Go to My Sites > Site > Posts > Add new
2. Click `+` and select the image block
3. Choose an image
4. Add a caption
5. Centre align image
6. Publish

## Result

Caption text was bunched up on the left with one or two words per line.

<img width="876" alt="Screenshot 2019-05-28 at 11 30 51" src="https://user-images.githubusercontent.com/11627765/58471622-3775d200-813c-11e9-9181-acd49e1536e5.png">

This issue only occurs on captions for centre aligned images — captions are displayed in the centre for images aligned left or right.

## Expected

The caption to be centre aligned as it appeared in the editor.

<img width="839" alt="Screenshot 2019-05-28 at 11 30 32" src="https://user-images.githubusercontent.com/11627765/58471637-3f357680-813c-11e9-8d02-4044d6c8401d.png">

* User report: https://en.forums.wordpress.com/topic/center-aligning-of-captions-not-working/

**Comment by RealCarFax** [comment]
I am also seeing a user report here #13810516-hc and am able to replicate this on my own testing site as well. The issue appears to be with this CSS:

```
.post-content .aligncenter {
	display: block;
}
```

Here's a screenshot of my user's issue: https://cld.wthms.co/E6H718

And how it looks when I disable that bit of CSS:https://cld.wthms.co/O7pnQD

**Comment by lakellie** [comment]
User reported in #2320102-zen

I gave them this CSS as a workaround:

```
.wp-block-image .aligncenter>figcaption {
	display: block;
}
```

**Comment by GeoJunkie** [comment]
Reported in #15980481-hc. Gave the above CSS as a workaround

**Comment by mendezcode** [comment]
✅ Fixed upstream on **r54559-wpcom-themes**.

**Comment by GeoJunkie** [comment]
It looks like the patch applied to the Baskerville theme instead of Baskerville 2. Working on that patch now.

**Comment by mendezcode** [comment]
✅ Fixed upstream on **r54868-wpcom-themes.** (Baskerville-2)
