### ISSUE TITLE
Rockfield theme editor coming up blank

### ISSUE THREAD

**Issue by paxblueribbon** [Automattic/themes#8545]
### Quick summary

When the user goes to their editor they get a blank page instead of the editor.  They're using the Rockfield theme.  I could reproduce this when SU'ed in as them.  I tried to switch to Rockfield on a test site and I get an error "Unable to activate theme. Contact support" when trying to activate Rockfield.  When I try to activate that theme from my blog RC I get an error page, but it from the logs it seems it successfully changed the theme, and the pages on my test site are editable.

When logged in as myself and going to the site's wp-admin the editor opens up as expected.

### Steps to reproduce

1. Go in user's dashboard, go to Pages, then click a page to edit it.

or.

1. Create a test site.
2. Give that site a theme other than Rockfield.
3. Try to change that theme to Rockfield.

### A clear and concise description of what you expected to happen.

Clicking on page from Pages list should pull up editor.

or.

Rockfield should activate as new theme without error.

### What actually happened

Click on page leads to blank page with no blocks.

Trying to switch theme to Rockfield produces error: "Unable to activate theme. Contact support."

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

zd-9188435
slack-C03TY6J1A/p1734479847097119
slack-C03TY6J1A/p1734120115110419

Previous instance of this was resolved by closing an unclosed group block, but in this case I can't find any unclosed group block when opening the editor as wp-admin logged in as myself.

**Comment by Robertght** [comment]
I wanted to share that I wasn't able to activate Rockfield initially, but then Varia and Button behaved the same, so I pinged in escalations: p1734505701940749-slack-C02FMH4G8

Leaving this as a blocker as I'm unable to even activate the theme.

**Comment by epeicher** [comment]
The issue was fixed by clearing the Theme cache, more info in the Slack thread p1734512835157399/1734505701.940749-slack-C02FMH4G8

![Image](https://github.com/user-attachments/assets/1079bf44-08a8-462a-9b9f-c0842ecf10d7)

Closing this, feel free to re-open if you see other issues
