### ISSUE TITLE
Storefront: Images with ratio other than 1:1 are incorrectly cropped

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#86]
## Steps to replicate

@joelwills attempted to reproduce this in a test site and wasn't able to do so (see discussion ref below). Re-uploading the image seemed to help, although this issue seems to manifest in Firefox, not Chrome.

<img width="349" alt="necklace_crop1" src="https://user-images.githubusercontent.com/2912202/38463739-b68936f6-3b09-11e8-9b51-3dbfbee9cf6a.png">

## Result

From the user:

>_To recap_, the display of product images greater than a 1:1 ratio, with Storefront theme, utillizing woocomerce, is subject to improper framing. So the images can appear "cut off" or cropped. But when the framing problem automatically catches up with itself, corrects itself, the image becomes per expected, "normal". This appears to be a Firefox related problem as the wordpress technician using Chrome didn't have the problem.

>A related problem_ is that Firefox is showing some images as side-ways. So rotated 45 degrees. For example, go to our website homepage, display dewolf necklaces, scroll down to the coral masquerade necklace, and it appears side-ways (in Firefox, but not in Chrome). That product image appears side-ways in the media library also (using Firefox), but fine in Chrome.

## Expected

Uploaded images should be displayed consistently and, where cropped, cropped similarly for Firefox and Chrome.

<img width="310" alt="necklace_crop" src="https://user-images.githubusercontent.com/2912202/38463741-bfbdf126-3b09-11e8-909f-ddd193cbf502.png">

* User report: 2283124-hc (see also p1522340092000459-slack-C2C8F5PNJ)
* Follow-up ticket: 1051005-zd
* User's site: dewolfdesignden.com generally, see Pretty in Peach page.

**Comment by alaczek** [comment]
Hi @pauljacobson,

Storefront (and it's child themes) has it's own repo [under WooCoommerce](https://github.com/woocommerce/storefront), so I moved your ticket over there (https://github.com/woocommerce/storefront/issues/809). 

This repo is only for A8C made themes (some of which are integrated with WooCommerce). I know this can be confusing, but if you're ever unsure where to report an issue you can always ping in #themes in Slack, and we'll be happy to help!
