### ISSUE TITLE
Edin: Padding for Widgets on Mobile devices

### ISSUE THREAD

**Issue by nerdysandy** [Automattic/themes#865]
## Steps to replicate
- Activate the Edin theme on your site.
- Install two sidebar widgets: Facebook Page Plugin and Custom HTML

## Result

On the desktop, there is space between the two widgets: https://cld.wthms.co/vYfbZ9 but not on mobile: https://cld.wthms.co/QVGbUv

## Expected

The Widgets should have a padding bottom value for mobile devices too so that there is some space between and they're not merged like this: https://cld.wthms.co/QVGbUv

PS: I've added slack discussion link too to the ticket.

* User report: 13098387-hc
* Follow-up ticket: 2069606-zen

**Comment by danieldudzic** [comment]
Hey @nerdysandy, 

Thank you for reporting.

I have now fixed this in https://wpcom-themes.trac.automattic.com/changeset/54566
