### ISSUE TITLE
Dyad 2: Galleries types ”circle” and "square" stretch the images.

### ISSUE THREAD

**Issue by Agepeuve** [Automattic/themes#873]
## Steps to replicate

* Using the classic editor, click on Add > Media and select a couple of images to create a gallery.
* Select "circles" or "square tiles" as its layout.

## Result

* The images will be properly displayed on the editor but they will appear stretched on the published post/page:

![Editor](https://cld.wthms.co/a2dH51+)

![Published](https://cld.wthms.co/4ilAaq+)

## Expected

The images should be displayed on the published post/page as they appear on the editor instead of distorted.

* User report: #10109307-hc
* Follow-up ticket: #2072008-zd

**Comment by kathrynwp** [comment]
Heya - not sure this is a theme-specific issue, did you test with other themes?

Sounds similar to:

https://github.com/Automattic/jetpack/issues/12409

**Comment by Agepeuve** [comment]
Yes, you're right. I tested it with a few other themes and I was able to replicate. I'm closing this issue and I'll move the report there :)
