### ISSUE TITLE
Calm Business: Editor: Title and content blocks not aligned

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#880]
## Steps to replicate

- Start with a WordPress.com site
- Activate `Calm business` theme on it.
- Visit a page/post editor

## Result

The title and content blocks regions are not aligned properly.

## Expected

The title and content blocks regions are aligned properly.

## Screenshots

| Images | Images |
|------|------|
| <img width="1216" alt="Screenshot 2019-06-02 at 15 08 52" src="https://user-images.githubusercontent.com/18581859/58759545-91660580-8549-11e9-9f88-8117af1a217c.png"> | <img width="1152" alt="Screenshot 2019-06-02 at 15 08 56" src="https://user-images.githubusercontent.com/18581859/58759547-91fe9c00-8549-11e9-96be-b359bb46a475.png"> | 
| ![Screenshot 2019-06-02 at 15 04 34](https://user-images.githubusercontent.com/18581859/58759543-91660580-8549-11e9-94fa-0b68ab60375f.png) | ![Screenshot 2019-06-02 at 15 04 37](https://user-images.githubusercontent.com/18581859/58759544-91660580-8549-11e9-85b9-9c99ddae264b.png) | 

It appears fine on the front view.

<img width="758" alt="Screenshot 2019-06-02 at 15 09 11" src="https://user-images.githubusercontent.com/18581859/58759555-ad69a700-8549-11e9-960d-fbd098b5e42f.png">

## Notes

This was not a support request. I found it when testing themes on my test sites.

## Related

https://github.com/Automattic/themes/issues/310

**Comment by danieldudzic** [comment]
Calm Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Mayland: https://wordpress.com/theme/mayland
