### ISSUE TITLE
Modern Business: Visual Inconsistency in Page Title between the editor and the site

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#887]
Font size seems to be different.

**Site:**
<img width="1281" alt="Screen Shot 2019-06-03 at 14 48 40" src="https://user-images.githubusercontent.com/908665/58806732-b4a6b880-860e-11e9-9027-2c9a761cd2e3.png">

**Editor:**
<img width="1281" alt="Screen Shot 2019-06-03 at 14 48 43" src="https://user-images.githubusercontent.com/908665/58806742-b83a3f80-860e-11e9-9509-29dcbc7b71bd.png">

**Comment by jeffikus** [comment]
@iamtakashi if you make the font sizes the same, they don't visually match. The font size is 1.6875em and if you edit that on the demo it doesn't look right. Let me know what you think. #886 is similar as well, but in that case the alignment was the issue.
