### ISSUE TITLE
Friendly Business: Visual Inconsistency in Page Title between the editor and the site

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#888]
The font size seems different.

**Site:**
<img width="1281" alt="Screen Shot 2019-06-03 at 14 51 09" src="https://user-images.githubusercontent.com/908665/58806963-2121b780-860f-11e9-99e5-9ea951ca387b.png">

**Editor:**
<img width="1281" alt="Screen Shot 2019-06-03 at 14 51 05" src="https://user-images.githubusercontent.com/908665/58806995-2e3ea680-860f-11e9-9f11-1b5dc98ab378.png">

**Comment by jeffikus** [comment]
@iamtakashi this is the same feedback as #887 I added. If you make the font sizes the same em values, based on the SASS variables, it doesn't visually line up. The editor is way smaller than the frontend. You can test this by inspecting on the demo editor and making the font size 2.25em. You'll see the pixel computation is far less in the editor.
