### ISSUE TITLE
Professional Business: Visual Inconsistency in Page Title between the editor and the site

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#889]
The font size seems different.

**Site:**
<img width="1281" alt="Screen Shot 2019-06-03 at 14 53 19" src="https://user-images.githubusercontent.com/908665/58807103-5a5a2780-860f-11e9-93f4-444331f24a82.png">

**Editor:**
<img width="1281" alt="Screen Shot 2019-06-03 at 14 53 22" src="https://user-images.githubusercontent.com/908665/58807123-647c2600-860f-11e9-9ff0-0912a978f578.png">

**Comment by jeffikus** [comment]
@iamtakashi similar feedback in #888 and #887
