### ISSUE TITLE
Calm Business: Heading size audit

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#891]
We need heading size audit because some of the sizings don't make sense.

![Screen Shot on 2019-06-03 at 17_49_56](https://user-images.githubusercontent.com/908665/58819422-1c1d3200-8628-11e9-9905-5ac7df500cc4.png)

**Comment by allancole** [comment]
While doing tests for #910, I noticed some of the heading font sizes in the editor are larger than they are on the front-end. 

#### Editor H2 = `32.125px`

![image](https://user-images.githubusercontent.com/709581/58896796-bfbc2000-86c4-11e9-92d9-80e96b192f57.png)

#### Frontend H2 = `24.75px`

![image](https://user-images.githubusercontent.com/709581/58896826-cfd3ff80-86c4-11e9-8d53-3496bed560df.png)
