### ISSUE TITLE
Modern Business: Heading size audit

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#894]
We need heading size audit because some of the sizings don't make sense.

![Screen Shot on 2019-06-03 at 17_55_54](https://user-images.githubusercontent.com/908665/58819792-e0cf3300-8628-11e9-89ea-9cb69caed375.png)

**Comment by allancole** [comment]
While doing tests for #910, I noticed some of the heading font sizes in the editor are larger than they are on the front-end.

#### Editor H2 = 37.125px

![image](https://user-images.githubusercontent.com/709581/58897701-eaa77380-86c6-11e9-9892-aa041b572377.png)

#### Frontend H2 = 24.75px

![image](https://user-images.githubusercontent.com/709581/58897794-2b9f8800-86c7-11e9-8214-da772a439209.png)
