### ISSUE TITLE
Test Secondary Page Templates with All the Variations

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#910]
We need to test all the secondary page templates to see if there are something that needs to be fixed or enhanced in the variations. File issues as you find them.

Note: If there is a same issue happening more than one theme, file them per theme.

**Secondary Page Templates**
- Contact
- About
- Team
- Services
- Portfolio
- Products (WIP)

**Comment by allancole** [comment]
The following Page Templates have been tested against all 6 theme variations:

- About
- Contact
- Team
- Portfolio
- Services

I only noticed a few problems in Calm and Modern and they we’re both related to the Heading Size audits happening in #891 and #894, so I left comments with details on each issue. 

That just leaves the Product Page Template, so once that design is finalized I’ll run this test against it.

**Comment by cathymcbride** [comment]
Done according to comments above. Closing.
