### ISSUE TITLE
Dara: Homepage content hidden behind featured slider

### ISSUE THREAD

**Issue by tijosh** [Automattic/themes#911]
## Steps to Reproduce

Cannot reliably reproduce this on test sites

## Issue Summary

The homepage content can sometimes be pushed up behind the featured slider on the Dara theme:

![Screenshot](https://cld.wthms.co/fdxy0f+)

![Screenshot](https://cld.wthms.co/HmqVGJ+)

This happens most predictably when viewing the site in an incognito window, and the problem corrects itself when you refresh the page.

## Occurences

So far, I've seen this on two occasions, both on Atomic sites:

@guicmazeredo and I worked on this issue with a user on 2019-04-18 in #12142521-hc / #1971513-zen and could not reproduce the issue on our own test sites (Atomic, using Dara)

@susanjanec and I also encountered it on 2019-06-04 in #13221182-hc 

In both instances, CSS was supplied to ensure the slider height remained constant, and it seems to work as a workaround:

```
.flexslider.hero {
    height: 600px!important;
}
```

In #13221182-hc the user also reported that their SiteOrigin Widgets slider on a page was affected similarly:

![Screenshot](https://cld.wthms.co/lLTE9i+)

This may indicate that Dara isn't handling the height size of any sliders correctly in some instances

* User report: #12142521-hc , #13221182-hc 
* Follow-up ticket: #1971513-zen

**Comment by danieldudzic** [comment]
Dara has been retired so I'm closing this as a wontfix.

We have launched a replacement called Shawburn: https://wordpress.com/theme/shawburn
