### ISSUE TITLE
Dyad 2: Menu fixed in Firefox

### ISSUE THREAD

**Issue by Gilmoursa** [Automattic/themes#92]
## Steps to replicate

1. Go to https://crackedpotkitchen.net/ in Chrome
2. Go to https://crackedpotkitchen.net/ in Firefox

## Result

The menu scrolls with the page in Chrome, but does not in Firefox

## Expected

I expected the menu to have the same behavior between Firefox and Chrome

* Follow-up ticket: #1079967-zen
* User's site: https://crackedpotkitchen.net/

**Comment by laurelfulford** [comment]
Hey @Gilmoursa! Dyad 2's menu seems to behave as expected for me in Firefox (v59.0.2 on OSX) and Chrome (v65.0.3325.181 in OSX). It's fixed at the top of browser windows 1400px wide and larger, and will scroll with the page on browser windows smaller than that.

If the menu's not doing that for you on those browser window sizes, could you please share the version of Firefox you're seeing this issue in? Thanks!

**Comment by alaczek** [comment]
I'm also seeing the same consistent behaviour across Chrome v65.0 and Firefox 59.0 on OSX. Could you make sure that browser size was the same (or at least wider then 1400px) in both browsers too?

**Comment by thomasguillot** [comment]
Works just fine for me too. @Gilmoursa can you please confirm the browser sizes.
