### ISSUE TITLE
Branch & issue cleanup

### ISSUE THREAD

**Issue by jeffikus** [Automattic/themes#927]
There are a lot of old branches we need to cleanup. Branches that have been merged should be deleted.

**Comment by nielslange** [comment]
@jeffikus, @allancole & @iamtakashi Shall I take care of this issue and delete all branches that had been merged or deleted already? 

---

To give you an impression about how many obsolete branches we're talking, I created the following JS snippet to quickly count the number of merged and closed branches:

```
const url = window.location.href;
const merged = document.querySelectorAll('.State--purple').length;
const closed = document.querySelectorAll('.State—red').length;
console.log(`${url} → Merged: ${merged} / Closed: ${closed}`);
```

https://github.com/Automattic/themes/branches/all?page=1 → Merged: 6  / Closed: 0
https://github.com/Automattic/themes/branches/all?page=2 → Merged: 16 / Closed: 0
https://github.com/Automattic/themes/branches/all?page=3 → Merged: 16 / Closed: 1
https://github.com/Automattic/themes/branches/all?page=4 → Merged: 18 / Closed: 1
https://github.com/Automattic/themes/branches/all?page=5 → Merged: 19 / Closed: 0
https://github.com/Automattic/themes/branches/all?page=6 → Merged: 17 / Closed: 2
https://github.com/Automattic/themes/branches/all?page=7 → Merged: 19 / Closed: 0
https://github.com/Automattic/themes/branches/all?page=8 → Merged: 17 / Closed: 2
https://github.com/Automattic/themes/branches/all?page=9 → Merged: 19 / Closed: 1
https://github.com/Automattic/themes/branches/all?page=10 → Merged: 17 / Closed: 1
https://github.com/Automattic/themes/branches/all?page=11 → Merged: 20 / Closed: 0
https://github.com/Automattic/themes/branches/all?page=12 → Merged: 16 / Closed: 1
https://github.com/Automattic/themes/branches/all?page=13 → Merged: 16 / Closed: 0
https://github.com/Automattic/themes/branches/all?page=14 → Merged: 19 / Closed: 0
https://github.com/Automattic/themes/branches/all?page=15 → Merged: 19 / Closed: 0
https://github.com/Automattic/themes/branches/all?page=16 → Merged: 3 / Closed: 0

Branches of merged PRs: **257**
Branches of deleted PRs: **9**

**Comment by jeffikus** [comment]
That would be great @nielslange !

For me, you can:
1 - Delete all the merged branches.
2 - Delete any stale branch older than 6 months - @allancole @iamtakashi what do you think of this?

**Comment by jeffikus** [comment]
@nielslange I deleted all my merged branches.

**Comment by nielslange** [comment]
> That would be great @nielslange !
> 
> For me, you can:
> 1 - Delete all the merged branches.
> 2 - Delete any stale branch older than 6 months - @allancole @iamtakashi what do you think of this?

Thanks for your reply, @jeffikus! I'd wait for @allancole's and @iamtakashi's replies as well to ensure that I do not delete anything one of them might still want to look up. That said, I like your suggestion of deleting all stalled branches that are older than 6 months and all merged/deleted branches should no longer be needed anyway. 😀

**Comment by iamtakashi** [comment]
@nielslange I personally don't have anything that I want to keep :) Sounds good to me.

**Comment by jeffikus** [comment]
@nielslange similarly I would say issues over 9-12 months old might be worth closing?

**Comment by nielslange** [comment]
> @nielslange similarly I would say issues over 9-12 months old might be worth closing?

Sounds good. After all, if these issues are important they can easily be reopened.

**Comment by nielslange** [comment]
<table>
<tr>
<td>Total branches before</td>
<td align="right">266</td>
</tr>
<tr>
<td>Deleted merged branches</td>
<td align="right">221</td>
</tr>
<tr>
<td>Deleted closed branches</td>
<td align="right">9</td>
</tr>
<tr>
<td>Total branches after</td>
<td align="right">36</td>
</tr>
</table>

**Comment by MaggieCabrera** [comment]
I've deleted branches on merged PRs, I think we should close this one
