### ISSUE TITLE
Calm Business: CSS blocks labelled as light gray are white

### ISSUE THREAD

**Issue by tbradsha** [Automattic/themes#945]
## Steps to replicate

See the theme CSS here:
https://s2.wp.com/wp-content/themes/pub/calm-business/style.css?minify=false

The following blocks are labelled as "light gray", but their values are white:

```
.entry .entry-content .has-light-gray-background-color,
.entry .entry-content .wp-block-pullquote.is-style-solid-color.has-light-gray-background-color {
  background-color: #fff;
}
```

```
.entry .entry-content .has-light-gray-color,
.entry .entry-content .wp-block-pullquote.is-style-solid-color blockquote.has-light-gray-color,
.entry .entry-content .wp-block-pullquote.is-style-solid-color blockquote.has-light-gray-color p {
  color: #fff;
}
```

## Result

When post/page content is set to use `.has-light-gray-background-color` or `.has-light-gray-color`, the background or text color is white instead of gray.

* User report: #13240710-hc

**Comment by danieldudzic** [comment]
Calm Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Mayland: https://wordpress.com/theme/mayland
