### ISSUE TITLE
Illustratr: Excerpts not respected

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#964]
## Steps to replicate

Enable *Illustratr* on a site. Create one, or several, long posts with excerpts. I tried this on limitedepsilon.wordpress.com after testing it on the theme demo site.

## Result

The entire post is displayed on the Posts page, even if feed settings are changed to excerpt-only. 

## Expected

Excerpts are displayed. 

* User report: #13370647-hc
* Follow-up ticket: #2103349-zen

**Comment by samiff** [comment]
I think there may have been some confusion with the `Feed Settings` here which would apply to the RSS feed specifically, not the blog posts page. Tested and the feed setting for excerpts seems to be working as expected on Varia & child themes.

Closing this one out, though there is #1805 open which is sort of related.
