### ISSUE TITLE
Cyanotype: Site Title becomes White when Header Image is added

### ISSUE THREAD

**Issue by zdenys** [Automattic/themes#969]
## Steps to replicate

1. Apply theme `Cyanotype`
2. Choose one of the Palette with dark text color in `WordPress.com > My Sites > Design > Customize > Colors and Backgrounds > Palettes`.
![](https://cld.wthms.co/Ip1Sa9+)
3. Set a Header Image in `WordPress.com > My Sites > Design > Customize > Header Image`

## Result

Site Title text becomes White (hence becomes unreadable with Blue/White Palette)

![](https://cld.wthms.co/WsJC68+)
_Link: https://cld.wthms.co/WsJC68_

## Expected

No change of color for Site Title

* User report: 2103728-zen

**Comment by danieldudzic** [comment]
Hi @zdenys,

This has been now fixed in update r54694.
