### ISSUE TITLE
Blask: Project Type Menu Items Displaying as Category or Tag with the Same Name

### ISSUE THREAD

**Issue by lizswafford** [Automattic/themes#97]
## Steps to replicate

Create a new Project Type and a Category with the same name, such as "example". Assign a Project to the Project Type "example", and a blog post to the Category "example". 

Add a new Menu Item to display a Project Type, in Customize > Menus > Primary area of the site. The newly added Project Type menu item will display Categories instead, and also change types in the Menu Add area of the Customizer. 

Deleting the Category "sample" from General > Settings > Writing > Categories will also remove the errant menu item in the Customizer.

Animated GIF showing the process of adding a Project Type in the Menu and having it change to a Category: http://cld.wthms.co/NF63QG

**Also applies to Tags and Project Types.** 

## Result

When clicking on the new menu item to view a Portfolio page on the live, public version of the site, the user will see a Category page with blog posts instead of the Portfolio page of the selected Project Type. 

## Expected

Project Type menu items should display regardless of the name being the same as one of the site's Categories or Tags. The taxonomies should be treated as different items. And portfolio pages and category pages should be different. 

* User report: #2693085-hc
* Follow-up ticket:  #1082138-zen
* User's site: [https://avidfashion.co.uk/](https://avidfashion.co.uk/)

**Comment by laurelfulford** [comment]
Thanks for this report, @lizswafford!

This sounds like this issue, which isn't theme-specific: 138-gh-customization

I'm going to close this ticket and move it over there.
