### ISSUE TITLE
Modern Business: Adjust size and weight for post title in posts list block.  

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#971]
Currently there is big differences in size and weight. We need to adjust it for both small and large screens.

Posts list block:
<img width="726" alt="Screen Shot 2019-06-17 at 11 34 15" src="https://user-images.githubusercontent.com/908665/59598562-63112a00-90f4-11e9-96ac-d8766c2aff52.png">

Archive:
<img width="742" alt="Screen Shot 2019-06-17 at 11 34 31" src="https://user-images.githubusercontent.com/908665/59598581-6c01fb80-90f4-11e9-8022-2eebd10d085e.png">

**Comment by danieldudzic** [comment]
Do you think the size and weight of the post titles should be uniform?

It seems to me that the context here is quite different.

Posts list block:

![Title](https://user-images.githubusercontent.com/905781/59804626-2cebca00-92ef-11e9-8c78-ce94333867ac.jpg)

The Posts list block has (or might have) a Page Title above the block, and also the width of the block is limited by the wrapper.

Archive:

![Archive_Title](https://user-images.githubusercontent.com/905781/59804632-337a4180-92ef-11e9-90c8-bed757425c04.jpg)

Archive, on the other hand, has no Page Title above and is also displayed at a greater width.

**Comment by iamtakashi** [comment]
Good point about the width. Let's only change the font-weight to 300.
