### ISSUE TITLE
All Variations: Updated screenshots in Theme Showcase

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#972]
All the variations updated its screenshot, but the theme showcase still displays old ones. It's likely something to do with cache. Investigate it, and display the new ones for everyone.

**Comment by danieldudzic** [comment]
Had to nuke the cached Photon files: https://mc.a8c.com/nuke-photon-cache/

The new screenshots are displaying fine now:

![Screenshots](https://user-images.githubusercontent.com/905781/59690098-19523d80-91e1-11e9-906d-7ca86c0b1e70.jpg)

**Comment by iamtakashi** [comment]
@danieldudzic I only see the new one for Professional. Others are still old ones for me. It's good to check logged-out https://wordpress.com/themes with an incognito.

<img width="1313" alt="Screen Shot 2019-06-19 at 13 13 32" src="https://user-images.githubusercontent.com/908665/59764688-33008d00-9294-11e9-8b70-ad4f8d3e2c09.png">

**Comment by allancole** [comment]
I just took a look at this and the screenshots in my sandbox definitely have the logos there. 

![image](https://user-images.githubusercontent.com/709581/59788092-fdaa6e00-9298-11e9-82f1-2b04a0d7e9c8.png)

But I don’t see that image from Calypso at the same URL yet: 
![image](https://user-images.githubusercontent.com/709581/59788204-3ba79200-9299-11e9-98b7-c0310a7bfc13.png)

Seems like it could be a photon or cache thing based on location, maybe?

**Comment by iamtakashi** [comment]
I've tried a bunch of different things such as using other browsers, using incognito mode, clearing cache etc., but I still only see new one for Professional :/

**Comment by iamtakashi** [comment]
<img width="1357" alt="Screen Shot 2019-06-19 at 19 00 02" src="https://user-images.githubusercontent.com/908665/59788820-7a067680-92c4-11e9-8a08-b8c0842634ac.png">

**Comment by danieldudzic** [comment]
Ok, I have now nuked the images with the `&zoom=2`.

Please try again (with cleared cache).

**Comment by iamtakashi** [comment]
Yes! Now I can see all of them with logos. Thanks @danieldudzic!
