### ISSUE TITLE
Modern Business: Update demo site with the page templates and menu

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#976]
Let's update the demo site with the following page templates and menu items for each page.

- Blog
- About
- Team
- Services
- Contact

All page templates are in this site: https://pagetemplatesandbox.wordpress.com/

View each page and copy the content in the code view and paste it to the demo site. You'll also need to make the menu for each template in the header takes to the right page.

**Comment by jeffikus** [comment]
Updated demo site content and menu items at https://modernbusinessdemo.wordpress.com/

https://modernbusinessdemo.wordpress.com/blog/
https://modernbusinessdemo.wordpress.com/about/
https://modernbusinessdemo.wordpress.com/team/
https://modernbusinessdemo.wordpress.com/services/
https://modernbusinessdemo.wordpress.com/contact/
