### ISSUE TITLE
Goran: Pullquote Block Displays Incorrectly

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#979]
## Steps to replicate

Add a Pullquote block to a post or page

## Result

Pullquote block was displayed as a regular `<blockquote>`:

![Pullquote Block Published](https://cld.wthms.co/BTaheV+)

## Expected

The Pullquote block would be displayed as it is in the editor:

![Pullquote Block in the Editor](https://cld.wthms.co/bzfJZc+)

Provided the customer the following CSS to resolve the issue:

```
.wp-block-pullquote {
    border-top: 4px solid #555d66;
    border-bottom: 4px solid #555d66;
}

.wp-block-pullquote blockquote {
    border-left: none;
    padding-left: 0;
    margin: 1em;
}

.wp-block-pullquote__citation, 
.wp-block-pullquote cite, 
.wp-block-pullquote footer {
    text-transform: uppercase;
    font-size: 13px;
    font-style: normal;
}
```

Same issue occurs for Edin, which I reported here: https://github.com/Automattic/themes/issues/965

**Comment by jeffikus** [comment]
Goran has been retired.
