### ISSUE TITLE
Calm Business: Change the way and the scope to remove the top margin of the first child element 

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#981]
As the same as all other variations, the theme removes the first block inside the `entry-content` when the homepage title is hidden with the following.

```
.home.page.hide-homepage-title .hentry:not(.has-post-thumbnail) .entry-content >.alignfull:first-child {
    margin-top: 0;
}
```
I think this is too specific, and we can widen the scope.

* This shouldn't be just for `alignfull`. We want to remove the top margin for all other alignments.
* If we add the equivalent margin 32px (or 1rem=22px, if we want it to be consistent with the top margin that uses `rem` unit) to the `entry-header` as a _bottom_ margin, we could simply do like...

```
.hentry:not(.has-post-thumbnail) .entry-content > :first-child {
    margin-top: 0;
}
```
**Motivation**

When we look at the preview in signup we see the rule isn't applied, because of the lack of the css class `hide-homepage-title`.

<img width="975" alt="Screen Shot 2019-06-18 at 02 05 28" src="https://user-images.githubusercontent.com/908665/59646169-9512a280-916d-11e9-9131-c69f36c75028.png">

**Comment by allancole** [comment]
Yeah, I agree this needs to happen. I’d argue the same should happen for the last block and it’s bottom margin.
