### ISSUE TITLE
Calm Business: onboarding preview shows low contrast text in quote block

### ISSUE THREAD

**Issue by ranh** [Automattic/themes#990]
When choosing a "Blog" site type and "Calm" site style during onboarding, the preview shows the following:

<img width="1270" alt="ranimac3 screenshot 2019-06-19 at 13 09 28" src="https://user-images.githubusercontent.com/426518/59759597-23d00e00-9299-11e9-929f-22d49d891fdd.png">

The quote block below the cover image includes a citation ("Oscar Wilde"), but it is set in white text so is nearly invisible. 

This only happens in the preview. When viewing the live site after onboarding is complete, the text is correctly set in `#6c7781` (dark-gray-300).

![calm20190619134823 food blog_](https://user-images.githubusercontent.com/426518/59759894-bcff2480-9299-11e9-941d-adc9467ff195.png)

To reproduce, start a new WordPress.com site and choose the "Blog" site type and "Calm" site style. Note that in the preview, the quote citation will be visible in all other styles, but not in the "Calm" style.

**Comment by iamtakashi** [comment]
@danieldudzic Could you look into this? If you can confirm this issue is isolated in the signup preview, can you report this to wp-calypso repo with "signup" tag, and close this issue?

**Comment by jeffikus** [comment]
@ranh I am not able to replicate that screen, can you describe in detail how you arrived at that screen as well as the URL it is on? Thanks!

**Comment by iamtakashi** [comment]
It looks like the preview of Blog segment is now hidden until we’re able to address the block rendering issues. https://github.com/Automattic/zelda-private/issues/83. Closing for now.
