### ISSUE TITLE
Baskerville 2: Copied Posts do not honor Sharing Buttons Setting

### ISSUE THREAD

**Issue by jacoswan** [Automattic/themes#994]
When copying an existing post, the Sharing buttons do not appear when published, even when the Sharing button option is checked in the settings:

![Sharing Options active](https://cld.wthms.co/q4Dwt0+)

## Steps to replicate

Issue alerted to in Baskerville, but is the same in Baskerville 2. 

1. Activate Baskerville 2. 
2. Create a new post. 
3. Publish with Post Likes and Sharing enabled in the Jetpack settings. 
4. Copy post, and publish copy. 
5. View Post » notice like button is present, sharing buttons are not.
6. Edit copied post, toggle sharing option off/on, re-save.
7. View post » notice share and likes are active. 

## Result

Sharing buttons do not appear on the published post.

## Expected

Sharing buttons should appear on the published copied post, if they were set to appear in the original post and nothing else was done.

* User report: #13535178-hc
* Follow-up ticket: #2122478-zd

Similar/related to this issue https://github.com/Automattic/themes/issues/195

**Comment by lancewillett** [comment]
Closing this as it is low priority, and unlikely to be fixed.
