### ISSUE TITLE
Singl: extra background space on mobile

### ISSUE THREAD

**Issue by gemmagarner** [Automattic/themes#995]
## Steps to replicate

1. Go to [singldemo.wordpress.com](https://singldemo.wordpress.com/)
2. Swipe left anywhere down the page

## Result

The background image overflows and create an area of empty space on the right.

![single-spacing-1](https://user-images.githubusercontent.com/11627765/59842440-7a4b5400-934e-11e9-92c5-72a4f9841b36.jpg)

* I wasn't able to replicate this issue using Device Mode in Chrome's developer tools (only a mobile device).
* Occurs on WordPress.com and WordPress.org sites.

## Expected

The background image to be contained and no extra space.

## Browsers
* Affects multiple browsers on iPhone and Android device. 
* Screenshot above is from Firefox on Android.

* User report: https://wordpress.org/support/topic/singl-theme-too-wide-on-mobile-browsers/

**Comment by danieldudzic** [comment]
Hi @gemmagarner,

Thank you for reporting.

This has now been fixed in r54698.
